Carma-platform: pose_to_tf::PoseToTfNode Class Reference
pose_to_tf::PoseToTfNode Class Reference
The class is responsible for processing pose to tf conversion.
#include <PoseToTF2Node.hpp>
Public Member Functions
PoseToTfNode (const rclcpp::NodeOptions &)
PoseToTfNode constructor.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &)
Private Attributes
carma_ros2_utils::SubPtr< geometry_msgs::msg::Pose > pose_sub
carma_ros2_utils::SubPtr< geometry_msgs::msg::PoseStamped > pose_stamped_sub
carma_ros2_utils::SubPtr< geometry_msgs::msg::PoseWithCovariance > pose_with_cov_sub
carma_ros2_utils::SubPtr< geometry_msgs::msg::PoseWithCovarianceStamped > pose_with_cov_stamped_sub
std::shared_ptr< PoseToTF2 > pose_to_tf_worker_
PoseToTF2Config config_
Detailed Description
The class is responsible for processing pose to tf conversion.
Definition at line 32 of file PoseToTF2Node.hpp.
Constructor & Destructor Documentation
PoseToTfNode()
pose_to_tf::PoseToTfNode::PoseToTfNode (const rclcpp::NodeOptions & options) explicit
PoseToTfNode constructor.
Definition at line 24 of file PoseToTF2Node.cpp.
      : carma_ros2_utils::CarmaLifecycleNode(options)
  {
    // Create initial config
    config_ = PoseToTF2Config();
    // Declare parameters
    config_.child_frame = declare_parameter<std::string>("message_type", config_.child_frame);
    config_.default_parent_frame = declare_parameter<std::string>("target_frame", config_.default_parent_frame);
  }
References pose_to_tf::PoseToTF2Config::child_frame, config_, and pose_to_tf::PoseToTF2Config::default_parent_frame.
Member Function Documentation
handle_on_configure()
carma_ros2_utils::CallbackReturn pose_to_tf::PoseToTfNode::handle_on_configure (const rclcpp_lifecycle::State &)
Definition at line 35 of file PoseToTF2Node.cpp.
  {
    tf2_ros::TransformBroadcaster tf_broadcaster(shared_from_this());
    pose_to_tf::PoseToTF2 worker(config_, [&tf_broadcaster](auto msg){tf_broadcaster.sendTransform(msg);}, shared_from_this());
    pose_to_tf_worker_= std::make_shared<PoseToTF2>(worker);
    // Setup subscribers
    pose_sub = create_subscription<geometry_msgs::msg::Pose>("pose_to_tf", 50,
                                                              std::bind(&pose_to_tf::PoseToTF2::poseCallback, pose_to_tf_worker_.get(), std_ph::_1));
    pose_stamped_sub = create_subscription<geometry_msgs::msg::PoseStamped>("pose_stamped_to_tf", 50,
                                                              std::bind(&pose_to_tf::PoseToTF2::poseStampedCallback, pose_to_tf_worker_.get(), std_ph::_1));
    pose_with_cov_sub = create_subscription<geometry_msgs::msg::PoseWithCovariance>("pose_with_cov_to_tf", 50,
                                                              std::bind(&pose_to_tf::PoseToTF2::poseWithCovarianceCallback, pose_to_tf_worker_.get(), std_ph::_1));
    pose_with_cov_stamped_sub = create_subscription<geometry_msgs::msg::PoseWithCovarianceStamped>("pose_with_cov_stamped_to_tf", 50,
                                                              std::bind(&pose_to_tf::PoseToTF2::poseWithCovarianceStampedCallback, pose_to_tf_worker_.get(), std_ph::_1));
    // Return success if everthing initialized successfully
    return CallbackReturn::SUCCESS;
  }
References config_, pose_stamped_sub, pose_sub, pose_to_tf_worker_, pose_with_cov_stamped_sub, pose_with_cov_sub, pose_to_tf::PoseToTF2::poseCallback(), pose_to_tf::PoseToTF2::poseStampedCallback(), pose_to_tf::PoseToTF2::poseWithCovarianceCallback(), and pose_to_tf::PoseToTF2::poseWithCovarianceStampedCallback().
Member Data Documentation
config_
PoseToTF2Config pose_to_tf::PoseToTfNode::config_ private
Definition at line 46 of file PoseToTF2Node.hpp.
Referenced by PoseToTfNode(), and handle_on_configure().
pose_stamped_sub
carma_ros2_utils::SubPtr<geometry_msgs::msg::PoseStamped> pose_to_tf::PoseToTfNode::pose_stamped_sub private
Definition at line 38 of file PoseToTF2Node.hpp.
Referenced by handle_on_configure().
pose_sub
carma_ros2_utils::SubPtr<geometry_msgs::msg::Pose> pose_to_tf::PoseToTfNode::pose_sub private
Definition at line 37 of file PoseToTF2Node.hpp.
Referenced by handle_on_configure().
pose_to_tf_worker_
std::shared_ptr<PoseToTF2> pose_to_tf::PoseToTfNode::pose_to_tf_worker_ private
Definition at line 43 of file PoseToTF2Node.hpp.
Referenced by handle_on_configure().
pose_with_cov_stamped_sub
carma_ros2_utils::SubPtr<geometry_msgs::msg::PoseWithCovarianceStamped> pose_to_tf::PoseToTfNode::pose_with_cov_stamped_sub private
Definition at line 40 of file PoseToTF2Node.hpp.
Referenced by handle_on_configure().
pose_with_cov_sub
carma_ros2_utils::SubPtr<geometry_msgs::msg::PoseWithCovariance> pose_to_tf::PoseToTfNode::pose_with_cov_sub private
Definition at line 39 of file PoseToTF2Node.hpp.
Referenced by handle_on_configure().
The documentation for this class was generated from the following files:
pose_to_tf/include/pose_to_tf/PoseToTF2Node.hpp
pose_to_tf/src/PoseToTF2Node.cpp