Carma-platform: platoon_control::PurePursuit Class Reference
platoon_control::PurePursuit Class Reference
This class includes logic for Pure Pursuit controller. This controller is used to calculate a steering angle using the current pose of the vehcile and a lookahead point.
#include <pure_pursuit.h>
Public Member Functions
PurePursuit ()
Default constructor for pure pursuit.
void calculateSteer (const cav_msgs::TrajectoryPlanPoint &tp)
calculates steering angle based on lookahead trajectory point
double calculateKappa (const cav_msgs::TrajectoryPlanPoint &tp)
calculates curvature to the lookahead trajectory point
double getAlphaSin (cav_msgs::TrajectoryPlanPoint tp, geometry_msgs::Pose current_pose)
calculates sin of the heading angle to the target point
double lowPassfilter (double gain, double prev_value, double value)
Lowpass filter to smoothen control signal.
double getSteeringAngle ()
returns steering angle
double getAngularVelocity ()
returns angular velocity
Public Attributes
geometry_msgs::Pose current_pose_
double velocity_ = 0.0
double angular_velocity_ = 0
double steering_angle_ = 0
PlatooningControlPluginConfig config_
Private Member Functions
double getLookaheadDist (const cav_msgs::TrajectoryPlanPoint &tp) const
calculate lookahead distance
double getYaw (const cav_msgs::TrajectoryPlanPoint &tp) const
calculate yaw angle of the vehicle
int getSteeringDirection (std::vector< double > v1, std::vector< double > v2) const
calculate steering direction
Private Attributes
double prev_steering = 0.0
double prev_ang_vel = 0.0
cav_msgs::TrajectoryPlanPoint tp0
double _integral = 0.0
Detailed Description
This class includes logic for Pure Pursuit controller. This controller is used to calculate a steering angle using the current pose of the vehcile and a lookahead point.
Definition at line 42 of file pure_pursuit.h.
Constructor & Destructor Documentation
PurePursuit()
platoon_control::PurePursuit::PurePursuit ()
Default constructor for pure pursuit.
Definition at line 27 of file pure_pursuit.cpp.
{}
Member Function Documentation
calculateKappa()
double platoon_control::PurePursuit::calculateKappa (const cav_msgs::TrajectoryPlanPoint & tp)
calculates curvature to the lookahead trajectory point
Parameters
tp lookahead trajectory point
Returns
curvature to the lookahead point
Definition at line 61 of file pure_pursuit.cpp.
    {
        double lookahead = getLookaheadDist(tp);
        ROS_DEBUG_STREAM("used lookahead: " << lookahead);
        double alpha = getAlphaSin(tp, current_pose_);
        ROS_DEBUG_STREAM("calculated alpha: " << alpha);
        double kappa = 2 * (alpha)/(lookahead);
        ROS_DEBUG_STREAM("calculated kappa: " << kappa);
        return kappa;
    }
References current_pose_, getAlphaSin(), and getLookaheadDist().
Referenced by calculateSteer().
calculateSteer()
void platoon_control::PurePursuit::calculateSteer (const cav_msgs::TrajectoryPlanPoint & tp)
calculates steering angle based on lookahead trajectory point
Parameters
tp lookahead trajectory point
Definition at line 72 of file pure_pursuit.cpp.
    {
        double kappa = calculateKappa(tp);
        ROS_DEBUG_STREAM("kappa pp: " << kappa);
        double lookahead = getLookaheadDist(tp);
        ROS_DEBUG_STREAM("lookahead pp: " << lookahead);
        double error=kappa*lookahead*lookahead/2;
        ROS_DEBUG_STREAM("error term pp: " << error);
        // Integral term
        _integral += error * config_.dt;
        ROS_DEBUG_STREAM("Integral term pp: " << _integral);
        if (_integral > config_.integratorMax_pp){
             _integral = config_.integratorMax_pp;
        }
        else if (_integral < config_.integratorMin_pp){
            _integral = config_.integratorMin_pp;
        }
        double Iout = config_.Ki_pp * _integral;
        ROS_DEBUG_STREAM("Iout pp: " << Iout);
        double steering = atan(config_.wheelBase * kappa)+Iout;
        steering += config_.correctionAngle;
        ROS_DEBUG_STREAM("calculated steering angle: " << steering);
        double filtered_steering = lowPassfilter(config_.lowpassGain, prev_steering, steering);
        ROS_DEBUG_STREAM("filtered steering: " << filtered_steering);
        if (std::isnan(filtered_steering)) filtered_steering = prev_steering;
        prev_steering = filtered_steering;
        steering_angle_ = filtered_steering;
        double ang_vel = velocity_ * kappa;
        ROS_DEBUG_STREAM("calculated angular velocity: " << ang_vel);
        double filtered_ang_vel = lowPassfilter(config_.lowpassGain, prev_ang_vel, ang_vel);
        ROS_DEBUG_STREAM("filtered angular velocity: " << filtered_ang_vel);
        prev_ang_vel = filtered_ang_vel;
        if (std::isnan(filtered_ang_vel)) filtered_ang_vel = prev_ang_vel;
        angular_velocity_ = filtered_ang_vel;
    }
References _integral, angular_velocity_, calculateKappa(), config_, PlatooningControlPluginConfig::correctionAngle, PlatooningControlPluginConfig::dt, getLookaheadDist(), PlatooningControlPluginConfig::integratorMax_pp, PlatooningControlPluginConfig::integratorMin_pp, PlatooningControlPluginConfig::Ki_pp, lowPassfilter(), PlatooningControlPluginConfig::lowpassGain, prev_ang_vel, prev_steering, steering_angle_, velocity_, and PlatooningControlPluginConfig::wheelBase.
Referenced by platoon_control::PlatoonControlWorker::generateSteer().
getAlphaSin()
double platoon_control::PurePursuit::getAlphaSin (cav_msgs::TrajectoryPlanPoint tp, geometry_msgs::Pose current_pose)
calculates sin of the heading angle to the target point
Parameters
tp lookahead trajectory point
current_pose current pose of the vehicle
Returns
sin of the heading angle
Definition at line 117 of file pure_pursuit.cpp.
    {
        tf::Transform inverse;
        tf::poseMsgToTF(current_pose, inverse);
        tf::Transform transform = inverse.inverse();
        geometry_msgs::Point point_msg;
        point_msg.x = tp.x;
        point_msg.y = tp.y;
        point_msg.z = current_pose.position.z;
        tf::Point p;
        pointMsgToTF(point_msg, p);
        tf::Point tf_p = transform * p;
        geometry_msgs::Point tf_point_msg;
        pointTFToMsg(tf_p, tf_point_msg);
        ROS_DEBUG_STREAM("relative latitude: " << tf_point_msg.y);
        ROS_DEBUG_STREAM("relative longitude: " << tf_point_msg.x);
        ROS_DEBUG_STREAM("relative z: " << tf_point_msg.z);
        double vec_mag = std::sqrt(tf_point_msg.y*tf_point_msg.y + tf_point_msg.x*tf_point_msg.x + tf_point_msg.z*tf_point_msg.z);
        ROS_DEBUG_STREAM("relative vector mag: " << vec_mag);
        double sin_alpha = tf_point_msg.y/vec_mag;
        ROS_DEBUG_STREAM("alpha sin from transform: " << sin_alpha);
        double angle_tp_map = atan2(tp.y, tp.x); // angle of vector to tp point in map frame
        ROS_DEBUG_STREAM("angle_tp_map: " << angle_tp_map);
        tf::Quaternion quat;
        tf::quaternionMsgToTF(current_pose.orientation, quat);
        double roll, pitch, yaw;
        tf::Matrix3x3(quat).getRPY(roll, pitch, yaw);
        ROS_DEBUG_STREAM("yaw: " << yaw);
        double alpha = angle_tp_map - yaw;
        double sin_alpha2 = sin(alpha);
        ROS_DEBUG_STREAM("alpha from orientation: " << alpha);
        ROS_DEBUG_STREAM("alpha sin from orientation: " << sin_alpha2);
        return sin_alpha;
    }
Referenced by calculateKappa().
getAngularVelocity()
double platoon_control::PurePursuit::getAngularVelocity ()
returns angular velocity
Returns
angular velocity in rad/s
Definition at line 56 of file pure_pursuit.cpp.
    {
        return angular_velocity_;
    }
References angular_velocity_.
Referenced by platoon_control::PlatoonControlWorker::generateSteer().
getLookaheadDist()
double platoon_control::PurePursuit::getLookaheadDist (const cav_msgs::TrajectoryPlanPoint & tp) const private
calculate lookahead distance
Parameters
tp trajectory point
Returns
lookahead distance from next trajectory point
Definition at line 29 of file pure_pursuit.cpp.
{
        double x_diff = (tp.x - current_pose_.position.x);
        double y_diff = (tp.y - current_pose_.position.y);
        double dist = std::sqrt(x_diff * x_diff + y_diff * y_diff);
        ROS_DEBUG_STREAM("calculated lookahead: " << dist);
        return dist;
    }
References current_pose_.
Referenced by calculateKappa(), and calculateSteer().
getSteeringAngle()
double platoon_control::PurePursuit::getSteeringAngle ()
returns steering angle
Returns
steering angle in rad
Definition at line 51 of file pure_pursuit.cpp.
    {
        return steering_angle_;
    }
References steering_angle_.
Referenced by platoon_control::PlatoonControlWorker::generateSteer().
getSteeringDirection()
int platoon_control::PurePursuit::getSteeringDirection (std::vector< double > v1, std::vector< double > v2) const private
calculate steering direction
Parameters
tp trajectory point
Returns
steering direction (+1 is left and -1 is right)
Definition at line 43 of file pure_pursuit.cpp.
{
        double corss_prod = v1[0]*v2[1] - v1[1]*v2[0];
        if (corss_prod >= 0.0){
             return -1;
        }
        return 1;
    }
getYaw()
double platoon_control::PurePursuit::getYaw (const cav_msgs::TrajectoryPlanPoint & tp) const private
calculate yaw angle of the vehicle
Parameters
tp trajectory point
Returns
yaw angle of the vehicle in rad
Definition at line 38 of file pure_pursuit.cpp.
{
        double yaw = atan2(tp.y - current_pose_.position.y, tp.x - current_pose_.position.x);
        return yaw;
    }
References current_pose_.
lowPassfilter()
double platoon_control::PurePursuit::lowPassfilter (double gain, double prev_value, double value)
Lowpass filter to smoothen control signal.
Parameters
gain filter gain
prev_value previous value
value current value
Returns
smoothened control signal
Definition at line 155 of file pure_pursuit.cpp.
    {
        value = prev_value + gain*(value - prev_value);
        return value;
    }
References value.
Referenced by calculateSteer().
Member Data Documentation
_integral
double platoon_control::PurePursuit::_integral = 0.0 private
Definition at line 137 of file pure_pursuit.h.
Referenced by calculateSteer().
angular_velocity_
double platoon_control::PurePursuit::angular_velocity_ = 0
Definition at line 98 of file pure_pursuit.h.
Referenced by calculateSteer(), and getAngularVelocity().
config_
PlatooningControlPluginConfig platoon_control::PurePursuit::config_
Definition at line 101 of file pure_pursuit.h.
Referenced by calculateSteer(), and platoon_control::PlatoonControlWorker::updateConfigParams().
current_pose_
geometry_msgs::Pose platoon_control::PurePursuit::current_pose_
Definition at line 96 of file pure_pursuit.h.
Referenced by calculateKappa(), platoon_control::PlatoonControlWorker::generateSteer(), getLookaheadDist(), and getYaw().
prev_ang_vel
double platoon_control::PurePursuit::prev_ang_vel = 0.0 private
Definition at line 130 of file pure_pursuit.h.
Referenced by calculateSteer().
prev_steering
double platoon_control::PurePursuit::prev_steering = 0.0 private
Definition at line 129 of file pure_pursuit.h.
Referenced by calculateSteer().
steering_angle_
double platoon_control::PurePursuit::steering_angle_ = 0
Definition at line 99 of file pure_pursuit.h.
Referenced by calculateSteer(), and getSteeringAngle().
tp0
cav_msgs::TrajectoryPlanPoint platoon_control::PurePursuit::tp0 private
Definition at line 135 of file pure_pursuit.h.
velocity_
double platoon_control::PurePursuit::velocity_ = 0.0
Definition at line 97 of file pure_pursuit.h.
Referenced by calculateSteer(), and platoon_control::PlatoonControlWorker::generateSteer().
The documentation for this class was generated from the following files:
platooning_control/include/pure_pursuit.h
platooning_control/src/pure_pursuit.cpp