Carma-platform: GenericSchemaDocument< ValueT, Allocator > Class Template Reference
GenericSchemaDocument< ValueT, Allocator > Class Template Reference
JSON schema document.
#include <schema.h>
Classes
struct SchemaEntry
struct SchemaRefEntry
Public Types
typedef ValueT ValueType
typedef IGenericRemoteSchemaDocumentProvider< GenericSchemaDocument > IRemoteSchemaDocumentProviderType
typedef Allocator AllocatorType
typedef ValueType::EncodingType EncodingType
typedef EncodingType::Ch Ch
typedef internal::Schema< GenericSchemaDocument > SchemaType
typedef GenericPointer< ValueType, Allocator > PointerType
Public Member Functions
GenericSchemaDocument (const ValueType &document, IRemoteSchemaDocumentProviderType *remoteProvider=0, Allocator *allocator=0)
Constructor.
~GenericSchemaDocument ()
Destructor.
const SchemaType & GetRoot () const
Get the root schema.
Private Member Functions
GenericSchemaDocument (const GenericSchemaDocument &)
Prohibit copying.
GenericSchemaDocument & operator= (const GenericSchemaDocument &)
Prohibit assignment.
void CreateSchemaRecursive (const SchemaType **schema, const PointerType &pointer, const ValueType &v, const ValueType &document)
void CreateSchema (const SchemaType **schema, const PointerType &pointer, const ValueType &v, const ValueType &document)
bool HandleRefSchema (const PointerType &source, const SchemaType **schema, const ValueType &v, const ValueType &document)
const SchemaType * GetSchema (const PointerType &pointer) const
PointerType GetPointer (const SchemaType *schema) const
const SchemaType * GetTypeless () const
Private Attributes
IRemoteSchemaDocumentProviderType * remoteProvider_
Allocator * allocator_
Allocator * ownAllocator_
const SchemaType * root_
Root schema.
SchemaType * typeless_
internal::Stack< Allocator > schemaMap_
internal::Stack< Allocator > schemaRef_
Static Private Attributes
static const size_t kInitialSchemaMapSize = 64
static const size_t kInitialSchemaRefSize = 64
Friends
class internal::Schema< GenericSchemaDocument >
template<typename , typename , typename >
class GenericSchemaValidator
Detailed Description
template<typename ValueT, typename Allocator = CrtAllocator>
class GenericSchemaDocument< ValueT, Allocator >
JSON schema document.
A JSON schema document is a compiled version of a JSON schema. It is basically a tree of internal::Schema.
Note
This is an immutable class (i.e. its instance cannot be modified after construction).
Template Parameters
ValueT Type of JSON value (e.g. Value), which also determine the encoding.
Allocator Allocator type for allocating memory of this document.
Definition at line 1318 of file schema.h.
Member Typedef Documentation
AllocatorType
template<typename ValueT , typename Allocator = CrtAllocator> typedef Allocator GenericSchemaDocument< ValueT, Allocator >::AllocatorType
Definition at line 1322 of file schema.h.
Ch
template<typename ValueT , typename Allocator = CrtAllocator> typedef EncodingType::Ch GenericSchemaDocument< ValueT, Allocator >::Ch
Definition at line 1324 of file schema.h.
EncodingType
template<typename ValueT , typename Allocator = CrtAllocator> typedef ValueType::EncodingType GenericSchemaDocument< ValueT, Allocator >::EncodingType
Definition at line 1323 of file schema.h.
IRemoteSchemaDocumentProviderType
template<typename ValueT , typename Allocator = CrtAllocator> typedef IGenericRemoteSchemaDocumentProvider<GenericSchemaDocument> GenericSchemaDocument< ValueT, Allocator >::IRemoteSchemaDocumentProviderType
Definition at line 1321 of file schema.h.
PointerType
template<typename ValueT , typename Allocator = CrtAllocator> typedef GenericPointer<ValueType, Allocator> GenericSchemaDocument< ValueT, Allocator >::PointerType
Definition at line 1326 of file schema.h.
SchemaType
template<typename ValueT , typename Allocator = CrtAllocator> typedef internal::Schema<GenericSchemaDocument> GenericSchemaDocument< ValueT, Allocator >::SchemaType
Definition at line 1325 of file schema.h.
ValueType
template<typename ValueT , typename Allocator = CrtAllocator> typedef ValueT GenericSchemaDocument< ValueT, Allocator >::ValueType
Definition at line 1320 of file schema.h.
Constructor & Destructor Documentation
GenericSchemaDocument() [1/2]
template<typename ValueT , typename Allocator = CrtAllocator> GenericSchemaDocument< ValueT, Allocator >::GenericSchemaDocument (const ValueType & document, IRemoteSchemaDocumentProviderType * remoteProvider = 0, Allocator * allocator = 0) inline explicit
Constructor.
Compile a JSON document into schema document.
Parameters
document A JSON document as source.
remoteProvider An optional remote schema document provider for resolving remote reference. Can be null.
allocator An optional allocator instance for allocating memory. Can be null.
Definition at line 1339 of file schema.h.
                                                                                                                                               :
        remoteProvider_(remoteProvider),
        allocator_(allocator),
        ownAllocator_(),
        root_(),
        typeless_(),
        schemaMap_(allocator, kInitialSchemaMapSize),
        schemaRef_(allocator, kInitialSchemaRefSize)
    {
        if (!allocator_)
            ownAllocator_ = allocator_ = RAPIDJSON_NEW(Allocator)();
        typeless_ = static_cast<SchemaType*>(allocator_->Malloc(sizeof(SchemaType)));
        new (typeless_) SchemaType(this, PointerType(), ValueType(kObjectType).Move(), ValueType(kObjectType).Move(), 0);
        // Generate root schema, it will call CreateSchema() to create sub-schemas,
        // And call AddRefSchema() if there are $ref.
        CreateSchemaRecursive(&root_, PointerType(), document, document);
        // Resolve $ref
        while (!schemaRef_.Empty()) {
            SchemaRefEntry* refEntry = schemaRef_.template Pop<SchemaRefEntry>(1);
            if (const SchemaType* s = GetSchema(refEntry->target)) {
                if (refEntry->schema)
                    *refEntry->schema = s;
                // Create entry in map if not exist
                if (!GetSchema(refEntry->source)) {
                    new (schemaMap_.template Push<SchemaEntry>()) SchemaEntry(refEntry->source, const_cast<SchemaType*>(s), false, allocator_);
                }
            }
            else if (refEntry->schema)
                *refEntry->schema = typeless_;
            refEntry->~SchemaRefEntry();
        }
        RAPIDJSON_ASSERT(root_ != 0);
        schemaRef_.ShrinkToFit(); // Deallocate all memory for ref
    }
References GenericSchemaDocument< ValueT, Allocator >::allocator_, GenericSchemaDocument< ValueT, Allocator >::CreateSchemaRecursive(), GenericSchemaDocument< ValueT, Allocator >::GetSchema(), kObjectType, GenericSchemaDocument< ValueT, Allocator >::ownAllocator_, RAPIDJSON_ASSERT, RAPIDJSON_NEW, GenericSchemaDocument< ValueT, Allocator >::root_, GenericSchemaDocument< ValueT, Allocator >::SchemaRefEntry::schema, GenericSchemaDocument< ValueT, Allocator >::schemaMap_, GenericSchemaDocument< ValueT, Allocator >::schemaRef_, GenericSchemaDocument< ValueT, Allocator >::SchemaRefEntry::source, GenericSchemaDocument< ValueT, Allocator >::SchemaRefEntry::target, and GenericSchemaDocument< ValueT, Allocator >::typeless_.
~GenericSchemaDocument()
template<typename ValueT , typename Allocator = CrtAllocator> GenericSchemaDocument< ValueT, Allocator >::~GenericSchemaDocument () inline
Destructor.
Definition at line 1400 of file schema.h.
{
        while (!schemaMap_.Empty())
            schemaMap_.template Pop<SchemaEntry>(1)->~SchemaEntry();
        if (typeless_) {
            typeless_->~SchemaType();
            Allocator::Free(typeless_);
        }
        RAPIDJSON_DELETE(ownAllocator_);
    }
References GenericSchemaDocument< ValueT, Allocator >::ownAllocator_, RAPIDJSON_DELETE, GenericSchemaDocument< ValueT, Allocator >::schemaMap_, and GenericSchemaDocument< ValueT, Allocator >::typeless_.
GenericSchemaDocument() [2/2]
template<typename ValueT , typename Allocator = CrtAllocator> GenericSchemaDocument< ValueT, Allocator >::GenericSchemaDocument (const GenericSchemaDocument< ValueT, Allocator > &) private
Prohibit copying.
Member Function Documentation
CreateSchema()
template<typename ValueT , typename Allocator = CrtAllocator> void GenericSchemaDocument< ValueT, Allocator >::CreateSchema (const SchemaType ** schema, const PointerType & pointer, const ValueType & v, const ValueType & document) inline private
Definition at line 1458 of file schema.h.
{
        RAPIDJSON_ASSERT(pointer.IsValid());
        if (v.IsObject()) {
            if (!HandleRefSchema(pointer, schema, v, document)) {
                SchemaType* s = new (allocator_->Malloc(sizeof(SchemaType))) SchemaType(this, pointer, v, document, allocator_);
                new (schemaMap_.template Push<SchemaEntry>()) SchemaEntry(pointer, s, true, allocator_);
                if (schema)
                    *schema = s;
            }
        }
    }
References GenericSchemaDocument< ValueT, Allocator >::allocator_, GenericSchemaDocument< ValueT, Allocator >::HandleRefSchema(), pointer, RAPIDJSON_ASSERT, and GenericSchemaDocument< ValueT, Allocator >::schemaMap_.
Referenced by GenericSchemaDocument< ValueT, Allocator >::CreateSchemaRecursive().
CreateSchemaRecursive()
template<typename ValueT , typename Allocator = CrtAllocator> void GenericSchemaDocument< ValueT, Allocator >::CreateSchemaRecursive (const SchemaType ** schema, const PointerType & pointer, const ValueType & v, const ValueType & document) inline private
Definition at line 1441 of file schema.h.
{
        if (schema)
            *schema = typeless_;
        if (v.GetType() == kObjectType) {
            const SchemaType* s = GetSchema(pointer);
            if (!s)
                CreateSchema(schema, pointer, v, document);
            for (typename ValueType::ConstMemberIterator itr = v.MemberBegin(); itr != v.MemberEnd(); ++itr)
                CreateSchemaRecursive(0, pointer.Append(itr->name, allocator_), itr->value, document);
        }
        else if (v.GetType() == kArrayType)
            for (SizeType i = 0; i < v.Size(); i++)
                CreateSchemaRecursive(0, pointer.Append(i, allocator_), v[i], document);
    }
References GenericSchemaDocument< ValueT, Allocator >::allocator_, GenericSchemaDocument< ValueT, Allocator >::CreateSchema(), GenericSchemaDocument< ValueT, Allocator >::CreateSchemaRecursive(), GenericSchemaDocument< ValueT, Allocator >::GetSchema(), process_bag::i, kArrayType, kObjectType, pointer, SizeType, and GenericSchemaDocument< ValueT, Allocator >::typeless_.
Referenced by GenericSchemaDocument< ValueT, Allocator >::GenericSchemaDocument(), and GenericSchemaDocument< ValueT, Allocator >::CreateSchemaRecursive().
GetPointer()
template<typename ValueT , typename Allocator = CrtAllocator> PointerType GenericSchemaDocument< ValueT, Allocator >::GetPointer (const SchemaType * schema) const inline private
Definition at line 1523 of file schema.h.
{
        for (const SchemaEntry* target = schemaMap_.template Bottom<SchemaEntry>(); target != schemaMap_.template End<SchemaEntry>(); ++target)
            if (schema == target->schema)
                return target->pointer;
        return PointerType();
    }
References GenericSchemaDocument< ValueT, Allocator >::schemaMap_.
GetRoot()
template<typename ValueT , typename Allocator = CrtAllocator> const SchemaType & GenericSchemaDocument< ValueT, Allocator >::GetRoot () const inline
Get the root schema.
Definition at line 1413 of file schema.h.
{ return *root_; }
References GenericSchemaDocument< ValueT, Allocator >::root_.
GetSchema()
template<typename ValueT , typename Allocator = CrtAllocator> const SchemaType * GenericSchemaDocument< ValueT, Allocator >::GetSchema (const PointerType & pointer) const inline private
Definition at line 1516 of file schema.h.
{
        for (const SchemaEntry* target = schemaMap_.template Bottom<SchemaEntry>(); target != schemaMap_.template End<SchemaEntry>(); ++target)
            if (pointer == target->pointer)
                return target->schema;
        return 0;
    }
References pointer, and GenericSchemaDocument< ValueT, Allocator >::schemaMap_.
Referenced by GenericSchemaDocument< ValueT, Allocator >::GenericSchemaDocument(), and GenericSchemaDocument< ValueT, Allocator >::CreateSchemaRecursive().
GetTypeless()
template<typename ValueT , typename Allocator = CrtAllocator> const SchemaType * GenericSchemaDocument< ValueT, Allocator >::GetTypeless () const inline private
Definition at line 1530 of file schema.h.
{ return typeless_; }
References GenericSchemaDocument< ValueT, Allocator >::typeless_.
HandleRefSchema()
template<typename ValueT , typename Allocator = CrtAllocator> bool GenericSchemaDocument< ValueT, Allocator >::HandleRefSchema (const PointerType & source, const SchemaType ** schema, const ValueType & v, const ValueType & document) inline private
Definition at line 1470 of file schema.h.
{
        static const Ch kRefString[] = { '$', 'r', 'e', 'f', '\0' };
        static const ValueType kRefValue(kRefString, 4);
        typename ValueType::ConstMemberIterator itr = v.FindMember(kRefValue);
        if (itr == v.MemberEnd())
            return false;
        if (itr->value.IsString()) {
            SizeType len = itr->value.GetStringLength();
            if (len > 0) {
                const Ch* s = itr->value.GetString();
                SizeType i = 0;
                while (i < len && s[i] != '#') // Find the first #
                    i++;
                if (i > 0) { // Remote reference, resolve immediately
                    if (remoteProvider_) {
                        if (const GenericSchemaDocument* remoteDocument = remoteProvider_->GetRemoteDocument(s, i)) {
                            PointerType pointer(&s[i], len - i, allocator_);
                            if (pointer.IsValid()) {
                                if (const SchemaType* sc = remoteDocument->GetSchema(pointer)) {
                                    if (schema)
                                        *schema = sc;
                                    return true;
                                }
                            }
                        }
                    }
                }
                else if (s[i] == '#') { // Local reference, defer resolution
                    PointerType pointer(&s[i], len - i, allocator_);
                    if (pointer.IsValid()) {
                        if (const ValueType* nv = pointer.Get(document))
                            if (HandleRefSchema(source, schema, *nv, document))
                                return true;
                        new (schemaRef_.template Push<SchemaRefEntry>()) SchemaRefEntry(source, pointer, schema, allocator_);
                        return true;
                    }
                }
            }
        }
        return false;
    }
References GenericSchemaDocument< ValueT, Allocator >::allocator_, IGenericRemoteSchemaDocumentProvider< SchemaDocumentType >::GetRemoteDocument(), GenericSchemaDocument< ValueT, Allocator >::HandleRefSchema(), process_bag::i, pointer, GenericSchemaDocument< ValueT, Allocator >::remoteProvider_, GenericSchemaDocument< ValueT, Allocator >::schemaRef_, SizeType, and source.
Referenced by GenericSchemaDocument< ValueT, Allocator >::CreateSchema(), and GenericSchemaDocument< ValueT, Allocator >::HandleRefSchema().
operator=()
template<typename ValueT , typename Allocator = CrtAllocator> GenericSchemaDocument & GenericSchemaDocument< ValueT, Allocator >::operator= (const GenericSchemaDocument< ValueT, Allocator > &) private
Prohibit assignment.
Friends And Related Function Documentation
GenericSchemaValidator
template<typename ValueT , typename Allocator = CrtAllocator> template<typename , typename , typename > friend class GenericSchemaValidator friend
Definition at line 1329 of file schema.h.
internal::Schema< GenericSchemaDocument >
template<typename ValueT , typename Allocator = CrtAllocator> friend class internal::Schema< GenericSchemaDocument > friend
Definition at line 1326 of file schema.h.
Member Data Documentation
allocator_
template<typename ValueT , typename Allocator = CrtAllocator> Allocator* GenericSchemaDocument< ValueT, Allocator >::allocator_ private
Definition at line 1536 of file schema.h.
Referenced by GenericSchemaDocument< ValueT, Allocator >::GenericSchemaDocument(), GenericSchemaDocument< ValueT, Allocator >::CreateSchema(), GenericSchemaDocument< ValueT, Allocator >::CreateSchemaRecursive(), and GenericSchemaDocument< ValueT, Allocator >::HandleRefSchema().
kInitialSchemaMapSize
template<typename ValueT , typename Allocator = CrtAllocator> const size_t GenericSchemaDocument< ValueT, Allocator >::kInitialSchemaMapSize = 64 static private
Definition at line 1532 of file schema.h.
kInitialSchemaRefSize
template<typename ValueT , typename Allocator = CrtAllocator> const size_t GenericSchemaDocument< ValueT, Allocator >::kInitialSchemaRefSize = 64 static private
Definition at line 1533 of file schema.h.
ownAllocator_
template<typename ValueT , typename Allocator = CrtAllocator> Allocator* GenericSchemaDocument< ValueT, Allocator >::ownAllocator_ private
Definition at line 1537 of file schema.h.
Referenced by GenericSchemaDocument< ValueT, Allocator >::GenericSchemaDocument(), and GenericSchemaDocument< ValueT, Allocator >::~GenericSchemaDocument().
remoteProvider_
template<typename ValueT , typename Allocator = CrtAllocator> IRemoteSchemaDocumentProviderType* GenericSchemaDocument< ValueT, Allocator >::remoteProvider_ private
Definition at line 1535 of file schema.h.
Referenced by GenericSchemaDocument< ValueT, Allocator >::HandleRefSchema().
root_
template<typename ValueT , typename Allocator = CrtAllocator> const SchemaType* GenericSchemaDocument< ValueT, Allocator >::root_ private
Root schema.
Definition at line 1538 of file schema.h.
Referenced by GenericSchemaDocument< ValueT, Allocator >::GenericSchemaDocument(), and GenericSchemaDocument< ValueT, Allocator >::GetRoot().
schemaMap_
template<typename ValueT , typename Allocator = CrtAllocator> internal::Stack<Allocator> GenericSchemaDocument< ValueT, Allocator >::schemaMap_ private
Definition at line 1540 of file schema.h.
Referenced by GenericSchemaDocument< ValueT, Allocator >::GenericSchemaDocument(), GenericSchemaDocument< ValueT, Allocator >::~GenericSchemaDocument(), GenericSchemaDocument< ValueT, Allocator >::CreateSchema(), GenericSchemaDocument< ValueT, Allocator >::GetPointer(), and GenericSchemaDocument< ValueT, Allocator >::GetSchema().
schemaRef_
template<typename ValueT , typename Allocator = CrtAllocator> internal::Stack<Allocator> GenericSchemaDocument< ValueT, Allocator >::schemaRef_ private
Definition at line 1541 of file schema.h.
Referenced by GenericSchemaDocument< ValueT, Allocator >::GenericSchemaDocument(), and GenericSchemaDocument< ValueT, Allocator >::HandleRefSchema().
typeless_
template<typename ValueT , typename Allocator = CrtAllocator> SchemaType* GenericSchemaDocument< ValueT, Allocator >::typeless_ private
Definition at line 1539 of file schema.h.
Referenced by GenericSchemaDocument< ValueT, Allocator >::GenericSchemaDocument(), GenericSchemaDocument< ValueT, Allocator >::~GenericSchemaDocument(), GenericSchemaDocument< ValueT, Allocator >::CreateSchemaRecursive(), and GenericSchemaDocument< ValueT, Allocator >::GetTypeless().
The documentation for this class was generated from the following files:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/fwd.h
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/schema.h