Carma-platform: mock_drivers::MockLightBarDriver Class Reference
mock_drivers::MockLightBarDriver Class Reference
#include <MockLightBarDriver.hpp>
Public Member Functions
MockLightBarDriver (ros::CARMANodeHandle node)
void publishData ()
void publishDriverStatus ()
string getNodeName ()
vector< string > getDriverTypesList ()
Private Member Functions
bool getDriverStatus_cb (cav_srvs::GetDriverStatusRequest &req, cav_srvs::GetDriverStatusResponse &resp)
bool bind_cb (cav_srvs::BindRequest &req, cav_srvs::BindResponse &resp)
bool getApiService_cb (cav_srvs::GetDriverApiRequest &req, cav_srvs::GetDriverApiResponse &resp)
bool setLightService_cb (cav_srvs::SetLightsRequest &req, cav_srvs::SetLightsResponse &resp)
bool getLightService_cb (cav_srvs::GetLightsRequest &req, cav_srvs::GetLightsResponse &resp)
cav_msgs::LightBarStatus getLightBarStatus ()
cav_msgs::DriverStatus getDriverStatus ()
vector< string > getDriverApi ()
Private Attributes
cav_msgs::DriverStatus driverStatus
ros::Publisher lbPub
string lbStatusTopic
ros::Publisher discoveryPub
ros::ServiceServer getLightsService
ros::ServiceServer setLightsService
ros::ServiceServer getApiService
ros::ServiceServer bindService
ros::ServiceServer getDriverStatusService
string lbGetLightService
string lbSetLightService
short EXPECTED_DATA_COL_COUNT
short SAMPLE_ID_IDX
bool greenFlash
bool yellowFlash
bool leftArrow
bool rightArrow
bool sidesSolid
bool greenSolid
bool yellowDim
bool takedown
Detailed Description
Definition at line 45 of file MockLightBarDriver.hpp.
Constructor & Destructor Documentation
MockLightBarDriver()
mock_drivers::MockLightBarDriver::MockLightBarDriver (ros::CARMANodeHandle node)
Definition at line 35 of file MockLightBarDriver.cpp.
{
                //lightbar topics and services
                lbStatusTopic = "lightbar/light_bar_status";
                lbGetLightService = "lightbar/get_lights";
                lbSetLightService = "lightbar/set_lights";
                //lightbar states
                greenFlash = false;
                yellowFlash = false;
                leftArrow = false;
                rightArrow = false;
                sidesSolid = false;
                greenSolid = false;
                yellowDim = false;
                takedown = false;
                //topics published
                lbPub = node.advertise<cav_msgs::LightBarStatus>(lbStatusTopic, 100);
                discoveryPub = node.advertise<cav_msgs::DriverStatus>("driver_discovery",100);
                //service server
                getApiService = node.advertiseService("mock_lightbar/get_driver_api",&MockLightBarDriver::getApiService_cb, this);
                bindService = node.advertiseService("mock_lightbar/bind",&MockLightBarDriver::bind_cb, this);
                getDriverStatusService = node.advertiseService("mock_lightbar/get_status",&MockLightBarDriver::getDriverStatus_cb,this);
                setLightsService = node.advertiseService(lbSetLightService, &MockLightBarDriver::setLightService_cb, this);
                getLightsService = node.advertiseService(lbGetLightService, &MockLightBarDriver::getLightService_cb, this);
                //publish driver status
                driverStatus.status = cav_msgs::DriverStatus::OPERATIONAL;
                publishDriverStatus();
            }
References bind_cb(), bindService, discoveryPub, driverStatus, getApiService, getApiService_cb(), getDriverStatus_cb(), getDriverStatusService, getLightService_cb(), getLightsService, greenFlash, greenSolid, lbGetLightService, lbPub, lbSetLightService, lbStatusTopic, leftArrow, publishDriverStatus(), rightArrow, setLightService_cb(), setLightsService, sidesSolid, takedown, yellowDim, and yellowFlash.
Member Function Documentation
bind_cb()
bool mock_drivers::MockLightBarDriver::bind_cb (cav_srvs::BindRequest & req, cav_srvs::BindResponse & resp) private
Definition at line 70 of file MockLightBarDriver.cpp.
{
                ROS_INFO_STREAM("bind received");
                return true;
            }
Referenced by MockLightBarDriver().
getApiService_cb()
bool mock_drivers::MockLightBarDriver::getApiService_cb (cav_srvs::GetDriverApiRequest & req, cav_srvs::GetDriverApiResponse & resp) private
Definition at line 76 of file MockLightBarDriver.cpp.
{
                resp.api_list = getDriverApi();
                return true;
            }
References getDriverApi().
Referenced by MockLightBarDriver().
getDriverApi()
vector< string > mock_drivers::MockLightBarDriver::getDriverApi () private
Definition at line 137 of file MockLightBarDriver.cpp.
{
                vector<string> api;
                api.push_back(lbStatusTopic);
                api.push_back(lbGetLightService);
                api.push_back(lbSetLightService);
                return api;
            }
References lbGetLightService, lbSetLightService, and lbStatusTopic.
Referenced by getApiService_cb().
getDriverStatus()
cav_msgs::DriverStatus mock_drivers::MockLightBarDriver::getDriverStatus () private
Definition at line 119 of file MockLightBarDriver.cpp.
{
                cav_msgs::DriverStatus status;
                status.name = getNodeName();
                status.status = driverStatus.status;
                status.can = false;
                status.radar = false;
                status.gnss = false;
                status.imu = false;
                status.lidar = false;
                status.roadway_sensor = false;
                status.comms = false;
                status.controller = false;
                status.camera = false;
                status.lightbar = true;
                return status;
            }
References driverStatus, and getNodeName().
Referenced by getDriverStatus_cb(), and publishDriverStatus().
getDriverStatus_cb()
bool mock_drivers::MockLightBarDriver::getDriverStatus_cb (cav_srvs::GetDriverStatusRequest & req, cav_srvs::GetDriverStatusResponse & resp) private
Definition at line 64 of file MockLightBarDriver.cpp.
{
                resp.status = getDriverStatus();
                return true;
            }
References getDriverStatus().
Referenced by MockLightBarDriver().
getDriverTypesList()
vector< string > mock_drivers::MockLightBarDriver::getDriverTypesList ()
Definition at line 159 of file MockLightBarDriver.cpp.
{
                vector<string> list;
                list.push_back("lightbar");
                return list;
            }
getLightBarStatus()
cav_msgs::LightBarStatus mock_drivers::MockLightBarDriver::getLightBarStatus () private
Helper function to build the lightbar status message
Returns
The lightbar status message
Definition at line 105 of file MockLightBarDriver.cpp.
{
                cav_msgs::LightBarStatus status;
                status.green_solid = greenSolid? 1:0;
                status.yellow_solid = yellowDim? 1:0;
                status.right_arrow = rightArrow? 1:0;
                status.left_arrow = leftArrow? 1:0;
                status.sides_solid = sidesSolid? 1:0;
                status.flash = yellowFlash? 1:0;
                status.green_flash = greenFlash? 1:0;
                status.takedown = takedown? 1:0;
                return status;
            }
References greenFlash, greenSolid, leftArrow, rightArrow, sidesSolid, takedown, yellowDim, and yellowFlash.
Referenced by getLightService_cb(), and publishData().
getLightService_cb()
bool mock_drivers::MockLightBarDriver::getLightService_cb (cav_srvs::GetLightsRequest & req, cav_srvs::GetLightsResponse & resp) private
Definition at line 96 of file MockLightBarDriver.cpp.
{
                resp.status = getLightBarStatus();
                return true;
            }
References getLightBarStatus().
Referenced by MockLightBarDriver().
getNodeName()
string mock_drivers::MockLightBarDriver::getNodeName ()
Definition at line 155 of file MockLightBarDriver.cpp.
{
                return "MockLightBarDriver";
            }
Referenced by getDriverStatus().
publishData()
void mock_drivers::MockLightBarDriver::publishData ()
Definition at line 146 of file MockLightBarDriver.cpp.
{
                cav_msgs::LightBarStatus status = getLightBarStatus();
                lbPub.publish(status);
            }
References getLightBarStatus(), and lbPub.
Referenced by main().
publishDriverStatus()
void mock_drivers::MockLightBarDriver::publishDriverStatus ()
Definition at line 151 of file MockLightBarDriver.cpp.
{
                discoveryPub.publish(getDriverStatus());
            }
References discoveryPub, and getDriverStatus().
Referenced by MockLightBarDriver(), and main().
setLightService_cb()
bool mock_drivers::MockLightBarDriver::setLightService_cb (cav_srvs::SetLightsRequest & req, cav_srvs::SetLightsResponse & resp) private
Definition at line 82 of file MockLightBarDriver.cpp.
{
                cav_msgs::LightBarStatus lightstatus = req.set_state;
                greenFlash = lightstatus.green_flash == 1;
                yellowFlash = lightstatus.flash == 1;
                leftArrow = lightstatus.left_arrow == 1;
                rightArrow = lightstatus.right_arrow== 1;
                sidesSolid = lightstatus.sides_solid == 1;
                greenSolid = lightstatus.green_solid == 1;
                yellowDim = lightstatus.yellow_solid == 1;
                takedown = lightstatus.takedown == 1;
                return true;
            }
References greenFlash, greenSolid, leftArrow, rightArrow, sidesSolid, takedown, yellowDim, and yellowFlash.
Referenced by MockLightBarDriver().
Member Data Documentation
bindService
ros::ServiceServer mock_drivers::MockLightBarDriver::bindService private
Definition at line 61 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver().
discoveryPub
ros::Publisher mock_drivers::MockLightBarDriver::discoveryPub private
Definition at line 55 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), and publishDriverStatus().
driverStatus
cav_msgs::DriverStatus mock_drivers::MockLightBarDriver::driverStatus private
Definition at line 51 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), and getDriverStatus().
EXPECTED_DATA_COL_COUNT
short mock_drivers::MockLightBarDriver::EXPECTED_DATA_COL_COUNT private
Definition at line 65 of file MockLightBarDriver.hpp.
getApiService
ros::ServiceServer mock_drivers::MockLightBarDriver::getApiService private
Definition at line 60 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver().
getDriverStatusService
ros::ServiceServer mock_drivers::MockLightBarDriver::getDriverStatusService private
Definition at line 62 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver().
getLightsService
ros::ServiceServer mock_drivers::MockLightBarDriver::getLightsService private
Definition at line 58 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver().
greenFlash
bool mock_drivers::MockLightBarDriver::greenFlash private
Definition at line 69 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), getLightBarStatus(), and setLightService_cb().
greenSolid
bool mock_drivers::MockLightBarDriver::greenSolid private
Definition at line 74 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), getLightBarStatus(), and setLightService_cb().
lbGetLightService
string mock_drivers::MockLightBarDriver::lbGetLightService private
Definition at line 63 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), and getDriverApi().
lbPub
ros::Publisher mock_drivers::MockLightBarDriver::lbPub private
Definition at line 53 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), and publishData().
lbSetLightService
string mock_drivers::MockLightBarDriver::lbSetLightService private
Definition at line 64 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), and getDriverApi().
lbStatusTopic
string mock_drivers::MockLightBarDriver::lbStatusTopic private
Definition at line 54 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), and getDriverApi().
leftArrow
bool mock_drivers::MockLightBarDriver::leftArrow private
Definition at line 71 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), getLightBarStatus(), and setLightService_cb().
rightArrow
bool mock_drivers::MockLightBarDriver::rightArrow private
Definition at line 72 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), getLightBarStatus(), and setLightService_cb().
SAMPLE_ID_IDX
short mock_drivers::MockLightBarDriver::SAMPLE_ID_IDX private
Definition at line 66 of file MockLightBarDriver.hpp.
setLightsService
ros::ServiceServer mock_drivers::MockLightBarDriver::setLightsService private
Definition at line 59 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver().
sidesSolid
bool mock_drivers::MockLightBarDriver::sidesSolid private
Definition at line 73 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), getLightBarStatus(), and setLightService_cb().
takedown
bool mock_drivers::MockLightBarDriver::takedown private
Definition at line 76 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), getLightBarStatus(), and setLightService_cb().
yellowDim
bool mock_drivers::MockLightBarDriver::yellowDim private
Definition at line 75 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), getLightBarStatus(), and setLightService_cb().
yellowFlash
bool mock_drivers::MockLightBarDriver::yellowFlash private
Definition at line 70 of file MockLightBarDriver.hpp.
Referenced by MockLightBarDriver(), getLightBarStatus(), and setLightService_cb().
The documentation for this class was generated from the following files:
mock_drivers/mock_lightbar_driver/include/mock_lightbar_driver/MockLightBarDriver.hpp
mock_drivers/mock_lightbar_driver/src/MockLightBarDriver.cpp