Carma-platform: FileWriteStream Class Reference
FileWriteStream Class Reference
Wrapper of C file stream for input using fread().
#include <filewritestream.h>
Public Types
typedef char Ch
Character type. Only support char.
Public Member Functions
FileWriteStream (std::FILE *fp, char *buffer, size_t bufferSize)
void Put (char c)
void PutN (char c, size_t n)
void Flush ()
char Peek () const
char Take ()
size_t Tell () const
char * PutBegin ()
size_t PutEnd (char *)
Private Member Functions
FileWriteStream (const FileWriteStream &)
FileWriteStream & operator= (const FileWriteStream &)
Private Attributes
std::FILE * fp_
char * buffer_
char * bufferEnd_
char * current_
Detailed Description
Wrapper of C file stream for input using fread().
Note
implements Stream concept
Definition at line 32 of file filewritestream.h.
Member Typedef Documentation
Ch
typedef char FileWriteStream::Ch
Character type. Only support char.
Definition at line 34 of file filewritestream.h.
Constructor & Destructor Documentation
FileWriteStream() [1/2]
FileWriteStream::FileWriteStream (std::FILE * fp, char * buffer, size_t bufferSize) inline
Definition at line 36 of file filewritestream.h.
                                                                  : fp_(fp), buffer_(buffer), bufferEnd_(buffer + bufferSize), current_(buffer_) {
        RAPIDJSON_ASSERT(fp_ != 0);
    }
References fp_, and RAPIDJSON_ASSERT.
FileWriteStream() [2/2]
FileWriteStream::FileWriteStream (const FileWriteStream &) private
Member Function Documentation
Flush()
void FileWriteStream::Flush () inline
Definition at line 63 of file filewritestream.h.
                 {
        if (current_ != buffer_) {
            size_t result = fwrite(buffer_, 1, static_cast<size_t>(current_ - buffer_), fp_);
            if (result < static_cast<size_t>(current_ - buffer_)) {
                // failure deliberately ignored at this time
                // added to avoid warn_unused_result build errors
            }
            current_ = buffer_;
        }
    }
References buffer_, current_, and fp_.
Referenced by Put(), and PutN().
operator=()
FileWriteStream & FileWriteStream::operator= (const FileWriteStream &) private
Peek()
char FileWriteStream::Peek () const inline
Definition at line 75 of file filewritestream.h.
{ RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
Put()
void FileWriteStream::Put (char c) inline
Definition at line 40 of file filewritestream.h.
                     {
        if (current_ >= bufferEnd_)
            Flush();
        *current_++ = c;
    }
References bufferEnd_, process_traj_logs::c, current_, and Flush().
PutBegin()
char * FileWriteStream::PutBegin () inline
Definition at line 78 of file filewritestream.h.
{ RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
PutEnd()
size_t FileWriteStream::PutEnd (char *) inline
Definition at line 79 of file filewritestream.h.
{ RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
PutN()
void FileWriteStream::PutN (char c, size_t n) inline
Definition at line 47 of file filewritestream.h.
{
        size_t avail = static_cast<size_t>(bufferEnd_ - current_);
        while (n > avail) {
            std::memset(current_, c, avail);
            current_ += avail;
            Flush();
            n -= avail;
            avail = static_cast<size_t>(bufferEnd_ - current_);
        }
        if (n > 0) {
            std::memset(current_, c, n);
            current_ += n;
        }
    }
References bufferEnd_, process_traj_logs::c, current_, and Flush().
Referenced by PutN().
Take()
char FileWriteStream::Take () inline
Definition at line 76 of file filewritestream.h.
{ RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
Tell()
size_t FileWriteStream::Tell () const inline
Definition at line 77 of file filewritestream.h.
{ RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
Member Data Documentation
buffer_
char* FileWriteStream::buffer_ private
Definition at line 87 of file filewritestream.h.
Referenced by Flush().
bufferEnd_
char* FileWriteStream::bufferEnd_ private
Definition at line 88 of file filewritestream.h.
Referenced by Put(), and PutN().
current_
char* FileWriteStream::current_ private
Definition at line 89 of file filewritestream.h.
Referenced by Flush(), Put(), and PutN().
fp_
std::FILE* FileWriteStream::fp_ private
Definition at line 86 of file filewritestream.h.
Referenced by FileWriteStream(), and Flush().
The documentation for this class was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/filewritestream.h