Carma-platform: Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags > Class Template Reference
Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags > Class Template Reference
JSON writer.
#include <writer.h>
Classes
struct Level
Information for each nested level.
Public Types
typedef SourceEncoding::Ch Ch
Public Member Functions
Writer (OutputStream &os, StackAllocator *stackAllocator=0, size_t levelDepth=kDefaultLevelDepth)
Constructor.
Writer (StackAllocator *allocator=0, size_t levelDepth=kDefaultLevelDepth)
void Reset (OutputStream &os)
Reset the writer with a new stream.
bool IsComplete () const
Checks whether the output is a complete JSON.
int GetMaxDecimalPlaces () const
void SetMaxDecimalPlaces (int maxDecimalPlaces)
Sets the maximum number of decimal places for double output.
Implementation of Handler
See also
Handler
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned u)
bool Int64 (int64_t i64)
bool Uint64 (uint64_t u64)
bool Double (double d)
Writes the given double value to the stream.
bool RawNumber (const Ch *str, SizeType length, bool copy=false)
bool String (const Ch *str, SizeType length, bool copy=false)
bool StartObject ()
bool Key (const Ch *str, SizeType length, bool copy=false)
bool EndObject (SizeType memberCount=0)
bool StartArray ()
bool EndArray (SizeType elementCount=0)
Static Public Attributes
static const int kDefaultMaxDecimalPlaces = 324
Protected Member Functions
bool WriteInt (int i)
bool WriteUint (unsigned u)
bool WriteInt64 (int64_t i64)
bool WriteUint64 (uint64_t u)
bool WriteDouble (double d)
Convenience extensions
static const size_t kDefaultLevelDepth = 32
OutputStream * os_
internal::Stack< StackAllocator > level_stack_
int maxDecimalPlaces_
bool hasRoot_
bool String (const Ch *const &str)
Simpler but slower overload.
bool Key (const Ch *const &str)
bool RawValue (const Ch *json, size_t length, Type type)
Write a raw JSON value.
void Flush ()
Flush the output stream.
bool WriteNull ()
bool WriteBool (bool b)
bool WriteInt (int i)
bool WriteUint (unsigned u)
bool WriteInt64 (int64_t i64)
bool WriteUint64 (uint64_t u64)
bool WriteDouble (double d)
bool WriteString (const Ch *str, SizeType length)
bool ScanWriteUnescapedString (GenericStringStream< SourceEncoding > &is, size_t length)
bool WriteStartObject ()
bool WriteEndObject ()
bool WriteStartArray ()
bool WriteEndArray ()
bool WriteRawValue (const Ch *json, size_t length)
void Prefix (Type type)
bool EndValue (bool ret)
Writer (const Writer &)
Writer & operator= (const Writer &)
Detailed Description
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags>
class Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >
JSON writer.
Writer implements the concept Handler. It generates JSON text by events to an output os.
User may programmatically calls the functions of a writer to generate JSON text.
On the other side, a writer can also be passed to objects that generates events,
for example Reader::Parse() and Document::Accept().
Template Parameters
OutputStream Type of output stream.
SourceEncoding Encoding of source string.
TargetEncoding Encoding of output stream.
StackAllocator Type of allocator for allocating memory of stack.
Note
implements Handler concept
Definition at line 91 of file writer.h.
Member Typedef Documentation
Ch
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> typedef SourceEncoding::Ch Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Ch
Definition at line 93 of file writer.h.
Constructor & Destructor Documentation
Writer() [1/3]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Writer (OutputStream & os, StackAllocator * stackAllocator = 0, size_t levelDepth = kDefaultLevelDepth) inline explicit
Constructor.
Parameters
os Output stream.
stackAllocator User supplied allocator. If it is null, it will create a private one.
levelDepth Initial capacity of stack.
Definition at line 103 of file writer.h.
                                                                                                         :
        os_(&os), level_stack_(stackAllocator, levelDepth * sizeof(Level)), maxDecimalPlaces_(kDefaultMaxDecimalPlaces), hasRoot_(false) {}
Writer() [2/3]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Writer (StackAllocator * allocator = 0, size_t levelDepth = kDefaultLevelDepth) inline explicit
Definition at line 107 of file writer.h.
                                                                                  :
        os_(0), level_stack_(allocator, levelDepth * sizeof(Level)), maxDecimalPlaces_(kDefaultMaxDecimalPlaces), hasRoot_(false) {}
Writer() [3/3]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Writer (const Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags > &) private
Member Function Documentation
Bool()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Bool (bool b) inline
Definition at line 184 of file writer.h.
{ Prefix(b ? kTrueType : kFalseType); return EndValue(WriteBool(b)); }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), kFalseType, kTrueType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteBool().
Double()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double (double d) inline
Writes the given double value to the stream.
Parameters
d The value to be written.
Returns
Whether it is succeed.
Definition at line 195 of file writer.h.
{ Prefix(kNumberType); return EndValue(WriteDouble(d)); }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), kNumberType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteDouble().
EndArray()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray (SizeType elementCount = 0) inline
Definition at line 247 of file writer.h.
{
        (void)elementCount;
        RAPIDJSON_ASSERT(level_stack_.GetSize() >= sizeof(Level));
        RAPIDJSON_ASSERT(level_stack_.template Top<Level>()->inArray);
        level_stack_.template Pop<Level>(1);
        return EndValue(WriteEndArray());
    }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), internal::Stack< Allocator >::GetSize(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, RAPIDJSON_ASSERT, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteEndArray().
EndObject()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject (SizeType memberCount = 0) inline
Definition at line 232 of file writer.h.
{
        (void)memberCount;
        RAPIDJSON_ASSERT(level_stack_.GetSize() >= sizeof(Level)); // not inside an Object
        RAPIDJSON_ASSERT(!level_stack_.template Top<Level>()->inArray); // currently inside an Array, not Object
        RAPIDJSON_ASSERT(0 == level_stack_.template Top<Level>()->valueCount % 2); // Object has a Key without a Value
        level_stack_.template Pop<Level>(1);
        return EndValue(WriteEndObject());
    }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), internal::Stack< Allocator >::GetSize(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, RAPIDJSON_ASSERT, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteEndObject().
EndValue()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue (bool ret) inline protected
Definition at line 491 of file writer.h.
{
        if (RAPIDJSON_UNLIKELY(level_stack_.Empty()))   // end of json text
            Flush();
        return ret;
    }
References internal::Stack< Allocator >::Empty(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Flush(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, and RAPIDJSON_UNLIKELY.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Bool(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int64(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawNumber(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawValue(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint64().
Flush()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> void Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Flush () inline
Flush the output stream.
Allows the user to flush the output stream immediately.
Definition at line 283 of file writer.h.
                 {
        os_->Flush();
    }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_.
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue().
GetMaxDecimalPlaces()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> int Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::GetMaxDecimalPlaces () const inline
Definition at line 149 of file writer.h.
{
        return maxDecimalPlaces_;
    }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::maxDecimalPlaces_.
Int()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int (int i) inline
Definition at line 185 of file writer.h.
{ Prefix(kNumberType); return EndValue(WriteInt(i)); }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), process_bag::i, kNumberType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt().
Int64()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int64 (int64_t i64) inline
Definition at line 187 of file writer.h.
{ Prefix(kNumberType); return EndValue(WriteInt64(i64)); }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), kNumberType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt64().
IsComplete()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::IsComplete () const inline
Checks whether the output is a complete JSON.
A complete JSON has a complete root object or array.
Definition at line 145 of file writer.h.
{
        return hasRoot_ && level_stack_.Empty();
    }
References internal::Stack< Allocator >::Empty(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::hasRoot_, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_.
Key() [1/2]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key (const Ch *const & str) inline
Definition at line 261 of file writer.h.
{ return Key(str, internal::StrLen(str)); }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key(), and internal::StrLen().
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key().
Key() [2/2]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key (const Ch * str, SizeType length, bool copy = false) inline
Definition at line 223 of file writer.h.
{ return String(str, length, copy); }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
Null()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null () inline
Definition at line 183 of file writer.h.
{ Prefix(kNullType);   return EndValue(WriteNull()); }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), kNullType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteNull().
operator=()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> Writer & Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::operator= (const Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags > &) private
Prefix()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> void Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix (Type type) inline protected
Definition at line 470 of file writer.h.
{
        (void)type;
        if (RAPIDJSON_LIKELY(level_stack_.GetSize() != 0)) { // this value is not at root
            Level* level = level_stack_.template Top<Level>();
            if (level->valueCount > 0) {
                if (level->inArray)
                    os_->Put(','); // add comma if it is not the first element in array
                else  // in object
                    os_->Put((level->valueCount % 2 == 0) ? ',' : ':');
            }
            if (!level->inArray && level->valueCount % 2 == 0)
                RAPIDJSON_ASSERT(type == kStringType);  // if it's in object, then even number should be a name
            level->valueCount++;
        }
        else {
            RAPIDJSON_ASSERT(!hasRoot_);    // Should only has one and only one root.
            hasRoot_ = true;
        }
    }
References internal::Stack< Allocator >::GetSize(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::hasRoot_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level::inArray, kStringType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, RAPIDJSON_ASSERT, RAPIDJSON_LIKELY, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level::valueCount.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Bool(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int64(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawNumber(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawValue(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint64().
RawNumber()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawNumber (const Ch * str, SizeType length, bool copy = false) inline
Definition at line 197 of file writer.h.
{
        RAPIDJSON_ASSERT(str != 0);
        (void)copy;
        Prefix(kNumberType);
        return EndValue(WriteString(str, length));
    }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), kNumberType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), RAPIDJSON_ASSERT, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString().
RawValue()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawValue (const Ch * json, size_t length, Type type) inline
Write a raw JSON value.
For user to write a stringified JSON as a value.
Parameters
json A well-formed JSON value. It should not contain null character within [0, length - 1] range.
length Length of the json.
type Type of the root of json.
Definition at line 273 of file writer.h.
{
        RAPIDJSON_ASSERT(json != 0);
        Prefix(type);
        return EndValue(WriteRawValue(json, length));
    }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), RAPIDJSON_ASSERT, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteRawValue().
Reset()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> void Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Reset (OutputStream & os) inline
Reset the writer with a new stream.
This function reset the writer with a new stream and default settings, in order to make a Writer object reusable for output multiple JSONs.
Parameters
os New output stream.
Writer<OutputStream> writer(os1);
writer.StartObject();
// ...
writer.EndObject();
writer.Reset(os2);
writer.StartObject();
// ...
writer.EndObject();
Definition at line 135 of file writer.h.
{
        os_ = &os;
        hasRoot_ = false;
        level_stack_.Clear();
    }
References internal::Stack< Allocator >::Clear(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::hasRoot_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_.
ScanWriteUnescapedString()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::ScanWriteUnescapedString (GenericStringStream< SourceEncoding > & is, size_t length) inline protected
Definition at line 452 of file writer.h.
{
        return RAPIDJSON_LIKELY(is.Tell() < length);
    }
References RAPIDJSON_LIKELY, and GenericStringStream< Encoding >::Tell().
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString().
SetMaxDecimalPlaces()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> void Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::SetMaxDecimalPlaces (int maxDecimalPlaces) inline
Sets the maximum number of decimal places for double output.
This setting truncates the output with specified number of decimal places.
For example,
writer.SetMaxDecimalPlaces(3);
writer.StartArray();
writer.Double(0.12345);                 // "0.123"
writer.Double(0.0001);                  // "0.0"
writer.Double(1.234567890123456e30);    // "1.234567890123456e30" (do not truncate significand for positive exponent)
writer.Double(1.23e-4);                 // "0.0"                  (do truncate significand for negative exponent)
writer.EndArray();
The default setting does not truncate any decimal places. You can restore to this setting by calling
writer.SetMaxDecimalPlaces(Writer::kDefaultMaxDecimalPlaces);
Definition at line 174 of file writer.h.
{
        maxDecimalPlaces_ = maxDecimalPlaces;
    }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::maxDecimalPlaces_.
StartArray()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray () inline
Definition at line 241 of file writer.h.
                      {
        Prefix(kArrayType);
        new (level_stack_.template Push<Level>()) Level(true);
        return WriteStartArray();
    }
References kArrayType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteStartArray().
StartObject()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject () inline
Definition at line 217 of file writer.h.
                       {
        Prefix(kObjectType);
        new (level_stack_.template Push<Level>()) Level(false);
        return WriteStartObject();
    }
References kObjectType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteStartObject().
String() [1/2]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String (const Ch *const & str) inline
Simpler but slower overload.
Definition at line 260 of file writer.h.
{ return String(str, internal::StrLen(str)); }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), and internal::StrLen().
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
String() [2/2]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String (const Ch * str, SizeType length, bool copy = false) inline
Definition at line 204 of file writer.h.
{
        RAPIDJSON_ASSERT(str != 0);
        (void)copy;
        Prefix(kStringType);
        return EndValue(WriteString(str, length));
    }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), kStringType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), RAPIDJSON_ASSERT, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString().
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key().
Uint()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint (unsigned u) inline
Definition at line 186 of file writer.h.
{ Prefix(kNumberType); return EndValue(WriteUint(u)); }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), kNumberType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint().
Uint64()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint64 (uint64_t u64) inline
Definition at line 188 of file writer.h.
{ Prefix(kNumberType); return EndValue(WriteUint64(u64)); }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), kNumberType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint64().
WriteBool()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteBool (bool b) inline protected
Definition at line 302 of file writer.h.
{
        if (b) {
            PutReserve(*os_, 4);
            PutUnsafe(*os_, 't'); PutUnsafe(*os_, 'r'); PutUnsafe(*os_, 'u'); PutUnsafe(*os_, 'e');
        }
        else {
            PutReserve(*os_, 5);
            PutUnsafe(*os_, 'f'); PutUnsafe(*os_, 'a'); PutUnsafe(*os_, 'l'); PutUnsafe(*os_, 's'); PutUnsafe(*os_, 'e');
        }
        return true;
    }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), and PutUnsafe().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Bool(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Bool().
WriteDouble() [1/2]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteDouble (double d) inline protected
Definition at line 350 of file writer.h.
{
        if (internal::Double(d).IsNanOrInf()) {
            if (!(writeFlags & kWriteNanAndInfFlag))
                return false;
            if (internal::Double(d).IsNan()) {
                PutReserve(*os_, 3);
                PutUnsafe(*os_, 'N'); PutUnsafe(*os_, 'a'); PutUnsafe(*os_, 'N');
                return true;
            }
            if (internal::Double(d).Sign()) {
                PutReserve(*os_, 9);
                PutUnsafe(*os_, '-');
            }
            else
                PutReserve(*os_, 8);
            PutUnsafe(*os_, 'I'); PutUnsafe(*os_, 'n'); PutUnsafe(*os_, 'f');
            PutUnsafe(*os_, 'i'); PutUnsafe(*os_, 'n'); PutUnsafe(*os_, 'i'); PutUnsafe(*os_, 't'); PutUnsafe(*os_, 'y');
            return true;
        }
        char buffer[25];
        char* end = internal::dtoa(d, buffer, maxDecimalPlaces_);
        PutReserve(*os_, static_cast<size_t>(end - buffer));
        for (char* p = buffer; p != end; ++p)
            PutUnsafe(*os_, static_cast<typename OutputStream::Ch>(*p));
        return true;
    }
References internal::dtoa(), kWriteNanAndInfFlag, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::maxDecimalPlaces_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), and PutUnsafe().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double().
WriteDouble() [2/2]
bool Writer< StringBuffer >::WriteDouble (double d) inline protected
Definition at line 543 of file writer.h.
{
    if (internal::Double(d).IsNanOrInf()) {
        // Note: This code path can only be reached if (RAPIDJSON_WRITE_DEFAULT_FLAGS & kWriteNanAndInfFlag).
        if (!(kWriteDefaultFlags & kWriteNanAndInfFlag))
            return false;
        if (internal::Double(d).IsNan()) {
            PutReserve(*os_, 3);
            PutUnsafe(*os_, 'N'); PutUnsafe(*os_, 'a'); PutUnsafe(*os_, 'N');
            return true;
        }
        if (internal::Double(d).Sign()) {
            PutReserve(*os_, 9);
            PutUnsafe(*os_, '-');
        }
        else
            PutReserve(*os_, 8);
        PutUnsafe(*os_, 'I'); PutUnsafe(*os_, 'n'); PutUnsafe(*os_, 'f');
        PutUnsafe(*os_, 'i'); PutUnsafe(*os_, 'n'); PutUnsafe(*os_, 'i'); PutUnsafe(*os_, 't'); PutUnsafe(*os_, 'y');
        return true;
    }
    char *buffer = os_->Push(25);
    char* end = internal::dtoa(d, buffer, maxDecimalPlaces_);
    os_->Pop(static_cast<size_t>(25 - (end - buffer)));
    return true;
}
References internal::dtoa(), kWriteDefaultFlags, kWriteNanAndInfFlag, PutReserve(), and PutUnsafe().
WriteEndArray()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteEndArray () inline protected
Definition at line 459 of file writer.h.
{ os_->Put(']'); return true; }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), and PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray().
WriteEndObject()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteEndObject () inline protected
Definition at line 457 of file writer.h.
{ os_->Put('}'); return true; }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_.
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject().
WriteInt() [1/2]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt (int i) inline protected
Definition at line 314 of file writer.h.
{
        char buffer[11];
        const char* end = internal::i32toa(i, buffer);
        PutReserve(*os_, static_cast<size_t>(end - buffer));
        for (const char* p = buffer; p != end; ++p)
            PutUnsafe(*os_, static_cast<typename OutputStream::Ch>(*p));
        return true;
    }
References process_bag::i, internal::i32toa(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), and PutUnsafe().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int().
WriteInt() [2/2]
bool Writer< StringBuffer >::WriteInt (int i) inline protected
Definition at line 511 of file writer.h.
{
    char *buffer = os_->Push(11);
    const char* end = internal::i32toa(i, buffer);
    os_->Pop(static_cast<size_t>(11 - (end - buffer)));
    return true;
}
References process_bag::i, and internal::i32toa().
WriteInt64() [1/2]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt64 (int64_t i64) inline protected
Definition at line 332 of file writer.h.
{
        char buffer[21];
        const char* end = internal::i64toa(i64, buffer);
        PutReserve(*os_, static_cast<size_t>(end - buffer));
        for (const char* p = buffer; p != end; ++p)
            PutUnsafe(*os_, static_cast<typename OutputStream::Ch>(*p));
        return true;
    }
References internal::i64toa(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), and PutUnsafe().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int64(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int64().
WriteInt64() [2/2]
bool Writer< StringBuffer >::WriteInt64 (int64_t i64) inline protected
Definition at line 527 of file writer.h.
{
    char *buffer = os_->Push(21);
    const char* end = internal::i64toa(i64, buffer);
    os_->Pop(static_cast<size_t>(21 - (end - buffer)));
    return true;
}
References internal::i64toa().
WriteNull()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteNull () inline protected
Definition at line 297 of file writer.h.
                      {
        PutReserve(*os_, 4);
        PutUnsafe(*os_, 'n'); PutUnsafe(*os_, 'u'); PutUnsafe(*os_, 'l'); PutUnsafe(*os_, 'l'); return true;
    }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), and PutUnsafe().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null().
WriteRawValue()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteRawValue (const Ch * json, size_t length) inline protected
Definition at line 461 of file writer.h.
{
        PutReserve(*os_, length);
        for (size_t i = 0; i < length; i++) {
            RAPIDJSON_ASSERT(json[i] != '\0');
            PutUnsafe(*os_, json[i]);
        }
        return true;
    }
References process_bag::i, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), PutUnsafe(), and RAPIDJSON_ASSERT.
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawValue(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawValue().
WriteStartArray()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteStartArray () inline protected
Definition at line 458 of file writer.h.
{ os_->Put('['); return true; }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_.
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray().
WriteStartObject()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteStartObject () inline protected
Definition at line 456 of file writer.h.
{ os_->Put('{'); return true; }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_.
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject().
WriteString()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString (const Ch * str, SizeType length) inline protected
Definition at line 378 of file writer.h.
{
        static const typename OutputStream::Ch hexDigits[16] = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F' };
        static const char escape[256] = {
#define Z16 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
            //0    1    2    3    4    5    6    7    8    9    A    B    C    D    E    F
            'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'b', 't', 'n', 'u', 'f', 'r', 'u', 'u', // 00
            'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', // 10
              0,   0, '"',   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, // 20
            Z16, Z16,                                                                       // 30~4F
              0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,'\\',   0,   0,   0, // 50
            Z16, Z16, Z16, Z16, Z16, Z16, Z16, Z16, Z16, Z16                                // 60~FF
#undef Z16
        };
        if (TargetEncoding::supportUnicode)
            PutReserve(*os_, 2 + length * 6); // "\uxxxx..."
        else
            PutReserve(*os_, 2 + length * 12);  // "\uxxxx\uyyyy..."
        PutUnsafe(*os_, '\"');
        GenericStringStream<SourceEncoding> is(str);
        while (ScanWriteUnescapedString(is, length)) {
            const Ch c = is.Peek();
            if (!TargetEncoding::supportUnicode && static_cast<unsigned>(c) >= 0x80) {
                // Unicode escaping
                unsigned codepoint;
                if (RAPIDJSON_UNLIKELY(!SourceEncoding::Decode(is, &codepoint)))
                    return false;
                PutUnsafe(*os_, '\\');
                PutUnsafe(*os_, 'u');
                if (codepoint <= 0xD7FF || (codepoint >= 0xE000 && codepoint <= 0xFFFF)) {
                    PutUnsafe(*os_, hexDigits[(codepoint >> 12) & 15]);
                    PutUnsafe(*os_, hexDigits[(codepoint >>  8) & 15]);
                    PutUnsafe(*os_, hexDigits[(codepoint >>  4) & 15]);
                    PutUnsafe(*os_, hexDigits[(codepoint      ) & 15]);
                }
                else {
                    RAPIDJSON_ASSERT(codepoint >= 0x010000 && codepoint <= 0x10FFFF);
                    // Surrogate pair
                    unsigned s = codepoint - 0x010000;
                    unsigned lead = (s >> 10) + 0xD800;
                    unsigned trail = (s & 0x3FF) + 0xDC00;
                    PutUnsafe(*os_, hexDigits[(lead >> 12) & 15]);
                    PutUnsafe(*os_, hexDigits[(lead >>  8) & 15]);
                    PutUnsafe(*os_, hexDigits[(lead >>  4) & 15]);
                    PutUnsafe(*os_, hexDigits[(lead      ) & 15]);
                    PutUnsafe(*os_, '\\');
                    PutUnsafe(*os_, 'u');
                    PutUnsafe(*os_, hexDigits[(trail >> 12) & 15]);
                    PutUnsafe(*os_, hexDigits[(trail >>  8) & 15]);
                    PutUnsafe(*os_, hexDigits[(trail >>  4) & 15]);
                    PutUnsafe(*os_, hexDigits[(trail      ) & 15]);
                }
            }
            else if ((sizeof(Ch) == 1 || static_cast<unsigned>(c) < 256) && RAPIDJSON_UNLIKELY(escape[static_cast<unsigned char>(c)]))  {
                is.Take();
                PutUnsafe(*os_, '\\');
                PutUnsafe(*os_, static_cast<typename OutputStream::Ch>(escape[static_cast<unsigned char>(c)]));
                if (escape[static_cast<unsigned char>(c)] == 'u') {
                    PutUnsafe(*os_, '0');
                    PutUnsafe(*os_, '0');
                    PutUnsafe(*os_, hexDigits[static_cast<unsigned char>(c) >> 4]);
                    PutUnsafe(*os_, hexDigits[static_cast<unsigned char>(c) & 0xF]);
                }
            }
            else if (RAPIDJSON_UNLIKELY(!(writeFlags & kWriteValidateEncodingFlag ?
                Transcoder<SourceEncoding, TargetEncoding>::Validate(is, *os_) :
                Transcoder<SourceEncoding, TargetEncoding>::TranscodeUnsafe(is, *os_))))
                return false;
        }
        PutUnsafe(*os_, '\"');
        return true;
    }
References process_traj_logs::c, kWriteValidateEncodingFlag, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, GenericStringStream< Encoding >::Peek(), PutReserve(), PutUnsafe(), RAPIDJSON_ASSERT, RAPIDJSON_UNLIKELY, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::ScanWriteUnescapedString(), GenericStringStream< Encoding >::Take(), and Z16.
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawNumber(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawNumber(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
WriteUint() [1/2]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint (unsigned u) inline protected
Definition at line 323 of file writer.h.
{
        char buffer[10];
        const char* end = internal::u32toa(u, buffer);
        PutReserve(*os_, static_cast<size_t>(end - buffer));
        for (const char* p = buffer; p != end; ++p)
            PutUnsafe(*os_, static_cast<typename OutputStream::Ch>(*p));
        return true;
    }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), PutUnsafe(), and internal::u32toa().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint().
WriteUint() [2/2]
bool Writer< StringBuffer >::WriteUint (unsigned u) inline protected
Definition at line 519 of file writer.h.
{
    char *buffer = os_->Push(10);
    const char* end = internal::u32toa(u, buffer);
    os_->Pop(static_cast<size_t>(10 - (end - buffer)));
    return true;
}
References internal::u32toa().
WriteUint64() [1/2]
bool Writer< StringBuffer >::WriteUint64 (uint64_t u) inline protected
Definition at line 535 of file writer.h.
{
    char *buffer = os_->Push(20);
    const char* end = internal::u64toa(u, buffer);
    os_->Pop(static_cast<size_t>(20 - (end - buffer)));
    return true;
}
References internal::u64toa().
WriteUint64() [2/2]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint64 (uint64_t u64) inline protected
Definition at line 341 of file writer.h.
{
        char buffer[20];
        char* end = internal::u64toa(u64, buffer);
        PutReserve(*os_, static_cast<size_t>(end - buffer));
        for (char* p = buffer; p != end; ++p)
            PutUnsafe(*os_, static_cast<typename OutputStream::Ch>(*p));
        return true;
    }
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), PutUnsafe(), and internal::u64toa().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint64(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint64().
Member Data Documentation
hasRoot_
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::hasRoot_ protected
Definition at line 500 of file writer.h.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::IsComplete(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Reset().
kDefaultLevelDepth
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> const size_t Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::kDefaultLevelDepth = 32 static protected
Definition at line 295 of file writer.h.
kDefaultMaxDecimalPlaces
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> const int Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::kDefaultMaxDecimalPlaces = 324 static
Definition at line 95 of file writer.h.
level_stack_
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> internal::Stack<StackAllocator> Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_ protected
Definition at line 498 of file writer.h.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::IsComplete(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Reset(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), and PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteIndent().
maxDecimalPlaces_
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> int Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::maxDecimalPlaces_ protected
Definition at line 499 of file writer.h.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::GetMaxDecimalPlaces(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::SetMaxDecimalPlaces(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteDouble().
os_
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> OutputStream* Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_ protected
Definition at line 497 of file writer.h.
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Flush(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Reset(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteBool(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteDouble(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteEndArray(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteEndObject(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteIndent(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt64(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteNull(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteRawValue(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteStartArray(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteStartObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint64().
The documentation for this class was generated from the following files:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/fwd.h
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/writer.h