Carma-platform: cav::UDPListener Class Reference
cav::UDPListener Class Reference
UDPListener is a helper class that manages listening on a UDP socket and passing received packets to subscribers.
#include <udp_listener.h>
Public Member Functions
UDPListener (boost::asio::io_service &io, unsigned short port)
Constructs a UDPListener.
virtual ~UDPListener ()
bool start ()
Starts the.
void stop ()
Public Attributes
boost::signals2::signal< void()> onClose
Called when the internal socket is closed and the UDPListener is no longer listening.
boost::signals2::signal< void(const boost::system::error_code &)> onError
Called on socket asio error.
boost::signals2::signal< void(const std::shared_ptr< const std::vector< uint8_t > > &)> onReceive
Called on packet received.
Private Member Functions
void start_recv_udp ()
starts asynchronous listening on udp socket. Uses reactor-style listening so that we can dynamically detect the length of the packet received
void handle_recv_udp (const boost::system::error_code &ec, std::size_t bytes_transferred)
Handles received packets.
Private Attributes
boost::asio::io_service & io_
boost::asio::ip::udp::socket socket_
std::atomic< bool > running_
bool started_
Detailed Description
UDPListener is a helper class that manages listening on a UDP socket and passing received packets to subscribers.
Definition at line 34 of file udp_listener.h.
Constructor & Destructor Documentation
UDPListener()
cav::UDPListener::UDPListener (boost::asio::io_service & io, unsigned short port) inline
Constructs a UDPListener.
Parameters
io - an io_service object to service the asynchronous IO
host - the address to listen on
port - the port to listen on
Definition at line 95 of file udp_listener.h.
                                                              : io_(io), socket_(io_),running_(false), started_(false)
    {
        socket_.open(boost::asio::ip::udp::v6());
        socket_.bind(boost::asio::ip::udp::endpoint(boost::asio::ip::udp::v6(),port));
    }
References socket_.
~UDPListener()
virtual cav::UDPListener::~UDPListener () inline virtual
Definition at line 101 of file udp_listener.h.
    {
        try{
            stop();
        }catch(...)
        {
        }
    }
References stop().
Member Function Documentation
handle_recv_udp()
void cav::UDPListener::handle_recv_udp (const boost::system::error_code & ec, std::size_t bytes_transferred) inline private
Handles received packets.
Parameters
ec
bytes_transferred
Definition at line 56 of file udp_listener.h.
    {
        if(!ec || ec == boost::asio::error::operation_aborted)
        {
            //Fetch size
            size_t size = socket_.available();
            //Create buffer
            std::shared_ptr<std::vector<uint8_t>> buf = std::make_shared<std::vector<uint8_t>>(size);
            //Perform read
            boost::system::error_code errorCode;
            socket_.receive(boost::asio::buffer(*buf),0,errorCode);
            if(!errorCode)
            {
                //Post signal to handle this received packet
                io_.post([this,buf](){onReceive(buf);});
            }
            //Should only continue if we are still running
            if(running_)
                start_recv_udp();
        }
        else
        {
            onError(ec);
        }
    }
References io_, onError, onReceive, running_, socket_, and start_recv_udp().
Referenced by start_recv_udp().
start()
bool cav::UDPListener::start () inline
Starts the.
Returns
Definition at line 131 of file udp_listener.h.
    {
        if(running_.exchange(true)) return false;
        start_recv_udp();
        return true;
    }
References running_, and start_recv_udp().
start_recv_udp()
void cav::UDPListener::start_recv_udp () inline private
starts asynchronous listening on udp socket. Uses reactor-style listening so that we can dynamically detect the length of the packet received
Definition at line 46 of file udp_listener.h.
    {
        socket_.async_receive(boost::asio::null_buffers(),[this](const boost::system::error_code&ec,size_t bytes){handle_recv_udp(ec,bytes);});
    }
References handle_recv_udp(), and socket_.
Referenced by handle_recv_udp(), and start().
stop()
void cav::UDPListener::stop () inline
Definition at line 138 of file udp_listener.h.
    {
        if(!running_.exchange(false)) return;
        onClose();
    }
References onClose, and running_.
Referenced by ~UDPListener().
Member Data Documentation
io_
boost::asio::io_service& cav::UDPListener::io_ private
Definition at line 36 of file udp_listener.h.
Referenced by handle_recv_udp().
onClose
boost::signals2::signal<void ()> cav::UDPListener::onClose
Called when the internal socket is closed and the UDPListener is no longer listening.
Definition at line 114 of file udp_listener.h.
Referenced by stop().
onError
boost::signals2::signal<void (const boost::system::error_code&)> cav::UDPListener::onError
Called on socket asio error.
Definition at line 119 of file udp_listener.h.
Referenced by handle_recv_udp().
onReceive
boost::signals2::signal<void (const std::shared_ptr< const std::vector<uint8_t>>&)> cav::UDPListener::onReceive
Called on packet received.
Definition at line 124 of file udp_listener.h.
Referenced by handle_recv_udp().
running_
std::atomic<bool> cav::UDPListener::running_ private
Definition at line 38 of file udp_listener.h.
Referenced by handle_recv_udp(), start(), and stop().
socket_
boost::asio::ip::udp::socket cav::UDPListener::socket_ private
Definition at line 37 of file udp_listener.h.
Referenced by UDPListener(), handle_recv_udp(), and start_recv_udp().
started_
bool cav::UDPListener::started_ private
Definition at line 39 of file udp_listener.h.
The documentation for this class was generated from the following file:
ns-3_adapter/include/udp_listener.h