Carma-platform: bounding_box_to_detected_object::Node Class Reference
bounding_box_to_detected_object::Node Class Reference
#include <bounding_box_to_detected_object_node.h>
Public Member Functions
Node (const rclcpp::NodeOptions &)
void bbox_callback (autoware_auto_msgs::msg::BoundingBoxArray::UniquePtr msg)
Callback for bounding box data to be converted. Publishes a DetectedObjects message from the bounding box array.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &)
Private Attributes
carma_ros2_utils::SubPtr< autoware_auto_msgs::msg::BoundingBoxArray > bbox_sub_
carma_ros2_utils::PubPtr< autoware_auto_msgs::msg::DetectedObjects > object_pub_
Detailed Description
Definition at line 28 of file bounding_box_to_detected_object_node.h.
Constructor & Destructor Documentation
Node()
bounding_box_to_detected_object::Node::Node (const rclcpp::NodeOptions & options) explicit
Definition at line 25 of file bounding_box_to_detected_object_node.cpp.
  : carma_ros2_utils::CarmaLifecycleNode(options)
    {
    }
Member Function Documentation
bbox_callback()
void bounding_box_to_detected_object::Node::bbox_callback (autoware_auto_msgs::msg::BoundingBoxArray::UniquePtr msg)
Callback for bounding box data to be converted. Publishes a DetectedObjects message from the bounding box array.
Parameters
msg The message to convert and republish
Definition at line 60 of file bounding_box_to_detected_object_node.cpp.
{
    autoware_auto_msgs::msg::DetectedObjects objects;
    objects.header = msg->header;
    objects.objects.reserve(msg->boxes.size());
    for (const auto& bb : msg->boxes) {
      objects.objects.emplace_back(detected_obj_from_bounding_box(bb));
    }
    object_pub_->publish(objects);
  }
References bounding_box_to_detected_object::detected_obj_from_bounding_box(), and object_pub_.
Referenced by handle_on_configure().
handle_on_configure()
carma_ros2_utils::CallbackReturn bounding_box_to_detected_object::Node::handle_on_configure (const rclcpp_lifecycle::State &)
Definition at line 30 of file bounding_box_to_detected_object_node.cpp.
{
    // Setup pub/sub
    bbox_sub_= create_subscription<autoware_auto_msgs::msg::BoundingBoxArray>("bounding_boxes",10,
      std::bind(&Node::bbox_callback, this, _1)
    );
    object_pub_= create_publisher<autoware_auto_msgs::msg::DetectedObjects>("lidar_detected_objects", 10);
    return CallbackReturn::SUCCESS;
  }
References bbox_callback(), bbox_sub_, and object_pub_.
Member Data Documentation
bbox_sub_
carma_ros2_utils::SubPtr<autoware_auto_msgs::msg::BoundingBoxArray> bounding_box_to_detected_object::Node::bbox_sub_ private
Definition at line 34 of file bounding_box_to_detected_object_node.h.
Referenced by handle_on_configure().
object_pub_
carma_ros2_utils::PubPtr<autoware_auto_msgs::msg::DetectedObjects> bounding_box_to_detected_object::Node::object_pub_ private
Definition at line 37 of file bounding_box_to_detected_object_node.h.
Referenced by bbox_callback(), and handle_on_configure().
The documentation for this class was generated from the following files:
object_detection_tracking/include/bounding_box_to_detected_object/bounding_box_to_detected_object_node.h
object_detection_tracking/src/bounding_box_to_detected_object/bounding_box_to_detected_object_node.cpp