Carma-platform: internal::BigInteger Class Reference
internal::BigInteger Class Reference
#include <biginteger.h>
Public Types
typedef uint64_t Type
Public Member Functions
BigInteger (const BigInteger &rhs)
BigInteger (uint64_t u)
BigInteger (const char *decimals, size_t length)
BigInteger & operator= (const BigInteger &rhs)
BigInteger & operator= (uint64_t u)
BigInteger & operator+= (uint64_t u)
BigInteger & operator*= (uint64_t u)
BigInteger & operator*= (uint32_t u)
BigInteger & operator<<= (size_t shift)
bool operator== (const BigInteger &rhs) const
bool operator== (const Type rhs) const
BigInteger & MultiplyPow5 (unsigned exp)
bool Difference (const BigInteger &rhs, BigInteger *out) const
int Compare (const BigInteger &rhs) const
size_t GetCount () const
Type GetDigit (size_t index) const
bool IsZero () const
Private Member Functions
void AppendDecimal64 (const char *begin, const char *end)
void PushBack (Type digit)
Static Private Member Functions
static uint64_t ParseUint64 (const char *begin, const char *end)
static uint64_t MulAdd64 (uint64_t a, uint64_t b, uint64_t k, uint64_t *outHigh)
Private Attributes
Type digits_ [kCapacity]
size_t count_
Static Private Attributes
static const size_t kBitCount = 3328
static const size_t kCapacity = kBitCount / sizeof(Type)
static const size_t kTypeBit = sizeof(Type) * 8
Detailed Description
Definition at line 28 of file biginteger.h.
Member Typedef Documentation
Type
typedef uint64_t internal::BigInteger::Type
Definition at line 30 of file biginteger.h.
Constructor & Destructor Documentation
BigInteger() [1/3]
internal::BigInteger::BigInteger (const BigInteger & rhs) inline
Definition at line 32 of file biginteger.h.
                                      : count_(rhs.count_) {
        std::memcpy(digits_, rhs.digits_, count_ * sizeof(Type));
    }
References count_, and digits_.
BigInteger() [2/3]
internal::BigInteger::BigInteger (uint64_t u) inline explicit
Definition at line 36 of file biginteger.h.
                                    : count_(1) {
        digits_[0] = u;
    }
References digits_.
BigInteger() [3/3]
internal::BigInteger::BigInteger (const char * decimals, size_t length) inline
Definition at line 40 of file biginteger.h.
                                                    : count_(1) {
        RAPIDJSON_ASSERT(length > 0);
        digits_[0] = 0;
        size_t i = 0;
        const size_t kMaxDigitPerIteration = 19;  // 2^64 = 18446744073709551616 > 10^19
        while (length >= kMaxDigitPerIteration) {
            AppendDecimal64(decimals + i, decimals + i + kMaxDigitPerIteration);
            length -= kMaxDigitPerIteration;
            i += kMaxDigitPerIteration;
        }
        if (length > 0)
            AppendDecimal64(decimals + i, decimals + i + length);
    }
References AppendDecimal64(), digits_, process_bag::i, and RAPIDJSON_ASSERT.
Member Function Documentation
AppendDecimal64()
void internal::BigInteger::AppendDecimal64 (const char * begin, const char * end) inline private
Definition at line 224 of file biginteger.h.
{
        uint64_t u = ParseUint64(begin, end);
        if (IsZero())
            *this = u;
        else {
            unsigned exp = static_cast<unsigned>(end - begin);
            (MultiplyPow5(exp) <<= exp) += u;   // *this = *this * 10^exp + u
        }
    }
References IsZero(), MultiplyPow5(), and ParseUint64().
Referenced by BigInteger().
Compare()
int internal::BigInteger::Compare (const BigInteger & rhs) const inline
Definition at line 208 of file biginteger.h.
{
        if (count_ != rhs.count_)
            return count_ < rhs.count_ ? -1 : 1;
        for (size_t i = count_; i-- > 0;)
            if (digits_[i] != rhs.digits_[i])
                return digits_[i] < rhs.digits_[i] ? -1 : 1;
        return 0;
    }
References count_, digits_, and process_bag::i.
Referenced by internal::CheckWithinHalfULP(), and Difference().
Difference()
bool internal::BigInteger::Difference (const BigInteger & rhs, BigInteger * out) const inline
Definition at line 186 of file biginteger.h.
{
        int cmp = Compare(rhs);
        RAPIDJSON_ASSERT(cmp != 0);
        const BigInteger *a, *b;  // Makes a > b
        bool ret;
        if (cmp < 0) { a = &rhs; b = this; ret = true; }
        else         { a = this; b = &rhs; ret = false; }
        Type borrow = 0;
        for (size_t i = 0; i < a->count_; i++) {
            Type d = a->digits_[i] - borrow;
            if (i < b->count_)
                d -= b->digits_[i];
            borrow = (d > a->digits_[i]) ? 1 : 0;
            out->digits_[i] = d;
            if (d != 0)
                out->count_ = i + 1;
        }
        return ret;
    }
References a, Compare(), count_, digits_, process_bag::i, and RAPIDJSON_ASSERT.
Referenced by internal::CheckWithinHalfULP().
GetCount()
size_t internal::BigInteger::GetCount () const inline
Definition at line 219 of file biginteger.h.
{ return count_; }
References count_.
GetDigit()
Type internal::BigInteger::GetDigit (size_t index) const inline
Definition at line 220 of file biginteger.h.
{ RAPIDJSON_ASSERT(index < count_); return digits_[index]; }
References count_, digits_, and RAPIDJSON_ASSERT.
IsZero()
bool internal::BigInteger::IsZero () const inline
Definition at line 221 of file biginteger.h.
{ return count_ == 1 && digits_[0] == 0; }
References count_, and digits_.
Referenced by AppendDecimal64(), and operator<<=().
MulAdd64()
static uint64_t internal::BigInteger::MulAdd64 (uint64_t a, uint64_t b, uint64_t k, uint64_t * outHigh) inline static private
Definition at line 249 of file biginteger.h.
{
#if defined(_MSC_VER) && defined(_M_AMD64)
        uint64_t low = _umul128(a, b, outHigh) + k;
        if (low < k)
            (*outHigh)++;
        return low;
#elif (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6)) && defined(__x86_64__)
        __extension__ typedef unsigned __int128 uint128;
        uint128 p = static_cast<uint128>(a) * static_cast<uint128>(b);
        p += k;
        *outHigh = static_cast<uint64_t>(p >> 64);
        return static_cast<uint64_t>(p);
#else
        const uint64_t a0 = a & 0xFFFFFFFF, a1 = a >> 32, b0 = b & 0xFFFFFFFF, b1 = b >> 32;
        uint64_t x0 = a0 * b0, x1 = a0 * b1, x2 = a1 * b0, x3 = a1 * b1;
        x1 += (x0 >> 32); // can't give carry
        x1 += x2;
        if (x1 < x2)
            x3 += (static_cast<uint64_t>(1) << 32);
        uint64_t lo = (x1 << 32) + (x0 & 0xFFFFFFFF);
        uint64_t hi = x3 + (x1 >> 32);
        lo += k;
        if (lo < k)
            hi++;
        *outHigh = hi;
        return lo;
#endif
    }
References a.
Referenced by operator*=().
MultiplyPow5()
BigInteger & internal::BigInteger::MultiplyPow5 (unsigned exp) inline
Definition at line 162 of file biginteger.h.
{
        static const uint32_t kPow5[12] = {
            5,
            5 * 5,
            5 * 5 * 5,
            5 * 5 * 5 * 5,
            5 * 5 * 5 * 5 * 5,
            5 * 5 * 5 * 5 * 5 * 5,
            5 * 5 * 5 * 5 * 5 * 5 * 5,
            5 * 5 * 5 * 5 * 5 * 5 * 5 * 5,
            5 * 5 * 5 * 5 * 5 * 5 * 5 * 5 * 5,
            5 * 5 * 5 * 5 * 5 * 5 * 5 * 5 * 5 * 5,
            5 * 5 * 5 * 5 * 5 * 5 * 5 * 5 * 5 * 5 * 5,
            5 * 5 * 5 * 5 * 5 * 5 * 5 * 5 * 5 * 5 * 5 * 5
        };
        if (exp == 0) return *this;
        for (; exp >= 27; exp -= 27) *this *= RAPIDJSON_UINT64_C2(0X6765C793, 0XFA10079D); // 5^27
        for (; exp >= 13; exp -= 13) *this *= static_cast<uint32_t>(1220703125u); // 5^13
        if (exp > 0)                 *this *= kPow5[exp - 1];
        return *this;
    }
References RAPIDJSON_UINT64_C2.
Referenced by AppendDecimal64(), and internal::CheckWithinHalfULP().
operator*=() [1/2]
BigInteger & internal::BigInteger::operator*= (uint32_t u) inline
Definition at line 105 of file biginteger.h.
{
        if (u == 0) return *this = 0;
        if (u == 1) return *this;
        if (*this == 1) return *this = u;
        uint64_t k = 0;
        for (size_t i = 0; i < count_; i++) {
            const uint64_t c = digits_[i] >> 32;
            const uint64_t d = digits_[i] & 0xFFFFFFFF;
            const uint64_t uc = u * c;
            const uint64_t ud = u * d;
            const uint64_t p0 = ud + k;
            const uint64_t p1 = uc + (p0 >> 32);
            digits_[i] = (p0 & 0xFFFFFFFF) | (p1 << 32);
            k = p1 >> 32;
        }
        if (k > 0)
            PushBack(k);
        return *this;
    }
References process_traj_logs::c, count_, digits_, process_bag::i, and PushBack().
operator*=() [2/2]
BigInteger & internal::BigInteger::operator*= (uint64_t u) inline
Definition at line 87 of file biginteger.h.
{
        if (u == 0) return *this = 0;
        if (u == 1) return *this;
        if (*this == 1) return *this = u;
        uint64_t k = 0;
        for (size_t i = 0; i < count_; i++) {
            uint64_t hi;
            digits_[i] = MulAdd64(digits_[i], u, k, &hi);
            k = hi;
        }
        if (k > 0)
            PushBack(k);
        return *this;
    }
References count_, digits_, process_bag::i, MulAdd64(), and PushBack().
operator+=()
BigInteger & internal::BigInteger::operator+= (uint64_t u) inline
Definition at line 70 of file biginteger.h.
{
        Type backup = digits_[0];
        digits_[0] += u;
        for (size_t i = 0; i < count_ - 1; i++) {
            if (digits_[i] >= backup)
                return *this; // no carry
            backup = digits_[i + 1];
            digits_[i + 1] += 1;
        }
        // Last carry
        if (digits_[count_ - 1] < backup)
            PushBack(1);
        return *this;
    }
References count_, digits_, process_bag::i, and PushBack().
operator<<=()
BigInteger & internal::BigInteger::operator<<= (size_t shift) inline
Definition at line 128 of file biginteger.h.
{
        if (IsZero() || shift == 0) return *this;
        size_t offset = shift / kTypeBit;
        size_t interShift = shift % kTypeBit;
        RAPIDJSON_ASSERT(count_ + offset <= kCapacity);
        if (interShift == 0) {
            std::memmove(&digits_[count_ - 1 + offset], &digits_[count_ - 1], count_ * sizeof(Type));
            count_ += offset;
        }
        else {
            digits_[count_] = 0;
            for (size_t i = count_; i > 0; i--)
                digits_[i + offset] = (digits_[i] << interShift) | (digits_[i - 1] >> (kTypeBit - interShift));
            digits_[offset] = digits_[0] << interShift;
            count_ += offset;
            if (digits_[count_])
                count_++;
        }
        std::memset(digits_, 0, offset * sizeof(Type));
        return *this;
    }
References count_, digits_, process_bag::i, IsZero(), kCapacity, kTypeBit, and RAPIDJSON_ASSERT.
operator=() [1/2]
BigInteger & internal::BigInteger::operator= (const BigInteger & rhs) inline
Definition at line 55 of file biginteger.h.
    {
        if (this != &rhs) {
            count_ = rhs.count_;
            std::memcpy(digits_, rhs.digits_, count_ * sizeof(Type));
        }
        return *this;
    }
References count_, and digits_.
operator=() [2/2]
BigInteger & internal::BigInteger::operator= (uint64_t u) inline
Definition at line 64 of file biginteger.h.
{
        digits_[0] = u;
        count_ = 1;
        return *this;
    }
References count_, and digits_.
operator==() [1/2]
bool internal::BigInteger::operator== (const BigInteger & rhs) const inline
Definition at line 154 of file biginteger.h.
{
        return count_ == rhs.count_ && std::memcmp(digits_, rhs.digits_, count_ * sizeof(Type)) == 0;
    }
References count_, and digits_.
operator==() [2/2]
bool internal::BigInteger::operator== (const Type rhs) const inline
Definition at line 158 of file biginteger.h.
{
        return count_ == 1 && digits_[0] == rhs;
    }
References count_, and digits_.
ParseUint64()
static uint64_t internal::BigInteger::ParseUint64 (const char * begin, const char * end) inline static private
Definition at line 239 of file biginteger.h.
{
        uint64_t r = 0;
        for (const char* p = begin; p != end; ++p) {
            RAPIDJSON_ASSERT(*p >= '0' && *p <= '9');
            r = r * 10u + static_cast<unsigned>(*p - '0');
        }
        return r;
    }
References RAPIDJSON_ASSERT.
Referenced by AppendDecimal64().
PushBack()
void internal::BigInteger::PushBack (Type digit) inline private
Definition at line 234 of file biginteger.h.
{
        RAPIDJSON_ASSERT(count_ < kCapacity);
        digits_[count_++] = digit;
    }
References count_, digits_, kCapacity, and RAPIDJSON_ASSERT.
Referenced by operator*=(), and operator+=().
Member Data Documentation
count_
size_t internal::BigInteger::count_ private
Definition at line 284 of file biginteger.h.
Referenced by BigInteger(), Compare(), Difference(), GetCount(), GetDigit(), IsZero(), operator*=(), operator+=(), operator<<=(), operator=(), operator==(), and PushBack().
digits_
Type internal::BigInteger::digits_[kCapacity] private
Definition at line 283 of file biginteger.h.
Referenced by BigInteger(), Compare(), Difference(), GetDigit(), IsZero(), operator*=(), operator+=(), operator<<=(), operator=(), operator==(), and PushBack().
kBitCount
const size_t internal::BigInteger::kBitCount = 3328 static private
Definition at line 279 of file biginteger.h.
kCapacity
const size_t internal::BigInteger::kCapacity = kBitCount / sizeof(Type) static private
Definition at line 280 of file biginteger.h.
Referenced by operator<<=(), and PushBack().
kTypeBit
const size_t internal::BigInteger::kTypeBit = sizeof(Type) * 8 static private
Definition at line 281 of file biginteger.h.
Referenced by operator<<=().
The documentation for this class was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/internal/biginteger.h