Carma-platform: carma_guidance_plugins::StrategicPlugin Class Reference
carma_guidance_plugins::StrategicPlugin Class Reference abstract
StrategicPlugin base class which can be extended by user provided plugins which wish to implement the Strategic Plugin ROS API. A strategic plugin is responsible for planning sequences of maneuvers to achieve high-level objects for the vehicle (follow the route, efficiently get through an intersection, etc.)
#include <strategic_plugin.hpp>
Public Member Functions
StrategicPlugin (const rclcpp::NodeOptions &)
StrategicPlugin constructor.
virtual ~StrategicPlugin ()=default
Virtual destructor for safe deletion.
virtual void plan_maneuvers_callback (std::shared_ptr< rmw_request_id_t > srv_header, carma_planning_msgs::srv::PlanManeuvers::Request::SharedPtr req, carma_planning_msgs::srv::PlanManeuvers::Response::SharedPtr resp)=0
Extending class provided callback which should return a planned trajectory based on the provided trajectory planning request.
std::string get_capability () override
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
uint8_t get_type () override final
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_deactivate (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_cleanup (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_shutdown (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_error (const rclcpp_lifecycle::State &, const std::string &exception_string) override final
Public Member Functions inherited from carma_guidance_plugins::PluginBaseNode
PluginBaseNode (const rclcpp::NodeOptions &)
PluginBaseNode constructor.
virtual ~PluginBaseNode ()=default
Virtual destructor for safe deletion.
virtual std::shared_ptr< carma_wm::WMListener > get_world_model_listener () final
Method to return the default world model listener provided as a convience by this base class If this method or get_world_model() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
virtual carma_wm::WorldModelConstPtr get_world_model () final
Method to return the default world model provided as a convience by this base class If this method or get_world_model_listener() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
virtual bool get_activation_status () final
Returns the activation status of this plugin. The plugins API callbacks will only be triggered when this method returns true.
virtual uint8_t get_type ()
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
std::string get_plugin_name_and_ns () const
Return the name of this plugin with namespace. NOTE: If only the name of the plugin is required, use get_plugin_name()
std::string get_plugin_name () const
Return the name of this plugin.
virtual bool get_availability ()=0
Get the availability status of this plugin based on the current operating environment. Method must be overriden by extending classes.
virtual std::string get_capability ()=0
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
virtual std::string get_version_id ()=0
Returns the version id of this plugin.
virtual carma_ros2_utils::CallbackReturn on_configure_plugin ()=0
Method which is triggered when this plugin is moved from the UNCONFIGURED to INACTIVE states. This method should be used to load parameters and is required to be implemented.
virtual carma_ros2_utils::CallbackReturn on_activate_plugin ()
Method which is triggered when this plugin is moved from the INACTIVE to ACTIVE states. This method should be used to prepare for future callbacks for plugin's capabilites.
virtual carma_ros2_utils::CallbackReturn on_deactivate_plugin ()
Method which is triggered when this plugin is moved from the ACTIVE to INACTIVE states. This method should be used to disable any functionality which should cease execution when plugin is inactive.
virtual carma_ros2_utils::CallbackReturn on_cleanup_plugin ()
Method which is triggered when this plugin is moved from the INACTIVE to UNCONFIGURED states. This method should be used to fully reset the plugin such that a future call to on_configure_plugin would leave the plugin in a fresh state as though just launched.
virtual carma_ros2_utils::CallbackReturn on_shutdown_plugin ()
Method which is triggered when this plugin is moved from any state to FINALIZED This method should be used to generate any shutdown logs or final cleanup.
virtual carma_ros2_utils::CallbackReturn on_error_plugin (const std::string &exception_string)
Method which is triggered when an unhandled exception occurs in this plugin This method should be used to cleanup such that the plugin could be moved to UNCONFIGURED state if possible.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_deactivate (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_cleanup (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_shutdown (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_error (const rclcpp_lifecycle::State &, const std::string &exception_string) override
FRIEND_TEST (carma_guidance_plugins_test, connections_test)
Private Attributes
carma_ros2_utils::ServicePtr< carma_planning_msgs::srv::PlanManeuvers > plan_maneuvers_service_
The service which will be called when a strategic plugin needs to plan maneuvers.
Detailed Description
StrategicPlugin base class which can be extended by user provided plugins which wish to implement the Strategic Plugin ROS API. A strategic plugin is responsible for planning sequences of maneuvers to achieve high-level objects for the vehicle (follow the route, efficiently get through an intersection, etc.)
Definition at line 32 of file strategic_plugin.hpp.
Constructor & Destructor Documentation
StrategicPlugin()
carma_guidance_plugins::StrategicPlugin::StrategicPlugin (const rclcpp::NodeOptions & options) explicit
StrategicPlugin constructor.
Definition at line 24 of file strategic_plugin.cpp.
      : PluginBaseNode(options)
  {}
~StrategicPlugin()
virtual carma_guidance_plugins::StrategicPlugin::~StrategicPlugin () virtual default
Virtual destructor for safe deletion.
Member Function Documentation
get_capability()
std::string carma_guidance_plugins::StrategicPlugin::get_capability () override virtual
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
Returns
Forward slash separated string describing the plugin's capabilities per the plugin capabilites API
Implements carma_guidance_plugins::PluginBaseNode.
Definition at line 28 of file strategic_plugin.cpp.
  {
    return "strategic_plan/plan_maneuvers";
  }
get_type()
uint8_t carma_guidance_plugins::StrategicPlugin::get_type () final override virtual
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
Returns
The extending class type or UNKOWN if the class or no parent class has implement this method.
Reimplemented from carma_guidance_plugins::PluginBaseNode.
Definition at line 33 of file strategic_plugin.cpp.
  {
    return carma_planning_msgs::msg::Plugin::STRATEGIC;
  }
handle_on_activate()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::StrategicPlugin::handle_on_activate (const rclcpp_lifecycle::State & prev_state) final override
Definition at line 52 of file strategic_plugin.cpp.
  {
    return PluginBaseNode::handle_on_activate(prev_state);
  }
References carma_guidance_plugins::PluginBaseNode::handle_on_activate().
handle_on_cleanup()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::StrategicPlugin::handle_on_cleanup (const rclcpp_lifecycle::State & prev_state) final override
Definition at line 62 of file strategic_plugin.cpp.
  {
    return PluginBaseNode::handle_on_cleanup(prev_state);
  }
References carma_guidance_plugins::PluginBaseNode::handle_on_cleanup().
handle_on_configure()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::StrategicPlugin::handle_on_configure (const rclcpp_lifecycle::State & prev_state) final override
Definition at line 38 of file strategic_plugin.cpp.
  {
    // Initialize plan maneuvers service
    plan_maneuvers_service_ = create_service<carma_planning_msgs::srv::PlanManeuvers>(std::string(get_name()) + "/plan_maneuvers",
      [this] (auto header, auto req, auto resp) {
        if (this->get_activation_status()) // Only trigger when activated
        {
          this->plan_maneuvers_callback(header, req, resp);
        }
      });
    return PluginBaseNode::handle_on_configure(prev_state);
  }
References carma_guidance_plugins::PluginBaseNode::get_activation_status(), carma_guidance_plugins::PluginBaseNode::handle_on_configure(), plan_maneuvers_callback(), and plan_maneuvers_service_.
handle_on_deactivate()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::StrategicPlugin::handle_on_deactivate (const rclcpp_lifecycle::State & prev_state) final override
Definition at line 57 of file strategic_plugin.cpp.
  {
    return PluginBaseNode::handle_on_deactivate(prev_state);
  }
References carma_guidance_plugins::PluginBaseNode::handle_on_deactivate().
handle_on_error()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::StrategicPlugin::handle_on_error (const rclcpp_lifecycle::State & prev_state, const std::string & exception_string) final override
Definition at line 72 of file strategic_plugin.cpp.
  {
    return PluginBaseNode::handle_on_error(prev_state, exception_string);
  }
References carma_guidance_plugins::PluginBaseNode::handle_on_error().
handle_on_shutdown()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::StrategicPlugin::handle_on_shutdown (const rclcpp_lifecycle::State & prev_state) final override
Definition at line 67 of file strategic_plugin.cpp.
  {
    return PluginBaseNode::handle_on_shutdown(prev_state);
  }
References carma_guidance_plugins::PluginBaseNode::handle_on_shutdown().
plan_maneuvers_callback()
virtual void carma_guidance_plugins::StrategicPlugin::plan_maneuvers_callback (std::shared_ptr< rmw_request_id_t > srv_header, carma_planning_msgs::srv::PlanManeuvers::Request::SharedPtr req, carma_planning_msgs::srv::PlanManeuvers::Response::SharedPtr resp) pure virtual
Extending class provided callback which should return a planned trajectory based on the provided trajectory planning request.
Parameters
srv_header RCL header for services calls. Can usually be ignored by implementers.
req The service request containing the previously planned maneuvers and vehicle state
resp The response containing the additional maneuvers generated by this plugin
Implemented in lci_strategic_plugin::LCIStrategicPlugin, route_following_plugin::RouteFollowingPlugin, sci_strategic_plugin::SCIStrategicPlugin, stop_and_dwell_strategic_plugin::StopAndDwellStrategicPlugin, approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin, platoon_strategic_ihp::Node, and SUB::Node.
Referenced by handle_on_configure().
Member Data Documentation
plan_maneuvers_service_
carma_ros2_utils::ServicePtr<carma_planning_msgs::srv::PlanManeuvers> carma_guidance_plugins::StrategicPlugin::plan_maneuvers_service_ private
The service which will be called when a strategic plugin needs to plan maneuvers.
Definition at line 39 of file strategic_plugin.hpp.
Referenced by handle_on_configure().
The documentation for this class was generated from the following files:
carma_guidance_plugins/include/carma_guidance_plugins/strategic_plugin.hpp
carma_guidance_plugins/src/strategic_plugin.cpp