Carma-platform: cav::DriverWrapper Class Reference
cav::DriverWrapper Class Reference abstract
#include <driver_wrapper.h>
Public Member Functions
DriverWrapper (int argc, char **argv, std::string name="driver_wrapper")
DriverWrapper Constructor.
virtual ~DriverWrapper ()
~DriverWrapper Destructor
virtual int run () final
run Starts the driver wrapper
Protected Attributes
std::shared_ptr< ros::NodeHandle > nh_
std::shared_ptr< ros::NodeHandle > private_nh_
cav_msgs::DriverStatus status_
int spin_rate_
Private Member Functions
virtual void initialize ()=0
Initialize the node prior to beginning ROS loop.
virtual void pre_spin ()=0
Called prior to spinOnce()
virtual void post_spin ()=0
Called after spinOnce()
virtual void shutdown ()=0
Prepare for node shutdown.
void status_publish_timer (const ros::TimerEvent &) const
Called every second to publish the status message.
void system_alert_cb (const cav_msgs::SystemAlertConstPtr &msg)
Callback on system alert topic.
Private Attributes
ros::Publisher driver_status_pub_
ros::Subscriber system_alert_sub_
bool shutdown_
Detailed Description
Definition at line 26 of file driver_wrapper.h.
Constructor & Destructor Documentation
DriverWrapper()
cav::DriverWrapper::DriverWrapper (int argc, char ** argv, std::string name = "driver_wrapper") inline
DriverWrapper Constructor.
Parameters
argc Command line argument count
argv Array of command line arguments
name Node name
Definition at line 37 of file driver_wrapper.h.
                                                                            : status_(), spin_rate_(10), shutdown_(false)
    {
        ros::init(argc, argv, name);
    }
~DriverWrapper()
virtual cav::DriverWrapper::~DriverWrapper () inline virtual
~DriverWrapper Destructor
Definition at line 45 of file driver_wrapper.h.
{}
Member Function Documentation
initialize()
virtual void cav::DriverWrapper::initialize () private pure virtual
Initialize the node prior to beginning ROS loop.
Referenced by run().
post_spin()
virtual void cav::DriverWrapper::post_spin () private pure virtual
Called after spinOnce()
Referenced by run().
pre_spin()
virtual void cav::DriverWrapper::pre_spin () private pure virtual
Called prior to spinOnce()
Referenced by run().
run()
int cav::DriverWrapper::run () final virtual
run Starts the driver wrapper
Returns
0 on exit with no errors
Definition at line 21 of file driver_wrapper.cpp.
{
    nh_.reset(new ros::NodeHandle);
    private_nh_.reset(new ros::NodeHandle("~"));
    //Setup initial status
    status_.name = ros::this_node::getName();
    status_.status = cav_msgs::DriverStatus::OFF;
    //Initialize pubs and subs
    driver_status_pub_ = nh_->advertise<cav_msgs::DriverStatus>("driver_discovery", 1);
    system_alert_sub_ = nh_->subscribe("/system_alert", 10, &DriverWrapper::system_alert_cb, this);
    ros::Timer timer = private_nh_->createTimer(ros::Duration(1), &DriverWrapper::status_publish_timer, this);
    ROS_INFO_STREAM("Driver Initializing");
    initialize();
    ros::Rate r(spin_rate_);
    while(ros::ok() && !shutdown_)
    {
        pre_spin();
        ros::spinOnce();
        post_spin();
        r.sleep();
    }
    ROS_INFO_STREAM("Driver Shutting Down");
    shutdown();
    ros::shutdown();
}
References driver_status_pub_, initialize(), nh_, lightbar_manager::OFF, post_spin(), pre_spin(), private_nh_, shutdown(), shutdown_, spin_rate_, status_, status_publish_timer(), system_alert_cb(), and system_alert_sub_.
shutdown()
virtual void cav::DriverWrapper::shutdown () private pure virtual
Prepare for node shutdown.
Referenced by run().
status_publish_timer()
void cav::DriverWrapper::status_publish_timer (const ros::TimerEvent &) const private
Called every second to publish the status message.
Definition at line 52 of file driver_wrapper.cpp.
{
    driver_status_pub_.publish(status_);
}
References driver_status_pub_, and status_.
Referenced by run().
system_alert_cb()
void cav::DriverWrapper::system_alert_cb (const cav_msgs::SystemAlertConstPtr & msg) private
Callback on system alert topic.
Definition at line 57 of file driver_wrapper.cpp.
{
    u_char t = msg->type;
    if(t == cav_msgs::SystemAlert::FATAL || t == cav_msgs::SystemAlert::SHUTDOWN)
    {
        shutdown_ = true;
    }
}
References arbitrator::SHUTDOWN, and shutdown_.
Referenced by run().
Member Data Documentation
driver_status_pub_
ros::Publisher cav::DriverWrapper::driver_status_pub_ private
Definition at line 92 of file driver_wrapper.h.
Referenced by run(), and status_publish_timer().
nh_
std::shared_ptr<ros::NodeHandle> cav::DriverWrapper::nh_ protected
Definition at line 55 of file driver_wrapper.h.
Referenced by run().
private_nh_
std::shared_ptr<ros::NodeHandle> cav::DriverWrapper::private_nh_ protected
Definition at line 55 of file driver_wrapper.h.
Referenced by run().
shutdown_
bool cav::DriverWrapper::shutdown_ private
Definition at line 94 of file driver_wrapper.h.
Referenced by run(), and system_alert_cb().
spin_rate_
int cav::DriverWrapper::spin_rate_ protected
Definition at line 57 of file driver_wrapper.h.
Referenced by run().
status_
cav_msgs::DriverStatus cav::DriverWrapper::status_ protected
Definition at line 56 of file driver_wrapper.h.
Referenced by run(), and status_publish_timer().
system_alert_sub_
ros::Subscriber cav::DriverWrapper::system_alert_sub_ private
Definition at line 93 of file driver_wrapper.h.
Referenced by run().
The documentation for this class was generated from the following files:
ns-3_adapter/include/driver_wrapper/driver_wrapper.h
ns-3_adapter/src/driver_wrapper/driver_wrapper.cpp