Carma-platform: platooning_control::PIDController Class Reference
platooning_control::PIDController Class Reference
This class includes logic for PID controller. PID controller is used in this plugin to maintain the inter-vehicle gap by adjusting the speed.
#include <pid_controller.hpp>
Public Member Functions
PIDController ()
Constructor for the PID controller class.
double calculate (double setpoint, double pv)
function to calculate control command based on setpoint and process vale
void reset ()
Public Attributes
std::shared_ptr< PlatooningControlPluginConfig > config_ = std::make_shared<PlatooningControlPluginConfig>()
plugin config object
Private Attributes
double _pre_error = 0.0
double _integral = 0.0
Detailed Description
This class includes logic for PID controller. PID controller is used in this plugin to maintain the inter-vehicle gap by adjusting the speed.
Definition at line 27 of file pid_controller.hpp.
Constructor & Destructor Documentation
PIDController()
platooning_control::PIDController::PIDController ()
Constructor for the PID controller class.
Definition at line 22 of file pid_controller.cpp.
{}
Member Function Documentation
calculate()
double platooning_control::PIDController::calculate (double setpoint, double pv)
function to calculate control command based on setpoint and process vale
Parameters
setpoint desired value
pv current value
Returns
the manipulated variable given a setpoint and current process value
Definition at line 24 of file pid_controller.cpp.
{
        // Calculate error
        double error = setpoint - pv;
        RCLCPP_DEBUG_STREAM(rclcpp::get_logger("platooning_control"),"PID error: " << error);
        // Proportional term
        double Pout = config_->kp * error;
        RCLCPP_DEBUG_STREAM(rclcpp::get_logger("platooning_control"), "Proportional term: " << Pout);
        // Integral term
        _integral += error * config_->dt;
        RCLCPP_DEBUG_STREAM(rclcpp::get_logger("platooning_control"),"Integral term: " << _integral);
        if (_integral > config_->integrator_max){
             _integral = config_->integrator_max;
        }
        else if (_integral < config_->integrator_min){
            _integral = config_->integrator_min;
        }
        double Iout = config_->ki * _integral;
        RCLCPP_DEBUG_STREAM(rclcpp::get_logger("platooning_control"), "Iout: " << Iout);
        // Derivative term
        double derivative = (error - _pre_error) / config_->dt;
        RCLCPP_DEBUG_STREAM(rclcpp::get_logger("platooning_control"), "derivative term: " << derivative);
        double Dout = config_->kd * derivative;
        RCLCPP_DEBUG_STREAM(rclcpp::get_logger("platooning_control"), "Dout: " << Dout);
        // Calculate total output
        double output = Pout + Iout + Dout;
        RCLCPP_DEBUG_STREAM(rclcpp::get_logger("platooning_control"), "total controller output: " << output);
        // Restrict to max/min
        if( output > config_->max_delta_speed_per_timestep )
            output = config_->max_delta_speed_per_timestep;
        else if( output < config_->min_delta_speed_per_timestep )
            output = config_->min_delta_speed_per_timestep;
        // Save error to previous error
        _pre_error = error;
        return output;
    }
References _integral, _pre_error, and config_.
Referenced by platooning_control::PlatooningControlWorker::generate_speed().
reset()
void platooning_control::PIDController::reset ()
Definition at line 68 of file pid_controller.cpp.
{
        _integral = 0.0;
        _pre_error = 0.0;
    }
References _integral, and _pre_error.
Referenced by platooning_control::PlatooningControlWorker::generate_speed().
Member Data Documentation
_integral
double platooning_control::PIDController::_integral = 0.0 private
Definition at line 66 of file pid_controller.hpp.
Referenced by calculate(), and reset().
_pre_error
double platooning_control::PIDController::_pre_error = 0.0 private
Definition at line 65 of file pid_controller.hpp.
Referenced by calculate(), and reset().
config_
std::shared_ptr<PlatooningControlPluginConfig> platooning_control::PIDController::config_ = std::make_shared<PlatooningControlPluginConfig>()
plugin config object
Definition at line 39 of file pid_controller.hpp.
Referenced by calculate().
The documentation for this class was generated from the following files:
platooning_control/include/platooning_control/pid_controller.hpp
platooning_control/src/pid_controller.cpp