Carma-platform: health_monitor::EntryManager Class Reference
health_monitor::EntryManager Class Reference
#include <entry_manager.h>
Public Member Functions
EntryManager ()
Default constructor for EntryManager.
EntryManager (std::vector< std::string > required_entries)
Constructor for EntryManager to set required entries.
EntryManager (std::vector< std::string > required_entries, std::vector< std::string > lidar_gps_entries, std::vector< std::string > camera_entries)
Constructor for EntryManager to set required entries and lidar gps entires.
void update_entry (const Entry &entry)
Add a new entry if the given name does not exist. Update an existing entry if the given name exists.
std::vector< Entry > get_entries () const
Get all registed entries as a list.
boost::optional< Entry > get_entry_by_name (const std::string &name) const
Get a entry using name as the key.
void delete_entry (const std::string &name)
Delete an entry using the given name as the key.
bool is_entry_required (const std::string &name) const
Check if the entry is required.
int is_lidar_gps_entry_required (const std::string &name) const
Check if the entry is required.
int is_camera_entry_required (const std::string &name) const
Private Attributes
std::vector< Entry > entry_list_
std::vector< std::string > required_entries_
std::vector< std::string > lidar_gps_entries_
std::vector< std::string > camera_entries_
Detailed Description
Definition at line 25 of file entry_manager.h.
Constructor & Destructor Documentation
EntryManager() [1/3]
health_monitor::EntryManager::EntryManager ()
Default constructor for EntryManager.
Definition at line 23 of file entry_manager.cpp.
{}
EntryManager() [2/3]
health_monitor::EntryManager::EntryManager (std::vector< std::string > required_entries)
Constructor for EntryManager to set required entries.
Definition at line 25 of file entry_manager.cpp.
:required_entries_(required_entries) {}
EntryManager() [3/3]
health_monitor::EntryManager::EntryManager (std::vector< std::string > required_entries, std::vector< std::string > lidar_gps_entries, std::vector< std::string > camera_entries)
Constructor for EntryManager to set required entries and lidar gps entires.
Definition at line 27 of file entry_manager.cpp.
                                         :required_entries_(required_entries),lidar_gps_entries_(lidar_gps_entries), camera_entries_(camera_entries){}
Member Function Documentation
delete_entry()
void health_monitor::EntryManager::delete_entry (const std::string & name)
Delete an entry using the given name as the key.
Definition at line 53 of file entry_manager.cpp.
    {
        for(auto i = entry_list_.begin(); i < entry_list_.end(); ++i)
        {
            if(i->name_.compare(name) == 0)
            {
                entry_list_.erase(i);
                return;
            }
        }
    }
References entry_list_, and process_bag::i.
get_entries()
std::vector< Entry > health_monitor::EntryManager::get_entries () const
Get all registed entries as a list.
Definition at line 47 of file entry_manager.cpp.
    {
        // returns the copy of the original list
        return std::vector<Entry>(entry_list_);
    }
References entry_list_.
Referenced by health_monitor::DriverManager::are_critical_drivers_operational_car(), and health_monitor::DriverManager::are_critical_drivers_operational_truck().
get_entry_by_name()
boost::optional< Entry > health_monitor::EntryManager::get_entry_by_name (const std::string & name) const
Get a entry using name as the key.
Definition at line 65 of file entry_manager.cpp.
    {
        for(auto i = entry_list_.begin(); i < entry_list_.end(); ++i)
        {
            if(i->name_.compare(name) == 0)
            {
                return *i;
            }
        }
        // use boost::optional because requested entry might not exist
        return boost::none;
    }
References entry_list_, and process_bag::i.
is_camera_entry_required()
int health_monitor::EntryManager::is_camera_entry_required (const std::string & name) const
Definition at line 105 of file entry_manager.cpp.
    {
        for(int i = 0;i < camera_entries_.size(); i++)
        {
            if(camera_entries_[i].compare(name) == 0)
            {
                return i;
            }
        }
        // default like above?
        return -1;
    }
References camera_entries_, and process_bag::i.
Referenced by health_monitor::DriverManager::are_critical_drivers_operational_car(), and health_monitor::DriverManager::are_critical_drivers_operational_truck().
is_entry_required()
bool health_monitor::EntryManager::is_entry_required (const std::string & name) const
Check if the entry is required.
Definition at line 78 of file entry_manager.cpp.
    {
        for(auto i = required_entries_.begin(); i < required_entries_.end(); ++i)
        {
            if(i->compare(name) == 0)
            {
                return true;
            }
        }
        return false;
    }
References process_bag::i, and required_entries_.
Referenced by health_monitor::DriverManager::are_critical_drivers_operational_car(), and health_monitor::DriverManager::are_critical_drivers_operational_truck().
is_lidar_gps_entry_required()
int health_monitor::EntryManager::is_lidar_gps_entry_required (const std::string & name) const
Check if the entry is required.
Definition at line 90 of file entry_manager.cpp.
    {
        for(int i=0;i<lidar_gps_entries_.size();i++)
        {
            if(lidar_gps_entries_[i].compare(name) == 0)
            {
                return i;
            }
        }
        return -1;
    }
References process_bag::i, and lidar_gps_entries_.
Referenced by health_monitor::DriverManager::are_critical_drivers_operational_car(), and health_monitor::DriverManager::are_critical_drivers_operational_truck().
update_entry()
void health_monitor::EntryManager::update_entry (const Entry & entry)
Add a new entry if the given name does not exist. Update an existing entry if the given name exists.
Definition at line 30 of file entry_manager.cpp.
    {
        for(auto i = entry_list_.begin(); i < entry_list_.end(); ++i)
        {
            if(i->name_.compare(entry.name_) == 0)
            {
                // name and type of the entry wont change
                i->active_ = entry.active_;
                i->available_ = entry.available_;
                i->timestamp_ = entry.timestamp_;
                return;
            }
        }
        entry_list_.push_back(entry);
    }
References health_monitor::Entry::active_, health_monitor::Entry::available_, entry_list_, process_bag::i, health_monitor::Entry::name_, and health_monitor::Entry::timestamp_.
Referenced by health_monitor::DriverManager::update_driver_status().
Member Data Documentation
camera_entries_
std::vector<std::string> health_monitor::EntryManager::camera_entries_ private
Definition at line 87 of file entry_manager.h.
Referenced by is_camera_entry_required().
entry_list_
std::vector<Entry> health_monitor::EntryManager::entry_list_ private
Definition at line 79 of file entry_manager.h.
Referenced by delete_entry(), get_entries(), get_entry_by_name(), and update_entry().
lidar_gps_entries_
std::vector<std::string> health_monitor::EntryManager::lidar_gps_entries_ private
Definition at line 85 of file entry_manager.h.
Referenced by is_lidar_gps_entry_required().
required_entries_
std::vector<std::string> health_monitor::EntryManager::required_entries_ private
Definition at line 82 of file entry_manager.h.
Referenced by is_entry_required().
The documentation for this class was generated from the following files:
health_monitor/include/entry_manager.h
health_monitor/src/entry_manager.cpp