Carma-platform: lightbar_manager::LightBarManagerStateMachine Class Reference
lightbar_manager::LightBarManagerStateMachine Class Reference
#include <lightbar_manager_sm.hpp>
Public Member Functions
LightBarManagerStateMachine ()
Default constructor for LightBarManagerStateMachine.
void next (const LightBarEvent &event)
Transition to the next state of the LightBarStateMachine.
LightBarState getCurrentState ()
Get current state machine status.
void handleStateChange (const carma_planning_msgs::msg::GuidanceState &msg)
This function triggers the transitioning to the next state in LightBarStateMachine based on the guidance state change.
Private Member Functions
void onDisengage ()
void onActive ()
void onEngage ()
Private Attributes
uint8_t guidance_state_ = carma_planning_msgs::msg::GuidanceState::SHUTDOWN
carma_ros2_utils::ClientPtr< carma_msgs::srv::ReleaseIndicatorControl > request_control_client_
carma_ros2_utils::ClientPtr< carma_msgs::srv::RequestIndicatorControl > release_control_client_
carma_ros2_utils::ClientPtr< carma_driver_msgs::srv::SetLightBarIndicator > set_indicator_client_
LightBarState current_state_ = DISENGAGED
Detailed Description
Definition at line 53 of file lightbar_manager_sm.hpp.
Constructor & Destructor Documentation
LightBarManagerStateMachine()
lightbar_manager::LightBarManagerStateMachine::LightBarManagerStateMachine ()
Default constructor for LightBarManagerStateMachine.
Definition at line 22 of file lightbar_manager_sm.cpp.
{}
Member Function Documentation
getCurrentState()
LightBarState lightbar_manager::LightBarManagerStateMachine::getCurrentState ()
Get current state machine status.
Definition at line 114 of file lightbar_manager_sm.cpp.
{
    return current_state_;
}
References current_state_.
Referenced by lightbar_manager::LightBarManagerWorker::getCurrentState().
handleStateChange()
void lightbar_manager::LightBarManagerStateMachine::handleStateChange (const carma_planning_msgs::msg::GuidanceState & msg)
This function triggers the transitioning to the next state in LightBarStateMachine based on the guidance state change.
Definition at line 62 of file lightbar_manager_sm.cpp.
{
    // Check if the msg is as same as before
    if (msg.state == guidance_state_)
        return;
    switch (msg.state)
    {
        case carma_planning_msgs::msg::GuidanceState::STARTUP:
        case carma_planning_msgs::msg::GuidanceState::SHUTDOWN:
            onDisengage();
            break;
        case carma_planning_msgs::msg::GuidanceState::ACTIVE:
        case carma_planning_msgs::msg::GuidanceState::DRIVERS_READY:
        case carma_planning_msgs::msg::GuidanceState::INACTIVE:
            onActive();
            break;
        case carma_planning_msgs::msg::GuidanceState::ENGAGED:
            onEngage();
            break;
        default:
            RCLCPP_WARN_STREAM(rclcpp::get_logger("lightbar_manager"),"LightBarManager received unknown state from guidance state machine:" << msg.state);
            break;
    }
    // Update the current state
    guidance_state_ = msg.state;
}
References lightbar_manager::ACTIVE, lightbar_manager::ENGAGED, guidance_state_, port_drayage_plugin::INACTIVE, onActive(), onDisengage(), onEngage(), and arbitrator::SHUTDOWN.
Referenced by lightbar_manager::LightBarManagerWorker::handleStateChange().
next()
void lightbar_manager::LightBarManagerStateMachine::next (const LightBarEvent & event)
Transition to the next state of the LightBarStateMachine.
Definition at line 25 of file lightbar_manager_sm.cpp.
{
    // Set to DISENGAGED state if guidance is disingaged
    if(event == LightBarEvent::GUIDANCE_DISENGAGED) {
        current_state_ = DISENGAGED;
        return;
    }
    switch(current_state_)
    {
        case DISENGAGED:
            if(event == LightBarEvent::GUIDANCE_CONNECTED) {
                current_state_ = ACTIVE;
            }
            else if(event == LightBarEvent::GUIDANCE_ENGAGED) {
                current_state_ = ENGAGED;
            }
            break;
        case ENGAGED:
            if(event == LightBarEvent::GUIDANCE_DISCONNECTED) {
                current_state_ = ACTIVE;
            }
            break;
        case ACTIVE:
            if(event == LightBarEvent::GUIDANCE_ENGAGED) {
                current_state_ = ENGAGED;
            }
            break;
        default:
            break;
    }
}
References lightbar_manager::ACTIVE, current_state_, lightbar_manager::DISENGAGED, lightbar_manager::ENGAGED, lightbar_manager::GUIDANCE_CONNECTED, lightbar_manager::GUIDANCE_DISCONNECTED, lightbar_manager::GUIDANCE_DISENGAGED, and lightbar_manager::GUIDANCE_ENGAGED.
Referenced by lightbar_manager::LightBarManagerWorker::next(), onActive(), onDisengage(), and onEngage().
onActive()
void lightbar_manager::LightBarManagerStateMachine::onActive () private
Definition at line 98 of file lightbar_manager_sm.cpp.
{
    // Transitioning FROM ENGAGED state to Active
    if (guidance_state_ == carma_planning_msgs::msg::GuidanceState::ENGAGED)
        next(GUIDANCE_DISCONNECTED);
    // Transitioning FROM all "OFF" states of guidance for lightbar (STARTUP, DRIVERS_READY, INACTIVE, OFF)
    else
        next(GUIDANCE_CONNECTED);
}
References lightbar_manager::ENGAGED, lightbar_manager::GUIDANCE_CONNECTED, lightbar_manager::GUIDANCE_DISCONNECTED, guidance_state_, and next().
Referenced by handleStateChange().
onDisengage()
void lightbar_manager::LightBarManagerStateMachine::onDisengage () private
Definition at line 93 of file lightbar_manager_sm.cpp.
{
    next(GUIDANCE_DISENGAGED);
}
References lightbar_manager::GUIDANCE_DISENGAGED, and next().
Referenced by handleStateChange().
onEngage()
void lightbar_manager::LightBarManagerStateMachine::onEngage () private
Definition at line 108 of file lightbar_manager_sm.cpp.
{
    next(GUIDANCE_ENGAGED);
}
References lightbar_manager::GUIDANCE_ENGAGED, and next().
Referenced by handleStateChange().
Member Data Documentation
current_state_
LightBarState lightbar_manager::LightBarManagerStateMachine::current_state_ = DISENGAGED private
Definition at line 94 of file lightbar_manager_sm.hpp.
Referenced by getCurrentState(), and next().
guidance_state_
uint8_t lightbar_manager::LightBarManagerStateMachine::guidance_state_ = carma_planning_msgs::msg::GuidanceState::SHUTDOWN private
Definition at line 86 of file lightbar_manager_sm.hpp.
Referenced by handleStateChange(), and onActive().
release_control_client_
carma_ros2_utils::ClientPtr<carma_msgs::srv::RequestIndicatorControl> lightbar_manager::LightBarManagerStateMachine::release_control_client_ private
Definition at line 90 of file lightbar_manager_sm.hpp.
request_control_client_
carma_ros2_utils::ClientPtr<carma_msgs::srv::ReleaseIndicatorControl> lightbar_manager::LightBarManagerStateMachine::request_control_client_ private
Definition at line 89 of file lightbar_manager_sm.hpp.
set_indicator_client_
carma_ros2_utils::ClientPtr<carma_driver_msgs::srv::SetLightBarIndicator> lightbar_manager::LightBarManagerStateMachine::set_indicator_client_ private
Definition at line 91 of file lightbar_manager_sm.hpp.
The documentation for this class was generated from the following files:
lightbar_manager/include/lightbar_manager/lightbar_manager_sm.hpp
lightbar_manager/src/lightbar_manager_sm.cpp