Carma-platform: mock_drivers::MockDriver Class Reference
mock_drivers::MockDriver Class Reference abstract
The template node for the mock drivers that will handle all of the default driver logic.
#include <MockDriver.h>
Public Member Functions
virtual ~MockDriver ()=0
int run ()
A function to initialize the publishers and subsricers and start the node. In child classes, this function will trigger a call to onRun().
virtual std::vector< DriverType > getDriverTypes ()=0
Pure Virtual method which child classes must override that returns the list of all driver types that class implements.
virtual uint8_t getDriverStatus ()=0
Pure Virtual method. Returns an integer value which corresponds to the cav_msgs/DriverStatus enum felids representing the status of the driver.
virtual unsigned int getRate ()=0
Pure virtual method that returns the desired operational rate of a child class.
bool spinCallback ()
Callback which will be triggered at the rate specified by getRate(). This callback will also trigger the onSpin() method.
Protected Types
template<class T >
using ConstPtr = boost::shared_ptr< const T >
template<class T >
using ConstPtrRef = const ConstPtr< T > &
template<class T >
using ROSCommsPtr = boost::shared_ptr< ROSComms< T > >
template<class T >
using ConstPtrRefROSComms = ROSComms< ConstPtrRef< T > >
template<class T >
using ConstPtrRefROSCommsPtr = ROSCommsPtr< ConstPtrRef< T > >
Protected Member Functions
virtual bool onSpin ()
Virtual method which child classes can override to add functionality which will occur during each spin loop. This means this function will be nominally called at the rate specified by getRate()
virtual int onRun ()=0
Pure virtual method which must be implemented by child classes. This method will be run once at startup. Child classes should add pub/sub initialization in this method implementation.
void driverDiscovery ()
Helper function to publish the driver discovery message.
MockDriverNode getMockDriverNode () const
Returns the mock driver node for the mock driver (used for testing)
template<typename T >
void addPassthroughPub (const std::string &sub_topic, const std::string &pub_topic, bool latch, size_t queue_size)
Function adds both a publisher and subscriber of the specified type. This means a passthrough subscription has been created. This version of the method should be used for message types which contain a Header at the field "header". The header field will be automatically updated to the current ros::Time::now().
template<typename T >
void addPassthroughPubNoHeader (const std::string &sub_topic, const std::string &pub_topic, bool latch, size_t queue_size)
Function adds both a publisher and subscriber of the specified type. This means a passthrough subscription has been created. This version of the method should be used for message types which does NOT contain a Header at the field "header".
Protected Attributes
MockDriverNode mock_driver_node_
const std::string bag_prefix_ = "/bag/hardware_interface/"
const std::string driver_discovery_topic_ = "driver_discovery"
ROSCommsPtr< cav_msgs::DriverStatus > driver_discovery_pub_ptr_
ros::Time last_discovery_pub_ = ros::Time(0)
Detailed Description
The template node for the mock drivers that will handle all of the default driver logic.
This class has virtual functions that define what to do when the mock driver is run.
It will also have build in default mock driver publishers and subscribers baked in, such as the driver discovery publisher.
Definition at line 39 of file MockDriver.h.
Member Typedef Documentation
ConstPtr
template<class T > using mock_drivers::MockDriver::ConstPtr = boost::shared_ptr<const T> protected
Definition at line 44 of file MockDriver.h.
ConstPtrRef
template<class T > using mock_drivers::MockDriver::ConstPtrRef = const ConstPtr<T>& protected
Definition at line 47 of file MockDriver.h.
ConstPtrRefROSComms
template<class T > using mock_drivers::MockDriver::ConstPtrRefROSComms = ROSComms<ConstPtrRef<T> > protected
Definition at line 53 of file MockDriver.h.
ConstPtrRefROSCommsPtr
template<class T > using mock_drivers::MockDriver::ConstPtrRefROSCommsPtr = ROSCommsPtr<ConstPtrRef<T> > protected
Definition at line 56 of file MockDriver.h.
ROSCommsPtr
template<class T > using mock_drivers::MockDriver::ROSCommsPtr = boost::shared_ptr<ROSComms<T> > protected
Definition at line 50 of file MockDriver.h.
Constructor & Destructor Documentation
~MockDriver()
mock_drivers::MockDriver::~MockDriver () pure virtual
Definition at line 21 of file MockDriver.cpp.
{
}
Member Function Documentation
addPassthroughPub()
template<typename T > void mock_drivers::MockDriver::addPassthroughPub (const std::string & sub_topic, const std::string & pub_topic, bool latch, size_t queue_size) protected
Function adds both a publisher and subscriber of the specified type. This means a passthrough subscription has been created. This version of the method should be used for message types which contain a Header at the field "header". The header field will be automatically updated to the current ros::Time::now().
Template Parameters
T ROS message type which the provided topic name applies to. Should be the base type only such as sensor_msgs/NavSatFix
Parameters
sub_topic The topic name to subscribe to.
pub_topic The topic name to publish to.
latch Flag idicating if the output publisher should be latched.
queue_size The size of the queue to use both for the publisher and subscriber
TODO: This function can be combined with addPassthroughPubNoHeader using C++ 17's constexpr if statements.
addPassthroughPubNoHeader()
template<typename T > void mock_drivers::MockDriver::addPassthroughPubNoHeader (const std::string & sub_topic, const std::string & pub_topic, bool latch, size_t queue_size) protected
Function adds both a publisher and subscriber of the specified type. This means a passthrough subscription has been created. This version of the method should be used for message types which does NOT contain a Header at the field "header".
Template Parameters
T ROS message type which the provided topic name applies to. Should be the base type only such as sensor_msgs/NavSatFix
Parameters
sub_topic The topic name to subscribe to.
pub_topic The topic name to publish to.
latch Flag idicating if the output publisher should be latched.
queue_size The size of the queue to use both for the publisher and subscriber
TODO: This function can be combined with addPassthroughPub using C++ 17's constexpr if statements.
driverDiscovery()
void mock_drivers::MockDriver::driverDiscovery () protected
Helper function to publish the driver discovery message.
Definition at line 63 of file MockDriver.cpp.
{
  cav_msgs::DriverStatus discovery_msg;
  discovery_msg.name = mock_driver_node_.getGraphName();
  discovery_msg.status = getDriverStatus();
  for (DriverType type : getDriverTypes())
  {
    switch (type)
    {
      case DriverType::CAN:
        discovery_msg.can = true;
        break;
      case DriverType::RADAR:
        discovery_msg.radar = true;
        break;
      case DriverType::GNSS:
        discovery_msg.gnss = true;
        break;
      case DriverType::LIDAR:
        discovery_msg.lidar = true;
        break;
      case DriverType::ROADWAY_SENSOR:
        discovery_msg.roadway_sensor = true;
        break;
      case DriverType::COMMS:
        discovery_msg.comms = true;
        break;
      case DriverType::CONTROLLER:
        discovery_msg.controller = true;
        break;
      case DriverType::CAMERA:
        discovery_msg.camera = true;
        break;
      case DriverType::IMU:
        discovery_msg.imu = true;
        break;
      case DriverType::TRAILER_ANGLE_SENSOR:
        discovery_msg.trailer_angle_sensor = true;
        break;
      case DriverType::LIGHTBAR:
        discovery_msg.lightbar = true;
        break;
      default:
        std::invalid_argument("Unsupported DriverType provided by getDriverTypes");
        break;
    }
  }
  mock_driver_node_.publishDataNoHeader<cav_msgs::DriverStatus>(driver_discovery_topic_, discovery_msg);
}
References CAMERA, CAN, COMMS, CONTROLLER, driver_discovery_topic_, getDriverStatus(), getDriverTypes(), mock_drivers::MockDriverNode::getGraphName(), GNSS, IMU, LIDAR, LIGHTBAR, mock_driver_node_, mock_drivers::MockDriverNode::publishDataNoHeader(), RADAR, ROADWAY_SENSOR, and TRAILER_ANGLE_SENSOR.
Referenced by spinCallback().
getDriverStatus()
virtual uint8_t mock_drivers::MockDriver::getDriverStatus () pure virtual
Pure Virtual method. Returns an integer value which corresponds to the cav_msgs/DriverStatus enum felids representing the status of the driver.
Returns
Integer value which must match one of the enum fields in cav_msgs/DriverStatus
Implemented in mock_drivers::MockCameraDriver, mock_drivers::MockCANDriver, mock_drivers::MockCommsDriver, mock_drivers::MockControllerDriver, mock_drivers::MockGNSSDriver, mock_drivers::MockIMUDriver, mock_drivers::MockLidarDriver, mock_drivers::MockRadarDriver, and mock_drivers::MockRoadwaySensorDriver.
Referenced by driverDiscovery().
getDriverTypes()
virtual std::vector< DriverType > mock_drivers::MockDriver::getDriverTypes () pure virtual
Pure Virtual method which child classes must override that returns the list of all driver types that class implements.
Returns
A list of DriverType that defines the interfaces the implementing class provides
Implemented in mock_drivers::MockCameraDriver, mock_drivers::MockCANDriver, mock_drivers::MockCommsDriver, mock_drivers::MockControllerDriver, mock_drivers::MockGNSSDriver, mock_drivers::MockIMUDriver, mock_drivers::MockLidarDriver, mock_drivers::MockRadarDriver, and mock_drivers::MockRoadwaySensorDriver.
Referenced by driverDiscovery().
getMockDriverNode()
MockDriverNode mock_drivers::MockDriver::getMockDriverNode () const protected
Returns the mock driver node for the mock driver (used for testing)
Definition at line 25 of file MockDriver.cpp.
{
  return mock_driver_node_;
}
References mock_driver_node_.
getRate()
virtual unsigned int mock_drivers::MockDriver::getRate () pure virtual
Pure virtual method that returns the desired operational rate of a child class.
Returns
Spin rate in Hz
Implemented in mock_drivers::MockCameraDriver, mock_drivers::MockCANDriver, mock_drivers::MockCommsDriver, mock_drivers::MockControllerDriver, mock_drivers::MockGNSSDriver, mock_drivers::MockIMUDriver, mock_drivers::MockLidarDriver, mock_drivers::MockRadarDriver, and mock_drivers::MockRoadwaySensorDriver.
Referenced by run().
onRun()
virtual int mock_drivers::MockDriver::onRun () protected pure virtual
Pure virtual method which must be implemented by child classes. This method will be run once at startup. Child classes should add pub/sub initialization in this method implementation.
Returns
An integer error code. A non-zero value will indicate an initialization failure and result in node shutdown.
Implemented in mock_drivers::MockCameraDriver, mock_drivers::MockCANDriver, mock_drivers::MockCommsDriver, mock_drivers::MockControllerDriver, mock_drivers::MockGNSSDriver, mock_drivers::MockIMUDriver, mock_drivers::MockLidarDriver, mock_drivers::MockRadarDriver, and mock_drivers::MockRoadwaySensorDriver.
Referenced by run().
onSpin()
bool mock_drivers::MockDriver::onSpin () protected virtual
Virtual method which child classes can override to add functionality which will occur during each spin loop. This means this function will be nominally called at the rate specified by getRate()
Returns
Return false if this node should shutdown. True otherwise.
Reimplemented in mock_drivers::MockControllerDriver.
Definition at line 30 of file MockDriver.cpp.
{
  return true;
}
Referenced by spinCallback().
run()
int mock_drivers::MockDriver::run ()
A function to initialize the publishers and subsricers and start the node. In child classes, this function will trigger a call to onRun().
Returns
An integer error code. A non-zero value will indicate an initialization failure and result in node shutdown.
Definition at line 35 of file MockDriver.cpp.
                    {
  mock_driver_node_.init();
  // driver discovery publisher
  mock_driver_node_.addPub(driver_discovery_pub_ptr_);
  mock_driver_node_.setSpinCallback(std::bind(&MockDriver::spinCallback, this));
  int return_val = onRun();
  if (return_val != 0) {
    return return_val;
  }
  mock_driver_node_.spin(getRate());
  return 0;
}
References mock_drivers::MockDriverNode::addPub(), driver_discovery_pub_ptr_, getRate(), mock_drivers::MockDriverNode::init(), mock_driver_node_, onRun(), mock_drivers::MockDriverNode::setSpinCallback(), mock_drivers::MockDriverNode::spin(), and spinCallback().
Referenced by main().
spinCallback()
bool mock_drivers::MockDriver::spinCallback ()
Callback which will be triggered at the rate specified by getRate(). This callback will also trigger the onSpin() method.
Returns
False if this node should shutdown. True otherwise.
Definition at line 53 of file MockDriver.cpp.
{
  if (last_discovery_pub_ == ros::Time(0) || (ros::Time::now() - last_discovery_pub_).toSec() > 0.95)
  {
    driverDiscovery();
    last_discovery_pub_ = ros::Time::now();
  }
  return onSpin();
}
References driverDiscovery(), last_discovery_pub_, and onSpin().
Referenced by run().
Member Data Documentation
bag_prefix_
const std::string mock_drivers::MockDriver::bag_prefix_ = "/bag/hardware_interface/" protected
Definition at line 63 of file MockDriver.h.
Referenced by mock_drivers::MockCameraDriver::onRun(), mock_drivers::MockCANDriver::onRun(), mock_drivers::MockCommsDriver::onRun(), mock_drivers::MockGNSSDriver::onRun(), mock_drivers::MockIMUDriver::onRun(), mock_drivers::MockLidarDriver::onRun(), mock_drivers::MockRadarDriver::onRun(), and mock_drivers::MockRoadwaySensorDriver::onRun().
driver_discovery_pub_ptr_
ROSCommsPtr<cav_msgs::DriverStatus> mock_drivers::MockDriver::driver_discovery_pub_ptr_ protected
Initial value:
=
      boost::make_shared<ROSComms<cav_msgs::DriverStatus>>(CommTypes::pub, false, 10, driver_discovery_topic_)
Definition at line 67 of file MockDriver.h.
Referenced by run().
driver_discovery_topic_
const std::string mock_drivers::MockDriver::driver_discovery_topic_ = "driver_discovery" protected
Definition at line 65 of file MockDriver.h.
Referenced by driverDiscovery().
last_discovery_pub_
ros::Time mock_drivers::MockDriver::last_discovery_pub_ = ros::Time(0) protected
Definition at line 70 of file MockDriver.h.
Referenced by spinCallback().
mock_driver_node_
MockDriverNode mock_drivers::MockDriver::mock_driver_node_ protected
Definition at line 59 of file MockDriver.h.
Referenced by mock_drivers::MockCameraDriver::MockCameraDriver(), mock_drivers::MockCANDriver::MockCANDriver(), mock_drivers::MockCommsDriver::MockCommsDriver(), mock_drivers::MockControllerDriver::MockControllerDriver(), mock_drivers::MockGNSSDriver::MockGNSSDriver(), mock_drivers::MockIMUDriver::MockIMUDriver(), mock_drivers::MockLidarDriver::MockLidarDriver(), mock_drivers::MockRadarDriver::MockRadarDriver(), mock_drivers::MockRoadwaySensorDriver::MockRoadwaySensorDriver(), driverDiscovery(), getMockDriverNode(), mock_drivers::MockCommsDriver::onRun(), mock_drivers::MockControllerDriver::onRun(), mock_drivers::MockControllerDriver::onSpin(), and run().
The documentation for this class was generated from the following files:
mock_drivers/rosbag_mock_drivers/include/rosbag_mock_drivers/MockDriver.h
mock_drivers/rosbag_mock_drivers/src/MockDriver.cpp