Carma-platform: trajectory_follower_wrapper::TrajectoryFollowerWrapperNode Class Reference
trajectory_follower_wrapper::TrajectoryFollowerWrapperNode Class Reference
#include <trajectory_follower_wrapper_node.hpp>
Public Member Functions
TrajectoryFollowerWrapperNode (const rclcpp::NodeOptions &options)
Node constructor.
rcl_interfaces::msg::SetParametersResult parameter_update_callback (const std::vector< rclcpp::Parameter > &parameters)
Callback for dynamic parameter updates.
void autoware_info_timer_callback ()
Timer callback to spin at 30 hz and frequently publish autoware kinematic state and trajectory.
void ackermann_control_cb (const autoware_auto_msgs::msg::AckermannControlCommand::SharedPtr msg)
autoware's control subscription callback
bool isControlCommandOld (const autoware_auto_msgs::msg::AckermannControlCommand &cmd) const
Check to see if the received control command recent or old.
autoware_auto_msgs::msg::VehicleKinematicState convert_state (const geometry_msgs::msg::PoseStamped &pose, const geometry_msgs::msg::TwistStamped &twist) const
convert vehicle's pose and twist messages to autoware kinematic state
autoware_msgs::msg::ControlCommandStamped convert_cmd (const autoware_auto_msgs::msg::AckermannControlCommand &cmd) const
convert autoware Ackermann control command to autoware stamped control command
autoware_msgs::msg::ControlCommandStamped generate_command () override
Extending class provided method which should generate a command message which will be published to the required topic by the base class.
bool get_availability () override
Get the availability status of this plugin based on the current operating environment. Method must be overriden by extending classes.
std::string get_version_id () override
Returns the version id of this plugin.
carma_ros2_utils::CallbackReturn on_configure_plugin () override
This method should be used to load parameters and will be called on the configure state transition.
FRIEND_TEST (TesttrajectoryFollowerWrapper, TestControlCallback)
FRIEND_TEST (TesttrajectoryFollowerWrapper, TestThreshold)
Public Member Functions inherited from carma_guidance_plugins::ControlPlugin
ControlPlugin (const rclcpp::NodeOptions &)
ControlPlugin constructor.
virtual ~ControlPlugin ()=default
Virtual destructor for safe deletion.
virtual autoware_msgs::msg::ControlCommandStamped generate_command ()=0
Extending class provided method which should generate a command message which will be published to the required topic by the base class.
std::string get_capability () override
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
uint8_t get_type () override final
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_deactivate (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_cleanup (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_shutdown (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_error (const rclcpp_lifecycle::State &, const std::string &exception_string) override final
Public Member Functions inherited from carma_guidance_plugins::PluginBaseNode
PluginBaseNode (const rclcpp::NodeOptions &)
PluginBaseNode constructor.
virtual ~PluginBaseNode ()=default
Virtual destructor for safe deletion.
virtual std::shared_ptr< carma_wm::WMListener > get_world_model_listener () final
Method to return the default world model listener provided as a convience by this base class If this method or get_world_model() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
virtual carma_wm::WorldModelConstPtr get_world_model () final
Method to return the default world model provided as a convience by this base class If this method or get_world_model_listener() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
virtual bool get_activation_status () final
Returns the activation status of this plugin. The plugins API callbacks will only be triggered when this method returns true.
virtual uint8_t get_type ()
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
std::string get_plugin_name_and_ns () const
Return the name of this plugin with namespace. NOTE: If only the name of the plugin is required, use get_plugin_name()
std::string get_plugin_name () const
Return the name of this plugin.
virtual bool get_availability ()=0
Get the availability status of this plugin based on the current operating environment. Method must be overriden by extending classes.
virtual std::string get_capability ()=0
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
virtual std::string get_version_id ()=0
Returns the version id of this plugin.
virtual carma_ros2_utils::CallbackReturn on_configure_plugin ()=0
Method which is triggered when this plugin is moved from the UNCONFIGURED to INACTIVE states. This method should be used to load parameters and is required to be implemented.
virtual carma_ros2_utils::CallbackReturn on_activate_plugin ()
Method which is triggered when this plugin is moved from the INACTIVE to ACTIVE states. This method should be used to prepare for future callbacks for plugin's capabilites.
virtual carma_ros2_utils::CallbackReturn on_deactivate_plugin ()
Method which is triggered when this plugin is moved from the ACTIVE to INACTIVE states. This method should be used to disable any functionality which should cease execution when plugin is inactive.
virtual carma_ros2_utils::CallbackReturn on_cleanup_plugin ()
Method which is triggered when this plugin is moved from the INACTIVE to UNCONFIGURED states. This method should be used to fully reset the plugin such that a future call to on_configure_plugin would leave the plugin in a fresh state as though just launched.
virtual carma_ros2_utils::CallbackReturn on_shutdown_plugin ()
Method which is triggered when this plugin is moved from any state to FINALIZED This method should be used to generate any shutdown logs or final cleanup.
virtual carma_ros2_utils::CallbackReturn on_error_plugin (const std::string &exception_string)
Method which is triggered when an unhandled exception occurs in this plugin This method should be used to cleanup such that the plugin could be moved to UNCONFIGURED state if possible.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_deactivate (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_cleanup (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_shutdown (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_error (const rclcpp_lifecycle::State &, const std::string &exception_string) override
FRIEND_TEST (carma_guidance_plugins_test, connections_test)
Public Attributes
TrajectoryFollowerWrapperConfig config_
Private Attributes
carma_ros2_utils::SubPtr< autoware_auto_msgs::msg::AckermannControlCommand > control_cmd_sub_
carma_ros2_utils::PubPtr< autoware_auto_msgs::msg::Trajectory > autoware_traj_pub_
carma_ros2_utils::PubPtr< autoware_auto_msgs::msg::VehicleKinematicState > autoware_state_pub_
rclcpp::TimerBase::SharedPtr autoware_info_timer_
std::optional< autoware_auto_msgs::msg::AckermannControlCommand > received_ctrl_command_
Additional Inherited Members
Protected Member Functions inherited from carma_guidance_plugins::ControlPlugin
void current_pose_callback (geometry_msgs::msg::PoseStamped::UniquePtr msg)
void current_twist_callback (geometry_msgs::msg::TwistStamped::UniquePtr msg)
void current_trajectory_callback (carma_planning_msgs::msg::TrajectoryPlan::UniquePtr msg)
Protected Attributes inherited from carma_guidance_plugins::ControlPlugin
boost::optional< geometry_msgs::msg::PoseStamped > current_pose_
The most recent pose message received by this node.
boost::optional< geometry_msgs::msg::TwistStamped > current_twist_
The most recent velocity message received by this node.
boost::optional< carma_planning_msgs::msg::TrajectoryPlan > current_trajectory_
The most recent trajectory received by this plugin.
Detailed Description
Definition at line 35 of file trajectory_follower_wrapper_node.hpp.
Constructor & Destructor Documentation
TrajectoryFollowerWrapperNode()
trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::TrajectoryFollowerWrapperNode (const rclcpp::NodeOptions & options) explicit
Node constructor.
Definition at line 22 of file trajectory_follower_wrapper_node.cpp.
      : carma_guidance_plugins::ControlPlugin(options)
  {
    // Create initial config
    config_ = TrajectoryFollowerWrapperConfig();
    config_.vehicle_response_lag = declare_parameter<double>("vehicle_response_lag", config_.vehicle_response_lag);
    config_.incoming_cmd_time_threshold = declare_parameter<double>("incoming_cmd_time_threshold", config_.incoming_cmd_time_threshold);
  }
References config_, trajectory_follower_wrapper::TrajectoryFollowerWrapperConfig::incoming_cmd_time_threshold, and trajectory_follower_wrapper::TrajectoryFollowerWrapperConfig::vehicle_response_lag.
Member Function Documentation
ackermann_control_cb()
void trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::ackermann_control_cb (const autoware_auto_msgs::msg::AckermannControlCommand::SharedPtr msg)
autoware's control subscription callback
Definition at line 103 of file trajectory_follower_wrapper_node.cpp.
  {
    RCLCPP_DEBUG_STREAM(rclcpp::get_logger("trajectory_follower_wrapper"), "In ackermann control callback");
    received_ctrl_command_ = *msg;
  }
References received_ctrl_command_.
Referenced by on_configure_plugin().
autoware_info_timer_callback()
void trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::autoware_info_timer_callback ()
Timer callback to spin at 30 hz and frequently publish autoware kinematic state and trajectory.
Definition at line 85 of file trajectory_follower_wrapper_node.cpp.
  {
    RCLCPP_DEBUG_STREAM(rclcpp::get_logger("trajectory_follower_wrapper"), "In autoware info timer callback");
    if (current_trajectory_ && current_pose_ && current_twist_)
    {
      // generate and publish autoware kinematic state
      auto autoware_state = convert_state(current_pose_.get(), current_twist_.get());
      autoware_state_pub_->publish(autoware_state);
      // generate and publish autoware trajectory
      current_trajectory_.get().header.frame_id = autoware_state.header.frame_id;
      auto autoware_traj_plan = basic_autonomy::waypoint_generation::process_trajectory_plan(current_trajectory_.get(), config_.vehicle_response_lag);
      autoware_traj_pub_->publish(autoware_traj_plan);
    }
  }
References autoware_state_pub_, autoware_traj_pub_, config_, convert_state(), carma_guidance_plugins::ControlPlugin::current_pose_, carma_guidance_plugins::ControlPlugin::current_trajectory_, carma_guidance_plugins::ControlPlugin::current_twist_, basic_autonomy::waypoint_generation::process_trajectory_plan(), and trajectory_follower_wrapper::TrajectoryFollowerWrapperConfig::vehicle_response_lag.
Referenced by on_configure_plugin().
convert_cmd()
autoware_msgs::msg::ControlCommandStamped trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::convert_cmd (const autoware_auto_msgs::msg::AckermannControlCommand & cmd) const
convert autoware Ackermann control command to autoware stamped control command
Definition at line 124 of file trajectory_follower_wrapper_node.cpp.
  {
    autoware_msgs::msg::ControlCommandStamped return_cmd;
    return_cmd.header.stamp = cmd.stamp;
    return_cmd.cmd.linear_acceleration = cmd.longitudinal.acceleration;
    return_cmd.cmd.linear_velocity = cmd.longitudinal.speed;
    return_cmd.cmd.steering_angle = cmd.lateral.steering_tire_angle;
    RCLCPP_DEBUG_STREAM(rclcpp::get_logger("trajectory_follower_wrapper"), "generated command cmd.stamp: " << std::to_string(rclcpp::Time(cmd.stamp).seconds()));
    RCLCPP_DEBUG_STREAM(rclcpp::get_logger("trajectory_follower_wrapper"), "generated command cmd.longitudinal.acceleration: " << cmd.longitudinal.acceleration);
    RCLCPP_DEBUG_STREAM(rclcpp::get_logger("trajectory_follower_wrapper"), "generated command cmd.longitudinal.speed: " << cmd.longitudinal.speed);
    RCLCPP_DEBUG_STREAM(rclcpp::get_logger("trajectory_follower_wrapper"), "generated command cmd.lateral.steering_tire_angle: " << cmd.lateral.steering_tire_angle);
    RCLCPP_DEBUG_STREAM(rclcpp::get_logger("trajectory_follower_wrapper"), "generated command cmd.lateral.steering_tire_rotation_rate: " << cmd.lateral.steering_tire_rotation_rate);
    return return_cmd;
  }
References carma_cooperative_perception::to_string().
Referenced by generate_command().
convert_state()
autoware_auto_msgs::msg::VehicleKinematicState trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::convert_state (const geometry_msgs::msg::PoseStamped & pose, const geometry_msgs::msg::TwistStamped & twist) const
convert vehicle's pose and twist messages to autoware kinematic state
Definition at line 110 of file trajectory_follower_wrapper_node.cpp.
  {
    autoware_auto_msgs::msg::VehicleKinematicState state;
    state.header = pose.header;
    state.state.x = pose.pose.position.x;
    state.state.y = pose.pose.position.y;
    state.state.z = pose.pose.position.z;
    state.state.heading.real = pose.pose.orientation.w;
    state.state.heading.imag = pose.pose.orientation.z;
    state.state.longitudinal_velocity_mps = twist.twist.linear.x;
    return state;
  }
Referenced by autoware_info_timer_callback().
FRIEND_TEST() [1/2]
trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::FRIEND_TEST (TesttrajectoryFollowerWrapper , TestControlCallback)
FRIEND_TEST() [2/2]
trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::FRIEND_TEST (TesttrajectoryFollowerWrapper , TestThreshold)
generate_command()
autoware_msgs::msg::ControlCommandStamped trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::generate_command () override virtual
Extending class provided method which should generate a command message which will be published to the required topic by the base class.
NOTE: Implementer can determine if trajectory has changed based on current_trajectory_->trajectory_id
Returns
The command message to publish
Implements carma_guidance_plugins::ControlPlugin.
Definition at line 142 of file trajectory_follower_wrapper_node.cpp.
  {
    // process and save the trajectory
    autoware_msgs::msg::ControlCommandStamped converted_cmd;
    if (!current_trajectory_ || !current_pose_ || !current_twist_ || !received_ctrl_command_.has_value())
    {
      RCLCPP_DEBUG_STREAM(rclcpp::get_logger("trajectory_follower_wrapper"), "Insufficient data, empty control command generated");
      return converted_cmd;
    }
    if (isControlCommandOld(received_ctrl_command_.value()))
    {
      RCLCPP_DEBUG_STREAM(rclcpp::get_logger("trajectory_follower_wrapper"), "Control Command is old, empty control command generated");
      return converted_cmd;
    }
    converted_cmd = convert_cmd(received_ctrl_command_.value());
    return converted_cmd;
  }
References convert_cmd(), carma_guidance_plugins::ControlPlugin::current_pose_, carma_guidance_plugins::ControlPlugin::current_trajectory_, carma_guidance_plugins::ControlPlugin::current_twist_, isControlCommandOld(), and received_ctrl_command_.
get_availability()
bool trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::get_availability () override virtual
Get the availability status of this plugin based on the current operating environment. Method must be overriden by extending classes.
Returns
This method should return true if the plugin's current understanding of the world means it would be capable of planning or executing its capability.
Implements carma_guidance_plugins::PluginBaseNode.
Definition at line 177 of file trajectory_follower_wrapper_node.cpp.
  {
    return true;
  }
get_version_id()
std::string trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::get_version_id () override virtual
Returns the version id of this plugin.
Returns
The version id represented as a string
Implements carma_guidance_plugins::PluginBaseNode.
Definition at line 182 of file trajectory_follower_wrapper_node.cpp.
  {
    return "1.0";
  }
isControlCommandOld()
bool trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::isControlCommandOld (const autoware_auto_msgs::msg::AckermannControlCommand & cmd) const
Check to see if the received control command recent or old.
Definition at line 165 of file trajectory_follower_wrapper_node.cpp.
  {
    double difference = std::abs(this->now().seconds() - rclcpp::Time(cmd.stamp).seconds());
    if (difference >= config_.incoming_cmd_time_threshold)
    {
      return true;
    }
    return false;
  }
References config_, and trajectory_follower_wrapper::TrajectoryFollowerWrapperConfig::incoming_cmd_time_threshold.
Referenced by generate_command().
on_configure_plugin()
carma_ros2_utils::CallbackReturn trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::on_configure_plugin () override virtual
This method should be used to load parameters and will be called on the configure state transition.
Implements carma_guidance_plugins::PluginBaseNode.
Definition at line 46 of file trajectory_follower_wrapper_node.cpp.
  {
    // Reset config
    config_ = TrajectoryFollowerWrapperConfig();
    // Load parameters
    get_parameter<double>("vehicle_response_lag", config_.vehicle_response_lag);
    get_parameter<double>("incoming_cmd_time_threshold", config_.incoming_cmd_time_threshold);
    RCLCPP_INFO_STREAM(rclcpp::get_logger("trajectory_follower_wrapper"), "Loaded Params: " << config_);
    // Register runtime parameter update callback
    add_on_set_parameters_callback(std::bind(&TrajectoryFollowerWrapperNode::parameter_update_callback, this, std_ph::_1));
    // NOTE: Currently, intra-process comms must be disabled for the following subscriber that is transient_local: https://github.com/ros2/rclcpp/issues/1753
    rclcpp::SubscriptionOptions intra_proc_disabled;
    intra_proc_disabled.use_intra_process_comm = rclcpp::IntraProcessSetting::Disable;
    auto sub_qos_transient_local = rclcpp::QoS(rclcpp::KeepAll()); // A subscriber with this QoS will store all messages that it has sent on the topic
    sub_qos_transient_local.transient_local();
    // Setup subscriber
    control_cmd_sub_ = create_subscription<autoware_auto_msgs::msg::AckermannControlCommand>("output/control_cmd", sub_qos_transient_local,
      std::bind(&TrajectoryFollowerWrapperNode::ackermann_control_cb, this, std::placeholders::_1),intra_proc_disabled);
    // Setup publishers
    autoware_traj_pub_ = create_publisher<autoware_auto_msgs::msg::Trajectory>("input/reference_trajectory", 10);
    autoware_state_pub_ = create_publisher<autoware_auto_msgs::msg::VehicleKinematicState>("input/current_kinematic_state", 10);
    // Setup timers to publish autoware compatible info (trajectory and state)
    autoware_info_timer_ = create_timer(
        get_clock(),
        std::chrono::milliseconds(33), // Spin at 30 Hz per plugin API
        std::bind(&TrajectoryFollowerWrapperNode::autoware_info_timer_callback, this));
    // Return success if everthing initialized successfully
    return CallbackReturn::SUCCESS;
  }
References ackermann_control_cb(), autoware_info_timer_, autoware_info_timer_callback(), autoware_state_pub_, autoware_traj_pub_, config_, control_cmd_sub_, trajectory_follower_wrapper::TrajectoryFollowerWrapperConfig::incoming_cmd_time_threshold, parameter_update_callback(), and trajectory_follower_wrapper::TrajectoryFollowerWrapperConfig::vehicle_response_lag.
parameter_update_callback()
rcl_interfaces::msg::SetParametersResult trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::parameter_update_callback (const std::vector< rclcpp::Parameter > & parameters)
Callback for dynamic parameter updates.
Definition at line 32 of file trajectory_follower_wrapper_node.cpp.
  {
    auto error_double = update_params<double>({
      {"vehicle_response_lag", config_.vehicle_response_lag},
      {"incoming_cmd_time_threshold", config_.incoming_cmd_time_threshold}
      }, parameters);
    rcl_interfaces::msg::SetParametersResult result;
    result.successful = !error_double;
    return result;
  }
References config_, trajectory_follower_wrapper::TrajectoryFollowerWrapperConfig::incoming_cmd_time_threshold, and trajectory_follower_wrapper::TrajectoryFollowerWrapperConfig::vehicle_response_lag.
Referenced by on_configure_plugin().
Member Data Documentation
autoware_info_timer_
rclcpp::TimerBase::SharedPtr trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::autoware_info_timer_ private
Definition at line 47 of file trajectory_follower_wrapper_node.hpp.
Referenced by on_configure_plugin().
autoware_state_pub_
carma_ros2_utils::PubPtr<autoware_auto_msgs::msg::VehicleKinematicState> trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::autoware_state_pub_ private
Definition at line 44 of file trajectory_follower_wrapper_node.hpp.
Referenced by autoware_info_timer_callback(), and on_configure_plugin().
autoware_traj_pub_
carma_ros2_utils::PubPtr<autoware_auto_msgs::msg::Trajectory> trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::autoware_traj_pub_ private
Definition at line 43 of file trajectory_follower_wrapper_node.hpp.
Referenced by autoware_info_timer_callback(), and on_configure_plugin().
config_
TrajectoryFollowerWrapperConfig trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::config_
Definition at line 81 of file trajectory_follower_wrapper_node.hpp.
Referenced by TrajectoryFollowerWrapperNode(), autoware_info_timer_callback(), isControlCommandOld(), on_configure_plugin(), and parameter_update_callback().
control_cmd_sub_
carma_ros2_utils::SubPtr<autoware_auto_msgs::msg::AckermannControlCommand> trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::control_cmd_sub_ private
Definition at line 40 of file trajectory_follower_wrapper_node.hpp.
Referenced by on_configure_plugin().
received_ctrl_command_
std::optional<autoware_auto_msgs::msg::AckermannControlCommand> trajectory_follower_wrapper::TrajectoryFollowerWrapperNode::received_ctrl_command_ private
Definition at line 50 of file trajectory_follower_wrapper_node.hpp.
Referenced by ackermann_control_cb(), and generate_command().
The documentation for this class was generated from the following files:
trajectory_follower_wrapper/include/trajectory_follower_wrapper/trajectory_follower_wrapper_node.hpp
trajectory_follower_wrapper/src/trajectory_follower_wrapper_node.cpp