Carma-platform: light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode Class Reference
light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode Class Reference
ROS node for the LightControlledIntersectionTransitPluginNode.
#include <light_controlled_intersection_tactical_plugin_node.hpp>
Public Member Functions
LightControlledIntersectionTransitPluginNode (const rclcpp::NodeOptions &)
LightControlledIntersectionTransitPluginNode constructor.
rcl_interfaces::msg::SetParametersResult parameter_update_callback (const std::vector< rclcpp::Parameter > &parameters)
Callback for dynamic parameter updates.
void plan_trajectory_callback (std::shared_ptr< rmw_request_id_t >, carma_planning_msgs::srv::PlanTrajectory::Request::SharedPtr req, carma_planning_msgs::srv::PlanTrajectory::Response::SharedPtr resp) override
Extending class provided callback which should return a planned trajectory based on the provided trajectory planning request.
bool get_availability () override
Get the availability status of this plugin based on the current operating environment. Method must be overriden by extending classes.
std::string get_version_id () override
Returns the version id of this plugin.
carma_ros2_utils::CallbackReturn on_configure_plugin () override
This method should be used to load parameters and will be called on the configure state transition.
Public Member Functions inherited from carma_guidance_plugins::TacticalPlugin
TacticalPlugin (const rclcpp::NodeOptions &)
TacticalPlugin constructor.
virtual ~TacticalPlugin ()=default
Virtual destructor for safe deletion.
virtual void plan_trajectory_callback (std::shared_ptr< rmw_request_id_t > srv_header, carma_planning_msgs::srv::PlanTrajectory::Request::SharedPtr req, carma_planning_msgs::srv::PlanTrajectory::Response::SharedPtr resp)=0
Extending class provided callback which should return a planned trajectory based on the provided trajectory planning request.
std::string get_capability () override
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
uint8_t get_type () override final
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_deactivate (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_cleanup (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_shutdown (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_error (const rclcpp_lifecycle::State &, const std::string &exception_string) override final
Public Member Functions inherited from carma_guidance_plugins::PluginBaseNode
PluginBaseNode (const rclcpp::NodeOptions &)
PluginBaseNode constructor.
virtual ~PluginBaseNode ()=default
Virtual destructor for safe deletion.
virtual std::shared_ptr< carma_wm::WMListener > get_world_model_listener () final
Method to return the default world model listener provided as a convience by this base class If this method or get_world_model() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
virtual carma_wm::WorldModelConstPtr get_world_model () final
Method to return the default world model provided as a convience by this base class If this method or get_world_model_listener() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
virtual bool get_activation_status () final
Returns the activation status of this plugin. The plugins API callbacks will only be triggered when this method returns true.
virtual uint8_t get_type ()
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
std::string get_plugin_name_and_ns () const
Return the name of this plugin with namespace. NOTE: If only the name of the plugin is required, use get_plugin_name()
std::string get_plugin_name () const
Return the name of this plugin.
virtual bool get_availability ()=0
Get the availability status of this plugin based on the current operating environment. Method must be overriden by extending classes.
virtual std::string get_capability ()=0
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
virtual std::string get_version_id ()=0
Returns the version id of this plugin.
virtual carma_ros2_utils::CallbackReturn on_configure_plugin ()=0
Method which is triggered when this plugin is moved from the UNCONFIGURED to INACTIVE states. This method should be used to load parameters and is required to be implemented.
virtual carma_ros2_utils::CallbackReturn on_activate_plugin ()
Method which is triggered when this plugin is moved from the INACTIVE to ACTIVE states. This method should be used to prepare for future callbacks for plugin's capabilites.
virtual carma_ros2_utils::CallbackReturn on_deactivate_plugin ()
Method which is triggered when this plugin is moved from the ACTIVE to INACTIVE states. This method should be used to disable any functionality which should cease execution when plugin is inactive.
virtual carma_ros2_utils::CallbackReturn on_cleanup_plugin ()
Method which is triggered when this plugin is moved from the INACTIVE to UNCONFIGURED states. This method should be used to fully reset the plugin such that a future call to on_configure_plugin would leave the plugin in a fresh state as though just launched.
virtual carma_ros2_utils::CallbackReturn on_shutdown_plugin ()
Method which is triggered when this plugin is moved from any state to FINALIZED This method should be used to generate any shutdown logs or final cleanup.
virtual carma_ros2_utils::CallbackReturn on_error_plugin (const std::string &exception_string)
Method which is triggered when an unhandled exception occurs in this plugin This method should be used to cleanup such that the plugin could be moved to UNCONFIGURED state if possible.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_deactivate (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_cleanup (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_shutdown (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_error (const rclcpp_lifecycle::State &, const std::string &exception_string) override
FRIEND_TEST (carma_guidance_plugins_test, connections_test)
Private Attributes
Config config_
carma_ros2_utils::ClientPtr< carma_planning_msgs::srv::PlanTrajectory > yield_client_
std::shared_ptr< LightControlledIntersectionTacticalPlugin > worker_
Detailed Description
ROS node for the LightControlledIntersectionTransitPluginNode.
Definition at line 32 of file light_controlled_intersection_tactical_plugin_node.hpp.
Constructor & Destructor Documentation
LightControlledIntersectionTransitPluginNode()
light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode::LightControlledIntersectionTransitPluginNode (const rclcpp::NodeOptions & options) explicit
LightControlledIntersectionTransitPluginNode constructor.
Definition at line 22 of file light_controlled_intersection_tactical_plugin_node.cpp.
      : carma_guidance_plugins::TacticalPlugin(options)
  {
    // Create initial config
    config_ = Config();
    // Declare parameters
    config_.centerline_sampling_spacing = declare_parameter<double>("centerline_sampling_spacing", config_.centerline_sampling_spacing);
    config_.trajectory_time_length = declare_parameter<double>("trajectory_time_length", config_.trajectory_time_length);
    config_.default_downsample_ratio = declare_parameter<int>("default_downsample_ratio", config_.default_downsample_ratio);
    config_.turn_downsample_ratio = declare_parameter<int>("turn_downsample_ratio", config_.turn_downsample_ratio);
    config_.curve_resample_step_size = declare_parameter<double>("curve_resample_step_size", config_.curve_resample_step_size);
    config_.curvature_moving_average_window_size = declare_parameter<int>("curvature_moving_average_window_size", config_.curvature_moving_average_window_size);
    config_.speed_moving_average_window_size = declare_parameter<int>("speed_moving_average_window_size", config_.speed_moving_average_window_size);
    config_.back_distance = declare_parameter<double>("back_distance", config_.back_distance);
    config_.buffer_ending_downtrack = declare_parameter<double>("buffer_ending_downtrack", config_.buffer_ending_downtrack);
    config_.vehicle_decel_limit_multiplier = declare_parameter<double>("vehicle_decel_limit_multiplier", config_.vehicle_decel_limit_multiplier);
    config_.vehicle_accel_limit_multiplier = declare_parameter<double>("vehicle_accel_limit_multiplier", config_.vehicle_accel_limit_multiplier);
    config_.lat_accel_multiplier = declare_parameter<double>("lat_accel_multiplier", config_.lat_accel_multiplier);
    config_.stop_line_buffer = declare_parameter<double>("stop_line_buffer", config_.stop_line_buffer);
    config_.minimum_speed = declare_parameter<double>("minimum_speed", config_.minimum_speed);
    config_.algorithm_evaluation_distance = declare_parameter<double>("algorithm_evaluation_distance", config_.algorithm_evaluation_distance);
    config_.algorithm_evaluation_period = declare_parameter<double>("algorithm_evaluation_period", config_.algorithm_evaluation_period);
    config_.lateral_accel_limit = declare_parameter<double>("vehicle_lateral_accel_limit", config_.lateral_accel_limit);
    config_.vehicle_accel_limit = declare_parameter<double>("vehicle_acceleration_limit", config_.vehicle_accel_limit);
    config_.vehicle_decel_limit = declare_parameter<double>("vehicle_deceleration_limit", config_.vehicle_decel_limit);
    config_.tactical_plugin_service_call_timeout = declare_parameter<int>("tactical_plugin_service_call_timeout", config_.tactical_plugin_service_call_timeout);
    config_.enable_object_avoidance = declare_parameter<bool>("enable_object_avoidance", config_.enable_object_avoidance);
  }
References light_controlled_intersection_tactical_plugin::Config::algorithm_evaluation_distance, light_controlled_intersection_tactical_plugin::Config::algorithm_evaluation_period, light_controlled_intersection_tactical_plugin::Config::back_distance, light_controlled_intersection_tactical_plugin::Config::buffer_ending_downtrack, light_controlled_intersection_tactical_plugin::Config::centerline_sampling_spacing, config_, light_controlled_intersection_tactical_plugin::Config::curvature_moving_average_window_size, light_controlled_intersection_tactical_plugin::Config::curve_resample_step_size, light_controlled_intersection_tactical_plugin::Config::default_downsample_ratio, light_controlled_intersection_tactical_plugin::Config::enable_object_avoidance, light_controlled_intersection_tactical_plugin::Config::lat_accel_multiplier, light_controlled_intersection_tactical_plugin::Config::lateral_accel_limit, light_controlled_intersection_tactical_plugin::Config::minimum_speed, light_controlled_intersection_tactical_plugin::Config::speed_moving_average_window_size, light_controlled_intersection_tactical_plugin::Config::stop_line_buffer, light_controlled_intersection_tactical_plugin::Config::tactical_plugin_service_call_timeout, light_controlled_intersection_tactical_plugin::Config::trajectory_time_length, light_controlled_intersection_tactical_plugin::Config::turn_downsample_ratio, light_controlled_intersection_tactical_plugin::Config::vehicle_accel_limit, light_controlled_intersection_tactical_plugin::Config::vehicle_accel_limit_multiplier, light_controlled_intersection_tactical_plugin::Config::vehicle_decel_limit, and light_controlled_intersection_tactical_plugin::Config::vehicle_decel_limit_multiplier.
Member Function Documentation
get_availability()
bool light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode::get_availability () override virtual
Get the availability status of this plugin based on the current operating environment. Method must be overriden by extending classes.
Returns
This method should return true if the plugin's current understanding of the world means it would be capable of planning or executing its capability.
Implements carma_guidance_plugins::PluginBaseNode.
Definition at line 138 of file light_controlled_intersection_tactical_plugin_node.cpp.
{
    return true;
  }
get_version_id()
std::string light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode::get_version_id () override virtual
Returns the version id of this plugin.
Returns
The version id represented as a string
Implements carma_guidance_plugins::PluginBaseNode.
Definition at line 142 of file light_controlled_intersection_tactical_plugin_node.cpp.
{
    return "v4.0"; // Version ID matches the value set in this package's package.xml
  }
on_configure_plugin()
carma_ros2_utils::CallbackReturn light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode::on_configure_plugin () override virtual
This method should be used to load parameters and will be called on the configure state transition.
Implements carma_guidance_plugins::PluginBaseNode.
Definition at line 87 of file light_controlled_intersection_tactical_plugin_node.cpp.
  {
    RCLCPP_INFO_STREAM(rclcpp::get_logger("light_controlled_intersection_tactical_plugin"), "LightControlledIntersectionTransitPluginNode trying to configure");
    // Reset config
    config_ = Config();
    // Load parameters
    get_parameter<double>("centerline_sampling_spacing", config_.centerline_sampling_spacing);
    get_parameter<double>("trajectory_time_length", config_.trajectory_time_length);
    get_parameter<int>("default_downsample_ratio", config_.default_downsample_ratio);
    get_parameter<int>("turn_downsample_ratio", config_.turn_downsample_ratio);
    get_parameter<double>("curve_resample_step_size", config_.curve_resample_step_size);
    get_parameter<int>("curvature_moving_average_window_size", config_.curvature_moving_average_window_size);
    get_parameter<int>("speed_moving_average_window_size", config_.speed_moving_average_window_size);
    get_parameter<double>("back_distance", config_.back_distance);
    get_parameter<double>("buffer_ending_downtrack", config_.buffer_ending_downtrack);
    get_parameter<double>("vehicle_decel_limit_multiplier", config_.vehicle_decel_limit_multiplier);
    get_parameter<double>("vehicle_accel_limit_multiplier", config_.vehicle_accel_limit_multiplier);
    get_parameter<double>("lat_accel_multiplier", config_.lat_accel_multiplier);
    get_parameter<double>("stop_line_buffer", config_.stop_line_buffer);
    get_parameter<double>("minimum_speed", config_.minimum_speed);
    get_parameter<double>("algorithm_evaluation_distance", config_.algorithm_evaluation_distance);
    get_parameter<double>("algorithm_evaluation_period", config_.algorithm_evaluation_period);
    get_parameter<double>("vehicle_lateral_accel_limit", config_.lateral_accel_limit);
    get_parameter<double>("vehicle_acceleration_limit", config_.vehicle_accel_limit);
    get_parameter<double>("vehicle_deceleration_limit", config_.vehicle_decel_limit);
    get_parameter<int>("tactical_plugin_service_call_timeout", config_.tactical_plugin_service_call_timeout);
    get_parameter<bool>("enable_object_avoidance", config_.enable_object_avoidance);
    // Use the configured multipliers to update the accel limits
    config_.lateral_accel_limit = config_.lateral_accel_limit * config_.lat_accel_multiplier;
    config_.vehicle_accel_limit = config_.vehicle_accel_limit * config_.vehicle_accel_limit_multiplier;
    config_.vehicle_decel_limit = config_.vehicle_decel_limit * config_.vehicle_decel_limit_multiplier;
    // Register runtime parameter update callback
    add_on_set_parameters_callback(std::bind(&LightControlledIntersectionTransitPluginNode::parameter_update_callback, this, std_ph::_1));
    RCLCPP_INFO_STREAM(rclcpp::get_logger("light_controlled_intersection_tactical_plugin"), "Loaded params: " << config_);
    // Initialize worker object
    worker_ = std::make_shared<LightControlledIntersectionTacticalPlugin>(get_world_model(), config_, get_plugin_name(), shared_from_this());
    yield_client_ = create_client<carma_planning_msgs::srv::PlanTrajectory>("yield_plugin/plan_trajectory");
    worker_->set_yield_client(yield_client_);
    RCLCPP_INFO(rclcpp::get_logger("light_controlled_intersection_tactical_plugin"), "Yield Client Set");
    // Return success if everything initialized successfully
    return CallbackReturn::SUCCESS;
  }
References light_controlled_intersection_tactical_plugin::Config::algorithm_evaluation_distance, light_controlled_intersection_tactical_plugin::Config::algorithm_evaluation_period, light_controlled_intersection_tactical_plugin::Config::back_distance, light_controlled_intersection_tactical_plugin::Config::buffer_ending_downtrack, light_controlled_intersection_tactical_plugin::Config::centerline_sampling_spacing, config_, light_controlled_intersection_tactical_plugin::Config::curvature_moving_average_window_size, light_controlled_intersection_tactical_plugin::Config::curve_resample_step_size, light_controlled_intersection_tactical_plugin::Config::default_downsample_ratio, light_controlled_intersection_tactical_plugin::Config::enable_object_avoidance, carma_guidance_plugins::PluginBaseNode::get_plugin_name(), carma_guidance_plugins::PluginBaseNode::get_world_model(), light_controlled_intersection_tactical_plugin::Config::lat_accel_multiplier, light_controlled_intersection_tactical_plugin::Config::lateral_accel_limit, light_controlled_intersection_tactical_plugin::Config::minimum_speed, parameter_update_callback(), light_controlled_intersection_tactical_plugin::Config::speed_moving_average_window_size, light_controlled_intersection_tactical_plugin::Config::stop_line_buffer, light_controlled_intersection_tactical_plugin::Config::tactical_plugin_service_call_timeout, light_controlled_intersection_tactical_plugin::Config::trajectory_time_length, light_controlled_intersection_tactical_plugin::Config::turn_downsample_ratio, light_controlled_intersection_tactical_plugin::Config::vehicle_accel_limit, light_controlled_intersection_tactical_plugin::Config::vehicle_accel_limit_multiplier, light_controlled_intersection_tactical_plugin::Config::vehicle_decel_limit, light_controlled_intersection_tactical_plugin::Config::vehicle_decel_limit_multiplier, worker_, and yield_client_.
parameter_update_callback()
rcl_interfaces::msg::SetParametersResult light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode::parameter_update_callback (const std::vector< rclcpp::Parameter > & parameters)
Callback for dynamic parameter updates.
Definition at line 54 of file light_controlled_intersection_tactical_plugin_node.cpp.
  {
     auto error = update_params<double>(
       {{"centerline_sampling_spacing", config_.centerline_sampling_spacing},
       {"trajectory_time_length", config_.trajectory_time_length},
       {"curve_resample_step_size", config_.curve_resample_step_size},
       {"back_distance", config_.back_distance},
       {"buffer_ending_downtrack", config_.buffer_ending_downtrack},
       {"vehicle_decel_limit_multiplier", config_.vehicle_decel_limit_multiplier},
       {"vehicle_accel_limit_multiplier", config_.vehicle_accel_limit_multiplier},
       {"lat_accel_multiplier", config_.lat_accel_multiplier},
       {"stop_line_buffer", config_.stop_line_buffer},
       {"minimum_speed", config_.minimum_speed},
       {"algorithm_evaluation_distance", config_.algorithm_evaluation_distance},
       {"algorithm_evaluation_period", config_.algorithm_evaluation_period}}, parameters); // Global acceleration limits not allowed to dynamically update
    auto error_2 = update_params<int>(
      {{"default_downsample_ratio", config_.default_downsample_ratio},
      {"turn_downsample_ratio", config_.turn_downsample_ratio},
      {"curvature_moving_average_window_size", config_.curvature_moving_average_window_size},
      {"speed_moving_average_window_size", config_.speed_moving_average_window_size}}, parameters);
    if (worker_)
    {
      worker_->setConfig(config_);
    }
    rcl_interfaces::msg::SetParametersResult result;
    result.successful = !error && !error_2;
    return result;
  }
References light_controlled_intersection_tactical_plugin::Config::algorithm_evaluation_distance, light_controlled_intersection_tactical_plugin::Config::algorithm_evaluation_period, light_controlled_intersection_tactical_plugin::Config::back_distance, light_controlled_intersection_tactical_plugin::Config::buffer_ending_downtrack, light_controlled_intersection_tactical_plugin::Config::centerline_sampling_spacing, config_, light_controlled_intersection_tactical_plugin::Config::curvature_moving_average_window_size, light_controlled_intersection_tactical_plugin::Config::curve_resample_step_size, light_controlled_intersection_tactical_plugin::Config::default_downsample_ratio, light_controlled_intersection_tactical_plugin::Config::lat_accel_multiplier, light_controlled_intersection_tactical_plugin::Config::minimum_speed, light_controlled_intersection_tactical_plugin::Config::speed_moving_average_window_size, light_controlled_intersection_tactical_plugin::Config::stop_line_buffer, light_controlled_intersection_tactical_plugin::Config::trajectory_time_length, light_controlled_intersection_tactical_plugin::Config::turn_downsample_ratio, light_controlled_intersection_tactical_plugin::Config::vehicle_accel_limit_multiplier, light_controlled_intersection_tactical_plugin::Config::vehicle_decel_limit_multiplier, and worker_.
Referenced by on_configure_plugin().
plan_trajectory_callback()
void light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode::plan_trajectory_callback (std::shared_ptr< rmw_request_id_t > srv_header, carma_planning_msgs::srv::PlanTrajectory::Request::SharedPtr req, carma_planning_msgs::srv::PlanTrajectory::Response::SharedPtr resp) override virtual
Extending class provided callback which should return a planned trajectory based on the provided trajectory planning request.
Parameters
srv_header RCL header for services calls. Can usually be ignored by implementers.
req The service request containing the maneuvers to plan trajectories for and current vehicle state
resp The response containing the planned trajectory
Implements carma_guidance_plugins::TacticalPlugin.
Definition at line 146 of file light_controlled_intersection_tactical_plugin_node.cpp.
  {
    worker_->planTrajectoryCB(req, resp);
  }
References worker_.
Member Data Documentation
config_
Config light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode::config_ private
Definition at line 36 of file light_controlled_intersection_tactical_plugin_node.hpp.
Referenced by LightControlledIntersectionTransitPluginNode(), on_configure_plugin(), and parameter_update_callback().
worker_
std::shared_ptr<LightControlledIntersectionTacticalPlugin> light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode::worker_ private
Definition at line 41 of file light_controlled_intersection_tactical_plugin_node.hpp.
Referenced by on_configure_plugin(), parameter_update_callback(), and plan_trajectory_callback().
yield_client_
carma_ros2_utils::ClientPtr<carma_planning_msgs::srv::PlanTrajectory> light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode::yield_client_ private
Definition at line 38 of file light_controlled_intersection_tactical_plugin_node.hpp.
Referenced by on_configure_plugin().
The documentation for this class was generated from the following files:
light_controlled_intersection_tactical_plugin/include/light_controlled_intersection_tactical_plugin/light_controlled_intersection_tactical_plugin_node.hpp
light_controlled_intersection_tactical_plugin/src/light_controlled_intersection_tactical_plugin_node.cpp