Carma-platform: GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator > Class Template Reference
GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator > Class Template Reference
JSON Schema Validator.
#include <schema.h>
Public Types
typedef SchemaDocumentType::SchemaType SchemaType
typedef SchemaDocumentType::PointerType PointerType
typedef SchemaType::EncodingType EncodingType
typedef EncodingType::Ch Ch
Public Member Functions
GenericSchemaValidator (const SchemaDocumentType &schemaDocument, StateAllocator *allocator=0, size_t schemaStackCapacity=kDefaultSchemaStackCapacity, size_t documentStackCapacity=kDefaultDocumentStackCapacity)
Constructor without output handler.
GenericSchemaValidator (const SchemaDocumentType &schemaDocument, OutputHandler &outputHandler, StateAllocator *allocator=0, size_t schemaStackCapacity=kDefaultSchemaStackCapacity, size_t documentStackCapacity=kDefaultDocumentStackCapacity)
Constructor with output handler.
~GenericSchemaValidator ()
Destructor.
void Reset ()
Reset the internal states.
virtual bool IsValid () const
Checks whether the current state is valid.
PointerType GetInvalidSchemaPointer () const
Gets the JSON pointer pointed to the invalid schema.
const Ch * GetInvalidSchemaKeyword () const
Gets the keyword of invalid schema.
PointerType GetInvalidDocumentPointer () const
Gets the JSON pointer pointed to the invalid value.
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned u)
bool Int64 (int64_t i)
bool Uint64 (uint64_t u)
bool Double (double d)
bool RawNumber (const Ch *str, SizeType length, bool copy)
bool String (const Ch *str, SizeType length, bool copy)
bool StartObject ()
bool Key (const Ch *str, SizeType len, bool copy)
bool EndObject (SizeType memberCount)
bool StartArray ()
bool EndArray (SizeType elementCount)
virtual ISchemaValidator * CreateSchemaValidator (const SchemaType &root)
virtual void DestroySchemaValidator (ISchemaValidator *validator)
virtual void * CreateHasher ()
virtual uint64_t GetHashCode (void *hasher)
virtual void DestroryHasher (void *hasher)
virtual void * MallocState (size_t size)
virtual void FreeState (void *p)
Public Member Functions inherited from internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >
virtual ~ISchemaStateFactory ()
virtual ISchemaValidator * CreateSchemaValidator (const SchemaDocumentType::SchemaType &)=0
virtual void DestroySchemaValidator (ISchemaValidator *validator)=0
virtual void * CreateHasher ()=0
virtual uint64_t GetHashCode (void *hasher)=0
virtual void DestroryHasher (void *hasher)=0
virtual void * MallocState (size_t size)=0
virtual void FreeState (void *p)=0
Public Member Functions inherited from internal::ISchemaValidator
virtual ~ISchemaValidator ()
virtual bool IsValid () const =0
Private Types
typedef SchemaType::Context Context
typedef GenericValue< UTF8<>, StateAllocator > HashCodeArray
typedef internal::Hasher< EncodingType, StateAllocator > HasherType
Private Member Functions
GenericSchemaValidator (const SchemaDocumentType &schemaDocument, const SchemaType &root, StateAllocator *allocator=0, size_t schemaStackCapacity=kDefaultSchemaStackCapacity, size_t documentStackCapacity=kDefaultDocumentStackCapacity)
StateAllocator & GetStateAllocator ()
bool BeginValue ()
bool EndValue ()
void AppendToken (const Ch *str, SizeType len)
RAPIDJSON_FORCEINLINE void PushSchema (const SchemaType &schema)
RAPIDJSON_FORCEINLINE void PopSchema ()
const SchemaType & CurrentSchema () const
Context & CurrentContext ()
const Context & CurrentContext () const
Private Attributes
const SchemaDocumentType * schemaDocument_
const SchemaType & root_
StateAllocator * stateAllocator_
StateAllocator * ownStateAllocator_
internal::Stack< StateAllocator > schemaStack_
stack to store the current path of schema (BaseSchemaType *)
internal::Stack< StateAllocator > documentStack_
stack to store the current path of validating document (Ch)
OutputHandler * outputHandler_
bool valid_
Static Private Attributes
static const size_t kDefaultSchemaStackCapacity = 1024
static const size_t kDefaultDocumentStackCapacity = 256
Detailed Description
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
class GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >
JSON Schema Validator.
A SAX style JSON schema validator. It uses a GenericSchemaDocument to validate SAX events. It delegates the incoming SAX events to an output handler. The default output handler does nothing. It can be reused multiple times by calling Reset().
Template Parameters
SchemaDocumentType Type of schema document.
OutputHandler Type of output handler. Default handler does nothing.
StateAllocator Allocator for storing the internal validation states.
Definition at line 1568 of file schema.h.
Member Typedef Documentation
Ch
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef EncodingType::Ch GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Ch
Definition at line 1576 of file schema.h.
Context
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef SchemaType::Context GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Context private
Definition at line 1793 of file schema.h.
EncodingType
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef SchemaType::EncodingType GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EncodingType
Definition at line 1575 of file schema.h.
HashCodeArray
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef GenericValue<UTF8<>, StateAllocator> GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::HashCodeArray private
Definition at line 1794 of file schema.h.
HasherType
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef internal::Hasher<EncodingType, StateAllocator> GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::HasherType private
Definition at line 1795 of file schema.h.
PointerType
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef SchemaDocumentType::PointerType GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PointerType
Definition at line 1574 of file schema.h.
SchemaType
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef SchemaDocumentType::SchemaType GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::SchemaType
Definition at line 1573 of file schema.h.
Constructor & Destructor Documentation
GenericSchemaValidator() [1/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GenericSchemaValidator (const SchemaDocumentType & schemaDocument, StateAllocator * allocator = 0, size_t schemaStackCapacity = kDefaultSchemaStackCapacity, size_t documentStackCapacity = kDefaultDocumentStackCapacity) inline
Constructor without output handler.
Parameters
schemaDocument The schema document to conform to.
allocator Optional allocator for storing internal validation states.
schemaStackCapacity Optional initial capacity of schema path stack.
documentStackCapacity Optional initial capacity of document path stack.
Definition at line 1585 of file schema.h.
        :
        schemaDocument_(&schemaDocument),
        root_(schemaDocument.GetRoot()),
        stateAllocator_(allocator),
        ownStateAllocator_(0),
        schemaStack_(allocator, schemaStackCapacity),
        documentStack_(allocator, documentStackCapacity),
        outputHandler_(0),
        valid_(true)
#if RAPIDJSON_SCHEMA_VERBOSE
        , depth_(0)
#endif
    {
    }
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateSchemaValidator().
GenericSchemaValidator() [2/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GenericSchemaValidator (const SchemaDocumentType & schemaDocument, OutputHandler & outputHandler, StateAllocator * allocator = 0, size_t schemaStackCapacity = kDefaultSchemaStackCapacity, size_t documentStackCapacity = kDefaultDocumentStackCapacity) inline
Constructor with output handler.
Parameters
schemaDocument The schema document to conform to.
allocator Optional allocator for storing internal validation states.
schemaStackCapacity Optional initial capacity of schema path stack.
documentStackCapacity Optional initial capacity of document path stack.
Definition at line 1612 of file schema.h.
        :
        schemaDocument_(&schemaDocument),
        root_(schemaDocument.GetRoot()),
        stateAllocator_(allocator),
        ownStateAllocator_(0),
        schemaStack_(allocator, schemaStackCapacity),
        documentStack_(allocator, documentStackCapacity),
        outputHandler_(&outputHandler),
        valid_(true)
#if RAPIDJSON_SCHEMA_VERBOSE
        , depth_(0)
#endif
    {
    }
~GenericSchemaValidator()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::~GenericSchemaValidator () inline
Destructor.
Definition at line 1634 of file schema.h.
{
        Reset();
        RAPIDJSON_DELETE(ownStateAllocator_);
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::ownStateAllocator_, RAPIDJSON_DELETE, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Reset().
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DestroySchemaValidator().
GenericSchemaValidator() [3/3]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GenericSchemaValidator (const SchemaDocumentType & schemaDocument, const SchemaType & root, StateAllocator * allocator = 0, size_t schemaStackCapacity = kDefaultSchemaStackCapacity, size_t documentStackCapacity = kDefaultDocumentStackCapacity) inline private
Definition at line 1797 of file schema.h.
        :
        schemaDocument_(&schemaDocument),
        root_(root),
        stateAllocator_(allocator),
        ownStateAllocator_(0),
        schemaStack_(allocator, schemaStackCapacity),
        documentStack_(allocator, documentStackCapacity),
        outputHandler_(0),
        valid_(true)
#if RAPIDJSON_SCHEMA_VERBOSE
        , depth_(depth)
#endif
    {
    }
Member Function Documentation
AppendToken()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AppendToken (const Ch * str, SizeType len) inline private
Definition at line 1895 of file schema.h.
{
        documentStack_.template Reserve<Ch>(1 + len * 2); // worst case all characters are escaped as two characters
        *documentStack_.template PushUnsafe<Ch>() = '/';
        for (SizeType i = 0; i < len; i++) {
            if (str[i] == '~') {
                *documentStack_.template PushUnsafe<Ch>() = '~';
                *documentStack_.template PushUnsafe<Ch>() = '0';
            }
            else if (str[i] == '/') {
                *documentStack_.template PushUnsafe<Ch>() = '~';
                *documentStack_.template PushUnsafe<Ch>() = '1';
            }
            else
                *documentStack_.template PushUnsafe<Ch>() = str[i];
        }
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::documentStack_, process_bag::i, and SizeType.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Key().
BeginValue()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BeginValue () inline private
Definition at line 1827 of file schema.h.
                      {
        if (schemaStack_.Empty())
            PushSchema(root_);
        else {
            if (CurrentContext().inArray)
                internal::TokenHelper<internal::Stack<StateAllocator>, Ch>::AppendIndexToken(documentStack_, CurrentContext().arrayElementIndex);
            if (!CurrentSchema().BeginValue(CurrentContext()))
                return false;
            SizeType count = CurrentContext().patternPropertiesSchemaCount;
            const SchemaType** sa = CurrentContext().patternPropertiesSchemas;
            typename Context::PatternValidatorType patternValidatorType = CurrentContext().valuePatternValidatorType;
            bool valueUniqueness = CurrentContext().valueUniqueness;
            RAPIDJSON_ASSERT(CurrentContext().valueSchema);
            PushSchema(*CurrentContext().valueSchema);
            if (count > 0) {
                CurrentContext().objectPatternValidatorType = patternValidatorType;
                ISchemaValidator**& va = CurrentContext().patternPropertiesValidators;
                SizeType& validatorCount = CurrentContext().patternPropertiesValidatorCount;
                va = static_cast<ISchemaValidator**>(MallocState(sizeof(ISchemaValidator*) * count));
                for (SizeType i = 0; i < count; i++)
                    va[validatorCount++] = CreateSchemaValidator(*sa[i]);
            }
            CurrentContext().arrayUniqueness = valueUniqueness;
        }
        return true;
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BeginValue(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateSchemaValidator(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentSchema(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::documentStack_, process_bag::i, GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::MallocState(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PushSchema(), RAPIDJSON_ASSERT, GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::root_, GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaStack_, and SizeType.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BeginValue().
Bool()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Bool (bool b) inline
Definition at line 1705 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Bool,   (CurrentContext(), b), (b)); }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Bool(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), and RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Bool().
CreateHasher()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void * GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateHasher () inline virtual
Implements internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 1770 of file schema.h.
{
        return new (GetStateAllocator().Malloc(sizeof(HasherType))) HasherType(&GetStateAllocator());
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetStateAllocator().
CreateSchemaValidator()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual ISchemaValidator * GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateSchemaValidator (const SchemaType & root) inline virtual
Implements internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 1756 of file schema.h.
{
        return new (GetStateAllocator().Malloc(sizeof(GenericSchemaValidator))) GenericSchemaValidator(*schemaDocument_, root,
#if RAPIDJSON_SCHEMA_VERBOSE
        depth_ + 1,
#endif
        &GetStateAllocator());
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GenericSchemaValidator(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetStateAllocator(), RAPIDJSON_SCHEMA_VERBOSE, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaDocument_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BeginValue().
CurrentContext() [1/2]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> Context & GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext () inline private
Definition at line 1924 of file schema.h.
{ return *schemaStack_.template Top<Context>(); }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaStack_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BeginValue(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Bool(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Double(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndArray(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndObject(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaKeyword(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int64(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Key(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Null(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::RawNumber(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartArray(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartObject(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::String(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint64().
CurrentContext() [2/2]
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const Context & GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext () const inline private
Definition at line 1925 of file schema.h.
{ return *schemaStack_.template Top<Context>(); }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaStack_.
CurrentSchema()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const SchemaType & GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentSchema () const inline private
Definition at line 1923 of file schema.h.
{ return *schemaStack_.template Top<Context>()->schema; }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaStack_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BeginValue(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndArray(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndObject(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaPointer(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Key().
DestroryHasher()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DestroryHasher (void * hasher) inline virtual
Implements internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 1778 of file schema.h.
{
        HasherType* h = static_cast<HasherType*>(hasher);
        h->~HasherType();
        StateAllocator::Free(h);
    }
DestroySchemaValidator()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DestroySchemaValidator (ISchemaValidator * validator) inline virtual
Definition at line 1764 of file schema.h.
{
        GenericSchemaValidator* v = static_cast<GenericSchemaValidator*>(validator);
        v->~GenericSchemaValidator();
        StateAllocator::Free(v);
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::~GenericSchemaValidator(), and guidance_plugin_validator.main::validator.
Double()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Double (double d) inline
Definition at line 1710 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Double, (CurrentContext(), d), (d)); }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Double(), and RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Double().
EndArray()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndArray (SizeType elementCount) inline
Definition at line 1743 of file schema.h.
{
        if (!valid_) return false;
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(EndArray, (elementCount));
        if (!CurrentSchema().EndArray(CurrentContext(), elementCount)) return valid_ = false;
        RAPIDJSON_SCHEMA_HANDLE_END_(EndArray, (elementCount));
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentSchema(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndArray(), RAPIDJSON_SCHEMA_HANDLE_END_, RAPIDJSON_SCHEMA_HANDLE_PARALLEL_, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::valid_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndArray().
EndObject()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndObject (SizeType memberCount) inline
Definition at line 1730 of file schema.h.
{
        if (!valid_) return false;
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(EndObject, (memberCount));
        if (!CurrentSchema().EndObject(CurrentContext(), memberCount)) return valid_ = false;
        RAPIDJSON_SCHEMA_HANDLE_END_(EndObject, (memberCount));
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentSchema(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndObject(), RAPIDJSON_SCHEMA_HANDLE_END_, RAPIDJSON_SCHEMA_HANDLE_PARALLEL_, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::valid_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndObject().
EndValue()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue () inline private
Definition at line 1858 of file schema.h.
                    {
        if (!CurrentSchema().EndValue(CurrentContext()))
            return false;
#if RAPIDJSON_SCHEMA_VERBOSE
        GenericStringBuffer<EncodingType> sb;
        schemaDocument_->GetPointer(&CurrentSchema()).Stringify(sb);
        *documentStack_.template Push<Ch>() = '\0';
        documentStack_.template Pop<Ch>(1);
        internal::PrintValidatorPointers(depth_, sb.GetString(), documentStack_.template Bottom<Ch>());
#endif
        uint64_t h = CurrentContext().arrayUniqueness ? static_cast<HasherType*>(CurrentContext().hasher)->GetHashCode() : 0;
        PopSchema();
        if (!schemaStack_.Empty()) {
            Context& context = CurrentContext();
            if (context.valueUniqueness) {
                HashCodeArray* a = static_cast<HashCodeArray*>(context.arrayElementHashCodes);
                if (!a)
                    CurrentContext().arrayElementHashCodes = a = new (GetStateAllocator().Malloc(sizeof(HashCodeArray))) HashCodeArray(kArrayType);
                for (typename HashCodeArray::ConstValueIterator itr = a->Begin(); itr != a->End(); ++itr)
                    if (itr->GetUint64() == h)
                        RAPIDJSON_INVALID_KEYWORD_RETURN(SchemaType::GetUniqueItemsString());
                a->PushBack(h, GetStateAllocator());
            }
        }
        // Remove the last token of document pointer
        while (!documentStack_.Empty() && *documentStack_.template Pop<Ch>(1) != '/')
            ;
        return true;
    }
References a, GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentSchema(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::documentStack_, GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetHashCode(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetStateAllocator(), GenericStringBuffer< Encoding, Allocator >::GetString(), kArrayType, GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PopSchema(), RAPIDJSON_INVALID_KEYWORD_RETURN, GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaDocument_, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaStack_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue().
FreeState()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::FreeState (void * p) inline virtual
Implements internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 1788 of file schema.h.
{
        StateAllocator::Free(p);
    }
GetHashCode()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual uint64_t GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetHashCode (void * hasher) inline virtual
Implements internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 1774 of file schema.h.
{
        return static_cast<HasherType*>(hasher)->GetHashCode();
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetHashCode().
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetHashCode().
GetInvalidDocumentPointer()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> PointerType GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidDocumentPointer () const inline
Gets the JSON pointer pointed to the invalid value.
Definition at line 1662 of file schema.h.
{
        return documentStack_.Empty() ? PointerType() : PointerType(documentStack_.template Bottom<Ch>(), documentStack_.GetSize() / sizeof(Ch));
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::documentStack_.
GetInvalidSchemaKeyword()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const Ch * GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaKeyword () const inline
Gets the keyword of invalid schema.
Definition at line 1657 of file schema.h.
{
        return schemaStack_.Empty() ? 0 : CurrentContext().invalidKeyword;
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaStack_.
GetInvalidSchemaPointer()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> PointerType GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaPointer () const inline
Gets the JSON pointer pointed to the invalid schema.
Definition at line 1652 of file schema.h.
{
        return schemaStack_.Empty() ? PointerType() : schemaDocument_->GetPointer(&CurrentSchema());
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentSchema(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaDocument_, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaStack_.
GetStateAllocator()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> StateAllocator & GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetStateAllocator () inline private
Definition at line 1821 of file schema.h.
{
        if (!stateAllocator_)
            stateAllocator_ = ownStateAllocator_ = RAPIDJSON_NEW(StateAllocator)();
        return *stateAllocator_;
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::ownStateAllocator_, RAPIDJSON_NEW, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::stateAllocator_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateHasher(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateSchemaValidator(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::MallocState().
Int()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int (int i) inline
Definition at line 1706 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Int,    (CurrentContext(), i), (i)); }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), process_bag::i, GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int(), and RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int().
Int64()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int64 (int64_t i) inline
Definition at line 1708 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Int64,  (CurrentContext(), i), (i)); }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), process_bag::i, GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int64(), and RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int64().
IsValid()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::IsValid () const inline virtual
Checks whether the current state is valid.
Implements internal::ISchemaValidator.
Definition at line 1649 of file schema.h.
{ return valid_; }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::valid_.
Key()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Key (const Ch * str, SizeType len, bool copy) inline
Definition at line 1722 of file schema.h.
{
        if (!valid_) return false;
        AppendToken(str, len);
        if (!CurrentSchema().Key(CurrentContext(), str, len, copy)) return valid_ = false;
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(Key, (str, len, copy));
        return valid_ = !outputHandler_ || outputHandler_->Key(str, len, copy);
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AppendToken(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentSchema(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Key(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::outputHandler_, RAPIDJSON_SCHEMA_HANDLE_PARALLEL_, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::valid_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Key().
MallocState()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void * GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::MallocState (size_t size) inline virtual
Implements internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
Definition at line 1784 of file schema.h.
{
        return GetStateAllocator().Malloc(size);
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetStateAllocator().
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BeginValue().
Null()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Null () inline
Definition at line 1704 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Null,   (CurrentContext()), ()); }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Null(), and RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Null().
PopSchema()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> RAPIDJSON_FORCEINLINE void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PopSchema () inline private
Definition at line 1914 of file schema.h.
{
        Context* c = schemaStack_.template Pop<Context>(1);
        if (HashCodeArray* a = static_cast<HashCodeArray*>(c->arrayElementHashCodes)) {
            a->~HashCodeArray();
            StateAllocator::Free(a);
        }
        c->~Context();
    }
References a, process_traj_logs::c, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaStack_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Reset().
PushSchema()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> RAPIDJSON_FORCEINLINE void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PushSchema (const SchemaType & schema) inline private
Definition at line 1912 of file schema.h.
{ new (schemaStack_.template Push<Context>()) Context(*this, &schema); }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaStack_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BeginValue().
RawNumber()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::RawNumber (const Ch * str, SizeType length, bool copy) inline
Definition at line 1711 of file schema.h.
                                    { RAPIDJSON_SCHEMA_HANDLE_VALUE_(String, (CurrentContext(), str, length, copy), (str, length, copy)); }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), RAPIDJSON_SCHEMA_HANDLE_VALUE_, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::String().
Reset()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Reset () inline
Reset the internal states.
Definition at line 1640 of file schema.h.
                 {
        while (!schemaStack_.Empty())
            PopSchema();
        documentStack_.Clear();
        valid_ = true;
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::documentStack_, GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PopSchema(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaStack_, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::valid_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::~GenericSchemaValidator().
StartArray()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartArray () inline
Definition at line 1737 of file schema.h.
                      {
        RAPIDJSON_SCHEMA_HANDLE_BEGIN_(StartArray, (CurrentContext()));
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(StartArray, ());
        return valid_ = !outputHandler_ || outputHandler_->StartArray();
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::outputHandler_, RAPIDJSON_SCHEMA_HANDLE_BEGIN_, RAPIDJSON_SCHEMA_HANDLE_PARALLEL_, GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartArray(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::valid_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartArray().
StartObject()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartObject () inline
Definition at line 1716 of file schema.h.
                       {
        RAPIDJSON_SCHEMA_HANDLE_BEGIN_(StartObject, (CurrentContext()));
        RAPIDJSON_SCHEMA_HANDLE_PARALLEL_(StartObject, ());
        return valid_ = !outputHandler_ || outputHandler_->StartObject();
    }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::outputHandler_, RAPIDJSON_SCHEMA_HANDLE_BEGIN_, RAPIDJSON_SCHEMA_HANDLE_PARALLEL_, GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartObject(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::valid_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartObject().
String()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::String (const Ch * str, SizeType length, bool copy) inline
Definition at line 1713 of file schema.h.
                                    { RAPIDJSON_SCHEMA_HANDLE_VALUE_(String, (CurrentContext(), str, length, copy), (str, length, copy)); }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), RAPIDJSON_SCHEMA_HANDLE_VALUE_, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::String().
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::RawNumber(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::String().
Uint()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint (unsigned u) inline
Definition at line 1707 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Uint,   (CurrentContext(), u), (u)); }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), RAPIDJSON_SCHEMA_HANDLE_VALUE_, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint().
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint().
Uint64()
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint64 (uint64_t u) inline
Definition at line 1709 of file schema.h.
{ RAPIDJSON_SCHEMA_HANDLE_VALUE_(Uint64, (CurrentContext(), u), (u)); }
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), RAPIDJSON_SCHEMA_HANDLE_VALUE_, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint64().
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint64().
Member Data Documentation
documentStack_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> internal::Stack<StateAllocator> GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::documentStack_ private
stack to store the current path of validating document (Ch)
Definition at line 1934 of file schema.h.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AppendToken(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BeginValue(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidDocumentPointer(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Reset().
kDefaultDocumentStackCapacity
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const size_t GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::kDefaultDocumentStackCapacity = 256 static private
Definition at line 1928 of file schema.h.
kDefaultSchemaStackCapacity
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const size_t GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::kDefaultSchemaStackCapacity = 1024 static private
Definition at line 1927 of file schema.h.
outputHandler_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> OutputHandler* GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::outputHandler_ private
Definition at line 1935 of file schema.h.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Key(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartArray(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartObject().
ownStateAllocator_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> StateAllocator* GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::ownStateAllocator_ private
Definition at line 1932 of file schema.h.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::~GenericSchemaValidator(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetStateAllocator().
root_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const SchemaType& GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::root_ private
Definition at line 1930 of file schema.h.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BeginValue().
schemaDocument_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const SchemaDocumentType* GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaDocument_ private
Definition at line 1929 of file schema.h.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateSchemaValidator(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaPointer().
schemaStack_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> internal::Stack<StateAllocator> GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::schemaStack_ private
stack to store the current path of schema (BaseSchemaType *)
Definition at line 1933 of file schema.h.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BeginValue(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentContext(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CurrentSchema(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndValue(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaKeyword(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaPointer(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PopSchema(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PushSchema(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Reset().
stateAllocator_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> StateAllocator* GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::stateAllocator_ private
Definition at line 1931 of file schema.h.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetStateAllocator().
valid_
template<typename SchemaDocumentType , typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::valid_ private
Definition at line 1936 of file schema.h.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndArray(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndObject(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::IsValid(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Key(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Reset(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartArray(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartObject().
The documentation for this class was generated from the following files:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/fwd.h
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/schema.h