Carma-platform: carma_wm_ctrl::GeofenceScheduler Class Reference
carma_wm_ctrl::GeofenceScheduler Class Reference
A GeofenceScheduler is responsable for notifying the user when a geofence is active or inactive according to its schedule.
#include <GeofenceScheduler.hpp>
Public Member Functions
GeofenceScheduler (std::shared_ptr< TimerFactory > timerFactory)
Constructor which takes in a TimerFactory. Timers from this factory will be used to generate the triggers for goefence activity.
void addGeofence (std::shared_ptr< Geofence > gf_ptr)
Add a geofence to the scheduler. This will cause it to trigger an event when it becomes active or goes inactive according to its schedule.
void onGeofenceActive (std::function< void(std::shared_ptr< Geofence >)> active_callback)
Method which allows the user to set a callback which will be triggered when a geofence becomes active.
void onGeofenceInactive (std::function< void(std::shared_ptr< Geofence >)> inactive_callback)
Method which allows the user to set a callback which will be triggered when a geofence becomes in-active.
void clearTimers ()
Clears the expired timers from the memory of this scheduler.
rcl_clock_type_t getClockType ()
Get the clock type of the clock being created by the timer factory.
rclcpp::Time now ()
Get current time used by scheduler.
Private Types
using Timer = carma_ros2_utils::timers::Timer
using TimerFactory = carma_ros2_utils::timers::TimerFactory
using ROSTimerFactory = carma_ros2_utils::timers::ROSTimerFactory
using TimerPtr = std::unique_ptr< Timer >
Private Member Functions
uint32_t nextId ()
Generates the next id to be used for a timer.
void startGeofenceCallback (std::shared_ptr< Geofence > gf_ptr, const unsigned int schedule_id, const int32_t timer_id)
The callback which is triggered when a geofence becomes active This will call the user set active_callback set from the onGeofenceActive function.
void endGeofenceCallback (std::shared_ptr< Geofence > gf_ptr, const unsigned int schedule_id, const int32_t timer_id)
The callback which is triggered when a geofence becomes in-active This will call the user set inactive_callback set from the onGeofenceInactive function.
Private Attributes
std::mutex mutex_
std::shared_ptr< TimerFactory > timerFactory_
std::unordered_map< uint32_t, std::pair< TimerPtr, bool > > timers_
std::unique_ptr< Timer > deletion_timer_
std::function< void(std::shared_ptr< Geofence >)> active_callback_
std::function< void(std::shared_ptr< Geofence >)> inactive_callback_
uint32_t next_id_ = 0
rcl_clock_type_t clock_type_ = RCL_SYSTEM_TIME
Detailed Description
A GeofenceScheduler is responsable for notifying the user when a geofence is active or inactive according to its schedule.
Definition at line 34 of file GeofenceScheduler.hpp.
Member Typedef Documentation
ROSTimerFactory
using carma_wm_ctrl::GeofenceScheduler::ROSTimerFactory = carma_ros2_utils::timers::ROSTimerFactory private
Definition at line 38 of file GeofenceScheduler.hpp.
Timer
using carma_wm_ctrl::GeofenceScheduler::Timer = carma_ros2_utils::timers::Timer private
Definition at line 36 of file GeofenceScheduler.hpp.
TimerFactory
using carma_wm_ctrl::GeofenceScheduler::TimerFactory = carma_ros2_utils::timers::TimerFactory private
Definition at line 37 of file GeofenceScheduler.hpp.
TimerPtr
using carma_wm_ctrl::GeofenceScheduler::TimerPtr = std::unique_ptr<Timer> private
Definition at line 39 of file GeofenceScheduler.hpp.
Constructor & Destructor Documentation
GeofenceScheduler()
carma_wm_ctrl::GeofenceScheduler::GeofenceScheduler (std::shared_ptr< TimerFactory > timerFactory)
Constructor which takes in a TimerFactory. Timers from this factory will be used to generate the triggers for goefence activity.
Parameters
timerFactory A pointer to a TimerFactory which can be used to generate timers for geofence triggers.
Definition at line 23 of file GeofenceScheduler.cpp.
  : timerFactory_(timerFactory)
{
  // Create repeating loop to clear geofence timers which are no longer needed
  deletion_timer_ =
      timerFactory_->buildTimer(nextId(), rclcpp::Duration(1), std::bind(&GeofenceScheduler::clearTimers, this));
  clock_type_ = timerFactory_->now().get_clock_type();
}
References clearTimers(), clock_type_, deletion_timer_, nextId(), and timerFactory_.
Member Function Documentation
addGeofence()
void carma_wm_ctrl::GeofenceScheduler::addGeofence (std::shared_ptr< Geofence > gf_ptr)
Add a geofence to the scheduler. This will cause it to trigger an event when it becomes active or goes inactive according to its schedule.
Parameters
geofence The geofence to be added
Definition at line 70 of file GeofenceScheduler.cpp.
{
  std::lock_guard<std::mutex> guard(mutex_);
  RCLCPP_INFO_STREAM(rclcpp::get_logger("carma_wm_ctrl"), "Attempting to add Geofence with Id: " << gf_ptr->id_);
  // Create timer for next start time
  for (size_t schedule_idx = 0; schedule_idx < gf_ptr->schedules.size(); schedule_idx++)
  {
    // resolve clock type
    auto interval_info = gf_ptr->schedules[schedule_idx].getNextInterval(timerFactory_->now());
    rclcpp::Time startTime = interval_info.second;
    if (!interval_info.first && startTime == rclcpp::Time(0, 0, clock_type_))
    {
      RCLCPP_WARN_STREAM(rclcpp::get_logger("carma_wm_ctrl"),
          "Failed to add geofence as its schedule did not contain an active or upcoming control period. GF Id: "
          << gf_ptr->id_);
      return;
    }
    // If this geofence is currently active set the start time to now
    if (interval_info.first)
    {
      startTime = timerFactory_->now();
    }
    int32_t timer_id = nextId();
    rclcpp::Duration control_duration = rclcpp::Duration(std::max((startTime - timerFactory_->now()).seconds() * 1e9, 0.0)); //guard for negative value
    // Build timer to trigger when this geofence becomes active
    TimerPtr timer = timerFactory_->buildTimer(
        timer_id, control_duration,
        std::bind(&GeofenceScheduler::startGeofenceCallback, this, gf_ptr, schedule_idx, timer_id), true, true);
    timers_[timer_id] = std::make_pair(std::move(timer), false);  // Add start timer to map by Id
  }
}
References clock_type_, mutex_, nextId(), startGeofenceCallback(), timerFactory_, and timers_.
Referenced by carma_wm_ctrl::WMBroadcaster::scheduleGeofence().
clearTimers()
void carma_wm_ctrl::GeofenceScheduler::clearTimers ()
Clears the expired timers from the memory of this scheduler.
Definition at line 48 of file GeofenceScheduler.cpp.
{
  std::lock_guard<std::mutex> guard(mutex_);
  auto it = timers_.begin();
  // Erase all expired timers_ using iterators to ensure operation is safe
  while (it != timers_.end())
  {
    // Check if timer is marked for deletion
    if (it->second.second)
    {
      // erase() function returns the iterator of the next
      // to last deleted element.
      it = timers_.erase(it);
    }
    else
    {
      it++;
    }
  }
}
References mutex_, and timers_.
Referenced by GeofenceScheduler().
endGeofenceCallback()
void carma_wm_ctrl::GeofenceScheduler::endGeofenceCallback (std::shared_ptr< Geofence > gf_ptr, const unsigned int schedule_id, const int32_t timer_id) private
The callback which is triggered when a geofence becomes in-active This will call the user set inactive_callback set from the onGeofenceInactive function.
Parameters
event The record of the timer event causing this to trigger
gf The geofence which is being un-activated
schedule_id index number of the schedule being used corresponding to this geofence
timer_id The id of the timer which caused this callback to occur
Definition at line 132 of file GeofenceScheduler.cpp.
{
  std::lock_guard<std::mutex> guard(mutex_);
  RCLCPP_INFO_STREAM(rclcpp::get_logger("carma_wm_ctrl"), "Deactivating Geofence with Id: " << gf_ptr->id_);
  inactive_callback_(gf_ptr);
  timers_[timer_id].second = true;  // Mark timer for deletion
  // Determine if a new timer is needed for this geofence
  auto interval_info = gf_ptr->schedules[schedule_id].getNextInterval(timerFactory_->now());
  rclcpp::Time startTime = interval_info.second;
  // If this geofence should currently be active set the start time to now
  if (interval_info.first)
  {
    startTime = timerFactory_->now();
  }
  if (!interval_info.first && startTime == rclcpp::Time(0, 0, clock_type_))
  {
    // No more active periods for this geofence so return
    return;
  }
  // Build timer to trigger when this geofence becomes active
  int32_t start_timer_id = nextId();
  rclcpp::Duration control_duration = rclcpp::Duration(std::max((startTime - timerFactory_->now()).seconds() * 1e9, 0.0)); //guard for negative value
  TimerPtr timer = timerFactory_->buildTimer(
      start_timer_id, control_duration,
      std::bind(&GeofenceScheduler::startGeofenceCallback, this, gf_ptr, schedule_id, start_timer_id), true, true);
  timers_[start_timer_id] = std::make_pair(std::move(timer), false);  // Add start timer to map by Id
}
References clock_type_, inactive_callback_, mutex_, nextId(), startGeofenceCallback(), timerFactory_, and timers_.
Referenced by startGeofenceCallback().
getClockType()
rcl_clock_type_t carma_wm_ctrl::GeofenceScheduler::getClockType ()
Get the clock type of the clock being created by the timer factory.
Definition at line 43 of file GeofenceScheduler.cpp.
{
  return clock_type_;
}
References clock_type_.
Referenced by carma_wm_ctrl::WMBroadcaster::addScheduleFromMsg(), and carma_wm_ctrl::WMBroadcaster::controlRequestFromRoute().
nextId()
uint32_t carma_wm_ctrl::GeofenceScheduler::nextId () private
Generates the next id to be used for a timer.
Returns
The next available timer id
Definition at line 37 of file GeofenceScheduler.cpp.
{
  next_id_++;
  return next_id_;
}
References next_id_.
Referenced by GeofenceScheduler(), addGeofence(), endGeofenceCallback(), and startGeofenceCallback().
now()
rclcpp::Time carma_wm_ctrl::GeofenceScheduler::now ()
Get current time used by scheduler.
Definition at line 32 of file GeofenceScheduler.cpp.
{
  return timerFactory_->now();
}
References timerFactory_.
Referenced by carma_wm_ctrl::WMBroadcaster::pubTCMACK().
onGeofenceActive()
void carma_wm_ctrl::GeofenceScheduler::onGeofenceActive (std::function< void(std::shared_ptr< Geofence >)> active_callback)
Method which allows the user to set a callback which will be triggered when a geofence becomes active.
Parameters
active_callback The callback which will be triggered
Definition at line 169 of file GeofenceScheduler.cpp.
{
  std::lock_guard<std::mutex> guard(mutex_);
  active_callback_ = active_callback;
}
References active_callback_, and mutex_.
Referenced by carma_wm_ctrl::WMBroadcaster::WMBroadcaster().
onGeofenceInactive()
void carma_wm_ctrl::GeofenceScheduler::onGeofenceInactive (std::function< void(std::shared_ptr< Geofence >)> inactive_callback)
Method which allows the user to set a callback which will be triggered when a geofence becomes in-active.
Parameters
inactive_callback The callback which will be triggered
Definition at line 175 of file GeofenceScheduler.cpp.
{
  std::lock_guard<std::mutex> guard(mutex_);
  inactive_callback_ = inactive_callback;
}
References inactive_callback_, and mutex_.
Referenced by carma_wm_ctrl::WMBroadcaster::WMBroadcaster().
startGeofenceCallback()
void carma_wm_ctrl::GeofenceScheduler::startGeofenceCallback (std::shared_ptr< Geofence > gf_ptr, const unsigned int schedule_id, const int32_t timer_id) private
The callback which is triggered when a geofence becomes active This will call the user set active_callback set from the onGeofenceActive function.
Parameters
event The record of the timer event causing this to trigger
gf The geofence which is being activated
schedule_id index number of the schedule being used corresponding to this geofence
timer_id The id of the timer which caused this callback to occur
Definition at line 110 of file GeofenceScheduler.cpp.
{
  std::lock_guard<std::mutex> guard(mutex_);
  rclcpp::Time endTime = timerFactory_->now() + gf_ptr->schedules[schedule_id].control_span_;
  RCLCPP_INFO_STREAM(rclcpp::get_logger("carma_wm_ctrl"), "Activating Geofence with Id: " << gf_ptr->id_ << ", which will end at:" << endTime.seconds());
  active_callback_(gf_ptr);
  // Build timer to trigger when this geofence becomes inactive
  int32_t ending_timer_id = nextId();
  rclcpp::Duration control_duration = rclcpp::Duration(std::max((endTime - timerFactory_->now()).seconds() * 1e9, 0.0)); //guard for negative value
  TimerPtr timer = timerFactory_->buildTimer(
      ending_timer_id, control_duration,
      std::bind(&GeofenceScheduler::endGeofenceCallback, this, gf_ptr, schedule_id, ending_timer_id), true, true);
  timers_[ending_timer_id] = std::make_pair(std::move(timer), false);  // Add end timer to map by Id
  timers_[timer_id].second = true;  // Mark start timer for deletion
}
References active_callback_, endGeofenceCallback(), mutex_, nextId(), timerFactory_, and timers_.
Referenced by addGeofence(), and endGeofenceCallback().
Member Data Documentation
active_callback_
std::function<void(std::shared_ptr<Geofence>)> carma_wm_ctrl::GeofenceScheduler::active_callback_ private
Definition at line 45 of file GeofenceScheduler.hpp.
Referenced by onGeofenceActive(), and startGeofenceCallback().
clock_type_
rcl_clock_type_t carma_wm_ctrl::GeofenceScheduler::clock_type_ = RCL_SYSTEM_TIME private
Definition at line 48 of file GeofenceScheduler.hpp.
Referenced by GeofenceScheduler(), addGeofence(), endGeofenceCallback(), and getClockType().
deletion_timer_
std::unique_ptr<Timer> carma_wm_ctrl::GeofenceScheduler::deletion_timer_ private
Definition at line 44 of file GeofenceScheduler.hpp.
Referenced by GeofenceScheduler().
inactive_callback_
std::function<void(std::shared_ptr<Geofence>)> carma_wm_ctrl::GeofenceScheduler::inactive_callback_ private
Definition at line 46 of file GeofenceScheduler.hpp.
Referenced by endGeofenceCallback(), and onGeofenceInactive().
mutex_
std::mutex carma_wm_ctrl::GeofenceScheduler::mutex_ private
Definition at line 41 of file GeofenceScheduler.hpp.
Referenced by addGeofence(), clearTimers(), endGeofenceCallback(), onGeofenceActive(), onGeofenceInactive(), and startGeofenceCallback().
next_id_
uint32_t carma_wm_ctrl::GeofenceScheduler::next_id_ = 0 private
Definition at line 47 of file GeofenceScheduler.hpp.
Referenced by nextId().
timerFactory_
std::shared_ptr<TimerFactory> carma_wm_ctrl::GeofenceScheduler::timerFactory_ private
Definition at line 42 of file GeofenceScheduler.hpp.
Referenced by GeofenceScheduler(), addGeofence(), endGeofenceCallback(), now(), and startGeofenceCallback().
timers_
std::unordered_map<uint32_t, std::pair<TimerPtr, bool> > carma_wm_ctrl::GeofenceScheduler::timers_ private
Definition at line 43 of file GeofenceScheduler.hpp.
Referenced by addGeofence(), clearTimers(), endGeofenceCallback(), and startGeofenceCallback().
The documentation for this class was generated from the following files:
carma_wm_ctrl/include/carma_wm_ctrl/GeofenceScheduler.hpp
carma_wm_ctrl/src/GeofenceScheduler.cpp