Carma-platform: internal::Double Class Reference
internal::Double Class Reference
#include <ieee754.h>
Public Member Functions
Double ()
Double (double d)
Double (uint64_t u)
double Value () const
uint64_t Uint64Value () const
double NextPositiveDouble () const
bool Sign () const
uint64_t Significand () const
int Exponent () const
bool IsNan () const
bool IsInf () const
bool IsNanOrInf () const
bool IsNormal () const
bool IsZero () const
uint64_t IntegerSignificand () const
int IntegerExponent () const
uint64_t ToBias () const
Static Public Member Functions
static int EffectiveSignificandSize (int order)
Private Attributes
union {
double d_
uint64_t u_
};
Static Private Attributes
static const int kSignificandSize = 52
static const int kExponentBias = 0x3FF
static const int kDenormalExponent = 1 - kExponentBias
static const uint64_t kSignMask = RAPIDJSON_UINT64_C2(0x80000000, 0x00000000)
static const uint64_t kExponentMask = RAPIDJSON_UINT64_C2(0x7FF00000, 0x00000000)
static const uint64_t kSignificandMask = RAPIDJSON_UINT64_C2(0x000FFFFF, 0xFFFFFFFF)
static const uint64_t kHiddenBit = RAPIDJSON_UINT64_C2(0x00100000, 0x00000000)
Detailed Description
Definition at line 23 of file ieee754.h.
Constructor & Destructor Documentation
Double() [1/3]
internal::Double::Double () inline
Definition at line 25 of file ieee754.h.
{}
Referenced by NextPositiveDouble().
Double() [2/3]
internal::Double::Double (double d) inline
Definition at line 26 of file ieee754.h.
: d_(d) {}
Double() [3/3]
internal::Double::Double (uint64_t u) inline
Definition at line 27 of file ieee754.h.
: u_(u) {}
Member Function Documentation
EffectiveSignificandSize()
static int internal::Double::EffectiveSignificandSize (int order) inline static
Definition at line 51 of file ieee754.h.
{
        if (order >= -1021)
            return 53;
        else if (order <= -1074)
            return 0;
        else
            return order + 1074;
    }
Referenced by internal::StrtodDiyFp().
Exponent()
int internal::Double::Exponent () const inline
Definition at line 39 of file ieee754.h.
{ return static_cast<int>(((u_ & kExponentMask) >> kSignificandSize) - kExponentBias); }
References kExponentBias, kExponentMask, kSignificandSize, and u_.
Referenced by IntegerExponent().
IntegerExponent()
int internal::Double::IntegerExponent () const inline
Definition at line 48 of file ieee754.h.
{ return (IsNormal() ? Exponent() : kDenormalExponent) - kSignificandSize; }
References Exponent(), IsNormal(), kDenormalExponent, and kSignificandSize.
Referenced by internal::CheckWithinHalfULP().
IntegerSignificand()
uint64_t internal::Double::IntegerSignificand () const inline
Definition at line 47 of file ieee754.h.
{ return IsNormal() ? Significand() | kHiddenBit : Significand(); }
References IsNormal(), kHiddenBit, and Significand().
Referenced by internal::CheckWithinHalfULP().
IsInf()
bool internal::Double::IsInf () const inline
Definition at line 42 of file ieee754.h.
{ return (u_ & kExponentMask) == kExponentMask && Significand() == 0; }
References kExponentMask, Significand(), and u_.
IsNan()
bool internal::Double::IsNan () const inline
Definition at line 41 of file ieee754.h.
{ return (u_ & kExponentMask) == kExponentMask && Significand() != 0; }
References kExponentMask, Significand(), and u_.
IsNanOrInf()
bool internal::Double::IsNanOrInf () const inline
Definition at line 43 of file ieee754.h.
{ return (u_ & kExponentMask) == kExponentMask; }
References kExponentMask, and u_.
IsNormal()
bool internal::Double::IsNormal () const inline
Definition at line 44 of file ieee754.h.
{ return (u_ & kExponentMask) != 0 || Significand() == 0; }
References kExponentMask, Significand(), and u_.
Referenced by IntegerExponent(), and IntegerSignificand().
IsZero()
bool internal::Double::IsZero () const inline
Definition at line 45 of file ieee754.h.
{ return (u_ & (kExponentMask | kSignificandMask)) == 0; }
References kExponentMask, kSignificandMask, and u_.
Referenced by internal::dtoa().
NextPositiveDouble()
double internal::Double::NextPositiveDouble () const inline
Definition at line 32 of file ieee754.h.
{
        RAPIDJSON_ASSERT(!Sign());
        return Double(u_ + 1).Value();
    }
References Double(), RAPIDJSON_ASSERT, Sign(), and u_.
Sign()
bool internal::Double::Sign () const inline
Definition at line 37 of file ieee754.h.
{ return (u_ & kSignMask) != 0; }
References kSignMask, and u_.
Referenced by internal::dtoa(), and NextPositiveDouble().
Significand()
uint64_t internal::Double::Significand () const inline
Definition at line 38 of file ieee754.h.
{ return u_ & kSignificandMask; }
References kSignificandMask, and u_.
Referenced by IntegerSignificand(), IsInf(), IsNan(), and IsNormal().
ToBias()
uint64_t internal::Double::ToBias () const inline
Definition at line 49 of file ieee754.h.
{ return (u_ & kSignMask) ? ~u_ + 1 : u_ | kSignMask; }
References kSignMask, and u_.
Uint64Value()
uint64_t internal::Double::Uint64Value () const inline
Definition at line 30 of file ieee754.h.
{ return u_; }
References u_.
Value()
double internal::Double::Value () const inline
Definition at line 29 of file ieee754.h.
{ return d_; }
References d_.
Member Data Documentation
union { ... } internal::Double::@8
d_
double internal::Double::d_
Definition at line 70 of file ieee754.h.
Referenced by Value().
kDenormalExponent
const int internal::Double::kDenormalExponent = 1 - kExponentBias static private
Definition at line 63 of file ieee754.h.
Referenced by IntegerExponent().
kExponentBias
const int internal::Double::kExponentBias = 0x3FF static private
Definition at line 62 of file ieee754.h.
Referenced by Exponent().
kExponentMask
const uint64_t internal::Double::kExponentMask = RAPIDJSON_UINT64_C2(0x7FF00000, 0x00000000) static private
Definition at line 65 of file ieee754.h.
Referenced by Exponent(), IsInf(), IsNan(), IsNanOrInf(), IsNormal(), and IsZero().
kHiddenBit
const uint64_t internal::Double::kHiddenBit = RAPIDJSON_UINT64_C2(0x00100000, 0x00000000) static private
Definition at line 67 of file ieee754.h.
Referenced by IntegerSignificand().
kSignificandMask
const uint64_t internal::Double::kSignificandMask = RAPIDJSON_UINT64_C2(0x000FFFFF, 0xFFFFFFFF) static private
Definition at line 66 of file ieee754.h.
Referenced by IsZero(), and Significand().
kSignificandSize
const int internal::Double::kSignificandSize = 52 static private
Definition at line 61 of file ieee754.h.
Referenced by Exponent(), and IntegerExponent().
kSignMask
const uint64_t internal::Double::kSignMask = RAPIDJSON_UINT64_C2(0x80000000, 0x00000000) static private
Definition at line 64 of file ieee754.h.
Referenced by Sign(), and ToBias().
u_
uint64_t internal::Double::u_
Definition at line 71 of file ieee754.h.
Referenced by Exponent(), IsInf(), IsNan(), IsNanOrInf(), IsNormal(), IsZero(), NextPositiveDouble(), Sign(), Significand(), ToBias(), and Uint64Value().
The documentation for this class was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/internal/ieee754.h