Carma-platform: internal::Hasher< Encoding, Allocator > Class Template Reference
internal::Hasher< Encoding, Allocator > Class Template Reference
#include <schema.h>
Classes
struct Number
Public Types
typedef Encoding::Ch Ch
Public Member Functions
Hasher (Allocator *allocator=0, size_t stackCapacity=kDefaultSize)
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned u)
bool Int64 (int64_t i)
bool Uint64 (uint64_t u)
bool Double (double d)
bool RawNumber (const Ch *str, SizeType len, bool)
bool String (const Ch *str, SizeType len, bool)
bool StartObject ()
bool Key (const Ch *str, SizeType len, bool copy)
bool EndObject (SizeType memberCount)
bool StartArray ()
bool EndArray (SizeType elementCount)
bool IsValid () const
uint64_t GetHashCode () const
Private Member Functions
bool WriteType (Type type)
bool WriteNumber (const Number &n)
bool WriteBuffer (Type type, const void *data, size_t len)
Static Private Member Functions
static uint64_t Hash (uint64_t h, uint64_t d)
Private Attributes
Stack< Allocator > stack_
Static Private Attributes
static const size_t kDefaultSize = 256
Detailed Description
template<typename Encoding, typename Allocator>
class internal::Hasher< Encoding, Allocator >
Definition at line 165 of file schema.h.
Member Typedef Documentation
Ch
template<typename Encoding , typename Allocator > typedef Encoding::Ch internal::Hasher< Encoding, Allocator >::Ch
Definition at line 167 of file schema.h.
Constructor & Destructor Documentation
Hasher()
template<typename Encoding , typename Allocator > internal::Hasher< Encoding, Allocator >::Hasher (Allocator * allocator = 0, size_t stackCapacity = kDefaultSize) inline
Definition at line 169 of file schema.h.
: stack_(allocator, stackCapacity) {}
Member Function Documentation
Bool()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::Bool (bool b) inline
Definition at line 172 of file schema.h.
{ return WriteType(b ? kTrueType : kFalseType); }
References kFalseType, kTrueType, and internal::Hasher< Encoding, Allocator >::WriteType().
Double()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::Double (double d) inline
Definition at line 177 of file schema.h.
{
        Number n;
        if (d < 0) n.u.i = static_cast<int64_t>(d);
        else       n.u.u = static_cast<uint64_t>(d);
        n.d = d;
        return WriteNumber(n);
    }
References internal::Hasher< Encoding, Allocator >::Number::d, internal::Hasher< Encoding, Allocator >::Number::U::i, internal::Hasher< Encoding, Allocator >::Number::U::u, internal::Hasher< Encoding, Allocator >::Number::u, and internal::Hasher< Encoding, Allocator >::WriteNumber().
EndArray()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::EndArray (SizeType elementCount) inline
Definition at line 207 of file schema.h.
{
        uint64_t h = Hash(0, kArrayType);
        uint64_t* e = stack_.template Pop<uint64_t>(elementCount);
        for (SizeType i = 0; i < elementCount; i++)
            h = Hash(h, e[i]); // Use hash to achieve element order sensitive
        *stack_.template Push<uint64_t>() = h;
        return true;
    }
References internal::Hasher< Encoding, Allocator >::Hash(), process_bag::i, kArrayType, SizeType, and internal::Hasher< Encoding, Allocator >::stack_.
EndObject()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::EndObject (SizeType memberCount) inline
Definition at line 197 of file schema.h.
{
        uint64_t h = Hash(0, kObjectType);
        uint64_t* kv = stack_.template Pop<uint64_t>(memberCount * 2);
        for (SizeType i = 0; i < memberCount; i++)
            h ^= Hash(kv[i * 2], kv[i * 2 + 1]);  // Use xor to achieve member order insensitive
        *stack_.template Push<uint64_t>() = h;
        return true;
    }
References internal::Hasher< Encoding, Allocator >::Hash(), process_bag::i, kObjectType, SizeType, and internal::Hasher< Encoding, Allocator >::stack_.
GetHashCode()
template<typename Encoding , typename Allocator > uint64_t internal::Hasher< Encoding, Allocator >::GetHashCode () const inline
Definition at line 218 of file schema.h.
{
        RAPIDJSON_ASSERT(IsValid());
        return *stack_.template Top<uint64_t>();
    }
References internal::Hasher< Encoding, Allocator >::IsValid(), RAPIDJSON_ASSERT, and internal::Hasher< Encoding, Allocator >::stack_.
Hash()
template<typename Encoding , typename Allocator > static uint64_t internal::Hasher< Encoding, Allocator >::Hash (uint64_t h, uint64_t d) inline static private
Definition at line 247 of file schema.h.
{
        static const uint64_t kPrime = RAPIDJSON_UINT64_C2(0x00000100, 0x000001b3);
        h ^= d;
        h *= kPrime;
        return h;
    }
References RAPIDJSON_UINT64_C2.
Referenced by internal::Hasher< Encoding, Allocator >::EndArray(), internal::Hasher< Encoding, Allocator >::EndObject(), and internal::Hasher< Encoding, Allocator >::WriteBuffer().
Int()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::Int (int i) inline
Definition at line 173 of file schema.h.
{ Number n; n.u.i = i; n.d = static_cast<double>(i); return WriteNumber(n); }
References internal::Hasher< Encoding, Allocator >::Number::d, process_bag::i, internal::Hasher< Encoding, Allocator >::Number::U::i, internal::Hasher< Encoding, Allocator >::Number::u, and internal::Hasher< Encoding, Allocator >::WriteNumber().
Int64()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::Int64 (int64_t i) inline
Definition at line 175 of file schema.h.
{ Number n; n.u.i = i; n.d = static_cast<double>(i); return WriteNumber(n); }
References internal::Hasher< Encoding, Allocator >::Number::d, process_bag::i, internal::Hasher< Encoding, Allocator >::Number::U::i, internal::Hasher< Encoding, Allocator >::Number::u, and internal::Hasher< Encoding, Allocator >::WriteNumber().
IsValid()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::IsValid () const inline
Definition at line 216 of file schema.h.
{ return stack_.GetSize() == sizeof(uint64_t); }
References internal::Hasher< Encoding, Allocator >::stack_.
Referenced by internal::Hasher< Encoding, Allocator >::GetHashCode().
Key()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::Key (const Ch * str, SizeType len, bool copy) inline
Definition at line 196 of file schema.h.
{ return String(str, len, copy); }
References internal::Hasher< Encoding, Allocator >::String().
Null()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::Null () inline
Definition at line 171 of file schema.h.
{ return WriteType(kNullType); }
References kNullType, and internal::Hasher< Encoding, Allocator >::WriteType().
RawNumber()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::RawNumber (const Ch * str, SizeType len, bool) inline
Definition at line 185 of file schema.h.
{
        WriteBuffer(kNumberType, str, len * sizeof(Ch));
        return true;
    }
References kNumberType, and internal::Hasher< Encoding, Allocator >::WriteBuffer().
StartArray()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::StartArray () inline
Definition at line 206 of file schema.h.
{ return true; }
StartObject()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::StartObject () inline
Definition at line 195 of file schema.h.
{ return true; }
String()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::String (const Ch * str, SizeType len, bool) inline
Definition at line 190 of file schema.h.
{
        WriteBuffer(kStringType, str, len * sizeof(Ch));
        return true;
    }
References kStringType, and internal::Hasher< Encoding, Allocator >::WriteBuffer().
Referenced by internal::Hasher< Encoding, Allocator >::Key().
Uint()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::Uint (unsigned u) inline
Definition at line 174 of file schema.h.
{ Number n; n.u.u = u; n.d = static_cast<double>(u); return WriteNumber(n); }
References internal::Hasher< Encoding, Allocator >::Number::d, internal::Hasher< Encoding, Allocator >::Number::U::u, internal::Hasher< Encoding, Allocator >::Number::u, and internal::Hasher< Encoding, Allocator >::WriteNumber().
Uint64()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::Uint64 (uint64_t u) inline
Definition at line 176 of file schema.h.
{ Number n; n.u.u = u; n.d = static_cast<double>(u); return WriteNumber(n); }
References internal::Hasher< Encoding, Allocator >::Number::d, internal::Hasher< Encoding, Allocator >::Number::U::u, internal::Hasher< Encoding, Allocator >::Number::u, and internal::Hasher< Encoding, Allocator >::WriteNumber().
WriteBuffer()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::WriteBuffer (Type type, const void * data, size_t len) inline private
Definition at line 237 of file schema.h.
{
        // FNV-1a from http://isthe.com/chongo/tech/comp/fnv/
        uint64_t h = Hash(RAPIDJSON_UINT64_C2(0x84222325, 0xcbf29ce4), type);
        const unsigned char* d = static_cast<const unsigned char*>(data);
        for (size_t i = 0; i < len; i++)
            h = Hash(h, d[i]);
        *stack_.template Push<uint64_t>() = h;
        return true;
    }
References process_traj_logs::data, internal::Hasher< Encoding, Allocator >::Hash(), process_bag::i, RAPIDJSON_UINT64_C2, and internal::Hasher< Encoding, Allocator >::stack_.
Referenced by internal::Hasher< Encoding, Allocator >::RawNumber(), internal::Hasher< Encoding, Allocator >::String(), internal::Hasher< Encoding, Allocator >::WriteNumber(), and internal::Hasher< Encoding, Allocator >::WriteType().
WriteNumber()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::WriteNumber (const Number & n) inline private
Definition at line 235 of file schema.h.
{ return WriteBuffer(kNumberType, &n, sizeof(n)); }
References kNumberType, and internal::Hasher< Encoding, Allocator >::WriteBuffer().
Referenced by internal::Hasher< Encoding, Allocator >::Double(), internal::Hasher< Encoding, Allocator >::Int(), internal::Hasher< Encoding, Allocator >::Int64(), internal::Hasher< Encoding, Allocator >::Uint(), and internal::Hasher< Encoding, Allocator >::Uint64().
WriteType()
template<typename Encoding , typename Allocator > bool internal::Hasher< Encoding, Allocator >::WriteType (Type type) inline private
Definition at line 233 of file schema.h.
{ return WriteBuffer(type, 0, 0); }
References internal::Hasher< Encoding, Allocator >::WriteBuffer().
Referenced by internal::Hasher< Encoding, Allocator >::Bool(), and internal::Hasher< Encoding, Allocator >::Null().
Member Data Documentation
kDefaultSize
template<typename Encoding , typename Allocator > const size_t internal::Hasher< Encoding, Allocator >::kDefaultSize = 256 static private
Definition at line 224 of file schema.h.
stack_
template<typename Encoding , typename Allocator > Stack<Allocator> internal::Hasher< Encoding, Allocator >::stack_ private
Definition at line 254 of file schema.h.
Referenced by internal::Hasher< Encoding, Allocator >::EndArray(), internal::Hasher< Encoding, Allocator >::EndObject(), internal::Hasher< Encoding, Allocator >::GetHashCode(), internal::Hasher< Encoding, Allocator >::IsValid(), and internal::Hasher< Encoding, Allocator >::WriteBuffer().
The documentation for this class was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/schema.h