Carma-platform: lci_strategic_plugin::LCIStrategicStateTransitionTable Class Reference
lci_strategic_plugin::LCIStrategicStateTransitionTable Class Reference
Class defining the state transition table behavior for the LCIStrategic Strategic Plugin.
#include <lci_state_transition_table.hpp>
Public Types
using TransitionCallback = std::function< void(TransitState prev_state, TransitState new_state, TransitEvent signal)>
Public Member Functions
LCIStrategicStateTransitionTable ()=default
Default Constructor.
TransitState getState () const
Returns the current state.
void signal (TransitEvent signal)
Trigger signal for the transition table.
void setTransitionCallback (TransitionCallback cb)
Callback setting function. The provided callback will be triggered any time the current state changes to a new state.
Private Member Functions
void signalWhenUNAVAILABLE (TransitEvent signal)
void signalWhenAPPROACHING (TransitEvent signal)
void signalWhenWAITING (TransitEvent signal)
void signalWhenDEPARTING (TransitEvent signal)
void logDebugSignal (TransitEvent signal) const
Helper function for logging the provide signal.
void setAndLogState (TransitState new_state, TransitEvent source_signal)
Function to change the current state and log the details of the transition.
Private Attributes
TransitState state_ = TransitState::UNAVAILABLE
Current state. This state should only ever be set using the setAndLogState() function.
TransitionCallback transition_callback_
Detailed Description
Class defining the state transition table behavior for the LCIStrategic Strategic Plugin.
Definition at line 25 of file lci_state_transition_table.hpp.
Member Typedef Documentation
TransitionCallback
using lci_strategic_plugin::LCIStrategicStateTransitionTable::TransitionCallback = std::function<void(TransitState prev_state, TransitState new_state, TransitEvent signal)>
Definition at line 28 of file lci_state_transition_table.hpp.
Constructor & Destructor Documentation
LCIStrategicStateTransitionTable()
lci_strategic_plugin::LCIStrategicStateTransitionTable::LCIStrategicStateTransitionTable () default
Default Constructor.
Member Function Documentation
getState()
TransitState lci_strategic_plugin::LCIStrategicStateTransitionTable::getState () const
Returns the current state.
Returns
Current state
Definition at line 29 of file lci_state_transition_table.cpp.
{
  return state_;
}
References state_.
Referenced by lci_strategic_plugin::LCIStrategicPlugin::plan_maneuvers_callback().
logDebugSignal()
void lci_strategic_plugin::LCIStrategicStateTransitionTable::logDebugSignal (TransitEvent signal) const private
Helper function for logging the provide signal.
Parameters
signal The signal to be logged
Definition at line 118 of file lci_state_transition_table.cpp.
{
  RCLCPP_DEBUG_STREAM(rclcpp::get_logger("lci_strategic_plugin"), "LCIStrategicStateTransitionTable received unsupported signal of " << signal << " while in state "
                                                                                  << state_);
}
References signal(), and state_.
Referenced by signalWhenAPPROACHING(), signalWhenDEPARTING(), signalWhenUNAVAILABLE(), and signalWhenWAITING().
setAndLogState()
void lci_strategic_plugin::LCIStrategicStateTransitionTable::setAndLogState (TransitState new_state, TransitEvent source_signal) private
Function to change the current state and log the details of the transition.
Parameters
new_state The state to set.
source_signal The signal which caused the new_state to be set
Definition at line 124 of file lci_state_transition_table.cpp.
{
  if (new_state == state_)
  {
    return;  // State was unchanged no need to log or trigger callbacks
  }
  RCLCPP_INFO_STREAM(rclcpp::get_logger("lci_strategic_plugin"), "LCIStrategicStateTransitionTable changed LCIStrategic Strategic Plugin state from "
                  << state_ << " to " << new_state << " because of signal " << source_signal);
  TransitState prev_state = state_;
  state_ = new_state; // Set new state
  if (transition_callback_) // Trigger callback if available
  {
    transition_callback_(prev_state, state_, source_signal);
  }
}
References state_, and transition_callback_.
Referenced by signalWhenAPPROACHING(), signalWhenDEPARTING(), signalWhenUNAVAILABLE(), and signalWhenWAITING().
setTransitionCallback()
void lci_strategic_plugin::LCIStrategicStateTransitionTable::setTransitionCallback (TransitionCallback cb)
Callback setting function. The provided callback will be triggered any time the current state changes to a new state.
Parameters
cb The callback function which will be provided with the previous state, new current state, and the signal which caused the transition.
Definition at line 59 of file lci_state_transition_table.cpp.
{
  transition_callback_ = cb;
}
References transition_callback_.
signal()
void lci_strategic_plugin::LCIStrategicStateTransitionTable::signal (TransitEvent signal)
Trigger signal for the transition table.
Parameters
signal The signal for the transition table to evaluate
Definition at line 34 of file lci_state_transition_table.cpp.
{
  switch (state_)
  {
    case TransitState::UNAVAILABLE:
      signalWhenUNAVAILABLE(signal);
      break;
    case TransitState::APPROACHING:
      signalWhenAPPROACHING(signal);
      break;
    case TransitState::WAITING:
      signalWhenWAITING(signal);
      break;
    case TransitState::DEPARTING:
      signalWhenDEPARTING(signal);
      break;
    default:
      throw std::invalid_argument("Transition table in unsupported state");
  }
}
References lci_strategic_plugin::APPROACHING, lci_strategic_plugin::DEPARTING, signal(), signalWhenAPPROACHING(), signalWhenDEPARTING(), signalWhenUNAVAILABLE(), signalWhenWAITING(), state_, lci_strategic_plugin::UNAVAILABLE, and lci_strategic_plugin::WAITING.
Referenced by logDebugSignal(), lci_strategic_plugin::LCIStrategicPlugin::planWhenAPPROACHING(), lci_strategic_plugin::LCIStrategicPlugin::planWhenDEPARTING(), lci_strategic_plugin::LCIStrategicPlugin::planWhenUNAVAILABLE(), lci_strategic_plugin::LCIStrategicPlugin::planWhenWAITING(), signal(), signalWhenAPPROACHING(), signalWhenDEPARTING(), signalWhenUNAVAILABLE(), and signalWhenWAITING().
signalWhenAPPROACHING()
void lci_strategic_plugin::LCIStrategicStateTransitionTable::signalWhenAPPROACHING (TransitEvent signal) private
Definition at line 76 of file lci_state_transition_table.cpp.
{
  switch (signal)
  {
    case TransitEvent::STOPPED:
      setAndLogState(TransitState::WAITING, signal);
      break;
    case TransitEvent::CROSSED_STOP_BAR:
      setAndLogState(TransitState::DEPARTING, signal);
      break;
    default:
      logDebugSignal(signal);
      break;
  }
}
References lci_strategic_plugin::CROSSED_STOP_BAR, lci_strategic_plugin::DEPARTING, logDebugSignal(), setAndLogState(), signal(), lci_strategic_plugin::STOPPED, and lci_strategic_plugin::WAITING.
Referenced by signal().
signalWhenDEPARTING()
void lci_strategic_plugin::LCIStrategicStateTransitionTable::signalWhenDEPARTING (TransitEvent signal) private
Definition at line 106 of file lci_state_transition_table.cpp.
{
  if (signal == TransitEvent::INTERSECTION_EXIT)
  {
    setAndLogState(TransitState::UNAVAILABLE, signal);
  }
  else
  {
    logDebugSignal(signal);
  }
}
References lci_strategic_plugin::INTERSECTION_EXIT, logDebugSignal(), setAndLogState(), signal(), and lci_strategic_plugin::UNAVAILABLE.
Referenced by signal().
signalWhenUNAVAILABLE()
void lci_strategic_plugin::LCIStrategicStateTransitionTable::signalWhenUNAVAILABLE (TransitEvent signal) private
Definition at line 64 of file lci_state_transition_table.cpp.
{
  if (signal == TransitEvent::IN_STOPPING_RANGE)
  {
    setAndLogState(TransitState::APPROACHING, signal);
  }
  else
  {
    logDebugSignal(signal);
  }
}
References lci_strategic_plugin::APPROACHING, lci_strategic_plugin::IN_STOPPING_RANGE, logDebugSignal(), setAndLogState(), and signal().
Referenced by signal().
signalWhenWAITING()
void lci_strategic_plugin::LCIStrategicStateTransitionTable::signalWhenWAITING (TransitEvent signal) private
Definition at line 94 of file lci_state_transition_table.cpp.
{
  if (signal == TransitEvent::RED_TO_GREEN_LIGHT)
  {
    setAndLogState(TransitState::DEPARTING, signal);
  }
  else
  {
    logDebugSignal(signal);
  }
}
References lci_strategic_plugin::DEPARTING, logDebugSignal(), lci_strategic_plugin::RED_TO_GREEN_LIGHT, setAndLogState(), and signal().
Referenced by signal().
Member Data Documentation
state_
TransitState lci_strategic_plugin::LCIStrategicStateTransitionTable::state_ = TransitState::UNAVAILABLE private
Current state. This state should only ever be set using the setAndLogState() function.
Definition at line 59 of file lci_state_transition_table.hpp.
Referenced by getState(), logDebugSignal(), setAndLogState(), and signal().
transition_callback_
TransitionCallback lci_strategic_plugin::LCIStrategicStateTransitionTable::transition_callback_ private
Definition at line 61 of file lci_state_transition_table.hpp.
Referenced by setAndLogState(), and setTransitionCallback().
The documentation for this class was generated from the following files:
lci_strategic_plugin/include/lci_strategic_plugin/lci_state_transition_table.hpp
lci_strategic_plugin/src/lci_state_transition_table.cpp