Carma-platform: internal::Stack< Allocator > Class Template Reference
internal::Stack< Allocator > Class Template Reference
A type-unsafe stack for storing different types of data.
#include <stack.h>
Public Member Functions
Stack (Allocator *allocator, size_t stackCapacity)
~Stack ()
void Swap (Stack &rhs) RAPIDJSON_NOEXCEPT
void Clear ()
void ShrinkToFit ()
template<typename T >
RAPIDJSON_FORCEINLINE void Reserve (size_t count=1)
template<typename T >
RAPIDJSON_FORCEINLINE T * Push (size_t count=1)
template<typename T >
RAPIDJSON_FORCEINLINE T * PushUnsafe (size_t count=1)
template<typename T >
T * Pop (size_t count)
template<typename T >
T * Top ()
template<typename T >
const T * Top () const
template<typename T >
T * End ()
template<typename T >
const T * End () const
template<typename T >
T * Bottom ()
template<typename T >
const T * Bottom () const
bool HasAllocator () const
Allocator & GetAllocator ()
bool Empty () const
size_t GetSize () const
size_t GetCapacity () const
Private Member Functions
template<typename T >
void Expand (size_t count)
void Resize (size_t newCapacity)
void Destroy ()
Stack (const Stack &)
Stack & operator= (const Stack &)
Private Attributes
Allocator * allocator_
Allocator * ownAllocator_
char * stack_
char * stackTop_
char * stackEnd_
size_t initialCapacity_
Detailed Description
template<typename Allocator>
class internal::Stack< Allocator >
A type-unsafe stack for storing different types of data.
Template Parameters
Allocator Allocator for allocating stack memory.
Definition at line 36 of file stack.h.
Constructor & Destructor Documentation
Stack() [1/2]
template<typename Allocator > internal::Stack< Allocator >::Stack (Allocator * allocator, size_t stackCapacity) inline
Definition at line 40 of file stack.h.
                                                      : allocator_(allocator), ownAllocator_(0), stack_(0), stackTop_(0), stackEnd_(0), initialCapacity_(stackCapacity) {
    }
~Stack()
template<typename Allocator > internal::Stack< Allocator >::~Stack () inline
Definition at line 61 of file stack.h.
             {
        Destroy();
    }
References internal::Stack< Allocator >::Destroy().
Stack() [2/2]
template<typename Allocator > internal::Stack< Allocator >::Stack (const Stack< Allocator > &) private
Member Function Documentation
Bottom() [1/2]
template<typename Allocator > template<typename T > T * internal::Stack< Allocator >::Bottom () inline
Definition at line 162 of file stack.h.
{ return reinterpret_cast<T*>(stack_); }
References internal::Stack< Allocator >::stack_.
Bottom() [2/2]
template<typename Allocator > template<typename T > const T * internal::Stack< Allocator >::Bottom () const inline
Definition at line 165 of file stack.h.
{ return reinterpret_cast<T*>(stack_); }
References internal::Stack< Allocator >::stack_.
Clear()
template<typename Allocator > void internal::Stack< Allocator >::Clear () inline
Definition at line 98 of file stack.h.
{ stackTop_ = stack_; }
References internal::Stack< Allocator >::stack_, and internal::Stack< Allocator >::stackTop_.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::ClearStack(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ClearStack(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Reset().
Destroy()
template<typename Allocator > void internal::Stack< Allocator >::Destroy () inline private
Definition at line 207 of file stack.h.
                   {
        Allocator::Free(stack_);
        RAPIDJSON_DELETE(ownAllocator_); // Only delete if it is owned by the stack
    }
References internal::Stack< Allocator >::ownAllocator_, RAPIDJSON_DELETE, and internal::Stack< Allocator >::stack_.
Referenced by internal::Stack< Allocator >::~Stack().
Empty()
template<typename Allocator > bool internal::Stack< Allocator >::Empty () const inline
Definition at line 176 of file stack.h.
{ return stackTop_ == stack_; }
References internal::Stack< Allocator >::stack_, and internal::Stack< Allocator >::stackTop_.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::IsComplete(), internal::GenericRegex< Encoding, Allocator >::Parse(), internal::GenericRegexSearch< RegexType, Allocator >::SearchWithAnchoring(), and internal::Stack< Allocator >::ShrinkToFit().
End() [1/2]
template<typename Allocator > template<typename T > T * internal::Stack< Allocator >::End () inline
Definition at line 156 of file stack.h.
{ return reinterpret_cast<T*>(stackTop_); }
References internal::Stack< Allocator >::stackTop_.
End() [2/2]
template<typename Allocator > template<typename T > const T * internal::Stack< Allocator >::End () const inline
Definition at line 159 of file stack.h.
{ return reinterpret_cast<T*>(stackTop_); }
References internal::Stack< Allocator >::stackTop_.
Expand()
template<typename Allocator > template<typename T > void internal::Stack< Allocator >::Expand (size_t count) inline private
Definition at line 182 of file stack.h.
{
        // Only expand the capacity if the current stack exists. Otherwise just create a stack with initial capacity.
        size_t newCapacity;
        if (stack_ == 0) {
            if (!allocator_)
                ownAllocator_ = allocator_ = RAPIDJSON_NEW(Allocator)();
            newCapacity = initialCapacity_;
        } else {
            newCapacity = GetCapacity();
            newCapacity += (newCapacity + 1) / 2;
        }
        size_t newSize = GetSize() + sizeof(T) * count;
        if (newCapacity < newSize)
            newCapacity = newSize;
        Resize(newCapacity);
    }
References internal::Stack< Allocator >::allocator_, internal::Stack< Allocator >::GetCapacity(), internal::Stack< Allocator >::GetSize(), internal::Stack< Allocator >::initialCapacity_, internal::Stack< Allocator >::ownAllocator_, RAPIDJSON_NEW, internal::Stack< Allocator >::Resize(), and internal::Stack< Allocator >::stack_.
GetAllocator()
template<typename Allocator > Allocator & internal::Stack< Allocator >::GetAllocator () inline
Definition at line 171 of file stack.h.
{
        RAPIDJSON_ASSERT(allocator_);
        return *allocator_;
    }
References internal::Stack< Allocator >::allocator_, and RAPIDJSON_ASSERT.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream().
GetCapacity()
template<typename Allocator > size_t internal::Stack< Allocator >::GetCapacity () const inline
Definition at line 178 of file stack.h.
{ return static_cast<size_t>(stackEnd_ - stack_); }
References internal::Stack< Allocator >::stack_, and internal::Stack< Allocator >::stackEnd_.
Referenced by internal::Stack< Allocator >::Expand(), GenericDocument< Encoding, Allocator, StackAllocator >::GetStackCapacity(), and internal::Stack< Allocator >::Resize().
GetSize()
template<typename Allocator > size_t internal::Stack< Allocator >::GetSize () const inline
Definition at line 177 of file stack.h.
{ return static_cast<size_t>(stackTop_ - stack_); }
References internal::Stack< Allocator >::stack_, and internal::Stack< Allocator >::stackTop_.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::ClearStack(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), internal::GenericRegex< Encoding, Allocator >::Eval(), internal::GenericRegex< Encoding, Allocator >::EvalQuantifier(), internal::Stack< Allocator >::Expand(), internal::GenericRegex< Encoding, Allocator >::Parse(), GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream(), internal::Stack< Allocator >::Pop(), GenericDocument< Encoding, Allocator, StackAllocator >::Populate(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), internal::Stack< Allocator >::Resize(), internal::Stack< Allocator >::ShrinkToFit(), internal::Stack< Allocator >::Top(), and PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteIndent().
HasAllocator()
template<typename Allocator > bool internal::Stack< Allocator >::HasAllocator () const inline
Definition at line 167 of file stack.h.
{
        return allocator_ != 0;
    }
References internal::Stack< Allocator >::allocator_.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream().
operator=()
template<typename Allocator > Stack & internal::Stack< Allocator >::operator= (const Stack< Allocator > &) private
Pop()
template<typename Allocator > template<typename T > T * internal::Stack< Allocator >::Pop (size_t count) inline
Definition at line 137 of file stack.h.
{
        RAPIDJSON_ASSERT(GetSize() >= count * sizeof(T));
        stackTop_ -= count * sizeof(T);
        return reinterpret_cast<T*>(stackTop_);
    }
References internal::Stack< Allocator >::GetSize(), RAPIDJSON_ASSERT, and internal::Stack< Allocator >::stackTop_.
Push()
template<typename Allocator > template<typename T > RAPIDJSON_FORCEINLINE T * internal::Stack< Allocator >::Push (size_t count = 1) inline
Definition at line 122 of file stack.h.
{
        Reserve<T>(count);
        return PushUnsafe<T>(count);
    }
PushUnsafe()
template<typename Allocator > template<typename T > RAPIDJSON_FORCEINLINE T * internal::Stack< Allocator >::PushUnsafe (size_t count = 1) inline
Definition at line 128 of file stack.h.
{
        RAPIDJSON_ASSERT(stackTop_);
        RAPIDJSON_ASSERT(stackTop_ + sizeof(T) * count <= stackEnd_);
        T* ret = reinterpret_cast<T*>(stackTop_);
        stackTop_ += sizeof(T) * count;
        return ret;
    }
References RAPIDJSON_ASSERT, internal::Stack< Allocator >::stackEnd_, and internal::Stack< Allocator >::stackTop_.
Reserve()
template<typename Allocator > template<typename T > RAPIDJSON_FORCEINLINE void internal::Stack< Allocator >::Reserve (size_t count = 1) inline
Definition at line 115 of file stack.h.
{
         // Expand the stack if needed
        if (RAPIDJSON_UNLIKELY(stackTop_ + sizeof(T) * count > stackEnd_))
            Expand<T>(count);
    }
References RAPIDJSON_UNLIKELY, internal::Stack< Allocator >::stackEnd_, and internal::Stack< Allocator >::stackTop_.
Resize()
template<typename Allocator > void internal::Stack< Allocator >::Resize (size_t newCapacity) inline private
Definition at line 200 of file stack.h.
{
        const size_t size = GetSize();  // Backup the current size
        stack_ = static_cast<char*>(allocator_->Realloc(stack_, GetCapacity(), newCapacity));
        stackTop_ = stack_ + size;
        stackEnd_ = stack_ + newCapacity;
    }
References internal::Stack< Allocator >::allocator_, internal::Stack< Allocator >::GetCapacity(), internal::Stack< Allocator >::GetSize(), internal::Stack< Allocator >::stack_, internal::Stack< Allocator >::stackEnd_, and internal::Stack< Allocator >::stackTop_.
Referenced by internal::Stack< Allocator >::Expand(), and internal::Stack< Allocator >::ShrinkToFit().
ShrinkToFit()
template<typename Allocator > void internal::Stack< Allocator >::ShrinkToFit () inline
Definition at line 100 of file stack.h.
                       {
        if (Empty()) {
            // If the stack is empty, completely deallocate the memory.
            Allocator::Free(stack_);
            stack_ = 0;
            stackTop_ = 0;
            stackEnd_ = 0;
        }
        else
            Resize(GetSize());
    }
References internal::Stack< Allocator >::Empty(), internal::Stack< Allocator >::GetSize(), internal::Stack< Allocator >::Resize(), internal::Stack< Allocator >::stack_, internal::Stack< Allocator >::stackEnd_, and internal::Stack< Allocator >::stackTop_.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::ClearStack().
Swap()
template<typename Allocator > void internal::Stack< Allocator >::Swap (Stack< Allocator > & rhs) inline
Definition at line 89 of file stack.h.
{
        internal::Swap(allocator_, rhs.allocator_);
        internal::Swap(ownAllocator_, rhs.ownAllocator_);
        internal::Swap(stack_, rhs.stack_);
        internal::Swap(stackTop_, rhs.stackTop_);
        internal::Swap(stackEnd_, rhs.stackEnd_);
        internal::Swap(initialCapacity_, rhs.initialCapacity_);
    }
References internal::Stack< Allocator >::allocator_, internal::Stack< Allocator >::initialCapacity_, internal::Stack< Allocator >::ownAllocator_, internal::Stack< Allocator >::stack_, internal::Stack< Allocator >::stackEnd_, internal::Stack< Allocator >::stackTop_, and internal::Swap().
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::Swap().
Top() [1/2]
template<typename Allocator > template<typename T > T * internal::Stack< Allocator >::Top () inline
Definition at line 144 of file stack.h.
             {
        RAPIDJSON_ASSERT(GetSize() >= sizeof(T));
        return reinterpret_cast<T*>(stackTop_ - sizeof(T));
    }
References internal::Stack< Allocator >::GetSize(), RAPIDJSON_ASSERT, and internal::Stack< Allocator >::stackTop_.
Top() [2/2]
template<typename Allocator > template<typename T > const T * internal::Stack< Allocator >::Top () const inline
Definition at line 150 of file stack.h.
{
        RAPIDJSON_ASSERT(GetSize() >= sizeof(T));
        return reinterpret_cast<T*>(stackTop_ - sizeof(T));
    }
References internal::Stack< Allocator >::GetSize(), RAPIDJSON_ASSERT, and internal::Stack< Allocator >::stackTop_.
Member Data Documentation
allocator_
template<typename Allocator > Allocator* internal::Stack< Allocator >::allocator_ private
Definition at line 216 of file stack.h.
Referenced by internal::Stack< Allocator >::Expand(), internal::Stack< Allocator >::GetAllocator(), internal::Stack< Allocator >::HasAllocator(), internal::Stack< Allocator >::Resize(), and internal::Stack< Allocator >::Swap().
initialCapacity_
template<typename Allocator > size_t internal::Stack< Allocator >::initialCapacity_ private
Definition at line 221 of file stack.h.
Referenced by internal::Stack< Allocator >::Expand(), and internal::Stack< Allocator >::Swap().
ownAllocator_
template<typename Allocator > Allocator* internal::Stack< Allocator >::ownAllocator_ private
Definition at line 217 of file stack.h.
Referenced by internal::Stack< Allocator >::Destroy(), internal::Stack< Allocator >::Expand(), and internal::Stack< Allocator >::Swap().
stack_
template<typename Allocator > char* internal::Stack< Allocator >::stack_ private
Definition at line 218 of file stack.h.
Referenced by internal::Stack< Allocator >::Bottom(), internal::Stack< Allocator >::Clear(), internal::Stack< Allocator >::Destroy(), internal::Stack< Allocator >::Empty(), internal::Stack< Allocator >::Expand(), internal::Stack< Allocator >::GetCapacity(), internal::Stack< Allocator >::GetSize(), internal::Stack< Allocator >::Resize(), internal::Stack< Allocator >::ShrinkToFit(), and internal::Stack< Allocator >::Swap().
stackEnd_
template<typename Allocator > char* internal::Stack< Allocator >::stackEnd_ private
Definition at line 220 of file stack.h.
Referenced by internal::Stack< Allocator >::GetCapacity(), internal::Stack< Allocator >::PushUnsafe(), internal::Stack< Allocator >::Reserve(), internal::Stack< Allocator >::Resize(), internal::Stack< Allocator >::ShrinkToFit(), and internal::Stack< Allocator >::Swap().
stackTop_
template<typename Allocator > char* internal::Stack< Allocator >::stackTop_ private
Definition at line 219 of file stack.h.
Referenced by internal::Stack< Allocator >::Clear(), internal::Stack< Allocator >::Empty(), internal::Stack< Allocator >::End(), internal::Stack< Allocator >::GetSize(), internal::Stack< Allocator >::Pop(), internal::Stack< Allocator >::PushUnsafe(), internal::Stack< Allocator >::Reserve(), internal::Stack< Allocator >::Resize(), internal::Stack< Allocator >::ShrinkToFit(), internal::Stack< Allocator >::Swap(), and internal::Stack< Allocator >::Top().
The documentation for this class was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/internal/stack.h