Carma-platform: cost_plugin_system::CostPluginWorker Class Reference
cost_plugin_system::CostPluginWorker Class Reference
#include <cost_plugin_worker.hpp>
Public Member Functions
CostPluginWorker ()
Default constructor for CostPluginWorker.
void init ()
Initialize the cost plugin system.
void run ()
Run the spin loop of cost plugin system.
double compute_final_score (cav_msgs::ManeuverPlan plan)
Public Attributes
std::unique_ptr< ros::CARMANodeHandle > nh_
std::unique_ptr< ros::CARMANodeHandle > pnh_
ros::ServiceServer compute_plan_cost_service_server_
Private Member Functions
bool get_score (cav_srvs::ComputePlanCostRequest &req, cav_srvs::ComputePlanCostResponse &res)
Private Attributes
double max_accelaration_
double max_decelaration_
double speed_limit_
double speed_buffer_
double weight_of_comfort_
double weight_of_efficiency_
double weight_of_feasibility_
double weight_of_fuel_
double weight_of_safety_
Detailed Description
Definition at line 34 of file cost_plugin_worker.hpp.
Constructor & Destructor Documentation
CostPluginWorker()
cost_plugin_system::CostPluginWorker::CostPluginWorker ()
Default constructor for CostPluginWorker.
Definition at line 21 of file cost_plugin_worker.cpp.
{
    }
Member Function Documentation
compute_final_score()
double cost_plugin_system::CostPluginWorker::compute_final_score (cav_msgs::ManeuverPlan plan)
Definition at line 51 of file cost_plugin_worker.cpp.
{
    cost_plugin_system::CostofComfort coc(max_decelaration_);
    cost_plugin_system::CostofEfficiency coe(speed_limit_, speed_buffer_);
    cost_plugin_system::CostofFeasibility cofe(max_accelaration_, max_decelaration_);
    cost_plugin_system::CostofFuel cof;
    cost_plugin_system::CostofLegality col;
    cost_plugin_system::CostofSafety cos(speed_limit_);
    double total_cost = 0.0;
    if (col.compute_cost(plan) == 0)
    {
        double cost_of_comfort = coc.compute_cost(plan);
        double cost_of_efficiency = coe.compute_cost(plan);
        double cost_of_feasibility = cofe.compute_cost(plan);
        double cost_of_fuel = cof.compute_cost(plan);
        double cost_of_safety = cos.compute_cost(plan);
        total_cost = weight_of_comfort_ * cost_of_comfort + weight_of_efficiency_ * cost_of_efficiency +
                     weight_of_feasibility_ * cost_of_feasibility + weight_of_fuel_ * cost_of_fuel +
                     weight_of_safety_ * cost_of_safety;
    }
    else
    {
        total_cost = -999.0;
    }
    return total_cost;
}
References cost_plugin_system::CostofComfort::compute_cost(), cost_plugin_system::CostofEfficiency::compute_cost(), cost_plugin_system::CostofFeasibility::compute_cost(), cost_plugin_system::CostofFuel::compute_cost(), cost_plugin_system::CostofLegality::compute_cost(), cost_plugin_system::CostofSafety::compute_cost(), max_accelaration_, max_decelaration_, speed_buffer_, speed_limit_, weight_of_comfort_, weight_of_efficiency_, weight_of_feasibility_, weight_of_fuel_, and weight_of_safety_.
Referenced by get_score().
get_score()
bool cost_plugin_system::CostPluginWorker::get_score (cav_srvs::ComputePlanCostRequest & req, cav_srvs::ComputePlanCostResponse & res) private
Definition at line 42 of file cost_plugin_worker.cpp.
{
    cav_msgs::ManeuverPlan plan = req.maneuver_plan;
    res.plan_cost = compute_final_score(plan);
    return true;
}
References compute_final_score().
Referenced by run().
init()
void cost_plugin_system::CostPluginWorker::init ()
Initialize the cost plugin system.
Definition at line 24 of file cost_plugin_worker.cpp.
{
    nh_.reset(new ros::CARMANodeHandle());
    pnh_.reset(new ros::CARMANodeHandle("~"));
    pnh_->param<double>("max_accelaration", max_accelaration_, 5.0);
    pnh_->param<double>("max_decelaration", max_decelaration_, 8.0);
    pnh_->param<double>("speed_limit", speed_limit_, 27.0);
    pnh_->param<double>("speed_buffer", speed_buffer_, 25.0);
    pnh_->param<double>("weight_of_comfort", weight_of_comfort_, 1.0);
    pnh_->param<double>("weight_of_efficiency", weight_of_efficiency_, 1.0);
    pnh_->param<double>("weight_of_feasibility", weight_of_feasibility_, 1.0);
    pnh_->param<double>("weight_of_fuel", weight_of_fuel_, 1.0);
    pnh_->param<double>("weight_of_safety", weight_of_safety_, 1.0);
}
References max_accelaration_, max_decelaration_, nh_, pnh_, speed_buffer_, speed_limit_, weight_of_comfort_, weight_of_efficiency_, weight_of_feasibility_, weight_of_fuel_, and weight_of_safety_.
Referenced by run().
run()
void cost_plugin_system::CostPluginWorker::run ()
Run the spin loop of cost plugin system.
Definition at line 80 of file cost_plugin_worker.cpp.
{
    init();
    ROS_INFO("Initalizing cost_plugin_system node...");
    // Init our ROS objects
    compute_plan_cost_service_server_ = nh_->advertiseService("compute_plan_cost", &CostPluginWorker::get_score, this);
    ROS_INFO("Ready to compute the total cost");
    ros::spin();
}
References compute_plan_cost_service_server_, get_score(), init(), and nh_.
Referenced by main().
Member Data Documentation
compute_plan_cost_service_server_
ros::ServiceServer cost_plugin_system::CostPluginWorker::compute_plan_cost_service_server_
Definition at line 57 of file cost_plugin_worker.hpp.
Referenced by run().
max_accelaration_
double cost_plugin_system::CostPluginWorker::max_accelaration_ private
Definition at line 61 of file cost_plugin_worker.hpp.
Referenced by compute_final_score(), and init().
max_decelaration_
double cost_plugin_system::CostPluginWorker::max_decelaration_ private
Definition at line 62 of file cost_plugin_worker.hpp.
Referenced by compute_final_score(), and init().
nh_
std::unique_ptr<ros::CARMANodeHandle> cost_plugin_system::CostPluginWorker::nh_
Definition at line 53 of file cost_plugin_worker.hpp.
Referenced by init(), and run().
pnh_
std::unique_ptr<ros::CARMANodeHandle> cost_plugin_system::CostPluginWorker::pnh_
Definition at line 54 of file cost_plugin_worker.hpp.
Referenced by init().
speed_buffer_
double cost_plugin_system::CostPluginWorker::speed_buffer_ private
Definition at line 64 of file cost_plugin_worker.hpp.
Referenced by compute_final_score(), and init().
speed_limit_
double cost_plugin_system::CostPluginWorker::speed_limit_ private
Definition at line 63 of file cost_plugin_worker.hpp.
Referenced by compute_final_score(), and init().
weight_of_comfort_
double cost_plugin_system::CostPluginWorker::weight_of_comfort_ private
Definition at line 65 of file cost_plugin_worker.hpp.
Referenced by compute_final_score(), and init().
weight_of_efficiency_
double cost_plugin_system::CostPluginWorker::weight_of_efficiency_ private
Definition at line 66 of file cost_plugin_worker.hpp.
Referenced by compute_final_score(), and init().
weight_of_feasibility_
double cost_plugin_system::CostPluginWorker::weight_of_feasibility_ private
Definition at line 67 of file cost_plugin_worker.hpp.
Referenced by compute_final_score(), and init().
weight_of_fuel_
double cost_plugin_system::CostPluginWorker::weight_of_fuel_ private
Definition at line 68 of file cost_plugin_worker.hpp.
Referenced by compute_final_score(), and init().
weight_of_safety_
double cost_plugin_system::CostPluginWorker::weight_of_safety_ private
Definition at line 69 of file cost_plugin_worker.hpp.
Referenced by compute_final_score(), and init().
The documentation for this class was generated from the following files:
cost_plugin_system/include/cost_plugin_worker.hpp
cost_plugin_system/src/cost_plugin_worker.cpp