Carma-platform: carma_guidance_plugins::ControlPlugin Class Reference
carma_guidance_plugins::ControlPlugin Class Reference abstract
ControlPlugin base class which can be extended by user provided plugins which wish to implement the Control Plugin ROS API.
#include <control_plugin.hpp>
Public Member Functions
ControlPlugin (const rclcpp::NodeOptions &)
ControlPlugin constructor.
virtual ~ControlPlugin ()=default
Virtual destructor for safe deletion.
virtual autoware_msgs::msg::ControlCommandStamped generate_command ()=0
Extending class provided method which should generate a command message which will be published to the required topic by the base class.
std::string get_capability () override
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
uint8_t get_type () override final
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_deactivate (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_cleanup (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_shutdown (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_error (const rclcpp_lifecycle::State &, const std::string &exception_string) override final
Public Member Functions inherited from carma_guidance_plugins::PluginBaseNode
PluginBaseNode (const rclcpp::NodeOptions &)
PluginBaseNode constructor.
virtual ~PluginBaseNode ()=default
Virtual destructor for safe deletion.
virtual std::shared_ptr< carma_wm::WMListener > get_world_model_listener () final
Method to return the default world model listener provided as a convience by this base class If this method or get_world_model() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
virtual carma_wm::WorldModelConstPtr get_world_model () final
Method to return the default world model provided as a convience by this base class If this method or get_world_model_listener() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
virtual bool get_activation_status () final
Returns the activation status of this plugin. The plugins API callbacks will only be triggered when this method returns true.
virtual uint8_t get_type ()
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
std::string get_plugin_name_and_ns () const
Return the name of this plugin with namespace. NOTE: If only the name of the plugin is required, use get_plugin_name()
std::string get_plugin_name () const
Return the name of this plugin.
virtual bool get_availability ()=0
Get the availability status of this plugin based on the current operating environment. Method must be overriden by extending classes.
virtual std::string get_capability ()=0
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
virtual std::string get_version_id ()=0
Returns the version id of this plugin.
virtual carma_ros2_utils::CallbackReturn on_configure_plugin ()=0
Method which is triggered when this plugin is moved from the UNCONFIGURED to INACTIVE states. This method should be used to load parameters and is required to be implemented.
virtual carma_ros2_utils::CallbackReturn on_activate_plugin ()
Method which is triggered when this plugin is moved from the INACTIVE to ACTIVE states. This method should be used to prepare for future callbacks for plugin's capabilites.
virtual carma_ros2_utils::CallbackReturn on_deactivate_plugin ()
Method which is triggered when this plugin is moved from the ACTIVE to INACTIVE states. This method should be used to disable any functionality which should cease execution when plugin is inactive.
virtual carma_ros2_utils::CallbackReturn on_cleanup_plugin ()
Method which is triggered when this plugin is moved from the INACTIVE to UNCONFIGURED states. This method should be used to fully reset the plugin such that a future call to on_configure_plugin would leave the plugin in a fresh state as though just launched.
virtual carma_ros2_utils::CallbackReturn on_shutdown_plugin ()
Method which is triggered when this plugin is moved from any state to FINALIZED This method should be used to generate any shutdown logs or final cleanup.
virtual carma_ros2_utils::CallbackReturn on_error_plugin (const std::string &exception_string)
Method which is triggered when an unhandled exception occurs in this plugin This method should be used to cleanup such that the plugin could be moved to UNCONFIGURED state if possible.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_deactivate (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_cleanup (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_shutdown (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_error (const rclcpp_lifecycle::State &, const std::string &exception_string) override
FRIEND_TEST (carma_guidance_plugins_test, connections_test)
Protected Attributes
boost::optional< geometry_msgs::msg::PoseStamped > current_pose_
The most recent pose message received by this node.
boost::optional< geometry_msgs::msg::TwistStamped > current_twist_
The most recent velocity message received by this node.
boost::optional< carma_planning_msgs::msg::TrajectoryPlan > current_trajectory_
The most recent trajectory received by this plugin.
Private Member Functions
void current_pose_callback (geometry_msgs::msg::PoseStamped::UniquePtr msg)
void current_twist_callback (geometry_msgs::msg::TwistStamped::UniquePtr msg)
void current_trajectory_callback (carma_planning_msgs::msg::TrajectoryPlan::UniquePtr msg)
Private Attributes
carma_ros2_utils::SubPtr< geometry_msgs::msg::PoseStamped > current_pose_sub_
carma_ros2_utils::SubPtr< geometry_msgs::msg::TwistStamped > current_velocity_sub_
carma_ros2_utils::SubPtr< carma_planning_msgs::msg::TrajectoryPlan > trajectory_plan_sub_
carma_ros2_utils::PubPtr< autoware_msgs::msg::ControlCommandStamped > vehicle_cmd_pub_
rclcpp::TimerBase::SharedPtr command_timer_
Detailed Description
ControlPlugin base class which can be extended by user provided plugins which wish to implement the Control Plugin ROS API.
A control plugin is responsible for generating high frequency vehicle speed and steering commands to execute the currently planned trajectory. This plugin provides default subscribers to track the pose, velocity, and current trajectory in the system. Extending classes must implement the generate_command() method to use that data and or additional data to plan commands at a 30Hz frequency.
Definition at line 38 of file control_plugin.hpp.
Constructor & Destructor Documentation
ControlPlugin()
carma_guidance_plugins::ControlPlugin::ControlPlugin (const rclcpp::NodeOptions & options) explicit
ControlPlugin constructor.
Definition at line 25 of file control_plugin.cpp.
      : PluginBaseNode(options)
  {}
~ControlPlugin()
virtual carma_guidance_plugins::ControlPlugin::~ControlPlugin () virtual default
Virtual destructor for safe deletion.
Member Function Documentation
current_pose_callback()
void carma_guidance_plugins::ControlPlugin::current_pose_callback (geometry_msgs::msg::PoseStamped::UniquePtr msg) private
Definition at line 39 of file control_plugin.cpp.
  {
    RCLCPP_DEBUG(rclcpp::get_logger("carma_guidance_plugins"), "Received pose message");
    current_pose_ = *msg;
  }
References current_pose_.
Referenced by handle_on_configure().
current_trajectory_callback()
void carma_guidance_plugins::ControlPlugin::current_trajectory_callback (carma_planning_msgs::msg::TrajectoryPlan::UniquePtr msg) private
Definition at line 51 of file control_plugin.cpp.
  {
    RCLCPP_DEBUG(rclcpp::get_logger("carma_guidance_plugins"), "Received trajectory message");
    current_trajectory_ = *msg;
  }
References current_trajectory_.
Referenced by handle_on_configure().
current_twist_callback()
void carma_guidance_plugins::ControlPlugin::current_twist_callback (geometry_msgs::msg::TwistStamped::UniquePtr msg) private
Definition at line 45 of file control_plugin.cpp.
  {
    RCLCPP_DEBUG(rclcpp::get_logger("carma_guidance_plugins"), "Received twist message");
    current_twist_ = *msg;
  }
References current_twist_.
Referenced by handle_on_configure().
generate_command()
virtual autoware_msgs::msg::ControlCommandStamped carma_guidance_plugins::ControlPlugin::generate_command () pure virtual
Extending class provided method which should generate a command message which will be published to the required topic by the base class.
NOTE: Implementer can determine if trajectory has changed based on current_trajectory_->trajectory_id
Returns
The command message to publish
Implemented in pure_pursuit_wrapper::PurePursuitWrapperNode, and SUB::Node.
Referenced by handle_on_configure().
get_capability()
std::string carma_guidance_plugins::ControlPlugin::get_capability () override virtual
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
Returns
Forward slash separated string describing the plugin's capabilities per the plugin capabilites API
Implements carma_guidance_plugins::PluginBaseNode.
Definition at line 29 of file control_plugin.cpp.
  {
    return "control/trajectory_control";
  }
get_type()
uint8_t carma_guidance_plugins::ControlPlugin::get_type () final override virtual
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
Returns
The extending class type or UNKOWN if the class or no parent class has implement this method.
Reimplemented from carma_guidance_plugins::PluginBaseNode.
Definition at line 34 of file control_plugin.cpp.
  {
    return carma_planning_msgs::msg::Plugin::CONTROL;
  }
handle_on_activate()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::ControlPlugin::handle_on_activate (const rclcpp_lifecycle::State & prev_state) final override
Definition at line 84 of file control_plugin.cpp.
  {
    return PluginBaseNode::handle_on_activate(prev_state);
  }
References carma_guidance_plugins::PluginBaseNode::handle_on_activate().
handle_on_cleanup()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::ControlPlugin::handle_on_cleanup (const rclcpp_lifecycle::State & prev_state) final override
Definition at line 94 of file control_plugin.cpp.
  {
    return PluginBaseNode::handle_on_cleanup(prev_state);
  }
References carma_guidance_plugins::PluginBaseNode::handle_on_cleanup().
handle_on_configure()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::ControlPlugin::handle_on_configure (const rclcpp_lifecycle::State & prev_state) final override
Definition at line 57 of file control_plugin.cpp.
  {
    // Initialize subscribers and publishers
    current_pose_sub_ = create_subscription<geometry_msgs::msg::PoseStamped>("current_pose", 1,
      std::bind(&ControlPlugin::current_pose_callback, this, std_ph::_1));
    current_velocity_sub_ = create_subscription<geometry_msgs::msg::TwistStamped>("vehicle/twist", 1,
      std::bind(&ControlPlugin::current_twist_callback, this, std_ph::_1));
    trajectory_plan_sub_ = create_subscription<carma_planning_msgs::msg::TrajectoryPlan>(std::string(get_name()) + "/plan_trajectory", 1,
      std::bind(&ControlPlugin::current_trajectory_callback, this, std_ph::_1));
    vehicle_cmd_pub_ = create_publisher<autoware_msgs::msg::ControlCommandStamped>("ctrl_raw", 1);
    command_timer_ = create_timer(
        get_clock(),
        std::chrono::milliseconds(33), // Spin at 30 Hz per plugin API
        [this]() {
          if (this->get_activation_status()) // Only trigger when activated
          {
            this->vehicle_cmd_pub_->publish(this->generate_command());
          }
        });
    return PluginBaseNode::handle_on_configure(prev_state);
  }
References command_timer_, current_pose_callback(), current_pose_sub_, current_trajectory_callback(), current_twist_callback(), current_velocity_sub_, generate_command(), carma_guidance_plugins::PluginBaseNode::get_activation_status(), carma_guidance_plugins::PluginBaseNode::handle_on_configure(), trajectory_plan_sub_, and vehicle_cmd_pub_.
handle_on_deactivate()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::ControlPlugin::handle_on_deactivate (const rclcpp_lifecycle::State & prev_state) final override
Definition at line 89 of file control_plugin.cpp.
  {
    return PluginBaseNode::handle_on_deactivate(prev_state);
  }
References carma_guidance_plugins::PluginBaseNode::handle_on_deactivate().
handle_on_error()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::ControlPlugin::handle_on_error (const rclcpp_lifecycle::State & prev_state, const std::string & exception_string) final override
Definition at line 104 of file control_plugin.cpp.
  {
    return PluginBaseNode::handle_on_error(prev_state, exception_string);
  }
References carma_guidance_plugins::PluginBaseNode::handle_on_error().
handle_on_shutdown()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::ControlPlugin::handle_on_shutdown (const rclcpp_lifecycle::State & prev_state) final override
Definition at line 99 of file control_plugin.cpp.
  {
    return PluginBaseNode::handle_on_shutdown(prev_state);
  }
References carma_guidance_plugins::PluginBaseNode::handle_on_shutdown().
Member Data Documentation
command_timer_
rclcpp::TimerBase::SharedPtr carma_guidance_plugins::ControlPlugin::command_timer_ private
Definition at line 51 of file control_plugin.hpp.
Referenced by handle_on_configure().
current_pose_
boost::optional<geometry_msgs::msg::PoseStamped> carma_guidance_plugins::ControlPlugin::current_pose_ protected
The most recent pose message received by this node.
Definition at line 62 of file control_plugin.hpp.
Referenced by current_pose_callback(), and pure_pursuit_wrapper::PurePursuitWrapperNode::generate_command().
current_pose_sub_
carma_ros2_utils::SubPtr<geometry_msgs::msg::PoseStamped> carma_guidance_plugins::ControlPlugin::current_pose_sub_ private
Definition at line 43 of file control_plugin.hpp.
Referenced by handle_on_configure().
current_trajectory_
boost::optional<carma_planning_msgs::msg::TrajectoryPlan> carma_guidance_plugins::ControlPlugin::current_trajectory_ protected
The most recent trajectory received by this plugin.
Definition at line 69 of file control_plugin.hpp.
Referenced by current_trajectory_callback(), and pure_pursuit_wrapper::PurePursuitWrapperNode::generate_command().
current_twist_
boost::optional<geometry_msgs::msg::TwistStamped> carma_guidance_plugins::ControlPlugin::current_twist_ protected
The most recent velocity message received by this node.
Definition at line 66 of file control_plugin.hpp.
Referenced by current_twist_callback(), and pure_pursuit_wrapper::PurePursuitWrapperNode::generate_command().
current_velocity_sub_
carma_ros2_utils::SubPtr<geometry_msgs::msg::TwistStamped> carma_guidance_plugins::ControlPlugin::current_velocity_sub_ private
Definition at line 44 of file control_plugin.hpp.
Referenced by handle_on_configure().
trajectory_plan_sub_
carma_ros2_utils::SubPtr<carma_planning_msgs::msg::TrajectoryPlan> carma_guidance_plugins::ControlPlugin::trajectory_plan_sub_ private
Definition at line 45 of file control_plugin.hpp.
Referenced by handle_on_configure().
vehicle_cmd_pub_
carma_ros2_utils::PubPtr<autoware_msgs::msg::ControlCommandStamped> carma_guidance_plugins::ControlPlugin::vehicle_cmd_pub_ private
Definition at line 48 of file control_plugin.hpp.
Referenced by handle_on_configure().
The documentation for this class was generated from the following files:
carma_guidance_plugins/include/carma_guidance_plugins/control_plugin.hpp
carma_guidance_plugins/src/control_plugin.cpp