Carma-platform: mpc_follower_wrapper::MPCFollowerWrapper Class Reference
mpc_follower_wrapper::MPCFollowerWrapper Class Reference
#include <mpc_follower_wrapper.hpp>
Public Member Functions
MPCFollowerWrapper (ros::CARMANodeHandle &nodeHandle)
virtual ~MPCFollowerWrapper ()=default
void Initialize ()
void CurrentPoseHandler (const geometry_msgs::PoseStamped::ConstPtr &pose)
void TrajectoryPlanPoseHandler (const cav_msgs::TrajectoryPlan::ConstPtr &tp)
Public Attributes
ros::Subscriber trajectory_plan_sub
ros::Subscriber pose_sub
Private Member Functions
void PublisherForWayPoints (const autoware_msgs::Lane &msg)
Private Attributes
ros::CARMANodeHandle & nh_
ros::Publisher mpc_plugin_discovery_pub_
cav_msgs::Plugin plugin_discovery_msg_
geometry_msgs::PoseStamped current_pose_
ros::Publisher way_points_pub_
ros::Timer discovery_pub_timer_
MPCFollowerWrapperWorker mpcww
Detailed Description
Main class for the node to handle the ROS interfacing.
Definition at line 45 of file mpc_follower_wrapper.hpp.
Constructor & Destructor Documentation
MPCFollowerWrapper()
mpc_follower_wrapper::MPCFollowerWrapper::MPCFollowerWrapper (ros::CARMANodeHandle & nodeHandle)
Constructor.
Parameters
nodeHandle the ROS node handle.
Definition at line 25 of file mpc_follower_wrapper.cpp.
                                                                    : nh_(nodeHandle)
{
  Initialize();
  ROS_INFO("Successfully launched node.");
}
References Initialize().
~MPCFollowerWrapper()
virtual mpc_follower_wrapper::MPCFollowerWrapper::~MPCFollowerWrapper () virtual default
Destructor.
Member Function Documentation
CurrentPoseHandler()
void mpc_follower_wrapper::MPCFollowerWrapper::CurrentPoseHandler (const geometry_msgs::PoseStamped::ConstPtr & pose)
Definition at line 57 of file mpc_follower_wrapper.cpp.
{
  current_pose_ = *pose;
}
References current_pose_.
Initialize()
void mpc_follower_wrapper::MPCFollowerWrapper::Initialize ()
Definition at line 33 of file mpc_follower_wrapper.cpp.
{
  // Trajectory Plan Subscriber
  trajectory_plan_sub = nh_.subscribe<cav_msgs::TrajectoryPlan>("mpc_follower/trajectory", 1, &MPCFollowerWrapper::TrajectoryPlanPoseHandler, this);
  // WayPoints Publisher
  way_points_pub_ = nh_.advertise<autoware_msgs::Lane>("final_waypoints", 10, true);
  mpc_plugin_discovery_pub_ = nh_.advertise<cav_msgs::Plugin>("plugin_discovery", 1);
  plugin_discovery_msg_.name = "MPC";
  plugin_discovery_msg_.version_id = "v1.0";
  plugin_discovery_msg_.available = true;
  plugin_discovery_msg_.activated = true;
  plugin_discovery_msg_.type = cav_msgs::Plugin::CONTROL;
  plugin_discovery_msg_.capability = "control_mpc_plan/plan_controls";
  discovery_pub_timer_ = nh_.createTimer(
      ros::Duration(ros::Rate(10.0)),
      [this](const auto&) { mpc_plugin_discovery_pub_.publish(plugin_discovery_msg_); });
}
References discovery_pub_timer_, mpc_plugin_discovery_pub_, nh_, plugin_discovery_msg_, trajectory_plan_sub, TrajectoryPlanPoseHandler(), and way_points_pub_.
Referenced by MPCFollowerWrapper().
PublisherForWayPoints()
void mpc_follower_wrapper::MPCFollowerWrapper::PublisherForWayPoints (const autoware_msgs::Lane & msg) private
Definition at line 88 of file mpc_follower_wrapper.cpp.
{
  way_points_pub_.publish(msg);
};
References way_points_pub_.
Referenced by TrajectoryPlanPoseHandler().
TrajectoryPlanPoseHandler()
void mpc_follower_wrapper::MPCFollowerWrapper::TrajectoryPlanPoseHandler (const cav_msgs::TrajectoryPlan::ConstPtr & tp)
Definition at line 62 of file mpc_follower_wrapper.cpp.
{
  ROS_DEBUG_STREAM("Received TrajectoryPlanCurrentPosecallback message");
    try {
      autoware_msgs::Lane lane;
      lane.header = tp->header;
      std::vector <autoware_msgs::Waypoint> waypoints;
      for(int i = 0; i < tp->trajectory_points.size() - 1; i++ ) {
        cav_msgs::TrajectoryPlanPoint t1 = tp->trajectory_points[i];
        cav_msgs::TrajectoryPlanPoint t2 = tp->trajectory_points[i + 1];
        autoware_msgs::Waypoint waypoint = mpcww.TrajectoryPlanPointToWaypointConverter(t1, t2);
        waypoints.push_back(waypoint);
      }
      lane.waypoints = waypoints;
      PublisherForWayPoints(lane);
    }
    catch(const std::exception& e) {
      ros::CARMANodeHandle::handleException(e);
    }
};
References process_bag::i, mpcww, PublisherForWayPoints(), and mpc_follower_wrapper::MPCFollowerWrapperWorker::TrajectoryPlanPointToWaypointConverter().
Referenced by Initialize().
Member Data Documentation
current_pose_
geometry_msgs::PoseStamped mpc_follower_wrapper::MPCFollowerWrapper::current_pose_ private
Definition at line 81 of file mpc_follower_wrapper.hpp.
Referenced by CurrentPoseHandler().
discovery_pub_timer_
ros::Timer mpc_follower_wrapper::MPCFollowerWrapper::discovery_pub_timer_ private
Definition at line 86 of file mpc_follower_wrapper.hpp.
Referenced by Initialize().
mpc_plugin_discovery_pub_
ros::Publisher mpc_follower_wrapper::MPCFollowerWrapper::mpc_plugin_discovery_pub_ private
Definition at line 76 of file mpc_follower_wrapper.hpp.
Referenced by Initialize().
mpcww
MPCFollowerWrapperWorker mpc_follower_wrapper::MPCFollowerWrapper::mpcww private
Definition at line 89 of file mpc_follower_wrapper.hpp.
Referenced by TrajectoryPlanPoseHandler().
nh_
ros::CARMANodeHandle& mpc_follower_wrapper::MPCFollowerWrapper::nh_ private
Definition at line 74 of file mpc_follower_wrapper.hpp.
Referenced by Initialize().
plugin_discovery_msg_
cav_msgs::Plugin mpc_follower_wrapper::MPCFollowerWrapper::plugin_discovery_msg_ private
Definition at line 79 of file mpc_follower_wrapper.hpp.
Referenced by Initialize().
pose_sub
ros::Subscriber mpc_follower_wrapper::MPCFollowerWrapper::pose_sub
Definition at line 64 of file mpc_follower_wrapper.hpp.
trajectory_plan_sub
ros::Subscriber mpc_follower_wrapper::MPCFollowerWrapper::trajectory_plan_sub
Definition at line 62 of file mpc_follower_wrapper.hpp.
Referenced by Initialize().
way_points_pub_
ros::Publisher mpc_follower_wrapper::MPCFollowerWrapper::way_points_pub_ private
Definition at line 85 of file mpc_follower_wrapper.hpp.
Referenced by Initialize(), and PublisherForWayPoints().
The documentation for this class was generated from the following files:
mpc_follower_wrapper/include/mpc_follower_wrapper/mpc_follower_wrapper.hpp
mpc_follower_wrapper/src/mpc_follower_wrapper.cpp