Carma-platform: GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType > Class Template Reference
GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType > Class Template Reference
Public Types
typedef CharType Ch
Public Member Functions
StackStream (internal::Stack< StackAllocator > &stack)
RAPIDJSON_FORCEINLINE void Put (Ch c)
RAPIDJSON_FORCEINLINE void * Push (SizeType count)
size_t Length () const
Ch * Pop ()
Private Member Functions
StackStream (const StackStream &)
StackStream & operator= (const StackStream &)
Private Attributes
internal::Stack< StackAllocator > & stack_
SizeType length_
Detailed Description
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator>
template<typename CharType>
class GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >
Definition at line 927 of file reader.h.
Member Typedef Documentation
Ch
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename CharType > typedef CharType GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Ch
Definition at line 929 of file reader.h.
Constructor & Destructor Documentation
StackStream() [1/2]
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename CharType > GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::StackStream (internal::Stack< StackAllocator > & stack) inline
Definition at line 931 of file reader.h.
: stack_(stack), length_(0) {}
StackStream() [2/2]
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename CharType > GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::StackStream (const StackStream< CharType > &) private
Member Function Documentation
Length()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename CharType > size_t GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Length () const inline
Definition at line 942 of file reader.h.
{ return length_; }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::length_.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseNumber(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseString().
operator=()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename CharType > StackStream & GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::operator= (const StackStream< CharType > &) private
Pop()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename CharType > Ch * GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Pop () inline
Definition at line 944 of file reader.h.
                  {
            return stack_.template Pop<Ch>(length_);
        }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::length_, and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::stack_.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseNumber(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseString().
Push()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename CharType > RAPIDJSON_FORCEINLINE void * GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Push (SizeType count) inline
Definition at line 937 of file reader.h.
{
            length_ += count;
            return stack_.template Push<Ch>(count);
        }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::length_, and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::stack_.
Put()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename CharType > RAPIDJSON_FORCEINLINE void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Put (Ch c) inline
Definition at line 932 of file reader.h.
{
            *stack_.template Push<Ch>() = c;
            ++length_;
        }
References process_traj_logs::c, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::length_, and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::stack_.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseNumber().
Member Data Documentation
length_
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename CharType > SizeType GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::length_ private
Definition at line 953 of file reader.h.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Length(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Pop(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Push(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Put().
stack_
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename CharType > internal::Stack<StackAllocator>& GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::stack_ private
Definition at line 952 of file reader.h.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Pop(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Push(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Put().
The documentation for this class was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/reader.h