Carma-platform: GenericReader< SourceEncoding, TargetEncoding, StackAllocator > Class Template Reference
GenericReader< SourceEncoding, TargetEncoding, StackAllocator > Class Template Reference
SAX-style JSON parser. Use Reader for UTF8 encoding and default allocator.
#include <reader.h>
Classes
struct ClearStackOnExit
class NumberStream
class NumberStream< InputStream, false, false >
class NumberStream< InputStream, true, false >
class NumberStream< InputStream, true, true >
class StackStream
Public Types
typedef SourceEncoding::Ch Ch
SourceEncoding character type.
Public Member Functions
GenericReader (StackAllocator *stackAllocator=0, size_t stackCapacity=kDefaultStackCapacity)
Constructor.
template<unsigned parseFlags, typename InputStream , typename Handler >
ParseResult Parse (InputStream &is, Handler &handler)
Parse JSON text.
template<typename InputStream , typename Handler >
ParseResult Parse (InputStream &is, Handler &handler)
Parse JSON text (with kParseDefaultFlags)
void IterativeParseInit ()
Initialize JSON text token-by-token parsing.
template<unsigned parseFlags, typename InputStream , typename Handler >
bool IterativeParseNext (InputStream &is, Handler &handler)
Parse one token from JSON text.
RAPIDJSON_FORCEINLINE bool IterativeParseComplete ()
Check if token-by-token parsing JSON text is complete.
bool HasParseError () const
Whether a parse error has occured in the last parsing.
ParseErrorCode GetParseErrorCode () const
Get the ParseErrorCode of last parsing.
size_t GetErrorOffset () const
Get the position of last parsing error in input, 0 otherwise.
Protected Member Functions
void SetParseError (ParseErrorCode code, size_t offset)
Private Types
enum IterativeParsingState {
IterativeParsingFinishState = 0 , IterativeParsingErrorState , IterativeParsingStartState , IterativeParsingObjectInitialState ,
IterativeParsingMemberKeyState , IterativeParsingMemberValueState , IterativeParsingObjectFinishState , IterativeParsingArrayInitialState ,
IterativeParsingElementState , IterativeParsingArrayFinishState , IterativeParsingValueState , IterativeParsingElementDelimiterState ,
IterativeParsingMemberDelimiterState , IterativeParsingKeyValueDelimiterState , cIterativeParsingStateCount
}
enum Token {
LeftBracketToken = 0 , RightBracketToken , LeftCurlyBracketToken , RightCurlyBracketToken ,
CommaToken , ColonToken , StringToken , FalseToken ,
TrueToken , NullToken , NumberToken , kTokenCount
}
Private Member Functions
GenericReader (const GenericReader &)
GenericReader & operator= (const GenericReader &)
void ClearStack ()
template<unsigned parseFlags, typename InputStream >
void SkipWhitespaceAndComments (InputStream &is)
template<unsigned parseFlags, typename InputStream , typename Handler >
void ParseObject (InputStream &is, Handler &handler)
template<unsigned parseFlags, typename InputStream , typename Handler >
void ParseArray (InputStream &is, Handler &handler)
template<unsigned parseFlags, typename InputStream , typename Handler >
void ParseNull (InputStream &is, Handler &handler)
template<unsigned parseFlags, typename InputStream , typename Handler >
void ParseTrue (InputStream &is, Handler &handler)
template<unsigned parseFlags, typename InputStream , typename Handler >
void ParseFalse (InputStream &is, Handler &handler)
template<typename InputStream >
unsigned ParseHex4 (InputStream &is, size_t escapeOffset)
template<unsigned parseFlags, typename InputStream , typename Handler >
void ParseString (InputStream &is, Handler &handler, bool isKey=false)
template<unsigned parseFlags, typename SEncoding , typename TEncoding , typename InputStream , typename OutputStream >
RAPIDJSON_FORCEINLINE void ParseStringToStream (InputStream &is, OutputStream &os)
template<unsigned parseFlags, typename InputStream , typename Handler >
void ParseNumber (InputStream &is, Handler &handler)
template<unsigned parseFlags, typename InputStream , typename Handler >
void ParseValue (InputStream &is, Handler &handler)
RAPIDJSON_FORCEINLINE Token Tokenize (Ch c)
RAPIDJSON_FORCEINLINE IterativeParsingState Predict (IterativeParsingState state, Token token)
template<unsigned parseFlags, typename InputStream , typename Handler >
RAPIDJSON_FORCEINLINE IterativeParsingState Transit (IterativeParsingState src, Token token, IterativeParsingState dst, InputStream &is, Handler &handler)
template<typename InputStream >
void HandleError (IterativeParsingState src, InputStream &is)
RAPIDJSON_FORCEINLINE bool IsIterativeParsingDelimiterState (IterativeParsingState s)
RAPIDJSON_FORCEINLINE bool IsIterativeParsingCompleteState (IterativeParsingState s)
template<unsigned parseFlags, typename InputStream , typename Handler >
ParseResult IterativeParse (InputStream &is, Handler &handler)
Static Private Member Functions
template<typename InputStream >
static RAPIDJSON_FORCEINLINE bool Consume (InputStream &is, typename InputStream::Ch expect)
template<typename InputStream , typename OutputStream >
static RAPIDJSON_FORCEINLINE void ScanCopyUnescapedString (InputStream &, OutputStream &)
Private Attributes
internal::Stack< StackAllocator > stack_
A stack for storing decoded string temporarily during non-destructive parsing.
ParseResult parseResult_
IterativeParsingState state_
Static Private Attributes
static const size_t kDefaultStackCapacity = 256
Default stack capacity in bytes for storing a single decoded string.
Detailed Description
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator>
class GenericReader< SourceEncoding, TargetEncoding, StackAllocator >
SAX-style JSON parser. Use Reader for UTF8 encoding and default allocator.
GenericReader parses JSON text from a stream, and send events synchronously to an object implementing Handler concept.
It needs to allocate a stack for storing a single decoded string during non-destructive parsing.
For in-situ parsing, the decoded string is directly written to the source text string, no temporary buffer is required.
A GenericReader object can be reused for parsing multiple JSON text.
Template Parameters
SourceEncoding Encoding of the input stream.
TargetEncoding Encoding of the parse output.
StackAllocator Allocator type for stack.
Definition at line 539 of file reader.h.
Member Typedef Documentation
Ch
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> typedef SourceEncoding::Ch GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Ch
SourceEncoding character type.
Definition at line 541 of file reader.h.
Member Enumeration Documentation
IterativeParsingState
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> enum GenericReader::IterativeParsingState private
Enumerator
IterativeParsingFinishState
IterativeParsingErrorState
IterativeParsingStartState
IterativeParsingObjectInitialState
IterativeParsingMemberKeyState
IterativeParsingMemberValueState
IterativeParsingObjectFinishState
IterativeParsingArrayInitialState
IterativeParsingElementState
IterativeParsingArrayFinishState
IterativeParsingValueState
IterativeParsingElementDelimiterState
IterativeParsingMemberDelimiterState
IterativeParsingKeyValueDelimiterState
cIterativeParsingStateCount
Definition at line 1741 of file reader.h.
{
        IterativeParsingFinishState = 0, // sink states at top
        IterativeParsingErrorState,      // sink states at top
        IterativeParsingStartState,
        // Object states
        IterativeParsingObjectInitialState,
        IterativeParsingMemberKeyState,
        IterativeParsingMemberValueState,
        IterativeParsingObjectFinishState,
        // Array states
        IterativeParsingArrayInitialState,
        IterativeParsingElementState,
        IterativeParsingArrayFinishState,
        // Single value state
        IterativeParsingValueState,
        // Delimiter states (at bottom)
        IterativeParsingElementDelimiterState,
        IterativeParsingMemberDelimiterState,
        IterativeParsingKeyValueDelimiterState,
        cIterativeParsingStateCount
    };
Token
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> enum GenericReader::Token private
Enumerator
LeftBracketToken
RightBracketToken
LeftCurlyBracketToken
RightCurlyBracketToken
CommaToken
ColonToken
StringToken
FalseToken
TrueToken
NullToken
NumberToken
kTokenCount
Definition at line 1769 of file reader.h.
               {
        LeftBracketToken = 0,
        RightBracketToken,
        LeftCurlyBracketToken,
        RightCurlyBracketToken,
        CommaToken,
        ColonToken,
        StringToken,
        FalseToken,
        TrueToken,
        NullToken,
        NumberToken,
        kTokenCount
    };
Constructor & Destructor Documentation
GenericReader() [1/2]
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GenericReader (StackAllocator * stackAllocator = 0, size_t stackCapacity = kDefaultStackCapacity) inline
Constructor.
Parameters
stackAllocator Optional allocator for allocating stack memory. (Only use for non-destructive parsing)
stackCapacity stack capacity in bytes for storing a single decoded string. (Only use for non-destructive parsing)
Definition at line 547 of file reader.h.
: stack_(stackAllocator, stackCapacity), parseResult_() {}
GenericReader() [2/2]
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GenericReader (const GenericReader< SourceEncoding, TargetEncoding, StackAllocator > &) private
Member Function Documentation
ClearStack()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ClearStack () inline private
Definition at line 697 of file reader.h.
{ stack_.Clear(); }
References internal::Stack< Allocator >::Clear(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::stack_.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ClearStackOnExit::~ClearStackOnExit().
Consume()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > static RAPIDJSON_FORCEINLINE bool GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Consume (InputStream & is, typename InputStream::Ch expect) inline static private
Definition at line 894 of file reader.h.
{
        if (RAPIDJSON_LIKELY(is.Peek() == expect)) {
            is.Take();
            return true;
        }
        else
            return false;
    }
References RAPIDJSON_LIKELY.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseArray(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseFalse(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseNull(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseNumber(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseObject(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseStringToStream(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseTrue(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::SkipWhitespaceAndComments().
GetErrorOffset()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> size_t GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetErrorOffset () const inline
Get the position of last parsing error in input, 0 otherwise.
Definition at line 687 of file reader.h.
{ return parseResult_.Offset(); }
References ParseResult::Offset(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::parseResult_.
GetParseErrorCode()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> ParseErrorCode GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetParseErrorCode () const inline
Get the ParseErrorCode of last parsing.
Definition at line 684 of file reader.h.
{ return parseResult_.Code(); }
References ParseResult::Code(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::parseResult_.
HandleError()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HandleError (IterativeParsingState src, InputStream & is) inline private
Definition at line 2134 of file reader.h.
{
        if (HasParseError()) {
            // Error flag has been set.
            return;
        }
        switch (src) {
        case IterativeParsingStartState:            RAPIDJSON_PARSE_ERROR(kParseErrorDocumentEmpty, is.Tell()); return;
        case IterativeParsingFinishState:           RAPIDJSON_PARSE_ERROR(kParseErrorDocumentRootNotSingular, is.Tell()); return;
        case IterativeParsingObjectInitialState:
        case IterativeParsingMemberDelimiterState:  RAPIDJSON_PARSE_ERROR(kParseErrorObjectMissName, is.Tell()); return;
        case IterativeParsingMemberKeyState:        RAPIDJSON_PARSE_ERROR(kParseErrorObjectMissColon, is.Tell()); return;
        case IterativeParsingMemberValueState:      RAPIDJSON_PARSE_ERROR(kParseErrorObjectMissCommaOrCurlyBracket, is.Tell()); return;
        case IterativeParsingKeyValueDelimiterState:
        case IterativeParsingArrayInitialState:
        case IterativeParsingElementDelimiterState: RAPIDJSON_PARSE_ERROR(kParseErrorValueInvalid, is.Tell()); return;
        default: RAPIDJSON_ASSERT(src == IterativeParsingElementState); RAPIDJSON_PARSE_ERROR(kParseErrorArrayMissCommaOrSquareBracket, is.Tell()); return;
        }
    }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HasParseError(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingArrayInitialState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingElementDelimiterState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingElementState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingFinishState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingKeyValueDelimiterState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingMemberDelimiterState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingMemberKeyState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingMemberValueState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingObjectInitialState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingStartState, kParseErrorArrayMissCommaOrSquareBracket, kParseErrorDocumentEmpty, kParseErrorDocumentRootNotSingular, kParseErrorObjectMissColon, kParseErrorObjectMissCommaOrCurlyBracket, kParseErrorObjectMissName, kParseErrorValueInvalid, RAPIDJSON_ASSERT, and RAPIDJSON_PARSE_ERROR.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParse(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext().
HasParseError()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> bool GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HasParseError () const inline
Whether a parse error has occured in the last parsing.
Definition at line 681 of file reader.h.
{ return parseResult_.IsError(); }
References ParseResult::IsError(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::parseResult_.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HandleError(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Transit().
IsIterativeParsingCompleteState()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> RAPIDJSON_FORCEINLINE bool GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IsIterativeParsingCompleteState (IterativeParsingState s) inline private
Definition at line 2158 of file reader.h.
{
        return s <= IterativeParsingErrorState;
    }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingErrorState.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseComplete(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext().
IsIterativeParsingDelimiterState()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> RAPIDJSON_FORCEINLINE bool GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IsIterativeParsingDelimiterState (IterativeParsingState s) inline private
Definition at line 2154 of file reader.h.
{
        return s >= IterativeParsingElementDelimiterState;
    }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingElementDelimiterState.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext().
IterativeParse()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > ParseResult GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParse (InputStream & is, Handler & handler) inline private
Definition at line 2163 of file reader.h.
{
        parseResult_.Clear();
        ClearStackOnExit scope(*this);
        IterativeParsingState state = IterativeParsingStartState;
        SkipWhitespaceAndComments<parseFlags>(is);
        RAPIDJSON_PARSE_ERROR_EARLY_RETURN(parseResult_);
        while (is.Peek() != '\0') {
            Token t = Tokenize(is.Peek());
            IterativeParsingState n = Predict(state, t);
            IterativeParsingState d = Transit<parseFlags>(state, t, n, is, handler);
            if (d == IterativeParsingErrorState) {
                HandleError(state, is);
                break;
            }
            state = d;
            // Do not further consume streams if a root JSON has been parsed.
            if ((parseFlags & kParseStopWhenDoneFlag) && state == IterativeParsingFinishState)
                break;
            SkipWhitespaceAndComments<parseFlags>(is);
            RAPIDJSON_PARSE_ERROR_EARLY_RETURN(parseResult_);
        }
        // Handle the end of file.
        if (state != IterativeParsingFinishState)
            HandleError(state, is);
        return parseResult_;
    }
References ParseResult::Clear(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HandleError(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingErrorState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingFinishState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingStartState, kParseStopWhenDoneFlag, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::parseResult_, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Predict(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Tokenize().
IterativeParseComplete()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> RAPIDJSON_FORCEINLINE bool GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseComplete () inline
Check if token-by-token parsing JSON text is complete.
Returns
Whether the JSON has been fully decoded.
Definition at line 676 of file reader.h.
{
        return IsIterativeParsingCompleteState(state_);
    }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IsIterativeParsingCompleteState(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::state_.
IterativeParseInit()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseInit () inline
Initialize JSON text token-by-token parsing.
Definition at line 606 of file reader.h.
{
        parseResult_.Clear();
        state_ = IterativeParsingStartState;
    }
References ParseResult::Clear(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingStartState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::parseResult_, and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::state_.
IterativeParseNext()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > bool GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext (InputStream & is, Handler & handler) inline
Parse one token from JSON text.
Template Parameters
InputStream Type of input stream, implementing Stream concept
Handler Type of handler, implementing Handler concept.
Parameters
is Input stream to be parsed.
handler The handler to receive events.
Returns
Whether the parsing is successful.
Definition at line 619 of file reader.h.
{
        while (RAPIDJSON_LIKELY(is.Peek() != '\0')) {
            SkipWhitespaceAndComments<parseFlags>(is);
            Token t = Tokenize(is.Peek());
            IterativeParsingState n = Predict(state_, t);
            IterativeParsingState d = Transit<parseFlags>(state_, t, n, is, handler);
            // If we've finished or hit an error...
            if (RAPIDJSON_UNLIKELY(IsIterativeParsingCompleteState(d))) {
                // Report errors.
                if (d == IterativeParsingErrorState) {
                    HandleError(state_, is);
                    return false;
                }
                // Transition to the finish state.
                RAPIDJSON_ASSERT(d == IterativeParsingFinishState);
                state_ = d;
                // If StopWhenDone is not set...
                if (!(parseFlags & kParseStopWhenDoneFlag)) {
                    // ... and extra non-whitespace data is found...
                    SkipWhitespaceAndComments<parseFlags>(is);
                    if (is.Peek() != '\0') {
                        // ... this is considered an error.
                        HandleError(state_, is);
                        return false;
                    }
                }
                // Success! We are done!
                return true;
            }
            // Transition to the new state.
            state_ = d;
            // If we parsed anything other than a delimiter, we invoked the handler, so we can return true now.
            if (!IsIterativeParsingDelimiterState(n))
                return true;
        }
        // We reached the end of file.
        stack_.Clear();
        if (state_ != IterativeParsingFinishState) {
            HandleError(state_, is);
            return false;
        }
        return true;
    }
References internal::Stack< Allocator >::Clear(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HandleError(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IsIterativeParsingCompleteState(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IsIterativeParsingDelimiterState(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingErrorState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingFinishState, kParseStopWhenDoneFlag, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Predict(), RAPIDJSON_ASSERT, RAPIDJSON_LIKELY, RAPIDJSON_UNLIKELY, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::stack_, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::state_, and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Tokenize().
operator=()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> GenericReader & GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::operator= (const GenericReader< SourceEncoding, TargetEncoding, StackAllocator > &) private
Parse() [1/2]
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > ParseResult GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse (InputStream & is, Handler & handler) inline
Parse JSON text.
Template Parameters
parseFlags Combination of ParseFlag.
InputStream Type of input stream, implementing Stream concept.
Handler Type of handler, implementing Handler concept.
Parameters
is Input stream to be parsed.
handler The handler to receive events.
Returns
Whether the parsing is successful.
Definition at line 558 of file reader.h.
{
        if (parseFlags & kParseIterativeFlag)
            return IterativeParse<parseFlags>(is, handler);
        parseResult_.Clear();
        ClearStackOnExit scope(*this);
        SkipWhitespaceAndComments<parseFlags>(is);
        RAPIDJSON_PARSE_ERROR_EARLY_RETURN(parseResult_);
        if (RAPIDJSON_UNLIKELY(is.Peek() == '\0')) {
            RAPIDJSON_PARSE_ERROR_NORETURN(kParseErrorDocumentEmpty, is.Tell());
            RAPIDJSON_PARSE_ERROR_EARLY_RETURN(parseResult_);
        }
        else {
            ParseValue<parseFlags>(is, handler);
            RAPIDJSON_PARSE_ERROR_EARLY_RETURN(parseResult_);
            if (!(parseFlags & kParseStopWhenDoneFlag)) {
                SkipWhitespaceAndComments<parseFlags>(is);
                RAPIDJSON_PARSE_ERROR_EARLY_RETURN(parseResult_);
                if (RAPIDJSON_UNLIKELY(is.Peek() != '\0')) {
                    RAPIDJSON_PARSE_ERROR_NORETURN(kParseErrorDocumentRootNotSingular, is.Tell());
                    RAPIDJSON_PARSE_ERROR_EARLY_RETURN(parseResult_);
                }
            }
        }
        return parseResult_;
    }
References ParseResult::Clear(), kParseErrorDocumentEmpty, kParseErrorDocumentRootNotSingular, kParseIterativeFlag, kParseStopWhenDoneFlag, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::parseResult_, RAPIDJSON_PARSE_ERROR_NORETURN, and RAPIDJSON_UNLIKELY.
Parse() [2/2]
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream , typename Handler > ParseResult GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse (InputStream & is, Handler & handler) inline
Parse JSON text (with kParseDefaultFlags)
Template Parameters
InputStream Type of input stream, implementing Stream concept
Handler Type of handler, implementing Handler concept.
Parameters
is Input stream to be parsed.
handler The handler to receive events.
Returns
Whether the parsing is successful.
Definition at line 599 of file reader.h.
{
        return Parse<kParseDefaultFlags>(is, handler);
    }
ParseArray()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseArray (InputStream & is, Handler & handler) inline private
Definition at line 807 of file reader.h.
{
        RAPIDJSON_ASSERT(is.Peek() == '[');
        is.Take();  // Skip '['
        if (RAPIDJSON_UNLIKELY(!handler.StartArray()))
            RAPIDJSON_PARSE_ERROR(kParseErrorTermination, is.Tell());
        SkipWhitespaceAndComments<parseFlags>(is);
        RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
        if (Consume(is, ']')) {
            if (RAPIDJSON_UNLIKELY(!handler.EndArray(0))) // empty array
                RAPIDJSON_PARSE_ERROR(kParseErrorTermination, is.Tell());
            return;
        }
        for (SizeType elementCount = 0;;) {
            ParseValue<parseFlags>(is, handler);
            RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
            ++elementCount;
            SkipWhitespaceAndComments<parseFlags>(is);
            RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
            if (Consume(is, ',')) {
                SkipWhitespaceAndComments<parseFlags>(is);
                RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
            }
            else if (Consume(is, ']')) {
                if (RAPIDJSON_UNLIKELY(!handler.EndArray(elementCount)))
                    RAPIDJSON_PARSE_ERROR(kParseErrorTermination, is.Tell());
                return;
            }
            else
                RAPIDJSON_PARSE_ERROR(kParseErrorArrayMissCommaOrSquareBracket, is.Tell());
            if (parseFlags & kParseTrailingCommasFlag) {
                if (is.Peek() == ']') {
                    if (RAPIDJSON_UNLIKELY(!handler.EndArray(elementCount)))
                        RAPIDJSON_PARSE_ERROR(kParseErrorTermination, is.Tell());
                    is.Take();
                    return;
                }
            }
        }
    }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Consume(), kParseErrorArrayMissCommaOrSquareBracket, kParseErrorTermination, kParseTrailingCommasFlag, RAPIDJSON_ASSERT, RAPIDJSON_PARSE_ERROR, RAPIDJSON_UNLIKELY, and SizeType.
ParseFalse()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseFalse (InputStream & is, Handler & handler) inline private
Definition at line 881 of file reader.h.
{
        RAPIDJSON_ASSERT(is.Peek() == 'f');
        is.Take();
        if (RAPIDJSON_LIKELY(Consume(is, 'a') && Consume(is, 'l') && Consume(is, 's') && Consume(is, 'e'))) {
            if (RAPIDJSON_UNLIKELY(!handler.Bool(false)))
                RAPIDJSON_PARSE_ERROR(kParseErrorTermination, is.Tell());
        }
        else
            RAPIDJSON_PARSE_ERROR(kParseErrorValueInvalid, is.Tell());
    }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Consume(), kParseErrorTermination, kParseErrorValueInvalid, RAPIDJSON_ASSERT, RAPIDJSON_LIKELY, RAPIDJSON_PARSE_ERROR, and RAPIDJSON_UNLIKELY.
ParseHex4()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > unsigned GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseHex4 (InputStream & is, size_t escapeOffset) inline private
Definition at line 905 of file reader.h.
{
        unsigned codepoint = 0;
        for (int i = 0; i < 4; i++) {
            Ch c = is.Peek();
            codepoint <<= 4;
            codepoint += static_cast<unsigned>(c);
            if (c >= '0' && c <= '9')
                codepoint -= '0';
            else if (c >= 'A' && c <= 'F')
                codepoint -= 'A' - 10;
            else if (c >= 'a' && c <= 'f')
                codepoint -= 'a' - 10;
            else {
                RAPIDJSON_PARSE_ERROR_NORETURN(kParseErrorStringUnicodeEscapeInvalidHex, escapeOffset);
                RAPIDJSON_PARSE_ERROR_EARLY_RETURN(0);
            }
            is.Take();
        }
        return codepoint;
    }
References process_traj_logs::c, process_bag::i, kParseErrorStringUnicodeEscapeInvalidHex, and RAPIDJSON_PARSE_ERROR_NORETURN.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseStringToStream().
ParseNull()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseNull (InputStream & is, Handler & handler) inline private
Definition at line 855 of file reader.h.
{
        RAPIDJSON_ASSERT(is.Peek() == 'n');
        is.Take();
        if (RAPIDJSON_LIKELY(Consume(is, 'u') && Consume(is, 'l') && Consume(is, 'l'))) {
            if (RAPIDJSON_UNLIKELY(!handler.Null()))
                RAPIDJSON_PARSE_ERROR(kParseErrorTermination, is.Tell());
        }
        else
            RAPIDJSON_PARSE_ERROR(kParseErrorValueInvalid, is.Tell());
    }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Consume(), kParseErrorTermination, kParseErrorValueInvalid, RAPIDJSON_ASSERT, RAPIDJSON_LIKELY, RAPIDJSON_PARSE_ERROR, and RAPIDJSON_UNLIKELY.
ParseNumber()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseNumber (InputStream & is, Handler & handler) inline private
Definition at line 1455 of file reader.h.
{
        internal::StreamLocalCopy<InputStream> copy(is);
        NumberStream<InputStream,
            ((parseFlags & kParseNumbersAsStringsFlag) != 0) ?
                ((parseFlags & kParseInsituFlag) == 0) :
                ((parseFlags & kParseFullPrecisionFlag) != 0),
            (parseFlags & kParseNumbersAsStringsFlag) != 0 &&
                (parseFlags & kParseInsituFlag) == 0> s(*this, copy.s);
        size_t startOffset = s.Tell();
        double d = 0.0;
        bool useNanOrInf = false;
        // Parse minus
        bool minus = Consume(s, '-');
        // Parse int: zero / ( digit1-9 *DIGIT )
        unsigned i = 0;
        uint64_t i64 = 0;
        bool use64bit = false;
        int significandDigit = 0;
        if (RAPIDJSON_UNLIKELY(s.Peek() == '0')) {
            i = 0;
            s.TakePush();
        }
        else if (RAPIDJSON_LIKELY(s.Peek() >= '1' && s.Peek() <= '9')) {
            i = static_cast<unsigned>(s.TakePush() - '0');
            if (minus)
                while (RAPIDJSON_LIKELY(s.Peek() >= '0' && s.Peek() <= '9')) {
                    if (RAPIDJSON_UNLIKELY(i >= 214748364)) { // 2^31 = 2147483648
                        if (RAPIDJSON_LIKELY(i != 214748364 || s.Peek() > '8')) {
                            i64 = i;
                            use64bit = true;
                            break;
                        }
                    }
                    i = i * 10 + static_cast<unsigned>(s.TakePush() - '0');
                    significandDigit++;
                }
            else
                while (RAPIDJSON_LIKELY(s.Peek() >= '0' && s.Peek() <= '9')) {
                    if (RAPIDJSON_UNLIKELY(i >= 429496729)) { // 2^32 - 1 = 4294967295
                        if (RAPIDJSON_LIKELY(i != 429496729 || s.Peek() > '5')) {
                            i64 = i;
                            use64bit = true;
                            break;
                        }
                    }
                    i = i * 10 + static_cast<unsigned>(s.TakePush() - '0');
                    significandDigit++;
                }
        }
        // Parse NaN or Infinity here
        else if ((parseFlags & kParseNanAndInfFlag) && RAPIDJSON_LIKELY((s.Peek() == 'I' || s.Peek() == 'N'))) {
            if (Consume(s, 'N')) {
                if (Consume(s, 'a') && Consume(s, 'N')) {
                    d = std::numeric_limits<double>::quiet_NaN();
                    useNanOrInf = true;
                }
            }
            else if (RAPIDJSON_LIKELY(Consume(s, 'I'))) {
                if (Consume(s, 'n') && Consume(s, 'f')) {
                    d = (minus ? -std::numeric_limits<double>::infinity() : std::numeric_limits<double>::infinity());
                    useNanOrInf = true;
                    if (RAPIDJSON_UNLIKELY(s.Peek() == 'i' && !(Consume(s, 'i') && Consume(s, 'n')
                                                                && Consume(s, 'i') && Consume(s, 't') && Consume(s, 'y')))) {
                        RAPIDJSON_PARSE_ERROR(kParseErrorValueInvalid, s.Tell());
                    }
                }
            }
            if (RAPIDJSON_UNLIKELY(!useNanOrInf)) {
                RAPIDJSON_PARSE_ERROR(kParseErrorValueInvalid, s.Tell());
            }
        }
        else
            RAPIDJSON_PARSE_ERROR(kParseErrorValueInvalid, s.Tell());
        // Parse 64bit int
        bool useDouble = false;
        if (use64bit) {
            if (minus)
                while (RAPIDJSON_LIKELY(s.Peek() >= '0' && s.Peek() <= '9')) {
                     if (RAPIDJSON_UNLIKELY(i64 >= RAPIDJSON_UINT64_C2(0x0CCCCCCC, 0xCCCCCCCC))) // 2^63 = 9223372036854775808
                        if (RAPIDJSON_LIKELY(i64 != RAPIDJSON_UINT64_C2(0x0CCCCCCC, 0xCCCCCCCC) || s.Peek() > '8')) {
                            d = static_cast<double>(i64);
                            useDouble = true;
                            break;
                        }
                    i64 = i64 * 10 + static_cast<unsigned>(s.TakePush() - '0');
                    significandDigit++;
                }
            else
                while (RAPIDJSON_LIKELY(s.Peek() >= '0' && s.Peek() <= '9')) {
                    if (RAPIDJSON_UNLIKELY(i64 >= RAPIDJSON_UINT64_C2(0x19999999, 0x99999999))) // 2^64 - 1 = 18446744073709551615
                        if (RAPIDJSON_LIKELY(i64 != RAPIDJSON_UINT64_C2(0x19999999, 0x99999999) || s.Peek() > '5')) {
                            d = static_cast<double>(i64);
                            useDouble = true;
                            break;
                        }
                    i64 = i64 * 10 + static_cast<unsigned>(s.TakePush() - '0');
                    significandDigit++;
                }
        }
        // Force double for big integer
        if (useDouble) {
            while (RAPIDJSON_LIKELY(s.Peek() >= '0' && s.Peek() <= '9')) {
                if (RAPIDJSON_UNLIKELY(d >= 1.7976931348623157e307)) // DBL_MAX / 10.0
                    RAPIDJSON_PARSE_ERROR(kParseErrorNumberTooBig, startOffset);
                d = d * 10 + (s.TakePush() - '0');
            }
        }
        // Parse frac = decimal-point 1*DIGIT
        int expFrac = 0;
        size_t decimalPosition;
        if (Consume(s, '.')) {
            decimalPosition = s.Length();
            if (RAPIDJSON_UNLIKELY(!(s.Peek() >= '0' && s.Peek() <= '9')))
                RAPIDJSON_PARSE_ERROR(kParseErrorNumberMissFraction, s.Tell());
            if (!useDouble) {
#if RAPIDJSON_64BIT
                // Use i64 to store significand in 64-bit architecture
                if (!use64bit)
                    i64 = i;
                while (RAPIDJSON_LIKELY(s.Peek() >= '0' && s.Peek() <= '9')) {
                    if (i64 > RAPIDJSON_UINT64_C2(0x1FFFFF, 0xFFFFFFFF)) // 2^53 - 1 for fast path
                        break;
                    else {
                        i64 = i64 * 10 + static_cast<unsigned>(s.TakePush() - '0');
                        --expFrac;
                        if (i64 != 0)
                            significandDigit++;
                    }
                }
                d = static_cast<double>(i64);
#else
                // Use double to store significand in 32-bit architecture
                d = static_cast<double>(use64bit ? i64 : i);
#endif
                useDouble = true;
            }
            while (RAPIDJSON_LIKELY(s.Peek() >= '0' && s.Peek() <= '9')) {
                if (significandDigit < 17) {
                    d = d * 10.0 + (s.TakePush() - '0');
                    --expFrac;
                    if (RAPIDJSON_LIKELY(d > 0.0))
                        significandDigit++;
                }
                else
                    s.TakePush();
            }
        }
        else
            decimalPosition = s.Length(); // decimal position at the end of integer.
        // Parse exp = e [ minus / plus ] 1*DIGIT
        int exp = 0;
        if (Consume(s, 'e') || Consume(s, 'E')) {
            if (!useDouble) {
                d = static_cast<double>(use64bit ? i64 : i);
                useDouble = true;
            }
            bool expMinus = false;
            if (Consume(s, '+'))
                ;
            else if (Consume(s, '-'))
                expMinus = true;
            if (RAPIDJSON_LIKELY(s.Peek() >= '0' && s.Peek() <= '9')) {
                exp = static_cast<int>(s.Take() - '0');
                if (expMinus) {
                    while (RAPIDJSON_LIKELY(s.Peek() >= '0' && s.Peek() <= '9')) {
                        exp = exp * 10 + static_cast<int>(s.Take() - '0');
                        if (exp >= 214748364) {                         // Issue #313: prevent overflow exponent
                            while (RAPIDJSON_UNLIKELY(s.Peek() >= '0' && s.Peek() <= '9'))  // Consume the rest of exponent
                                s.Take();
                        }
                    }
                }
                else {  // positive exp
                    int maxExp = 308 - expFrac;
                    while (RAPIDJSON_LIKELY(s.Peek() >= '0' && s.Peek() <= '9')) {
                        exp = exp * 10 + static_cast<int>(s.Take() - '0');
                        if (RAPIDJSON_UNLIKELY(exp > maxExp))
                            RAPIDJSON_PARSE_ERROR(kParseErrorNumberTooBig, startOffset);
                    }
                }
            }
            else
                RAPIDJSON_PARSE_ERROR(kParseErrorNumberMissExponent, s.Tell());
            if (expMinus)
                exp = -exp;
        }
        // Finish parsing, call event according to the type of number.
        bool cont = true;
        if (parseFlags & kParseNumbersAsStringsFlag) {
            if (parseFlags & kParseInsituFlag) {
                s.Pop();  // Pop stack no matter if it will be used or not.
                typename InputStream::Ch* head = is.PutBegin();
                const size_t length = s.Tell() - startOffset;
                RAPIDJSON_ASSERT(length <= 0xFFFFFFFF);
                // unable to insert the \0 character here, it will erase the comma after this number
                const typename TargetEncoding::Ch* const str = reinterpret_cast<typename TargetEncoding::Ch*>(head);
                cont = handler.RawNumber(str, SizeType(length), false);
            }
            else {
                SizeType numCharsToCopy = static_cast<SizeType>(s.Length());
                StringStream srcStream(s.Pop());
                StackStream<typename TargetEncoding::Ch> dstStream(stack_);
                while (numCharsToCopy--) {
                    Transcoder<UTF8<>, TargetEncoding>::Transcode(srcStream, dstStream);
                }
                dstStream.Put('\0');
                const typename TargetEncoding::Ch* str = dstStream.Pop();
                const SizeType length = static_cast<SizeType>(dstStream.Length()) - 1;
                cont = handler.RawNumber(str, SizeType(length), true);
            }
        }
        else {
           size_t length = s.Length();
           const char* decimal = s.Pop();  // Pop stack no matter if it will be used or not.
           if (useDouble) {
               int p = exp + expFrac;
               if (parseFlags & kParseFullPrecisionFlag)
                   d = internal::StrtodFullPrecision(d, p, decimal, length, decimalPosition, exp);
               else
                   d = internal::StrtodNormalPrecision(d, p);
               cont = handler.Double(minus ? -d : d);
           }
           else if (useNanOrInf) {
               cont = handler.Double(d);
           }
           else {
               if (use64bit) {
                   if (minus)
                       cont = handler.Int64(static_cast<int64_t>(~i64 + 1));
                   else
                       cont = handler.Uint64(i64);
               }
               else {
                   if (minus)
                       cont = handler.Int(static_cast<int32_t>(~i + 1));
                   else
                       cont = handler.Uint(i);
               }
           }
        }
        if (RAPIDJSON_UNLIKELY(!cont))
            RAPIDJSON_PARSE_ERROR(kParseErrorTermination, startOffset);
    }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Consume(), process_bag::i, kParseErrorNumberMissExponent, kParseErrorNumberMissFraction, kParseErrorNumberTooBig, kParseErrorTermination, kParseErrorValueInvalid, kParseFullPrecisionFlag, kParseInsituFlag, kParseNanAndInfFlag, kParseNumbersAsStringsFlag, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Length(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Pop(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Put(), RAPIDJSON_ASSERT, RAPIDJSON_LIKELY, RAPIDJSON_PARSE_ERROR, RAPIDJSON_UINT64_C2, RAPIDJSON_UNLIKELY, SizeType, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::stack_, internal::StrtodFullPrecision(), and internal::StrtodNormalPrecision().
ParseObject()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseObject (InputStream & is, Handler & handler) inline private
Definition at line 739 of file reader.h.
{
        RAPIDJSON_ASSERT(is.Peek() == '{');
        is.Take();  // Skip '{'
        if (RAPIDJSON_UNLIKELY(!handler.StartObject()))
            RAPIDJSON_PARSE_ERROR(kParseErrorTermination, is.Tell());
        SkipWhitespaceAndComments<parseFlags>(is);
        RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
        if (Consume(is, '}')) {
            if (RAPIDJSON_UNLIKELY(!handler.EndObject(0)))  // empty object
                RAPIDJSON_PARSE_ERROR(kParseErrorTermination, is.Tell());
            return;
        }
        for (SizeType memberCount = 0;;) {
            if (RAPIDJSON_UNLIKELY(is.Peek() != '"'))
                RAPIDJSON_PARSE_ERROR(kParseErrorObjectMissName, is.Tell());
            ParseString<parseFlags>(is, handler, true);
            RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
            SkipWhitespaceAndComments<parseFlags>(is);
            RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
            if (RAPIDJSON_UNLIKELY(!Consume(is, ':')))
                RAPIDJSON_PARSE_ERROR(kParseErrorObjectMissColon, is.Tell());
            SkipWhitespaceAndComments<parseFlags>(is);
            RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
            ParseValue<parseFlags>(is, handler);
            RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
            SkipWhitespaceAndComments<parseFlags>(is);
            RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
            ++memberCount;
            switch (is.Peek()) {
                case ',':
                    is.Take();
                    SkipWhitespaceAndComments<parseFlags>(is);
                    RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
                    break;
                case '}':
                    is.Take();
                    if (RAPIDJSON_UNLIKELY(!handler.EndObject(memberCount)))
                        RAPIDJSON_PARSE_ERROR(kParseErrorTermination, is.Tell());
                    return;
                default:
                    RAPIDJSON_PARSE_ERROR(kParseErrorObjectMissCommaOrCurlyBracket, is.Tell()); break; // This useless break is only for making warning and coverage happy
            }
            if (parseFlags & kParseTrailingCommasFlag) {
                if (is.Peek() == '}') {
                    if (RAPIDJSON_UNLIKELY(!handler.EndObject(memberCount)))
                        RAPIDJSON_PARSE_ERROR(kParseErrorTermination, is.Tell());
                    is.Take();
                    return;
                }
            }
        }
    }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Consume(), kParseErrorObjectMissColon, kParseErrorObjectMissCommaOrCurlyBracket, kParseErrorObjectMissName, kParseErrorTermination, kParseTrailingCommasFlag, RAPIDJSON_ASSERT, RAPIDJSON_PARSE_ERROR, RAPIDJSON_UNLIKELY, and SizeType.
ParseString()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseString (InputStream & is, Handler & handler, bool isKey = false) inline private
Definition at line 958 of file reader.h.
{
        internal::StreamLocalCopy<InputStream> copy(is);
        InputStream& s(copy.s);
        RAPIDJSON_ASSERT(s.Peek() == '\"');
        s.Take();  // Skip '\"'
        bool success = false;
        if (parseFlags & kParseInsituFlag) {
            typename InputStream::Ch *head = s.PutBegin();
            ParseStringToStream<parseFlags, SourceEncoding, SourceEncoding>(s, s);
            RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
            size_t length = s.PutEnd(head) - 1;
            RAPIDJSON_ASSERT(length <= 0xFFFFFFFF);
            const typename TargetEncoding::Ch* const str = reinterpret_cast<typename TargetEncoding::Ch*>(head);
            success = (isKey ? handler.Key(str, SizeType(length), false) : handler.String(str, SizeType(length), false));
        }
        else {
            StackStream<typename TargetEncoding::Ch> stackStream(stack_);
            ParseStringToStream<parseFlags, SourceEncoding, TargetEncoding>(s, stackStream);
            RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
            SizeType length = static_cast<SizeType>(stackStream.Length()) - 1;
            const typename TargetEncoding::Ch* const str = stackStream.Pop();
            success = (isKey ? handler.Key(str, length, true) : handler.String(str, length, true));
        }
        if (RAPIDJSON_UNLIKELY(!success))
            RAPIDJSON_PARSE_ERROR(kParseErrorTermination, s.Tell());
    }
References kParseErrorTermination, kParseInsituFlag, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Length(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StackStream< CharType >::Pop(), RAPIDJSON_ASSERT, RAPIDJSON_PARSE_ERROR, RAPIDJSON_UNLIKELY, SizeType, and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::stack_.
ParseStringToStream()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename SEncoding , typename TEncoding , typename InputStream , typename OutputStream > RAPIDJSON_FORCEINLINE void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseStringToStream (InputStream & is, OutputStream & os) inline private
Definition at line 990 of file reader.h.
{
#define Z16 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
        static const char escape[256] = {
            Z16, Z16, 0, 0,'\"', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,'/',
            Z16, Z16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,'\\', 0, 0, 0,
            0, 0,'\b', 0, 0, 0,'\f', 0, 0, 0, 0, 0, 0, 0,'\n', 0,
            0, 0,'\r', 0,'\t', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            Z16, Z16, Z16, Z16, Z16, Z16, Z16, Z16
        };
#undef Z16
        for (;;) {
            // Scan and copy string before "\\\"" or < 0x20. This is an optional optimzation.
            if (!(parseFlags & kParseValidateEncodingFlag))
                ScanCopyUnescapedString(is, os);
            Ch c = is.Peek();
            if (RAPIDJSON_UNLIKELY(c == '\\')) {    // Escape
                size_t escapeOffset = is.Tell();    // For invalid escaping, report the inital '\\' as error offset
                is.Take();
                Ch e = is.Peek();
                if ((sizeof(Ch) == 1 || unsigned(e) < 256) && RAPIDJSON_LIKELY(escape[static_cast<unsigned char>(e)])) {
                    is.Take();
                    os.Put(static_cast<typename TEncoding::Ch>(escape[static_cast<unsigned char>(e)]));
                }
                else if (RAPIDJSON_LIKELY(e == 'u')) {    // Unicode
                    is.Take();
                    unsigned codepoint = ParseHex4(is, escapeOffset);
                    RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
                    if (RAPIDJSON_UNLIKELY(codepoint >= 0xD800 && codepoint <= 0xDBFF)) {
                        // Handle UTF-16 surrogate pair
                        if (RAPIDJSON_UNLIKELY(!Consume(is, '\\') || !Consume(is, 'u')))
                            RAPIDJSON_PARSE_ERROR(kParseErrorStringUnicodeSurrogateInvalid, escapeOffset);
                        unsigned codepoint2 = ParseHex4(is, escapeOffset);
                        RAPIDJSON_PARSE_ERROR_EARLY_RETURN_VOID;
                        if (RAPIDJSON_UNLIKELY(codepoint2 < 0xDC00 || codepoint2 > 0xDFFF))
                            RAPIDJSON_PARSE_ERROR(kParseErrorStringUnicodeSurrogateInvalid, escapeOffset);
                        codepoint = (((codepoint - 0xD800) << 10) | (codepoint2 - 0xDC00)) + 0x10000;
                    }
                    TEncoding::Encode(os, codepoint);
                }
                else
                    RAPIDJSON_PARSE_ERROR(kParseErrorStringEscapeInvalid, escapeOffset);
            }
            else if (RAPIDJSON_UNLIKELY(c == '"')) {    // Closing double quote
                is.Take();
                os.Put('\0');   // null-terminate the string
                return;
            }
            else if (RAPIDJSON_UNLIKELY(static_cast<unsigned>(c) < 0x20)) { // RFC 4627: unescaped = %x20-21 / %x23-5B / %x5D-10FFFF
                if (c == '\0')
                    RAPIDJSON_PARSE_ERROR(kParseErrorStringMissQuotationMark, is.Tell());
                else
                    RAPIDJSON_PARSE_ERROR(kParseErrorStringInvalidEncoding, is.Tell());
            }
            else {
                size_t offset = is.Tell();
                if (RAPIDJSON_UNLIKELY((parseFlags & kParseValidateEncodingFlag ?
                    !Transcoder<SEncoding, TEncoding>::Validate(is, os) :
                    !Transcoder<SEncoding, TEncoding>::Transcode(is, os))))
                    RAPIDJSON_PARSE_ERROR(kParseErrorStringInvalidEncoding, offset);
            }
        }
    }
References process_traj_logs::c, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Consume(), kParseErrorStringEscapeInvalid, kParseErrorStringInvalidEncoding, kParseErrorStringMissQuotationMark, kParseErrorStringUnicodeSurrogateInvalid, kParseValidateEncodingFlag, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseHex4(), RAPIDJSON_LIKELY, RAPIDJSON_PARSE_ERROR, RAPIDJSON_UNLIKELY, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ScanCopyUnescapedString(), and Z16.
ParseTrue()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseTrue (InputStream & is, Handler & handler) inline private
Definition at line 868 of file reader.h.
{
        RAPIDJSON_ASSERT(is.Peek() == 't');
        is.Take();
        if (RAPIDJSON_LIKELY(Consume(is, 'r') && Consume(is, 'u') && Consume(is, 'e'))) {
            if (RAPIDJSON_UNLIKELY(!handler.Bool(true)))
                RAPIDJSON_PARSE_ERROR(kParseErrorTermination, is.Tell());
        }
        else
            RAPIDJSON_PARSE_ERROR(kParseErrorValueInvalid, is.Tell());
    }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Consume(), kParseErrorTermination, kParseErrorValueInvalid, RAPIDJSON_ASSERT, RAPIDJSON_LIKELY, RAPIDJSON_PARSE_ERROR, and RAPIDJSON_UNLIKELY.
ParseValue()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseValue (InputStream & is, Handler & handler) inline private
Definition at line 1723 of file reader.h.
{
        switch (is.Peek()) {
            case 'n': ParseNull  <parseFlags>(is, handler); break;
            case 't': ParseTrue  <parseFlags>(is, handler); break;
            case 'f': ParseFalse <parseFlags>(is, handler); break;
            case '"': ParseString<parseFlags>(is, handler); break;
            case '{': ParseObject<parseFlags>(is, handler); break;
            case '[': ParseArray <parseFlags>(is, handler); break;
            default :
                      ParseNumber<parseFlags>(is, handler);
                      break;
        }
    }
Predict()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> RAPIDJSON_FORCEINLINE IterativeParsingState GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Predict (IterativeParsingState state, Token token) inline private
Definition at line 1815 of file reader.h.
{
        // current state x one lookahead token -> new state
        static const char G[cIterativeParsingStateCount][kTokenCount] = {
            // Finish(sink state)
            {
                IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState,
                IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState,
                IterativeParsingErrorState
            },
            // Error(sink state)
            {
                IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState,
                IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState,
                IterativeParsingErrorState
            },
            // Start
            {
                IterativeParsingArrayInitialState,  // Left bracket
                IterativeParsingErrorState,         // Right bracket
                IterativeParsingObjectInitialState, // Left curly bracket
                IterativeParsingErrorState,         // Right curly bracket
                IterativeParsingErrorState,         // Comma
                IterativeParsingErrorState,         // Colon
                IterativeParsingValueState,         // String
                IterativeParsingValueState,         // False
                IterativeParsingValueState,         // True
                IterativeParsingValueState,         // Null
                IterativeParsingValueState          // Number
            },
            // ObjectInitial
            {
                IterativeParsingErrorState,         // Left bracket
                IterativeParsingErrorState,         // Right bracket
                IterativeParsingErrorState,         // Left curly bracket
                IterativeParsingObjectFinishState,  // Right curly bracket
                IterativeParsingErrorState,         // Comma
                IterativeParsingErrorState,         // Colon
                IterativeParsingMemberKeyState,     // String
                IterativeParsingErrorState,         // False
                IterativeParsingErrorState,         // True
                IterativeParsingErrorState,         // Null
                IterativeParsingErrorState          // Number
            },
            // MemberKey
            {
                IterativeParsingErrorState,             // Left bracket
                IterativeParsingErrorState,             // Right bracket
                IterativeParsingErrorState,             // Left curly bracket
                IterativeParsingErrorState,             // Right curly bracket
                IterativeParsingErrorState,             // Comma
                IterativeParsingKeyValueDelimiterState, // Colon
                IterativeParsingErrorState,             // String
                IterativeParsingErrorState,             // False
                IterativeParsingErrorState,             // True
                IterativeParsingErrorState,             // Null
                IterativeParsingErrorState              // Number
            },
            // MemberValue
            {
                IterativeParsingErrorState,             // Left bracket
                IterativeParsingErrorState,             // Right bracket
                IterativeParsingErrorState,             // Left curly bracket
                IterativeParsingObjectFinishState,      // Right curly bracket
                IterativeParsingMemberDelimiterState,   // Comma
                IterativeParsingErrorState,             // Colon
                IterativeParsingErrorState,             // String
                IterativeParsingErrorState,             // False
                IterativeParsingErrorState,             // True
                IterativeParsingErrorState,             // Null
                IterativeParsingErrorState              // Number
            },
            // ObjectFinish(sink state)
            {
                IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState,
                IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState,
                IterativeParsingErrorState
            },
            // ArrayInitial
            {
                IterativeParsingArrayInitialState,      // Left bracket(push Element state)
                IterativeParsingArrayFinishState,       // Right bracket
                IterativeParsingObjectInitialState,     // Left curly bracket(push Element state)
                IterativeParsingErrorState,             // Right curly bracket
                IterativeParsingErrorState,             // Comma
                IterativeParsingErrorState,             // Colon
                IterativeParsingElementState,           // String
                IterativeParsingElementState,           // False
                IterativeParsingElementState,           // True
                IterativeParsingElementState,           // Null
                IterativeParsingElementState            // Number
            },
            // Element
            {
                IterativeParsingErrorState,             // Left bracket
                IterativeParsingArrayFinishState,       // Right bracket
                IterativeParsingErrorState,             // Left curly bracket
                IterativeParsingErrorState,             // Right curly bracket
                IterativeParsingElementDelimiterState,  // Comma
                IterativeParsingErrorState,             // Colon
                IterativeParsingErrorState,             // String
                IterativeParsingErrorState,             // False
                IterativeParsingErrorState,             // True
                IterativeParsingErrorState,             // Null
                IterativeParsingErrorState              // Number
            },
            // ArrayFinish(sink state)
            {
                IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState,
                IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState,
                IterativeParsingErrorState
            },
            // Single Value (sink state)
            {
                IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState,
                IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState, IterativeParsingErrorState,
                IterativeParsingErrorState
            },
            // ElementDelimiter
            {
                IterativeParsingArrayInitialState,      // Left bracket(push Element state)
                IterativeParsingArrayFinishState,       // Right bracket
                IterativeParsingObjectInitialState,     // Left curly bracket(push Element state)
                IterativeParsingErrorState,             // Right curly bracket
                IterativeParsingErrorState,             // Comma
                IterativeParsingErrorState,             // Colon
                IterativeParsingElementState,           // String
                IterativeParsingElementState,           // False
                IterativeParsingElementState,           // True
                IterativeParsingElementState,           // Null
                IterativeParsingElementState            // Number
            },
            // MemberDelimiter
            {
                IterativeParsingErrorState,         // Left bracket
                IterativeParsingErrorState,         // Right bracket
                IterativeParsingErrorState,         // Left curly bracket
                IterativeParsingObjectFinishState,  // Right curly bracket
                IterativeParsingErrorState,         // Comma
                IterativeParsingErrorState,         // Colon
                IterativeParsingMemberKeyState,     // String
                IterativeParsingErrorState,         // False
                IterativeParsingErrorState,         // True
                IterativeParsingErrorState,         // Null
                IterativeParsingErrorState          // Number
            },
            // KeyValueDelimiter
            {
                IterativeParsingArrayInitialState,      // Left bracket(push MemberValue state)
                IterativeParsingErrorState,             // Right bracket
                IterativeParsingObjectInitialState,     // Left curly bracket(push MemberValue state)
                IterativeParsingErrorState,             // Right curly bracket
                IterativeParsingErrorState,             // Comma
                IterativeParsingErrorState,             // Colon
                IterativeParsingMemberValueState,       // String
                IterativeParsingMemberValueState,       // False
                IterativeParsingMemberValueState,       // True
                IterativeParsingMemberValueState,       // Null
                IterativeParsingMemberValueState        // Number
            },
        }; // End of G
        return static_cast<IterativeParsingState>(G[state][token]);
    }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::cIterativeParsingStateCount, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingArrayFinishState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingArrayInitialState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingElementDelimiterState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingElementState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingErrorState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingKeyValueDelimiterState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingMemberDelimiterState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingMemberKeyState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingMemberValueState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingObjectFinishState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingObjectInitialState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingValueState, and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::kTokenCount.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParse(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext().
ScanCopyUnescapedString()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ScanCopyUnescapedString (InputStream & , OutputStream &) inline static private
Definition at line 1058 of file reader.h.
{
            // Do nothing for generic version
    }
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseStringToStream().
SetParseError()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::SetParseError (ParseErrorCode code, size_t offset) inline protected
Definition at line 690 of file reader.h.
{ parseResult_.Set(code, offset); }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::parseResult_, and ParseResult::Set().
SkipWhitespaceAndComments()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream > void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::SkipWhitespaceAndComments (InputStream & is) inline private
Definition at line 710 of file reader.h.
{
        SkipWhitespace(is);
        if (parseFlags & kParseCommentsFlag) {
            while (RAPIDJSON_UNLIKELY(Consume(is, '/'))) {
                if (Consume(is, '*')) {
                    while (true) {
                        if (RAPIDJSON_UNLIKELY(is.Peek() == '\0'))
                            RAPIDJSON_PARSE_ERROR(kParseErrorUnspecificSyntaxError, is.Tell());
                        else if (Consume(is, '*')) {
                            if (Consume(is, '/'))
                                break;
                        }
                        else
                            is.Take();
                    }
                }
                else if (RAPIDJSON_LIKELY(Consume(is, '/')))
                    while (is.Peek() != '\0' && is.Take() != '\n') {}
                else
                    RAPIDJSON_PARSE_ERROR(kParseErrorUnspecificSyntaxError, is.Tell());
                SkipWhitespace(is);
            }
        }
    }
References GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Consume(), kParseCommentsFlag, kParseErrorUnspecificSyntaxError, RAPIDJSON_LIKELY, RAPIDJSON_PARSE_ERROR, RAPIDJSON_UNLIKELY, and SkipWhitespace().
Tokenize()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> RAPIDJSON_FORCEINLINE Token GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Tokenize (Ch c) inline private
Definition at line 1788 of file reader.h.
{
#define N NumberToken
#define N16 N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N
        // Maps from ASCII to Token
        static const unsigned char tokenMap[256] = {
            N16, // 00~0F
            N16, // 10~1F
            N, N, StringToken, N, N, N, N, N, N, N, N, N, CommaToken, N, N, N, // 20~2F
            N, N, N, N, N, N, N, N, N, N, ColonToken, N, N, N, N, N, // 30~3F
            N16, // 40~4F
            N, N, N, N, N, N, N, N, N, N, N, LeftBracketToken, N, RightBracketToken, N, N, // 50~5F
            N, N, N, N, N, N, FalseToken, N, N, N, N, N, N, N, NullToken, N, // 60~6F
            N, N, N, N, TrueToken, N, N, N, N, N, N, LeftCurlyBracketToken, N, RightCurlyBracketToken, N, N, // 70~7F
            N16, N16, N16, N16, N16, N16, N16, N16 // 80~FF
        };
#undef N
#undef N16
        if (sizeof(Ch) == 1 || static_cast<unsigned>(c) < 256)
            return static_cast<Token>(tokenMap[static_cast<unsigned char>(c)]);
        else
            return NumberToken;
    }
References process_traj_logs::c, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ColonToken, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::CommaToken, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::FalseToken, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::LeftBracketToken, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::LeftCurlyBracketToken, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NullToken, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberToken, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::RightBracketToken, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::RightCurlyBracketToken, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::StringToken, and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::TrueToken.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParse(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext().
Transit()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > RAPIDJSON_FORCEINLINE IterativeParsingState GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Transit (IterativeParsingState src, Token token, IterativeParsingState dst, InputStream & is, Handler & handler) inline private
Definition at line 1982 of file reader.h.
{
        (void)token;
        switch (dst) {
        case IterativeParsingErrorState:
            return dst;
        case IterativeParsingObjectInitialState:
        case IterativeParsingArrayInitialState:
        {
            // Push the state(Element or MemeberValue) if we are nested in another array or value of member.
            // In this way we can get the correct state on ObjectFinish or ArrayFinish by frame pop.
            IterativeParsingState n = src;
            if (src == IterativeParsingArrayInitialState || src == IterativeParsingElementDelimiterState)
                n = IterativeParsingElementState;
            else if (src == IterativeParsingKeyValueDelimiterState)
                n = IterativeParsingMemberValueState;
            // Push current state.
            *stack_.template Push<SizeType>(1) = n;
            // Initialize and push the member/element count.
            *stack_.template Push<SizeType>(1) = 0;
            // Call handler
            bool hr = (dst == IterativeParsingObjectInitialState) ? handler.StartObject() : handler.StartArray();
            // On handler short circuits the parsing.
            if (!hr) {
                RAPIDJSON_PARSE_ERROR_NORETURN(kParseErrorTermination, is.Tell());
                return IterativeParsingErrorState;
            }
            else {
                is.Take();
                return dst;
            }
        }
        case IterativeParsingMemberKeyState:
            ParseString<parseFlags>(is, handler, true);
            if (HasParseError())
                return IterativeParsingErrorState;
            else
                return dst;
        case IterativeParsingKeyValueDelimiterState:
            RAPIDJSON_ASSERT(token == ColonToken);
            is.Take();
            return dst;
        case IterativeParsingMemberValueState:
            // Must be non-compound value. Or it would be ObjectInitial or ArrayInitial state.
            ParseValue<parseFlags>(is, handler);
            if (HasParseError()) {
                return IterativeParsingErrorState;
            }
            return dst;
        case IterativeParsingElementState:
            // Must be non-compound value. Or it would be ObjectInitial or ArrayInitial state.
            ParseValue<parseFlags>(is, handler);
            if (HasParseError()) {
                return IterativeParsingErrorState;
            }
            return dst;
        case IterativeParsingMemberDelimiterState:
        case IterativeParsingElementDelimiterState:
            is.Take();
            // Update member/element count.
            *stack_.template Top<SizeType>() = *stack_.template Top<SizeType>() + 1;
            return dst;
        case IterativeParsingObjectFinishState:
        {
            // Transit from delimiter is only allowed when trailing commas are enabled
            if (!(parseFlags & kParseTrailingCommasFlag) && src == IterativeParsingMemberDelimiterState) {
                RAPIDJSON_PARSE_ERROR_NORETURN(kParseErrorObjectMissName, is.Tell());
                return IterativeParsingErrorState;
            }
            // Get member count.
            SizeType c = *stack_.template Pop<SizeType>(1);
            // If the object is not empty, count the last member.
            if (src == IterativeParsingMemberValueState)
                ++c;
            // Restore the state.
            IterativeParsingState n = static_cast<IterativeParsingState>(*stack_.template Pop<SizeType>(1));
            // Transit to Finish state if this is the topmost scope.
            if (n == IterativeParsingStartState)
                n = IterativeParsingFinishState;
            // Call handler
            bool hr = handler.EndObject(c);
            // On handler short circuits the parsing.
            if (!hr) {
                RAPIDJSON_PARSE_ERROR_NORETURN(kParseErrorTermination, is.Tell());
                return IterativeParsingErrorState;
            }
            else {
                is.Take();
                return n;
            }
        }
        case IterativeParsingArrayFinishState:
        {
            // Transit from delimiter is only allowed when trailing commas are enabled
            if (!(parseFlags & kParseTrailingCommasFlag) && src == IterativeParsingElementDelimiterState) {
                RAPIDJSON_PARSE_ERROR_NORETURN(kParseErrorValueInvalid, is.Tell());
                return IterativeParsingErrorState;
            }
            // Get element count.
            SizeType c = *stack_.template Pop<SizeType>(1);
            // If the array is not empty, count the last element.
            if (src == IterativeParsingElementState)
                ++c;
            // Restore the state.
            IterativeParsingState n = static_cast<IterativeParsingState>(*stack_.template Pop<SizeType>(1));
            // Transit to Finish state if this is the topmost scope.
            if (n == IterativeParsingStartState)
                n = IterativeParsingFinishState;
            // Call handler
            bool hr = handler.EndArray(c);
            // On handler short circuits the parsing.
            if (!hr) {
                RAPIDJSON_PARSE_ERROR_NORETURN(kParseErrorTermination, is.Tell());
                return IterativeParsingErrorState;
            }
            else {
                is.Take();
                return n;
            }
        }
        default:
            // This branch is for IterativeParsingValueState actually.
            // Use `default:` rather than
            // `case IterativeParsingValueState:` is for code coverage.
            // The IterativeParsingStartState is not enumerated in this switch-case.
            // It is impossible for that case. And it can be caught by following assertion.
            // The IterativeParsingFinishState is not enumerated in this switch-case either.
            // It is a "derivative" state which cannot triggered from Predict() directly.
            // Therefore it cannot happen here. And it can be caught by following assertion.
            RAPIDJSON_ASSERT(dst == IterativeParsingValueState);
            // Must be non-compound value. Or it would be ObjectInitial or ArrayInitial state.
            ParseValue<parseFlags>(is, handler);
            if (HasParseError()) {
                return IterativeParsingErrorState;
            }
            return IterativeParsingFinishState;
        }
    }
References process_traj_logs::c, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ColonToken, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HasParseError(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingArrayFinishState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingArrayInitialState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingElementDelimiterState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingElementState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingErrorState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingFinishState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingKeyValueDelimiterState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingMemberDelimiterState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingMemberKeyState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingMemberValueState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingObjectFinishState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingObjectInitialState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingStartState, GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParsingValueState, kParseErrorObjectMissName, kParseErrorTermination, kParseErrorValueInvalid, kParseTrailingCommasFlag, RAPIDJSON_ASSERT, RAPIDJSON_PARSE_ERROR_NORETURN, SizeType, and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::stack_.
Member Data Documentation
kDefaultStackCapacity
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> const size_t GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::kDefaultStackCapacity = 256 static private
Default stack capacity in bytes for storing a single decoded string.
Definition at line 2197 of file reader.h.
parseResult_
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> ParseResult GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::parseResult_ private
Definition at line 2199 of file reader.h.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetErrorOffset(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetParseErrorCode(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HasParseError(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParse(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseInit(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::SetParseError().
stack_
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> internal::Stack<StackAllocator> GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::stack_ private
A stack for storing decoded string temporarily during non-destructive parsing.
Definition at line 2198 of file reader.h.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ClearStack(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseNumber(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::ParseString(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Transit().
state_
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> IterativeParsingState GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::state_ private
Definition at line 2200 of file reader.h.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseComplete(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseInit(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext().
The documentation for this class was generated from the following files:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/fwd.h
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/reader.h