Carma-platform: AutoUTFOutputStream< CharType, OutputByteStream > Class Template Reference
AutoUTFOutputStream< CharType, OutputByteStream > Class Template Reference
Output stream wrapper with dynamically bound encoding and automatic encoding detection.
#include <encodedstream.h>
Public Types
typedef CharType Ch
Public Member Functions
AutoUTFOutputStream (OutputByteStream &os, UTFType type, bool putBOM)
Constructor.
UTFType GetType () const
void Put (Ch c)
void Flush ()
Ch Peek () const
Ch Take ()
size_t Tell () const
Ch * PutBegin ()
size_t PutEnd (Ch *)
Private Types
typedef void(* PutFunc) (OutputByteStream &, Ch)
Private Member Functions
RAPIDJSON_STATIC_ASSERT (sizeof(typename OutputByteStream::Ch)==1)
AutoUTFOutputStream (const AutoUTFOutputStream &)
AutoUTFOutputStream & operator= (const AutoUTFOutputStream &)
void PutBOM ()
Private Attributes
OutputByteStream * os_
UTFType type_
PutFunc putFunc_
Detailed Description
template<typename CharType, typename OutputByteStream>
class AutoUTFOutputStream< CharType, OutputByteStream >
Output stream wrapper with dynamically bound encoding and automatic encoding detection.
Template Parameters
CharType Type of character for writing.
OutputByteStream type of output byte stream to be wrapped.
Definition at line 233 of file encodedstream.h.
Member Typedef Documentation
Ch
template<typename CharType , typename OutputByteStream > typedef CharType AutoUTFOutputStream< CharType, OutputByteStream >::Ch
Definition at line 236 of file encodedstream.h.
PutFunc
template<typename CharType , typename OutputByteStream > typedef void(* AutoUTFOutputStream< CharType, OutputByteStream >::PutFunc) (OutputByteStream &, Ch) private
Definition at line 280 of file encodedstream.h.
Constructor & Destructor Documentation
AutoUTFOutputStream() [1/2]
template<typename CharType , typename OutputByteStream > AutoUTFOutputStream< CharType, OutputByteStream >::AutoUTFOutputStream (OutputByteStream & os, UTFType type, bool putBOM) inline
Constructor.
Parameters
os output stream to be wrapped.
type UTF encoding type.
putBOM Whether to write BOM at the beginning of the stream.
Definition at line 244 of file encodedstream.h.
                                                                         : os_(&os), type_(type) {
        RAPIDJSON_ASSERT(type >= kUTF8 && type <= kUTF32BE);
        // Runtime check whether the size of character type is sufficient. It only perform checks with assertion.
        if (type_ == kUTF16LE || type_ == kUTF16BE) RAPIDJSON_ASSERT(sizeof(Ch) >= 2);
        if (type_ == kUTF32LE || type_ == kUTF32BE) RAPIDJSON_ASSERT(sizeof(Ch) >= 4);
        static const PutFunc f[] = { RAPIDJSON_ENCODINGS_FUNC(Put) };
        putFunc_ = f[type_];
        if (putBOM)
            PutBOM();
    }
References kUTF16BE, kUTF16LE, kUTF32BE, kUTF32LE, kUTF8, AutoUTFOutputStream< CharType, OutputByteStream >::Put(), AutoUTFOutputStream< CharType, OutputByteStream >::PutBOM(), AutoUTFOutputStream< CharType, OutputByteStream >::putFunc_, RAPIDJSON_ASSERT, RAPIDJSON_ENCODINGS_FUNC, and AutoUTFOutputStream< CharType, OutputByteStream >::type_.
AutoUTFOutputStream() [2/2]
template<typename CharType , typename OutputByteStream > AutoUTFOutputStream< CharType, OutputByteStream >::AutoUTFOutputStream (const AutoUTFOutputStream< CharType, OutputByteStream > &) private
Member Function Documentation
Flush()
template<typename CharType , typename OutputByteStream > void AutoUTFOutputStream< CharType, OutputByteStream >::Flush () inline
Definition at line 261 of file encodedstream.h.
{ os_->Flush(); }
References AutoUTFOutputStream< CharType, OutputByteStream >::os_.
GetType()
template<typename CharType , typename OutputByteStream > UTFType AutoUTFOutputStream< CharType, OutputByteStream >::GetType () const inline
Definition at line 258 of file encodedstream.h.
{ return type_; }
References AutoUTFOutputStream< CharType, OutputByteStream >::type_.
operator=()
template<typename CharType , typename OutputByteStream > AutoUTFOutputStream & AutoUTFOutputStream< CharType, OutputByteStream >::operator= (const AutoUTFOutputStream< CharType, OutputByteStream > &) private
Peek()
template<typename CharType , typename OutputByteStream > Ch AutoUTFOutputStream< CharType, OutputByteStream >::Peek () const inline
Definition at line 264 of file encodedstream.h.
{ RAPIDJSON_ASSERT(false); return 0;}
References RAPIDJSON_ASSERT.
Put()
template<typename CharType , typename OutputByteStream > void AutoUTFOutputStream< CharType, OutputByteStream >::Put (Ch c) inline
Definition at line 260 of file encodedstream.h.
{ putFunc_(*os_, c); }
References process_traj_logs::c, AutoUTFOutputStream< CharType, OutputByteStream >::os_, and AutoUTFOutputStream< CharType, OutputByteStream >::putFunc_.
Referenced by AutoUTFOutputStream< CharType, OutputByteStream >::AutoUTFOutputStream().
PutBegin()
template<typename CharType , typename OutputByteStream > Ch * AutoUTFOutputStream< CharType, OutputByteStream >::PutBegin () inline
Definition at line 267 of file encodedstream.h.
{ RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
PutBOM()
template<typename CharType , typename OutputByteStream > void AutoUTFOutputStream< CharType, OutputByteStream >::PutBOM () inline private
Definition at line 274 of file encodedstream.h.
                  {
        typedef void (*PutBOMFunc)(OutputByteStream&);
        static const PutBOMFunc f[] = { RAPIDJSON_ENCODINGS_FUNC(PutBOM) };
        f[type_](*os_);
    }
References AutoUTFOutputStream< CharType, OutputByteStream >::PutBOM(), RAPIDJSON_ENCODINGS_FUNC, and AutoUTFOutputStream< CharType, OutputByteStream >::type_.
Referenced by AutoUTFOutputStream< CharType, OutputByteStream >::AutoUTFOutputStream(), and AutoUTFOutputStream< CharType, OutputByteStream >::PutBOM().
PutEnd()
template<typename CharType , typename OutputByteStream > size_t AutoUTFOutputStream< CharType, OutputByteStream >::PutEnd (Ch *) inline
Definition at line 268 of file encodedstream.h.
{ RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
RAPIDJSON_STATIC_ASSERT()
template<typename CharType , typename OutputByteStream > AutoUTFOutputStream< CharType, OutputByteStream >::RAPIDJSON_STATIC_ASSERT (sizeof(typename OutputByteStream::Ch) = =1) private
Take()
template<typename CharType , typename OutputByteStream > Ch AutoUTFOutputStream< CharType, OutputByteStream >::Take () inline
Definition at line 265 of file encodedstream.h.
{ RAPIDJSON_ASSERT(false); return 0;}
References RAPIDJSON_ASSERT.
Tell()
template<typename CharType , typename OutputByteStream > size_t AutoUTFOutputStream< CharType, OutputByteStream >::Tell () const inline
Definition at line 266 of file encodedstream.h.
{ RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
Member Data Documentation
os_
template<typename CharType , typename OutputByteStream > OutputByteStream* AutoUTFOutputStream< CharType, OutputByteStream >::os_ private
Definition at line 282 of file encodedstream.h.
Referenced by AutoUTFOutputStream< CharType, OutputByteStream >::Flush(), and AutoUTFOutputStream< CharType, OutputByteStream >::Put().
putFunc_
template<typename CharType , typename OutputByteStream > PutFunc AutoUTFOutputStream< CharType, OutputByteStream >::putFunc_ private
Definition at line 284 of file encodedstream.h.
Referenced by AutoUTFOutputStream< CharType, OutputByteStream >::AutoUTFOutputStream(), and AutoUTFOutputStream< CharType, OutputByteStream >::Put().
type_
template<typename CharType , typename OutputByteStream > UTFType AutoUTFOutputStream< CharType, OutputByteStream >::type_ private
Definition at line 283 of file encodedstream.h.
Referenced by AutoUTFOutputStream< CharType, OutputByteStream >::AutoUTFOutputStream(), AutoUTFOutputStream< CharType, OutputByteStream >::GetType(), and AutoUTFOutputStream< CharType, OutputByteStream >::PutBOM().
The documentation for this class was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/encodedstream.h