Carma-platform: carma_wm::WMListener Class Reference
carma_wm::WMListener Class Reference
Class which provies automated subscription and threading support for the world model.
#include <WMListener.hpp>
Public Member Functions
WMListener (rclcpp::node_interfaces::NodeBaseInterface::SharedPtr node_base, rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging, rclcpp::node_interfaces::NodeTopicsInterface::SharedPtr node_topics, rclcpp::node_interfaces::NodeParametersInterface::SharedPtr node_params_, bool multi_thread=false)
Constructor which can be used to specify threading behavior of this class.
~WMListener ()
Destructor.
WorldModelConstPtr getWorldModel ()
Returns a pointer to an intialized world model instance.
void setMapCallback (std::function< void()> callback)
Allows user to set a callback to be triggered when a map update is received NOTE: If operating in multi-threaded mode the world model will remain locked until the user function completes.
void setRouteCallback (std::function< void()> callback)
Allows user to set a callback to be triggered when a route update is received NOTE: If operating in multi-threaded mode the world model will remain locked until the user function completes.
std::unique_lock< std::mutex > getLock (bool pre_locked=true)
Returns a unique_lock which can be used to lock world model updates until the user finishes a desired operation. This function should be used when multiple queries are needed and this object is operating in multi-threaded mode.
void setConfigSpeedLimit (double config_lim) const
Allows user to set a callback to be triggered when a route update is received NOTE: If operating in multi-threaded mode the world model will remain locked until the user function completes.
void enableUpdatesWithoutRouteWL ()
Use to allow updates to occur even if they invalidate the current route. This is only meant to be used by components which generate the route.
bool checkIfReRoutingNeededWL ()
Returns true if a map update has been processed which requires rerouting. This method is meant to be used by routing components.
Private Member Functions
void mapUpdateCallback (autoware_lanelet2_msgs::msg::MapBin::UniquePtr geofence_msg)
Private Attributes
carma_ros2_utils::SubPtr< carma_perception_msgs::msg::RoadwayObstacleList > roadway_objects_sub_
carma_ros2_utils::SubPtr< autoware_lanelet2_msgs::msg::MapBin > map_update_sub_
rclcpp::node_interfaces::NodeBaseInterface::SharedPtr node_base_
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging_
rclcpp::node_interfaces::NodeTopicsInterface::SharedPtr node_topics_
rclcpp::node_interfaces::NodeParametersInterface::SharedPtr node_params_
std::unique_ptr< WMListenerWorker > worker_
carma_ros2_utils::SubPtr< autoware_lanelet2_msgs::msg::MapBin > map_sub_
carma_ros2_utils::SubPtr< carma_planning_msgs::msg::Route > route_sub_
carma_ros2_utils::SubPtr< carma_v2x_msgs::msg::SPAT > traffic_spat_sub_
const bool multi_threaded_
std::mutex mw_mutex_
Detailed Description
Class which provies automated subscription and threading support for the world model.
Users should generally create and cache a single instance of this class within a node. They can then retrieve a pointer to an initialized WorldModel object for doing queries. By default this class follows the threading model of the host node, but it can operate in the background if specified in the constructor. When used in a multi-threading case users can ensure threadsafe operation though usage of the getLock function
Definition at line 45 of file WMListener.hpp.
Constructor & Destructor Documentation
WMListener()
carma_wm::WMListener::WMListener (rclcpp::node_interfaces::NodeBaseInterface::SharedPtr node_base, rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging, rclcpp::node_interfaces::NodeTopicsInterface::SharedPtr node_topics, rclcpp::node_interfaces::NodeParametersInterface::SharedPtr node_params_, bool multi_thread = false)
Constructor which can be used to specify threading behavior of this class.
By default this object follows node threading behavior (ie. waiting for ros::spin()) If the object is operating in multi-threaded mode a ros::AsyncSpinner is used to implement a background thread.
Parameters
multi_thread If true this object will subscribe using background threads. Defaults to false
Definition at line 25 of file WMListener.cpp.
    :node_base_(node_base),node_logging_(node_logging),node_topics_(node_topics),worker_(std::unique_ptr<WMListenerWorker>(new WMListenerWorker)), multi_threaded_(multi_thread)
{
  RCLCPP_DEBUG_STREAM(node_logging_->get_logger(), "WMListener: Creating world model listener");
  //Declare parameter if it doesn't exist
  rclcpp::Parameter config_speed_limit_param("config_speed_limit");
  if(!node_params_->get_parameter("config_speed_limit", config_speed_limit_param)){
    rclcpp::ParameterValue config_speed_limit_param_value;
    config_speed_limit_param_value = node_params_->declare_parameter("config_speed_limit", rclcpp::ParameterValue (0.0));
  }
  rclcpp::Parameter participant_param("vehicle_participant_type");
  if(!node_params_->get_parameter("vehicle_participant_type", participant_param)){
    rclcpp::ParameterValue participant_param_value;
    participant_param_value = node_params_->declare_parameter("vehicle_participant_type", rclcpp::ParameterValue(""));
  }
  // Get params
  config_speed_limit_param = node_params_->get_parameter("config_speed_limit");
  participant_param = node_params_->get_parameter("vehicle_participant_type");
  RCLCPP_INFO_STREAM(node_logging->get_logger(), "Loaded config speed limit: " << config_speed_limit_param.as_double());
  RCLCPP_INFO_STREAM(node_logging->get_logger(), "Loaded vehicle participant type: " << participant_param.as_string());
  setConfigSpeedLimit(config_speed_limit_param.as_double());
  worker_->setVehicleParticipationType(participant_param.as_string());
  rclcpp::SubscriptionOptions map_update_options;
  rclcpp::SubscriptionOptions map_options;
  rclcpp::SubscriptionOptions route_options;
  rclcpp::SubscriptionOptions roadway_objects_options;
  rclcpp::SubscriptionOptions traffic_spat_options;
  if(multi_threaded_)
  {
    RCLCPP_DEBUG_STREAM(node_logging_->get_logger(), "WMListener: Using a multi-threaded subscription");
    auto map_update_cb_group = node_base_->create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    map_update_options.callback_group = map_update_cb_group;
    auto map_cb_group = node_base_->create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    map_options.callback_group = map_cb_group;
    auto route_cb_group = node_base_->create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    route_options.callback_group = route_cb_group;
    auto roadway_objects_group = node_base_->create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    roadway_objects_options.callback_group = roadway_objects_group;
    auto traffic_spat_group = node_base_->create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    traffic_spat_options.callback_group = traffic_spat_group;
  }
  // Setup subscribers
  route_sub_ = rclcpp::create_subscription<carma_planning_msgs::msg::Route>(node_topics_, "route", 1,
                                  std::bind(&WMListenerWorker::routeCallback, worker_.get(), std::placeholders::_1), route_options);
  roadway_objects_sub_ = rclcpp::create_subscription<carma_perception_msgs::msg::RoadwayObstacleList>(node_topics_, "roadway_objects", 1,
                                  std::bind(&WMListenerWorker::roadwayObjectListCallback, worker_.get(), std::placeholders::_1), roadway_objects_options);
  traffic_spat_sub_ = rclcpp::create_subscription<carma_v2x_msgs::msg::SPAT>(node_topics_, "incoming_spat", 1,
                                  std::bind(&WMListenerWorker::incomingSpatCallback, worker_.get(), std::placeholders::_1), traffic_spat_options);
  // NOTE: Currently, intra-process comms must be disabled for subscribers that are transient_local: https://github.com/ros2/rclcpp/issues/1753
  map_update_options.use_intra_process_comm = rclcpp::IntraProcessSetting::Disable; // Disable intra-process comms for the map update subscriber
  auto map_update_sub_qos = rclcpp::QoS(rclcpp::KeepLast(10)); // Set the queue size for the map update subscriber
  map_update_sub_qos.transient_local();  // If it is possible that this node is a late-joiner to its topic, it must be set to transient_local to receive earlier messages that were missed.
                                         // NOTE: The publisher's QoS must be set to transisent_local() as well for earlier messages to be resent to this later-joiner.
  // Create map update subscriber that will receive earlier messages that were missed ONLY if the publisher is transient_local too
  map_update_sub_ = rclcpp::create_subscription<autoware_lanelet2_msgs::msg::MapBin>(node_topics_, "map_update", map_update_sub_qos,
                  std::bind(&WMListener::mapUpdateCallback, this, std::placeholders::_1), map_update_options);
  map_options.use_intra_process_comm = rclcpp::IntraProcessSetting::Disable; // Disable intra-process comms for the semantic map subscriber
  auto map_sub_qos = rclcpp::QoS(rclcpp::KeepLast(2)); // Set the queue size for the semantic map subscriber
  map_sub_qos.transient_local();  // If it is possible that this node is a late-joiner to its topic, it must be set to transient_local to receive earlier messages that were missed.
                                  // NOTE: The publisher's QoS must be set to transisent_local() as well for earlier messages to be resent to this later-joiner.
  // Create semantic mab subscriber that will receive earlier messages that were missed ONLY if the publisher is transient_local too
  map_sub_ = rclcpp::create_subscription<autoware_lanelet2_msgs::msg::MapBin>(node_topics_, "semantic_map", map_sub_qos,
                                  std::bind(&WMListenerWorker::mapCallback, worker_.get(), std::placeholders::_1), map_options);
}
References carma_wm::WMListenerWorker::incomingSpatCallback(), map_sub_, map_update_sub_, carma_wm::WMListenerWorker::mapCallback(), mapUpdateCallback(), multi_threaded_, node_base_, node_logging_, node_params_, node_topics_, roadway_objects_sub_, carma_wm::WMListenerWorker::roadwayObjectListCallback(), route_sub_, carma_wm::WMListenerWorker::routeCallback(), setConfigSpeedLimit(), traffic_spat_sub_, and worker_.
~WMListener()
carma_wm::WMListener::~WMListener ()
Destructor.
Definition at line 116 of file WMListener.cpp.
{}
Member Function Documentation
checkIfReRoutingNeededWL()
bool carma_wm::WMListener::checkIfReRoutingNeededWL ()
Returns true if a map update has been processed which requires rerouting. This method is meant to be used by routing components.
Returns
True is rerouting is needed
Definition at line 124 of file WMListener.cpp.
{
  const std::lock_guard<std::mutex> lock(mw_mutex_);
  return worker_->checkIfReRoutingNeeded();
}
References mw_mutex_, and worker_.
Referenced by route::Route::handle_on_configure().
enableUpdatesWithoutRouteWL()
void carma_wm::WMListener::enableUpdatesWithoutRouteWL ()
Use to allow updates to occur even if they invalidate the current route. This is only meant to be used by components which generate the route.
Definition at line 118 of file WMListener.cpp.
{
  const std::lock_guard<std::mutex> lock(mw_mutex_);
  worker_->enableUpdatesWithoutRoute();
}
References mw_mutex_, and worker_.
Referenced by route::Route::handle_on_configure().
getLock()
std::unique_lock< std::mutex > carma_wm::WMListener::getLock (bool pre_locked = true)
Returns a unique_lock which can be used to lock world model updates until the user finishes a desired operation. This function should be used when multiple queries are needed and this object is operating in multi-threaded mode.
Parameters
pre_locked If true the returned lock will already be locked. If false the lock will be deferred with std::defer_lock Default is true
Returns
std::unique_lock for thread safe access to world model data
Definition at line 157 of file WMListener.cpp.
{
  if (pre_locked)
  {
    std::unique_lock<std::mutex> lock(mw_mutex_);  // Create movable lock
    return lock;
  }
  std::unique_lock<std::mutex> lock(mw_mutex_, std::defer_lock);  // Create movable deferred lock
  return lock;
}
References mw_mutex_.
getWorldModel()
WorldModelConstPtr carma_wm::WMListener::getWorldModel ()
Returns a pointer to an intialized world model instance.
Returns
Const pointer to a world model object
Definition at line 130 of file WMListener.cpp.
{
  const std::lock_guard<std::mutex> lock(mw_mutex_);
  return worker_->getWorldModel();
}
References mw_mutex_, and worker_.
Referenced by plan_delegator::PlanDelegator::handle_on_configure(), and route::Route::handle_on_configure().
mapUpdateCallback()
void carma_wm::WMListener::mapUpdateCallback (autoware_lanelet2_msgs::msg::MapBin::UniquePtr geofence_msg) private
Definition at line 136 of file WMListener.cpp.
{
  const std::lock_guard<std::mutex> lock(mw_mutex_);
  RCLCPP_INFO_STREAM(node_logging_->get_logger(), "New Map Update Received. SeqNum: " << geofence_msg->seq_id);
  worker_->mapUpdateCallback(std::move(geofence_msg));
}
References mw_mutex_, node_logging_, and worker_.
Referenced by WMListener().
setConfigSpeedLimit()
void carma_wm::WMListener::setConfigSpeedLimit (double config_lim) const
Allows user to set a callback to be triggered when a route update is received NOTE: If operating in multi-threaded mode the world model will remain locked until the user function completes.
Parameters
config_lim A function that populate the configurable speed limit value after the world model is updated with a new route
Definition at line 168 of file WMListener.cpp.
{
  worker_->setConfigSpeedLimit(config_lim);
}
References worker_.
Referenced by WMListener().
setMapCallback()
void carma_wm::WMListener::setMapCallback (std::function< void()> callback)
Allows user to set a callback to be triggered when a map update is received NOTE: If operating in multi-threaded mode the world model will remain locked until the user function completes.
Parameters
callback A callback function that will be triggered after the world model receives a new map update
Definition at line 145 of file WMListener.cpp.
{
  const std::lock_guard<std::mutex> lock(mw_mutex_);
  worker_->setMapCallback(callback);
}
References callback(), mw_mutex_, and worker_.
setRouteCallback()
void carma_wm::WMListener::setRouteCallback (std::function< void()> callback)
Allows user to set a callback to be triggered when a route update is received NOTE: If operating in multi-threaded mode the world model will remain locked until the user function completes.
Parameters
callback A callback function that will be triggered after the world model is updated with a new route
Definition at line 151 of file WMListener.cpp.
{
  const std::lock_guard<std::mutex> lock(mw_mutex_);
  worker_->setRouteCallback(callback);
}
References callback(), mw_mutex_, and worker_.
Member Data Documentation
map_sub_
carma_ros2_utils::SubPtr<autoware_lanelet2_msgs::msg::MapBin> carma_wm::WMListener::map_sub_ private
Definition at line 141 of file WMListener.hpp.
Referenced by WMListener().
map_update_sub_
carma_ros2_utils::SubPtr<autoware_lanelet2_msgs::msg::MapBin> carma_wm::WMListener::map_update_sub_ private
Definition at line 132 of file WMListener.hpp.
Referenced by WMListener().
multi_threaded_
const bool carma_wm::WMListener::multi_threaded_ private
Definition at line 144 of file WMListener.hpp.
Referenced by WMListener().
mw_mutex_
std::mutex carma_wm::WMListener::mw_mutex_ private
Definition at line 145 of file WMListener.hpp.
Referenced by checkIfReRoutingNeededWL(), enableUpdatesWithoutRouteWL(), getLock(), getWorldModel(), mapUpdateCallback(), setMapCallback(), and setRouteCallback().
node_base_
rclcpp::node_interfaces::NodeBaseInterface::SharedPtr carma_wm::WMListener::node_base_ private
Definition at line 134 of file WMListener.hpp.
Referenced by WMListener().
node_logging_
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr carma_wm::WMListener::node_logging_ private
Definition at line 135 of file WMListener.hpp.
Referenced by WMListener(), and mapUpdateCallback().
node_params_
rclcpp::node_interfaces::NodeParametersInterface::SharedPtr carma_wm::WMListener::node_params_ private
Definition at line 137 of file WMListener.hpp.
Referenced by WMListener().
node_topics_
rclcpp::node_interfaces::NodeTopicsInterface::SharedPtr carma_wm::WMListener::node_topics_ private
Definition at line 136 of file WMListener.hpp.
Referenced by WMListener().
roadway_objects_sub_
carma_ros2_utils::SubPtr<carma_perception_msgs::msg::RoadwayObstacleList> carma_wm::WMListener::roadway_objects_sub_ private
Definition at line 131 of file WMListener.hpp.
Referenced by WMListener().
route_sub_
carma_ros2_utils::SubPtr<carma_planning_msgs::msg::Route> carma_wm::WMListener::route_sub_ private
Definition at line 142 of file WMListener.hpp.
Referenced by WMListener().
traffic_spat_sub_
carma_ros2_utils::SubPtr<carma_v2x_msgs::msg::SPAT> carma_wm::WMListener::traffic_spat_sub_ private
Definition at line 143 of file WMListener.hpp.
Referenced by WMListener().
worker_
std::unique_ptr<WMListenerWorker> carma_wm::WMListener::worker_ private
Definition at line 139 of file WMListener.hpp.
Referenced by WMListener(), checkIfReRoutingNeededWL(), enableUpdatesWithoutRouteWL(), getWorldModel(), mapUpdateCallback(), setConfigSpeedLimit(), setMapCallback(), and setRouteCallback().
The documentation for this class was generated from the following files:
carma_wm/include/carma_wm/WMListener.hpp
carma_wm/src/WMListener.cpp