Carma-platform: GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false > Class Template Reference
GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false > Class Template Reference
Public Types
typedef InputStream::Ch Ch
Public Member Functions
NumberStream (GenericReader &reader, InputStream &s)
RAPIDJSON_FORCEINLINE Ch Peek () const
RAPIDJSON_FORCEINLINE Ch TakePush ()
RAPIDJSON_FORCEINLINE Ch Take ()
RAPIDJSON_FORCEINLINE void Push (char)
size_t Tell ()
size_t Length ()
const char * Pop ()
Protected Member Functions
NumberStream & operator= (const NumberStream &)
Protected Attributes
InputStream & is
Detailed Description
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator>
template<typename InputStream>
class GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >
Definition at line 1398 of file reader.h.
Member Typedef Documentation
Ch
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > typedef InputStream::Ch GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::Ch
Definition at line 1400 of file reader.h.
Constructor & Destructor Documentation
NumberStream()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::NumberStream (GenericReader & reader, InputStream & s) inline
Definition at line 1402 of file reader.h.
: is(s) { (void)reader;  }
Member Function Documentation
Length()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > size_t GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::Length () inline
Definition at line 1410 of file reader.h.
{ return 0; }
operator=()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > NumberStream & GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::operator= (const NumberStream< InputStream, false, false > &) protected
Peek()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > RAPIDJSON_FORCEINLINE Ch GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::Peek () const inline
Definition at line 1404 of file reader.h.
{ return is.Peek(); }
References GenericInsituStringStream< Encoding >::Peek().
Pop()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > const char * GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::Pop () inline
Definition at line 1411 of file reader.h.
{ return 0; }
Push()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > RAPIDJSON_FORCEINLINE void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::Push (char) inline
Definition at line 1407 of file reader.h.
{}
Take()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > RAPIDJSON_FORCEINLINE Ch GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::Take () inline
Definition at line 1406 of file reader.h.
{ return is.Take(); }
References GenericInsituStringStream< Encoding >::Take().
TakePush()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > RAPIDJSON_FORCEINLINE Ch GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::TakePush () inline
Definition at line 1405 of file reader.h.
{ return is.Take(); }
References GenericInsituStringStream< Encoding >::Take().
Tell()
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > size_t GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::Tell () inline
Definition at line 1409 of file reader.h.
{ return is.Tell(); }
References GenericInsituStringStream< Encoding >::Tell().
Member Data Documentation
is
template<typename SourceEncoding , typename TargetEncoding , typename StackAllocator = CrtAllocator> template<typename InputStream > InputStream& GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::is protected
Definition at line 1416 of file reader.h.
The documentation for this class was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/reader.h