Carma-platform: internal::Schema< SchemaDocumentType > Class Template Reference
internal::Schema< SchemaDocumentType > Class Template Reference
#include <schema.h>
Classes
struct PatternProperty
struct Property
struct SchemaArray
Public Types
typedef SchemaDocumentType::ValueType ValueType
typedef SchemaDocumentType::AllocatorType AllocatorType
typedef SchemaDocumentType::PointerType PointerType
typedef ValueType::EncodingType EncodingType
typedef EncodingType::Ch Ch
typedef SchemaValidationContext< SchemaDocumentType > Context
typedef Schema< SchemaDocumentType > SchemaType
typedef GenericValue< EncodingType, AllocatorType > SValue
Public Member Functions
Schema (SchemaDocumentType *schemaDocument, const PointerType &p, const ValueType &value, const ValueType &document, AllocatorType *allocator)
~Schema ()
bool BeginValue (Context &context) const
RAPIDJSON_FORCEINLINE bool EndValue (Context &context) const
bool Null (Context &context) const
bool Bool (Context &context, bool) const
bool Int (Context &context, int i) const
bool Uint (Context &context, unsigned u) const
bool Int64 (Context &context, int64_t i) const
bool Uint64 (Context &context, uint64_t u) const
bool Double (Context &context, double d) const
bool String (Context &context, const Ch *str, SizeType length, bool) const
bool StartObject (Context &context) const
bool Key (Context &context, const Ch *str, SizeType len, bool) const
bool EndObject (Context &context, SizeType memberCount) const
bool StartArray (Context &context) const
bool EndArray (Context &context, SizeType elementCount) const
Private Types
enum SchemaValueType {
kNullSchemaType , kBooleanSchemaType , kObjectSchemaType , kArraySchemaType ,
kStringSchemaType , kNumberSchemaType , kIntegerSchemaType , kTotalSchemaType
}
typedef internal::GenericRegex< EncodingType > RegexType
Private Member Functions
template<typename V1 , typename V2 >
void AddUniqueElement (V1 &a, const V2 &v)
void AssignIfExist (SchemaArray &out, SchemaDocumentType &schemaDocument, const PointerType &p, const ValueType &value, const ValueType &name, const ValueType &document)
template<typename ValueType >
RegexType * CreatePattern (const ValueType &value)
void AddType (const ValueType &type)
bool CreateParallelValidator (Context &context) const
void CreateSchemaValidators (Context &context, const SchemaArray &schemas) const
bool FindPropertyIndex (const ValueType &name, SizeType *outIndex) const
bool CheckInt (Context &context, int64_t i) const
bool CheckUint (Context &context, uint64_t i) const
bool CheckDoubleMinimum (Context &context, double d) const
bool CheckDoubleMaximum (Context &context, double d) const
bool CheckDoubleMultipleOf (Context &context, double d) const
Static Private Member Functions
static const ValueType * GetMember (const ValueType &value, const ValueType &name)
static void AssignIfExist (bool &out, const ValueType &value, const ValueType &name)
static void AssignIfExist (SizeType &out, const ValueType &value, const ValueType &name)
static bool IsPatternMatch (const RegexType *pattern, const Ch *str, SizeType)
Private Attributes
AllocatorType * allocator_
const SchemaType * typeless_
uint64_t * enum_
SizeType enumCount_
SchemaArray allOf_
SchemaArray anyOf_
SchemaArray oneOf_
const SchemaType * not_
unsigned type_
SizeType validatorCount_
SizeType notValidatorIndex_
Property * properties_
const SchemaType * additionalPropertiesSchema_
PatternProperty * patternProperties_
SizeType patternPropertyCount_
SizeType propertyCount_
SizeType minProperties_
SizeType maxProperties_
bool additionalProperties_
bool hasDependencies_
bool hasRequired_
bool hasSchemaDependencies_
const SchemaType * additionalItemsSchema_
const SchemaType * itemsList_
const SchemaType ** itemsTuple_
SizeType itemsTupleCount_
SizeType minItems_
SizeType maxItems_
bool additionalItems_
bool uniqueItems_
RegexType * pattern_
SizeType minLength_
SizeType maxLength_
SValue minimum_
SValue maximum_
SValue multipleOf_
bool exclusiveMinimum_
bool exclusiveMaximum_
Friends
class GenericSchemaDocument< ValueType, AllocatorType >
Detailed Description
template<typename SchemaDocumentType>
class internal::Schema< SchemaDocumentType >
Definition at line 338 of file schema.h.
Member Typedef Documentation
AllocatorType
template<typename SchemaDocumentType > typedef SchemaDocumentType::AllocatorType internal::Schema< SchemaDocumentType >::AllocatorType
Definition at line 341 of file schema.h.
Ch
template<typename SchemaDocumentType > typedef EncodingType::Ch internal::Schema< SchemaDocumentType >::Ch
Definition at line 344 of file schema.h.
Context
template<typename SchemaDocumentType > typedef SchemaValidationContext<SchemaDocumentType> internal::Schema< SchemaDocumentType >::Context
Definition at line 345 of file schema.h.
EncodingType
template<typename SchemaDocumentType > typedef ValueType::EncodingType internal::Schema< SchemaDocumentType >::EncodingType
Definition at line 343 of file schema.h.
PointerType
template<typename SchemaDocumentType > typedef SchemaDocumentType::PointerType internal::Schema< SchemaDocumentType >::PointerType
Definition at line 342 of file schema.h.
RegexType
template<typename SchemaDocumentType > typedef internal::GenericRegex<EncodingType> internal::Schema< SchemaDocumentType >::RegexType private
Definition at line 938 of file schema.h.
SchemaType
template<typename SchemaDocumentType > typedef Schema<SchemaDocumentType> internal::Schema< SchemaDocumentType >::SchemaType
Definition at line 346 of file schema.h.
SValue
template<typename SchemaDocumentType > typedef GenericValue<EncodingType, AllocatorType> internal::Schema< SchemaDocumentType >::SValue
Definition at line 347 of file schema.h.
ValueType
template<typename SchemaDocumentType > typedef SchemaDocumentType::ValueType internal::Schema< SchemaDocumentType >::ValueType
Definition at line 340 of file schema.h.
Member Enumeration Documentation
SchemaValueType
template<typename SchemaDocumentType > enum internal::Schema::SchemaValueType private
Enumerator
kNullSchemaType
kBooleanSchemaType
kObjectSchemaType
kArraySchemaType
kStringSchemaType
kNumberSchemaType
kIntegerSchemaType
kTotalSchemaType
Definition at line 926 of file schema.h.
{
        kNullSchemaType,
        kBooleanSchemaType,
        kObjectSchemaType,
        kArraySchemaType,
        kStringSchemaType,
        kNumberSchemaType,
        kIntegerSchemaType,
        kTotalSchemaType
    };
Constructor & Destructor Documentation
Schema()
template<typename SchemaDocumentType > internal::Schema< SchemaDocumentType >::Schema (SchemaDocumentType * schemaDocument, const PointerType & p, const ValueType & value, const ValueType & document, AllocatorType * allocator) inline
Definition at line 350 of file schema.h.
                                                                                                                                                  :
        allocator_(allocator),
        typeless_(schemaDocument->GetTypeless()),
        enum_(),
        enumCount_(),
        not_(),
        type_((1 << kTotalSchemaType) - 1), // typeless
        validatorCount_(),
        properties_(),
        additionalPropertiesSchema_(),
        patternProperties_(),
        patternPropertyCount_(),
        propertyCount_(),
        minProperties_(),
        maxProperties_(SizeType(~0)),
        additionalProperties_(true),
        hasDependencies_(),
        hasRequired_(),
        hasSchemaDependencies_(),
        additionalItemsSchema_(),
        itemsList_(),
        itemsTuple_(),
        itemsTupleCount_(),
        minItems_(),
        maxItems_(SizeType(~0)),
        additionalItems_(true),
        uniqueItems_(false),
        pattern_(),
        minLength_(0),
        maxLength_(~SizeType(0)),
        exclusiveMinimum_(false),
        exclusiveMaximum_(false)
    {
        typedef typename SchemaDocumentType::ValueType ValueType;
        typedef typename ValueType::ConstValueIterator ConstValueIterator;
        typedef typename ValueType::ConstMemberIterator ConstMemberIterator;
        if (!value.IsObject())
            return;
        if (const ValueType* v = GetMember(value, GetTypeString())) {
            type_ = 0;
            if (v->IsString())
                AddType(*v);
            else if (v->IsArray())
                for (ConstValueIterator itr = v->Begin(); itr != v->End(); ++itr)
                    AddType(*itr);
        }
        if (const ValueType* v = GetMember(value, GetEnumString()))
            if (v->IsArray() && v->Size() > 0) {
                enum_ = static_cast<uint64_t*>(allocator_->Malloc(sizeof(uint64_t) * v->Size()));
                for (ConstValueIterator itr = v->Begin(); itr != v->End(); ++itr) {
                    typedef Hasher<EncodingType, MemoryPoolAllocator<> > EnumHasherType;
                    char buffer[256 + 24];
                    MemoryPoolAllocator<> hasherAllocator(buffer, sizeof(buffer));
                    EnumHasherType h(&hasherAllocator, 256);
                    itr->Accept(h);
                    enum_[enumCount_++] = h.GetHashCode();
                }
            }
        if (schemaDocument) {
            AssignIfExist(allOf_, *schemaDocument, p, value, GetAllOfString(), document);
            AssignIfExist(anyOf_, *schemaDocument, p, value, GetAnyOfString(), document);
            AssignIfExist(oneOf_, *schemaDocument, p, value, GetOneOfString(), document);
        }
        if (const ValueType* v = GetMember(value, GetNotString())) {
            schemaDocument->CreateSchema(&not_, p.Append(GetNotString(), allocator_), *v, document);
            notValidatorIndex_ = validatorCount_;
            validatorCount_++;
        }
        // Object
        const ValueType* properties = GetMember(value, GetPropertiesString());
        const ValueType* required = GetMember(value, GetRequiredString());
        const ValueType* dependencies = GetMember(value, GetDependenciesString());
        {
            // Gather properties from properties/required/dependencies
            SValue allProperties(kArrayType);
            if (properties && properties->IsObject())
                for (ConstMemberIterator itr = properties->MemberBegin(); itr != properties->MemberEnd(); ++itr)
                    AddUniqueElement(allProperties, itr->name);
            if (required && required->IsArray())
                for (ConstValueIterator itr = required->Begin(); itr != required->End(); ++itr)
                    if (itr->IsString())
                        AddUniqueElement(allProperties, *itr);
            if (dependencies && dependencies->IsObject())
                for (ConstMemberIterator itr = dependencies->MemberBegin(); itr != dependencies->MemberEnd(); ++itr) {
                    AddUniqueElement(allProperties, itr->name);
                    if (itr->value.IsArray())
                        for (ConstValueIterator i = itr->value.Begin(); i != itr->value.End(); ++i)
                            if (i->IsString())
                                AddUniqueElement(allProperties, *i);
                }
            if (allProperties.Size() > 0) {
                propertyCount_ = allProperties.Size();
                properties_ = static_cast<Property*>(allocator_->Malloc(sizeof(Property) * propertyCount_));
                for (SizeType i = 0; i < propertyCount_; i++) {
                    new (&properties_[i]) Property();
                    properties_[i].name = allProperties[i];
                    properties_[i].schema = typeless_;
                }
            }
        }
        if (properties && properties->IsObject()) {
            PointerType q = p.Append(GetPropertiesString(), allocator_);
            for (ConstMemberIterator itr = properties->MemberBegin(); itr != properties->MemberEnd(); ++itr) {
                SizeType index;
                if (FindPropertyIndex(itr->name, &index))
                    schemaDocument->CreateSchema(&properties_[index].schema, q.Append(itr->name, allocator_), itr->value, document);
            }
        }
        if (const ValueType* v = GetMember(value, GetPatternPropertiesString())) {
            PointerType q = p.Append(GetPatternPropertiesString(), allocator_);
            patternProperties_ = static_cast<PatternProperty*>(allocator_->Malloc(sizeof(PatternProperty) * v->MemberCount()));
            patternPropertyCount_ = 0;
            for (ConstMemberIterator itr = v->MemberBegin(); itr != v->MemberEnd(); ++itr) {
                new (&patternProperties_[patternPropertyCount_]) PatternProperty();
                patternProperties_[patternPropertyCount_].pattern = CreatePattern(itr->name);
                schemaDocument->CreateSchema(&patternProperties_[patternPropertyCount_].schema, q.Append(itr->name, allocator_), itr->value, document);
                patternPropertyCount_++;
            }
        }
        if (required && required->IsArray())
            for (ConstValueIterator itr = required->Begin(); itr != required->End(); ++itr)
                if (itr->IsString()) {
                    SizeType index;
                    if (FindPropertyIndex(*itr, &index)) {
                        properties_[index].required = true;
                        hasRequired_ = true;
                    }
                }
        if (dependencies && dependencies->IsObject()) {
            PointerType q = p.Append(GetDependenciesString(), allocator_);
            hasDependencies_ = true;
            for (ConstMemberIterator itr = dependencies->MemberBegin(); itr != dependencies->MemberEnd(); ++itr) {
                SizeType sourceIndex;
                if (FindPropertyIndex(itr->name, &sourceIndex)) {
                    if (itr->value.IsArray()) {
                        properties_[sourceIndex].dependencies = static_cast<bool*>(allocator_->Malloc(sizeof(bool) * propertyCount_));
                        std::memset(properties_[sourceIndex].dependencies, 0, sizeof(bool)* propertyCount_);
                        for (ConstValueIterator targetItr = itr->value.Begin(); targetItr != itr->value.End(); ++targetItr) {
                            SizeType targetIndex;
                            if (FindPropertyIndex(*targetItr, &targetIndex))
                                properties_[sourceIndex].dependencies[targetIndex] = true;
                        }
                    }
                    else if (itr->value.IsObject()) {
                        hasSchemaDependencies_ = true;
                        schemaDocument->CreateSchema(&properties_[sourceIndex].dependenciesSchema, q.Append(itr->name, allocator_), itr->value, document);
                        properties_[sourceIndex].dependenciesValidatorIndex = validatorCount_;
                        validatorCount_++;
                    }
                }
            }
        }
        if (const ValueType* v = GetMember(value, GetAdditionalPropertiesString())) {
            if (v->IsBool())
                additionalProperties_ = v->GetBool();
            else if (v->IsObject())
                schemaDocument->CreateSchema(&additionalPropertiesSchema_, p.Append(GetAdditionalPropertiesString(), allocator_), *v, document);
        }
        AssignIfExist(minProperties_, value, GetMinPropertiesString());
        AssignIfExist(maxProperties_, value, GetMaxPropertiesString());
        // Array
        if (const ValueType* v = GetMember(value, GetItemsString())) {
            PointerType q = p.Append(GetItemsString(), allocator_);
            if (v->IsObject()) // List validation
                schemaDocument->CreateSchema(&itemsList_, q, *v, document);
            else if (v->IsArray()) { // Tuple validation
                itemsTuple_ = static_cast<const Schema**>(allocator_->Malloc(sizeof(const Schema*) * v->Size()));
                SizeType index = 0;
                for (ConstValueIterator itr = v->Begin(); itr != v->End(); ++itr, index++)
                    schemaDocument->CreateSchema(&itemsTuple_[itemsTupleCount_++], q.Append(index, allocator_), *itr, document);
            }
        }
        AssignIfExist(minItems_, value, GetMinItemsString());
        AssignIfExist(maxItems_, value, GetMaxItemsString());
        if (const ValueType* v = GetMember(value, GetAdditionalItemsString())) {
            if (v->IsBool())
                additionalItems_ = v->GetBool();
            else if (v->IsObject())
                schemaDocument->CreateSchema(&additionalItemsSchema_, p.Append(GetAdditionalItemsString(), allocator_), *v, document);
        }
        AssignIfExist(uniqueItems_, value, GetUniqueItemsString());
        // String
        AssignIfExist(minLength_, value, GetMinLengthString());
        AssignIfExist(maxLength_, value, GetMaxLengthString());
        if (const ValueType* v = GetMember(value, GetPatternString()))
            pattern_ = CreatePattern(*v);
        // Number
        if (const ValueType* v = GetMember(value, GetMinimumString()))
            if (v->IsNumber())
                minimum_.CopyFrom(*v, *allocator_);
        if (const ValueType* v = GetMember(value, GetMaximumString()))
            if (v->IsNumber())
                maximum_.CopyFrom(*v, *allocator_);
        AssignIfExist(exclusiveMinimum_, value, GetExclusiveMinimumString());
        AssignIfExist(exclusiveMaximum_, value, GetExclusiveMaximumString());
        if (const ValueType* v = GetMember(value, GetMultipleOfString()))
            if (v->IsNumber() && v->GetDouble() > 0.0)
                multipleOf_.CopyFrom(*v, *allocator_);
    }
References internal::Schema< SchemaDocumentType >::additionalItems_, internal::Schema< SchemaDocumentType >::additionalItemsSchema_, internal::Schema< SchemaDocumentType >::additionalProperties_, internal::Schema< SchemaDocumentType >::additionalPropertiesSchema_, internal::Schema< SchemaDocumentType >::AddType(), internal::Schema< SchemaDocumentType >::AddUniqueElement(), internal::Schema< SchemaDocumentType >::allocator_, internal::Schema< SchemaDocumentType >::allOf_, internal::Schema< SchemaDocumentType >::anyOf_, internal::Schema< SchemaDocumentType >::AssignIfExist(), internal::Schema< SchemaDocumentType >::CreatePattern(), internal::Schema< SchemaDocumentType >::Property::dependencies, internal::Schema< SchemaDocumentType >::Property::dependenciesValidatorIndex, internal::Schema< SchemaDocumentType >::enum_, internal::Schema< SchemaDocumentType >::enumCount_, internal::Schema< SchemaDocumentType >::exclusiveMaximum_, internal::Schema< SchemaDocumentType >::exclusiveMinimum_, internal::Schema< SchemaDocumentType >::FindPropertyIndex(), internal::Schema< SchemaDocumentType >::GetMember(), internal::Schema< SchemaDocumentType >::hasDependencies_, internal::Schema< SchemaDocumentType >::hasRequired_, internal::Schema< SchemaDocumentType >::hasSchemaDependencies_, process_bag::i, internal::Schema< SchemaDocumentType >::itemsList_, internal::Schema< SchemaDocumentType >::itemsTuple_, internal::Schema< SchemaDocumentType >::itemsTupleCount_, kArrayType, internal::Schema< SchemaDocumentType >::maximum_, internal::Schema< SchemaDocumentType >::maxItems_, internal::Schema< SchemaDocumentType >::maxLength_, internal::Schema< SchemaDocumentType >::maxProperties_, internal::Schema< SchemaDocumentType >::minimum_, internal::Schema< SchemaDocumentType >::minItems_, internal::Schema< SchemaDocumentType >::minLength_, internal::Schema< SchemaDocumentType >::minProperties_, internal::Schema< SchemaDocumentType >::multipleOf_, internal::Schema< SchemaDocumentType >::Property::name, internal::Schema< SchemaDocumentType >::not_, internal::Schema< SchemaDocumentType >::notValidatorIndex_, internal::Schema< SchemaDocumentType >::oneOf_, internal::Schema< SchemaDocumentType >::PatternProperty::pattern, internal::Schema< SchemaDocumentType >::pattern_, internal::Schema< SchemaDocumentType >::patternProperties_, internal::Schema< SchemaDocumentType >::patternPropertyCount_, internal::Schema< SchemaDocumentType >::properties_, internal::Schema< SchemaDocumentType >::propertyCount_, internal::Schema< SchemaDocumentType >::Property::required, internal::Schema< SchemaDocumentType >::Property::schema, SizeType, internal::Schema< SchemaDocumentType >::type_, internal::Schema< SchemaDocumentType >::typeless_, internal::Schema< SchemaDocumentType >::uniqueItems_, internal::Schema< SchemaDocumentType >::validatorCount_, and value.
~Schema()
template<typename SchemaDocumentType > internal::Schema< SchemaDocumentType >::~Schema () inline
Definition at line 578 of file schema.h.
              {
        AllocatorType::Free(enum_);
        if (properties_) {
            for (SizeType i = 0; i < propertyCount_; i++)
                properties_[i].~Property();
            AllocatorType::Free(properties_);
        }
        if (patternProperties_) {
            for (SizeType i = 0; i < patternPropertyCount_; i++)
                patternProperties_[i].~PatternProperty();
            AllocatorType::Free(patternProperties_);
        }
        AllocatorType::Free(itemsTuple_);
#if RAPIDJSON_SCHEMA_HAS_REGEX
        if (pattern_) {
            pattern_->~RegexType();
            AllocatorType::Free(pattern_);
        }
#endif
    }
References internal::Schema< SchemaDocumentType >::enum_, process_bag::i, internal::Schema< SchemaDocumentType >::itemsTuple_, internal::Schema< SchemaDocumentType >::pattern_, internal::Schema< SchemaDocumentType >::patternProperties_, internal::Schema< SchemaDocumentType >::patternPropertyCount_, internal::Schema< SchemaDocumentType >::properties_, internal::Schema< SchemaDocumentType >::propertyCount_, and SizeType.
Member Function Documentation
AddType()
template<typename SchemaDocumentType > void internal::Schema< SchemaDocumentType >::AddType (const ValueType & type) inline private
Definition at line 1036 of file schema.h.
{
        if      (type == GetNullString()   ) type_ |= 1 << kNullSchemaType;
        else if (type == GetBooleanString()) type_ |= 1 << kBooleanSchemaType;
        else if (type == GetObjectString() ) type_ |= 1 << kObjectSchemaType;
        else if (type == GetArrayString()  ) type_ |= 1 << kArraySchemaType;
        else if (type == GetStringString() ) type_ |= 1 << kStringSchemaType;
        else if (type == GetIntegerString()) type_ |= 1 << kIntegerSchemaType;
        else if (type == GetNumberString() ) type_ |= (1 << kNumberSchemaType) | (1 << kIntegerSchemaType);
    }
References internal::Schema< SchemaDocumentType >::kArraySchemaType, internal::Schema< SchemaDocumentType >::kBooleanSchemaType, internal::Schema< SchemaDocumentType >::kIntegerSchemaType, internal::Schema< SchemaDocumentType >::kNullSchemaType, internal::Schema< SchemaDocumentType >::kNumberSchemaType, internal::Schema< SchemaDocumentType >::kObjectSchemaType, internal::Schema< SchemaDocumentType >::kStringSchemaType, and internal::Schema< SchemaDocumentType >::type_.
Referenced by internal::Schema< SchemaDocumentType >::Schema().
AddUniqueElement()
template<typename SchemaDocumentType > template<typename V1 , typename V2 > void internal::Schema< SchemaDocumentType >::AddUniqueElement (V1 & a, const V2 & v) inline private
Definition at line 954 of file schema.h.
{
        for (typename V1::ConstValueIterator itr = a.Begin(); itr != a.End(); ++itr)
            if (*itr == v)
                return;
        V1 c(v, *allocator_);
        a.PushBack(c, *allocator_);
    }
References a, internal::Schema< SchemaDocumentType >::allocator_, and process_traj_logs::c.
Referenced by internal::Schema< SchemaDocumentType >::Schema().
AssignIfExist() [1/3]
template<typename SchemaDocumentType > static void internal::Schema< SchemaDocumentType >::AssignIfExist (bool & out, const ValueType & value, const ValueType & name) inline static private
Definition at line 967 of file schema.h.
{
        if (const ValueType* v = GetMember(value, name))
            if (v->IsBool())
                out = v->GetBool();
    }
References internal::Schema< SchemaDocumentType >::GetMember(), and value.
Referenced by internal::Schema< SchemaDocumentType >::Schema().
AssignIfExist() [2/3]
template<typename SchemaDocumentType > void internal::Schema< SchemaDocumentType >::AssignIfExist (SchemaArray & out, SchemaDocumentType & schemaDocument, const PointerType & p, const ValueType & value, const ValueType & name, const ValueType & document) inline private
Definition at line 979 of file schema.h.
{
        if (const ValueType* v = GetMember(value, name)) {
            if (v->IsArray() && v->Size() > 0) {
                PointerType q = p.Append(name, allocator_);
                out.count = v->Size();
                out.schemas = static_cast<const Schema**>(allocator_->Malloc(out.count * sizeof(const Schema*)));
                memset(out.schemas, 0, sizeof(Schema*)* out.count);
                for (SizeType i = 0; i < out.count; i++)
                    schemaDocument.CreateSchema(&out.schemas[i], q.Append(i, allocator_), (*v)[i], document);
                out.begin = validatorCount_;
                validatorCount_ += out.count;
            }
        }
    }
References internal::Schema< SchemaDocumentType >::allocator_, internal::Schema< SchemaDocumentType >::SchemaArray::begin, internal::Schema< SchemaDocumentType >::SchemaArray::count, internal::Schema< SchemaDocumentType >::GetMember(), process_bag::i, internal::Schema< SchemaDocumentType >::SchemaArray::schemas, SizeType, internal::Schema< SchemaDocumentType >::validatorCount_, and value.
AssignIfExist() [3/3]
template<typename SchemaDocumentType > static void internal::Schema< SchemaDocumentType >::AssignIfExist (SizeType & out, const ValueType & value, const ValueType & name) inline static private
Definition at line 973 of file schema.h.
{
        if (const ValueType* v = GetMember(value, name))
            if (v->IsUint64() && v->GetUint64() <= SizeType(~0))
                out = static_cast<SizeType>(v->GetUint64());
    }
References internal::Schema< SchemaDocumentType >::GetMember(), SizeType, and value.
BeginValue()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::BeginValue (Context & context) const inline
Definition at line 599 of file schema.h.
{
        if (context.inArray) {
            if (uniqueItems_)
                context.valueUniqueness = true;
            if (itemsList_)
                context.valueSchema = itemsList_;
            else if (itemsTuple_) {
                if (context.arrayElementIndex < itemsTupleCount_)
                    context.valueSchema = itemsTuple_[context.arrayElementIndex];
                else if (additionalItemsSchema_)
                    context.valueSchema = additionalItemsSchema_;
                else if (additionalItems_)
                    context.valueSchema = typeless_;
                else
                    RAPIDJSON_INVALID_KEYWORD_RETURN(GetItemsString());
            }
            else
                context.valueSchema = typeless_;
            context.arrayElementIndex++;
        }
        return true;
    }
References internal::Schema< SchemaDocumentType >::additionalItems_, internal::Schema< SchemaDocumentType >::additionalItemsSchema_, internal::SchemaValidationContext< SchemaDocumentType >::arrayElementIndex, internal::SchemaValidationContext< SchemaDocumentType >::inArray, internal::Schema< SchemaDocumentType >::itemsList_, internal::Schema< SchemaDocumentType >::itemsTuple_, internal::Schema< SchemaDocumentType >::itemsTupleCount_, RAPIDJSON_INVALID_KEYWORD_RETURN, internal::Schema< SchemaDocumentType >::typeless_, internal::Schema< SchemaDocumentType >::uniqueItems_, internal::SchemaValidationContext< SchemaDocumentType >::valueSchema, and internal::SchemaValidationContext< SchemaDocumentType >::valueUniqueness.
Bool()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::Bool (Context & context, bool) const inline
Definition at line 697 of file schema.h.
{
        if (!(type_ & (1 << kBooleanSchemaType)))
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetTypeString());
        return CreateParallelValidator(context);
    }
References internal::Schema< SchemaDocumentType >::CreateParallelValidator(), internal::Schema< SchemaDocumentType >::kBooleanSchemaType, RAPIDJSON_INVALID_KEYWORD_RETURN, and internal::Schema< SchemaDocumentType >::type_.
CheckDoubleMaximum()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::CheckDoubleMaximum (Context & context, double d) const inline private
Definition at line 1179 of file schema.h.
{
        if (exclusiveMaximum_ ? d >= maximum_.GetDouble() : d > maximum_.GetDouble())
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetMaximumString());
        return true;
    }
References internal::Schema< SchemaDocumentType >::exclusiveMaximum_, internal::Schema< SchemaDocumentType >::maximum_, and RAPIDJSON_INVALID_KEYWORD_RETURN.
Referenced by internal::Schema< SchemaDocumentType >::CheckInt(), internal::Schema< SchemaDocumentType >::CheckUint(), and internal::Schema< SchemaDocumentType >::Double().
CheckDoubleMinimum()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::CheckDoubleMinimum (Context & context, double d) const inline private
Definition at line 1173 of file schema.h.
{
        if (exclusiveMinimum_ ? d <= minimum_.GetDouble() : d < minimum_.GetDouble())
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetMinimumString());
        return true;
    }
References internal::Schema< SchemaDocumentType >::exclusiveMinimum_, internal::Schema< SchemaDocumentType >::minimum_, and RAPIDJSON_INVALID_KEYWORD_RETURN.
Referenced by internal::Schema< SchemaDocumentType >::CheckInt(), internal::Schema< SchemaDocumentType >::CheckUint(), and internal::Schema< SchemaDocumentType >::Double().
CheckDoubleMultipleOf()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::CheckDoubleMultipleOf (Context & context, double d) const inline private
Definition at line 1185 of file schema.h.
{
        double a = std::abs(d), b = std::abs(multipleOf_.GetDouble());
        double q = std::floor(a / b);
        double r = a - q * b;
        if (r > 0.0)
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetMultipleOfString());
        return true;
    }
References a, internal::Schema< SchemaDocumentType >::multipleOf_, and RAPIDJSON_INVALID_KEYWORD_RETURN.
Referenced by internal::Schema< SchemaDocumentType >::CheckInt(), internal::Schema< SchemaDocumentType >::CheckUint(), and internal::Schema< SchemaDocumentType >::Double().
CheckInt()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::CheckInt (Context & context, int64_t i) const inline private
Definition at line 1096 of file schema.h.
{
        if (!(type_ & ((1 << kIntegerSchemaType) | (1 << kNumberSchemaType))))
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetTypeString());
        if (!minimum_.IsNull()) {
            if (minimum_.IsInt64()) {
                if (exclusiveMinimum_ ? i <= minimum_.GetInt64() : i < minimum_.GetInt64())
                    RAPIDJSON_INVALID_KEYWORD_RETURN(GetMinimumString());
            }
            else if (minimum_.IsUint64()) {
                RAPIDJSON_INVALID_KEYWORD_RETURN(GetMinimumString()); // i <= max(int64_t) < minimum.GetUint64()
            }
            else if (!CheckDoubleMinimum(context, static_cast<double>(i)))
                return false;
        }
        if (!maximum_.IsNull()) {
            if (maximum_.IsInt64()) {
                if (exclusiveMaximum_ ? i >= maximum_.GetInt64() : i > maximum_.GetInt64())
                    RAPIDJSON_INVALID_KEYWORD_RETURN(GetMaximumString());
            }
            else if (maximum_.IsUint64()) { }
                /* do nothing */ // i <= max(int64_t) < maximum_.GetUint64()
            else if (!CheckDoubleMaximum(context, static_cast<double>(i)))
                return false;
        }
        if (!multipleOf_.IsNull()) {
            if (multipleOf_.IsUint64()) {
                if (static_cast<uint64_t>(i >= 0 ? i : -i) % multipleOf_.GetUint64() != 0)
                    RAPIDJSON_INVALID_KEYWORD_RETURN(GetMultipleOfString());
            }
            else if (!CheckDoubleMultipleOf(context, static_cast<double>(i)))
                return false;
        }
        return true;
    }
References internal::Schema< SchemaDocumentType >::CheckDoubleMaximum(), internal::Schema< SchemaDocumentType >::CheckDoubleMinimum(), internal::Schema< SchemaDocumentType >::CheckDoubleMultipleOf(), internal::Schema< SchemaDocumentType >::exclusiveMaximum_, internal::Schema< SchemaDocumentType >::exclusiveMinimum_, process_bag::i, internal::Schema< SchemaDocumentType >::kIntegerSchemaType, internal::Schema< SchemaDocumentType >::kNumberSchemaType, internal::Schema< SchemaDocumentType >::maximum_, internal::Schema< SchemaDocumentType >::minimum_, internal::Schema< SchemaDocumentType >::multipleOf_, RAPIDJSON_INVALID_KEYWORD_RETURN, and internal::Schema< SchemaDocumentType >::type_.
Referenced by internal::Schema< SchemaDocumentType >::Int(), and internal::Schema< SchemaDocumentType >::Int64().
CheckUint()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::CheckUint (Context & context, uint64_t i) const inline private
Definition at line 1135 of file schema.h.
{
        if (!(type_ & ((1 << kIntegerSchemaType) | (1 << kNumberSchemaType))))
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetTypeString());
        if (!minimum_.IsNull()) {
            if (minimum_.IsUint64()) {
                if (exclusiveMinimum_ ? i <= minimum_.GetUint64() : i < minimum_.GetUint64())
                    RAPIDJSON_INVALID_KEYWORD_RETURN(GetMinimumString());
            }
            else if (minimum_.IsInt64())
                /* do nothing */; // i >= 0 > minimum.Getint64()
            else if (!CheckDoubleMinimum(context, static_cast<double>(i)))
                return false;
        }
        if (!maximum_.IsNull()) {
            if (maximum_.IsUint64()) {
                if (exclusiveMaximum_ ? i >= maximum_.GetUint64() : i > maximum_.GetUint64())
                    RAPIDJSON_INVALID_KEYWORD_RETURN(GetMaximumString());
            }
            else if (maximum_.IsInt64())
                RAPIDJSON_INVALID_KEYWORD_RETURN(GetMaximumString()); // i >= 0 > maximum_
            else if (!CheckDoubleMaximum(context, static_cast<double>(i)))
                return false;
        }
        if (!multipleOf_.IsNull()) {
            if (multipleOf_.IsUint64()) {
                if (i % multipleOf_.GetUint64() != 0)
                    RAPIDJSON_INVALID_KEYWORD_RETURN(GetMultipleOfString());
            }
            else if (!CheckDoubleMultipleOf(context, static_cast<double>(i)))
                return false;
        }
        return true;
    }
References internal::Schema< SchemaDocumentType >::CheckDoubleMaximum(), internal::Schema< SchemaDocumentType >::CheckDoubleMinimum(), internal::Schema< SchemaDocumentType >::CheckDoubleMultipleOf(), internal::Schema< SchemaDocumentType >::exclusiveMaximum_, internal::Schema< SchemaDocumentType >::exclusiveMinimum_, process_bag::i, internal::Schema< SchemaDocumentType >::kIntegerSchemaType, internal::Schema< SchemaDocumentType >::kNumberSchemaType, internal::Schema< SchemaDocumentType >::maximum_, internal::Schema< SchemaDocumentType >::minimum_, internal::Schema< SchemaDocumentType >::multipleOf_, RAPIDJSON_INVALID_KEYWORD_RETURN, and internal::Schema< SchemaDocumentType >::type_.
Referenced by internal::Schema< SchemaDocumentType >::Uint(), and internal::Schema< SchemaDocumentType >::Uint64().
CreateParallelValidator()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::CreateParallelValidator (Context & context) const inline private
Definition at line 1046 of file schema.h.
{
        if (enum_ || context.arrayUniqueness)
            context.hasher = context.factory.CreateHasher();
        if (validatorCount_) {
            RAPIDJSON_ASSERT(context.validators == 0);
            context.validators = static_cast<ISchemaValidator**>(context.factory.MallocState(sizeof(ISchemaValidator*) * validatorCount_));
            context.validatorCount = validatorCount_;
            if (allOf_.schemas)
                CreateSchemaValidators(context, allOf_);
            if (anyOf_.schemas)
                CreateSchemaValidators(context, anyOf_);
            if (oneOf_.schemas)
                CreateSchemaValidators(context, oneOf_);
            if (not_)
                context.validators[notValidatorIndex_] = context.factory.CreateSchemaValidator(*not_);
            if (hasSchemaDependencies_) {
                for (SizeType i = 0; i < propertyCount_; i++)
                    if (properties_[i].dependenciesSchema)
                        context.validators[properties_[i].dependenciesValidatorIndex] = context.factory.CreateSchemaValidator(*properties_[i].dependenciesSchema);
            }
        }
        return true;
    }
References internal::Schema< SchemaDocumentType >::allOf_, internal::Schema< SchemaDocumentType >::anyOf_, internal::SchemaValidationContext< SchemaDocumentType >::arrayUniqueness, internal::ISchemaStateFactory< SchemaType >::CreateHasher(), internal::ISchemaStateFactory< SchemaType >::CreateSchemaValidator(), internal::Schema< SchemaDocumentType >::CreateSchemaValidators(), internal::Schema< SchemaDocumentType >::Property::dependenciesValidatorIndex, internal::Schema< SchemaDocumentType >::enum_, internal::SchemaValidationContext< SchemaDocumentType >::factory, internal::SchemaValidationContext< SchemaDocumentType >::hasher, internal::Schema< SchemaDocumentType >::hasSchemaDependencies_, process_bag::i, internal::ISchemaStateFactory< SchemaType >::MallocState(), internal::Schema< SchemaDocumentType >::not_, internal::Schema< SchemaDocumentType >::notValidatorIndex_, internal::Schema< SchemaDocumentType >::oneOf_, internal::Schema< SchemaDocumentType >::properties_, internal::Schema< SchemaDocumentType >::propertyCount_, RAPIDJSON_ASSERT, internal::Schema< SchemaDocumentType >::SchemaArray::schemas, SizeType, internal::SchemaValidationContext< SchemaDocumentType >::validatorCount, internal::Schema< SchemaDocumentType >::validatorCount_, and internal::SchemaValidationContext< SchemaDocumentType >::validators.
Referenced by internal::Schema< SchemaDocumentType >::Bool(), internal::Schema< SchemaDocumentType >::Double(), internal::Schema< SchemaDocumentType >::Int(), internal::Schema< SchemaDocumentType >::Int64(), internal::Schema< SchemaDocumentType >::Null(), internal::Schema< SchemaDocumentType >::StartArray(), internal::Schema< SchemaDocumentType >::StartObject(), internal::Schema< SchemaDocumentType >::String(), internal::Schema< SchemaDocumentType >::Uint(), and internal::Schema< SchemaDocumentType >::Uint64().
CreatePattern()
template<typename SchemaDocumentType > template<typename ValueType > RegexType * internal::Schema< SchemaDocumentType >::CreatePattern (const ValueType & value) inline private
Definition at line 996 of file schema.h.
{
        if (value.IsString()) {
            RegexType* r = new (allocator_->Malloc(sizeof(RegexType))) RegexType(value.GetString());
            if (!r->IsValid()) {
                r->~RegexType();
                AllocatorType::Free(r);
                r = 0;
            }
            return r;
        }
        return 0;
    }
References internal::Schema< SchemaDocumentType >::allocator_, internal::GenericRegex< Encoding, Allocator >::IsValid(), and value.
Referenced by internal::Schema< SchemaDocumentType >::Schema().
CreateSchemaValidators()
template<typename SchemaDocumentType > void internal::Schema< SchemaDocumentType >::CreateSchemaValidators (Context & context, const SchemaArray & schemas) const inline private
Definition at line 1077 of file schema.h.
{
        for (SizeType i = 0; i < schemas.count; i++)
            context.validators[schemas.begin + i] = context.factory.CreateSchemaValidator(*schemas.schemas[i]);
    }
References internal::Schema< SchemaDocumentType >::SchemaArray::begin, internal::Schema< SchemaDocumentType >::SchemaArray::count, internal::ISchemaStateFactory< SchemaType >::CreateSchemaValidator(), internal::SchemaValidationContext< SchemaDocumentType >::factory, process_bag::i, internal::Schema< SchemaDocumentType >::SchemaArray::schemas, SizeType, and internal::SchemaValidationContext< SchemaDocumentType >::validators.
Referenced by internal::Schema< SchemaDocumentType >::CreateParallelValidator().
Double()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::Double (Context & context, double d) const inline
Definition at line 727 of file schema.h.
{
        if (!(type_ & (1 << kNumberSchemaType)))
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetTypeString());
        if (!minimum_.IsNull() && !CheckDoubleMinimum(context, d))
            return false;
        if (!maximum_.IsNull() && !CheckDoubleMaximum(context, d))
            return false;
        if (!multipleOf_.IsNull() && !CheckDoubleMultipleOf(context, d))
            return false;
        return CreateParallelValidator(context);
    }
References internal::Schema< SchemaDocumentType >::CheckDoubleMaximum(), internal::Schema< SchemaDocumentType >::CheckDoubleMinimum(), internal::Schema< SchemaDocumentType >::CheckDoubleMultipleOf(), internal::Schema< SchemaDocumentType >::CreateParallelValidator(), internal::Schema< SchemaDocumentType >::kNumberSchemaType, internal::Schema< SchemaDocumentType >::maximum_, internal::Schema< SchemaDocumentType >::minimum_, internal::Schema< SchemaDocumentType >::multipleOf_, RAPIDJSON_INVALID_KEYWORD_RETURN, and internal::Schema< SchemaDocumentType >::type_.
EndArray()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::EndArray (Context & context, SizeType elementCount) const inline
Definition at line 869 of file schema.h.
{
        context.inArray = false;
        if (elementCount < minItems_)
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetMinItemsString());
        if (elementCount > maxItems_)
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetMaxItemsString());
        return true;
    }
References internal::SchemaValidationContext< SchemaDocumentType >::inArray, internal::Schema< SchemaDocumentType >::maxItems_, internal::Schema< SchemaDocumentType >::minItems_, and RAPIDJSON_INVALID_KEYWORD_RETURN.
EndObject()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::EndObject (Context & context, SizeType memberCount) const inline
Definition at line 829 of file schema.h.
{
        if (hasRequired_)
            for (SizeType index = 0; index < propertyCount_; index++)
                if (properties_[index].required)
                    if (!context.propertyExist[index])
                        RAPIDJSON_INVALID_KEYWORD_RETURN(GetRequiredString());
        if (memberCount < minProperties_)
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetMinPropertiesString());
        if (memberCount > maxProperties_)
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetMaxPropertiesString());
        if (hasDependencies_) {
            for (SizeType sourceIndex = 0; sourceIndex < propertyCount_; sourceIndex++)
                if (context.propertyExist[sourceIndex]) {
                    if (properties_[sourceIndex].dependencies) {
                        for (SizeType targetIndex = 0; targetIndex < propertyCount_; targetIndex++)
                            if (properties_[sourceIndex].dependencies[targetIndex] && !context.propertyExist[targetIndex])
                                RAPIDJSON_INVALID_KEYWORD_RETURN(GetDependenciesString());
                    }
                    else if (properties_[sourceIndex].dependenciesSchema)
                        if (!context.validators[properties_[sourceIndex].dependenciesValidatorIndex]->IsValid())
                            RAPIDJSON_INVALID_KEYWORD_RETURN(GetDependenciesString());
                }
        }
        return true;
    }
References internal::Schema< SchemaDocumentType >::Property::dependenciesValidatorIndex, internal::Schema< SchemaDocumentType >::hasDependencies_, internal::Schema< SchemaDocumentType >::hasRequired_, internal::ISchemaValidator::IsValid(), internal::Schema< SchemaDocumentType >::maxProperties_, internal::Schema< SchemaDocumentType >::minProperties_, internal::Schema< SchemaDocumentType >::properties_, internal::Schema< SchemaDocumentType >::propertyCount_, internal::SchemaValidationContext< SchemaDocumentType >::propertyExist, RAPIDJSON_INVALID_KEYWORD_RETURN, SizeType, and internal::SchemaValidationContext< SchemaDocumentType >::validators.
EndValue()
template<typename SchemaDocumentType > RAPIDJSON_FORCEINLINE bool internal::Schema< SchemaDocumentType >::EndValue (Context & context) const inline
Definition at line 624 of file schema.h.
{
        if (context.patternPropertiesValidatorCount > 0) {
            bool otherValid = false;
            SizeType count = context.patternPropertiesValidatorCount;
            if (context.objectPatternValidatorType != Context::kPatternValidatorOnly)
                otherValid = context.patternPropertiesValidators[--count]->IsValid();
            bool patternValid = true;
            for (SizeType i = 0; i < count; i++)
                if (!context.patternPropertiesValidators[i]->IsValid()) {
                    patternValid = false;
                    break;
                }
            if (context.objectPatternValidatorType == Context::kPatternValidatorOnly) {
                if (!patternValid)
                    RAPIDJSON_INVALID_KEYWORD_RETURN(GetPatternPropertiesString());
            }
            else if (context.objectPatternValidatorType == Context::kPatternValidatorWithProperty) {
                if (!patternValid || !otherValid)
                    RAPIDJSON_INVALID_KEYWORD_RETURN(GetPatternPropertiesString());
            }
            else if (!patternValid && !otherValid) // kPatternValidatorWithAdditionalProperty)
                RAPIDJSON_INVALID_KEYWORD_RETURN(GetPatternPropertiesString());
        }
        if (enum_) {
            const uint64_t h = context.factory.GetHashCode(context.hasher);
            for (SizeType i = 0; i < enumCount_; i++)
                if (enum_[i] == h)
                    goto foundEnum;
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetEnumString());
            foundEnum:;
        }
        if (allOf_.schemas)
            for (SizeType i = allOf_.begin; i < allOf_.begin + allOf_.count; i++)
                if (!context.validators[i]->IsValid())
                    RAPIDJSON_INVALID_KEYWORD_RETURN(GetAllOfString());
        if (anyOf_.schemas) {
            for (SizeType i = anyOf_.begin; i < anyOf_.begin + anyOf_.count; i++)
                if (context.validators[i]->IsValid())
                    goto foundAny;
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetAnyOfString());
            foundAny:;
        }
        if (oneOf_.schemas) {
            bool oneValid = false;
            for (SizeType i = oneOf_.begin; i < oneOf_.begin + oneOf_.count; i++)
                if (context.validators[i]->IsValid()) {
                    if (oneValid)
                        RAPIDJSON_INVALID_KEYWORD_RETURN(GetOneOfString());
                    else
                        oneValid = true;
                }
            if (!oneValid)
                RAPIDJSON_INVALID_KEYWORD_RETURN(GetOneOfString());
        }
        if (not_ && context.validators[notValidatorIndex_]->IsValid())
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetNotString());
        return true;
    }
References internal::Schema< SchemaDocumentType >::allOf_, internal::Schema< SchemaDocumentType >::anyOf_, internal::Schema< SchemaDocumentType >::SchemaArray::begin, internal::Schema< SchemaDocumentType >::SchemaArray::count, internal::Schema< SchemaDocumentType >::enum_, internal::Schema< SchemaDocumentType >::enumCount_, internal::SchemaValidationContext< SchemaDocumentType >::factory, internal::ISchemaStateFactory< SchemaType >::GetHashCode(), internal::SchemaValidationContext< SchemaDocumentType >::hasher, process_bag::i, internal::ISchemaValidator::IsValid(), internal::SchemaValidationContext< SchemaDocumentType >::kPatternValidatorOnly, internal::SchemaValidationContext< SchemaDocumentType >::kPatternValidatorWithProperty, internal::Schema< SchemaDocumentType >::not_, internal::Schema< SchemaDocumentType >::notValidatorIndex_, internal::SchemaValidationContext< SchemaDocumentType >::objectPatternValidatorType, internal::Schema< SchemaDocumentType >::oneOf_, internal::SchemaValidationContext< SchemaDocumentType >::patternPropertiesValidatorCount, internal::SchemaValidationContext< SchemaDocumentType >::patternPropertiesValidators, RAPIDJSON_INVALID_KEYWORD_RETURN, internal::Schema< SchemaDocumentType >::SchemaArray::schemas, SizeType, and internal::SchemaValidationContext< SchemaDocumentType >::validators.
FindPropertyIndex()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::FindPropertyIndex (const ValueType & name, SizeType * outIndex) const inline private
Definition at line 1083 of file schema.h.
{
        SizeType len = name.GetStringLength();
        const Ch* str = name.GetString();
        for (SizeType index = 0; index < propertyCount_; index++)
            if (properties_[index].name.GetStringLength() == len &&
                (std::memcmp(properties_[index].name.GetString(), str, sizeof(Ch) * len) == 0))
            {
                *outIndex = index;
                return true;
            }
        return false;
    }
References internal::Schema< SchemaDocumentType >::Property::name, internal::Schema< SchemaDocumentType >::properties_, internal::Schema< SchemaDocumentType >::propertyCount_, and SizeType.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::Key().
GetMember()
template<typename SchemaDocumentType > static const ValueType * internal::Schema< SchemaDocumentType >::GetMember (const ValueType & value, const ValueType & name) inline static private
Definition at line 962 of file schema.h.
{
        typename ValueType::ConstMemberIterator itr = value.FindMember(name);
        return itr != value.MemberEnd() ? &(itr->value) : 0;
    }
References value.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::AssignIfExist().
Int()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::Int (Context & context, int i) const inline
Definition at line 703 of file schema.h.
{
        if (!CheckInt(context, i))
            return false;
        return CreateParallelValidator(context);
    }
References internal::Schema< SchemaDocumentType >::CheckInt(), internal::Schema< SchemaDocumentType >::CreateParallelValidator(), and process_bag::i.
Int64()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::Int64 (Context & context, int64_t i) const inline
Definition at line 715 of file schema.h.
{
        if (!CheckInt(context, i))
            return false;
        return CreateParallelValidator(context);
    }
References internal::Schema< SchemaDocumentType >::CheckInt(), internal::Schema< SchemaDocumentType >::CreateParallelValidator(), and process_bag::i.
IsPatternMatch()
template<typename SchemaDocumentType > static bool internal::Schema< SchemaDocumentType >::IsPatternMatch (const RegexType * pattern, const Ch * str, SizeType) inline static private
Definition at line 1009 of file schema.h.
{
        GenericRegexSearch<RegexType> rs(*pattern);
        return rs.Search(str);
    }
References internal::GenericRegexSearch< RegexType, Allocator >::Search().
Referenced by internal::Schema< SchemaDocumentType >::Key(), and internal::Schema< SchemaDocumentType >::String().
Key()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::Key (Context & context, const Ch * str, SizeType len, bool) const inline
Definition at line 782 of file schema.h.
{
        if (patternProperties_) {
            context.patternPropertiesSchemaCount = 0;
            for (SizeType i = 0; i < patternPropertyCount_; i++)
                if (patternProperties_[i].pattern && IsPatternMatch(patternProperties_[i].pattern, str, len)) {
                    context.patternPropertiesSchemas[context.patternPropertiesSchemaCount++] = patternProperties_[i].schema;
                    context.valueSchema = typeless_;
                }
        }
        SizeType index;
        if (FindPropertyIndex(ValueType(str, len).Move(), &index)) {
            if (context.patternPropertiesSchemaCount > 0) {
                context.patternPropertiesSchemas[context.patternPropertiesSchemaCount++] = properties_[index].schema;
                context.valueSchema = typeless_;
                context.valuePatternValidatorType = Context::kPatternValidatorWithProperty;
            }
            else
                context.valueSchema = properties_[index].schema;
            if (context.propertyExist)
                context.propertyExist[index] = true;
            return true;
        }
        if (additionalPropertiesSchema_) {
            if (additionalPropertiesSchema_ && context.patternPropertiesSchemaCount > 0) {
                context.patternPropertiesSchemas[context.patternPropertiesSchemaCount++] = additionalPropertiesSchema_;
                context.valueSchema = typeless_;
                context.valuePatternValidatorType = Context::kPatternValidatorWithAdditionalProperty;
            }
            else
                context.valueSchema = additionalPropertiesSchema_;
            return true;
        }
        else if (additionalProperties_) {
            context.valueSchema = typeless_;
            return true;
        }
        if (context.patternPropertiesSchemaCount == 0) // patternProperties are not additional properties
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetAdditionalPropertiesString());
        return true;
    }
References internal::Schema< SchemaDocumentType >::additionalProperties_, internal::Schema< SchemaDocumentType >::additionalPropertiesSchema_, internal::Schema< SchemaDocumentType >::FindPropertyIndex(), process_bag::i, internal::Schema< SchemaDocumentType >::IsPatternMatch(), internal::SchemaValidationContext< SchemaDocumentType >::kPatternValidatorWithAdditionalProperty, internal::SchemaValidationContext< SchemaDocumentType >::kPatternValidatorWithProperty, internal::Schema< SchemaDocumentType >::patternProperties_, internal::SchemaValidationContext< SchemaDocumentType >::patternPropertiesSchemaCount, internal::SchemaValidationContext< SchemaDocumentType >::patternPropertiesSchemas, internal::Schema< SchemaDocumentType >::patternPropertyCount_, internal::Schema< SchemaDocumentType >::properties_, internal::SchemaValidationContext< SchemaDocumentType >::propertyExist, RAPIDJSON_INVALID_KEYWORD_RETURN, internal::Schema< SchemaDocumentType >::Property::schema, internal::Schema< SchemaDocumentType >::PatternProperty::schema, SizeType, internal::Schema< SchemaDocumentType >::typeless_, internal::SchemaValidationContext< SchemaDocumentType >::valuePatternValidatorType, and internal::SchemaValidationContext< SchemaDocumentType >::valueSchema.
Null()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::Null (Context & context) const inline
Definition at line 691 of file schema.h.
{
        if (!(type_ & (1 << kNullSchemaType)))
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetTypeString());
        return CreateParallelValidator(context);
    }
References internal::Schema< SchemaDocumentType >::CreateParallelValidator(), internal::Schema< SchemaDocumentType >::kNullSchemaType, RAPIDJSON_INVALID_KEYWORD_RETURN, and internal::Schema< SchemaDocumentType >::type_.
StartArray()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::StartArray (Context & context) const inline
Definition at line 859 of file schema.h.
{
        if (!(type_ & (1 << kArraySchemaType)))
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetTypeString());
        context.arrayElementIndex = 0;
        context.inArray = true;
        return CreateParallelValidator(context);
    }
References internal::SchemaValidationContext< SchemaDocumentType >::arrayElementIndex, internal::Schema< SchemaDocumentType >::CreateParallelValidator(), internal::SchemaValidationContext< SchemaDocumentType >::inArray, internal::Schema< SchemaDocumentType >::kArraySchemaType, RAPIDJSON_INVALID_KEYWORD_RETURN, and internal::Schema< SchemaDocumentType >::type_.
StartObject()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::StartObject (Context & context) const inline
Definition at line 763 of file schema.h.
{
        if (!(type_ & (1 << kObjectSchemaType)))
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetTypeString());
        if (hasDependencies_ || hasRequired_) {
            context.propertyExist = static_cast<bool*>(context.factory.MallocState(sizeof(bool) * propertyCount_));
            std::memset(context.propertyExist, 0, sizeof(bool) * propertyCount_);
        }
        if (patternProperties_) { // pre-allocate schema array
            SizeType count = patternPropertyCount_ + 1; // extra for valuePatternValidatorType
            context.patternPropertiesSchemas = static_cast<const SchemaType**>(context.factory.MallocState(sizeof(const SchemaType*) * count));
            context.patternPropertiesSchemaCount = 0;
            std::memset(context.patternPropertiesSchemas, 0, sizeof(SchemaType*) * count);
        }
        return CreateParallelValidator(context);
    }
References internal::Schema< SchemaDocumentType >::CreateParallelValidator(), internal::SchemaValidationContext< SchemaDocumentType >::factory, internal::Schema< SchemaDocumentType >::hasDependencies_, internal::Schema< SchemaDocumentType >::hasRequired_, internal::Schema< SchemaDocumentType >::kObjectSchemaType, internal::ISchemaStateFactory< SchemaType >::MallocState(), internal::Schema< SchemaDocumentType >::patternProperties_, internal::SchemaValidationContext< SchemaDocumentType >::patternPropertiesSchemaCount, internal::SchemaValidationContext< SchemaDocumentType >::patternPropertiesSchemas, internal::Schema< SchemaDocumentType >::patternPropertyCount_, internal::Schema< SchemaDocumentType >::propertyCount_, internal::SchemaValidationContext< SchemaDocumentType >::propertyExist, RAPIDJSON_INVALID_KEYWORD_RETURN, SizeType, and internal::Schema< SchemaDocumentType >::type_.
String()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::String (Context & context, const Ch * str, SizeType length, bool) const inline
Definition at line 743 of file schema.h.
{
        if (!(type_ & (1 << kStringSchemaType)))
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetTypeString());
        if (minLength_ != 0 || maxLength_ != SizeType(~0)) {
            SizeType count;
            if (internal::CountStringCodePoint<EncodingType>(str, length, &count)) {
                if (count < minLength_)
                    RAPIDJSON_INVALID_KEYWORD_RETURN(GetMinLengthString());
                if (count > maxLength_)
                    RAPIDJSON_INVALID_KEYWORD_RETURN(GetMaxLengthString());
            }
        }
        if (pattern_ && !IsPatternMatch(pattern_, str, length))
            RAPIDJSON_INVALID_KEYWORD_RETURN(GetPatternString());
        return CreateParallelValidator(context);
    }
References internal::Schema< SchemaDocumentType >::CreateParallelValidator(), internal::Schema< SchemaDocumentType >::IsPatternMatch(), internal::Schema< SchemaDocumentType >::kStringSchemaType, internal::Schema< SchemaDocumentType >::maxLength_, internal::Schema< SchemaDocumentType >::minLength_, internal::Schema< SchemaDocumentType >::pattern_, RAPIDJSON_INVALID_KEYWORD_RETURN, SizeType, and internal::Schema< SchemaDocumentType >::type_.
Uint()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::Uint (Context & context, unsigned u) const inline
Definition at line 709 of file schema.h.
{
        if (!CheckUint(context, u))
            return false;
        return CreateParallelValidator(context);
    }
References internal::Schema< SchemaDocumentType >::CheckUint(), and internal::Schema< SchemaDocumentType >::CreateParallelValidator().
Uint64()
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::Uint64 (Context & context, uint64_t u) const inline
Definition at line 721 of file schema.h.
{
        if (!CheckUint(context, u))
            return false;
        return CreateParallelValidator(context);
    }
References internal::Schema< SchemaDocumentType >::CheckUint(), and internal::Schema< SchemaDocumentType >::CreateParallelValidator().
Friends And Related Function Documentation
GenericSchemaDocument< ValueType, AllocatorType >
template<typename SchemaDocumentType > friend class GenericSchemaDocument< ValueType, AllocatorType > friend
Definition at line 347 of file schema.h.
Member Data Documentation
additionalItems_
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::additionalItems_ private
Definition at line 1247 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::BeginValue().
additionalItemsSchema_
template<typename SchemaDocumentType > const SchemaType* internal::Schema< SchemaDocumentType >::additionalItemsSchema_ private
Definition at line 1241 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::BeginValue().
additionalProperties_
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::additionalProperties_ private
Definition at line 1236 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::Key().
additionalPropertiesSchema_
template<typename SchemaDocumentType > const SchemaType* internal::Schema< SchemaDocumentType >::additionalPropertiesSchema_ private
Definition at line 1230 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::Key().
allocator_
template<typename SchemaDocumentType > AllocatorType* internal::Schema< SchemaDocumentType >::allocator_ private
Definition at line 1217 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::AddUniqueElement(), internal::Schema< SchemaDocumentType >::AssignIfExist(), and internal::Schema< SchemaDocumentType >::CreatePattern().
allOf_
template<typename SchemaDocumentType > SchemaArray internal::Schema< SchemaDocumentType >::allOf_ private
Definition at line 1221 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::CreateParallelValidator(), and internal::Schema< SchemaDocumentType >::EndValue().
anyOf_
template<typename SchemaDocumentType > SchemaArray internal::Schema< SchemaDocumentType >::anyOf_ private
Definition at line 1222 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::CreateParallelValidator(), and internal::Schema< SchemaDocumentType >::EndValue().
enum_
template<typename SchemaDocumentType > uint64_t* internal::Schema< SchemaDocumentType >::enum_ private
Definition at line 1219 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::~Schema(), internal::Schema< SchemaDocumentType >::CreateParallelValidator(), and internal::Schema< SchemaDocumentType >::EndValue().
enumCount_
template<typename SchemaDocumentType > SizeType internal::Schema< SchemaDocumentType >::enumCount_ private
Definition at line 1220 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::EndValue().
exclusiveMaximum_
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::exclusiveMaximum_ private
Definition at line 1258 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::CheckDoubleMaximum(), internal::Schema< SchemaDocumentType >::CheckInt(), and internal::Schema< SchemaDocumentType >::CheckUint().
exclusiveMinimum_
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::exclusiveMinimum_ private
Definition at line 1257 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::CheckDoubleMinimum(), internal::Schema< SchemaDocumentType >::CheckInt(), and internal::Schema< SchemaDocumentType >::CheckUint().
hasDependencies_
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::hasDependencies_ private
Definition at line 1237 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::EndObject(), and internal::Schema< SchemaDocumentType >::StartObject().
hasRequired_
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::hasRequired_ private
Definition at line 1238 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::EndObject(), and internal::Schema< SchemaDocumentType >::StartObject().
hasSchemaDependencies_
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::hasSchemaDependencies_ private
Definition at line 1239 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::CreateParallelValidator().
itemsList_
template<typename SchemaDocumentType > const SchemaType* internal::Schema< SchemaDocumentType >::itemsList_ private
Definition at line 1242 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::BeginValue().
itemsTuple_
template<typename SchemaDocumentType > const SchemaType** internal::Schema< SchemaDocumentType >::itemsTuple_ private
Definition at line 1243 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::~Schema(), and internal::Schema< SchemaDocumentType >::BeginValue().
itemsTupleCount_
template<typename SchemaDocumentType > SizeType internal::Schema< SchemaDocumentType >::itemsTupleCount_ private
Definition at line 1244 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::BeginValue().
maximum_
template<typename SchemaDocumentType > SValue internal::Schema< SchemaDocumentType >::maximum_ private
Definition at line 1255 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::CheckDoubleMaximum(), internal::Schema< SchemaDocumentType >::CheckInt(), internal::Schema< SchemaDocumentType >::CheckUint(), and internal::Schema< SchemaDocumentType >::Double().
maxItems_
template<typename SchemaDocumentType > SizeType internal::Schema< SchemaDocumentType >::maxItems_ private
Definition at line 1246 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::EndArray().
maxLength_
template<typename SchemaDocumentType > SizeType internal::Schema< SchemaDocumentType >::maxLength_ private
Definition at line 1252 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::String().
maxProperties_
template<typename SchemaDocumentType > SizeType internal::Schema< SchemaDocumentType >::maxProperties_ private
Definition at line 1235 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::EndObject().
minimum_
template<typename SchemaDocumentType > SValue internal::Schema< SchemaDocumentType >::minimum_ private
Definition at line 1254 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::CheckDoubleMinimum(), internal::Schema< SchemaDocumentType >::CheckInt(), internal::Schema< SchemaDocumentType >::CheckUint(), and internal::Schema< SchemaDocumentType >::Double().
minItems_
template<typename SchemaDocumentType > SizeType internal::Schema< SchemaDocumentType >::minItems_ private
Definition at line 1245 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::EndArray().
minLength_
template<typename SchemaDocumentType > SizeType internal::Schema< SchemaDocumentType >::minLength_ private
Definition at line 1251 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::String().
minProperties_
template<typename SchemaDocumentType > SizeType internal::Schema< SchemaDocumentType >::minProperties_ private
Definition at line 1234 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::EndObject().
multipleOf_
template<typename SchemaDocumentType > SValue internal::Schema< SchemaDocumentType >::multipleOf_ private
Definition at line 1256 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::CheckDoubleMultipleOf(), internal::Schema< SchemaDocumentType >::CheckInt(), internal::Schema< SchemaDocumentType >::CheckUint(), and internal::Schema< SchemaDocumentType >::Double().
not_
template<typename SchemaDocumentType > const SchemaType* internal::Schema< SchemaDocumentType >::not_ private
Definition at line 1224 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::CreateParallelValidator(), and internal::Schema< SchemaDocumentType >::EndValue().
notValidatorIndex_
template<typename SchemaDocumentType > SizeType internal::Schema< SchemaDocumentType >::notValidatorIndex_ private
Definition at line 1227 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::CreateParallelValidator(), and internal::Schema< SchemaDocumentType >::EndValue().
oneOf_
template<typename SchemaDocumentType > SchemaArray internal::Schema< SchemaDocumentType >::oneOf_ private
Definition at line 1223 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::CreateParallelValidator(), and internal::Schema< SchemaDocumentType >::EndValue().
pattern_
template<typename SchemaDocumentType > RegexType* internal::Schema< SchemaDocumentType >::pattern_ private
Definition at line 1250 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::~Schema(), and internal::Schema< SchemaDocumentType >::String().
patternProperties_
template<typename SchemaDocumentType > PatternProperty* internal::Schema< SchemaDocumentType >::patternProperties_ private
Definition at line 1231 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::~Schema(), internal::Schema< SchemaDocumentType >::Key(), and internal::Schema< SchemaDocumentType >::StartObject().
patternPropertyCount_
template<typename SchemaDocumentType > SizeType internal::Schema< SchemaDocumentType >::patternPropertyCount_ private
Definition at line 1232 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::~Schema(), internal::Schema< SchemaDocumentType >::Key(), and internal::Schema< SchemaDocumentType >::StartObject().
properties_
template<typename SchemaDocumentType > Property* internal::Schema< SchemaDocumentType >::properties_ private
Definition at line 1229 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::~Schema(), internal::Schema< SchemaDocumentType >::CreateParallelValidator(), internal::Schema< SchemaDocumentType >::EndObject(), internal::Schema< SchemaDocumentType >::FindPropertyIndex(), and internal::Schema< SchemaDocumentType >::Key().
propertyCount_
template<typename SchemaDocumentType > SizeType internal::Schema< SchemaDocumentType >::propertyCount_ private
Definition at line 1233 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::~Schema(), internal::Schema< SchemaDocumentType >::CreateParallelValidator(), internal::Schema< SchemaDocumentType >::EndObject(), internal::Schema< SchemaDocumentType >::FindPropertyIndex(), and internal::Schema< SchemaDocumentType >::StartObject().
type_
template<typename SchemaDocumentType > unsigned internal::Schema< SchemaDocumentType >::type_ private
Definition at line 1225 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::AddType(), internal::Schema< SchemaDocumentType >::Bool(), internal::Schema< SchemaDocumentType >::CheckInt(), internal::Schema< SchemaDocumentType >::CheckUint(), internal::Schema< SchemaDocumentType >::Double(), internal::Schema< SchemaDocumentType >::Null(), internal::Schema< SchemaDocumentType >::StartArray(), internal::Schema< SchemaDocumentType >::StartObject(), and internal::Schema< SchemaDocumentType >::String().
typeless_
template<typename SchemaDocumentType > const SchemaType* internal::Schema< SchemaDocumentType >::typeless_ private
Definition at line 1218 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::BeginValue(), and internal::Schema< SchemaDocumentType >::Key().
uniqueItems_
template<typename SchemaDocumentType > bool internal::Schema< SchemaDocumentType >::uniqueItems_ private
Definition at line 1248 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), and internal::Schema< SchemaDocumentType >::BeginValue().
validatorCount_
template<typename SchemaDocumentType > SizeType internal::Schema< SchemaDocumentType >::validatorCount_ private
Definition at line 1226 of file schema.h.
Referenced by internal::Schema< SchemaDocumentType >::Schema(), internal::Schema< SchemaDocumentType >::AssignIfExist(), and internal::Schema< SchemaDocumentType >::CreateParallelValidator().
The documentation for this class was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/schema.h