Carma-platform: cav::DriverApplication Class Reference
cav::DriverApplication Class Reference abstract
Base class for CAV Platform drivers.
#include <driver_application.h>
Public Member Functions
DriverApplication (int argc, char **argv, std::string name)
virtual ~DriverApplication ()
virtual int run () final
Starts the application.
Protected Member Functions
virtual void setStatus (cav_msgs::DriverStatus status) final
Sets the status of the DriverApplication.
virtual cav_msgs::DriverStatus getStatus () final
Get's status.
Protected Attributes
int spin_rate
should be set prior to DriverApplication beginning its control loop. Ideally inheriting classes should set the spin_rate be set within the DriverApplication::initialize() function
std::shared_ptr< ros::NodeHandle > pnh_
ROS NodeHandle within the private ("~") namespace.
std::shared_ptr< ros::NodeHandle > nh_
ROS NodeHandle within the node root namespace.
Private Member Functions
void status_publish_timer (const ros::TimerEvent &) const
Called every second to publish the status message.
bool bind_service_cb (cav_srvs::Bind::Request &req, cav_srvs::Bind::Response &res)
Callback for bind service.
bool get_driver_api_cb (cav_srvs::GetDriverApiRequest &req, cav_srvs::GetDriverApiResponse &res)
Callback go the get_driver_api service.
bool get_status_cb (cav_srvs::GetDriverStatusRequest &req, cav_srvs::GetDriverStatusResponse &res)
Callback for the get_status service.
virtual std::vector< std::string > & get_api ()=0
Returns the fully scoped API for this node.
virtual void initialize ()=0
Initialize the node prior to beginning ROS loop.
virtual void pre_spin ()=0
Called prior to spinOnce()
virtual void post_spin ()=0
Called after spinOnce()
virtual void shutdown ()
void system_alert_cb (const cav_msgs::SystemAlertConstPtr &msg)
Private Attributes
ros::Publisher driver_status_pub_
ros::Subscriber system_alert_sub_
bool shutdown_
cav_msgs::DriverStatus status_
std::unordered_map< std::string, std::shared_ptr< bond::Bond > > bond_map_
std::mutex bond_mutex_
int argc_
char ** argv_
std::string name_
Detailed Description
Base class for CAV Platform drivers.
DriverApplication is responsible for common behaviours of the drivers in the CAV Platform Architecture. It initiliazes the ROS node context and is responsible for managing the ROS "spin" loop. *
Definition at line 60 of file driver_application.h.
Constructor & Destructor Documentation
DriverApplication()
cav::DriverApplication::DriverApplication (int argc, char ** argv, std::string name)
Parameters
argc - Command line argument count
argv - Array of command line arguments
name - Node name
Definition at line 39 of file driver_application.cpp.
{
    argc_ = argc;
    argv_ = argv;
    name_ = name;
}
References argc_, argv_, and name_.
~DriverApplication()
virtual cav::DriverApplication::~DriverApplication () inline virtual
Definition at line 74 of file driver_application.h.
{};
Member Function Documentation
bind_service_cb()
bool cav::DriverApplication::bind_service_cb (cav_srvs::Bind::Request & req, cav_srvs::Bind::Response & res) private
Callback for bind service.
This node will bind on /[driver_name]/bond topic with id passed in the request
Parameters
req
res
Returns
Definition at line 117 of file driver_application.cpp.
{
    std::unique_lock<std::mutex> lock(bond_mutex_);
    if(bond_map_.find(req.id) != bond_map_.end())
    {
        ROS_WARN_STREAM(ros::this_node::getName() << " already bonded to id: " << req.id);
        return true;
    }
    ROS_DEBUG_STREAM(ros::this_node::getName() << " binding to id: " << req.id);
    std::shared_ptr<bond::Bond> bond(new bond::Bond(ros::this_node::getName() + "/bond", req.id));
    bond->start();
    bond_map_[req.id] = bond;
    return true;
}
References bond_map_, and bond_mutex_.
Referenced by run().
get_api()
virtual std::vector< std::string > & cav::DriverApplication::get_api () private pure virtual
Returns the fully scoped API for this node.
Returns
Implemented in NS3Adapter.
Referenced by get_driver_api_cb().
get_driver_api_cb()
bool cav::DriverApplication::get_driver_api_cb (cav_srvs::GetDriverApiRequest & req, cav_srvs::GetDriverApiResponse & res) private
Callback go the get_driver_api service.
This function will return a list of API specified by the inheriting class through get_api
Parameters
req
res
Returns
true to signal we handled this callback
Definition at line 137 of file driver_application.cpp.
{
    res.api_list = get_api();
    ROS_DEBUG_STREAM("Sending API");
    return true;
}
References get_api().
Referenced by run().
get_status_cb()
bool cav::DriverApplication::get_status_cb (cav_srvs::GetDriverStatusRequest & req, cav_srvs::GetDriverStatusResponse & res) private
Callback for the get_status service.
This function will return the current status of the driver_node
Parameters
req - empty
res - contains driver status of this node
Returns
true to signal we handled this calback
Definition at line 146 of file driver_application.cpp.
{
    res.status = status_;
    return true;
}
References status_.
Referenced by run().
getStatus()
virtual cav_msgs::DriverStatus cav::DriverApplication::getStatus () inline final protected virtual
Get's status.
Returns
Definition at line 100 of file driver_application.h.
{ return status_; }
References status_.
Referenced by NS3Adapter::getDriverStatus(), NS3Adapter::onConnectHandler(), and NS3Adapter::onDisconnectHandler().
initialize()
virtual void cav::DriverApplication::initialize () private pure virtual
Initialize the node prior to beginning ROS loop.
This function is called after the DriverApplication has initialized the ROS context and nodehandles
Returns
Implemented in NS3Adapter.
Referenced by run().
post_spin()
virtual void cav::DriverApplication::post_spin () private pure virtual
Called after spinOnce()
Implemented in NS3Adapter.
Referenced by run().
pre_spin()
virtual void cav::DriverApplication::pre_spin () private pure virtual
Called prior to spinOnce()
Implemented in NS3Adapter.
Referenced by run().
run()
int cav::DriverApplication::run () final virtual
Starts the application.
Returns
0 on exit with no errors
Definition at line 46 of file driver_application.cpp.
{
    ros::init(argc_,argv_,name_);
    //Initialize nodehandles
    nh_.reset(new ros::NodeHandle());
    pnh_.reset(new ros::NodeHandle("~"));
    //Setup initial status
    status_.name = ros::this_node::getName();
    status_.status = cav_msgs::DriverStatus::OFF;
    //Initialize DriverApplication services
    ros::ServiceServer bind_service = pnh_->advertiseService("bind", &DriverApplication::bind_service_cb,this);
    ros::ServiceServer api_service = pnh_->advertiseService("get_driver_api",
                                                            &DriverApplication::get_driver_api_cb, this);
    ros::ServiceServer driver_status_svs = pnh_->advertiseService("get_status", &DriverApplication::get_status_cb,this);
    driver_status_pub_ = nh_->advertise<cav_msgs::DriverStatus>("driver_discovery",1);
    system_alert_sub_ = nh_->subscribe("/system_alert",10,&DriverApplication::system_alert_cb, this);
    ros::Timer timer = pnh_->createTimer(ros::Duration(1), &DriverApplication::status_publish_timer,this);
    ROS_INFO("Driver services initialized");
    initialize();
    ros::Rate r(spin_rate);
    while(ros::ok() && !shutdown_)
    {
        pre_spin();
        ros::spinOnce();
        post_spin();
        r.sleep();
    }
    ROS_INFO_STREAM("Driver Shutting Down");
    shutdown();
    ros::shutdown();
}
References argc_, argv_, bind_service_cb(), driver_status_pub_, get_driver_api_cb(), get_status_cb(), initialize(), name_, nh_, lightbar_manager::OFF, pnh_, post_spin(), pre_spin(), shutdown(), shutdown_, spin_rate, status_, status_publish_timer(), system_alert_cb(), and system_alert_sub_.
Referenced by main().
setStatus()
void cav::DriverApplication::setStatus (cav_msgs::DriverStatus status) final protected virtual
Sets the status of the DriverApplication.
If status is changed then the DriverApplication will release all bonds to notify to connected nodes that the status has been updated. The name is managed by the DriverApplication class and is not overriden within a call to this function
Parameters
status - The status to be set
Definition at line 97 of file driver_application.cpp.
{
    //If the driver status has been changed we need to release bonds
    //notifying connected nodes there has been a change in the status of this node
    if(!DriverStatusEquals(status,status_))
    {
        std::unique_lock<std::mutex> lock(bond_mutex_);
        ROS_INFO_STREAM("Status updated releasing bonds, Status: " << (int) status.status);
        bond_map_.clear();
        status_ = status;
        status_.name = ros::this_node::getName();
    }
}
References bond_map_, bond_mutex_, cav::DriverStatusEquals(), and status_.
Referenced by NS3Adapter::NS3Adapter(), NS3Adapter::onConnectHandler(), and NS3Adapter::onDisconnectHandler().
shutdown()
virtual void cav::DriverApplication::shutdown () inline private virtual
Reimplemented in NS3Adapter.
Definition at line 187 of file driver_application.h.
{((void)0);};
Referenced by run().
status_publish_timer()
void cav::DriverApplication::status_publish_timer (const ros::TimerEvent &) const private
Called every second to publish the status message.
Definition at line 112 of file driver_application.cpp.
{
    driver_status_pub_.publish(status_);
}
References driver_status_pub_, and status_.
Referenced by run().
system_alert_cb()
void cav::DriverApplication::system_alert_cb (const cav_msgs::SystemAlertConstPtr & msg) private
Definition at line 153 of file driver_application.cpp.
{
   switch(msg->type)
   {
       case cav_msgs::SystemAlert::FATAL:
       case cav_msgs::SystemAlert::SHUTDOWN:
           shutdown_ = true;
           break;
       default:
           break;
   }
}
References arbitrator::SHUTDOWN, and shutdown_.
Referenced by run().
Member Data Documentation
argc_
int cav::DriverApplication::argc_ private
Definition at line 198 of file driver_application.h.
Referenced by DriverApplication(), and run().
argv_
char** cav::DriverApplication::argv_ private
Definition at line 199 of file driver_application.h.
Referenced by DriverApplication(), and run().
bond_map_
std::unordered_map<std::string, std::shared_ptr<bond::Bond> > cav::DriverApplication::bond_map_ private
Definition at line 196 of file driver_application.h.
Referenced by bind_service_cb(), and setStatus().
bond_mutex_
std::mutex cav::DriverApplication::bond_mutex_ private
Definition at line 197 of file driver_application.h.
Referenced by bind_service_cb(), and setStatus().
driver_status_pub_
ros::Publisher cav::DriverApplication::driver_status_pub_ private
Definition at line 192 of file driver_application.h.
Referenced by run(), and status_publish_timer().
name_
std::string cav::DriverApplication::name_ private
Definition at line 200 of file driver_application.h.
Referenced by DriverApplication(), and run().
nh_
cav::DriverApplication::nh_ protected
ROS NodeHandle within the node root namespace.
Definition at line 118 of file driver_application.h.
Referenced by run().
pnh_
cav::DriverApplication::pnh_ protected
ROS NodeHandle within the private ("~") namespace.
Definition at line 118 of file driver_application.h.
Referenced by NS3Adapter::initialize(), and run().
shutdown_
bool cav::DriverApplication::shutdown_ private
Definition at line 194 of file driver_application.h.
Referenced by run(), and system_alert_cb().
spin_rate
cav::DriverApplication::spin_rate protected
should be set prior to DriverApplication beginning its control loop. Ideally inheriting classes should set the spin_rate be set within the DriverApplication::initialize() function
Definition at line 107 of file driver_application.h.
Referenced by NS3Adapter::initialize(), run(), and guidance_plugin_validator.guidance_plugin_validator.GuidancePluginValidator::spin().
status_
cav_msgs::DriverStatus cav::DriverApplication::status_ private
Definition at line 195 of file driver_application.h.
Referenced by get_status_cb(), getStatus(), run(), setStatus(), and status_publish_timer().
system_alert_sub_
ros::Subscriber cav::DriverApplication::system_alert_sub_ private
Definition at line 193 of file driver_application.h.
Referenced by run().
The documentation for this class was generated from the following files:
ns-3_adapter/include/driver_application/driver_application.h
ns-3_adapter/src/driver_application/driver_application.cpp