Carma-platform: cost_plugin_system::CostofFuel Class Reference
cost_plugin_system::CostofFuel Class Reference
#include <cost_fuel.hpp>
Public Member Functions
CostofFuel ()
double compute_cost (cav_msgs::ManeuverPlan plan) const
Compute the cost of a given maneuver plan.
Public Member Functions inherited from cost_plugin_system::CostPlugins
virtual double compute_cost (cav_msgs::ManeuverPlan plan) const =0
Compute the cost of a given maneuver plan.
virtual ~CostPlugins ()
Virtual destructor provided for memory safety.
Detailed Description
Definition at line 22 of file cost_fuel.hpp.
Constructor & Destructor Documentation
CostofFuel()
cost_plugin_system::CostofFuel::CostofFuel () inline
Definition at line 25 of file cost_fuel.hpp.
{};
Member Function Documentation
compute_cost()
double cost_plugin_system::CostofFuel::compute_cost (cav_msgs::ManeuverPlan plan) const virtual
Compute the cost of a given maneuver plan.
Parameters
plan The plan to evaluate
Returns
double The total cost
Implements cost_plugin_system::CostPlugins.
Definition at line 24 of file cost_fuel.cpp.
{
    double cost = 0.0;
    int maneuver_size = plan.maneuvers.size();
    for (auto it = plan.maneuvers.begin(); it != plan.maneuvers.end(); it++)
    {
        double average_speed = (cost_utils::get_maneuver_start_speed(*it) + cost_utils::get_maneuver_end_speed(*it)) / 2;
        double average_acceleration = (cost_utils::get_maneuver_end_speed(*it) - cost_utils::get_maneuver_start_speed(*it)) /
                                      (cost_utils::get_maneuver_end_time(*it).toSec() - cost_utils::get_maneuver_start_time(*it).toSec());
        cost += pow(average_speed, 2.0) + pow(average_acceleration, 2.0);
    }
    // Normalize the cost
    double coefficient = 1000;
    cost = cost / (coefficient * maneuver_size);
    return cost;
}
References cost_utils::get_maneuver_end_speed(), cost_utils::get_maneuver_end_time(), cost_utils::get_maneuver_start_speed(), and cost_utils::get_maneuver_start_time().
Referenced by cost_plugin_system::CostPluginWorker::compute_final_score().
The documentation for this class was generated from the following files:
cost_plugin_system/include/cost_fuel.hpp
cost_plugin_system/src/cost_fuel.cpp