Carma-platform: cost_plugin_system::CostofFeasibility Class Reference
cost_plugin_system::CostofFeasibility Class Reference
#include <cost_feasibility.hpp>
Public Member Functions
CostofFeasibility (double max_accelaration, double max_deceleration)
double compute_cost (cav_msgs::ManeuverPlan plan) const
Compute the cost of a given maneuver plan.
Public Member Functions inherited from cost_plugin_system::CostPlugins
virtual double compute_cost (cav_msgs::ManeuverPlan plan) const =0
Compute the cost of a given maneuver plan.
virtual ~CostPlugins ()
Virtual destructor provided for memory safety.
Private Attributes
double max_accelaration_
double max_deceleration_
Detailed Description
Definition at line 22 of file cost_feasibility.hpp.
Constructor & Destructor Documentation
CostofFeasibility()
cost_plugin_system::CostofFeasibility::CostofFeasibility (double max_accelaration, double max_deceleration)
Definition at line 24 of file cost_feasibility.cpp.
{
    max_accelaration_ = max_accelaration;
    max_deceleration_ = max_deceleration;
}
References max_accelaration_, and max_deceleration_.
Member Function Documentation
compute_cost()
double cost_plugin_system::CostofFeasibility::compute_cost (cav_msgs::ManeuverPlan plan) const virtual
Compute the cost of a given maneuver plan.
Parameters
plan The plan to evaluate
Returns
double The total cost
Implements cost_plugin_system::CostPlugins.
Definition at line 29 of file cost_feasibility.cpp.
{
    double cost = 0.0;
    int maneuver_size = sizeof(plan.maneuvers);
    for (auto it = plan.maneuvers.begin(); it != plan.maneuvers.end(); it++)
    {
        double average_acceleration = (cost_utils::get_maneuver_end_speed(*it) - cost_utils::get_maneuver_start_speed(*it)) /
                                      (cost_utils::get_maneuver_end_time(*it).toSec() - cost_utils::get_maneuver_start_time(*it).toSec());
        cost += (average_acceleration > max_accelaration_) ? 1 : 0 + (average_acceleration < max_deceleration_) ? 1 : 0;
    }
    // Normalize the cost
    cost = cost / (maneuver_size * 2);
    return cost;
}
References cost_utils::get_maneuver_end_speed(), cost_utils::get_maneuver_end_time(), cost_utils::get_maneuver_start_speed(), cost_utils::get_maneuver_start_time(), max_accelaration_, and max_deceleration_.
Referenced by cost_plugin_system::CostPluginWorker::compute_final_score().
Member Data Documentation
max_accelaration_
double cost_plugin_system::CostofFeasibility::max_accelaration_ private
Definition at line 30 of file cost_feasibility.hpp.
Referenced by CostofFeasibility(), and compute_cost().
max_deceleration_
double cost_plugin_system::CostofFeasibility::max_deceleration_ private
Definition at line 31 of file cost_feasibility.hpp.
Referenced by CostofFeasibility(), and compute_cost().
The documentation for this class was generated from the following files:
cost_plugin_system/include/cost_feasibility.hpp
cost_plugin_system/src/cost_feasibility.cpp