Carma-platform: cost_plugin_system::CostofSafety Class Reference
cost_plugin_system::CostofSafety Class Reference
#include <cost_safety.hpp>
Public Member Functions
CostofSafety (double speed_limit)
double compute_cost (cav_msgs::ManeuverPlan plan) const
Compute the cost of a given maneuver plan.
Public Member Functions inherited from cost_plugin_system::CostPlugins
virtual double compute_cost (cav_msgs::ManeuverPlan plan) const =0
Compute the cost of a given maneuver plan.
virtual ~CostPlugins ()
Virtual destructor provided for memory safety.
Private Attributes
double speed_limit_
Detailed Description
Definition at line 22 of file cost_safety.hpp.
Constructor & Destructor Documentation
CostofSafety()
cost_plugin_system::CostofSafety::CostofSafety (double speed_limit)
Definition at line 24 of file cost_safety.cpp.
{
    speed_limit_ = speed_limit;
}
References speed_limit_.
Member Function Documentation
compute_cost()
double cost_plugin_system::CostofSafety::compute_cost (cav_msgs::ManeuverPlan plan) const virtual
Compute the cost of a given maneuver plan.
Parameters
plan The plan to evaluate
Returns
double The total cost
Implements cost_plugin_system::CostPlugins.
Definition at line 29 of file cost_safety.cpp.
{
    double cost = 0.0;
    int maneuver_size = sizeof(plan.maneuvers);
    for (auto it = plan.maneuvers.begin(); it != plan.maneuvers.end(); it++)
    {
        double average_speed = (cost_utils::get_maneuver_start_speed(*it) + cost_utils::get_maneuver_end_speed(*it)) / 2;
        cost += pow(average_speed, 2.0) - (1 + pow(speed_limit_, 2.0)) / pow(speed_limit_, 2.0) * average_speed + 1;
    }
    // Normalize the cost
    cost = cost / (pow(speed_limit_, 2.0)* maneuver_size);
    return cost;
}
References cost_utils::get_maneuver_end_speed(), cost_utils::get_maneuver_start_speed(), and speed_limit_.
Referenced by cost_plugin_system::CostPluginWorker::compute_final_score().
Member Data Documentation
speed_limit_
double cost_plugin_system::CostofSafety::speed_limit_ private
Definition at line 30 of file cost_safety.hpp.
Referenced by CostofSafety(), and compute_cost().
The documentation for this class was generated from the following files:
cost_plugin_system/include/cost_safety.hpp
cost_plugin_system/src/cost_safety.cpp