Carma-platform: carma_cooperative_perception::SdsmToDetectionListNode Class Reference
carma_cooperative_perception::SdsmToDetectionListNode Class Reference
#include <sdsm_to_detection_list_component.hpp>
Public Member Functions
SdsmToDetectionListNode (const rclcpp::NodeOptions &options)
auto sdsm_msg_callback (const input_msg_type &msg) const -> void
Private Types
using input_msg_type = carma_v2x_msgs::msg::SensorDataSharingMessage
using input_msg_shared_pointer = typename input_msg_type::SharedPtr
using output_msg_type = carma_cooperative_perception_interfaces::msg::DetectionList
Private Attributes
rclcpp::Publisher< output_msg_type >::SharedPtr publisher_
rclcpp::Subscription< input_msg_type >::SharedPtr subscription_
rclcpp::Subscription< std_msgs::msg::String >::SharedPtr georeference_subscription_
std::string georeference_ {""}
Detailed Description
Definition at line 30 of file sdsm_to_detection_list_component.hpp.
Member Typedef Documentation
input_msg_shared_pointer
using carma_cooperative_perception::SdsmToDetectionListNode::input_msg_shared_pointer = typename input_msg_type::SharedPtr private
Definition at line 33 of file sdsm_to_detection_list_component.hpp.
input_msg_type
using carma_cooperative_perception::SdsmToDetectionListNode::input_msg_type = carma_v2x_msgs::msg::SensorDataSharingMessage private
Definition at line 32 of file sdsm_to_detection_list_component.hpp.
output_msg_type
using carma_cooperative_perception::SdsmToDetectionListNode::output_msg_type = carma_cooperative_perception_interfaces::msg::DetectionList private
Definition at line 34 of file sdsm_to_detection_list_component.hpp.
Constructor & Destructor Documentation
SdsmToDetectionListNode()
carma_cooperative_perception::SdsmToDetectionListNode::SdsmToDetectionListNode (const rclcpp::NodeOptions & options) inline explicit
Definition at line 37 of file sdsm_to_detection_list_component.hpp.
  : CarmaLifecycleNode{options},
    publisher_{create_publisher<output_msg_type>("output/detections", 1)},
    subscription_{create_subscription<input_msg_type>(
      "input/sdsm", 1, [this](input_msg_shared_pointer msg_ptr) { sdsm_msg_callback(*msg_ptr); })},
    georeference_subscription_{create_subscription<std_msgs::msg::String>(
      "input/georeference", 1,
      [this](std_msgs::msg::String::SharedPtr msg_ptr) { georeference_ = msg_ptr->data; })}
  {
  }
References sdsm_msg_callback().
Member Function Documentation
sdsm_msg_callback()
auto carma_cooperative_perception::SdsmToDetectionListNode::sdsm_msg_callback (const input_msg_type & msg) const -> void inline
Definition at line 48 of file sdsm_to_detection_list_component.hpp.
  {
    publisher_->publish(to_detection_list_msg(msg, georeference_));
  }
References carma_cooperative_perception::to_detection_list_msg().
Referenced by SdsmToDetectionListNode().
Member Data Documentation
georeference_
std::string carma_cooperative_perception::SdsmToDetectionListNode::georeference_ {""} private
Definition at line 58 of file sdsm_to_detection_list_component.hpp.
georeference_subscription_
rclcpp::Subscription<std_msgs::msg::String>::SharedPtr carma_cooperative_perception::SdsmToDetectionListNode::georeference_subscription_ private
Definition at line 56 of file sdsm_to_detection_list_component.hpp.
publisher_
rclcpp::Publisher<output_msg_type>::SharedPtr carma_cooperative_perception::SdsmToDetectionListNode::publisher_ private
Definition at line 54 of file sdsm_to_detection_list_component.hpp.
subscription_
rclcpp::Subscription<input_msg_type>::SharedPtr carma_cooperative_perception::SdsmToDetectionListNode::subscription_ private
Definition at line 55 of file sdsm_to_detection_list_component.hpp.
The documentation for this class was generated from the following file:
carma_cooperative_perception/include/carma_cooperative_perception/sdsm_to_detection_list_component.hpp