Carma-platform: GenericDocument< Encoding, Allocator, StackAllocator > Class Template Reference
GenericDocument< Encoding, Allocator, StackAllocator > Class Template Reference
A document for parsing JSON text as DOM.
#include <document.h>
Classes
struct ClearStackOnExit
Public Types
typedef Encoding::Ch Ch
Character type derived from Encoding.
typedef GenericValue< Encoding, Allocator > ValueType
Value type of the document.
typedef Allocator AllocatorType
Allocator type from template parameter.
Public Types inherited from GenericValue< Encoding, MemoryPoolAllocator<> >
typedef GenericMember< Encoding, MemoryPoolAllocator<> > Member
Name-value pair in an object.
typedef Encoding EncodingType
Encoding type from template parameter.
typedef MemoryPoolAllocator<> AllocatorType
Allocator type from template parameter.
typedef Encoding::Ch Ch
Character type derived from Encoding.
typedef GenericStringRef< Ch > StringRefType
Reference to a constant string.
typedef GenericMemberIterator< false, Encoding, MemoryPoolAllocator<> >::Iterator MemberIterator
Member iterator for iterating in object.
typedef GenericMemberIterator< true, Encoding, MemoryPoolAllocator<> >::Iterator ConstMemberIterator
Constant member iterator for iterating in object.
typedef GenericValue * ValueIterator
Value iterator for iterating in array.
typedef const GenericValue * ConstValueIterator
Constant value iterator for iterating in array.
typedef GenericValue< Encoding, MemoryPoolAllocator<> > ValueType
Value type of itself.
typedef GenericArray< false, ValueType > Array
typedef GenericArray< true, ValueType > ConstArray
typedef GenericObject< false, ValueType > Object
typedef GenericObject< true, ValueType > ConstObject
enum
Public Member Functions
GenericDocument (Type type, Allocator *allocator=0, size_t stackCapacity=kDefaultStackCapacity, StackAllocator *stackAllocator=0)
Constructor.
GenericDocument (Allocator *allocator=0, size_t stackCapacity=kDefaultStackCapacity, StackAllocator *stackAllocator=0)
Constructor.
~GenericDocument ()
GenericDocument & Swap (GenericDocument &rhs) RAPIDJSON_NOEXCEPT
Exchange the contents of this document with those of another.
template<typename Generator >
GenericDocument & Populate (Generator &g)
Populate this document by a generator which produces SAX events.
Allocator & GetAllocator ()
Get the allocator of this document.
size_t GetStackCapacity () const
Get the capacity of stack in bytes.
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned i)
bool Int64 (int64_t i)
bool Uint64 (uint64_t i)
bool Double (double d)
bool RawNumber (const Ch *str, SizeType length, bool copy)
bool String (const Ch *str, SizeType length, bool copy)
bool StartObject ()
bool Key (const Ch *str, SizeType length, bool copy)
bool EndObject (SizeType memberCount)
bool StartArray ()
bool EndArray (SizeType elementCount)
Parse from stream
template<unsigned parseFlags, typename SourceEncoding , typename InputStream >
GenericDocument & ParseStream (InputStream &is)
Parse JSON text from an input stream (with Encoding conversion)
template<unsigned parseFlags, typename InputStream >
GenericDocument & ParseStream (InputStream &is)
Parse JSON text from an input stream.
template<typename InputStream >
GenericDocument & ParseStream (InputStream &is)
Parse JSON text from an input stream (with kParseDefaultFlags)
Parse in-place from mutable string
template<unsigned parseFlags>
GenericDocument & ParseInsitu (Ch *str)
Parse JSON text from a mutable string.
GenericDocument & ParseInsitu (Ch *str)
Parse JSON text from a mutable string (with kParseDefaultFlags)
Parse from read-only string
template<unsigned parseFlags, typename SourceEncoding >
GenericDocument & Parse (const typename SourceEncoding::Ch *str)
Parse JSON text from a read-only string (with Encoding conversion)
template<unsigned parseFlags>
GenericDocument & Parse (const Ch *str)
Parse JSON text from a read-only string.
GenericDocument & Parse (const Ch *str)
Parse JSON text from a read-only string (with kParseDefaultFlags)
template<unsigned parseFlags, typename SourceEncoding >
GenericDocument & Parse (const typename SourceEncoding::Ch *str, size_t length)
template<unsigned parseFlags>
GenericDocument & Parse (const Ch *str, size_t length)
GenericDocument & Parse (const Ch *str, size_t length)
Handling parse errors
bool HasParseError () const
Whether a parse error has occured in the last parsing.
ParseErrorCode GetParseError () const
Get the ParseErrorCode of last parsing.
size_t GetErrorOffset () const
Get the position of last parsing error in input, 0 otherwise.
operator ParseResult () const
Implicit conversion to get the last parse result.
Public Member Functions inherited from GenericValue< Encoding, MemoryPoolAllocator<> >
GenericValue & operator= (GenericValue &rhs) RAPIDJSON_NOEXCEPT
Assignment with move semantics.
GenericValue & operator= (StringRefType str) RAPIDJSON_NOEXCEPT
Assignment of constant string reference (no copy)
RAPIDJSON_DISABLEIF_RETURN ((internal::IsPointer< T >),(GenericValue &)) operator
Assignment with primitive types.
RAPIDJSON_FORCEINLINE const Ch * GetStringPointer () const
RAPIDJSON_FORCEINLINE const Ch * SetStringPointer (const Ch *str)
RAPIDJSON_FORCEINLINE GenericValue * GetElementsPointer () const
RAPIDJSON_FORCEINLINE GenericValue * SetElementsPointer (GenericValue *elements)
RAPIDJSON_FORCEINLINE Member * GetMembersPointer () const
RAPIDJSON_FORCEINLINE Member * SetMembersPointer (Member *members)
void SetArrayRaw (GenericValue *values, SizeType count, MemoryPoolAllocator<> &allocator)
void SetObjectRaw (Member *members, SizeType count, MemoryPoolAllocator<> &allocator)
Initialize this value as object with initial data, without calling destructor.
void SetStringRaw (StringRefType s) RAPIDJSON_NOEXCEPT
Initialize this value as constant string, without calling destructor.
void SetStringRaw (StringRefType s, MemoryPoolAllocator<> &allocator)
Initialize this value as copy string with initial data, without calling destructor.
void RawAssign (GenericValue &rhs) RAPIDJSON_NOEXCEPT
Assignment without calling destructor.
bool StringEqual (const GenericValue< Encoding, SourceAllocator > &rhs) const
GenericValue () RAPIDJSON_NOEXCEPT
Default constructor creates a null value.
GenericValue (Type type) RAPIDJSON_NOEXCEPT
Constructor with JSON value type.
GenericValue (const GenericValue< Encoding, SourceAllocator > &rhs, MemoryPoolAllocator<> &allocator, bool copyConstStrings=false)
Explicit copy constructor (with allocator)
GenericValue (T b, RAPIDJSON_ENABLEIF((internal::IsSame< bool, T >))) RAPIDJSON_NOEXCEPT
Constructor for boolean value.
GenericValue (int i) RAPIDJSON_NOEXCEPT
Constructor for int value.
GenericValue (unsigned u) RAPIDJSON_NOEXCEPT
Constructor for unsigned value.
GenericValue (int64_t i64) RAPIDJSON_NOEXCEPT
Constructor for int64_t value.
GenericValue (uint64_t u64) RAPIDJSON_NOEXCEPT
Constructor for uint64_t value.
GenericValue (double d) RAPIDJSON_NOEXCEPT
Constructor for double value.
GenericValue (float f) RAPIDJSON_NOEXCEPT
Constructor for float value.
GenericValue (const Ch *s, SizeType length) RAPIDJSON_NOEXCEPT
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (StringRefType s) RAPIDJSON_NOEXCEPT
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (const Ch *s, SizeType length, MemoryPoolAllocator<> &allocator)
Constructor for copy-string (i.e. do make a copy of string)
GenericValue (const Ch *s, MemoryPoolAllocator<> &allocator)
Constructor for copy-string (i.e. do make a copy of string)
GenericValue (Array a) RAPIDJSON_NOEXCEPT
Constructor for Array.
GenericValue (Object o) RAPIDJSON_NOEXCEPT
Constructor for Object.
~GenericValue ()
Destructor.
Private Member Functions
GenericDocument (const GenericDocument &)
Prohibit copying.
GenericDocument & operator= (const GenericDocument &)
Prohibit assignment.
void ClearStack ()
void Destroy ()
Private Attributes
Allocator * allocator_
Allocator * ownAllocator_
internal::Stack< StackAllocator > stack_
ParseResult parseResult_
Static Private Attributes
static const size_t kDefaultStackCapacity = 1024
Friends
template<typename , typename >
class GenericValue
void swap (GenericDocument &a, GenericDocument &b) RAPIDJSON_NOEXCEPT
free-standing swap function helper
Additional Inherited Members
Public Attributes inherited from GenericValue< Encoding, MemoryPoolAllocator<> >
Data data_
Static Public Attributes inherited from GenericValue< Encoding, MemoryPoolAllocator<> >
static const SizeType kDefaultArrayCapacity
static const SizeType kDefaultObjectCapacity
Detailed Description
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator>
class GenericDocument< Encoding, Allocator, StackAllocator >
A document for parsing JSON text as DOM.
Note
implements Handler concept
Template Parameters
Encoding Encoding for both parsing and string storage.
Allocator Allocator for allocating memory for the DOM
StackAllocator Allocator for allocating memory for stack during parsing.
Warning
Although GenericDocument inherits from GenericValue, the API does not provide any virtual functions, especially no virtual destructor. To avoid memory leaks, do not delete a GenericDocument object via a pointer to a GenericValue.
Definition at line 2087 of file document.h.
Member Typedef Documentation
AllocatorType
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> typedef Allocator GenericDocument< Encoding, Allocator, StackAllocator >::AllocatorType
Allocator type from template parameter.
Definition at line 2091 of file document.h.
Ch
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> typedef Encoding::Ch GenericDocument< Encoding, Allocator, StackAllocator >::Ch
Character type derived from Encoding.
Definition at line 2089 of file document.h.
ValueType
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> typedef GenericValue<Encoding, Allocator> GenericDocument< Encoding, Allocator, StackAllocator >::ValueType
Value type of the document.
Definition at line 2090 of file document.h.
Constructor & Destructor Documentation
GenericDocument() [1/3]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> GenericDocument< Encoding, Allocator, StackAllocator >::GenericDocument (Type type, Allocator * allocator = 0, size_t stackCapacity = kDefaultStackCapacity, StackAllocator * stackAllocator = 0) inline explicit
Constructor.
Creates an empty document of specified type.
Parameters
type Mandatory type of object to create.
allocator Optional allocator for allocating memory.
stackCapacity Optional initial capacity of stack in bytes.
stackAllocator Optional allocator for allocating memory for stack.
Definition at line 2100 of file document.h.
                                                                                                                                                    :
        GenericValue<Encoding, Allocator>(type),  allocator_(allocator), ownAllocator_(0), stack_(stackAllocator, stackCapacity), parseResult_()
    {
        if (!allocator_)
            ownAllocator_ = allocator_ = RAPIDJSON_NEW(Allocator)();
    }
References GenericDocument< Encoding, Allocator, StackAllocator >::allocator_, GenericDocument< Encoding, Allocator, StackAllocator >::ownAllocator_, and RAPIDJSON_NEW.
GenericDocument() [2/3]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> GenericDocument< Encoding, Allocator, StackAllocator >::GenericDocument (Allocator * allocator = 0, size_t stackCapacity = kDefaultStackCapacity, StackAllocator * stackAllocator = 0) inline
Constructor.
Creates an empty document which type is Null.
Parameters
allocator Optional allocator for allocating memory.
stackCapacity Optional initial capacity of stack in bytes.
stackAllocator Optional allocator for allocating memory for stack.
Definition at line 2113 of file document.h.
                                                                                                                                :
        allocator_(allocator), ownAllocator_(0), stack_(stackAllocator, stackCapacity), parseResult_()
    {
        if (!allocator_)
            ownAllocator_ = allocator_ = RAPIDJSON_NEW(Allocator)();
    }
References GenericDocument< Encoding, Allocator, StackAllocator >::allocator_, GenericDocument< Encoding, Allocator, StackAllocator >::ownAllocator_, and RAPIDJSON_NEW.
~GenericDocument()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> GenericDocument< Encoding, Allocator, StackAllocator >::~GenericDocument () inline
Definition at line 2135 of file document.h.
                       {
        Destroy();
    }
References GenericDocument< Encoding, Allocator, StackAllocator >::Destroy().
GenericDocument() [3/3]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> GenericDocument< Encoding, Allocator, StackAllocator >::GenericDocument (const GenericDocument< Encoding, Allocator, StackAllocator > &) private
Prohibit copying.
Member Function Documentation
Bool()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::Bool (bool b) inline
Definition at line 2401 of file document.h.
{ new (stack_.template Push<ValueType>()) ValueType(b); return true; }
References GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
ClearStack()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> void GenericDocument< Encoding, Allocator, StackAllocator >::ClearStack () inline private
Definition at line 2448 of file document.h.
                      {
        if (Allocator::kNeedFree)
            while (stack_.GetSize() > 0)    // Here assumes all elements in stack array are GenericValue (Member is actually 2 GenericValue objects)
                (stack_.template Pop<ValueType>(1))->~ValueType();
        else
            stack_.Clear();
        stack_.ShrinkToFit();
    }
References internal::Stack< Allocator >::Clear(), internal::Stack< Allocator >::GetSize(), internal::Stack< Allocator >::ShrinkToFit(), and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::ClearStackOnExit::~ClearStackOnExit().
Destroy()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> void GenericDocument< Encoding, Allocator, StackAllocator >::Destroy () inline private
Definition at line 2457 of file document.h.
                   {
        RAPIDJSON_DELETE(ownAllocator_);
    }
References GenericDocument< Encoding, Allocator, StackAllocator >::ownAllocator_, and RAPIDJSON_DELETE.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::~GenericDocument().
Double()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::Double (double d) inline
Definition at line 2406 of file document.h.
{ new (stack_.template Push<ValueType>()) ValueType(d); return true; }
References GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
EndArray()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::EndArray (SizeType elementCount) inline
Definition at line 2436 of file document.h.
{
        ValueType* elements = stack_.template Pop<ValueType>(elementCount);
        stack_.template Top<ValueType>()->SetArrayRaw(elements, elementCount, GetAllocator());
        return true;
    }
References GenericDocument< Encoding, Allocator, StackAllocator >::GetAllocator(), and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
EndObject()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::EndObject (SizeType memberCount) inline
Definition at line 2428 of file document.h.
{
        typename ValueType::Member* members = stack_.template Pop<typename ValueType::Member>(memberCount);
        stack_.template Top<ValueType>()->SetObjectRaw(members, memberCount, GetAllocator());
        return true;
    }
References GenericDocument< Encoding, Allocator, StackAllocator >::GetAllocator(), and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
GetAllocator()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> Allocator & GenericDocument< Encoding, Allocator, StackAllocator >::GetAllocator () inline
Get the allocator of this document.
Definition at line 2375 of file document.h.
{
        RAPIDJSON_ASSERT(allocator_);
        return *allocator_;
    }
References GenericDocument< Encoding, Allocator, StackAllocator >::allocator_, and RAPIDJSON_ASSERT.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::EndArray(), GenericDocument< Encoding, Allocator, StackAllocator >::EndObject(), GenericDocument< Encoding, Allocator, StackAllocator >::RawNumber(), and GenericDocument< Encoding, Allocator, StackAllocator >::String().
GetErrorOffset()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> size_t GenericDocument< Encoding, Allocator, StackAllocator >::GetErrorOffset () const inline
Get the position of last parsing error in input, 0 otherwise.
Definition at line 2357 of file document.h.
{ return parseResult_.Offset(); }
References ParseResult::Offset(), and GenericDocument< Encoding, Allocator, StackAllocator >::parseResult_.
GetParseError()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> ParseErrorCode GenericDocument< Encoding, Allocator, StackAllocator >::GetParseError () const inline
Get the ParseErrorCode of last parsing.
Definition at line 2354 of file document.h.
{ return parseResult_.Code(); }
References ParseResult::Code(), and GenericDocument< Encoding, Allocator, StackAllocator >::parseResult_.
GetStackCapacity()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> size_t GenericDocument< Encoding, Allocator, StackAllocator >::GetStackCapacity () const inline
Get the capacity of stack in bytes.
Definition at line 2381 of file document.h.
{ return stack_.GetCapacity(); }
References internal::Stack< Allocator >::GetCapacity(), and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
HasParseError()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError () const inline
Whether a parse error has occured in the last parsing.
Definition at line 2351 of file document.h.
{ return parseResult_.IsError(); }
References ParseResult::IsError(), and GenericDocument< Encoding, Allocator, StackAllocator >::parseResult_.
Int()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::Int (int i) inline
Definition at line 2402 of file document.h.
{ new (stack_.template Push<ValueType>()) ValueType(i); return true; }
References process_bag::i, and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
Int64()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::Int64 (int64_t i) inline
Definition at line 2404 of file document.h.
{ new (stack_.template Push<ValueType>()) ValueType(i); return true; }
References process_bag::i, and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
Key()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::Key (const Ch * str, SizeType length, bool copy) inline
Definition at line 2426 of file document.h.
{ return String(str, length, copy); }
References GenericDocument< Encoding, Allocator, StackAllocator >::String().
Null()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::Null () inline
Definition at line 2400 of file document.h.
{ new (stack_.template Push<ValueType>()) ValueType(); return true; }
References GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
operator ParseResult()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> GenericDocument< Encoding, Allocator, StackAllocator >::operator ParseResult () const inline
Implicit conversion to get the last parse result.
Returns
ParseResult of the last parse operation
Document doc;
ParseResult ok = doc.Parse(json);
if (!ok)
  printf( "JSON parse error: %s (%u)\n", GetParseError_En(ok.Code()), ok.Offset());
Definition at line 2371 of file document.h.
{ return parseResult_; }
References GenericDocument< Encoding, Allocator, StackAllocator >::parseResult_.
operator=()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::operator= (const GenericDocument< Encoding, Allocator, StackAllocator > &) private
Prohibit assignment.
Parse() [1/6]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags> GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const Ch * str) inline
Parse JSON text from a read-only string.
Template Parameters
parseFlags Combination of ParseFlag (must not contain kParseInsituFlag).
Parameters
str Read-only zero-terminated string to be parsed.
Definition at line 2299 of file document.h.
{
        return Parse<parseFlags, Encoding>(str);
    }
Parse() [2/6]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const Ch * str) inline
Parse JSON text from a read-only string (with kParseDefaultFlags)
Parameters
str Read-only zero-terminated string to be parsed.
Definition at line 2306 of file document.h.
{
        return Parse<kParseDefaultFlags>(str);
    }
Parse() [3/6]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags> GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const Ch * str, size_t length) inline
Definition at line 2320 of file document.h.
{
        return Parse<parseFlags, Encoding>(str, length);
    }
Parse() [4/6]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const Ch * str, size_t length) inline
Definition at line 2324 of file document.h.
{
        return Parse<kParseDefaultFlags>(str, length);
    }
Parse() [5/6]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename SourceEncoding > GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const typename SourceEncoding::Ch * str) inline
Parse JSON text from a read-only string (with Encoding conversion)
Template Parameters
parseFlags Combination of ParseFlag (must not contain kParseInsituFlag).
SourceEncoding Transcoding from input Encoding
Parameters
str Read-only zero-terminated string to be parsed.
Definition at line 2288 of file document.h.
{
        RAPIDJSON_ASSERT(!(parseFlags & kParseInsituFlag));
        GenericStringStream<SourceEncoding> s(str);
        return ParseStream<parseFlags, SourceEncoding>(s);
    }
References kParseInsituFlag, and RAPIDJSON_ASSERT.
Parse() [6/6]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename SourceEncoding > GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::Parse (const typename SourceEncoding::Ch * str, size_t length) inline
Definition at line 2311 of file document.h.
{
        RAPIDJSON_ASSERT(!(parseFlags & kParseInsituFlag));
        MemoryStream ms(reinterpret_cast<const char*>(str), length * sizeof(typename SourceEncoding::Ch));
        EncodedInputStream<SourceEncoding, MemoryStream> is(ms);
        ParseStream<parseFlags, SourceEncoding>(is);
        return *this;
    }
References kParseInsituFlag, and RAPIDJSON_ASSERT.
ParseInsitu() [1/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags> GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::ParseInsitu (Ch * str) inline
Parse JSON text from a mutable string.
Template Parameters
parseFlags Combination of ParseFlag.
Parameters
str Mutable zero-terminated string to be parsed.
Returns
The document itself for fluent API.
Definition at line 2265 of file document.h.
{
        GenericInsituStringStream<Encoding> s(str);
        return ParseStream<parseFlags | kParseInsituFlag>(s);
    }
ParseInsitu() [2/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::ParseInsitu (Ch * str) inline
Parse JSON text from a mutable string (with kParseDefaultFlags)
Parameters
str Mutable zero-terminated string to be parsed.
Returns
The document itself for fluent API.
Definition at line 2274 of file document.h.
{
        return ParseInsitu<kParseDefaultFlags>(str);
    }
ParseStream() [1/3]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename SourceEncoding , typename InputStream > GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream (InputStream & is) inline
Parse JSON text from an input stream (with Encoding conversion)
Template Parameters
parseFlags Combination of ParseFlag.
SourceEncoding Encoding of input stream
InputStream Type of input stream, implementing Stream concept
Parameters
is Input stream to be parsed.
Returns
The document itself for fluent API.
Definition at line 2222 of file document.h.
{
        GenericReader<SourceEncoding, Encoding, StackAllocator> reader(
            stack_.HasAllocator() ? &stack_.GetAllocator() : 0);
        ClearStackOnExit scope(*this);
        parseResult_ = reader.template Parse<parseFlags>(is, *this);
        if (parseResult_) {
            RAPIDJSON_ASSERT(stack_.GetSize() == sizeof(ValueType)); // Got one and only one root object
            ValueType::operator=(*stack_.template Pop<ValueType>(1));// Move value from stack to document
        }
        return *this;
    }
References internal::Stack< Allocator >::GetAllocator(), internal::Stack< Allocator >::GetSize(), internal::Stack< Allocator >::HasAllocator(), GenericValue< Encoding, Allocator >::operator=(), GenericDocument< Encoding, Allocator, StackAllocator >::parseResult_, RAPIDJSON_ASSERT, and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
ParseStream() [2/3]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream > GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream (InputStream & is) inline
Parse JSON text from an input stream.
Template Parameters
parseFlags Combination of ParseFlag.
InputStream Type of input stream, implementing Stream concept
Parameters
is Input stream to be parsed.
Returns
The document itself for fluent API.
Definition at line 2241 of file document.h.
{
        return ParseStream<parseFlags, Encoding, InputStream>(is);
    }
ParseStream() [3/3]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> template<typename InputStream > GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream (InputStream & is) inline
Parse JSON text from an input stream (with kParseDefaultFlags)
Template Parameters
InputStream Type of input stream, implementing Stream concept
Parameters
is Input stream to be parsed.
Returns
The document itself for fluent API.
Definition at line 2251 of file document.h.
{
        return ParseStream<kParseDefaultFlags, Encoding, InputStream>(is);
    }
Populate()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> template<typename Generator > GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::Populate (Generator & g) inline
Populate this document by a generator which produces SAX events.
Template Parameters
Generator A functor with bool f(Handler) prototype.
Parameters
g Generator functor which sends SAX events to the parameter.
Returns
The document itself for fluent API.
Definition at line 2202 of file document.h.
{
        ClearStackOnExit scope(*this);
        if (g(*this)) {
            RAPIDJSON_ASSERT(stack_.GetSize() == sizeof(ValueType)); // Got one and only one root object
            ValueType::operator=(*stack_.template Pop<ValueType>(1));// Move value from stack to document
        }
        return *this;
    }
References internal::Stack< Allocator >::GetSize(), GenericValue< Encoding, Allocator >::operator=(), RAPIDJSON_ASSERT, and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
RawNumber()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::RawNumber (const Ch * str, SizeType length, bool copy) inline
Definition at line 2408 of file document.h.
{
        if (copy)
            new (stack_.template Push<ValueType>()) ValueType(str, length, GetAllocator());
        else
            new (stack_.template Push<ValueType>()) ValueType(str, length);
        return true;
    }
References GenericDocument< Encoding, Allocator, StackAllocator >::GetAllocator(), and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
StartArray()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::StartArray () inline
Definition at line 2434 of file document.h.
{ new (stack_.template Push<ValueType>()) ValueType(kArrayType); return true; }
References kArrayType, and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
StartObject()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::StartObject () inline
Definition at line 2424 of file document.h.
{ new (stack_.template Push<ValueType>()) ValueType(kObjectType); return true; }
References kObjectType, and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
String()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::String (const Ch * str, SizeType length, bool copy) inline
Definition at line 2416 of file document.h.
{
        if (copy)
            new (stack_.template Push<ValueType>()) ValueType(str, length, GetAllocator());
        else
            new (stack_.template Push<ValueType>()) ValueType(str, length);
        return true;
    }
References GenericDocument< Encoding, Allocator, StackAllocator >::GetAllocator(), and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::Key().
Swap()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> GenericDocument & GenericDocument< Encoding, Allocator, StackAllocator >::Swap (GenericDocument< Encoding, Allocator, StackAllocator > & rhs) inline
Exchange the contents of this document with those of another.
Parameters
rhs Another document.
Note
Constant complexity.
See also
GenericValue::Swap
Definition at line 2169 of file document.h.
{
        ValueType::Swap(rhs);
        stack_.Swap(rhs.stack_);
        internal::Swap(allocator_, rhs.allocator_);
        internal::Swap(ownAllocator_, rhs.ownAllocator_);
        internal::Swap(parseResult_, rhs.parseResult_);
        return *this;
    }
References GenericDocument< Encoding, Allocator, StackAllocator >::allocator_, GenericDocument< Encoding, Allocator, StackAllocator >::ownAllocator_, GenericDocument< Encoding, Allocator, StackAllocator >::parseResult_, GenericDocument< Encoding, Allocator, StackAllocator >::stack_, internal::Stack< Allocator >::Swap(), and internal::Swap().
Uint()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::Uint (unsigned i) inline
Definition at line 2403 of file document.h.
{ new (stack_.template Push<ValueType>()) ValueType(i); return true; }
References process_bag::i, and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
Uint64()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> bool GenericDocument< Encoding, Allocator, StackAllocator >::Uint64 (uint64_t i) inline
Definition at line 2405 of file document.h.
{ new (stack_.template Push<ValueType>()) ValueType(i); return true; }
References process_bag::i, and GenericDocument< Encoding, Allocator, StackAllocator >::stack_.
Friends And Related Function Documentation
GenericValue
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> template<typename , typename > friend class GenericValue friend
Definition at line 2396 of file document.h.
swap
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> void swap (GenericDocument< Encoding, Allocator, StackAllocator > & a, GenericDocument< Encoding, Allocator, StackAllocator > & b) friend
free-standing swap function helper
Helper function to enable support for common swap implementation pattern based on std::swap:
void swap(MyClass& a, MyClass& b) {
    using std::swap;
    swap(a.doc, b.doc);
    // ...
}
See also
Swap()
Definition at line 2194 of file document.h.
{ a.Swap(b); }
Member Data Documentation
allocator_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> Allocator* GenericDocument< Encoding, Allocator, StackAllocator >::allocator_ private
Definition at line 2462 of file document.h.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::GenericDocument(), GenericDocument< Encoding, Allocator, StackAllocator >::GetAllocator(), and GenericDocument< Encoding, Allocator, StackAllocator >::Swap().
kDefaultStackCapacity
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> const size_t GenericDocument< Encoding, Allocator, StackAllocator >::kDefaultStackCapacity = 1024 static private
Definition at line 2461 of file document.h.
ownAllocator_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> Allocator* GenericDocument< Encoding, Allocator, StackAllocator >::ownAllocator_ private
Definition at line 2463 of file document.h.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::GenericDocument(), GenericDocument< Encoding, Allocator, StackAllocator >::Destroy(), and GenericDocument< Encoding, Allocator, StackAllocator >::Swap().
parseResult_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> ParseResult GenericDocument< Encoding, Allocator, StackAllocator >::parseResult_ private
Definition at line 2465 of file document.h.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::GetErrorOffset(), GenericDocument< Encoding, Allocator, StackAllocator >::GetParseError(), GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), GenericDocument< Encoding, Allocator, StackAllocator >::operator ParseResult(), GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream(), and GenericDocument< Encoding, Allocator, StackAllocator >::Swap().
stack_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>, typename StackAllocator = CrtAllocator> internal::Stack<StackAllocator> GenericDocument< Encoding, Allocator, StackAllocator >::stack_ private
Definition at line 2464 of file document.h.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::Bool(), GenericDocument< Encoding, Allocator, StackAllocator >::ClearStack(), GenericDocument< Encoding, Allocator, StackAllocator >::Double(), GenericDocument< Encoding, Allocator, StackAllocator >::EndArray(), GenericDocument< Encoding, Allocator, StackAllocator >::EndObject(), GenericDocument< Encoding, Allocator, StackAllocator >::GetStackCapacity(), GenericDocument< Encoding, Allocator, StackAllocator >::Int(), GenericDocument< Encoding, Allocator, StackAllocator >::Int64(), GenericDocument< Encoding, Allocator, StackAllocator >::Null(), GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream(), GenericDocument< Encoding, Allocator, StackAllocator >::Populate(), GenericDocument< Encoding, Allocator, StackAllocator >::RawNumber(), GenericDocument< Encoding, Allocator, StackAllocator >::StartArray(), GenericDocument< Encoding, Allocator, StackAllocator >::StartObject(), GenericDocument< Encoding, Allocator, StackAllocator >::String(), GenericDocument< Encoding, Allocator, StackAllocator >::Swap(), GenericDocument< Encoding, Allocator, StackAllocator >::Uint(), and GenericDocument< Encoding, Allocator, StackAllocator >::Uint64().
The documentation for this class was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/document.h