Carma-platform: NS3Client Class Reference
NS3Client Class Reference
#include <ns-3_client.h>
Public Member Functions
NS3Client ()
Initializes the NS-3 client, sets up i/o services.
~NS3Client ()
bool registermsg (const std::shared_ptr< std::vector< uint8_t > > &message, const std::string &remote_address, unsigned short remote_port, unsigned short local_port)
connects and send handshake message to MOSAIC CARMA Ambassador
bool connect (const std::string &remote_address, unsigned short remote_port, unsigned short local_port, boost::system::error_code &ec)
Connects the driver to the OBU at the provided IPv4 address and Port.
bool connect (const std::string &remote_address, unsigned short remote_port, unsigned short local_port)
void close ()
Closes connection.
bool connected ()
returns connected state
bool sendNS3Message (const std::shared_ptr< std::vector< uint8_t > > &message)
sends a udp message
Public Attributes
boost::signals2::signal< void()> onConnect
Signaled when client is connected to the NS-3 adapter.
boost::signals2::signal< void()> onDisconnect
Signaled when client is disconnected from hardware.
boost::signals2::signal< void(const boost::system::error_code &)> onError
Signaled when client experiences a fatal error. Client should be closed and reconnected.
boost::signals2::signal< void(std::vector< uint8_t > const &, uint16_t id)> onMessageReceived
Signaled when message received.
Private Member Functions
void process (const std::shared_ptr< const std::vector< uint8_t > > &data)
maintains the process thread
Private Attributes
std::unique_ptr< boost::asio::io_service > io_
std::unique_ptr< boost::asio::io_service::strand > output_strand_
std::shared_ptr< boost::asio::io_service::work > work_
std::shared_ptr< std::thread > io_thread_
volatile bool running_
std::unique_ptr< boost::asio::ip::udp::socket > udp_out_socket_
boost::asio::ip::udp::endpoint remote_udp_ep_
std::unique_ptr< cav::UDPListener > udp_listener_
Detailed Description
Definition at line 31 of file ns-3_client.h.
Constructor & Destructor Documentation
NS3Client()
NS3Client::NS3Client ()
Initializes the NS-3 client, sets up i/o services.
Definition at line 5 of file ns-3_client.cpp.
                     :
    running_(false)
{}
~NS3Client()
NS3Client::~NS3Client ()
Definition at line 10 of file ns-3_client.cpp.
                      {
    try{
        close();
    }catch(...){}
}
References close().
Member Function Documentation
close()
void NS3Client::close ()
Closes connection.
closes all sockets, and stops all threads used for io and processing, blocks until threads are closed
Definition at line 109 of file ns-3_client.cpp.
                      {
    if(!running_) return;
    running_ = false;
    work_.reset();
    io_->stop();
    io_thread_->join();
    udp_listener_->stop();
    udp_out_socket_.reset();
    onDisconnect();
}
References io_, io_thread_, onDisconnect, running_, udp_listener_, udp_out_socket_, and work_.
Referenced by ~NS3Client(), NS3Adapter::pre_spin(), registermsg(), and NS3Adapter::shutdown().
connect() [1/2]
bool NS3Client::connect (const std::string & remote_address, unsigned short remote_port, unsigned short local_port)
Definition at line 39 of file ns-3_client.cpp.
{
    boost::system::error_code ignored_ec;
    return connect(remote_address, remote_port, local_port, ignored_ec);
}
References connect().
connect() [2/2]
bool NS3Client::connect (const std::string & remote_address, unsigned short remote_port, unsigned short local_port, boost::system::error_code & ec)
Connects the driver to the OBU at the provided IPv4 address and Port.
Parameters
address IPv4 address of OBU
port of client service
ec error code set during connect
Returns
true on sucessful connect, false otherwise
Definition at line 45 of file ns-3_client.cpp.
{
    //If we are already connected return false
    if(running_) return false;
    //Get remote endpoint
    try
    {
        remote_udp_ep_ = boost::asio::ip::udp::endpoint(boost::asio::ip::address::from_string(remote_address),remote_port);
    }catch(std::exception e)
    {
        ec = boost::asio::error::invalid_argument;
        throw e;
    }
    ec.clear();
    io_.reset(new boost::asio::io_service());
    output_strand_.reset(new boost::asio::io_service::strand(*io_));
    //build the udp listener, this class listens on address::port and sends packets through onReceive
    try
    {
        if(udp_listener_){
            udp_listener_.reset(nullptr);
        }
        udp_listener_.reset(new cav::UDPListener(*io_,local_port));
    }catch(boost::system::system_error e)
    {
        ec = e.code();
        return false;
    }
    catch(std::exception e)
    {
        std::cerr << "NS3Client::connect threw exception : " << e.what();
        return false;
    };
    //connect signals
    udp_listener_->onReceive.connect([this](const std::shared_ptr<const std::vector<uint8_t>>& data){process(data);});
    udp_out_socket_.reset(new boost::asio::ip::udp::socket(*io_,remote_udp_ep_.protocol()));
    work_.reset(new boost::asio::io_service::work(*io_));
    // run the io service
    udp_listener_->start();
    io_thread_.reset(new std::thread([this]()
{
                                         boost::system::error_code err;
                                         io_->run(err);
                                         if(err)
{
                                             onError(err);
                                         }
                                     }));
    running_ = true;
    onConnect();
    return true;
}
References process_traj_logs::data, io_, io_thread_, onConnect, onError, output_strand_, process(), remote_udp_ep_, running_, udp_listener_, udp_out_socket_, and work_.
Referenced by connect(), and registermsg().
connected()
bool NS3Client::connected () inline
returns connected state
Returns
returns true if connected, false otherwise
Definition at line 78 of file ns-3_client.h.
{ return running_; }
References running_.
Referenced by NS3Adapter::onOutboundMessage(), and NS3Adapter::sendMessageSrv().
process()
void NS3Client::process (const std::shared_ptr< const std::vector< uint8_t > > & data) private
maintains the process thread
This will parse through the incoming UDP packets to find what looks like a valid J2735 message. The UPER scheme makes it hard to definitively know if a message is valid or just noise, so all possible messages from a packet are sent. This will create some false positives, but will ensure that a falsely identified message doesn't keep a real one from getting through.
Definition at line 120 of file ns-3_client.cpp.
{
    auto & entry = *data;
    // Valid message should begin with 2 bytes message ID and 1 byte length.
    for (size_t i = 0; i < entry.size() - 3; i++) { // leave 3 bytes after (for lsb of id, length byte 1, and either message body or length byte 2)
        // Generate the 16-bit message id from two bytes, skip if it isn't a valid one
        uint16_t msg_id = (static_cast<uint16_t>(entry[i]) << 8) | static_cast<uint16_t>(entry[i + 1]);
        // Parse the length, check it doesn't run over
        size_t len = 0;
        size_t len_byte_1 = entry[i + 2];
        int len_bytes = 0;
        // length < 128 encoded by single byte with msb set to 0
        if ((len_byte_1 & 0x80 ) == 0x00) {
            len = static_cast<size_t>(len_byte_1);
            len_bytes = 1;
            // check for 0 length
            if (len_byte_1 == 0x00) { continue; }
        }
            // length < 16384 encoded by 14 bits in 2 bytes (10xxxxxx xxxxxxxx)
        else if ((len_byte_1 & 0x40) == 0x00) { //we know msb = 1, check that next bit is 0
            if (i + 3 < entry.size()) {
                size_t len_byte_2 = entry[i + 3];
                len = ((len_byte_1 & 0x3f) << 8) | len_byte_2;
                len_bytes = 2;
            }
        }
        else {
            // TODO lengths greater than 16383 (0x3FFF) are encoded by splitting up the message into discrete chunks, each with its own length
            // marker. It doesn't look like we'll be receiving anything that long
            std::cerr << "NS3Client::process() : received a message with length field longer than 16383." << std::endl;
            continue;
        }
        if (len == -1) { continue; }
        // If the length makes sense bsmPub(fits in the buffer), copy out the message bytes and pass to the Application class
        if ((i + 1 + len + len_bytes) < entry.size()) {
            // bool found_valid_msg = true;
            size_t start_index = i;
            size_t end_index = i + 2 + len + len_bytes; // includes 2 msgID bytes before message body
            //this constructor has range [first, last) hence the + 1
            std::vector<uint8_t> msg_vec(entry.begin() + start_index, entry.begin() + end_index);
            onMessageReceived(msg_vec, msg_id);
            break;
        }
    }
}
References process_traj_logs::data, process_traj_logs::end_index, process_bag::i, onMessageReceived, and process_traj_logs::start_index.
Referenced by connect().
registermsg()
bool NS3Client::registermsg (const std::shared_ptr< std::vector< uint8_t > > & message, const std::string & remote_address, unsigned short remote_port, unsigned short local_port)
connects and send handshake message to MOSAIC CARMA Ambassador
Parameters
message udp message
remote_address IPv4 address of OBU
remote_port of client service
local_port of client service
Returns
true on sucessful connect, false otherwise
Definition at line 16 of file ns-3_client.cpp.
{
    bool success = false;
    if (connect(remote_address, remote_port, local_port))
    {
        bool send_success = sendNS3Message(message);
        if (send_success)
        {
            // ROS_DEBUG("Handshake Message sent successfully");
            success = true;
        }
        // else ROS_DEBUG("Handshake Message send failed");
    }
    // else ROS_DEBUG( "Connection failed" );
    close();
    return success;
}
References close(), connect(), and sendNS3Message().
Referenced by NS3Adapter::broadcastHandshakemsg().
sendNS3Message()
bool NS3Client::sendNS3Message (const std::shared_ptr< std::vector< uint8_t > > & message)
sends a udp message
Definition at line 167 of file ns-3_client.cpp.
{
    if(!running_) return false;
    try {
        output_strand_->post([this,message]()
{
                                 try
{
                                     udp_out_socket_->send_to(boost::asio::buffer(*message), remote_udp_ep_);
                                 }
                                 catch(boost::system::system_error error_code)
{
                                     onError(error_code.code());
                                 }
                                 catch(...)
{
                                     onError(boost::asio::error::fault);
                                 }
                             });
        return true;
    }
    catch (std::exception& e) {
        return false;
    }
}
References onError, output_strand_, remote_udp_ep_, running_, and udp_out_socket_.
Referenced by registermsg(), NS3Adapter::sendMessageFromQueue(), and NS3Adapter::sendMessageSrv().
Member Data Documentation
io_
std::unique_ptr<boost::asio::io_service> NS3Client::io_ private
Definition at line 107 of file ns-3_client.h.
Referenced by close(), and connect().
io_thread_
std::shared_ptr<std::thread> NS3Client::io_thread_ private
Definition at line 111 of file ns-3_client.h.
Referenced by close(), and connect().
onConnect
boost::signals2::signal<void()> NS3Client::onConnect
Signaled when client is connected to the NS-3 adapter.
Definition at line 83 of file ns-3_client.h.
Referenced by connect(), and NS3Adapter::initialize().
onDisconnect
boost::signals2::signal<void()> NS3Client::onDisconnect
Signaled when client is disconnected from hardware.
Definition at line 88 of file ns-3_client.h.
Referenced by close(), and NS3Adapter::initialize().
onError
boost::signals2::signal<void(const boost::system::error_code&)> NS3Client::onError
Signaled when client experiences a fatal error. Client should be closed and reconnected.
Definition at line 93 of file ns-3_client.h.
Referenced by connect(), NS3Adapter::initialize(), and sendNS3Message().
onMessageReceived
boost::signals2::signal<void(std::vector<uint8_t> const &, uint16_t id)> NS3Client::onMessageReceived
Signaled when message received.
Definition at line 98 of file ns-3_client.h.
Referenced by NS3Adapter::initialize(), and process().
output_strand_
std::unique_ptr<boost::asio::io_service::strand> NS3Client::output_strand_ private
Definition at line 108 of file ns-3_client.h.
Referenced by connect(), and sendNS3Message().
remote_udp_ep_
boost::asio::ip::udp::endpoint NS3Client::remote_udp_ep_ private
Definition at line 116 of file ns-3_client.h.
Referenced by connect(), and sendNS3Message().
running_
volatile bool NS3Client::running_ private
Definition at line 112 of file ns-3_client.h.
Referenced by close(), connect(), connected(), and sendNS3Message().
udp_listener_
std::unique_ptr<cav::UDPListener> NS3Client::udp_listener_ private
Definition at line 117 of file ns-3_client.h.
Referenced by close(), and connect().
udp_out_socket_
std::unique_ptr<boost::asio::ip::udp::socket> NS3Client::udp_out_socket_ private
Definition at line 115 of file ns-3_client.h.
Referenced by close(), connect(), and sendNS3Message().
work_
std::shared_ptr<boost::asio::io_service::work> NS3Client::work_ private
Definition at line 109 of file ns-3_client.h.
Referenced by close(), and connect().
The documentation for this class was generated from the following files:
ns-3_adapter/include/ns-3_client.h
ns-3_adapter/src/ns-3_client.cpp