Carma-platform: carma_guidance_plugins::PluginBaseNode Class Reference
carma_guidance_plugins::PluginBaseNode Class Reference abstract
PluginBaseNode provides default functionality for all carma guidance plugins. This includes basic state machine management (largely delegated to ROS2 lifecycle behavior), required interfaces, and plugin discovery.
#include <plugin_base_node.hpp>
Public Member Functions
PluginBaseNode (const rclcpp::NodeOptions &)
PluginBaseNode constructor.
virtual ~PluginBaseNode ()=default
Virtual destructor for safe deletion.
virtual std::shared_ptr< carma_wm::WMListener > get_world_model_listener () final
Method to return the default world model listener provided as a convience by this base class If this method or get_world_model() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
virtual carma_wm::WorldModelConstPtr get_world_model () final
Method to return the default world model provided as a convience by this base class If this method or get_world_model_listener() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
virtual bool get_activation_status () final
Returns the activation status of this plugin. The plugins API callbacks will only be triggered when this method returns true.
virtual uint8_t get_type ()
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
std::string get_plugin_name_and_ns () const
Return the name of this plugin with namespace. NOTE: If only the name of the plugin is required, use get_plugin_name()
std::string get_plugin_name () const
Return the name of this plugin.
virtual bool get_availability ()=0
Get the availability status of this plugin based on the current operating environment. Method must be overriden by extending classes.
virtual std::string get_capability ()=0
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
virtual std::string get_version_id ()=0
Returns the version id of this plugin.
virtual carma_ros2_utils::CallbackReturn on_configure_plugin ()=0
Method which is triggered when this plugin is moved from the UNCONFIGURED to INACTIVE states. This method should be used to load parameters and is required to be implemented.
virtual carma_ros2_utils::CallbackReturn on_activate_plugin ()
Method which is triggered when this plugin is moved from the INACTIVE to ACTIVE states. This method should be used to prepare for future callbacks for plugin's capabilites.
virtual carma_ros2_utils::CallbackReturn on_deactivate_plugin ()
Method which is triggered when this plugin is moved from the ACTIVE to INACTIVE states. This method should be used to disable any functionality which should cease execution when plugin is inactive.
virtual carma_ros2_utils::CallbackReturn on_cleanup_plugin ()
Method which is triggered when this plugin is moved from the INACTIVE to UNCONFIGURED states. This method should be used to fully reset the plugin such that a future call to on_configure_plugin would leave the plugin in a fresh state as though just launched.
virtual carma_ros2_utils::CallbackReturn on_shutdown_plugin ()
Method which is triggered when this plugin is moved from any state to FINALIZED This method should be used to generate any shutdown logs or final cleanup.
virtual carma_ros2_utils::CallbackReturn on_error_plugin (const std::string &exception_string)
Method which is triggered when an unhandled exception occurs in this plugin This method should be used to cleanup such that the plugin could be moved to UNCONFIGURED state if possible.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_deactivate (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_cleanup (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_shutdown (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_error (const rclcpp_lifecycle::State &, const std::string &exception_string) override
FRIEND_TEST (carma_guidance_plugins_test, connections_test)
Private Member Functions
void discovery_timer_callback ()
Callback for the plugin discovery timer which will publish the plugin discovery message.
void lazy_wm_initialization ()
Helper function for lazy initialization of wm_listener_. If already initialized method returns (ie. not a reset)
Private Attributes
rclcpp::Publisher< carma_planning_msgs::msg::Plugin >::SharedPtr plugin_discovery_pub_
Publisher for plugin discovery. This publisher will begin publishing.
rclcpp::TimerBase::SharedPtr discovery_timer_
Timer to trigger publication of the plugin discovery message at a fixed frequency.
std::shared_ptr< carma_wm::WMListener > wm_listener_
carma_wm::WorldModelConstPtr wm_
Detailed Description
PluginBaseNode provides default functionality for all carma guidance plugins. This includes basic state machine management (largely delegated to ROS2 lifecycle behavior), required interfaces, and plugin discovery.
Extending classes must implement the on_configure_plugin method to load parameters, and my override the other state transitions methods on_<state>_plugin if desired. Additionally, extending classes must implement the methods such as get_version_id() which are used to populate the plugin discovery message.
NOTE: At the moment, this class and all extending classes are setup to support only single threading.
Definition at line 40 of file plugin_base_node.hpp.
Constructor & Destructor Documentation
PluginBaseNode()
carma_guidance_plugins::PluginBaseNode::PluginBaseNode (const rclcpp::NodeOptions & options) explicit
PluginBaseNode constructor.
Definition at line 25 of file plugin_base_node.cpp.
      : carma_ros2_utils::CarmaLifecycleNode(options)
  {
    // Setup discovery timer to publish onto the plugin_discovery_pub
    discovery_timer_ = create_timer(
        get_clock(),
        std::chrono::milliseconds(500), // 2 Hz frequency to account for 1Hz maneuver planning frequency
        std::bind(&PluginBaseNode::discovery_timer_callback, this));
  }
References discovery_timer_, and discovery_timer_callback().
~PluginBaseNode()
virtual carma_guidance_plugins::PluginBaseNode::~PluginBaseNode () virtual default
Virtual destructor for safe deletion.
Member Function Documentation
discovery_timer_callback()
void carma_guidance_plugins::PluginBaseNode::discovery_timer_callback () private
Callback for the plugin discovery timer which will publish the plugin discovery message.
Definition at line 141 of file plugin_base_node.cpp.
  {
    if (!plugin_discovery_pub_) // If the publisher has not been initalized then initialize it.
    {
      // Setup plugin publisher discovery which should bypass lifecycle behavior to ensure plugins are found
      // prior to them needing to be activated.
      // NOTE: Any other topics which need to be setup in the future should use handle_on_configure and the default this->create_publisher method to get a lifecycle publisher instead
      auto this_shared = shared_from_this(); // Usage of shared_from_this() means this cannot be done in the constructor thus it is delegated to the timer callback
      plugin_discovery_pub_ = rclcpp::create_publisher<carma_planning_msgs::msg::Plugin>(this_shared, "plugin_discovery", 1);
    }
    carma_planning_msgs::msg::Plugin msg;
    msg.name = get_plugin_name_and_ns();
    msg.version_id = get_version_id();
    msg.type = get_type();
    msg.available = get_availability();
    msg.activated = get_activation_status();
    msg.capability = get_capability();
    plugin_discovery_pub_->publish(msg);
  }
References get_activation_status(), get_availability(), get_capability(), get_plugin_name_and_ns(), get_type(), get_version_id(), and plugin_discovery_pub_.
Referenced by PluginBaseNode().
FRIEND_TEST()
carma_guidance_plugins::PluginBaseNode::FRIEND_TEST (carma_guidance_plugins_test , connections_test)
get_activation_status()
bool carma_guidance_plugins::PluginBaseNode::get_activation_status () final virtual
Returns the activation status of this plugin. The plugins API callbacks will only be triggered when this method returns true.
Returns
True if plugin is in the ACTIVE state. False otherwise.
Definition at line 72 of file plugin_base_node.cpp.
{
    // Determine the plugin activation state by checking which lifecycle state we are in.
    // If we are active then the plugin is active otherwise the plugin is inactive
    return get_current_state().id() == lifecycle_msgs::msg::State::PRIMARY_STATE_ACTIVE;
  }
Referenced by discovery_timer_callback(), carma_guidance_plugins::ControlPlugin::handle_on_configure(), carma_guidance_plugins::StrategicPlugin::handle_on_configure(), and carma_guidance_plugins::TacticalPlugin::handle_on_configure().
get_availability()
virtual bool carma_guidance_plugins::PluginBaseNode::get_availability () pure virtual
Get the availability status of this plugin based on the current operating environment. Method must be overriden by extending classes.
Returns
This method should return true if the plugin's current understanding of the world means it would be capable of planning or executing its capability.
Implemented in lci_strategic_plugin::LCIStrategicPlugin, route_following_plugin::RouteFollowingPlugin, sci_strategic_plugin::SCIStrategicPlugin, stop_and_dwell_strategic_plugin::StopAndDwellStrategicPlugin, stop_controlled_intersection_tactical_plugin::StopControlledIntersectionTacticalPlugin, approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin, cooperative_lanechange::CooperativeLaneChangePlugin, inlanecruising_plugin::InLaneCruisingPluginNode, intersection_transit_maneuvering::IntersectionTransitManeuveringNode, light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode, platoon_strategic_ihp::Node, platooning_tactical_plugin::Node, pure_pursuit_wrapper::PurePursuitWrapperNode, stop_and_wait_plugin::StopandWaitNode, SUB::Node, SUB::Node, SUB::Node, and yield_plugin::YieldPluginNode.
Referenced by discovery_timer_callback().
get_capability()
virtual std::string carma_guidance_plugins::PluginBaseNode::get_capability () pure virtual
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
Returns
Forward slash separated string describing the plugin's capabilities per the plugin capabilites API
Implemented in carma_guidance_plugins::ControlPlugin, carma_guidance_plugins::StrategicPlugin, and carma_guidance_plugins::TacticalPlugin.
Referenced by discovery_timer_callback().
get_plugin_name()
std::string carma_guidance_plugins::PluginBaseNode::get_plugin_name () const
Return the name of this plugin.
Returns
Name of this plugin
Definition at line 50 of file plugin_base_node.cpp.
  {
    return std::string(get_name());
  }
Referenced by light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode::on_configure_plugin(), and stop_controlled_intersection_tactical_plugin::StopControlledIntersectionTacticalPlugin::plan_trajectory_callback().
get_plugin_name_and_ns()
std::string carma_guidance_plugins::PluginBaseNode::get_plugin_name_and_ns () const
Return the name of this plugin with namespace. NOTE: If only the name of the plugin is required, use get_plugin_name()
Returns
Name of this plugin with namespace
Definition at line 55 of file plugin_base_node.cpp.
  {
    return std::string(get_namespace()) + "/" + std::string(get_name());
  }
Referenced by discovery_timer_callback().
get_type()
uint8_t carma_guidance_plugins::PluginBaseNode::get_type () virtual
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
Returns
The extending class type or UNKOWN if the class or no parent class has implement this method.
Reimplemented in carma_guidance_plugins::ControlPlugin, carma_guidance_plugins::StrategicPlugin, and carma_guidance_plugins::TacticalPlugin.
Definition at line 134 of file plugin_base_node.cpp.
  {
    // Base class returns unknown.
    // Its expected that 2nd level extending classes (strategic, tactical, control) will return correct type by overriding
    return carma_planning_msgs::msg::Plugin::UNKNOWN;
  }
Referenced by discovery_timer_callback().
get_version_id()
virtual std::string carma_guidance_plugins::PluginBaseNode::get_version_id () pure virtual
Returns the version id of this plugin.
Returns
The version id represented as a string
Implemented in lci_strategic_plugin::LCIStrategicPlugin, route_following_plugin::RouteFollowingPlugin, sci_strategic_plugin::SCIStrategicPlugin, stop_and_dwell_strategic_plugin::StopAndDwellStrategicPlugin, stop_controlled_intersection_tactical_plugin::StopControlledIntersectionTacticalPlugin, approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin, cooperative_lanechange::CooperativeLaneChangePlugin, intersection_transit_maneuvering::IntersectionTransitManeuveringNode, light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode, platoon_strategic_ihp::Node, platooning_tactical_plugin::Node, pure_pursuit_wrapper::PurePursuitWrapperNode, SUB::Node, SUB::Node, SUB::Node, inlanecruising_plugin::InLaneCruisingPluginNode, stop_and_wait_plugin::StopandWaitNode, and yield_plugin::YieldPluginNode.
Referenced by discovery_timer_callback().
get_world_model()
carma_wm::WorldModelConstPtr carma_guidance_plugins::PluginBaseNode::get_world_model () final virtual
Method to return the default world model provided as a convience by this base class If this method or get_world_model_listener() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
Returns
Pointer to an initialized world model. Returned instance is that same as get_world_model_listener()->getWorldModel();
Definition at line 66 of file plugin_base_node.cpp.
  {
    lazy_wm_initialization();
    return wm_;
  }
References lazy_wm_initialization(), and wm_.
Referenced by approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin::on_configure_plugin(), cooperative_lanechange::CooperativeLaneChangePlugin::on_configure_plugin(), inlanecruising_plugin::InLaneCruisingPluginNode::on_configure_plugin(), lci_strategic_plugin::LCIStrategicPlugin::on_configure_plugin(), platoon_strategic_ihp::Node::on_configure_plugin(), platooning_tactical_plugin::Node::on_configure_plugin(), route_following_plugin::RouteFollowingPlugin::on_configure_plugin(), sci_strategic_plugin::SCIStrategicPlugin::on_configure_plugin(), stop_and_dwell_strategic_plugin::StopAndDwellStrategicPlugin::on_configure_plugin(), stop_and_wait_plugin::StopandWaitNode::on_configure_plugin(), yield_plugin::YieldPluginNode::on_configure_plugin(), light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode::on_configure_plugin(), and stop_controlled_intersection_tactical_plugin::StopControlledIntersectionTacticalPlugin::on_configure_plugin().
get_world_model_listener()
std::shared_ptr< carma_wm::WMListener > carma_guidance_plugins::PluginBaseNode::get_world_model_listener () final virtual
Method to return the default world model listener provided as a convience by this base class If this method or get_world_model() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
Returns
Pointer to an initialized world model listener
Definition at line 60 of file plugin_base_node.cpp.
  {
    lazy_wm_initialization();
    return wm_listener_;
  }
References lazy_wm_initialization(), and wm_listener_.
Referenced by route_following_plugin::RouteFollowingPlugin::on_configure_plugin().
handle_on_activate()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::PluginBaseNode::handle_on_activate (const rclcpp_lifecycle::State &) override
Definition at line 109 of file plugin_base_node.cpp.
  {
    return on_activate_plugin();
  }
References on_activate_plugin().
Referenced by carma_guidance_plugins::ControlPlugin::handle_on_activate(), carma_guidance_plugins::StrategicPlugin::handle_on_activate(), and carma_guidance_plugins::TacticalPlugin::handle_on_activate().
handle_on_cleanup()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::PluginBaseNode::handle_on_cleanup (const rclcpp_lifecycle::State &) override
Definition at line 119 of file plugin_base_node.cpp.
  {
    return on_cleanup_plugin();
  }
References on_cleanup_plugin().
Referenced by carma_guidance_plugins::ControlPlugin::handle_on_cleanup(), carma_guidance_plugins::StrategicPlugin::handle_on_cleanup(), and carma_guidance_plugins::TacticalPlugin::handle_on_cleanup().
handle_on_configure()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::PluginBaseNode::handle_on_configure (const rclcpp_lifecycle::State &) override
Definition at line 104 of file plugin_base_node.cpp.
  {
    return on_configure_plugin();
  }
References on_configure_plugin().
Referenced by carma_guidance_plugins::ControlPlugin::handle_on_configure(), carma_guidance_plugins::StrategicPlugin::handle_on_configure(), and carma_guidance_plugins::TacticalPlugin::handle_on_configure().
handle_on_deactivate()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::PluginBaseNode::handle_on_deactivate (const rclcpp_lifecycle::State &) override
Definition at line 114 of file plugin_base_node.cpp.
  {
    return on_deactivate_plugin();
  }
References on_deactivate_plugin().
Referenced by carma_guidance_plugins::ControlPlugin::handle_on_deactivate(), carma_guidance_plugins::StrategicPlugin::handle_on_deactivate(), and carma_guidance_plugins::TacticalPlugin::handle_on_deactivate().
handle_on_error()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::PluginBaseNode::handle_on_error (const rclcpp_lifecycle::State & , const std::string & exception_string) override
Definition at line 129 of file plugin_base_node.cpp.
  {
    return on_error_plugin(exception_string);
  }
References on_error_plugin().
Referenced by carma_guidance_plugins::ControlPlugin::handle_on_error(), carma_guidance_plugins::StrategicPlugin::handle_on_error(), and carma_guidance_plugins::TacticalPlugin::handle_on_error().
handle_on_shutdown()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::PluginBaseNode::handle_on_shutdown (const rclcpp_lifecycle::State &) override
Definition at line 124 of file plugin_base_node.cpp.
  {
    return on_shutdown_plugin();
  }
References on_shutdown_plugin().
Referenced by carma_guidance_plugins::ControlPlugin::handle_on_shutdown(), carma_guidance_plugins::StrategicPlugin::handle_on_shutdown(), and carma_guidance_plugins::TacticalPlugin::handle_on_shutdown().
lazy_wm_initialization()
void carma_guidance_plugins::PluginBaseNode::lazy_wm_initialization () private
Helper function for lazy initialization of wm_listener_. If already initialized method returns (ie. not a reset)
Definition at line 36 of file plugin_base_node.cpp.
  {
    if (wm_listener_)
      return; // Already initialized
    wm_listener_ = std::make_shared<carma_wm::WMListener>(
        this->get_node_base_interface(), this->get_node_logging_interface(),
       this->get_node_topics_interface(), this->get_node_parameters_interface()
      );
    wm_ = wm_listener_->getWorldModel();
  }
References wm_, and wm_listener_.
Referenced by get_world_model(), and get_world_model_listener().
on_activate_plugin()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::PluginBaseNode::on_activate_plugin () virtual
Method which is triggered when this plugin is moved from the INACTIVE to ACTIVE states. This method should be used to prepare for future callbacks for plugin's capabilites.
Returns
SUCCESS, FAILURE, or ERROR. Transition to ACTIVE will only complete on SUCCESS.
Reimplemented in approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin, lci_strategic_plugin::LCIStrategicPlugin, route_following_plugin::RouteFollowingPlugin, sci_strategic_plugin::SCIStrategicPlugin, and stop_and_dwell_strategic_plugin::StopAndDwellStrategicPlugin.
Definition at line 78 of file plugin_base_node.cpp.
  {
    return carma_ros2_utils::CallbackReturn::SUCCESS;
  }
Referenced by handle_on_activate().
on_cleanup_plugin()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::PluginBaseNode::on_cleanup_plugin () virtual
Method which is triggered when this plugin is moved from the INACTIVE to UNCONFIGURED states. This method should be used to fully reset the plugin such that a future call to on_configure_plugin would leave the plugin in a fresh state as though just launched.
Returns
SUCCESS, FAILURE, or ERROR. Transition to UNCONFIGURED will only complete on SUCCESS.
Reimplemented in platoon_strategic_ihp::Node.
Definition at line 88 of file plugin_base_node.cpp.
  {
    return carma_ros2_utils::CallbackReturn::SUCCESS;
  }
Referenced by handle_on_cleanup().
on_configure_plugin()
virtual carma_ros2_utils::CallbackReturn carma_guidance_plugins::PluginBaseNode::on_configure_plugin () pure virtual
Method which is triggered when this plugin is moved from the UNCONFIGURED to INACTIVE states. This method should be used to load parameters and is required to be implemented.
Returns
SUCCESS, FAILURE, or ERROR. Transition to INACTIVE will only complete on SUCCESS.
Implemented in approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin, cooperative_lanechange::CooperativeLaneChangePlugin, inlanecruising_plugin::InLaneCruisingPluginNode, lci_strategic_plugin::LCIStrategicPlugin, platoon_strategic_ihp::Node, platooning_tactical_plugin::Node, route_following_plugin::RouteFollowingPlugin, sci_strategic_plugin::SCIStrategicPlugin, stop_and_dwell_strategic_plugin::StopAndDwellStrategicPlugin, stop_and_wait_plugin::StopandWaitNode, SUB::Node, SUB::Node, SUB::Node, yield_plugin::YieldPluginNode, intersection_transit_maneuvering::IntersectionTransitManeuveringNode, light_controlled_intersection_tactical_plugin::LightControlledIntersectionTransitPluginNode, pure_pursuit_wrapper::PurePursuitWrapperNode, and stop_controlled_intersection_tactical_plugin::StopControlledIntersectionTacticalPlugin.
Referenced by handle_on_configure().
on_deactivate_plugin()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::PluginBaseNode::on_deactivate_plugin () virtual
Method which is triggered when this plugin is moved from the ACTIVE to INACTIVE states. This method should be used to disable any functionality which should cease execution when plugin is inactive.
Returns
SUCCESS, FAILURE, or ERROR. Transition to INACTIVE will only complete on SUCCESS.
Definition at line 83 of file plugin_base_node.cpp.
  {
    return carma_ros2_utils::CallbackReturn::SUCCESS;
  }
Referenced by handle_on_deactivate().
on_error_plugin()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::PluginBaseNode::on_error_plugin (const std::string & exception_string) virtual
Method which is triggered when an unhandled exception occurs in this plugin This method should be used to cleanup such that the plugin could be moved to UNCONFIGURED state if possible.
Parameters
exception_string The exception description
Returns
SUCCESS, FAILURE, or ERROR. On SUCCESS plugin moves to UNCONFIGURED state else FINALIZED. Default behavior is to move to FINALIZED.
Definition at line 98 of file plugin_base_node.cpp.
  {
    // On error should default to failure so user must explicitly implement error handling to get any other behavior
    return carma_ros2_utils::CallbackReturn::FAILURE;
  }
Referenced by handle_on_error().
on_shutdown_plugin()
carma_ros2_utils::CallbackReturn carma_guidance_plugins::PluginBaseNode::on_shutdown_plugin () virtual
Method which is triggered when this plugin is moved from any state to FINALIZED This method should be used to generate any shutdown logs or final cleanup.
Returns
SUCCESS, FAILURE, or ERROR. On ERROR, may temporarily go to on_error_plugin() before calling finalized.
Definition at line 93 of file plugin_base_node.cpp.
  {
    return carma_ros2_utils::CallbackReturn::SUCCESS;
  }
Referenced by handle_on_shutdown().
Member Data Documentation
discovery_timer_
rclcpp::TimerBase::SharedPtr carma_guidance_plugins::PluginBaseNode::discovery_timer_ private
Timer to trigger publication of the plugin discovery message at a fixed frequency.
Definition at line 51 of file plugin_base_node.hpp.
Referenced by PluginBaseNode().
plugin_discovery_pub_
rclcpp::Publisher<carma_planning_msgs::msg::Plugin>::SharedPtr carma_guidance_plugins::PluginBaseNode::plugin_discovery_pub_ private
Publisher for plugin discovery. This publisher will begin publishing.
Definition at line 47 of file plugin_base_node.hpp.
Referenced by discovery_timer_callback().
wm_
carma_wm::WorldModelConstPtr carma_guidance_plugins::PluginBaseNode::wm_ private
Definition at line 61 of file plugin_base_node.hpp.
Referenced by get_world_model(), and lazy_wm_initialization().
wm_listener_
std::shared_ptr<carma_wm::WMListener> carma_guidance_plugins::PluginBaseNode::wm_listener_ private
Definition at line 56 of file plugin_base_node.hpp.
Referenced by get_world_model_listener(), and lazy_wm_initialization().
The documentation for this class was generated from the following files:
carma_guidance_plugins/include/carma_guidance_plugins/plugin_base_node.hpp
carma_guidance_plugins/src/plugin_base_node.cpp