Carma-platform: platooning_tactical_plugin::Node Class Reference
platooning_tactical_plugin::Node Class Reference
ROS node for the PlatooningTacticalPlugin to initialize and configure parameters and publishers/subscribers.
#include <platooning_tactical_plugin_node.h>
Public Member Functions
Node (const rclcpp::NodeOptions &)
Node constructor.
rcl_interfaces::msg::SetParametersResult parameter_update_callback (const std::vector< rclcpp::Parameter > &parameters)
Example callback for dynamic parameter updates.
void plan_trajectory_callback (std::shared_ptr< rmw_request_id_t >, carma_planning_msgs::srv::PlanTrajectory::Request::SharedPtr req, carma_planning_msgs::srv::PlanTrajectory::Response::SharedPtr resp) override
Extending class provided callback which should return a planned trajectory based on the provided trajectory planning request.
bool get_availability () override
Get the availability status of this plugin based on the current operating environment. Method must be overriden by extending classes.
std::string get_version_id () override
Returns the version id of this plugin.
carma_ros2_utils::CallbackReturn on_configure_plugin ()
This method should be used to load parameters and will be called on the configure state transition.
Public Member Functions inherited from carma_guidance_plugins::TacticalPlugin
TacticalPlugin (const rclcpp::NodeOptions &)
TacticalPlugin constructor.
virtual ~TacticalPlugin ()=default
Virtual destructor for safe deletion.
virtual void plan_trajectory_callback (std::shared_ptr< rmw_request_id_t > srv_header, carma_planning_msgs::srv::PlanTrajectory::Request::SharedPtr req, carma_planning_msgs::srv::PlanTrajectory::Response::SharedPtr resp)=0
Extending class provided callback which should return a planned trajectory based on the provided trajectory planning request.
std::string get_capability () override
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
uint8_t get_type () override final
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_deactivate (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_cleanup (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_shutdown (const rclcpp_lifecycle::State &) override final
carma_ros2_utils::CallbackReturn handle_on_error (const rclcpp_lifecycle::State &, const std::string &exception_string) override final
Public Member Functions inherited from carma_guidance_plugins::PluginBaseNode
PluginBaseNode (const rclcpp::NodeOptions &)
PluginBaseNode constructor.
virtual ~PluginBaseNode ()=default
Virtual destructor for safe deletion.
virtual std::shared_ptr< carma_wm::WMListener > get_world_model_listener () final
Method to return the default world model listener provided as a convience by this base class If this method or get_world_model() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
virtual carma_wm::WorldModelConstPtr get_world_model () final
Method to return the default world model provided as a convience by this base class If this method or get_world_model_listener() are not called then the world model remains uninitialized and will not create unnecessary subscriptions.
virtual bool get_activation_status () final
Returns the activation status of this plugin. The plugins API callbacks will only be triggered when this method returns true.
virtual uint8_t get_type ()
Returns the type of this plugin according to the carma_planning_msgs::Plugin type enum. Extending classes for the specific type should override this method.
std::string get_plugin_name_and_ns () const
Return the name of this plugin with namespace. NOTE: If only the name of the plugin is required, use get_plugin_name()
std::string get_plugin_name () const
Return the name of this plugin.
virtual bool get_availability ()=0
Get the availability status of this plugin based on the current operating environment. Method must be overriden by extending classes.
virtual std::string get_capability ()=0
Get the capability string representing this plugins capabilities Method must be overriden by extending classes. Expectation is that abstract plugin type parent classes will provide a default implementation.
virtual std::string get_version_id ()=0
Returns the version id of this plugin.
virtual carma_ros2_utils::CallbackReturn on_configure_plugin ()=0
Method which is triggered when this plugin is moved from the UNCONFIGURED to INACTIVE states. This method should be used to load parameters and is required to be implemented.
virtual carma_ros2_utils::CallbackReturn on_activate_plugin ()
Method which is triggered when this plugin is moved from the INACTIVE to ACTIVE states. This method should be used to prepare for future callbacks for plugin's capabilites.
virtual carma_ros2_utils::CallbackReturn on_deactivate_plugin ()
Method which is triggered when this plugin is moved from the ACTIVE to INACTIVE states. This method should be used to disable any functionality which should cease execution when plugin is inactive.
virtual carma_ros2_utils::CallbackReturn on_cleanup_plugin ()
Method which is triggered when this plugin is moved from the INACTIVE to UNCONFIGURED states. This method should be used to fully reset the plugin such that a future call to on_configure_plugin would leave the plugin in a fresh state as though just launched.
virtual carma_ros2_utils::CallbackReturn on_shutdown_plugin ()
Method which is triggered when this plugin is moved from any state to FINALIZED This method should be used to generate any shutdown logs or final cleanup.
virtual carma_ros2_utils::CallbackReturn on_error_plugin (const std::string &exception_string)
Method which is triggered when an unhandled exception occurs in this plugin This method should be used to cleanup such that the plugin could be moved to UNCONFIGURED state if possible.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_deactivate (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_cleanup (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_shutdown (const rclcpp_lifecycle::State &) override
carma_ros2_utils::CallbackReturn handle_on_error (const rclcpp_lifecycle::State &, const std::string &exception_string) override
FRIEND_TEST (carma_guidance_plugins_test, connections_test)
Private Attributes
PlatooningTacticalPluginConfig config_
std::shared_ptr< PlatooningTacticalPlugin > worker_
Detailed Description
ROS node for the PlatooningTacticalPlugin to initialize and configure parameters and publishers/subscribers.
Definition at line 31 of file platooning_tactical_plugin_node.h.
Constructor & Destructor Documentation
Node()
platooning_tactical_plugin::Node::Node (const rclcpp::NodeOptions & options) explicit
Node constructor.
Definition at line 23 of file platooning_tactical_plugin_node.cpp.
      : carma_guidance_plugins::TacticalPlugin(options)
  {
    // Create initial config
    config_ = PlatooningTacticalPluginConfig();
    // Declare parameters
    config_.trajectory_time_length = declare_parameter<double>("trajectory_time_length", config_.trajectory_time_length);
    config_.curve_resample_step_size = declare_parameter<double>("curve_resample_step_size", config_.curve_resample_step_size);
    config_.default_downsample_ratio = declare_parameter<int>("default_downsample_ratio", config_.default_downsample_ratio);
    config_.turn_downsample_ratio = declare_parameter<int>("turn_downsample_ratio", config_.turn_downsample_ratio);
    config_.minimum_speed = declare_parameter<double>("minimum_speed", config_.minimum_speed);
    config_.max_accel_multiplier = declare_parameter<double>("max_accel_multiplier", config_.max_accel_multiplier);
    config_.lat_accel_multiplier = declare_parameter<double>("lat_accel_multiplier", config_.lat_accel_multiplier);
    config_.back_distance = declare_parameter<double>("back_distance", config_.back_distance);
    config_.speed_moving_average_window_size = declare_parameter<int>("speed_moving_average_window_size", config_.speed_moving_average_window_size);
    config_.curvature_moving_average_window_size = declare_parameter<int>("curvature_moving_average_window_size", config_.curvature_moving_average_window_size);
    config_.max_accel = declare_parameter<double>("vehicle_acceleration_limit", config_.max_accel);
    config_.lateral_accel_limit = declare_parameter<double>("vehicle_lateral_accel_limit", config_.lateral_accel_limit);
    config_.enable_object_avoidance = declare_parameter<bool>("enable_object_avoidance", config_.enable_object_avoidance);
    config_.buffer_ending_downtrack = declare_parameter<double>("buffer_ending_downtrack", config_.buffer_ending_downtrack);
    config_.lateral_accel_limit = config_.lateral_accel_limit * config_.lat_accel_multiplier;
    config_.max_accel = config_.max_accel *  config_.max_accel_multiplier;
    RCLCPP_INFO_STREAM(get_logger(), "PlatooningTacticalPlugin Params" << config_);
  }
References PlatooningTacticalPluginConfig::back_distance, PlatooningTacticalPluginConfig::buffer_ending_downtrack, config_, PlatooningTacticalPluginConfig::curvature_moving_average_window_size, PlatooningTacticalPluginConfig::curve_resample_step_size, PlatooningTacticalPluginConfig::default_downsample_ratio, PlatooningTacticalPluginConfig::enable_object_avoidance, PlatooningTacticalPluginConfig::lat_accel_multiplier, PlatooningTacticalPluginConfig::lateral_accel_limit, PlatooningTacticalPluginConfig::max_accel, PlatooningTacticalPluginConfig::max_accel_multiplier, PlatooningTacticalPluginConfig::minimum_speed, PlatooningTacticalPluginConfig::speed_moving_average_window_size, PlatooningTacticalPluginConfig::trajectory_time_length, and PlatooningTacticalPluginConfig::turn_downsample_ratio.
Member Function Documentation
get_availability()
bool platooning_tactical_plugin::Node::get_availability () override virtual
Get the availability status of this plugin based on the current operating environment. Method must be overriden by extending classes.
Returns
This method should return true if the plugin's current understanding of the world means it would be capable of planning or executing its capability.
Implements carma_guidance_plugins::PluginBaseNode.
Definition at line 137 of file platooning_tactical_plugin_node.cpp.
{
    return true;
  }
get_version_id()
std::string platooning_tactical_plugin::Node::get_version_id () override virtual
Returns the version id of this plugin.
Returns
The version id represented as a string
Implements carma_guidance_plugins::PluginBaseNode.
Definition at line 141 of file platooning_tactical_plugin_node.cpp.
{
    return "v4.0";
  }
on_configure_plugin()
carma_ros2_utils::CallbackReturn platooning_tactical_plugin::Node::on_configure_plugin () virtual
This method should be used to load parameters and will be called on the configure state transition.
Implements carma_guidance_plugins::PluginBaseNode.
Definition at line 90 of file platooning_tactical_plugin_node.cpp.
  {
    // Reset config
    config_ = PlatooningTacticalPluginConfig();
    // Load parameters
    get_parameter<double>("trajectory_time_length", config_.trajectory_time_length);
    get_parameter<double>("curve_resample_step_size", config_.curve_resample_step_size);
    get_parameter<int>("default_downsample_ratio", config_.default_downsample_ratio);
    get_parameter<int>("turn_downsample_ratio", config_.turn_downsample_ratio);
    get_parameter<double>("minimum_speed", config_.minimum_speed);
    get_parameter<double>("max_accel_multiplier", config_.max_accel_multiplier);
    get_parameter<double>("lat_accel_multiplier", config_.lat_accel_multiplier);
    get_parameter<double>("back_distance", config_.back_distance);
    get_parameter<int>("speed_moving_average_window_size", config_.speed_moving_average_window_size);
    get_parameter<int>("curvature_moving_average_window_size", config_.curvature_moving_average_window_size);
    get_parameter<double>("vehicle_acceleration_limit", config_.max_accel);
    get_parameter<double>("vehicle_lateral_accel_limit", config_.lateral_accel_limit);
    get_parameter<bool>("enable_object_avoidance", config_.enable_object_avoidance);
    get_parameter<double>("buffer_ending_downtrack", config_.buffer_ending_downtrack);
    config_.lateral_accel_limit = config_.lateral_accel_limit * config_.lat_accel_multiplier;
    config_.max_accel = config_.max_accel *  config_.max_accel_multiplier;
    RCLCPP_INFO_STREAM(get_logger(), "PlatooningTacticalPlugin Params" << config_);
    // Register runtime parameter update callback
    add_on_set_parameters_callback(std::bind(&Node::parameter_update_callback, this, std_ph::_1));
    worker_ = std::make_shared<PlatooningTacticalPlugin>(get_world_model(), config_,
      std::make_shared<carma_ros2_utils::timers::ROSTimerFactory>(shared_from_this()));
    // Return success if everything initialized successfully
    return CallbackReturn::SUCCESS;
  }
References PlatooningTacticalPluginConfig::back_distance, PlatooningTacticalPluginConfig::buffer_ending_downtrack, config_, PlatooningTacticalPluginConfig::curvature_moving_average_window_size, PlatooningTacticalPluginConfig::curve_resample_step_size, PlatooningTacticalPluginConfig::default_downsample_ratio, PlatooningTacticalPluginConfig::enable_object_avoidance, carma_guidance_plugins::PluginBaseNode::get_world_model(), PlatooningTacticalPluginConfig::lat_accel_multiplier, PlatooningTacticalPluginConfig::lateral_accel_limit, PlatooningTacticalPluginConfig::max_accel, PlatooningTacticalPluginConfig::max_accel_multiplier, PlatooningTacticalPluginConfig::minimum_speed, parameter_update_callback(), PlatooningTacticalPluginConfig::speed_moving_average_window_size, PlatooningTacticalPluginConfig::trajectory_time_length, PlatooningTacticalPluginConfig::turn_downsample_ratio, and worker_.
parameter_update_callback()
rcl_interfaces::msg::SetParametersResult platooning_tactical_plugin::Node::parameter_update_callback (const std::vector< rclcpp::Parameter > & parameters)
Example callback for dynamic parameter updates.
Definition at line 52 of file platooning_tactical_plugin_node.cpp.
  {
    auto error = update_params<bool>({
      {"enable_object_avoidance", config_.enable_object_avoidance}
    }, parameters);
    auto error2 = update_params<int>({
      {"default_downsample_ratio", config_.default_downsample_ratio},
      {"turn_downsample_ratio", config_.turn_downsample_ratio},
      {"speed_moving_average_window_size", config_.speed_moving_average_window_size},
      {"curvature_moving_average_window_size", config_.curvature_moving_average_window_size}
    }, parameters);
    auto error3 = update_params<double>({
      {"trajectory_time_length", config_.trajectory_time_length},
      {"curve_resample_step_size", config_.curve_resample_step_size},
      {"minimum_speed", config_.minimum_speed},
      {"max_accel_multiplier", config_.max_accel_multiplier},
      {"lat_accel_multiplier", config_.lat_accel_multiplier},
      {"back_distance", config_.back_distance},
      {"buffer_ending_downtrack", config_.buffer_ending_downtrack}
    }, parameters); // Accel limits system wide and not allowed to be updated per node
    config_.lateral_accel_limit = config_.lateral_accel_limit * config_.lat_accel_multiplier;
    config_.max_accel = config_.max_accel *  config_.max_accel_multiplier;
    rcl_interfaces::msg::SetParametersResult result;
    result.successful = !error && !error2 && !error3;
    if (result.successful && worker_)
    {
      worker_->set_config(config_);
    }
    return result;
  }
References PlatooningTacticalPluginConfig::back_distance, PlatooningTacticalPluginConfig::buffer_ending_downtrack, config_, PlatooningTacticalPluginConfig::curvature_moving_average_window_size, PlatooningTacticalPluginConfig::curve_resample_step_size, PlatooningTacticalPluginConfig::default_downsample_ratio, PlatooningTacticalPluginConfig::enable_object_avoidance, PlatooningTacticalPluginConfig::lat_accel_multiplier, PlatooningTacticalPluginConfig::lateral_accel_limit, PlatooningTacticalPluginConfig::max_accel, PlatooningTacticalPluginConfig::max_accel_multiplier, PlatooningTacticalPluginConfig::minimum_speed, PlatooningTacticalPluginConfig::speed_moving_average_window_size, PlatooningTacticalPluginConfig::trajectory_time_length, PlatooningTacticalPluginConfig::turn_downsample_ratio, and worker_.
Referenced by on_configure_plugin().
plan_trajectory_callback()
void platooning_tactical_plugin::Node::plan_trajectory_callback (std::shared_ptr< rmw_request_id_t > srv_header, carma_planning_msgs::srv::PlanTrajectory::Request::SharedPtr req, carma_planning_msgs::srv::PlanTrajectory::Response::SharedPtr resp) override virtual
Extending class provided callback which should return a planned trajectory based on the provided trajectory planning request.
Parameters
srv_header RCL header for services calls. Can usually be ignored by implementers.
req The service request containing the maneuvers to plan trajectories for and current vehicle state
resp The response containing the planned trajectory
Implements carma_guidance_plugins::TacticalPlugin.
Definition at line 126 of file platooning_tactical_plugin_node.cpp.
  {
    if (!worker_)
      return;
    worker_->plan_trajectory_cb(*req, *resp);
  }
References worker_.
Member Data Documentation
config_
PlatooningTacticalPluginConfig platooning_tactical_plugin::Node::config_ private
Definition at line 34 of file platooning_tactical_plugin_node.h.
Referenced by Node(), on_configure_plugin(), and parameter_update_callback().
worker_
std::shared_ptr<PlatooningTacticalPlugin> platooning_tactical_plugin::Node::worker_ private
Definition at line 36 of file platooning_tactical_plugin_node.h.
Referenced by on_configure_plugin(), parameter_update_callback(), and plan_trajectory_callback().
The documentation for this class was generated from the following files:
platooning_tactical_plugin/include/platooning_tactical_plugin/platooning_tactical_plugin_node.h
platooning_tactical_plugin/src/platooning_tactical_plugin_node.cpp