Carma-platform: internal::DecodedStream< SourceStream, Encoding > Class Template Reference
internal::DecodedStream< SourceStream, Encoding > Class Template Reference
#include <regex.h>
Public Member Functions
DecodedStream (SourceStream &ss)
unsigned Peek ()
unsigned Take ()
Private Member Functions
void Decode ()
Private Attributes
SourceStream & ss_
unsigned codepoint_
Detailed Description
template<typename SourceStream, typename Encoding>
class internal::DecodedStream< SourceStream, Encoding >
Definition at line 53 of file regex.h.
Constructor & Destructor Documentation
DecodedStream()
template<typename SourceStream , typename Encoding > internal::DecodedStream< SourceStream, Encoding >::DecodedStream (SourceStream & ss) inline
Definition at line 55 of file regex.h.
: ss_(ss), codepoint_() { Decode(); }
References internal::DecodedStream< SourceStream, Encoding >::Decode().
Member Function Documentation
Decode()
template<typename SourceStream , typename Encoding > void internal::DecodedStream< SourceStream, Encoding >::Decode () inline private
Definition at line 65 of file regex.h.
                  {
        if (!Encoding::Decode(ss_, &codepoint_))
            codepoint_ = 0;
    }
References internal::DecodedStream< SourceStream, Encoding >::codepoint_, and internal::DecodedStream< SourceStream, Encoding >::ss_.
Referenced by internal::DecodedStream< SourceStream, Encoding >::DecodedStream(), and internal::DecodedStream< SourceStream, Encoding >::Take().
Peek()
template<typename SourceStream , typename Encoding > unsigned internal::DecodedStream< SourceStream, Encoding >::Peek () inline
Definition at line 56 of file regex.h.
{ return codepoint_; }
References internal::DecodedStream< SourceStream, Encoding >::codepoint_.
Referenced by internal::GenericRegex< Encoding, Allocator >::Parse(), internal::GenericRegex< Encoding, Allocator >::ParseRange(), and internal::GenericRegex< Encoding, Allocator >::ParseUnsigned().
Take()
template<typename SourceStream , typename Encoding > unsigned internal::DecodedStream< SourceStream, Encoding >::Take () inline
Definition at line 57 of file regex.h.
                    {
        unsigned c = codepoint_;
        if (c) // No further decoding when '\0'
            Decode();
        return c;
    }
References process_traj_logs::c, internal::DecodedStream< SourceStream, Encoding >::codepoint_, and internal::DecodedStream< SourceStream, Encoding >::Decode().
Referenced by internal::GenericRegex< Encoding, Allocator >::CharacterEscape(), internal::GenericRegex< Encoding, Allocator >::Parse(), internal::GenericRegex< Encoding, Allocator >::ParseRange(), internal::GenericRegex< Encoding, Allocator >::ParseUnsigned(), and internal::GenericRegexSearch< RegexType, Allocator >::SearchWithAnchoring().
Member Data Documentation
codepoint_
template<typename SourceStream , typename Encoding > unsigned internal::DecodedStream< SourceStream, Encoding >::codepoint_ private
Definition at line 71 of file regex.h.
Referenced by internal::DecodedStream< SourceStream, Encoding >::Decode(), internal::DecodedStream< SourceStream, Encoding >::Peek(), and internal::DecodedStream< SourceStream, Encoding >::Take().
ss_
template<typename SourceStream , typename Encoding > SourceStream& internal::DecodedStream< SourceStream, Encoding >::ss_ private
Definition at line 70 of file regex.h.
Referenced by internal::DecodedStream< SourceStream, Encoding >::Decode().
The documentation for this class was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/internal/regex.h