Carma-platform: port_drayage_plugin::PortDrayagePlugin Class Reference
port_drayage_plugin::PortDrayagePlugin Class Reference
#include <port_drayage_plugin.hpp>
Public Member Functions
PortDrayagePlugin (const rclcpp::NodeOptions &)
PortDrayagePlugin constructor.
bool callSetActiveRouteClient (std::shared_ptr< carma_planning_msgs::srv::SetActiveRoute::Request > req)
Calls the /guidance/set_active_route service client to set an active route.
void publishMobilityOperation (const carma_v2x_msgs::msg::MobilityOperation &msg)
Publishes a Mobility Operation message to the outgoing mobility operation topic.
void publishUIInstructions (const carma_msgs::msg::UIInstructions &msg)
Publishes a UI Instructions message to the outgoing UI Instructions topic.
rcl_interfaces::msg::SetParametersResult parameter_update_callback (const std::vector< rclcpp::Parameter > &parameters)
Callback for dynamic parameter updates.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &prev_state)
Private Attributes
carma_ros2_utils::SubPtr< geometry_msgs::msg::PoseStamped > pose_subscriber_
carma_ros2_utils::SubPtr< carma_v2x_msgs::msg::MobilityOperation > inbound_mobility_operation_subscriber_
carma_ros2_utils::SubPtr< carma_planning_msgs::msg::GuidanceState > guidance_state_subscriber_
carma_ros2_utils::SubPtr< carma_planning_msgs::msg::RouteEvent > route_event_subscriber_
carma_ros2_utils::SubPtr< std_msgs::msg::String > georeference_subscriber_
carma_ros2_utils::PubPtr< carma_v2x_msgs::msg::MobilityOperation > outbound_mobility_operations_publisher_
carma_ros2_utils::PubPtr< carma_msgs::msg::UIInstructions > ui_instructions_publisher_
carma_ros2_utils::ClientPtr< carma_planning_msgs::srv::SetActiveRoute > set_active_route_client_
Config config_
PortDrayageWorker pdw_
Detailed Description
Primary Port Drayage Plugin implementation class. Split into this class primarily concerned with the handling of ROS message processing and the PortDrayageWorker class responsible for handling the core business logic of the Port Drayage functionality.
Definition at line 43 of file port_drayage_plugin.hpp.
Constructor & Destructor Documentation
PortDrayagePlugin()
port_drayage_plugin::PortDrayagePlugin::PortDrayagePlugin (const rclcpp::NodeOptions & options) explicit
PortDrayagePlugin constructor.
Definition at line 22 of file port_drayage_plugin.cpp.
      : carma_ros2_utils::CarmaLifecycleNode(options),
      pdw_(get_node_logging_interface(), get_clock(),
           std::bind(&PortDrayagePlugin::publishMobilityOperation, this, std_ph::_1),
           std::bind(&PortDrayagePlugin::publishUIInstructions, this, std_ph::_1),
           std::bind(&PortDrayagePlugin::callSetActiveRouteClient, this, std_ph::_1))
  {
    // Create initial config
    config_ = Config();
    // Declare parameters
    config_.cmv_id = declare_parameter<std::string>("vehicle_id", config_.cmv_id);
    config_.cargo_id = declare_parameter<std::string>("cargo_id", config_.cargo_id);
    config_.enable_port_drayage = declare_parameter<bool>("enable_port_drayage", config_.enable_port_drayage);
    config_.starting_at_staging_area = declare_parameter<bool>("starting_at_staging_area", config_.starting_at_staging_area);
  }
References port_drayage_plugin::Config::cargo_id, port_drayage_plugin::Config::cmv_id, config_, port_drayage_plugin::Config::enable_port_drayage, and port_drayage_plugin::Config::starting_at_staging_area.
Member Function Documentation
callSetActiveRouteClient()
bool port_drayage_plugin::PortDrayagePlugin::callSetActiveRouteClient (std::shared_ptr< carma_planning_msgs::srv::SetActiveRoute::Request > req)
Calls the /guidance/set_active_route service client to set an active route.
Parameters
req The service request being used to call the service client
Returns
If the service client call was successful and no errors occurred while setting the new active route
Definition at line 110 of file port_drayage_plugin.cpp.
  {
    // Send request to set_active_route service
    auto route_result = set_active_route_client_->async_send_request(req);
    // Wait for response from service call
    auto future_status = route_result.wait_for(std::chrono::milliseconds(100));
    if (future_status == std::future_status::ready) {
      if(route_result.get()->error_status == carma_planning_msgs::srv::SetActiveRoute::Response::NO_ERROR){
        RCLCPP_DEBUG_STREAM(get_logger(), "Route Generation succeeded for Set Active Route service call.");
        return true;
      }
      else{
        RCLCPP_DEBUG_STREAM(get_logger(), "Route Generation failed for Set Active Route service call.");
        return false;
      }
    }
    else {
      // No response was received after making the service call
      RCLCPP_DEBUG_STREAM(get_logger(), "Set Active Route service call was not successful.");
      return false;
    }
  }
References set_active_route_client_.
handle_on_configure()
carma_ros2_utils::CallbackReturn port_drayage_plugin::PortDrayagePlugin::handle_on_configure (const rclcpp_lifecycle::State & prev_state)
Definition at line 63 of file port_drayage_plugin.cpp.
  {
    RCLCPP_INFO_STREAM(get_logger(), "port_drayage_plugin trying to configure");
    // Reset config
    config_ = Config();
    // Load parameters
    get_parameter<std::string>("vehicle_id", config_.cmv_id);
    get_parameter<std::string>("cargo_id", config_.cargo_id);
    get_parameter<bool>("enable_port_drayage", config_.enable_port_drayage);
    get_parameter<bool>("starting_at_staging_area", config_.starting_at_staging_area);
    RCLCPP_INFO_STREAM(get_logger(), "Loaded params: " << config_);
    // Register runtime parameter update callback
    add_on_set_parameters_callback(std::bind(&PortDrayagePlugin::parameter_update_callback, this, std_ph::_1));
    // Setup subscribers
    pose_subscriber_ = create_subscription<geometry_msgs::msg::PoseStamped>("current_pose", 5,
                                                              std::bind(&PortDrayageWorker::onNewPose, &pdw_, std_ph::_1));
    inbound_mobility_operation_subscriber_ = create_subscription<carma_v2x_msgs::msg::MobilityOperation>("incoming_mobility_operation", 5,
                                                              std::bind(&PortDrayageWorker::onInboundMobilityOperation, &pdw_, std_ph::_1));
    guidance_state_subscriber_ = create_subscription<carma_planning_msgs::msg::GuidanceState> ("guidance_state", 5,
                                                              std::bind(&PortDrayageWorker::onGuidanceState, &pdw_, std_ph::_1));
    route_event_subscriber_ = create_subscription<carma_planning_msgs::msg::RouteEvent>("route_event", 5,
                                                              std::bind(&PortDrayageWorker::onRouteEvent, &pdw_, std_ph::_1));
    georeference_subscriber_ = create_subscription<std_msgs::msg::String>("georeference", 1,
                                                              std::bind(&PortDrayageWorker::onNewGeoreference, &pdw_, std_ph::_1));
    // Setup publishers
    outbound_mobility_operations_publisher_ = create_publisher<carma_v2x_msgs::msg::MobilityOperation>("outgoing_mobility_operation", 5);
    ui_instructions_publisher_ = create_publisher<carma_msgs::msg::UIInstructions>("ui_instructions", 5);
    // Setup service clients
    set_active_route_client_ = create_client<carma_planning_msgs::srv::SetActiveRoute>("set_active_route");
    // Set PortDrayageWorker variables
    pdw_.setVehicleID(config_.cmv_id);
    pdw_.setCargoID(config_.cargo_id);
    pdw_.setEnablePortDrayageFlag(config_.enable_port_drayage);
    pdw_.setStartingAtStagingAreaFlag(config_.starting_at_staging_area);
    // Return success if everything initialized successfully
    return CallbackReturn::SUCCESS;
  }
References port_drayage_plugin::Config::cargo_id, port_drayage_plugin::Config::cmv_id, config_, port_drayage_plugin::Config::enable_port_drayage, georeference_subscriber_, guidance_state_subscriber_, inbound_mobility_operation_subscriber_, port_drayage_plugin::PortDrayageWorker::onGuidanceState(), port_drayage_plugin::PortDrayageWorker::onInboundMobilityOperation(), port_drayage_plugin::PortDrayageWorker::onNewGeoreference(), port_drayage_plugin::PortDrayageWorker::onNewPose(), port_drayage_plugin::PortDrayageWorker::onRouteEvent(), outbound_mobility_operations_publisher_, parameter_update_callback(), pdw_, pose_subscriber_, route_event_subscriber_, set_active_route_client_, port_drayage_plugin::PortDrayageWorker::setCargoID(), port_drayage_plugin::PortDrayageWorker::setEnablePortDrayageFlag(), port_drayage_plugin::PortDrayageWorker::setStartingAtStagingAreaFlag(), port_drayage_plugin::PortDrayageWorker::setVehicleID(), port_drayage_plugin::Config::starting_at_staging_area, and ui_instructions_publisher_.
parameter_update_callback()
rcl_interfaces::msg::SetParametersResult port_drayage_plugin::PortDrayagePlugin::parameter_update_callback (const std::vector< rclcpp::Parameter > & parameters)
Callback for dynamic parameter updates.
Definition at line 39 of file port_drayage_plugin.cpp.
  {
    auto error = update_params<std::string>({
      {"vehicle_id", config_.cmv_id},
      {"cargo_id", config_.cargo_id}}, parameters);
    auto error_2 = update_params<bool>({
      {"enable_port_drayage", config_.enable_port_drayage},
      {"starting_at_staging_area", config_.starting_at_staging_area}}, parameters);
    rcl_interfaces::msg::SetParametersResult result;
    result.successful = !error && !error_2;
    if (result.successful) {
      // Set PortDrayageWorker parameters
      pdw_.setVehicleID(config_.cmv_id);
      pdw_.setCargoID(config_.cargo_id);
      pdw_.setEnablePortDrayageFlag(config_.enable_port_drayage);
      pdw_.setStartingAtStagingAreaFlag(config_.starting_at_staging_area);
    }
    return result;
  }
References port_drayage_plugin::Config::cargo_id, port_drayage_plugin::Config::cmv_id, config_, port_drayage_plugin::Config::enable_port_drayage, pdw_, port_drayage_plugin::PortDrayageWorker::setCargoID(), port_drayage_plugin::PortDrayageWorker::setEnablePortDrayageFlag(), port_drayage_plugin::PortDrayageWorker::setStartingAtStagingAreaFlag(), port_drayage_plugin::PortDrayageWorker::setVehicleID(), and port_drayage_plugin::Config::starting_at_staging_area.
Referenced by handle_on_configure().
publishMobilityOperation()
void port_drayage_plugin::PortDrayagePlugin::publishMobilityOperation (const carma_v2x_msgs::msg::MobilityOperation & msg)
Publishes a Mobility Operation message to the outgoing mobility operation topic.
Parameters
msg The Mobility Operation message to be published
Definition at line 136 of file port_drayage_plugin.cpp.
  {
    outbound_mobility_operations_publisher_->publish(msg);
  }
References outbound_mobility_operations_publisher_.
publishUIInstructions()
void port_drayage_plugin::PortDrayagePlugin::publishUIInstructions (const carma_msgs::msg::UIInstructions & msg)
Publishes a UI Instructions message to the outgoing UI Instructions topic.
Parameters
msg The UI Instructions message to be published
Definition at line 141 of file port_drayage_plugin.cpp.
  {
    ui_instructions_publisher_->publish(msg);
  }
References ui_instructions_publisher_.
Member Data Documentation
config_
Config port_drayage_plugin::PortDrayagePlugin::config_ private
Definition at line 62 of file port_drayage_plugin.hpp.
Referenced by PortDrayagePlugin(), handle_on_configure(), and parameter_update_callback().
georeference_subscriber_
carma_ros2_utils::SubPtr<std_msgs::msg::String> port_drayage_plugin::PortDrayagePlugin::georeference_subscriber_ private
Definition at line 52 of file port_drayage_plugin.hpp.
Referenced by handle_on_configure().
guidance_state_subscriber_
carma_ros2_utils::SubPtr<carma_planning_msgs::msg::GuidanceState> port_drayage_plugin::PortDrayagePlugin::guidance_state_subscriber_ private
Definition at line 50 of file port_drayage_plugin.hpp.
Referenced by handle_on_configure().
inbound_mobility_operation_subscriber_
carma_ros2_utils::SubPtr<carma_v2x_msgs::msg::MobilityOperation> port_drayage_plugin::PortDrayagePlugin::inbound_mobility_operation_subscriber_ private
Definition at line 49 of file port_drayage_plugin.hpp.
Referenced by handle_on_configure().
outbound_mobility_operations_publisher_
carma_ros2_utils::PubPtr<carma_v2x_msgs::msg::MobilityOperation> port_drayage_plugin::PortDrayagePlugin::outbound_mobility_operations_publisher_ private
Definition at line 55 of file port_drayage_plugin.hpp.
Referenced by handle_on_configure(), and publishMobilityOperation().
pdw_
PortDrayageWorker port_drayage_plugin::PortDrayagePlugin::pdw_ private
Definition at line 65 of file port_drayage_plugin.hpp.
Referenced by handle_on_configure(), and parameter_update_callback().
pose_subscriber_
carma_ros2_utils::SubPtr<geometry_msgs::msg::PoseStamped> port_drayage_plugin::PortDrayagePlugin::pose_subscriber_ private
Definition at line 48 of file port_drayage_plugin.hpp.
Referenced by handle_on_configure().
route_event_subscriber_
carma_ros2_utils::SubPtr<carma_planning_msgs::msg::RouteEvent> port_drayage_plugin::PortDrayagePlugin::route_event_subscriber_ private
Definition at line 51 of file port_drayage_plugin.hpp.
Referenced by handle_on_configure().
set_active_route_client_
carma_ros2_utils::ClientPtr<carma_planning_msgs::srv::SetActiveRoute> port_drayage_plugin::PortDrayagePlugin::set_active_route_client_ private
Definition at line 59 of file port_drayage_plugin.hpp.
Referenced by callSetActiveRouteClient(), and handle_on_configure().
ui_instructions_publisher_
carma_ros2_utils::PubPtr<carma_msgs::msg::UIInstructions> port_drayage_plugin::PortDrayagePlugin::ui_instructions_publisher_ private
Definition at line 56 of file port_drayage_plugin.hpp.
Referenced by handle_on_configure(), and publishUIInstructions().
The documentation for this class was generated from the following files:
port_drayage_plugin/include/port_drayage_plugin/port_drayage_plugin.hpp
port_drayage_plugin/src/port_drayage_plugin.cpp