Carma-platform: mock_drivers::MockDriverNode Class Reference
mock_drivers::MockDriverNode Class Reference
Node class which connects to the ROS network.
#include <MockDriverNode.h>
Public Member Functions
std::string getGraphName () const
Returns the fully qualified name of this node in the ROS network graph.
template<typename T >
void addPub (T comm)
Function to add a publisher from a ROSComms object.
template<typename T >
void addSub (T comm)
Function to add a subscriber from a ROSComms object.
template<typename T >
void addSrv (T comm)
Function to add a service from a ROSComms object.
void spin (double rate) const
Begin the ros node.
void setSpinCallback (std::function< bool()> cb) const
Set the spin callback for the ros node.
void init ()
Initialize the CARMA Node Handle pointer for the MockDriverNode (must be called before spin)
template<typename T >
void publishData (std::string topic, T msg)
Publish data on a desired topic.
template<typename T >
void publishDataNoHeader (std::string topic, T msg)
Publish data with no header on a desired topic.
MockDriverNode ()
MockDriverNode (bool dummy)
std::vector< std::string > getTopics ()
Returns a vector of all the topics that the node would publish to (only when it is a dummy node). Used for testing.
std::vector< ros::Time > getTimeStamps ()
Returns a vector of all the time stamps of the data that would be published (only when it is a dummy node). Used for testing.
bool isDummy ()
Returns if the node is a dummy node. Used for testing.
Private Attributes
boost::shared_ptr< ros::CARMANodeHandle > cnh_
std::vector< PublisherWapper > publishers_
std::vector< ros::Subscriber > subscribers_
std::vector< ros::ServiceServer > services_
bool dummy_ = false
std::vector< std::string > topics_
std::vector< ros::Time > time_stamps_
Detailed Description
Node class which connects to the ROS network.
Definition at line 34 of file MockDriverNode.h.
Constructor & Destructor Documentation
MockDriverNode() [1/2]
mock_drivers::MockDriverNode::MockDriverNode ()
Definition at line 21 of file MockDriverNode.cpp.
{
}
MockDriverNode() [2/2]
mock_drivers::MockDriverNode::MockDriverNode (bool dummy)
Definition at line 24 of file MockDriverNode.cpp.
                                         : dummy_(dummy)
{
}
Member Function Documentation
addPub()
template<typename T > void mock_drivers::MockDriverNode::addPub (T comm) inline
Function to add a publisher from a ROSComms object.
Definition at line 59 of file MockDriverNode.h.
  {
    if (!dummy_)
    {
      PublisherWapper pub;
      pub.pub = cnh_->advertise<decltype(comm->getTemplateType())>(comm->getTopic(), comm->getQueueSize());
      pub.base_topic_name = comm->getTopic();
      publishers_.push_back(pub);
    }
  }
References cnh_, dummy_, pub, and publishers_.
Referenced by mock_drivers::MockControllerDriver::onRun(), and mock_drivers::MockDriver::run().
addSrv()
template<typename T > void mock_drivers::MockDriverNode::addSrv (T comm) inline
Function to add a service from a ROSComms object.
Definition at line 83 of file MockDriverNode.h.
  {
    if (!dummy_)
    {
      services_.push_back(cnh_->advertiseService(
          comm->getTopic(), &ROSComms<decltype(comm->getReqType()), decltype(comm->getResType())>::callback, comm));
    }
  }
References callback(), cnh_, dummy_, and services_.
Referenced by mock_drivers::MockControllerDriver::onRun().
addSub()
template<typename T > void mock_drivers::MockDriverNode::addSub (T comm) inline
Function to add a subscriber from a ROSComms object.
Definition at line 72 of file MockDriverNode.h.
  {
    if (!dummy_)
    {
      subscribers_.push_back(cnh_->subscribe<decltype(comm->getTemplateType())>(
          comm->getTopic(), comm->getQueueSize(), &ROSComms<decltype(comm->getTemplateType())>::callback, comm));
    }
  }
References callback(), cnh_, dummy_, and subscribers_.
Referenced by mock_drivers::MockCommsDriver::onRun(), and mock_drivers::MockControllerDriver::onRun().
getGraphName()
std::string mock_drivers::MockDriverNode::getGraphName () const
Returns the fully qualified name of this node in the ROS network graph.
Returns
The fully specified name
Definition at line 28 of file MockDriverNode.cpp.
{
  if (dummy_)
  {
    return "dummy_mock_driver";
  }
  return ros::this_node::getName();
}
References dummy_.
Referenced by mock_drivers::MockDriver::driverDiscovery().
getTimeStamps()
std::vector< ros::Time > mock_drivers::MockDriverNode::getTimeStamps () inline
Returns a vector of all the time stamps of the data that would be published (only when it is a dummy node). Used for testing.
Definition at line 159 of file MockDriverNode.h.
  {
    return time_stamps_;
  }
References time_stamps_.
getTopics()
std::vector< std::string > mock_drivers::MockDriverNode::getTopics () inline
Returns a vector of all the topics that the node would publish to (only when it is a dummy node). Used for testing.
Definition at line 153 of file MockDriverNode.h.
  {
    return topics_;
  }
References topics_.
init()
void mock_drivers::MockDriverNode::init ()
Initialize the CARMA Node Handle pointer for the MockDriverNode (must be called before spin)
Definition at line 56 of file MockDriverNode.cpp.
{
  if (!dummy_)
  {
    cnh_ = boost::make_shared<ros::CARMANodeHandle>(ros::CARMANodeHandle());
  }
}
References cnh_, and dummy_.
Referenced by mock_drivers::MockDriver::run().
isDummy()
bool mock_drivers::MockDriverNode::isDummy () inline
Returns if the node is a dummy node. Used for testing.
Definition at line 164 of file MockDriverNode.h.
  {
    return dummy_;
  }
References dummy_.
publishData()
template<typename T > void mock_drivers::MockDriverNode::publishData (std::string topic, T msg) inline
Publish data on a desired topic.
This function must take in the full name of topic that will be published including the namespaces and leading /. This can probably be made to take that information in on construction of the node but we can add that once it breaks :)
Definition at line 108 of file MockDriverNode.h.
  {
    if (!dummy_)
    {
      auto pub = std::find_if(publishers_.begin(), publishers_.end(),
                              [&](PublisherWapper p) { return p.base_topic_name == topic; });
      if (pub == publishers_.end())
        throw std::invalid_argument("Attempted to publish to topic " + topic + " but no publisher was found");
      pub->pub.publish(msg);
    }
    else
    {
      topics_.push_back(topic);
      time_stamps_.push_back(msg.header.stamp);
    }
  };
References dummy_, pub, publishers_, time_stamps_, and topics_.
publishDataNoHeader()
template<typename T > void mock_drivers::MockDriverNode::publishDataNoHeader (std::string topic, T msg) inline
Publish data with no header on a desired topic.
Same as the publishData function, except this is used when the data doesn't have a header. This exists to allow for testing of the code. This can be combined with publishData once we are in c++ 17 and can use constexpr if statement.
Definition at line 132 of file MockDriverNode.h.
  {
    if (!dummy_)
    {
      auto pub = std::find_if(publishers_.begin(), publishers_.end(),
                              [&](PublisherWapper p) { return p.base_topic_name == topic; });
      if (pub == publishers_.end())
        throw std::invalid_argument("Attempted to publish to topic " + topic + " but no publisher was found");
      pub->pub.publish(msg);
    }
    else
    {
      topics_.push_back(topic);
    }
  };
References dummy_, pub, publishers_, and topics_.
Referenced by mock_drivers::MockDriver::driverDiscovery(), and mock_drivers::MockControllerDriver::onSpin().
setSpinCallback()
void mock_drivers::MockDriverNode::setSpinCallback (std::function< bool()> cb) const
Set the spin callback for the ros node.
Definition at line 47 of file MockDriverNode.cpp.
{
  if (!dummy_)
  {
    ros::CARMANodeHandle::setSpinRate(10.0); // Set spin to avoid exception until spin is called and this value updated
    ros::CARMANodeHandle::setSpinCallback(cb);
  }
}
References dummy_.
Referenced by mock_drivers::MockDriver::run().
spin()
void mock_drivers::MockDriverNode::spin (double rate) const
Begin the ros node.
Definition at line 38 of file MockDriverNode.cpp.
{
  if (!dummy_)
  {
    ros::CARMANodeHandle::setSpinRate(rate);
    ros::CARMANodeHandle::spin();
  }
}
References dummy_.
Referenced by mock_drivers::MockDriver::run().
Member Data Documentation
cnh_
boost::shared_ptr<ros::CARMANodeHandle> mock_drivers::MockDriverNode::cnh_ private
Definition at line 37 of file MockDriverNode.h.
Referenced by addPub(), addSrv(), addSub(), and init().
dummy_
bool mock_drivers::MockDriverNode::dummy_ = false private
Definition at line 43 of file MockDriverNode.h.
Referenced by addPub(), addSrv(), addSub(), getGraphName(), init(), isDummy(), publishData(), publishDataNoHeader(), setSpinCallback(), and spin().
publishers_
std::vector<PublisherWapper> mock_drivers::MockDriverNode::publishers_ private
Definition at line 38 of file MockDriverNode.h.
Referenced by addPub(), publishData(), and publishDataNoHeader().
services_
std::vector<ros::ServiceServer> mock_drivers::MockDriverNode::services_ private
Definition at line 40 of file MockDriverNode.h.
Referenced by addSrv().
subscribers_
std::vector<ros::Subscriber> mock_drivers::MockDriverNode::subscribers_ private
Definition at line 39 of file MockDriverNode.h.
Referenced by addSub().
time_stamps_
std::vector<ros::Time> mock_drivers::MockDriverNode::time_stamps_ private
Definition at line 46 of file MockDriverNode.h.
Referenced by getTimeStamps(), and publishData().
topics_
std::vector<std::string> mock_drivers::MockDriverNode::topics_ private
Definition at line 45 of file MockDriverNode.h.
Referenced by getTopics(), publishData(), and publishDataNoHeader().
The documentation for this class was generated from the following files:
mock_drivers/rosbag_mock_drivers/include/rosbag_mock_drivers/MockDriverNode.h
mock_drivers/rosbag_mock_drivers/src/MockDriverNode.cpp