Carma-platform: roadway_objects::RoadwayObjectsNode Class Reference
roadway_objects::RoadwayObjectsNode Class Reference
The class responsible for converting detected objects into objects that are mapped onto specific lanelets.
#include <roadway_objects_node.hpp>
Public Member Functions
RoadwayObjectsNode (const rclcpp::NodeOptions &)
Node constructor.
void publishObstacles (const carma_perception_msgs::msg::RoadwayObstacleList &msg)
Callback to publish RoadwayObstacleList.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &)
Private Attributes
carma_ros2_utils::SubPtr< carma_perception_msgs::msg::ExternalObjectList > external_objects_sub_
carma_ros2_utils::PubPtr< carma_perception_msgs::msg::RoadwayObstacleList > roadway_obs_pub_
std::shared_ptr< carma_wm::WMListener > wm_listener_
std::shared_ptr< RoadwayObjectsWorker > object_worker_
Detailed Description
The class responsible for converting detected objects into objects that are mapped onto specific lanelets.
Definition at line 38 of file roadway_objects_node.hpp.
Constructor & Destructor Documentation
RoadwayObjectsNode()
roadway_objects::RoadwayObjectsNode::RoadwayObjectsNode (const rclcpp::NodeOptions & options) explicit
Node constructor.
Definition at line 22 of file roadway_objects_node.cpp.
      : carma_ros2_utils::CarmaLifecycleNode(options)
  {
  }
Member Function Documentation
handle_on_configure()
carma_ros2_utils::CallbackReturn roadway_objects::RoadwayObjectsNode::handle_on_configure (const rclcpp_lifecycle::State &)
Definition at line 27 of file roadway_objects_node.cpp.
  {
    RCLCPP_INFO_STREAM(get_logger(), "RoadwayObjectsNode trying to configure");
    wm_listener_ = std::make_shared<carma_wm::WMListener>(get_node_base_interface(), get_node_logging_interface(),
                    get_node_topics_interface(), get_node_parameters_interface());
    object_worker_ = std::make_shared<RoadwayObjectsWorker>(wm_listener_->getWorldModel(), std::bind(&RoadwayObjectsNode::publishObstacles, this, std_ph::_1), get_node_logging_interface());
    // Setup publishers
    roadway_obs_pub_ = create_publisher<carma_perception_msgs::msg::RoadwayObstacleList>("roadway_objects", 10);
    // Setup subscribers
    external_objects_sub_ = create_subscription<carma_perception_msgs::msg::ExternalObjectList>("external_objects", 10,
                                                              std::bind(&RoadwayObjectsWorker::externalObjectsCallback, object_worker_.get(), std_ph::_1));
    // Return success if everthing initialized successfully
    return CallbackReturn::SUCCESS;
  }
References external_objects_sub_, roadway_objects::RoadwayObjectsWorker::externalObjectsCallback(), object_worker_, publishObstacles(), roadway_obs_pub_, and wm_listener_.
publishObstacles()
void roadway_objects::RoadwayObjectsNode::publishObstacles (const carma_perception_msgs::msg::RoadwayObstacleList & msg)
Callback to publish RoadwayObstacleList.
Definition at line 47 of file roadway_objects_node.cpp.
  {
    roadway_obs_pub_->publish(msg);
  }
References roadway_obs_pub_.
Referenced by handle_on_configure().
Member Data Documentation
external_objects_sub_
carma_ros2_utils::SubPtr<carma_perception_msgs::msg::ExternalObjectList> roadway_objects::RoadwayObjectsNode::external_objects_sub_ private
Definition at line 44 of file roadway_objects_node.hpp.
Referenced by handle_on_configure().
object_worker_
std::shared_ptr<RoadwayObjectsWorker> roadway_objects::RoadwayObjectsNode::object_worker_ private
Definition at line 53 of file roadway_objects_node.hpp.
Referenced by handle_on_configure().
roadway_obs_pub_
carma_ros2_utils::PubPtr<carma_perception_msgs::msg::RoadwayObstacleList> roadway_objects::RoadwayObjectsNode::roadway_obs_pub_ private
Definition at line 47 of file roadway_objects_node.hpp.
Referenced by handle_on_configure(), and publishObstacles().
wm_listener_
std::shared_ptr<carma_wm::WMListener> roadway_objects::RoadwayObjectsNode::wm_listener_ private
Definition at line 50 of file roadway_objects_node.hpp.
Referenced by handle_on_configure().
The documentation for this class was generated from the following files:
roadway_objects/include/roadway_objects/roadway_objects_node.hpp
roadway_objects/src/roadway_objects_node.cpp