Carma-platform: bsm_generator::BSMGenerator Class Reference
bsm_generator::BSMGenerator Class Reference
The class responsible for publishing BSM messages.
#include <bsm_generator_node.hpp>
Public Member Functions
BSMGenerator (const rclcpp::NodeOptions &)
BSMGenerator constructor.
rcl_interfaces::msg::SetParametersResult parameter_update_callback (const std::vector< rclcpp::Parameter > &parameters)
Function callback for dynamic parameter updates.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &)
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &)
Private Member Functions
void initializeBSM ()
Function to fill the BSM message with initial default data.
void poseCallback (const geometry_msgs::msg::PoseStamped::UniquePtr msg)
Callback to populate BSM message with longitude, latitude, and elevation data.
void accelCallback (const automotive_platform_msgs::msg::VelocityAccelCov::UniquePtr msg)
Callback to populate BSM message with longitudinal acceleration data.
void yawCallback (const sensor_msgs::msg::Imu::UniquePtr msg)
Callback to populate BSM message with yaw rate data.
void gearCallback (const j2735_v2x_msgs::msg::TransmissionState::UniquePtr msg)
Callback to populate BSM message with transmission state data.
void speedCallback (const geometry_msgs::msg::TwistStamped::UniquePtr msg)
Callback to populate BSM message with vehicle speed data.
void steerWheelAngleCallback (const std_msgs::msg::Float64::UniquePtr msg)
Callback to populate BSM message with vehicle steering wheel angle data.
void brakeCallback (const std_msgs::msg::Float64::UniquePtr msg)
Callback to populate BSM message with vehicle applied brake status.
void headingCallback (const gps_msgs::msg::GPSFix::UniquePtr msg)
Callback to populate BSM message with vehicle heading data.
void georeferenceCallback (const std_msgs::msg::String::UniquePtr msg)
Callback for map projection string to define lat/lon -> map conversion.
void generateBSM ()
Timer callback, which publishes a BSM.
Private Attributes
carma_ros2_utils::SubPtr< geometry_msgs::msg::PoseStamped > pose_sub_
carma_ros2_utils::SubPtr< automotive_platform_msgs::msg::VelocityAccelCov > accel_sub_
carma_ros2_utils::SubPtr< sensor_msgs::msg::Imu > yaw_sub_
carma_ros2_utils::SubPtr< j2735_v2x_msgs::msg::TransmissionState > gear_sub_
carma_ros2_utils::SubPtr< geometry_msgs::msg::TwistStamped > speed_sub_
carma_ros2_utils::SubPtr< std_msgs::msg::Float64 > steer_wheel_angle_sub_
carma_ros2_utils::SubPtr< std_msgs::msg::Float64 > brake_sub_
carma_ros2_utils::SubPtr< gps_msgs::msg::GPSFix > heading_sub_
carma_ros2_utils::SubPtr< std_msgs::msg::String > georeference_sub_
carma_ros2_utils::PubPtr< carma_v2x_msgs::msg::BSM > bsm_pub_
rclcpp::TimerBase::SharedPtr timer_
Config config_
std::shared_ptr< BSMGeneratorWorker > worker
carma_v2x_msgs::msg::BSM bsm_
std::string georeference_ {""}
std::shared_ptr< lanelet::projection::LocalFrameProjector > map_projector_
std::vector< uint8_t > bsm_message_id_
Detailed Description
The class responsible for publishing BSM messages.
Definition at line 45 of file bsm_generator_node.hpp.
Constructor & Destructor Documentation
BSMGenerator()
bsm_generator::BSMGenerator::BSMGenerator (const rclcpp::NodeOptions & options) explicit
BSMGenerator constructor.
Definition at line 22 of file bsm_generator_node.cpp.
      : carma_ros2_utils::CarmaLifecycleNode(options)
  {
    // Create initial config
    config_ = Config();
    // Declare parameters
    config_.bsm_generation_frequency = declare_parameter<double>("bsm_generation_frequency", config_.bsm_generation_frequency);
    config_.bsm_id_change_period = declare_parameter<double>("bsm_id_change_period", config_.bsm_id_change_period);
    config_.bsm_id_rotation_enabled  = declare_parameter<bool>("bsm_id_rotation_enabled", config_.bsm_id_rotation_enabled);
    config_.bsm_message_id           = declare_parameter<int>("bsm_message_id", config_.bsm_message_id);
    config_.vehicle_length           = declare_parameter<double>("vehicle_length", config_.vehicle_length);
    config_.vehicle_width            = declare_parameter<double>("vehicle_width", config_.vehicle_width);
  }
References bsm_generator::Config::bsm_generation_frequency, bsm_generator::Config::bsm_id_change_period, bsm_generator::Config::bsm_id_rotation_enabled, bsm_generator::Config::bsm_message_id, config_, bsm_generator::Config::vehicle_length, and bsm_generator::Config::vehicle_width.
Member Function Documentation
accelCallback()
void bsm_generator::BSMGenerator::accelCallback (const automotive_platform_msgs::msg::VelocityAccelCov::UniquePtr msg) private
Callback to populate BSM message with longitudinal acceleration data.
Parameters
msg Latest acceleration message
Definition at line 154 of file bsm_generator_node.cpp.
  {
    bsm_.core_data.accel_set.longitudinal = worker->getLongAccelInRange(msg->accleration);
    bsm_.core_data.accel_set.presence_vector = bsm_.core_data.accel_set.presence_vector | bsm_.core_data.accel_set.ACCELERATION_AVAILABLE;
  }
References bsm_, and worker.
Referenced by handle_on_configure().
brakeCallback()
void bsm_generator::BSMGenerator::brakeCallback (const std_msgs::msg::Float64::UniquePtr msg) private
Callback to populate BSM message with vehicle applied brake status.
Parameters
msg Latest brake status message
Definition at line 166 of file bsm_generator_node.cpp.
  {
    bsm_.core_data.brakes.wheel_brakes.brake_applied_status = worker->getBrakeAppliedStatus(msg->data);
  }
References bsm_, and worker.
Referenced by handle_on_configure().
gearCallback()
void bsm_generator::BSMGenerator::gearCallback (const j2735_v2x_msgs::msg::TransmissionState::UniquePtr msg) private
Callback to populate BSM message with transmission state data.
Parameters
msg Latest transmissio state message
Definition at line 143 of file bsm_generator_node.cpp.
  {
    bsm_.core_data.transmission.transmission_state = msg->transmission_state;
  }
References bsm_.
Referenced by handle_on_configure().
generateBSM()
void bsm_generator::BSMGenerator::generateBSM () private
Timer callback, which publishes a BSM.
Definition at line 195 of file bsm_generator_node.cpp.
  {
    bsm_.header.stamp = this->now();
    bsm_.core_data.msg_count = worker->getNextMsgCount();
    if (config_.bsm_id_rotation_enabled)
      bsm_.core_data.id = worker->getMsgId( this->now(), config_.bsm_id_change_period);
    else
    {
      std::vector<uint8_t> id(4);
      for(int i = 0; i < id.size(); ++i)
      {
        id[i] = config_.bsm_message_id >> (8 * i);
      }
      bsm_.core_data.id = id;
    }
    bsm_.core_data.sec_mark = worker->getSecMark( this->now() );
    bsm_.core_data.presence_vector = bsm_.core_data.presence_vector | bsm_.core_data.SEC_MARK_AVAILABLE;
    // currently the accuracy is not available because ndt_matching does not provide accuracy measurement
    bsm_.core_data.accuracy.presence_vector = 0;
    bsm_pub_->publish(bsm_);
  }
References bsm_, bsm_generator::Config::bsm_id_change_period, bsm_generator::Config::bsm_id_rotation_enabled, bsm_generator::Config::bsm_message_id, bsm_pub_, config_, process_bag::i, and worker.
Referenced by handle_on_activate().
georeferenceCallback()
void bsm_generator::BSMGenerator::georeferenceCallback (const std_msgs::msg::String::UniquePtr msg) private
Callback for map projection string to define lat/lon -> map conversion.
Parameters
msg The proj string defining the projection.
Definition at line 127 of file bsm_generator_node.cpp.
  {
    // Build projector from proj string
    if (georeference_ != msg->data)
    {
      georeference_ = msg->data;
      map_projector_ = std::make_shared<lanelet::projection::LocalFrameProjector>(msg->data.c_str());
    }
  }
References georeference_, and map_projector_.
Referenced by handle_on_configure().
handle_on_activate()
carma_ros2_utils::CallbackReturn bsm_generator::BSMGenerator::handle_on_activate (const rclcpp_lifecycle::State & prev_state)
Definition at line 107 of file bsm_generator_node.cpp.
  {
    // Timer setup for generating a BSM
    int bsm_generation_period_ms = (1 / config_.bsm_generation_frequency) * 1000; // Conversion from frequency (Hz) to milliseconds time period
    timer_ = create_timer(get_clock(),
                          std::chrono::milliseconds(bsm_generation_period_ms),
                          std::bind(&BSMGenerator::generateBSM, this));
    return CallbackReturn::SUCCESS;
  }
References bsm_generator::Config::bsm_generation_frequency, config_, generateBSM(), and timer_.
handle_on_configure()
carma_ros2_utils::CallbackReturn bsm_generator::BSMGenerator::handle_on_configure (const rclcpp_lifecycle::State &)
Definition at line 55 of file bsm_generator_node.cpp.
  {
    RCLCPP_INFO_STREAM(get_logger(), "BSMGenerator trying to configure");
    // Reset config
    config_ = Config();
    // Load parameters
    get_parameter<double>("bsm_generation_frequency", config_.bsm_generation_frequency);
    get_parameter<double>("bsm_id_change_period", config_.bsm_id_change_period);
    get_parameter<bool>("bsm_id_rotation_enabled", config_.bsm_id_rotation_enabled);
    get_parameter<int>("bsm_message_id", config_.bsm_message_id);
    get_parameter<double>("vehicle_length", config_.vehicle_length);
    get_parameter<double>("vehicle_width", config_.vehicle_width);
    RCLCPP_INFO_STREAM(get_logger(), "Loaded params: " << config_);
    // Register runtime parameter update callback
    add_on_set_parameters_callback(std::bind(&BSMGenerator::parameter_update_callback, this, std_ph::_1));
    // Setup subscribers
    pose_sub_ = create_subscription<geometry_msgs::msg::PoseStamped>("pose", 1,
                                                              std::bind(&BSMGenerator::poseCallback, this, std_ph::_1));
    accel_sub_ = create_subscription<automotive_platform_msgs::msg::VelocityAccelCov>("velocity_accel_cov", 1,
                                                              std::bind(&BSMGenerator::accelCallback, this, std_ph::_1));
    yaw_sub_ = create_subscription<sensor_msgs::msg::Imu>("imu_raw", 1,
                                                              std::bind(&BSMGenerator::yawCallback, this, std_ph::_1));
    gear_sub_ = create_subscription<j2735_v2x_msgs::msg::TransmissionState>("transmission_state", 1,
                                                              std::bind(&BSMGenerator::gearCallback, this, std_ph::_1));
    speed_sub_ = create_subscription<geometry_msgs::msg::TwistStamped>("ekf_twist", 1,
                                                              std::bind(&BSMGenerator::speedCallback, this, std_ph::_1));
    steer_wheel_angle_sub_ = create_subscription<std_msgs::msg::Float64>("steering_wheel_angle", 1,
                                                              std::bind(&BSMGenerator::steerWheelAngleCallback, this, std_ph::_1));
    brake_sub_ = create_subscription<std_msgs::msg::Float64>("brake_position", 1,
                                                              std::bind(&BSMGenerator::brakeCallback, this, std_ph::_1));
    heading_sub_ = create_subscription<gps_msgs::msg::GPSFix>("gnss_fix_fused", 1,
                                                              std::bind(&BSMGenerator::headingCallback, this, std_ph::_1));
    georeference_sub_ = create_subscription<std_msgs::msg::String>("georeference", 1,
                                                              std::bind(&BSMGenerator::georeferenceCallback, this, std_ph::_1));
    // Setup publishers
    bsm_pub_ = create_publisher<carma_v2x_msgs::msg::BSM>("bsm_outbound", 5);
    // Initialize the generated BSM message
    initializeBSM();
    worker = std::make_shared<BSMGeneratorWorker>();
    // Return success if everthing initialized successfully
    return CallbackReturn::SUCCESS;
  }
References accel_sub_, accelCallback(), brake_sub_, brakeCallback(), bsm_generator::Config::bsm_generation_frequency, bsm_generator::Config::bsm_id_change_period, bsm_generator::Config::bsm_id_rotation_enabled, bsm_generator::Config::bsm_message_id, bsm_pub_, config_, gear_sub_, gearCallback(), georeference_sub_, georeferenceCallback(), heading_sub_, headingCallback(), initializeBSM(), parameter_update_callback(), pose_sub_, poseCallback(), speed_sub_, speedCallback(), steer_wheel_angle_sub_, steerWheelAngleCallback(), bsm_generator::Config::vehicle_length, bsm_generator::Config::vehicle_width, worker, yaw_sub_, and yawCallback().
headingCallback()
void bsm_generator::BSMGenerator::headingCallback (const gps_msgs::msg::GPSFix::UniquePtr msg) private
Callback to populate BSM message with vehicle heading data.
Parameters
msg Latest GNSS message
Definition at line 189 of file bsm_generator_node.cpp.
  {
    bsm_.core_data.heading = worker->getHeadingInRange(static_cast<float>(msg->track));
    bsm_.core_data.presence_vector = bsm_.core_data.presence_vector | bsm_.core_data.HEADING_AVAILABLE;
  }
References bsm_, and worker.
Referenced by handle_on_configure().
initializeBSM()
void bsm_generator::BSMGenerator::initializeBSM () private
Function to fill the BSM message with initial default data.
Definition at line 118 of file bsm_generator_node.cpp.
  {
    bsm_.core_data.presence_vector = 0;
    bsm_.core_data.size.vehicle_width = config_.vehicle_width;
    bsm_.core_data.size.vehicle_length = config_.vehicle_length;
    bsm_.core_data.size.presence_vector = bsm_.core_data.size.presence_vector | bsm_.core_data.size.VEHICLE_LENGTH_AVAILABLE;
    bsm_.core_data.size.presence_vector = bsm_.core_data.size.presence_vector | bsm_.core_data.size.VEHICLE_WIDTH_AVAILABLE;
  }
References bsm_, config_, bsm_generator::Config::vehicle_length, and bsm_generator::Config::vehicle_width.
Referenced by handle_on_configure().
parameter_update_callback()
rcl_interfaces::msg::SetParametersResult bsm_generator::BSMGenerator::parameter_update_callback (const std::vector< rclcpp::Parameter > & parameters)
Function callback for dynamic parameter updates.
Definition at line 37 of file bsm_generator_node.cpp.
  {
    auto error = update_params<bool>({{"bsm_id_rotation_enabled", config_.bsm_id_rotation_enabled}}, parameters);
    auto error_2 = update_params<int>({{"bsm_message_id", config_.bsm_message_id}}, parameters);
    auto error_3 = update_params<double>({
        {"bsm_generation_frequency", config_.bsm_generation_frequency},
        {"bsm_id_change_period", config_.bsm_id_change_period},
        {"vehicle_length", config_.vehicle_length},
        {"vehicle_width", config_.vehicle_width}
    }, parameters);
    rcl_interfaces::msg::SetParametersResult result;
    result.successful = !error && !error_2 && !error_3;
    return result;
  }
References bsm_generator::Config::bsm_generation_frequency, bsm_generator::Config::bsm_id_change_period, bsm_generator::Config::bsm_id_rotation_enabled, bsm_generator::Config::bsm_message_id, config_, bsm_generator::Config::vehicle_length, and bsm_generator::Config::vehicle_width.
Referenced by handle_on_configure().
poseCallback()
void bsm_generator::BSMGenerator::poseCallback (const geometry_msgs::msg::PoseStamped::UniquePtr msg) private
Callback to populate BSM message with longitude, latitude, and elevation data.
Parameters
msg Latest pose message
Definition at line 171 of file bsm_generator_node.cpp.
  {
    // Use pose message as an indicator of new location updates
    if (!map_projector_) {
        RCLCPP_DEBUG_STREAM(get_logger(), "Ignoring pose message as projection string has not been defined");
        return;
    }
    lanelet::GPSPoint coord = map_projector_->reverse( { msg->pose.position.x, msg->pose.position.y, msg->pose.position.z } );
    bsm_.core_data.longitude = coord.lon;
    bsm_.core_data.latitude = coord.lat;
    bsm_.core_data.elev = coord.ele;
    bsm_.core_data.presence_vector = bsm_.core_data.presence_vector | bsm_.core_data.LONGITUDE_AVAILABLE;
    bsm_.core_data.presence_vector = bsm_.core_data.presence_vector | bsm_.core_data.LATITUDE_AVAILABLE;
    bsm_.core_data.presence_vector = bsm_.core_data.presence_vector | bsm_.core_data.ELEVATION_AVAILABLE;
  }
References bsm_, and map_projector_.
Referenced by handle_on_configure().
speedCallback()
void bsm_generator::BSMGenerator::speedCallback (const geometry_msgs::msg::TwistStamped::UniquePtr msg) private
Callback to populate BSM message with vehicle speed data.
Parameters
msg Latest speed message
Definition at line 137 of file bsm_generator_node.cpp.
  {
    bsm_.core_data.speed = worker->getSpeedInRange(msg->twist.linear.x);
    bsm_.core_data.presence_vector = bsm_.core_data.presence_vector | bsm_.core_data.SPEED_AVAILABLE;
  }
References bsm_, and worker.
Referenced by handle_on_configure().
steerWheelAngleCallback()
void bsm_generator::BSMGenerator::steerWheelAngleCallback (const std_msgs::msg::Float64::UniquePtr msg) private
Callback to populate BSM message with vehicle steering wheel angle data.
Parameters
msg Latest steering wheel angle message
Definition at line 148 of file bsm_generator_node.cpp.
  {
    bsm_.core_data.angle = worker->getSteerWheelAngleInRange(msg->data);
    bsm_.core_data.presence_vector = bsm_.core_data.presence_vector | bsm_.core_data.STEER_WHEEL_ANGLE_AVAILABLE;
  }
References bsm_, and worker.
Referenced by handle_on_configure().
yawCallback()
void bsm_generator::BSMGenerator::yawCallback (const sensor_msgs::msg::Imu::UniquePtr msg) private
Callback to populate BSM message with yaw rate data.
Parameters
msg Latest IMU message
Definition at line 160 of file bsm_generator_node.cpp.
  {
    bsm_.core_data.accel_set.yaw_rate = worker->getYawRateInRange(static_cast<float>(msg->angular_velocity.z));
    bsm_.core_data.accel_set.presence_vector = bsm_.core_data.accel_set.presence_vector | bsm_.core_data.accel_set.YAWRATE_AVAILABLE;
  }
References bsm_, and worker.
Referenced by handle_on_configure().
Member Data Documentation
accel_sub_
carma_ros2_utils::SubPtr<automotive_platform_msgs::msg::VelocityAccelCov> bsm_generator::BSMGenerator::accel_sub_ private
Definition at line 51 of file bsm_generator_node.hpp.
Referenced by handle_on_configure().
brake_sub_
carma_ros2_utils::SubPtr<std_msgs::msg::Float64> bsm_generator::BSMGenerator::brake_sub_ private
Definition at line 56 of file bsm_generator_node.hpp.
Referenced by handle_on_configure().
bsm_
carma_v2x_msgs::msg::BSM bsm_generator::BSMGenerator::bsm_ private
Definition at line 73 of file bsm_generator_node.hpp.
Referenced by accelCallback(), brakeCallback(), gearCallback(), generateBSM(), headingCallback(), initializeBSM(), poseCallback(), speedCallback(), steerWheelAngleCallback(), and yawCallback().
bsm_message_id_
std::vector<uint8_t> bsm_generator::BSMGenerator::bsm_message_id_ private
Definition at line 78 of file bsm_generator_node.hpp.
bsm_pub_
carma_ros2_utils::PubPtr<carma_v2x_msgs::msg::BSM> bsm_generator::BSMGenerator::bsm_pub_ private
Definition at line 61 of file bsm_generator_node.hpp.
Referenced by generateBSM(), and handle_on_configure().
config_
Config bsm_generator::BSMGenerator::config_ private
Definition at line 67 of file bsm_generator_node.hpp.
Referenced by BSMGenerator(), generateBSM(), handle_on_activate(), handle_on_configure(), initializeBSM(), and parameter_update_callback().
gear_sub_
carma_ros2_utils::SubPtr<j2735_v2x_msgs::msg::TransmissionState> bsm_generator::BSMGenerator::gear_sub_ private
Definition at line 53 of file bsm_generator_node.hpp.
Referenced by handle_on_configure().
georeference_
std::string bsm_generator::BSMGenerator::georeference_ {""} private
Definition at line 75 of file bsm_generator_node.hpp.
Referenced by georeferenceCallback().
georeference_sub_
carma_ros2_utils::SubPtr<std_msgs::msg::String> bsm_generator::BSMGenerator::georeference_sub_ private
Definition at line 58 of file bsm_generator_node.hpp.
Referenced by handle_on_configure().
heading_sub_
carma_ros2_utils::SubPtr<gps_msgs::msg::GPSFix> bsm_generator::BSMGenerator::heading_sub_ private
Definition at line 57 of file bsm_generator_node.hpp.
Referenced by handle_on_configure().
map_projector_
std::shared_ptr<lanelet::projection::LocalFrameProjector> bsm_generator::BSMGenerator::map_projector_ private
Definition at line 76 of file bsm_generator_node.hpp.
Referenced by georeferenceCallback(), and poseCallback().
pose_sub_
carma_ros2_utils::SubPtr<geometry_msgs::msg::PoseStamped> bsm_generator::BSMGenerator::pose_sub_ private
Definition at line 50 of file bsm_generator_node.hpp.
Referenced by handle_on_configure().
speed_sub_
carma_ros2_utils::SubPtr<geometry_msgs::msg::TwistStamped> bsm_generator::BSMGenerator::speed_sub_ private
Definition at line 54 of file bsm_generator_node.hpp.
Referenced by handle_on_configure().
steer_wheel_angle_sub_
carma_ros2_utils::SubPtr<std_msgs::msg::Float64> bsm_generator::BSMGenerator::steer_wheel_angle_sub_ private
Definition at line 55 of file bsm_generator_node.hpp.
Referenced by handle_on_configure().
timer_
rclcpp::TimerBase::SharedPtr bsm_generator::BSMGenerator::timer_ private
Definition at line 64 of file bsm_generator_node.hpp.
Referenced by handle_on_activate().
worker
std::shared_ptr<BSMGeneratorWorker> bsm_generator::BSMGenerator::worker private
Definition at line 70 of file bsm_generator_node.hpp.
Referenced by accelCallback(), brakeCallback(), generateBSM(), handle_on_configure(), headingCallback(), speedCallback(), steerWheelAngleCallback(), and yawCallback().
yaw_sub_
carma_ros2_utils::SubPtr<sensor_msgs::msg::Imu> bsm_generator::BSMGenerator::yaw_sub_ private
Definition at line 52 of file bsm_generator_node.hpp.
Referenced by handle_on_configure().
The documentation for this class was generated from the following files:
bsm_generator/include/bsm_generator/bsm_generator_node.hpp
bsm_generator/src/bsm_generator_node.cpp