Carma-platform: pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject > Class Template Reference
pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject > Class Template Reference
Filter point clouds and indices based on a function object passed in the ctor.
#include <functor_filter.h>
Public Types
using FunctionObjectT = FunctionObject
Public Member Functions
FunctorFilter (FunctionObjectT function_object, bool extract_removed_indices=false)
Constructor.
const FunctionObjectT & getFunctionObject () const noexcept
FunctionObjectT & getFunctionObject () noexcept
void applyFilter (Indices &indices) override
Filtered results are indexed by an indices array.
void applyFilter (PointCloud< PointT > &output) override
Protected Member Functions
FunctorFilter (bool extract_removed_indices=false)
ctor to be used by derived classes with member function as FilterFunction
void setFunctionObject (FunctionObjectT function_object) const noexcept
utility function for derived class
Protected Attributes
bool keep_organized_ = false
float user_filter_value_ = std::numeric_limits<float>::quiet_NaN()
Private Types
using Base = FilterIndices< PointT >
using PCL_Base = PCLBase< PointT >
Private Attributes
FunctionObjectT functionObject_
Detailed Description
template<typename PointT, typename FunctionObject>
class pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >
Filter point clouds and indices based on a function object passed in the ctor.
The function object can be anything (lambda, std::function, invocable class, etc.) that can be moved into the class. Additionally, it must satisfy the condition is_function_object_for_filter_v
Definition at line 45 of file functor_filter.h.
Member Typedef Documentation
Base
template<typename PointT , typename FunctionObject > using pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::Base = FilterIndices<PointT> private
Definition at line 46 of file functor_filter.h.
FunctionObjectT
template<typename PointT , typename FunctionObject > using pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::FunctionObjectT = FunctionObject
Definition at line 50 of file functor_filter.h.
PCL_Base
template<typename PointT , typename FunctionObject > using pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::PCL_Base = PCLBase<PointT> private
Definition at line 47 of file functor_filter.h.
Constructor & Destructor Documentation
FunctorFilter() [1/2]
template<typename PointT , typename FunctionObject > pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::FunctorFilter (FunctionObjectT function_object, bool extract_removed_indices = false) inline
Constructor.
Parameters
[in] function_object Object of effective type FilterFunction in order to filter out the indices for which it returns false
[in] extract_removed_indices Set to true if you want to be able to extract the indices of points being removed (default = false).
Definition at line 77 of file functor_filter.h.
   : Base(extract_removed_indices), functionObject_(std::move(function_object))
   {
     filter_name_ = "functor_filter";
   }
FunctorFilter() [2/2]
template<typename PointT , typename FunctionObject > pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::FunctorFilter (bool extract_removed_indices = false) inline protected
ctor to be used by derived classes with member function as FilterFunction
Parameters
[in] extract_removed_indices Set to true if you want to be able to extract the indices of points being removed (default = false).
Note
The class would be ill-defined until setFunctionObject has been called Do not call any filter routine until then
Definition at line 160 of file functor_filter.h.
                                                       : Base(extract_removed_indices)
   {
     filter_name_ = "functor_filter";
   }
Member Function Documentation
applyFilter() [1/2]
template<typename PointT , typename FunctionObject > void pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::applyFilter (Indices & indices) inline override
Filtered results are indexed by an indices array.
Parameters
[out] indices The resultant indices.
Definition at line 100 of file functor_filter.h.
   {
     indices.clear();
     indices.reserve(indices_->size());
     if (extract_removed_indices_) {
       removed_indices_->clear();
       removed_indices_->reserve(indices_->size());
     }
     for (const auto index : *indices_) {
       // function object returns true for points that should be selected
       if (negative_ != functionObject_(*input_, index)) {
         indices.push_back(index);
       }
       else if (extract_removed_indices_) {
         removed_indices_->push_back(index);
       }
     }
   }
References pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::functionObject_.
Referenced by pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::applyFilter().
applyFilter() [2/2]
template<typename PointT , typename FunctionObject > void pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::applyFilter (PointCloud< PointT > & output) inline override
Definition at line 120 of file functor_filter.h.
    {
        Indices indices;
        if (keep_organized_)
        {
            if (!extract_removed_indices_)
            {
                PCL_WARN ("[pcl::FilterIndices<PointT>::applyFilter] extract_removed_indices_ was set to 'true' to keep the point cloud organized.\n");
                extract_removed_indices_ = true;
            }
            applyFilter (indices);
            output = *input_;
            // To preserve legacy behavior, only coordinates xyz are filtered.
            // Copying a PointXYZ initialized with the user_filter_value_ into a generic
            // PointT, ensures only the xyz coordinates, if they exist at destination,
            // are overwritten.
            const PointXYZ ufv (user_filter_value_, user_filter_value_, user_filter_value_);
            for (const auto ri : *removed_indices_)  // ri = removed index
            copyPoint(ufv, output[ri]);
            if (!std::isfinite (user_filter_value_))
            output.is_dense = false;
        }
        else
        {
            output.is_dense = true;
            applyFilter (indices);
            pcl::copyPointCloud (*input_, indices, output);
        }
    }
References pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::applyFilter(), pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::keep_organized_, and pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::user_filter_value_.
getFunctionObject() [1/2]
template<typename PointT , typename FunctionObject > const FunctionObjectT & pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::getFunctionObject () const inline noexcept
Definition at line 84 of file functor_filter.h.
   {
     return functionObject_;
   }
References pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::functionObject_.
getFunctionObject() [2/2]
template<typename PointT , typename FunctionObject > FunctionObjectT & pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::getFunctionObject () inline noexcept
Definition at line 90 of file functor_filter.h.
   {
     return functionObject_;
   }
References pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::functionObject_.
setFunctionObject()
template<typename PointT , typename FunctionObject > void pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::setFunctionObject (FunctionObjectT function_object) const inline protected noexcept
utility function for derived class
Parameters
[in] function_object Object of effective type FilterFunction in order to filter out the indices for which it returns false
Definition at line 171 of file functor_filter.h.
   {
     functionObject_ = std::move(function_object);
   }
References pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::functionObject_.
Member Data Documentation
functionObject_
template<typename PointT , typename FunctionObject > FunctionObjectT pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::functionObject_ private
Definition at line 68 of file functor_filter.h.
Referenced by pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::applyFilter(), pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::getFunctionObject(), and pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::setFunctionObject().
keep_organized_
template<typename PointT , typename FunctionObject > bool pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::keep_organized_ = false protected
Definition at line 63 of file functor_filter.h.
Referenced by pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::applyFilter().
user_filter_value_
template<typename PointT , typename FunctionObject > float pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::user_filter_value_ = std::numeric_limits<float>::quiet_NaN() protected
Definition at line 64 of file functor_filter.h.
Referenced by pcl::experimental::advanced::FunctorFilter< PointT, FunctionObject >::applyFilter().
The documentation for this class was generated from the following file:
points_map_filter/src/pcl_expirimental-1.12.1/functor_filter.h