Carma-platform: health_monitor::DriverManager Class Reference
health_monitor::DriverManager Class Reference
#include <driver_manager.h>
Public Member Functions
DriverManager ()
Default constructor for DriverManager with driver_timeout_ = 1000.
DriverManager (std::vector< std::string > critical_driver_names, const long driver_timeout, std::vector< std::string > lidar_gps_driver_names, std::vector< std::string > camera_driver_names)
Constructor for DriverManager takes in crtitical driver names and driver timeout.
void update_driver_status (const cav_msgs::DriverStatusConstPtr &msg, long current_time)
Update driver status.
std::string are_critical_drivers_operational_truck (long current_time)
Check if all critical drivers are operational for truck.
std::string are_critical_drivers_operational_car (long current_time)
Check if all critical drivers are operational for car.
void evaluate_sensor (int &sensor_input, bool available, long current_time, long timestamp, long driver_timeout)
Evaluate if the sensor is available.
cav_msgs::SystemAlert handleSpin (bool truck, bool car, long time_now, long start_up_timestamp, long startup_duration)
Handle the spin and publisher.
Private Attributes
EntryManager em_
bool starting_up_ = true
long driver_timeout_ {1000}
Detailed Description
Definition at line 25 of file driver_manager.h.
Constructor & Destructor Documentation
DriverManager() [1/2]
health_monitor::DriverManager::DriverManager ()
Default constructor for DriverManager with driver_timeout_ = 1000.
Definition at line 21 of file driver_manager.cpp.
{}
DriverManager() [2/2]
health_monitor::DriverManager::DriverManager (std::vector< std::string > critical_driver_names, const long driver_timeout, std::vector< std::string > lidar_gps_driver_names, std::vector< std::string > camera_driver_names)
Constructor for DriverManager takes in crtitical driver names and driver timeout.
Definition at line 23 of file driver_manager.cpp.
                                              :
                                em_(EntryManager(critical_driver_names,lidar_gps_driver_names, camera_driver_names)), driver_timeout_(driver_timeout) {}
Member Function Documentation
are_critical_drivers_operational_car()
std::string health_monitor::DriverManager::are_critical_drivers_operational_car (long current_time)
Check if all critical drivers are operational for car.
Definition at line 136 of file driver_manager.cpp.
    {
        int ssc=0;
        int lidar=0;
        int gps=0;
        int camera=0;
        std::vector<Entry> driver_list = em_.get_entries(); //Real time driver list from driver status
        for(auto i = driver_list.begin(); i < driver_list.end(); ++i)
        {
            if(em_.is_entry_required(i->name_))
            {
                evaluate_sensor(ssc,i->available_,current_time,i->timestamp_,driver_timeout_);
            }
            if(em_.is_lidar_gps_entry_required(i->name_)==0) //Lidar
            {
                evaluate_sensor(lidar,i->available_,current_time,i->timestamp_,driver_timeout_);
            }
            else if(em_.is_lidar_gps_entry_required(i->name_)==1) //GPS
            {
                evaluate_sensor(gps,i->available_,current_time,i->timestamp_,driver_timeout_);
            }
            else if(em_.is_camera_entry_required(i->name_)==0)
            {
                evaluate_sensor(camera,i->available_,current_time,i->timestamp_,driver_timeout_);
            }
        }
        // NOTE: THIS IS A MANUAL DISABLE OF ALL LIDAR FAILURE DETECTION FOLLOWING THE ROS2 PORT
        lidar=1;
        gps=1;
        //Decision making
        if(ssc==1)
        {
            if((lidar==0) && (gps==0))
            {
                return "s_1_l_0_g_0";
            }
            else if((lidar==0) && (gps==1) && (camera == 1))
            {
                return "s_1_l_0_g_1";
            }
            else if((lidar==1) && (gps==0) && (camera == 1))
            {
                return "s_1_l_1_g_0";
            }
            else if ((camera==0) && (lidar == 1) && (gps ==1))
            {
                return "s_1_l_1_g_1_c_0";
            }
            else if ((camera==0) && (lidar == 0) && (gps == 1))
            {
                return "s_1_l_0_g_1_c_0";
            }
            else if ((camera==0) && (lidar == 1) && (gps == 0))
            {
                return "s_1_l_1_g_0_c_0";
            }
            else if((lidar==1) && (gps==1) && (camera == 1))
            {
                return "s_1_l_1_g_1_c_1";
            }
        }
        else
        {
            return "s_0";
        }
    }
References driver_timeout_, em_, evaluate_sensor(), health_monitor::EntryManager::get_entries(), process_bag::i, health_monitor::EntryManager::is_camera_entry_required(), health_monitor::EntryManager::is_entry_required(), and health_monitor::EntryManager::is_lidar_gps_entry_required().
Referenced by handleSpin().
are_critical_drivers_operational_truck()
std::string health_monitor::DriverManager::are_critical_drivers_operational_truck (long current_time)
Check if all critical drivers are operational for truck.
Definition at line 47 of file driver_manager.cpp.
    {
        int ssc=0;
        int lidar1=0;
        int lidar2=0;
        int gps=0;
        int camera=0; //Add Camera Driver
        std::vector<Entry> driver_list = em_.get_entries(); //Real time driver list from driver status
        for(auto i = driver_list.begin(); i < driver_list.end(); ++i)
        {
            if(em_.is_entry_required(i->name_))
            {
              evaluate_sensor(ssc,i->available_,current_time,i->timestamp_,driver_timeout_);
            }
            if(em_.is_lidar_gps_entry_required(i->name_)==0) //Lidar1
            {
               evaluate_sensor(lidar1,i->available_,current_time,i->timestamp_,driver_timeout_);
            }
            else if(em_.is_lidar_gps_entry_required(i->name_)==1) //Lidar2
            {
              evaluate_sensor(lidar2,i->available_,current_time,i->timestamp_,driver_timeout_);
            }
            else if(em_.is_lidar_gps_entry_required(i->name_)==2) //GPS
            {
              evaluate_sensor(gps,i->available_,current_time,i->timestamp_,driver_timeout_);
            }
            else if(em_.is_camera_entry_required(i->name_)==0)
            {
                evaluate_sensor(camera,i->available_,current_time,i->timestamp_,driver_timeout_);
            }
        }
        // NOTE: THIS IS A MANUAL DISABLE OF ALL LIDAR AND GPS FAILURE DETECTION FOLLOWING THE ROS2 PORT
        lidar1=1;
        lidar2=1;
        gps=1;
        //Decision making
        if (ssc == 0)
        {
            return "s_0";
        }
        // if ssc= 1
        if((lidar1==0) && (lidar2==0) && (gps==0))
        {
            return "s_1_l1_0_l2_0_g_0";
        }
        else if((lidar1==0) && (lidar2==0) && (gps==1))
        {
            return "s_1_l1_0_l2_0_g_1";
        }
        else if((lidar1==0) && (lidar2==1) && (gps==0))
        {
            return "s_1_l1_0_l2_1_g_0";
        }
        else if((lidar1==0) && (lidar2==1) && (gps==1))
        {
            return "s_1_l1_0_l2_1_g_1";
        }
        else if((lidar1==1) && (lidar2==0) && (gps==0))
        {
            return "s_1_l1_1_l2_0_g_0";
        }
        else if((lidar1==1) && (lidar2==0) && (gps==1))
        {
            return "s_1_l1_1_l2_0_g_1";
        }
        else if((lidar1==1) && (lidar2==1) && (gps==0))
        {
            return "s_1_l1_1_l2_1_g_0";
        }
        else if ((camera==0) && (lidar1 ==1) && (lidar2 == 1) && (gps == 1) )
        {
            return "s_1_l1_1_l2_1_g_1_c_0";
        }
        else if((lidar1==1) && (lidar2==1) && (gps==1) && (camera == 1))
        {
            return "s_1_l1_1_l2_1_g_1_c_1";
        }
    }
References driver_timeout_, em_, evaluate_sensor(), health_monitor::EntryManager::get_entries(), process_bag::i, health_monitor::EntryManager::is_camera_entry_required(), health_monitor::EntryManager::is_entry_required(), and health_monitor::EntryManager::is_lidar_gps_entry_required().
Referenced by handleSpin().
evaluate_sensor()
void health_monitor::DriverManager::evaluate_sensor (int & sensor_input, bool available, long current_time, long timestamp, long driver_timeout)
Evaluate if the sensor is available.
Definition at line 35 of file driver_manager.cpp.
    {
        if((!available) || (current_time-timestamp > driver_timeout))
        {
            sensor_input=0;
        }
        else
        {
            sensor_input=1;
        }
    }
Referenced by are_critical_drivers_operational_car(), and are_critical_drivers_operational_truck().
handleSpin()
cav_msgs::SystemAlert health_monitor::DriverManager::handleSpin (bool truck, bool car, long time_now, long start_up_timestamp, long startup_duration)
Handle the spin and publisher.
Definition at line 211 of file driver_manager.cpp.
    {
        cav_msgs::SystemAlert alert;
        if(truck==true)
        {
            std::string status = are_critical_drivers_operational_truck(time_now);
            if(status.compare("s_1_l1_1_l2_1_g_1_c_1") == 0)
            {
                starting_up_ = false;
                alert.description = "All essential drivers are ready";
                alert.type = cav_msgs::SystemAlert::DRIVERS_READY;
                return alert;
            }
           else if(starting_up_ && (time_now - start_up_timestamp <= start_duration))
            {
                alert.description = "System is starting up...";
                alert.type = cav_msgs::SystemAlert::NOT_READY;
                return alert;
            }
             else if(status.compare("s_1_l1_1_l2_1_g_1_c_0")==0)
            {
                alert.description = "Camera Failed";
                alert.type = cav_msgs::SystemAlert::SHUTDOWN;
            }
            else if((status.compare("s_1_l1_0_l2_1_g_1") == 0) || (status.compare("s_1_l1_1_l2_0_g_1") == 0))
            {
                alert.description = "One LIDAR Failed";
                alert.type = cav_msgs::SystemAlert::CAUTION;
                return alert;
            }
            else if((status.compare("s_1_l1_0_l2_1_g_0") == 0) || (status.compare("s_1_l1_1_l2_0_g_0") == 0))
            {
                alert.description = "One Lidar and GPS Failed";
                alert.type = cav_msgs::SystemAlert::CAUTION;
                return alert;
            }
            else if(status.compare("s_1_l1_1_l2_1_g_0") == 0)
            {
                alert.description = "GPS Failed";
                alert.type = cav_msgs::SystemAlert::CAUTION;
                return alert;
            }
            else if(status.compare("s_1_l1_0_l2_0_g_1") == 0)
            {
                alert.description = "Both LIDARS Failed";
                alert.type = cav_msgs::SystemAlert::WARNING;
                return alert;
            }
            else if(status.compare("s_1_l1_0_l2_0_g_0") == 0)
            {
                alert.description = "LIDARS and GPS Failed";
                alert.type = cav_msgs::SystemAlert::SHUTDOWN;
                return alert;
            }
            else if(status.compare("s_0") == 0)
            {
                alert.description = "SSC Failed";
                alert.type = cav_msgs::SystemAlert::SHUTDOWN;
                return alert;
            }
            else
            {
                alert.description = "Unknown problem assessing essential driver availability";
                alert.type = cav_msgs::SystemAlert::FATAL;
                return alert;
            }
        }
        else if(car==true)
        {
            std::string status = are_critical_drivers_operational_car(time_now);
            if(status.compare("s_1_l_1_g_1_c_1") == 0)
            {
                starting_up_ = false;
                alert.description = "All essential drivers are ready";
                alert.type = cav_msgs::SystemAlert::DRIVERS_READY;
                return alert;
            }
            else if(starting_up_ && (time_now - start_up_timestamp <= start_duration))
            {
                alert.description = "System is starting up...";
                alert.type = cav_msgs::SystemAlert::NOT_READY;
                return alert;
            }
            else if(status.compare("s_1_l_1_g_1_c_0") == 0)
            {
                alert.description = "Camera Failed";
                alert.type = cav_msgs::SystemAlert::SHUTDOWN;
                return alert;
            }
            else if(status.compare("s_1_l_1_g_0") == 0)
            {
                alert.description = "GPS Failed";
                alert.type = cav_msgs::SystemAlert::CAUTION;
                return alert;
            }
            else if(status.compare("s_1_l_0_g_1") == 0)
            {
                alert.description = "LIDAR Failed";
                alert.type = cav_msgs::SystemAlert::WARNING;
                return alert;
            }
            else if(status.compare("s_1_l_0_g_0") == 0)
            {
                alert.description = "LIDAR, GPS Failed";
                alert.type = cav_msgs::SystemAlert::SHUTDOWN;
                return alert;
            }
            else if(status.compare("s_1_l_0_g_1_c_0") == 0)
            {
                alert.description = "LIDAR, Camera Failed";
                alert.type = cav_msgs::SystemAlert::SHUTDOWN;
                return alert;
            }
            else if(status.compare("s_1_l_1_g_0_c_0") == 0)
            {
                alert.description = " GPS, Camera Failed";
                alert.type = cav_msgs::SystemAlert::SHUTDOWN;
                return alert;
            }
            else if(status.compare("s_0") == 0)
            {
                alert.description = "SSC Failed";
                alert.type = cav_msgs::SystemAlert::SHUTDOWN;
                return alert;
            }
            else
            {
                alert.description = "Unknown problem assessing essential driver availability";
                alert.type = cav_msgs::SystemAlert::FATAL;
                return alert;
            }
        }
        else
        {
            alert.description = "Need to set either truck or car flag";
            alert.type = cav_msgs::SystemAlert::FATAL;
            return alert;
        }
    }
References are_critical_drivers_operational_car(), are_critical_drivers_operational_truck(), arbitrator::SHUTDOWN, and starting_up_.
update_driver_status()
void health_monitor::DriverManager::update_driver_status (const cav_msgs::DriverStatusConstPtr & msg, long current_time)
Update driver status.
Definition at line 27 of file driver_manager.cpp.
    {
        Entry driver_status(msg->status == cav_msgs::DriverStatus::OPERATIONAL || msg->status == cav_msgs::DriverStatus::DEGRADED,true, msg->name, current_time, 0, "");
        em_.update_entry(driver_status);
        // NOTE: The following is a temporary hack to allow the lidar driver to be moved to ROS2 which will not use this node
        Entry fake_entry(msg->status == cav_msgs::DriverStatus::OPERATIONAL,true, msg->name, current_time, 0, "");
    }
References em_, and health_monitor::EntryManager::update_entry().
Member Data Documentation
driver_timeout_
long health_monitor::DriverManager::driver_timeout_ {1000} private
Definition at line 64 of file driver_manager.h.
Referenced by are_critical_drivers_operational_car(), and are_critical_drivers_operational_truck().
em_
EntryManager health_monitor::DriverManager::em_ private
Definition at line 61 of file driver_manager.h.
Referenced by are_critical_drivers_operational_car(), are_critical_drivers_operational_truck(), and update_driver_status().
starting_up_
bool health_monitor::DriverManager::starting_up_ = true private
Definition at line 62 of file driver_manager.h.
Referenced by handleSpin().
The documentation for this class was generated from the following files:
health_monitor/include/driver_manager.h
health_monitor/src/driver_manager.cpp