Carma-platform: route::RouteStateWorker Class Reference
route::RouteStateWorker Class Reference
#include <route_state_worker.hpp>
Public Types
enum RouteEvent {
ROUTE_LOADED = 0 , ROUTE_SELECTED = 1 , ROUTE_STARTED = 2 , ROUTE_COMPLETED = 3 ,
ROUTE_DEPARTED = 4 , ROUTE_ABORTED = 5 , ROUTE_GEN_FAILED = 6 , ROUTE_INVALIDATION = 7
}
enum RouteState { LOADING = 0 , SELECTION = 1 , ROUTING = 2 , FOLLOWING = 3 }
Public Member Functions
RouteStateWorker ()=default
void onRouteEvent (RouteEvent event)
Process route event based on designed state machine diagram.
RouteState getRouteState () const
Get current route state machine state.
void setLoggerInterface (rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr logger)
Private Attributes
RouteState state_ = RouteState::LOADING
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr logger_
Detailed Description
Definition at line 24 of file route_state_worker.hpp.
Member Enumeration Documentation
RouteEvent
enum route::RouteStateWorker::RouteEvent
Possible events for the RouteStateWorker to respond to: ROUTE_LOADED - Route worker received all necessary parameters and loaded route file path ROUTE_SELECTED - A route file has been selected by user ROUTE_STARTED - A route is generated by provided route file ROUTE_COMPLETED - Reached the destination of current route ROUTE_DEPARTED - Vehicle has deviated from the route ROUTE_ABORTED - User decides to stop following the current route ROUTE_GEN_FAILED - No route can be generated based on provided route file ROUTE_INVALIDATION - Certain portion of the route is invalidated based on situation.
Enumerator
ROUTE_LOADED
ROUTE_SELECTED
ROUTE_STARTED
ROUTE_COMPLETED
ROUTE_DEPARTED
ROUTE_ABORTED
ROUTE_GEN_FAILED
ROUTE_INVALIDATION
Definition at line 39 of file route_state_worker.hpp.
{
                ROUTE_LOADED = 0,
                ROUTE_SELECTED = 1,
                ROUTE_STARTED = 2,
                ROUTE_COMPLETED = 3,
                ROUTE_DEPARTED = 4,
                ROUTE_ABORTED = 5,
                ROUTE_GEN_FAILED = 6,
                ROUTE_INVALIDATION = 7,
            };
RouteState
enum route::RouteStateWorker::RouteState
Possible states of the RouteStateWorker: LOADING - RouteState worker's initial state, waiting for all necessary parameters to be set SELECTION - RouteState worker is waiting on user to select a route ROUTING - Calling lanelet2 library to generate a route based on selected route file FOLLOWING - Following a route and tracking its downtrack and crosstrack distance
Enumerator
LOADING
SELECTION
ROUTING
FOLLOWING
Definition at line 57 of file route_state_worker.hpp.
{
                LOADING = 0,
                SELECTION = 1,
                ROUTING = 2,
                FOLLOWING = 3,
            };
Constructor & Destructor Documentation
RouteStateWorker()
route::RouteStateWorker::RouteStateWorker () default
Member Function Documentation
getRouteState()
RouteStateWorker::RouteState route::RouteStateWorker::getRouteState () const
Get current route state machine state.
Definition at line 21 of file route_state_worker.cpp.
{
        return state_;
    }
References state_.
Referenced by route::RouteGeneratorWorker::abortActiveRouteCb(), route::RouteGeneratorWorker::bumperPoseCb(), route::RouteGeneratorWorker::getAvailableRouteCb(), route::RouteGeneratorWorker::setActiveRouteCb(), and route::RouteGeneratorWorker::spinCallback().
onRouteEvent()
void route::RouteStateWorker::onRouteEvent (RouteEvent event)
Process route event based on designed state machine diagram.
Parameters
event Incoming route event
Definition at line 25 of file route_state_worker.cpp.
{
        auto old_state = state_;
        switch (state_)
        {
        case RouteState::LOADING:
            if(event == RouteEvent::ROUTE_LOADED)
            {
                state_ = RouteState::SELECTION;
            }
            break;
        case RouteState::SELECTION:
            if(event == RouteEvent::ROUTE_SELECTED)
            {
                state_ = RouteState::ROUTING;
            }
            break;
        case RouteState::ROUTING:
            if(event == RouteEvent::ROUTE_STARTED)
            {
                state_ = RouteState::FOLLOWING;
            } else if(event == RouteEvent::ROUTE_GEN_FAILED)
            {
                state_ = RouteState::SELECTION;
            }
            break;
        case RouteState::FOLLOWING:
            if(event == RouteEvent::ROUTE_COMPLETED || event == RouteEvent::ROUTE_DEPARTED || event == RouteEvent::ROUTE_ABORTED)
            {
                state_ = RouteState::LOADING;
            }
            else if(event == RouteEvent::ROUTE_INVALIDATION)
            {
                state_ = RouteState::ROUTING;
            }
            break;
        default:
            // should not reach here
            throw std::invalid_argument("Current state is illegal: " + std::to_string(state_));
        }
        RCLCPP_INFO_STREAM(logger_->get_logger(), "Received Route Event: " << event << " transitioning from: " << old_state << " to: " << state_);
    }
References logger_, state_, and carma_cooperative_perception::to_string().
Referenced by route::RouteGeneratorWorker::abortActiveRouteCb(), route::RouteGeneratorWorker::bumperPoseCb(), route::RouteGeneratorWorker::getAvailableRouteCb(), route::RouteGeneratorWorker::setActiveRouteCb(), route::RouteGeneratorWorker::setRouteFilePath(), and route::RouteGeneratorWorker::spinCallback().
setLoggerInterface()
void route::RouteStateWorker::setLoggerInterface (rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr logger)
Definition at line 70 of file route_state_worker.cpp.
    {
        logger_ = logger;
    }
References logger_.
Referenced by route::RouteGeneratorWorker::setLoggerInterface().
Member Data Documentation
logger_
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr route::RouteStateWorker::logger_ private
Definition at line 85 of file route_state_worker.hpp.
Referenced by onRouteEvent(), and setLoggerInterface().
state_
RouteState route::RouteStateWorker::state_ = RouteState::LOADING private
Definition at line 82 of file route_state_worker.hpp.
Referenced by getRouteState(), and onRouteEvent().
The documentation for this class was generated from the following files:
route/include/route/route_state_worker.hpp
route/src/route_state_worker.cpp