Carma-platform: internal::ISchemaStateFactory< SchemaType > Class Template Reference
internal::ISchemaStateFactory< SchemaType > Class Template Reference abstract
#include <schema.h>
Public Member Functions
virtual ~ISchemaStateFactory ()
virtual ISchemaValidator * CreateSchemaValidator (const SchemaType &)=0
virtual void DestroySchemaValidator (ISchemaValidator *validator)=0
virtual void * CreateHasher ()=0
virtual uint64_t GetHashCode (void *hasher)=0
virtual void DestroryHasher (void *hasher)=0
virtual void * MallocState (size_t size)=0
virtual void FreeState (void *p)=0
Detailed Description
template<typename SchemaType>
class internal::ISchemaStateFactory< SchemaType >
Definition at line 148 of file schema.h.
Constructor & Destructor Documentation
~ISchemaStateFactory()
template<typename SchemaType > virtual internal::ISchemaStateFactory< SchemaType >::~ISchemaStateFactory () inline virtual
Definition at line 150 of file schema.h.
{}
Member Function Documentation
CreateHasher()
template<typename SchemaType > virtual void * internal::ISchemaStateFactory< SchemaType >::CreateHasher () pure virtual
Implemented in GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by internal::Schema< SchemaDocumentType >::CreateParallelValidator().
CreateSchemaValidator()
template<typename SchemaType > virtual ISchemaValidator * internal::ISchemaStateFactory< SchemaType >::CreateSchemaValidator (const SchemaType &) pure virtual
Implemented in GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by internal::Schema< SchemaDocumentType >::CreateParallelValidator(), and internal::Schema< SchemaDocumentType >::CreateSchemaValidators().
DestroryHasher()
template<typename SchemaType > virtual void internal::ISchemaStateFactory< SchemaType >::DestroryHasher (void * hasher) pure virtual
Implemented in GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by internal::SchemaValidationContext< SchemaDocumentType >::~SchemaValidationContext().
DestroySchemaValidator()
template<typename SchemaType > virtual void internal::ISchemaStateFactory< SchemaType >::DestroySchemaValidator (ISchemaValidator * validator) pure virtual
Referenced by internal::SchemaValidationContext< SchemaDocumentType >::~SchemaValidationContext().
FreeState()
template<typename SchemaType > virtual void internal::ISchemaStateFactory< SchemaType >::FreeState (void * p) pure virtual
Implemented in GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by internal::SchemaValidationContext< SchemaDocumentType >::~SchemaValidationContext().
GetHashCode()
template<typename SchemaType > virtual uint64_t internal::ISchemaStateFactory< SchemaType >::GetHashCode (void * hasher) pure virtual
Implemented in GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by internal::Schema< SchemaDocumentType >::EndValue().
MallocState()
template<typename SchemaType > virtual void * internal::ISchemaStateFactory< SchemaType >::MallocState (size_t size) pure virtual
Implemented in GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >.
Referenced by internal::Schema< SchemaDocumentType >::CreateParallelValidator(), and internal::Schema< SchemaDocumentType >::StartObject().
The documentation for this class was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/schema.h