Carma-platform: cost_plugin_system::CostofEfficiency Class Reference
cost_plugin_system::CostofEfficiency Class Reference
#include <cost_efficiency.hpp>
Public Member Functions
CostofEfficiency (double speed_limit, double speed_buffer)
double compute_cost (cav_msgs::ManeuverPlan plan) const
Compute the cost of a given maneuver plan.
Public Member Functions inherited from cost_plugin_system::CostPlugins
virtual double compute_cost (cav_msgs::ManeuverPlan plan) const =0
Compute the cost of a given maneuver plan.
virtual ~CostPlugins ()
Virtual destructor provided for memory safety.
Private Attributes
double speed_limit_
double speed_buffer_
Detailed Description
Definition at line 22 of file cost_efficiency.hpp.
Constructor & Destructor Documentation
CostofEfficiency()
cost_plugin_system::CostofEfficiency::CostofEfficiency (double speed_limit, double speed_buffer)
Definition at line 24 of file cost_efficiency.cpp.
{
    speed_limit_ = speed_limit;
    speed_buffer_ = speed_buffer;
}
References speed_buffer_, and speed_limit_.
Member Function Documentation
compute_cost()
double cost_plugin_system::CostofEfficiency::compute_cost (cav_msgs::ManeuverPlan plan) const virtual
Compute the cost of a given maneuver plan.
Parameters
plan The plan to evaluate
Returns
double The total cost
Implements cost_plugin_system::CostPlugins.
Definition at line 30 of file cost_efficiency.cpp.
{
    double cost = 0.0;
    int maneuver_size = plan.maneuvers.size();
    for (auto it = plan.maneuvers.begin(); it != plan.maneuvers.end(); it++)
    {
        double average_speed = (cost_utils::get_maneuver_start_speed(*it) + cost_utils::get_maneuver_end_speed(*it)) / 2;
        if (average_speed < speed_buffer_)
        {
            cost += 1 - 1 / speed_buffer_ * average_speed;
        }
        else if (average_speed > speed_limit_)
        {
            cost += 1;
        }
        else
        {
            cost += 1 / (speed_limit_ - speed_buffer_) * average_speed - speed_buffer_ / (speed_limit_ - speed_buffer_);
        }
    }
    // Normalize the cost
    cost = cost / maneuver_size;
    return cost;
}
References cost_utils::get_maneuver_end_speed(), cost_utils::get_maneuver_start_speed(), speed_buffer_, and speed_limit_.
Referenced by cost_plugin_system::CostPluginWorker::compute_final_score().
Member Data Documentation
speed_buffer_
double cost_plugin_system::CostofEfficiency::speed_buffer_ private
Definition at line 30 of file cost_efficiency.hpp.
Referenced by CostofEfficiency(), and compute_cost().
speed_limit_
double cost_plugin_system::CostofEfficiency::speed_limit_ private
Definition at line 29 of file cost_efficiency.hpp.
Referenced by CostofEfficiency(), and compute_cost().
The documentation for this class was generated from the following files:
cost_plugin_system/include/cost_efficiency.hpp
cost_plugin_system/src/cost_efficiency.cpp