Carma-platform: approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable Class Reference
approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable Class Reference
Class defining the state transition table behavior for the ApproachingEmergencyVehiclePlugin.
#include <approaching_emergency_vehicle_transition_table.hpp>
Public Types
using TransitionCallback = std::function< void(ApproachingEmergencyVehicleState prev_state, ApproachingEmergencyVehicleState new_state, ApproachingEmergencyVehicleEvent event)>
Public Member Functions
ApproachingEmergencyVehicleTransitionTable ()=default
ApproachingEmergencyVehicleTransitionTable Constructor.
ApproachingEmergencyVehicleState getState () const
Returns the current state.
void event (ApproachingEmergencyVehicleEvent event)
Trigger event for the transition table.
void setTransitionCallback (TransitionCallback cb)
Callback setting function. The provided callback will be triggered any time the current state changes to a new state.
Private Member Functions
void eventWhenNO_APPROACHING_ERV (ApproachingEmergencyVehicleEvent event)
void eventWhenMOVING_OVER_FOR_APPROACHING_ERV (ApproachingEmergencyVehicleEvent event)
void eventWhenWAITING_FOR_APPROACHING_ERV (ApproachingEmergencyVehicleEvent event)
void eventWhenSLOWING_DOWN_FOR_ERV (ApproachingEmergencyVehicleEvent event)
void logDebugEvent (ApproachingEmergencyVehicleEvent event) const
Helper function for logging the provide event.
void setAndLogState (ApproachingEmergencyVehicleState new_state, ApproachingEmergencyVehicleEvent source_event)
Function to change the current state and log the details of the transition.
Private Attributes
ApproachingEmergencyVehicleState state_ = ApproachingEmergencyVehicleState::NO_APPROACHING_ERV
Current state. This state should only ever be set using the setAndLogState() function.
TransitionCallback transition_callback_
Detailed Description
Class defining the state transition table behavior for the ApproachingEmergencyVehiclePlugin.
Definition at line 28 of file approaching_emergency_vehicle_transition_table.hpp.
Member Typedef Documentation
TransitionCallback
using approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable::TransitionCallback = std::function<void(ApproachingEmergencyVehicleState prev_state, ApproachingEmergencyVehicleState new_state, ApproachingEmergencyVehicleEvent event)>
Definition at line 31 of file approaching_emergency_vehicle_transition_table.hpp.
Constructor & Destructor Documentation
ApproachingEmergencyVehicleTransitionTable()
approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable::ApproachingEmergencyVehicleTransitionTable () default
ApproachingEmergencyVehicleTransitionTable Constructor.
Parameters
mode Defines the operational mode of the state machine which modifies some of the state transitions
Member Function Documentation
event()
void approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable::event (ApproachingEmergencyVehicleEvent event)
Trigger event for the transition table.
Parameters
event The event for the transition table to evaluate
Definition at line 27 of file approaching_emergency_vehicle_transition_table.cpp.
{
  switch (state_)
  {
    case ApproachingEmergencyVehicleState::NO_APPROACHING_ERV:
      eventWhenNO_APPROACHING_ERV(event);
      break;
    case ApproachingEmergencyVehicleState::MOVING_OVER_FOR_APPROACHING_ERV:
      eventWhenMOVING_OVER_FOR_APPROACHING_ERV(event);
      break;
    case ApproachingEmergencyVehicleState::WAITING_FOR_APPROACHING_ERV:
      eventWhenWAITING_FOR_APPROACHING_ERV(event);
      break;
    case ApproachingEmergencyVehicleState::SLOWING_DOWN_FOR_ERV:
      eventWhenSLOWING_DOWN_FOR_ERV(event);
      break;
    default:
      throw std::invalid_argument("Transition table in unsupported state");
  }
}
References event(), eventWhenMOVING_OVER_FOR_APPROACHING_ERV(), eventWhenNO_APPROACHING_ERV(), eventWhenSLOWING_DOWN_FOR_ERV(), eventWhenWAITING_FOR_APPROACHING_ERV(), approaching_emergency_vehicle_plugin::MOVING_OVER_FOR_APPROACHING_ERV, approaching_emergency_vehicle_plugin::NO_APPROACHING_ERV, approaching_emergency_vehicle_plugin::SLOWING_DOWN_FOR_ERV, state_, and approaching_emergency_vehicle_plugin::WAITING_FOR_APPROACHING_ERV.
Referenced by approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin::checkForErvTimeout(), event(), eventWhenMOVING_OVER_FOR_APPROACHING_ERV(), eventWhenNO_APPROACHING_ERV(), eventWhenSLOWING_DOWN_FOR_ERV(), eventWhenWAITING_FOR_APPROACHING_ERV(), logDebugEvent(), and approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin::plan_maneuvers_callback().
eventWhenMOVING_OVER_FOR_APPROACHING_ERV()
void approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable::eventWhenMOVING_OVER_FOR_APPROACHING_ERV (ApproachingEmergencyVehicleEvent event) private
Definition at line 95 of file approaching_emergency_vehicle_transition_table.cpp.
{
  switch (event)
  {
    case ApproachingEmergencyVehicleEvent::ERV_UPDATE_TIMEOUT:
      setAndLogState(ApproachingEmergencyVehicleState::NO_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::NO_APPROACHING_ERV:
      setAndLogState(ApproachingEmergencyVehicleState::NO_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::APPROACHING_ERV_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::MOVING_OVER_FOR_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::APPROACHING_ERV_NOT_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::WAITING_FOR_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::ERV_ABOUT_TO_PASS_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::WAITING_FOR_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::ERV_ABOUT_TO_PASS_NOT_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::WAITING_FOR_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::ERV_PASSING_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::SLOWING_DOWN_FOR_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::ERV_PASSING_NOT_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::SLOWING_DOWN_FOR_ERV, event);
      break;
    default:
      logDebugEvent(event);
      break;
  }
}
References approaching_emergency_vehicle_plugin::APPROACHING_ERV_IN_PATH, approaching_emergency_vehicle_plugin::APPROACHING_ERV_NOT_IN_PATH, approaching_emergency_vehicle_plugin::ERV_ABOUT_TO_PASS_IN_PATH, approaching_emergency_vehicle_plugin::ERV_ABOUT_TO_PASS_NOT_IN_PATH, approaching_emergency_vehicle_plugin::ERV_PASSING_IN_PATH, approaching_emergency_vehicle_plugin::ERV_PASSING_NOT_IN_PATH, approaching_emergency_vehicle_plugin::ERV_UPDATE_TIMEOUT, event(), logDebugEvent(), approaching_emergency_vehicle_plugin::MOVING_OVER_FOR_APPROACHING_ERV, approaching_emergency_vehicle_plugin::NO_APPROACHING_ERV, setAndLogState(), approaching_emergency_vehicle_plugin::SLOWING_DOWN_FOR_ERV, and approaching_emergency_vehicle_plugin::WAITING_FOR_APPROACHING_ERV.
Referenced by event().
eventWhenNO_APPROACHING_ERV()
void approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable::eventWhenNO_APPROACHING_ERV (ApproachingEmergencyVehicleEvent event) private
Definition at line 57 of file approaching_emergency_vehicle_transition_table.cpp.
{
  switch (event)
  {
    case ApproachingEmergencyVehicleEvent::NO_APPROACHING_ERV:
      setAndLogState(ApproachingEmergencyVehicleState::NO_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::APPROACHING_ERV_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::MOVING_OVER_FOR_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::APPROACHING_ERV_NOT_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::WAITING_FOR_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::ERV_ABOUT_TO_PASS_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::WAITING_FOR_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::ERV_ABOUT_TO_PASS_NOT_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::WAITING_FOR_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::ERV_PASSING_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::SLOWING_DOWN_FOR_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::ERV_PASSING_NOT_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::SLOWING_DOWN_FOR_ERV, event);
      break;
    default:
      logDebugEvent(event);
      break;
  }
}
References approaching_emergency_vehicle_plugin::APPROACHING_ERV_IN_PATH, approaching_emergency_vehicle_plugin::APPROACHING_ERV_NOT_IN_PATH, approaching_emergency_vehicle_plugin::ERV_ABOUT_TO_PASS_IN_PATH, approaching_emergency_vehicle_plugin::ERV_ABOUT_TO_PASS_NOT_IN_PATH, approaching_emergency_vehicle_plugin::ERV_PASSING_IN_PATH, approaching_emergency_vehicle_plugin::ERV_PASSING_NOT_IN_PATH, event(), logDebugEvent(), approaching_emergency_vehicle_plugin::MOVING_OVER_FOR_APPROACHING_ERV, approaching_emergency_vehicle_plugin::NO_APPROACHING_ERV, setAndLogState(), approaching_emergency_vehicle_plugin::SLOWING_DOWN_FOR_ERV, and approaching_emergency_vehicle_plugin::WAITING_FOR_APPROACHING_ERV.
Referenced by event().
eventWhenSLOWING_DOWN_FOR_ERV()
void approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable::eventWhenSLOWING_DOWN_FOR_ERV (ApproachingEmergencyVehicleEvent event) private
Definition at line 179 of file approaching_emergency_vehicle_transition_table.cpp.
{
  switch (event)
  {
    case ApproachingEmergencyVehicleEvent::ERV_UPDATE_TIMEOUT:
      setAndLogState(ApproachingEmergencyVehicleState::NO_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::ERV_PASSED:
      setAndLogState(ApproachingEmergencyVehicleState::NO_APPROACHING_ERV, event);
      break;
    default:
      logDebugEvent(event);
      break;
  }
}
References approaching_emergency_vehicle_plugin::ERV_PASSED, approaching_emergency_vehicle_plugin::ERV_UPDATE_TIMEOUT, event(), logDebugEvent(), approaching_emergency_vehicle_plugin::NO_APPROACHING_ERV, and setAndLogState().
Referenced by event().
eventWhenWAITING_FOR_APPROACHING_ERV()
void approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable::eventWhenWAITING_FOR_APPROACHING_ERV (ApproachingEmergencyVehicleEvent event) private
Definition at line 137 of file approaching_emergency_vehicle_transition_table.cpp.
{
  switch (event)
  {
    case ApproachingEmergencyVehicleEvent::ERV_UPDATE_TIMEOUT:
      setAndLogState(ApproachingEmergencyVehicleState::NO_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::NO_APPROACHING_ERV:
      setAndLogState(ApproachingEmergencyVehicleState::NO_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::APPROACHING_ERV_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::MOVING_OVER_FOR_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::APPROACHING_ERV_NOT_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::WAITING_FOR_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::ERV_ABOUT_TO_PASS_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::WAITING_FOR_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::ERV_ABOUT_TO_PASS_NOT_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::WAITING_FOR_APPROACHING_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::ERV_PASSING_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::SLOWING_DOWN_FOR_ERV, event);
      break;
    case ApproachingEmergencyVehicleEvent::ERV_PASSING_NOT_IN_PATH:
      setAndLogState(ApproachingEmergencyVehicleState::SLOWING_DOWN_FOR_ERV, event);
      break;
    default:
      logDebugEvent(event);
      break;
  }
}
References approaching_emergency_vehicle_plugin::APPROACHING_ERV_IN_PATH, approaching_emergency_vehicle_plugin::APPROACHING_ERV_NOT_IN_PATH, approaching_emergency_vehicle_plugin::ERV_ABOUT_TO_PASS_IN_PATH, approaching_emergency_vehicle_plugin::ERV_ABOUT_TO_PASS_NOT_IN_PATH, approaching_emergency_vehicle_plugin::ERV_PASSING_IN_PATH, approaching_emergency_vehicle_plugin::ERV_PASSING_NOT_IN_PATH, approaching_emergency_vehicle_plugin::ERV_UPDATE_TIMEOUT, event(), logDebugEvent(), approaching_emergency_vehicle_plugin::MOVING_OVER_FOR_APPROACHING_ERV, approaching_emergency_vehicle_plugin::NO_APPROACHING_ERV, setAndLogState(), approaching_emergency_vehicle_plugin::SLOWING_DOWN_FOR_ERV, and approaching_emergency_vehicle_plugin::WAITING_FOR_APPROACHING_ERV.
Referenced by event().
getState()
ApproachingEmergencyVehicleState approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable::getState () const
Returns the current state.
Returns
Current state
Definition at line 22 of file approaching_emergency_vehicle_transition_table.cpp.
{
  return state_;
}
References state_.
Referenced by approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin::generateApproachingErvStatusMessage(), approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin::getSecondsUntilPassing(), and approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin::plan_maneuvers_callback().
logDebugEvent()
void approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable::logDebugEvent (ApproachingEmergencyVehicleEvent event) const private
Helper function for logging the provide event.
Parameters
event The event to be logged
Definition at line 197 of file approaching_emergency_vehicle_transition_table.cpp.
{
  RCLCPP_INFO_STREAM(rclcpp::get_logger("approaching_emergency_vehicle_plugin"), "ApproachingEmergencyVehicleTransitionTable received unsupported event of " << event << " while in state "
                                                                                  << state_);
}
References event(), and state_.
Referenced by eventWhenMOVING_OVER_FOR_APPROACHING_ERV(), eventWhenNO_APPROACHING_ERV(), eventWhenSLOWING_DOWN_FOR_ERV(), and eventWhenWAITING_FOR_APPROACHING_ERV().
setAndLogState()
void approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable::setAndLogState (ApproachingEmergencyVehicleState new_state, ApproachingEmergencyVehicleEvent source_event) private
Function to change the current state and log the details of the transition.
Parameters
new_state The state to set.
source_event The event which caused the new_state to be set
Definition at line 203 of file approaching_emergency_vehicle_transition_table.cpp.
{
  if (new_state == state_)
  {
    return;  // State was unchanged no need to log or trigger callbacks
  }
  RCLCPP_INFO_STREAM(rclcpp::get_logger("approaching_emergency_vehicle_plugin"), "ApproachingEmergencyVehicleTransitionTable changed ApproachingEmergencyVehicle Strategic Plugin state from "
                  << state_ << " to " << new_state << " because of event " << source_event);
  ApproachingEmergencyVehicleState prev_state = state_;
  state_ = new_state; // Set new state
  if (transition_callback_) // Trigger callback if available
  {
    transition_callback_(prev_state, state_, source_event);
  }
}
References state_, and transition_callback_.
Referenced by eventWhenMOVING_OVER_FOR_APPROACHING_ERV(), eventWhenNO_APPROACHING_ERV(), eventWhenSLOWING_DOWN_FOR_ERV(), and eventWhenWAITING_FOR_APPROACHING_ERV().
setTransitionCallback()
void approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable::setTransitionCallback (TransitionCallback cb)
Callback setting function. The provided callback will be triggered any time the current state changes to a new state.
Parameters
cb The callback function which will be provided with the previous state, new current state, and the event which caused the transition.
Definition at line 52 of file approaching_emergency_vehicle_transition_table.cpp.
{
  transition_callback_ = cb;
}
References transition_callback_.
Member Data Documentation
state_
ApproachingEmergencyVehicleState approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable::state_ = ApproachingEmergencyVehicleState::NO_APPROACHING_ERV private
Current state. This state should only ever be set using the setAndLogState() function.
Definition at line 65 of file approaching_emergency_vehicle_transition_table.hpp.
Referenced by event(), getState(), logDebugEvent(), and setAndLogState().
transition_callback_
TransitionCallback approaching_emergency_vehicle_plugin::ApproachingEmergencyVehicleTransitionTable::transition_callback_ private
Definition at line 67 of file approaching_emergency_vehicle_transition_table.hpp.
Referenced by setAndLogState(), and setTransitionCallback().
The documentation for this class was generated from the following files:
approaching_emergency_vehicle_plugin/include/approaching_emergency_vehicle_plugin/approaching_emergency_vehicle_transition_table.hpp
approaching_emergency_vehicle_plugin/src/approaching_emergency_vehicle_transition_table.cpp