Carma-platform: mock_drivers::MockCommsDriver Class Reference
mock_drivers::MockCommsDriver Class Reference
Mock Comms driver. Operates as a passthrough for bag data which updates the timestamps on received messages.
#include <MockCommsDriver.h>
Public Member Functions
MockCommsDriver (bool dummy=false)
~MockCommsDriver ()
std::vector< DriverType > getDriverTypes () override
Pure Virtual method which child classes must override that returns the list of all driver types that class implements.
uint8_t getDriverStatus () override
Pure Virtual method. Returns an integer value which corresponds to the cav_msgs/DriverStatus enum felids representing the status of the driver.
unsigned int getRate () override
Pure virtual method that returns the desired operational rate of a child class.
Public Member Functions inherited from mock_drivers::MockDriver
virtual ~MockDriver ()=0
int run ()
A function to initialize the publishers and subsricers and start the node. In child classes, this function will trigger a call to onRun().
virtual std::vector< DriverType > getDriverTypes ()=0
Pure Virtual method which child classes must override that returns the list of all driver types that class implements.
virtual uint8_t getDriverStatus ()=0
Pure Virtual method. Returns an integer value which corresponds to the cav_msgs/DriverStatus enum felids representing the status of the driver.
virtual unsigned int getRate ()=0
Pure virtual method that returns the desired operational rate of a child class.
bool spinCallback ()
Callback which will be triggered at the rate specified by getRate(). This callback will also trigger the onSpin() method.
Protected Member Functions
int onRun () override
Pure virtual method which must be implemented by child classes. This method will be run once at startup. Child classes should add pub/sub initialization in this method implementation.
Protected Member Functions inherited from mock_drivers::MockDriver
virtual bool onSpin ()
Virtual method which child classes can override to add functionality which will occur during each spin loop. This means this function will be nominally called at the rate specified by getRate()
virtual int onRun ()=0
Pure virtual method which must be implemented by child classes. This method will be run once at startup. Child classes should add pub/sub initialization in this method implementation.
void driverDiscovery ()
Helper function to publish the driver discovery message.
MockDriverNode getMockDriverNode () const
Returns the mock driver node for the mock driver (used for testing)
template<typename T >
void addPassthroughPub (const std::string &sub_topic, const std::string &pub_topic, bool latch, size_t queue_size)
Function adds both a publisher and subscriber of the specified type. This means a passthrough subscription has been created. This version of the method should be used for message types which contain a Header at the field "header". The header field will be automatically updated to the current ros::Time::now().
template<typename T >
void addPassthroughPubNoHeader (const std::string &sub_topic, const std::string &pub_topic, bool latch, size_t queue_size)
Function adds both a publisher and subscriber of the specified type. This means a passthrough subscription has been created. This version of the method should be used for message types which does NOT contain a Header at the field "header".
Private Member Functions
void outboundCallback (const cav_msgs::ByteArray::ConstPtr &msg) const
Private Attributes
ConstPtrRefROSCommsPtr< cav_msgs::ByteArray > outbound_sub_ptr_
const std::string inbound_binary_topic_ = "comms/inbound_binary_msg"
const std::string outbound_binary_topic_ = "comms/outbound_binary_msg"
Additional Inherited Members
Protected Types inherited from mock_drivers::MockDriver
template<class T >
using ConstPtr = boost::shared_ptr< const T >
template<class T >
using ConstPtrRef = const ConstPtr< T > &
template<class T >
using ROSCommsPtr = boost::shared_ptr< ROSComms< T > >
template<class T >
using ConstPtrRefROSComms = ROSComms< ConstPtrRef< T > >
template<class T >
using ConstPtrRefROSCommsPtr = ROSCommsPtr< ConstPtrRef< T > >
Protected Attributes inherited from mock_drivers::MockDriver
MockDriverNode mock_driver_node_
const std::string bag_prefix_ = "/bag/hardware_interface/"
const std::string driver_discovery_topic_ = "driver_discovery"
ROSCommsPtr< cav_msgs::DriverStatus > driver_discovery_pub_ptr_
ros::Time last_discovery_pub_ = ros::Time(0)
Detailed Description
Mock Comms driver. Operates as a passthrough for bag data which updates the timestamps on received messages.
Definition at line 25 of file MockCommsDriver.h.
Constructor & Destructor Documentation
MockCommsDriver()
mock_drivers::MockCommsDriver::MockCommsDriver (bool dummy = false)
Definition at line 36 of file MockCommsDriver.cpp.
{
  mock_driver_node_ = MockDriverNode(dummy);
  std::function<void(const cav_msgs::ByteArray::ConstPtr&)> outbound_ptr =
      std::bind(&MockCommsDriver::outboundCallback, this, std::placeholders::_1);
  outbound_sub_ptr_ = boost::make_shared<ConstPtrRefROSComms<cav_msgs::ByteArray>>(outbound_ptr, CommTypes::sub, false,
                                                                                   10, outbound_binary_topic_);
}
References mock_drivers::MockDriver::mock_driver_node_, outbound_binary_topic_, outbound_sub_ptr_, outboundCallback(), and sub.
~MockCommsDriver()
mock_drivers::MockCommsDriver::~MockCommsDriver () inline
Definition at line 40 of file MockCommsDriver.h.
{};
Member Function Documentation
getDriverStatus()
uint8_t mock_drivers::MockCommsDriver::getDriverStatus () override virtual
Pure Virtual method. Returns an integer value which corresponds to the cav_msgs/DriverStatus enum felids representing the status of the driver.
Returns
Integer value which must match one of the enum fields in cav_msgs/DriverStatus
Implements mock_drivers::MockDriver.
Definition at line 26 of file MockCommsDriver.cpp.
{
  return cav_msgs::DriverStatus::OPERATIONAL;
}
getDriverTypes()
std::vector< DriverType > mock_drivers::MockCommsDriver::getDriverTypes () override virtual
Pure Virtual method which child classes must override that returns the list of all driver types that class implements.
Returns
A list of DriverType that defines the interfaces the implementing class provides
Implements mock_drivers::MockDriver.
Definition at line 21 of file MockCommsDriver.cpp.
{
  return { DriverType::COMMS };
}
References COMMS.
getRate()
unsigned int mock_drivers::MockCommsDriver::getRate () override virtual
Pure virtual method that returns the desired operational rate of a child class.
Returns
Spin rate in Hz
Implements mock_drivers::MockDriver.
Definition at line 46 of file MockCommsDriver.cpp.
{
  return 20; // 20 Hz as default spin rate to match expected comms data rate
}
onRun()
int mock_drivers::MockCommsDriver::onRun () override protected virtual
Pure virtual method which must be implemented by child classes. This method will be run once at startup. Child classes should add pub/sub initialization in this method implementation.
Returns
An integer error code. A non-zero value will indicate an initialization failure and result in node shutdown.
Implements mock_drivers::MockDriver.
Definition at line 51 of file MockCommsDriver.cpp.
{
  // driver publisher and subscriber
  addPassthroughPub<cav_msgs::ByteArray>(bag_prefix_ + inbound_binary_topic_, inbound_binary_topic_, false, 10);
  mock_driver_node_.addSub(outbound_sub_ptr_);
  return 0;
}
References mock_drivers::MockDriverNode::addSub(), mock_drivers::MockDriver::bag_prefix_, inbound_binary_topic_, mock_drivers::MockDriver::mock_driver_node_, and outbound_sub_ptr_.
outboundCallback()
void mock_drivers::MockCommsDriver::outboundCallback (const cav_msgs::ByteArray::ConstPtr & msg) const private
Definition at line 31 of file MockCommsDriver.cpp.
{
  ROS_DEBUG_STREAM("Received Byte Array of type: " << msg->message_type);
};
Referenced by MockCommsDriver().
Member Data Documentation
inbound_binary_topic_
const std::string mock_drivers::MockCommsDriver::inbound_binary_topic_ = "comms/inbound_binary_msg" private
Definition at line 30 of file MockCommsDriver.h.
Referenced by onRun().
outbound_binary_topic_
const std::string mock_drivers::MockCommsDriver::outbound_binary_topic_ = "comms/outbound_binary_msg" private
Definition at line 31 of file MockCommsDriver.h.
Referenced by MockCommsDriver().
outbound_sub_ptr_
ConstPtrRefROSCommsPtr<cav_msgs::ByteArray> mock_drivers::MockCommsDriver::outbound_sub_ptr_ private
Definition at line 28 of file MockCommsDriver.h.
Referenced by MockCommsDriver(), and onRun().
The documentation for this class was generated from the following files:
mock_drivers/rosbag_mock_drivers/include/rosbag_mock_drivers/MockCommsDriver.h
mock_drivers/rosbag_mock_drivers/src/MockCommsDriver.cpp