Carma-platform: subsystem_controllers::SSCDriverManager Class Reference
subsystem_controllers::SSCDriverManager Class Reference
The SSCDriverManager serves as a component to manage ROS1 SSC Driver in CARMA which is primarily in ROS2.
#include <ssc_driver_manager.hpp>
Public Member Functions
SSCDriverManager ()
Default constructor for SSCDriverManager with driver_timeout_ = 1000ms.
SSCDriverManager (const std::string &ssc_driver_name, const long driver_timeout)
Constructor for SSCDriverManager.
void update_driver_status (const carma_driver_msgs::msg::DriverStatus::SharedPtr msg, long current_time)
Update driver status.
bool is_ssc_driver_operational (long current_time)
Check if all critical drivers are operational.
carma_msgs::msg::SystemAlert get_latest_system_alert (long time_now, long start_up_timestamp, long startup_duration)
Handle the spin and publisher.
Protected Member Functions
FRIEND_TEST (DriverManagerTest, testCarTruckHandleSpinFatalUnknown)
Protected Attributes
std::string ssc_driver_name_ = ""
std::shared_ptr< Entry > latest_ssc_status_entry_ = std::make_shared<Entry>()
Latest SSC Status entry to keep track.
long driver_timeout_ = 1000
bool starting_up_ = true
Detailed Description
The SSCDriverManager serves as a component to manage ROS1 SSC Driver in CARMA which is primarily in ROS2.
Definition at line 45 of file ssc_driver_manager.hpp.
Constructor & Destructor Documentation
SSCDriverManager() [1/2]
subsystem_controllers::SSCDriverManager::SSCDriverManager ()
Default constructor for SSCDriverManager with driver_timeout_ = 1000ms.
Definition at line 29 of file ssc_driver_manager.cpp.
{}
SSCDriverManager() [2/2]
subsystem_controllers::SSCDriverManager::SSCDriverManager (const std::string & ssc_driver_name, const long driver_timeout)
Constructor for SSCDriverManager.
Parameters
ssc_driver_name The driver name which will be treated as required. A failure in this plugin will result in an exception
driver_timeout The timeout threshold for the driver
Definition at line 31 of file ssc_driver_manager.cpp.
: ssc_driver_name_(ssc_driver_name), driver_timeout_(driver_timeout)
{
}
Member Function Documentation
FRIEND_TEST()
subsystem_controllers::SSCDriverManager::FRIEND_TEST (DriverManagerTest , testCarTruckHandleSpinFatalUnknown) protected
get_latest_system_alert()
carma_msgs::msg::SystemAlert subsystem_controllers::SSCDriverManager::get_latest_system_alert (long time_now, long start_up_timestamp, long startup_duration)
Handle the spin and publisher.
Definition at line 36 of file ssc_driver_manager.cpp.
{
  carma_msgs::msg::SystemAlert alert;
  bool ssc_is_operational = is_ssc_driver_operational(time_now);
  if (ssc_is_operational) {
    starting_up_ = false;
    alert.description = "All essential drivers are ready";
    alert.type = carma_msgs::msg::SystemAlert::DRIVERS_READY;
    return alert;
  } else if (starting_up_ && (time_now - start_up_timestamp <= startup_duration)) {
    alert.description = "System is starting up...";
    alert.type = carma_msgs::msg::SystemAlert::NOT_READY;
    return alert;
  } else if (!ssc_is_operational) {
    alert.description = "SSC Failed";
    alert.type = carma_msgs::msg::SystemAlert::SHUTDOWN;
    return alert;
  } else {
    alert.description = "Unknown problem assessing SSC driver availability";
    alert.type = carma_msgs::msg::SystemAlert::FATAL;
    return alert;
  }
}
References is_ssc_driver_operational(), arbitrator::SHUTDOWN, and starting_up_.
is_ssc_driver_operational()
bool subsystem_controllers::SSCDriverManager::is_ssc_driver_operational (long current_time)
Check if all critical drivers are operational.
Definition at line 78 of file ssc_driver_manager.cpp.
{
  // Manual disable of ssc entry in case ssc wrapper is in ros2
  if (ssc_driver_name_.empty()) {
    return true;
  }
  // No entry recorded, then return false
  if (!latest_ssc_status_entry_) {
    return false;
  }
  RCLCPP_DEBUG_STREAM(
    rclcpp::get_logger("subsystem_controller"),
    "latest_ssc_status_entry_->name_: "
      << latest_ssc_status_entry_->name_ << ", current_time: " << current_time
      << ", latest_ssc_status_entry_->timestamp_: " << latest_ssc_status_entry_->timestamp_
      << ", difference: " << current_time - (latest_ssc_status_entry_->timestamp_));
  // Detect whether if available or timed out
  if (
    (!latest_ssc_status_entry_->available_) ||
    (current_time - latest_ssc_status_entry_->timestamp_ > driver_timeout_)) {
    return false;
  } else {
    return true;
  }
}
References driver_timeout_, latest_ssc_status_entry_, and ssc_driver_name_.
Referenced by get_latest_system_alert().
update_driver_status()
void subsystem_controllers::SSCDriverManager::update_driver_status (const carma_driver_msgs::msg::DriverStatus::SharedPtr msg, long current_time)
Update driver status.
Definition at line 62 of file ssc_driver_manager.cpp.
{
  // update driver status is only called in response to a message received on driver_discovery.
  // This topic is only being published in ros1. Check only SSC
  if (ssc_driver_name_ == msg->name) {
    Entry driver_status(
      msg->status == carma_driver_msgs::msg::DriverStatus::OPERATIONAL ||
        msg->status == carma_driver_msgs::msg::DriverStatus::DEGRADED,
      msg->name, current_time);
    latest_ssc_status_entry_ = std::make_shared<Entry>(driver_status);
  }
}
References latest_ssc_status_entry_, and ssc_driver_name_.
Member Data Documentation
driver_timeout_
long subsystem_controllers::SSCDriverManager::driver_timeout_ = 1000 protected
Definition at line 87 of file ssc_driver_manager.hpp.
Referenced by is_ssc_driver_operational().
latest_ssc_status_entry_
std::shared_ptr<Entry> subsystem_controllers::SSCDriverManager::latest_ssc_status_entry_ = std::make_shared<Entry>() protected
Latest SSC Status entry to keep track.
Definition at line 84 of file ssc_driver_manager.hpp.
Referenced by is_ssc_driver_operational(), and update_driver_status().
ssc_driver_name_
std::string subsystem_controllers::SSCDriverManager::ssc_driver_name_ = "" protected
Definition at line 81 of file ssc_driver_manager.hpp.
Referenced by is_ssc_driver_operational(), and update_driver_status().
starting_up_
bool subsystem_controllers::SSCDriverManager::starting_up_ = true protected
Definition at line 89 of file ssc_driver_manager.hpp.
Referenced by get_latest_system_alert().
The documentation for this class was generated from the following files:
subsystem_controllers/include/subsystem_controllers/drivers_controller/ssc_driver_manager.hpp
subsystem_controllers/src/drivers_controller/ssc_driver_manager.cpp