Carma-platform: mock_drivers::MockControllerDriver Class Reference
mock_drivers::MockControllerDriver Class Reference
Mock Controller driver. Implements controller service and feedback logic to support CARMA Platform Guidance State Machine.
#include <MockControllerDriver.h>
Public Member Functions
void vehicleCmdCallback (const autoware_msgs::VehicleCmd::ConstPtr &msg)
Callback for the vehicle command topic. This callback must be triggered at least once before the enable robotic service is called.
bool enableRoboticSrv (const cav_srvs::SetEnableRobotic::Request &req, cav_srvs::SetEnableRobotic::Response &res)
Callback for the enable robotic service. Triggering this callback will modify the RobotEnabled message output by this driver.
MockControllerDriver (bool dummy=false)
~MockControllerDriver ()
bool onSpin () override
Virtual method which child classes can override to add functionality which will occur during each spin loop. This means this function will be nominally called at the rate specified by getRate()
std::vector< DriverType > getDriverTypes () override
Pure Virtual method which child classes must override that returns the list of all driver types that class implements.
uint8_t getDriverStatus () override
Pure Virtual method. Returns an integer value which corresponds to the cav_msgs/DriverStatus enum felids representing the status of the driver.
unsigned int getRate () override
Pure virtual method that returns the desired operational rate of a child class.
Public Member Functions inherited from mock_drivers::MockDriver
virtual ~MockDriver ()=0
int run ()
A function to initialize the publishers and subsricers and start the node. In child classes, this function will trigger a call to onRun().
virtual std::vector< DriverType > getDriverTypes ()=0
Pure Virtual method which child classes must override that returns the list of all driver types that class implements.
virtual uint8_t getDriverStatus ()=0
Pure Virtual method. Returns an integer value which corresponds to the cav_msgs/DriverStatus enum felids representing the status of the driver.
virtual unsigned int getRate ()=0
Pure virtual method that returns the desired operational rate of a child class.
bool spinCallback ()
Callback which will be triggered at the rate specified by getRate(). This callback will also trigger the onSpin() method.
Protected Member Functions
int onRun () override
Pure virtual method which must be implemented by child classes. This method will be run once at startup. Child classes should add pub/sub initialization in this method implementation.
Protected Member Functions inherited from mock_drivers::MockDriver
virtual bool onSpin ()
Virtual method which child classes can override to add functionality which will occur during each spin loop. This means this function will be nominally called at the rate specified by getRate()
virtual int onRun ()=0
Pure virtual method which must be implemented by child classes. This method will be run once at startup. Child classes should add pub/sub initialization in this method implementation.
void driverDiscovery ()
Helper function to publish the driver discovery message.
MockDriverNode getMockDriverNode () const
Returns the mock driver node for the mock driver (used for testing)
template<typename T >
void addPassthroughPub (const std::string &sub_topic, const std::string &pub_topic, bool latch, size_t queue_size)
Function adds both a publisher and subscriber of the specified type. This means a passthrough subscription has been created. This version of the method should be used for message types which contain a Header at the field "header". The header field will be automatically updated to the current ros::Time::now().
template<typename T >
void addPassthroughPubNoHeader (const std::string &sub_topic, const std::string &pub_topic, bool latch, size_t queue_size)
Function adds both a publisher and subscriber of the specified type. This means a passthrough subscription has been created. This version of the method should be used for message types which does NOT contain a Header at the field "header".
Private Attributes
boost::shared_ptr< ROSComms< cav_msgs::RobotEnabled > > robot_status_ptr_
ConstPtrRefROSCommsPtr< autoware_msgs::VehicleCmd > vehicle_cmd_ptr_
boost::shared_ptr< ROSComms< cav_srvs::SetEnableRobotic::Request &, cav_srvs::SetEnableRobotic::Response & > > enable_robotic_ptr_
const std::string robot_status_topic_ = "controller/robot_status"
const std::string vehicle_cmd_topic_ = "vehicle_cmd"
const std::string enable_robotic_srv_ = "controller/enable_robotic"
bool robot_active_ = false
bool robot_enabled_ = false
Additional Inherited Members
Protected Types inherited from mock_drivers::MockDriver
template<class T >
using ConstPtr = boost::shared_ptr< const T >
template<class T >
using ConstPtrRef = const ConstPtr< T > &
template<class T >
using ROSCommsPtr = boost::shared_ptr< ROSComms< T > >
template<class T >
using ConstPtrRefROSComms = ROSComms< ConstPtrRef< T > >
template<class T >
using ConstPtrRefROSCommsPtr = ROSCommsPtr< ConstPtrRef< T > >
Protected Attributes inherited from mock_drivers::MockDriver
MockDriverNode mock_driver_node_
const std::string bag_prefix_ = "/bag/hardware_interface/"
const std::string driver_discovery_topic_ = "driver_discovery"
ROSCommsPtr< cav_msgs::DriverStatus > driver_discovery_pub_ptr_
ros::Time last_discovery_pub_ = ros::Time(0)
Detailed Description
Mock Controller driver. Implements controller service and feedback logic to support CARMA Platform Guidance State Machine.
Definition at line 27 of file MockControllerDriver.h.
Constructor & Destructor Documentation
MockControllerDriver()
mock_drivers::MockControllerDriver::MockControllerDriver (bool dummy = false)
Definition at line 51 of file MockControllerDriver.cpp.
{
  mock_driver_node_ = MockDriverNode(dummy);
  robot_status_ptr_ =
      boost::make_shared<ROSComms<cav_msgs::RobotEnabled>>(CommTypes::pub, false, 10, robot_status_topic_);
  vehicle_cmd_ptr_ = boost::make_shared<ConstPtrRefROSComms<autoware_msgs::VehicleCmd>>(
      std::bind(&MockControllerDriver::vehicleCmdCallback, this, std::placeholders::_1), CommTypes::sub, false, 10,
      vehicle_cmd_topic_);
  enable_robotic_ptr_ =
      boost::make_shared<ROSComms<cav_srvs::SetEnableRobotic::Request&, cav_srvs::SetEnableRobotic::Response&>>(
          std::bind(&MockControllerDriver::enableRoboticSrv, this, std::placeholders::_1, std::placeholders::_2),
          CommTypes::srv, enable_robotic_srv_);
}
References enable_robotic_ptr_, enable_robotic_srv_, enableRoboticSrv(), mock_drivers::MockDriver::mock_driver_node_, pub, robot_status_ptr_, robot_status_topic_, srv, sub, vehicle_cmd_ptr_, vehicle_cmd_topic_, and vehicleCmdCallback().
~MockControllerDriver()
mock_drivers::MockControllerDriver::~MockControllerDriver () inline
Definition at line 70 of file MockControllerDriver.h.
{};
Member Function Documentation
enableRoboticSrv()
bool mock_drivers::MockControllerDriver::enableRoboticSrv (const cav_srvs::SetEnableRobotic::Request & req, cav_srvs::SetEnableRobotic::Response & res)
Callback for the enable robotic service. Triggering this callback will modify the RobotEnabled message output by this driver.
Parameters
req The service request in message
res The service response out message
Returns
Flag idicating if the service was processed successfully.
Definition at line 36 of file MockControllerDriver.cpp.
{
  if (robot_enabled_ && req.set == cav_srvs::SetEnableRobotic::Request::ENABLE)
  {
    robot_active_ = true;
  }
  else
  {
    robot_active_ = false;
  }
  return true;
}
References robot_active_, and robot_enabled_.
Referenced by MockControllerDriver().
getDriverStatus()
uint8_t mock_drivers::MockControllerDriver::getDriverStatus () override virtual
Pure Virtual method. Returns an integer value which corresponds to the cav_msgs/DriverStatus enum felids representing the status of the driver.
Returns
Integer value which must match one of the enum fields in cav_msgs/DriverStatus
Implements mock_drivers::MockDriver.
Definition at line 26 of file MockControllerDriver.cpp.
{
  return cav_msgs::DriverStatus::OPERATIONAL;
}
getDriverTypes()
std::vector< DriverType > mock_drivers::MockControllerDriver::getDriverTypes () override virtual
Pure Virtual method which child classes must override that returns the list of all driver types that class implements.
Returns
A list of DriverType that defines the interfaces the implementing class provides
Implements mock_drivers::MockDriver.
Definition at line 21 of file MockControllerDriver.cpp.
{
  return { DriverType::CONTROLLER };
}
References CONTROLLER.
getRate()
unsigned int mock_drivers::MockControllerDriver::getRate () override virtual
Pure virtual method that returns the desired operational rate of a child class.
Returns
Spin rate in Hz
Implements mock_drivers::MockDriver.
Definition at line 79 of file MockControllerDriver.cpp.
{
  return 20;  // 20 Hz as default spin rate to match expected controller data rate
}
onRun()
int mock_drivers::MockControllerDriver::onRun () override protected virtual
Pure virtual method which must be implemented by child classes. This method will be run once at startup. Child classes should add pub/sub initialization in this method implementation.
Returns
An integer error code. A non-zero value will indicate an initialization failure and result in node shutdown.
Implements mock_drivers::MockDriver.
Definition at line 84 of file MockControllerDriver.cpp.
{
  // driver publisher, subscriber, and service
  mock_driver_node_.addPub(robot_status_ptr_);
  mock_driver_node_.addSub(vehicle_cmd_ptr_);
  mock_driver_node_.addSrv(enable_robotic_ptr_);
  return 0;
}
References mock_drivers::MockDriverNode::addPub(), mock_drivers::MockDriverNode::addSrv(), mock_drivers::MockDriverNode::addSub(), enable_robotic_ptr_, mock_drivers::MockDriver::mock_driver_node_, robot_status_ptr_, and vehicle_cmd_ptr_.
onSpin()
bool mock_drivers::MockControllerDriver::onSpin () override virtual
Virtual method which child classes can override to add functionality which will occur during each spin loop. This means this function will be nominally called at the rate specified by getRate()
Returns
Return false if this node should shutdown. True otherwise.
Reimplemented from mock_drivers::MockDriver.
Definition at line 68 of file MockControllerDriver.cpp.
{
  cav_msgs::RobotEnabled robot_status;
  robot_status.robot_active = robot_active_;
  robot_status.robot_enabled = robot_enabled_;
  mock_driver_node_.publishDataNoHeader<cav_msgs::RobotEnabled>(robot_status_topic_, robot_status);
  return true;
}
References mock_drivers::MockDriver::mock_driver_node_, mock_drivers::MockDriverNode::publishDataNoHeader(), robot_active_, robot_enabled_, and robot_status_topic_.
vehicleCmdCallback()
void mock_drivers::MockControllerDriver::vehicleCmdCallback (const autoware_msgs::VehicleCmd::ConstPtr & msg)
Callback for the vehicle command topic. This callback must be triggered at least once before the enable robotic service is called.
Parameters
msg The vehicle command to receive
Definition at line 31 of file MockControllerDriver.cpp.
{
  robot_enabled_ = true;  // If a command was received set the robot enabled status to true
}
References robot_enabled_.
Referenced by MockControllerDriver().
Member Data Documentation
enable_robotic_ptr_
boost::shared_ptr<ROSComms<cav_srvs::SetEnableRobotic::Request&, cav_srvs::SetEnableRobotic::Response&> > mock_drivers::MockControllerDriver::enable_robotic_ptr_ private
Definition at line 33 of file MockControllerDriver.h.
Referenced by MockControllerDriver(), and onRun().
enable_robotic_srv_
const std::string mock_drivers::MockControllerDriver::enable_robotic_srv_ = "controller/enable_robotic" private
Definition at line 40 of file MockControllerDriver.h.
Referenced by MockControllerDriver().
robot_active_
bool mock_drivers::MockControllerDriver::robot_active_ = false private
Definition at line 43 of file MockControllerDriver.h.
Referenced by enableRoboticSrv(), and onSpin().
robot_enabled_
bool mock_drivers::MockControllerDriver::robot_enabled_ = false private
Definition at line 44 of file MockControllerDriver.h.
Referenced by enableRoboticSrv(), onSpin(), and vehicleCmdCallback().
robot_status_ptr_
boost::shared_ptr<ROSComms<cav_msgs::RobotEnabled> > mock_drivers::MockControllerDriver::robot_status_ptr_ private
Definition at line 30 of file MockControllerDriver.h.
Referenced by MockControllerDriver(), and onRun().
robot_status_topic_
const std::string mock_drivers::MockControllerDriver::robot_status_topic_ = "controller/robot_status" private
Definition at line 36 of file MockControllerDriver.h.
Referenced by MockControllerDriver(), and onSpin().
vehicle_cmd_ptr_
ConstPtrRefROSCommsPtr<autoware_msgs::VehicleCmd> mock_drivers::MockControllerDriver::vehicle_cmd_ptr_ private
Definition at line 31 of file MockControllerDriver.h.
Referenced by MockControllerDriver(), and onRun().
vehicle_cmd_topic_
const std::string mock_drivers::MockControllerDriver::vehicle_cmd_topic_ = "vehicle_cmd" private
Definition at line 39 of file MockControllerDriver.h.
Referenced by MockControllerDriver().
The documentation for this class was generated from the following files:
mock_drivers/rosbag_mock_drivers/include/rosbag_mock_drivers/MockControllerDriver.h
mock_drivers/rosbag_mock_drivers/src/MockControllerDriver.cpp