Carma-platform: GenericValue< Encoding, Allocator > Class Template Reference
GenericValue< Encoding, Allocator > Class Template Reference
Represents a JSON value. Use Value for UTF8 encoding and default allocator.
#include <document.h>
Classes
struct ArrayData
union Data
struct Flag
union Number
struct ObjectData
struct ShortString
struct String
Public Types
typedef GenericMember< Encoding, Allocator > Member
Name-value pair in an object.
typedef Encoding EncodingType
Encoding type from template parameter.
typedef Allocator AllocatorType
Allocator type from template parameter.
typedef Encoding::Ch Ch
Character type derived from Encoding.
typedef GenericStringRef< Ch > StringRefType
Reference to a constant string.
typedef GenericMemberIterator< false, Encoding, Allocator >::Iterator MemberIterator
Member iterator for iterating in object.
typedef GenericMemberIterator< true, Encoding, Allocator >::Iterator ConstMemberIterator
Constant member iterator for iterating in object.
typedef GenericValue * ValueIterator
Value iterator for iterating in array.
typedef const GenericValue * ConstValueIterator
Constant value iterator for iterating in array.
typedef GenericValue< Encoding, Allocator > ValueType
Value type of itself.
typedef GenericArray< false, ValueType > Array
typedef GenericArray< true, ValueType > ConstArray
typedef GenericObject< false, ValueType > Object
typedef GenericObject< true, ValueType > ConstObject
Assignment operators
enum {
kBoolFlag = 0x0008 , kNumberFlag = 0x0010 , kIntFlag = 0x0020 , kUintFlag = 0x0040 ,
kInt64Flag = 0x0080 , kUint64Flag = 0x0100 , kDoubleFlag = 0x0200 , kStringFlag = 0x0400 ,
kCopyFlag = 0x0800 , kInlineStrFlag = 0x1000 , kNullFlag = kNullType , kTrueFlag = kTrueType | kBoolFlag ,
kFalseFlag = kFalseType | kBoolFlag , kNumberIntFlag = kNumberType | kNumberFlag | kIntFlag | kInt64Flag , kNumberUintFlag = kNumberType | kNumberFlag | kUintFlag | kUint64Flag | kInt64Flag , kNumberInt64Flag = kNumberType | kNumberFlag | kInt64Flag ,
kNumberUint64Flag = kNumberType | kNumberFlag | kUint64Flag , kNumberDoubleFlag = kNumberType | kNumberFlag | kDoubleFlag , kNumberAnyFlag = kNumberType | kNumberFlag | kIntFlag | kInt64Flag | kUintFlag | kUint64Flag | kDoubleFlag , kConstStringFlag = kStringType | kStringFlag ,
kCopyStringFlag = kStringType | kStringFlag | kCopyFlag , kShortStringFlag = kStringType | kStringFlag | kCopyFlag | kInlineStrFlag , kObjectFlag = kObjectType , kArrayFlag = kArrayType ,
kTypeMask = 0x07
}
template<typename , typename , typename >
class GenericDocument
static const SizeType kDefaultArrayCapacity = 16
static const SizeType kDefaultObjectCapacity = 16
Data data_
GenericValue & operator= (GenericValue &rhs) RAPIDJSON_NOEXCEPT
Assignment with move semantics.
GenericValue & operator= (StringRefType str) RAPIDJSON_NOEXCEPT
Assignment of constant string reference (no copy)
template<typename T >
RAPIDJSON_DISABLEIF_RETURN ((internal::IsPointer< T >),(GenericValue &)) operator
Assignment with primitive types.
RAPIDJSON_FORCEINLINE const Ch * GetStringPointer () const
RAPIDJSON_FORCEINLINE const Ch * SetStringPointer (const Ch *str)
RAPIDJSON_FORCEINLINE GenericValue * GetElementsPointer () const
RAPIDJSON_FORCEINLINE GenericValue * SetElementsPointer (GenericValue *elements)
RAPIDJSON_FORCEINLINE Member * GetMembersPointer () const
RAPIDJSON_FORCEINLINE Member * SetMembersPointer (Member *members)
void SetArrayRaw (GenericValue *values, SizeType count, Allocator &allocator)
void SetObjectRaw (Member *members, SizeType count, Allocator &allocator)
Initialize this value as object with initial data, without calling destructor.
void SetStringRaw (StringRefType s) RAPIDJSON_NOEXCEPT
Initialize this value as constant string, without calling destructor.
void SetStringRaw (StringRefType s, Allocator &allocator)
Initialize this value as copy string with initial data, without calling destructor.
void RawAssign (GenericValue &rhs) RAPIDJSON_NOEXCEPT
Assignment without calling destructor.
template<typename SourceAllocator >
bool StringEqual (const GenericValue< Encoding, SourceAllocator > &rhs) const
Constructors and destructor.
GenericValue () RAPIDJSON_NOEXCEPT
Default constructor creates a null value.
GenericValue (Type type) RAPIDJSON_NOEXCEPT
Constructor with JSON value type.
template<typename SourceAllocator >
GenericValue (const GenericValue< Encoding, SourceAllocator > &rhs, Allocator &allocator, bool copyConstStrings=false)
Explicit copy constructor (with allocator)
template<typename T >
GenericValue (T b, RAPIDJSON_ENABLEIF((internal::IsSame< bool, T >))) RAPIDJSON_NOEXCEPT
Constructor for boolean value.
GenericValue (int i) RAPIDJSON_NOEXCEPT
Constructor for int value.
GenericValue (unsigned u) RAPIDJSON_NOEXCEPT
Constructor for unsigned value.
GenericValue (int64_t i64) RAPIDJSON_NOEXCEPT
Constructor for int64_t value.
GenericValue (uint64_t u64) RAPIDJSON_NOEXCEPT
Constructor for uint64_t value.
GenericValue (double d) RAPIDJSON_NOEXCEPT
Constructor for double value.
GenericValue (float f) RAPIDJSON_NOEXCEPT
Constructor for float value.
GenericValue (const Ch *s, SizeType length) RAPIDJSON_NOEXCEPT
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (StringRefType s) RAPIDJSON_NOEXCEPT
Constructor for constant string (i.e. do not make a copy of string)
GenericValue (const Ch *s, SizeType length, Allocator &allocator)
Constructor for copy-string (i.e. do make a copy of string)
GenericValue (const Ch *s, Allocator &allocator)
Constructor for copy-string (i.e. do make a copy of string)
GenericValue (Array a) RAPIDJSON_NOEXCEPT
Constructor for Array.
GenericValue (Object o) RAPIDJSON_NOEXCEPT
Constructor for Object.
~GenericValue ()
Destructor.
GenericValue (const GenericValue &rhs)
Copy constructor is not permitted.
Detailed Description
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>>
class GenericValue< Encoding, Allocator >
Represents a JSON value. Use Value for UTF8 encoding and default allocator.
A JSON value can be one of 7 types. This class is a variant type supporting these types.
Use the Value if UTF8 and default allocator
Template Parameters
Encoding Encoding of the value. (Even non-string values need to have the same encoding in a document)
Allocator Allocator type for allocating memory of object, array and string.
Definition at line 551 of file document.h.
Member Typedef Documentation
AllocatorType
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef Allocator GenericValue< Encoding, Allocator >::AllocatorType
Allocator type from template parameter.
Definition at line 556 of file document.h.
Array
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef GenericArray<false, ValueType> GenericValue< Encoding, Allocator >::Array
Definition at line 564 of file document.h.
Ch
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef Encoding::Ch GenericValue< Encoding, Allocator >::Ch
Character type derived from Encoding.
Definition at line 557 of file document.h.
ConstArray
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef GenericArray<true, ValueType> GenericValue< Encoding, Allocator >::ConstArray
Definition at line 565 of file document.h.
ConstMemberIterator
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef GenericMemberIterator<true,Encoding,Allocator>::Iterator GenericValue< Encoding, Allocator >::ConstMemberIterator
Constant member iterator for iterating in object.
Definition at line 560 of file document.h.
ConstObject
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef GenericObject<true, ValueType> GenericValue< Encoding, Allocator >::ConstObject
Definition at line 567 of file document.h.
ConstValueIterator
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef const GenericValue* GenericValue< Encoding, Allocator >::ConstValueIterator
Constant value iterator for iterating in array.
Definition at line 562 of file document.h.
EncodingType
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef Encoding GenericValue< Encoding, Allocator >::EncodingType
Encoding type from template parameter.
Definition at line 555 of file document.h.
Member
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef GenericMember<Encoding, Allocator> GenericValue< Encoding, Allocator >::Member
Name-value pair in an object.
Definition at line 554 of file document.h.
MemberIterator
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef GenericMemberIterator<false,Encoding,Allocator>::Iterator GenericValue< Encoding, Allocator >::MemberIterator
Member iterator for iterating in object.
Definition at line 559 of file document.h.
Object
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef GenericObject<false, ValueType> GenericValue< Encoding, Allocator >::Object
Definition at line 566 of file document.h.
StringRefType
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef GenericStringRef<Ch> GenericValue< Encoding, Allocator >::StringRefType
Reference to a constant string.
Definition at line 558 of file document.h.
ValueIterator
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef GenericValue* GenericValue< Encoding, Allocator >::ValueIterator
Value iterator for iterating in array.
Definition at line 561 of file document.h.
ValueType
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> typedef GenericValue<Encoding, Allocator> GenericValue< Encoding, Allocator >::ValueType
Value type of itself.
Definition at line 563 of file document.h.
Member Enumeration Documentation
anonymous enum
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> anonymous enum
Enumerator
kBoolFlag
kNumberFlag
kIntFlag
kUintFlag
kInt64Flag
kUint64Flag
kDoubleFlag
kStringFlag
kCopyFlag
kInlineStrFlag
kNullFlag
kTrueFlag
kFalseFlag
kNumberIntFlag
kNumberUintFlag
kNumberInt64Flag
kNumberUint64Flag
kNumberDoubleFlag
kNumberAnyFlag
kConstStringFlag
kCopyStringFlag
kShortStringFlag
kObjectFlag
kArrayFlag
kTypeMask
Definition at line 1874 of file document.h.
         {
        kBoolFlag       = 0x0008,
        kNumberFlag     = 0x0010,
        kIntFlag        = 0x0020,
        kUintFlag       = 0x0040,
        kInt64Flag      = 0x0080,
        kUint64Flag     = 0x0100,
        kDoubleFlag     = 0x0200,
        kStringFlag     = 0x0400,
        kCopyFlag       = 0x0800,
        kInlineStrFlag  = 0x1000,
        // Initial flags of different types.
        kNullFlag = kNullType,
        kTrueFlag = kTrueType | kBoolFlag,
        kFalseFlag = kFalseType | kBoolFlag,
        kNumberIntFlag = kNumberType | kNumberFlag | kIntFlag | kInt64Flag,
        kNumberUintFlag = kNumberType | kNumberFlag | kUintFlag | kUint64Flag | kInt64Flag,
        kNumberInt64Flag = kNumberType | kNumberFlag | kInt64Flag,
        kNumberUint64Flag = kNumberType | kNumberFlag | kUint64Flag,
        kNumberDoubleFlag = kNumberType | kNumberFlag | kDoubleFlag,
        kNumberAnyFlag = kNumberType | kNumberFlag | kIntFlag | kInt64Flag | kUintFlag | kUint64Flag | kDoubleFlag,
        kConstStringFlag = kStringType | kStringFlag,
        kCopyStringFlag = kStringType | kStringFlag | kCopyFlag,
        kShortStringFlag = kStringType | kStringFlag | kCopyFlag | kInlineStrFlag,
        kObjectFlag = kObjectType,
        kArrayFlag = kArrayType,
        kTypeMask = 0x07
    };
Constructor & Destructor Documentation
GenericValue() [1/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue () inline
Default constructor creates a null value.
Definition at line 573 of file document.h.
: data_() { data_.f.flags = kNullFlag; }
References GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, and GenericValue< Encoding, Allocator >::kNullFlag.
Referenced by GenericValue< Encoding, Allocator >::GenericValue().
GenericValue() [2/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (const GenericValue< Encoding, Allocator > & rhs) private
Copy constructor is not permitted.
GenericValue() [3/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (Type type) inline explicit
Constructor with JSON value type.
This creates a Value of specified type with default content.
Parameters
type Type of the value.
Note
Default content for number is zero.
Definition at line 603 of file document.h.
                                                        : data_() {
        static const uint16_t defaultFlags[7] = {
            kNullFlag, kFalseFlag, kTrueFlag, kObjectFlag, kArrayFlag, kShortStringFlag,
            kNumberAnyFlag
        };
        RAPIDJSON_ASSERT(type >= kNullType && type <= kNumberType);
        data_.f.flags = defaultFlags[type];
        // Use ShortString to store empty string.
        if (type == kStringType)
            data_.ss.SetLength(0);
    }
References GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, GenericValue< Encoding, Allocator >::kArrayFlag, GenericValue< Encoding, Allocator >::kFalseFlag, GenericValue< Encoding, Allocator >::kNullFlag, kNullType, GenericValue< Encoding, Allocator >::kNumberAnyFlag, kNumberType, GenericValue< Encoding, Allocator >::kObjectFlag, GenericValue< Encoding, Allocator >::kShortStringFlag, kStringType, GenericValue< Encoding, Allocator >::kTrueFlag, RAPIDJSON_ASSERT, GenericValue< Encoding, Allocator >::ShortString::SetLength(), and GenericValue< Encoding, Allocator >::Data::ss.
GenericValue() [4/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> template<typename SourceAllocator > GenericValue< Encoding, Allocator >::GenericValue (const GenericValue< Encoding, SourceAllocator > & rhs, Allocator & allocator, bool copyConstStrings = false) inline
Explicit copy constructor (with allocator)
Creates a copy of a Value by using the given Allocator
Template Parameters
SourceAllocator allocator of rhs
Parameters
rhs Value to copy from (read-only)
allocator Allocator for allocating copied elements and buffers. Commonly use GenericDocument::GetAllocator().
copyConstStrings Force copying of constant strings (e.g. referencing an in-situ buffer)
See also
CopyFrom()
Definition at line 625 of file document.h.
{
        switch (rhs.GetType()) {
        case kObjectType: {
                SizeType count = rhs.data_.o.size;
                Member* lm = reinterpret_cast<Member*>(allocator.Malloc(count * sizeof(Member)));
                const typename GenericValue<Encoding,SourceAllocator>::Member* rm = rhs.GetMembersPointer();
                for (SizeType i = 0; i < count; i++) {
                    new (&lm[i].name) GenericValue(rm[i].name, allocator, copyConstStrings);
                    new (&lm[i].value) GenericValue(rm[i].value, allocator, copyConstStrings);
                }
                data_.f.flags = kObjectFlag;
                data_.o.size = data_.o.capacity = count;
                SetMembersPointer(lm);
            }
            break;
        case kArrayType: {
                SizeType count = rhs.data_.a.size;
                GenericValue* le = reinterpret_cast<GenericValue*>(allocator.Malloc(count * sizeof(GenericValue)));
                const GenericValue<Encoding,SourceAllocator>* re = rhs.GetElementsPointer();
                for (SizeType i = 0; i < count; i++)
                    new (&le[i]) GenericValue(re[i], allocator, copyConstStrings);
                data_.f.flags = kArrayFlag;
                data_.a.size = data_.a.capacity = count;
                SetElementsPointer(le);
            }
            break;
        case kStringType:
            if (rhs.data_.f.flags == kConstStringFlag && !copyConstStrings) {
                data_.f.flags = rhs.data_.f.flags;
                data_  = *reinterpret_cast<const Data*>(&rhs.data_);
            }
            else
                SetStringRaw(StringRef(rhs.GetString(), rhs.GetStringLength()), allocator);
            break;
        default:
            data_.f.flags = rhs.data_.f.flags;
            data_  = *reinterpret_cast<const Data*>(&rhs.data_);
            break;
        }
    }
References GenericValue< Encoding, Allocator >::GenericValue(), GenericValue< Encoding, Allocator >::Data::a, GenericValue< Encoding, Allocator >::ObjectData::capacity, GenericValue< Encoding, Allocator >::ArrayData::capacity, GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, GenericValue< Encoding, Allocator >::GetElementsPointer(), GenericValue< Encoding, Allocator >::GetMembersPointer(), process_bag::i, GenericValue< Encoding, Allocator >::kArrayFlag, kArrayType, GenericValue< Encoding, Allocator >::kConstStringFlag, GenericValue< Encoding, Allocator >::kObjectFlag, kObjectType, kStringType, GenericMember< Encoding, Allocator >::name, GenericValue< Encoding, Allocator >::Data::o, GenericValue< Encoding, Allocator >::SetElementsPointer(), GenericValue< Encoding, Allocator >::SetMembersPointer(), GenericValue< Encoding, Allocator >::SetStringRaw(), GenericValue< Encoding, Allocator >::ObjectData::size, GenericValue< Encoding, Allocator >::ArrayData::size, SizeType, StringRef(), GenericMember< Encoding, Allocator >::value, and value.
GenericValue() [5/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> template<typename T > GenericValue< Encoding, Allocator >::GenericValue (T b, RAPIDJSON_ENABLEIF((internal::IsSame< bool, T >))) inline explicit
Constructor for boolean value.
Parameters
b Boolean value
Note
This constructor is limited to real boolean values and rejects implicitly converted types like arbitrary pointers. Use an explicit cast to bool, if you want to construct a boolean JSON value in such cases.
Definition at line 674 of file document.h.
        : data_() {
            // safe-guard against failing SFINAE
            RAPIDJSON_STATIC_ASSERT((internal::IsSame<bool,T>::Value));
            data_.f.flags = b ? kTrueFlag : kFalseFlag;
    }
References GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, GenericValue< Encoding, Allocator >::kFalseFlag, GenericValue< Encoding, Allocator >::kTrueFlag, and RAPIDJSON_STATIC_ASSERT.
GenericValue() [6/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (int i) inline explicit
Constructor for int value.
Definition at line 685 of file document.h.
                                                    : data_() {
        data_.n.i64 = i;
        data_.f.flags = (i >= 0) ? (kNumberIntFlag | kUintFlag | kUint64Flag) : kNumberIntFlag;
    }
References GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, process_bag::i, GenericValue< Encoding, Allocator >::Number::i64, GenericValue< Encoding, Allocator >::kNumberIntFlag, GenericValue< Encoding, Allocator >::kUint64Flag, GenericValue< Encoding, Allocator >::kUintFlag, and GenericValue< Encoding, Allocator >::Data::n.
GenericValue() [7/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (unsigned u) inline explicit
Constructor for unsigned value.
Definition at line 691 of file document.h.
                                                         : data_() {
        data_.n.u64 = u;
        data_.f.flags = (u & 0x80000000) ? kNumberUintFlag : (kNumberUintFlag | kIntFlag | kInt64Flag);
    }
References GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, GenericValue< Encoding, Allocator >::kInt64Flag, GenericValue< Encoding, Allocator >::kIntFlag, GenericValue< Encoding, Allocator >::kNumberUintFlag, GenericValue< Encoding, Allocator >::Data::n, and GenericValue< Encoding, Allocator >::Number::u64.
GenericValue() [8/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (int64_t i64) inline explicit
Constructor for int64_t value.
Definition at line 697 of file document.h.
                                                          : data_() {
        data_.n.i64 = i64;
        data_.f.flags = kNumberInt64Flag;
        if (i64 >= 0) {
            data_.f.flags |= kNumberUint64Flag;
            if (!(static_cast<uint64_t>(i64) & RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0x00000000)))
                data_.f.flags |= kUintFlag;
            if (!(static_cast<uint64_t>(i64) & RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0x80000000)))
                data_.f.flags |= kIntFlag;
        }
        else if (i64 >= static_cast<int64_t>(RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0x80000000)))
            data_.f.flags |= kIntFlag;
    }
References GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, GenericValue< Encoding, Allocator >::Number::i64, GenericValue< Encoding, Allocator >::kIntFlag, GenericValue< Encoding, Allocator >::kNumberInt64Flag, GenericValue< Encoding, Allocator >::kNumberUint64Flag, GenericValue< Encoding, Allocator >::kUintFlag, GenericValue< Encoding, Allocator >::Data::n, and RAPIDJSON_UINT64_C2.
GenericValue() [9/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (uint64_t u64) inline explicit
Constructor for uint64_t value.
Definition at line 712 of file document.h.
                                                           : data_() {
        data_.n.u64 = u64;
        data_.f.flags = kNumberUint64Flag;
        if (!(u64 & RAPIDJSON_UINT64_C2(0x80000000, 0x00000000)))
            data_.f.flags |= kInt64Flag;
        if (!(u64 & RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0x00000000)))
            data_.f.flags |= kUintFlag;
        if (!(u64 & RAPIDJSON_UINT64_C2(0xFFFFFFFF, 0x80000000)))
            data_.f.flags |= kIntFlag;
    }
References GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, GenericValue< Encoding, Allocator >::kInt64Flag, GenericValue< Encoding, Allocator >::kIntFlag, GenericValue< Encoding, Allocator >::kNumberUint64Flag, GenericValue< Encoding, Allocator >::kUintFlag, GenericValue< Encoding, Allocator >::Data::n, RAPIDJSON_UINT64_C2, and GenericValue< Encoding, Allocator >::Number::u64.
GenericValue() [10/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (double d) inline explicit
Constructor for double value.
Definition at line 724 of file document.h.
: data_() { data_.n.d = d; data_.f.flags = kNumberDoubleFlag; }
References GenericValue< Encoding, Allocator >::Number::d, GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, GenericValue< Encoding, Allocator >::kNumberDoubleFlag, and GenericValue< Encoding, Allocator >::Data::n.
GenericValue() [11/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (float f) inline explicit
Constructor for float value.
Definition at line 727 of file document.h.
: data_() { data_.n.d = static_cast<double>(f); data_.f.flags = kNumberDoubleFlag; }
References GenericValue< Encoding, Allocator >::Number::d, GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, GenericValue< Encoding, Allocator >::kNumberDoubleFlag, and GenericValue< Encoding, Allocator >::Data::n.
GenericValue() [12/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (const Ch * s, SizeType length) inline
Constructor for constant string (i.e. do not make a copy of string)
Definition at line 730 of file document.h.
: data_() { SetStringRaw(StringRef(s, length)); }
References GenericValue< Encoding, Allocator >::SetStringRaw(), and StringRef().
GenericValue() [13/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (StringRefType s) inline explicit
Constructor for constant string (i.e. do not make a copy of string)
Definition at line 733 of file document.h.
: data_() { SetStringRaw(s); }
References GenericValue< Encoding, Allocator >::SetStringRaw().
GenericValue() [14/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (const Ch * s, SizeType length, Allocator & allocator) inline
Constructor for copy-string (i.e. do make a copy of string)
Definition at line 736 of file document.h.
: data_() { SetStringRaw(StringRef(s, length), allocator); }
References GenericValue< Encoding, Allocator >::SetStringRaw(), and StringRef().
GenericValue() [15/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (const Ch * s, Allocator & allocator) inline
Constructor for copy-string (i.e. do make a copy of string)
Definition at line 739 of file document.h.
: data_() { SetStringRaw(StringRef(s), allocator); }
References GenericValue< Encoding, Allocator >::SetStringRaw(), and StringRef().
GenericValue() [16/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (Array a) inline
Constructor for Array.
Parameters
a An array obtained by GetArray().
Note
Array is always pass-by-value.
the source array is moved into this value and the sourec array becomes empty.
Definition at line 754 of file document.h.
                                             : data_(a.value_.data_) {
        a.value_.data_ = Data();
        a.value_.data_.f.flags = kArrayFlag;
    }
References a, and GenericValue< Encoding, Allocator >::kArrayFlag.
GenericValue() [17/17]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::GenericValue (Object o) inline
Constructor for Object.
Parameters
o An object obtained by GetObject().
Note
Object is always pass-by-value.
the source object is moved into this value and the sourec object becomes empty.
Definition at line 765 of file document.h.
                                              : data_(o.value_.data_) {
        o.value_.data_ = Data();
        o.value_.data_.f.flags = kObjectFlag;
    }
References GenericValue< Encoding, Allocator >::kObjectFlag.
~GenericValue()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue< Encoding, Allocator >::~GenericValue () inline
Destructor.
Need to destruct elements of array, members of object, or copy-string.
Definition at line 773 of file document.h.
                    {
        if (Allocator::kNeedFree) { // Shortcut by Allocator's trait
            switch(data_.f.flags) {
            case kArrayFlag:
                {
                    GenericValue* e = GetElementsPointer();
                    for (GenericValue* v = e; v != e + data_.a.size; ++v)
                        v->~GenericValue();
                    Allocator::Free(e);
                }
                break;
            case kObjectFlag:
                for (MemberIterator m = MemberBegin(); m != MemberEnd(); ++m)
                    m->~Member();
                Allocator::Free(GetMembersPointer());
                break;
            case kCopyStringFlag:
                Allocator::Free(const_cast<Ch*>(GetStringPointer()));
                break;
            default:
                break;  // Do nothing for other types.
            }
        }
    }
References GenericValue< Encoding, Allocator >::Data::a, GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, GenericValue< Encoding, Allocator >::GetElementsPointer(), GenericValue< Encoding, Allocator >::GetMembersPointer(), GenericValue< Encoding, Allocator >::GetStringPointer(), GenericValue< Encoding, Allocator >::kArrayFlag, GenericValue< Encoding, Allocator >::kCopyStringFlag, GenericValue< Encoding, Allocator >::kObjectFlag, and GenericValue< Encoding, Allocator >::ArrayData::size.
Referenced by GenericValue< Encoding, Allocator >::operator=().
Member Function Documentation
GetElementsPointer()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> RAPIDJSON_FORCEINLINE GenericValue * GenericValue< Encoding, Allocator >::GetElementsPointer () const inline
Definition at line 1991 of file document.h.
{ return RAPIDJSON_GETPOINTER(GenericValue, data_.a.elements); }
References GenericValue< Encoding, Allocator >::Data::a, GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::ArrayData::elements, and RAPIDJSON_GETPOINTER.
Referenced by GenericValue< Encoding, Allocator >::GenericValue(), and GenericValue< Encoding, Allocator >::~GenericValue().
GetMembersPointer()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> RAPIDJSON_FORCEINLINE Member * GenericValue< Encoding, Allocator >::GetMembersPointer () const inline
Definition at line 1993 of file document.h.
{ return RAPIDJSON_GETPOINTER(Member, data_.o.members); }
References GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::ObjectData::members, GenericValue< Encoding, Allocator >::Data::o, and RAPIDJSON_GETPOINTER.
Referenced by GenericValue< Encoding, Allocator >::GenericValue(), and GenericValue< Encoding, Allocator >::~GenericValue().
GetStringPointer()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> RAPIDJSON_FORCEINLINE const Ch * GenericValue< Encoding, Allocator >::GetStringPointer () const inline
Definition at line 1989 of file document.h.
{ return RAPIDJSON_GETPOINTER(Ch, data_.s.str); }
References GenericValue< Encoding, Allocator >::data_, RAPIDJSON_GETPOINTER, GenericValue< Encoding, Allocator >::Data::s, and GenericValue< Encoding, Allocator >::String::str.
Referenced by GenericValue< Encoding, Allocator >::~GenericValue().
operator=() [1/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue & GenericValue< Encoding, Allocator >::operator= (GenericValue< Encoding, Allocator > & rhs) inline
Assignment with move semantics.
Parameters
rhs Source of the assignment. It will become a null value after assignment.
Definition at line 809 of file document.h.
{
        RAPIDJSON_ASSERT(this != &rhs);
        this->~GenericValue();
        RawAssign(rhs);
        return *this;
    }
References GenericValue< Encoding, Allocator >::~GenericValue(), RAPIDJSON_ASSERT, and GenericValue< Encoding, Allocator >::RawAssign().
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::ParseStream(), and GenericDocument< Encoding, Allocator, StackAllocator >::Populate().
operator=() [2/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> GenericValue & GenericValue< Encoding, Allocator >::operator= (StringRefType str) inline
Assignment of constant string reference (no copy)
Parameters
str Constant string reference to be assigned
Note
This overload is needed to avoid clashes with the generic primitive type assignment overload below.
See also
GenericStringRef, operator=(T)
Definition at line 828 of file document.h.
{
        GenericValue s(str);
        return *this = s;
    }
RAPIDJSON_DISABLEIF_RETURN()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> template<typename T > GenericValue< Encoding, Allocator >::RAPIDJSON_DISABLEIF_RETURN ((internal::IsPointer< T >) , (GenericValue< Encoding, Allocator > &))
Assignment with primitive types.
Template Parameters
T Either Type, int, unsigned, int64_t, uint64_t
Parameters
value The value to be assigned.
Note
The source type T explicitly disallows all pointer types, especially (const) Ch*. This helps avoiding implicitly referencing character strings with insufficient lifetime, use SetString(const Ch*, Allocator&) (for copying) or StringRef() (to explicitly mark the pointer as constant) instead. All other pointer types would implicitly convert to bool, use SetBool() instead. Set boolean value
References value.
RawAssign()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void GenericValue< Encoding, Allocator >::RawAssign (GenericValue< Encoding, Allocator > & rhs) inline
Assignment without calling destructor.
Definition at line 2047 of file document.h.
{
        data_ = rhs.data_;
        // data_.f.flags = rhs.data_.f.flags;
        rhs.data_.f.flags = kNullFlag;
    }
References GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, and GenericValue< Encoding, Allocator >::kNullFlag.
Referenced by GenericValue< Encoding, Allocator >::operator=().
SetArrayRaw()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void GenericValue< Encoding, Allocator >::SetArrayRaw (GenericValue< Encoding, Allocator > * values, SizeType count, Allocator & allocator) inline
Definition at line 1997 of file document.h.
{
        data_.f.flags = kArrayFlag;
        if (count) {
            GenericValue* e = static_cast<GenericValue*>(allocator.Malloc(count * sizeof(GenericValue)));
            SetElementsPointer(e);
            std::memcpy(e, values, count * sizeof(GenericValue));
        }
        else
            SetElementsPointer(0);
        data_.a.size = data_.a.capacity = count;
    }
References GenericValue< Encoding, Allocator >::Data::a, GenericValue< Encoding, Allocator >::ArrayData::capacity, GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, GenericValue< Encoding, Allocator >::kArrayFlag, GenericValue< Encoding, Allocator >::SetElementsPointer(), and GenericValue< Encoding, Allocator >::ArrayData::size.
SetElementsPointer()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> RAPIDJSON_FORCEINLINE GenericValue * GenericValue< Encoding, Allocator >::SetElementsPointer (GenericValue< Encoding, Allocator > * elements) inline
Definition at line 1992 of file document.h.
{ return RAPIDJSON_SETPOINTER(GenericValue, data_.a.elements, elements); }
References GenericValue< Encoding, Allocator >::Data::a, GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::ArrayData::elements, and RAPIDJSON_SETPOINTER.
Referenced by GenericValue< Encoding, Allocator >::GenericValue(), and GenericValue< Encoding, Allocator >::SetArrayRaw().
SetMembersPointer()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> RAPIDJSON_FORCEINLINE Member * GenericValue< Encoding, Allocator >::SetMembersPointer (Member * members) inline
Definition at line 1994 of file document.h.
{ return RAPIDJSON_SETPOINTER(Member, data_.o.members, members); }
References GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::ObjectData::members, GenericValue< Encoding, Allocator >::Data::o, and RAPIDJSON_SETPOINTER.
Referenced by GenericValue< Encoding, Allocator >::GenericValue(), and GenericValue< Encoding, Allocator >::SetObjectRaw().
SetObjectRaw()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void GenericValue< Encoding, Allocator >::SetObjectRaw (Member * members, SizeType count, Allocator & allocator) inline
Initialize this value as object with initial data, without calling destructor.
Definition at line 2010 of file document.h.
{
        data_.f.flags = kObjectFlag;
        if (count) {
            Member* m = static_cast<Member*>(allocator.Malloc(count * sizeof(Member)));
            SetMembersPointer(m);
            std::memcpy(m, members, count * sizeof(Member));
        }
        else
            SetMembersPointer(0);
        data_.o.size = data_.o.capacity = count;
    }
References GenericValue< Encoding, Allocator >::ObjectData::capacity, GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, GenericValue< Encoding, Allocator >::kObjectFlag, GenericValue< Encoding, Allocator >::Data::o, GenericValue< Encoding, Allocator >::SetMembersPointer(), and GenericValue< Encoding, Allocator >::ObjectData::size.
SetStringPointer()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> RAPIDJSON_FORCEINLINE const Ch * GenericValue< Encoding, Allocator >::SetStringPointer (const Ch * str) inline
Definition at line 1990 of file document.h.
{ return RAPIDJSON_SETPOINTER(Ch, data_.s.str, str); }
References GenericValue< Encoding, Allocator >::data_, RAPIDJSON_SETPOINTER, GenericValue< Encoding, Allocator >::Data::s, and GenericValue< Encoding, Allocator >::String::str.
Referenced by GenericValue< Encoding, Allocator >::SetStringRaw().
SetStringRaw() [1/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void GenericValue< Encoding, Allocator >::SetStringRaw (StringRefType s) inline
Initialize this value as constant string, without calling destructor.
Definition at line 2023 of file document.h.
{
        data_.f.flags = kConstStringFlag;
        SetStringPointer(s);
        data_.s.length = s.length;
    }
References GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, GenericValue< Encoding, Allocator >::kConstStringFlag, GenericValue< Encoding, Allocator >::String::length, GenericValue< Encoding, Allocator >::Data::s, and GenericValue< Encoding, Allocator >::SetStringPointer().
Referenced by GenericValue< Encoding, Allocator >::GenericValue().
SetStringRaw() [2/2]
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void GenericValue< Encoding, Allocator >::SetStringRaw (StringRefType s, Allocator & allocator) inline
Initialize this value as copy string with initial data, without calling destructor.
Definition at line 2030 of file document.h.
{
        Ch* str = 0;
        if (ShortString::Usable(s.length)) {
            data_.f.flags = kShortStringFlag;
            data_.ss.SetLength(s.length);
            str = data_.ss.str;
        } else {
            data_.f.flags = kCopyStringFlag;
            data_.s.length = s.length;
            str = static_cast<Ch *>(allocator.Malloc((s.length + 1) * sizeof(Ch)));
            SetStringPointer(str);
        }
        std::memcpy(str, s, s.length * sizeof(Ch));
        str[s.length] = '\0';
    }
References GenericValue< Encoding, Allocator >::data_, GenericValue< Encoding, Allocator >::Data::f, GenericValue< Encoding, Allocator >::Flag::flags, GenericValue< Encoding, Allocator >::kCopyStringFlag, GenericValue< Encoding, Allocator >::kShortStringFlag, GenericStringRef< CharType >::length, GenericValue< Encoding, Allocator >::String::length, GenericValue< Encoding, Allocator >::Data::s, GenericValue< Encoding, Allocator >::ShortString::SetLength(), GenericValue< Encoding, Allocator >::SetStringPointer(), GenericValue< Encoding, Allocator >::Data::ss, GenericValue< Encoding, Allocator >::ShortString::str, and GenericValue< Encoding, Allocator >::ShortString::Usable().
StringEqual()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> template<typename SourceAllocator > bool GenericValue< Encoding, Allocator >::StringEqual (const GenericValue< Encoding, SourceAllocator > & rhs) const inline
Definition at line 2054 of file document.h.
{
        RAPIDJSON_ASSERT(IsString());
        RAPIDJSON_ASSERT(rhs.IsString());
        const SizeType len1 = GetStringLength();
        const SizeType len2 = rhs.GetStringLength();
        if(len1 != len2) { return false; }
        const Ch* const str1 = GetString();
        const Ch* const str2 = rhs.GetString();
        if(str1 == str2) { return true; } // fast path for constant string
        return (std::memcmp(str1, str2, sizeof(Ch) * len1) == 0);
    }
References RAPIDJSON_ASSERT, and SizeType.
Friends And Related Function Documentation
GenericDocument
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> template<typename , typename , typename > friend class GenericDocument friend
Definition at line 1872 of file document.h.
Member Data Documentation
data_
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> Data GenericValue< Encoding, Allocator >::data_
Definition at line 2069 of file document.h.
Referenced by GenericValue< Encoding, Allocator >::GenericValue(), GenericValue< Encoding, Allocator >::~GenericValue(), GenericValue< Encoding, Allocator >::GetElementsPointer(), GenericValue< Encoding, Allocator >::GetMembersPointer(), GenericValue< Encoding, Allocator >::GetStringPointer(), GenericValue< Encoding, Allocator >::RawAssign(), GenericValue< Encoding, Allocator >::SetArrayRaw(), GenericValue< Encoding, Allocator >::SetElementsPointer(), GenericValue< Encoding, Allocator >::SetMembersPointer(), GenericValue< Encoding, Allocator >::SetObjectRaw(), GenericValue< Encoding, Allocator >::SetStringPointer(), and GenericValue< Encoding, Allocator >::SetStringRaw().
kDefaultArrayCapacity
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> const SizeType GenericValue< Encoding, Allocator >::kDefaultArrayCapacity = 16 static
Definition at line 1905 of file document.h.
kDefaultObjectCapacity
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> const SizeType GenericValue< Encoding, Allocator >::kDefaultObjectCapacity = 16 static
Definition at line 1906 of file document.h.
The documentation for this class was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/document.h