Carma-platform: NS3Adapter Class Reference
NS3Adapter Class Reference
Is the class responsible for the NS-3 Adapter driver.
#include <ns-3_adapter.h>
Classes
struct WaveConfigStruct
Public Member Functions
NS3Adapter (int argc, char **argv)
constructor
~NS3Adapter ()
void onConnectHandler ()
Handles the NS-3 onConnect Event.
void onDisconnectHandler ()
Handles the NS-3 onDisconnect Event.
void onMessageReceivedHandler (const std::vector< uint8_t > &data, uint16_t id)
Handles messages received from the NS-3 Client.
std::vector< uint8_t > packMessage (const cav_msgs::ByteArray &message)
Packs an outgoing message into J2375 standard.
void onOutboundMessage (const cav_msgs::ByteArrayPtr &message)
Handles outbound messages from the ROS network.
bool sendMessageSrv (cav_srvs::SendMessage::Request &req, cav_srvs::SendMessage::Response &res)
Message sending service.
void sendMessageFromQueue ()
Sends a message from the queue of outbound messages.
void loadWaveConfig (const std::string &fileName)
Callback for dynamic reconfig service.
void pose_cb (geometry_msgs::PoseStamped pose_msg)
std::string compose_handshake_msg (std::string veh_id, std::string role_id, std::string port, std::string ip)
Composes the json string for handshake with ns-3.
void broadcastHandshakemsg (const std::string &msg_string)
cav_msgs::DriverStatus getDriverStatus ()
std::deque< std::shared_ptr< std::vector< uint8_t > > > getMsgQueue ()
std::string uint8_vector_to_hex_string (const std::vector< uint8_t > &v)
converts a uint8_t vector to an ascii representation
Public Member Functions inherited from cav::DriverApplication
DriverApplication (int argc, char **argv, std::string name)
virtual ~DriverApplication ()
virtual int run () final
Starts the application.
Private Member Functions
virtual void initialize () override
Initializes ROS context for this node.
virtual void post_spin () override
Called by the base DriverApplication class after spin.
virtual void pre_spin () override
Called by the base DriverApplication class prior to Spin.
virtual void shutdown () override
virtual std::vector< std::string > & get_api () override
Called by the base DriverApplication class to fetch this implementation's api.
Private Attributes
std::vector< std::string > api_
ros::Publisher comms_pub_
ros::Subscriber comms_sub_
ros::Subscriber pose_sub_
ros::ServiceServer comms_srv_
std::shared_ptr< ros::NodeHandle > comms_api_nh_
geometry_msgs::PoseStamped pose_msg_
std::string vehicle_id_
std::string role_id_ = "ego_vehicle"
std::string port_ = "2000"
std::string host_ip_ = "127.0.0.1"
std::string ns3_address_ = "192.168.88.40"
int ns3_registration_port_ = 1000
std::mutex cfg_mutex_
boost::recursive_mutex dyn_cfg_mutex_
NS3Client ns3_client_
std::deque< std::shared_ptr< std::vector< uint8_t > > > send_msg_queue_
bool connecting_ = false
std::shared_ptr< std::thread > connect_thread_
boost::system::error_code ns3_client_error_
std::vector< WaveConfigStruct > wave_cfg_items_
uint32_t queue_size_
Additional Inherited Members
Protected Member Functions inherited from cav::DriverApplication
virtual void setStatus (cav_msgs::DriverStatus status) final
Sets the status of the DriverApplication.
virtual cav_msgs::DriverStatus getStatus () final
Get's status.
Protected Attributes inherited from cav::DriverApplication
int spin_rate
should be set prior to DriverApplication beginning its control loop. Ideally inheriting classes should set the spin_rate be set within the DriverApplication::initialize() function
std::shared_ptr< ros::NodeHandle > pnh_
ROS NodeHandle within the private ("~") namespace.
std::shared_ptr< ros::NodeHandle > nh_
ROS NodeHandle within the node root namespace.
Detailed Description
Is the class responsible for the NS-3 Adapter driver.
Definition at line 47 of file ns-3_adapter.h.
Constructor & Destructor Documentation
NS3Adapter()
NS3Adapter::NS3Adapter (int argc, char ** argv)
constructor
Parameters
argc - command line argument count
argv - command line arguments
Definition at line 22 of file ns-3_adapter.cpp.
                                            : cav::DriverApplication(argc, argv, "ns3")
{
    queue_size_ = 1000;
    cav_msgs::DriverStatus status;
    status.status = cav_msgs::DriverStatus::OFF;
    status.comms = true;
    setStatus(status);
}
References lightbar_manager::OFF, queue_size_, and cav::DriverApplication::setStatus().
~NS3Adapter()
NS3Adapter::~NS3Adapter () inline
Definition at line 75 of file ns-3_adapter.h.
{ shutdown(); }
References shutdown().
Member Function Documentation
broadcastHandshakemsg()
void NS3Adapter::broadcastHandshakemsg (const std::string & msg_string)
Definition at line 462 of file ns-3_adapter.cpp.
{
    auto msg_vector = std::vector<uint8_t>(msg_string.begin(), msg_string.end());
    std::shared_ptr<std::vector<uint8_t>> message_content = std::make_shared<std::vector<uint8_t>>(std::move(msg_vector));
    std::string addres;
    unsigned short remote_port;
    bool success = ns3_client_.registermsg(message_content, ns3_address_, ns3_registration_port_, ns3_registration_port_);
    if (!success) {
        ROS_WARN_STREAM("Handshake Message send failed");
    }
    else {
        ROS_DEBUG("Handshake Message successfully");
    }
}
References ns3_address_, ns3_client_, ns3_registration_port_, and NS3Client::registermsg().
Referenced by initialize().
compose_handshake_msg()
std::string NS3Adapter::compose_handshake_msg (std::string veh_id, std::string role_id, std::string port, std::string ip)
Composes the json string for handshake with ns-3.
Parameters
fileName
Returns
the json string for the msg
Definition at line 423 of file ns-3_adapter.cpp.
{
    // document is the root of a json message
    rapidjson::Document document;
    // define the document as an object rather than an array
    document.SetObject();
    // create a rapidjson array type with similar syntax to std::vector
    rapidjson::Value array(rapidjson::kArrayType);
    // must pass an allocator when the object may need to allocate memory
    rapidjson::Document::AllocatorType& allocator = document.GetAllocator();
    rapidjson::Value idtextPart;
    idtextPart.SetString(veh_id.c_str(), allocator);
    document.AddMember("vehicle_id", idtextPart, allocator);
    rapidjson::Value roletextPart;
    roletextPart.SetString(role_id.c_str(), allocator);
    document.AddMember("role_id", roletextPart, allocator);
    rapidjson::Value porttextPart;
    porttextPart.SetString(port.c_str(), allocator);
    document.AddMember("port", porttextPart, allocator);
    rapidjson::Value iptextPart;
    iptextPart.SetString(ip.c_str(), allocator);
    document.AddMember("host_ip", iptextPart, allocator);
    rapidjson::StringBuffer strbuf;
    rapidjson::Writer<rapidjson::StringBuffer> writer(strbuf);
    document.Accept(writer);
    std::string strbufstring = strbuf.GetString();
    return strbufstring;
}
References kArrayType.
Referenced by initialize().
get_api()
virtual std::vector< std::string > & NS3Adapter::get_api () inline override private virtual
Called by the base DriverApplication class to fetch this implementation's api.
The API is a list of fully scoped names to topics and services specified by the CAV Platform architecture
Returns
list of api
Implements cav::DriverApplication.
Definition at line 147 of file ns-3_adapter.h.
{ return api_; }
References api_.
getDriverStatus()
cav_msgs::DriverStatus NS3Adapter::getDriverStatus ()
Definition at line 479 of file ns-3_adapter.cpp.
{
    return getStatus();
}
References cav::DriverApplication::getStatus().
getMsgQueue()
std::deque< std::shared_ptr< std::vector< uint8_t > > > NS3Adapter::getMsgQueue ()
Definition at line 484 of file ns-3_adapter.cpp.
{
    return send_msg_queue_;
}
References send_msg_queue_.
initialize()
void NS3Adapter::initialize () override private virtual
Initializes ROS context for this node.
Establishes the connection to the NS-3 Adapter. Sets up pertinent events and corresponding topics
Implements cav::DriverApplication.
Definition at line 32 of file ns-3_adapter.cpp.
{
    std::string wave_cfg_file;
    ros::NodeHandle pnh("~");
    pnh.param<std::string>("wave_cfg_file",wave_cfg_file,"etc/wave.json");
    //pnh.param<int>("listening_port",config_.listening_port, 5398);
    //pnh.param<int>("dsrc_listening_port",config_.dsrc_listening_port, 1516);
    //pnh.param<std::string>("dsrc_address",config_.dsrc_address, "169.254.1.1");
    loadWaveConfig(wave_cfg_file);
    //comms_api_nh_.reset(new ros::NodeHandle("comms"));
    //dyn_cfg_server_.reset(new dynamic_reconfigure::Server<dsrc::DSRCConfig>(dyn_cfg_mutex_));
    //dyn_cfg_server_->updateConfig(config_);
    //dyn_cfg_server_->setCallback([this](dsrc::DSRCConfig & cfg, uint32_t level) { dynReconfigCB(cfg, level); });
    // Start the handshake
    pnh_->getParam("vehicle_id", vehicle_id_);
    pnh_->getParam("carla/ego_vehicle/role_name", role_id_);
    pnh.param<std::string>("ns-3_address", ns3_address_, "192.168.88.40");
    pnh.param<int>("ns-3_registration_port", ns3_registration_port_, 1000);
    std::string handshake_msg = compose_handshake_msg(vehicle_id_, role_id_, port_, host_ip_);
    broadcastHandshakemsg(handshake_msg);
    //Setup connection handlers
    ns3_client_error_.clear();
    ns3_client_.onConnect.connect([this]() { onConnectHandler(); });
    ns3_client_.onDisconnect.connect([this]() { onDisconnectHandler(); });
    ns3_client_.onError.connect([this](const boost::system::error_code& err){ns3_client_error_ = err;});
    //Setup the ROS API
    std::string node_name = ros::this_node::getName();
    api_.clear();
    //Comms Subscriber
    comms_sub_ = comms_api_nh_->subscribe("outbound_binary_msg", queue_size_, &NS3Adapter::onOutboundMessage, this);
    api_.push_back(comms_sub_.getTopic());
    //Comms Publisher
    comms_pub_ = comms_api_nh_->advertise<cav_msgs::ByteArray>("inbound_binary_msg", queue_size_);
    api_.push_back(comms_pub_.getTopic());
    //Comms Service
    comms_srv_ = comms_api_nh_->advertiseService("send", &NS3Adapter::sendMessageSrv, this);
    api_.push_back(comms_srv_.getService());
    pose_sub_ = pnh_->subscribe("current_pose", 1, &NS3Adapter::pose_cb, this);
    ns3_client_.onMessageReceived.connect([this](std::vector<uint8_t> const &msg, uint16_t id) {onMessageReceivedHandler(msg, id); });
    spin_rate = 50;
}
References api_, broadcastHandshakemsg(), comms_api_nh_, comms_pub_, comms_srv_, comms_sub_, compose_handshake_msg(), host_ip_, loadWaveConfig(), ns3_address_, ns3_client_, ns3_client_error_, ns3_registration_port_, NS3Client::onConnect, onConnectHandler(), NS3Client::onDisconnect, onDisconnectHandler(), NS3Client::onError, NS3Client::onMessageReceived, onMessageReceivedHandler(), onOutboundMessage(), cav::DriverApplication::pnh_, port_, pose_cb(), pose_sub_, queue_size_, role_id_, sendMessageSrv(), cav::DriverApplication::spin_rate, and vehicle_id_.
loadWaveConfig()
void NS3Adapter::loadWaveConfig (const std::string & fileName)
Callback for dynamic reconfig service.
Parameters
cfg
level
void dynReconfigCB(dsrc::DSRCConfig & cfg, uint32_t level);
Loads the wave file with the given name for configuring WAVE message ids with channel and PSID
Parameters
fileName
Definition at line 319 of file ns-3_adapter.cpp.
{
    ROS_DEBUG_STREAM("Loading wave config");
    const char* schema = "{\n"
                         " \"$schema\":\"http://json-schema.org/draft-06/schema\",\n"
                         " \"title\":\"Wave Config Schema\",\n"
                         " \"description\":\"A simple schema to describe DSRC/Wave messages\",\n"
                         "  \"type\": \"array\",\n"
                         "  \"items\": {\n"
                         "    \"type\": \"object\",\n"
                         "    \"properties\": {\n"
                         "      \"name\": {\n"
                         "        \"description\": \"message type - abbreviated name\",\n"
                         "        \"type\": \"string\"\n"
                         "      },\n"
                         "      \"psid\": {\n"
                         "        \"description\": \"psid assigned to message type in decimal\",\n"
                         "        \"type\": \"string\"\n"
                         "      },\n"
                         "      \"ns3_id\": {\n"
                         "        \"description\": \"J2735 NS-3 id assigned to message type in decimal\",\n"
                         "        \"type\": \"string\"\n"
                         "      },\n"
                         "      \"channel\": {\n"
                         "        \"description\": \"DSRC radio channel assigned to message type in decimal\",\n"
                         "        \"type\": \"string\"\n"
                         "      },\n"
                         "      \"priority\": {\n"
                         "        \"description\": \"WSM Priotiy to use assigned to message type in decimal\",\n"
                         "        \"type\":\"string\"\n"
                         "      }\n"
                         "    },\n"
                         "    \"required\":[\"name\",\"psid\",\"ns3_id\",\"channel\",\"priority\"]"
                         "  }\n"
                         "}\n";
    std::ifstream file;
    try
    {
        file.open(fileName);
    }
    catch (std::exception& e)
    {
        ROS_ERROR_STREAM("Unable to open file : " << fileName << ", exception: " << e.what());
        return;
    }
    rapidjson::Document sd;
    if(sd.Parse(schema).HasParseError())
    {
        ROS_ERROR_STREAM("Invalid Wave Config Schema");
        return;
    }
    rapidjson::SchemaDocument schemaDocument(sd);
    rapidjson::Document doc;
    rapidjson::IStreamWrapper isw(file);
    if(doc.ParseStream(isw).HasParseError())
    {
        ROS_ERROR_STREAM("Error Parsing Wave Config");
        return;
    }
    rapidjson::SchemaValidator validator(schemaDocument);
    if(!doc.Accept(validator))
    {
        ROS_ERROR_STREAM("Wave Config improperly formatted");
        return;
    }
    for(auto& it : doc.GetArray())
    {
        auto entry = it.GetObject();
        wave_cfg_items_.emplace_back(entry["name"].GetString(),
                                     entry["psid"].GetString(),
                                     entry["ns3_id"].GetString(),
                                     entry["channel"].GetString(),
                                     entry["priority"].GetString());
    }
}
References guidance_plugin_validator.main::validator, and wave_cfg_items_.
Referenced by initialize().
onConnectHandler()
void NS3Adapter::onConnectHandler ()
Handles the NS-3 onConnect Event.
Establishes status of the node
Definition at line 89 of file ns-3_adapter.cpp.
{
    ROS_INFO_STREAM("NS-3 Adapter Connected");
    cav_msgs::DriverStatus status = getStatus();
    status.status = cav_msgs::DriverStatus::OPERATIONAL;
    setStatus(status);
}
References cav::DriverApplication::getStatus(), and cav::DriverApplication::setStatus().
Referenced by initialize().
onDisconnectHandler()
void NS3Adapter::onDisconnectHandler ()
Handles the NS-3 onDisconnect Event.
On Disconnect this node will enter a reconnect loop attempting to reconnect
Definition at line 96 of file ns-3_adapter.cpp.
{
    cav_msgs::DriverStatus status = getStatus();
    status.status = cav_msgs::DriverStatus::OFF;
    setStatus(status);
    ROS_WARN_STREAM("NS-3 Adapter Disconnected");
}
References cav::DriverApplication::getStatus(), lightbar_manager::OFF, and cav::DriverApplication::setStatus().
Referenced by initialize().
onMessageReceivedHandler()
void NS3Adapter::onMessageReceivedHandler (const std::vector< uint8_t > & data, uint16_t id)
Handles messages received from the NS-3 Client.
Populates a ROS message with the contents of the incoming OBU message, and publishes to the ROS 'inbound_binary_msg' topic.
Populates a ROS message with the contents of the incoming OBU message, and publishes to the ROS 'recv' topic.
Definition at line 109 of file ns-3_adapter.cpp.
{
    // Create and populate the message
    auto it = std::find_if(wave_cfg_items_.begin(),wave_cfg_items_.end(),[id](const WaveConfigStruct& entry)
{
                                                                               return entry.ns3_id == std::to_string(id);
                                                                            });
    cav_msgs::ByteArray msg;
    msg.header.stamp = ros::Time::now();
    msg.header.frame_id = "";
    msg.message_type = it != wave_cfg_items_.end() ? it->name : "Unknown";
    msg.content = data;
    // Publish it
    comms_pub_.publish(msg);
    ROS_DEBUG_STREAM("Application received Data: " << data.size() << " bytes, message: " << uint8_vector_to_hex_string(data));
}
References comms_pub_, process_traj_logs::data, uint8_vector_to_hex_string(), and wave_cfg_items_.
Referenced by initialize().
onOutboundMessage()
void NS3Adapter::onOutboundMessage (const cav_msgs::ByteArrayPtr & message)
Handles outbound messages from the ROS network.
Parameters
message
This method packs the message according to the J2375 2016 standard, and sends it to the client program
Parameters
message
This method receives a message from the ROS network, and adds it to the send queue.
Definition at line 189 of file ns-3_adapter.cpp.
{
    if(!ns3_client_.connected())
    {
        ROS_WARN_STREAM("Outbound message received but node is not connected to NS-3");
        return;
    }
    std::shared_ptr<std::vector<uint8_t>> message_content = std::make_shared<std::vector<uint8_t>>(std::move(packMessage(*message)));
    send_msg_queue_.push_back(std::move(message_content));
}
References NS3Client::connected(), ns3_client_, packMessage(), and send_msg_queue_.
Referenced by initialize().
packMessage()
std::vector< uint8_t > NS3Adapter::packMessage (const cav_msgs::ByteArray & message)
Packs an outgoing message into J2375 standard.
Parameters
message
This processes an incoming ByteArray message, and packs it according to the Active Message file for the OSU.
Parameters
message
This processes an incoming ByteArray message, and packs it according to the J2735 standard.
TODO: Right now it doesn't do anything except return the message data (ignoring message type). Depending on what the input is, that might be all that's necessary, but possibly more. Depending on what the input is, that might be all that's necessary, but possibly more.
Definition at line 138 of file ns-3_adapter.cpp.
{
    std::stringstream ss;
    auto wave_item = std::find_if(wave_cfg_items_.begin(),wave_cfg_items_.end(),[&message](const WaveConfigStruct& entry)
    {
        return entry.name == message.message_type;
    });
    WaveConfigStruct cfg;
    if(wave_item == wave_cfg_items_.end())
    {
        ROS_WARN_STREAM("No wave config entry for type: " << message.message_type << ", using defaults");
        cfg.name = message.message_type;
        cfg.channel = "CCH";  //Assuming the Default channel is not the safety related info that would be in a BSM message
        cfg.priority = "1";
        cfg.ns3_id = std::to_string((message.content[0] << 8 ) | message.content[1]);
        cfg.psid = cfg.ns3_id;
    }
    else
    {
        cfg = *wave_item;
    }
    ss << "Version=0.7" << std::endl;
    ss << "Type=" << cfg.name << std::endl;
    ss << "PSID=" << cfg.psid << std::endl;
    ss << "VehicleID=" << vehicle_id_ << std::endl;
    ss << "Priority=" << cfg.priority << std::endl;
    ss << "TxMode=ALT" << std::endl;
    ss << "TxChannel=" << cfg.channel << std::endl;
    ss << "TxInterval=0" << std::endl;
    ss << "DeliveryStart=" << std::endl;
    ss << "DeliveryStop=" << std::endl;
    ss << "Signature=False" << std::endl;
    ss << "Encryption=False" << std::endl;
    ss << "VehiclePosX=" << pose_msg_.pose.position.x << std::endl;
    ss << "VehiclePosY=" << pose_msg_.pose.position.y << std::endl;
    ss << "Payload=" <<  uint8_vector_to_hex_string(message.content) << std::endl;
    std::string str = ss.str();
    return std::vector<uint8_t>(str.begin(), str.end());
}
References NS3Adapter::WaveConfigStruct::channel, NS3Adapter::WaveConfigStruct::name, NS3Adapter::WaveConfigStruct::ns3_id, pose_msg_, NS3Adapter::WaveConfigStruct::priority, NS3Adapter::WaveConfigStruct::psid, carma_cooperative_perception::to_string(), uint8_vector_to_hex_string(), vehicle_id_, and wave_cfg_items_.
Referenced by onOutboundMessage(), and sendMessageSrv().
pose_cb()
void NS3Adapter::pose_cb (geometry_msgs::PoseStamped pose_msg)
Definition at line 416 of file ns-3_adapter.cpp.
{
    pose_msg_ = pose_msg;
    /*TODO: Add Pose Functionality*/
}
References pose_msg_.
Referenced by initialize().
post_spin()
void NS3Adapter::post_spin () override private virtual
Called by the base DriverApplication class after spin.
Sends messages from the outgoing queue
Implements cav::DriverApplication.
Definition at line 298 of file ns-3_adapter.cpp.
{
    sendMessageFromQueue();
}
References sendMessageFromQueue().
pre_spin()
void NS3Adapter::pre_spin () override private virtual
Called by the base DriverApplication class prior to Spin.
Manages local state of hardware device, reconnecting as needed
Implements cav::DriverApplication.
Definition at line 247 of file ns-3_adapter.cpp.
{
    // Adjust output queue size if config changed.
    if(ns3_client_error_)
    {
        ROS_ERROR_STREAM("NS-3 Client Error : " << ns3_client_error_.message());
        ns3_client_.close();
        ns3_client_error_.clear();
    }
    //If we are not connected
    //TODO: Set up functionality for disconnected NS-3
    /*if (!connecting_ && !ns3_client_.connected())
    {
        connecting_ = true;
        if (connect_thread_)
            connect_thread_->join();
        //We don't want to block the spin thread because the driver
        //application maintains driver status topic
        connect_thread_.reset(new std::thread([this]()
        {
            dsrc::DSRCConfig cfg;
            {
                std::lock_guard<std::mutex> lock(cfg_mutex_);
                cfg = config_;
            }
            ROS_INFO("Attempting to connect to OBU");
            boost::system::error_code ec;
           // ROS_INFO("Connecting to %s:%u", cfg.dsrc_address.c_str(), cfg.dsrc_listening_port);
            ROS_INFO("Local port: %u", cfg.listening_port);
            try {
                if (!ns3_client_.connect(cfg.dsrc_address, cfg.dsrc_listening_port,
                                          cfg.listening_port, ec))
                {
                    ROS_WARN_STREAM("Failed to connect, err: " << ec.message());
                }
            }catch(std::exception e)
            {
                ROS_ERROR_STREAM("Exception connecting to dsrc radio: " << e.what() << " error_code: " << ec.message());
               // ROS_ERROR_STREAM("Config:\n\tdsrc_address:" << cfg.dsrc_address
                                         << "\n\tdsrc_listening_port:" << cfg.dsrc_listening_port
                                         << "\n\tlistening_port:" << cfg.listening_port);
            }
            connecting_ = false;
        }));
    }*/
}
References NS3Client::close(), ns3_client_, and ns3_client_error_.
sendMessageFromQueue()
void NS3Adapter::sendMessageFromQueue ()
Sends a message from the queue of outbound messages.
Definition at line 203 of file ns-3_adapter.cpp.
{
    if (!send_msg_queue_.empty()) {
        ROS_DEBUG_STREAM("Sending message: " << std::string(send_msg_queue_.front()->begin(),send_msg_queue_.front()->end()));
        bool success = ns3_client_.sendNS3Message(send_msg_queue_.front());
        send_msg_queue_.pop_front();
        if (!success) {
            ROS_WARN_STREAM("Message send failed");
        }
        else {
            ROS_DEBUG("Message successfully sent from queue");
        }
    }
}
References ns3_client_, send_msg_queue_, and NS3Client::sendNS3Message().
Referenced by post_spin().
sendMessageSrv()
bool NS3Adapter::sendMessageSrv (cav_srvs::SendMessage::Request & req, cav_srvs::SendMessage::Response & res)
Message sending service.
Parameters
req
res
Definition at line 222 of file ns-3_adapter.cpp.
{
    if(!ns3_client_.connected())
    {
        ROS_WARN_STREAM("Outbound message received but node is not connected to NS-3 Radio");
        res.errorStatus = 1;
        return true;
    }
    // Package data into a message shared pointer; this lets packMessage have
    // the same interface for outgoing messages from the topic and service.
    const cav_msgs::ByteArray::ConstPtr message = cav_msgs::ByteArray::ConstPtr(new cav_msgs::ByteArray(req.message_to_send));
    std::shared_ptr<std::vector<uint8_t>> message_data = std::make_shared<std::vector<uint8_t>>(std::move(packMessage(*message)));
    bool success = ns3_client_.sendNS3Message(message_data);
    if (success) {
        ROS_DEBUG("SendMessage service returned success");
        res.errorStatus = 0;
    }
    else {
        ROS_WARN_STREAM("SendMessage service returned failure");
        res.errorStatus = 1;
    }
    return true;
}
References NS3Client::connected(), ns3_client_, packMessage(), and NS3Client::sendNS3Message().
Referenced by initialize().
shutdown()
void NS3Adapter::shutdown () override private virtual
Reimplemented from cav::DriverApplication.
Definition at line 401 of file ns-3_adapter.cpp.
{
    ROS_INFO("Shutdown signal received from DriverApplication");
    if (connect_thread_)
    {
        ROS_INFO("Cleaning up connection thread");
        connect_thread_->join();
        connect_thread_.reset();
    }
    ROS_INFO("Closing connection to radio");
    ns3_client_.close();
}
References NS3Client::close(), connect_thread_, and ns3_client_.
Referenced by ~NS3Adapter().
uint8_vector_to_hex_string()
std::string NS3Adapter::uint8_vector_to_hex_string (const std::vector< uint8_t > & v)
converts a uint8_t vector to an ascii representation
Parameters
v
Returns
Definition at line 11 of file ns-3_adapter.cpp.
{
    std::stringstream ss;
    ss << std::hex << std::setfill('0');
    std::vector<uint8_t>::const_iterator it;
    for (it = v.begin(); it != v.end(); it++) {
        ss << std::setw(2) << static_cast<unsigned>(*it);
    }
    return ss.str();
}
Referenced by onMessageReceivedHandler(), and packMessage().
Member Data Documentation
api_
std::vector<std::string> NS3Adapter::api_ private
Definition at line 79 of file ns-3_adapter.h.
Referenced by get_api(), and initialize().
cfg_mutex_
std::mutex NS3Adapter::cfg_mutex_ private
Definition at line 103 of file ns-3_adapter.h.
comms_api_nh_
std::shared_ptr<ros::NodeHandle> NS3Adapter::comms_api_nh_ private
Definition at line 86 of file ns-3_adapter.h.
Referenced by initialize().
comms_pub_
ros::Publisher NS3Adapter::comms_pub_ private
Definition at line 82 of file ns-3_adapter.h.
Referenced by initialize(), and onMessageReceivedHandler().
comms_srv_
ros::ServiceServer NS3Adapter::comms_srv_ private
Definition at line 85 of file ns-3_adapter.h.
Referenced by initialize().
comms_sub_
ros::Subscriber NS3Adapter::comms_sub_ private
Definition at line 83 of file ns-3_adapter.h.
Referenced by initialize().
connect_thread_
std::shared_ptr<std::thread> NS3Adapter::connect_thread_ private
Definition at line 110 of file ns-3_adapter.h.
Referenced by shutdown().
connecting_
bool NS3Adapter::connecting_ = false private
Definition at line 109 of file ns-3_adapter.h.
dyn_cfg_mutex_
boost::recursive_mutex NS3Adapter::dyn_cfg_mutex_ private
Definition at line 105 of file ns-3_adapter.h.
host_ip_
std::string NS3Adapter::host_ip_ = "127.0.0.1" private
Definition at line 96 of file ns-3_adapter.h.
Referenced by initialize().
ns3_address_
std::string NS3Adapter::ns3_address_ = "192.168.88.40" private
Definition at line 98 of file ns-3_adapter.h.
Referenced by broadcastHandshakemsg(), and initialize().
ns3_client_
NS3Client NS3Adapter::ns3_client_ private
Definition at line 106 of file ns-3_adapter.h.
Referenced by broadcastHandshakemsg(), initialize(), onOutboundMessage(), pre_spin(), sendMessageFromQueue(), sendMessageSrv(), and shutdown().
ns3_client_error_
boost::system::error_code NS3Adapter::ns3_client_error_ private
Definition at line 111 of file ns-3_adapter.h.
Referenced by initialize(), and pre_spin().
ns3_registration_port_
int NS3Adapter::ns3_registration_port_ = 1000 private
Definition at line 99 of file ns-3_adapter.h.
Referenced by broadcastHandshakemsg(), and initialize().
port_
std::string NS3Adapter::port_ = "2000" private
Definition at line 95 of file ns-3_adapter.h.
Referenced by initialize().
pose_msg_
geometry_msgs::PoseStamped NS3Adapter::pose_msg_ private
Definition at line 89 of file ns-3_adapter.h.
Referenced by packMessage(), and pose_cb().
pose_sub_
ros::Subscriber NS3Adapter::pose_sub_ private
Definition at line 84 of file ns-3_adapter.h.
Referenced by initialize().
queue_size_
uint32_t NS3Adapter::queue_size_ private
Definition at line 114 of file ns-3_adapter.h.
Referenced by NS3Adapter(), and initialize().
role_id_
std::string NS3Adapter::role_id_ = "ego_vehicle" private
Definition at line 94 of file ns-3_adapter.h.
Referenced by initialize().
send_msg_queue_
std::deque<std::shared_ptr<std::vector<uint8_t> > > NS3Adapter::send_msg_queue_ private
Definition at line 108 of file ns-3_adapter.h.
Referenced by getMsgQueue(), onOutboundMessage(), and sendMessageFromQueue().
vehicle_id_
std::string NS3Adapter::vehicle_id_ private
Definition at line 92 of file ns-3_adapter.h.
Referenced by initialize(), and packMessage().
wave_cfg_items_
std::vector<WaveConfigStruct> NS3Adapter::wave_cfg_items_ private
Definition at line 113 of file ns-3_adapter.h.
Referenced by loadWaveConfig(), onMessageReceivedHandler(), and packMessage().
The documentation for this class was generated from the following files:
ns-3_adapter/include/ns-3_adapter.h
ns-3_adapter/src/ns-3_adapter.cpp