Carma-platform: pose_to_tf::PoseToTF2 Class Reference
pose_to_tf::PoseToTF2 Class Reference
Primary logic class for the PoseToTF2 node.
#include <PoseToTF2.hpp>
Public Types
using TransformPublisher = std::function< void(const geometry_msgs::msg::TransformStamped &)>
Public Member Functions
PoseToTF2 (PoseToTF2Config config, TransformPublisher transform_pub, std::shared_ptr< carma_ros2_utils::CarmaLifecycleNode > node)
Constructor.
void poseStampedCallback (geometry_msgs::msg::PoseStamped::UniquePtr msg)
Callback for new pose stamped messages.
void poseWithCovarianceStampedCallback (geometry_msgs::msg::PoseWithCovarianceStamped::UniquePtr msg)
Callback for new pose stamped messages.
void poseCallback (geometry_msgs::msg::Pose::UniquePtr msg)
Callback for new pose stamped messages.
void poseWithCovarianceCallback (geometry_msgs::msg::PoseWithCovariance::UniquePtr msg)
Callback for new pose with covariance messages.
Private Attributes
std::shared_ptr< carma_ros2_utils::CarmaLifecycleNode > node_
PoseToTF2Config config_
TransformPublisher transform_pub_
Detailed Description
Primary logic class for the PoseToTF2 node.
Definition at line 33 of file PoseToTF2.hpp.
Member Typedef Documentation
TransformPublisher
using pose_to_tf::PoseToTF2::TransformPublisher = std::function<void(const geometry_msgs::msg::TransformStamped&)>
Definition at line 36 of file PoseToTF2.hpp.
Constructor & Destructor Documentation
PoseToTF2()
pose_to_tf::PoseToTF2::PoseToTF2 (PoseToTF2Config config, TransformPublisher transform_pub, std::shared_ptr< carma_ros2_utils::CarmaLifecycleNode > node)
Constructor.
Parameters
transform_pub A callback to trigger transform broadcast
Definition at line 60 of file PoseToTF2.cpp.
  : config_(config), transform_pub_(transform_pub), node_(node)
{
}
Member Function Documentation
poseCallback()
void pose_to_tf::PoseToTF2::poseCallback (geometry_msgs::msg::Pose::UniquePtr msg)
Callback for new pose stamped messages.
Parameters
msg The pose message to forward
Definition at line 81 of file PoseToTF2.cpp.
{
  geometry_msgs::msg::TransformStamped out_tf;
  tf2::convert(*msg, out_tf.transform);
  out_tf.header.stamp = node_->now();
  out_tf.header.frame_id = config_.default_parent_frame;
  out_tf.child_frame_id = config_.child_frame;
  transform_pub_(out_tf);
}
References pose_to_tf::PoseToTF2Config::child_frame, config_, tf2::anonymous_namespace{PoseToTF2.cpp}::convert(), pose_to_tf::PoseToTF2Config::default_parent_frame, node_, and transform_pub_.
Referenced by pose_to_tf::PoseToTfNode::handle_on_configure().
poseStampedCallback()
void pose_to_tf::PoseToTF2::poseStampedCallback (geometry_msgs::msg::PoseStamped::UniquePtr msg)
Callback for new pose stamped messages.
Parameters
msg The pose message to forward
Definition at line 65 of file PoseToTF2.cpp.
{
  geometry_msgs::msg::TransformStamped out_tf;
  tf2::convert(*msg, out_tf);
  out_tf.child_frame_id = config_.child_frame;
  transform_pub_(out_tf);
}
References pose_to_tf::PoseToTF2Config::child_frame, config_, tf2::anonymous_namespace{PoseToTF2.cpp}::convert(), and transform_pub_.
Referenced by pose_to_tf::PoseToTfNode::handle_on_configure().
poseWithCovarianceCallback()
void pose_to_tf::PoseToTF2::poseWithCovarianceCallback (geometry_msgs::msg::PoseWithCovariance::UniquePtr msg)
Callback for new pose with covariance messages.
Parameters
msg The pose message to forward
Definition at line 91 of file PoseToTF2.cpp.
{
  geometry_msgs::msg::TransformStamped out_tf;
  tf2::convert(*msg, out_tf.transform);
  out_tf.header.stamp = node_->now();
  out_tf.header.frame_id = config_.default_parent_frame;
  out_tf.child_frame_id = config_.child_frame;
  transform_pub_(out_tf);
}
References pose_to_tf::PoseToTF2Config::child_frame, config_, tf2::anonymous_namespace{PoseToTF2.cpp}::convert(), pose_to_tf::PoseToTF2Config::default_parent_frame, node_, and transform_pub_.
Referenced by pose_to_tf::PoseToTfNode::handle_on_configure().
poseWithCovarianceStampedCallback()
void pose_to_tf::PoseToTF2::poseWithCovarianceStampedCallback (geometry_msgs::msg::PoseWithCovarianceStamped::UniquePtr msg)
Callback for new pose stamped messages.
Parameters
msg The pose message to forward
Definition at line 73 of file PoseToTF2.cpp.
{
  geometry_msgs::msg::TransformStamped out_tf;
  tf2::convert(*msg, out_tf);
  out_tf.child_frame_id = config_.child_frame;
  transform_pub_(out_tf);
}
References pose_to_tf::PoseToTF2Config::child_frame, config_, tf2::anonymous_namespace{PoseToTF2.cpp}::convert(), and transform_pub_.
Referenced by pose_to_tf::PoseToTfNode::handle_on_configure().
Member Data Documentation
config_
PoseToTF2Config pose_to_tf::PoseToTF2::config_ private
Definition at line 77 of file PoseToTF2.hpp.
Referenced by poseCallback(), poseStampedCallback(), poseWithCovarianceCallback(), and poseWithCovarianceStampedCallback().
node_
std::shared_ptr<carma_ros2_utils::CarmaLifecycleNode> pose_to_tf::PoseToTF2::node_ private
Definition at line 75 of file PoseToTF2.hpp.
Referenced by poseCallback(), and poseWithCovarianceCallback().
transform_pub_
TransformPublisher pose_to_tf::PoseToTF2::transform_pub_ private
Definition at line 78 of file PoseToTF2.hpp.
Referenced by poseCallback(), poseStampedCallback(), poseWithCovarianceCallback(), and poseWithCovarianceStampedCallback().
The documentation for this class was generated from the following files:
pose_to_tf/include/pose_to_tf/PoseToTF2.hpp
pose_to_tf/src/PoseToTF2.cpp