Carma-platform: platoon_control_ihp::PlatoonControlIHPPlugin Class Reference
platoon_control_ihp::PlatoonControlIHPPlugin Class Reference
This class includes logic for Platoon control IHP. It includes publishers and subscribers and their callback functions.
#include <platoon_control_ihp.h>
Public Member Functions
PlatoonControlIHPPlugin ()
Default constructor for PlatoonControlPluginIHP class.
void initialize ()
Initialize plugin variables and publishers/subscribers.
void run ()
general starting point of this node
void generateControlSignals (const cav_msgs::TrajectoryPlanPoint &point0, const cav_msgs::TrajectoryPlanPoint &point_end)
generate control signal by calculating speed and steering commands.
geometry_msgs::TwistStamped composeTwistCmd (double linear_vel, double angular_vel)
Compose twist message from linear and angular velocity commands.
autoware_msgs::ControlCommandStamped composeCtrlCmd (double linear_vel, double steering_angle)
Compose control message from speed and steering commands.
cav_msgs::TrajectoryPlanPoint getLookaheadTrajectoryPoint (cav_msgs::TrajectoryPlan trajectory_plan)
find the point correspoding to the lookahead distance
bool controlTimerCb ()
timer callback for control signal publishers
Public Attributes
geometry_msgs::PoseStamped pose_msg_
double current_speed_ = 0.0
double trajectory_speed_ = 0.0
cav_msgs::TrajectoryPlan latest_trajectory_
Private Member Functions
void pose_cb (const geometry_msgs::PoseStampedConstPtr &msg)
callback function for pose
void platoonInfo_cb (const cav_msgs::PlatooningInfoConstPtr &msg)
callback function for platoon info
void trajectoryPlan_cb (const cav_msgs::TrajectoryPlan::ConstPtr &tp)
callback function for trajectory plan
void currentTwist_cb (const geometry_msgs::TwistStamped::ConstPtr &twist)
callback function for current twist
double getTrajectorySpeed (std::vector< cav_msgs::TrajectoryPlanPoint > trajectory_points)
calculate average speed of a set of trajectory points
Private Attributes
std::shared_ptr< ros::CARMANodeHandle > nh_
std::shared_ptr< ros::CARMANodeHandle > pnh_
PlatoonControlIHPWorker pcw_
PlatooningControlIHPPluginConfig config_
PlatoonLeaderInfo platoon_leader_
long prev_input_time_ = 0
long consecutive_input_counter_ = 0
cav_msgs::Plugin plugin_discovery_msg_
ros::Subscriber trajectory_plan_sub
ros::Subscriber current_twist_sub_
ros::Subscriber pose_sub_
ros::Subscriber platoon_info_sub_
ros::Publisher twist_pub_
ros::Publisher ctrl_pub_
ros::Publisher plugin_discovery_pub_
ros::Publisher platoon_info_pub_
ros::Timer discovery_pub_timer_
ros::Timer control_pub_timer_
Detailed Description
This class includes logic for Platoon control IHP. It includes publishers and subscribers and their callback functions.
Definition at line 40 of file platoon_control_ihp.h.
Constructor & Destructor Documentation
PlatoonControlIHPPlugin()
platoon_control_ihp::PlatoonControlIHPPlugin::PlatoonControlIHPPlugin ()
Default constructor for PlatoonControlPluginIHP class.
Definition at line 22 of file platoon_control_ihp.cpp.
    {
        pcw_ = PlatoonControlIHPWorker();
    }
References pcw_.
Member Function Documentation
composeCtrlCmd()
autoware_msgs::ControlCommandStamped platoon_control_ihp::PlatoonControlIHPPlugin::composeCtrlCmd (double linear_vel, double steering_angle)
Compose control message from speed and steering commands.
Parameters
linear_vel linear velocity in m/s
steering_angle steering angle in rad
Returns
control command
Definition at line 258 of file platoon_control_ihp.cpp.
    {
        autoware_msgs::ControlCommandStamped cmd_ctrl;
        cmd_ctrl.header.stamp = ros::Time::now();
        cmd_ctrl.cmd.linear_velocity = linear_vel;
        ROS_DEBUG_STREAM("ctrl command speed " << cmd_ctrl.cmd.linear_velocity);
        cmd_ctrl.cmd.steering_angle = steering_angle;
        ROS_DEBUG_STREAM("ctrl command steering " << cmd_ctrl.cmd.steering_angle);
        return cmd_ctrl;
    }
Referenced by generateControlSignals().
composeTwistCmd()
geometry_msgs::TwistStamped platoon_control_ihp::PlatoonControlIHPPlugin::composeTwistCmd (double linear_vel, double angular_vel)
Compose twist message from linear and angular velocity commands.
Parameters
linear_vel linear velocity in m/s
angular_vel angular velocity in rad/s
Returns
twist message
Definition at line 249 of file platoon_control_ihp.cpp.
    {
        geometry_msgs::TwistStamped cmd_twist;
        cmd_twist.twist.linear.x = linear_vel;
        cmd_twist.twist.angular.z = angular_vel;
        cmd_twist.header.stamp = ros::Time::now();
        return cmd_twist;
    }
Referenced by generateControlSignals().
controlTimerCb()
bool platoon_control_ihp::PlatoonControlIHPPlugin::controlTimerCb ()
timer callback for control signal publishers
Returns
true if control signals are correctly calculated.
Definition at line 109 of file platoon_control_ihp.cpp.
    {
        ROS_DEBUG_STREAM("In control timer callback ");
        // If it has been a long time since input data has arrived then reset the input counter and return
        // Note: this quiets the controller after its input stream stops, which is necessary to allow
        // the replacement controller to publish on the same output topic after this one is done.
        long current_time = ros::Time::now().toNSec() / 1000000;
        ROS_DEBUG_STREAM("current_time = " << current_time << ", prev_input_time_ = " << prev_input_time_ << ", input counter = " << consecutive_input_counter_);
        if (current_time - prev_input_time_ > config_.shutdownTimeout)
        {
            ROS_DEBUG_STREAM("returning due to timeout.");
            consecutive_input_counter_ = 0;
            return false;
        }
        // If there have not been enough consecutive timely inputs then return (waiting for
        // previous control plugin to time out and stop publishing, since it uses same output topic)
        if (consecutive_input_counter_ <= config_.ignoreInitialInputs)
        {
            ROS_DEBUG_STREAM("returning due to first data input");
            return false;
        }
        cav_msgs::TrajectoryPlanPoint second_trajectory_point = latest_trajectory_.trajectory_points[1];
        cav_msgs::TrajectoryPlanPoint lookahead_point = getLookaheadTrajectoryPoint(latest_trajectory_);
        trajectory_speed_ = getTrajectorySpeed(latest_trajectory_.trajectory_points);
        generateControlSignals(second_trajectory_point, lookahead_point);
        return true;
    }
References config_, consecutive_input_counter_, generateControlSignals(), getLookaheadTrajectoryPoint(), getTrajectorySpeed(), PlatooningControlIHPPluginConfig::ignoreInitialInputs, latest_trajectory_, prev_input_time_, PlatooningControlIHPPluginConfig::shutdownTimeout, and trajectory_speed_.
Referenced by initialize().
currentTwist_cb()
void platoon_control_ihp::PlatoonControlIHPPlugin::currentTwist_cb (const geometry_msgs::TwistStamped::ConstPtr & twist) private
callback function for current twist
Parameters
msg twist stamped msg
Definition at line 241 of file platoon_control_ihp.cpp.
    {
        current_speed_ = twist->twist.linear.x;
    }
References current_speed_.
Referenced by initialize().
generateControlSignals()
void platoon_control_ihp::PlatoonControlIHPPlugin::generateControlSignals (const cav_msgs::TrajectoryPlanPoint & point0, const cav_msgs::TrajectoryPlanPoint & point_end)
generate control signal by calculating speed and steering commands.
Parameters
point0 start point of control window
point_end end point of control wondow
Definition at line 270 of file platoon_control_ihp.cpp.
    {
        // setting a speed baseline according to the trajectory speed profile. PID will calculate additional speed changes in addition to this value.
        pcw_.setCurrentSpeed(trajectory_speed_); //TODO why this and not the actual vehicle speed?  Method name suggests different use than this.
        // pcw_.setCurrentSpeed(current_speed_);
        pcw_.setLeader(platoon_leader_);
        pcw_.generateSpeed(first_trajectory_point);
        pcw_.generateSteer(lookahead_point);
        geometry_msgs::TwistStamped twist_msg = composeTwistCmd(pcw_.speedCmd_, pcw_.angVelCmd_);
        twist_pub_.publish(twist_msg);
        autoware_msgs::ControlCommandStamped ctrl_msg = composeCtrlCmd(pcw_.speedCmd_, pcw_.steerCmd_);
        ctrl_pub_.publish(ctrl_msg);
    }
References platoon_control_ihp::PlatoonControlIHPWorker::angVelCmd_, composeCtrlCmd(), composeTwistCmd(), ctrl_pub_, platoon_control_ihp::PlatoonControlIHPWorker::generateSpeed(), platoon_control_ihp::PlatoonControlIHPWorker::generateSteer(), pcw_, platoon_leader_, platoon_control_ihp::PlatoonControlIHPWorker::setCurrentSpeed(), platoon_control_ihp::PlatoonControlIHPWorker::setLeader(), platoon_control_ihp::PlatoonControlIHPWorker::speedCmd_, platoon_control_ihp::PlatoonControlIHPWorker::steerCmd_, trajectory_speed_, and twist_pub_.
Referenced by controlTimerCb().
getLookaheadTrajectoryPoint()
cav_msgs::TrajectoryPlanPoint platoon_control_ihp::PlatoonControlIHPPlugin::getLookaheadTrajectoryPoint (cav_msgs::TrajectoryPlan trajectory_plan)
find the point correspoding to the lookahead distance
Parameters
trajectory_plan trajectory plan
Returns
trajectory point
Definition at line 156 of file platoon_control_ihp.cpp.
    {
        cav_msgs::TrajectoryPlanPoint lookahead_point;
        double lookahead_dist = config_.lookaheadRatio * current_speed_;
        ROS_DEBUG_STREAM("lookahead based on speed: " << lookahead_dist);
        lookahead_dist = std::max(config_.minLookaheadDist, lookahead_dist);
        ROS_DEBUG_STREAM("final lookahead: " << lookahead_dist);
        double traveled_dist = 0.0;
        bool found_point = false;
        for (size_t i = 1; i<trajectory_plan.trajectory_points.size() - 1; i++)
        {
            double dx =  pose_msg_.pose.position.x - trajectory_plan.trajectory_points[i].x;
            double dy =  pose_msg_.pose.position.y - trajectory_plan.trajectory_points[i].y;
            double dx1 = trajectory_plan.trajectory_points[i].x - trajectory_plan.trajectory_points[i-1].x;
            double dy1 = trajectory_plan.trajectory_points[i].y - trajectory_plan.trajectory_points[i-1].y;
            double dist1 = std::sqrt(dx1*dx1 + dy1*dy1);
            ROS_DEBUG_STREAM("trajectory spacing: " << dist1);
            double dist = std::sqrt(dx*dx + dy*dy);
            traveled_dist = dist;
            if ((lookahead_dist - traveled_dist) < 1.0)
            {
                lookahead_point =  trajectory_plan.trajectory_points[i];
                found_point = true;
                ROS_DEBUG_STREAM("found lookahead point at index: " << i);
                break;
            }
        }
        if (!found_point)
        {
            lookahead_point = trajectory_plan.trajectory_points.back();
            ROS_DEBUG_STREAM("lookahead point set as the last trajectory point");
        }
        return lookahead_point;
    }
References config_, current_speed_, process_bag::i, PlatooningControlIHPPluginConfig::lookaheadRatio, PlatooningControlIHPPluginConfig::minLookaheadDist, and pose_msg_.
Referenced by controlTimerCb().
getTrajectorySpeed()
double platoon_control_ihp::PlatoonControlIHPPlugin::getTrajectorySpeed (std::vector< cav_msgs::TrajectoryPlanPoint > trajectory_points) private
calculate average speed of a set of trajectory points
Parameters
trajectory_points set of trajectory points
Returns
trajectory speed in m/s
Definition at line 289 of file platoon_control_ihp.cpp.
    {
        double trajectory_speed = 0;
        double dx1 = trajectory_points[trajectory_points.size()-1].x - trajectory_points[0].x;
        double dy1 = trajectory_points[trajectory_points.size()-1].y - trajectory_points[0].y;
        double d1 = sqrt(dx1*dx1 + dy1*dy1);
        double t1 = (trajectory_points[trajectory_points.size()-1].target_time.toSec() - trajectory_points[0].target_time.toSec());
        double avg_speed = d1/t1;
        ROS_DEBUG_STREAM("trajectory_points size = " << trajectory_points.size() << ", d1 = " << d1 << ", t1 = " << t1 << ", avg_speed = " << avg_speed);
        for(size_t i = 0; i < trajectory_points.size() - 2; i++ )
        {
            double dx = trajectory_points[i + 1].x - trajectory_points[i].x;
            double dy = trajectory_points[i + 1].y - trajectory_points[i].y;
            double d = sqrt(dx*dx + dy*dy);
            double t = (trajectory_points[i + 1].target_time.toSec() - trajectory_points[i].target_time.toSec());
            double v = d/t;
            if(v > trajectory_speed)
            {
                trajectory_speed = v;
            }
        }
        ROS_DEBUG_STREAM("trajectory speed: " << trajectory_speed);
        ROS_DEBUG_STREAM("avg trajectory speed: " << avg_speed);
        return avg_speed; //TODO: why are 2 speeds being calculated? Which should be returned?
    }
References process_bag::i.
Referenced by controlTimerCb().
initialize()
void platoon_control_ihp::PlatoonControlIHPPlugin::initialize ()
Initialize plugin variables and publishers/subscribers.
Definition at line 28 of file platoon_control_ihp.cpp.
    {
        nh_.reset(new ros::CARMANodeHandle());
        pnh_.reset(new ros::CARMANodeHandle("~"));
        PlatooningControlIHPPluginConfig config;
        pnh_->param<double>("maxAccel", config.maxAccel, config.maxAccel);
        pnh_->param<double>("Kp", config.Kp, config.Kp);
        pnh_->param<double>("Kd", config.Kd, config.Kd);
        pnh_->param<double>("Ki", config.Ki, config.Ki);
        pnh_->param<double>("maxValue", config.maxValue, config.maxValue);
        pnh_->param<double>("minValue", config.minValue, config.minValue);
        pnh_->param<double>("dt", config.dt, config.dt);
        pnh_->param<double>("adjustmentCap", config.adjustmentCap, config.adjustmentCap);
        pnh_->param<double>("integratorMax", config.integratorMax, config.integratorMax);
        pnh_->param<double>("integratorMin", config.integratorMin, config.integratorMin);
        pnh_->param<double>("Kdd", config.Kdd, config.Kdd);
        pnh_->param<int>("cmdTmestamp", config.cmdTmestamp, config.cmdTmestamp);
        pnh_->param<double>("lowpassGain", config.lowpassGain, config.lowpassGain);
        pnh_->param<double>("lookaheadRatio", config.lookaheadRatio, config.lookaheadRatio);
        pnh_->param<double>("minLookaheadDist", config.minLookaheadDist, config.minLookaheadDist);
        // Global params (from vehicle config)
        pnh_->getParam("/vehicle_id", config.vehicleID);
        pnh_->getParam("/vehicle_wheel_base", config.wheelBase);
        pnh_->getParam("/control_plugin_shutdown_timeout", config.shutdownTimeout);
        pnh_->getParam("/control_plugin_ignore_initial_inputs", config.ignoreInitialInputs);
        pcw_.updateConfigParams(config);
        config_ = config;
        // Trajectory Plan Subscriber
        trajectory_plan_sub = nh_->subscribe<cav_msgs::TrajectoryPlan>("platoon_control_ihp/plan_trajectory", 1, &PlatoonControlIHPPlugin::trajectoryPlan_cb, this);
        // Current Twist Subscriber
        current_twist_sub_ = nh_->subscribe<geometry_msgs::TwistStamped>("current_velocity", 1, &PlatoonControlIHPPlugin::currentTwist_cb, this);
        // Platoon Info Subscriber
        // topic name so it is specific to ihp plugins
        platoon_info_sub_ = nh_->subscribe<cav_msgs::PlatooningInfo>("platoon_info_ihp", 1, &PlatoonControlIHPPlugin::platoonInfo_cb, this);
        // Control Publisher
        twist_pub_ = nh_->advertise<geometry_msgs::TwistStamped>("twist_raw", 5, true);
        ctrl_pub_ = nh_->advertise<autoware_msgs::ControlCommandStamped>("ctrl_raw", 5, true);
        platoon_info_pub_ = nh_->advertise<cav_msgs::PlatooningInfo>("platooning_info", 1, true);
        pose_sub_ = nh_->subscribe("current_pose", 1, &PlatoonControlIHPPlugin::pose_cb, this);
        plugin_discovery_pub_ = nh_->advertise<cav_msgs::Plugin>("plugin_discovery", 1);
        plugin_discovery_msg_.name = "platoon_control_ihp";
        plugin_discovery_msg_.version_id = "v1.0";
        plugin_discovery_msg_.available = true;
        plugin_discovery_msg_.activated = true;
        plugin_discovery_msg_.type = cav_msgs::Plugin::CONTROL;
        plugin_discovery_msg_.capability = "control/trajectory_control";
        discovery_pub_timer_ = pnh_->createTimer(
            ros::Duration(ros::Rate(10.0)),
            [this](const auto&) { plugin_discovery_pub_.publish(plugin_discovery_msg_);
                                  ROS_DEBUG_STREAM("10hz timer callback called");});
        ROS_DEBUG_STREAM("discovery timer created");
        control_pub_timer_ = pnh_->createTimer(
            ros::Duration(ros::Rate(30.0)),
            [this](const auto&) { ROS_DEBUG_STREAM("30hz timer callback called");
                                  controlTimerCb();  });
        ROS_DEBUG_STREAM("control timer created ");
    }
References PlatooningControlIHPPluginConfig::adjustmentCap, PlatooningControlIHPPluginConfig::cmdTmestamp, config_, control_pub_timer_, controlTimerCb(), ctrl_pub_, current_twist_sub_, currentTwist_cb(), discovery_pub_timer_, PlatooningControlIHPPluginConfig::dt, PlatooningControlIHPPluginConfig::ignoreInitialInputs, PlatooningControlIHPPluginConfig::integratorMax, PlatooningControlIHPPluginConfig::integratorMin, PlatooningControlIHPPluginConfig::Kd, PlatooningControlIHPPluginConfig::Kdd, PlatooningControlIHPPluginConfig::Ki, PlatooningControlIHPPluginConfig::Kp, PlatooningControlIHPPluginConfig::lookaheadRatio, PlatooningControlIHPPluginConfig::lowpassGain, PlatooningControlIHPPluginConfig::maxAccel, PlatooningControlIHPPluginConfig::maxValue, PlatooningControlIHPPluginConfig::minLookaheadDist, PlatooningControlIHPPluginConfig::minValue, nh_, pcw_, platoon_info_pub_, platoon_info_sub_, platoonInfo_cb(), plugin_discovery_msg_, plugin_discovery_pub_, pnh_, pose_cb(), pose_sub_, PlatooningControlIHPPluginConfig::shutdownTimeout, trajectory_plan_sub, trajectoryPlan_cb(), twist_pub_, platoon_control_ihp::PlatoonControlIHPWorker::updateConfigParams(), PlatooningControlIHPPluginConfig::vehicleID, and PlatooningControlIHPPluginConfig::wheelBase.
Referenced by run().
platoonInfo_cb()
void platoon_control_ihp::PlatoonControlIHPPlugin::platoonInfo_cb (const cav_msgs::PlatooningInfoConstPtr & msg) private
callback function for platoon info
Parameters
msg platoon info msg
Definition at line 208 of file platoon_control_ihp.cpp.
    {
        platoon_leader_.staticId = msg->leader_id;
        platoon_leader_.vehiclePosition = msg->leader_downtrack_distance;
        platoon_leader_.commandSpeed = msg->leader_cmd_speed;
        // TODO: index is 0 temp to test the leader state
        platoon_leader_.NumberOfVehicleInFront = msg->host_platoon_position;
        platoon_leader_.leaderIndex = 0;
        ROS_DEBUG_STREAM("Platoon leader leader id:  " << platoon_leader_.staticId);
        ROS_DEBUG_STREAM("Platoon leader leader pose:  " << platoon_leader_.vehiclePosition);
        ROS_DEBUG_STREAM("Platoon leader leader cmd speed:  " << platoon_leader_.commandSpeed);
        cav_msgs::PlatooningInfo platooing_info_msg = *msg;
        // platooing_info_msg.desired_gap = pcw_.desired_gap_;
        // platooing_info_msg.actual_gap = pcw_.actual_gap_;
        pcw_.actual_gap_ = platooing_info_msg.actual_gap;
        pcw_.desired_gap_ = platooing_info_msg.desired_gap;
        // UCLA: Read host platoon position
        pcw_.host_platoon_position_ = platooing_info_msg.host_platoon_position;
        // UCLA: Read the time headway summation of all predecessors
        pcw_.current_predecessor_time_headway_sum_ = platooing_info_msg.current_predecessor_time_headway_sum;
        // UCLA: Read predecessor speed m/s, and DtD position m.
        pcw_.predecessor_speed_ = platooing_info_msg.predecessor_speed;
        pcw_.predecessor_position_ = platooing_info_msg.predecessor_position;
        platooing_info_msg.host_cmd_speed = pcw_.speedCmd_;
        platoon_info_pub_.publish(platooing_info_msg);
    }
References platoon_control_ihp::PlatoonControlIHPWorker::actual_gap_, platoon_control_ihp::PlatoonLeaderInfo::commandSpeed, platoon_control_ihp::PlatoonControlIHPWorker::current_predecessor_time_headway_sum_, platoon_control_ihp::PlatoonControlIHPWorker::desired_gap_, platoon_control_ihp::PlatoonControlIHPWorker::host_platoon_position_, platoon_control_ihp::PlatoonLeaderInfo::leaderIndex, platoon_control_ihp::PlatoonLeaderInfo::NumberOfVehicleInFront, pcw_, platoon_info_pub_, platoon_leader_, platoon_control_ihp::PlatoonControlIHPWorker::predecessor_position_, platoon_control_ihp::PlatoonControlIHPWorker::predecessor_speed_, platoon_control_ihp::PlatoonControlIHPWorker::speedCmd_, platoon_control_ihp::PlatoonLeaderInfo::staticId, and platoon_control_ihp::PlatoonLeaderInfo::vehiclePosition.
Referenced by initialize().
pose_cb()
void platoon_control_ihp::PlatoonControlIHPPlugin::pose_cb (const geometry_msgs::PoseStampedConstPtr & msg) private
callback function for pose
Parameters
msg pose stamped msg
Definition at line 202 of file platoon_control_ihp.cpp.
    {
        pose_msg_ = geometry_msgs::PoseStamped(*msg.get());
        pcw_.setCurrentPose(pose_msg_);
    }
References pcw_, pose_msg_, and platoon_control_ihp::PlatoonControlIHPWorker::setCurrentPose().
Referenced by initialize().
run()
void platoon_control_ihp::PlatoonControlIHPPlugin::run ()
general starting point of this node
Definition at line 103 of file platoon_control_ihp.cpp.
    {
        initialize();
        ros::CARMANodeHandle::spin();
    }
References initialize().
Referenced by main().
trajectoryPlan_cb()
void platoon_control_ihp::PlatoonControlIHPPlugin::trajectoryPlan_cb (const cav_msgs::TrajectoryPlan::ConstPtr & tp) private
callback function for trajectory plan
Parameters
msg trajectory plan msg
Definition at line 142 of file platoon_control_ihp.cpp.
    {
        if (tp->trajectory_points.size() < 2) {
            ROS_WARN_STREAM("PlatoonControlIHPPlugin cannot execute trajectory as only 1 point was provided");
            return;
        }
        latest_trajectory_ = *tp;
        prev_input_time_ = ros::Time::now().toNSec() / 1000000;
        ++consecutive_input_counter_;
        ROS_DEBUG_STREAM("New trajectory plan #" << consecutive_input_counter_ << " at time " << prev_input_time_);
        ROS_DEBUG_STREAM("tp header time =                " << tp->header.stamp.toNSec() / 1000000);
    }
References consecutive_input_counter_, latest_trajectory_, and prev_input_time_.
Referenced by initialize().
Member Data Documentation
config_
PlatooningControlIHPPluginConfig platoon_control_ihp::PlatoonControlIHPPlugin::config_ private
Definition at line 116 of file platoon_control_ihp.h.
Referenced by controlTimerCb(), getLookaheadTrajectoryPoint(), and initialize().
consecutive_input_counter_
long platoon_control_ihp::PlatoonControlIHPPlugin::consecutive_input_counter_ = 0 private
Definition at line 122 of file platoon_control_ihp.h.
Referenced by controlTimerCb(), and trajectoryPlan_cb().
control_pub_timer_
ros::Timer platoon_control_ihp::PlatoonControlIHPPlugin::control_pub_timer_ private
Definition at line 169 of file platoon_control_ihp.h.
Referenced by initialize().
ctrl_pub_
ros::Publisher platoon_control_ihp::PlatoonControlIHPPlugin::ctrl_pub_ private
Definition at line 165 of file platoon_control_ihp.h.
Referenced by generateControlSignals(), and initialize().
current_speed_
double platoon_control_ihp::PlatoonControlIHPPlugin::current_speed_ = 0.0
Definition at line 100 of file platoon_control_ihp.h.
Referenced by currentTwist_cb(), and getLookaheadTrajectoryPoint().
current_twist_sub_
ros::Subscriber platoon_control_ihp::PlatoonControlIHPPlugin::current_twist_sub_ private
Definition at line 160 of file platoon_control_ihp.h.
Referenced by initialize().
discovery_pub_timer_
ros::Timer platoon_control_ihp::PlatoonControlIHPPlugin::discovery_pub_timer_ private
Definition at line 168 of file platoon_control_ihp.h.
Referenced by initialize().
latest_trajectory_
cav_msgs::TrajectoryPlan platoon_control_ihp::PlatoonControlIHPPlugin::latest_trajectory_
Definition at line 103 of file platoon_control_ihp.h.
Referenced by controlTimerCb(), and trajectoryPlan_cb().
nh_
std::shared_ptr<ros::CARMANodeHandle> platoon_control_ihp::PlatoonControlIHPPlugin::nh_ private
Definition at line 110 of file platoon_control_ihp.h.
Referenced by initialize().
pcw_
PlatoonControlIHPWorker platoon_control_ihp::PlatoonControlIHPPlugin::pcw_ private
Definition at line 113 of file platoon_control_ihp.h.
Referenced by PlatoonControlIHPPlugin(), generateControlSignals(), initialize(), platoonInfo_cb(), and pose_cb().
platoon_info_pub_
ros::Publisher platoon_control_ihp::PlatoonControlIHPPlugin::platoon_info_pub_ private
Definition at line 167 of file platoon_control_ihp.h.
Referenced by initialize(), and platoonInfo_cb().
platoon_info_sub_
ros::Subscriber platoon_control_ihp::PlatoonControlIHPPlugin::platoon_info_sub_ private
Definition at line 162 of file platoon_control_ihp.h.
Referenced by initialize().
platoon_leader_
PlatoonLeaderInfo platoon_control_ihp::PlatoonControlIHPPlugin::platoon_leader_ private
Definition at line 120 of file platoon_control_ihp.h.
Referenced by generateControlSignals(), and platoonInfo_cb().
plugin_discovery_msg_
cav_msgs::Plugin platoon_control_ihp::PlatoonControlIHPPlugin::plugin_discovery_msg_ private
Definition at line 156 of file platoon_control_ihp.h.
Referenced by initialize().
plugin_discovery_pub_
ros::Publisher platoon_control_ihp::PlatoonControlIHPPlugin::plugin_discovery_pub_ private
Definition at line 166 of file platoon_control_ihp.h.
Referenced by initialize().
pnh_
std::shared_ptr<ros::CARMANodeHandle> platoon_control_ihp::PlatoonControlIHPPlugin::pnh_ private
Definition at line 110 of file platoon_control_ihp.h.
Referenced by initialize().
pose_msg_
geometry_msgs::PoseStamped platoon_control_ihp::PlatoonControlIHPPlugin::pose_msg_
Definition at line 97 of file platoon_control_ihp.h.
Referenced by getLookaheadTrajectoryPoint(), and pose_cb().
pose_sub_
ros::Subscriber platoon_control_ihp::PlatoonControlIHPPlugin::pose_sub_ private
Definition at line 161 of file platoon_control_ihp.h.
Referenced by initialize().
prev_input_time_
long platoon_control_ihp::PlatoonControlIHPPlugin::prev_input_time_ = 0 private
Definition at line 121 of file platoon_control_ihp.h.
Referenced by controlTimerCb(), and trajectoryPlan_cb().
trajectory_plan_sub
ros::Subscriber platoon_control_ihp::PlatoonControlIHPPlugin::trajectory_plan_sub private
Definition at line 159 of file platoon_control_ihp.h.
Referenced by initialize().
trajectory_speed_
double platoon_control_ihp::PlatoonControlIHPPlugin::trajectory_speed_ = 0.0
Definition at line 101 of file platoon_control_ihp.h.
Referenced by controlTimerCb(), and generateControlSignals().
twist_pub_
ros::Publisher platoon_control_ihp::PlatoonControlIHPPlugin::twist_pub_ private
Definition at line 164 of file platoon_control_ihp.h.
Referenced by generateControlSignals(), and initialize().
The documentation for this class was generated from the following files:
platooning_control_ihp/include/platoon_control_ihp.h
platooning_control_ihp/src/platoon_control_ihp.cpp