Carma-platform: subsystem_controllers::EntryManager Class Reference
subsystem_controllers::EntryManager Class Reference
The EntryManager serves as a component to track the status of each required CARMA ROS 1 driver.
#include <entry_manager.hpp>
Public Member Functions
EntryManager ()
Default constructor for EntryManager.
EntryManager (std::vector< std::string > required_entries)
Constructor for EntryManager to set required entries.
EntryManager (std::vector< std::string > required_entries, std::vector< std::string > camera_entries)
Constructor for EntryManager to set required entries and camera entires.
void update_entry (const Entry &entry)
Add a new entry if the given name does not exist. Update an existing entry if the given name exists.
std::vector< Entry > get_entries () const
Get all registed entries as a list.
boost::optional< Entry > get_entry_by_name (const std::string &name) const
Get a entry using name as the key.
void delete_entry (const std::string &name)
Delete an entry using the given name as the key.
bool is_entry_required (const std::string &name) const
Check if the entry is required.
int is_camera_entry_required (const std::string &name) const
Check if the entry is a required camera entry.
EntryManager ()=default
Default constructor for EntryManager.
void update_entry (const Entry &entry)
Add a new entry if the given name does not exist. Update an existing entry if the given name exists.
std::vector< Entry > get_entries () const
Get all entries as a list.
std::vector< std::string > get_entry_names () const
Get all entry names as a list.
boost::optional< Entry > get_entry_by_name (const std::string &name) const
Get a entry using name as the key.
void delete_entry (const std::string &name)
Delete an entry using the given name as the key.
Private Attributes
std::vector< Entry > entry_list_
private list to keep track of all entries
std::vector< std::string > required_entries_
std::vector< std::string > camera_entries_
std::unordered_map< std::string, Entry > entry_map_
private map by entry name to keep track of all entries
Detailed Description
The EntryManager serves as a component to track the status of each required CARMA ROS 1 driver.
An entry manager keeps track of the set of entries and makes it easy to add or remove entries.
Definition at line 30 of file entry_manager.hpp.
Constructor & Destructor Documentation
EntryManager() [1/4]
subsystem_controllers::EntryManager::EntryManager ()
Default constructor for EntryManager.
Definition at line 22 of file entry_manager.cpp.
{}
EntryManager() [2/4]
subsystem_controllers::EntryManager::EntryManager (std::vector< std::string > required_entries)
Constructor for EntryManager to set required entries.
Definition at line 24 of file entry_manager.cpp.
:required_entries_(required_entries) {}
EntryManager() [3/4]
subsystem_controllers::EntryManager::EntryManager (std::vector< std::string > required_entries, std::vector< std::string > camera_entries)
Constructor for EntryManager to set required entries and camera entires.
Definition at line 26 of file entry_manager.cpp.
                :required_entries_(required_entries), camera_entries_(camera_entries){}
EntryManager() [4/4]
subsystem_controllers::EntryManager::EntryManager () default
Default constructor for EntryManager.
Member Function Documentation
delete_entry() [1/2]
void subsystem_controllers::EntryManager::delete_entry (const std::string & name)
Delete an entry using the given name as the key.
Definition at line 50 of file entry_manager.cpp.
    {
        for(auto i = entry_list_.begin(); i < entry_list_.end(); ++i)
        {
            if(i->name_.compare(name) == 0)
            {
                entry_list_.erase(i);
                return;
            }
        }
    }
References entry_list_, and process_bag::i.
delete_entry() [2/2]
void subsystem_controllers::EntryManager::delete_entry (const std::string & name)
Delete an entry using the given name as the key.
get_entries() [1/2]
std::vector< Entry > subsystem_controllers::EntryManager::get_entries () const
Get all registed entries as a list.
Definition at line 44 of file entry_manager.cpp.
    {
        // returns the copy of the original list
        return std::vector<Entry>(entry_list_);
    }
References entry_list_.
Referenced by subsystem_controllers::PluginManager::activate(), subsystem_controllers::PluginManager::cleanup(), subsystem_controllers::PluginManager::configure(), subsystem_controllers::PluginManager::deactivate(), subsystem_controllers::PluginManager::get_active_plugins(), subsystem_controllers::PluginManager::get_control_plugins_by_capability(), subsystem_controllers::PluginManager::get_registered_plugins(), subsystem_controllers::PluginManager::get_strategic_plugins_by_capability(), and subsystem_controllers::PluginManager::get_tactical_plugins_by_capability().
get_entries() [2/2]
std::vector< Entry > subsystem_controllers::EntryManager::get_entries () const
Get all entries as a list.
get_entry_by_name() [1/2]
boost::optional< Entry > subsystem_controllers::EntryManager::get_entry_by_name (const std::string & name) const
Get a entry using name as the key.
Definition at line 62 of file entry_manager.cpp.
    {
        for(auto i = entry_list_.begin(); i < entry_list_.end(); ++i)
        {
            if(i->name_.compare(name) == 0)
            {
                return *i;
            }
        }
        // use boost::optional because requested entry might not exist
        return boost::none;
    }
References entry_list_, and process_bag::i.
Referenced by subsystem_controllers::PluginManager::activate_plugin(), and subsystem_controllers::PluginManager::update_plugin_status().
get_entry_by_name() [2/2]
boost::optional< Entry > subsystem_controllers::EntryManager::get_entry_by_name (const std::string & name) const
Get a entry using name as the key.
get_entry_names()
std::vector< std::string > subsystem_controllers::EntryManager::get_entry_names () const
Get all entry names as a list.
Definition at line 40 of file entry_manager.cpp.
    {
        std::vector<std::string> names;
        names.reserve(entry_map_.size());
        for (const auto& e : entry_map_)
            names.push_back(e.second.name_);
        return names;
    }
References entry_map_.
Referenced by subsystem_controllers::PluginManager::shutdown().
is_camera_entry_required()
int subsystem_controllers::EntryManager::is_camera_entry_required (const std::string & name) const
Check if the entry is a required camera entry.
Definition at line 87 of file entry_manager.cpp.
    {
        for(int i = 0;i < camera_entries_.size(); i++)
        {
            if(camera_entries_[i].compare(name) == 0)
            {
                return i;
            }
        }
        // default like above?
        return -1;
    }
References camera_entries_, and process_bag::i.
is_entry_required()
bool subsystem_controllers::EntryManager::is_entry_required (const std::string & name) const
Check if the entry is required.
Definition at line 75 of file entry_manager.cpp.
    {
        for(auto i = required_entries_.begin(); i < required_entries_.end(); ++i)
        {
            if(i->compare(name) == 0)
            {
                return true;
            }
        }
        return false;
    }
References process_bag::i, and required_entries_.
update_entry() [1/2]
void subsystem_controllers::EntryManager::update_entry (const Entry & entry)
Add a new entry if the given name does not exist. Update an existing entry if the given name exists.
Definition at line 29 of file entry_manager.cpp.
    {
        for(auto i = entry_list_.begin(); i < entry_list_.end(); ++i)
        {
            if(i->name_.compare(entry.name_) == 0)
            {
                // name entry wont change
                i->available_ = entry.available_;
                i->timestamp_ = entry.timestamp_;
                return;
            }
        }
        entry_list_.push_back(entry);
    }
References subsystem_controllers::Entry::available_, entry_list_, process_bag::i, subsystem_controllers::Entry::name_, and subsystem_controllers::Entry::timestamp_.
Referenced by subsystem_controllers::PluginManager::PluginManager(), subsystem_controllers::PluginManager::activate(), subsystem_controllers::PluginManager::activate_plugin(), subsystem_controllers::PluginManager::add_plugin(), subsystem_controllers::PluginManager::cleanup(), subsystem_controllers::PluginManager::configure(), subsystem_controllers::PluginManager::deactivate(), and subsystem_controllers::PluginManager::update_plugin_status().
update_entry() [2/2]
void subsystem_controllers::EntryManager::update_entry (const Entry & entry)
Add a new entry if the given name does not exist. Update an existing entry if the given name exists.
Parameters
entry The entry to update or add
Member Data Documentation
camera_entries_
std::vector<std::string> subsystem_controllers::EntryManager::camera_entries_ private
Definition at line 89 of file entry_manager.hpp.
Referenced by is_camera_entry_required().
entry_list_
std::vector<Entry> subsystem_controllers::EntryManager::entry_list_ private
private list to keep track of all entries
Definition at line 83 of file entry_manager.hpp.
Referenced by delete_entry(), get_entries(), get_entry_by_name(), and update_entry().
entry_map_
std::unordered_map<std::string, Entry> subsystem_controllers::EntryManager::entry_map_ private
private map by entry name to keep track of all entries
Definition at line 69 of file entry_manager.h.
Referenced by get_entry_names().
required_entries_
std::vector<std::string> subsystem_controllers::EntryManager::required_entries_ private
Definition at line 86 of file entry_manager.hpp.
Referenced by is_entry_required().
The documentation for this class was generated from the following files:
subsystem_controllers/include/subsystem_controllers/drivers_controller/entry_manager.hpp
subsystem_controllers/include/subsystem_controllers/guidance_controller/entry_manager.h
subsystem_controllers/src/drivers_controller/entry_manager.cpp
subsystem_controllers/src/guidance_controller/entry_manager.cpp