Carma-platform: inlanecruising_plugin/src/helper.cpp File Reference
helper.cpp File Reference
#include "ros/ros.h"
#include <cav_srvs/PlanTrajectory.h>
Functions
bool callback (cav_srvs::PlanTrajectory::Request &req, cav_srvs::PlanTrajectory::Response &res)
int main (int argc, char **argv)
Function Documentation
callback()
bool callback (cav_srvs::PlanTrajectory::Request & req, cav_srvs::PlanTrajectory::Response & res)
Definition at line 21 of file helper.cpp.
{
    if (req.initial_trajectory_plan.trajectory_id == "YieldReq"){
        res.trajectory_plan.trajectory_id = "YieldResp";
    }
    ROS_ERROR("Yield callback");
    return true;
}
Referenced by mock_drivers::MockDriverNode::addSrv(), mock_drivers::MockDriverNode::addSub(), main(), carma_wm::WMListener::setMapCallback(), carma_wm::WMListenerWorker::setMapCallback(), carma_wm::WMListener::setRouteCallback(), and carma_wm::WMListenerWorker::setRouteCallback().
main()
int main (int argc, char ** argv)
Definition at line 32 of file helper.cpp.
{
  ros::init(argc, argv, "helper");
  ros::NodeHandle n;
  ros::ServiceServer service = n.advertiseService("yield_plugin/plan_trajectory", callback);
  ros::spin();
  ros::Duration(5).sleep();
  return 0;
}
References callback().