Carma-platform: tf2::anonymous_namespace{PoseToTF2.cpp} Namespace Reference
tf2::anonymous_namespace{PoseToTF2.cpp} Namespace Reference
Functions
void convert (const geometry_msgs::msg::Pose &pose, geometry_msgs::msg::Transform &trans)
void convert (const geometry_msgs::msg::PoseWithCovariance &pose, geometry_msgs::msg::Transform &trans)
void convert (const geometry_msgs::msg::PoseStamped &pose, geometry_msgs::msg::TransformStamped &trans)
void convert (const geometry_msgs::msg::PoseWithCovarianceStamped &pose, geometry_msgs::msg::TransformStamped &trans)
Function Documentation
convert() [1/4]
void tf2::anonymous_namespace{PoseToTF2.cpp}::convert (const geometry_msgs::msg::Pose & pose, geometry_msgs::msg::Transform & trans)
Definition at line 30 of file PoseToTF2.cpp.
{
  trans.rotation = pose.orientation;
  trans.translation.x = pose.position.x;
  trans.translation.y = pose.position.y;
  trans.translation.z = pose.position.z;
}
convert() [2/4]
void tf2::anonymous_namespace{PoseToTF2.cpp}::convert (const geometry_msgs::msg::PoseStamped & pose, geometry_msgs::msg::TransformStamped & trans)
Definition at line 43 of file PoseToTF2.cpp.
{
  convert(pose.pose, trans.transform);
  trans.header = pose.header;
}
References convert().
convert() [3/4]
void tf2::anonymous_namespace{PoseToTF2.cpp}::convert (const geometry_msgs::msg::PoseWithCovariance & pose, geometry_msgs::msg::Transform & trans)
Definition at line 38 of file PoseToTF2.cpp.
{
  convert(pose.pose, trans);
}
References convert().
convert() [4/4]
void tf2::anonymous_namespace{PoseToTF2.cpp}::convert (const geometry_msgs::msg::PoseWithCovarianceStamped & pose, geometry_msgs::msg::TransformStamped & trans)
Definition at line 49 of file PoseToTF2.cpp.
{
  convert(pose.pose, trans.transform);
  trans.header = pose.header;
}
References convert().
Referenced by convert(), pose_to_tf::PoseToTF2::poseCallback(), pose_to_tf::PoseToTF2::poseStampedCallback(), pose_to_tf::PoseToTF2::poseWithCovarianceCallback(), and pose_to_tf::PoseToTF2::poseWithCovarianceStampedCallback().