Carma-platform: speedharm-cli Namespace Reference
speedharm-cli Namespace Reference
Functions
def print_response (resp)
def unknown_command (cmd)
def process_set_command (parts)
def process_get_command (parts)
def process_delete_command (parts)
def cd (new_url)
def process_cd_command (parts)
def process_post_command (parts)
def process_create_vehicle ()
def process_create_experiment ()
def process_create_algorithm ()
def process_create_command (parts)
def select_vehicle ()
def process_assign_experiment ()
def process_assign_algorithm ()
def process_assign_command (parts)
def process_list_vehicles ()
def process_list_experiments ()
def process_list_algorithms ()
def process_list_command (parts)
def process_fetch_command (parts)
def parse_input (cmd)
def get_cur_url ()
def main ()
Variables
string version_id = "v0.1"
bool running = True
string base_url = "http://35.153.64.44:8081"
string rel_url = ""
string vehicles_url = "/rest/vehicles"
string experiments_url = "/rest/experiments"
string algorithms_url = "/rest/algorithms"
Function Documentation
cd()
def speedharm-cli.cd (new_url)
Definition at line 73 of file speedharm-cli.py.
def cd(new_url):
    global rel_url
    rel_url = urlparse.urljoin(rel_url, new_url)
Referenced by process_cd_command().
get_cur_url()
def speedharm-cli.get_cur_url ()
Definition at line 279 of file speedharm-cli.py.
def get_cur_url():
    return urlparse.urljoin(base_url, rel_url)
Referenced by main(), process_delete_command(), process_get_command(), and process_post_command().
main()
def speedharm-cli.main ()
Definition at line 282 of file speedharm-cli.py.
def main():
    print("Speed Harmonization Command Line Configurator " + version_id + ".")
    while running:
        parse_input(raw_input(get_cur_url() + ">> "))
References get_cur_url(), main(), and parse_input().
Referenced by main().
parse_input()
def speedharm-cli.parse_input (cmd)
Parse the command input and execute the appropriate action
Definition at line 232 of file speedharm-cli.py.
def parse_input(cmd):
    """
    Parse the command input and execute the appropriate action
    """
    parts = cmd.split(' ') # Split on spaces
    args = {"set" : "variable value", "get" : "[url]", "cd" : "rel_url",
            "post" : "data", "delete" : "[url]", "create" : "(vehicle | experiment | algorithm)",
            "assign" : "(experiment | algorithm)", "list" : "(vehicle | experiment | algorithm)",
            "fetch" : "(vehicle | experiment | algorithm) id", "help": "", "exit" : ""}
    try:
        if parts[0] == "exit":
            global running
            running = False
            exit(0)
        elif parts[0] == "set":
            process_set_command(parts)
        elif parts[0] == "get":
            process_get_command(parts)
        elif parts[0] == "cd":
            process_cd_command(parts)
        elif parts[0] == "post":
            process_post_command(parts)
        elif parts[0] == "delete":
            process_delete_command(parts)
        elif parts[0] == "create":
            process_create_command(parts)
        elif parts[0] == "assign":
            process_assign_command(parts)
        elif parts[0] == "list":
            process_list_command(parts)
        elif parts[0] == "fetch":
            process_fetch_command(parts)
        elif parts[0] == "help":
            print("Commands: ")
            for cmd, usage in args.items():
                print("{} {}".format(cmd, usage))
        else:
            unknown_command(cmd)
    except IndexError:
        print("Incorrect usage of: " + parts[0])
        print("Usage: " + parts[0] + " " + args[parts[0]])
    except requests.exceptions.ConnectionError:
        print("Unable to connect to " + base_url + ".")
References process_assign_command(), process_cd_command(), process_create_command(), process_delete_command(), process_fetch_command(), process_get_command(), process_list_command(), process_post_command(), process_set_command(), and unknown_command().
Referenced by main().
print_response()
def speedharm-cli.print_response (resp)
Definition at line 40 of file speedharm-cli.py.
def print_response(resp):
    try:
        print(resp.status_code)
        print(resp.headers)
        print(resp.json())
    except:
        print("Unable to decode the rest of the response.")
Referenced by process_assign_algorithm(), process_assign_experiment(), process_create_algorithm(), process_create_experiment(), process_create_vehicle(), process_delete_command(), process_fetch_command(), process_get_command(), and process_post_command().
process_assign_algorithm()
def speedharm-cli.process_assign_algorithm ()
Definition at line 162 of file speedharm-cli.py.
def process_assign_algorithm():
    veh_id = select_vehicle()
    r = requests.get(urlparse.urljoin(base_url, algorithms_url), verify=False).json()
    print("Select Algorithm: ")
    for exp in r:
        print("{}. Class: {}".format(exp["id"], exp["className"]))
    algo_id = raw_input("Algorithm ID#? ")
    headers = { "Content-Type" : "application/json" }
    data = json.dumps({"id": int(veh_id)})
    r = requests.post(urlparse.urljoin(base_url, algorithms_url + "/" + algo_id + "/vehicles"), data=data, headers=headers, verify=False)
    print_response(r)
References print_response(), and select_vehicle().
Referenced by process_assign_command().
process_assign_command()
def speedharm-cli.process_assign_command (parts)
Definition at line 178 of file speedharm-cli.py.
def process_assign_command(parts):
    if parts[1] == "experiment":
        process_assign_experiment()
    elif parts[1] == "algorithm":
        process_assign_algorithm()
    else:
        print("Unknown relationship to assign: " + parts[1])
References process_assign_algorithm(), and process_assign_experiment().
Referenced by parse_input().
process_assign_experiment()
def speedharm-cli.process_assign_experiment ()
Definition at line 146 of file speedharm-cli.py.
def process_assign_experiment():
    veh_id = select_vehicle()
    r = requests.get(urlparse.urljoin(base_url, experiments_url), verify=False).json()
    print("Select Experiment: ")
    for exp in r:
        print("{}. Description: {}; Location: {}".format(exp["id"], exp["description"], exp["location"]))
    exp_id = raw_input("Experiment ID#? ")
    headers = { "Content-Type" : "application/json" }
    data = json.dumps({"id": int(veh_id)})
    r = requests.post(urlparse.urljoin(base_url, experiments_url + "/" + exp_id + "/vehicles"), data=data, headers=headers, verify=False)
    print_response(r)
References print_response(), and select_vehicle().
Referenced by process_assign_command().
process_cd_command()
def speedharm-cli.process_cd_command (parts)
Definition at line 77 of file speedharm-cli.py.
def process_cd_command(parts):
    cd(parts[1])
References cd().
Referenced by parse_input().
process_create_algorithm()
def speedharm-cli.process_create_algorithm ()
Definition at line 110 of file speedharm-cli.py.
def process_create_algorithm():
    # Get the available algorithms
    r = requests.get(urlparse.urljoin(base_url, "/rest/"), verify=False)
    algos = r.json()["availableAlgorithms"]
    print("Select Algorithm: ")
    for a in zip(algos, range(len(algos))):
        print("{}. {}".format(a[1] + 1, a[0]))
    idx = input("Choice #? ") - 1
    full_url = urlparse.urljoin(base_url, algorithms_url)
    headers = { "Content-Type" : "application/json" }
    data = json.dumps({"className": algos[idx]})
    r = requests.post(full_url, data=data, headers=headers, verify=False)
    print_response(r)
References print_response().
Referenced by process_create_command().
process_create_command()
def speedharm-cli.process_create_command (parts)
Definition at line 127 of file speedharm-cli.py.
def process_create_command(parts):
    if parts[1] == "vehicle":
        process_create_vehicle()
    elif parts[1] == "experiment":
        process_create_experiment()
    elif parts[1] == "algorithm":
        process_create_algorithm()
    else:
        print("Unknown entity to create: " + parts[1])
References process_create_algorithm(), process_create_experiment(), and process_create_vehicle().
Referenced by parse_input().
process_create_experiment()
def speedharm-cli.process_create_experiment ()
Definition at line 102 of file speedharm-cli.py.
def process_create_experiment():
    description = raw_input("Experiment Description: ")
    location = raw_input("Experiment Location: ")
    full_url = urlparse.urljoin(base_url, experiments_url)
    headers = { "Content-Type" : "application/json" }
    r = requests.post(full_url, data=json.dumps({"description": description, "location": location}), headers=headers, verify=False)
    print_response(r)
References print_response().
Referenced by process_create_command().
process_create_vehicle()
def speedharm-cli.process_create_vehicle ()
Definition at line 94 of file speedharm-cli.py.
def process_create_vehicle():
    uniqVehId = raw_input("Unique Vehicle ID: ")
    description = raw_input("Vehicle Description: ")
    full_url = urlparse.urljoin(base_url, vehicles_url)
    headers = { "Content-Type" : "application/json" }
    r = requests.post(full_url, data=json.dumps({"uniqVehId": uniqVehId, "description": description}), headers=headers, verify=False)
    print_response(r)
References print_response().
Referenced by process_create_command().
process_delete_command()
def speedharm-cli.process_delete_command (parts)
Definition at line 63 of file speedharm-cli.py.
def process_delete_command(parts):
    full_url = get_cur_url()
    if (len(parts) > 1):
        full_url = urlparse.urljoin(full_url, parts[1])
    ack = raw_input("Are you sure you want to delete " + full_url +"?\n(y/N): ")
    if ack.lower() == "y":
        r = requests.delete(full_url, verify=False)
        print_response(r)
References get_cur_url(), and print_response().
Referenced by parse_input().
process_fetch_command()
def speedharm-cli.process_fetch_command (parts)
Definition at line 218 of file speedharm-cli.py.
def process_fetch_command(parts):
    if parts[1] == "vehicle":
        full_url = urlparse.urljoin(base_url, vehicles_url)
    elif parts[1] == "experiment":
        full_url = urlparse.urljoin(base_url, experiments_url)
    elif parts[1] == "algorithm":
        full_url = urlparse.urljoin(base_url, algorithms_url)
    else:
        print("Unknown entity to fetch: " + parts[1])
        return
    r = requests.get(full_url + "/" + parts[2], verify=False)
    print_response(r)
References print_response().
Referenced by parse_input().
process_get_command()
def speedharm-cli.process_get_command (parts)
Definition at line 54 of file speedharm-cli.py.
def process_get_command(parts):
    full_url = get_cur_url()
    if (len(parts) > 1):
        # A url has been specified
        full_url = urlparse.urljoin(full_url, parts[1])
    r = requests.get(full_url, verify=False)
    print_response(r)
References get_cur_url(), and print_response().
Referenced by parse_input().
process_list_algorithms()
def speedharm-cli.process_list_algorithms ()
Definition at line 201 of file speedharm-cli.py.
def process_list_algorithms():
    r = requests.get(urlparse.urljoin(base_url, algorithms_url), verify=False).json()
    print("Algorithms:")
    for veh in r:
        print("{}. ClassName: {}".format(veh["id"], veh["className"]))
Referenced by process_list_command().
process_list_command()
def speedharm-cli.process_list_command (parts)
Definition at line 208 of file speedharm-cli.py.
def process_list_command(parts):
    if parts[1] == "vehicles":
        process_list_vehicles()
    elif parts[1] == "experiments":
        process_list_experiments()
    elif parts[1] == "algorithms":
        process_list_algorithms()
    else:
        print("Unknown entity to list: " + parts[1])
References process_list_algorithms(), process_list_experiments(), and process_list_vehicles().
Referenced by parse_input().
process_list_experiments()
def speedharm-cli.process_list_experiments ()
Definition at line 194 of file speedharm-cli.py.
def process_list_experiments():
    r = requests.get(urlparse.urljoin(base_url, experiments_url), verify=False).json()
    print("Experiments:")
    for veh in r:
        print("{}. Description: {}; Location: {}".format(veh["id"], veh["description"], veh["location"]))
Referenced by process_list_command().
process_list_vehicles()
def speedharm-cli.process_list_vehicles ()
Definition at line 187 of file speedharm-cli.py.
def process_list_vehicles():
    r = requests.get(urlparse.urljoin(base_url, vehicles_url), verify=False).json()
    print("Vehicles:")
    for veh in r:
        print("{}. Description: {}; Unique ID: {}".format(veh["id"], veh["description"], veh["uniqVehId"]))
Referenced by process_list_command().
process_post_command()
def speedharm-cli.process_post_command (parts)
Definition at line 80 of file speedharm-cli.py.
def process_post_command(parts):
    data_start = 1
    full_url = get_cur_url()
    # if len(parts) > 2:
    #     data_start = 2
    #     full_url = urlparse.urljoin(full_url, parts[1])
    data = eval(" ".join(parts[data_start:]))
    headers = { "Content-Type" : "application/json" }
    r = requests.post(full_url, data=json.dumps(data), headers=headers, verify=False)
    print_response(r)
References get_cur_url(), and print_response().
Referenced by parse_input().
process_set_command()
def speedharm-cli.process_set_command (parts)
Definition at line 51 of file speedharm-cli.py.
def process_set_command(parts):
    exec("global " + parts[1] + ";" + parts[1] + " = " + parts[2])
Referenced by parse_input().
select_vehicle()
def speedharm-cli.select_vehicle ()
Definition at line 137 of file speedharm-cli.py.
def select_vehicle():
    r = requests.get(urlparse.urljoin(base_url, vehicles_url), verify=False).json()
    print("Select Vehicle:")
    for veh in r:
        print("{}. Description: {}; Unique ID: {}".format(veh["id"], veh["description"], veh["uniqVehId"]))
    return raw_input("Vehicle ID#? ")
Referenced by process_assign_algorithm(), and process_assign_experiment().
unknown_command()
def speedharm-cli.unknown_command (cmd)
Definition at line 48 of file speedharm-cli.py.
def unknown_command(cmd):
    print(cmd + " is not a recognized command. Try \"help\" for help.")
Referenced by parse_input().
Variable Documentation
algorithms_url
string speedharm-cli.algorithms_url = "/rest/algorithms"
Definition at line 37 of file speedharm-cli.py.
base_url
string speedharm-cli.base_url = "http://35.153.64.44:8081"
Definition at line 30 of file speedharm-cli.py.
experiments_url
string speedharm-cli.experiments_url = "/rest/experiments"
Definition at line 36 of file speedharm-cli.py.
rel_url
string speedharm-cli.rel_url = ""
Definition at line 32 of file speedharm-cli.py.
running
bool speedharm-cli.running = True
Definition at line 29 of file speedharm-cli.py.
vehicles_url
string speedharm-cli.vehicles_url = "/rest/vehicles"
Definition at line 35 of file speedharm-cli.py.
version_id
string speedharm-cli.version_id = "v0.1"
Definition at line 28 of file speedharm-cli.py.