Carma-platform: plan_delegator::anonymous_namespace{plan_delegator.cpp} Namespace Reference
plan_delegator::anonymous_namespace{plan_delegator.cpp} Namespace Reference
Functions
void setManeuverStartingLaneletId (carma_planning_msgs::msg::Maneuver &mvr, lanelet::Id start_id)
Anonymous function to set the starting_lane_id for all maneuver types except lane following. This maneuver parameter cannot be set with SET_MANEUVER_PROPERTY calls since it is not included in LANE_FOLLOW maneuvers.
void setManeuverEndingLaneletId (carma_planning_msgs::msg::Maneuver &mvr, lanelet::Id end_id)
Anonymous function to set the ending_lane_id for all maneuver types except lane following. This maneuver parameter cannot be set with SET_MANEUVER_PROPERTY calls since it is not included in LANE_FOLLOW maneuvers.
std::string getManeuverStartingLaneletId (carma_planning_msgs::msg::Maneuver mvr)
Anonymous function to get the starting lanelet id for all maneuver types except lane following. This maneuver parameters cannot be obtained with GET_MANEUVER_PROPERTY calls since they are not included in LANE_FOLLOW maneuvers.
std::string getManeuverEndingLaneletId (carma_planning_msgs::msg::Maneuver mvr)
Anonymous function to get the ending lanelet id for all maneuver types except lane following. This maneuver parameters cannot be obtained with GET_MANEUVER_PROPERTY calls since they are not included in LANE_FOLLOW maneuvers.
Function Documentation
getManeuverEndingLaneletId()
std::string plan_delegator::anonymous_namespace{plan_delegator.cpp}::getManeuverEndingLaneletId (carma_planning_msgs::msg::Maneuver mvr)
Anonymous function to get the ending lanelet id for all maneuver types except lane following. This maneuver parameters cannot be obtained with GET_MANEUVER_PROPERTY calls since they are not included in LANE_FOLLOW maneuvers.
Definition at line 112 of file plan_delegator.cpp.
{
            switch(mvr.type) {
                case carma_planning_msgs::msg::Maneuver::LANE_CHANGE:
                    return mvr.lane_change_maneuver.ending_lane_id;
                case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_STRAIGHT:
                    return mvr.intersection_transit_straight_maneuver.ending_lane_id;
                case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_LEFT_TURN:
                    return mvr.intersection_transit_left_turn_maneuver.ending_lane_id;
                case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_RIGHT_TURN:
                    return mvr.intersection_transit_right_turn_maneuver.ending_lane_id;
                case carma_planning_msgs::msg::Maneuver::STOP_AND_WAIT:
                    return mvr.stop_and_wait_maneuver.ending_lane_id;
                default:
                    throw std::invalid_argument("Maneuver type does not have starting and ending lane ids");
            }
        }
Referenced by plan_delegator::PlanDelegator::updateManeuverParameters().
getManeuverStartingLaneletId()
std::string plan_delegator::anonymous_namespace{plan_delegator.cpp}::getManeuverStartingLaneletId (carma_planning_msgs::msg::Maneuver mvr)
Anonymous function to get the starting lanelet id for all maneuver types except lane following. This maneuver parameters cannot be obtained with GET_MANEUVER_PROPERTY calls since they are not included in LANE_FOLLOW maneuvers.
Definition at line 90 of file plan_delegator.cpp.
{
            switch(mvr.type) {
                case carma_planning_msgs::msg::Maneuver::LANE_CHANGE:
                    return mvr.lane_change_maneuver.starting_lane_id;
                case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_STRAIGHT:
                    return mvr.intersection_transit_straight_maneuver.starting_lane_id;
                case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_LEFT_TURN:
                    return mvr.intersection_transit_left_turn_maneuver.starting_lane_id;
                case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_RIGHT_TURN:
                    return mvr.intersection_transit_right_turn_maneuver.starting_lane_id;
                case carma_planning_msgs::msg::Maneuver::STOP_AND_WAIT:
                    return mvr.stop_and_wait_maneuver.starting_lane_id;
                default:
                    throw std::invalid_argument("Maneuver type does not have starting and ending lane ids");
            }
        }
Referenced by plan_delegator::PlanDelegator::updateManeuverParameters().
setManeuverEndingLaneletId()
void plan_delegator::anonymous_namespace{plan_delegator.cpp}::setManeuverEndingLaneletId (carma_planning_msgs::msg::Maneuver & mvr, lanelet::Id end_id)
Anonymous function to set the ending_lane_id for all maneuver types except lane following. This maneuver parameter cannot be set with SET_MANEUVER_PROPERTY calls since it is not included in LANE_FOLLOW maneuvers.
Definition at line 61 of file plan_delegator.cpp.
{
            RCLCPP_DEBUG_STREAM(rclcpp::get_logger("plan_delegator"),"Updating maneuver ending_lane_id to " << end_id);
            switch(mvr.type) {
                case carma_planning_msgs::msg::Maneuver::LANE_CHANGE:
                    mvr.lane_change_maneuver.ending_lane_id = std::to_string(end_id);
                    break;
                case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_STRAIGHT:
                    mvr.intersection_transit_straight_maneuver.ending_lane_id = std::to_string(end_id);
                    break;
                case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_LEFT_TURN:
                    mvr.intersection_transit_left_turn_maneuver.ending_lane_id = std::to_string(end_id);
                    break;
                case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_RIGHT_TURN:
                    mvr.intersection_transit_right_turn_maneuver.ending_lane_id = std::to_string(end_id);
                    break;
                case carma_planning_msgs::msg::Maneuver::STOP_AND_WAIT:
                    mvr.stop_and_wait_maneuver.ending_lane_id = std::to_string(end_id);
                    break;
                default:
                    throw std::invalid_argument("Maneuver type does not have starting and ending lane ids");
            }
        }
References carma_cooperative_perception::to_string().
Referenced by plan_delegator::PlanDelegator::updateManeuverParameters().
setManeuverStartingLaneletId()
void plan_delegator::anonymous_namespace{plan_delegator.cpp}::setManeuverStartingLaneletId (carma_planning_msgs::msg::Maneuver & mvr, lanelet::Id start_id)
Anonymous function to set the starting_lane_id for all maneuver types except lane following. This maneuver parameter cannot be set with SET_MANEUVER_PROPERTY calls since it is not included in LANE_FOLLOW maneuvers.
Definition at line 32 of file plan_delegator.cpp.
{
            RCLCPP_DEBUG_STREAM(rclcpp::get_logger("plan_delegator"),"Updating maneuver starting_lane_id to " << start_id);
            switch(mvr.type) {
                case carma_planning_msgs::msg::Maneuver::LANE_CHANGE:
                    mvr.lane_change_maneuver.starting_lane_id = std::to_string(start_id);
                    break;
                case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_STRAIGHT:
                    mvr.intersection_transit_straight_maneuver.starting_lane_id = std::to_string(start_id);
                    break;
                case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_LEFT_TURN:
                    mvr.intersection_transit_left_turn_maneuver.starting_lane_id = std::to_string(start_id);
                    break;
                case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_RIGHT_TURN:
                    mvr.intersection_transit_right_turn_maneuver.starting_lane_id = std::to_string(start_id);
                    break;
                case carma_planning_msgs::msg::Maneuver::STOP_AND_WAIT:
                    mvr.stop_and_wait_maneuver.starting_lane_id = std::to_string(start_id);
                    break;
                default:
                    throw std::invalid_argument("Maneuver type does not have starting and ending lane ids");
            }
        }
References carma_cooperative_perception::to_string().
Referenced by plan_delegator::PlanDelegator::updateManeuverParameters().