Carma-platform: yield_plugin Namespace Reference
yield_plugin Namespace Reference
Classes
struct GetCollisionResult
Convenience class for saving collision results.
struct PointSpeedPair
Convenience class for pairing 2d points with speeds.
class YieldPlugin
Class containing primary business logic for the In-Lane Cruising Plugin.
class YieldPluginNode
ROS node for the YieldPlugin.
Typedefs
using MobilityResponseCB = std::function< void(const carma_v2x_msgs::msg::MobilityResponse &)>
using LaneChangeStatusCB = std::function< void(const carma_planning_msgs::msg::LaneChangeStatus &)>
Functions
def generate_launch_description ()
double get_trajectory_end_time (const carma_planning_msgs::msg::TrajectoryPlan &trajectory)
double get_trajectory_start_time (const carma_planning_msgs::msg::TrajectoryPlan &trajectory)
double get_trajectory_duration (const carma_planning_msgs::msg::TrajectoryPlan &trajectory)
double get_trajectory_duration (const std::vector< carma_perception_msgs::msg::PredictedState > &trajectory)
double get_smallest_time_step_of_traj (const carma_planning_msgs::msg::TrajectoryPlan &original_tp)
Typedef Documentation
LaneChangeStatusCB
using yield_plugin::LaneChangeStatusCB = typedef std::function<void(const carma_planning_msgs::msg::LaneChangeStatus&)>
Definition at line 52 of file yield_plugin.hpp.
MobilityResponseCB
using yield_plugin::MobilityResponseCB = typedef std::function<void(const carma_v2x_msgs::msg::MobilityResponse&)>
Definition at line 51 of file yield_plugin.hpp.
Function Documentation
generate_launch_description()
def yield_plugin.generate_launch_description ()
Definition at line 31 of file yield_plugin.launch.py.
def generate_launch_description():
    # Declare the log_level launch argument
    log_level = LaunchConfiguration('log_level')
    declare_log_level_arg = DeclareLaunchArgument(
        name ='log_level', default_value='DEBUG')
    # Get parameter file path
    param_file_path = os.path.join(
        get_package_share_directory('yield_plugin'), 'config/parameters.yaml')
    # Launch node(s) in a carma container to allow logging to be configured
    container = ComposableNodeContainer(
        package='carma_ros2_utils',
        name='yield_plugin_container',
        namespace=GetCurrentNamespace(),
        executable='carma_component_container_mt',
        composable_node_descriptions=[
            # Launch the core node(s)
            ComposableNode(
                    package='yield_plugin',
                    plugin='yield_plugin::YieldPluginNode',
                    name='yield_plugin',
                    extra_arguments=[
                        {'use_intra_process_comms': True},
                        {'--log-level' : log_level }
                    ],
                    parameters=[ param_file_path ]
            ),
        ]
    )
    return LaunchDescription([
        declare_log_level_arg,
        container
    ])
get_smallest_time_step_of_traj()
double yield_plugin::get_smallest_time_step_of_traj (const carma_planning_msgs::msg::TrajectoryPlan & original_tp)
Definition at line 388 of file yield_plugin.cpp.
  {
    double smallest_time_step = std::numeric_limits<double>::infinity();
    for (size_t i = 0; i < original_tp.trajectory_points.size() - 1; i ++)
    {
      smallest_time_step = std::min(smallest_time_step,
        (rclcpp::Time(original_tp.trajectory_points.at(i + 1).target_time)
        - rclcpp::Time(original_tp.trajectory_points.at(i).target_time)).seconds());
    }
    RCLCPP_DEBUG_STREAM(rclcpp::get_logger("yield_plugin"),"smallest_time_step: " << smallest_time_step);
    return smallest_time_step;
  }
References process_bag::i.
Referenced by yield_plugin::YieldPlugin::generate_JMT_trajectory().
get_trajectory_duration() [1/2]
double yield_plugin::get_trajectory_duration (const carma_planning_msgs::msg::TrajectoryPlan & trajectory)
Definition at line 63 of file yield_plugin.cpp.
  {
    return fabs(get_trajectory_end_time(trajectory) - get_trajectory_start_time(trajectory));
  }
References get_trajectory_end_time(), and get_trajectory_start_time().
Referenced by yield_plugin::YieldPlugin::get_collision().
get_trajectory_duration() [2/2]
double yield_plugin::get_trajectory_duration (const std::vector< carma_perception_msgs::msg::PredictedState > & trajectory)
Definition at line 68 of file yield_plugin.cpp.
  {
    return (rclcpp::Time(trajectory.back().header.stamp) - rclcpp::Time(trajectory.front().header.stamp)).seconds();
  }
get_trajectory_end_time()
double yield_plugin::get_trajectory_end_time (const carma_planning_msgs::msg::TrajectoryPlan & trajectory)
Definition at line 53 of file yield_plugin.cpp.
  {
    return rclcpp::Time(trajectory.trajectory_points.back().target_time).seconds();
  }
Referenced by yield_plugin::YieldPlugin::get_earliest_collision_object_and_time(), yield_plugin::YieldPlugin::get_predicted_velocity_at_time(), get_trajectory_duration(), yield_plugin::YieldPlugin::plan_trajectory_callback(), and yield_plugin::YieldPlugin::update_traj_for_cooperative_behavior().
get_trajectory_start_time()
double yield_plugin::get_trajectory_start_time (const carma_planning_msgs::msg::TrajectoryPlan & trajectory)
Definition at line 58 of file yield_plugin.cpp.
  {
    return rclcpp::Time(trajectory.trajectory_points.front().target_time).seconds();
  }
Referenced by yield_plugin::YieldPlugin::get_collision_time(), and get_trajectory_duration().