Carma-platform: msgIntersect Namespace Reference
msgIntersect Namespace Reference
Functions
def send (msg, ip_send, port_send)
def listen (ip_listen, port_listen)
def main ()
Function Documentation
listen()
def msgIntersect.listen (ip_listen, port_listen)
Definition at line 23 of file msgIntersect.py.
def listen(ip_listen, port_listen):
    listen_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    listen_socket.bind((ip_listen, port_listen))
    return listen_socket
Referenced by main().
main()
def msgIntersect.main ()
Definition at line 30 of file msgIntersect.py.
def main():
    # declarations
    print('Starting intersect.')
    ip_listen = '127.0.0.1'
    ip_send = '192.168.0.146'
    port_listen = 1516  # listen to Immediate Forward Plugin
    port_send = 5398    # send to CARMA listening_port
    sk_listen = listen(ip_listen, port_listen)
    print("Waiting to receive data\n")
    while(1):
        data = sk_listen.recvfrom(10000)[0]
        data = data.decode('ascii')
        # print(data)
        idx = data.find("Payload=")
        payload = data[idx+8:-1]
        encoded = payload.encode('utf-8')
        msgBytes = unhexlify(encoded)
        # send
        send(msgBytes, ip_send, port_send)
        sleep(0.1)
References listen(), main(), and send().
Referenced by main().
send()
def msgIntersect.send (msg, ip_send, port_send)
Definition at line 17 of file msgIntersect.py.
def send(msg, ip_send, port_send):
    sk_send = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sk_send.sendto(msg, (ip_send, port_send))
    # print("Sent: ", msg)
    sk_send.close()
Referenced by main().