Carma-platform: approaching_emergency_vehicle_plugin::anonymous_namespace{approaching_emergency_vehicle_plugin_node.cpp} Namespace Reference
approaching_emergency_vehicle_plugin::anonymous_namespace{approaching_emergency_vehicle_plugin_node.cpp} Namespace Reference
Functions
double getManeuverEndSpeed (const carma_planning_msgs::msg::Maneuver &mvr)
Anonymous function to extract maneuver end speed which cannot be obtained with GET_MANEUVER_PROPERY calls due to it missing in stop and wait plugin.
Function Documentation
getManeuverEndSpeed()
double approaching_emergency_vehicle_plugin::anonymous_namespace{approaching_emergency_vehicle_plugin_node.cpp}::getManeuverEndSpeed (const carma_planning_msgs::msg::Maneuver & mvr)
Anonymous function to extract maneuver end speed which cannot be obtained with GET_MANEUVER_PROPERY calls due to it missing in stop and wait plugin.
Definition at line 27 of file approaching_emergency_vehicle_plugin_node.cpp.
{
      switch(mvr.type) {
        case carma_planning_msgs::msg::Maneuver::LANE_FOLLOWING:
          return mvr.lane_following_maneuver.end_speed;
        case carma_planning_msgs::msg::Maneuver::LANE_CHANGE:
          return mvr.lane_change_maneuver.end_speed;
        case carma_planning_msgs::msg::Maneuver::STOP_AND_WAIT:
          return 0;
        default:
          return 0;
      }
    }
Referenced by approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin::generateApproachingErvStatusMessage(), approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin::generateMoveOverManeuverPlan(), approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin::generateReducedSpeedLaneFollowingeManeuverPlan(), and approaching_emergency_vehicle_plugin::ApproachingEmergencyVehiclePlugin::getManeuverDuration().