Carma-platform: cost_utils Namespace Reference
cost_utils Namespace Reference
Functions
ros::Time get_plan_start_time (const cav_msgs::ManeuverPlan &)
Get the start time of the first maneuver in the plan.
double get_plan_start_distance (const cav_msgs::ManeuverPlan &)
Get the start distance of the first maneuver in the plan.
ros::Time get_plan_end_time (const cav_msgs::ManeuverPlan &)
Get the end time of the first maneuver in the plan.
double get_plan_end_distance (const cav_msgs::ManeuverPlan &)
Get the end distance of the first maneuver in the plan.
ros::Time get_maneuver_start_time (const cav_msgs::Maneuver &)
Get the start time of the specified maneuver.
double get_maneuver_start_distance (const cav_msgs::Maneuver &)
Get the start distance the specified maneuver.
ros::Time get_maneuver_end_time (const cav_msgs::Maneuver &)
Get the end time of the specified maneuver.
double get_maneuver_end_distance (const cav_msgs::Maneuver &)
Get the end distance of the specified maneuver.
double get_maneuver_start_speed (const cav_msgs::Maneuver &)
Get the start speed of the specified maneuver.
double get_maneuver_end_speed (const cav_msgs::Maneuver &)
Get the end speed of the specified maneuver.
std::string get_maneuver_starting_lane_id (const cav_msgs::Maneuver &)
Get the starting lane of the specified maneuver.
std::string get_maneuver_ending_lane_id (const cav_msgs::Maneuver &)
Get the ending lane of the specified maneuver.
Function Documentation
get_maneuver_end_distance()
double cost_utils::get_maneuver_end_distance (const cav_msgs::Maneuver & mvr)
Get the end distance of the specified maneuver.
Parameters
mvr The maneuver to examine
Returns
The double-valued linear downtrack distance in meters to the end of the maneuver
Exceptions
An invalid argument exception if the maneuver is poorly constructed
Definition at line 78 of file cost_utils.cpp.
{
    return GET_MANEUVER_PROPERTY(mvr, end_dist);
}
References GET_MANEUVER_PROPERTY.
Referenced by get_plan_end_distance().
get_maneuver_end_speed()
double cost_utils::get_maneuver_end_speed (const cav_msgs::Maneuver & mvr)
Get the end speed of the specified maneuver.
Parameters
mvr The maneuver to examine
Returns
The double-valued speed in meter/second to the end of the maneuver
Exceptions
An invalid argument exception if the maneuver is poorly constructed
Definition at line 93 of file cost_utils.cpp.
{
    if(mvr.type == cav_msgs::Maneuver::LANE_FOLLOWING){
        return mvr.lane_following_maneuver.end_speed;
    }else if(mvr.type == cav_msgs::Maneuver::INTERSECTION_TRANSIT_LEFT_TURN){
        return mvr.intersection_transit_left_turn_maneuver.end_speed;
    }else if(mvr.type == cav_msgs::Maneuver::INTERSECTION_TRANSIT_RIGHT_TURN){
        return mvr.intersection_transit_right_turn_maneuver.end_speed;
    }else if(mvr.type == cav_msgs::Maneuver::INTERSECTION_TRANSIT_STRAIGHT){
        return mvr.intersection_transit_straight_maneuver.end_speed;
    }else if(mvr.type == cav_msgs::Maneuver::STOP_AND_WAIT){
        return 0.0;
    }
    throw std::invalid_argument("Trying to get end_speed of maneuver with invalid type.");
}
Referenced by cost_plugin_system::CostofComfort::compute_cost(), cost_plugin_system::CostofEfficiency::compute_cost(), cost_plugin_system::CostofFeasibility::compute_cost(), cost_plugin_system::CostofFuel::compute_cost(), and cost_plugin_system::CostofSafety::compute_cost().
get_maneuver_end_time()
ros::Time cost_utils::get_maneuver_end_time (const cav_msgs::Maneuver & mvr)
Get the end time of the specified maneuver.
Parameters
mvr The maneuver to examine
Returns
The ros::Time at which it ends
Exceptions
An invalid argument exception if the maneuver is poorly constructed
Definition at line 68 of file cost_utils.cpp.
{
    return GET_MANEUVER_PROPERTY(mvr, end_time);
}
References GET_MANEUVER_PROPERTY.
Referenced by cost_plugin_system::CostofComfort::compute_cost(), cost_plugin_system::CostofFeasibility::compute_cost(), cost_plugin_system::CostofFuel::compute_cost(), and get_plan_end_time().
get_maneuver_ending_lane_id()
std::string cost_utils::get_maneuver_ending_lane_id (const cav_msgs::Maneuver & mvr)
Get the ending lane of the specified maneuver.
Parameters
mvr The maneuver to examine
Returns
The string-valued ending lane id of the maneuver
Exceptions
An invalid argument exception if the maneuver is poorly constructed
Definition at line 131 of file cost_utils.cpp.
{
    if (mvr.type == cav_msgs::Maneuver::LANE_FOLLOWING){
        if (mvr.lane_following_maneuver.lane_ids.size() < 2) {
            throw std::invalid_argument("Lane following maneuver does not have ending lane");
        }
        return mvr.lane_following_maneuver.lane_ids[1];
    } else if (mvr.type == cav_msgs::Maneuver::INTERSECTION_TRANSIT_LEFT_TURN) {
        return mvr.intersection_transit_left_turn_maneuver.ending_lane_id;
    } else if (mvr.type == cav_msgs::Maneuver::INTERSECTION_TRANSIT_RIGHT_TURN) {
        return mvr.intersection_transit_right_turn_maneuver.ending_lane_id;
    } else if (mvr.type == cav_msgs::Maneuver::INTERSECTION_TRANSIT_STRAIGHT) {
        return mvr.intersection_transit_straight_maneuver.ending_lane_id;
    } else if (mvr.type == cav_msgs::Maneuver::LANE_CHANGE) {
        return mvr.lane_change_maneuver.ending_lane_id;
    } else if(mvr.type == cav_msgs::Maneuver::STOP_AND_WAIT){
        return mvr.stop_and_wait_maneuver.ending_lane_id;
    }
    throw std::invalid_argument("Trying to get ending_lane_id of maneuver with invalid type.");
}
Referenced by cost_plugin_system::CostofComfort::compute_cost().
get_maneuver_start_distance()
double cost_utils::get_maneuver_start_distance (const cav_msgs::Maneuver & mvr)
Get the start distance the specified maneuver.
Parameters
mvr The maneuver to examine
Returns
The double-valued linear downtrack distance in meters to the start of the maneuver
Exceptions
An invalid argument exception if the maneuver is poorly constructed
Definition at line 83 of file cost_utils.cpp.
{
    return GET_MANEUVER_PROPERTY(mvr, start_dist);
}
References GET_MANEUVER_PROPERTY.
Referenced by get_plan_start_distance().
get_maneuver_start_speed()
double cost_utils::get_maneuver_start_speed (const cav_msgs::Maneuver & mvr)
Get the start speed of the specified maneuver.
Parameters
mvr The maneuver to examine
Returns
The double-valued speed in meter/second to the start of the maneuver
Exceptions
An invalid argument exception if the maneuver is poorly constructed
Definition at line 88 of file cost_utils.cpp.
{
    return GET_MANEUVER_PROPERTY(mvr, start_speed);
}
References GET_MANEUVER_PROPERTY.
Referenced by cost_plugin_system::CostofComfort::compute_cost(), cost_plugin_system::CostofEfficiency::compute_cost(), cost_plugin_system::CostofFeasibility::compute_cost(), cost_plugin_system::CostofFuel::compute_cost(), and cost_plugin_system::CostofSafety::compute_cost().
get_maneuver_start_time()
ros::Time cost_utils::get_maneuver_start_time (const cav_msgs::Maneuver & mvr)
Get the start time of the specified maneuver.
Parameters
mvr The maneuver to examine
Returns
The ros::Time at which it starts
Exceptions
An invalid argument exception if the maneuver is poorly constructed
Definition at line 73 of file cost_utils.cpp.
{
    return GET_MANEUVER_PROPERTY(mvr, start_time);
}
References GET_MANEUVER_PROPERTY.
Referenced by cost_plugin_system::CostofComfort::compute_cost(), cost_plugin_system::CostofFeasibility::compute_cost(), cost_plugin_system::CostofFuel::compute_cost(), and get_plan_start_time().
get_maneuver_starting_lane_id()
std::string cost_utils::get_maneuver_starting_lane_id (const cav_msgs::Maneuver & mvr)
Get the starting lane of the specified maneuver.
Parameters
mvr The maneuver to examine
Returns
The string-valued starting lane id of the maneuver
Exceptions
An invalid argument exception if the maneuver is poorly constructed
Definition at line 109 of file cost_utils.cpp.
{
    if (mvr.type == cav_msgs::Maneuver::LANE_FOLLOWING){
        if (mvr.lane_following_maneuver.lane_ids.empty()) {
            throw std::invalid_argument("Lane following maneuver has");
        }
        return mvr.lane_following_maneuver.lane_ids[0];
    } else if (mvr.type == cav_msgs::Maneuver::INTERSECTION_TRANSIT_LEFT_TURN) {
        return mvr.intersection_transit_left_turn_maneuver.starting_lane_id;
    } else if (mvr.type == cav_msgs::Maneuver::INTERSECTION_TRANSIT_RIGHT_TURN) {
        return mvr.intersection_transit_right_turn_maneuver.starting_lane_id;
    } else if (mvr.type == cav_msgs::Maneuver::INTERSECTION_TRANSIT_STRAIGHT) {
        return mvr.intersection_transit_straight_maneuver.starting_lane_id;
    } else if (mvr.type == cav_msgs::Maneuver::LANE_CHANGE) {
        return mvr.lane_change_maneuver.starting_lane_id;
    }else if (mvr.type == cav_msgs::Maneuver::STOP_AND_WAIT) {
        return mvr.stop_and_wait_maneuver.starting_lane_id;
    }
    throw std::invalid_argument("Trying to get starting_lane_id of maneuver with invalid type.");
}
Referenced by cost_plugin_system::CostofComfort::compute_cost().
get_plan_end_distance()
double cost_utils::get_plan_end_distance (const cav_msgs::ManeuverPlan & plan)
Get the end distance of the first maneuver in the plan.
Parameters
plan The plan to examine
Returns
The double-valued linear downtrack distance in meters to the end of the plan
Exceptions
An invalid argument exception if the plan is empty
Definition at line 35 of file cost_utils.cpp.
{
    if (plan.maneuvers.empty())
    {
        throw std::invalid_argument("cost_plugin_system::get_plan_end_dist called on empty maneuver plan");
    }
    cav_msgs::Maneuver m = plan.maneuvers.back();
    return get_maneuver_end_distance(m);
}
References get_maneuver_end_distance().
get_plan_end_time()
ros::Time cost_utils::get_plan_end_time (const cav_msgs::ManeuverPlan & plan)
Get the end time of the first maneuver in the plan.
Parameters
plan The plan to examine
Returns
The ros::Time at which it ends
Exceptions
An invalid argument exception if the plan is empty
Definition at line 23 of file cost_utils.cpp.
{
    if (plan.maneuvers.empty())
    {
        throw std::invalid_argument("cost_plugin_system::get_plan_end_time called on empty maneuver plan");
    }
    cav_msgs::Maneuver m = plan.maneuvers.back();
    return get_maneuver_end_time(m);
}
References get_maneuver_end_time().
get_plan_start_distance()
double cost_utils::get_plan_start_distance (const cav_msgs::ManeuverPlan & plan)
Get the start distance of the first maneuver in the plan.
Parameters
plan The plan to examine
Returns
The double-valued linear downtrack distance in meters to the start of the plan
Exceptions
An invalid argument exception if the plan is empty
Definition at line 57 of file cost_utils.cpp.
{
    if (plan.maneuvers.empty())
    {
        throw std::invalid_argument("cost_plugin_system::get_plan_start_dist called on empty maneuver plan");
    }
    cav_msgs::Maneuver m = plan.maneuvers.front();
    return get_maneuver_start_distance(m);
}
References get_maneuver_start_distance().
get_plan_start_time()
ros::Time cost_utils::get_plan_start_time (const cav_msgs::ManeuverPlan & plan)
Get the start time of the first maneuver in the plan.
Parameters
plan The plan to examine
Returns
The ros::Time at which it starts
Exceptions
An invalid argument exception if the plan is empty
Definition at line 46 of file cost_utils.cpp.
{
    if (plan.maneuvers.empty())
    {
        throw std::invalid_argument("cost_plugin_system::get_plan_start_time called on empty maneuver plan");
    }
    cav_msgs::Maneuver m = plan.maneuvers.front();
    return get_maneuver_start_time(m);
}
References get_maneuver_start_time().