Carma-platform: route_following_plugin::anonymous_namespace{route_following_plugin.cpp} Namespace Reference
route_following_plugin::anonymous_namespace{route_following_plugin.cpp} Namespace Reference
Functions
double getManeuverEndSpeed (const carma_planning_msgs::msg::Maneuver &mvr)
Anonymous function to extract maneuver end speed which can not be optained with GET_MANEUVER_PROPERY calls due to it missing in stop and wait plugin.
void setManeuverLaneletIds (carma_planning_msgs::msg::Maneuver &mvr, lanelet::Id start_id, lanelet::Id end_id)
Anonymous function to set the lanelet ids for all maneuver types except lane following.
Function Documentation
getManeuverEndSpeed()
double route_following_plugin::anonymous_namespace{route_following_plugin.cpp}::getManeuverEndSpeed (const carma_planning_msgs::msg::Maneuver & mvr)
Anonymous function to extract maneuver end speed which can not be optained with GET_MANEUVER_PROPERY calls due to it missing in stop and wait plugin.
Definition at line 36 of file route_following_plugin.cpp.
{
    switch(mvr.type) {
        case carma_planning_msgs::msg::Maneuver::LANE_FOLLOWING:
            return mvr.lane_following_maneuver.end_speed;
        case carma_planning_msgs::msg::Maneuver::LANE_CHANGE:
            return mvr.lane_change_maneuver.end_speed;
        case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_STRAIGHT:
            return mvr.intersection_transit_straight_maneuver.end_speed;
        case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_LEFT_TURN:
            return mvr.intersection_transit_left_turn_maneuver.end_speed;
        case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_RIGHT_TURN:
            return mvr.intersection_transit_right_turn_maneuver.end_speed;
        case carma_planning_msgs::msg::Maneuver::STOP_AND_WAIT:
            return 0;
        default:
            return 0;
    }
}
Referenced by route_following_plugin::RouteFollowingPlugin::getManeuverDuration(), route_following_plugin::RouteFollowingPlugin::maneuverWithBufferStartsAfterDowntrack(), and route_following_plugin::RouteFollowingPlugin::routeCb().
setManeuverLaneletIds()
void route_following_plugin::anonymous_namespace{route_following_plugin.cpp}::setManeuverLaneletIds (carma_planning_msgs::msg::Maneuver & mvr, lanelet::Id start_id, lanelet::Id end_id)
Anonymous function to set the lanelet ids for all maneuver types except lane following.
Definition at line 58 of file route_following_plugin.cpp.
{
    switch(mvr.type) {
        case carma_planning_msgs::msg::Maneuver::LANE_CHANGE:
            mvr.lane_change_maneuver.starting_lane_id = std::to_string(start_id);
            mvr.lane_change_maneuver.ending_lane_id = std::to_string(end_id);
            break;
        case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_STRAIGHT:
            mvr.intersection_transit_straight_maneuver.starting_lane_id = std::to_string(start_id);
            mvr.intersection_transit_straight_maneuver.ending_lane_id = std::to_string(end_id);
            break;
        case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_LEFT_TURN:
            mvr.intersection_transit_left_turn_maneuver.starting_lane_id = std::to_string(start_id);
            mvr.intersection_transit_left_turn_maneuver.ending_lane_id = std::to_string(end_id);
            break;
        case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_RIGHT_TURN:
            mvr.intersection_transit_right_turn_maneuver.starting_lane_id = std::to_string(start_id);
            mvr.intersection_transit_right_turn_maneuver.ending_lane_id = std::to_string(end_id);
            break;
        case carma_planning_msgs::msg::Maneuver::STOP_AND_WAIT:
            mvr.stop_and_wait_maneuver.starting_lane_id = std::to_string(start_id);
            mvr.stop_and_wait_maneuver.ending_lane_id = std::to_string(end_id);
            break;
        default:
            throw std::invalid_argument("Maneuver type does not have start,end lane ids");
    }
}
References carma_cooperative_perception::to_string().
Referenced by route_following_plugin::RouteFollowingPlugin::addStopAndWaitAtRouteEnd().