Carma-platform: RouteCreation_KML2CSV Namespace Reference
RouteCreation_KML2CSV Namespace Reference
Functions
def convertKMLToWaypoints (filename)
def main ()
Function Documentation
convertKMLToWaypoints()
def RouteCreation_KML2CSV.convertKMLToWaypoints (filename)
Convert the point data located in filename into a lane element
Definition at line 23 of file RouteCreation_KML2CSV.py.
def convertKMLToWaypoints(filename):
    """
    Convert the point data located in filename into a lane element
    """
    out = []
    xml = ET.parse(filename)
    root = xml.getroot()
    for coord in root.findall(".//{http://www.opengis.net/kml/2.2}coordinates"):
        (lon, lat, _) = coord.text.split(",")
        out.append((lat.strip(), lon.strip()))
    return out
Referenced by main().
main()
def RouteCreation_KML2CSV.main ()
Definition at line 38 of file RouteCreation_KML2CSV.py.
def main():
    parser = argparse.ArgumentParser("Convert a KML file into a CSV file, to further process with RouteCreation_CSV2Yaml.py")
    parser.add_argument("kml_input", help="KML input containing the desired route geometry")
    parser.add_argument("default_speed", help="The default speed limit along the route")
    parser.add_argument("csv_output", help="The file to write the CSV out to")
    args = parser.parse_args()
    print("Converting {} to CSV as {}".format(args.kml_input, args.csv_output))
    output = open(args.csv_output, "w")
    output.write("Latitude,Longitude,Speed\n")
    waypoints = convertKMLToWaypoints(args.kml_input)
    print("{} waypoints found. Using speed {} for all. Writing output...".format(len(waypoints), args.default_speed))
    count = 0
    for waypoint in waypoints:
        output.write("{},{},{}\n".format(waypoint[0], waypoint[1], args.default_speed))
        count += 1
    print("Wrote {} entries to {}.".format(count, args.csv_output))
References convertKMLToWaypoints(), and main().
Referenced by main().