Carma-platform: intersection_transit_maneuvering Namespace Reference
intersection_transit_maneuvering Namespace Reference
Classes
class IntersectionTransitManeuveringNode
ROS node for the inlanecruising_plugin.
class Servicer
Functions
std::ostream & operator<< (std::ostream &os, carma_planning_msgs::msg::ManeuverParameters m)
Stream operators for carma_planning_msgs::msg::Maneuver and nested messages. NOTE: Does not print meta data.
std::ostream & operator<< (std::ostream &os, carma_planning_msgs::msg::IntersectionTransitStraightManeuver m)
std::ostream & operator<< (std::ostream &os, carma_planning_msgs::msg::IntersectionTransitLeftTurnManeuver m)
std::ostream & operator<< (std::ostream &os, carma_planning_msgs::msg::IntersectionTransitRightTurnManeuver m)
std::ostream & operator<< (std::ostream &os, carma_planning_msgs::msg::LaneFollowingManeuver m)
std::ostream & operator<< (std::ostream &os, carma_planning_msgs::msg::Maneuver m)
Function Documentation
operator<<() [1/6]
std::ostream & intersection_transit_maneuvering::operator<< (std::ostream & os, carma_planning_msgs::msg::IntersectionTransitLeftTurnManeuver m)
Definition at line 65 of file intersection_transit_maneuvering.cpp.
{
    os << "parameters: { " << m.parameters << " }"
        << " start_dist: " << m.start_dist
        << " end_dist: " << m.end_dist
        << " start_speed: " << m.start_speed
        << " end_speed: " << m.end_speed
        << " start_time: " << std::to_string(rclcpp::Time(m.start_time).seconds())
        << " end_time: " << std::to_string(rclcpp::Time(m.end_time).seconds())
        << " starting_lane_id: " << m.starting_lane_id
        << " ending_lane_id: " << m.ending_lane_id;
    return os;
}
References carma_cooperative_perception::to_string().
operator<<() [2/6]
std::ostream & intersection_transit_maneuvering::operator<< (std::ostream & os, carma_planning_msgs::msg::IntersectionTransitRightTurnManeuver m)
Definition at line 78 of file intersection_transit_maneuvering.cpp.
{
    os << "parameters: { " << m.parameters << " }"
        << " start_dist: " << m.start_dist
        << " end_dist: " << m.end_dist
        << " start_speed: " << m.start_speed
        << " end_speed: " << m.end_speed
        << " start_time: " << std::to_string(rclcpp::Time(m.start_time).seconds())
        << " end_time: " << std::to_string(rclcpp::Time(m.end_time).seconds())
        << " starting_lane_id: " << m.starting_lane_id
        << " ending_lane_id: " << m.ending_lane_id;
    return os;
}
References carma_cooperative_perception::to_string().
operator<<() [3/6]
std::ostream & intersection_transit_maneuvering::operator<< (std::ostream & os, carma_planning_msgs::msg::IntersectionTransitStraightManeuver m)
Definition at line 52 of file intersection_transit_maneuvering.cpp.
{
    os << "parameters: { " << m.parameters << " }"
        << " start_dist: " << m.start_dist
        << " end_dist: " << m.end_dist
        << " start_speed: " << m.start_speed
        << " end_speed: " << m.end_speed
        << " start_time: " << std::to_string(rclcpp::Time(m.start_time).seconds())
        << " end_time: " << std::to_string(rclcpp::Time(m.end_time).seconds())
        << " starting_lane_id: " << m.starting_lane_id
        << " ending_lane_id: " << m.ending_lane_id;
    return os;
}
References carma_cooperative_perception::to_string().
operator<<() [4/6]
std::ostream & intersection_transit_maneuvering::operator<< (std::ostream & os, carma_planning_msgs::msg::LaneFollowingManeuver m)
Definition at line 91 of file intersection_transit_maneuvering.cpp.
{
    os << "parameters: { " << m.parameters << " }"
        << " start_dist: " << m.start_dist
        << " end_dist: " << m.end_dist
        << " start_speed: " << m.start_speed
        << " end_speed: " << m.end_speed
        << " start_time: " << std::to_string(rclcpp::Time(m.start_time).seconds())
        << " end_time: " << std::to_string(rclcpp::Time(m.end_time).seconds())
        << " lane_ids: [ ";
        for (const auto& i : m.lane_ids)
            os << i << " ";
        os << "]";
    return os;
}
References process_bag::i, and carma_cooperative_perception::to_string().
operator<<() [5/6]
std::ostream & intersection_transit_maneuvering::operator<< (std::ostream & os, carma_planning_msgs::msg::Maneuver m)
Definition at line 110 of file intersection_transit_maneuvering.cpp.
{
    os << "Maneuver Type: " << unsigned(m.type);
    switch(m.type) {
        case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_STRAIGHT:
            os << m.intersection_transit_straight_maneuver;
            break;
        case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_LEFT_TURN:
            os << m.intersection_transit_left_turn_maneuver;
            break;
        case carma_planning_msgs::msg::Maneuver::INTERSECTION_TRANSIT_RIGHT_TURN:
            os << m.intersection_transit_right_turn_maneuver;
            break;
        case carma_planning_msgs::msg::Maneuver::LANE_FOLLOWING:
            os << m.lane_following_maneuver;
            break;
        default:
            os << " not yet supported for printing. ";
    }
    return os;
}
operator<<() [6/6]
std::ostream & intersection_transit_maneuvering::operator<< (std::ostream & os, carma_planning_msgs::msg::ManeuverParameters m)
Stream operators for carma_planning_msgs::msg::Maneuver and nested messages. NOTE: Does not print meta data.
Definition at line 43 of file intersection_transit_maneuvering.cpp.
{
    os << "maneuver_id: " << m.maneuver_id
        << " negotiation_type: " << unsigned(m.negotiation_type)
        << " planning_strategic_plugin: " << m.planning_strategic_plugin
        << " presence_vector: " << unsigned(m.presence_vector)
        << " planning_tactical_plugin: " << m.planning_tactical_plugin;
    return os;
}