Carma-platform: speedharm_auto_configure Namespace Reference
speedharm_auto_configure Namespace Reference
Functions
def log (msg)
def print_response (resp)
def get_active_experiment_url ()
def create_experiment (desc, loc)
def assign_experiment (veh_id, experiment_url)
def get_registered_veh_data ()
def create_algorithm (algo_name)
def assign_algorithm (veh_id, algo_url)
def main ()
Variables
string version_id = "v0.1"
string base_url = "http://35.153.64.44:8081"
string vehicles_url = "/rest/vehicles"
string experiments_url = "/rest/experiments"
string algorithms_url = "/rest/algorithms"
string default_algorithm = "gov.dot.fhwa.saxton.speedharm.executive.algorithms.ReduceSpeedAlgorithm"
int sleep_duration_millis = 1000
Function Documentation
assign_algorithm()
def speedharm_auto_configure.assign_algorithm (veh_id, algo_url)
Definition at line 85 of file speedharm_auto_configure.py.
def assign_algorithm(veh_id, algo_url):
    headers = { "Content-Type" : "application/json" }
    data = json.dumps({"id": int(veh_id)})
    r = requests.post(urlparse.urljoin(algo_url + "/vehicles", ""), data=data, headers=headers, verify=False)
    print_response(r)
References print_response().
Referenced by main().
assign_experiment()
def speedharm_auto_configure.assign_experiment (veh_id, experiment_url)
Definition at line 66 of file speedharm_auto_configure.py.
def assign_experiment(veh_id, experiment_url):
    headers = { "Content-Type" : "application/json" }
    data = json.dumps({"id": int(veh_id)})
    r = requests.post(urlparse.urljoin(experiment_url + "/vehicles", ""), data=data, headers=headers, verify=False)
Referenced by main().
create_algorithm()
def speedharm_auto_configure.create_algorithm (algo_name)
Definition at line 76 of file speedharm_auto_configure.py.
def create_algorithm(algo_name):
    full_url = urlparse.urljoin(base_url, algorithms_url)
    headers = { "Content-Type" : "application/json" }
    data = json.dumps({"className": algo_name})
    r = requests.post(full_url, data=data, headers=headers, verify=False)
    print_response(r)
    return r.headers["Location"]
References print_response().
Referenced by main().
create_experiment()
def speedharm_auto_configure.create_experiment (desc, loc)
Definition at line 59 of file speedharm_auto_configure.py.
def create_experiment(desc, loc):
    full_url = urlparse.urljoin(base_url, experiments_url)
    headers = { "Content-Type" : "application/json" }
    r = requests.post(full_url, data=json.dumps({"description": desc, "location": loc}), headers=headers, verify=False)
    print_response(r)
    return r.headers["Location"]
References print_response().
Referenced by main().
get_active_experiment_url()
def speedharm_auto_configure.get_active_experiment_url ()
Definition at line 51 of file speedharm_auto_configure.py.
def get_active_experiment_url():
    r = requests.get(urlparse.urljoin(base_url, experiments_url), verify=False).json()
    for exp in r:
        if exp["description"].find("AUTO-CONFIG") > -1:
            return urlparse.urljoin(base_url, experiments_url + "/" + exp["id"])
    return None
Referenced by main().
get_registered_veh_data()
def speedharm_auto_configure.get_registered_veh_data ()
Definition at line 71 of file speedharm_auto_configure.py.
def get_registered_veh_data():
    r = requests.get(urlparse.urljoin(base_url, vehicles_url), verify=False)
    print_response(r)
    return r.json()
References print_response().
Referenced by main().
log()
def speedharm_auto_configure.log (msg)
Definition at line 41 of file speedharm_auto_configure.py.
def log(msg):
    cur_datetime = datetime.utcnow()
    unix_ts = calendar.timegm(cur_datetime.utctimetuple())
    print("[" + str(unix_ts) + "] " + str(msg))
Referenced by main(), and print_response().
main()
def speedharm_auto_configure.main ()
Definition at line 91 of file speedharm_auto_configure.py.
def main():
    log("Speed Harmonization Auto Configurator " + version_id + ".")
    log("Connecting to " + base_url + "...")
    while True:
        for veh in get_registered_veh_data():
            if not "expId" in veh:
                # Vehicle isn't yet assigned to an experiment, assume it's also not assigned to an algorithm
                log("Detected new vehicle ID=" + str(veh["id"]) + " with no experiment, assigning to experiment.")
                active_experiment_url = get_active_experiment_url()
                if not active_experiment_url:
                    cur_datetime = datetime.utcnow()
                    unix_ts = calendar.timegm(cur_datetime.utctimetuple())
                    active_experiment_url = create_experiment("AUTO-CONFIG Experiment Generated @ " + str(unix_ts), "UNSPECIFIED")
                    log("Created new experiment at " + active_experiment_url)
                else:
                    log("Discovered active experiment at " + active_experiment_url)
                assign_experiment(veh["id"], active_experiment_url)
                log("Assigned vehicle ID=" + str(veh["id"]) + " to experiment " + active_experiment_url)
                # Vehicle isn't yet assigned to an algorithm
                log("Detected new vehicle ID=" + str(veh["id"]) + " with no algorithm, assigning to algorithm.")
                algo_url = create_algorithm(default_algorithm)
                log("Created new algorithm of type " + default_algorithm + " at " + algo_url)
                assign_algorithm(veh["id"], algo_url)
                log("Assigned vehicle ID=" + str(veh["id"]) + " to algorithm " + algo_url)
        log("Sleeping " + str(sleep_duration_millis) + "ms...")
        time.sleep(sleep_duration_millis / 1000.0)
References assign_algorithm(), assign_experiment(), create_algorithm(), create_experiment(), get_active_experiment_url(), get_registered_veh_data(), log(), and main().
Referenced by main().
print_response()
def speedharm_auto_configure.print_response (resp)
Definition at line 46 of file speedharm_auto_configure.py.
def print_response(resp):
    log(resp.status_code)
    log(resp.headers)
    log(resp.json())
References log().
Referenced by assign_algorithm(), create_algorithm(), create_experiment(), and get_registered_veh_data().
Variable Documentation
algorithms_url
string speedharm_auto_configure.algorithms_url = "/rest/algorithms"
Definition at line 37 of file speedharm_auto_configure.py.
base_url
string speedharm_auto_configure.base_url = "http://35.153.64.44:8081"
Definition at line 32 of file speedharm_auto_configure.py.
default_algorithm
string speedharm_auto_configure.default_algorithm = "gov.dot.fhwa.saxton.speedharm.executive.algorithms.ReduceSpeedAlgorithm"
Definition at line 38 of file speedharm_auto_configure.py.
experiments_url
string speedharm_auto_configure.experiments_url = "/rest/experiments"
Definition at line 36 of file speedharm_auto_configure.py.
sleep_duration_millis
int speedharm_auto_configure.sleep_duration_millis = 1000
Definition at line 39 of file speedharm_auto_configure.py.
vehicles_url
string speedharm_auto_configure.vehicles_url = "/rest/vehicles"
Definition at line 35 of file speedharm_auto_configure.py.
version_id
string speedharm_auto_configure.version_id = "v0.1"
Definition at line 31 of file speedharm_auto_configure.py.