Carma-platform: arbitrator_utils Namespace Reference
arbitrator_utils Namespace Reference
Functions
rclcpp::Time get_plan_start_time (const carma_planning_msgs::msg::ManeuverPlan &)
Get the start time of the first maneuver in the plan.
double get_plan_start_distance (const carma_planning_msgs::msg::ManeuverPlan &)
Get the start distance of the first maneuver in the plan.
rclcpp::Time get_plan_end_time (const carma_planning_msgs::msg::ManeuverPlan &)
Get the end time of the first maneuver in the plan.
double get_plan_end_distance (const carma_planning_msgs::msg::ManeuverPlan &)
Get the end distance of the first maneuver in the plan.
rclcpp::Time get_maneuver_start_time (const carma_planning_msgs::msg::Maneuver &)
Get the start time of the specified maneuver.
double get_maneuver_start_distance (const carma_planning_msgs::msg::Maneuver &)
Get the start distance the specified maneuver.
rclcpp::Time get_maneuver_end_time (const carma_planning_msgs::msg::Maneuver &)
Get the end time of the specified maneuver.
double get_maneuver_end_distance (const carma_planning_msgs::msg::Maneuver &)
Get the end distance of the specified maneuver.
Function Documentation
get_maneuver_end_distance()
double arbitrator_utils::get_maneuver_end_distance (const carma_planning_msgs::msg::Maneuver & mvr)
Get the end distance of the specified maneuver.
Parameters
mvr The maneuver to examine
Returns
The double-valued linear downtrack distance in meters to the end of the maneuver
Exceptions
An invalid argument exception if the maneuver is poorly constructed
Definition at line 79 of file arbitrator_utils.cpp.
    {
        return GET_MANEUVER_PROPERTY(mvr, end_dist);
    }
References GET_MANEUVER_PROPERTY.
Referenced by arbitrator::FixedPriorityCostFunction::compute_total_cost(), and get_plan_end_distance().
get_maneuver_end_time()
rclcpp::Time arbitrator_utils::get_maneuver_end_time (const carma_planning_msgs::msg::Maneuver & mvr)
Get the end time of the specified maneuver.
Parameters
mvr The maneuver to examine
Returns
The rclcpp::Time at which it ends
Exceptions
An invalid argument exception if the maneuver is poorly constructed
Definition at line 69 of file arbitrator_utils.cpp.
    {
        return GET_MANEUVER_PROPERTY(mvr, end_time);
    }
References GET_MANEUVER_PROPERTY.
Referenced by get_plan_end_time().
get_maneuver_start_distance()
double arbitrator_utils::get_maneuver_start_distance (const carma_planning_msgs::msg::Maneuver & mvr)
Get the start distance the specified maneuver.
Parameters
mvr The maneuver to examine
Returns
The double-valued linear downtrack distance in meters to the start of the maneuver
Exceptions
An invalid argument exception if the maneuver is poorly constructed
Definition at line 84 of file arbitrator_utils.cpp.
    {
        return GET_MANEUVER_PROPERTY(mvr, start_dist);
    }
References GET_MANEUVER_PROPERTY.
Referenced by arbitrator::FixedPriorityCostFunction::compute_total_cost(), and get_plan_start_distance().
get_maneuver_start_time()
rclcpp::Time arbitrator_utils::get_maneuver_start_time (const carma_planning_msgs::msg::Maneuver & mvr)
Get the start time of the specified maneuver.
Parameters
mvr The maneuver to examine
Returns
The rclcpp::Time at which it starts
Exceptions
An invalid argument exception if the maneuver is poorly constructed
Definition at line 74 of file arbitrator_utils.cpp.
    {
        return GET_MANEUVER_PROPERTY(mvr, start_time);
    }
References GET_MANEUVER_PROPERTY.
Referenced by get_plan_start_time().
get_plan_end_distance()
double arbitrator_utils::get_plan_end_distance (const carma_planning_msgs::msg::ManeuverPlan & plan)
Get the end distance of the first maneuver in the plan.
Parameters
plan The plan to examine
Returns
The double-valued linear downtrack distance in meters to the end of the plan
Exceptions
An invalid argument exception if the plan is empty
Definition at line 36 of file arbitrator_utils.cpp.
    {
        if (plan.maneuvers.empty())
        {
            throw std::invalid_argument("arbitrator::get_plan_end_dist called on empty maneuver plan");
        }
        carma_planning_msgs::msg::Maneuver m = plan.maneuvers.back();
        return get_maneuver_end_distance(m);
    }
References get_maneuver_end_distance().
Referenced by arbitrator::CostSystemCostFunction::compute_cost_per_unit_distance(), and arbitrator::FixedPriorityCostFunction::compute_cost_per_unit_distance().
get_plan_end_time()
rclcpp::Time arbitrator_utils::get_plan_end_time (const carma_planning_msgs::msg::ManeuverPlan & plan)
Get the end time of the first maneuver in the plan.
Parameters
plan The plan to examine
Returns
The rclcpp::Time at which it ends
Exceptions
An invalid argument exception if the plan is empty
Definition at line 24 of file arbitrator_utils.cpp.
    {
        if (plan.maneuvers.empty())
        {
            throw std::invalid_argument("arbitrator::get_plan_end_time called on empty maneuver plan");
        }
        carma_planning_msgs::msg::Maneuver m = plan.maneuvers.back();
        return get_maneuver_end_time(m);
    }
References get_maneuver_end_time().
Referenced by arbitrator::TreePlanner::generate_plan(), and arbitrator::Arbitrator::planning_state().
get_plan_start_distance()
double arbitrator_utils::get_plan_start_distance (const carma_planning_msgs::msg::ManeuverPlan & plan)
Get the start distance of the first maneuver in the plan.
Parameters
plan The plan to examine
Returns
The double-valued linear downtrack distance in meters to the start of the plan
Exceptions
An invalid argument exception if the plan is empty
Definition at line 58 of file arbitrator_utils.cpp.
    {
        if (plan.maneuvers.empty())
        {
            throw std::invalid_argument("arbitrator::get_plan_start_dist called on empty maneuver plan");
        }
        carma_planning_msgs::msg::Maneuver m = plan.maneuvers.front();
        return get_maneuver_start_distance(m);
    }
References get_maneuver_start_distance().
Referenced by arbitrator::CostSystemCostFunction::compute_cost_per_unit_distance(), and arbitrator::FixedPriorityCostFunction::compute_cost_per_unit_distance().
get_plan_start_time()
rclcpp::Time arbitrator_utils::get_plan_start_time (const carma_planning_msgs::msg::ManeuverPlan & plan)
Get the start time of the first maneuver in the plan.
Parameters
plan The plan to examine
Returns
The rclcpp::Time at which it starts
Exceptions
An invalid argument exception if the plan is empty
Definition at line 47 of file arbitrator_utils.cpp.
    {
        if (plan.maneuvers.empty())
        {
            throw std::invalid_argument("arbitrator::get_plan_start_time called on empty maneuver plan");
        }
        carma_planning_msgs::msg::Maneuver m = plan.maneuvers.front();
        return get_maneuver_start_time(m);
    }
References get_maneuver_start_time().
Referenced by arbitrator::TreePlanner::generate_plan(), and arbitrator::Arbitrator::planning_state().