Carma-platform: basic_autonomy::log Namespace Reference
basic_autonomy::log Namespace Reference
Functions
std::string basicPointToStream (lanelet::BasicPoint2d point)
Helper function to convert a lanelet::BasicPoint2d to a string.
std::string pointSpeedPairToStream (waypoint_generation::PointSpeedPair point)
Helper function to convert a PointSpeedPair to a string.
template<class T >
void printDebugPerLine (const std::vector< T > &values, std::function< std::string(T)> func)
Print a RCLCPP_DEBUG_STREAM for each value in values where the printed value is a string returned by func.
template<class T >
void printDebugPerLine (const std::vector< T > &values, std::string(*free_func)(T))
Print a RCLCPP_DEBUG_STREAM for each value in values where the printed value is a string returned by free_func.
void printDoublesPerLineWithPrefix (const std::string &prefix, const std::vector< double > &values)
Print a RCLCPP_DEBUG_STREAM for each value in values where the printed value is << prefix << value.
Function Documentation
basicPointToStream()
std::string basic_autonomy::log::basicPointToStream (lanelet::BasicPoint2d point)
Helper function to convert a lanelet::BasicPoint2d to a string.
Definition at line 26 of file log.cpp.
{
  std::ostringstream out;
  out << point.x() << ", " << point.y();
  return out.str();
}
References process_traj_logs::point.
Referenced by basic_autonomy::waypoint_generation::compose_lanefollow_trajectory_from_path(), and pointSpeedPairToStream().
pointSpeedPairToStream()
std::string basic_autonomy::log::pointSpeedPairToStream (waypoint_generation::PointSpeedPair point)
Helper function to convert a PointSpeedPair to a string.
Definition at line 35 of file log.cpp.
{
  std::ostringstream out;
  out << "Point: " << basicPointToStream(point.point) << " Speed: " << point.speed;
  return out.str();
}
References basicPointToStream(), and process_traj_logs::point.
Referenced by basic_autonomy::waypoint_generation::compose_lanefollow_trajectory_from_path().
printDebugPerLine() [1/2]
template<class T > void basic_autonomy::log::printDebugPerLine (const std::vector< T > & values, std::function< std::string(T)> func)
Print a RCLCPP_DEBUG_STREAM for each value in values where the printed value is a string returned by func.
Definition at line 40 of file log.hpp.
    {
        for (const auto& value : values)
        {
            RCLCPP_DEBUG_STREAM(rclcpp::get_logger(BASIC_AUTONOMY_LOGGER), func(value));
        }
    }
References basic_autonomy::BASIC_AUTONOMY_LOGGER, and value.
Referenced by basic_autonomy::waypoint_generation::compose_lanefollow_trajectory_from_path(), and printDebugPerLine().
printDebugPerLine() [2/2]
template<class T > void basic_autonomy::log::printDebugPerLine (const std::vector< T > & values, std::string(*)(T) free_func)
Print a RCLCPP_DEBUG_STREAM for each value in values where the printed value is a string returned by free_func.
Definition at line 52 of file log.hpp.
    {
        auto function = static_cast<std::function<std::string(T)>>(free_func);
        printDebugPerLine(values, function);
    }
References printDebugPerLine().
printDoublesPerLineWithPrefix()
void basic_autonomy::log::printDoublesPerLineWithPrefix (const std::string & prefix, const std::vector< double > & values)
Print a RCLCPP_DEBUG_STREAM for each value in values where the printed value is << prefix << value.
Print a ROS_DEBUG_STREAM for each value in values where the printed value is << prefix << value.
Definition at line 45 of file log.cpp.
{
  for (const auto& value : values)
  {
    RCLCPP_DEBUG_STREAM(rclcpp::get_logger(BASIC_AUTONOMY_LOGGER), prefix << value);
  }
}
References basic_autonomy::BASIC_AUTONOMY_LOGGER, and value.
Referenced by basic_autonomy::waypoint_generation::compose_lanefollow_trajectory_from_path(), and basic_autonomy::waypoint_generation::optimize_speed().