Carma-platform: RouteCreation_CSV2Yaml Namespace Reference
RouteCreation_CSV2Yaml Namespace Reference
Functions
def waypointAsYAMLString (lat, lon, speedLimit)
def convertCSVToRouteFile (csvPath, routeFilePath, routeName)
Function Documentation
convertCSVToRouteFile()
def RouteCreation_CSV2Yaml.convertCSVToRouteFile (csvPath, routeFilePath, routeName)
Definition at line 47 of file RouteCreation_CSV2Yaml.py.
def convertCSVToRouteFile(csvPath, routeFilePath, routeName):
    print('Converting csv file to route file...')
    with open(csvPath, 'rb') as csvfile: # Open csv file
        with open(routeFilePath, 'wb') as yamlfile: # Open yaml file
            waypoint_reader = csv.reader(csvfile, delimiter=',')
            # Write header
            yamlfile.write('!gov.dot.fhwa.saxton.carma.route.Route' + '\n')
            yamlfile.write('routeName: ' + routeName + '\n')
            yamlfile.write('maxJoinDistance: ' + '40.0' + '\n')
            yamlfile.write('waypoints:\n')
            latIndex = 2
            lonIndex = 3
            speedLimitIndex = 4
            firstLine = True
            for row in waypoint_reader:
                if (firstLine): # Find needed column index and skip header row
                    index = 0
                    for col_name in row:
                        if (col_name == 'Latitude'):
                            latIndex = index
                        elif (col_name == 'Longitude'):
                            lonIndex = index
                        elif (col_name == 'Speed'):
                            speedLimitIndex = index
                        index += 1
                    firstLine = False
                    continue
                lat = float(row[latIndex])
                lon = float(row[lonIndex])
                speedLimit = int(row[speedLimitIndex])
                # Write waypoint to file
                yamlfile.write(waypointAsYAMLString(lat,lon,speedLimit))
    print('Done converting csv file to route file')
# Main execution
References convertCSVToRouteFile(), and waypointAsYAMLString().
Referenced by convertCSVToRouteFile().
waypointAsYAMLString()
def RouteCreation_CSV2Yaml.waypointAsYAMLString (lat, lon, speedLimit)
Definition at line 28 of file RouteCreation_CSV2Yaml.py.
def waypointAsYAMLString(lat, lon, speedLimit):
  return (
    '  - !gov.dot.fhwa.saxton.carma.route.RouteWaypoint\n'
    '    location: !gov.dot.fhwa.saxton.carma.geometry.geodesic.Location\n'
      '      latitude: ' + str(lat) + '\n'
      '      longitude: ' + str(lon) + '\n'
      '      altitude: 0.0\n'
    '    minCrossTrack: -10.0\n'
    '    maxCrossTrack: 10.0\n'
    '    lowerSpeedLimit: 0\n'
    '    upperSpeedLimit: ' + str(speedLimit) + '\n'
    '    laneCount: 1\n'
    '    interiorLaneMarkings: SOLID_WHITE\n'
    '    leftMostLaneMarking: SOLID_YELLOW\n'
    '    rightMostLaneMarking: SOLID_WHITE\n'
    '\n'
    )
# Main function which converts the provided csv file to the specified route file
Referenced by convertCSVToRouteFile().