Carma-platform: lanelet::MapConformer Namespace Reference
lanelet::MapConformer Namespace Reference
Namespaces
namespace anonymous_namespace{MapConformer.cpp}
Functions
void ensureCompliance (lanelet::LaneletMapPtr map, lanelet::Velocity config_limit=80_mph)
Function modifies an existing map to make a best effort attempt at ensuring the map confroms to the expectations of CarmaUSTrafficRules.
Detailed Description
The map conformer API is responsible for ensuring that a loaded lanelet2 map meets the expectations of CarmaUsTrafficRules Rather than simply validating the map this class will actually modify the map when possible to ensure compliance. NOTE: This class is not meant to be used by carma_wm users at runtime. It is only used in WMTestLibraryForGuidance currently to support unit testing.
The map conformer is responsible for ensuring that a loaded lanelet2 map meets the expectations of CarmaUsTrafficRules Rather than simply validating the map this class will actually modify the map when possible to ensure compliance. NOTE: This class is not meant to be used by carma_wm users at runtime. It is only used in WMTestLibraryForGuidance currently to support unit testing.
Function Documentation
ensureCompliance()
void lanelet::MapConformer::ensureCompliance (lanelet::LaneletMapPtr map, lanelet::Velocity config_limit = 80_mph)
Function modifies an existing map to make a best effort attempt at ensuring the map confroms to the expectations of CarmaUSTrafficRules.
Map is updated by ensuring all lanelet and area bounds are marked with PassingControlLines In addition, lanelets and areas are updated to have their accessability marked with a RegionAccessRule. At the moment the creation of DigitalSpeedLimits for all lanelets/areas is not performed. This is because CarmaUSTrafficRules supports the existing SpeedLimit definition and allows DigitalSpeedLimits to be overlayed on that.
Parameters
map A pointer to the map which will be modified in place
config_limit A value corresponding to the configurable speed limit value
Definition at line 550 of file MapConformer.cpp.
{
  auto default_traffic_rules = getAllGermanTrafficRules();  // Use german traffic rules as default as they most closely
                                                            // match the generic traffic rules
  // Handle lanelets
  for (auto lanelet : map->laneletLayer)
  {
    addInferredAccessRule(lanelet, map, default_traffic_rules);
    addInferredPassingControlLine(lanelet, map);
    addInferredDirectionOfTravel(lanelet, map, default_traffic_rules);
    addValidSpeedLimit(lanelet, map, config_limit, default_traffic_rules);// 0_mph can be changed with the config_limit
  }
  // Handle areas
  for (auto area : map->areaLayer)
  {
    addInferredAccessRule(area, map, default_traffic_rules);
    addInferredPassingControlLine(area, map);
  }
}
References lanelet::MapConformer::anonymous_namespace{MapConformer.cpp}::addInferredAccessRule(), lanelet::MapConformer::anonymous_namespace{MapConformer.cpp}::addInferredDirectionOfTravel(), lanelet::MapConformer::anonymous_namespace{MapConformer.cpp}::addInferredPassingControlLine(), lanelet::MapConformer::anonymous_namespace{MapConformer.cpp}::addValidSpeedLimit(), and lanelet::MapConformer::anonymous_namespace{MapConformer.cpp}::getAllGermanTrafficRules().
Referenced by carma_wm_ctrl::WMBroadcaster::baseMapCallback(), and carma_wm::test::buildGuidanceTestMap().