Carma-platform: basic_autonomy::smoothing Namespace Reference
basic_autonomy::smoothing Namespace Reference
Classes
class BSpline
Realization of SplineI that uses the Eigen::Splines library for interpolation.
class SplineI
Interface to a spline interpolator that can be used to smoothly interpolate between points.
Typedefs
typedef Eigen::Spline< double, 2 > Spline2d
Functions
std::vector< double > moving_average_filter (const std::vector< double > input, int window_size, bool ignore_first_point=true)
Extremely simplie moving average filter.
Typedef Documentation
Spline2d
typedef Eigen::Spline< double, 2 > basic_autonomy::smoothing::Spline2d
Definition at line 29 of file BSpline.h.
Function Documentation
moving_average_filter()
std::vector< double > basic_autonomy::smoothing::moving_average_filter (const std::vector< double > input, int window_size, bool ignore_first_point = true)
Extremely simplie moving average filter.
Parameters
input The points to be filtered
window_size The number of points to use in the moving window for averaging
Returns
The filterted points
Definition at line 24 of file filters.cpp.
{
  if (window_size % 2 == 0) {
    throw std::invalid_argument("moving_average_filter window size must be odd");
  }
  std::vector<double> output;
  output.reserve(input.size());
  if (input.size() == 0) {
    return output;
  }
  int start_index = 0;
  if (ignore_first_point) {
    start_index = 1;
    output.push_back(input[0]);
  }
  for (int i = start_index; i < static_cast<int>(input.size()); i++) {
    double total = 0;
    int sample_min = std::max(0, i - window_size / 2);
    int sample_max = std::min((int) input.size() - 1 , i + window_size / 2);
    int count = sample_max - sample_min + 1;
    std::vector<double> sample;
    sample.reserve(count);
    for (int j = sample_min; j <= sample_max; j++) {
      total += input[j];
    }
    output.push_back(total / (double) count);
  }
  return output;
}
References process_bag::i, and process_traj_logs::start_index.
Referenced by basic_autonomy::waypoint_generation::compose_lanechange_trajectory_from_path(), basic_autonomy::waypoint_generation::compose_lanefollow_trajectory_from_path(), stop_controlled_intersection_tactical_plugin::StopControlledIntersectionTacticalPlugin::compose_trajectory_from_centerline(), and stop_and_wait_plugin::StopandWait::compose_trajectory_from_centerline().