Carma-platform: inlanecruising_plugin::log Namespace Reference
inlanecruising_plugin::log Namespace Reference
Functions
std::string basicPointToStream (lanelet::BasicPoint2d point)
Helper function to convert a lanelet::BasicPoint2d to a string.
std::string pointSpeedPairToStream (PointSpeedPair point)
Helper function to convert a PointSpeedPair to a string.
template<class T >
void printDebugPerLine (const std::vector< T > &values, std::function< std::string(T)> func)
Print a RCLPP_DEBUG_STREAM for each value in values where the printed value is a string returned by func.
template<class T >
void printDebugPerLine (const std::vector< T > &values, std::string(*free_func)(T))
Print a RCLPP_DEBUG_STREAM for each value in values where the printed value is a string returned by free_func.
void printDoublesPerLineWithPrefix (const std::string &prefix, const std::vector< double > &values)
Print a RCLPP_DEBUG_STREAM for each value in values where the printed value is << prefix << value.
Function Documentation
basicPointToStream()
std::string inlanecruising_plugin::log::basicPointToStream (lanelet::BasicPoint2d point)
Helper function to convert a lanelet::BasicPoint2d to a string.
Definition at line 11 of file log.hpp.
{
  std::ostringstream out;
  out << point.x() << ", " << point.y();
  return out.str();
}
References process_traj_logs::point.
Referenced by pointSpeedPairToStream().
pointSpeedPairToStream()
std::string inlanecruising_plugin::log::pointSpeedPairToStream (PointSpeedPair point)
Helper function to convert a PointSpeedPair to a string.
Definition at line 20 of file log.hpp.
{
  std::ostringstream out;
  out << "Point: " << basicPointToStream(point.point) << " Speed: " << point.speed;
  return out.str();
}
References basicPointToStream(), and process_traj_logs::point.
printDebugPerLine() [1/2]
template<class T > void inlanecruising_plugin::log::printDebugPerLine (const std::vector< T > & values, std::function< std::string(T)> func)
Print a RCLPP_DEBUG_STREAM for each value in values where the printed value is a string returned by func.
Definition at line 31 of file log.hpp.
{
  for (const auto& value : values)
  {
    RCLCPP_DEBUG_STREAM(rclcpp::get_logger(ILC_LOGGER), func(value));
  }
}
References inlanecruising_plugin::ILC_LOGGER, and value.
Referenced by printDebugPerLine().
printDebugPerLine() [2/2]
template<class T > void inlanecruising_plugin::log::printDebugPerLine (const std::vector< T > & values, std::string(*)(T) free_func)
Print a RCLPP_DEBUG_STREAM for each value in values where the printed value is a string returned by free_func.
Definition at line 43 of file log.hpp.
{
  auto function = static_cast<std::function<std::string(T)>>(free_func);
  printDebugPerLine(values, function);
}
References printDebugPerLine().
printDoublesPerLineWithPrefix()
void inlanecruising_plugin::log::printDoublesPerLineWithPrefix (const std::string & prefix, const std::vector< double > & values)
Print a RCLPP_DEBUG_STREAM for each value in values where the printed value is << prefix << value.
Definition at line 52 of file log.hpp.
{
  for (const auto& value : values)
  {
    RCLCPP_DEBUG_STREAM(rclcpp::get_logger(ILC_LOGGER), prefix << value);
  }
}
References inlanecruising_plugin::ILC_LOGGER, and value.