var stop__and__dwell__strategic__plugin_8hpp =
[
    [ "stop_and_dwell_strategic_plugin::StopAndDwellStrategicPlugin", "classstop__and__dwell__strategic__plugin_1_1StopAndDwellStrategicPlugin.html", "classstop__and__dwell__strategic__plugin_1_1StopAndDwellStrategicPlugin" ],
    [ "stop_and_dwell_strategic_plugin::StopAndDwellStrategicPlugin::VehicleState", "structstop__and__dwell__strategic__plugin_1_1StopAndDwellStrategicPlugin_1_1VehicleState.html", "structstop__and__dwell__strategic__plugin_1_1StopAndDwellStrategicPlugin_1_1VehicleState" ]
];