Carma-platform: ns-3_adapter/thirdparty/rapidjson/include/rapidjson/stream.h File Reference
stream.h File Reference
#include "rapidjson.h"
#include "encodings.h"
Classes
struct StreamTraits< Stream >
Provides additional information for stream.
struct GenericStringStream< Encoding >
Read-only string stream.
struct StreamTraits< GenericStringStream< Encoding > >
struct GenericInsituStringStream< Encoding >
A read-write string stream.
struct StreamTraits< GenericInsituStringStream< Encoding > >
Typedefs
typedef GenericStringStream< UTF8<> > StringStream
String stream with UTF8 encoding.
typedef GenericInsituStringStream< UTF8<> > InsituStringStream
Insitu string stream with UTF8 encoding.
Functions
template<typename Stream >
void PutReserve (Stream &stream, size_t count)
Reserve n characters for writing to a stream.
template<typename Stream >
void PutUnsafe (Stream &stream, typename Stream::Ch c)
Write character to a stream, presuming buffer is reserved.
template<typename Stream , typename Ch >
void PutN (Stream &stream, Ch c, size_t n)
Put N copies of a character to a stream.
Typedef Documentation
InsituStringStream
typedef GenericInsituStringStream<UTF8<> > InsituStringStream
Insitu string stream with UTF8 encoding.
Definition at line 175 of file stream.h.
StringStream
typedef GenericStringStream<UTF8<> > StringStream
String stream with UTF8 encoding.
Definition at line 134 of file stream.h.
Function Documentation
PutN()
template<typename Stream , typename Ch > void PutN (Stream & stream, Ch c, size_t n) inline
Put N copies of a character to a stream.
Definition at line 97 of file stream.h.
{
    PutReserve(stream, n);
    for (size_t i = 0; i < n; i++)
        PutUnsafe(stream, c);
}
References process_traj_logs::c, process_bag::i, PutReserve(), and PutUnsafe().
PutReserve()
template<typename Stream > void PutReserve (Stream & stream, size_t count) inline
Reserve n characters for writing to a stream.
Definition at line 84 of file stream.h.
{
    (void)stream;
    (void)count;
}
Referenced by PutN(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteBool(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteDouble(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt64(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteNull(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteRawValue(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint64().
PutUnsafe()
template<typename Stream > void PutUnsafe (Stream & stream, typename Stream::Ch c) inline
Write character to a stream, presuming buffer is reserved.
Definition at line 91 of file stream.h.
{
    stream.Put(c);
}
References process_traj_logs::c.
Referenced by UTF8< CharType >::EncodeUnsafe(), UTF16< CharType >::EncodeUnsafe(), UTF32< CharType >::EncodeUnsafe(), ASCII< CharType >::EncodeUnsafe(), PutN(), Transcoder< Encoding, Encoding >::TranscodeUnsafe(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteBool(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteDouble(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt64(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteNull(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteRawValue(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint64().