Carma-platform: GenericInsituStringStream< Encoding > Struct Template Reference
GenericInsituStringStream< Encoding > Struct Template Reference
A read-write string stream.
#include <stream.h>
Public Types
typedef Encoding::Ch Ch
Public Member Functions
GenericInsituStringStream (Ch *src)
Ch Peek ()
Ch Take ()
size_t Tell ()
void Put (Ch c)
Ch * PutBegin ()
size_t PutEnd (Ch *begin)
void Flush ()
Ch * Push (size_t count)
void Pop (size_t count)
Public Attributes
Ch * src_
Ch * dst_
Ch * head_
Detailed Description
template<typename Encoding>
struct GenericInsituStringStream< Encoding >
A read-write string stream.
This string stream is particularly designed for in-situ parsing.
Note
implements Stream concept
Definition at line 144 of file stream.h.
Member Typedef Documentation
Ch
template<typename Encoding > typedef Encoding::Ch GenericInsituStringStream< Encoding >::Ch
Definition at line 145 of file stream.h.
Constructor & Destructor Documentation
GenericInsituStringStream()
template<typename Encoding > GenericInsituStringStream< Encoding >::GenericInsituStringStream (Ch * src) inline
Definition at line 147 of file stream.h.
: src_(src), dst_(0), head_(src) {}
Member Function Documentation
Flush()
template<typename Encoding > void GenericInsituStringStream< Encoding >::Flush () inline
Definition at line 159 of file stream.h.
{}
Peek()
template<typename Encoding > Ch GenericInsituStringStream< Encoding >::Peek () inline
Definition at line 150 of file stream.h.
{ return *src_; }
References GenericInsituStringStream< Encoding >::src_.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::Peek().
Pop()
template<typename Encoding > void GenericInsituStringStream< Encoding >::Pop (size_t count) inline
Definition at line 162 of file stream.h.
{ dst_ -= count; }
References GenericInsituStringStream< Encoding >::dst_.
Push()
template<typename Encoding > Ch * GenericInsituStringStream< Encoding >::Push (size_t count) inline
Definition at line 161 of file stream.h.
{ Ch* begin = dst_; dst_ += count; return begin; }
References GenericInsituStringStream< Encoding >::dst_.
Put()
template<typename Encoding > void GenericInsituStringStream< Encoding >::Put (Ch c) inline
Definition at line 155 of file stream.h.
{ RAPIDJSON_ASSERT(dst_ != 0); *dst_++ = c; }
References process_traj_logs::c, GenericInsituStringStream< Encoding >::dst_, and RAPIDJSON_ASSERT.
PutBegin()
template<typename Encoding > Ch * GenericInsituStringStream< Encoding >::PutBegin () inline
Definition at line 157 of file stream.h.
{ return dst_ = src_; }
References GenericInsituStringStream< Encoding >::dst_, and GenericInsituStringStream< Encoding >::src_.
Referenced by GenericPointer< ValueType, Allocator >::Parse().
PutEnd()
template<typename Encoding > size_t GenericInsituStringStream< Encoding >::PutEnd (Ch * begin) inline
Definition at line 158 of file stream.h.
{ return static_cast<size_t>(dst_ - begin); }
References GenericInsituStringStream< Encoding >::dst_.
Referenced by GenericPointer< ValueType, Allocator >::Parse().
Take()
template<typename Encoding > Ch GenericInsituStringStream< Encoding >::Take () inline
Definition at line 151 of file stream.h.
{ return *src_++; }
References GenericInsituStringStream< Encoding >::src_.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::Take(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::TakePush().
Tell()
template<typename Encoding > size_t GenericInsituStringStream< Encoding >::Tell () inline
Definition at line 152 of file stream.h.
{ return static_cast<size_t>(src_ - head_); }
References GenericInsituStringStream< Encoding >::head_, and GenericInsituStringStream< Encoding >::src_.
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false, false >::Tell().
Member Data Documentation
dst_
template<typename Encoding > Ch* GenericInsituStringStream< Encoding >::dst_
Definition at line 165 of file stream.h.
Referenced by GenericInsituStringStream< Encoding >::Pop(), GenericInsituStringStream< Encoding >::Push(), GenericInsituStringStream< Encoding >::Put(), GenericInsituStringStream< Encoding >::PutBegin(), and GenericInsituStringStream< Encoding >::PutEnd().
head_
template<typename Encoding > Ch* GenericInsituStringStream< Encoding >::head_
Definition at line 166 of file stream.h.
Referenced by GenericInsituStringStream< Encoding >::Tell().
src_
template<typename Encoding > Ch* GenericInsituStringStream< Encoding >::src_
Definition at line 164 of file stream.h.
Referenced by GenericInsituStringStream< Encoding >::Peek(), GenericInsituStringStream< Encoding >::PutBegin(), GenericInsituStringStream< Encoding >::Take(), and GenericInsituStringStream< Encoding >::Tell().
The documentation for this struct was generated from the following files:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/fwd.h
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/stream.h