Carma-platform: UTF8< CharType > Struct Template Reference
UTF8< CharType > Struct Template Reference
UTF-8 encoding.
#include <encodings.h>
Public Types
enum { supportUnicode = 1 }
typedef CharType Ch
Static Public Member Functions
template<typename OutputStream >
static void Encode (OutputStream &os, unsigned codepoint)
template<typename OutputStream >
static void EncodeUnsafe (OutputStream &os, unsigned codepoint)
template<typename InputStream >
static bool Decode (InputStream &is, unsigned *codepoint)
template<typename InputStream , typename OutputStream >
static bool Validate (InputStream &is, OutputStream &os)
static unsigned char GetRange (unsigned char c)
template<typename InputByteStream >
static CharType TakeBOM (InputByteStream &is)
template<typename InputByteStream >
static Ch Take (InputByteStream &is)
template<typename OutputByteStream >
static void PutBOM (OutputByteStream &os)
template<typename OutputByteStream >
static void Put (OutputByteStream &os, Ch c)
Detailed Description
template<typename CharType = char>
struct UTF8< CharType >
UTF-8 encoding.
http://en.wikipedia.org/wiki/UTF-8 http://tools.ietf.org/html/rfc3629
Template Parameters
CharType Code unit for storing 8-bit UTF-8 data. Default is char.
Note
implements Encoding concept
Definition at line 96 of file encodings.h.
Member Typedef Documentation
Ch
template<typename CharType = char> typedef CharType UTF8< CharType >::Ch
Definition at line 97 of file encodings.h.
Member Enumeration Documentation
anonymous enum
template<typename CharType = char> anonymous enum
Enumerator
supportUnicode
Definition at line 99 of file encodings.h.
{ supportUnicode = 1 };
Member Function Documentation
Decode()
template<typename CharType = char> template<typename InputStream > static bool UTF8< CharType >::Decode (InputStream & is, unsigned * codepoint) inline static
Definition at line 146 of file encodings.h.
{
#define COPY() c = is.Take(); *codepoint = (*codepoint << 6) | (static_cast<unsigned char>(c) & 0x3Fu)
#define TRANS(mask) result &= ((GetRange(static_cast<unsigned char>(c)) & mask) != 0)
#define TAIL() COPY(); TRANS(0x70)
        typename InputStream::Ch c = is.Take();
        if (!(c & 0x80)) {
            *codepoint = static_cast<unsigned char>(c);
            return true;
        }
        unsigned char type = GetRange(static_cast<unsigned char>(c));
        if (type >= 32) {
            *codepoint = 0;
        } else {
            *codepoint = (0xFFu >> type) & static_cast<unsigned char>(c);
        }
        bool result = true;
        switch (type) {
        case 2: TAIL(); return result;
        case 3: TAIL(); TAIL(); return result;
        case 4: COPY(); TRANS(0x50); TAIL(); return result;
        case 5: COPY(); TRANS(0x10); TAIL(); TAIL(); return result;
        case 6: TAIL(); TAIL(); TAIL(); return result;
        case 10: COPY(); TRANS(0x20); TAIL(); return result;
        case 11: COPY(); TRANS(0x60); TAIL(); TAIL(); return result;
        default: return false;
        }
#undef COPY
#undef TRANS
#undef TAIL
    }
References process_traj_logs::c, COPY, UTF8< CharType >::GetRange(), TAIL, and TRANS.
Encode()
template<typename CharType = char> template<typename OutputStream > static void UTF8< CharType >::Encode (OutputStream & os, unsigned codepoint) inline static
Definition at line 102 of file encodings.h.
{
        if (codepoint <= 0x7F)
            os.Put(static_cast<Ch>(codepoint & 0xFF));
        else if (codepoint <= 0x7FF) {
            os.Put(static_cast<Ch>(0xC0 | ((codepoint >> 6) & 0xFF)));
            os.Put(static_cast<Ch>(0x80 | ((codepoint & 0x3F))));
        }
        else if (codepoint <= 0xFFFF) {
            os.Put(static_cast<Ch>(0xE0 | ((codepoint >> 12) & 0xFF)));
            os.Put(static_cast<Ch>(0x80 | ((codepoint >> 6) & 0x3F)));
            os.Put(static_cast<Ch>(0x80 | (codepoint & 0x3F)));
        }
        else {
            RAPIDJSON_ASSERT(codepoint <= 0x10FFFF);
            os.Put(static_cast<Ch>(0xF0 | ((codepoint >> 18) & 0xFF)));
            os.Put(static_cast<Ch>(0x80 | ((codepoint >> 12) & 0x3F)));
            os.Put(static_cast<Ch>(0x80 | ((codepoint >> 6) & 0x3F)));
            os.Put(static_cast<Ch>(0x80 | (codepoint & 0x3F)));
        }
    }
References RAPIDJSON_ASSERT.
EncodeUnsafe()
template<typename CharType = char> template<typename OutputStream > static void UTF8< CharType >::EncodeUnsafe (OutputStream & os, unsigned codepoint) inline static
Definition at line 124 of file encodings.h.
{
        if (codepoint <= 0x7F)
            PutUnsafe(os, static_cast<Ch>(codepoint & 0xFF));
        else if (codepoint <= 0x7FF) {
            PutUnsafe(os, static_cast<Ch>(0xC0 | ((codepoint >> 6) & 0xFF)));
            PutUnsafe(os, static_cast<Ch>(0x80 | ((codepoint & 0x3F))));
        }
        else if (codepoint <= 0xFFFF) {
            PutUnsafe(os, static_cast<Ch>(0xE0 | ((codepoint >> 12) & 0xFF)));
            PutUnsafe(os, static_cast<Ch>(0x80 | ((codepoint >> 6) & 0x3F)));
            PutUnsafe(os, static_cast<Ch>(0x80 | (codepoint & 0x3F)));
        }
        else {
            RAPIDJSON_ASSERT(codepoint <= 0x10FFFF);
            PutUnsafe(os, static_cast<Ch>(0xF0 | ((codepoint >> 18) & 0xFF)));
            PutUnsafe(os, static_cast<Ch>(0x80 | ((codepoint >> 12) & 0x3F)));
            PutUnsafe(os, static_cast<Ch>(0x80 | ((codepoint >> 6) & 0x3F)));
            PutUnsafe(os, static_cast<Ch>(0x80 | (codepoint & 0x3F)));
        }
    }
References PutUnsafe(), and RAPIDJSON_ASSERT.
GetRange()
template<typename CharType = char> static unsigned char UTF8< CharType >::GetRange (unsigned char c) inline static
Definition at line 204 of file encodings.h.
{
        // Referring to DFA of http://bjoern.hoehrmann.de/utf-8/decoder/dfa/
        // With new mapping 1 -> 0x10, 7 -> 0x20, 9 -> 0x40, such that AND operation can test multiple types.
        static const unsigned char type[] = {
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
            0x10,0x10,0x10,0x10,0x10,0x10,0x10,0x10,0x10,0x10,0x10,0x10,0x10,0x10,0x10,0x10,
            0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,
            0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,
            0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,
            8,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,  2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
            10,3,3,3,3,3,3,3,3,3,3,3,3,4,3,3, 11,6,6,6,5,8,8,8,8,8,8,8,8,8,8,8,
        };
        return type[c];
    }
References process_traj_logs::c.
Referenced by UTF8< CharType >::Decode(), and UTF8< CharType >::Validate().
Put()
template<typename CharType = char> template<typename OutputByteStream > static void UTF8< CharType >::Put (OutputByteStream & os, Ch c) inline static
Definition at line 250 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename OutputByteStream::Ch) == 1);
        os.Put(static_cast<typename OutputByteStream::Ch>(c));
    }
References process_traj_logs::c, and RAPIDJSON_STATIC_ASSERT.
PutBOM()
template<typename CharType = char> template<typename OutputByteStream > static void UTF8< CharType >::PutBOM (OutputByteStream & os) inline static
Definition at line 242 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename OutputByteStream::Ch) == 1);
        os.Put(static_cast<typename OutputByteStream::Ch>(0xEFu));
        os.Put(static_cast<typename OutputByteStream::Ch>(0xBBu));
        os.Put(static_cast<typename OutputByteStream::Ch>(0xBFu));
    }
References RAPIDJSON_STATIC_ASSERT.
Take()
template<typename CharType = char> template<typename InputByteStream > static Ch UTF8< CharType >::Take (InputByteStream & is) inline static
Definition at line 236 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename InputByteStream::Ch) == 1);
        return static_cast<Ch>(is.Take());
    }
References RAPIDJSON_STATIC_ASSERT.
Referenced by UTF8< CharType >::TakeBOM().
TakeBOM()
template<typename CharType = char> template<typename InputByteStream > static CharType UTF8< CharType >::TakeBOM (InputByteStream & is) inline static
Definition at line 223 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename InputByteStream::Ch) == 1);
        typename InputByteStream::Ch c = Take(is);
        if (static_cast<unsigned char>(c) != 0xEFu) return c;
        c = is.Take();
        if (static_cast<unsigned char>(c) != 0xBBu) return c;
        c = is.Take();
        if (static_cast<unsigned char>(c) != 0xBFu) return c;
        c = is.Take();
        return c;
    }
References process_traj_logs::c, RAPIDJSON_STATIC_ASSERT, and UTF8< CharType >::Take().
Validate()
template<typename CharType = char> template<typename InputStream , typename OutputStream > static bool UTF8< CharType >::Validate (InputStream & is, OutputStream & os) inline static
Definition at line 179 of file encodings.h.
{
#define COPY() os.Put(c = is.Take())
#define TRANS(mask) result &= ((GetRange(static_cast<unsigned char>(c)) & mask) != 0)
#define TAIL() COPY(); TRANS(0x70)
        Ch c;
        COPY();
        if (!(c & 0x80))
            return true;
        bool result = true;
        switch (GetRange(static_cast<unsigned char>(c))) {
        case 2: TAIL(); return result;
        case 3: TAIL(); TAIL(); return result;
        case 4: COPY(); TRANS(0x50); TAIL(); return result;
        case 5: COPY(); TRANS(0x10); TAIL(); TAIL(); return result;
        case 6: TAIL(); TAIL(); TAIL(); return result;
        case 10: COPY(); TRANS(0x20); TAIL(); return result;
        case 11: COPY(); TRANS(0x60); TAIL(); TAIL(); return result;
        default: return false;
        }
#undef COPY
#undef TRANS
#undef TAIL
    }
References process_traj_logs::c, COPY, UTF8< CharType >::GetRange(), TAIL, and TRANS.
The documentation for this struct was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/encodings.h