Carma-platform: UTF32BE< CharType > Struct Template Reference
UTF32BE< CharType > Struct Template Reference
UTF-32 big endian encoding.
#include <encodings.h>
Static Public Member Functions
template<typename InputByteStream >
static CharType TakeBOM (InputByteStream &is)
template<typename InputByteStream >
static CharType Take (InputByteStream &is)
template<typename OutputByteStream >
static void PutBOM (OutputByteStream &os)
template<typename OutputByteStream >
static void Put (OutputByteStream &os, CharType c)
Static Public Member Functions inherited from UTF32< unsigned >
static void Encode (OutputStream &os, unsigned codepoint)
static void EncodeUnsafe (OutputStream &os, unsigned codepoint)
static bool Decode (InputStream &is, unsigned *codepoint)
static bool Validate (InputStream &is, OutputStream &os)
Additional Inherited Members
Public Types inherited from UTF32< unsigned >
enum
typedef unsigned Ch
Public Member Functions inherited from UTF32< unsigned >
RAPIDJSON_STATIC_ASSERT (sizeof(Ch) >=4)
Detailed Description
template<typename CharType = unsigned>
struct UTF32BE< CharType >
UTF-32 big endian encoding.
Definition at line 496 of file encodings.h.
Member Function Documentation
Put()
template<typename CharType = unsigned> template<typename OutputByteStream > static void UTF32BE< CharType >::Put (OutputByteStream & os, CharType c) inline static
Definition at line 524 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename OutputByteStream::Ch) == 1);
        os.Put(static_cast<typename OutputByteStream::Ch>((c >> 24) & 0xFFu));
        os.Put(static_cast<typename OutputByteStream::Ch>((c >> 16) & 0xFFu));
        os.Put(static_cast<typename OutputByteStream::Ch>((c >> 8) & 0xFFu));
        os.Put(static_cast<typename OutputByteStream::Ch>(c & 0xFFu));
    }
References process_traj_logs::c, and UTF32< unsigned >::RAPIDJSON_STATIC_ASSERT().
PutBOM()
template<typename CharType = unsigned> template<typename OutputByteStream > static void UTF32BE< CharType >::PutBOM (OutputByteStream & os) inline static
Definition at line 515 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename OutputByteStream::Ch) == 1);
        os.Put(static_cast<typename OutputByteStream::Ch>(0x00u));
        os.Put(static_cast<typename OutputByteStream::Ch>(0x00u));
        os.Put(static_cast<typename OutputByteStream::Ch>(0xFEu));
        os.Put(static_cast<typename OutputByteStream::Ch>(0xFFu));
    }
References UTF32< unsigned >::RAPIDJSON_STATIC_ASSERT().
Take()
template<typename CharType = unsigned> template<typename InputByteStream > static CharType UTF32BE< CharType >::Take (InputByteStream & is) inline static
Definition at line 505 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename InputByteStream::Ch) == 1);
        unsigned c = static_cast<unsigned>(static_cast<uint8_t>(is.Take())) << 24;
        c |= static_cast<unsigned>(static_cast<uint8_t>(is.Take())) << 16;
        c |= static_cast<unsigned>(static_cast<uint8_t>(is.Take())) << 8;
        c |= static_cast<unsigned>(static_cast<uint8_t>(is.Take()));
        return static_cast<CharType>(c);
    }
References process_traj_logs::c, and UTF32< unsigned >::RAPIDJSON_STATIC_ASSERT().
Referenced by UTF32BE< CharType >::TakeBOM().
TakeBOM()
template<typename CharType = unsigned> template<typename InputByteStream > static CharType UTF32BE< CharType >::TakeBOM (InputByteStream & is) inline static
Definition at line 498 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename InputByteStream::Ch) == 1);
        CharType c = Take(is);
        return static_cast<uint32_t>(c) == 0x0000FEFFu ? Take(is) : c;
    }
References process_traj_logs::c, UTF32< unsigned >::RAPIDJSON_STATIC_ASSERT(), and UTF32BE< CharType >::Take().
The documentation for this struct was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/encodings.h