Carma-platform: UTF16LE< CharType > Struct Template Reference
UTF16LE< CharType > Struct Template Reference
UTF-16 little endian encoding.
#include <encodings.h>
Static Public Member Functions
template<typename InputByteStream >
static CharType TakeBOM (InputByteStream &is)
template<typename InputByteStream >
static CharType Take (InputByteStream &is)
template<typename OutputByteStream >
static void PutBOM (OutputByteStream &os)
template<typename OutputByteStream >
static void Put (OutputByteStream &os, CharType c)
Static Public Member Functions inherited from UTF16< wchar_t >
static void Encode (OutputStream &os, unsigned codepoint)
static void EncodeUnsafe (OutputStream &os, unsigned codepoint)
static bool Decode (InputStream &is, unsigned *codepoint)
static bool Validate (InputStream &is, OutputStream &os)
Additional Inherited Members
Public Types inherited from UTF16< wchar_t >
enum
typedef wchar_t Ch
Public Member Functions inherited from UTF16< wchar_t >
RAPIDJSON_STATIC_ASSERT (sizeof(Ch) >=2)
Detailed Description
template<typename CharType = wchar_t>
struct UTF16LE< CharType >
UTF-16 little endian encoding.
Definition at line 342 of file encodings.h.
Member Function Documentation
Put()
template<typename CharType = wchar_t> template<typename OutputByteStream > static void UTF16LE< CharType >::Put (OutputByteStream & os, CharType c) inline static
Definition at line 366 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename OutputByteStream::Ch) == 1);
        os.Put(static_cast<typename OutputByteStream::Ch>(static_cast<unsigned>(c) & 0xFFu));
        os.Put(static_cast<typename OutputByteStream::Ch>((static_cast<unsigned>(c) >> 8) & 0xFFu));
    }
References process_traj_logs::c, and UTF16< wchar_t >::RAPIDJSON_STATIC_ASSERT().
PutBOM()
template<typename CharType = wchar_t> template<typename OutputByteStream > static void UTF16LE< CharType >::PutBOM (OutputByteStream & os) inline static
Definition at line 359 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename OutputByteStream::Ch) == 1);
        os.Put(static_cast<typename OutputByteStream::Ch>(0xFFu));
        os.Put(static_cast<typename OutputByteStream::Ch>(0xFEu));
    }
References UTF16< wchar_t >::RAPIDJSON_STATIC_ASSERT().
Take()
template<typename CharType = wchar_t> template<typename InputByteStream > static CharType UTF16LE< CharType >::Take (InputByteStream & is) inline static
Definition at line 351 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename InputByteStream::Ch) == 1);
        unsigned c = static_cast<uint8_t>(is.Take());
        c |= static_cast<unsigned>(static_cast<uint8_t>(is.Take())) << 8;
        return static_cast<CharType>(c);
    }
References process_traj_logs::c, and UTF16< wchar_t >::RAPIDJSON_STATIC_ASSERT().
Referenced by UTF16LE< CharType >::TakeBOM().
TakeBOM()
template<typename CharType = wchar_t> template<typename InputByteStream > static CharType UTF16LE< CharType >::TakeBOM (InputByteStream & is) inline static
Definition at line 344 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename InputByteStream::Ch) == 1);
        CharType c = Take(is);
        return static_cast<uint16_t>(c) == 0xFEFFu ? Take(is) : c;
    }
References process_traj_logs::c, UTF16< wchar_t >::RAPIDJSON_STATIC_ASSERT(), and UTF16LE< CharType >::Take().
The documentation for this struct was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/encodings.h