Carma-platform: UTF16< CharType > Struct Template Reference
UTF16< CharType > Struct Template Reference
UTF-16 encoding.
#include <encodings.h>
Public Types
enum { supportUnicode = 1 }
typedef CharType Ch
Public Member Functions
RAPIDJSON_STATIC_ASSERT (sizeof(Ch) >=2)
Static Public Member Functions
template<typename OutputStream >
static void Encode (OutputStream &os, unsigned codepoint)
template<typename OutputStream >
static void EncodeUnsafe (OutputStream &os, unsigned codepoint)
template<typename InputStream >
static bool Decode (InputStream &is, unsigned *codepoint)
template<typename InputStream , typename OutputStream >
static bool Validate (InputStream &is, OutputStream &os)
Detailed Description
template<typename CharType = wchar_t>
struct UTF16< CharType >
UTF-16 encoding.
http://en.wikipedia.org/wiki/UTF-16 http://tools.ietf.org/html/rfc2781
Template Parameters
CharType Type for storing 16-bit UTF-16 data. Default is wchar_t. C++11 may use char16_t instead.
Note
implements Encoding concept
For in-memory access, no need to concern endianness. The code units and code points are represented by CPU's endianness. For streaming, use UTF16LE and UTF16BE, which handle endianness.
Definition at line 269 of file encodings.h.
Member Typedef Documentation
Ch
template<typename CharType = wchar_t> typedef CharType UTF16< CharType >::Ch
Definition at line 270 of file encodings.h.
Member Enumeration Documentation
anonymous enum
template<typename CharType = wchar_t> anonymous enum
Enumerator
supportUnicode
Definition at line 273 of file encodings.h.
{ supportUnicode = 1 };
Member Function Documentation
Decode()
template<typename CharType = wchar_t> template<typename InputStream > static bool UTF16< CharType >::Decode (InputStream & is, unsigned * codepoint) inline static
Definition at line 307 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename InputStream::Ch) >= 2);
        typename InputStream::Ch c = is.Take();
        if (c < 0xD800 || c > 0xDFFF) {
            *codepoint = static_cast<unsigned>(c);
            return true;
        }
        else if (c <= 0xDBFF) {
            *codepoint = (static_cast<unsigned>(c) & 0x3FF) << 10;
            c = is.Take();
            *codepoint |= (static_cast<unsigned>(c) & 0x3FF);
            *codepoint += 0x10000;
            return c >= 0xDC00 && c <= 0xDFFF;
        }
        return false;
    }
References process_traj_logs::c, and UTF16< CharType >::RAPIDJSON_STATIC_ASSERT().
Encode()
template<typename CharType = wchar_t> template<typename OutputStream > static void UTF16< CharType >::Encode (OutputStream & os, unsigned codepoint) inline static
Definition at line 276 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename OutputStream::Ch) >= 2);
        if (codepoint <= 0xFFFF) {
            RAPIDJSON_ASSERT(codepoint < 0xD800 || codepoint > 0xDFFF); // Code point itself cannot be surrogate pair
            os.Put(static_cast<typename OutputStream::Ch>(codepoint));
        }
        else {
            RAPIDJSON_ASSERT(codepoint <= 0x10FFFF);
            unsigned v = codepoint - 0x10000;
            os.Put(static_cast<typename OutputStream::Ch>((v >> 10) | 0xD800));
            os.Put(static_cast<typename OutputStream::Ch>((v & 0x3FF) | 0xDC00));
        }
    }
References RAPIDJSON_ASSERT, and UTF16< CharType >::RAPIDJSON_STATIC_ASSERT().
EncodeUnsafe()
template<typename CharType = wchar_t> template<typename OutputStream > static void UTF16< CharType >::EncodeUnsafe (OutputStream & os, unsigned codepoint) inline static
Definition at line 292 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename OutputStream::Ch) >= 2);
        if (codepoint <= 0xFFFF) {
            RAPIDJSON_ASSERT(codepoint < 0xD800 || codepoint > 0xDFFF); // Code point itself cannot be surrogate pair
            PutUnsafe(os, static_cast<typename OutputStream::Ch>(codepoint));
        }
        else {
            RAPIDJSON_ASSERT(codepoint <= 0x10FFFF);
            unsigned v = codepoint - 0x10000;
            PutUnsafe(os, static_cast<typename OutputStream::Ch>((v >> 10) | 0xD800));
            PutUnsafe(os, static_cast<typename OutputStream::Ch>((v & 0x3FF) | 0xDC00));
        }
    }
References PutUnsafe(), RAPIDJSON_ASSERT, and UTF16< CharType >::RAPIDJSON_STATIC_ASSERT().
RAPIDJSON_STATIC_ASSERT()
template<typename CharType = wchar_t> UTF16< CharType >::RAPIDJSON_STATIC_ASSERT (sizeof(Ch) >= 2)
Referenced by UTF16< CharType >::Decode(), UTF16< CharType >::Encode(), UTF16< CharType >::EncodeUnsafe(), and UTF16< CharType >::Validate().
Validate()
template<typename CharType = wchar_t> template<typename InputStream , typename OutputStream > static bool UTF16< CharType >::Validate (InputStream & is, OutputStream & os) inline static
Definition at line 325 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename InputStream::Ch) >= 2);
        RAPIDJSON_STATIC_ASSERT(sizeof(typename OutputStream::Ch) >= 2);
        typename InputStream::Ch c;
        os.Put(static_cast<typename OutputStream::Ch>(c = is.Take()));
        if (c < 0xD800 || c > 0xDFFF)
            return true;
        else if (c <= 0xDBFF) {
            os.Put(c = is.Take());
            return c >= 0xDC00 && c <= 0xDFFF;
        }
        return false;
    }
References process_traj_logs::c, and UTF16< CharType >::RAPIDJSON_STATIC_ASSERT().
The documentation for this struct was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/encodings.h