Carma-platform: GenericStringStream< Encoding > Struct Template Reference
GenericStringStream< Encoding > Struct Template Reference
Read-only string stream.
#include <stream.h>
Public Types
typedef Encoding::Ch Ch
Public Member Functions
GenericStringStream (const Ch *src)
Ch Peek () const
Ch Take ()
size_t Tell () const
Ch * PutBegin ()
void Put (Ch)
void Flush ()
size_t PutEnd (Ch *)
Public Attributes
const Ch * src_
Current read position.
const Ch * head_
Original head of the string.
Detailed Description
template<typename Encoding>
struct GenericStringStream< Encoding >
Read-only string stream.
Note
implements Stream concept
Definition at line 110 of file stream.h.
Member Typedef Documentation
Ch
template<typename Encoding > typedef Encoding::Ch GenericStringStream< Encoding >::Ch
Definition at line 111 of file stream.h.
Constructor & Destructor Documentation
GenericStringStream()
template<typename Encoding > GenericStringStream< Encoding >::GenericStringStream (const Ch * src) inline
Definition at line 113 of file stream.h.
: src_(src), head_(src) {}
Member Function Documentation
Flush()
template<typename Encoding > void GenericStringStream< Encoding >::Flush () inline
Definition at line 121 of file stream.h.
{ RAPIDJSON_ASSERT(false); }
References RAPIDJSON_ASSERT.
Peek()
template<typename Encoding > Ch GenericStringStream< Encoding >::Peek () const inline
Definition at line 115 of file stream.h.
{ return *src_; }
References GenericStringStream< Encoding >::src_.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString().
Put()
template<typename Encoding > void GenericStringStream< Encoding >::Put (Ch) inline
Definition at line 120 of file stream.h.
{ RAPIDJSON_ASSERT(false); }
References RAPIDJSON_ASSERT.
PutBegin()
template<typename Encoding > Ch * GenericStringStream< Encoding >::PutBegin () inline
Definition at line 119 of file stream.h.
{ RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
PutEnd()
template<typename Encoding > size_t GenericStringStream< Encoding >::PutEnd (Ch *) inline
Definition at line 122 of file stream.h.
{ RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
Take()
template<typename Encoding > Ch GenericStringStream< Encoding >::Take () inline
Definition at line 116 of file stream.h.
{ return *src_++; }
References GenericStringStream< Encoding >::src_.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString().
Tell()
template<typename Encoding > size_t GenericStringStream< Encoding >::Tell () const inline
Definition at line 117 of file stream.h.
{ return static_cast<size_t>(src_ - head_); }
References GenericStringStream< Encoding >::head_, and GenericStringStream< Encoding >::src_.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::ScanWriteUnescapedString().
Member Data Documentation
head_
template<typename Encoding > const Ch* GenericStringStream< Encoding >::head_
Original head of the string.
Definition at line 125 of file stream.h.
Referenced by GenericStringStream< Encoding >::Tell().
src_
template<typename Encoding > const Ch* GenericStringStream< Encoding >::src_
Current read position.
Definition at line 124 of file stream.h.
Referenced by internal::CountStringCodePoint(), GenericStringStream< Encoding >::Peek(), GenericStringStream< Encoding >::Take(), and GenericStringStream< Encoding >::Tell().
The documentation for this struct was generated from the following files:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/fwd.h
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/stream.h