Carma-platform: UTF32< CharType > Struct Template Reference
UTF32< CharType > Struct Template Reference
UTF-32 encoding.
#include <encodings.h>
Public Types
enum { supportUnicode = 1 }
typedef CharType Ch
Public Member Functions
RAPIDJSON_STATIC_ASSERT (sizeof(Ch) >=4)
Static Public Member Functions
template<typename OutputStream >
static void Encode (OutputStream &os, unsigned codepoint)
template<typename OutputStream >
static void EncodeUnsafe (OutputStream &os, unsigned codepoint)
template<typename InputStream >
static bool Decode (InputStream &is, unsigned *codepoint)
template<typename InputStream , typename OutputStream >
static bool Validate (InputStream &is, OutputStream &os)
Detailed Description
template<typename CharType = unsigned>
struct UTF32< CharType >
UTF-32 encoding.
http://en.wikipedia.org/wiki/UTF-32
Template Parameters
CharType Type for storing 32-bit UTF-32 data. Default is unsigned. C++11 may use char32_t instead.
Note
implements Encoding concept
For in-memory access, no need to concern endianness. The code units and code points are represented by CPU's endianness. For streaming, use UTF32LE and UTF32BE, which handle endianness.
Definition at line 418 of file encodings.h.
Member Typedef Documentation
Ch
template<typename CharType = unsigned> typedef CharType UTF32< CharType >::Ch
Definition at line 419 of file encodings.h.
Member Enumeration Documentation
anonymous enum
template<typename CharType = unsigned> anonymous enum
Enumerator
supportUnicode
Definition at line 422 of file encodings.h.
{ supportUnicode = 1 };
Member Function Documentation
Decode()
template<typename CharType = unsigned> template<typename InputStream > static bool UTF32< CharType >::Decode (InputStream & is, unsigned * codepoint) inline static
Definition at line 439 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename InputStream::Ch) >= 4);
        Ch c = is.Take();
        *codepoint = c;
        return c <= 0x10FFFF;
    }
References process_traj_logs::c, and UTF32< CharType >::RAPIDJSON_STATIC_ASSERT().
Encode()
template<typename CharType = unsigned> template<typename OutputStream > static void UTF32< CharType >::Encode (OutputStream & os, unsigned codepoint) inline static
Definition at line 425 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename OutputStream::Ch) >= 4);
        RAPIDJSON_ASSERT(codepoint <= 0x10FFFF);
        os.Put(codepoint);
    }
References RAPIDJSON_ASSERT, and UTF32< CharType >::RAPIDJSON_STATIC_ASSERT().
EncodeUnsafe()
template<typename CharType = unsigned> template<typename OutputStream > static void UTF32< CharType >::EncodeUnsafe (OutputStream & os, unsigned codepoint) inline static
Definition at line 432 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename OutputStream::Ch) >= 4);
        RAPIDJSON_ASSERT(codepoint <= 0x10FFFF);
        PutUnsafe(os, codepoint);
    }
References PutUnsafe(), RAPIDJSON_ASSERT, and UTF32< CharType >::RAPIDJSON_STATIC_ASSERT().
RAPIDJSON_STATIC_ASSERT()
template<typename CharType = unsigned> UTF32< CharType >::RAPIDJSON_STATIC_ASSERT (sizeof(Ch) >= 4)
Referenced by UTF32< CharType >::Decode(), UTF32< CharType >::Encode(), UTF32< CharType >::EncodeUnsafe(), and UTF32< CharType >::Validate().
Validate()
template<typename CharType = unsigned> template<typename InputStream , typename OutputStream > static bool UTF32< CharType >::Validate (InputStream & is, OutputStream & os) inline static
Definition at line 447 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename InputStream::Ch) >= 4);
        Ch c;
        os.Put(c = is.Take());
        return c <= 0x10FFFF;
    }
References process_traj_logs::c, and UTF32< CharType >::RAPIDJSON_STATIC_ASSERT().
The documentation for this struct was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/encodings.h