Carma-platform: ParseResult Struct Reference
ParseResult Struct Reference
RapidJSON error handling
Result of parsing (wraps ParseErrorCode)
#include <error.h>
Public Types
typedef bool(ParseResult::* BooleanType) () const
! Unspecified boolean type
Public Member Functions
ParseResult ()
Default constructor, no error.
ParseResult (ParseErrorCode code, size_t offset)
Constructor to set an error.
ParseErrorCode Code () const
Get the error code.
size_t Offset () const
Get the error offset, if IsError(), 0 otherwise.
operator BooleanType () const
Explicit conversion to bool, returns true, iff !IsError().
bool IsError () const
Whether the result is an error.
bool operator== (const ParseResult &that) const
bool operator== (ParseErrorCode code) const
bool operator!= (const ParseResult &that) const
bool operator!= (ParseErrorCode code) const
void Clear ()
Reset error code.
void Set (ParseErrorCode code, size_t offset=0)
Update error code and offset.
Private Attributes
ParseErrorCode code_
size_t offset_
Friends
bool operator== (ParseErrorCode code, const ParseResult &err)
bool operator!= (ParseErrorCode code, const ParseResult &err)
Detailed Description
Result of parsing (wraps ParseErrorCode)
Document doc;
ParseResult ok = doc.Parse("[42]");
if (!ok) {
    fprintf(stderr, "JSON parse error: %s (%u)",
            GetParseError_En(ok.Code()), ok.Offset());
    exit(EXIT_FAILURE);
}
See also
GenericReader::Parse, GenericDocument::Parse
Definition at line 106 of file error.h.
Member Typedef Documentation
BooleanType
typedef bool(ParseResult::* ParseResult::BooleanType) () const
! Unspecified boolean type
Definition at line 108 of file error.h.
Constructor & Destructor Documentation
ParseResult() [1/2]
ParseResult::ParseResult () inline
Default constructor, no error.
Definition at line 111 of file error.h.
: code_(kParseErrorNone), offset_(0) {}
ParseResult() [2/2]
ParseResult::ParseResult (ParseErrorCode code, size_t offset) inline
Constructor to set an error.
Definition at line 113 of file error.h.
: code_(code), offset_(offset) {}
Member Function Documentation
Clear()
void ParseResult::Clear () inline
Reset error code.
Definition at line 134 of file error.h.
{ Set(kParseErrorNone); }
References kParseErrorNone, and Set().
Referenced by GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParse(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseInit(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse().
Code()
ParseErrorCode ParseResult::Code () const inline
Get the error code.
Definition at line 116 of file error.h.
{ return code_; }
References code_.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::GetParseError(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetParseErrorCode().
IsError()
bool ParseResult::IsError () const inline
Whether the result is an error.
Definition at line 123 of file error.h.
{ return code_ != kParseErrorNone; }
References code_, and kParseErrorNone.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::HasParseError(), GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HasParseError(), and operator BooleanType().
Offset()
size_t ParseResult::Offset () const inline
Get the error offset, if IsError(), 0 otherwise.
Definition at line 118 of file error.h.
{ return offset_; }
References offset_.
Referenced by GenericDocument< Encoding, Allocator, StackAllocator >::GetErrorOffset(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetErrorOffset().
operator BooleanType()
ParseResult::operator BooleanType () const inline
Explicit conversion to bool, returns true, iff !IsError().
Definition at line 121 of file error.h.
{ return !IsError() ? &ParseResult::IsError : NULL; }
References IsError().
operator!=() [1/2]
bool ParseResult::operator!= (const ParseResult & that) const inline
Definition at line 129 of file error.h.
{ return !(*this == that); }
operator!=() [2/2]
bool ParseResult::operator!= (ParseErrorCode code) const inline
Definition at line 130 of file error.h.
{ return !(*this == code); }
operator==() [1/2]
bool ParseResult::operator== (const ParseResult & that) const inline
Definition at line 125 of file error.h.
{ return code_ == that.code_; }
References code_.
operator==() [2/2]
bool ParseResult::operator== (ParseErrorCode code) const inline
Definition at line 126 of file error.h.
{ return code_ == code; }
References code_.
Set()
void ParseResult::Set (ParseErrorCode code, size_t offset = 0) inline
Update error code and offset.
Definition at line 136 of file error.h.
{ code_ = code; offset_ = offset; }
References code_, and offset_.
Referenced by Clear(), and GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::SetParseError().
Friends And Related Function Documentation
operator!=
bool operator!= (ParseErrorCode code, const ParseResult & err) friend
Definition at line 131 of file error.h.
{ return err != code; }
operator==
bool operator== (ParseErrorCode code, const ParseResult & err) friend
Definition at line 127 of file error.h.
{ return code == err.code_; }
Member Data Documentation
code_
ParseErrorCode ParseResult::code_ private
Definition at line 139 of file error.h.
Referenced by Code(), IsError(), operator==(), and Set().
offset_
size_t ParseResult::offset_ private
Definition at line 140 of file error.h.
Referenced by Offset(), and Set().
The documentation for this struct was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/error/error.h