Carma-platform: ASCII< CharType > Struct Template Reference
ASCII< CharType > Struct Template Reference
ASCII encoding.
#include <encodings.h>
Public Types
enum { supportUnicode = 0 }
typedef CharType Ch
Static Public Member Functions
template<typename OutputStream >
static void Encode (OutputStream &os, unsigned codepoint)
template<typename OutputStream >
static void EncodeUnsafe (OutputStream &os, unsigned codepoint)
template<typename InputStream >
static bool Decode (InputStream &is, unsigned *codepoint)
template<typename InputStream , typename OutputStream >
static bool Validate (InputStream &is, OutputStream &os)
template<typename InputByteStream >
static CharType TakeBOM (InputByteStream &is)
template<typename InputByteStream >
static Ch Take (InputByteStream &is)
template<typename OutputByteStream >
static void PutBOM (OutputByteStream &os)
template<typename OutputByteStream >
static void Put (OutputByteStream &os, Ch c)
Detailed Description
template<typename CharType = char>
struct ASCII< CharType >
ASCII encoding.
http://en.wikipedia.org/wiki/ASCII
Template Parameters
CharType Code unit for storing 7-bit ASCII data. Default is char.
Note
implements Encoding concept
Definition at line 542 of file encodings.h.
Member Typedef Documentation
Ch
template<typename CharType = char> typedef CharType ASCII< CharType >::Ch
Definition at line 543 of file encodings.h.
Member Enumeration Documentation
anonymous enum
template<typename CharType = char> anonymous enum
Enumerator
supportUnicode
Definition at line 545 of file encodings.h.
{ supportUnicode = 0 };
Member Function Documentation
Decode()
template<typename CharType = char> template<typename InputStream > static bool ASCII< CharType >::Decode (InputStream & is, unsigned * codepoint) inline static
Definition at line 560 of file encodings.h.
{
        uint8_t c = static_cast<uint8_t>(is.Take());
        *codepoint = c;
        return c <= 0X7F;
    }
References process_traj_logs::c.
Encode()
template<typename CharType = char> template<typename OutputStream > static void ASCII< CharType >::Encode (OutputStream & os, unsigned codepoint) inline static
Definition at line 548 of file encodings.h.
{
        RAPIDJSON_ASSERT(codepoint <= 0x7F);
        os.Put(static_cast<Ch>(codepoint & 0xFF));
    }
References RAPIDJSON_ASSERT.
EncodeUnsafe()
template<typename CharType = char> template<typename OutputStream > static void ASCII< CharType >::EncodeUnsafe (OutputStream & os, unsigned codepoint) inline static
Definition at line 554 of file encodings.h.
{
        RAPIDJSON_ASSERT(codepoint <= 0x7F);
        PutUnsafe(os, static_cast<Ch>(codepoint & 0xFF));
    }
References PutUnsafe(), and RAPIDJSON_ASSERT.
Put()
template<typename CharType = char> template<typename OutputByteStream > static void ASCII< CharType >::Put (OutputByteStream & os, Ch c) inline static
Definition at line 593 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename OutputByteStream::Ch) == 1);
        os.Put(static_cast<typename OutputByteStream::Ch>(c));
    }
References process_traj_logs::c, and RAPIDJSON_STATIC_ASSERT.
PutBOM()
template<typename CharType = char> template<typename OutputByteStream > static void ASCII< CharType >::PutBOM (OutputByteStream & os) inline static
Definition at line 587 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename OutputByteStream::Ch) == 1);
        (void)os;
    }
References RAPIDJSON_STATIC_ASSERT.
Take()
template<typename CharType = char> template<typename InputByteStream > static Ch ASCII< CharType >::Take (InputByteStream & is) inline static
Definition at line 581 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename InputByteStream::Ch) == 1);
        return static_cast<Ch>(is.Take());
    }
References RAPIDJSON_STATIC_ASSERT.
Referenced by ASCII< CharType >::TakeBOM().
TakeBOM()
template<typename CharType = char> template<typename InputByteStream > static CharType ASCII< CharType >::TakeBOM (InputByteStream & is) inline static
Definition at line 574 of file encodings.h.
{
        RAPIDJSON_STATIC_ASSERT(sizeof(typename InputByteStream::Ch) == 1);
        uint8_t c = static_cast<uint8_t>(Take(is));
        return static_cast<Ch>(c);
    }
References process_traj_logs::c, RAPIDJSON_STATIC_ASSERT, and ASCII< CharType >::Take().
Validate()
template<typename CharType = char> template<typename InputStream , typename OutputStream > static bool ASCII< CharType >::Validate (InputStream & is, OutputStream & os) inline static
Definition at line 567 of file encodings.h.
{
        uint8_t c = static_cast<uint8_t>(is.Take());
        os.Put(static_cast<typename OutputStream::Ch>(c));
        return c <= 0x7F;
    }
References process_traj_logs::c.
The documentation for this struct was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/encodings.h