Carma-platform: AutoUTF< CharType > Struct Template Reference
AutoUTF< CharType > Struct Template Reference
Dynamically select encoding according to stream's runtime-specified UTF encoding type.
#include <encodings.h>
Public Types
enum { supportUnicode = 1 }
typedef CharType Ch
Static Public Member Functions
template<typename OutputStream >
static RAPIDJSON_FORCEINLINE void Encode (OutputStream &os, unsigned codepoint)
template<typename OutputStream >
static RAPIDJSON_FORCEINLINE void EncodeUnsafe (OutputStream &os, unsigned codepoint)
template<typename InputStream >
static RAPIDJSON_FORCEINLINE bool Decode (InputStream &is, unsigned *codepoint)
template<typename InputStream , typename OutputStream >
static RAPIDJSON_FORCEINLINE bool Validate (InputStream &is, OutputStream &os)
Detailed Description
template<typename CharType>
struct AutoUTF< CharType >
Dynamically select encoding according to stream's runtime-specified UTF encoding type.
Note
This class can be used with AutoUTFInputtStream and AutoUTFOutputStream, which provides GetType().
Definition at line 615 of file encodings.h.
Member Typedef Documentation
Ch
template<typename CharType > typedef CharType AutoUTF< CharType >::Ch
Definition at line 616 of file encodings.h.
Member Enumeration Documentation
anonymous enum
template<typename CharType > anonymous enum
Enumerator
supportUnicode
Definition at line 618 of file encodings.h.
{ supportUnicode = 1 };
Member Function Documentation
Decode()
template<typename CharType > template<typename InputStream > static RAPIDJSON_FORCEINLINE bool AutoUTF< CharType >::Decode (InputStream & is, unsigned * codepoint) inline static
Definition at line 637 of file encodings.h.
{
        typedef bool (*DecodeFunc)(InputStream&, unsigned*);
        static const DecodeFunc f[] = { RAPIDJSON_ENCODINGS_FUNC(Decode) };
        return (*f[is.GetType()])(is, codepoint);
    }
References AutoUTF< CharType >::Decode(), and RAPIDJSON_ENCODINGS_FUNC.
Referenced by AutoUTF< CharType >::Decode().
Encode()
template<typename CharType > template<typename OutputStream > static RAPIDJSON_FORCEINLINE void AutoUTF< CharType >::Encode (OutputStream & os, unsigned codepoint) inline static
Definition at line 623 of file encodings.h.
{
        typedef void (*EncodeFunc)(OutputStream&, unsigned);
        static const EncodeFunc f[] = { RAPIDJSON_ENCODINGS_FUNC(Encode) };
        (*f[os.GetType()])(os, codepoint);
    }
References AutoUTF< CharType >::Encode(), and RAPIDJSON_ENCODINGS_FUNC.
Referenced by AutoUTF< CharType >::Encode().
EncodeUnsafe()
template<typename CharType > template<typename OutputStream > static RAPIDJSON_FORCEINLINE void AutoUTF< CharType >::EncodeUnsafe (OutputStream & os, unsigned codepoint) inline static
Definition at line 630 of file encodings.h.
{
        typedef void (*EncodeFunc)(OutputStream&, unsigned);
        static const EncodeFunc f[] = { RAPIDJSON_ENCODINGS_FUNC(EncodeUnsafe) };
        (*f[os.GetType()])(os, codepoint);
    }
References AutoUTF< CharType >::EncodeUnsafe(), and RAPIDJSON_ENCODINGS_FUNC.
Referenced by AutoUTF< CharType >::EncodeUnsafe().
Validate()
template<typename CharType > template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool AutoUTF< CharType >::Validate (InputStream & is, OutputStream & os) inline static
Definition at line 644 of file encodings.h.
{
        typedef bool (*ValidateFunc)(InputStream&, OutputStream&);
        static const ValidateFunc f[] = { RAPIDJSON_ENCODINGS_FUNC(Validate) };
        return (*f[is.GetType()])(is, os);
    }
References RAPIDJSON_ENCODINGS_FUNC, and AutoUTF< CharType >::Validate().
Referenced by AutoUTF< CharType >::Validate().
The documentation for this struct was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/encodings.h