Carma-platform: GenericValue< Encoding, Allocator >::ShortString Struct Reference
GenericValue< Encoding, Allocator >::ShortString Struct Reference
#include <document.h>
Public Types
enum { MaxChars = sizeof(static_cast<Flag*>(0)->payload) / sizeof(Ch) , MaxSize = MaxChars - 1 , LenPos = MaxSize }
Public Member Functions
void SetLength (SizeType len)
SizeType GetLength () const
Static Public Member Functions
static bool Usable (SizeType len)
Public Attributes
Ch str [MaxChars]
Detailed Description
template<typename Encoding, typename Allocator = MemoryPoolAllocator<>>
struct GenericValue< Encoding, Allocator >::ShortString
Definition at line 1933 of file document.h.
Member Enumeration Documentation
anonymous enum
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> anonymous enum
Enumerator
MaxChars
MaxSize
LenPos
Definition at line 1934 of file document.h.
{ MaxChars = sizeof(static_cast<Flag*>(0)->payload) / sizeof(Ch), MaxSize = MaxChars - 1, LenPos = MaxSize };
Member Function Documentation
GetLength()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> SizeType GenericValue< Encoding, Allocator >::ShortString::GetLength () const inline
Definition at line 1939 of file document.h.
{ return  static_cast<SizeType>(MaxSize -  str[LenPos]); }
References GenericValue< Encoding, Allocator >::ShortString::LenPos, GenericValue< Encoding, Allocator >::ShortString::MaxSize, SizeType, and GenericValue< Encoding, Allocator >::ShortString::str.
SetLength()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> void GenericValue< Encoding, Allocator >::ShortString::SetLength (SizeType len) inline
Definition at line 1938 of file document.h.
{ str[LenPos] = static_cast<Ch>(MaxSize -  len); }
References GenericValue< Encoding, Allocator >::ShortString::LenPos, GenericValue< Encoding, Allocator >::ShortString::MaxSize, and GenericValue< Encoding, Allocator >::ShortString::str.
Referenced by GenericValue< Encoding, Allocator >::GenericValue(), and GenericValue< Encoding, Allocator >::SetStringRaw().
Usable()
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> static bool GenericValue< Encoding, Allocator >::ShortString::Usable (SizeType len) inline static
Definition at line 1937 of file document.h.
{ return                       (MaxSize >= len); }
References GenericValue< Encoding, Allocator >::ShortString::MaxSize.
Referenced by GenericValue< Encoding, Allocator >::SetStringRaw().
Member Data Documentation
str
template<typename Encoding , typename Allocator = MemoryPoolAllocator<>> Ch GenericValue< Encoding, Allocator >::ShortString::str[MaxChars]
Definition at line 1935 of file document.h.
Referenced by GenericValue< Encoding, Allocator >::ShortString::GetLength(), GenericValue< Encoding, Allocator >::ShortString::SetLength(), and GenericValue< Encoding, Allocator >::SetStringRaw().
The documentation for this struct was generated from the following file:
ns-3_adapter/thirdparty/rapidjson/include/rapidjson/document.h