Carma-platform: cpp_message::Map_Message Class Reference
cpp_message::Map_Message Class Reference
#include <Map_Message.h>
Public Member Functions
Map_Message (rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging)
constructor
boost::optional< j2735_v2x_msgs::msg::MapData > decode_map_message (std::vector< uint8_t > &binary_array)
Construct a new map message object.
j2735_v2x_msgs::msg::GenericLane decode_generic_lane (GenericLane_t *g_lane)
Construct Generic lane j2735 ROS MAP.msg.
Public Attributes
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging_
Detailed Description
Definition at line 31 of file Map_Message.h.
Constructor & Destructor Documentation
Map_Message()
cpp_message::Map_Message::Map_Message (rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging) inline explicit
constructor
Definition at line 37 of file Map_Message.h.
        {
            node_logging_ = node_logging;
        };
References node_logging_.
Member Function Documentation
decode_generic_lane()
j2735_v2x_msgs::msg::GenericLane cpp_message::Map_Message::decode_generic_lane (GenericLane_t * g_lane)
Construct Generic lane j2735 ROS MAP.msg.
Parameters
g_lane Pointer that has decoded GenericLane object to convert into ROS
shared_pointers Vector of shared pointers
Returns
Generic Lane j2735 ROS Msg
Definition at line 331 of file Map_Message.cpp.
    {
        j2735_v2x_msgs::msg::GenericLane gl;
        // Egress Approach
        if (g_lane->egressApproach)
        {
            gl.egress_approach_exists = true;
            gl.egress_approach = *g_lane->egressApproach;
        }
        else
        {
            gl.egress_approach_exists = false;
        }
        // Ingress Approach
        if (g_lane->ingressApproach)
        {
            gl.ingress_approach_exists = true;
            gl.ingress_approach = *g_lane->ingressApproach;
        }
        else
        {
            gl.ingress_approach_exists = false;
        }
        // Lane Attributes
        //  - Lane Direction
        size_t lane_direction_bits_to_shift = g_lane->laneAttributes.directionalUse.bits_unused;
        gl.lane_attributes.directional_use.lane_direction = *g_lane->laneAttributes.directionalUse.buf >> lane_direction_bits_to_shift;
        // - LaneType
        gl.lane_attributes.lane_type.choice = (int)g_lane->laneAttributes.laneType.present - 1; // j2735 ROS msg starts from index 0
        gl.lane_attributes.lane_type.crosswalk.lane_attributes_crosswalk = *g_lane->laneAttributes.laneType.choice.crosswalk.buf >>
                                                                           g_lane->laneAttributes.laneType.choice.crosswalk.bits_unused;
        gl.lane_attributes.lane_type.median.lane_attributes_barrier = *g_lane->laneAttributes.laneType.choice.median.buf >>
                                                                      g_lane->laneAttributes.laneType.choice.median.bits_unused;
        gl.lane_attributes.lane_type.parking.lane_attributes_parking = *g_lane->laneAttributes.laneType.choice.parking.buf >>
                                                                       g_lane->laneAttributes.laneType.choice.parking.bits_unused;
        gl.lane_attributes.lane_type.bike_lane.lane_attributes_bike = *g_lane->laneAttributes.laneType.choice.bikeLane.buf >>
                                                                      g_lane->laneAttributes.laneType.choice.bikeLane.bits_unused;
        gl.lane_attributes.lane_type.sidewalk.lane_attributes_sidewalk = *g_lane->laneAttributes.laneType.choice.sidewalk.buf >>
                                                                         g_lane->laneAttributes.laneType.choice.sidewalk.bits_unused;
        gl.lane_attributes.lane_type.striping.lane_attributes_striping = *g_lane->laneAttributes.laneType.choice.striping.buf >>
                                                                         g_lane->laneAttributes.laneType.choice.striping.bits_unused;
        gl.lane_attributes.lane_type.tracked_vehicle.lane_attributes_trackedvehicle = *g_lane->laneAttributes.laneType.choice.trackedVehicle.buf >>
                                                                                      g_lane->laneAttributes.laneType.choice.trackedVehicle.bits_unused;
        gl.lane_attributes.lane_type.vehicle.lane_attributes_vehicle = *g_lane->laneAttributes.laneType.choice.vehicle.buf >>
                                                                       g_lane->laneAttributes.laneType.choice.vehicle.bits_unused;
        if (g_lane->maneuvers)
        {
            gl.maneuvers_exists = true;
            gl.maneuvers.allowed_maneuvers = *g_lane->maneuvers->buf >> g_lane->maneuvers->bits_unused;
        }
        gl.lane_attributes.shared_with.lane_sharing = *g_lane->laneAttributes.sharedWith.buf >> g_lane->laneAttributes.sharedWith.bits_unused;
        if (g_lane->connectsTo)
        {
            gl.connects_to_exists = true;
            for (size_t c = 0; c < g_lane->connectsTo->list.count; c++)
            {
                Connection_t* ct = g_lane->connectsTo->list.array[c];
                j2735_v2x_msgs::msg::Connection entry;
                // Connection ID
                if (ct->connectionID)
                {
                    entry.connection_id_exists = true;
                    entry.connection_id = *ct->connectionID;
                }
                else
                {
                    entry.connection_id_exists = false;
                }
                // Connecting Lane
                entry.connecting_lane.lane = ct->connectingLane.lane;
                if (ct->connectingLane.maneuver)
                {
                    entry.connecting_lane.maneuver_exists = true;
                    uint16_t binary = ct->connectingLane.maneuver->buf[0] >> 4;
                    unsigned int maneuver_type;
                    maneuver_type = 4;
                    // e.g. shift the binary right until it equals to 1 (0b00000001) to determine the location of the non-zero bit
                    for (int m = 0; m < ct->connectingLane.maneuver->size; m++)
                    {
                        if ((int)binary == 1)
{
                            entry.connecting_lane.maneuver.allowed_maneuvers = maneuver_type;
                            break;
                        }
                        else
{
                            maneuver_type -= 1;
                            binary = binary >> 1;
                        }
                    }
                }
                else
                {
                    entry.connecting_lane.maneuver_exists = false;
                    entry.connecting_lane.maneuver.allowed_maneuvers = 0;
                }
                // Remote Intersection
                if (ct->remoteIntersection)
                {
                    entry.remote_intersection_exists = true;
                    // Remote Intersection Region
                    if (ct->remoteIntersection->region)
                    {
                        entry.remote_intersection.region_exists = true;
                        entry.remote_intersection.region = *ct->remoteIntersection->region;
                    }
                    else
                    {
                        entry.remote_intersection.region_exists = false;
                        entry.remote_intersection.region = j2735_v2x_msgs::msg::IntersectionReferenceID::REGION_UNAVAILABLE;
                    }
                    entry.remote_intersection.id = ct->remoteIntersection->id;
                }
                else
                {
                    entry.remote_intersection_exists = false;
                }
                // Signal Group
                if (ct->signalGroup)
                {
                    entry.signal_group_exists = true;
                    entry.signal_group = *ct->signalGroup;
                }
                else
                {
                    entry.signal_group_exists = false;
                }
                // User Class
                if (ct->userClass)
                {
                    entry.user_class_exists = true;
                    entry.user_class = *ct->userClass;
                }
                gl.connects_to.connect_to_list.push_back(entry);
            }
        }
        else
        {
            gl.connects_to_exists = false;
        } // end connects to
        if (g_lane->laneID)
        {
            gl.lane_id = g_lane->laneID;
        }
        // Node List
        gl.node_list.choice = (int)g_lane->nodeList.present - 1; // ROS j2735 msg starts from 0 index
        gl.node_list.computed.offset_x_axis.large = g_lane->nodeList.choice.computed.offsetXaxis.choice.large;
        gl.node_list.computed.offset_x_axis.small = g_lane->nodeList.choice.computed.offsetXaxis.choice.small;
        gl.node_list.computed.offset_y_axis.large = g_lane->nodeList.choice.computed.offsetYaxis.choice.large;
        gl.node_list.computed.offset_y_axis.small = g_lane->nodeList.choice.computed.offsetYaxis.choice.small;
        // NodeList Scale Axis
        if (g_lane->nodeList.choice.computed.scaleXaxis)
        {
            gl.node_list.computed.scale_x_axis_exists = true;
            gl.node_list.computed.scale_x_axis = *g_lane->nodeList.choice.computed.scaleXaxis;
        }
        if (g_lane->nodeList.choice.computed.scaleYaxis)
        {
            gl.node_list.computed.scale_y_axis_exists = true;
            gl.node_list.computed.scale_y_axis = *g_lane->nodeList.choice.computed.scaleYaxis;
        }
        // Rotate XY
        if (g_lane->nodeList.choice.computed.rotateXY)
        {
            gl.node_list.computed.rotatexy_exists = true;
            gl.node_list.computed.rotate_xy = *g_lane->nodeList.choice.computed.rotateXY;
        }
        // Scale Axis
        if (g_lane->nodeList.choice.computed.scaleXaxis)
        {
            gl.node_list.computed.scale_x_axis_exists = true;
            gl.node_list.computed.scale_x_axis = *g_lane->nodeList.choice.computed.scaleXaxis;
        }
        if (g_lane->nodeList.choice.computed.scaleYaxis)
        {
            gl.node_list.computed.scale_y_axis_exists = true;
            gl.node_list.computed.scale_y_axis = *g_lane->nodeList.choice.computed.scaleYaxis;
        }
        // Reference lat long
        gl.node_list.computed.reference_lane_id = g_lane->nodeList.choice.computed.referenceLaneId;
        // Nodes
        for (size_t n = 0; n < g_lane->nodeList.choice.nodes.list.count; n++)
        {
            j2735_v2x_msgs::msg::NodeXY node;
            // Attributes
            if (g_lane->nodeList.choice.nodes.list.array[n]->attributes)
            {
                NodeAttributeSetXY* attributes = g_lane->nodeList.choice.nodes.list.array[n]->attributes;
                node.attributes_exists = true;
                // Attribute Data
                if (attributes->data)
                {
                    node.attributes.data_exists = true;
                    j2735_v2x_msgs::msg::LaneDataAttribute data;
                    for (size_t d = 0; d < attributes->data->list.count; d++)
                    {
                        data.lane_angle = attributes->data->list.array[d]->choice.laneAngle;
                        data.lane_crown_point_center = attributes->data->list.array[d]->choice.laneCrownPointCenter;
                        data.lane_crown_point_left = attributes->data->list.array[d]->choice.laneCrownPointLeft;
                        data.lane_crown_point_right = attributes->data->list.array[d]->choice.laneCrownPointRight;
                        data.path_end_point_angle = attributes->data->list.array[d]->choice.pathEndPointAngle;
                        for (size_t sl = 0; sl < attributes->data->list.array[d]->choice.speedLimits.list.count; sl++)
{
                            j2735_v2x_msgs::msg::RegulatorySpeedLimit speedLimit;
                            speedLimit.speed = attributes->data->list.array[d]->choice.speedLimits.list.array[sl]->speed;
                            speedLimit.type.speed_limit_type = attributes->data->list.array[d]->choice.speedLimits.list.array[sl]->type;
                            data.speed_limits.speed_limits.push_back(speedLimit);
                        }
                        node.attributes.data.lane_attribute_list.push_back(data);
                    }
                }
                else
                {
                    node.attributes.data_exists = false;
                } // end Attribute Data
                // Attribute DElevation
                if (attributes->dElevation)
                {
                    node.attributes.d_elevation_exists = true;
                    node.attributes.d_elevation = *attributes->dElevation;
                }
                else
                {
                    node.attributes.d_elevation_exists = false;
                } // end Attribute DElevation
                // Attributes Disabled
                if (attributes->disabled)
                {
                    node.attributes.disabled_exists = true;
                    for (size_t sa = 0; sa < attributes->disabled->list.count; sa++)
                    {
                        j2735_v2x_msgs::msg::SegmentAttributeXY sxy;
                        sxy.segment_attribute_xy = *attributes->disabled->list.array[sa];
                        node.attributes.disabled.segment_attribute_xy.push_back(sxy);
                    }
                }
                else
                {
                    node.attributes.disabled_exists = false;
                } // end Attributes Disabled
                // Attributes DWidth
                if (attributes->dWidth)
                {
                    node.attributes.d_width_exists = true;
                    node.attributes.d_width = *attributes->dWidth;
                }
                else
                {
                    node.attributes.d_width_exists = false;
                } // end Attributes DWidth
                // Attributes Enabled
                if (attributes->enabled)
                {
                    node.attributes.enabled_exists = true;
                    for (size_t en = 0; en < attributes->enabled->list.count; en++)
                    {
                        j2735_v2x_msgs::msg::SegmentAttributeXY enabled;
                        enabled.segment_attribute_xy = *attributes->enabled->list.array[en];
                        node.attributes.enabled.segment_attribute_xy.push_back(enabled);
                    }
                }
                else
                {
                    node.attributes.enabled_exists = false;
                } // end Attributes Enabled
                // Attribute Local Node
                if (attributes->localNode)
                {
                    node.attributes.local_node_exists = true;
                    for (size_t ln = 0; ln < attributes->localNode->list.count; ln++)
                    {
                        j2735_v2x_msgs::msg::NodeAttributeXY n_att;
                        n_att.node_attribute_xy = *attributes->localNode->list.array[ln];
                        node.attributes.local_node.node_attribute_xy_list.push_back(n_att);
                    }
                }
                else
                {
                    node.attributes.local_node_exists = false;
                } // end Attribute Local Node
            }
            else
            {
                node.attributes_exists = false;
            } // end Attributes
            // Node Delta
            node.delta.choice = (int)g_lane->nodeList.choice.nodes.list.array[n]->delta.present - 1; // index starts from 0 on j2735 msg
            node.delta.node_latlon.latitude = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_LatLon.lat;
            node.delta.node_latlon.longitude = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_LatLon.lon;
            node.delta.node_xy1.x = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_XY1.x;
            node.delta.node_xy1.y = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_XY1.y;
            node.delta.node_xy2.x = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_XY2.x;
            node.delta.node_xy2.y = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_XY2.y;
            node.delta.node_xy3.x = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_XY3.x;
            node.delta.node_xy3.y = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_XY3.y;
            node.delta.node_xy4.x = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_XY4.x;
            node.delta.node_xy4.y = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_XY4.y;
            node.delta.node_xy5.x = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_XY5.x;
            node.delta.node_xy5.y = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_XY5.y;
            node.delta.node_xy6.x = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_XY6.x;
            node.delta.node_xy6.y = g_lane->nodeList.choice.nodes.list.array[n]->delta.choice.node_XY6.y;
            gl.node_list.nodes.node_set_xy.push_back(node);
            // end Node Delta Handling
        }
        if (g_lane->overlays)
        {
            gl.overlay_lane_list_exists = true;
            for (size_t o = 0; o < g_lane->overlays->list.count; o++)
            {
                LaneID_t* ln = g_lane->overlays->list.array[o];
                gl.overlay_lane_list.overlay_lane_list.push_back(*ln);
            }
        }
        return gl;
    }
References LaneTypeAttributes::LaneTypeAttributes_u::bikeLane, BIT_STRING_s::bits_unused, BIT_STRING_s::buf, ComputedLane::ComputedLane__offsetXaxis::choice, ComputedLane::ComputedLane__offsetYaxis::choice, LaneTypeAttributes::choice, NodeListXY::choice, NodeListXY::NodeListXY_u::computed, Connection::connectingLane, Connection::connectionID, GenericLane::connectsTo, LaneTypeAttributes::LaneTypeAttributes_u::crosswalk, NodeAttributeSetXY::data, NodeAttributeSetXY::dElevation, LaneAttributes::directionalUse, NodeAttributeSetXY::disabled, NodeAttributeSetXY::dWidth, GenericLane::egressApproach, NodeAttributeSetXY::enabled, IntersectionReferenceID::id, GenericLane::ingressApproach, ConnectingLane::lane, GenericLane::laneAttributes, GenericLane::laneID, LaneAttributes::laneType, ComputedLane::ComputedLane__offsetXaxis::ComputedLane__offsetXaxis_u::large, ComputedLane::ComputedLane__offsetYaxis::ComputedLane__offsetYaxis_u::large, NodeAttributeSetXY::localNode, ConnectingLane::maneuver, GenericLane::maneuvers, LaneTypeAttributes::LaneTypeAttributes_u::median, GenericLane::nodeList, NodeListXY::NodeListXY_u::nodes, ComputedLane::offsetXaxis, ComputedLane::offsetYaxis, GenericLane::overlays, LaneTypeAttributes::LaneTypeAttributes_u::parking, LaneTypeAttributes::present, NodeListXY::present, ComputedLane::referenceLaneId, IntersectionReferenceID::region, Connection::remoteIntersection, ComputedLane::rotateXY, ComputedLane::scaleXaxis, ComputedLane::scaleYaxis, LaneAttributes::sharedWith, LaneTypeAttributes::LaneTypeAttributes_u::sidewalk, Connection::signalGroup, BIT_STRING_s::size, ComputedLane::ComputedLane__offsetXaxis::ComputedLane__offsetXaxis_u::small, ComputedLane::ComputedLane__offsetYaxis::ComputedLane__offsetYaxis_u::small, LaneTypeAttributes::LaneTypeAttributes_u::striping, LaneTypeAttributes::LaneTypeAttributes_u::trackedVehicle, Connection::userClass, and LaneTypeAttributes::LaneTypeAttributes_u::vehicle.
Referenced by decode_map_message().
decode_map_message()
boost::optional< j2735_v2x_msgs::msg::MapData > cpp_message::Map_Message::decode_map_message (std::vector< uint8_t > & binary_array)
Construct a new map message object.
Parameters
binary_array Container with binary input.
Returns
decoded ros message, returns ROS warning and an empty optional if decoding fails.
Definition at line 22 of file Map_Message.cpp.
    {
        j2735_v2x_msgs::msg::MapData output;
        // decode results
        asn_dec_rval_t rval;
        MessageFrame_t *message = nullptr;
        // copy from vector to array
        size_t len = binary_array.size();
        uint8_t buf[len];
        std::copy(binary_array.begin(), binary_array.end(), buf);
        // use asn1c lib to decode
        rval = uper_decode(0, &asn_DEF_MessageFrame, (void **) &message, buf, len, 0, 0);
        if (rval.code != RC_OK)
        {
            ASN_STRUCT_FREE(asn_DEF_MessageFrame, message);
            return boost::optional<j2735_v2x_msgs::msg::MapData>{};
        }
        auto map_msg = message->value.choice.MapData;
        // Time Stamp
        if (map_msg.timeStamp)
        {
            output.time_stamp_exists = true;
            output.time_stamp = *map_msg.timeStamp;
        }
        else
        {
            output.time_stamp_exists = false;
        }
        output.msg_issue_revision = map_msg.msgIssueRevision;
        output.layer_type.layer_type = *map_msg.layerType;
        // Layer ID
        if (map_msg.layerID)
        {
            output.layer_id_exists = true;
            output.layer_id = *map_msg.layerID;
        } // end layer ID
        else
        {
            output.layer_id_exists = false;
        }
        // Intersection Handling
        if (map_msg.intersections)
        {
            output.intersections_exists = true;
            // Map Intersections
            for (size_t i = 0; i < map_msg.intersections->list.count; i++)
            {
                IntersectionGeometry_t* map_msg_intersections = map_msg.intersections->list.array[i];
                j2735_v2x_msgs::msg::IntersectionGeometry new_intersection;
                new_intersection.id.id = map_msg_intersections->id.id;
                if (map_msg_intersections->id.region)
                {
                    new_intersection.id.region_exists = true; // TODO: Implement intersection ID Region
                    new_intersection.id.region = *map_msg_intersections->id.region;
                }
                else
                {
                    new_intersection.id.region_exists = false;
                    new_intersection.id.region = j2735_v2x_msgs::msg::IntersectionReferenceID::REGION_UNAVAILABLE;
                }
                for (size_t i = 0; i < map_msg_intersections->laneSet.list.count; i++)
                {
                    j2735_v2x_msgs::msg::GenericLane gl = decode_generic_lane(map_msg_intersections->laneSet.list.array[i]);
                    new_intersection.lane_set.lane_list.push_back(gl);
                }
                if (map_msg_intersections->name)
                {
                    new_intersection.name_exists = true;
                    DescriptiveName_t* nm = map_msg_intersections->name;
                    std::string n;
                    for (size_t x = 0; x < nm->size; x++)
                    {
                        n.push_back(nm->buf[x]);
                    }
                    new_intersection.name = n;
                }
                else
                {
                    new_intersection.name_exists = false;
                }
                if (map_msg_intersections->laneWidth)
                {
                    new_intersection.lane_width_exists = true;
                    new_intersection.lane_width = *map_msg_intersections->laneWidth;
                }
                else
                {
                    new_intersection.lane_width_exists = false;
                }
                if (map_msg_intersections->preemptPriorityData)
                {
                    new_intersection.preempt_priority_data_exists = true;
                    for (size_t p = 0; i < map_msg_intersections->preemptPriorityData->list.count; p++)
                    {
                        j2735_v2x_msgs::msg::SignalControlZone signal_control_zone;
                        /*SignalControlZone.msg states that RegionalExtension has not yet been implemented*/
                        new_intersection.preempt_priority_data.preempt_priority_list.push_back(signal_control_zone);
                    }
                }
                else
                {
                    new_intersection.preempt_priority_data_exists = false;
                }
                if (map_msg_intersections->speedLimits)
                {
                    new_intersection.speed_limits_exists = true;
                    for (size_t s = 0; s < map_msg_intersections->speedLimits->list.count; s++)
                    {
                        j2735_v2x_msgs::msg::RegulatorySpeedLimit regulatory_speed_limit;
                        regulatory_speed_limit.speed = map_msg_intersections->speedLimits->list.array[s]->speed;
                        regulatory_speed_limit.type.speed_limit_type = map_msg_intersections->speedLimits->list.array[s]->type;
                        new_intersection.speed_limits.speed_limits.push_back(regulatory_speed_limit);
                    }
                }
                else
                {
                    new_intersection.speed_limits_exists = false;
                }
                if (map_msg_intersections->refPoint.elevation)
                    if (map_msg_intersections->refPoint.elevation)
                        if (map_msg_intersections->refPoint.elevation)
{
                            new_intersection.ref_point.elevation_exists = true;
                            new_intersection.ref_point.elevation_exists = true;
                            new_intersection.ref_point.elevation_exists = true;
                            DSRC_Elevation_t* dsrc_el = map_msg_intersections->refPoint.elevation;
                            new_intersection.ref_point.elevation = *dsrc_el;
                        }
                        else
{
                            new_intersection.ref_point.elevation_exists = false;
                        }
                new_intersection.ref_point.latitude = map_msg_intersections->refPoint.lat;
                new_intersection.ref_point.longitude = map_msg_intersections->refPoint.Long;
                new_intersection.revision = map_msg_intersections->revision;
                output.intersections.push_back(new_intersection);
            }
        } // end intersection handling
        else
        {
            output.intersections_exists = false;
        }
        // Road Segment
        if (map_msg.roadSegments)
        {
            output.road_segments_exists = true;
            for (size_t i = 0; i < map_msg.roadSegments->list.count; i++)
            {
                RoadSegment_t* rseg = map_msg.roadSegments->list.array[i];
                j2735_v2x_msgs::msg::RoadSegment rs;
                if (rseg->laneWidth)
                {
                    rs.lane_width_exists = true;
                    rs.lane_width = *rseg->laneWidth;
                }
                else
                {
                    rs.lane_width_exists = false;
                }
                // Road Segment Name
                if (rseg->name)
                {
                    rs.name_exists = true;
                    DescriptiveName_t* nm = rseg->name;
                    std::string n;
                    for (size_t i = 0; i < nm->size; i++)
                    {
                        n.push_back(nm->buf[i]);
                    }
                    rs.name = n;
                }
                else
                {
                    rs.name_exists = false;
                }
                if (rseg->speedLimits)
                {
                    rs.speed_limits_exists = true;
                    for (size_t i = 0; i < rseg->speedLimits->list.count; i++)
                    {
                        j2735_v2x_msgs::msg::RegulatorySpeedLimit sl;
                        sl.speed = rseg->speedLimits->list.array[i]->speed;
                        sl.type.speed_limit_type = rseg->speedLimits->list.array[i]->type;
                        rs.speed_limits.speed_limits.push_back(sl);
                    }
                } // end speed limits
                else
                {
                    rs.speed_limits_exists = false;
                }
                if (rseg->refPoint.elevation)
                {
                    rs.ref_point.elevation_exists = true;
                    rs.ref_point.elevation = *rseg->refPoint.elevation;
                }
                else
                {
                    rs.ref_point.elevation_exists = false;
                }
                rs.ref_point.latitude = rseg->refPoint.lat;
                rs.ref_point.longitude = rseg->refPoint.Long;
                // RLS
                for (size_t i = 0; i < rseg->roadLaneSet.list.count; i++)
                {
                    j2735_v2x_msgs::msg::GenericLane gl;
                    gl = decode_generic_lane(rseg->roadLaneSet.list.array[i]);
                    rs.road_lane_set.road_lane_set_list.push_back(gl);
                }
                output.road_segments.road_segment_list.push_back(rs);
            }
        } // end Road Segments
        // Data Parameters
        if (map_msg.dataParameters)
        {
            output.data_parameters_exists = true;
            for (size_t i = 0; i < map_msg.dataParameters->geoidUsed->size; i++)
            {
                output.data_parameters.geoid_used.push_back(map_msg.dataParameters->geoidUsed->buf[i]);
            }
            for (size_t i = 0; i < map_msg.dataParameters->lastCheckedDate->size; i++)
            {
                output.data_parameters.last_checked_date.push_back(map_msg.dataParameters->lastCheckedDate->buf[i]);
            }
            for (size_t i = 0; i < map_msg.dataParameters->processAgency->size; i++)
            {
                output.data_parameters.process_agency.push_back(map_msg.dataParameters->processAgency->buf[i]);
            }
            for (size_t i = 0; i < map_msg.dataParameters->processMethod->size; i++)
            {
                output.data_parameters.last_checked_date.push_back(map_msg.dataParameters->processMethod->buf[i]);
            }
        }
        else
        {
            output.data_parameters_exists = false;
        }
        // Restriction List
        if (map_msg.restrictionList)
        {
            output.restriction_list_exists = true;
            for (size_t i = 0; i < map_msg.restrictionList->list.count; i++)
            {
                RestrictionClassAssignment_t* rca = map_msg.restrictionList->list.array[i];
                j2735_v2x_msgs::msg::RestrictionClassAssignment rclass;
                rclass.id = rca->id;
                output.restriction_list.restriction_class_list.push_back(rclass);
            }
        } // end Restriction List
        else
        {
            output.restriction_list_exists = false;
        }
        ASN_STRUCT_FREE(asn_DEF_MessageFrame, message);
        return output;
    }
References asn_DEF_MessageFrame, ASN_STRUCT_FREE, OCTET_STRING::buf, asn_dec_rval_s::code, decode_generic_lane(), Position3D::elevation, IntersectionGeometry::id, IntersectionReferenceID::id, RestrictionClassAssignment::id, IntersectionGeometry::laneSet, IntersectionGeometry::laneWidth, RoadSegment::laneWidth, Position3D::lat, Position3D::Long, IntersectionGeometry::name, RoadSegment::name, IntersectionGeometry::preemptPriorityData, RC_OK, IntersectionGeometry::refPoint, RoadSegment::refPoint, IntersectionReferenceID::region, IntersectionGeometry::revision, RoadSegment::roadLaneSet, OCTET_STRING::size, IntersectionGeometry::speedLimits, RoadSegment::speedLimits, and uper_decode().
Referenced by cpp_message::Node::inbound_binary_callback().
Member Data Documentation
node_logging_
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr cpp_message::Map_Message::node_logging_
Definition at line 43 of file Map_Message.h.
Referenced by Map_Message().
The documentation for this class was generated from the following files:
carma-messenger-core/cpp_message/include/cpp_message/Map_Message.h
carma-messenger-core/cpp_message/src/Map_Message.cpp