Carma-platform: cpp_message::Emergency_Vehicle_Ack Class Reference
cpp_message::Emergency_Vehicle_Ack Class Reference
#include <EmergencyVehicleAck_Message.h>
Public Member Functions
Emergency_Vehicle_Ack (rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging)
constructor
boost::optional< carma_v2x_msgs::msg::EmergencyVehicleAck > decode_emergency_vehicle_ack_message (std::vector< uint8_t > &binary_array)
Emergency Vehicle Acknowledgement message decoding function.
boost::optional< std::vector< uint8_t > > encode_emergency_vehicle_ack_message (carma_v2x_msgs::msg::EmergencyVehicleAck plainMessage)
helper functions for Emergency Vehicle Acknowledgement message encoding.
Public Attributes
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging_
Static Private Attributes
static const int Emergency_Vehicle_Ack_TEST_ID = 247
Detailed Description
Definition at line 22 of file EmergencyVehicleAck_Message.h.
Constructor & Destructor Documentation
Emergency_Vehicle_Ack()
cpp_message::Emergency_Vehicle_Ack::Emergency_Vehicle_Ack (rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging) inline explicit
constructor
Definition at line 32 of file EmergencyVehicleAck_Message.h.
        {
            node_logging_ = node_logging;
        };
References node_logging_.
Member Function Documentation
decode_emergency_vehicle_ack_message()
boost::optional< carma_v2x_msgs::msg::EmergencyVehicleAck > cpp_message::Emergency_Vehicle_Ack::decode_emergency_vehicle_ack_message (std::vector< uint8_t > & binary_array)
Emergency Vehicle Acknowledgement message decoding function.
Parameters
binary_array Container with binary input.
Returns
decoded ros message, returns ROS warning and an empty optional if decoding fails.
Definition at line 43 of file EmergencyVehicleAck_Message.cpp.
    {
        carma_v2x_msgs::msg::MobilityHeader header;
        carma_v2x_msgs::msg::EmergencyVehicleAck output;
        // decode results - stored in binary_array
        asn_dec_rval_t rval;
        MessageFrame_t *message = nullptr;
        // copy from vector to array
        size_t len = binary_array.size();
        uint8_t buf[len];
        std::copy(binary_array.begin(), binary_array.end(), buf);
        // use asn1c lib to decode
        rval = uper_decode(0, &asn_DEF_MessageFrame, (void **)&message, buf, len, 0, 0);
        // if decode success
        if (rval.code == RC_OK)
        {
            // copy acknowledgement boolean (TestMessage07 for EmergencyVehicleAck)
            Mobility_Header Header_constant;
            std::string sender_id, recipient_id, sender_bsm_id, plan_id, timestamp_string;
            uint64_t timestamp;
            // get sender id
            size_t str_len = message->value.choice.TestMessage07.header.hostStaticId.size;
            if (str_len >= Header_constant.STATIC_ID_MIN_LENGTH && str_len <= Header_constant.STATIC_ID_MAX_LENGTH)
            {
                for (size_t i = 0; i < str_len; i++)
                {
                    sender_id += message->value.choice.TestMessage07.header.hostStaticId.buf[i];
                }
            }
            else
                sender_id = Header_constant.STRING_DEFAULT;
            header.sender_id = sender_id;
            // get recepient id
            str_len = message->value.choice.TestMessage07.header.targetStaticId.size;
            if (str_len >= Header_constant.STATIC_ID_MIN_LENGTH && str_len <= Header_constant.STATIC_ID_MAX_LENGTH)
            {
                for (size_t i = 0; i < str_len; i++)
                {
                    recipient_id += message->value.choice.TestMessage07.header.targetStaticId.buf[i];
                }
            }
            else
                recipient_id = Header_constant.STRING_DEFAULT;
            header.recipient_id = recipient_id;
            // get bsm id
            // sender_bsm_id is meant to represent the vehicle BSM id in hex string (Ex: FFFFFFFF)
            str_len = message->value.choice.TestMessage07.header.hostBSMId.size;
            for (size_t i = 0; i < str_len; i++)
            {
                sender_bsm_id += message->value.choice.TestMessage07.header.hostBSMId.buf[i];
            }
            if (str_len < Header_constant.BSM_ID_LENGTH)
            {
                sender_bsm_id = std::string((Header_constant.BSM_ID_LENGTH - str_len), '0').append(sender_bsm_id);
            }
            else if (str_len > Header_constant.BSM_ID_LENGTH)
            {
                RCLCPP_WARN(node_logging_->get_logger(), "BSM ID -size greater than limit, changing to default");
                sender_bsm_id = Header_constant.BSM_ID_DEFAULT;
            }
            header.sender_bsm_id = sender_bsm_id;
            // get plan id
            str_len = message->value.choice.TestMessage07.header.planId.size;
            if (str_len == Header_constant.GUID_LENGTH)
            {
                for (size_t i = 0; i < str_len; i++)
                {
                    plan_id += message->value.choice.TestMessage07.header.planId.buf[i];
                }
            }
            else
                plan_id = Header_constant.GUID_DEFAULT;
            header.plan_id = plan_id;
            // recover uint64_t timestamp from string
            str_len = message->value.choice.TestMessage07.header.timestamp.size;
            timestamp = 0;
            char timestamp_ch[str_len + 1];
            for (size_t i = 0; i < str_len; i++)
            {
                timestamp_ch[i] = message->value.choice.TestMessage07.header.timestamp.buf[i];
            }
            timestamp_ch[str_len] = '\0'; // String needs a null terminator
            timestamp = atoll(timestamp_ch);
            header.timestamp = timestamp;
            output.m_header = header;
            // get acknowledgement
            output.acknowledgement = message->value.choice.TestMessage07.body.acknowledgement;
            ASN_STRUCT_FREE(asn_DEF_MessageFrame, message);
            return boost::optional<carma_v2x_msgs::msg::EmergencyVehicleAck>(output);
        }
        RCLCPP_WARN_STREAM(node_logging_->get_logger(), "emergency vehicle acknowledgement decoding failed");
        ASN_STRUCT_FREE(asn_DEF_MessageFrame, message);
        return boost::optional<carma_v2x_msgs::msg::EmergencyVehicleAck>{};
    }
References asn_DEF_MessageFrame, ASN_STRUCT_FREE, cpp_message::Mobility_Header::BSM_ID_DEFAULT, cpp_message::Mobility_Header::BSM_ID_LENGTH, asn_dec_rval_s::code, cpp_message::Mobility_Header::GUID_DEFAULT, cpp_message::Mobility_Header::GUID_LENGTH, node_logging_, RC_OK, cpp_message::Mobility_Header::STATIC_ID_MAX_LENGTH, cpp_message::Mobility_Header::STATIC_ID_MIN_LENGTH, cpp_message::Mobility_Header::STRING_DEFAULT, and uper_decode().
Referenced by cpp_message::Node::inbound_binary_callback().
encode_emergency_vehicle_ack_message()
boost::optional< std::vector< uint8_t > > cpp_message::Emergency_Vehicle_Ack::encode_emergency_vehicle_ack_message (carma_v2x_msgs::msg::EmergencyVehicleAck plainMessage)
helper functions for Emergency Vehicle Acknowledgement message encoding.
Parameters
plainMessage contains emergency vehicle acknowledgement ros message.
Returns
encoded byte array, returns ROS warning and an empty optional if encoding fails.
Definition at line 154 of file EmergencyVehicleAck_Message.cpp.
    {
        std::vector<std::shared_ptr<void>> shared_ptrs; // keep references to the objects until the encoding is complete
        // encode result placeholder
        uint8_t buffer[512] = {0};
        size_t buffer_size = sizeof(buffer);
        asn_enc_rval_t ec;
        MessageFrame_t *message = create_store_shared<MessageFrame_t>(shared_ptrs);
        // set message type to TestMessage07
        message->messageId = Emergency_Vehicle_Ack_TEST_ID;
        message->value.present = MessageFrame__value_PR_TestMessage07;
        // convert host_id string to char array
        std::string sender_id = plainMessage.m_header.sender_id;
        Mobility_Header Header;
        size_t string_size = sender_id.size();
        if (string_size < Header.STATIC_ID_MIN_LENGTH || string_size > Header.STATIC_ID_MAX_LENGTH)
        {
            RCLCPP_WARN(node_logging_->get_logger(), "Unacceptable host id value, changing to default");
            sender_id = Header.STRING_DEFAULT;
            string_size = Header.STRING_DEFAULT.size();
        }
        uint8_t string_content_hostId[string_size];
        for (size_t i = 0; i < string_size; i++)
        {
            string_content_hostId[i] = sender_id[i];
        }
        message->value.choice.TestMessage07.header.hostStaticId.buf = string_content_hostId;
        message->value.choice.TestMessage07.header.hostStaticId.size = string_size;
        // convert target_id string to char array
        std::string recipient_id = plainMessage.m_header.recipient_id;
        string_size = recipient_id.size();
        if (string_size < Header.STATIC_ID_MIN_LENGTH || string_size > Header.STATIC_ID_MAX_LENGTH)
        {
            RCLCPP_WARN(node_logging_->get_logger(), "Unacceptable recipient id value, changing to default");
            recipient_id = Header.STRING_DEFAULT;
            string_size = Header.STRING_DEFAULT.size();
        }
        uint8_t string_content_targetId[string_size];
        for (size_t i = 0; i < string_size; i++)
        {
            string_content_targetId[i] = recipient_id[i];
        }
        message->value.choice.TestMessage07.header.targetStaticId.buf = string_content_targetId;
        message->value.choice.TestMessage07.header.targetStaticId.size = string_size;
        // convert bsm_id string to char array
        // sender_bsm_id is meant to represent the vehicle BSM id in hex string (Ex: FFFFFFFF)
        std::string sender_bsm_id = plainMessage.m_header.sender_bsm_id;
        string_size = sender_bsm_id.size();
        if (string_size < Header.BSM_ID_LENGTH)
        {
            sender_bsm_id = std::string((Header.BSM_ID_LENGTH - string_size), '0').append(sender_bsm_id);
        }
        else if (string_size > Header.BSM_ID_LENGTH)
        {
            RCLCPP_WARN(node_logging_->get_logger(), "BSM ID greater than limit, changing to default");
            sender_bsm_id = Header.BSM_ID_DEFAULT;
        }
        string_size = Header.BSM_ID_LENGTH;
        uint8_t string_content_BSMId[string_size];
        for (size_t i = 0; i < string_size; i++)
        {
            string_content_BSMId[i] = sender_bsm_id[i];
        }
        message->value.choice.TestMessage07.header.hostBSMId.buf = string_content_BSMId;
        message->value.choice.TestMessage07.header.hostBSMId.size = string_size;
        // convert plan_id string to char array
        std::string plan_id = plainMessage.m_header.plan_id;
        string_size = plan_id.size();
        if (string_size != Header.GUID_LENGTH)
        {
            RCLCPP_WARN(node_logging_->get_logger(), "Unacceptable GUID, changing to default");
            plan_id = Header.GUID_DEFAULT;
            string_size = Header.GUID_LENGTH;
        }
        uint8_t string_content_planId[string_size];
        for (size_t i = 0; i < string_size; i++)
        {
            string_content_planId[i] = plan_id[i];
        }
        message->value.choice.TestMessage07.header.planId.buf = string_content_planId;
        message->value.choice.TestMessage07.header.planId.size = string_size;
        // get timestamp and convert to char array
        uint64_t time = plainMessage.m_header.timestamp;
        std::string timestamp = std::to_string(time);
        string_size = timestamp.size();
        if (string_size < Header.TIMESTAMP_MESSAGE_LENGTH)
        {
            timestamp = std::string((Header.TIMESTAMP_MESSAGE_LENGTH - string_size), '0').append(timestamp);
        }
        else if (string_size > Header.TIMESTAMP_MESSAGE_LENGTH)
        {
            RCLCPP_WARN(node_logging_->get_logger(), "Unacceptable timestamp value, changing to default");
            timestamp = std::string(Header.TIMESTAMP_MESSAGE_LENGTH, '0');
        }
        uint8_t string_content_timestamp[Header.TIMESTAMP_MESSAGE_LENGTH];
        for (size_t i = 0; i < Header.TIMESTAMP_MESSAGE_LENGTH; i++)
        {
            string_content_timestamp[i] = timestamp[i];
        }
        message->value.choice.TestMessage07.header.timestamp.buf = string_content_timestamp;
        message->value.choice.TestMessage07.header.timestamp.size = Header.TIMESTAMP_MESSAGE_LENGTH;
        message->value.choice.TestMessage07.body.acknowledgement = plainMessage.acknowledgement;
        ec = uper_encode_to_buffer(&asn_DEF_MessageFrame, 0, message, buffer, buffer_size);
        // log a warning if that fails
        if (ec.encoded == -1)
        {
            RCLCPP_WARN_STREAM(node_logging_->get_logger(), "Encoding for Emergency Vehicle Ack Message failed");
            return boost::optional<std::vector<uint8_t>>{};
        }
        // copy to byte array msg
        size_t array_length = (ec.encoded + 7) / 8;
        std::vector<uint8_t> b_array(array_length);
        for (size_t i = 0; i < array_length; i++)
            b_array[i] = buffer[i];
        // for(size_t i = 0; i < array_length; i++) std::cout<< int(b_array[i])<< ", ";
        return boost::optional<std::vector<uint8_t>>(b_array);
    }
References asn_DEF_MessageFrame, Emergency_Vehicle_Ack_TEST_ID, asn_enc_rval_s::encoded, MessageFrame__value_PR_TestMessage07, node_logging_, and uper_encode_to_buffer().
Referenced by cpp_message::Node::outbound_emergency_vehicle_ack_message_callback().
Member Data Documentation
Emergency_Vehicle_Ack_TEST_ID
const int cpp_message::Emergency_Vehicle_Ack::Emergency_Vehicle_Ack_TEST_ID = 247 static private
Definition at line 26 of file EmergencyVehicleAck_Message.h.
Referenced by encode_emergency_vehicle_ack_message().
node_logging_
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr cpp_message::Emergency_Vehicle_Ack::node_logging_
Definition at line 38 of file EmergencyVehicleAck_Message.h.
Referenced by Emergency_Vehicle_Ack(), decode_emergency_vehicle_ack_message(), and encode_emergency_vehicle_ack_message().
The documentation for this class was generated from the following files:
carma-messenger-core/cpp_message/include/cpp_message/EmergencyVehicleAck_Message.h
carma-messenger-core/cpp_message/src/EmergencyVehicleAck_Message.cpp