Carma-platform: j2735_convertor::SDSMConvertor Class Reference
j2735_convertor::SDSMConvertor Class Reference
Is the class responsible for converting J2735 SDSMs to CARMA usable SDSMs.
#include <sdsm_convertor.hpp>
Static Public Member Functions
static void convert (const j3224_v2x_msgs::msg::SensorDataSharingMessage &in_msg, carma_v2x_msgs::msg::SensorDataSharingMessage &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::SensorDataSharingMessage into a carma_v2x_msgs::msg::SensorDataSharingMessage.
static void convert (const carma_v2x_msgs::msg::SensorDataSharingMessage &in_msg, j3224_v2x_msgs::msg::SensorDataSharingMessage &out_msg)
Convert the contents of a carma_v2x_msgs::msg::SensorDataSharingMessage into a j3224_v2x_msgs::msg::SensorDataSharingMessage.
Static Private Member Functions
static void convert (const j2735_v2x_msgs::msg::YawRate &in_msg, carma_v2x_msgs::msg::YawRate &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::YawRate into a carma_v2x_msgs::msg::YawRate.
static void convert (const carma_v2x_msgs::msg::YawRate &in_msg, j2735_v2x_msgs::msg::YawRate &out_msg)
Convert the contents of a carma_v2x_msgs::msg::YawRate into a j2735_v2x_msgs::msg::YawRate.
static void convert (const j2735_v2x_msgs::msg::Position3D &in_msg, carma_v2x_msgs::msg::Position3D &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::Position3D into a carma_v2x_msgs::msg::Position3D.
static void convert (const carma_v2x_msgs::msg::Position3D &in_msg, j2735_v2x_msgs::msg::Position3D &out_msg)
Convert the contents of a carma_v2x_msgs::msg::Position3D into a j2735_v2x_msgs::msg::Position3D.
static void convert (const j2735_v2x_msgs::msg::PositionalAccuracy &in_msg, carma_v2x_msgs::msg::PositionalAccuracy &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::PositionalAccuracy into a carma_v2x_msgs::msg::PositionalAccuracy.
static void convert (const carma_v2x_msgs::msg::PositionalAccuracy &in_msg, j2735_v2x_msgs::msg::PositionalAccuracy &out_msg)
Convert the contents of a carma_v2x_msgs::msg::PositionalAccuracy into a j2735_v2x_msgs::msg::PositionalAccuracy.
static void convert (const j2735_v2x_msgs::msg::Speed &in_msg, carma_v2x_msgs::msg::Speed &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::Speed into a carma_v2x_msgs::msg::Speed.
static void convert (const carma_v2x_msgs::msg::Speed &in_msg, j2735_v2x_msgs::msg::Speed &out_msg)
Convert the contents of a carma_v2x_msgs::msg::Speed into a j2735_v2x_msgs::msg::Speed.
static void convert (const j2735_v2x_msgs::msg::Heading &in_msg, carma_v2x_msgs::msg::Heading &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::Heading into a carma_v2x_msgs::msg::Heading.
static void convert (const carma_v2x_msgs::msg::Heading &in_msg, j2735_v2x_msgs::msg::Heading &out_msg)
Convert the contents of a carma_v2x_msgs::msg::Heading into a j2735_v2x_msgs::msg::Heading.
static void convert (const j2735_v2x_msgs::msg::AccelerationSet4Way &in_msg, carma_v2x_msgs::msg::AccelerationSet4Way &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::AccelerationSet4Way into a carma_v2x_msgs::msg::AccelerationSet4Way.
static void convert (const carma_v2x_msgs::msg::AccelerationSet4Way &out_msg, j2735_v2x_msgs::msg::AccelerationSet4Way &in_msg)
Convert the contents of a carma_v2x_msgs::msg::AccelerationSet4Way into a j2735_v2x_msgs::msg::AccelerationSet4Way.
static void convert (const j2735_v2x_msgs::msg::VehicleSize &in_msg, carma_v2x_msgs::msg::VehicleSize &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::VehicleSize into a carma_v2x_msgs::msg::VehicleSize.
static void convert (const carma_v2x_msgs::msg::VehicleSize &in_msg, j2735_v2x_msgs::msg::VehicleSize &out_msg)
Convert the contents of a carma_v2x_msgs::msg::VehicleSize into a j2735_v2x_msgs::msg::VehicleSize.
static void convert (const j2735_v2x_msgs::msg::VehicleHeight &in_msg, carma_v2x_msgs::msg::VehicleHeight &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::VehicleHeight into a carma_v2x_msgs::msg::VehicleHeight.
static void convert (const carma_v2x_msgs::msg::VehicleHeight &in_msg, j2735_v2x_msgs::msg::VehicleHeight &out_msg)
Convert the contents of a carma_v2x_msgs::msg::VehicleHeight into a j2735_v2x_msgs::msg::VehicleHeight.
static void convert (const j2735_v2x_msgs::msg::AttachmentRadius &in_msg, carma_v2x_msgs::msg::AttachmentRadius &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::AttachmentRadius into a carma_v2x_msgs::msg::AttachmentRadius.
static void convert (const carma_v2x_msgs::msg::AttachmentRadius &in_msg, j2735_v2x_msgs::msg::AttachmentRadius &out_msg)
Convert the contents of a carma_v2x_msgs::msg::AttachmentRadius into a j2735_v2x_msgs::msg::AttachmentRadius.
static void convert (const j3224_v2x_msgs::msg::DetectedObjectData &in_msg, carma_v2x_msgs::msg::DetectedObjectData &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::DetectedObjectData into a carma_v2x_msgs::msg::DetectedObjectData.
static void convert (const carma_v2x_msgs::msg::DetectedObjectData &in_msg, j3224_v2x_msgs::msg::DetectedObjectData &out_msg)
Convert the contents of a carma_v2x_msgs::msg::DetectedObjectData into a j3224_v2x_msgs::msg::DetectedObjectData.
static void convert (const j3224_v2x_msgs::msg::DetectedObjectCommonData &in_msg, carma_v2x_msgs::msg::DetectedObjectCommonData &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::DetectedObjectCommonData into a carma_v2x_msgs::msg::DetectedObjectCommonData.
static void convert (const carma_v2x_msgs::msg::DetectedObjectCommonData &in_msg, j3224_v2x_msgs::msg::DetectedObjectCommonData &out_msg)
Convert the contents of a carma_v2x_msgs::msg::DetectedObjectCommonData into a j3224_v2x_msgs::msg::DetectedObjectCommonData.
static void convert (const j3224_v2x_msgs::msg::DetectedObjectOptionalData &in_msg, carma_v2x_msgs::msg::DetectedObjectOptionalData &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::DetectedObjectOptionalData into a carma_v2x_msgs::msg::DetectedObjectOptionalData.
static void convert (const carma_v2x_msgs::msg::DetectedObjectOptionalData &in_msg, j3224_v2x_msgs::msg::DetectedObjectOptionalData &out_msg)
Convert the contents of a carma_v2x_msgs::msg::DetectedObjectOptionalData into a j3224_v2x_msgs::msg::DetectedObjectOptionalData.
static void convert (const j3224_v2x_msgs::msg::MeasurementTimeOffset &in_msg, carma_v2x_msgs::msg::MeasurementTimeOffset &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::MeasurementTimeOffset into a carma_v2x_msgs::msg::MeasurementTimeOffset.
static void convert (const carma_v2x_msgs::msg::MeasurementTimeOffset &in_msg, j3224_v2x_msgs::msg::MeasurementTimeOffset &out_msg)
Convert the contents of a carma_v2x_msgs::msg::MeasurementTimeOffset into a j3224_v2x_msgs::msg::MeasurementTimeOffset.
static void convert (const j3224_v2x_msgs::msg::PositionOffsetXYZ &in_msg, carma_v2x_msgs::msg::PositionOffsetXYZ &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::PositionOffsetXYZ into a carma_v2x_msgs::msg::PositionOffsetXYZ.
static void convert (const carma_v2x_msgs::msg::PositionOffsetXYZ &in_msg, j3224_v2x_msgs::msg::PositionOffsetXYZ &out_msg)
Convert the contents of a carma_v2x_msgs::msg::PositionOffsetXYZ into a j3224_v2x_msgs::msg::PositionOffsetXYZ.
static void convert (const j3224_v2x_msgs::msg::ObjectDistance &in_msg, carma_v2x_msgs::msg::ObjectDistance &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::ObjectDistance into a carma_v2x_msgs::msg::ObjectDistance.
static void convert (const carma_v2x_msgs::msg::ObjectDistance &in_msg, j3224_v2x_msgs::msg::ObjectDistance &out_msg)
Convert the contents of a carma_v2x_msgs::msg::ObjectDistance into a j3224_v2x_msgs::msg::ObjectDistance.
static void convert (const j3224_v2x_msgs::msg::DetectedVehicleData &in_msg, carma_v2x_msgs::msg::DetectedVehicleData &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::DetectedVehicleData into a carma_v2x_msgs::msg::DetectedVehicleData.
static void convert (const carma_v2x_msgs::msg::DetectedVehicleData &in_msg, j3224_v2x_msgs::msg::DetectedVehicleData &out_msg)
Convert the contents of a carma_v2x_msgs::msg::DetectedVehicleData into a j3224_v2x_msgs::msg::DetectedVehicleData.
static void convert (const j3224_v2x_msgs::msg::Attitude &in_msg, carma_v2x_msgs::msg::Attitude &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::Attitude into a carma_v2x_msgs::msg::Attitude.
static void convert (const carma_v2x_msgs::msg::Attitude &in_msg, j3224_v2x_msgs::msg::Attitude &out_msg)
Convert the contents of a carma_v2x_msgs::msg::Attitude into a j3224_v2x_msgs::msg::Attitude.
static void convert (const j3224_v2x_msgs::msg::PitchDetected &in_msg, carma_v2x_msgs::msg::PitchDetected &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::PitchDetected into a carma_v2x_msgs::msg::PitchDetected.
static void convert (const carma_v2x_msgs::msg::PitchDetected &in_msg, j3224_v2x_msgs::msg::PitchDetected &out_msg)
Convert the contents of a carma_v2x_msgs::msg::PitchDetected into a j3224_v2x_msgs::msg::PitchDetected.
static void convert (const j3224_v2x_msgs::msg::RollDetected &in_msg, carma_v2x_msgs::msg::RollDetected &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::RollDetected into a carma_v2x_msgs::msg::RollDetected.
static void convert (const carma_v2x_msgs::msg::RollDetected &in_msg, j3224_v2x_msgs::msg::RollDetected &out_msg)
Convert the contents of a carma_v2x_msgs::msg::RollDetected into a j3224_v2x_msgs::msg::RollDetected.
static void convert (const j3224_v2x_msgs::msg::YawDetected &in_msg, carma_v2x_msgs::msg::YawDetected &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::YawDetected into a carma_v2x_msgs::msg::YawDetected.
static void convert (const carma_v2x_msgs::msg::YawDetected &in_msg, j3224_v2x_msgs::msg::YawDetected &out_msg)
Convert the contents of a carma_v2x_msgs::msg::YawDetected into a j3224_v2x_msgs::msg::YawDetected.
static void convert (const j3224_v2x_msgs::msg::AngularVelocity &in_msg, carma_v2x_msgs::msg::AngularVelocity &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::AngularVelocity into a carma_v2x_msgs::msg::AngularVelocity.
static void convert (const carma_v2x_msgs::msg::AngularVelocity &in_msg, j3224_v2x_msgs::msg::AngularVelocity &out_msg)
Convert the contents of a carma_v2x_msgs::msg::AngularVelocity into a j3224_v2x_msgs::msg::AngularVelocity.
static void convert (const j3224_v2x_msgs::msg::PitchRate &in_msg, carma_v2x_msgs::msg::PitchRate &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::PitchRate into a carma_v2x_msgs::msg::PitchRate.
static void convert (const carma_v2x_msgs::msg::PitchRate &in_msg, j3224_v2x_msgs::msg::PitchRate &out_msg)
Convert the contents of a carma_v2x_msgs::msg::PitchRate into a j3224_v2x_msgs::msg::PitchRate.
static void convert (const j3224_v2x_msgs::msg::RollRate &in_msg, carma_v2x_msgs::msg::RollRate &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::RollRate into a carma_v2x_msgs::msg::RollRate.
static void convert (const carma_v2x_msgs::msg::RollRate &in_msg, j3224_v2x_msgs::msg::RollRate &out_msg)
Convert the contents of a carma_v2x_msgs::msg::RollRate into a j3224_v2x_msgs::msg::RollRate.
static void convert (const j3224_v2x_msgs::msg::DetectedVRUData &in_msg, carma_v2x_msgs::msg::DetectedVRUData &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::DetectedVRUData into a carma_v2x_msgs::msg::DetectedVRUData.
static void convert (const carma_v2x_msgs::msg::DetectedVRUData &in_msg, j3224_v2x_msgs::msg::DetectedVRUData &out_msg)
Convert the contents of a carma_v2x_msgs::msg::DetectedVRUData into a j3224_v2x_msgs::msg::DetectedVRUData.
static void convert (const j3224_v2x_msgs::msg::DetectedObstacleData &in_msg, carma_v2x_msgs::msg::DetectedObstacleData &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::DetectedObstacleData into a carma_v2x_msgs::msg::DetectedObstacleData.
static void convert (const carma_v2x_msgs::msg::DetectedObstacleData &in_msg, j3224_v2x_msgs::msg::DetectedObstacleData &out_msg)
Convert the contents of a carma_v2x_msgs::msg::DetectedObstacleData into a j3224_v2x_msgs::msg::DetectedObstacleData.
static void convert (const j3224_v2x_msgs::msg::ObstacleSize &in_msg, carma_v2x_msgs::msg::ObstacleSize &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::ObstacleSize into a carma_v2x_msgs::msg::ObstacleSize.
static void convert (const carma_v2x_msgs::msg::ObstacleSize &in_msg, j3224_v2x_msgs::msg::ObstacleSize &out_msg)
Convert the contents of a carma_v2x_msgs::msg::ObstacleSize into a j3224_v2x_msgs::msg::ObstacleSize.
static void convert (const j3224_v2x_msgs::msg::SizeValue &in_msg, carma_v2x_msgs::msg::SizeValue &out_msg)
Convert the contents of a j3224_v2x_msgs::msg::SizeValue into a carma_v2x_msgs::msg::SizeValue.
static void convert (const carma_v2x_msgs::msg::SizeValue &in_msg, j3224_v2x_msgs::msg::SizeValue &out_msg)
Convert the contents of a carma_v2x_msgs::msg::SizeValue into a j3224_v2x_msgs::msg::SizeValue.
Detailed Description
Is the class responsible for converting J2735 SDSMs to CARMA usable SDSMs.
Handles conversion between SDSMs in the j3224_v2x_msgs and carma_v2x_msgs packages with additional conversions for j2735_v2x_msgs. Unit conversions and presence flags are also handled
Definition at line 36 of file sdsm_convertor.hpp.
Member Function Documentation
convert() [1/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::AccelerationSet4Way & out_msg, j2735_v2x_msgs::msg::AccelerationSet4Way & in_msg) static private
Convert the contents of a carma_v2x_msgs::msg::AccelerationSet4Way into a j2735_v2x_msgs::msg::AccelerationSet4Way.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of logitudinal (CM_PER_M), lateral (CM_PER_M), and vert (FIFTIETH_G_PER_M_PER_SEC_SQUARED) acceleration plus yaw rate (CENTI_DEG_PER_DEG) and presence flags are handled
Definition at line 229 of file sdsm_convertor.cpp.
{
  // Convert Longitudinal and Lateral
  out_msg.longitudinal = ValueConvertor::valueCavToJ2735<int16_t>(
      in_msg.longitudinal, units::CM_PER_M, in_msg.presence_vector,
      carma_v2x_msgs::msg::AccelerationSet4Way::ACCELERATION_AVAILABLE, j2735_v2x_msgs::msg::AccelerationSet4Way::ACCELERATION_UNAVAILABLE);
  out_msg.lateral = ValueConvertor::valueCavToJ2735<int16_t>(in_msg.lateral, units::CM_PER_M, in_msg.presence_vector,
                                                             carma_v2x_msgs::msg::AccelerationSet4Way::ACCELERATION_AVAILABLE,
                                                             j2735_v2x_msgs::msg::AccelerationSet4Way::ACCELERATION_UNAVAILABLE);
  // Convert Vertical
  out_msg.vert =
      ValueConvertor::valueCavToJ2735<int8_t>(in_msg.vert, units::FIFTIETH_G_PER_M_PER_SEC_SQR, in_msg.presence_vector,
                                              carma_v2x_msgs::msg::AccelerationSet4Way::ACCELERATION_VERTICAL_AVAILABLE,
                                              j2735_v2x_msgs::msg::AccelerationSet4Way::ACCELERATION_VERTICAL_UNAVAILABLE);
  // Convert Yaw Rate
  out_msg.yaw_rate = ValueConvertor::valueCavToJ2735<int16_t>(
      in_msg.yaw_rate, units::CENTI_DEG_PER_DEG, in_msg.presence_vector,
      carma_v2x_msgs::msg::AccelerationSet4Way::YAWRATE_AVAILABLE, j2735_v2x_msgs::msg::AccelerationSet4Way::YAWRATE_UNAVAILABLE);
}
References j2735_convertor::units::CENTI_DEG_PER_DEG, j2735_convertor::units::CM_PER_M, and j2735_convertor::units::FIFTIETH_G_PER_M_PER_SEC_SQR.
convert() [2/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::AngularVelocity & in_msg, j3224_v2x_msgs::msg::AngularVelocity & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::AngularVelocity into a j3224_v2x_msgs::msg::AngularVelocity.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion of pitch_rate and roll_rate with presence flags handled
Definition at line 618 of file sdsm_convertor.cpp.
{
    convert(in_msg.pitch_rate, out_msg.pitch_rate);
    convert(in_msg.roll_rate, out_msg.roll_rate);
}
References convert().
convert() [3/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::AttachmentRadius & in_msg, j2735_v2x_msgs::msg::AttachmentRadius & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::AttachmentRadius into a j2735_v2x_msgs::msg::AttachmentRadius.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using DECI_M_PER_M
Definition at line 304 of file sdsm_convertor.cpp.
{
    out_msg.attachment_radius = in_msg.attachment_radius * units::DECI_M_PER_M;
}
References j2735_convertor::units::DECI_M_PER_M.
convert() [4/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::Attitude & in_msg, j3224_v2x_msgs::msg::Attitude & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::Attitude into a j3224_v2x_msgs::msg::Attitude.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of pitch, roll, yaw and presence flags are handled
Definition at line 575 of file sdsm_convertor.cpp.
{
    convert(in_msg.pitch, out_msg.pitch);
    convert(in_msg.roll, out_msg.roll);
    convert(in_msg.yaw, out_msg.yaw);
}
References convert().
convert() [5/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::DetectedObjectCommonData & in_msg, j3224_v2x_msgs::msg::DetectedObjectCommonData & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::DetectedObjectCommonData into a j3224_v2x_msgs::msg::DetectedObjectCommonData.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of measurement_time, pos, speed, heading, and presence flags are handled for optional conversions
Definition at line 377 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    convert(in_msg.measurement_time, out_msg.measurement_time);
    convert(in_msg.pos, out_msg.pos);
    convert(in_msg.speed, out_msg.speed);
    convert(in_msg.heading, out_msg.heading);
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedObjectCommonData::HAS_SPEED_Z){
        convert(in_msg.speed_z, out_msg.speed_z);
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedObjectCommonData::HAS_SPEED_CONFIDENCE_Z){
        out_msg.speed_confidence_z = in_msg.speed_confidence_z;
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedObjectCommonData::HAS_ACCEL_4_WAY){
        convert(in_msg.accel_4_way, out_msg.accel_4_way);
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedObjectCommonData::HAS_ACC_CFD_X){
        out_msg.acc_cfd_x = in_msg.acc_cfd_x;
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedObjectCommonData::HAS_ACC_CFD_Y){
        out_msg.acc_cfd_y = in_msg.acc_cfd_y;
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedObjectCommonData::HAS_ACC_CFD_Z){
        out_msg.acc_cfd_z = in_msg.acc_cfd_z;
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedObjectCommonData::HAS_ACC_CFD_YAW){
        out_msg.acc_cfd_yaw = in_msg.acc_cfd_yaw;
    }
    out_msg.obj_type = in_msg.obj_type;
    out_msg.obj_type_cfd = in_msg.obj_type_cfd;
    out_msg.detected_id = in_msg.detected_id;
    out_msg.time_confidence = in_msg.time_confidence;
    out_msg.pos_confidence = in_msg.pos_confidence;
    out_msg.speed_confidence = in_msg.speed_confidence;
    out_msg.heading_conf = in_msg.heading_conf;
}
References convert().
convert() [6/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::DetectedObjectData & in_msg, j3224_v2x_msgs::msg::DetectedObjectData & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::DetectedObjectData into a j3224_v2x_msgs::msg::DetectedObjectData.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Common data conversion setup and presence flag for optional data is handled
Definition at line 325 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    convert(in_msg.detected_object_common_data, out_msg.detected_object_common_data);
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedObjectData::HAS_DETECTED_OBJECT_OPTIONAL_DATA){
        convert(in_msg.detected_object_optional_data, out_msg.detected_object_optional_data);
    }
}
References convert().
convert() [7/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::DetectedObjectOptionalData & in_msg, j3224_v2x_msgs::msg::DetectedObjectOptionalData & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::DetectedObjectOptionalData into a j3224_v2x_msgs::msg::DetectedObjectOptionalData.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Type choice is handled for either det_veh, det_vru, or det_obst
Definition at line 433 of file sdsm_convertor.cpp.
{
    out_msg.choice = in_msg.choice;
    if(in_msg.choice == carma_v2x_msgs::msg::DetectedObjectOptionalData::DET_VEH){
        convert(in_msg.det_veh, out_msg.det_veh);
    }
    if(in_msg.choice == carma_v2x_msgs::msg::DetectedObjectOptionalData::DET_VRU){
        convert(in_msg.det_vru, out_msg.det_vru);
    }
    if(in_msg.choice == carma_v2x_msgs::msg::DetectedObjectOptionalData::DET_OBST){
        convert(in_msg.det_obst, out_msg.det_obst);
    }
}
References convert().
convert() [8/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::DetectedObstacleData & in_msg, j3224_v2x_msgs::msg::DetectedObstacleData & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::DetectedObstacleData into a j3224_v2x_msgs::msg::DetectedObstacleData.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion of size and presence flags are handled
Definition at line 708 of file sdsm_convertor.cpp.
{
    convert(in_msg.obst_size, out_msg.obst_size);
    out_msg.obst_size_confidence = in_msg.obst_size_confidence;
}
References convert().
convert() [9/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::DetectedVehicleData & in_msg, j3224_v2x_msgs::msg::DetectedVehicleData & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::DetectedVehicleData into a j3224_v2x_msgs::msg::DetectedVehicleData.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of veh_attitude, veh_ang_vel, size, height and presence flags are handled
Definition at line 532 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVehicleData::HAS_LIGHTS){
        out_msg.lights.exterior_lights = in_msg.lights.exterior_lights;
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVehicleData::HAS_VEH_ATTITUDE){
        convert(in_msg.veh_attitude, out_msg.veh_attitude);
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVehicleData::HAS_VEH_ATTITUDE_CONFIDENCE){
        out_msg.veh_attitude_confidence = in_msg.veh_attitude_confidence;
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVehicleData::HAS_ANG_VEL){
        convert(in_msg.veh_ang_vel, out_msg.veh_ang_vel);
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVehicleData::HAS_ANG_VEL_CONFIDENCE){
        out_msg.veh_ang_vel_confidence = in_msg.veh_ang_vel_confidence;
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVehicleData::HAS_SIZE){
        convert(in_msg.size, out_msg.size);
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVehicleData::HAS_HEIGHT){
        convert(in_msg.height, out_msg.height);
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVehicleData::HAS_VEHICLE_SIZE_CONFIDENCE){
        out_msg.vehicle_size_confidence = in_msg.vehicle_size_confidence;
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVehicleData::HAS_VEHICLE_CLASS){
        out_msg.vehicle_class = in_msg.vehicle_class;
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVehicleData::HAS_CLASS_CONF){
        out_msg.class_conf = in_msg.class_conf;
    }
}
References convert().
convert() [10/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::DetectedVRUData & in_msg, j3224_v2x_msgs::msg::DetectedVRUData & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::DetectedVRUData into a j3224_v2x_msgs::msg::DetectedVRUData.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion for radius and presence flags are handled
Definition at line 684 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVRUData::HAS_BASIC_TYPE){
        out_msg.basic_type = in_msg.basic_type;
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVRUData::HAS_PROPULSION){
        out_msg.propulsion = in_msg.propulsion;
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVRUData::HAS_ATTACHMENT){
        out_msg.attachment = in_msg.attachment;
    }
    if(in_msg.presence_vector & carma_v2x_msgs::msg::DetectedVRUData::HAS_RADIUS){
        convert(in_msg.radius, out_msg.radius);
    }
}
References convert().
convert() [11/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::Heading & in_msg, j2735_v2x_msgs::msg::Heading & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::Heading into a j2735_v2x_msgs::msg::Heading.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of EIGHTIETH_DEG_PER_DEG
Definition at line 196 of file sdsm_convertor.cpp.
{
    if(!in_msg.unavailable){
        out_msg.heading = in_msg.heading * units::EIGHTIETH_DEG_PER_DEG;
    }
    else{
        out_msg.heading = j2735_v2x_msgs::msg::Heading::HEADING_UNAVAILABLE;
    }
}
References j2735_convertor::units::EIGHTIETH_DEG_PER_DEG.
convert() [12/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::MeasurementTimeOffset & in_msg, j3224_v2x_msgs::msg::MeasurementTimeOffset & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::MeasurementTimeOffset into a j3224_v2x_msgs::msg::MeasurementTimeOffset.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of MS_PER_S
Definition at line 453 of file sdsm_convertor.cpp.
{
    out_msg.measurement_time_offset = in_msg.measurement_time_offset * units::MS_PER_S;
}
References j2735_convertor::units::MS_PER_S.
convert() [13/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::ObjectDistance & in_msg, j3224_v2x_msgs::msg::ObjectDistance & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::ObjectDistance into a j3224_v2x_msgs::msg::ObjectDistance.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of DECI_M_PER_M
Definition at line 491 of file sdsm_convertor.cpp.
{
    out_msg.object_distance = in_msg.object_distance * units::DECI_M_PER_M;
}
References j2735_convertor::units::DECI_M_PER_M.
convert() [14/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::ObstacleSize & in_msg, j3224_v2x_msgs::msg::ObstacleSize & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::ObstacleSize into a j3224_v2x_msgs::msg::ObstacleSize.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion of width and length with presence flags handled
Definition at line 726 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    convert(in_msg.width, out_msg.width);
    convert(in_msg.length, out_msg.length);
    if(in_msg.presence_vector & carma_v2x_msgs::msg::ObstacleSize::HAS_HEIGHT){
        convert(in_msg.height, out_msg.height);
    }
}
References convert().
convert() [15/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::PitchDetected & in_msg, j3224_v2x_msgs::msg::PitchDetected & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::PitchDetected into a j3224_v2x_msgs::msg::PitchDetected.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of EIGHTIETH_DEG_PER_DEG
Definition at line 587 of file sdsm_convertor.cpp.
{
    out_msg.pitch_detected = in_msg.pitch_detected * units::EIGHTIETH_DEG_PER_DEG;
}
References j2735_convertor::units::EIGHTIETH_DEG_PER_DEG.
convert() [16/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::PitchRate & in_msg, j3224_v2x_msgs::msg::PitchRate & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::PitchRate into a j3224_v2x_msgs::msg::PitchRate.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of HUNDREDTH_DEG_PER_S
Definition at line 635 of file sdsm_convertor.cpp.
{
    if(!in_msg.unavailable){
        out_msg.pitch_rate = in_msg.pitch_rate / units::HUNDREDTH_DEG_PER_S;
    }
    else{
        out_msg.pitch_rate = j3224_v2x_msgs::msg::PitchRate::UNAVAILABLE;
    }
}
References j2735_convertor::units::HUNDREDTH_DEG_PER_S.
convert() [17/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::Position3D & in_msg, j2735_v2x_msgs::msg::Position3D & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::Position3D into a j2735_v2x_msgs::msg::Position3D.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of latitude, longitude (TENTH_MICRO_DEGREE), elevation (DECI_M_PER_M) and presence flags are handled
Definition at line 115 of file sdsm_convertor.cpp.
{
    out_msg.latitude = in_msg.latitude * units::TENTH_MICRO_DEG_PER_DEG;
    out_msg.longitude = in_msg.longitude * units::TENTH_MICRO_DEG_PER_DEG;
    if(in_msg.elevation_exists){
        out_msg.elevation_exists = true;
        out_msg.elevation = in_msg.elevation * units::DECI_M_PER_M;
    }
}
References j2735_convertor::units::DECI_M_PER_M, and j2735_convertor::units::TENTH_MICRO_DEG_PER_DEG.
convert() [18/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::PositionalAccuracy & in_msg, j2735_v2x_msgs::msg::PositionalAccuracy & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::PositionalAccuracy into a j2735_v2x_msgs::msg::PositionalAccuracy.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of semi_major/semi_minor axes (TWENTIETH_M_PER_M), orientation (DEG_360_OVER_65535_PER_DEG), and presence flags are handled
Definition at line 145 of file sdsm_convertor.cpp.
{
  // Convert semi_major Axis
  out_msg.semi_major = ValueConvertor::valueCavToJ2735<uint8_t>(
      in_msg.semi_major, units::TWENTIETH_M_PER_M, in_msg.presence_vector,
      carma_v2x_msgs::msg::PositionalAccuracy::ACCURACY_AVAILABLE, j2735_v2x_msgs::msg::PositionalAccuracy::ACCURACY_UNAVAILABLE);
  // Convert semi_minor Axis
  out_msg.semi_minor = ValueConvertor::valueCavToJ2735<uint8_t>(
      in_msg.semi_minor, units::TWENTIETH_M_PER_M, in_msg.presence_vector,
      carma_v2x_msgs::msg::PositionalAccuracy::ACCURACY_AVAILABLE, j2735_v2x_msgs::msg::PositionalAccuracy::ACCURACY_UNAVAILABLE);
  // Convert Orientation
  out_msg.orientation = ValueConvertor::valueCavToJ2735<uint16_t>(
      in_msg.orientation, units::DEG_360_OVER_65535_PER_DEG, in_msg.presence_vector,
      carma_v2x_msgs::msg::PositionalAccuracy::ACCURACY_ORIENTATION_AVAILABLE,
      j2735_v2x_msgs::msg::PositionalAccuracy::ACCURACY_ORIENTATION_UNAVAILABLE);
}
References j2735_convertor::units::DEG_360_OVER_65535_PER_DEG, and j2735_convertor::units::TWENTIETH_M_PER_M.
convert() [19/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::PositionOffsetXYZ & in_msg, j3224_v2x_msgs::msg::PositionOffsetXYZ & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::PositionOffsetXYZ into a j3224_v2x_msgs::msg::PositionOffsetXYZ.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of offset_x, offset_y and presence flag for optional offset_z are handled
Definition at line 472 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    if(in_msg.presence_vector){
        convert(in_msg.offset_x, out_msg.offset_x);
        convert(in_msg.offset_y, out_msg.offset_y);
    }
    if(carma_v2x_msgs::msg::PositionOffsetXYZ::HAS_OFFSET_Z & in_msg.presence_vector){
        convert(in_msg.offset_z, out_msg.offset_z);
    }
}
References convert().
convert() [20/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::RollDetected & in_msg, j3224_v2x_msgs::msg::RollDetected & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::RollDetected into a j3224_v2x_msgs::msg::RollDetected.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of EIGHTIETH_DEG_PER_DEG
Definition at line 597 of file sdsm_convertor.cpp.
{
    out_msg.roll_detected = in_msg.roll_detected * units::EIGHTIETH_DEG_PER_DEG;
}
References j2735_convertor::units::EIGHTIETH_DEG_PER_DEG.
convert() [21/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::RollRate & in_msg, j3224_v2x_msgs::msg::RollRate & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::RollRate into a j3224_v2x_msgs::msg::RollRate.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of HUNDREDTH_DEG_PER_S
Definition at line 656 of file sdsm_convertor.cpp.
{
    if(!in_msg.unavailable){
        out_msg.roll_rate = in_msg.roll_rate / units::HUNDREDTH_DEG_PER_S;
    }
    else{
        out_msg.roll_rate = j3224_v2x_msgs::msg::RollRate::UNAVAILABLE;
    }
}
References j2735_convertor::units::HUNDREDTH_DEG_PER_S.
convert() [22/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::SensorDataSharingMessage & in_msg, j3224_v2x_msgs::msg::SensorDataSharingMessage & out_msg) static
Convert the contents of a carma_v2x_msgs::msg::SensorDataSharingMessage into a j3224_v2x_msgs::msg::SensorDataSharingMessage.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 57 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    convert(in_msg.ref_pos, out_msg.ref_pos);
    convert(in_msg.ref_pos_xy_conf, out_msg.ref_pos_xy_conf);
    if(in_msg.presence_vector & carma_v2x_msgs::msg::SensorDataSharingMessage::HAS_REF_POS_EL_CONF){
        out_msg.ref_pos_el_conf = in_msg.ref_pos_el_conf;
    }
    out_msg.msg_cnt = in_msg.msg_cnt;
    out_msg.source_id = in_msg.source_id;
    out_msg.equipment_type = in_msg.equipment_type;
    out_msg.sdsm_time_stamp = in_msg.sdsm_time_stamp;
    // Create a j3224_v2x_msgs list to copy each detected object into
    j3224_v2x_msgs::msg::DetectedObjectList detected_object_list;
    // Go through the array of carma detected objects and convert their DetectedObjectData
    for(auto in_object : in_msg.objects.detected_object_data){
        j3224_v2x_msgs::msg::DetectedObjectData out_object;
        convert(in_object, out_object);
        // Add the converted object to the j3224_v2x_msgs array
        detected_object_list.detected_object_data.push_back(out_object);
    }
    // Set the placeholder list as the j3224_v2x_msgs output
    out_msg.objects = detected_object_list;
}
References convert().
convert() [23/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::SizeValue & in_msg, j3224_v2x_msgs::msg::SizeValue & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::SizeValue into a j3224_v2x_msgs::msg::SizeValue.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of TEN_CM_PER_M
Definition at line 743 of file sdsm_convertor.cpp.
{
    out_msg.size_value = in_msg.size_value * units::TEN_CM_PER_M;
}
References j2735_convertor::units::TEN_CM_PER_M.
convert() [24/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::Speed & in_msg, j2735_v2x_msgs::msg::Speed & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::Speed into a j2735_v2x_msgs::msg::Speed.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of FIFTIETH_M_PER_M
Definition at line 175 of file sdsm_convertor.cpp.
{
    if(!in_msg.unavailable){
    out_msg.speed = in_msg.speed * units::FIFTIETH_M_PER_M;
    }
    else{
    out_msg.speed = j2735_v2x_msgs::msg::Speed::UNAVAILABLE;
    }
}
References j2735_convertor::units::FIFTIETH_M_PER_M.
convert() [25/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::VehicleHeight & in_msg, j2735_v2x_msgs::msg::VehicleHeight & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::VehicleHeight into a j2735_v2x_msgs::msg::VehicleHeight.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using FIVE_CM_PER_M and presence flag is handled
Definition at line 289 of file sdsm_convertor.cpp.
{
    if(!in_msg.unavailable){
        out_msg.vehicle_height = in_msg.vehicle_height * units::FIVE_CM_PER_M;
    }
    else{
        out_msg.vehicle_height = j2735_v2x_msgs::msg::VehicleHeight::VEHICLE_HEIGHT_UNAVAILABLE;
    }
}
References j2735_convertor::units::FIVE_CM_PER_M.
convert() [26/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::VehicleSize & in_msg, j2735_v2x_msgs::msg::VehicleSize & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::VehicleSize into a j2735_v2x_msgs::msg::VehicleSize.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of vehicle_width and vehicle_length (CM_PER_M) with presence flags handled
Definition at line 265 of file sdsm_convertor.cpp.
{
  // Convert Vehicle Width
  out_msg.vehicle_width = ValueConvertor::valueCavToJ2735<float>(
      in_msg.vehicle_width, units::CM_PER_M, in_msg.presence_vector, carma_v2x_msgs::msg::VehicleSize::VEHICLE_WIDTH_AVAILABLE,
      j2735_v2x_msgs::msg::VehicleSize::VEHICLE_WIDTH_UNAVAILABLE);
  // Convert Vehicle length
  out_msg.vehicle_length = ValueConvertor::valueCavToJ2735<float>(
      in_msg.vehicle_length, units::CM_PER_M, in_msg.presence_vector, carma_v2x_msgs::msg::VehicleSize::VEHICLE_LENGTH_AVAILABLE,
      j2735_v2x_msgs::msg::VehicleSize::VEHICLE_LENGTH_UNAVAILABLE);
}
References j2735_convertor::units::CM_PER_M.
convert() [27/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::YawDetected & in_msg, j3224_v2x_msgs::msg::YawDetected & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::YawDetected into a j3224_v2x_msgs::msg::YawDetected.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of EIGHTIETH_DEG_PER_DEG
Definition at line 607 of file sdsm_convertor.cpp.
{
    out_msg.yaw_detected = in_msg.yaw_detected * units::EIGHTIETH_DEG_PER_DEG;
}
References j2735_convertor::units::EIGHTIETH_DEG_PER_DEG.
convert() [28/56]
void j2735_convertor::SDSMConvertor::convert (const carma_v2x_msgs::msg::YawRate & in_msg, j2735_v2x_msgs::msg::YawRate & out_msg) static private
Convert the contents of a carma_v2x_msgs::msg::YawRate into a j2735_v2x_msgs::msg::YawRate.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of HUNDREDTH_DEG_PER_S
Definition at line 100 of file sdsm_convertor.cpp.
{
    out_msg.yaw_rate = in_msg.yaw_rate / units::HUNDREDTH_DEG_PER_S;
}
References j2735_convertor::units::HUNDREDTH_DEG_PER_S.
convert() [29/56]
void j2735_convertor::SDSMConvertor::convert (const j2735_v2x_msgs::msg::AccelerationSet4Way & in_msg, carma_v2x_msgs::msg::AccelerationSet4Way & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::AccelerationSet4Way into a carma_v2x_msgs::msg::AccelerationSet4Way.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of logitudinal (CM_PER_M), lateral (CM_PER_M), and vert (FIFTIETH_G_PER_M_PER_SEC_SQUARED) acceleration plus yaw rate (CENTI_DEG_PER_DEG) and presence flags are handled
Definition at line 207 of file sdsm_convertor.cpp.
{
  // Convert Longitudinal and Lateral
  out_msg.longitudinal = ValueConvertor::valueJ2735ToCav<float>(
      in_msg.longitudinal, units::CM_PER_M, out_msg.presence_vector,
      carma_v2x_msgs::msg::AccelerationSet4Way::ACCELERATION_AVAILABLE, j2735_v2x_msgs::msg::AccelerationSet4Way::ACCELERATION_UNAVAILABLE);
  out_msg.lateral = ValueConvertor::valueJ2735ToCav<float>(
      in_msg.lateral, units::CM_PER_M, out_msg.presence_vector,
      carma_v2x_msgs::msg::AccelerationSet4Way::ACCELERATION_AVAILABLE, j2735_v2x_msgs::msg::AccelerationSet4Way::ACCELERATION_UNAVAILABLE);
  // Convert Vertical
  out_msg.vert = ValueConvertor::valueJ2735ToCav<float>(
      in_msg.vert, units::FIFTIETH_G_PER_M_PER_SEC_SQR, out_msg.presence_vector,
      carma_v2x_msgs::msg::AccelerationSet4Way::ACCELERATION_VERTICAL_AVAILABLE,
      j2735_v2x_msgs::msg::AccelerationSet4Way::ACCELERATION_VERTICAL_UNAVAILABLE);
  // Convert Yaw Rate
  out_msg.yaw_rate = ValueConvertor::valueJ2735ToCav<float>(
      in_msg.yaw_rate, units::CENTI_DEG_PER_DEG, out_msg.presence_vector,
      carma_v2x_msgs::msg::AccelerationSet4Way::YAWRATE_AVAILABLE, j2735_v2x_msgs::msg::AccelerationSet4Way::YAWRATE_UNAVAILABLE);
}
References j2735_convertor::units::CENTI_DEG_PER_DEG, j2735_convertor::units::CM_PER_M, and j2735_convertor::units::FIFTIETH_G_PER_M_PER_SEC_SQR.
convert() [30/56]
void j2735_convertor::SDSMConvertor::convert (const j2735_v2x_msgs::msg::AttachmentRadius & in_msg, carma_v2x_msgs::msg::AttachmentRadius & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::AttachmentRadius into a carma_v2x_msgs::msg::AttachmentRadius.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using DECI_M_PER_M
Definition at line 300 of file sdsm_convertor.cpp.
{
    out_msg.attachment_radius = in_msg.attachment_radius / units::DECI_M_PER_M;
}
References j2735_convertor::units::DECI_M_PER_M.
convert() [31/56]
void j2735_convertor::SDSMConvertor::convert (const j2735_v2x_msgs::msg::Heading & in_msg, carma_v2x_msgs::msg::Heading & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::Heading into a carma_v2x_msgs::msg::Heading.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of EIGHTIETH_DEG_PER_DEG
Definition at line 186 of file sdsm_convertor.cpp.
{
    if(in_msg.heading != j2735_v2x_msgs::msg::Heading::HEADING_UNAVAILABLE){
        out_msg.unavailable = false;
        out_msg.heading = in_msg.heading / units::EIGHTIETH_DEG_PER_DEG;
    }
    else{
        out_msg.unavailable = true;
    }
}
References j2735_convertor::units::EIGHTIETH_DEG_PER_DEG.
convert() [32/56]
void j2735_convertor::SDSMConvertor::convert (const j2735_v2x_msgs::msg::Position3D & in_msg, carma_v2x_msgs::msg::Position3D & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::Position3D into a carma_v2x_msgs::msg::Position3D.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of latitude, longitude (TENTH_MICRO_DEGREE), elevation (DECI_M_PER_M) and presence flags are handled
Definition at line 106 of file sdsm_convertor.cpp.
{
    out_msg.latitude = in_msg.latitude / units::TENTH_MICRO_DEG_PER_DEG;
    out_msg.longitude = in_msg.longitude / units::TENTH_MICRO_DEG_PER_DEG;
    if(in_msg.elevation_exists){
        out_msg.elevation_exists = true;
        out_msg.elevation = in_msg.elevation / units::DECI_M_PER_M;
    }
}
References j2735_convertor::units::DECI_M_PER_M, and j2735_convertor::units::TENTH_MICRO_DEG_PER_DEG.
convert() [33/56]
void j2735_convertor::SDSMConvertor::convert (const j2735_v2x_msgs::msg::PositionalAccuracy & in_msg, carma_v2x_msgs::msg::PositionalAccuracy & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::PositionalAccuracy into a carma_v2x_msgs::msg::PositionalAccuracy.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of semi_major/semi_minor axes (TWENTIETH_M_PER_M), orientation (DEG_360_OVER_65535_PER_DEG), and presence flags are handled
Definition at line 127 of file sdsm_convertor.cpp.
{
  // Convert semi_major Axis
  out_msg.semi_major = ValueConvertor::valueJ2735ToCav<float>(
      in_msg.semi_major, units::TWENTIETH_M_PER_M, out_msg.presence_vector,
      carma_v2x_msgs::msg::PositionalAccuracy::ACCURACY_AVAILABLE, j2735_v2x_msgs::msg::PositionalAccuracy::ACCURACY_UNAVAILABLE);
  // Convert semi_minor Axis
  out_msg.semi_minor = ValueConvertor::valueJ2735ToCav<float>(
      in_msg.semi_minor, units::TWENTIETH_M_PER_M, out_msg.presence_vector,
      carma_v2x_msgs::msg::PositionalAccuracy::ACCURACY_AVAILABLE, j2735_v2x_msgs::msg::PositionalAccuracy::ACCURACY_UNAVAILABLE);
  // Convert Orientation
  out_msg.orientation = ValueConvertor::valueJ2735ToCav<double>(
      in_msg.orientation, units::DEG_360_OVER_65535_PER_DEG, out_msg.presence_vector,
      carma_v2x_msgs::msg::PositionalAccuracy::ACCURACY_ORIENTATION_AVAILABLE,
      j2735_v2x_msgs::msg::PositionalAccuracy::ACCURACY_ORIENTATION_UNAVAILABLE);
}
References j2735_convertor::units::DEG_360_OVER_65535_PER_DEG, and j2735_convertor::units::TWENTIETH_M_PER_M.
convert() [34/56]
void j2735_convertor::SDSMConvertor::convert (const j2735_v2x_msgs::msg::Speed & in_msg, carma_v2x_msgs::msg::Speed & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::Speed into a carma_v2x_msgs::msg::Speed.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of FIFTIETH_M_PER_M
Definition at line 165 of file sdsm_convertor.cpp.
{
    if(in_msg.speed != j2735_v2x_msgs::msg::Speed::UNAVAILABLE){
        out_msg.unavailable = false;
        out_msg.speed = in_msg.speed / units::FIFTIETH_M_PER_M;
    }
    else{
        out_msg.unavailable = true;
    }
}
References j2735_convertor::units::FIFTIETH_M_PER_M.
convert() [35/56]
void j2735_convertor::SDSMConvertor::convert (const j2735_v2x_msgs::msg::VehicleHeight & in_msg, carma_v2x_msgs::msg::VehicleHeight & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::VehicleHeight into a carma_v2x_msgs::msg::VehicleHeight.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using FIVE_CM_PER_M and presence flag is handled
Definition at line 279 of file sdsm_convertor.cpp.
{
    if(in_msg.vehicle_height != j2735_v2x_msgs::msg::VehicleHeight::VEHICLE_HEIGHT_UNAVAILABLE){
        out_msg.unavailable = false;
        out_msg.vehicle_height = in_msg.vehicle_height / units::FIVE_CM_PER_M;
    }
    else{
        out_msg.unavailable = true;
    }
}
References j2735_convertor::units::FIVE_CM_PER_M.
convert() [36/56]
void j2735_convertor::SDSMConvertor::convert (const j2735_v2x_msgs::msg::VehicleSize & in_msg, carma_v2x_msgs::msg::VehicleSize & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::VehicleSize into a carma_v2x_msgs::msg::VehicleSize.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of vehicle_width and vehicle_length (CM_PER_M) with presence flags handled
Definition at line 253 of file sdsm_convertor.cpp.
{
  // Convert Vehicle Width
  out_msg.vehicle_width = ValueConvertor::valueJ2735ToCav<float>(
      in_msg.vehicle_width, units::CM_PER_M, out_msg.presence_vector, carma_v2x_msgs::msg::VehicleSize::VEHICLE_WIDTH_AVAILABLE,
      j2735_v2x_msgs::msg::VehicleSize::VEHICLE_WIDTH_UNAVAILABLE);
  // Convert Vehicle length
  out_msg.vehicle_length = ValueConvertor::valueJ2735ToCav<float>(
      in_msg.vehicle_length, units::CM_PER_M, out_msg.presence_vector, carma_v2x_msgs::msg::VehicleSize::VEHICLE_LENGTH_AVAILABLE,
      j2735_v2x_msgs::msg::VehicleSize::VEHICLE_LENGTH_UNAVAILABLE);
}
References j2735_convertor::units::CM_PER_M.
convert() [37/56]
void j2735_convertor::SDSMConvertor::convert (const j2735_v2x_msgs::msg::YawRate & in_msg, carma_v2x_msgs::msg::YawRate & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::YawRate into a carma_v2x_msgs::msg::YawRate.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of HUNDREDTH_DEG_PER_S
Definition at line 96 of file sdsm_convertor.cpp.
{
    out_msg.yaw_rate = in_msg.yaw_rate * units::HUNDREDTH_DEG_PER_S;
}
References j2735_convertor::units::HUNDREDTH_DEG_PER_S.
convert() [38/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::AngularVelocity & in_msg, carma_v2x_msgs::msg::AngularVelocity & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::AngularVelocity into a carma_v2x_msgs::msg::AngularVelocity.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion of pitch_rate and roll_rate with presence flags handled
Definition at line 613 of file sdsm_convertor.cpp.
{
    convert(in_msg.pitch_rate, out_msg.pitch_rate);
    convert(in_msg.roll_rate, out_msg.roll_rate);
}
References convert().
convert() [39/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::Attitude & in_msg, carma_v2x_msgs::msg::Attitude & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::Attitude into a carma_v2x_msgs::msg::Attitude.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of pitch, roll, yaw and presence flags are handled
Definition at line 569 of file sdsm_convertor.cpp.
{
    convert(in_msg.pitch, out_msg.pitch);
    convert(in_msg.roll, out_msg.roll);
    convert(in_msg.yaw, out_msg.yaw);
}
References convert().
convert() [40/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::DetectedObjectCommonData & in_msg, carma_v2x_msgs::msg::DetectedObjectCommonData & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::DetectedObjectCommonData into a carma_v2x_msgs::msg::DetectedObjectCommonData.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of measurement_time, pos, speed, heading, and presence flags are handled for optional conversions
Definition at line 337 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    convert(in_msg.measurement_time, out_msg.measurement_time);
    convert(in_msg.pos, out_msg.pos);
    convert(in_msg.speed, out_msg.speed);
    convert(in_msg.heading, out_msg.heading);
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedObjectCommonData::HAS_SPEED_Z){
        convert(in_msg.speed_z, out_msg.speed_z);
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedObjectCommonData::HAS_SPEED_CONFIDENCE_Z){
        out_msg.speed_confidence_z = in_msg.speed_confidence_z;
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedObjectCommonData::HAS_ACCEL_4_WAY){
        convert(in_msg.accel_4_way, out_msg.accel_4_way);
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedObjectCommonData::HAS_ACC_CFD_X){
        out_msg.acc_cfd_x = in_msg.acc_cfd_x;
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedObjectCommonData::HAS_ACC_CFD_Y){
        out_msg.acc_cfd_y = in_msg.acc_cfd_y;
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedObjectCommonData::HAS_ACC_CFD_Z){
        out_msg.acc_cfd_z = in_msg.acc_cfd_z;
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedObjectCommonData::HAS_ACC_CFD_YAW){
        out_msg.acc_cfd_yaw = in_msg.acc_cfd_yaw;
    }
    out_msg.obj_type = in_msg.obj_type;
    out_msg.obj_type_cfd = in_msg.obj_type_cfd;
    out_msg.detected_id = in_msg.detected_id;
    out_msg.time_confidence = in_msg.time_confidence;
    out_msg.pos_confidence = in_msg.pos_confidence;
    out_msg.speed_confidence = in_msg.speed_confidence;
    out_msg.heading_conf = in_msg.heading_conf;
}
References convert().
convert() [41/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::DetectedObjectData & in_msg, carma_v2x_msgs::msg::DetectedObjectData & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::DetectedObjectData into a carma_v2x_msgs::msg::DetectedObjectData.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Common data conversion setup and presence flag for optional data is handled
Definition at line 315 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    convert(in_msg.detected_object_common_data, out_msg.detected_object_common_data);
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedObjectData::HAS_DETECTED_OBJECT_OPTIONAL_DATA){
        convert(in_msg.detected_object_optional_data, out_msg.detected_object_optional_data);
    }
}
References convert().
convert() [42/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::DetectedObjectOptionalData & in_msg, carma_v2x_msgs::msg::DetectedObjectOptionalData & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::DetectedObjectOptionalData into a carma_v2x_msgs::msg::DetectedObjectOptionalData.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Type choice is handled for either det_veh, det_vru, or det_obst
Definition at line 418 of file sdsm_convertor.cpp.
{
    out_msg.choice = in_msg.choice;
    if(in_msg.choice == j3224_v2x_msgs::msg::DetectedObjectOptionalData::DET_VEH){
        convert(in_msg.det_veh, out_msg.det_veh);
    }
    if(in_msg.choice == j3224_v2x_msgs::msg::DetectedObjectOptionalData::DET_VRU){
        convert(in_msg.det_vru, out_msg.det_vru);
    }
    if(in_msg.choice == j3224_v2x_msgs::msg::DetectedObjectOptionalData::DET_OBST){
        convert(in_msg.det_obst, out_msg.det_obst);
    }
}
References convert().
convert() [43/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::DetectedObstacleData & in_msg, carma_v2x_msgs::msg::DetectedObstacleData & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::DetectedObstacleData into a carma_v2x_msgs::msg::DetectedObstacleData.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion of size and presence flags are handled
Definition at line 703 of file sdsm_convertor.cpp.
{
    convert(in_msg.obst_size, out_msg.obst_size);
    out_msg.obst_size_confidence = in_msg.obst_size_confidence;
}
References convert().
convert() [44/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::DetectedVehicleData & in_msg, carma_v2x_msgs::msg::DetectedVehicleData & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::DetectedVehicleData into a carma_v2x_msgs::msg::DetectedVehicleData.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of veh_attitude, veh_ang_vel, size, height and presence flags are handled
Definition at line 497 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVehicleData::HAS_LIGHTS){
        out_msg.lights.exterior_lights = in_msg.lights.exterior_lights;
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVehicleData::HAS_VEH_ATTITUDE){
        convert(in_msg.veh_attitude, out_msg.veh_attitude);
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVehicleData::HAS_VEH_ATTITUDE_CONFIDENCE){
        out_msg.veh_attitude_confidence = in_msg.veh_attitude_confidence;
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVehicleData::HAS_ANG_VEL){
        convert(in_msg.veh_ang_vel, out_msg.veh_ang_vel);
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVehicleData::HAS_ANG_VEL_CONFIDENCE){
        out_msg.veh_ang_vel_confidence = in_msg.veh_ang_vel_confidence;
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVehicleData::HAS_SIZE){
        convert(in_msg.size, out_msg.size);
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVehicleData::HAS_HEIGHT){
        convert(in_msg.height, out_msg.height);
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVehicleData::HAS_VEHICLE_SIZE_CONFIDENCE){
        out_msg.vehicle_size_confidence = in_msg.vehicle_size_confidence;
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVehicleData::HAS_VEHICLE_CLASS){
        out_msg.vehicle_class = in_msg.vehicle_class;
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVehicleData::HAS_CLASS_CONF){
        out_msg.class_conf = in_msg.class_conf;
    }
}
References convert().
convert() [45/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::DetectedVRUData & in_msg, carma_v2x_msgs::msg::DetectedVRUData & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::DetectedVRUData into a carma_v2x_msgs::msg::DetectedVRUData.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion for radius and presence flags are handled
Definition at line 667 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVRUData::HAS_BASIC_TYPE){
        out_msg.basic_type = in_msg.basic_type;
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVRUData::HAS_PROPULSION){
        out_msg.propulsion = in_msg.propulsion;
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVRUData::HAS_ATTACHMENT){
        out_msg.attachment = in_msg.attachment;
    }
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::DetectedVRUData::HAS_RADIUS){
        convert(in_msg.radius, out_msg.radius);
    }
}
References convert().
convert() [46/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::MeasurementTimeOffset & in_msg, carma_v2x_msgs::msg::MeasurementTimeOffset & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::MeasurementTimeOffset into a carma_v2x_msgs::msg::MeasurementTimeOffset.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of MS_PER_S
Definition at line 449 of file sdsm_convertor.cpp.
{
    out_msg.measurement_time_offset = in_msg.measurement_time_offset / units::MS_PER_S;
}
References j2735_convertor::units::MS_PER_S.
convert() [47/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::ObjectDistance & in_msg, carma_v2x_msgs::msg::ObjectDistance & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::ObjectDistance into a carma_v2x_msgs::msg::ObjectDistance.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of DECI_M_PER_M
Definition at line 487 of file sdsm_convertor.cpp.
{
    out_msg.object_distance = in_msg.object_distance / units::DECI_M_PER_M;
}
References j2735_convertor::units::DECI_M_PER_M.
convert() [48/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::ObstacleSize & in_msg, carma_v2x_msgs::msg::ObstacleSize & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::ObstacleSize into a carma_v2x_msgs::msg::ObstacleSize.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion of width and length with presence flags handled
Definition at line 715 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    convert(in_msg.width, out_msg.width);
    convert(in_msg.length, out_msg.length);
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::ObstacleSize::HAS_HEIGHT){
        convert(in_msg.height, out_msg.height);
    }
}
References convert().
convert() [49/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::PitchDetected & in_msg, carma_v2x_msgs::msg::PitchDetected & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::PitchDetected into a carma_v2x_msgs::msg::PitchDetected.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of EIGHTIETH_DEG_PER_DEG
Definition at line 583 of file sdsm_convertor.cpp.
{
    out_msg.pitch_detected = in_msg.pitch_detected / units::EIGHTIETH_DEG_PER_DEG;
}
References j2735_convertor::units::EIGHTIETH_DEG_PER_DEG.
convert() [50/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::PitchRate & in_msg, carma_v2x_msgs::msg::PitchRate & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::PitchRate into a carma_v2x_msgs::msg::PitchRate.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of HUNDREDTH_DEG_PER_S
Definition at line 625 of file sdsm_convertor.cpp.
{
    if(in_msg.pitch_rate != j3224_v2x_msgs::msg::PitchRate::UNAVAILABLE){
        out_msg.unavailable = false;
        out_msg.pitch_rate = in_msg.pitch_rate * units::HUNDREDTH_DEG_PER_S;
    }
    else{
        out_msg.unavailable = true;
    }
}
References j2735_convertor::units::HUNDREDTH_DEG_PER_S.
convert() [51/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::PositionOffsetXYZ & in_msg, carma_v2x_msgs::msg::PositionOffsetXYZ & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::PositionOffsetXYZ into a carma_v2x_msgs::msg::PositionOffsetXYZ.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions of offset_x, offset_y and presence flag for optional offset_z are handled
Definition at line 459 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    if(in_msg.presence_vector){
        convert(in_msg.offset_x, out_msg.offset_x);
        convert(in_msg.offset_y, out_msg.offset_y);
    }
    if(j3224_v2x_msgs::msg::PositionOffsetXYZ::HAS_OFFSET_Z & in_msg.presence_vector){
        convert(in_msg.offset_z, out_msg.offset_z);
    }
}
References convert().
convert() [52/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::RollDetected & in_msg, carma_v2x_msgs::msg::RollDetected & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::RollDetected into a carma_v2x_msgs::msg::RollDetected.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of EIGHTIETH_DEG_PER_DEG
Definition at line 593 of file sdsm_convertor.cpp.
{
    out_msg.roll_detected = in_msg.roll_detected / units::EIGHTIETH_DEG_PER_DEG;
}
References j2735_convertor::units::EIGHTIETH_DEG_PER_DEG.
convert() [53/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::RollRate & in_msg, carma_v2x_msgs::msg::RollRate & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::RollRate into a carma_v2x_msgs::msg::RollRate.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of HUNDREDTH_DEG_PER_S
Definition at line 646 of file sdsm_convertor.cpp.
{
    if(in_msg.roll_rate != j3224_v2x_msgs::msg::RollRate::UNAVAILABLE){
        out_msg.unavailable = false;
        out_msg.roll_rate = in_msg.roll_rate * units::HUNDREDTH_DEG_PER_S;
    }
    else{
        out_msg.unavailable = true;
    }
}
References j2735_convertor::units::HUNDREDTH_DEG_PER_S.
convert() [54/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::SensorDataSharingMessage & in_msg, carma_v2x_msgs::msg::SensorDataSharingMessage & out_msg) static
Convert the contents of a j3224_v2x_msgs::msg::SensorDataSharingMessage into a carma_v2x_msgs::msg::SensorDataSharingMessage.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 26 of file sdsm_convertor.cpp.
{
    out_msg.presence_vector |= in_msg.presence_vector;
    convert(in_msg.ref_pos, out_msg.ref_pos);
    convert(in_msg.ref_pos_xy_conf, out_msg.ref_pos_xy_conf);
    if(in_msg.presence_vector & j3224_v2x_msgs::msg::SensorDataSharingMessage::HAS_REF_POS_EL_CONF){
        out_msg.ref_pos_el_conf = in_msg.ref_pos_el_conf;
    }
    out_msg.msg_cnt = in_msg.msg_cnt;
    out_msg.source_id = in_msg.source_id;
    out_msg.equipment_type = in_msg.equipment_type;
    out_msg.sdsm_time_stamp = in_msg.sdsm_time_stamp;
    // Create a carma_v2x_msgs list to copy each detected object into
    carma_v2x_msgs::msg::DetectedObjectList detected_object_list;
    // Go through the array of j3224 detected objects and convert their DetectedObjectData
    for(auto in_object : in_msg.objects.detected_object_data){
        carma_v2x_msgs::msg::DetectedObjectData out_object;
        convert(in_object, out_object);
        // Add the converted object to the carma_v2x_msgs array
        detected_object_list.detected_object_data.push_back(out_object);
    }
    // Set the placeholder list as the carma_v2x_msgs output
    out_msg.objects = detected_object_list;
}
References convert().
Referenced by convert(), j2735_convertor::Node::j3224SdsmHandler(), and j2735_convertor::Node::SdsmHandler().
convert() [55/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::SizeValue & in_msg, carma_v2x_msgs::msg::SizeValue & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::SizeValue into a carma_v2x_msgs::msg::SizeValue.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of TEN_CM_PER_M
Definition at line 739 of file sdsm_convertor.cpp.
{
    out_msg.size_value = in_msg.size_value / units::TEN_CM_PER_M;
}
References j2735_convertor::units::TEN_CM_PER_M.
convert() [56/56]
void j2735_convertor::SDSMConvertor::convert (const j3224_v2x_msgs::msg::YawDetected & in_msg, carma_v2x_msgs::msg::YawDetected & out_msg) static private
Convert the contents of a j3224_v2x_msgs::msg::YawDetected into a carma_v2x_msgs::msg::YawDetected.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversion using units of EIGHTIETH_DEG_PER_DEG
Definition at line 603 of file sdsm_convertor.cpp.
{
    out_msg.yaw_detected = in_msg.yaw_detected / units::EIGHTIETH_DEG_PER_DEG;
}
References j2735_convertor::units::EIGHTIETH_DEG_PER_DEG.
The documentation for this class was generated from the following files:
carma-messenger-core/j2735_convertor/include/j2735_convertor/sdsm_convertor.hpp
carma-messenger-core/j2735_convertor/src/sdsm_convertor.cpp