Carma-platform: traffic::TrafficIncidentNode Class Reference
traffic::TrafficIncidentNode Class Reference
#include <traffic_incident_node.hpp>
Public Member Functions
TrafficIncidentNode (const rclcpp::NodeOptions &)
TrafficIncidentNode constructor.
void publishTrafficIncidentMobilityOperation (const carma_v2x_msgs::msg::MobilityOperation &traffic_msg)
Publish mobility operation message.
bool startTrafficBroadcastCallback (const std::shared_ptr< rmw_request_id_t >, const carma_msgs::srv::SetTrafficEvent::Request::SharedPtr req, carma_msgs::srv::SetTrafficEvent::Response::SharedPtr resp)
bool stopTrafficBroadcastCallback (const std::shared_ptr< rmw_request_id_t >, const std_srvs::srv::Trigger::Request::SharedPtr req, std_srvs::srv::Trigger::Response::SharedPtr resp)
Private Member Functions
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &)
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &)
void spin_callback (void)
Private Attributes
carma_ros2_utils::SubPtr< gps_msgs::msg::GPSFix > pinpoint_driver_sub_
carma_ros2_utils::PubPtr< carma_v2x_msgs::msg::MobilityOperation > traffic_mobility_operation_pub_
carma_ros2_utils::ServicePtr< carma_msgs::srv::SetTrafficEvent > start_broadcast_request_service_server
carma_ros2_utils::ServicePtr< std_srvs::srv::Trigger > stop_broadcast_request_service_server
rclcpp::TimerBase::SharedPtr spin_timer_
TrafficIncidentWorker traffic_worker_
std::string sender_id_
std::string event_reason_
std::string event_type_
double down_track_
double up_track_
double min_gap_
Detailed Description
Definition at line 34 of file traffic_incident_node.hpp.
Constructor & Destructor Documentation
TrafficIncidentNode()
traffic::TrafficIncidentNode::TrafficIncidentNode (const rclcpp::NodeOptions & options) explicit
TrafficIncidentNode constructor.
Definition at line 23 of file traffic_incident_node.cpp.
: carma_ros2_utils::CarmaLifecycleNode(options),
  traffic_worker_(
    std::bind(&TrafficIncidentNode::publishTrafficIncidentMobilityOperation, this, std_ph::_1))
{
  declare_parameter<std::string>("sender_id", sender_id_);
  declare_parameter<std::string>("event_reason", event_reason_);
  declare_parameter<std::string>("event_type", event_type_);
  declare_parameter<double>("down_track", down_track_);
  declare_parameter<double>("up_track", up_track_);
  declare_parameter<double>("min_gap", min_gap_);
}
References down_track_, event_reason_, event_type_, min_gap_, sender_id_, and up_track_.
Member Function Documentation
handle_on_activate()
carma_ros2_utils::CallbackReturn traffic::TrafficIncidentNode::handle_on_activate (const rclcpp_lifecycle::State &) private
Definition at line 82 of file traffic_incident_node.cpp.
{
  // spin loop
  spin_timer_ = create_timer(
    get_clock(),
    std::chrono::milliseconds(100),
    std::bind(&TrafficIncidentNode::spin_callback, this));
  RCLCPP_INFO_STREAM(get_logger(), "Traffic Incident node is initialized...");
  return CallbackReturn::SUCCESS;
}
References spin_callback(), and spin_timer_.
handle_on_configure()
carma_ros2_utils::CallbackReturn traffic::TrafficIncidentNode::handle_on_configure (const rclcpp_lifecycle::State &) private
Definition at line 36 of file traffic_incident_node.cpp.
{
  get_parameter<std::string>("sender_id", sender_id_);
  get_parameter<std::string>("event_reason", event_reason_);
  get_parameter<std::string>("event_type", event_type_);
  get_parameter<double>("down_track", down_track_);
  get_parameter<double>("up_track", up_track_);
  get_parameter<double>("min_gap", min_gap_);
  traffic_worker_.setSenderId(sender_id_);
  traffic_worker_.setDownTrack(down_track_);
  traffic_worker_.setUpTrack(up_track_);
  traffic_worker_.setMinGap(min_gap_);
  traffic_worker_.setEventReason(event_reason_);
  traffic_worker_.setEventType(event_type_);
  // Setup pub/sub
  pinpoint_driver_sub_ = create_subscription<gps_msgs::msg::GPSFix>(
    "gps_common_fix",
    10,
    std::bind(&TrafficIncidentWorker::pinpointDriverCallback, &traffic_worker_, std_ph::_1));
  traffic_mobility_operation_pub_ =
    create_publisher<carma_v2x_msgs::msg::MobilityOperation>("outgoing_mobility_operation", 10);
  // setup services
  start_broadcast_request_service_server = create_service<carma_msgs::srv::SetTrafficEvent>(
    "start_broadcasting_traffic_event",
    std::bind(
      &TrafficIncidentNode::startTrafficBroadcastCallback,
      this,
      std_ph::_1,
      std_ph::_2,
      std_ph::_3));
  stop_broadcast_request_service_server = create_service<std_srvs::srv::Trigger>(
    "stop_broadcasting_traffic_event",
    std::bind(
      &TrafficIncidentNode::stopTrafficBroadcastCallback,
      this,
      std_ph::_1,
      std_ph::_2,
      std_ph::_3));
  return CallbackReturn::SUCCESS;
}
References down_track_, event_reason_, event_type_, min_gap_, pinpoint_driver_sub_, traffic::TrafficIncidentWorker::pinpointDriverCallback(), sender_id_, traffic::TrafficIncidentWorker::setDownTrack(), traffic::TrafficIncidentWorker::setEventReason(), traffic::TrafficIncidentWorker::setEventType(), traffic::TrafficIncidentWorker::setMinGap(), traffic::TrafficIncidentWorker::setSenderId(), traffic::TrafficIncidentWorker::setUpTrack(), start_broadcast_request_service_server, startTrafficBroadcastCallback(), stop_broadcast_request_service_server, stopTrafficBroadcastCallback(), traffic_mobility_operation_pub_, traffic_worker_, and up_track_.
publishTrafficIncidentMobilityOperation()
void traffic::TrafficIncidentNode::publishTrafficIncidentMobilityOperation (const carma_v2x_msgs::msg::MobilityOperation & traffic_msg)
Publish mobility operation message.
Definition at line 94 of file traffic_incident_node.cpp.
{
  traffic_mobility_operation_pub_->publish(traffic_msg);
}
References traffic_mobility_operation_pub_.
spin_callback()
void traffic::TrafficIncidentNode::spin_callback (void) private
Definition at line 150 of file traffic_incident_node.cpp.
{
  if (
    traffic_worker_.getDownTrack() > 0 && traffic_worker_.getUpTrack() > 0 &&
    traffic_worker_.getMinGap() > 0 && traffic_worker_.getAdvisorySpeed() > 0) {
    // construct local mobilityOperation msg
    carma_v2x_msgs::msg::MobilityOperation traffic_mobility_msg =
      traffic_worker_.mobilityMessageGenerator(traffic_worker_.getPinPoint());
    // start constantly broadcasting mobilityOperation msg
    traffic_mobility_operation_pub_->publish(traffic_mobility_msg);
  }
}
References traffic::TrafficIncidentWorker::getAdvisorySpeed(), traffic::TrafficIncidentWorker::getDownTrack(), traffic::TrafficIncidentWorker::getMinGap(), traffic::TrafficIncidentWorker::getPinPoint(), traffic::TrafficIncidentWorker::getUpTrack(), traffic::TrafficIncidentWorker::mobilityMessageGenerator(), traffic_mobility_operation_pub_, and traffic_worker_.
Referenced by handle_on_activate().
startTrafficBroadcastCallback()
bool traffic::TrafficIncidentNode::startTrafficBroadcastCallback (const std::shared_ptr< rmw_request_id_t > , const carma_msgs::srv::SetTrafficEvent::Request::SharedPtr req, carma_msgs::srv::SetTrafficEvent::Response::SharedPtr resp)
Definition at line 105 of file traffic_incident_node.cpp.
{
  // update instance variables with incoming request params
  traffic_worker_.setMinGap(req->minimum_gap);
  traffic_worker_.setDownTrack(req->down_track);
  traffic_worker_.setUpTrack(req->up_track);
  traffic_worker_.setAdvisorySpeed(req->advisory_speed);
  // return service response true
  resp->success = true;
  return true;
}
References traffic::TrafficIncidentWorker::setAdvisorySpeed(), traffic::TrafficIncidentWorker::setDownTrack(), traffic::TrafficIncidentWorker::setMinGap(), traffic::TrafficIncidentWorker::setUpTrack(), and traffic_worker_.
Referenced by handle_on_configure().
stopTrafficBroadcastCallback()
bool traffic::TrafficIncidentNode::stopTrafficBroadcastCallback (const std::shared_ptr< rmw_request_id_t > , const std_srvs::srv::Trigger::Request::SharedPtr req, std_srvs::srv::Trigger::Response::SharedPtr resp)
Definition at line 125 of file traffic_incident_node.cpp.
{
  try {
    // reset instance variables
    traffic_worker_.setMinGap(0);
    traffic_worker_.setDownTrack(0);
    traffic_worker_.setUpTrack(0);
    traffic_worker_.setAdvisorySpeed(0);
    resp->success = true;
    resp->message = "stop broadcasting";
    // return service response true
    return true;
  } catch (...) {
    // in case any exception
    resp->success = false;
    return false;
  }
}
References traffic::TrafficIncidentWorker::setAdvisorySpeed(), traffic::TrafficIncidentWorker::setDownTrack(), traffic::TrafficIncidentWorker::setMinGap(), traffic::TrafficIncidentWorker::setUpTrack(), and traffic_worker_.
Referenced by handle_on_configure().
Member Data Documentation
down_track_
double traffic::TrafficIncidentNode::down_track_ private
Definition at line 86 of file traffic_incident_node.hpp.
Referenced by TrafficIncidentNode(), and handle_on_configure().
event_reason_
std::string traffic::TrafficIncidentNode::event_reason_ private
Definition at line 84 of file traffic_incident_node.hpp.
Referenced by TrafficIncidentNode(), and handle_on_configure().
event_type_
std::string traffic::TrafficIncidentNode::event_type_ private
Definition at line 85 of file traffic_incident_node.hpp.
Referenced by TrafficIncidentNode(), and handle_on_configure().
min_gap_
double traffic::TrafficIncidentNode::min_gap_ private
Definition at line 88 of file traffic_incident_node.hpp.
Referenced by TrafficIncidentNode(), and handle_on_configure().
pinpoint_driver_sub_
carma_ros2_utils::SubPtr<gps_msgs::msg::GPSFix> traffic::TrafficIncidentNode::pinpoint_driver_sub_ private
Definition at line 66 of file traffic_incident_node.hpp.
Referenced by handle_on_configure().
sender_id_
std::string traffic::TrafficIncidentNode::sender_id_ private
Definition at line 83 of file traffic_incident_node.hpp.
Referenced by TrafficIncidentNode(), and handle_on_configure().
spin_timer_
rclcpp::TimerBase::SharedPtr traffic::TrafficIncidentNode::spin_timer_ private
Definition at line 77 of file traffic_incident_node.hpp.
Referenced by handle_on_activate().
start_broadcast_request_service_server
carma_ros2_utils::ServicePtr<carma_msgs::srv::SetTrafficEvent> traffic::TrafficIncidentNode::start_broadcast_request_service_server private
Definition at line 73 of file traffic_incident_node.hpp.
Referenced by handle_on_configure().
stop_broadcast_request_service_server
carma_ros2_utils::ServicePtr<std_srvs::srv::Trigger> traffic::TrafficIncidentNode::stop_broadcast_request_service_server private
Definition at line 74 of file traffic_incident_node.hpp.
Referenced by handle_on_configure().
traffic_mobility_operation_pub_
carma_ros2_utils::PubPtr<carma_v2x_msgs::msg::MobilityOperation> traffic::TrafficIncidentNode::traffic_mobility_operation_pub_ private
Definition at line 69 of file traffic_incident_node.hpp.
Referenced by handle_on_configure(), publishTrafficIncidentMobilityOperation(), and spin_callback().
traffic_worker_
TrafficIncidentWorker traffic::TrafficIncidentNode::traffic_worker_ private
Definition at line 80 of file traffic_incident_node.hpp.
Referenced by handle_on_configure(), spin_callback(), startTrafficBroadcastCallback(), and stopTrafficBroadcastCallback().
up_track_
double traffic::TrafficIncidentNode::up_track_ private
Definition at line 87 of file traffic_incident_node.hpp.
Referenced by TrafficIncidentNode(), and handle_on_configure().
The documentation for this class was generated from the following files:
carma-messenger-core/traffic_incident/include/traffic_incident_node.hpp
carma-messenger-core/traffic_incident/src/traffic_incident_node.cpp