Carma-platform: j2735_convertor::SPATConvertor Class Reference
j2735_convertor::SPATConvertor Class Reference
Is the class responsible for converting J2735 SPATs to CARMA usable SPATs.
#include <spat_convertor.hpp>
Static Public Member Functions
static void convert (const j2735_v2x_msgs::msg::SPAT &in_msg, carma_v2x_msgs::msg::SPAT &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::MapData into a carma_v2x_msgs::msg::MapData.
Static Private Member Functions
static void convertTimeChangeDetails (const j2735_v2x_msgs::msg::TimeChangeDetails &in_msg, carma_v2x_msgs::msg::TimeChangeDetails &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TimeChangeDetails into a carma_v2x_msgs::msg::TimeChangeDetails.
static void convertAdvisorySpeed (const j2735_v2x_msgs::msg::AdvisorySpeed &in_msg, carma_v2x_msgs::msg::AdvisorySpeed &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::AdvisorySpeed into a carma_v2x_msgs::msg::AdvisorySpeed.
static void convertMovementEvent (const j2735_v2x_msgs::msg::MovementEvent &in_msg, carma_v2x_msgs::msg::MovementEvent &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::MovementEvent into a carma_v2x_msgs::msg::MovementEvent.
static void convertMovementState (const j2735_v2x_msgs::msg::MovementState &in_msg, carma_v2x_msgs::msg::MovementState &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::MovementState into a carma_v2x_msgs::msg::MovementState.
static void convertIntersectionState (const j2735_v2x_msgs::msg::IntersectionState &in_msg, carma_v2x_msgs::msg::IntersectionState &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::IntersectionState into a carma_v2x_msgs::msg::IntersectionState.
Detailed Description
Is the class responsible for converting J2735 SPATs to CARMA usable SPATs.
Handles conversion between Map messages in the j2735_msgs and cav_msgs packages. Unit conversions are handled
Definition at line 36 of file spat_convertor.hpp.
Member Function Documentation
convert()
void j2735_convertor::SPATConvertor::convert (const j2735_v2x_msgs::msg::SPAT & in_msg, carma_v2x_msgs::msg::SPAT & out_msg) static
Convert the contents of a j2735_v2x_msgs::msg::MapData into a carma_v2x_msgs::msg::MapData.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions are handled
Definition at line 122 of file spat_convertor.cpp.
{
  out_msg.time_stamp = in_msg.time_stamp;
  out_msg.time_stamp_exists = in_msg.time_stamp_exists;
  out_msg.name = in_msg.name;
  out_msg.name_exists = in_msg.name_exists;
  // Convert Intersection State List
  for (j2735_v2x_msgs::msg::IntersectionState state : in_msg.intersections.intersection_state_list)
  {
    carma_v2x_msgs::msg::IntersectionState cav_state;
    convertIntersectionState(state, cav_state);
    out_msg.intersection_state_list.push_back(cav_state);
  }
}
References convertIntersectionState().
Referenced by j2735_convertor::Node::j2735SpatHandler().
convertAdvisorySpeed()
void j2735_convertor::SPATConvertor::convertAdvisorySpeed (const j2735_v2x_msgs::msg::AdvisorySpeed & in_msg, carma_v2x_msgs::msg::AdvisorySpeed & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::AdvisorySpeed into a carma_v2x_msgs::msg::AdvisorySpeed.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions are handled
Definition at line 43 of file spat_convertor.cpp.
{
  out_msg.type = in_msg.type;
  out_msg.speed_exists = in_msg.speed_exists;
  // Convert Speed
  out_msg.speed = (double)in_msg.speed / units::DECI_MPS_PER_MPS;
  // Done Conversion
  out_msg.confidence = in_msg.confidence;
  out_msg.distance = in_msg.distance;
  out_msg.distance_exists = in_msg.distance_exists;
  out_msg.restriction_class_id = in_msg.restriction_class_id;
  out_msg.restriction_class_id_exists = in_msg.restriction_class_id_exists;
}
References j2735_convertor::units::DECI_MPS_PER_MPS.
Referenced by convertMovementEvent().
convertIntersectionState()
void j2735_convertor::SPATConvertor::convertIntersectionState (const j2735_v2x_msgs::msg::IntersectionState & in_msg, carma_v2x_msgs::msg::IntersectionState & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::IntersectionState into a carma_v2x_msgs::msg::IntersectionState.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions are handled
Definition at line 92 of file spat_convertor.cpp.
{
  out_msg.name = in_msg.name;
  out_msg.name_exists = in_msg.name_exists;
  out_msg.id = in_msg.id;
  out_msg.revision = in_msg.revision;
  out_msg.status = in_msg.status;
  out_msg.moy = in_msg.moy;
  out_msg.moy_exists = in_msg.moy_exists;
  // Convert units of timestamp from ms to s
  out_msg.time_stamp = (double)in_msg.time_stamp / units::MS_PER_S;
  out_msg.time_stamp_exists = in_msg.time_stamp_exists;
  // Done conversion
  out_msg.lane_id_list = in_msg.enabled_lanes.lane_id_list;
  out_msg.enabled_lanes_exists = in_msg.enabled_lanes_exists;
  // Convert MovementState
  for (j2735_v2x_msgs::msg::MovementState state : in_msg.states.movement_list)
  {
    carma_v2x_msgs::msg::MovementState cav_state;
    convertMovementState(state, cav_state);
    out_msg.movement_list.push_back(cav_state);
  }
  // Done Conversion
  out_msg.connection_maneuver_assist_list = in_msg.maneuever_assist_list.connection_maneuver_assist_list;
  out_msg.maneuever_assist_list_exists = in_msg.maneuever_assist_list_exists;
}
References convertMovementState(), and j2735_convertor::units::MS_PER_S.
Referenced by convert().
convertMovementEvent()
void j2735_convertor::SPATConvertor::convertMovementEvent (const j2735_v2x_msgs::msg::MovementEvent & in_msg, carma_v2x_msgs::msg::MovementEvent & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::MovementEvent into a carma_v2x_msgs::msg::MovementEvent.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions are handled
Definition at line 57 of file spat_convertor.cpp.
{
  out_msg.event_state = in_msg.event_state;
  out_msg.timing_exists = in_msg.timing_exists;
  // Convert TimeChangeDetails
  convertTimeChangeDetails(in_msg.timing, out_msg.timing);
  // Done Conversion
  out_msg.speeds_exists = in_msg.speeds_exists;
  // Convert AdvisorySpeedList
  for (j2735_v2x_msgs::msg::AdvisorySpeed speed : in_msg.speeds.advisory_speed_list)
  {
    carma_v2x_msgs::msg::AdvisorySpeed cav_speed;
    convertAdvisorySpeed(speed, cav_speed);
    out_msg.advisory_speed_list.push_back(cav_speed);
  }
}
References convertAdvisorySpeed(), and convertTimeChangeDetails().
Referenced by convertMovementState().
convertMovementState()
void j2735_convertor::SPATConvertor::convertMovementState (const j2735_v2x_msgs::msg::MovementState & in_msg, carma_v2x_msgs::msg::MovementState & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::MovementState into a carma_v2x_msgs::msg::MovementState.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions are handled
Definition at line 75 of file spat_convertor.cpp.
{
  out_msg.movement_name = in_msg.movement_name;
  out_msg.movement_name_exists = in_msg.movement_name_exists;
  out_msg.signal_group = in_msg.signal_group;
  // Convert MovementEvent
  for (j2735_v2x_msgs::msg::MovementEvent event : in_msg.state_time_speed.movement_event_list)
  {
    carma_v2x_msgs::msg::MovementEvent cav_event;
    convertMovementEvent(event, cav_event);
    out_msg.movement_event_list.push_back(cav_event);
  }
  // Done Conversion
  out_msg.connection_maneuver_assist_list = in_msg.maneuver_assist_list.connection_maneuver_assist_list;
  out_msg.maneuver_assist_list_exists = in_msg.maneuver_assist_list_exists;
}
References convertMovementEvent().
Referenced by convertIntersectionState().
convertTimeChangeDetails()
void j2735_convertor::SPATConvertor::convertTimeChangeDetails (const j2735_v2x_msgs::msg::TimeChangeDetails & in_msg, carma_v2x_msgs::msg::TimeChangeDetails & out_msg) static private
Convert the contents of a j2735_v2x_msgs::msg::TimeChangeDetails into a carma_v2x_msgs::msg::TimeChangeDetails.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions are handled
Definition at line 25 of file spat_convertor.cpp.
{
  out_msg.confidence = in_msg.confidence;
  out_msg.confidence_exists = in_msg.confidence_exists;
  out_msg.start_time_exists = in_msg.start_time_exists;
  out_msg.max_end_time_exists = in_msg.max_end_time_exists;
  out_msg.likely_time_exists = in_msg.likely_time_exists;
  out_msg.next_time_exists = in_msg.next_time_exists;
  // Convert Time Marks
  out_msg.start_time = (double)in_msg.start_time / units::DECI_S_PER_S;
  out_msg.min_end_time = (double)in_msg.min_end_time / units::DECI_S_PER_S;
  out_msg.max_end_time = (double)in_msg.max_end_time / units::DECI_S_PER_S;
  out_msg.likely_time_exists = (double)in_msg.likely_time_exists / units::DECI_S_PER_S;
  out_msg.next_time = (double)in_msg.next_time / units::DECI_S_PER_S;
  // Done Conversion
}
References j2735_convertor::units::DECI_S_PER_S.
Referenced by convertMovementEvent().
The documentation for this class was generated from the following files:
carma-messenger-core/j2735_convertor/include/j2735_convertor/spat_convertor.hpp
carma-messenger-core/j2735_convertor/src/spat_convertor.cpp