Carma-platform: traffic::TrafficIncidentWorker Class Reference
traffic::TrafficIncidentWorker Class Reference
#include <traffic_incident_worker.hpp>
Public Types
using PublishTrafficCallback = std::function< void(const carma_v2x_msgs::msg::MobilityOperation &)>
Public Member Functions
TrafficIncidentWorker (PublishTrafficCallback traffic_pub)
Constructor.
void pinpointDriverCallback (gps_msgs::msg::GPSFix::UniquePtr pinpoint_msg)
pinpointDriverCallback populates lat lon heading from pinpoint driver.
template<class T >
std::string anytypeToString (T value)
anytypeToString converts anytype to string value
std::string doubleToString (double value)
void setSenderId (std::string sender_id)
void setEventReason (std::string event_reason)
void setEventType (std::string event_type)
void setDownTrack (double down_track)
void setUpTrack (double up_track)
void setMinGap (double min_gap)
void setPinPoint (gps_msgs::msg::GPSFix pinpoint_msg)
void setAdvisorySpeed (double advisory_speed)
std::string getSenderId ()
std::string getEventReason ()
std::string getEventType ()
double getDownTrack ()
double getUpTrack ()
double getMinGap ()
gps_msgs::msg::GPSFix getPinPoint ()
double getAdvisorySpeed ()
carma_v2x_msgs::msg::MobilityOperation mobilityMessageGenerator (const gps_msgs::msg::GPSFix &msg)
Public Attributes
const std::string USE_CASE_NAME_ = "carma3/Incident_Use_Case"
Private Attributes
PublishTrafficCallback traffic_pub_
std::string sender_id_ = "USDOT-49096"
std::string closed_lane_ = "[1]"
std::string event_reason_ = ""
std::string event_type_ = "OPEN"
double down_track_ = 0
double up_track_ = 0
double min_gap_ = 0
double advisory_speed_ = 0
gps_msgs::msg::GPSFix pinpoint_msg_
Detailed Description
Definition at line 33 of file traffic_incident_worker.hpp.
Member Typedef Documentation
PublishTrafficCallback
using traffic::TrafficIncidentWorker::PublishTrafficCallback = std::function<void(const carma_v2x_msgs::msg::MobilityOperation &)>
Definition at line 36 of file traffic_incident_worker.hpp.
Constructor & Destructor Documentation
TrafficIncidentWorker()
traffic::TrafficIncidentWorker::TrafficIncidentWorker (PublishTrafficCallback traffic_pub)
Constructor.
Definition at line 21 of file traffic_incident_worker.cpp.
: traffic_pub_(traffic_pub){};
Member Function Documentation
anytypeToString()
template<class T > traffic::TrafficIncidentWorker::anytypeToString (T value) inline
anytypeToString converts anytype to string value
Parameters
value which gets converted.
Definition at line 55 of file traffic_incident_worker.hpp.
  {
    std::stringstream ss;
    ss << value;
    return ss.str();
  }
Referenced by mobilityMessageGenerator().
doubleToString()
std::string traffic::TrafficIncidentWorker::doubleToString (double value)
Definition at line 55 of file traffic_incident_worker.cpp.
{
  std::ostringstream ss;
  ss << std::setprecision(10);
  ss << value;
  return ss.str();
}
Referenced by mobilityMessageGenerator().
getAdvisorySpeed()
double traffic::TrafficIncidentWorker::getAdvisorySpeed ()
Definition at line 103 of file traffic_incident_worker.cpp.
{ return this->advisory_speed_; }
References advisory_speed_.
Referenced by traffic::TrafficIncidentNode::spin_callback().
getDownTrack()
double traffic::TrafficIncidentWorker::getDownTrack ()
Definition at line 95 of file traffic_incident_worker.cpp.
{ return this->down_track_; }
References down_track_.
Referenced by traffic::TrafficIncidentNode::spin_callback().
getEventReason()
std::string traffic::TrafficIncidentWorker::getEventReason ()
Definition at line 91 of file traffic_incident_worker.cpp.
{ return this->event_reason_; }
References event_reason_.
getEventType()
std::string traffic::TrafficIncidentWorker::getEventType ()
Definition at line 93 of file traffic_incident_worker.cpp.
{ return this->event_type_; }
References event_type_.
getMinGap()
double traffic::TrafficIncidentWorker::getMinGap ()
Definition at line 99 of file traffic_incident_worker.cpp.
{ return this->min_gap_; }
References min_gap_.
Referenced by traffic::TrafficIncidentNode::spin_callback().
getPinPoint()
gps_msgs::msg::GPSFix traffic::TrafficIncidentWorker::getPinPoint ()
Definition at line 101 of file traffic_incident_worker.cpp.
{ return this->pinpoint_msg_; }
References pinpoint_msg_.
Referenced by traffic::TrafficIncidentNode::spin_callback().
getSenderId()
std::string traffic::TrafficIncidentWorker::getSenderId ()
Definition at line 89 of file traffic_incident_worker.cpp.
{ return this->sender_id_; }
References sender_id_.
getUpTrack()
double traffic::TrafficIncidentWorker::getUpTrack ()
Definition at line 97 of file traffic_incident_worker.cpp.
{ return this->up_track_; }
References up_track_.
Referenced by traffic::TrafficIncidentNode::spin_callback().
mobilityMessageGenerator()
carma_v2x_msgs::msg::MobilityOperation traffic::TrafficIncidentWorker::mobilityMessageGenerator (const gps_msgs::msg::GPSFix & msg)
Definition at line 33 of file traffic_incident_worker.cpp.
{
  carma_v2x_msgs::msg::MobilityOperation traffic_mobility_msg;
  traffic_mobility_msg.m_header.timestamp = pinpoint_msg.header.stamp.sec * 1000;
  traffic_mobility_msg.m_header.sender_id = sender_id_;
  traffic_mobility_msg.strategy = USE_CASE_NAME_;
  traffic_mobility_msg.strategy_params =
    "lat:" + doubleToString(pinpoint_msg.latitude) + "," +
    "lon:" + doubleToString(pinpoint_msg.longitude) + "," +
    "downtrack:" + anytypeToString(down_track_) + "," + "uptrack:" + anytypeToString(up_track_) +
    "," + "min_gap:" + anytypeToString(min_gap_) + "," +
    "advisory_speed:" + anytypeToString(advisory_speed_) + "," + "event_reason:" + event_reason_ +
    "," + "event_type:" + event_type_;
  return traffic_mobility_msg;
}
References advisory_speed_, anytypeToString(), doubleToString(), down_track_, event_reason_, event_type_, min_gap_, sender_id_, up_track_, and USE_CASE_NAME_.
Referenced by pinpointDriverCallback(), and traffic::TrafficIncidentNode::spin_callback().
pinpointDriverCallback()
void traffic::TrafficIncidentWorker::pinpointDriverCallback (gps_msgs::msg::GPSFix::UniquePtr pinpoint_msg)
pinpointDriverCallback populates lat lon heading from pinpoint driver.
Parameters
gps_msgs::msg::GPSFix.
Definition at line 24 of file traffic_incident_worker.cpp.
{
  carma_v2x_msgs::msg::MobilityOperation traffic_mobility_msg =
    mobilityMessageGenerator(*pinpoint_msg);
  // comment out this for now since we are not broadcasting upon receiving GPS signal
  // traffic_pub_(traffic_mobility_msg);
  setPinPoint(*pinpoint_msg);
}
References mobilityMessageGenerator(), and setPinPoint().
Referenced by traffic::TrafficIncidentNode::handle_on_configure().
setAdvisorySpeed()
void traffic::TrafficIncidentWorker::setAdvisorySpeed (double advisory_speed)
Definition at line 84 of file traffic_incident_worker.cpp.
{
  this->advisory_speed_ = advisory_speed;
}
References advisory_speed_.
Referenced by traffic::TrafficIncidentNode::startTrafficBroadcastCallback(), and traffic::TrafficIncidentNode::stopTrafficBroadcastCallback().
setDownTrack()
void traffic::TrafficIncidentWorker::setDownTrack (double down_track)
Definition at line 74 of file traffic_incident_worker.cpp.
{ this->down_track_ = down_track; }
References down_track_.
Referenced by traffic::TrafficIncidentNode::handle_on_configure(), traffic::TrafficIncidentNode::startTrafficBroadcastCallback(), and traffic::TrafficIncidentNode::stopTrafficBroadcastCallback().
setEventReason()
void traffic::TrafficIncidentWorker::setEventReason (std::string event_reason)
Definition at line 65 of file traffic_incident_worker.cpp.
{
  this->event_reason_ = event_reason;
}
References event_reason_.
Referenced by traffic::TrafficIncidentNode::handle_on_configure().
setEventType()
void traffic::TrafficIncidentWorker::setEventType (std::string event_type)
Definition at line 70 of file traffic_incident_worker.cpp.
{ this->event_type_ = event_type; }
References event_type_.
Referenced by traffic::TrafficIncidentNode::handle_on_configure().
setMinGap()
void traffic::TrafficIncidentWorker::setMinGap (double min_gap)
Definition at line 72 of file traffic_incident_worker.cpp.
{ this->min_gap_ = min_gap; }
References min_gap_.
Referenced by traffic::TrafficIncidentNode::handle_on_configure(), traffic::TrafficIncidentNode::startTrafficBroadcastCallback(), and traffic::TrafficIncidentNode::stopTrafficBroadcastCallback().
setPinPoint()
void traffic::TrafficIncidentWorker::setPinPoint (gps_msgs::msg::GPSFix pinpoint_msg)
Definition at line 79 of file traffic_incident_worker.cpp.
{
  this->pinpoint_msg_ = pinpoint_msg;
}
References pinpoint_msg_.
Referenced by pinpointDriverCallback().
setSenderId()
void traffic::TrafficIncidentWorker::setSenderId (std::string sender_id)
Definition at line 63 of file traffic_incident_worker.cpp.
{ this->sender_id_ = sender_id; }
References sender_id_.
Referenced by traffic::TrafficIncidentNode::handle_on_configure().
setUpTrack()
void traffic::TrafficIncidentWorker::setUpTrack (double up_track)
Definition at line 76 of file traffic_incident_worker.cpp.
{ this->up_track_ = up_track; }
References up_track_.
Referenced by traffic::TrafficIncidentNode::handle_on_configure(), traffic::TrafficIncidentNode::startTrafficBroadcastCallback(), and traffic::TrafficIncidentNode::stopTrafficBroadcastCallback().
Member Data Documentation
advisory_speed_
double traffic::TrafficIncidentWorker::advisory_speed_ = 0 private
Definition at line 105 of file traffic_incident_worker.hpp.
Referenced by getAdvisorySpeed(), mobilityMessageGenerator(), and setAdvisorySpeed().
closed_lane_
std::string traffic::TrafficIncidentWorker::closed_lane_ = "[1]" private
Definition at line 99 of file traffic_incident_worker.hpp.
down_track_
double traffic::TrafficIncidentWorker::down_track_ = 0 private
Definition at line 102 of file traffic_incident_worker.hpp.
Referenced by getDownTrack(), mobilityMessageGenerator(), and setDownTrack().
event_reason_
std::string traffic::TrafficIncidentWorker::event_reason_ = "" private
Definition at line 100 of file traffic_incident_worker.hpp.
Referenced by getEventReason(), mobilityMessageGenerator(), and setEventReason().
event_type_
std::string traffic::TrafficIncidentWorker::event_type_ = "OPEN" private
Definition at line 101 of file traffic_incident_worker.hpp.
Referenced by getEventType(), mobilityMessageGenerator(), and setEventType().
min_gap_
double traffic::TrafficIncidentWorker::min_gap_ = 0 private
Definition at line 104 of file traffic_incident_worker.hpp.
Referenced by getMinGap(), mobilityMessageGenerator(), and setMinGap().
pinpoint_msg_
gps_msgs::msg::GPSFix traffic::TrafficIncidentWorker::pinpoint_msg_ private
Definition at line 106 of file traffic_incident_worker.hpp.
Referenced by getPinPoint(), and setPinPoint().
sender_id_
std::string traffic::TrafficIncidentWorker::sender_id_ = "USDOT-49096" private
Definition at line 98 of file traffic_incident_worker.hpp.
Referenced by getSenderId(), mobilityMessageGenerator(), and setSenderId().
traffic_pub_
PublishTrafficCallback traffic::TrafficIncidentWorker::traffic_pub_ private
Definition at line 95 of file traffic_incident_worker.hpp.
up_track_
double traffic::TrafficIncidentWorker::up_track_ = 0 private
Definition at line 103 of file traffic_incident_worker.hpp.
Referenced by getUpTrack(), mobilityMessageGenerator(), and setUpTrack().
USE_CASE_NAME_
const std::string traffic::TrafficIncidentWorker::USE_CASE_NAME_ = "carma3/Incident_Use_Case"
Definition at line 90 of file traffic_incident_worker.hpp.
Referenced by mobilityMessageGenerator().
The documentation for this class was generated from the following files:
carma-messenger-core/traffic_incident/include/traffic_incident_worker.hpp
carma-messenger-core/traffic_incident/src/traffic_incident_worker.cpp