Carma-platform: emergency_response_vehicle_plugin::UDPListener Class Reference
emergency_response_vehicle_plugin::UDPListener Class Reference
UDPListener is a helper class that manages listening on a UDP socket and passing received packets to subscribers. NOTE: Class is loosely based off of UDPListener class implemented in the usdot-fhwa-stol GitHub organization's carma-cohda-dsrc-driver repository: https://github.com/usdot-fhwa-stol/carma-cohda-dsrc-driver.
#include <udp_listener.hpp>
Public Member Functions
UDPListener (boost::asio::io_service &io, unsigned short port)
Constructs a UDPListener.
bool start ()
Starts the.
Public Attributes
boost::signals2::signal< void(const std::shared_ptr< const std::vector< uint8_t > > &)> onReceive
Called on packet received.
Private Member Functions
void startReceiveUdp ()
Starts asynchronous listening on udp socket.
void handleReceivedUdp (const boost::system::error_code &error_code, std::size_t bytes_transferred)
Handles received packets.
Private Attributes
boost::asio::io_service & io_
boost::asio::ip::udp::socket socket_
std::string logger_name_ = "emergency_response_vehicle_plugin::UDPListener"
Detailed Description
UDPListener is a helper class that manages listening on a UDP socket and passing received packets to subscribers. NOTE: Class is loosely based off of UDPListener class implemented in the usdot-fhwa-stol GitHub organization's carma-cohda-dsrc-driver repository: https://github.com/usdot-fhwa-stol/carma-cohda-dsrc-driver.
Definition at line 34 of file udp_listener.hpp.
Constructor & Destructor Documentation
UDPListener()
emergency_response_vehicle_plugin::UDPListener::UDPListener (boost::asio::io_service & io, unsigned short port)
Constructs a UDPListener.
Parameters
io - an io_service object to service the asynchronous IO
port - the port to listen on
Definition at line 22 of file udp_listener.cpp.
                                                                         : io_(io), socket_(io_)
    {
        socket_.open(boost::asio::ip::udp::v4());
        socket_.bind(boost::asio::ip::udp::endpoint(boost::asio::ip::udp::v4(), port));
    }
References socket_.
Member Function Documentation
handleReceivedUdp()
void emergency_response_vehicle_plugin::UDPListener::handleReceivedUdp (const boost::system::error_code & error_code, std::size_t bytes_transferred) private
Handles received packets.
Parameters
error_code
bytes_transferred
Definition at line 39 of file udp_listener.cpp.
    {
        if(!error_code)
        {
            // Get the number of bytes available for reading
            size_t buffer_size = socket_.available();
            // Create buffer based on number of bytes available for reading
            std::shared_ptr<std::vector<uint8_t>> buffer = std::make_shared<std::vector<uint8_t>>(buffer_size);
            boost::system::error_code receive_error_code;
            // Receive data on UDP socket; data is stored in 'buffer'
            socket_.receive(boost::asio::buffer(*buffer), 0, receive_error_code);
            if(!receive_error_code)
            {
                // Trigger the onReceive() function with 'buffer' (containing the received data) as an argument
                io_.post([this, buffer](){onReceive(buffer);});
            }
            startReceiveUdp();
        }
        else
        {
            RCLCPP_WARN_STREAM(rclcpp::get_logger(logger_name_), "Error occurred while reading data from UDP socket!");
        }
    }
References io_, logger_name_, onReceive, socket_, and startReceiveUdp().
Referenced by startReceiveUdp().
start()
bool emergency_response_vehicle_plugin::UDPListener::start ()
Starts the.
Returns
Definition at line 68 of file udp_listener.cpp.
    {
        startReceiveUdp();
        return true;
    }
References startReceiveUdp().
startReceiveUdp()
void emergency_response_vehicle_plugin::UDPListener::startReceiveUdp () private
Starts asynchronous listening on udp socket.
Definition at line 28 of file udp_listener.cpp.
    {
        auto read_handler = [this](const boost::system::error_code& error_code, size_t bytes_transferred){
                handleReceivedUdp(error_code, bytes_transferred);};
        // Pass read_handler so that handleReceivedUdp() is called after the async_receive operation completes.
        socket_.async_receive(
            boost::asio::null_buffers(),
            read_handler);
    }
References handleReceivedUdp(), and socket_.
Referenced by handleReceivedUdp(), and start().
Member Data Documentation
io_
boost::asio::io_service& emergency_response_vehicle_plugin::UDPListener::io_ private
Definition at line 37 of file udp_listener.hpp.
Referenced by handleReceivedUdp().
logger_name_
std::string emergency_response_vehicle_plugin::UDPListener::logger_name_ = "emergency_response_vehicle_plugin::UDPListener" private
Definition at line 41 of file udp_listener.hpp.
Referenced by handleReceivedUdp().
onReceive
boost::signals2::signal<void (const std::shared_ptr< const std::vector<uint8_t>>&)> emergency_response_vehicle_plugin::UDPListener::onReceive
Called on packet received.
Definition at line 67 of file udp_listener.hpp.
Referenced by handleReceivedUdp().
socket_
boost::asio::ip::udp::socket emergency_response_vehicle_plugin::UDPListener::socket_ private
Definition at line 39 of file udp_listener.hpp.
Referenced by UDPListener(), handleReceivedUdp(), and startReceiveUdp().
The documentation for this class was generated from the following files:
carma-messenger-core/emergency_response_vehicle_plugin/include/emergency_response_vehicle_plugin/udp_listener.hpp
carma-messenger-core/emergency_response_vehicle_plugin/src/udp_listener.cpp