Carma-platform: emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin Class Reference
emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin Class Reference
#include <emergency_response_vehicle_plugin_node.hpp>
Public Member Functions
EmergencyResponseVehiclePlugin (const rclcpp::NodeOptions &)
EmergencyResponseVehiclePlugin constructor.
rcl_interfaces::msg::SetParametersResult parameter_update_callback (const std::vector< rclcpp::Parameter > &parameters)
callback for dynamic parameter updates
void connect (unsigned short local_port)
Function for connecting the udp_listener_ member object to a local port to enable it to process incoming UDP packets from a device that provides the activation status of the Emergency Response Vehicle's emergency lights and emergency sirens. A warning statement is logged if an error occurs while building and running the udp_listener_.
void processIncomingUdpBinary (const std::shared_ptr< const std::vector< uint8_t > > &data)
Function to process the incoming UDP packet binary data from the device that provides the activation status of the Emergency Response Vehicle's emergency lights and emergency sirens. UDP packets are received by the udp_listener_ object and the binary data is passed to this function.
void loadRouteDestinationPointsFromFile (const std::string &route_file_path)
Function to extract the route destination points from a .csv file stored on the Host PC at the file path provided in the route_file_path argument. Route destination points are stored sequentially within the plugin's route_destination_points_ member object.
uint8_t getNextMsgCount (uint8_t old_msg_count)
Helper function to get the next value associated with a generated BSM's 'msgcount' field based on the provided msgcount of the previously generated BSM.
carma_v2x_msgs::msg::BSM generateBSM ()
Function for generating a BSM for the Emergency Response Vehicle based on the latest status of this object's member variables. This function also updates the value of prev_msg_count_.
void publishBSM ()
Function for publishing a BSM for the Emergency Response Vehicle. Makes a call to generateBSM() to obtain the BSM that will be published.
void arrivedAtEmergencyDestinationCallback (std::shared_ptr< rmw_request_id_t >, std_srvs::srv::Trigger::Request::SharedPtr req, std_srvs::srv::Trigger::Response::SharedPtr resp)
Service callback for a service call that indicates the Emergency Response Vehicle has arrived at its destination. Service is called by the Emergency Response Web UI Widget, and results in this plugin clearing its route_destination_points_ so that future route destination points will not be included in regional extension of the BSMs generated within generateBSM().
void incomingEmergencyVehicleResponseCallback (carma_v2x_msgs::msg::EmergencyVehicleResponse::UniquePtr msg)
A callback to process a received EmergencyVehicleResponse message, which indicates that a CDA vehicle is unable to change lanes out of the path of an approaching Emergency Response Vehicle. If the message is intended for the ego Emergency Response Vehicle, then a call to broadcastEmergencyVehicleAck() will be made, and message will be published using emergency_vehicle_ui_warnings_pub_ to provide the Emergency Response Web UI widget with information to display in a warning message to the user.
void broadcastEmergencyVehicleAck (const std::string &recipient_id)
A function for publishing an outgoing EmergencyVehicleAck message in response to the CDA vehicle that broadcasted an EmergencyVehicleResponse message to this Emergency Resposne Vehicle.
double getDistanceBetween (const double &lat_1_deg, const double &lon_1_deg, const double &lat_2_deg, const double &lon_2_deg)
A helpfer function to approximate the distance (in meters) between two pairs of latitude/longitude coordinates. This function uses the Haversine Formula and assumes Earth as a spherical shape to approximate this measurement.
void poseCallback (gps_msgs::msg::GPSFix::UniquePtr msg)
Message callback for the Emergency Response Vehicle's current latitude and longitude.
void twistCallback (geometry_msgs::msg::TwistStamped::UniquePtr msg)
Message callback for the Emergency Response Vehicle's current velocity.
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &)
carma_ros2_utils::CallbackReturn handle_on_activate (const rclcpp_lifecycle::State &)
virtual void handle_on_shutdown ()
Private Member Functions
FRIEND_TEST (EmergencyResponseVehiclePluginTest, testGetDistanceBetween)
FRIEND_TEST (EmergencyResponseVehiclePluginTest, testRemoveRouteDestinationPoint)
FRIEND_TEST (EmergencyResponseVehiclePluginTest, testGenerateBsm)
FRIEND_TEST (EmergencyResponseVehiclePluginTest, testLoadRouteDestinationPointsFromFile)
FRIEND_TEST (EmergencyResponseVehiclePluginTest, testProcessIncomingUdpBinary)
Private Attributes
carma_ros2_utils::SubPtr< carma_v2x_msgs::msg::EmergencyVehicleResponse > incoming_emergency_vehicle_response_sub_
carma_ros2_utils::SubPtr< gps_msgs::msg::GPSFix > pose_sub_
carma_ros2_utils::SubPtr< geometry_msgs::msg::TwistStamped > twist_sub_
carma_ros2_utils::PubPtr< carma_v2x_msgs::msg::BSM > outgoing_bsm_pub_
carma_ros2_utils::PubPtr< carma_v2x_msgs::msg::EmergencyVehicleAck > outgoing_emergency_vehicle_ack_pub_
carma_ros2_utils::PubPtr< carma_msgs::msg::UIInstructions > emergency_vehicle_ui_warnings_pub_
carma_ros2_utils::ServicePtr< std_srvs::srv::Trigger > arrived_at_emergency_destination_server_
Config config_
rclcpp::TimerBase::SharedPtr bsm_generation_timer_
std::vector< carma_v2x_msgs::msg::Position3D > route_destination_points_
std::string bsm_id_string_
uint8_t prev_msg_count_ = 0
double current_latitude_
double current_longitude_
double current_velocity_
bool emergency_lights_active_ = false
bool emergency_sirens_active_ = false
std::string logger_name_ = "emergency_response_vehicle_plugin_node"
std::shared_ptr< boost::asio::io_service::work > work_
std::shared_ptr< std::thread > io_thread_
std::unique_ptr< boost::asio::io_service > io_
std::unique_ptr< UDPListener > udp_listener_
Detailed Description
Definition at line 58 of file emergency_response_vehicle_plugin_node.hpp.
Constructor & Destructor Documentation
EmergencyResponseVehiclePlugin()
emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::EmergencyResponseVehiclePlugin (const rclcpp::NodeOptions & options) explicit
EmergencyResponseVehiclePlugin constructor.
Definition at line 22 of file emergency_response_vehicle_plugin_node.cpp.
      : carma_ros2_utils::CarmaLifecycleNode(options)
  {
    // Create initial config
    config_ = Config();
    // Declare parameters
    config_.enable_emergency_response_vehicle_plugin = declare_parameter<bool>("enable_emergency_response_vehicle_plugin", config_.enable_emergency_response_vehicle_plugin);
    config_.bsm_generation_frequency = declare_parameter<double>("bsm_generation_frequency", config_.bsm_generation_frequency);
    config_.min_distance_to_next_destination_point = declare_parameter<double>("min_distance_to_next_destination_point", config_.min_distance_to_next_destination_point);
    config_.emergency_route_file_name = declare_parameter<std::string>("emergency_route_file_name", config_.emergency_route_file_name);
    config_.route_file_folder = declare_parameter<std::string>("route_file_folder", config_.route_file_folder);
    config_.listening_port = declare_parameter<int>("listening_port", config_.listening_port);
    config_.bsm_message_id = declare_parameter<int>("bsm_message_id", config_.bsm_message_id);
  }
References emergency_response_vehicle_plugin::Config::bsm_generation_frequency, emergency_response_vehicle_plugin::Config::bsm_message_id, config_, emergency_response_vehicle_plugin::Config::emergency_route_file_name, emergency_response_vehicle_plugin::Config::enable_emergency_response_vehicle_plugin, emergency_response_vehicle_plugin::Config::listening_port, emergency_response_vehicle_plugin::Config::min_distance_to_next_destination_point, and emergency_response_vehicle_plugin::Config::route_file_folder.
Member Function Documentation
arrivedAtEmergencyDestinationCallback()
void emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::arrivedAtEmergencyDestinationCallback (std::shared_ptr< rmw_request_id_t > , std_srvs::srv::Trigger::Request::SharedPtr req, std_srvs::srv::Trigger::Response::SharedPtr resp)
Service callback for a service call that indicates the Emergency Response Vehicle has arrived at its destination. Service is called by the Emergency Response Web UI Widget, and results in this plugin clearing its route_destination_points_ so that future route destination points will not be included in regional extension of the BSMs generated within generateBSM().
Parameters
req An empty std_srvs::srv::Trigger::Request.
resp A std_srvs::srv::Trigger::Response with the 'success' field set to true. Emergency Resonse Vehicle's route.
Definition at line 353 of file emergency_response_vehicle_plugin_node.cpp.
  {
    RCLCPP_DEBUG_STREAM(rclcpp::get_logger(logger_name_), "ERV has arrived destination. Removing " << route_destination_points_.size() << " route destination points from plugin.");
    // Clear plugin's route member objects
    route_destination_points_.clear();
    resp->success = true;
  }
References logger_name_, and route_destination_points_.
Referenced by handle_on_configure().
broadcastEmergencyVehicleAck()
void emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::broadcastEmergencyVehicleAck (const std::string & recipient_id)
A function for publishing an outgoing EmergencyVehicleAck message in response to the CDA vehicle that broadcasted an EmergencyVehicleResponse message to this Emergency Resposne Vehicle.
Parameters
recipient_id The vehicle id of the CDA vehicle that this EmergencyVehicleAck message is intended for.
Definition at line 384 of file emergency_response_vehicle_plugin_node.cpp.
  {
    carma_v2x_msgs::msg::EmergencyVehicleAck ack_msg;
    ack_msg.m_header.sender_id = bsm_id_string_;
    ack_msg.m_header.recipient_id = recipient_id;
    ack_msg.acknowledgement = true;
    outgoing_emergency_vehicle_ack_pub_->publish(ack_msg);
  }
References bsm_id_string_, and outgoing_emergency_vehicle_ack_pub_.
Referenced by incomingEmergencyVehicleResponseCallback().
connect()
void emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::connect (unsigned short local_port)
Function for connecting the udp_listener_ member object to a local port to enable it to process incoming UDP packets from a device that provides the activation status of the Emergency Response Vehicle's emergency lights and emergency sirens. A warning statement is logged if an error occurs while building and running the udp_listener_.
Parameters
local_port The local port that udp_listener_ will listen to UDP packets on.
Definition at line 135 of file emergency_response_vehicle_plugin_node.cpp.
  {
    io_.reset(new boost::asio::io_service());
    // Build UDPListener object, which listens to UDP packets on local port defined by local_port
    try{
      if(udp_listener_){
        udp_listener_.reset(nullptr);
      }
      udp_listener_.reset(new UDPListener(*io_, local_port));
    }
    catch(boost::system::system_error e){
      RCLCPP_WARN_STREAM(rclcpp::get_logger(logger_name_), "Error occurred when building UDPListener!");
    }
    catch(std::exception e){
      RCLCPP_WARN_STREAM(rclcpp::get_logger(logger_name_), "Exception thrown when building UDPListener: " << e.what());
    };
    // Connect udp_listener_'s onReceive() to this object's processIncomingUdpBinary() function
    udp_listener_->onReceive.connect([this](const std::shared_ptr<const std::vector<uint8_t>>& data){processIncomingUdpBinary(data);});
    // Called to enable asynchronous processing of UDP packets when io->run is called
    work_.reset(new boost::asio::io_service::work(*io_));
    udp_listener_->start();
    // Run the io service
    io_thread_.reset(new std::thread([this](){
      boost::system::error_code error;
      io_->run(error);
      if(error)
      {
        RCLCPP_WARN_STREAM(rclcpp::get_logger(logger_name_), "Error occurred when running io service. UDPListener will not be functional!");
      }
    }));
  }
References io_, io_thread_, logger_name_, processIncomingUdpBinary(), udp_listener_, and work_.
Referenced by handle_on_activate().
FRIEND_TEST() [1/5]
emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::FRIEND_TEST (EmergencyResponseVehiclePluginTest , testGenerateBsm) private
FRIEND_TEST() [2/5]
emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::FRIEND_TEST (EmergencyResponseVehiclePluginTest , testGetDistanceBetween) private
FRIEND_TEST() [3/5]
emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::FRIEND_TEST (EmergencyResponseVehiclePluginTest , testLoadRouteDestinationPointsFromFile) private
FRIEND_TEST() [4/5]
emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::FRIEND_TEST (EmergencyResponseVehiclePluginTest , testProcessIncomingUdpBinary) private
FRIEND_TEST() [5/5]
emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::FRIEND_TEST (EmergencyResponseVehiclePluginTest , testRemoveRouteDestinationPoint) private
generateBSM()
carma_v2x_msgs::msg::BSM emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::generateBSM ()
Function for generating a BSM for the Emergency Response Vehicle based on the latest status of this object's member variables. This function also updates the value of prev_msg_count_.
Returns
The generated carma_v2x_msgs::msg::BSM message.
Definition at line 271 of file emergency_response_vehicle_plugin_node.cpp.
  {
    carma_v2x_msgs::msg::BSM bsm_msg;
    bsm_msg.header.stamp = this->now();
    // Set msg_count
    uint8_t new_msg_count = getNextMsgCount(prev_msg_count_);
    bsm_msg.core_data.msg_count = new_msg_count;
    prev_msg_count_ = new_msg_count;
    // Set BSM ID
    std::vector<uint8_t> id(4);
    for(int i = 0; i < id.size(); ++i){
      id[i] = config_.bsm_message_id >> (8 * i);
    }
    bsm_msg.core_data.id = id;
    // Store string representation of BSM ID
    std::stringstream ss;
    for(size_t i = 0; i < bsm_msg.core_data.id.size(); ++i){
      ss << std::setfill('0') << std::setw(2) << std::hex << (unsigned)bsm_msg.core_data.id.at(i);
    }
    bsm_id_string_ = ss.str();
    // Set current latitude, longitude, and velocity
    bsm_msg.core_data.presence_vector |= carma_v2x_msgs::msg::BSMCoreData::LATITUDE_AVAILABLE;
    bsm_msg.core_data.latitude = current_latitude_;
    bsm_msg.core_data.presence_vector |= carma_v2x_msgs::msg::BSMCoreData::LONGITUDE_AVAILABLE;
    bsm_msg.core_data.longitude = current_longitude_;
    bsm_msg.core_data.presence_vector |= carma_v2x_msgs::msg::BSMCoreData::SPEED_AVAILABLE;
    bsm_msg.core_data.speed = current_velocity_;
    // Set lights status, siren status, and emergency response type as necessary
    if(emergency_lights_active_ || emergency_sirens_active_){
      bsm_msg.presence_vector |= carma_v2x_msgs::msg::BSM::HAS_PART_II;
      // BSMPartIIExtension.special_vehicle_extensions
      carma_v2x_msgs::msg::BSMPartIIExtension part_ii_special;
      part_ii_special.part_ii_id = carma_v2x_msgs::msg::BSMPartIIExtension::SPECIAL_VEHICLE_EXT;
      // BSMPartIIExtension.special_vehicle_extensions.vehicle_alerts
      part_ii_special.special_vehicle_extensions.presence_vector |= j2735_v2x_msgs::msg::SpecialVehicleExtensions::HAS_VEHICLE_ALERTS;
      if(emergency_sirens_active_){
        part_ii_special.special_vehicle_extensions.vehicle_alerts.siren_use.siren_in_use = j2735_v2x_msgs::msg::SirenInUse::IN_USE;
      }
      if(emergency_lights_active_){
        part_ii_special.special_vehicle_extensions.vehicle_alerts.lights_use.lightbar_in_use = j2735_v2x_msgs::msg::LightbarInUse::IN_USE;
      }
      // Update BSM to indicate that ERV is actively responding to an emergency if sirens and lights are active and at least one future route destination point exists
      if(emergency_sirens_active_ && emergency_lights_active_ && !route_destination_points_.empty()){
        part_ii_special.special_vehicle_extensions.vehicle_alerts.presence_vector |= j2735_v2x_msgs::msg::EmergencyDetails::HAS_RESPONSE_TYPE;
        part_ii_special.special_vehicle_extensions.vehicle_alerts.response_type.response_type = j2735_v2x_msgs::msg::ResponseType::EMERGENCY;
      }
      bsm_msg.part_ii.push_back(part_ii_special);
    }
    // Set route destination points
    if(!route_destination_points_.empty()){
      bsm_msg.presence_vector |= carma_v2x_msgs::msg::BSM::HAS_REGIONAL;
      // Create BSM regional extension that ERV's route destination points will be added to
      carma_v2x_msgs::msg::BSMRegionalExtension regional_ext;
      regional_ext.regional_extension_id = carma_v2x_msgs::msg::BSMRegionalExtension::ROUTE_DESTINATIONS;
      // Add route destination points to regional extension
      for(size_t i = 0; i < route_destination_points_.size(); ++i){
          regional_ext.route_destination_points.push_back(route_destination_points_[i]);
      }
      bsm_msg.regional.push_back(regional_ext);
    }
    return bsm_msg;
  }
References bsm_id_string_, emergency_response_vehicle_plugin::Config::bsm_message_id, config_, current_latitude_, current_longitude_, current_velocity_, emergency_lights_active_, emergency_sirens_active_, getNextMsgCount(), prev_msg_count_, and route_destination_points_.
Referenced by publishBSM().
getDistanceBetween()
double emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::getDistanceBetween (const double & lat_1_deg, const double & lon_1_deg, const double & lat_2_deg, const double & lon_2_deg)
A helpfer function to approximate the distance (in meters) between two pairs of latitude/longitude coordinates. This function uses the Haversine Formula and assumes Earth as a spherical shape to approximate this measurement.
Parameters
lat_1_deg The latitude (in degrees) of the first coordinate pair.
lon_1_deg The longitude (in degrees) of the first coordinate pair.
lat_2_deg The latitude (in degrees) of the second coordinate pair.
lon_2_deg The longitude (in degrees) of the second coordinate pair.
Returns
The approximate distance (in meters) between the two provided latitude/longitude coordinate pairs.
Definition at line 395 of file emergency_response_vehicle_plugin_node.cpp.
  {
    // Convert latitude and longitude values from degrees to radians for point 1
    double lat_1_rad = lat_1_deg * (M_PI / 180.0);
    double lon_1_rad = lon_1_deg * (M_PI / 180.0);
    // Convert latitude and longitude values from degrees to radians for point 2
    double lat_2_rad = lat_2_deg * (M_PI / 180.0);
    double lon_2_rad = lon_2_deg * (M_PI / 180.0);
    // Calculate deltas for inputted latitude and longitude values
    double delta_lat_rad = lat_2_rad - lat_1_rad;
    double delta_lon_rad = lon_2_rad - lon_1_rad;
    // Split calculation into two steps for readability
    double a = std::pow(std::sin(delta_lat_rad / 2.0), 2) + std::pow(std::sin(delta_lon_rad / 2.0), 2) * std::cos(lat_1_rad) * std::cos(lat_2_rad);
    double distance = EARTH_RADIUS_METERS * 2.0 * std::asin(sqrt(a));
    // Return distance between (lat_1, lon_1) and (lat_2, lon_2) in meters
    return distance;
  }
References emergency_response_vehicle_plugin::EARTH_RADIUS_METERS.
Referenced by poseCallback().
getNextMsgCount()
uint8_t emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::getNextMsgCount (uint8_t old_msg_count)
Helper function to get the next value associated with a generated BSM's 'msgcount' field based on the provided msgcount of the previously generated BSM.
Parameters
old_msg_count The value of the previously generated BSM's 'msgcount' field.
Returns
The value to be used for the next generated BSM's 'msgcount' field.
Definition at line 254 of file emergency_response_vehicle_plugin_node.cpp.
{
    old_msg_count++;
    if(old_msg_count > carma_v2x_msgs::msg::BSMCoreData::MSG_COUNT_MAX)
    {
        old_msg_count = 0;
    }
    return old_msg_count;
  }
Referenced by generateBSM().
handle_on_activate()
carma_ros2_utils::CallbackReturn emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::handle_on_activate (const rclcpp_lifecycle::State & prev_state)
Definition at line 109 of file emergency_response_vehicle_plugin_node.cpp.
  {
    // Enable BSM generation, UDP listener, etc. based on the setting of config_.enable_emergency_response_vehicle_plugin
    if(config_.enable_emergency_response_vehicle_plugin){
      RCLCPP_DEBUG_STREAM(rclcpp::get_logger(logger_name_), "Plugin has been enabled by its configuration parameter settings.");
      // Create timer for plugin to generate and publish a new BSM
      int bsm_generation_period_ms = (1 / config_.bsm_generation_frequency) * 1000; // Conversion from frequency (Hz) to milliseconds time period
      bsm_generation_timer_ = create_timer(get_clock(),
                            std::chrono::milliseconds(bsm_generation_period_ms),
                            std::bind(&EmergencyResponseVehiclePlugin::publishBSM, this));
      // Load route destination points from file path provided by the configuration parameters
      std::string emergency_route_file_path = config_.route_file_folder + config_.emergency_route_file_name;
      loadRouteDestinationPointsFromFile(emergency_route_file_path);
      // Connect udp_listener_ to process incoming UDP packets that provide the status of this ERV's emergency lights and sirens
      connect(config_.listening_port);
    }
    else{
      RCLCPP_WARN_STREAM(rclcpp::get_logger(logger_name_), "Plugin has been disabled by its configuration parameter settings.");
    }
    return CallbackReturn::SUCCESS;
  }
References emergency_response_vehicle_plugin::Config::bsm_generation_frequency, bsm_generation_timer_, config_, connect(), emergency_response_vehicle_plugin::Config::emergency_route_file_name, emergency_response_vehicle_plugin::Config::enable_emergency_response_vehicle_plugin, emergency_response_vehicle_plugin::Config::listening_port, loadRouteDestinationPointsFromFile(), logger_name_, publishBSM(), and emergency_response_vehicle_plugin::Config::route_file_folder.
handle_on_configure()
carma_ros2_utils::CallbackReturn emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::handle_on_configure (const rclcpp_lifecycle::State &)
Definition at line 63 of file emergency_response_vehicle_plugin_node.cpp.
  {
    RCLCPP_INFO_STREAM(rclcpp::get_logger(logger_name_), "EmergencyResponseVehiclePlugin trying to configure");
    // Reset config
    config_ = Config();
    // Load parameters
    get_parameter<bool>("enable_emergency_response_vehicle_plugin", config_.enable_emergency_response_vehicle_plugin);
    get_parameter<double>("bsm_generation_frequency", config_.bsm_generation_frequency);
    get_parameter<double>("min_distance_to_next_destination_point", config_.min_distance_to_next_destination_point);
    get_parameter<std::string>("emergency_route_file_name", config_.emergency_route_file_name);
    get_parameter<std::string>("route_file_folder", config_.route_file_folder);
    get_parameter<int>("listening_port", config_.listening_port);
    get_parameter<int>("bsm_message_id", config_.bsm_message_id);
    RCLCPP_INFO_STREAM(rclcpp::get_logger(logger_name_), "Loaded params: " << config_);
    // Register runtime parameter update callback
    add_on_set_parameters_callback(std::bind(&EmergencyResponseVehiclePlugin::parameter_update_callback, this, std_ph::_1));
    // Setup subscribers
    incoming_emergency_vehicle_response_sub_ = create_subscription<carma_v2x_msgs::msg::EmergencyVehicleResponse>("incoming_emergency_vehicle_response", 5,
                                                              std::bind(&EmergencyResponseVehiclePlugin::incomingEmergencyVehicleResponseCallback, this, std_ph::_1));
    pose_sub_ = create_subscription<gps_msgs::msg::GPSFix>("vehicle_pose", 5,
                                                              std::bind(&EmergencyResponseVehiclePlugin::poseCallback, this, std_ph::_1));
    twist_sub_ = create_subscription<geometry_msgs::msg::TwistStamped>("velocity", 5,
                                                              std::bind(&EmergencyResponseVehiclePlugin::twistCallback, this, std_ph::_1));
    // Setup publishers
    outgoing_bsm_pub_ = create_publisher<carma_v2x_msgs::msg::BSM>("outgoing_bsm", 5);
    outgoing_emergency_vehicle_ack_pub_ = create_publisher<carma_v2x_msgs::msg::EmergencyVehicleAck>("outgoing_emergency_vehicle_ack", 5);
    emergency_vehicle_ui_warnings_pub_ = create_publisher<carma_msgs::msg::UIInstructions>("emergency_vehicle_ui_warning", 5);
    // Setup service servers
    arrived_at_emergency_destination_server_ = create_service<std_srvs::srv::Trigger>("arrived_at_emergency_destination",
                                                              std::bind(&EmergencyResponseVehiclePlugin::arrivedAtEmergencyDestinationCallback, this, std_ph::_1, std_ph::_2, std_ph::_3));
    // Return success if everthing initialized successfully
    return CallbackReturn::SUCCESS;
  }
References arrived_at_emergency_destination_server_, arrivedAtEmergencyDestinationCallback(), emergency_response_vehicle_plugin::Config::bsm_generation_frequency, emergency_response_vehicle_plugin::Config::bsm_message_id, config_, emergency_response_vehicle_plugin::Config::emergency_route_file_name, emergency_vehicle_ui_warnings_pub_, emergency_response_vehicle_plugin::Config::enable_emergency_response_vehicle_plugin, incoming_emergency_vehicle_response_sub_, incomingEmergencyVehicleResponseCallback(), emergency_response_vehicle_plugin::Config::listening_port, logger_name_, emergency_response_vehicle_plugin::Config::min_distance_to_next_destination_point, outgoing_bsm_pub_, outgoing_emergency_vehicle_ack_pub_, parameter_update_callback(), pose_sub_, poseCallback(), emergency_response_vehicle_plugin::Config::route_file_folder, twist_sub_, and twistCallback().
handle_on_shutdown()
void emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::handle_on_shutdown () virtual
Definition at line 172 of file emergency_response_vehicle_plugin_node.cpp.
  {
    work_.reset();
    io_->stop();
    io_thread_->join();
  }
References io_, io_thread_, and work_.
incomingEmergencyVehicleResponseCallback()
void emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::incomingEmergencyVehicleResponseCallback (carma_v2x_msgs::msg::EmergencyVehicleResponse::UniquePtr msg)
A callback to process a received EmergencyVehicleResponse message, which indicates that a CDA vehicle is unable to change lanes out of the path of an approaching Emergency Response Vehicle. If the message is intended for the ego Emergency Response Vehicle, then a call to broadcastEmergencyVehicleAck() will be made, and message will be published using emergency_vehicle_ui_warnings_pub_ to provide the Emergency Response Web UI widget with information to display in a warning message to the user.
Parameters
msg The incoming EmergencyVehicleResponse message.
Definition at line 366 of file emergency_response_vehicle_plugin_node.cpp.
  {
    // Only process message if it is intended for the ego vehicle and the sending vehicle is unable to change lanes
    if((msg->m_header.recipient_id == bsm_id_string_) && !msg->can_change_lanes){
      // Generate warning message and send to UI so the UI can display an alert for the user
      carma_msgs::msg::UIInstructions ui_warning_msg;
      ui_warning_msg.msg = "Downstream vehicle " + msg->m_header.sender_id + " is unable to change lanes!";
      ui_warning_msg.type = carma_msgs::msg::UIInstructions::INFO;
      emergency_vehicle_ui_warnings_pub_->publish(ui_warning_msg);
      // Trigger publication of EmergencyVehicleAck to indicate ERV has received the EmergencyVehicleResponse message
      broadcastEmergencyVehicleAck(msg->m_header.sender_id);
    }
  }
References broadcastEmergencyVehicleAck(), bsm_id_string_, and emergency_vehicle_ui_warnings_pub_.
Referenced by handle_on_configure().
loadRouteDestinationPointsFromFile()
void emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::loadRouteDestinationPointsFromFile (const std::string & route_file_path)
Function to extract the route destination points from a .csv file stored on the Host PC at the file path provided in the route_file_path argument. Route destination points are stored sequentially within the plugin's route_destination_points_ member object.
Parameters
route_file_path The file path on the Host PC that contains the .csv file for the Emergency Response Vehicle's route destination points.
Returns
A vector containing the sequential route destination points that describe the Emergency Response Vehicle's route at startup.
Definition at line 213 of file emergency_response_vehicle_plugin_node.cpp.
  {
    // Only load destination points if the file is a .csv; assumes file name ends with ".csv"
    if(route_file_path.find(".csv") == std::string::npos){
      RCLCPP_WARN_STREAM(rclcpp::get_logger(logger_name_), "Route file located at " << route_file_path << " is not a .csv, destination points will not be loaded");
    }
    else{
      RCLCPP_DEBUG_STREAM(rclcpp::get_logger(logger_name_), "Loading route destination points from " << route_file_path);
      std::ifstream fs(route_file_path);
      std::string line;
      // Read each line in route file (if any) and generate a route destination point
      // NOTE: Each line of the .csv follows the format "LONGITUDE<float>,LATITUDE<float>,ELEVATION<float>,DESTINATION-NAME<string>"
      while(std::getline(fs, line)){
        carma_v2x_msgs::msg::Position3D destination_point;
        // lat lon and elev is seperated by comma
        auto comma = line.find(",");
        // convert lon value in degrees from string
        destination_point.longitude = std::stof(line.substr(0, comma));
        line.erase(0, comma + 1);
        comma = line.find(",");
        // convert lat value in degrees from string
        destination_point.latitude = std::stof(line.substr(0, comma));
        // elevation is in meters
        line.erase(0, comma + 1);
        comma = line.find(",");
        destination_point.elevation = std::stof(line.substr(0, comma));
        destination_point.elevation_exists = true;
        route_destination_points_.push_back(destination_point);
      }
      RCLCPP_DEBUG_STREAM(rclcpp::get_logger(logger_name_), "Number of route destination points loaded: " << route_destination_points_.size());
      if(route_destination_points_.empty()){
        RCLCPP_WARN_STREAM(rclcpp::get_logger(logger_name_), "No route destination points were loaded by plugin!");
      }
    }
  }
References logger_name_, and route_destination_points_.
Referenced by handle_on_activate().
parameter_update_callback()
rcl_interfaces::msg::SetParametersResult emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::parameter_update_callback (const std::vector< rclcpp::Parameter > & parameters)
callback for dynamic parameter updates
Definition at line 38 of file emergency_response_vehicle_plugin_node.cpp.
  {
    auto error_1 = update_params<bool>({{"enable_emergency_response_vehicle_plugin", config_.enable_emergency_response_vehicle_plugin}}, parameters);
    auto error_2 = update_params<double>({
        {"bsm_generation_frequency", config_.bsm_generation_frequency},
        {"min_distance_to_next_destination_point", config_.min_distance_to_next_destination_point},
    }, parameters);
    auto error_3 = update_params<std::string>({
        {"emergency_route_file_name", config_.emergency_route_file_name},
        {"route_file_folder", config_.route_file_folder}
    }, parameters);
    rcl_interfaces::msg::SetParametersResult result;
    auto error_4 = update_params<int>({
        {"listening_port", config_.listening_port},
        {"bsm_message_id", config_.bsm_message_id},
    }, parameters);
    result.successful = !error_1 && !error_2 && !error_3 && !error_4;
    return result;
  }
References emergency_response_vehicle_plugin::Config::bsm_generation_frequency, emergency_response_vehicle_plugin::Config::bsm_message_id, config_, emergency_response_vehicle_plugin::Config::emergency_route_file_name, emergency_response_vehicle_plugin::Config::enable_emergency_response_vehicle_plugin, emergency_response_vehicle_plugin::Config::listening_port, emergency_response_vehicle_plugin::Config::min_distance_to_next_destination_point, and emergency_response_vehicle_plugin::Config::route_file_folder.
Referenced by handle_on_configure().
poseCallback()
void emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::poseCallback (gps_msgs::msg::GPSFix::UniquePtr msg)
Message callback for the Emergency Response Vehicle's current latitude and longitude.
Parameters
msg The incoming gps_msgs::msg::GPSFix message.
Definition at line 418 of file emergency_response_vehicle_plugin_node.cpp.
  {
    current_latitude_ = msg->latitude;
    current_longitude_ = msg->longitude;
    if(!route_destination_points_.empty()){
      // Get distance between current ERV location and first destination point
      double distance_to_next_destination_point = getDistanceBetween(current_latitude_, current_longitude_, route_destination_points_[0].latitude, route_destination_points_[0].longitude);
      // Remove first destination point if ERV is within configurable distance of that point
      if(distance_to_next_destination_point <= config_.min_distance_to_next_destination_point){
        RCLCPP_DEBUG_STREAM(rclcpp::get_logger(logger_name_), "ERV is " << distance_to_next_destination_point << " meters from next destination point. Point will be removed.");
        route_destination_points_.erase(route_destination_points_.begin());
      }
    }
  }
References config_, current_latitude_, current_longitude_, getDistanceBetween(), logger_name_, emergency_response_vehicle_plugin::Config::min_distance_to_next_destination_point, and route_destination_points_.
Referenced by handle_on_configure().
processIncomingUdpBinary()
void emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::processIncomingUdpBinary (const std::shared_ptr< const std::vector< uint8_t > > & data)
Function to process the incoming UDP packet binary data from the device that provides the activation status of the Emergency Response Vehicle's emergency lights and emergency sirens. UDP packets are received by the udp_listener_ object and the binary data is passed to this function.
Parameters
data The binary data associated with the received UDP packet.
Definition at line 179 of file emergency_response_vehicle_plugin_node.cpp.
  {
    auto data_vector = *data;
    if(!data_vector.empty())
    {
      // Extract the first byte of the received UDP binary since this describes the status of the emergency response vehicle's sirens and lights
      uint8_t value = data_vector[0];
      if(value == SirensAndLightsStatus::SIRENS_AND_LIGHTS_INACTIVE){
        emergency_sirens_active_ = false;
        emergency_lights_active_ = false;
      }
      else if(value == SirensAndLightsStatus::ONLY_SIRENS_ACTIVE){
        emergency_sirens_active_ = true;
        emergency_lights_active_ = false;
      }
      else if(value == SirensAndLightsStatus::ONLY_LIGHTS_ACTIVE){
        emergency_sirens_active_ = false;
        emergency_lights_active_ = true;
      }
      else if(value == SirensAndLightsStatus::SIRENS_AND_LIGHTS_ACTIVE){
        emergency_sirens_active_ = true;
        emergency_lights_active_ = true;
      }
      else{
        RCLCPP_WARN_STREAM(rclcpp::get_logger(logger_name_), "Unsupported initial UDP byte of " << value << " received; packet will not be processed");
      }
    }
    else{
      RCLCPP_WARN_STREAM(rclcpp::get_logger(logger_name_), "Empty UDP payload received; packet will not be processed");
    }
  }
References emergency_lights_active_, emergency_sirens_active_, logger_name_, emergency_response_vehicle_plugin::ONLY_LIGHTS_ACTIVE, emergency_response_vehicle_plugin::ONLY_SIRENS_ACTIVE, emergency_response_vehicle_plugin::SIRENS_AND_LIGHTS_ACTIVE, and emergency_response_vehicle_plugin::SIRENS_AND_LIGHTS_INACTIVE.
Referenced by connect().
publishBSM()
void emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::publishBSM ()
Function for publishing a BSM for the Emergency Response Vehicle. Makes a call to generateBSM() to obtain the BSM that will be published.
Definition at line 263 of file emergency_response_vehicle_plugin_node.cpp.
  {
    carma_v2x_msgs::msg::BSM outgoing_bsm_msg = generateBSM();
    // Publish BSM
    outgoing_bsm_pub_->publish(outgoing_bsm_msg);
  }
References generateBSM(), and outgoing_bsm_pub_.
Referenced by handle_on_activate().
twistCallback()
void emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::twistCallback (geometry_msgs::msg::TwistStamped::UniquePtr msg)
Message callback for the Emergency Response Vehicle's current velocity.
Parameters
msg The incoming geometry_msgs::msg::TwistStamped message.
Definition at line 435 of file emergency_response_vehicle_plugin_node.cpp.
  {
    current_velocity_ = msg->twist.linear.x;
  }
References current_velocity_.
Referenced by handle_on_configure().
Member Data Documentation
arrived_at_emergency_destination_server_
carma_ros2_utils::ServicePtr<std_srvs::srv::Trigger> emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::arrived_at_emergency_destination_server_ private
Definition at line 73 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by handle_on_configure().
bsm_generation_timer_
rclcpp::TimerBase::SharedPtr emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::bsm_generation_timer_ private
Definition at line 79 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by handle_on_activate().
bsm_id_string_
std::string emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::bsm_id_string_ private
Definition at line 85 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by broadcastEmergencyVehicleAck(), generateBSM(), and incomingEmergencyVehicleResponseCallback().
config_
Config emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::config_ private
Definition at line 76 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by EmergencyResponseVehiclePlugin(), generateBSM(), handle_on_activate(), handle_on_configure(), parameter_update_callback(), and poseCallback().
current_latitude_
double emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::current_latitude_ private
Definition at line 91 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by generateBSM(), and poseCallback().
current_longitude_
double emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::current_longitude_ private
Definition at line 92 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by generateBSM(), and poseCallback().
current_velocity_
double emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::current_velocity_ private
Definition at line 93 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by generateBSM(), and twistCallback().
emergency_lights_active_
bool emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::emergency_lights_active_ = false private
Definition at line 96 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by generateBSM(), and processIncomingUdpBinary().
emergency_sirens_active_
bool emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::emergency_sirens_active_ = false private
Definition at line 97 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by generateBSM(), and processIncomingUdpBinary().
emergency_vehicle_ui_warnings_pub_
carma_ros2_utils::PubPtr<carma_msgs::msg::UIInstructions> emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::emergency_vehicle_ui_warnings_pub_ private
Definition at line 70 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by handle_on_configure(), and incomingEmergencyVehicleResponseCallback().
incoming_emergency_vehicle_response_sub_
carma_ros2_utils::SubPtr<carma_v2x_msgs::msg::EmergencyVehicleResponse> emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::incoming_emergency_vehicle_response_sub_ private
Definition at line 63 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by handle_on_configure().
io_
std::unique_ptr<boost::asio::io_service> emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::io_ private
Definition at line 105 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by connect(), and handle_on_shutdown().
io_thread_
std::shared_ptr<std::thread> emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::io_thread_ private
Definition at line 104 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by connect(), and handle_on_shutdown().
logger_name_
std::string emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::logger_name_ = "emergency_response_vehicle_plugin_node" private
Definition at line 100 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by arrivedAtEmergencyDestinationCallback(), connect(), handle_on_activate(), handle_on_configure(), loadRouteDestinationPointsFromFile(), poseCallback(), and processIncomingUdpBinary().
outgoing_bsm_pub_
carma_ros2_utils::PubPtr<carma_v2x_msgs::msg::BSM> emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::outgoing_bsm_pub_ private
Definition at line 68 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by handle_on_configure(), and publishBSM().
outgoing_emergency_vehicle_ack_pub_
carma_ros2_utils::PubPtr<carma_v2x_msgs::msg::EmergencyVehicleAck> emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::outgoing_emergency_vehicle_ack_pub_ private
Definition at line 69 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by broadcastEmergencyVehicleAck(), and handle_on_configure().
pose_sub_
carma_ros2_utils::SubPtr<gps_msgs::msg::GPSFix> emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::pose_sub_ private
Definition at line 64 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by handle_on_configure().
prev_msg_count_
uint8_t emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::prev_msg_count_ = 0 private
Definition at line 88 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by generateBSM().
route_destination_points_
std::vector<carma_v2x_msgs::msg::Position3D> emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::route_destination_points_ private
Definition at line 82 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by arrivedAtEmergencyDestinationCallback(), generateBSM(), loadRouteDestinationPointsFromFile(), and poseCallback().
twist_sub_
carma_ros2_utils::SubPtr<geometry_msgs::msg::TwistStamped> emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::twist_sub_ private
Definition at line 65 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by handle_on_configure().
udp_listener_
std::unique_ptr<UDPListener> emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::udp_listener_ private
Definition at line 108 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by connect().
work_
std::shared_ptr<boost::asio::io_service::work> emergency_response_vehicle_plugin::EmergencyResponseVehiclePlugin::work_ private
Definition at line 103 of file emergency_response_vehicle_plugin_node.hpp.
Referenced by connect(), and handle_on_shutdown().
The documentation for this class was generated from the following files:
carma-messenger-core/emergency_response_vehicle_plugin/include/emergency_response_vehicle_plugin/emergency_response_vehicle_plugin_node.hpp
carma-messenger-core/emergency_response_vehicle_plugin/src/emergency_response_vehicle_plugin_node.cpp