Carma-platform: j2735_convertor::Node Class Reference
j2735_convertor::Node Class Reference
Is the class responsible for conversion of j2735_msgs to cav_msgs.
#include <j2735_convertor_node.hpp>
Public Member Functions
Node (const rclcpp::NodeOptions &)
Node constructor.
void BsmHandler (const carma_v2x_msgs::msg::BSM::UniquePtr message)
Converts carma_v2x_msgs::msg::BSM messages to j2735_v2x_msgs::msg::BSM and publishes the converted messages.
void j2735BsmHandler (j2735_v2x_msgs::msg::BSM::UniquePtr message)
Converts j2735_v2x_msgs::msg::BSM messages to carma_v2x_msgs::msg::BSM and publishes the converted messages.
void PsmHandler (const carma_v2x_msgs::msg::PSM::UniquePtr message)
Converts carma_v2x_msgs::msg::PSM messages to j2735_v2x_msgs::msg::PSM and publishes the converted messages.
void j2735PsmHandler (j2735_v2x_msgs::msg::PSM::UniquePtr message)
Converts j2735_v2x_msgs::msg::PSM messages to carma_v2x_msgs::msg::PSM and publishes the converted messages.
void j2735SpatHandler (j2735_v2x_msgs::msg::SPAT::UniquePtr message)
Converts j2735_v2x_msgs::msg::SPAT messages to carma_v2x_msgs::msg::SPAT and publishes the converted messages.
void j2735MapHandler (j2735_v2x_msgs::msg::MapData::UniquePtr message)
Converts j2735_v2x_msgs::msg::MapData messages to carma_v2x_msgs::msg::MapData and publishes the converted messages.
void ControlMessageHandler (carma_v2x_msgs::msg::TrafficControlMessage::UniquePtr message)
Converts carma_v2x_msgs::msg::TrafficControlMessage messages to j2735_v2x_msgs::msg::TrafficControlMessage and publishes the converted messages.
void j2735ControlMessageHandler (j2735_v2x_msgs::msg::TrafficControlMessage::UniquePtr message)
Converts j2735_v2x_msgs::msg::TrafficControlMessage messages to carma_v2x_msgs::msg::TrafficControlMessage and publishes the converted messages.
void ControlRequestHandler (carma_v2x_msgs::msg::TrafficControlRequest::UniquePtr message)
Converts carma_v2x_msgs::msg::ControlRequest messages to j2735_v2x_msgs::msg::ControlRequest and publishes the converted messages.
void j2735ControlRequestHandler (j2735_v2x_msgs::msg::TrafficControlRequest::UniquePtr message)
Converts j2735_v2x_msgs::msg::ControlRequest messages to carma_v2x_msgs::msg::ControlRequest and publishes the converted messages.
void SdsmHandler (const carma_v2x_msgs::msg::SensorDataSharingMessage::UniquePtr message)
void j3224SdsmHandler (j3224_v2x_msgs::msg::SensorDataSharingMessage::UniquePtr message)
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &)
Private Attributes
carma_ros2_utils::SubPtr< j2735_v2x_msgs::msg::BSM > j2735_bsm_sub_
carma_ros2_utils::SubPtr< j2735_v2x_msgs::msg::PSM > j2735_psm_sub_
carma_ros2_utils::SubPtr< j2735_v2x_msgs::msg::SPAT > j2735_spat_sub_
carma_ros2_utils::SubPtr< j2735_v2x_msgs::msg::MapData > j2735_map_sub_
carma_ros2_utils::SubPtr< j3224_v2x_msgs::msg::SensorDataSharingMessage > j3224_sdsm_sub_
carma_ros2_utils::SubPtr< carma_v2x_msgs::msg::BSM > outbound_bsm_sub_
carma_ros2_utils::SubPtr< carma_v2x_msgs::msg::PSM > outbound_psm_sub_
carma_ros2_utils::SubPtr< carma_v2x_msgs::msg::SensorDataSharingMessage > outbound_sdsm_sub_
carma_ros2_utils::SubPtr< j2735_v2x_msgs::msg::TrafficControlMessage > j2735_geofence_control_sub_
carma_ros2_utils::SubPtr< j2735_v2x_msgs::msg::TrafficControlRequest > j2735_geofence_request_sub_
carma_ros2_utils::SubPtr< carma_v2x_msgs::msg::TrafficControlMessage > outbound_geofence_control_sub_
carma_ros2_utils::SubPtr< carma_v2x_msgs::msg::TrafficControlRequest > outbound_geofence_request_sub_
carma_ros2_utils::PubPtr< carma_v2x_msgs::msg::BSM > converted_bsm_pub_
carma_ros2_utils::PubPtr< carma_v2x_msgs::msg::PSM > converted_psm_pub_
carma_ros2_utils::PubPtr< carma_v2x_msgs::msg::SPAT > converted_spat_pub_
carma_ros2_utils::PubPtr< carma_v2x_msgs::msg::MapData > converted_map_pub_
carma_ros2_utils::PubPtr< carma_v2x_msgs::msg::SensorDataSharingMessage > converted_sdsm_pub_
carma_ros2_utils::PubPtr< j2735_v2x_msgs::msg::BSM > outbound_j2735_bsm_pub_
carma_ros2_utils::PubPtr< j2735_v2x_msgs::msg::PSM > outbound_j2735_psm_pub_
carma_ros2_utils::PubPtr< j3224_v2x_msgs::msg::SensorDataSharingMessage > outbound_j3224_sdsm_pub_
carma_ros2_utils::PubPtr< j2735_v2x_msgs::msg::TrafficControlMessage > outbound_j2735_geofence_control_pub_
carma_ros2_utils::PubPtr< j2735_v2x_msgs::msg::TrafficControlRequest > outbound_j2735_geofence_request_pub_
carma_ros2_utils::PubPtr< carma_v2x_msgs::msg::TrafficControlMessage > converted_geofence_control_pub_
carma_ros2_utils::PubPtr< carma_v2x_msgs::msg::TrafficControlRequest > converted_geofence_request_pub_
Detailed Description
Is the class responsible for conversion of j2735_msgs to cav_msgs.
The J2735Convertor is a ROS Node which subscribes to topics containing messages from the j2735_msgs package. The j2735_msgs are then converted to cav_msgs types including any necessary unit conversions.
Each j2735 topic has its own thread for processing. This will help prevent larger message types like Map from blocking small high frequency message types like BSMs.
Other subscribed topics like system_alert are handled on the default global queue
When an internal exception is triggered the node will first broadcast a FATAL message to the system_alert topic before shutting itself down. This node will also shut itself down on receive of a SHUTDOWN message from system_alert
Definition at line 54 of file j2735_convertor_node.hpp.
Constructor & Destructor Documentation
Node()
j2735_convertor::Node::Node (const rclcpp::NodeOptions & options) explicit
Node constructor.
Definition at line 22 of file j2735_convertor_node.cpp.
      : carma_ros2_utils::CarmaLifecycleNode(options)
  {}
Member Function Documentation
BsmHandler()
void j2735_convertor::Node::BsmHandler (const carma_v2x_msgs::msg::BSM::UniquePtr message)
Converts carma_v2x_msgs::msg::BSM messages to j2735_v2x_msgs::msg::BSM and publishes the converted messages.
Parameters
message The message to convert
Definition at line 145 of file j2735_convertor_node.cpp.
  {
    j2735_v2x_msgs::msg::BSM j2735_msg;
    BSMConvertor::convert(*message, j2735_msg);  // Convert message
    outbound_j2735_bsm_pub_->publish(j2735_msg);  // Publish converted message
  }
References j2735_convertor::BSMConvertor::convert(), and outbound_j2735_bsm_pub_.
Referenced by handle_on_configure().
ControlMessageHandler()
void j2735_convertor::Node::ControlMessageHandler (carma_v2x_msgs::msg::TrafficControlMessage::UniquePtr message)
Converts carma_v2x_msgs::msg::TrafficControlMessage messages to j2735_v2x_msgs::msg::TrafficControlMessage and publishes the converted messages.
Parameters
message The message to convert
Definition at line 187 of file j2735_convertor_node.cpp.
{
    j2735_v2x_msgs::msg::TrafficControlMessage converted_msg;
    j2735_convertor::geofence_control::convert(*message, converted_msg);  // Convert message
    outbound_j2735_geofence_control_pub_->publish(converted_msg);       // Publish converted message
  }
References j2735_convertor::geofence_control::convert(), and outbound_j2735_geofence_control_pub_.
Referenced by handle_on_configure().
ControlRequestHandler()
void j2735_convertor::Node::ControlRequestHandler (carma_v2x_msgs::msg::TrafficControlRequest::UniquePtr message)
Converts carma_v2x_msgs::msg::ControlRequest messages to j2735_v2x_msgs::msg::ControlRequest and publishes the converted messages.
Parameters
message The message to convert
Definition at line 199 of file j2735_convertor_node.cpp.
{
    j2735_v2x_msgs::msg::TrafficControlRequest converted_msg;
    j2735_convertor::geofence_request::convert(*message, converted_msg);  // Convert message
    outbound_j2735_geofence_request_pub_->publish(converted_msg);       // Publish converted message
  }
References j2735_convertor::geofence_request::convert(), and outbound_j2735_geofence_request_pub_.
Referenced by handle_on_configure().
handle_on_configure()
carma_ros2_utils::CallbackReturn j2735_convertor::Node::handle_on_configure (const rclcpp_lifecycle::State &)
Definition at line 27 of file j2735_convertor_node.cpp.
  {
      // J2735 BSM Subscriber
    auto j2735_bsm_cb_group = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    rclcpp::SubscriptionOptions j2735_bsm_options;
    j2735_bsm_options.callback_group = j2735_bsm_cb_group;
    j2735_bsm_sub_ = create_subscription<j2735_v2x_msgs::msg::BSM>("incoming_j2735_bsm", 100, std::bind(&Node::j2735BsmHandler, this, std_ph::_1), j2735_bsm_options);
    // BSM Publisher
    converted_bsm_pub_ = create_publisher<carma_v2x_msgs::msg::BSM>("incoming_bsm", 100);
    // Outgoing J2735 BSM Subscriber
    auto outbound_bsm_cb_group = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    rclcpp::SubscriptionOptions outbound_bsm_options;
    outbound_bsm_options.callback_group = outbound_bsm_cb_group;
    outbound_bsm_sub_ = create_subscription<carma_v2x_msgs::msg::BSM>("outgoing_bsm", 1, std::bind(&Node::BsmHandler,
                                          this, std_ph::_1), outbound_bsm_options);  // Queue size of 1 as we should never publish outdated BSMs
    // BSM Publisher
    outbound_j2735_bsm_pub_ = create_publisher<j2735_v2x_msgs::msg::BSM>("outgoing_j2735_bsm", 1);  // Queue size of 1 as we should never publish outdated BSMs
    // J2735 PSM Subscriber
    auto j2735_psm_cb_group = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    rclcpp::SubscriptionOptions j2735_psm_options;
    j2735_psm_options.callback_group = j2735_psm_cb_group;
    j2735_psm_sub_ = create_subscription<j2735_v2x_msgs::msg::PSM>("incoming_j2735_psm", 100, std::bind(&Node::j2735PsmHandler, this, std_ph::_1), j2735_psm_options);
    // PSM Publisher
    converted_psm_pub_ = create_publisher<carma_v2x_msgs::msg::PSM>("incoming_psm", 100);
    // Outgoing J2735 PSM Subscriber
    auto outbound_psm_cb_group = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    rclcpp::SubscriptionOptions outbound_psm_options;
    outbound_psm_options.callback_group = outbound_psm_cb_group;
    outbound_psm_sub_ = create_subscription<carma_v2x_msgs::msg::PSM>("outgoing_psm", 1, std::bind(&Node::PsmHandler,
                                          this, std_ph::_1), outbound_psm_options);  // Queue size of 1 as we should never publish outdated PSMs
    // PSM Publisher
    outbound_j2735_psm_pub_ = create_publisher<j2735_v2x_msgs::msg::PSM>("outgoing_j2735_psm", 1);  // Queue size of 1 as we should never publish outdated PSMs
    // J2735 SPAT Subscriber
    auto j2735_spat_cb_group = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    rclcpp::SubscriptionOptions j2735_spat_options;
    j2735_spat_options.callback_group = j2735_bsm_cb_group;
    j2735_spat_sub_ = create_subscription<j2735_v2x_msgs::msg::SPAT>("incoming_j2735_spat", 100, std::bind(&Node::j2735SpatHandler, this, std_ph::_1), j2735_spat_options);
    // SPAT Publisher TODO think about queue sizes
    converted_spat_pub_ = create_publisher<carma_v2x_msgs::msg::SPAT>("incoming_spat", 100);
    // J2735 MAP Subscriber
    auto j2735_map_cb_group = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    rclcpp::SubscriptionOptions j2735_map_options;
    j2735_map_options.callback_group = j2735_map_cb_group;
    j2735_map_sub_ = create_subscription<j2735_v2x_msgs::msg::MapData>("incoming_j2735_map", 50, std::bind(&Node::j2735MapHandler, this, std_ph::_1), j2735_map_options);
    // MAP Publisher TODO think about queue sizes
    converted_map_pub_ = create_publisher<carma_v2x_msgs::msg::MapData>("incoming_map", 50);
    // Added, check namespace and standards ///////////////////////////////////////////////////////
    // J3224 SDSM Subscriber
    auto j3224_sdsm_cb_group = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    rclcpp::SubscriptionOptions j3224_sdsm_options;
    j3224_sdsm_options.callback_group = j3224_sdsm_cb_group;
    j3224_sdsm_sub_ = create_subscription<j3224_v2x_msgs::msg::SensorDataSharingMessage>("incoming_j3224_sdsm", 100, std::bind(&Node::j3224SdsmHandler, this, std_ph::_1), j3224_sdsm_options);
    // SDSM carma Publisher
    converted_sdsm_pub_ = create_publisher<carma_v2x_msgs::msg::SensorDataSharingMessage>("incoming_sdsm", 100);
    // Outgoing J3224 SDSM Subscriber
    auto outbound_sdsm_cb_group = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    rclcpp::SubscriptionOptions outbound_sdsm_options;
    outbound_sdsm_options.callback_group = outbound_sdsm_cb_group;
    outbound_sdsm_sub_ = create_subscription<carma_v2x_msgs::msg::SensorDataSharingMessage>("outgoing_sdsm", 1, std::bind(&Node::SdsmHandler,
                                          this, std_ph::_1), outbound_sdsm_options);  // Queue size of 1 as we should never publish outdated PSMs
    // SDSM j3224 Publisher
    outbound_j3224_sdsm_pub_ = create_publisher<j3224_v2x_msgs::msg::SensorDataSharingMessage>("outgoing_j3224_sdsm", 1);
    // End of SDSM pub/sub ///////////////////////////////////////////////////////
    // Incoming geofence pub/sub
    converted_geofence_control_pub_ = create_publisher<carma_v2x_msgs::msg::TrafficControlMessage>("incoming_geofence_control", 50);
    converted_geofence_request_pub_ = create_publisher<carma_v2x_msgs::msg::TrafficControlRequest>("incoming_geofence_request", 50);
    auto j2735_geofence_control_cb_group = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    rclcpp::SubscriptionOptions j2735_geofence_control_options;
    j2735_geofence_control_options.callback_group = j2735_geofence_control_cb_group;
    j2735_geofence_control_sub_ = create_subscription<j2735_v2x_msgs::msg::TrafficControlMessage>("incoming_j2735_geofence_control", 50, std::bind(&Node::j2735ControlMessageHandler, this, std_ph::_1), j2735_geofence_control_options);
    auto j2735_geofence_request_cb_group = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    rclcpp::SubscriptionOptions j2735_geofence_request_options;
    j2735_geofence_request_options.callback_group = j2735_geofence_request_cb_group;
    j2735_geofence_request_sub_ = create_subscription<j2735_v2x_msgs::msg::TrafficControlRequest>("incoming_j2735_geofence_request", 50, std::bind(&Node::j2735ControlRequestHandler, this, std_ph::_1), j2735_geofence_request_options);
    // Outgoing geofence pub/sub
    auto outbound_geofence_control_cb_group = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    rclcpp::SubscriptionOptions outbound_geofence_control_options;
    outbound_geofence_control_options.callback_group = outbound_geofence_control_cb_group;
    outbound_geofence_control_sub_ = create_subscription<carma_v2x_msgs::msg::TrafficControlMessage>("outgoing_geofence_control", 50, std::bind(&Node::ControlMessageHandler, this, std_ph::_1), outbound_geofence_control_options);
    auto outbound_geofence_request_cb_group = create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);
    rclcpp::SubscriptionOptions outbound_geofence_request_options;
    outbound_geofence_request_options.callback_group = outbound_geofence_request_cb_group;
    outbound_geofence_request_sub_ = create_subscription<carma_v2x_msgs::msg::TrafficControlRequest>("outgoing_geofence_request", 50, std::bind(&Node::ControlRequestHandler, this, std_ph::_1), outbound_geofence_request_options);
    outbound_j2735_geofence_control_pub_ = create_publisher<j2735_v2x_msgs::msg::TrafficControlMessage>("outgoing_j2735_geofence_control", 10);
    outbound_j2735_geofence_request_pub_ = create_publisher<j2735_v2x_msgs::msg::TrafficControlRequest>("outgoing_j2735_geofence_request", 10);
    // Return success if everthing initialized successfully
    return CallbackReturn::SUCCESS;
  }
References BsmHandler(), ControlMessageHandler(), ControlRequestHandler(), converted_bsm_pub_, converted_geofence_control_pub_, converted_geofence_request_pub_, converted_map_pub_, converted_psm_pub_, converted_sdsm_pub_, converted_spat_pub_, j2735_bsm_sub_, j2735_geofence_control_sub_, j2735_geofence_request_sub_, j2735_map_sub_, j2735_psm_sub_, j2735_spat_sub_, j2735BsmHandler(), j2735ControlMessageHandler(), j2735ControlRequestHandler(), j2735MapHandler(), j2735PsmHandler(), j2735SpatHandler(), j3224_sdsm_sub_, j3224SdsmHandler(), outbound_bsm_sub_, outbound_geofence_control_sub_, outbound_geofence_request_sub_, outbound_j2735_bsm_pub_, outbound_j2735_geofence_control_pub_, outbound_j2735_geofence_request_pub_, outbound_j2735_psm_pub_, outbound_j3224_sdsm_pub_, outbound_psm_sub_, outbound_sdsm_sub_, PsmHandler(), and SdsmHandler().
j2735BsmHandler()
void j2735_convertor::Node::j2735BsmHandler (j2735_v2x_msgs::msg::BSM::UniquePtr message)
Converts j2735_v2x_msgs::msg::BSM messages to carma_v2x_msgs::msg::BSM and publishes the converted messages.
Parameters
message The message to convert
Definition at line 152 of file j2735_convertor_node.cpp.
  {
    carma_v2x_msgs::msg::BSM converted_msg;
    BSMConvertor::convert(*message, converted_msg);  // Convert message
    converted_bsm_pub_->publish(converted_msg);       // Publish converted message
  }
References j2735_convertor::BSMConvertor::convert(), and converted_bsm_pub_.
Referenced by handle_on_configure().
j2735ControlMessageHandler()
void j2735_convertor::Node::j2735ControlMessageHandler (j2735_v2x_msgs::msg::TrafficControlMessage::UniquePtr message)
Converts j2735_v2x_msgs::msg::TrafficControlMessage messages to carma_v2x_msgs::msg::TrafficControlMessage and publishes the converted messages.
Parameters
message The message to convert
Definition at line 193 of file j2735_convertor_node.cpp.
{
    carma_v2x_msgs::msg::TrafficControlMessage converted_msg;
    j2735_convertor::geofence_control::convert(*message, converted_msg);  // Convert message
    converted_geofence_control_pub_->publish(converted_msg);       // Publish converted message
  }
References j2735_convertor::geofence_control::convert(), and converted_geofence_control_pub_.
Referenced by handle_on_configure().
j2735ControlRequestHandler()
void j2735_convertor::Node::j2735ControlRequestHandler (j2735_v2x_msgs::msg::TrafficControlRequest::UniquePtr message)
Converts j2735_v2x_msgs::msg::ControlRequest messages to carma_v2x_msgs::msg::ControlRequest and publishes the converted messages.
Parameters
message The message to convert
Definition at line 205 of file j2735_convertor_node.cpp.
{
    carma_v2x_msgs::msg::TrafficControlRequest converted_msg;
    j2735_convertor::geofence_request::convert(*message, converted_msg);  // Convert message
    converted_geofence_request_pub_->publish(converted_msg);       // Publish converted message
  }
References j2735_convertor::geofence_request::convert(), and converted_geofence_request_pub_.
Referenced by handle_on_configure().
j2735MapHandler()
void j2735_convertor::Node::j2735MapHandler (j2735_v2x_msgs::msg::MapData::UniquePtr message)
Converts j2735_v2x_msgs::msg::MapData messages to carma_v2x_msgs::msg::MapData and publishes the converted messages.
Parameters
message The message to convert
Definition at line 180 of file j2735_convertor_node.cpp.
  {
    carma_v2x_msgs::msg::MapData converted_msg;
    MapConvertor::convert(*message, converted_msg);  // Convert message
    converted_map_pub_->publish(converted_msg);       // Publish converted message
  }
References j2735_convertor::MapConvertor::convert(), and converted_map_pub_.
Referenced by handle_on_configure().
j2735PsmHandler()
void j2735_convertor::Node::j2735PsmHandler (j2735_v2x_msgs::msg::PSM::UniquePtr message)
Converts j2735_v2x_msgs::msg::PSM messages to carma_v2x_msgs::msg::PSM and publishes the converted messages.
Parameters
message The message to convert
Definition at line 166 of file j2735_convertor_node.cpp.
  {
    carma_v2x_msgs::msg::PSM converted_msg;
    PSMConvertor::convert(*message, converted_msg);  // Convert message
    converted_psm_pub_->publish(converted_msg);       // Publish converted message
  }
References j2735_convertor::PSMConvertor::convert(), and converted_psm_pub_.
Referenced by handle_on_configure().
j2735SpatHandler()
void j2735_convertor::Node::j2735SpatHandler (j2735_v2x_msgs::msg::SPAT::UniquePtr message)
Converts j2735_v2x_msgs::msg::SPAT messages to carma_v2x_msgs::msg::SPAT and publishes the converted messages.
Parameters
message The message to convert
Definition at line 173 of file j2735_convertor_node.cpp.
  {
    carma_v2x_msgs::msg::SPAT converted_msg;
    SPATConvertor::convert(*message, converted_msg);  // Convert message
    converted_spat_pub_->publish(converted_msg);       // Publish converted message
  }
References j2735_convertor::SPATConvertor::convert(), and converted_spat_pub_.
Referenced by handle_on_configure().
j3224SdsmHandler()
void j2735_convertor::Node::j3224SdsmHandler (j3224_v2x_msgs::msg::SensorDataSharingMessage::UniquePtr message)
Definition at line 219 of file j2735_convertor_node.cpp.
  {
    carma_v2x_msgs::msg::SensorDataSharingMessage converted_msg;
    SDSMConvertor::convert(*message, converted_msg);  // Convert message
    converted_sdsm_pub_->publish(converted_msg);       // Publish converted message
  }
References j2735_convertor::SDSMConvertor::convert(), and converted_sdsm_pub_.
Referenced by handle_on_configure().
PsmHandler()
void j2735_convertor::Node::PsmHandler (const carma_v2x_msgs::msg::PSM::UniquePtr message)
Converts carma_v2x_msgs::msg::PSM messages to j2735_v2x_msgs::msg::PSM and publishes the converted messages.
Parameters
message The message to convert
Definition at line 159 of file j2735_convertor_node.cpp.
  {
    j2735_v2x_msgs::msg::PSM j2735_msg;
    PSMConvertor::convert(*message, j2735_msg);  // Convert message
    outbound_j2735_psm_pub_->publish(j2735_msg);  // Publish converted message
  }
References j2735_convertor::PSMConvertor::convert(), and outbound_j2735_psm_pub_.
Referenced by handle_on_configure().
SdsmHandler()
void j2735_convertor::Node::SdsmHandler (const carma_v2x_msgs::msg::SensorDataSharingMessage::UniquePtr message)
Definition at line 212 of file j2735_convertor_node.cpp.
  {
    j3224_v2x_msgs::msg::SensorDataSharingMessage j3224_msg;
    SDSMConvertor::convert(*message, j3224_msg);  // Convert message
    outbound_j3224_sdsm_pub_->publish(j3224_msg);  // Publish converted message
  }
References j2735_convertor::SDSMConvertor::convert(), and outbound_j3224_sdsm_pub_.
Referenced by handle_on_configure().
Member Data Documentation
converted_bsm_pub_
carma_ros2_utils::PubPtr<carma_v2x_msgs::msg::BSM> j2735_convertor::Node::converted_bsm_pub_ private
Definition at line 73 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure(), and j2735BsmHandler().
converted_geofence_control_pub_
carma_ros2_utils::PubPtr<carma_v2x_msgs::msg::TrafficControlMessage> j2735_convertor::Node::converted_geofence_control_pub_ private
Definition at line 83 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure(), and j2735ControlMessageHandler().
converted_geofence_request_pub_
carma_ros2_utils::PubPtr<carma_v2x_msgs::msg::TrafficControlRequest> j2735_convertor::Node::converted_geofence_request_pub_ private
Definition at line 84 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure(), and j2735ControlRequestHandler().
converted_map_pub_
carma_ros2_utils::PubPtr<carma_v2x_msgs::msg::MapData> j2735_convertor::Node::converted_map_pub_ private
Definition at line 76 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure(), and j2735MapHandler().
converted_psm_pub_
carma_ros2_utils::PubPtr<carma_v2x_msgs::msg::PSM> j2735_convertor::Node::converted_psm_pub_ private
Definition at line 74 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure(), and j2735PsmHandler().
converted_sdsm_pub_
carma_ros2_utils::PubPtr<carma_v2x_msgs::msg::SensorDataSharingMessage> j2735_convertor::Node::converted_sdsm_pub_ private
Definition at line 77 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure(), and j3224SdsmHandler().
converted_spat_pub_
carma_ros2_utils::PubPtr<carma_v2x_msgs::msg::SPAT> j2735_convertor::Node::converted_spat_pub_ private
Definition at line 75 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure(), and j2735SpatHandler().
j2735_bsm_sub_
carma_ros2_utils::SubPtr<j2735_v2x_msgs::msg::BSM> j2735_convertor::Node::j2735_bsm_sub_ private
Definition at line 59 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure().
j2735_geofence_control_sub_
carma_ros2_utils::SubPtr<j2735_v2x_msgs::msg::TrafficControlMessage> j2735_convertor::Node::j2735_geofence_control_sub_ private
Definition at line 67 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure().
j2735_geofence_request_sub_
carma_ros2_utils::SubPtr<j2735_v2x_msgs::msg::TrafficControlRequest> j2735_convertor::Node::j2735_geofence_request_sub_ private
Definition at line 68 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure().
j2735_map_sub_
carma_ros2_utils::SubPtr<j2735_v2x_msgs::msg::MapData> j2735_convertor::Node::j2735_map_sub_ private
Definition at line 62 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure().
j2735_psm_sub_
carma_ros2_utils::SubPtr<j2735_v2x_msgs::msg::PSM> j2735_convertor::Node::j2735_psm_sub_ private
Definition at line 60 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure().
j2735_spat_sub_
carma_ros2_utils::SubPtr<j2735_v2x_msgs::msg::SPAT> j2735_convertor::Node::j2735_spat_sub_ private
Definition at line 61 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure().
j3224_sdsm_sub_
carma_ros2_utils::SubPtr<j3224_v2x_msgs::msg::SensorDataSharingMessage> j2735_convertor::Node::j3224_sdsm_sub_ private
Definition at line 63 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure().
outbound_bsm_sub_
carma_ros2_utils::SubPtr<carma_v2x_msgs::msg::BSM> j2735_convertor::Node::outbound_bsm_sub_ private
Definition at line 64 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure().
outbound_geofence_control_sub_
carma_ros2_utils::SubPtr<carma_v2x_msgs::msg::TrafficControlMessage> j2735_convertor::Node::outbound_geofence_control_sub_ private
Definition at line 69 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure().
outbound_geofence_request_sub_
carma_ros2_utils::SubPtr<carma_v2x_msgs::msg::TrafficControlRequest> j2735_convertor::Node::outbound_geofence_request_sub_ private
Definition at line 70 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure().
outbound_j2735_bsm_pub_
carma_ros2_utils::PubPtr<j2735_v2x_msgs::msg::BSM> j2735_convertor::Node::outbound_j2735_bsm_pub_ private
Definition at line 78 of file j2735_convertor_node.hpp.
Referenced by BsmHandler(), and handle_on_configure().
outbound_j2735_geofence_control_pub_
carma_ros2_utils::PubPtr<j2735_v2x_msgs::msg::TrafficControlMessage> j2735_convertor::Node::outbound_j2735_geofence_control_pub_ private
Definition at line 81 of file j2735_convertor_node.hpp.
Referenced by ControlMessageHandler(), and handle_on_configure().
outbound_j2735_geofence_request_pub_
carma_ros2_utils::PubPtr<j2735_v2x_msgs::msg::TrafficControlRequest> j2735_convertor::Node::outbound_j2735_geofence_request_pub_ private
Definition at line 82 of file j2735_convertor_node.hpp.
Referenced by ControlRequestHandler(), and handle_on_configure().
outbound_j2735_psm_pub_
carma_ros2_utils::PubPtr<j2735_v2x_msgs::msg::PSM> j2735_convertor::Node::outbound_j2735_psm_pub_ private
Definition at line 79 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure(), and PsmHandler().
outbound_j3224_sdsm_pub_
carma_ros2_utils::PubPtr<j3224_v2x_msgs::msg::SensorDataSharingMessage> j2735_convertor::Node::outbound_j3224_sdsm_pub_ private
Definition at line 80 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure(), and SdsmHandler().
outbound_psm_sub_
carma_ros2_utils::SubPtr<carma_v2x_msgs::msg::PSM> j2735_convertor::Node::outbound_psm_sub_ private
Definition at line 65 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure().
outbound_sdsm_sub_
carma_ros2_utils::SubPtr<carma_v2x_msgs::msg::SensorDataSharingMessage> j2735_convertor::Node::outbound_sdsm_sub_ private
Definition at line 66 of file j2735_convertor_node.hpp.
Referenced by handle_on_configure().
The documentation for this class was generated from the following files:
carma-messenger-core/j2735_convertor/include/j2735_convertor/j2735_convertor_node.hpp
carma-messenger-core/j2735_convertor/src/j2735_convertor_node.cpp