Carma-platform: cpp_message::BSM_Message Class Reference
cpp_message::BSM_Message Class Reference
#include <BSM_Message.h>
Public Member Functions
BSM_Message (rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging)
constructor
boost::optional< j2735_v2x_msgs::msg::BSM > decode_bsm_message (std::vector< uint8_t > &binary_array)
BSM message decoding function.
boost::optional< std::vector< uint8_t > > encode_bsm_message (const j2735_v2x_msgs::msg::BSM &plainMessage)
helper functions for BSM message encoding.
Public Attributes
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging_
Static Private Attributes
static const int BSM_TEST_ID =20
Detailed Description
Definition at line 21 of file BSM_Message.h.
Constructor & Destructor Documentation
BSM_Message()
cpp_message::BSM_Message::BSM_Message (rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging) inline explicit
constructor
Definition at line 34 of file BSM_Message.h.
{
            node_logging_ = node_logging;
        };
References node_logging_.
Member Function Documentation
decode_bsm_message()
boost::optional< j2735_v2x_msgs::msg::BSM > cpp_message::BSM_Message::decode_bsm_message (std::vector< uint8_t > & binary_array)
BSM message decoding function.
Parameters
binary_array Container with binary input.
Returns
decoded ros message, returns ROS warning and an empty optional if decoding fails.
Definition at line 25 of file BSM_Message.cpp.
{
        j2735_v2x_msgs::msg::BSM output;
        //decode results - stored in binary_array
        asn_dec_rval_t rval;
        MessageFrame_t* message = nullptr;
        //copy from vector to array
        size_t len=binary_array.size();
        uint8_t buf[len];
        std::copy(binary_array.begin(),binary_array.end(),buf);
        //use asn1c lib to decode
        rval=uper_decode(0, &asn_DEF_MessageFrame,(void **) &message, buf, len, 0, 0);
        //if decode success
        if(rval.code==RC_OK)
        {
            BSMcoreData_t core_data_msg = message->value.choice.BasicSafetyMessage.coreData;
            output.core_data.msg_count = core_data_msg.msgCnt;
            auto id_len = core_data_msg.id.size;
            for(auto i = 0; i < id_len; i++)
            {
                output.core_data.id.push_back(core_data_msg.id.buf[i]);
            }
            output.core_data.sec_mark = core_data_msg.secMark;
            output.core_data.latitude = core_data_msg.lat;
            output.core_data.longitude = core_data_msg.Long;
            output.core_data.elev = core_data_msg.elev;
            output.core_data.accuracy.orientation = core_data_msg.accuracy.orientation;
            output.core_data.accuracy.semi_major = core_data_msg.accuracy.semiMajor;
            output.core_data.accuracy.semi_minor = core_data_msg.accuracy.semiMinor;
            output.core_data.transmission.transmission_state = core_data_msg.transmission;
            output.core_data.speed = core_data_msg.speed;
            output.core_data.heading = core_data_msg.heading;
            output.core_data.angle = core_data_msg.angle;
            output.core_data.accel_set.lateral = core_data_msg.accelSet.lat;
            output.core_data.accel_set.longitudinal =core_data_msg.accelSet.Long;
            output.core_data.accel_set.vert = core_data_msg.accelSet.vert;
            output.core_data.accel_set.yaw_rate = core_data_msg.accelSet.yaw;
            // brake_applied_status decoding
            // e.g. make 0b0100000 to 0b0000100
            uint8_t binary = core_data_msg.brakes.wheelBrakes.buf[0] >> 3;
            unsigned int brake_applied_status_type = 4;
            // e.g. shift the binary right until it equals to 1 (0b00000001) to determine the location of the non-zero bit
            for (int i = 0; i < 4; i ++)
            {
                if ((int)binary == 1)
                {
                    output.core_data.brakes.wheel_brakes.brake_applied_status = brake_applied_status_type;
                    break;
                }
                else
                {
                    brake_applied_status_type -= 1;
                    binary = binary >> 1;
                }
            }
            output.core_data.brakes.traction.traction_control_status = core_data_msg.brakes.traction;
            output.core_data.brakes.abs.anti_lock_brake_status = core_data_msg.brakes.abs;
            output.core_data.brakes.scs.stability_control_status = core_data_msg.brakes.scs;
            output.core_data.brakes.brake_boost.brake_boost_applied = core_data_msg.brakes.brakeBoost;
            output.core_data.brakes.aux_brakes.auxiliary_brake_status = core_data_msg.brakes.auxBrakes;
            output.core_data.size.vehicle_length = core_data_msg.size.length;
            output.core_data.size.vehicle_width = core_data_msg.size.width;
            return boost::optional<j2735_v2x_msgs::msg::BSM>(output);
        }
        RCLCPP_WARN_STREAM( node_logging_->get_logger(), "BasicSafetyMessage decoding failed");
        return boost::optional<j2735_v2x_msgs::msg::BSM>{};
    }
References BrakeSystemStatus::abs, BSMcoreData::accelSet, BSMcoreData::accuracy, BSMcoreData::angle, asn_DEF_MessageFrame, BrakeSystemStatus::auxBrakes, BrakeSystemStatus::brakeBoost, BSMcoreData::brakes, BIT_STRING_s::buf, OCTET_STRING::buf, asn_dec_rval_s::code, BSMcoreData::elev, BSMcoreData::heading, BSMcoreData::id, AccelerationSet4Way::lat, BSMcoreData::lat, VehicleSize::length, AccelerationSet4Way::Long, BSMcoreData::Long, BSMcoreData::msgCnt, node_logging_, PositionalAccuracy::orientation, RC_OK, BrakeSystemStatus::scs, BSMcoreData::secMark, PositionalAccuracy::semiMajor, PositionalAccuracy::semiMinor, BSMcoreData::size, OCTET_STRING::size, BSMcoreData::speed, BrakeSystemStatus::traction, BSMcoreData::transmission, uper_decode(), AccelerationSet4Way::vert, BrakeSystemStatus::wheelBrakes, VehicleSize::width, and AccelerationSet4Way::yaw.
Referenced by cpp_message::Node::inbound_binary_callback().
encode_bsm_message()
boost::optional< std::vector< uint8_t > > cpp_message::BSM_Message::encode_bsm_message (const j2735_v2x_msgs::msg::BSM & plainMessage)
helper functions for BSM message encoding.
Parameters
plainMessage contains BSM ros message.
Returns
encoded byte array, returns ROS warning and an empty optional if encoding fails.
Definition at line 100 of file BSM_Message.cpp.
    {
        //Uncomment below (and one line at the end of the function) to print the message in human readable form
        //FILE *fp;
        //fp = fopen("/absolute/directory/log_C.txt", "w");
        //fprintf(fp, "encodeBSM function is called\n");
        //encode result placeholder
        uint8_t buffer[544];
        size_t buffer_size=sizeof(buffer);
        asn_enc_rval_t ec;
        MessageFrame_t message;
        //set message type to BasicSafetyMessage
        message.messageId = 20;
        message.value.present = MessageFrame__value_PR_BasicSafetyMessage;
        BasicSafetyMessage bsm_msg;
        bsm_msg.partII = nullptr;
        bsm_msg.regional = nullptr;
        // Encode coreData
        BSMcoreData_t core_data;
        core_data.msgCnt = plain_msg.core_data.msg_count;
        //Set the fields
        uint8_t id_content[4] = {0};
        for(auto i = 0; i < 4; i++)
        {
            id_content[i] = (char) plain_msg.core_data.id[i];
        }
        TemporaryID_t temp_id;
        temp_id.buf = id_content;
        temp_id.size = 4;
        core_data.id = temp_id;
        core_data.secMark = plain_msg.core_data.sec_mark;
        core_data.lat = plain_msg.core_data.latitude;
        core_data.Long = plain_msg.core_data.longitude;
        core_data.elev = plain_msg.core_data.elev;
        PositionalAccuracy_t pos_acc;
        pos_acc.orientation = plain_msg.core_data.accuracy.orientation;
        pos_acc.semiMajor = plain_msg.core_data.accuracy.semi_major;
        pos_acc.semiMinor = plain_msg.core_data.accuracy.semi_minor;
        core_data.accuracy = pos_acc;
        core_data.transmission = plain_msg.core_data.transmission.transmission_state;
        core_data.speed = plain_msg.core_data.speed;
        core_data.heading = plain_msg.core_data.heading;
        core_data.angle = plain_msg.core_data.angle;
        AccelerationSet4Way_t accel;
        accel.lat = plain_msg.core_data.accel_set.lateral;
        accel.Long = plain_msg.core_data.accel_set.longitudinal;
        accel.vert= plain_msg.core_data.accel_set.vert;
        accel.yaw = plain_msg.core_data.accel_set.yaw_rate;
        core_data.accelSet = accel;
        VehicleSize_t vehicle_size;
        vehicle_size.length = plain_msg.core_data.size.vehicle_length;
        vehicle_size.width = plain_msg.core_data.size.vehicle_width;
        core_data.size = vehicle_size;
        BrakeSystemStatus_t brakes;
        brakes.traction = plain_msg.core_data.brakes.traction.traction_control_status;
        brakes.abs = plain_msg.core_data.brakes.abs.anti_lock_brake_status;
        brakes.scs = plain_msg.core_data.brakes.scs.stability_control_status;
        brakes.brakeBoost = plain_msg.core_data.brakes.brake_boost.brake_boost_applied;
        brakes.auxBrakes = plain_msg.core_data.brakes.aux_brakes.auxiliary_brake_status;
        BrakeAppliedStatus_t brake_applied_status;
        uint8_t wheel_brake[1] = {8}; // dummy 8 value
        // there are 3 unused bits in the end: 0b000
        // which makes every possible encoded value to be multiples of 8: 0b00001000 (8), 0b00010000 (16), 0b00011000 (24) etc
        // so num in brackets indicate the position in the bit string:
        // unavailable: 0b10000000, leftFront: 0b01000000 etc
        wheel_brake[0] = (char) (8 << (4 - plain_msg.core_data.brakes.wheel_brakes.brake_applied_status));
        brake_applied_status.buf = wheel_brake;
        brake_applied_status.size = 1;
        brake_applied_status.bits_unused = 3;
        brakes.wheelBrakes = brake_applied_status;
        core_data.brakes = brakes;
        bsm_msg.coreData = core_data;
        message.value.choice.BasicSafetyMessage = bsm_msg;
        //encode message
        ec=uper_encode_to_buffer(&asn_DEF_MessageFrame, 0 , &message , buffer , buffer_size);
        // Uncomment below to enable logging in human readable form
        //asn_fprint(fp, &asn_DEF_MessageFrame, message);
        //log a warning if that fails
        if(ec.encoded == -1) {
            RCLCPP_WARN_STREAM( node_logging_->get_logger(), "Encoding for BasicSafetyMessage has failed");
            std::cout << "Failed: " << ec.failed_type->name << std::endl;
            return boost::optional<std::vector<uint8_t>>{};
        }
        //copy to byte array msg
        size_t array_length=(ec.encoded + 7) / 8;
        std::vector<uint8_t> b_array(array_length);
        for(size_t i=0;i<array_length;i++)b_array[i]=buffer[i];
        //Debugging/Unit Testing
        //for(size_t i = 0; i < array_length; i++) std::cout<< int(b_array[i])<< ", ";
        return boost::optional<std::vector<uint8_t>>(b_array);
    }
References BrakeSystemStatus::abs, BSMcoreData::accelSet, BSMcoreData::accuracy, BSMcoreData::angle, asn_DEF_MessageFrame, BrakeSystemStatus::auxBrakes, BIT_STRING_s::bits_unused, BrakeSystemStatus::brakeBoost, BSMcoreData::brakes, BIT_STRING_s::buf, OCTET_STRING::buf, BasicSafetyMessage::coreData, BSMcoreData::elev, asn_enc_rval_s::encoded, asn_enc_rval_s::failed_type, BSMcoreData::heading, BSMcoreData::id, AccelerationSet4Way::lat, BSMcoreData::lat, VehicleSize::length, AccelerationSet4Way::Long, BSMcoreData::Long, MessageFrame__value_PR_BasicSafetyMessage, BSMcoreData::msgCnt, asn_TYPE_descriptor_s::name, node_logging_, PositionalAccuracy::orientation, BasicSafetyMessage::partII, BasicSafetyMessage::regional, BrakeSystemStatus::scs, BSMcoreData::secMark, PositionalAccuracy::semiMajor, PositionalAccuracy::semiMinor, BIT_STRING_s::size, BSMcoreData::size, OCTET_STRING::size, BSMcoreData::speed, BrakeSystemStatus::traction, BSMcoreData::transmission, uper_encode_to_buffer(), AccelerationSet4Way::vert, BrakeSystemStatus::wheelBrakes, VehicleSize::width, and AccelerationSet4Way::yaw.
Referenced by cpp_message::Node::outbound_bsm_message_callback().
Member Data Documentation
BSM_TEST_ID
const int cpp_message::BSM_Message::BSM_TEST_ID =20 static private
Definition at line 25 of file BSM_Message.h.
node_logging_
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr cpp_message::BSM_Message::node_logging_
Definition at line 29 of file BSM_Message.h.
Referenced by BSM_Message(), decode_bsm_message(), and encode_bsm_message().
The documentation for this class was generated from the following files:
carma-messenger-core/cpp_message/include/cpp_message/BSM_Message.h
carma-messenger-core/cpp_message/src/BSM_Message.cpp