Carma-platform: cpp_message::Mobility_Response Class Reference
cpp_message::Mobility_Response Class Reference
#include <MobilityResponse_Message.h>
Public Member Functions
Mobility_Response (rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging)
constructor
boost::optional< carma_v2x_msgs::msg::MobilityResponse > decode_mobility_response_message (std::vector< uint8_t > &binary_array)
Mobility Response message decoding function.
boost::optional< std::vector< uint8_t > > encode_mobility_response_message (carma_v2x_msgs::msg::MobilityResponse plainMessage)
Mobility Response message encoding function.
Public Attributes
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging_
Static Private Attributes
static const int MOBILITY_RESPONSE_TEST_ID =241
static const int URGENCY_MIN =0
static const int URGENCY_MAX =1000
static const int URGENCY_UNKNOWN =0
Detailed Description
Definition at line 21 of file MobilityResponse_Message.h.
Constructor & Destructor Documentation
Mobility_Response()
cpp_message::Mobility_Response::Mobility_Response (rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr node_logging) inline explicit
constructor
Definition at line 34 of file MobilityResponse_Message.h.
{
                node_logging_ = node_logging;
            };
References node_logging_.
Member Function Documentation
decode_mobility_response_message()
boost::optional< carma_v2x_msgs::msg::MobilityResponse > cpp_message::Mobility_Response::decode_mobility_response_message (std::vector< uint8_t > & binary_array)
Mobility Response message decoding function.
Parameters
binary_array Container with binary input.
Returns
decoded ros message, returns ROS warning and an empty message if decoding fails.
Definition at line 26 of file MobilityResponse_Message.cpp.
    {
        carma_v2x_msgs::msg::MobilityHeader header;
        carma_v2x_msgs::msg::MobilityResponse output;
        //decode results - stored in binary_array
        asn_dec_rval_t rval;
        MessageFrame_t* message=nullptr;
        //copy from vector to array
        size_t len=binary_array.size();
        uint8_t buf[len];
        std::copy(binary_array.begin(),binary_array.end(),buf);
        //use asn1c lib to decode
        rval=uper_decode(0, &asn_DEF_MessageFrame,(void **) &message, buf, len, 0, 0);
        if(rval.code==RC_OK){
            Mobility_Header Header_constant;
            std::string sender_id, recipient_id, sender_bsm_id, plan_id;
            uint64_t timestamp;
            //get sender id
            size_t str_len=message->value.choice.TestMessage01.header.hostStaticId.size;
            if(str_len<=Header_constant.STATIC_ID_MAX_LENGTH && str_len>=Header_constant.STATIC_ID_MIN_LENGTH)
            {
                for(size_t i=0;i<str_len;i++){
                    sender_id +=message->value.choice.TestMessage01.header.hostStaticId.buf[i];
                }
            }
            else sender_id=Header_constant.STRING_DEFAULT;
            header.sender_id=sender_id;
            //get recepient id
            str_len=message->value.choice.TestMessage01.header.targetStaticId.size;
            if(str_len<=Header_constant.STATIC_ID_MAX_LENGTH && str_len>=Header_constant.STATIC_ID_MIN_LENGTH)
            {
                for(size_t i=0;i<str_len;i++){
                    recipient_id +=message->value.choice.TestMessage01.header.targetStaticId.buf[i];
                }
            }
            else recipient_id=Header_constant.STRING_DEFAULT;
            header.recipient_id=recipient_id;
            //get bsm id
            str_len=message->value.choice.TestMessage01.header.hostBSMId.size;
            for(size_t i=0;i<str_len;i++){
                sender_bsm_id +=message->value.choice.TestMessage01.header.hostBSMId.buf[i];
            }
            if(str_len<Header_constant.BSM_ID_LENGTH){
                sender_bsm_id=std::string((Header_constant.BSM_ID_DEFAULT.size()-str_len),'0').append(sender_bsm_id);
            }
            else if(str_len>Header_constant.BSM_ID_LENGTH){
                RCLCPP_WARN(node_logging_->get_logger(),"BSM ID -size greater than limit, changing to default");
                sender_bsm_id=Header_constant.BSM_ID_DEFAULT;
            }
            header.sender_bsm_id=sender_bsm_id;
            //get plan id
            str_len=message->value.choice.TestMessage01.header.planId.size;
            if(str_len==Header_constant.GUID_LENGTH)
            {
                for(size_t i=0;i<str_len;i++){
                    plan_id +=message->value.choice.TestMessage01.header.planId.buf[i];
                }
            }
            else plan_id=Header_constant.GUID_DEFAULT;
            header.plan_id=plan_id;
            //recover uint64_t timestamp from string
            str_len=message->value.choice.TestMessage01.header.timestamp.size;
            timestamp=0;
            for(size_t i=0;i<str_len;i++){
                timestamp*=10;
                timestamp+=int(message->value.choice.TestMessage01.header.timestamp.buf[i])-'0';
            }
            header.timestamp=timestamp;
            output.m_header=header;
            //get urgency from long to uint16
            long tmp=message->value.choice.TestMessage01.body.urgency;
            if(tmp>URGENCY_MAX || tmp<URGENCY_MIN){
                RCLCPP_WARN_STREAM( node_logging_->get_logger(), "Urgency message out of range");
                ASN_STRUCT_FREE(asn_DEF_MessageFrame, message);
                return boost::optional<carma_v2x_msgs::msg::MobilityResponse>{};
            }
            output.urgency=tmp;
            //get isaccepted bool
            bool isAccepted=message->value.choice.TestMessage01.body.isAccepted;
            output.is_accepted=isAccepted;
            //get the mobility plan choice
            MobilityPlanType_t planType_choice = message->value.choice.TestMessage01.body.planType;
            output.plan_type.type = planType_choice;
            //get the mobility reason choice
            MobilityReason_t reason_choice = *message->value.choice.TestMessage01.body.reason;
            output.reason.reason = reason_choice;
            //get the mobility repeat choice
            MobilityRepeat_t repeat_choice = *message->value.choice.TestMessage01.body.repeat;
            output.repeat.repeat = repeat_choice;
            ASN_STRUCT_FREE(asn_DEF_MessageFrame, message);
            return boost::optional<carma_v2x_msgs::msg::MobilityResponse>(output);
        }
        //else return an empty object
        RCLCPP_WARN_STREAM( node_logging_->get_logger(), "Decoding mobility response message failed");
        ASN_STRUCT_FREE(asn_DEF_MessageFrame, message);
        return boost::optional<carma_v2x_msgs::msg::MobilityResponse>{};
    }
References asn_DEF_MessageFrame, ASN_STRUCT_FREE, cpp_message::Mobility_Header::BSM_ID_DEFAULT, cpp_message::Mobility_Header::BSM_ID_LENGTH, asn_dec_rval_s::code, cpp_message::Mobility_Header::GUID_DEFAULT, cpp_message::Mobility_Header::GUID_LENGTH, node_logging_, RC_OK, cpp_message::Mobility_Header::STATIC_ID_MIN_LENGTH, cpp_message::Mobility_Header::STRING_DEFAULT, uper_decode(), URGENCY_MAX, and URGENCY_MIN.
Referenced by cpp_message::Node::inbound_binary_callback().
encode_mobility_response_message()
boost::optional< std::vector< uint8_t > > cpp_message::Mobility_Response::encode_mobility_response_message (carma_v2x_msgs::msg::MobilityResponse plainMessage)
Mobility Response message encoding function.
Parameters
plainMessage contains mobility response ros message to be encoded as byte array.
Returns
encoded byte array, returns ROS warning and an empty optional if encoding fails.
Definition at line 144 of file MobilityResponse_Message.cpp.
    {
        //encode result placeholder
        uint8_t buffer[1472];
        size_t buffer_size=sizeof(buffer);
        asn_enc_rval_t ec;
        auto message_shared = std::make_shared<MessageFrame_t>();
        MessageFrame_t* message = message_shared.get();
        //set message type to TestMessage01
        message->messageId=MOBILITY_RESPONSE_TEST_ID;
        message->value.present=MessageFrame__value_PR_TestMessage01;
        //convert host_id string to char array
        Mobility_Header Header;
        std::string sender_id=plainMessage.m_header.sender_id;
        size_t string_size=sender_id.size();
        if(string_size<Header.STATIC_ID_MIN_LENGTH || string_size>Header.STATIC_ID_MAX_LENGTH){
            RCLCPP_WARN(node_logging_->get_logger(),"Unacceptable host id value, changing to default");
            sender_id=Header.STRING_DEFAULT;
            string_size=Header.STRING_DEFAULT.size();
        }
        uint8_t string_content_hostId[string_size];
        for(size_t i=0;i<string_size;i++)
        {
            string_content_hostId[i]=sender_id[i];
        }
        message->value.choice.TestMessage01.header.hostStaticId.buf=string_content_hostId;
        message->value.choice.TestMessage01.header.hostStaticId.size=string_size;
        //convert target_id string to char array
        std::string recipient_id=plainMessage.m_header.recipient_id;
        string_size=recipient_id.size();
        if(string_size<Header.STATIC_ID_MIN_LENGTH || string_size>Header.STATIC_ID_MAX_LENGTH){
            RCLCPP_WARN(node_logging_->get_logger(),"Unacceptable recipient id value, changing to default");
            recipient_id=Header.STRING_DEFAULT;
            string_size=Header.STRING_DEFAULT.size();
        }
        uint8_t string_content_targetId[string_size];
        for(size_t i=0;i<string_size;i++)
        {
            string_content_targetId[i]=recipient_id[i];
        }
        message->value.choice.TestMessage01.header.targetStaticId.buf=string_content_targetId;
        message->value.choice.TestMessage01.header.targetStaticId.size=string_size;
         //convert bsm_id string to char array
        std::string sender_bsm_id=plainMessage.m_header.sender_bsm_id;
        string_size=sender_bsm_id.size();
        if(string_size<Header.BSM_ID_DEFAULT.size()){
            sender_bsm_id=std::string((Header.BSM_ID_DEFAULT.size()-string_size),'0').append(sender_bsm_id);
        }
        else if(string_size>Header.BSM_ID_DEFAULT.size()){
            RCLCPP_WARN(node_logging_->get_logger(),"Unacceptable BSM ID, changing to default");
            sender_bsm_id=Header.BSM_ID_DEFAULT;
        }
        string_size=Header.BSM_ID_DEFAULT.size();
        uint8_t string_content_BSMId[string_size];
        for(size_t i=0;i<string_size;i++)
        {
            string_content_BSMId[i]=sender_bsm_id[i];
        }
        message->value.choice.TestMessage01.header.hostBSMId.buf=string_content_BSMId;
        message->value.choice.TestMessage01.header.hostBSMId.size=string_size;
         //convert plan_id string to char array
        std::string plan_id=plainMessage.m_header.plan_id;
        string_size=plan_id.size();
        if(string_size!=Header.GUID_LENGTH){
            RCLCPP_WARN(node_logging_->get_logger(),"Unacceptable GUID, changing to default");
            plan_id=Header.GUID_DEFAULT;
            string_size=Header.GUID_LENGTH;
        }
        uint8_t string_content_planId[string_size];
        for(size_t i=0;i<string_size;i++)
        {
            string_content_planId[i]=plan_id[i];
        }
        message->value.choice.TestMessage01.header.planId.buf=string_content_planId;
        message->value.choice.TestMessage01.header.planId.size=string_size;
        //get timestamp and convert to char array
        uint64_t time=plainMessage.m_header.timestamp;
        std::string timestamp=std::to_string(time);
        string_size=timestamp.size();
        if(string_size<Header.TIMESTAMP_MESSAGE_LENGTH){
            timestamp=std::string(Header.TIMESTAMP_MESSAGE_LENGTH-string_size,'0').append(timestamp);
        }
        else if(string_size>Header.TIMESTAMP_MESSAGE_LENGTH){
            RCLCPP_WARN(node_logging_->get_logger(),"Unacceptable timestamp value, changing to default");
            timestamp=std::string(Header.TIMESTAMP_MESSAGE_LENGTH,'0');
        }
        string_size=Header.TIMESTAMP_MESSAGE_LENGTH;
        uint8_t string_content_timestamp[string_size];
        for(size_t i=0;i<string_size;i++)
        {
            string_content_timestamp[i]=timestamp[i];
        }
        message->value.choice.TestMessage01.header.timestamp.buf=string_content_timestamp;
        message->value.choice.TestMessage01.header.timestamp.size=string_size;
        //get urgency
        uint16_t urgency=plainMessage.urgency;
        if(urgency<URGENCY_MIN || urgency> URGENCY_MAX) urgency=URGENCY_UNKNOWN;
        message->value.choice.TestMessage01.body.urgency=urgency;
        //get isAccepted
        message->value.choice.TestMessage01.body.isAccepted=plainMessage.is_accepted;
        //get plantype
        message->value.choice.TestMessage01.body.planType = plainMessage.plan_type.type;
        //get reason
        long reason_choice = plainMessage.reason.reason;
        message->value.choice.TestMessage01.body.reason = &reason_choice;
        //get repeat
        long repeat_choice = plainMessage.repeat.repeat;
        message->value.choice.TestMessage01.body.repeat = &repeat_choice;
        //encode message
        ec=uper_encode_to_buffer(&asn_DEF_MessageFrame, 0 , message , buffer , buffer_size);
        //log a warning if that fails
        if(ec.encoded == -1) {
            RCLCPP_WARN_STREAM( node_logging_->get_logger(), "Encoding for Mobility Response Message failed");
            return boost::optional<std::vector<uint8_t>>{};
        }
        //copy to byte array msg
        size_t array_length=(ec.encoded + 7) / 8;
        std::vector<uint8_t> b_array(array_length);
        for(size_t i=0;i<array_length;i++)b_array[i]=buffer[i];
        // for(size_t i = 0; i < array_length; i++) std::cout<< int(b_array[i])<< ", ";
        return boost::optional<std::vector<uint8_t>>(b_array);
    }
References asn_DEF_MessageFrame, asn_enc_rval_s::encoded, MessageFrame__value_PR_TestMessage01, MOBILITY_RESPONSE_TEST_ID, node_logging_, uper_encode_to_buffer(), URGENCY_MAX, and URGENCY_UNKNOWN.
Referenced by cpp_message::Node::outbound_mobility_response_message_callback().
Member Data Documentation
MOBILITY_RESPONSE_TEST_ID
const int cpp_message::Mobility_Response::MOBILITY_RESPONSE_TEST_ID =241 static private
Definition at line 24 of file MobilityResponse_Message.h.
Referenced by encode_mobility_response_message().
node_logging_
rclcpp::node_interfaces::NodeLoggingInterface::SharedPtr cpp_message::Mobility_Response::node_logging_
Definition at line 39 of file MobilityResponse_Message.h.
Referenced by Mobility_Response(), decode_mobility_response_message(), and encode_mobility_response_message().
URGENCY_MAX
const int cpp_message::Mobility_Response::URGENCY_MAX =1000 static private
Definition at line 26 of file MobilityResponse_Message.h.
Referenced by decode_mobility_response_message(), and encode_mobility_response_message().
URGENCY_MIN
const int cpp_message::Mobility_Response::URGENCY_MIN =0 static private
Definition at line 25 of file MobilityResponse_Message.h.
Referenced by decode_mobility_response_message().
URGENCY_UNKNOWN
const int cpp_message::Mobility_Response::URGENCY_UNKNOWN =0 static private
Definition at line 27 of file MobilityResponse_Message.h.
Referenced by encode_mobility_response_message().
The documentation for this class was generated from the following files:
carma-messenger-core/cpp_message/include/cpp_message/MobilityResponse_Message.h
carma-messenger-core/cpp_message/src/MobilityResponse_Message.cpp