Carma-platform: truck_inspection_plugin::Node Class Reference
truck_inspection_plugin::Node Class Reference
#include <truck_inspection_plugin_node.hpp>
Public Member Functions
Node (const rclcpp::NodeOptions &)
Node constructor.
rcl_interfaces::msg::SetParametersResult parameter_update_callback (const std::vector< rclcpp::Parameter > &parameters)
callback for dynamic parameter updates
void mobilityOperationCallback (carma_v2x_msgs::msg::MobilityOperation::UniquePtr msg)
subscription callback
void inspectionRequestCallback (std::shared_ptr< rmw_request_id_t > header, std::shared_ptr< std_srvs::srv::Trigger::Request > request, std::shared_ptr< std_srvs::srv::Trigger::Response > response)
service callback
bool isSafetyLogValid (const std::string &log)
bool isADSAutoEngaged (const std::string &log)
carma_ros2_utils::CallbackReturn handle_on_configure (const rclcpp_lifecycle::State &)
void content_pub_timer_callback ()
Private Attributes
carma_ros2_utils::SubPtr< carma_v2x_msgs::msg::MobilityOperation > mo_sub_
carma_ros2_utils::PubPtr< std_msgs::msg::String > content_pub_
carma_ros2_utils::PubPtr< carma_v2x_msgs::msg::MobilityRequest > mr_pub_
carma_ros2_utils::PubPtr< std_msgs::msg::String > cav_detection_pub_
carma_ros2_utils::ServicePtr< std_srvs::srv::Trigger > inspection_request_service_server_
Config config_
const std::string INSPECTION_STRATEGY = "TruckInspection"
int number_of_entries
std::string safety_log_
rclcpp::TimerBase::SharedPtr content_pub_timer_
Detailed Description
Definition at line 33 of file truck_inspection_plugin_node.hpp.
Constructor & Destructor Documentation
Node()
truck_inspection_plugin::Node::Node (const rclcpp::NodeOptions & options) explicit
Node constructor.
Definition at line 22 of file truck_inspection_plugin_node.cpp.
      : carma_ros2_utils::CarmaLifecycleNode(options)
  {
    // Create initial config
    config_ = Config();
    // Declare parameters
    config_.num_of_entries = declare_parameter<int>("num_of_entries", config_.num_of_entries);
  }
References config_, and truck_inspection_plugin::Config::num_of_entries.
Member Function Documentation
content_pub_timer_callback()
void truck_inspection_plugin::Node::content_pub_timer_callback ()
Definition at line 78 of file truck_inspection_plugin_node.cpp.
  {
          if(!this->safety_log_.empty()) {
                std_msgs::msg::String msg_content;
                msg_content.data = this->safety_log_;
                content_pub_->publish(msg_content);
          }
  }
References content_pub_, and safety_log_.
Referenced by handle_on_configure().
handle_on_configure()
carma_ros2_utils::CallbackReturn truck_inspection_plugin::Node::handle_on_configure (const rclcpp_lifecycle::State &)
Definition at line 43 of file truck_inspection_plugin_node.cpp.
  {
    // Reset config
    config_ = Config();
    // Load parameters
    get_parameter<int>("num_of_entries", config_.num_of_entries);
    // Register runtime parameter update callback
    add_on_set_parameters_callback(std::bind(&Node::parameter_update_callback, this, std_ph::_1));
    // Setup subscribers
    mo_sub_ = create_subscription<carma_v2x_msgs::msg::MobilityOperation>("mobility_operation_inbound", 5,
                                                              std::bind(&Node::mobilityOperationCallback, this, std_ph::_1));
    // Setup publishers
    mr_pub_ = create_publisher<carma_v2x_msgs::msg::MobilityRequest>("mobility_request_outbound", 5);
    cav_detection_pub_ = create_publisher<std_msgs::msg::String>("cav_truck_identified", 5);
    content_pub_ = create_publisher<std_msgs::msg::String>("truck_safety_info", 5);
    // Setup service servers
    inspection_request_service_server_ = create_service<std_srvs::srv::Trigger>("send_inspection_request",std::bind(&Node::inspectionRequestCallback, this, std_ph::_1, std_ph::_2, std_ph::_3));
    content_pub_timer_ = create_timer(
    get_clock(),
    std::chrono::milliseconds(50),
    std::bind(&Node::content_pub_timer_callback, this));
    RCLCPP_INFO_STREAM(this->get_logger(), "Truck inspection plugin is initialized...");
    // Return success if everthing initialized successfully
    return CallbackReturn::SUCCESS;
  }
References cav_detection_pub_, config_, content_pub_, content_pub_timer_, content_pub_timer_callback(), inspection_request_service_server_, inspectionRequestCallback(), mo_sub_, mobilityOperationCallback(), mr_pub_, truck_inspection_plugin::Config::num_of_entries, and parameter_update_callback().
inspectionRequestCallback()
void truck_inspection_plugin::Node::inspectionRequestCallback (std::shared_ptr< rmw_request_id_t > header, std::shared_ptr< std_srvs::srv::Trigger::Request > request, std::shared_ptr< std_srvs::srv::Trigger::Response > response)
service callback
Definition at line 88 of file truck_inspection_plugin_node.cpp.
  {
        carma_v2x_msgs::msg::MobilityRequest msg;
        msg.strategy = Node::INSPECTION_STRATEGY;
        mr_pub_->publish(msg);
        // reset safety log
        this->safety_log_ = "";
        response->success = true;
  }
References INSPECTION_STRATEGY, mr_pub_, and safety_log_.
Referenced by handle_on_configure().
isADSAutoEngaged()
bool truck_inspection_plugin::Node::isADSAutoEngaged (const std::string & log)
isSafetyLogValid()
bool truck_inspection_plugin::Node::isSafetyLogValid (const std::string & log)
Definition at line 122 of file truck_inspection_plugin_node.cpp.
  {
      // Check 1: if number of k-v pairs matches expectation
      std::string temp;
      int count = 0;
      std::stringstream ss(log);
      while(std::getline(ss, temp, ','))
      {
          if(!temp.empty())
          {
              count++;
          }
          else
          {
              // do not allow spaces in the safety log
              return false;
          }
      }
      return count == this->number_of_entries;
  }
References number_of_entries.
Referenced by mobilityOperationCallback().
mobilityOperationCallback()
void truck_inspection_plugin::Node::mobilityOperationCallback (carma_v2x_msgs::msg::MobilityOperation::UniquePtr msg)
subscription callback
Definition at line 100 of file truck_inspection_plugin_node.cpp.
  {
        // if there is a truck around running CARMA
        if(msg->strategy == Node::INSPECTION_STRATEGY)
        {
            // if the incoming message contains a valid safety log
            if(isSafetyLogValid(msg->strategy_params))
            {
                safety_log_ = msg->strategy_params;
                safety_log_ += ",timestamp:" + std::to_string(msg->m_header.timestamp);
            } else {
                std_msgs::msg::String msg_out;
                std::string k_v_pair = msg->strategy_params;
                // get only VIN number, state and license plate
                msg_out.data = k_v_pair;
                // publish message to show there is a cav truck in the radio range of the ego-vehicle
                cav_detection_pub_->publish(msg_out);
            }
        }
  }
References cav_detection_pub_, INSPECTION_STRATEGY, isSafetyLogValid(), and safety_log_.
Referenced by handle_on_configure().
parameter_update_callback()
rcl_interfaces::msg::SetParametersResult truck_inspection_plugin::Node::parameter_update_callback (const std::vector< rclcpp::Parameter > & parameters)
callback for dynamic parameter updates
Definition at line 32 of file truck_inspection_plugin_node.cpp.
  {
    auto error = update_params<int>({{"num_of_entries", config_.num_of_entries}}, parameters);
    rcl_interfaces::msg::SetParametersResult result;
    result.successful = !error;
    return result;
  }
References config_, and truck_inspection_plugin::Config::num_of_entries.
Referenced by handle_on_configure().
Member Data Documentation
cav_detection_pub_
carma_ros2_utils::PubPtr<std_msgs::msg::String> truck_inspection_plugin::Node::cav_detection_pub_ private
Definition at line 43 of file truck_inspection_plugin_node.hpp.
Referenced by handle_on_configure(), and mobilityOperationCallback().
config_
Config truck_inspection_plugin::Node::config_ private
Definition at line 49 of file truck_inspection_plugin_node.hpp.
Referenced by Node(), handle_on_configure(), and parameter_update_callback().
content_pub_
carma_ros2_utils::PubPtr<std_msgs::msg::String> truck_inspection_plugin::Node::content_pub_ private
Definition at line 41 of file truck_inspection_plugin_node.hpp.
Referenced by content_pub_timer_callback(), and handle_on_configure().
content_pub_timer_
rclcpp::TimerBase::SharedPtr truck_inspection_plugin::Node::content_pub_timer_ private
Definition at line 56 of file truck_inspection_plugin_node.hpp.
Referenced by handle_on_configure().
inspection_request_service_server_
carma_ros2_utils::ServicePtr<std_srvs::srv::Trigger> truck_inspection_plugin::Node::inspection_request_service_server_ private
Definition at line 46 of file truck_inspection_plugin_node.hpp.
Referenced by handle_on_configure().
INSPECTION_STRATEGY
const std::string truck_inspection_plugin::Node::INSPECTION_STRATEGY = "TruckInspection" private
Definition at line 51 of file truck_inspection_plugin_node.hpp.
Referenced by inspectionRequestCallback(), and mobilityOperationCallback().
mo_sub_
carma_ros2_utils::SubPtr<carma_v2x_msgs::msg::MobilityOperation> truck_inspection_plugin::Node::mo_sub_ private
Definition at line 38 of file truck_inspection_plugin_node.hpp.
Referenced by handle_on_configure().
mr_pub_
carma_ros2_utils::PubPtr<carma_v2x_msgs::msg::MobilityRequest> truck_inspection_plugin::Node::mr_pub_ private
Definition at line 42 of file truck_inspection_plugin_node.hpp.
Referenced by handle_on_configure(), and inspectionRequestCallback().
number_of_entries
int truck_inspection_plugin::Node::number_of_entries private
Definition at line 52 of file truck_inspection_plugin_node.hpp.
Referenced by isSafetyLogValid().
safety_log_
std::string truck_inspection_plugin::Node::safety_log_ private
Definition at line 53 of file truck_inspection_plugin_node.hpp.
Referenced by content_pub_timer_callback(), inspectionRequestCallback(), and mobilityOperationCallback().
The documentation for this class was generated from the following files:
carma-messenger-core/truck_inspection_plugin/include/truck_inspection_plugin/truck_inspection_plugin_node.hpp
carma-messenger-core/truck_inspection_plugin/src/truck_inspection_plugin_node.cpp