Carma-platform: j2735_convertor::geofence_request Namespace Reference
j2735_convertor::geofence_request Namespace Reference
Namespace responsible for converting j2735 style Geofence request messages to CARMA usable control messages.
Functions
void convert (const j2735_v2x_msgs::msg::OffsetPoint &in_msg, carma_v2x_msgs::msg::OffsetPoint &out_msg, const int8_t scale)
Convert the contents of a j2735_v2x_msgs::msg::OffsetPoint into a carma_v2x_msgs::msg::OffsetPoint.
void convert (const j2735_v2x_msgs::msg::TrafficControlBounds &in_msg, carma_v2x_msgs::msg::TrafficControlBounds &out_msg, const int8_t scale)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlBounds into a carma_v2x_msgs::msg::TrafficControlBounds.
void convert (const j2735_v2x_msgs::msg::TrafficControlRequestV01 &in_msg, carma_v2x_msgs::msg::TrafficControlRequestV01 &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlRequestV01 into a carma_v2x_msgs::msg::TrafficControlRequestV01.
void convert (const j2735_v2x_msgs::msg::TrafficControlRequest &in_msg, carma_v2x_msgs::msg::TrafficControlRequest &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlRequest into a carma_v2x_msgs::msg::TrafficControlRequest.
void convert (const carma_v2x_msgs::msg::TrafficControlBounds &in_msg, j2735_v2x_msgs::msg::TrafficControlBounds &out_msg, const int8_t scale)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlBounds into a j2735_v2x_msgs::msg::TrafficControlBounds.
void convert (const carma_v2x_msgs::msg::TrafficControlRequestV01 &in_msg, j2735_v2x_msgs::msg::TrafficControlRequestV01 &out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlRequestV01 into a j2735_v2x_msgs::msg::TrafficControlRequestV01.
void convert (const carma_v2x_msgs::msg::TrafficControlRequest &in_msg, j2735_v2x_msgs::msg::TrafficControlRequest &out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlRequest into a j2735_v2x_msgs::msg::TrafficControlRequest.
bool isIntegerDivisable (const std::vector< double > &data, int16_t divisor)
bool isLessThan (const std::vector< double > &data, int16_t threshold)
Detailed Description
Namespace responsible for converting j2735 style Geofence request messages to CARMA usable control messages.
Handles conversion between ControlRequest in the j2735_msgs and cav_msgs packages. Unit conversions and presence flags are also handled
Function Documentation
convert() [1/7]
void j2735_convertor::geofence_request::convert (const carma_v2x_msgs::msg::TrafficControlBounds & in_msg, j2735_v2x_msgs::msg::TrafficControlBounds & out_msg, const int8_t scale)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlBounds into a j2735_v2x_msgs::msg::TrafficControlBounds.
Parameters
in_msg The message to be converted
out_msg The message to store the output
scale The scaling exponent to apply to the bound position. Units applied as 10^n. This normally comes from a ControlRequest message. The scaling here should be the same as what would appear in the ControlRequest (ie. it is not an inverted scaling)
Exceptions
std::invalid_argument If the provided scale will result in a value that does not fit within the 16 bit int bounds of the out message.
Unit conversions and presence flags are handled
Definition at line 121 of file control_request_convertor.cpp.
{
  rclcpp::Time oldest(in_msg.oldest.sec , in_msg.oldest.nanosec);
  out_msg.oldest = oldest.seconds() / units::SEC_PER_MIN;
  out_msg.reflat = in_msg.reflat * units::TENTH_MICRO_DEG_PER_DEG;
  out_msg.reflon = in_msg.reflon * units::TENTH_MICRO_DEG_PER_DEG;
  double scaled_deltax0 = in_msg.offsets[0].deltax / pow(10, scale);
  double scaled_deltay0 = in_msg.offsets[0].deltay / pow(10, scale);
  double scaled_deltax1 = in_msg.offsets[1].deltax / pow(10, scale);
  double scaled_deltay1 = in_msg.offsets[1].deltay / pow(10, scale);
  double scaled_deltax2 = in_msg.offsets[2].deltax / pow(10, scale);
  double scaled_deltay2 = in_msg.offsets[2].deltay / pow(10, scale);
  // Check bounds of message storage ability
  constexpr int INT_16_MIN = -32768;
  constexpr int INT_16_MAX = 32767;
  if (scaled_deltax0 < INT_16_MIN || INT_16_MAX < scaled_deltax0 ||
      scaled_deltay0 < INT_16_MIN || INT_16_MAX < scaled_deltay0 ||
      scaled_deltax1 < INT_16_MIN || INT_16_MAX < scaled_deltax1 ||
      scaled_deltay1 < INT_16_MIN || INT_16_MAX < scaled_deltay1 ||
      scaled_deltax2 < INT_16_MIN || INT_16_MAX < scaled_deltay2 ||
      scaled_deltay2 < INT_16_MIN || INT_16_MAX < scaled_deltay2 )
  {
    throw std::invalid_argument("carma_v2x_msgs::msg::ControlBounds cannot be converted because the provided bounds cannot be scaled into the 16 bit integer range without reducing precision below 1m.");
  }
  out_msg.offsets[0].deltax=scaled_deltax0;
  out_msg.offsets[0].deltay=scaled_deltay0;
  out_msg.offsets[1].deltax=scaled_deltax1;
  out_msg.offsets[1].deltay=scaled_deltay1;
  out_msg.offsets[2].deltax=scaled_deltax2;
  out_msg.offsets[2].deltay=scaled_deltay2;
}
References j2735_convertor::units::SEC_PER_MIN, and j2735_convertor::units::TENTH_MICRO_DEG_PER_DEG.
convert() [2/7]
void j2735_convertor::geofence_request::convert (const carma_v2x_msgs::msg::TrafficControlRequest & in_msg, j2735_v2x_msgs::msg::TrafficControlRequest & out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlRequest into a j2735_v2x_msgs::msg::TrafficControlRequest.
Parameters
in_msg The message to be converted
out_msg The message to store the output
NOTE: Scale determined dynamically based on bound size. This function estimates the required scaling based on the following algorithm. If all input bounds are less than 1000, 100, or 10 then use a scale of -1, -2, -3 respectively. This gives higher resolution for smaller bounds while ensuring there is not integer overflow.
If the bounds are larger than 1000, the resolution will cap at 1m accuracy and determine a scaling of 1, 2, or 3 based on if all bounds can be cleanly divided by 10, 100, or 1000 respectively after integer truncation.
If the numbers cannot be scaled and they exceed the bounds of the output 16 bit int, then an exception will be thrown.
Unit conversions and presence flags are handled
Definition at line 260 of file control_request_convertor.cpp.
  {
     // uint8 choice
     out_msg.choice = in_msg.choice;
     switch(in_msg.choice)
     {
       case carma_v2x_msgs::msg::TrafficControlRequest::RESERVED :
       break;
       case carma_v2x_msgs::msg::TrafficControlRequest::TCRV01 :
       convert(in_msg.tcr_v01, out_msg.tcr_v01);
       break;
       default :
      break;
     }
  }
References convert().
convert() [3/7]
void j2735_convertor::geofence_request::convert (const carma_v2x_msgs::msg::TrafficControlRequestV01 & in_msg, j2735_v2x_msgs::msg::TrafficControlRequestV01 & out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlRequestV01 into a j2735_v2x_msgs::msg::TrafficControlRequestV01.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 157 of file control_request_convertor.cpp.
{
  // # reqid ::= Id64b
  // j2735_msgs/Id64b reqid
  out_msg.reqid = in_msg.reqid;
  // # reqseq ::= INTEGER (0..255)
  // uint8 reqseq
  out_msg.reqseq = in_msg.reqseq;
  bool canScale_neg_1_x = true;
  bool canScale_neg_2_x = true;
  bool canScale_neg_3_x = true;
  bool canScale_neg_1_y = true;
  bool canScale_neg_2_y = true;
  bool canScale_neg_3_y = true;
  for (auto bound : in_msg.bounds)
  {
    std::vector<double> offsetsx;
    std::vector<double> offsetsy;
    for (auto offset : bound.offsets)
    {
        offsetsx.push_back(offset.deltax);
        offsetsy.push_back(offset.deltay);
    }
    canScale_neg_1_x = canScale_neg_1_x && isLessThan(offsetsx, 1000);
    canScale_neg_2_x = canScale_neg_2_x && isLessThan(offsetsx, 100);
    canScale_neg_3_x = canScale_neg_3_x && isLessThan(offsetsx, 10);
    canScale_neg_1_y = canScale_neg_1_y && isLessThan(offsetsy, 1000);
    canScale_neg_2_y = canScale_neg_2_y && isLessThan(offsetsy, 100);
    canScale_neg_3_y = canScale_neg_3_y && isLessThan(offsetsy, 10);
  }
  if (canScale_neg_3_x && canScale_neg_3_y )
  {
    out_msg.scale = -3;
  } else if (canScale_neg_2_x && canScale_neg_2_y )
  {
    out_msg.scale = -2;
  } else if (canScale_neg_1_x && canScale_neg_1_y)
  {
    out_msg.scale = -1;
  } else
  {
    out_msg.scale = 0;
  }
  if (out_msg.scale == 0)
  {
    bool canScale_1_x = true;
    bool canScale_2_x = true;
    bool canScale_3_x = true;
    bool canScale_1_y = true;
    bool canScale_2_y = true;
    bool canScale_3_y = true;
    for (auto bound : in_msg.bounds)
    {
      std::vector<double> offsetsx;
      std::vector<double> offsetsy;
      for (auto offset : bound.offsets)
        {
        offsetsx.push_back(offset.deltax);
        offsetsy.push_back(offset.deltay);
        }
     // std::vector<carma_v2x_msgs::msg::OffsetPoint> offsets(bound.offsets.begin(), bound.offsets.end());
      canScale_1_x = canScale_1_x && isIntegerDivisable(offsetsx, 10);
      canScale_2_x = canScale_2_x && isIntegerDivisable(offsetsx, 100);
      canScale_3_x = canScale_3_x && isIntegerDivisable(offsetsx, 1000);
      canScale_1_y = canScale_1_y && isIntegerDivisable(offsetsy, 10);
      canScale_2_y = canScale_2_y && isIntegerDivisable(offsetsy, 100);
      canScale_3_y = canScale_3_y && isIntegerDivisable(offsetsy, 1000);
    }
    if (canScale_3_x && canScale_3_y)
    {
      out_msg.scale = 3;
    } else if (canScale_2_x && canScale_3_y)
    {
      out_msg.scale = 2;
    } else if (canScale_1_x && canScale_1_y)
    {
      out_msg.scale = 1;
    }
  }
  for (auto bound : in_msg.bounds)
  {
    j2735_v2x_msgs::msg::TrafficControlBounds out_bound;
    convert(bound, out_bound, out_msg.scale);
    out_msg.bounds.emplace_back(out_bound);
  }
}
References convert(), isIntegerDivisable(), and isLessThan().
convert() [4/7]
void j2735_convertor::geofence_request::convert (const j2735_v2x_msgs::msg::OffsetPoint & in_msg, carma_v2x_msgs::msg::OffsetPoint & out_msg, const int8_t scale)
Convert the contents of a j2735_v2x_msgs::msg::OffsetPoint into a carma_v2x_msgs::msg::OffsetPoint.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 29 of file control_request_convertor.cpp.
{
  out_msg.deltax = (double)in_msg.deltax* pow(10, scale);
  out_msg.deltay = (double)in_msg.deltay* pow(10, scale);
}
Referenced by j2735_convertor::Node::ControlRequestHandler(), convert(), and j2735_convertor::Node::j2735ControlRequestHandler().
convert() [5/7]
void j2735_convertor::geofence_request::convert (const j2735_v2x_msgs::msg::TrafficControlBounds & in_msg, carma_v2x_msgs::msg::TrafficControlBounds & out_msg, const int8_t scale)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlBounds into a carma_v2x_msgs::msg::TrafficControlBounds.
Parameters
in_msg The message to be converted
out_msg The message to store the output
scale The scaling exponent to apply to the bound position. Units applied as 10^n. This normally comes from a ControlRequest message.
Unit conversions and presence flags are handled
Definition at line 35 of file control_request_convertor.cpp.
{
  out_msg.oldest = rclcpp::Time(in_msg.oldest * units::SEC_PER_MIN, 0);
  out_msg.reflat = (double)in_msg.reflat / units::TENTH_MICRO_DEG_PER_DEG;
  out_msg.reflon = (double)in_msg.reflon / units::TENTH_MICRO_DEG_PER_DEG;
  for(int i = 0; i < 3; i++)
  {
    convert(in_msg.offsets[i], out_msg.offsets[i],scale);
  }
}
References convert(), j2735_convertor::units::SEC_PER_MIN, and j2735_convertor::units::TENTH_MICRO_DEG_PER_DEG.
convert() [6/7]
void j2735_convertor::geofence_request::convert (const j2735_v2x_msgs::msg::TrafficControlRequest & in_msg, carma_v2x_msgs::msg::TrafficControlRequest & out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlRequest into a carma_v2x_msgs::msg::TrafficControlRequest.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 68 of file control_request_convertor.cpp.
{
  // uint8 choice
  out_msg.choice = in_msg.choice;
  switch(in_msg.choice)
  {
    case j2735_v2x_msgs::msg::TrafficControlRequest::RESERVED :
      break;
    case j2735_v2x_msgs::msg::TrafficControlRequest::TCRV01 :
      convert(in_msg.tcr_v01, out_msg.tcr_v01);
      break;
    default:
      break;
  }
}
References convert().
convert() [7/7]
void j2735_convertor::geofence_request::convert (const j2735_v2x_msgs::msg::TrafficControlRequestV01 & in_msg, carma_v2x_msgs::msg::TrafficControlRequestV01 & out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlRequestV01 into a carma_v2x_msgs::msg::TrafficControlRequestV01.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 47 of file control_request_convertor.cpp.
{
  // # reqid ::= Id64b
  // j2735_msgs/Id64b reqid
  out_msg.reqid = in_msg.reqid;
  // # reqseq ::= INTEGER (0..255)
  // uint8 reqseq
  out_msg.reqseq = in_msg.reqseq;
  //# Bounds SEQUENCE (SIZE(1..63)) OF TrafficControlBounds
  for (auto in_bound : in_msg.bounds)
  {
    carma_v2x_msgs::msg::TrafficControlBounds out_bound;
    convert(in_bound, out_bound, in_msg.scale);
    out_msg.bounds.emplace_back(out_bound);
  }
}
References convert().
isIntegerDivisable()
bool j2735_convertor::geofence_request::isIntegerDivisable (const std::vector< double > & data, int16_t divisor)
Definition at line 94 of file control_request_convertor.cpp.
{
  for (auto element : data)
  {
    int64_t int_element = (int64_t)element; // Cast to integer to allow use of modulo
    if (int_element % divisor != 0)
    {
      return false;
    }
  }
  return true;
}
Referenced by convert().
isLessThan()
bool j2735_convertor::geofence_request::isLessThan (const std::vector< double > & data, int16_t threshold)
Definition at line 108 of file control_request_convertor.cpp.
{
  for (auto element : data)
  {
    if (element > fabs(threshold))
    {
      return false;
    }
  }
  return true;
}
Referenced by convert().