Carma-platform: j2735_convertor::geofence_control Namespace Reference
j2735_convertor::geofence_control Namespace Reference
Namespace responsible for converting j2735 style Geofence control messages to CARMA usable control messages.
Functions
void convert (const j2735_v2x_msgs::msg::DailySchedule &in_msg, carma_v2x_msgs::msg::DailySchedule &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::DailySchedule into a carma_v2x_msgs::msg::DailySchedule.
void convert (const j2735_v2x_msgs::msg::PathNode &in_msg, carma_v2x_msgs::msg::PathNode &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::PathNode into a carma_v2x_msgs::msg::PathNode.
void convert (const j2735_v2x_msgs::msg::RepeatParams &in_msg, carma_v2x_msgs::msg::RepeatParams &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::RepeatParams into a carma_v2x_msgs::msg::RepeatParams.
void convert (const j2735_v2x_msgs::msg::TrafficControlDetail &in_msg, carma_v2x_msgs::msg::TrafficControlDetail &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlDetail into a carma_v2x_msgs::msg::TrafficControlDetail.
void convert (const j2735_v2x_msgs::msg::TrafficControlGeometry &in_msg, carma_v2x_msgs::msg::TrafficControlGeometry &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlGeometry into a carma_v2x_msgs::msg::TrafficControlGeometry.
void convert (const j2735_v2x_msgs::msg::TrafficControlMessage &in_msg, carma_v2x_msgs::msg::TrafficControlMessage &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlMessage into a carma_v2x_msgs::msg::TrafficControlMessage.
void convert (const j2735_v2x_msgs::msg::TrafficControlMessageV01 &in_msg, carma_v2x_msgs::msg::TrafficControlMessageV01 &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlMessageV01 into a carma_v2x_msgs::msg::TrafficControlMessageV01.
void convert (const j2735_v2x_msgs::msg::TrafficControlParams &in_msg, carma_v2x_msgs::msg::TrafficControlParams &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlParams into a carma_v2x_msgs::msg::TrafficControlParams.
void convert (const j2735_v2x_msgs::msg::TrafficControlSchedule &in_msg, carma_v2x_msgs::msg::TrafficControlSchedule &out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlSchedule into a carma_v2x_msgs::msg::TrafficControlSchedule.
void convert (const carma_v2x_msgs::msg::DailySchedule &in_msg, j2735_v2x_msgs::msg::DailySchedule &out_msg)
Convert the contents of a carma_v2x_msgs::msg::DailySchedule into a j2735_v2x_msgs::msg::DailySchedule.
void convert (const carma_v2x_msgs::msg::PathNode &in_msg, j2735_v2x_msgs::msg::PathNode &out_msg)
Convert the contents of a carma_v2x_msgs::msg::PathNode into a j2735_v2x_msgs::msg::PathNode.
void convert (const carma_v2x_msgs::msg::RepeatParams &in_msg, j2735_v2x_msgs::msg::RepeatParams &out_msg)
Convert the contents of a carma_v2x_msgs::msg::RepeatParams into a j2735_v2x_msgs::msg::RepeatParams.
void convert (const carma_v2x_msgs::msg::TrafficControlDetail &in_msg, j2735_v2x_msgs::msg::TrafficControlDetail &out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlDetail into a j2735_v2x_msgs::msg::TrafficControlDetail.
void convert (const carma_v2x_msgs::msg::TrafficControlGeometry &in_msg, j2735_v2x_msgs::msg::TrafficControlGeometry &out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlGeometry into a j2735_v2x_msgs::msg::TrafficControlGeometry.
void convert (const carma_v2x_msgs::msg::TrafficControlMessage &in_msg, j2735_v2x_msgs::msg::TrafficControlMessage &out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlMessage into a j2735_v2x_msgs::msg::TrafficControlMessage.
void convert (const carma_v2x_msgs::msg::TrafficControlMessageV01 &in_msg, j2735_v2x_msgs::msg::TrafficControlMessageV01 &out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlMessageV01 into a j2735_v2x_msgs::msg::TrafficControlMessageV01.
void convert (const carma_v2x_msgs::msg::TrafficControlParams &in_msg, j2735_v2x_msgs::msg::TrafficControlParams &out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlParams into a j2735_v2x_msgs::msg::TrafficControlParams.
void convert (const carma_v2x_msgs::msg::TrafficControlSchedule &in_msg, j2735_v2x_msgs::msg::TrafficControlSchedule &out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlSchedule into a j2735_v2x_msgs::msg::TrafficControlSchedule.
Detailed Description
Namespace responsible for converting j2735 style Geofence control messages to CARMA usable control messages.
Handles conversion between ControlMessages in the j2735_msgs and cav_msgs packages. Unit conversions and presence flags are also handled
Function Documentation
convert() [1/18]
void j2735_convertor::geofence_control::convert (const carma_v2x_msgs::msg::DailySchedule & in_msg, j2735_v2x_msgs::msg::DailySchedule & out_msg)
Convert the contents of a carma_v2x_msgs::msg::DailySchedule into a j2735_v2x_msgs::msg::DailySchedule.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 313 of file control_message_convertor.cpp.
{
  rclcpp::Time begin(in_msg.begin.sec , in_msg.begin.nanosec);
  out_msg.begin = begin.seconds() / units::SEC_PER_MIN;
  rclcpp::Time duration(in_msg.duration.sec  , in_msg.duration.nanosec);
  out_msg.duration = duration.seconds() / units::SEC_PER_MIN;
}
References j2735_convertor::units::SEC_PER_MIN.
convert() [2/18]
void j2735_convertor::geofence_control::convert (const carma_v2x_msgs::msg::PathNode & in_msg, j2735_v2x_msgs::msg::PathNode & out_msg)
Convert the contents of a carma_v2x_msgs::msg::PathNode into a j2735_v2x_msgs::msg::PathNode.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 321 of file control_message_convertor.cpp.
{
  out_msg.x = (int16_t)(in_msg.x * units::CM_PER_M);
  out_msg.y = (int16_t)(in_msg.y * units::CM_PER_M);
  out_msg.z_exists = in_msg.z_exists;
  if(out_msg.z_exists)
  {
    out_msg.z = (int16_t)(in_msg.z * units::CM_PER_M);
  }
  out_msg.width_exists = in_msg.width_exists;
  if(out_msg.width_exists)
  {
    out_msg.width = (int8_t)(in_msg.width * units::CM_PER_M);
  }
}
References j2735_convertor::units::CM_PER_M.
convert() [3/18]
void j2735_convertor::geofence_control::convert (const carma_v2x_msgs::msg::RepeatParams & in_msg, j2735_v2x_msgs::msg::RepeatParams & out_msg)
Convert the contents of a carma_v2x_msgs::msg::RepeatParams into a j2735_v2x_msgs::msg::RepeatParams.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 339 of file control_message_convertor.cpp.
{
  rclcpp::Time offset(in_msg.offset.sec , in_msg.offset.nanosec);
  out_msg.offset =  offset.seconds() / units::SEC_PER_MIN;
  rclcpp::Time period(in_msg.period.sec  , in_msg.period.nanosec);
  out_msg.period = period.seconds()/ units::SEC_PER_MIN;
  rclcpp::Time span(in_msg.span.sec , in_msg.span.nanosec);
  out_msg.span = span.seconds()/ units::SEC_PER_MIN;
}
References j2735_convertor::units::SEC_PER_MIN.
convert() [4/18]
void j2735_convertor::geofence_control::convert (const carma_v2x_msgs::msg::TrafficControlDetail & in_msg, j2735_v2x_msgs::msg::TrafficControlDetail & out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlDetail into a j2735_v2x_msgs::msg::TrafficControlDetail.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 349 of file control_message_convertor.cpp.
{
  out_msg.choice = in_msg.choice;
  switch(in_msg.choice)
  {
    case carma_v2x_msgs::msg::TrafficControlDetail::SIGNAL_CHOICE :
      out_msg.signal = in_msg.signal;
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::STOP_CHOICE :
      // Not implemented yet
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::YIELD_CHOICE :
      // Not implemented yet
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::NOTOWING_CHOICE :
      // Not implemented yet
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::RESTRICTED_CHOICE :
      // Not implemented yet
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::CLOSED_CHOICE :
      out_msg.closed = in_msg.closed;
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::CHAINS_CHOICE :
      out_msg.chains = in_msg.chains;
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::DIRECTION_CHOICE :
      out_msg.direction = in_msg.direction;
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::LATAFFINITY_CHOICE :
      out_msg.lataffinity = in_msg.lataffinity;
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::LATPERM_CHOICE :
      for(int i = 0; i < 2; i++)
      {
        out_msg.latperm[i] = in_msg.latperm[i];
      }
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::PARKING_CHOICE :
      out_msg.parking = in_msg.parking;
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::MINSPEED_CHOICE :
      out_msg.minspeed = (uint16_t)(in_msg.minspeed * units::DECI_MPS_PER_MPS);
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::MAXSPEED_CHOICE :
      out_msg.maxspeed = (uint16_t)(in_msg.maxspeed * units::DECI_MPS_PER_MPS);
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::MINHDWY_CHOICE :
      out_msg.minhdwy = (uint16_t)(in_msg.minhdwy * units::DECI_M_PER_M);
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::MAXVEHMASS_CHOICE :
      out_msg.maxvehmass = (uint16_t)in_msg.maxvehmass;
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::MAXVEHHEIGHT_CHOICE :
      out_msg.maxvehheight = (uint8_t)(in_msg.maxvehheight * units::DECI_M_PER_M);
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::MAXVEHWIDTH_CHOICE :
      out_msg.maxvehwidth = (uint8_t)(in_msg.maxvehwidth * units::DECI_M_PER_M);
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::MAXVEHLENGTH_CHOICE :
      out_msg.maxvehlength = (uint8_t)(in_msg.maxvehlength * units::DECI_M_PER_M);
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::MAXVEHAXLES_CHOICE :
      out_msg.maxvehaxles = in_msg.maxvehaxles;
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::MINVEHOCC_CHOICE :
      out_msg.minvehocc = in_msg.minvehocc;
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::MAXPLATOONSIZE_CHOICE :
      out_msg.maxplatoonsize = in_msg.maxplatoonsize;
      break;
    case carma_v2x_msgs::msg::TrafficControlDetail::MINPLATOONHDWY_CHOICE :
      out_msg.minplatoonhdwy = (uint8_t)(in_msg.minplatoonhdwy * units::DECI_M_PER_M);
      break;
    default :
      // Throw Error?
      break;
  }
}
References j2735_convertor::units::DECI_M_PER_M, and j2735_convertor::units::DECI_MPS_PER_MPS.
convert() [5/18]
void j2735_convertor::geofence_control::convert (const carma_v2x_msgs::msg::TrafficControlGeometry & in_msg, j2735_v2x_msgs::msg::TrafficControlGeometry & out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlGeometry into a j2735_v2x_msgs::msg::TrafficControlGeometry.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 429 of file control_message_convertor.cpp.
{
  out_msg.proj = in_msg.proj;
  out_msg.datum = in_msg.datum;
  rclcpp::Time reftime(in_msg.reftime.sec , in_msg.reftime.nanosec);
  out_msg.reftime = reftime.seconds() / units::SEC_PER_MIN;
  out_msg.reflon = (int32_t)(in_msg.reflon * units::TENTH_MICRO_DEG_PER_DEG);
  out_msg.reflat = (int32_t)(in_msg.reflat * units::TENTH_MICRO_DEG_PER_DEG);
  out_msg.refelv = (int32_t)((in_msg.refelv + 409.6) * units::DECI_M_PER_M); // handle offset
  out_msg.heading = (int32_t)(in_msg.heading * units::DECI_S_PER_S);
  for (auto in_node : in_msg.nodes)
  {
    j2735_v2x_msgs::msg::PathNode out_node;
    convert(in_node, out_node);
    out_msg.nodes.push_back(out_node);
  }
}
References convert(), j2735_convertor::units::DECI_M_PER_M, j2735_convertor::units::DECI_S_PER_S, j2735_convertor::units::SEC_PER_MIN, and j2735_convertor::units::TENTH_MICRO_DEG_PER_DEG.
convert() [6/18]
void j2735_convertor::geofence_control::convert (const carma_v2x_msgs::msg::TrafficControlMessage & in_msg, j2735_v2x_msgs::msg::TrafficControlMessage & out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlMessage into a j2735_v2x_msgs::msg::TrafficControlMessage.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 448 of file control_message_convertor.cpp.
{
  // uint8 choice
  out_msg.choice = in_msg.choice;
  switch(in_msg.choice)
  {
    case carma_v2x_msgs::msg::TrafficControlMessage::RESERVED :
      // Not implemented yet
      break;
    case carma_v2x_msgs::msg::TrafficControlMessage::TCMV01 :
      convert(in_msg.tcm_v01, out_msg.tcm_v01);
      break;
    default :
      // Throw Error?
      break;
  }
}
References convert().
convert() [7/18]
void j2735_convertor::geofence_control::convert (const carma_v2x_msgs::msg::TrafficControlMessageV01 & in_msg, j2735_v2x_msgs::msg::TrafficControlMessageV01 & out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlMessageV01 into a j2735_v2x_msgs::msg::TrafficControlMessageV01.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 466 of file control_message_convertor.cpp.
{
  // # reqid ::= Id64b
  // j2735_msgs/Id64b reqid
  out_msg.reqid = in_msg.reqid;
  // # reqseq ::= INTEGER (0..255)
  // uint8 reqseq
  out_msg.reqseq = in_msg.reqseq;
  // # msgtot INTEGER (0..65535), -- total expected traffic control message responses
  // uint16 msgtot
  out_msg.msgtot = in_msg.msgtot;
  // # msgnum INTEGER (0..65535), -- message index for each response out of total responses
  // uint16 msgnum
  out_msg.msgnum = in_msg.msgnum;
  // # id Id128b, -- unique traffic control id
  // j2735_msgs/Id128b id
  out_msg.id = in_msg.id;
  // # updated EpochMins
  // time updated
  rclcpp::Time updated(in_msg.updated.sec , in_msg.updated.nanosec);
  out_msg.updated = updated.seconds() / units::SEC_PER_MIN;
  // # package [0] TrafficControlPackage OPTIONAL, -- related traffic control ids
  // j2735_msgs/TrafficControlPackage package
  // bool package_exists
  out_msg.package_exists = in_msg.package_exists;
  if(out_msg.package_exists)
  {
    out_msg.package = in_msg.package;
  }
  // # params [1] TrafficControlParams OPTIONAL
  // cav_msgs/TrafficControlParams params
  // bool params_exists
  out_msg.params_exists = in_msg.params_exists;
  if(out_msg.params_exists)
  {
    convert(in_msg.params, out_msg.params);
  }
  // # geometry [2] TrafficControlGeometry OPTIONAL
  // cav_msgs/TrafficControlGeometry geometry
  // bool geometry_exists
  out_msg.geometry_exists = in_msg.geometry_exists;
  if(out_msg.geometry_exists)
  {
    convert(in_msg.geometry, out_msg.geometry);
  }
}
References convert(), and j2735_convertor::units::SEC_PER_MIN.
convert() [8/18]
void j2735_convertor::geofence_control::convert (const carma_v2x_msgs::msg::TrafficControlParams & in_msg, j2735_v2x_msgs::msg::TrafficControlParams & out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlParams into a j2735_v2x_msgs::msg::TrafficControlParams.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 521 of file control_message_convertor.cpp.
{
  // j2735_msgs/TrafficControlVehClass[] vclasses
  out_msg.vclasses = in_msg.vclasses;
  // # schedule TrafficControlSchedule
  // carma_v2x_msgs/msg/trafficcontrolschedule s.hppedule
  convert(in_msg.schedule, out_msg.schedule);
  // # regulatory BOOLEAN
  // bool regulatory
  out_msg.regulatory = in_msg.regulatory;
  // # detail TrafficControlDetail
  // cav_msgs/TrafficControlDetail detail
  convert(in_msg.detail, out_msg.detail);
}
References convert().
convert() [9/18]
void j2735_convertor::geofence_control::convert (const carma_v2x_msgs::msg::TrafficControlSchedule & in_msg, j2735_v2x_msgs::msg::TrafficControlSchedule & out_msg)
Convert the contents of a carma_v2x_msgs::msg::TrafficControlSchedule into a j2735_v2x_msgs::msg::TrafficControlSchedule.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 539 of file control_message_convertor.cpp.
{
  rclcpp::Time start(in_msg.start.sec, in_msg.start.nanosec);
  out_msg.start = start.seconds()/ units::SEC_PER_MIN;
  out_msg.end_exists = in_msg.end_exists;
  if(out_msg.end_exists)
  {
    rclcpp::Time end(in_msg.end.sec , in_msg.end.nanosec);
    out_msg.end = end.seconds()/ units::SEC_PER_MIN;
  }
  out_msg.dow_exists = in_msg.dow_exists;
  if(out_msg.dow_exists)
  {
    out_msg.dow = in_msg.dow;
  }
  out_msg.between_exists = in_msg.between_exists;
  if(out_msg.between_exists)
  {
    for (auto in_between : in_msg.between)
    {
      j2735_v2x_msgs::msg::DailySchedule out_between;
      convert(in_between, out_between);
      out_msg.between.push_back(out_between);
    }
  }
  out_msg.repeat_exists = in_msg.repeat_exists;
  if(out_msg.repeat_exists)
  {
    convert(in_msg.repeat, out_msg.repeat);
  }
}
References convert(), and j2735_convertor::units::SEC_PER_MIN.
convert() [10/18]
void j2735_convertor::geofence_control::convert (const j2735_v2x_msgs::msg::DailySchedule & in_msg, carma_v2x_msgs::msg::DailySchedule & out_msg)
Convert the contents of a j2735_v2x_msgs::msg::DailySchedule into a carma_v2x_msgs::msg::DailySchedule.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 29 of file control_message_convertor.cpp.
{
  out_msg.begin = rclcpp::Duration(in_msg.begin * units::SEC_PER_MIN, 0);
  out_msg.duration = rclcpp::Duration(in_msg.duration * units::SEC_PER_MIN,0);
}
References j2735_convertor::units::SEC_PER_MIN.
Referenced by j2735_convertor::Node::ControlMessageHandler(), convert(), and j2735_convertor::Node::j2735ControlMessageHandler().
convert() [11/18]
void j2735_convertor::geofence_control::convert (const j2735_v2x_msgs::msg::PathNode & in_msg, carma_v2x_msgs::msg::PathNode & out_msg)
Convert the contents of a j2735_v2x_msgs::msg::PathNode into a carma_v2x_msgs::msg::PathNode.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 35 of file control_message_convertor.cpp.
{
  out_msg.x = (double)in_msg.x / units::CM_PER_M;
  out_msg.y = (double)in_msg.y / units::CM_PER_M;
  out_msg.z_exists = in_msg.z_exists;
  if(out_msg.z_exists)
  {
    out_msg.z = (double)in_msg.z / units::CM_PER_M;
  }
  out_msg.width_exists = in_msg.width_exists;
  if(out_msg.width_exists)
  {
    out_msg.width = (float)in_msg.width / units::CM_PER_M;
  }
}
References j2735_convertor::units::CM_PER_M.
convert() [12/18]
void j2735_convertor::geofence_control::convert (const j2735_v2x_msgs::msg::RepeatParams & in_msg, carma_v2x_msgs::msg::RepeatParams & out_msg)
Convert the contents of a j2735_v2x_msgs::msg::RepeatParams into a carma_v2x_msgs::msg::RepeatParams.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 53 of file control_message_convertor.cpp.
{
  out_msg.offset = rclcpp::Duration(in_msg.offset * units::SEC_PER_MIN, 0);
  out_msg.period = rclcpp::Duration(in_msg.period * units::SEC_PER_MIN, 0);
  out_msg.span = rclcpp::Duration(in_msg.span * units::SEC_PER_MIN, 0);
}
References j2735_convertor::units::SEC_PER_MIN.
convert() [13/18]
void j2735_convertor::geofence_control::convert (const j2735_v2x_msgs::msg::TrafficControlDetail & in_msg, carma_v2x_msgs::msg::TrafficControlDetail & out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlDetail into a carma_v2x_msgs::msg::TrafficControlDetail.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 60 of file control_message_convertor.cpp.
{
  out_msg.choice = in_msg.choice;
  switch(in_msg.choice)
  {
    case j2735_v2x_msgs::msg::TrafficControlDetail::SIGNAL_CHOICE :
      out_msg.signal = in_msg.signal;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::STOP_CHOICE :
      // Not implemented yet
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::YIELD_CHOICE :
      // Not implemented yet
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::NOTOWING_CHOICE :
      // Not implemented yet
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::RESTRICTED_CHOICE :
      // Not implemented yet
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::CLOSED_CHOICE :
      out_msg.closed = in_msg.closed;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::CHAINS_CHOICE :
      out_msg.chains = in_msg.chains;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::DIRECTION_CHOICE :
      out_msg.direction = in_msg.direction;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::LATAFFINITY_CHOICE :
      out_msg.lataffinity = in_msg.lataffinity;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::LATPERM_CHOICE :
      for(int i = 0; i < 2; i++)
      {
        out_msg.latperm[i] = in_msg.latperm[i];
      }
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::PARKING_CHOICE :
      out_msg.parking = in_msg.parking;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::MINSPEED_CHOICE :
      out_msg.minspeed = (float)in_msg.minspeed / units::DECI_MPS_PER_MPS;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::MAXSPEED_CHOICE :
      out_msg.maxspeed = (float)in_msg.maxspeed / units::DECI_MPS_PER_MPS;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::MINHDWY_CHOICE :
      out_msg.minhdwy = (float)in_msg.minhdwy / units::DECI_M_PER_M;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::MAXVEHMASS_CHOICE :
      out_msg.maxvehmass = (float)in_msg.maxvehmass;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::MAXVEHHEIGHT_CHOICE :
      out_msg.maxvehheight = (float)in_msg.maxvehheight / units::DECI_M_PER_M;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::MAXVEHWIDTH_CHOICE :
      out_msg.maxvehwidth = (float)in_msg.maxvehwidth / units::DECI_M_PER_M;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::MAXVEHLENGTH_CHOICE :
      out_msg.maxvehlength = (float)in_msg.maxvehlength / units::DECI_M_PER_M;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::MAXVEHAXLES_CHOICE :
      out_msg.maxvehaxles = in_msg.maxvehaxles;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::MINVEHOCC_CHOICE :
      out_msg.minvehocc = in_msg.minvehocc;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::MAXPLATOONSIZE_CHOICE :
      out_msg.maxplatoonsize = in_msg.maxplatoonsize;
      break;
    case j2735_v2x_msgs::msg::TrafficControlDetail::MINPLATOONHDWY_CHOICE :
      out_msg.minplatoonhdwy = (float)in_msg.minplatoonhdwy / units::DECI_M_PER_M;
      break;
    default :
      // Throw Error?
      break;
  }
}
References j2735_convertor::units::DECI_M_PER_M, and j2735_convertor::units::DECI_MPS_PER_MPS.
convert() [14/18]
void j2735_convertor::geofence_control::convert (const j2735_v2x_msgs::msg::TrafficControlGeometry & in_msg, carma_v2x_msgs::msg::TrafficControlGeometry & out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlGeometry into a carma_v2x_msgs::msg::TrafficControlGeometry.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 140 of file control_message_convertor.cpp.
{
  out_msg.proj = in_msg.proj;
  out_msg.datum = in_msg.datum;
  int32_t sec = 0;
  // Use conditional to avoid issues from casting in std::min
  if ((double)in_msg.reftime* units::SEC_PER_MIN >  (double)std::numeric_limits<int32_t>::max())
  {
    sec = std::numeric_limits<int32_t>::max();
  }
  else
  {
    sec = in_msg.reftime* units::SEC_PER_MIN;
  }
  out_msg.reftime = rclcpp::Time(sec, 0);
  out_msg.reflon = (double)in_msg.reflon / units::TENTH_MICRO_DEG_PER_DEG;
  out_msg.reflat = (double)in_msg.reflat / units::TENTH_MICRO_DEG_PER_DEG;
  out_msg.refelv = (float)in_msg.refelv / units::DECI_M_PER_M - (float) 409.6; //handle offset
  out_msg.heading = (float)in_msg.heading / units::DECI_S_PER_S;
  for (auto in_node : in_msg.nodes)
  {
    carma_v2x_msgs::msg::PathNode out_node;
    convert(in_node, out_node);
    out_msg.nodes.push_back(out_node);
  }
}
References convert(), j2735_convertor::units::DECI_M_PER_M, j2735_convertor::units::DECI_S_PER_S, j2735_convertor::units::SEC_PER_MIN, and j2735_convertor::units::TENTH_MICRO_DEG_PER_DEG.
convert() [15/18]
void j2735_convertor::geofence_control::convert (const j2735_v2x_msgs::msg::TrafficControlMessage & in_msg, carma_v2x_msgs::msg::TrafficControlMessage & out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlMessage into a carma_v2x_msgs::msg::TrafficControlMessage.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 171 of file control_message_convertor.cpp.
{
  // uint8 choice
  out_msg.choice = in_msg.choice;
  switch(in_msg.choice)
  {
    case j2735_v2x_msgs::msg::TrafficControlMessage::RESERVED :
      // Not implemented yet
      break;
    case j2735_v2x_msgs::msg::TrafficControlMessage::TCMV01 :
      convert(in_msg.tcm_v01, out_msg.tcm_v01);
      break;
    default :
      // Throw Error?
      break;
  }
}
References convert().
convert() [16/18]
void j2735_convertor::geofence_control::convert (const j2735_v2x_msgs::msg::TrafficControlMessageV01 & in_msg, carma_v2x_msgs::msg::TrafficControlMessageV01 & out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlMessageV01 into a carma_v2x_msgs::msg::TrafficControlMessageV01.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 189 of file control_message_convertor.cpp.
{
  // # reqid ::= Id64b
  // j2735_msgs/Id64b reqid
  out_msg.reqid = in_msg.reqid;
  // # reqseq ::= INTEGER (0..255)
  // uint8 reqseq
  out_msg.reqseq = in_msg.reqseq;
  // # msgtot INTEGER (0..65535), -- total expected traffic control message responses
  // uint16 msgtot
  out_msg.msgtot = in_msg.msgtot;
  // # msgnum INTEGER (0..65535), -- message index for each response out of total responses
  // uint16 msgnum
  out_msg.msgnum = in_msg.msgnum;
  // # id Id128b, -- unique traffic control id
  // j2735_msgs/Id128b id
  out_msg.id = in_msg.id;
  // # updated EpochMins
  // time updated
  out_msg.updated = rclcpp::Time(in_msg.updated * units::SEC_PER_MIN, 0);
  // # package [0] TrafficControlPackage OPTIONAL, -- related traffic control ids
  // j2735_msgs/TrafficControlPackage package
  // bool package_exists
  out_msg.package_exists = in_msg.package_exists;
  if(out_msg.package_exists)
  {
    out_msg.package = in_msg.package;
  }
  // # params [1] TrafficControlParams OPTIONAL
  // cav_msgs/TrafficControlParams params
  // bool params_exists
  out_msg.params_exists = in_msg.params_exists;
  if(out_msg.params_exists)
  {
    convert(in_msg.params, out_msg.params);
  }
  // # geometry [2] TrafficControlGeometry OPTIONAL
  // cav_msgs/TrafficControlGeometry geometry
  // bool geometry_exists
  out_msg.geometry_exists = in_msg.geometry_exists;
  if(out_msg.geometry_exists)
  {
    convert(in_msg.geometry, out_msg.geometry);
  }
}
References convert(), and j2735_convertor::units::SEC_PER_MIN.
convert() [17/18]
void j2735_convertor::geofence_control::convert (const j2735_v2x_msgs::msg::TrafficControlParams & in_msg, carma_v2x_msgs::msg::TrafficControlParams & out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlParams into a carma_v2x_msgs::msg::TrafficControlParams.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 243 of file control_message_convertor.cpp.
{
  // j2735_msgs/TrafficControlVehClass[] vclasses
  out_msg.vclasses = in_msg.vclasses;
  // # schedule TrafficControlSchedule
  // carma_v2x_msgs/msg/trafficcontrolschedule s.hppedule
  convert(in_msg.schedule, out_msg.schedule);
  // # regulatory BOOLEAN
  // bool regulatory
  out_msg.regulatory = in_msg.regulatory;
  // # detail TrafficControlDetail
  // cav_msgs/TrafficControlDetail detail
  convert(in_msg.detail, out_msg.detail);
}
References convert().
convert() [18/18]
void j2735_convertor::geofence_control::convert (const j2735_v2x_msgs::msg::TrafficControlSchedule & in_msg, carma_v2x_msgs::msg::TrafficControlSchedule & out_msg)
Convert the contents of a j2735_v2x_msgs::msg::TrafficControlSchedule into a carma_v2x_msgs::msg::TrafficControlSchedule.
Parameters
in_msg The message to be converted
out_msg The message to store the output
Unit conversions and presence flags are handled
Definition at line 261 of file control_message_convertor.cpp.
{
  out_msg.start = rclcpp::Time(in_msg.start * units::SEC_PER_MIN, 0);
  out_msg.end_exists = in_msg.end_exists;
  if(out_msg.end_exists)
  {
    int32_t sec = 0;
    // Use conditional to avoid issues from casting in std::min
    if ((double)in_msg.end* units::SEC_PER_MIN >  (double)std::numeric_limits<int32_t>::max())
    {
      sec = std::numeric_limits<int32_t>::max();
    }
    else
    {
      sec = in_msg.end* units::SEC_PER_MIN;
    }
    out_msg.end = rclcpp::Time(sec, 0);
  }
  out_msg.dow_exists = in_msg.dow_exists;
  if(out_msg.dow_exists)
  {
    out_msg.dow = in_msg.dow;
  }
  out_msg.between_exists = in_msg.between_exists;
  if(out_msg.between_exists)
  {
    for (auto in_between : in_msg.between)
    {
      carma_v2x_msgs::msg::DailySchedule out_between;
      convert(in_between, out_between);
      out_msg.between.push_back(out_between);
    }
  }
  out_msg.repeat_exists = in_msg.repeat_exists;
  if(out_msg.repeat_exists)
  {
    convert(in_msg.repeat, out_msg.repeat);
  }
}
References convert(), and j2735_convertor::units::SEC_PER_MIN.