Carma-platform: carma-messenger-core/cpp_message/include/generated/per_encoder.h File Reference
per_encoder.h File Reference
#include <asn_application.h>
#include <per_support.h>
Typedefs
typedef asn_enc_rval_t() per_type_encoder_f(const struct asn_TYPE_descriptor_s *type_descriptor, const asn_per_constraints_t *constraints, const void *struct_ptr, asn_per_outp_t *per_output)
Functions
asn_enc_rval_t uper_encode (const struct asn_TYPE_descriptor_s *type_descriptor, const asn_per_constraints_t *constraints, const void *struct_ptr, asn_app_consume_bytes_f *consume_bytes_cb, void *app_key)
asn_enc_rval_t uper_encode_to_buffer (const struct asn_TYPE_descriptor_s *type_descriptor, const asn_per_constraints_t *constraints, const void *struct_ptr, void *buffer, size_t buffer_size)
ssize_t uper_encode_to_new_buffer (const struct asn_TYPE_descriptor_s *type_descriptor, const asn_per_constraints_t *constraints, const void *struct_ptr, void **buffer_r)
Typedef Documentation
per_type_encoder_f
typedef asn_enc_rval_t() per_type_encoder_f(const struct asn_TYPE_descriptor_s *type_descriptor, const asn_per_constraints_t *constraints, const void *struct_ptr, asn_per_outp_t *per_output)
Definition at line 61 of file per_encoder.h.
Function Documentation
uper_encode()
asn_enc_rval_t uper_encode (const struct asn_TYPE_descriptor_s * type_descriptor, const asn_per_constraints_t * constraints, const void * struct_ptr, asn_app_consume_bytes_f * consume_bytes_cb, void * app_key)
uper_encode_to_buffer()
asn_enc_rval_t uper_encode_to_buffer (const struct asn_TYPE_descriptor_s * type_descriptor, const asn_per_constraints_t * constraints, const void * struct_ptr, void * buffer, size_t buffer_size)
Referenced by cpp_message::BSM_Message::encode_bsm_message(), cpp_message::Node::encode_geofence_control(), cpp_message::Node::encode_geofence_request(), cpp_message::Mobility_Operation::encode_mobility_operation_message(), cpp_message::Mobility_Path::encode_mobility_path_message(), cpp_message::Mobility_Request::encode_mobility_request_message(), cpp_message::Mobility_Response::encode_mobility_response_message(), cpp_message::PSM_Message::encode_psm_message(), and cpp_message::SPAT_Message::encode_spat_message().
uper_encode_to_new_buffer()
ssize_t uper_encode_to_new_buffer (const struct asn_TYPE_descriptor_s * type_descriptor, const asn_per_constraints_t * constraints, const void * struct_ptr, void ** buffer_r)
Referenced by cpp_message::Node::encode_geofence_control().