Carma-platform: carma-messenger-core/cpp_message/include/generated/per_decoder.h File Reference
per_decoder.h File Reference
#include <asn_application.h>
#include <per_support.h>
Typedefs
typedef asn_dec_rval_t() per_type_decoder_f(const asn_codec_ctx_t *opt_codec_ctx, const struct asn_TYPE_descriptor_s *type_descriptor, const asn_per_constraints_t *constraints, void **struct_ptr, asn_per_data_t *per_data)
Functions
asn_dec_rval_t uper_decode_complete (const struct asn_codec_ctx_s *opt_codec_ctx, const struct asn_TYPE_descriptor_s *type_descriptor, void **struct_ptr, const void *buffer, size_t size)
asn_dec_rval_t uper_decode (const struct asn_codec_ctx_s *opt_codec_ctx, const struct asn_TYPE_descriptor_s *type_descriptor, void **struct_ptr, const void *buffer, size_t size, int skip_bits, int unused_bits)
Typedef Documentation
per_type_decoder_f
typedef asn_dec_rval_t() per_type_decoder_f(const asn_codec_ctx_t *opt_codec_ctx, const struct asn_TYPE_descriptor_s *type_descriptor, const asn_per_constraints_t *constraints, void **struct_ptr, asn_per_data_t *per_data)
Definition at line 47 of file per_decoder.h.
Function Documentation
uper_decode()
asn_dec_rval_t uper_decode (const struct asn_codec_ctx_s * opt_codec_ctx, const struct asn_TYPE_descriptor_s * type_descriptor, void ** struct_ptr, const void * buffer, size_t size, int skip_bits, int unused_bits)
Referenced by cpp_message::BSM_Message::decode_bsm_message(), cpp_message::Emergency_Vehicle_Response::decode_emergency_vehicle_response_message(), cpp_message::Node::decode_geofence_control(), cpp_message::Node::decode_geofence_request(), cpp_message::Map_Message::decode_map_message(), cpp_message::Mobility_Operation::decode_mobility_operation_message(), cpp_message::Mobility_Path::decode_mobility_path_message(), cpp_message::Mobility_Request::decode_mobility_request_message(), cpp_message::Mobility_Response::decode_mobility_response_message(), cpp_message::PSM_Message::decode_psm_message(), and cpp_message::SPAT_Message::decode_spat_message().
uper_decode_complete()
asn_dec_rval_t uper_decode_complete (const struct asn_codec_ctx_s * opt_codec_ctx, const struct asn_TYPE_descriptor_s * type_descriptor, void ** struct_ptr, const void * buffer, size_t size)