Carma-streets: OpenAPI::OAIEnum Class Reference
OpenAPI::OAIEnum Class Reference
#include <OAIEnum.h>
Public Member Functions
OAIEnum ()
OAIEnum (QString jsonString)
virtual ~OAIEnum ()
virtual QJsonValue asJsonValue () const
virtual QString asJson () const
virtual void fromJson (QString jsonString)
virtual void fromJsonValue (QJsonValue jval)
virtual bool isSet () const
virtual bool isValid () const
OAIEnum ()
OAIEnum (QString jsonString)
virtual ~OAIEnum ()
virtual QJsonValue asJsonValue () const
virtual QString asJson () const
virtual void fromJson (QString jsonString)
virtual void fromJsonValue (QJsonValue jval)
virtual bool isSet () const
virtual bool isValid () const
Private Attributes
QString jstr
Detailed Description
Definition at line 21 of file OAIEnum.h.
Constructor & Destructor Documentation
OAIEnum() [1/4]
OpenAPI::OAIEnum::OAIEnum () inline
Definition at line 23 of file OAIEnum.h.
{}
OAIEnum() [2/4]
OpenAPI::OAIEnum::OAIEnum (QString jsonString) inline
Definition at line 25 of file OAIEnum.h.
{
        fromJson(jsonString);
    }
References fromJson().
~OAIEnum() [1/2]
virtual OpenAPI::OAIEnum::~OAIEnum () inline virtual
Definition at line 29 of file OAIEnum.h.
{}
OAIEnum() [3/4]
OpenAPI::OAIEnum::OAIEnum () inline
Definition at line 23 of file OAIEnum.h.
{}
OAIEnum() [4/4]
OpenAPI::OAIEnum::OAIEnum (QString jsonString) inline
Definition at line 25 of file OAIEnum.h.
{
        fromJson(jsonString);
    }
References fromJson().
~OAIEnum() [2/2]
virtual OpenAPI::OAIEnum::~OAIEnum () inline virtual
Definition at line 29 of file OAIEnum.h.
{}
Member Function Documentation
asJson() [1/2]
virtual QString OpenAPI::OAIEnum::asJson () const inline virtual
Definition at line 35 of file OAIEnum.h.
{
        return jstr;
    }
References jstr.
asJson() [2/2]
virtual QString OpenAPI::OAIEnum::asJson () const inline virtual
Definition at line 35 of file OAIEnum.h.
{
        return jstr;
    }
References jstr.
asJsonValue() [1/2]
virtual QJsonValue OpenAPI::OAIEnum::asJsonValue () const inline virtual
Definition at line 31 of file OAIEnum.h.
{
        return QJsonValue(jstr);
    }
References jstr.
asJsonValue() [2/2]
virtual QJsonValue OpenAPI::OAIEnum::asJsonValue () const inline virtual
Definition at line 31 of file OAIEnum.h.
{
        return QJsonValue(jstr);
    }
References jstr.
fromJson() [1/2]
virtual void OpenAPI::OAIEnum::fromJson (QString jsonString) inline virtual
Definition at line 39 of file OAIEnum.h.
{
        jstr = jsonString;
    }
References jstr.
Referenced by OAIEnum().
fromJson() [2/2]
virtual void OpenAPI::OAIEnum::fromJson (QString jsonString) inline virtual
Definition at line 39 of file OAIEnum.h.
{
        jstr = jsonString;
    }
References jstr.
fromJsonValue() [1/2]
virtual void OpenAPI::OAIEnum::fromJsonValue (QJsonValue jval) inline virtual
Definition at line 43 of file OAIEnum.h.
{
        jstr = jval.toString();
    }
References jstr.
fromJsonValue() [2/2]
virtual void OpenAPI::OAIEnum::fromJsonValue (QJsonValue jval) inline virtual
Definition at line 43 of file OAIEnum.h.
{
        jstr = jval.toString();
    }
References jstr.
isSet() [1/2]
virtual bool OpenAPI::OAIEnum::isSet () const inline virtual
Definition at line 47 of file OAIEnum.h.
{
        return false;
    }
isSet() [2/2]
virtual bool OpenAPI::OAIEnum::isSet () const inline virtual
Definition at line 47 of file OAIEnum.h.
{
        return false;
    }
isValid() [1/2]
virtual bool OpenAPI::OAIEnum::isValid () const inline virtual
Definition at line 51 of file OAIEnum.h.
{
        return true;
    }
isValid() [2/2]
virtual bool OpenAPI::OAIEnum::isValid () const inline virtual
Definition at line 51 of file OAIEnum.h.
{
        return true;
    }
Member Data Documentation
jstr
QString OpenAPI::OAIEnum::jstr private
Definition at line 56 of file OAIEnum.h.
Referenced by asJson(), asJsonValue(), fromJson(), and fromJsonValue().
The documentation for this class was generated from the following files:
streets_utils/streets_api/intersection_client_api/OAIEnum.h
streets_utils/streets_api/intersection_server_api/src/models/OAIEnum.h