Carma-streets: streets_service::streets_service Class Reference
streets_service::streets_service Class Reference
Streets Service is a base class for CARMA-Streets services. It initializes the streets_clock_singleton is a maintains a time wrapper object that allows services to configurably use system time or time sync messages as a source for time. This allows CARMA-Streets services that extend this class use CDASim as a source for time. This class also initializes the streets_configuration singleton using a file path provided by the CONFIG_FILE_PATH environment variable.
#include <streets_service.h>
Public Member Functions
streets_service ()=default
Constructor.
~streets_service ()
Destructor stop time_consumer kafka producer if not null.
streets_service (const streets_service &)=delete
streets_service (streets_service &&)=delete
streets_service & operator= (const streets_service &)=delete
streets_service & operator= (const streets_service &&)=delete
virtual bool initialize ()
Method to initialize services members, singletons, kafka consumers and producers and any other connections required for service. Classes that extend this streets_service need to override this method and call the streets_service::initialize() in the override method.
virtual void start ()
Method to start all threads needed for the Streets Service. This includes but is not limited to any threads to consume/produce message to kafka, or poll internal/external resources. Classes that extend this streets_service need to override this method and call the streets_service::start() in the override method.
Protected Member Functions
bool initialize_kafka_producer (const std::string &producer_topic, std::shared_ptr< kafka_clients::kafka_producer_worker > &producer) const
Helper method to initialize Kafka producer for a given topic.
bool initialize_kafka_consumer (const std::string &consumer_topic, std::shared_ptr< kafka_clients::kafka_consumer_worker > &consumer) const
Helper method to initialise Kafka consumer. NOTE: Will assign consumer group id as service_name.
std::string get_system_config (const char *config_name, const std::string &default_val) const noexcept
Returns string value of environment variable with given name. If no value is found, returns default.
void consume_time_sync_message () const
Method to consume continously consume time sync messages from Kafka topic and update streets_clock_singleton with received data.
std::string get_service_name () const
Returns service name set in configuration file.
bool is_simulation_mode () const
Returns boolean if service is currently configured to be in simulation_mode. This corresponsds to the value of the environment variable SIMULATION_MODE. Simulation mode indicates whether the streets_clock_singleton uses simulation time for kafka or system time.
std::shared_ptr< spdlog::logger > create_daily_logger (const std::string &name, const std::string &extension=".log", const std::string &pattern="[%Y-%m-%d %H:%M:%S.%e] %v", const spdlog::level::level_enum &level=spdlog::level::info) const
Method to create SPDLOG Daily rotating file logger. The logger is accessible by calling spdlog::get(name). The log files created by this logger will include data and time in name and will be stored in the LOGS_DIRECTORY set path.
Private Member Functions
FRIEND_TEST (test_streets_service, test_consume_time_sync_message)
FRIEND_TEST (test_streets_service, test_initialize_consumer)
FRIEND_TEST (test_streets_service, test_initialize_producer)
FRIEND_TEST (test_streets_service, test_initialize_sim)
FRIEND_TEST (test_streets_service, test_get_system_config)
FRIEND_TEST (test_streets_service, test_create_daily_logger)
FRIEND_TEST (test_streets_service, test_create_daily_logger_default)
Private Attributes
std::string _service_name
bool _simulation_mode
std::shared_ptr< kafka_clients::kafka_consumer_worker > _time_consumer
std::string _logs_directory
Detailed Description
Streets Service is a base class for CARMA-Streets services. It initializes the streets_clock_singleton is a maintains a time wrapper object that allows services to configurably use system time or time sync messages as a source for time. This allows CARMA-Streets services that extend this class use CDASim as a source for time. This class also initializes the streets_configuration singleton using a file path provided by the CONFIG_FILE_PATH environment variable.
Author
Paul Bourelly
Definition at line 21 of file streets_service.h.
Constructor & Destructor Documentation
streets_service() [1/3]
streets_service::streets_service::streets_service () default
Constructor.
~streets_service()
streets_service::streets_service::~streets_service ()
Destructor stop time_consumer kafka producer if not null.
Definition at line 5 of file streets_service.cpp.
{
        SPDLOG_INFO("Destructor called for streets service {0}!", _service_name);
        if ( _time_consumer ) {
            _time_consumer->stop();
        }
    }
streets_service() [2/3]
streets_service::streets_service::streets_service (const streets_service &) delete
streets_service() [3/3]
streets_service::streets_service::streets_service (streets_service &&) delete
Member Function Documentation
consume_time_sync_message()
void streets_service::streets_service::consume_time_sync_message () const protected
Method to consume continously consume time sync messages from Kafka topic and update streets_clock_singleton with received data.
Definition at line 83 of file streets_service.cpp.
{
        _time_consumer->subscribe();
        while (_time_consumer->is_running())
        {
            const std::string payload = _time_consumer->consume(1000);
            if (payload.length() != 0)
            {
                try {
                    SPDLOG_DEBUG("Consumed: {0}", payload);
                    simulation::time_sync_message msg;
                    msg.fromJson(payload);
                    streets_clock_singleton::update(msg.timestep);
                }
                catch( const std::runtime_error &e) {
                    SPDLOG_WARN( "{0} exception occured will consuming {1} msg! Skipping message!", e.what(), payload);
                }
            }
        }
    }
References streets_service::simulation::time_sync_message::fromJson(), streets_service::simulation::time_sync_message::timestep, and streets_service::streets_clock_singleton::update().
create_daily_logger()
std::shared_ptr< spdlog::logger > streets_service::streets_service::create_daily_logger (const std::string & name, const std::string & extension = ".log", const std::string & pattern = "[%Y-%m-%d %H:%M:%S.%e] %v", const spdlog::level::level_enum & level = spdlog::level::info) const protected
Method to create SPDLOG Daily rotating file logger. The logger is accessible by calling spdlog::get(name). The log files created by this logger will include data and time in name and will be stored in the LOGS_DIRECTORY set path.
Parameters
name Name of the logger
extension file extension for log files created
pattern pattern for output of log statments. Please review SPDLOG documentation (https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#customizing-format-using-set_pattern).
level log level to set for logger. Can be dynamically changed by getting logger and changing log level.
Definition at line 40 of file streets_service.cpp.
    {
        auto logger  = spdlog::daily_logger_mt<spdlog::async_factory>(
                name,  // logger name
                _logs_directory +name + extension,  // log file name and path
                23, // hours to rotate
                59 // minutes to rotate
            );
        // Only log log statement content
        logger->set_pattern(pattern);
        logger->set_level(level);
        logger->flush_on(level);
        return logger;
    }
Referenced by traffic_signal_controller_service::tsc_service::configure_snmp_cmd_logger(), and traffic_signal_controller_service::tsc_service::configure_veh_ped_call_logger().
FRIEND_TEST() [1/7]
streets_service::streets_service::FRIEND_TEST (test_streets_service , test_consume_time_sync_message) private
FRIEND_TEST() [2/7]
streets_service::streets_service::FRIEND_TEST (test_streets_service , test_create_daily_logger) private
FRIEND_TEST() [3/7]
streets_service::streets_service::FRIEND_TEST (test_streets_service , test_create_daily_logger_default) private
FRIEND_TEST() [4/7]
streets_service::streets_service::FRIEND_TEST (test_streets_service , test_get_system_config) private
FRIEND_TEST() [5/7]
streets_service::streets_service::FRIEND_TEST (test_streets_service , test_initialize_consumer) private
FRIEND_TEST() [6/7]
streets_service::streets_service::FRIEND_TEST (test_streets_service , test_initialize_producer) private
FRIEND_TEST() [7/7]
streets_service::streets_service::FRIEND_TEST (test_streets_service , test_initialize_sim) private
get_service_name()
std::string streets_service::streets_service::get_service_name () const protected
Returns service name set in configuration file.
Returns
Returns service name set in configuration file.
Definition at line 131 of file streets_service.cpp.
{
        return _service_name;
    }
get_system_config()
std::string streets_service::streets_service::get_system_config (const char * config_name, const std::string & default_val) const protected noexcept
Returns string value of environment variable with given name. If no value is found, returns default.
Parameters
config_name name of environment variable.
default_val string default value for environment variable if no value is found.
Exceptions
runtime_error if config_name is nullptr or environment variable is not set.
Returns
value of environment variable.
Definition at line 113 of file streets_service.cpp.
{
        // Check for config_name nullptr and use default value
        if (config_name == nullptr ) {
            SPDLOG_WARN("System config_name was nullptr! Using default value {0}!" , default_val);
            return default_val;
        }
        // If std::getenv(config_name) returns value, use this value
        if (const auto config = std::getenv(config_name)) {
            SPDLOG_DEBUG("Reading system config {0} as : {1}!", config_name, config);
            return config;
        }
        // If std::getenv(config_name) returns nullptr, environment variable was not set so use default
        else {
            SPDLOG_WARN("System config {0} was not set! Using default value {1}!" ,config_name, default_val);
            return default_val;
        }
    }
initialize()
bool streets_service::streets_service::initialize () virtual
Method to initialize services members, singletons, kafka consumers and producers and any other connections required for service. Classes that extend this streets_service need to override this method and call the streets_service::initialize() in the override method.
Returns
bool depending on whether initialize method completes successfully.
Reimplemented in traffic_signal_controller_service::tsc_service.
Definition at line 12 of file streets_service.cpp.
{
        try {
            std::string config_file_path = get_system_config(CONFIG_FILE_PATH_ENV.c_str(), DEFAULT_CONFIG_FILE_PATH);
            streets_configuration::create(config_file_path);
            std::string sim_mode_string = get_system_config(SIMULATION_MODE_ENV.c_str(),DEFAULT_SIMULATION_MODE);
            _simulation_mode = sim_mode_string.compare("true") == 0 || sim_mode_string.compare("TRUE") == 0 ;
            streets_clock_singleton::create(_simulation_mode);
            _service_name = streets_configuration::get_service_name();
            SPDLOG_INFO("Initializing {0} streets service in simulation mode : {1}!", _service_name, _simulation_mode);
            if ( _simulation_mode ) {
                std::string time_sync_topic = get_system_config(TIME_SYNC_TOPIC_ENV.c_str(), DEFAULT_TIME_SYNC_TOPIC);
                if (!initialize_kafka_consumer(time_sync_topic, _time_consumer)){
                    return false;
                }
            }
            _logs_directory = get_system_config(LOGS_DIRECTORY_ENV.c_str(), DEFAULT_LOGS_DIRECTORY);
        } catch( const streets_configuration_exception &e) {
            SPDLOG_ERROR("Exception occured during {0} initialization : {1}" , _service_name , e.what());
            return false;
        }
        catch ( const std::runtime_error &e ) {
            SPDLOG_ERROR("Exception occured during {0} initialization : {1}" , _service_name , e.what());
            return false;
        }
        return true;
    }
References streets_service::CONFIG_FILE_PATH_ENV, streets_service::streets_singleton< fwha_stol::lib::time::CarmaClock, bool >::create(), streets_service::streets_singleton< streets_configuration, std::string >::create(), streets_service::DEFAULT_CONFIG_FILE_PATH, streets_service::DEFAULT_LOGS_DIRECTORY, streets_service::DEFAULT_SIMULATION_MODE, streets_service::DEFAULT_TIME_SYNC_TOPIC, streets_service::streets_configuration::get_service_name(), streets_service::LOGS_DIRECTORY_ENV, streets_service::SIMULATION_MODE_ENV, and streets_service::TIME_SYNC_TOPIC_ENV.
Referenced by traffic_signal_controller_service::tsc_service::initialize().
initialize_kafka_consumer()
bool streets_service::streets_service::initialize_kafka_consumer (const std::string & consumer_topic, std::shared_ptr< kafka_clients::kafka_consumer_worker > & consumer) const protected
Helper method to initialise Kafka consumer. NOTE: Will assign consumer group id as service_name.
Parameters
consumer_topic topic name.
consumer shared_ptr to kafka consumer.
Returns
true if initialization is successful and false if initialization fails.
Definition at line 70 of file streets_service.cpp.
{
        auto client = std::make_unique<kafka_clients::kafka_client>();
        std::string bootstrap_server = streets_configuration::get_string_config("bootstrap_server");
        kafka_consumer = client->create_consumer(bootstrap_server, consumer_topic, _service_name);
        if (!kafka_consumer->init())
        {
            SPDLOG_CRITICAL("Kafka initialize error");
            return false;
        }
        SPDLOG_DEBUG("Initialized Kafka consumer!");
        return true;
    }
References streets_service::streets_configuration::get_string_config().
Referenced by traffic_signal_controller_service::tsc_service::initialize().
initialize_kafka_producer()
bool streets_service::streets_service::initialize_kafka_producer (const std::string & producer_topic, std::shared_ptr< kafka_clients::kafka_producer_worker > & producer) const protected
Helper method to initialize Kafka producer for a given topic.
Parameters
producer_topic topic name.
producer shared_ptr to kafka producer.
Returns
true if initialization is successful and false if initialization fails.
Definition at line 55 of file streets_service.cpp.
{
        auto client = std::make_unique<kafka_clients::kafka_client>();
        std::string bootstrap_server = streets_configuration::get_string_config("bootstrap_server");
        producer = client->create_producer(bootstrap_server, producer_topic);
        if (!producer->init())
        {
            SPDLOG_CRITICAL("Kafka producer initialize error on topic {0}", producer_topic);
            return false;
        }
        SPDLOG_DEBUG("Initialized Kafka producer on topic {0}!", producer_topic);
        return true;
    }
References streets_service::streets_configuration::get_string_config(), and simulate_bsm::producer.
Referenced by traffic_signal_controller_service::tsc_service::initialize().
is_simulation_mode()
bool streets_service::streets_service::is_simulation_mode () const protected
Returns boolean if service is currently configured to be in simulation_mode. This corresponsds to the value of the environment variable SIMULATION_MODE. Simulation mode indicates whether the streets_clock_singleton uses simulation time for kafka or system time.
Returns
true if in simulation mode, false if in real time more
Definition at line 135 of file streets_service.cpp.
{
        return _simulation_mode;
    }
Referenced by traffic_signal_controller_service::tsc_service::initialize(), and traffic_signal_controller_service::tsc_service::produce_spat_json().
operator=() [1/2]
streets_service & streets_service::streets_service::operator= (const streets_service &&) delete
operator=() [2/2]
streets_service & streets_service::streets_service::operator= (const streets_service &) delete
start()
void streets_service::streets_service::start () virtual
Method to start all threads needed for the Streets Service. This includes but is not limited to any threads to consume/produce message to kafka, or poll internal/external resources. Classes that extend this streets_service need to override this method and call the streets_service::start() in the override method.
Reimplemented in traffic_signal_controller_service::tsc_service.
Definition at line 106 of file streets_service.cpp.
{
        if ( _simulation_mode ) {
            std::thread time_sync_thread(&streets_service::consume_time_sync_message, this);
            time_sync_thread.detach();
        }
    }
Referenced by traffic_signal_controller_service::tsc_service::start().
Member Data Documentation
_logs_directory
std::string streets_service::streets_service::_logs_directory private
Definition at line 116 of file streets_service.h.
_service_name
std::string streets_service::streets_service::_service_name private
Definition at line 110 of file streets_service.h.
_simulation_mode
bool streets_service::streets_service::_simulation_mode private
Definition at line 112 of file streets_service.h.
_time_consumer
std::shared_ptr<kafka_clients::kafka_consumer_worker> streets_service::streets_service::_time_consumer private
Definition at line 114 of file streets_service.h.
The documentation for this class was generated from the following files:
streets_utils/streets_service_base/include/streets_service.h
streets_utils/streets_service_base/src/streets_service.cpp