Carma-streets: message_services::workers::vehicle_status_intent_worker Class Reference
message_services::workers::vehicle_status_intent_worker Class Reference
#include <vehicle_status_intent_worker.h>
Public Member Functions
vehicle_status_intent_worker ()
~vehicle_status_intent_worker ()
std::map< std::string, models::vehicle_status_intent > & get_curr_map ()
Return the vector of vehicle_status_intent stored in the vehicle_status_intent_worker.
void process_incoming_msg (const std::string json_str)
void pop_element_from_map (std::string key)
Remove an element from vehicle_status_intent vector based on the element position. If the position is greater than the deque current size, the last element is removed.
void update_by_incoming_bsm_msg (models::bsm bsm)
Update the vehicle status and intent base on the bsm info.
void update_insert_by_incoming_mobilityoperation_msg (models::mobilityoperation mo)
If the vehicle id from the MobilityOperation message exist in vehicle status and intent map, update the vehicle status and intent base on the MobilityOperation info. If the vehicle id from the MobilityOperation message does not exist in vehicle status and intent map, insert a new the vehicle status and intent object to the map base on the MobilityOperation info.
void update_insert_by_incoming_mobilitypath_msg (models::mobilitypath mp)
If the vehicle id from the mobilitypath message exist in vehicle status and intent map, update the vehicle status and intent base on the mobilitypath info. If the vehicle id from the mobilitypath message does not exist in vehicle status and intent map, insert a new the vehicle status and intent object to the map base on the mobilitypath info.
Public Member Functions inherited from message_services::workers::base_worker
base_worker ()
~base_worker ()
virtual void process_incoming_msg (const std::string json_str)=0
Public Attributes
std::mutex worker_mtx
Private Attributes
std::map< std::string, models::vehicle_status_intent > vsi_map_
Detailed Description
Definition at line 20 of file vehicle_status_intent_worker.h.
Constructor & Destructor Documentation
vehicle_status_intent_worker()
message_services::workers::vehicle_status_intent_worker::vehicle_status_intent_worker ()
Definition at line 7 of file vehicle_status_intent_worker.cpp.
{}
~vehicle_status_intent_worker()
message_services::workers::vehicle_status_intent_worker::~vehicle_status_intent_worker ()
Definition at line 9 of file vehicle_status_intent_worker.cpp.
        {
            this->vsi_map_.clear();
        }
References vsi_map_.
Member Function Documentation
get_curr_map()
std::map< std::string, models::vehicle_status_intent > & message_services::workers::vehicle_status_intent_worker::get_curr_map ()
Return the vector of vehicle_status_intent stored in the vehicle_status_intent_worker.
Definition at line 14 of file vehicle_status_intent_worker.cpp.
        {
            return this->vsi_map_;
        }
References vsi_map_.
pop_element_from_map()
void message_services::workers::vehicle_status_intent_worker::pop_element_from_map (std::string key)
Remove an element from vehicle_status_intent vector based on the element position. If the position is greater than the deque current size, the last element is removed.
Parameters
long Current element position in the vehicle_status_intent deque.
Definition at line 19 of file vehicle_status_intent_worker.cpp.
        {
            this->vsi_map_.erase(key);
        }
References vsi_map_.
process_incoming_msg()
void message_services::workers::vehicle_status_intent_worker::process_incoming_msg (const std::string json_str) virtual
Implements message_services::workers::base_worker.
Definition at line 118 of file vehicle_status_intent_worker.cpp.
{}
update_by_incoming_bsm_msg()
void message_services::workers::vehicle_status_intent_worker::update_by_incoming_bsm_msg (models::bsm bsm)
Update the vehicle status and intent base on the bsm info.
Parameters
bsm_obj an instance of bsm
Definition at line 24 of file vehicle_status_intent_worker.cpp.
        {
            std::unique_lock<std::mutex> lck(worker_mtx);
            std::map<std::string, models::vehicle_status_intent>::iterator itr = this->vsi_map_.begin();
            while (itr != this->vsi_map_.end())
            {
                if (itr->second.getBsm_id() == bsm.getCore_data().temprary_id)
                {
                    itr->second.setCur_speed(bsm.getCore_data().speed);
                    itr->second.setVehicle_length(bsm.getCore_data().size.length);
                    itr->second.setBsm_id(bsm.getCore_data().temprary_id);
                    //Todo other fields
                }
                ++itr;
            }
        }
References message_services::models::bsm::getCore_data(), message_services::models::VehicleSize::length, message_services::models::bsmCoreData::size, message_services::models::bsmCoreData::speed, message_services::models::bsmCoreData::temprary_id, vsi_map_, and worker_mtx.
update_insert_by_incoming_mobilityoperation_msg()
void message_services::workers::vehicle_status_intent_worker::update_insert_by_incoming_mobilityoperation_msg (models::mobilityoperation mo)
If the vehicle id from the MobilityOperation message exist in vehicle status and intent map, update the vehicle status and intent base on the MobilityOperation info. If the vehicle id from the MobilityOperation message does not exist in vehicle status and intent map, insert a new the vehicle status and intent object to the map base on the MobilityOperation info.
Parameters
mo_obj an instance of mobilityoperation
Definition at line 41 of file vehicle_status_intent_worker.cpp.
        {
            std::unique_lock<std::mutex> lck(worker_mtx);
            std::map<std::string, models::vehicle_status_intent>::iterator itr = this->vsi_map_.begin();
            bool is_update = false;
            while (itr != this->vsi_map_.end())
            {
                if (itr->first == mo.getHeader().sender_id)
                {
                    is_update = true;
                    std::string is_allowed_int_str = mo.get_value_from_strategy_params("is_allowed_int");
                    if (is_allowed_int_str.length() > 0)
                    {
                        std::stringstream is_allowed_ss(is_allowed_int_str);
                        int is_allowed_int;
                        is_allowed_ss >> is_allowed_int;
                        itr->second.setIs_allowed(is_allowed_int);
                    }
                    itr->second.setVehicle_id(mo.getHeader().sender_id);
                    itr->second.setBsm_id(mo.getHeader().sender_bsm_id);
                    itr->second.setCur_timestamp(mo.getHeader().timestamp);
                    //Todo other fields
                    return;
                }
                ++itr;
            }
            if (!is_update)
            {
                models::vehicle_status_intent vsi_obj;
                std::string is_allowed_int_str = mo.get_value_from_strategy_params("is_allowed_int");
                if (is_allowed_int_str.length() > 0)
                {
                    std::stringstream is_allowed_ss(is_allowed_int_str);
                    int is_allowed_int;
                    is_allowed_ss >> is_allowed_int;
                    vsi_obj.setIs_allowed(is_allowed_int);
                }
                vsi_obj.setVehicle_id(mo.getHeader().sender_id);
                vsi_obj.setBsm_id(mo.getHeader().sender_bsm_id);
                vsi_obj.setCur_timestamp(mo.getHeader().timestamp);
                //Todo other fields
                vsi_map_[mo.getHeader().sender_id] = vsi_obj;
            }
        }
References message_services::models::mobilityoperation::get_value_from_strategy_params(), message_services::models::mobilityoperation::getHeader(), message_services::models::mobility_header::sender_bsm_id, message_services::models::mobility_header::sender_id, message_services::models::vehicle_status_intent::setBsm_id(), message_services::models::vehicle_status_intent::setCur_timestamp(), message_services::models::vehicle_status_intent::setIs_allowed(), message_services::models::vehicle_status_intent::setVehicle_id(), message_services::models::mobility_header::timestamp, vsi_map_, and worker_mtx.
update_insert_by_incoming_mobilitypath_msg()
void message_services::workers::vehicle_status_intent_worker::update_insert_by_incoming_mobilitypath_msg (models::mobilitypath mp)
If the vehicle id from the mobilitypath message exist in vehicle status and intent map, update the vehicle status and intent base on the mobilitypath info. If the vehicle id from the mobilitypath message does not exist in vehicle status and intent map, insert a new the vehicle status and intent object to the map base on the mobilitypath info.
Parameters
mp_obj an instance of mobilitypath
Definition at line 88 of file vehicle_status_intent_worker.cpp.
        {
            std::unique_lock<std::mutex> lck(worker_mtx);
            std::map<std::string, models::vehicle_status_intent>::iterator itr = this->vsi_map_.begin();
            bool is_update = false;
            while (itr != this->vsi_map_.end())
            {
                if (itr->first == mp.getHeader().sender_id)
                {
                    is_update = true;
                    itr->second.setVehicle_id(mp.getHeader().sender_id);
                    itr->second.setBsm_id(mp.getHeader().sender_bsm_id);
                    itr->second.setCur_timestamp(mp.getHeader().timestamp);
                    //Todo other fields
                }
                ++itr;
            }
            if (!is_update)
            {
                models::vehicle_status_intent vsi_obj;
                vsi_obj.setVehicle_id(mp.getHeader().sender_id);
                vsi_obj.setBsm_id(mp.getHeader().sender_bsm_id);
                vsi_obj.setCur_timestamp(mp.getHeader().timestamp);
                //Todo update other fields
                vsi_map_[mp.getHeader().sender_id] = vsi_obj;
            }
        }
References message_services::models::mobilitypath::getHeader(), message_services::models::mobility_header::sender_bsm_id, message_services::models::mobility_header::sender_id, message_services::models::vehicle_status_intent::setBsm_id(), message_services::models::vehicle_status_intent::setCur_timestamp(), message_services::models::vehicle_status_intent::setVehicle_id(), message_services::models::mobility_header::timestamp, vsi_map_, and worker_mtx.
Member Data Documentation
vsi_map_
std::map<std::string, models::vehicle_status_intent> message_services::workers::vehicle_status_intent_worker::vsi_map_ private
Definition at line 23 of file vehicle_status_intent_worker.h.
Referenced by ~vehicle_status_intent_worker(), get_curr_map(), pop_element_from_map(), update_by_incoming_bsm_msg(), update_insert_by_incoming_mobilityoperation_msg(), and update_insert_by_incoming_mobilitypath_msg().
worker_mtx
std::mutex message_services::workers::vehicle_status_intent_worker::worker_mtx
Definition at line 28 of file vehicle_status_intent_worker.h.
Referenced by update_by_incoming_bsm_msg(), update_insert_by_incoming_mobilityoperation_msg(), and update_insert_by_incoming_mobilitypath_msg().
The documentation for this class was generated from the following files:
message_services/include/vehicle_status_intent_worker.h
message_services/src/workers/vehicle_status_intent_worker.cpp