Carma-streets: streets_signal_optimization::streets_desired_phase_plan_generator Class Reference
streets_signal_optimization::streets_desired_phase_plan_generator Class Reference
#include <streets_desired_phase_plan_generator.h>
Public Member Functions
streets_desired_phase_plan_generator ()=default
Construct a new desired phase plan generator object.
~streets_desired_phase_plan_generator ()=default
Destroy the desired phase plan generator object.
std::vector< streets_desired_phase_plan::streets_desired_phase_plan > generate_desire_phase_plan_list (const std::shared_ptr< OpenAPI::OAIIntersection_info > &intersection_info_ptr, std::unordered_map< std::string, streets_vehicles::vehicle > &vehicles, signal_phase_and_timing::intersection_state &intersection_state, const std::shared_ptr< streets_signal_optimization::movement_groups > &move_groups, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > &tsc_config_ptr)
Generate a list of desired phase plans. Each desired phase plan in the list includes the existing fixed future movement groups from the provided intersection_state and a new movement group with a given duration at the end. An empty desired phase plan list means that the desired phase plan converted from the spat cannot be updated. This can happen in one of the following scenarios:
streets_desired_phase_plan::streets_desired_phase_plan convert_spat_to_dpp (signal_phase_and_timing::intersection_state &intersection_state, const std::shared_ptr< streets_signal_optimization::movement_groups > &move_groups) const
Convert the provided intersection_state to a desired phase plan. The number of fixed future movement groups shall be at least 1.
uint64_t find_tbd_start_time (const streets_desired_phase_plan::streets_desired_phase_plan &base_desired_phase_plan, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > &tsc_config_ptr) const
Find the TBD start time based on the provided modified spat. The start time of the TBD area is equal to the end time of the last movement event of a given signal group\movement event.
void configure_scheduler (const std::shared_ptr< OpenAPI::OAIIntersection_info > &intersection_info_ptr)
Configure the scheduler pointer.
void create_signal_group_entry_lane_mapping (const std::shared_ptr< OpenAPI::OAIIntersection_info > &intersection_info_ptr)
Create signal group id to list of entry lane id mapping. Each signal group might be assigned to more than one entry lanes.
void set_configuration (const uint64_t _initial_green_buffer, const uint64_t _final_green_buffer, const uint64_t _et_inaccuracy_buffer, const uint64_t _queue_max_time_headway, const double _so_radius, const uint64_t _min_green, const uint64_t _max_green, const uint8_t _desired_future_move_group_count)
Set the configurable parameters to the desired values.
void set_initial_green_buffer (const uint64_t buffer)
Set the initial green buffer (ms). This value is used to account for the time it takes a vehicle before entering the intersection box at a green phase.
uint64_t get_initial_green_buffer () const
Get the initial green buffer (ms).
void set_final_green_buffer (const uint64_t buffer)
Set the final green buffer (ms). This value is used to account for safety. The assumption is that no vehicle shall enter the intersection box after the end of a green phase minus the final green buffer.
uint64_t get_final_green_buffer () const
Get the final green buffer (ms).
void set_et_inaccuracy_buffer (const uint64_t buffer)
Set the entering time (ET) inaccuracy_buffer (ms). This value is defined to account for entering time (ET) estimation inaccuracy. To find the required green duration for dissipating a queue from an entry lane, the end of the green is set to the estimated ET of the last vehicle in the queue plus this configurable parameter plus final_green_buffer.
uint64_t get_et_inaccuracy_buffer () const
Get the ET inaccuracy buffer (ms).
void set_queue_max_time_headway (const uint64_t buffer)
Set the queue max time headway (ms). This value defines the maximum allowed time headway between the estimated entering times (ETs) of two consecutive vehicles within a queue.
uint64_t get_queue_max_time_headway () const
Get the queue max time headway (ms).
void set_so_radius (const double radius)
Set the so area radius (meter). The signal optimization service only considers vehicles that are within the signal optimization area.
double get_so_radius () const
Get the so area radius (meter).
void set_min_green (const uint64_t _min_green)
Set the configurable minimum green (ms).
uint64_t get_min_green () const
Get the configurable minimum green (ms).
void set_max_green (const uint64_t _max_green)
Set the configurable maximum green (ms).
uint64_t get_max_green () const
Get the configurable maximum green (ms).
void set_desired_future_move_group_count (const uint8_t count)
Set the desired number of future movement groups.
uint8_t get_desired_future_move_group_count () const
Get the desired number of future movement groups.
std::unordered_map< uint8_t, std::vector< int > > get_signal_group_entry_lane_mapping () const
Get the entry lane to signal group mapping.
Private Member Functions
void verify_movement_group_list (const std::shared_ptr< OpenAPI::OAIIntersection_info > &intersection_info_ptr, const std::shared_ptr< streets_signal_optimization::movement_groups > &move_groups) const
Given an intersection_info pointer and a list of possible movement groups, this method checks if all signal groups included in the movement groups list are included in the intersection_info pointer. Basically, a signal group cannot be used if it is not connected to a given link lanelet (i.e., it does not exist in the intersection_info pointer). This method will throw exception if this requirement is not satisfied.
std::shared_ptr< streets_vehicle_scheduler::intersection_schedule > get_schedule_plan (std::unordered_map< std::string, streets_vehicles::vehicle > &vehicles) const
Given a map of vehicles and vehicle ids, this method will run the signalized_vehicle_scheduler methods to populate the signalized_intersection_schedule with a schedule for all vehicles in the vehicle map based on UC 3 scheduling logic which estimates vehicles' entering times to the intersection box based on the modified spat.
streets_vehicle_scheduler::signalized_intersection_schedule get_ev_schedules_within_so (const std::shared_ptr< streets_vehicle_scheduler::intersection_schedule > &sched_ptr, const std::unordered_map< std::string, streets_vehicles::vehicle > &vehicles) const
Given a populated signalized_intersection_schedule, this method will return a new signalized_intersection_schedule object that includes those EVs that are within the signal optimization area.
std::unordered_map< int, std::list< streets_vehicle_scheduler::signalized_vehicle_schedule > > get_schedules_in_tbd_per_lane (const streets_vehicle_scheduler::signalized_intersection_schedule &ev_schedules_within_so, const std::shared_ptr< OpenAPI::OAIIntersection_info > &intersection_info_ptr, const uint64_t &tbd_start) const
Given a populated signalized_intersection_schedule object, intersection_info shared pointer, and the start time of TBD area, This method returns a MAP of entry lanes as keys and a list of vehicle schedules for each entry lane as value. Only those vehicles that have an entering time (ET) after the start of the TBD area will be included in this mapping.
std::unordered_map< int, uint64_t > get_green_end_per_entry_lane (const std::unordered_map< int, std::list< streets_vehicle_scheduler::signalized_vehicle_schedule > > &schedules_in_tbd, const uint64_t &tbd_start) const
Given a list of signalized_vehicle_schedules to entry lane id mapping, for each entry lane, this method will find the last vehicle in the queue, calculates the queue dissipation time, and finally returns the end time for the required green duration to dissipate the queue. The last vehicle in the queue is the vehicle that has entering time (ET) equal to its earliest entering time (EET) and the time headway between its ET and its following vehicle's ET is greater than the configurable queue_max_time_headway parameter. If such a vehicle could not be found, the last vehicle in the entry lane will be considered as the last vehicle in the queue.
streets_vehicle_scheduler::signalized_vehicle_schedule get_last_vehicle_in_queue (const std::list< streets_vehicle_scheduler::signalized_vehicle_schedule > &evs_in_lane) const
Given a list of signalized_vehicle_schedules for an entry lane, this method will find the last vehicle in the queue. The last vehicle in the queue is the vehicle that has entering time (ET) equal to its earliest entering time (EET) and the time headway between its ET and its following vehicle's ET is greater than the configurable queue_max_time_headway parameter. If such a vehicle could not be found, the last vehicle in the entry lane will be considered as the last vehicle in the queue.
void update_desired_phase_plan_list (const std::shared_ptr< streets_signal_optimization::movement_groups > &move_groups, const std::unordered_map< int, uint64_t > &green_end_per_entry_lane, const streets_desired_phase_plan::streets_desired_phase_plan &base_desired_phase_plan, std::vector< streets_desired_phase_plan::streets_desired_phase_plan > &desired_phase_plan_list, const std::shared_ptr< OpenAPI::OAIIntersection_info > &intersection_info_ptr, const uint64_t &tbd_start)
Given a list of movement groups, a mapping of the end time of required green duration for clearing the queue to entry lane id, and an updated base_desired_phase_plan, this method with create a list of desired phase plans, where each desired phase plan in the list includes the existing fixed future movement groups from the received spat and a new movement group with a given duration at the end. For each movement group, this method first checks if the movement group can be added to the base_desired_phase_plan (i.e., if the movement group has a common signal group with the last movement group in the base_desired_phase_plan). If the movement group can be added, for each entry lane allowed by the subject movement group, this method will add a new desired phase plan to the list, where the last movement group is the subject movement group and the end time of the green is the end time of required green duration for clearing the queue of the subject entry lane.
uint8_t find_signal_group_for_entry_lane (const std::shared_ptr< OpenAPI::OAIIntersection_info > &intersection_info_ptr, const OpenAPI::OAILanelet_info &entry_lane_info) const
Given the entry lane object, this method finds the signal group id. Note: The signalized_vehicle_scheduler is only capable of understanding intersection where all connection lanes from a single entry lane share a signal_group_id. Therefore, vehicles from an entry lane with different directions at the intersection box shall be able to receive protected green at the same time.
FRIEND_TEST (test_streets_desired_phase_plan_generator, test_generate_desired_phase_plan_list)
Private Attributes
std::shared_ptr< streets_vehicle_scheduler::signalized_vehicle_scheduler > scheduler_ptr
A shared pointer to the signalized vehicle scheduler.
streets_desired_phase_plan_generator_configuration config
A struct containing the configurable parameters for desired_phsae_plan_generator functions.
bool is_configured = false
The bool parameter defining whether the configurable parameter are set to their desired values or not.
std::unordered_map< uint8_t, std::vector< int > > signal_group_entry_lane_mapping
Map of signal group to vector of entry lanes that are served by this signal group.. Each signal group might be assigned to more than one entry lanes.
Detailed Description
Definition at line 24 of file streets_desired_phase_plan_generator.h.
Constructor & Destructor Documentation
streets_desired_phase_plan_generator()
streets_signal_optimization::streets_desired_phase_plan_generator::streets_desired_phase_plan_generator () default
Construct a new desired phase plan generator object.
~streets_desired_phase_plan_generator()
streets_signal_optimization::streets_desired_phase_plan_generator::~streets_desired_phase_plan_generator () default
Destroy the desired phase plan generator object.
Member Function Documentation
configure_scheduler()
void streets_signal_optimization::streets_desired_phase_plan_generator::configure_scheduler (const std::shared_ptr< OpenAPI::OAIIntersection_info > & intersection_info_ptr)
Configure the scheduler pointer.
Parameters
intersection_info_ptr An intersection_info pointer.
configure the signalized_vehicle_scheduler pointer
Definition at line 286 of file streets_desired_phase_plan_generator.cpp.
{
        scheduler_ptr = std::make_shared<streets_vehicle_scheduler::signalized_vehicle_scheduler>();
        scheduler_ptr->set_intersection_info(intersection_info_ptr);
        scheduler_ptr->set_initial_green_buffer(config.initial_green_buffer);
        scheduler_ptr->set_final_green_buffer(config.final_green_buffer);
    }
References config, streets_signal_optimization::streets_desired_phase_plan_generator_configuration::final_green_buffer, streets_signal_optimization::streets_desired_phase_plan_generator_configuration::initial_green_buffer, and scheduler_ptr.
Referenced by generate_desire_phase_plan_list().
convert_spat_to_dpp()
streets_desired_phase_plan::streets_desired_phase_plan streets_signal_optimization::streets_desired_phase_plan_generator::convert_spat_to_dpp (signal_phase_and_timing::intersection_state & intersection_state, const std::shared_ptr< streets_signal_optimization::movement_groups > & move_groups) const
Convert the provided intersection_state to a desired phase plan. The number of fixed future movement groups shall be at least 1.
Parameters
intersection_info_ptr An intersection_info pointer.
move_groups Shared pointer to a list of possible movement groups.
Returns
streets_desired_phase_plan::streets_desired_phase_plan desired phase plan converted from intersection_state.
Exceptions
If a movement state does not have any movement event in its state_time_speed list.
If a signal group has a green timing that partially overlaps with a green timing of another signal group.
is_added parameter checks if mg_green has been added to the base_desired_phase_plan somewhere before the last existing movement_group. If this parameter is false at the end of the for loop, mg_green must be added to the end of the list.
If is_added is false, mg_green is not added to the base_desired_phase_plan which means that mg_green must be added to the end of the list!
Definition at line 156 of file streets_desired_phase_plan_generator.cpp.
{
        streets_desired_phase_plan::streets_desired_phase_plan base_desired_phase_plan;
        base_desired_phase_plan.timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
        std::vector<streets_desired_phase_plan::signal_group2green_phase_timing> mg_green_list;
        for (const auto& mg : move_groups->groups) {
            signal_phase_and_timing::movement_state move_state_1;
            signal_phase_and_timing::movement_state move_state_2;
            move_state_1 = intersection_state.get_movement(mg.signal_groups.first);
            if (move_state_1.state_time_speed.empty()) {
                throw streets_desired_phase_plan_generator_exception("signal group " + std::to_string(move_state_1.signal_group) + " has empty movement_state list in the provided intersection_state object!");
            }
            if (mg.signal_groups.second != 0) {
                move_state_2 = intersection_state.get_movement(mg.signal_groups.second);
                if (move_state_2.state_time_speed.empty()) {
                    throw streets_desired_phase_plan_generator_exception("signal group " + std::to_string(move_state_2.signal_group) + " has empty movement_state list in the provided intersection_state object!");
                }
            }
            for (const auto& me1 : move_state_1.state_time_speed) {
                if (me1.event_state == signal_phase_and_timing::movement_phase_state::protected_movement_allowed) {
                    streets_desired_phase_plan::signal_group2green_phase_timing movement_group;
                    movement_group.start_time = me1.timing.get_epoch_start_time();
                    movement_group.end_time = me1.timing.get_epoch_min_end_time();
                    movement_group.signal_groups.push_back(move_state_1.signal_group);
                    if (mg.signal_groups.second == 0) {
                        mg_green_list.push_back(movement_group);
                        continue;
                    }
                    for (const auto& me2 : move_state_2.state_time_speed) {
                        if (me2.event_state == signal_phase_and_timing::movement_phase_state::protected_movement_allowed &&
                                    ((me2.timing.get_epoch_start_time() < me1.timing.get_epoch_start_time() &&
                                    me2.timing.get_epoch_min_end_time() > me1.timing.get_epoch_start_time()) ||
                                    (me2.timing.get_epoch_start_time() < me1.timing.get_epoch_min_end_time() &&
                                    me2.timing.get_epoch_min_end_time() > me1.timing.get_epoch_min_end_time()))) {
                            throw streets_desired_phase_plan_generator_exception("spat has fixed future signal groups with partially overlapping green durations!");
                        }
                        if (me2.event_state == signal_phase_and_timing::movement_phase_state::protected_movement_allowed &&
                                    me2.timing.get_epoch_start_time() == me1.timing.get_epoch_start_time() &&
                                    me2.timing.get_epoch_min_end_time() == me1.timing.get_epoch_min_end_time()) {
                            movement_group.signal_groups.push_back(move_state_2.signal_group);
                            mg_green_list.push_back(movement_group);
                            break;
                        }
                        else if (me2.timing.get_epoch_start_time() > me1.timing.get_epoch_start_time()) {
                            break;
                        }
                    }
                }
            }
        }
        for (const auto& mg_green : mg_green_list) {
            if (base_desired_phase_plan.desired_phase_plan.empty()) {
                base_desired_phase_plan.desired_phase_plan.push_back(mg_green);
            }
            else {
                bool is_added = false;
                for (int index = 0; index < base_desired_phase_plan.desired_phase_plan.size(); ++index) {
                    if ( (mg_green.start_time < base_desired_phase_plan.desired_phase_plan[index].start_time &&
                                mg_green.end_time > base_desired_phase_plan.desired_phase_plan[index].start_time) ||
                            (mg_green.start_time < base_desired_phase_plan.desired_phase_plan[index].end_time &&
                                mg_green.end_time > base_desired_phase_plan.desired_phase_plan[index].end_time) ) {
                        throw streets_desired_phase_plan_generator_exception("spat has future movement groups with partially overlapping green durations!");
                    }
                    if (mg_green.end_time < base_desired_phase_plan.desired_phase_plan[index].start_time) {
                        base_desired_phase_plan.desired_phase_plan.insert(base_desired_phase_plan.desired_phase_plan.begin() + index, mg_green);
                        is_added = true;
                        break;
                    }
                }
                if (!is_added) {
                    base_desired_phase_plan.desired_phase_plan.push_back(mg_green);
                }
            }
        }
        SPDLOG_DEBUG("Base desired phase plan converted from the modified spat: {0}", base_desired_phase_plan.toJson());
        return base_desired_phase_plan;
    }
References streets_desired_phase_plan::streets_desired_phase_plan::desired_phase_plan, signal_phase_and_timing::intersection_state::get_movement(), signal_phase_and_timing::protected_movement_allowed, signal_phase_and_timing::movement_state::signal_group, streets_signal_optimization::movement_group::signal_groups, signal_phase_and_timing::movement_state::state_time_speed, streets_desired_phase_plan::streets_desired_phase_plan::timestamp, to_string(), and streets_desired_phase_plan::streets_desired_phase_plan::toJson().
Referenced by generate_desire_phase_plan_list().
create_signal_group_entry_lane_mapping()
void streets_signal_optimization::streets_desired_phase_plan_generator::create_signal_group_entry_lane_mapping (const std::shared_ptr< OpenAPI::OAIIntersection_info > & intersection_info_ptr)
Create signal group id to list of entry lane id mapping. Each signal group might be assigned to more than one entry lanes.
Parameters
intersection_info_ptr An intersection_info pointer.
Definition at line 497 of file streets_desired_phase_plan_generator.cpp.
{
        signal_group_entry_lane_mapping.clear();
        for ( const auto &lane : intersection_info_ptr->getEntryLanelets() ) {
            uint8_t signal_group = find_signal_group_for_entry_lane(intersection_info_ptr, lane);
            SPDLOG_DEBUG("Creating signal group to entry lane mapping - entry lane id = {0}, signal group id = {1}", lane.getId(), signal_group);
            if (signal_group_entry_lane_mapping.find(signal_group) == signal_group_entry_lane_mapping.end()) {
                std::vector<int> lane_ids;
                lane_ids.push_back(lane.getId());
                signal_group_entry_lane_mapping.try_emplace(signal_group, lane_ids);
            }
            else {
                signal_group_entry_lane_mapping.at(signal_group).push_back(lane.getId());
            }
        }
    }
References find_signal_group_for_entry_lane(), and signal_group_entry_lane_mapping.
Referenced by update_desired_phase_plan_list().
find_signal_group_for_entry_lane()
uint8_t streets_signal_optimization::streets_desired_phase_plan_generator::find_signal_group_for_entry_lane (const std::shared_ptr< OpenAPI::OAIIntersection_info > & intersection_info_ptr, const OpenAPI::OAILanelet_info & entry_lane_info) const private
Given the entry lane object, this method finds the signal group id. Note: The signalized_vehicle_scheduler is only capable of understanding intersection where all connection lanes from a single entry lane share a signal_group_id. Therefore, vehicles from an entry lane with different directions at the intersection box shall be able to receive protected green at the same time.
Parameters
intersection_info_ptr An intersection_info pointer.
entry_lane_info entry lanelet lane.
Returns
uint8_t signal group id
Exceptions
If a connection link lanelet does not have a signal group id.
If two or more connection link lanelets from a single entry lane have different signal group ids.
Definition at line 516 of file streets_desired_phase_plan_generator.cpp.
{
        // check if all links connected to the entry lane have the same signal ids or not!
        uint8_t signal_group_id = 0;
        bool first_link_visited = false;
        auto connection_lanelet_ids = entry_lane_info.getConnectingLaneletIds();
        for ( const auto &lane : intersection_info_ptr->getLinkLanelets() ) {
            // check if the link lanelet's id (lane.getId()) is included in the list of connecting lanelet ids of the received entry lanelet.
            if ( std::find(connection_lanelet_ids.begin(), connection_lanelet_ids.end(), lane.getId()) != connection_lanelet_ids.end() ) {
                if ( !lane.getSignalGroupId() ) {
                    throw streets_desired_phase_plan_generator_exception("The connection link lanelet does not have a group_id!");
                }
                if (first_link_visited && lane.getSignalGroupId() != signal_group_id){
                    throw streets_desired_phase_plan_generator_exception("The link lanelets connected to the entry lane have different signal_group_ids! The streets_desired_phase_plan_generator is only capable of understanding intersection where all connection lanes from a single entry lane share a signal_group_id!");
                }
                if (!first_link_visited) {
                    signal_group_id = lane.getSignalGroupId();
                    first_link_visited = true;
                }
            }
        }
        if (signal_group_id == 0) {
            throw streets_desired_phase_plan_generator_exception("Could not find signal group id for entry lane " +
                                    std::to_string(entry_lane_info.getId()) + "!");
        }
        return signal_group_id;
    }
References OpenAPI::OAILanelet_info::getConnectingLaneletIds(), OpenAPI::OAILanelet_info::getId(), and to_string().
Referenced by create_signal_group_entry_lane_mapping().
find_tbd_start_time()
uint64_t streets_signal_optimization::streets_desired_phase_plan_generator::find_tbd_start_time (const streets_desired_phase_plan::streets_desired_phase_plan & base_desired_phase_plan, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > & tsc_config_ptr) const
Find the TBD start time based on the provided modified spat. The start time of the TBD area is equal to the end time of the last movement event of a given signal group\movement event.
Parameters
base_desired_phase_plan The desired_phase_plan converted from the provided intersection_state.
tsc_config_ptr shared pointer to tsc configuration state object.
Returns
uint64_t start time of TBD.
Exceptions
An exception if the base_desired_phase_plan converted from spat is empty.
An exception if the tsc_config_ptr does not include the configuration parameter for a signal group.
An exception if the maximum (yellow_change_interval + red_clearance) for the last movement group stays zero!
Definition at line 254 of file streets_desired_phase_plan_generator.cpp.
{
        uint64_t tbd_start = 0;
        if (base_desired_phase_plan.desired_phase_plan.empty()) {
            throw streets_desired_phase_plan_generator_exception("No green movement group is found in the spat. base_desired_phase_plan is empty!");
        }
        // find the last fixed movement group in the base_desired_phase_plan
        auto last_movement_group = base_desired_phase_plan.desired_phase_plan.back();
        uint64_t yellow_red_interval_local = 0;
        uint64_t yellow_red_interval_max = 0;
        // find the maximum (yellow_change_duration + red_clearance) for the signal groups included in the last fixed movement group
        for (const auto sg : last_movement_group.signal_groups) {
            auto sg_config = tsc_config_ptr->get_signal_group_configuration_by_sg(sg);
            if (sg != static_cast<int>(sg_config.signal_group_id)) {
                throw streets_desired_phase_plan_generator_exception("TSC_config does not have signal group " + std::to_string(sg) + "'s configuration parameters!");
            }
            yellow_red_interval_local = static_cast<uint64_t>(sg_config.yellow_change_duration + sg_config.red_clearance);
            if (yellow_red_interval_max < yellow_red_interval_local) {
                yellow_red_interval_max = yellow_red_interval_local;
            }
        }
        if (yellow_red_interval_max == 0) {
            throw streets_desired_phase_plan_generator_exception("yellow_red_interval_max that stores the maximum (yellow_change_duration + red_clearance) for the signal groups included in the last fixed movement group, is not updated!");
        }
        tbd_start = last_movement_group.end_time + yellow_red_interval_max;
        SPDLOG_DEBUG("TBD start time: {0}", tbd_start);
        return tbd_start;
    }
References streets_desired_phase_plan::streets_desired_phase_plan::desired_phase_plan, and to_string().
Referenced by generate_desire_phase_plan_list().
FRIEND_TEST()
streets_signal_optimization::streets_desired_phase_plan_generator::FRIEND_TEST (test_streets_desired_phase_plan_generator , test_generate_desired_phase_plan_list) private
generate_desire_phase_plan_list()
std::vector< streets_desired_phase_plan::streets_desired_phase_plan > streets_signal_optimization::streets_desired_phase_plan_generator::generate_desire_phase_plan_list (const std::shared_ptr< OpenAPI::OAIIntersection_info > & intersection_info_ptr, std::unordered_map< std::string, streets_vehicles::vehicle > & vehicles, signal_phase_and_timing::intersection_state & intersection_state, const std::shared_ptr< streets_signal_optimization::movement_groups > & move_groups, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > & tsc_config_ptr)
Generate a list of desired phase plans. Each desired phase plan in the list includes the existing fixed future movement groups from the provided intersection_state and a new movement group with a given duration at the end. An empty desired phase plan list means that the desired phase plan converted from the spat cannot be updated. This can happen in one of the following scenarios:
There are no vehicles in the SO area.
All vehicles can enter the intersection box within the already fixed future movement groups (i.e., there are no vehicle with ET greater than the start time of the TBD area.).
No movement group that serves vehicles can be added to the end of the movement event list from the spat due to repeating signal group constraint (i.e., a movement group that has a common signal group with the last fixed future movement group in spat).
Parameters
intersection_info_ptr An intersection_info pointer.
vehicles A map of the vehicles to schedule, with vehicle id as keys.
intersection_state An intersection_state object from the most recent spat.
move_groups Shared pointer to a list of possible movement groups.
tsc_config_ptr shared pointer to tsc configuration state object.
Returns
vector<streets_desired_phase_plan::streets_desired_phase_plan> list of desired phase plans.
Exceptions
if the provided intersection_state does not have any fixed future movement group.
First, check if all signal groups included in the movement group list exist in the intersection_info pointer (i.e., each signal group is connected to at least one link lanelet).
If the configurable parameters are not set, set them to their default values. Default values:
initial_green_buffer = 2,000 ms
final_green_buffer = 2,000 ms
et_inaccuracy_buffer = 2,000 ms
queue_max_time_headway = 3,000 ms
so_radius = 200 meter
min_green = 50,000 ms
max_green = 120,000 ms
desired_future_move_group_count = 1
Convert the provided intersection_state to a desired_phase_plan and name it base_desired_phase_plan. If base_desired_phase_plan is empty, then throw exception. If the number of fixed movement group in base_desired_phase_plan is greater than the desired number of fixed movement groups, then there is no need for adding a new movement group to base_desired_phase_plan. Thus, return an empty desired_phase_plan_list. Otherwise, find the start time of the TBD area and continue.
The provided spat have only a configurable number of fixed future movement groups. Any time area after the fixed future movement groups is defined as the to-be-determined (TBD) area. Basically, the TBD area starts from the end time of the red clearance of the last fixed greens. If a vehicle's estimated entering time (ET) is within the TBD area (after the end time of the last movement_state), the vehicle will be considered in the queue calculation.
If the vehicle map is empty, return an empty desired phase plan list.
Create a local spat pointer. Check if the scheduler pointer is configured. Set the spat in the scheduler pointer. Then, schedule all vehicles and get the intersection_scheduler pointer
Then, add the schedule plans for those EVs that are within the SO area to a separate signalized_intersection_schedule object. If the new list is empty (i.e., there is no EV in the SO area), return an empty desired phase plan list.
Then, seperate EV schedules that have estimated entering times (ETs) within TBD area based on their entry lane. The list of EV schedules for each entry lane is sorted based on the estimated ET. If the schedules in TBD per entry lane map is empty (i.e., there is no EV with an estimated ET within TBD area), return an empty desired phase plan list.
For each entry lane, find the last vehicle in the queue, calculate the queue dissipation time, and finally, estimate the end time of the required green for dissipation the queue from the subject entry lane. If the green end time per entry lane map is empty, throw exception (there are EVs with estimated ET within TVD area, but there is no green considered for any vehicle!) and return an empty desired phase plan list.
For each possible movement group, first, check if the movement group can be added to the base desired phase plan, (check if the subject movement group has a common signal group with the last movement group in the base desired phase plan list or not!). If the movement group can be added to the base desired phase plan, for each entry lane included in the subject movement group, add a new desired phase plan to the desired phase plan list where the subject movement group is added to the base desired phsae plan with the green end time calculated for the entry lane. If the desired phase plan list is empty, it means that no movement group that clears a given queue can be added to the base desired phase plan.
Definition at line 6 of file streets_desired_phase_plan_generator.cpp.
{
        std::vector<streets_desired_phase_plan::streets_desired_phase_plan> desired_phase_plan_list;
        verify_movement_group_list(intersection_info_ptr, move_groups);
        if (!is_configured) {
            SPDLOG_WARN("set_configuration was not called. Setting configuration to default!");
            set_configuration(2000, 2000, 2000, 3000, 200, 5000, 120000, 1);
        }
        streets_desired_phase_plan::streets_desired_phase_plan base_desired_phase_plan = convert_spat_to_dpp(intersection_state, move_groups);
        if (base_desired_phase_plan.desired_phase_plan.empty()) {
            throw streets_desired_phase_plan_generator_exception("No green movement group is found in the spat. base_desired_phase_plan is empty!");
        }
        if (base_desired_phase_plan.desired_phase_plan.size() > config.desired_future_move_group_count) {
            SPDLOG_DEBUG("The number of fixed future movement groups in the modified spat ({0}) is greater than the desired number of fixed future movement groups ({1})!", base_desired_phase_plan.desired_phase_plan.size(), config.desired_future_move_group_count);
            return desired_phase_plan_list;
        }
        uint64_t tbd_start = find_tbd_start_time(base_desired_phase_plan, tsc_config_ptr);
        if ( vehicles.empty() ) {
            SPDLOG_DEBUG("No vehicles to schedule.");
            return desired_phase_plan_list;
        }
        auto spat_ptr = std::make_shared<signal_phase_and_timing::spat>();
        spat_ptr->set_intersection(intersection_state);
        if (!scheduler_ptr) {
            SPDLOG_DEBUG("scheduler_ptr is not configured!");
            configure_scheduler(intersection_info_ptr);
        }
        scheduler_ptr->set_spat(spat_ptr);
        std::shared_ptr<streets_vehicle_scheduler::intersection_schedule> sched_ptr = get_schedule_plan(vehicles);
        streets_vehicle_scheduler::signalized_intersection_schedule ev_schedules_within_so = get_ev_schedules_within_so(sched_ptr, vehicles);
        if (ev_schedules_within_so.vehicle_schedules.empty()){
            SPDLOG_DEBUG("No EV within the SO area.");
            return desired_phase_plan_list;
        }
        std::unordered_map<int, std::list<streets_vehicle_scheduler::signalized_vehicle_schedule>> schedules_in_tbd = get_schedules_in_tbd_per_lane(ev_schedules_within_so, intersection_info_ptr, tbd_start);
        if (schedules_in_tbd.empty()){
            SPDLOG_DEBUG("No EV within the TBD area.");
            return desired_phase_plan_list;
        }
        std::unordered_map<int, uint64_t> green_end_per_entry_lane = get_green_end_per_entry_lane(schedules_in_tbd, tbd_start);
        if (green_end_per_entry_lane.empty()) {
            SPDLOG_WARN("Vehicles schedules in TBD is not empty, green_end_per_entry_lane map is empty!");
            return desired_phase_plan_list;
        }
        update_desired_phase_plan_list(move_groups, green_end_per_entry_lane, base_desired_phase_plan, desired_phase_plan_list, intersection_info_ptr, tbd_start);
        if (desired_phase_plan_list.empty()) {
            SPDLOG_WARN("No movement group could be added and thus, the desired_phase_plan_list is empty!");
        }
        return desired_phase_plan_list;
    }
References config, configure_scheduler(), convert_spat_to_dpp(), streets_signal_optimization::streets_desired_phase_plan_generator_configuration::desired_future_move_group_count, streets_desired_phase_plan::streets_desired_phase_plan::desired_phase_plan, find_tbd_start_time(), get_ev_schedules_within_so(), get_green_end_per_entry_lane(), get_schedule_plan(), get_schedules_in_tbd_per_lane(), is_configured, scheduler_ptr, set_configuration(), update_desired_phase_plan_list(), streets_vehicle_scheduler::signalized_intersection_schedule::vehicle_schedules, and verify_movement_group_list().
get_desired_future_move_group_count()
uint8_t streets_signal_optimization::streets_desired_phase_plan_generator::get_desired_future_move_group_count () const
Get the desired number of future movement groups.
Returns
uint8_t desired number of future movement group..
Definition at line 634 of file streets_desired_phase_plan_generator.cpp.
{
        return config.desired_future_move_group_count;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::desired_future_move_group_count.
get_et_inaccuracy_buffer()
uint64_t streets_signal_optimization::streets_desired_phase_plan_generator::get_et_inaccuracy_buffer () const
Get the ET inaccuracy buffer (ms).
Returns
uint64_t ET inaccuracy buffer in milliseconds.
Definition at line 594 of file streets_desired_phase_plan_generator.cpp.
{
        return config.et_inaccuracy_buffer;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::et_inaccuracy_buffer.
get_ev_schedules_within_so()
streets_vehicle_scheduler::signalized_intersection_schedule streets_signal_optimization::streets_desired_phase_plan_generator::get_ev_schedules_within_so (const std::shared_ptr< streets_vehicle_scheduler::intersection_schedule > & sched_ptr, const std::unordered_map< std::string, streets_vehicles::vehicle > & vehicles) const private
Given a populated signalized_intersection_schedule, this method will return a new signalized_intersection_schedule object that includes those EVs that are within the signal optimization area.
Parameters
sched_ptr An intersection_schedule shared pointer populated with vehicle schedules.
vehicles A map of the vehicles to schedule, with vehicle id as keys.
Returns
streets_vehicle_scheduler::signalized_intersection_schedule A signalized_intersection_schedule object.
Definition at line 310 of file streets_desired_phase_plan_generator.cpp.
{
        auto schedule_ptr = std::dynamic_pointer_cast<streets_vehicle_scheduler::signalized_intersection_schedule> (sched_ptr);
        streets_vehicle_scheduler::signalized_intersection_schedule ev_schedules_within_so;
        for (const auto& veh_sched : schedule_ptr->vehicle_schedules) {
            if (veh_sched.state == streets_vehicles::vehicle_state::EV && vehicles.at(veh_sched.v_id)._cur_distance <= config.so_radius) {
                ev_schedules_within_so.vehicle_schedules.push_back(veh_sched);
            }
        }
        return ev_schedules_within_so;
    }
References config, streets_vehicles::EV, streets_signal_optimization::streets_desired_phase_plan_generator_configuration::so_radius, and streets_vehicle_scheduler::signalized_intersection_schedule::vehicle_schedules.
Referenced by generate_desire_phase_plan_list().
get_final_green_buffer()
uint64_t streets_signal_optimization::streets_desired_phase_plan_generator::get_final_green_buffer () const
Get the final green buffer (ms).
Returns
uint64_t final green buffer in milliseconds.
Definition at line 586 of file streets_desired_phase_plan_generator.cpp.
{
        return config.final_green_buffer;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::final_green_buffer.
get_green_end_per_entry_lane()
std::unordered_map< int, uint64_t > streets_signal_optimization::streets_desired_phase_plan_generator::get_green_end_per_entry_lane (const std::unordered_map< int, std::list< streets_vehicle_scheduler::signalized_vehicle_schedule > > & schedules_in_tbd, const uint64_t & tbd_start) const private
Given a list of signalized_vehicle_schedules to entry lane id mapping, for each entry lane, this method will find the last vehicle in the queue, calculates the queue dissipation time, and finally returns the end time for the required green duration to dissipate the queue. The last vehicle in the queue is the vehicle that has entering time (ET) equal to its earliest entering time (EET) and the time headway between its ET and its following vehicle's ET is greater than the configurable queue_max_time_headway parameter. If such a vehicle could not be found, the last vehicle in the entry lane will be considered as the last vehicle in the queue.
Parameters
schedules_in_tbd A list of signalized_vehicle_schedules to entry lane mapping.
tbd_start Start time of the TBD area.
Returns
unordered_map<int, uint64_t> End time of required green duration for clearing the queue to entry lane id mapping.
Definition at line 352 of file streets_desired_phase_plan_generator.cpp.
{
        std::unordered_map<int, uint64_t> green_end_per_entry_lane;
        for (const auto &[entry_lane_id, evs_in_lane] : schedules_in_tbd) {
            SPDLOG_DEBUG("Calculate green end time for entry lane {0}", entry_lane_id);
            // Get last vehicle in queue
            if (!evs_in_lane.empty()) {
                streets_vehicle_scheduler::signalized_vehicle_schedule last_ev_in_queue = get_last_vehicle_in_queue(evs_in_lane);
                uint64_t et_rounded = uint64_t(std::ceil(double(last_ev_in_queue.et)/100.0) * 100);
                uint64_t green_end_compared_with_min_green = std::max(et_rounded + config.et_inaccuracy_buffer + config.final_green_buffer, tbd_start + config.min_green);
                uint64_t green_end = std::min(green_end_compared_with_min_green, tbd_start + config.max_green);
                // in case the green_end is overwritten by max_green, check if there is any ET within the new green duration.
                // if not, skip this entry lane, assuming there is no queue that can be served.
                if (green_end < green_end_compared_with_min_green && evs_in_lane.front().et >= green_end - config.final_green_buffer) {
                    SPDLOG_WARN("The required green duration for dissipation the queue in entry lane " +
                            std::to_string(entry_lane_id) +
                            " is overwritten by max_green which cannot serve any vehicle! green_end without considering max_green: " +
                            std::to_string(green_end_compared_with_min_green) +
                            ", green_end considering max_green: " + std::to_string(green_end) +
                            ", first EV's entering time: " + std::to_string(evs_in_lane.front().et) + ".");
                }
                else
                {
                    green_end_per_entry_lane.try_emplace(entry_lane_id, green_end);
                }
            }
            else {
                SPDLOG_DEBUG("There are no EVs in entry lane {0} that is within the SO area and has an estimated ET after the start time of the TBD area", entry_lane_id);
            }
        }
        return green_end_per_entry_lane;
    }
References config, streets_vehicle_scheduler::signalized_vehicle_schedule::et, streets_signal_optimization::streets_desired_phase_plan_generator_configuration::et_inaccuracy_buffer, streets_signal_optimization::streets_desired_phase_plan_generator_configuration::final_green_buffer, get_last_vehicle_in_queue(), streets_signal_optimization::streets_desired_phase_plan_generator_configuration::max_green, streets_signal_optimization::streets_desired_phase_plan_generator_configuration::min_green, and to_string().
Referenced by generate_desire_phase_plan_list().
get_initial_green_buffer()
uint64_t streets_signal_optimization::streets_desired_phase_plan_generator::get_initial_green_buffer () const
Get the initial green buffer (ms).
Returns
uint64_t initial green buffer in milliseconds.
Definition at line 578 of file streets_desired_phase_plan_generator.cpp.
{
        return config.initial_green_buffer;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::initial_green_buffer.
get_last_vehicle_in_queue()
streets_vehicle_scheduler::signalized_vehicle_schedule streets_signal_optimization::streets_desired_phase_plan_generator::get_last_vehicle_in_queue (const std::list< streets_vehicle_scheduler::signalized_vehicle_schedule > & evs_in_lane) const private
Given a list of signalized_vehicle_schedules for an entry lane, this method will find the last vehicle in the queue. The last vehicle in the queue is the vehicle that has entering time (ET) equal to its earliest entering time (EET) and the time headway between its ET and its following vehicle's ET is greater than the configurable queue_max_time_headway parameter. If such a vehicle could not be found, the last vehicle in the entry lane will be considered as the last vehicle in the queue.
Parameters
evs_in_lane A list of signalized_vehicle_schedules for an entry lane.
Returns
streets_vehicle_scheduler::signalized_vehicle_schedule The schedule of the last vehicle in the queue.
Definition at line 394 of file streets_desired_phase_plan_generator.cpp.
{
        bool is_last_vehicle_in_queue_found = false;
        streets_vehicle_scheduler::signalized_vehicle_schedule prev_ev_sched;
        streets_vehicle_scheduler::signalized_vehicle_schedule last_ev_in_queue;
        for (const auto &ev_sched : evs_in_lane) {
            if (ev_sched.v_id != evs_in_lane.front().v_id && ev_sched.et == ev_sched.eet && (ev_sched.et - prev_ev_sched.et >= config.queue_max_time_headway)) {
                is_last_vehicle_in_queue_found = true;
                last_ev_in_queue = prev_ev_sched;
            }
            prev_ev_sched = ev_sched;
        }
        if (!is_last_vehicle_in_queue_found) {
            last_ev_in_queue = evs_in_lane.back();
        }
        return last_ev_in_queue;
    }
References config, streets_vehicle_scheduler::signalized_vehicle_schedule::et, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::queue_max_time_headway.
Referenced by get_green_end_per_entry_lane().
get_max_green()
uint64_t streets_signal_optimization::streets_desired_phase_plan_generator::get_max_green () const
Get the configurable maximum green (ms).
Returns
uint64_t maximum green in milliseconds.
Definition at line 626 of file streets_desired_phase_plan_generator.cpp.
{
        return config.max_green;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::max_green.
get_min_green()
uint64_t streets_signal_optimization::streets_desired_phase_plan_generator::get_min_green () const
Get the configurable minimum green (ms).
Returns
uint64_t minimum green in milliseconds.
Definition at line 618 of file streets_desired_phase_plan_generator.cpp.
{
        return config.min_green;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::min_green.
get_queue_max_time_headway()
uint64_t streets_signal_optimization::streets_desired_phase_plan_generator::get_queue_max_time_headway () const
Get the queue max time headway (ms).
Returns
uint64_t queue max time headway in milliseconds.
Definition at line 602 of file streets_desired_phase_plan_generator.cpp.
{
        return config.queue_max_time_headway;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::queue_max_time_headway.
get_schedule_plan()
std::shared_ptr< streets_vehicle_scheduler::intersection_schedule > streets_signal_optimization::streets_desired_phase_plan_generator::get_schedule_plan (std::unordered_map< std::string, streets_vehicles::vehicle > & vehicles) const private
Given a map of vehicles and vehicle ids, this method will run the signalized_vehicle_scheduler methods to populate the signalized_intersection_schedule with a schedule for all vehicles in the vehicle map based on UC 3 scheduling logic which estimates vehicles' entering times to the intersection box based on the modified spat.
Parameters
vehicles A map of the vehicles to schedule, with vehicle id as keys.
Returns
std::shared_ptr<streets_vehicle_scheduler::intersection_schedule> An intersection_schedule shared pointer.
configure the signalized_intersection_schedule pointer
schedule vehicles
Definition at line 296 of file streets_desired_phase_plan_generator.cpp.
{
        std::shared_ptr<streets_vehicle_scheduler::intersection_schedule> sched_ptr;
        sched_ptr = std::make_shared<streets_vehicle_scheduler::signalized_intersection_schedule>();
        sched_ptr->timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
        scheduler_ptr->schedule_vehicles(vehicles, sched_ptr);
        return sched_ptr;
    }
References scheduler_ptr.
Referenced by generate_desire_phase_plan_list().
get_schedules_in_tbd_per_lane()
std::unordered_map< int, std::list< streets_vehicle_scheduler::signalized_vehicle_schedule > > streets_signal_optimization::streets_desired_phase_plan_generator::get_schedules_in_tbd_per_lane (const streets_vehicle_scheduler::signalized_intersection_schedule & ev_schedules_within_so, const std::shared_ptr< OpenAPI::OAIIntersection_info > & intersection_info_ptr, const uint64_t & tbd_start) const private
Given a populated signalized_intersection_schedule object, intersection_info shared pointer, and the start time of TBD area, This method returns a MAP of entry lanes as keys and a list of vehicle schedules for each entry lane as value. Only those vehicles that have an entering time (ET) after the start of the TBD area will be included in this mapping.
Parameters
ev_schedules_within_so A populated signalized_intersection_schedule object.
intersection_info_ptr An intersection_info pointer.
tbd_start Start time of the TBD area.
Returns
unordered_map<int, vector<streets_vehicle_scheduler::signalized_vehicle_schedule>> entry lane to list of signalized_vehicle_schedule mapping, where the list of signalized_vehicle_schedule includes the schedules that have ETs after the start time of the TBD area.
Definition at line 326 of file streets_desired_phase_plan_generator.cpp.
{
        std::unordered_map<int, std::list<streets_vehicle_scheduler::signalized_vehicle_schedule>> schedules_per_lane;
        for ( const auto &entry_lane_obj : intersection_info_ptr->getEntryLanelets() ) {
            std::list<streets_vehicle_scheduler::signalized_vehicle_schedule> schedules_in_lane;
            for ( const auto &ev_sched : ev_schedules_within_so.vehicle_schedules ) {
                if (ev_sched.state == streets_vehicles::vehicle_state::EV && ev_sched.entry_lane == entry_lane_obj.getId() && ev_sched.et >= tbd_start) {
                    SPDLOG_DEBUG("Adding schedule for vehicle {0} to EV schedule list in entry lane {1}", ev_sched.v_id, ev_sched.entry_lane);
                    schedules_in_lane.push_back(ev_sched);
                }
            }
            if ( !schedules_in_lane.empty()) {
                schedules_in_lane.sort(streets_vehicle_scheduler::et_comparator);
                schedules_per_lane.try_emplace( entry_lane_obj.getId(), schedules_in_lane );
            }
            else {
                SPDLOG_DEBUG("No EVs in lane {0}.", static_cast<int>(entry_lane_obj.getId()) );
            }
        }
        return schedules_per_lane;
    }
References streets_vehicle_scheduler::et_comparator(), streets_vehicles::EV, and streets_vehicle_scheduler::signalized_intersection_schedule::vehicle_schedules.
Referenced by generate_desire_phase_plan_list().
get_signal_group_entry_lane_mapping()
std::unordered_map< uint8_t, std::vector< int > > streets_signal_optimization::streets_desired_phase_plan_generator::get_signal_group_entry_lane_mapping () const
Get the entry lane to signal group mapping.
Returns
std::unordered_map<uint8_t, std::vector<int>> entry lane to signal group mapping.
Definition at line 638 of file streets_desired_phase_plan_generator.cpp.
{
        return signal_group_entry_lane_mapping;
    }
References signal_group_entry_lane_mapping.
get_so_radius()
double streets_signal_optimization::streets_desired_phase_plan_generator::get_so_radius () const
Get the so area radius (meter).
Returns
double so radius in meters.
Definition at line 610 of file streets_desired_phase_plan_generator.cpp.
{
        return config.so_radius;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::so_radius.
set_configuration()
void streets_signal_optimization::streets_desired_phase_plan_generator::set_configuration (const uint64_t _initial_green_buffer, const uint64_t _final_green_buffer, const uint64_t _et_inaccuracy_buffer, const uint64_t _queue_max_time_headway, const double _so_radius, const uint64_t _min_green, const uint64_t _max_green, const uint8_t _desired_future_move_group_count)
Set the configurable parameters to the desired values.
Parameters
_initial_green_buffer initial green buffer in milliseconds.
_final_green_buffer final green buffer in milliseconds.
_et_inaccuracy_buffer ET inaccuracy buffer in milliseconds.
_queue_max_time_headway queue max time headway in milliseconds.
_so_radius so radius in meters.
_min_green maximum green in milliseconds.
_max_green minimum green in milliseconds.
_desired_future_move_group_count desired number of future movement group.
Definition at line 547 of file streets_desired_phase_plan_generator.cpp.
{
        config.initial_green_buffer = _initial_green_buffer;
        config.final_green_buffer = _final_green_buffer;
        config.et_inaccuracy_buffer = _et_inaccuracy_buffer;
        config.queue_max_time_headway = _queue_max_time_headway;
        config.so_radius = _so_radius;
        config.min_green = _min_green;
        config.max_green = _max_green;
        config.desired_future_move_group_count = _desired_future_move_group_count;
        is_configured = true;
        SPDLOG_DEBUG("Configuration parameter - initial_green_buffer: {0}", config.initial_green_buffer);
        SPDLOG_DEBUG("Configuration parameter - final_green_buffer: {0}", config.final_green_buffer);
        SPDLOG_DEBUG("Configuration parameter - et_inaccuracy_buffer: {0}", config.et_inaccuracy_buffer);
        SPDLOG_DEBUG("Configuration parameter - queue_max_time_headway: {0}", config.queue_max_time_headway);
        SPDLOG_DEBUG("Configuration parameter - so_radius: {0}", config.so_radius);
        SPDLOG_DEBUG("Configuration parameter - min_green: {0}", config.min_green);
        SPDLOG_DEBUG("Configuration parameter - max_green: {0}", config.max_green);
        SPDLOG_DEBUG("Configuration parameter - desired_future_move_group_count: {0}", config.desired_future_move_group_count);
    }
References config, streets_signal_optimization::streets_desired_phase_plan_generator_configuration::desired_future_move_group_count, streets_signal_optimization::streets_desired_phase_plan_generator_configuration::et_inaccuracy_buffer, streets_signal_optimization::streets_desired_phase_plan_generator_configuration::final_green_buffer, streets_signal_optimization::streets_desired_phase_plan_generator_configuration::initial_green_buffer, is_configured, streets_signal_optimization::streets_desired_phase_plan_generator_configuration::max_green, streets_signal_optimization::streets_desired_phase_plan_generator_configuration::min_green, streets_signal_optimization::streets_desired_phase_plan_generator_configuration::queue_max_time_headway, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::so_radius.
Referenced by generate_desire_phase_plan_list().
set_desired_future_move_group_count()
void streets_signal_optimization::streets_desired_phase_plan_generator::set_desired_future_move_group_count (const uint8_t count)
Set the desired number of future movement groups.
Parameters
count desired number of future movement group.
Definition at line 630 of file streets_desired_phase_plan_generator.cpp.
{
        config.desired_future_move_group_count = count;
    }
References config, simulate_bsm::count, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::desired_future_move_group_count.
set_et_inaccuracy_buffer()
void streets_signal_optimization::streets_desired_phase_plan_generator::set_et_inaccuracy_buffer (const uint64_t buffer)
Set the entering time (ET) inaccuracy_buffer (ms). This value is defined to account for entering time (ET) estimation inaccuracy. To find the required green duration for dissipating a queue from an entry lane, the end of the green is set to the estimated ET of the last vehicle in the queue plus this configurable parameter plus final_green_buffer.
Parameters
buffer ET inaccuracy buffer in milliseconds.
Definition at line 590 of file streets_desired_phase_plan_generator.cpp.
{
        config.et_inaccuracy_buffer = buffer;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::et_inaccuracy_buffer.
set_final_green_buffer()
void streets_signal_optimization::streets_desired_phase_plan_generator::set_final_green_buffer (const uint64_t buffer)
Set the final green buffer (ms). This value is used to account for safety. The assumption is that no vehicle shall enter the intersection box after the end of a green phase minus the final green buffer.
Parameters
buffer final green buffer in milliseconds.
Definition at line 582 of file streets_desired_phase_plan_generator.cpp.
{
        config.final_green_buffer = buffer;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::final_green_buffer.
set_initial_green_buffer()
void streets_signal_optimization::streets_desired_phase_plan_generator::set_initial_green_buffer (const uint64_t buffer)
Set the initial green buffer (ms). This value is used to account for the time it takes a vehicle before entering the intersection box at a green phase.
Parameters
buffer initial green buffer in milliseconds.
Definition at line 574 of file streets_desired_phase_plan_generator.cpp.
{
        config.initial_green_buffer = buffer;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::initial_green_buffer.
set_max_green()
void streets_signal_optimization::streets_desired_phase_plan_generator::set_max_green (const uint64_t _max_green)
Set the configurable maximum green (ms).
Parameters
_max_green maximum green in milliseconds.
Definition at line 622 of file streets_desired_phase_plan_generator.cpp.
{
        config.max_green = _max_green;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::max_green.
set_min_green()
void streets_signal_optimization::streets_desired_phase_plan_generator::set_min_green (const uint64_t _min_green)
Set the configurable minimum green (ms).
Parameters
_min_green minimum green in milliseconds.
Definition at line 614 of file streets_desired_phase_plan_generator.cpp.
{
        config.min_green = _min_green;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::min_green.
set_queue_max_time_headway()
void streets_signal_optimization::streets_desired_phase_plan_generator::set_queue_max_time_headway (const uint64_t buffer)
Set the queue max time headway (ms). This value defines the maximum allowed time headway between the estimated entering times (ETs) of two consecutive vehicles within a queue.
Parameters
buffer queue max time headway in milliseconds.
Definition at line 598 of file streets_desired_phase_plan_generator.cpp.
{
        config.queue_max_time_headway = buffer;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::queue_max_time_headway.
set_so_radius()
void streets_signal_optimization::streets_desired_phase_plan_generator::set_so_radius (const double radius)
Set the so area radius (meter). The signal optimization service only considers vehicles that are within the signal optimization area.
Parameters
radius so radius in meters.
Definition at line 606 of file streets_desired_phase_plan_generator.cpp.
{
        config.so_radius = radius;
    }
References config, and streets_signal_optimization::streets_desired_phase_plan_generator_configuration::so_radius.
update_desired_phase_plan_list()
void streets_signal_optimization::streets_desired_phase_plan_generator::update_desired_phase_plan_list (const std::shared_ptr< streets_signal_optimization::movement_groups > & move_groups, const std::unordered_map< int, uint64_t > & green_end_per_entry_lane, const streets_desired_phase_plan::streets_desired_phase_plan & base_desired_phase_plan, std::vector< streets_desired_phase_plan::streets_desired_phase_plan > & desired_phase_plan_list, const std::shared_ptr< OpenAPI::OAIIntersection_info > & intersection_info_ptr, const uint64_t & tbd_start) private
Given a list of movement groups, a mapping of the end time of required green duration for clearing the queue to entry lane id, and an updated base_desired_phase_plan, this method with create a list of desired phase plans, where each desired phase plan in the list includes the existing fixed future movement groups from the received spat and a new movement group with a given duration at the end. For each movement group, this method first checks if the movement group can be added to the base_desired_phase_plan (i.e., if the movement group has a common signal group with the last movement group in the base_desired_phase_plan). If the movement group can be added, for each entry lane allowed by the subject movement group, this method will add a new desired phase plan to the list, where the last movement group is the subject movement group and the end time of the green is the end time of required green duration for clearing the queue of the subject entry lane.
Parameters
move_groups Shared pointer to a list of possible movement groups.
green_end_per_entry_lane End time of required green duration for clearing the queue to entry lane id mapping.
base_desired_phase_plan The desired_phase_plan converted from the provided intersection_state.
desired_phase_plan_list An empty desired phase plan list to be populated by this method.
intersection_info_ptr An intersection_info pointer.
tbd_start Start time of the TBD area.
Exceptions
If the base_desired_phase_plan is empty.
If the base_desired_phase_plan, it means that either the base_desired_phase_plan is not created based on the spat, or the spat does not have any fixed movement group (even the current active phase timing) in it.
If the signal_group_entry_lane_mapping is empty, call create_signal_group_entry_lane_mapping() function to find the mapping. This mapping maps signal group ids and entry lane ids.
Loop through all candidate movement groups, check if it can be added to the base_desired_phase_plan, and if yes, add it to the base_desired_phase_plan with all different possible green duration options.
Check if the movement group can be added to the end of the base desired phase plan
Loop through the entry lanes connected to the first signal group. For each entry lane, add the movement group to the end of the base desired phase plan with the required green duration calculated for this entry lane.
If the movement group contains 2 signal groups, loop through the entry lanes connected to the second signal group. For each entry lane, add the movement group to the end of the base desired phase plan with the required green duration calculated for this entry lane.
Definition at line 415 of file streets_desired_phase_plan_generator.cpp.
{
        if (base_desired_phase_plan.desired_phase_plan.empty()) {
            throw streets_desired_phase_plan_generator_exception("The base desired phase plan is empty!");
        }
        if (signal_group_entry_lane_mapping.empty()) {
            SPDLOG_DEBUG("The signal_group_entry_lane_mapping is empty!");
            create_signal_group_entry_lane_mapping(intersection_info_ptr);
        }
        for (const auto &move_group : move_groups->groups) {
            bool can_mg_be_added = true;
            for (const auto &signal_group : base_desired_phase_plan.desired_phase_plan.back().signal_groups) {
                if ( signal_group == move_group.signal_groups.first || (move_group.signal_groups.second != 0 && signal_group == move_group.signal_groups.second) ) {
                    can_mg_be_added = false;
                    break;
                }
            }
            if (can_mg_be_added) {
                for (const auto &entry_lane : signal_group_entry_lane_mapping.at(move_group.signal_groups.first)) {
                    if (green_end_per_entry_lane.find(entry_lane) != green_end_per_entry_lane.end()) {
                        desired_phase_plan_list.push_back(base_desired_phase_plan);
                        streets_desired_phase_plan::signal_group2green_phase_timing mg_timing;
                        mg_timing.start_time = tbd_start;
                        mg_timing.end_time = green_end_per_entry_lane.at(entry_lane);
                        mg_timing.signal_groups.push_back(move_group.signal_groups.first);
                        if (move_group.signal_groups.second != 0) {
                            mg_timing.signal_groups.push_back(move_group.signal_groups.second);
                        }
                        desired_phase_plan_list.back().desired_phase_plan.push_back(mg_timing);
                    }
                }
                if (move_group.signal_groups.second != 0) {
                    for (const auto &entry_lane : signal_group_entry_lane_mapping.at(move_group.signal_groups.second)) {
                        if (green_end_per_entry_lane.find(entry_lane) != green_end_per_entry_lane.end()) {
                            desired_phase_plan_list.push_back(base_desired_phase_plan);
                            streets_desired_phase_plan::signal_group2green_phase_timing mg_timing;
                            mg_timing.start_time = tbd_start;
                            mg_timing.end_time = green_end_per_entry_lane.at(entry_lane);
                            mg_timing.signal_groups.push_back(move_group.signal_groups.first);
                            mg_timing.signal_groups.push_back(move_group.signal_groups.second);
                            desired_phase_plan_list.back().desired_phase_plan.push_back(mg_timing);
                        }
                    }
                }
            }
            else {
                SPDLOG_DEBUG("movement group {0} cannot be added to base_desired_phase_plan since this movement group includes a common signal group with the last fixed movement group in the modified spat!", move_group.name);
            }
        }
    }
References create_signal_group_entry_lane_mapping(), streets_desired_phase_plan::streets_desired_phase_plan::desired_phase_plan, streets_desired_phase_plan::signal_group2green_phase_timing::end_time, signal_group_entry_lane_mapping, streets_desired_phase_plan::signal_group2green_phase_timing::signal_groups, and streets_desired_phase_plan::signal_group2green_phase_timing::start_time.
Referenced by generate_desire_phase_plan_list().
verify_movement_group_list()
void streets_signal_optimization::streets_desired_phase_plan_generator::verify_movement_group_list (const std::shared_ptr< OpenAPI::OAIIntersection_info > & intersection_info_ptr, const std::shared_ptr< streets_signal_optimization::movement_groups > & move_groups) const private
Given an intersection_info pointer and a list of possible movement groups, this method checks if all signal groups included in the movement groups list are included in the intersection_info pointer. Basically, a signal group cannot be used if it is not connected to a given link lanelet (i.e., it does not exist in the intersection_info pointer). This method will throw exception if this requirement is not satisfied.
Parameters
intersection_info_ptr An intersection_info pointer.
move_groups Shared pointer to a list of possible movement groups.
Exceptions
If a signal group included in the movement group list does not exist in the intersection_info pointer.
Definition at line 131 of file streets_desired_phase_plan_generator.cpp.
    {
        std::vector<int> signal_group_list;
        for (const auto &lane : intersection_info_ptr->getLinkLanelets()) {
            if ( std::find(signal_group_list.begin(), signal_group_list.end(), lane.getSignalGroupId()) == signal_group_list.end() ) {
                signal_group_list.push_back(lane.getSignalGroupId());
            }
        }
        for (const auto &mg : move_groups->groups) {
            if (std::find(signal_group_list.begin(), signal_group_list.end(), mg.signal_groups.first) == signal_group_list.end()) {
                throw streets_desired_phase_plan_generator_exception("Signal group " + std::to_string(mg.signal_groups.first) +
                                                        " does not exist in intersection_info pointer!");
            }
            if (mg.signal_groups.second != 0 &&
                    std::find(signal_group_list.begin(), signal_group_list.end(), mg.signal_groups.second) == signal_group_list.end()) {
                throw streets_desired_phase_plan_generator_exception("Signal group " + std::to_string(mg.signal_groups.second) +
                                                        " does not exist in intersection_info pointer!");
            }
        }
    }
References to_string().
Referenced by generate_desire_phase_plan_list().
Member Data Documentation
config
streets_desired_phase_plan_generator_configuration streets_signal_optimization::streets_desired_phase_plan_generator::config private
A struct containing the configurable parameters for desired_phsae_plan_generator functions.
Definition at line 35 of file streets_desired_phase_plan_generator.h.
Referenced by configure_scheduler(), generate_desire_phase_plan_list(), get_desired_future_move_group_count(), get_et_inaccuracy_buffer(), get_ev_schedules_within_so(), get_final_green_buffer(), get_green_end_per_entry_lane(), get_initial_green_buffer(), get_last_vehicle_in_queue(), get_max_green(), get_min_green(), get_queue_max_time_headway(), get_so_radius(), set_configuration(), set_desired_future_move_group_count(), set_et_inaccuracy_buffer(), set_final_green_buffer(), set_initial_green_buffer(), set_max_green(), set_min_green(), set_queue_max_time_headway(), and set_so_radius().
is_configured
bool streets_signal_optimization::streets_desired_phase_plan_generator::is_configured = false private
The bool parameter defining whether the configurable parameter are set to their desired values or not.
Definition at line 40 of file streets_desired_phase_plan_generator.h.
Referenced by generate_desire_phase_plan_list(), and set_configuration().
scheduler_ptr
std::shared_ptr<streets_vehicle_scheduler::signalized_vehicle_scheduler> streets_signal_optimization::streets_desired_phase_plan_generator::scheduler_ptr private
A shared pointer to the signalized vehicle scheduler.
Definition at line 30 of file streets_desired_phase_plan_generator.h.
Referenced by configure_scheduler(), generate_desire_phase_plan_list(), and get_schedule_plan().
signal_group_entry_lane_mapping
std::unordered_map<uint8_t, std::vector<int> > streets_signal_optimization::streets_desired_phase_plan_generator::signal_group_entry_lane_mapping private
Map of signal group to vector of entry lanes that are served by this signal group.. Each signal group might be assigned to more than one entry lanes.
Definition at line 46 of file streets_desired_phase_plan_generator.h.
Referenced by create_signal_group_entry_lane_mapping(), get_signal_group_entry_lane_mapping(), and update_desired_phase_plan_list().
The documentation for this class was generated from the following files:
streets_utils/streets_signal_optimization/include/streets_desired_phase_plan_generator.h
streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_generator.cpp