Carma-streets: traffic_signal_controller_service::snmp_client Class Reference
traffic_signal_controller_service::snmp_client Class Reference
#include <snmp_client.h>
Public Member Functions
snmp_client (const std::string &ip, const int &port, const std::string &community="public", int snmp_version=0, int timeout=100)
Constructor for Traffic Signal Controller Service client. Uses the arguments provided to establish an snmp connection.
snmp_client ()=delete
virtual bool process_snmp_request (const std::string &input_oid, const streets_snmp_cmd::REQUEST_TYPE &request_type, streets_snmp_cmd::snmp_response_obj &val)
Returns true or false depending on whether the request could be processed for given input OID at the Traffic Signal Controller.
void log_error (const int &status, const streets_snmp_cmd::REQUEST_TYPE &request_type, snmp_pdu *response) const
Finds error type from status and logs an error.
virtual ~snmp_client ()
Destructor for client. Closes the snmp session.
Private Attributes
snmp_session session
snmp_session * ss
snmp_pdu * pdu
oid OID [MAX_OID_LEN]
size_t OID_len = MAX_OID_LEN
std::string ip_ = ""
int port_ = 0
std::string community_ = "public"
int snmp_version_ = 0
Detailed Description
Definition at line 19 of file snmp_client.h.
Constructor & Destructor Documentation
snmp_client() [1/2]
traffic_signal_controller_service::snmp_client::snmp_client (const std::string & ip, const int & port, const std::string & community = "public", int snmp_version = 0, int timeout = 100)
Constructor for Traffic Signal Controller Service client. Uses the arguments provided to establish an snmp connection.
Parameters
ip The ip ,as a string, for the tsc_client_service to establish an snmp communication with.
port Target port as integer on the host for snmp communication.
community The community id as a string. Defaults to "public" if unassigned.
snmp_version The snmp_version as defined in net-snmp.Default to 0 if unassigned. net-snmp version definition: SNMP_VERSION_1:0 SNMP_VERSION_2c:1 SNMP_VERSION_2u:2 SNMP_VERSION_3:3"
timeout The time in microseconds after which an snmp session request expires. Defaults to 100 if unassigned
Definition at line 6 of file snmp_client.cpp.
        : ip_(ip), port_(port), community_(community),snmp_version_(snmp_version)
    {
        SPDLOG_DEBUG("Starting SNMP Client");
        SPDLOG_DEBUG("Target device IP address: {0}", ip_);
        SPDLOG_DEBUG("Target device NTCIP port: {0}", port_);
        // Bring the IP address and port of the target SNMP device in the required form, which is "IPADDRESS:PORT":
        std::string ip_port_string = ip_ + ":" + std::to_string(port_);
        char* ip_port = &ip_port_string[0];
        init_snmp("carma_snmp");
        snmp_sess_init(&session);
        session.peername = ip_port;
        session.version = snmp_version_;
        // Establish the session parameters.
        char community_char[community_.length()];
        std::copy(community_.begin(), community_.end(), community_char);
        unsigned char* comm = reinterpret_cast<unsigned char*>(community_char);
        session.community = comm;
        session.community_len = community_.length();
        // Timeout is in microseconds
        session.timeout = timeout;
        session.retries = 0;
        ss = snmp_open(&session);
        if (ss == nullptr)
        {
            SPDLOG_ERROR("Failed to establish session with target device");
            snmp_sess_perror("snmpget", &session);
            throw snmp_client_exception("Failed to establish session with target device");
        }
        else
        {
            SPDLOG_INFO("Established session with device at {0}", ip_);
        }
    }
References community_, ip_, port_, session, snmp_version_, and to_string().
snmp_client() [2/2]
traffic_signal_controller_service::snmp_client::snmp_client () delete
~snmp_client()
traffic_signal_controller_service::snmp_client::~snmp_client () virtual
Destructor for client. Closes the snmp session.
Definition at line 50 of file snmp_client.cpp.
{
        SPDLOG_WARN("Closing snmp session");
        snmp_close(ss);
    }
Member Function Documentation
log_error()
void traffic_signal_controller_service::snmp_client::log_error (const int & status, const streets_snmp_cmd::REQUEST_TYPE & request_type, snmp_pdu * response) const
Finds error type from status and logs an error.
Parameters
status The integer value corresponding to net-snmp defined errors. macros considered are STAT_SUCCESS(0) and STAT_TIMEOUT(2)
streets_snmp_cmd::REQUEST_TYPE The request type for which the error is being logged (GET/SET).
response The snmp_pdu struct
Definition at line 181 of file snmp_client.cpp.
    {
        if (status == STAT_SUCCESS)
        {
            SPDLOG_ERROR("Variable type: {0}",response->variables->type);
            SPDLOG_ERROR("Error in packet.{0} ", static_cast<std::string>(snmp_errstring(static_cast<int>(response->errstat))));
        }
        else if (status == STAT_TIMEOUT){
            SPDLOG_ERROR("Timeout, no response from server");
        }
        else{
            if(request_type == streets_snmp_cmd::REQUEST_TYPE::GET){
                SPDLOG_ERROR("Unknown SNMP Error for {0}", "GET");
            }
            else if(request_type == streets_snmp_cmd::REQUEST_TYPE::SET){
                SPDLOG_ERROR("Unknown SNMP Error for {0}", "SET");
            }
        }
    }
References streets_snmp_cmd::GET, and streets_snmp_cmd::SET.
Referenced by process_snmp_request().
process_snmp_request()
bool traffic_signal_controller_service::snmp_client::process_snmp_request (const std::string & input_oid, const streets_snmp_cmd::REQUEST_TYPE & request_type, streets_snmp_cmd::snmp_response_obj & val) virtual
Returns true or false depending on whether the request could be processed for given input OID at the Traffic Signal Controller.
Parameters
input_oid The OID to request information for.
streets_snmp_cmd::REQUEST_TYPE The request type for which the error is being logged. Accepted values are "GET" and "SET" only.
value_int The integer value for the object returned by reference. For "SET" it is the value to be set. For "GET", it is the value returned for the returned object by reference. This is an optional argument, if not provided, defaults to 0.
value_str String value for the object, returned by reference. Optional argument, if not provided the value is set as an empty string
Returns
Integer value at the oid, returns false if value cannot be set/requested or oid doesn't have an integer value to return.
Definition at line 56 of file snmp_client.cpp.
{
        /*Structure to hold response from the remote host*/
        snmp_pdu *response;
        // Create pdu for the data
        if (request_type == streets_snmp_cmd::REQUEST_TYPE::GET)
        {
            SPDLOG_DEBUG("Attemping to GET value for: {0}", input_oid);
            pdu = snmp_pdu_create(SNMP_MSG_GET);
        }
        else if (request_type == streets_snmp_cmd::REQUEST_TYPE::SET)
        {
            SPDLOG_DEBUG("Attemping to SET value for {0}", input_oid, " to {1}", val.val_int);
            pdu = snmp_pdu_create(SNMP_MSG_SET);
        }
        else{
            SPDLOG_ERROR("Invalid request type, method accepts only GET and SET");
        }
        // Read input OID into an OID variable:
        // net-snmp has several methods for creating an OID object
        // their documentation suggests using get_node. read_objid seems like a simpler approach
        // TO DO: investigate update to get_node
        if(!read_objid(input_oid.c_str(), OID, &OID_len)){
            // If oid cannot be created
            SPDLOG_ERROR("OID could not be created from input: {0}", input_oid);
            return false;
        }
        else{
            if(request_type == streets_snmp_cmd::REQUEST_TYPE::GET)
            {
                // Add OID to pdu for get request
                snmp_add_null_var(pdu, OID, OID_len);
            }
            else if(request_type == streets_snmp_cmd::REQUEST_TYPE::SET)
            {
                if(val.type == streets_snmp_cmd::RESPONSE_TYPE::INTEGER){
                    snmp_add_var(pdu, OID, OID_len, 'i', (std::to_string(val.val_int)).c_str());
                }
                else if(val.type == streets_snmp_cmd::RESPONSE_TYPE::STRING){
                    SPDLOG_ERROR("Setting string value is currently not supported");
                    return false;
                }
            }
            SPDLOG_DEBUG("Created OID for input: {0}", input_oid);
        }
        // Send the request
        int status = snmp_synch_response(ss, pdu, &response);
        // Check response
        if(status == STAT_SUCCESS && response->errstat == SNMP_ERR_NOERROR) {
            SPDLOG_DEBUG("STAT_SUCCESS, received a response");
            if(request_type == streets_snmp_cmd::REQUEST_TYPE::GET){
                for(auto vars = response->variables; vars; vars = vars->next_variable){
                    // Get value of variable depending on ASN.1 type
                    // Variable could be a integer, string, bitstring, ojbid, counter : defined here https://github.com/net-snmp/net-snmp/blob/master/include/net-snmp/types.h
                    // get Integer value
                    if(vars->type == ASN_INTEGER){
                        if(vars->val.integer){
                            val.val_int = *vars->val.integer;
                            SPDLOG_DEBUG("Integer value in object: {0}", val.val_int);
                        }
                        else{
                            SPDLOG_ERROR("Response specifies type integer, but no integer value found");
                            return false;
                        }
                    }
                    else if(vars->type == ASN_OCTET_STR){
                        if(vars->val.string){
                            size_t str_len = vars->val_len;
                            for(size_t i = 0; i < str_len; ++i)
{
                                val.val_string.push_back(vars->val.string[i]);
                            }
                        }
                        else{
                            SPDLOG_ERROR("Response specifies type string, but no string value found");
                            return false;
                        }
                    }
                    else{
                        SPDLOG_ERROR("Received a message type which isn't an integer or string");
                        return false;
                    }
                }
            }
            else if(request_type == streets_snmp_cmd::REQUEST_TYPE::SET){
                if(val.type == streets_snmp_cmd::RESPONSE_TYPE::INTEGER){
                    SPDLOG_DEBUG("Success in SET for OID: {0} Value: {1}", input_oid ,val.val_int);
                }
                else if(val.type == streets_snmp_cmd::RESPONSE_TYPE::STRING){
                    SPDLOG_DEBUG("Success in SET for OID: {0} Value:", input_oid);
                    for(auto data : val.val_string){
                        SPDLOG_DEBUG("{0}", data);
                    }
                }
            }
        }
        else
        {
            log_error(status, request_type, response);
            return false;
        }
        if (response){
            snmp_free_pdu(response);
            OID_len = MAX_OID_LEN;
        }
        return true;
    }
References simulate_bsm::data, streets_snmp_cmd::GET, simulate_bsm::i, streets_snmp_cmd::INTEGER, log_error(), OID, OID_len, pdu, streets_snmp_cmd::SET, streets_snmp_cmd::STRING, to_string(), streets_snmp_cmd::snmp_response_obj::type, streets_snmp_cmd::snmp_response_obj::val_int, and streets_snmp_cmd::snmp_response_obj::val_string.
Member Data Documentation
community_
std::string traffic_signal_controller_service::snmp_client::community_ = "public" private
Definition at line 44 of file snmp_client.h.
Referenced by snmp_client().
ip_
std::string traffic_signal_controller_service::snmp_client::ip_ = "" private
Definition at line 40 of file snmp_client.h.
Referenced by snmp_client().
OID
oid traffic_signal_controller_service::snmp_client::OID[MAX_OID_LEN] private
Definition at line 35 of file snmp_client.h.
Referenced by process_snmp_request().
OID_len
size_t traffic_signal_controller_service::snmp_client::OID_len = MAX_OID_LEN private
Definition at line 36 of file snmp_client.h.
Referenced by process_snmp_request().
pdu
snmp_pdu* traffic_signal_controller_service::snmp_client::pdu private
Definition at line 31 of file snmp_client.h.
Referenced by process_snmp_request().
port_
int traffic_signal_controller_service::snmp_client::port_ = 0 private
Definition at line 42 of file snmp_client.h.
Referenced by snmp_client().
session
snmp_session traffic_signal_controller_service::snmp_client::session private
Definition at line 27 of file snmp_client.h.
Referenced by snmp_client().
snmp_version_
int traffic_signal_controller_service::snmp_client::snmp_version_ = 0 private
Definition at line 47 of file snmp_client.h.
Referenced by snmp_client().
ss
snmp_session* traffic_signal_controller_service::snmp_client::ss private
Definition at line 28 of file snmp_client.h.
The documentation for this class was generated from the following files:
tsc_client_service/include/snmp_client.h
tsc_client_service/src/snmp_client.cpp