Carma-streets: streets_service::streets_clock_singleton Class Reference
streets_service::streets_clock_singleton Class Reference
Streets Clock Singleton is a singleton that manages a CarmaClock object. The CarmaClock object is created by the CARMA Time Library (https://github.com/usdot-fhwa-stol/carma-time-lib) and is a wrapper object that allows for time based operation using chronos system time calls or an external source for time. Its constructor takes a boolean parameter, what when set to true relies on update calls to save and store the current time. When passed false, the CarmaClock object functions exactly as chrono system time calls including now() and sleep() calls, using the system time.
#include <streets_clock_singleton.h>
Static Public Member Functions
static void update (uint64_t time)
Static access to the CarmaClock update method (see https://github.com/usdot-fhwa-stol/carma-time-lib). Updates the current time held by the CarmaClock to the value of the time parameter (in milliseconds).
static uint64_t time_in_ms ()
Static access to the CarmaClock timeInMilliseconds method (see https://github.com/usdot-fhwa-stol/carma-time-lib). Returns the epoch time in milliseconds.
static void sleep_for (uint64_t ms)
Sleep/block calling thread for provided duration in milliseconds. TODO: Add this functionality to the underlying CarmaClock object.
static void sleep_until (uint64_t ms)
Sleep/block calling thread until provided time in milliseconds.
Static Public Member Functions inherited from streets_service::streets_singleton< fwha_stol::lib::time::CarmaClock, bool >
static fwha_stol::lib::time::CarmaClock & get_singleton ()
static fwha_stol::lib::time::CarmaClock & create (Args...args)
Method to intialize streets_singleton with constructor params ...Args of templated class.
Static Protected Member Functions
static T & get_singleton ()
Friends
class streets_singleton< fwha_stol::lib::time::CarmaClock, bool >
Additional Inherited Members
Public Member Functions inherited from streets_service::streets_singleton< fwha_stol::lib::time::CarmaClock, bool >
streets_singleton (const streets_singleton &)=delete
streets_singleton (streets_singleton &&)=delete
streets_singleton & operator= (const streets_singleton &)=delete
streets_singleton & operator= (const streets_singleton &&)=delete
Protected Member Functions inherited from streets_service::streets_singleton< fwha_stol::lib::time::CarmaClock, bool >
streets_singleton ()=default
~streets_singleton ()=default
Static Protected Attributes inherited from streets_service::streets_singleton< fwha_stol::lib::time::CarmaClock, bool >
static std::unique_ptr< fwha_stol::lib::time::CarmaClock > instance
Detailed Description
Streets Clock Singleton is a singleton that manages a CarmaClock object. The CarmaClock object is created by the CARMA Time Library (https://github.com/usdot-fhwa-stol/carma-time-lib) and is a wrapper object that allows for time based operation using chronos system time calls or an external source for time. Its constructor takes a boolean parameter, what when set to true relies on update calls to save and store the current time. When passed false, the CarmaClock object functions exactly as chrono system time calls including now() and sleep() calls, using the system time.
NOTE Before attempting to statically access any functionality in this class, call streets_clock_singleton::create(bool simulation_mode) to initialize the clock singleton in simulation mode or real time mode.
Author
Paul Bourelly
Definition at line 21 of file streets_clock_singleton.h.
Member Function Documentation
get_singleton()
static T & streets_service::streets_singleton< T, Args >::get_singleton () static protected
Method for static singleton instance retrieval
Returns
T singleton instance
Referenced by sleep_for(), sleep_until(), time_in_ms(), and update().
sleep_for()
void streets_service::streets_clock_singleton::sleep_for (uint64_t ms) static
Sleep/block calling thread for provided duration in milliseconds. TODO: Add this functionality to the underlying CarmaClock object.
Parameters
ms time in milliseconds to sleep for.
Definition at line 19 of file streets_clock_singleton.cpp.
{
        auto &inst = get_singleton();
        inst.wait_for_initialization();
        auto cur_time = inst.nowInMilliseconds();
        inst.sleep_until(cur_time + ms);
    }
References get_singleton().
Referenced by sensor_data_sharing_service::sds_service::consume_detections(), traffic_signal_controller_service::tsc_service::control_tsc_phases(), sensor_data_sharing_service::sds_service::produce_sdsms(), traffic_signal_controller_service::tsc_service::produce_tsc_config_json(), and traffic_signal_controller_service::tsc_service::set_tsc_hold_and_omit_forceoff_call().
sleep_until()
void streets_service::streets_clock_singleton::sleep_until (uint64_t ms) static
Sleep/block calling thread until provided time in milliseconds.
Parameters
ms time in milliseconds to sleep until.
Definition at line 26 of file streets_clock_singleton.cpp.
{
        auto &inst = get_singleton();
        inst.wait_for_initialization();
        inst.sleep_until(ms);
    }
References get_singleton().
time_in_ms()
uint64_t streets_service::streets_clock_singleton::time_in_ms () static
Static access to the CarmaClock timeInMilliseconds method (see https://github.com/usdot-fhwa-stol/carma-time-lib). Returns the epoch time in milliseconds.
Returns
In simulation mode this returns the value from the last update call. If update has not been called yet this method will block until the first call to update and then return that value. When not in simulation mode return system epoch time in milliseconds.
Definition at line 11 of file streets_clock_singleton.cpp.
{
        auto &inst = get_singleton();
        SPDLOG_TRACE("Calling thread is waiting on streets clock initialization.");
        inst.wait_for_initialization();
        SPDLOG_TRACE("Thread is released after initialization.");
        return inst.nowInMilliseconds();
    }
References get_singleton().
Referenced by sensor_data_sharing_service::sds_service::consume_detections(), traffic_signal_controller_service::tsc_service::control_tsc_phases(), signal_phase_and_timing::time_change_details::convert_hour_tenth_secs2epoch_ts(), signal_phase_and_timing::intersection_state::convert_min_mills2epoch_ts(), signal_phase_and_timing::time_change_details::convert_msepoch_to_hour_tenth_secs(), signal_phase_and_timing::intersection_state::convert_offset(), sensor_data_sharing_service::sds_service::create_sdsm(), traffic_signal_controller_service::monitor_desired_phase_plan::fix_upcoming_green(), traffic_signal_controller_service::monitor_desired_phase_plan::fix_upcoming_yell_red(), traffic_signal_controller_service::tsc_service::log_spat_latency(), traffic_signal_controller_service::tsc_service::produce_spat_json(), traffic_signal_controller_service::monitor_desired_phase_plan::prune_expired_greens_from_dpp(), signal_phase_and_timing::intersection_state::set_timestamp_local(), signal_phase_and_timing::intersection_state::set_timestamp_ntcip(), traffic_signal_controller_service::tsc_service::set_tsc_hold_and_omit_forceoff_call(), and traffic_signal_controller_service::control_tsc_state::update_tsc_control_queue().
update()
void streets_service::streets_clock_singleton::update (uint64_t time) static
Static access to the CarmaClock update method (see https://github.com/usdot-fhwa-stol/carma-time-lib). Updates the current time held by the CarmaClock to the value of the time parameter (in milliseconds).
Exceptions
std::invalid_arguement if called with CarmaClock not in simulation mode
Parameters
time time to update to in milliseconds.
Definition at line 5 of file streets_clock_singleton.cpp.
{
        auto &inst = get_singleton();
        inst.update(timestep);
        SPDLOG_TRACE("streets clock is updated to {0}", timestep);
    }
References get_singleton().
Referenced by streets_service::streets_service::consume_time_sync_message().
Friends And Related Function Documentation
streets_singleton< fwha_stol::lib::time::CarmaClock, bool >
friend class streets_singleton< fwha_stol::lib::time::CarmaClock, bool > friend
Definition at line 1 of file streets_clock_singleton.h.
The documentation for this class was generated from the following files:
streets_utils/streets_service_base/include/streets_clock_singleton.h
streets_utils/streets_service_base/src/streets_clock_singleton.cpp