Carma-streets: kafka_clients::kafka_client Class Reference
kafka_clients::kafka_client Class Reference
#include <kafka_client.h>
Public Member Functions
std::shared_ptr< kafka_clients::kafka_consumer_worker > create_consumer (const std::string &broker_str, const std::string &topic_str, std::string &group_id_str) const
std::shared_ptr< kafka_clients::kafka_producer_worker > create_producer (const std::string &broker_str, const std::string &topic_str) const
rapidjson::Document read_json_file (const std::string &json_file) const
std::string get_value_by_doc (rapidjson::Document &doc, const char *key) const
Detailed Description
Definition at line 15 of file kafka_client.h.
Member Function Documentation
create_consumer()
std::shared_ptr< kafka_clients::kafka_consumer_worker > kafka_clients::kafka_client::create_consumer (const std::string & broker_str, const std::string & topic_str, std::string & group_id_str) const
Definition at line 5 of file kafka_client.cpp.
    {
        try
        {
            int partition = 0;
            int64_t cur_offset = RdKafka::Topic::OFFSET_END;
            auto consumer_ptr = std::make_shared<kafka_clients::kafka_consumer_worker>(bootstrap_server, topic_str, group_id_str, cur_offset, partition);
            return consumer_ptr;
        }
        catch (...)
        {
            std::exception_ptr p = std::current_exception();
            SPDLOG_CRITICAL("Create consumer failure: {0}", (p ? p.__cxa_exception_type()->name() : "null"));
            exit(1);
        }
    }
Referenced by call_consumer_thread().
create_producer()
std::shared_ptr< kafka_clients::kafka_producer_worker > kafka_clients::kafka_client::create_producer (const std::string & broker_str, const std::string & topic_str) const
Definition at line 23 of file kafka_client.cpp.
    {
        try
        {
            int partition = 0;
            auto producer_ptr = std::make_shared<kafka_clients::kafka_producer_worker>(bootstrap_server, topic_str, partition);
            return producer_ptr;
        }
        catch (...)
        {
            std::exception_ptr p = std::current_exception();
            SPDLOG_CRITICAL("Create consumer failure: {0}", (p ? p.__cxa_exception_type()->name() : "null"));
            exit(1);
        }
    }
Referenced by call_producer_thread().
get_value_by_doc()
std::string kafka_clients::kafka_client::get_value_by_doc (rapidjson::Document & doc, const char * key) const
Referenced by call_consumer_thread(), and call_producer_thread().
read_json_file()
rapidjson::Document kafka_clients::kafka_client::read_json_file (const std::string & json_file) const
Referenced by call_consumer_thread(), and call_producer_thread().
The documentation for this class was generated from the following files:
kafka_clients/include/kafka_client.h
kafka_clients/src/kafka_client.cpp