Carma-streets: intersection_client Class Reference
intersection_client Class Reference
#include <intersection_client.h>
Public Member Functions
intersection_client ()
~intersection_client ()
void call ()
Detailed Description
Definition at line 6 of file intersection_client.h.
Constructor & Destructor Documentation
intersection_client()
intersection_client::intersection_client () inline
Definition at line 9 of file intersection_client.h.
{};
~intersection_client()
intersection_client::~intersection_client () inline
Definition at line 10 of file intersection_client.h.
{};
Member Function Documentation
call()
void intersection_client::call ()
Definition at line 6 of file intersection_client.cpp.
{
      OAIDefaultApi apiInstance;
      QEventLoop loop;
      connect(&apiInstance, &OAIDefaultApi::getIntersectionInfoSignal, [&](OAIIntersection_info int_info)
              {
                qDebug() << "Intersection name: " <<  int_info.getName();
                qDebug() << "Intersection id: "   << int_info.getId();
                QList<OpenAPI::OAILanelet_info> link_lanelets = int_info.getLinkLanelets();
                QList<OpenAPI::OAILanelet_info>::iterator begin = link_lanelets.begin();
                for(QList<OpenAPI::OAILanelet_info>::iterator itr = begin; itr != link_lanelets.end(); itr++ )
                {
                  qDebug() << "link lanelet ID: "   << itr->getId();
                  qDebug() << "Speed Limit: " << itr->getSpeedLimit();
                  qDebug() << "Conflict lanelets: ";
                  for(auto inner_itr = itr->getConflictLaneletIds().begin(); inner_itr != itr->getConflictLaneletIds().end(); inner_itr++ )
                  {
                        qDebug() <<  *inner_itr;
                  }
                }
                loop.quit(); });
      connect(&apiInstance, &OAIDefaultApi::getIntersectionInfoSignalE, [&](OAIIntersection_info, QNetworkReply::NetworkError, QString error_str)
              {
                qDebug() << "Error happened while issuing request : " << error_str;
                loop.quit(); });
      apiInstance.getIntersectionInfo();
      QTimer::singleShot(5000, &loop, &QEventLoop::quit);
      loop.exec();
}
References OpenAPI::OAIIntersection_info::getId(), OpenAPI::OAIDefaultApi::getIntersectionInfo(), OpenAPI::OAIIntersection_info::getLinkLanelets(), and OpenAPI::OAIIntersection_info::getName().
Referenced by main().
The documentation for this class was generated from the following files:
examples/qt_rest_clients_api/intersection_client/intersection_client.h
examples/qt_rest_clients_api/intersection_client/intersection_client.cpp