Carma-streets: signal_phase_and_timing::spat Class Reference
signal_phase_and_timing::spat Class Reference
#include <spat.h>
Public Member Functions
std::string toJson ()
Serialize SPaT object to rapidjson::Value for writing as JSON string (Thread Safe).
intersection_state get_intersection ()
Get copy of current intersection state. Note: SPaT object currently only supports storing single intersection state (Thread Safe).
std::string get_name ()
Get SPaT name.
uint32_t get_timestamp ()
Get timestamp in minute of the current UTC year (Thread Safe).
void set_intersection (const intersection_state &intersection)
Update current intersection state (Thread Safe).
void fromJson (const std::string &json)
Deserialize SPaT JSON into SPaT object (Thread Safe).
void update (ntcip::ntcip_1202_ext &ntcip_data, bool use_ntcip_timestamp)
Update spat object data using ntcip_1202_ext data received via UDP socket. Bool flag to control whether to use ntcip_1202_ext message provided timestamp or host unix timestamp information (Thread Safe).
void initialize_intersection (const std::string &intersection_name, const int intersection_id, const std::unordered_map< int, int > &phase_number_to_signal_group)
Method to initialize intersection information not provided in the ntcip SPaT UDP message but necessary for the J2735 SPaT message. This method must be executed prior to using the update method (Thread Safe).
void set_timestamp_ntcip (const uint32_t second_of_day, const uint16_t millisecond_of_second)
Method to set SPaT timestamp based on NTCIP message timestamp. The NTCIP message timestamp consists of a seconds_of_day and a milliseconds of second field. This method will get the current day from system time and then apply seconds and milliseconds informat as a offset for the current day.
void update_spat_with_candidate_dpp (const streets_desired_phase_plan::streets_desired_phase_plan &candidate_dpp, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_state)
Update spat movement_event list with desired phase plan information.
void process_first_desired_green (movement_state &cur_movement_state_ref, const streets_desired_phase_plan::signal_group2green_phase_timing &desired_sg_green_timing, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_state) const
Process first desired green signal group and duration in desired phase plan. Populate movement_event list of current movement_state with movement_events for first entry in desired phase plan.
void process_second_onward_desired_green (signal_phase_and_timing::movement_state &cur_movement_state_ref, const streets_desired_phase_plan::signal_group2green_phase_timing &desired_sg_green_timing, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_state) const
Process all desired green signal group and duration in desired phase plan that are not the first entry. Populate movement_event list of current movement_state with movement_events for all entries after first entry in desired phase plan.
void populate_movement_event (signal_phase_and_timing::movement_event &movement_event_to_populate, const signal_phase_and_timing::movement_phase_state &phase_state, const uint64_t start_time_epoch, const uint64_t end_time_epoch) const
Populate movement_event with movement_phase_state, start_time and end_time(min_end_time).
void append_full_green_yellow_red_phases_by_desired_green (signal_phase_and_timing::movement_state &cur_movement_state_ref, const streets_desired_phase_plan::signal_group2green_phase_timing &desired_sg_green_timing, const int desired_yellow_duration, const int desired_red_clearance) const
Populate movement_event list for given movement_state with green event, yellow change event, and red clearance event.
int find_max_desired_yellow_duration_red_clearance_pair (std::vector< int > desired_signal_groups, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_state) const
Find the signal group id for the signal group in a pair (movement group) that will have the largest yellow change plus red clearance time interval. This is useful since the largest yellow change plus red clearance will control how long all red events during this time interval will last.
void set_timestamp_local ()
Method to set SPaT timestamp based on system time.
void update_intersection_state (ntcip::ntcip_1202_ext &ntcip_data)
Method to update the front entry in the intersections list of intersection_state(s) with the provided NTCIP SPaT data (Thread Safe).
bool operator== (const spat &other) const
Equals operator to asses whether two objects contain equivalent data.
bool operator!= (const spat &other) const
Returns the inverse of equals operator.
Private Attributes
u_int32_t timestamp = 0
Timestamp in minutes of the UTC year (see J2735 SPaT message documentation for reference).
std::string name
Descriptive name for this collection.
std::list< intersection_state > intersections
Sets of SPaT data (one per intersection).
std::unordered_map< int, int > phase_to_signal_group
Map of phase number(NTCIP) to signal group(J2735).
std::shared_mutex spat_lock
Read/Write lock for concurrent access for read operations and exclusive access for write operations.
Detailed Description
Definition at line 22 of file spat.h.
Member Function Documentation
append_full_green_yellow_red_phases_by_desired_green()
void signal_phase_and_timing::spat::append_full_green_yellow_red_phases_by_desired_green (signal_phase_and_timing::movement_state & cur_movement_state_ref, const streets_desired_phase_plan::signal_group2green_phase_timing & desired_sg_green_timing, const int desired_yellow_duration, const int desired_red_clearance) const
Populate movement_event list for given movement_state with green event, yellow change event, and red clearance event.
Parameters
cur_movement_state_ref reference to movement_state.
desired_sg_green_timing desired phase plan entry for which to populate green, yellow and red clearance events.
desired_yellow_duration yellow duration configured for signal group of movement_state.
desired_red_clearance red clearance configured for signal group of movement_state.
Definition at line 372 of file spat.cpp.
    {
        auto desired_green_start_time_epoch = desired_sg_green_timing.start_time;
        auto desired_green_end_time_epoch = desired_sg_green_timing.end_time;
        // Add GREEN movement event
        signal_phase_and_timing::movement_event green_movement_event;
        populate_movement_event(green_movement_event,
                                signal_phase_and_timing::movement_phase_state::protected_movement_allowed,
                                desired_green_start_time_epoch, desired_green_end_time_epoch);
        cur_movement_state_ref.state_time_speed.push_back(green_movement_event);
        // Add YELLOW movement event
        signal_phase_and_timing::movement_event yellow_movement_event;
        uint64_t calculated_yellow_end_time_epoch = desired_green_end_time_epoch + desired_yellow_duration;
        populate_movement_event(yellow_movement_event,
                                signal_phase_and_timing::movement_phase_state::protected_clearance,
                                desired_green_end_time_epoch, calculated_yellow_end_time_epoch);
        cur_movement_state_ref.state_time_speed.push_back(yellow_movement_event);
        // Add RED movement event
        signal_phase_and_timing::movement_event red_movement_event;
        uint64_t calculated_red_end_time_epoch = calculated_yellow_end_time_epoch + desired_red_clearance;
        populate_movement_event(red_movement_event,
                                signal_phase_and_timing::movement_phase_state::stop_and_remain,
                                calculated_yellow_end_time_epoch,
                                calculated_red_end_time_epoch);
        cur_movement_state_ref.state_time_speed.push_back(red_movement_event);
    }
References streets_desired_phase_plan::signal_group2green_phase_timing::end_time, populate_movement_event(), signal_phase_and_timing::protected_clearance, signal_phase_and_timing::protected_movement_allowed, streets_desired_phase_plan::signal_group2green_phase_timing::start_time, signal_phase_and_timing::movement_state::state_time_speed, and signal_phase_and_timing::stop_and_remain.
Referenced by process_first_desired_green(), and process_second_onward_desired_green().
find_max_desired_yellow_duration_red_clearance_pair()
int signal_phase_and_timing::spat::find_max_desired_yellow_duration_red_clearance_pair (std::vector< int > desired_signal_groups, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_state) const
Find the signal group id for the signal group in a pair (movement group) that will have the largest yellow change plus red clearance time interval. This is useful since the largest yellow change plus red clearance will control how long all red events during this time interval will last.
Parameters
desired_signal_groups a pair of signal groups that make up a movement group.
tsc_state A pointer for traffic signal controller configuration informaton including yellow change and red intervals for all signal groups.
Returns
int the signal group id which has the largest combination of yellow change and red clearance time interval.
Definition at line 405 of file spat.cpp.
    {
        int return_sg_id = desired_signal_groups.front();
        int total = 0;
        for (auto sg : desired_signal_groups)
        {
            int desired_yellow_duration = tsc_state->tsc_config_list.empty()? 0 :tsc_state->get_signal_group_configuration_by_sg(sg).yellow_change_duration;
            int desired_red_clearance = tsc_state->tsc_config_list.empty()? 0 :tsc_state->get_signal_group_configuration_by_sg(sg).red_clearance;
            int local_total =  desired_yellow_duration+ desired_red_clearance;
            if (local_total > total)
            {
                total = local_total;
                return_sg_id = sg;
            }
        }
        return return_sg_id;
    }
Referenced by process_first_desired_green(), and process_second_onward_desired_green().
fromJson()
void signal_phase_and_timing::spat::fromJson (const std::string & json)
Deserialize SPaT JSON into SPaT object (Thread Safe).
Parameters
val SPaT JSON.
Definition at line 35 of file spat.cpp.
{
        rapidjson::Document doc;
        doc.Parse(json.c_str());
        if (doc.HasParseError()) {
            throw signal_phase_and_timing_exception("SPaT message JSON is misformatted. JSON parsing failed!");
        }
        // Write lock
        std::unique_lock  lock(spat_lock);
        if ( doc.HasMember("time_stamp") && doc.FindMember("time_stamp")->value.IsUint64()) {
            timestamp =  (uint32_t) doc["time_stamp"].GetUint64(); // OPTIONAL in J2735 SPaT definition
        }
        if (doc.FindMember("name")->value.IsString() ) {
            name = doc["name"].GetString();  // OPTIONAL see J2735 SPaT definition
        }
        if ( doc.FindMember("intersections")->value.IsArray() ) {
            // REQUIRED see J2735 SPaT definition
            // Clear intersection state list in case it is populated.
            intersections.clear();
            for ( const auto &intersection : doc["intersections"].GetArray() ){
                intersection_state cur_state;
                cur_state.fromJson(intersection);
                intersections.push_back(cur_state);
            }
        }
        else {
            throw signal_phase_and_timing_exception("SPaT message is missing required intersections property!");
        }
    }
References signal_phase_and_timing::intersection_state::fromJson(), intersections, name, spat_lock, and timestamp.
get_intersection()
intersection_state signal_phase_and_timing::spat::get_intersection ()
Get copy of current intersection state. Note: SPaT object currently only supports storing single intersection state (Thread Safe).
Returns
intersection_state
Definition at line 424 of file spat.cpp.
{
        std::shared_lock lock(spat_lock);
        if (intersections.empty())
            throw signal_phase_and_timing_exception("No intersection included currently in SPaT!");
        return intersections.front();
    }
References intersections, and spat_lock.
get_name()
std::string signal_phase_and_timing::spat::get_name ()
Get SPaT name.
Returns
std::string SPaT name.
Definition at line 432 of file spat.cpp.
{
        std::shared_lock lock(spat_lock);
        return name;
    }
References name, and spat_lock.
get_timestamp()
uint32_t signal_phase_and_timing::spat::get_timestamp ()
Get timestamp in minute of the current UTC year (Thread Safe).
Returns
uint32_t timestamp minute of the current UTC year.
Definition at line 437 of file spat.cpp.
{
        std::shared_lock lock(spat_lock);
        return timestamp;
    }
References spat_lock, and timestamp.
initialize_intersection()
void signal_phase_and_timing::spat::initialize_intersection (const std::string & intersection_name, const int intersection_id, const std::unordered_map< int, int > & phase_number_to_signal_group)
Method to initialize intersection information not provided in the ntcip SPaT UDP message but necessary for the J2735 SPaT message. This method must be executed prior to using the update method (Thread Safe).
Parameters
intersection_name name of intersection
intersection_id J2735 intersection ID
phase_number_to_signal_group a map of phase numbers (NTCIP) to signal groups (J2735)
Definition at line 84 of file spat.cpp.
{
        // Write lock
        std::unique_lock lock(spat_lock);
        if (!intersections.empty()) {
            intersections.clear();
        }
        intersection_state cur_state;
        cur_state.name = intersection_name;
        cur_state.id =  (uint16_t) intersection_id;
        phase_to_signal_group = _phase_number_to_signal_group;
        cur_state.initialize_movement_states( phase_to_signal_group );
        intersections.push_back(cur_state);
    }
References signal_phase_and_timing::intersection_state::id, signal_phase_and_timing::intersection_state::initialize_movement_states(), intersections, signal_phase_and_timing::intersection_state::name, phase_to_signal_group, and spat_lock.
operator!=()
bool signal_phase_and_timing::spat::operator!= (const spat & other) const
Returns the inverse of equals operator.
Parameters
other second object to compare current object with.
Returns
true if both objects do not contain equivalent data.
false if both objects do contain equivalent data.
Definition at line 453 of file spat.cpp.
{
        return !operator==(other);
    }
References operator==().
operator==()
bool signal_phase_and_timing::spat::operator== (const spat & other) const
Equals operator to asses whether two objects contain equivalent data.
Parameters
compare second object to compare current object with.
Returns
true if both object contain equivalent data.
false if not.
Definition at line 449 of file spat.cpp.
{
        return timestamp == other.timestamp && name == other.name && intersections == other.intersections;
    }
References intersections, name, and timestamp.
Referenced by operator!=().
populate_movement_event()
void signal_phase_and_timing::spat::populate_movement_event (signal_phase_and_timing::movement_event & movement_event_to_populate, const signal_phase_and_timing::movement_phase_state & phase_state, const uint64_t start_time_epoch, const uint64_t end_time_epoch) const
Populate movement_event with movement_phase_state, start_time and end_time(min_end_time).
Parameters
movement_event_to_populate reference to movement_event to populate.
phase_state enumeration to describe phase state.
start_time_epoch start time of movement event in milliseconds epoch time.
end_time_epoch end time of movement event in milliseconds epoch time.
Definition at line 362 of file spat.cpp.
    {
        movemnet_event_to_populate.event_state = phase_state;
        movemnet_event_to_populate.timing.set_start_time(start_time_epoch);
        movemnet_event_to_populate.timing.set_min_end_time(end_time_epoch);
    }
References signal_phase_and_timing::movement_event::event_state, signal_phase_and_timing::time_change_details::set_min_end_time(), signal_phase_and_timing::time_change_details::set_start_time(), and signal_phase_and_timing::movement_event::timing.
Referenced by append_full_green_yellow_red_phases_by_desired_green(), and process_first_desired_green().
process_first_desired_green()
void signal_phase_and_timing::spat::process_first_desired_green (signal_phase_and_timing::movement_state & cur_movement_state_ref, const streets_desired_phase_plan::signal_group2green_phase_timing & desired_sg_green_timing, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_state) const
Process first desired green signal group and duration in desired phase plan. Populate movement_event list of current movement_state with movement_events for first entry in desired phase plan.
Parameters
cur_movement_state_ref reference to movement_state inside SPaT for which to populate movement_event list.
desired_sg_green_timing first entry in desired phase plan which contains information about a green duration and the signal groups to which it applies.
tsc_state tsc state and signal group mapping information for red clearance and yellow change duraction.
If the SPAT current movement event is GREEN event state,
Updating the currnet GREEN event end time with desired green end time.
Add YELLOW movement event with start time equals to desired green end time, and end time equals to start time plus desired yellow duration
Add RED movement event with start time equals to the above YELLOW end time, and end time equals to start time plus desired red clearance
If the SPAT current movement state is RED,
Updating the current RED movement event end time equals to desired green end time + yellow duration + red clearance
If the SPAT current movement state is YELLOW,
Updating the YELLOW movement event end time equals to YELLOW start time + yellow duration of current spat movement state signal group id.
Add RED movement event start time equals to the above YELLOW start time and end with desired green end time + desired yellow duration + desired red clearance.
Definition at line 178 of file spat.cpp.
    {
        auto desired_green_signal_group_ids = desired_sg_green_timing.signal_groups;
        auto desired_green_start_time_epoch = desired_sg_green_timing.start_time;
        auto desired_green_end_time_epoch = desired_sg_green_timing.end_time;
        // If SPAT Current signal group id is in the current desired phase plan signal group ids, process desired green event for the SPAT
        // current movement event
        int current_signal_group_id = cur_movement_state_ref.signal_group;
        // Get yellow change and red clearance time interval for signal group in movement group with the largest combination
        // of yellow change and red clearance time interval.
        int signal_group_with_largest_clearance = find_max_desired_yellow_duration_red_clearance_pair(desired_sg_green_timing.signal_groups, tsc_state);
        int desired_yellow_duration = tsc_state->tsc_config_list.empty() ? 0 : tsc_state->get_signal_group_configuration_by_sg(signal_group_with_largest_clearance).yellow_change_duration;
        int desired_red_clearance = tsc_state->tsc_config_list.empty() ? 0 : tsc_state->get_signal_group_configuration_by_sg(signal_group_with_largest_clearance).red_clearance;
        SPDLOG_DEBUG("process signal group = {0} \t AND First desired sg ids = [{1} , {2}]",
                    current_signal_group_id, desired_green_signal_group_ids.front(),
                    desired_green_signal_group_ids.back());
        SPDLOG_DEBUG("desired sg id={0} \tdesired_yellow_duration = {1} \t AND desired_red_clearance = {2}",signal_group_with_largest_clearance, desired_yellow_duration, desired_red_clearance);
        if (std::count(desired_green_signal_group_ids.begin(), desired_green_signal_group_ids.end(), current_signal_group_id))
        {
            // GREEN
            if (cur_movement_state_ref.state_time_speed.front().event_state == signal_phase_and_timing::movement_phase_state::protected_movement_allowed) // GREEN
            {
                // Updating GREEN movement event
                cur_movement_state_ref.state_time_speed.front().timing.set_min_end_time(desired_green_end_time_epoch);
                // Add YELLOW movement event
                signal_phase_and_timing::movement_event yellow_movement_event;
                uint64_t calculated_yellow_end_time_epoch = desired_green_end_time_epoch + desired_yellow_duration;
                populate_movement_event(yellow_movement_event,
                                        signal_phase_and_timing::movement_phase_state::protected_clearance,
                                        desired_green_end_time_epoch,
                                        calculated_yellow_end_time_epoch);
                cur_movement_state_ref.state_time_speed.push_back(yellow_movement_event);
                // Add RED movement event
                signal_phase_and_timing::movement_event red_movement_event;
                populate_movement_event(red_movement_event,
                                        signal_phase_and_timing::movement_phase_state::stop_and_remain,
                                        calculated_yellow_end_time_epoch,
                                        calculated_yellow_end_time_epoch + desired_red_clearance);
                cur_movement_state_ref.state_time_speed.push_back(red_movement_event);
            }
            /****
             * If SPAT current movement state is RED event state,
             * - Updating red event state end time to desired green start time.
             * - Adding GREEN event state start time to desired green start time and end time equals to desired green end time.
             * - Add YELLOW event state start time to desired green end time and end time euqals to start time + desired yellow duration.
             * - Add RED event state start time to the above YELLO end time and end time euqals to start time + desired red clearance.
             * ***/
            else if (cur_movement_state_ref.state_time_speed.front().event_state == signal_phase_and_timing::movement_phase_state::stop_and_remain) // RED
            {
                // Updating RED movement event
                cur_movement_state_ref.state_time_speed.front().timing.set_min_end_time(desired_green_start_time_epoch);
                // Append GREEN, YELLOW, and RED movement events
                append_full_green_yellow_red_phases_by_desired_green(cur_movement_state_ref,
                                                                    desired_sg_green_timing,
                                                                    desired_yellow_duration,
                                                                    desired_red_clearance);
            }
            else
            {
                throw signal_phase_and_timing_exception("SPAT current movement event has to be green or red event state!");
            }
        }
        else
        {
            // SPAT Current signal group id is NOT in the current desired phase plan signal group ids
            if (cur_movement_state_ref.state_time_speed.front().event_state == signal_phase_and_timing::movement_phase_state::stop_and_remain) // RED
            {
                // Updating the current RED event state
                cur_movement_state_ref.state_time_speed.front().timing.set_min_end_time(desired_green_end_time_epoch +
                                                                                        desired_yellow_duration +
                                                                                        desired_red_clearance);
            }
            else if (cur_movement_state_ref.state_time_speed.front().event_state == signal_phase_and_timing::movement_phase_state::protected_clearance) // YELLOW
            {
                // Updating the current YELLOW movement event
                int spat_current_yellow_duration = tsc_state->tsc_config_list.empty()? 0 : tsc_state->get_signal_group_configuration_by_sg(current_signal_group_id).yellow_change_duration;
                SPDLOG_DEBUG("signal_group_with_largest_clearance={0} \tdesired_yellow_duration = {1} \t AND desired_red_clearance = {2}",signal_group_with_largest_clearance, desired_yellow_duration, desired_red_clearance);
                uint64_t calculated_yellow_end_time_epoch = cur_movement_state_ref.state_time_speed.front().timing.get_epoch_start_time()
                                                            + spat_current_yellow_duration;
                cur_movement_state_ref.state_time_speed.front().timing.set_min_end_time(calculated_yellow_end_time_epoch);
                // Add RED movement event
                signal_phase_and_timing::movement_event red_movement_event;
                uint64_t calculated_red_end_time_epoch = desired_green_end_time_epoch + desired_yellow_duration + desired_red_clearance;
                populate_movement_event(red_movement_event,
                                        signal_phase_and_timing::movement_phase_state::stop_and_remain,
                                        calculated_yellow_end_time_epoch,
                                        calculated_red_end_time_epoch);
                cur_movement_state_ref.state_time_speed.push_back(red_movement_event);
            }
            else
            {
                throw signal_phase_and_timing_exception("SPAT current movement event has to be red or yellow if its signal group id is not in desired signal group ids!");
            }
        }
    }
References append_full_green_yellow_red_phases_by_desired_green(), simulate_bsm::count, streets_desired_phase_plan::signal_group2green_phase_timing::end_time, find_max_desired_yellow_duration_red_clearance_pair(), populate_movement_event(), signal_phase_and_timing::protected_clearance, signal_phase_and_timing::protected_movement_allowed, signal_phase_and_timing::movement_state::signal_group, streets_desired_phase_plan::signal_group2green_phase_timing::signal_groups, streets_desired_phase_plan::signal_group2green_phase_timing::start_time, signal_phase_and_timing::movement_state::state_time_speed, and signal_phase_and_timing::stop_and_remain.
Referenced by update_spat_with_candidate_dpp().
process_second_onward_desired_green()
void signal_phase_and_timing::spat::process_second_onward_desired_green (signal_phase_and_timing::movement_state & cur_movement_state_ref, const streets_desired_phase_plan::signal_group2green_phase_timing & desired_sg_green_timing, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_state) const
Process all desired green signal group and duration in desired phase plan that are not the first entry. Populate movement_event list of current movement_state with movement_events for all entries after first entry in desired phase plan.
Parameters
cur_movement_state_ref reference to movement_state inside SPaT for which to populate movement_event list.
desired_sg_green_timing entry in desired phase plan which contains information about a green duration and the signal groups to which it applies.
tsc_state tsc state and signal group mapping information for red clearance and yellow change duraction.
Definition at line 298 of file spat.cpp.
    {
        auto desired_green_signal_group_ids = desired_sg_green_timing.signal_groups;
        auto desired_green_start_time_epoch = desired_sg_green_timing.start_time;
        auto desired_green_end_time_epoch = desired_sg_green_timing.end_time;
        /***
         * If current signal group id is in the current desired phase plan signal group ids,
         * - Updating the last RED movement event from movement event list. Updating the last RED movement event end time equals to desired green start time.
         * - Adding GREEN event state start time to desired green start time and end time equals to desired green end time.
         * - Adding YELLOW event state start time to desired green end time and end time euqals to start time + yellow duration.
         * - Adding RED event state start time to the above YELLO end time and end time euqals to start time + red clearance.
         **/
        int current_signal_group_id = cur_movement_state_ref.signal_group;
        // Get yellow change and red clearance time interval for signal group in movement group with the largest combination
        // of yellow change and red clearance time interval.
        int signal_group_with_largest_clearance = find_max_desired_yellow_duration_red_clearance_pair(desired_sg_green_timing.signal_groups, tsc_state);
        int desired_yellow_duration = tsc_state->tsc_config_list.empty() ? 0 : tsc_state->get_signal_group_configuration_by_sg(signal_group_with_largest_clearance).yellow_change_duration;
        int desired_red_clearance = tsc_state->tsc_config_list.empty() ? 0 : tsc_state->get_signal_group_configuration_by_sg(signal_group_with_largest_clearance).red_clearance;
        SPDLOG_DEBUG("process signal group = {0} \t AND second and onwards desired sg ids = [{1} , {2}]",
                    current_signal_group_id,
                    desired_green_signal_group_ids.front(),
                    desired_green_signal_group_ids.back());
        SPDLOG_DEBUG("desired sg id={0} \tdesired_yellow_duration = {1} \t AND desired_red_clearance = {2}",signal_group_with_largest_clearance, desired_yellow_duration, desired_red_clearance);
        if (std::count(desired_green_signal_group_ids.begin(), desired_green_signal_group_ids.end(), current_signal_group_id))
        {
            if (cur_movement_state_ref.state_time_speed.back().event_state != signal_phase_and_timing::movement_phase_state::stop_and_remain)
            {
                throw signal_phase_and_timing_exception("The last movement event has to be red to turn green again");
            }
            //  Updating the last RED movement end time
            cur_movement_state_ref.state_time_speed.back().timing.set_min_end_time(desired_green_start_time_epoch);
            // Append GREEN, YELLOW, and RED movement events
            append_full_green_yellow_red_phases_by_desired_green(cur_movement_state_ref,
                                                                desired_sg_green_timing,
                                                                desired_yellow_duration,
                                                                desired_red_clearance);
        }
        else
        {
            /***
             * If current signal group id is NOT in the current desired phase plan signal group ids,
             ***/
            if (cur_movement_state_ref.state_time_speed.back().event_state == signal_phase_and_timing::movement_phase_state::stop_and_remain) // RED
            {
                // Updating the current RED event state end time equals to desired green phase end time + desired yellow duration + desired red clearance
                cur_movement_state_ref.state_time_speed.back().timing.set_min_end_time(desired_green_end_time_epoch
                                                                                        + desired_yellow_duration
                                                                                        + desired_red_clearance);
            }
            else
            {
                throw signal_phase_and_timing_exception("For processing future movement events, the movement event has to be red if its signal group is not in the desired signal groups.");
            }
        }
    }
References append_full_green_yellow_red_phases_by_desired_green(), simulate_bsm::count, streets_desired_phase_plan::signal_group2green_phase_timing::end_time, find_max_desired_yellow_duration_red_clearance_pair(), signal_phase_and_timing::movement_state::signal_group, streets_desired_phase_plan::signal_group2green_phase_timing::signal_groups, streets_desired_phase_plan::signal_group2green_phase_timing::start_time, signal_phase_and_timing::movement_state::state_time_speed, and signal_phase_and_timing::stop_and_remain.
Referenced by update_spat_with_candidate_dpp().
set_intersection()
void signal_phase_and_timing::spat::set_intersection (const intersection_state & intersection)
Update current intersection state (Thread Safe).
Parameters
intersection intersection state update.
Definition at line 442 of file spat.cpp.
{
        // Write lock
        std::unique_lock lock(spat_lock);
        intersections.clear();
        intersections.push_front(intersection);
    }
References intersections, and spat_lock.
set_timestamp_local()
void signal_phase_and_timing::spat::set_timestamp_local ()
Method to set SPaT timestamp based on system time.
Definition at line 109 of file spat.cpp.
{
        if ( !intersections.empty() ) {
            intersection_state &intersection = intersections.front();
            intersection.set_timestamp_local();
            timestamp =  intersection.moy;
        }
        else {
            throw signal_phase_and_timing_exception("Intersection State List is empty! Cannot populate timestamp information!");
        }
    }
References intersections, and timestamp.
Referenced by update().
set_timestamp_ntcip()
void signal_phase_and_timing::spat::set_timestamp_ntcip (const uint32_t second_of_day, const uint16_t millisecond_of_second)
Method to set SPaT timestamp based on NTCIP message timestamp. The NTCIP message timestamp consists of a seconds_of_day and a milliseconds of second field. This method will get the current day from system time and then apply seconds and milliseconds informat as a offset for the current day.
Parameters
second_of_day NTCIP message timestamp information (seconds of the current UTC day).
millisecond_of_second NTCIP message timestamp information (millisecond of the current second).
Definition at line 98 of file spat.cpp.
{
        if ( !intersections.empty()) {
            intersection_state &intersection = intersections.front();
            intersection.set_timestamp_ntcip(second_of_day, millisecond_of_second);
            timestamp = intersection.moy;
        }
        else {
            throw signal_phase_and_timing_exception("Intersection State List is empty! Cannot populate timestamp information!");
        }
    }
References intersections, and timestamp.
Referenced by update().
toJson()
std::string signal_phase_and_timing::spat::toJson ()
Serialize SPaT object to rapidjson::Value for writing as JSON string (Thread Safe).
Returns
rapidjson::Value serialize SPaT object
Definition at line 5 of file spat.cpp.
{
        rapidjson::Document doc;
        auto allocator = doc.GetAllocator();
        // Create SPaT JSON value
        rapidjson::Value spat(rapidjson::kObjectType);
        // Read lock
        std::shared_lock lock(spat_lock);
        // Populate SPat JSON
        spat.AddMember("time_stamp", timestamp, allocator);
        spat.AddMember( "name", name, allocator);
        if ( !intersections.empty() ) {
            rapidjson::Value list(rapidjson::kArrayType);
            for (const auto &intersection : intersections ) {
                list.PushBack(intersection.toJson(allocator), allocator);
            }
            spat.AddMember("intersections", list, allocator);
        }else {
            throw signal_phase_and_timing_exception("SPaT message is missing required intersections property!");
        }
        rapidjson::StringBuffer buffer;
        try {
            rapidjson::Writer<rapidjson::StringBuffer> writer(buffer);
            spat.Accept(writer);
        }
        catch( const std::exception &e ) {
            throw signal_phase_and_timing_exception(e.what());
        }
        return buffer.GetString();
    }
References intersections, name, spat_lock, and timestamp.
update()
void signal_phase_and_timing::spat::update (ntcip::ntcip_1202_ext & ntcip_data, bool use_ntcip_timestamp)
Update spat object data using ntcip_1202_ext data received via UDP socket. Bool flag to control whether to use ntcip_1202_ext message provided timestamp or host unix timestamp information (Thread Safe).
Parameters
ntcip_data bytes from UDP socket, read into a struct
use_ntcip_timestamp Bool flag to control whether to use ntcip_1202_ext message provided timestamp or host unix timestamp information. If true will use message timestamp.
Definition at line 66 of file spat.cpp.
{
        if ( phase_to_signal_group.empty() || intersections.front().name.empty() || intersections.front().id == 0) {
            throw signal_phase_and_timing_exception("Before updating SPAT with NTCIP information spat::initialize() must be called! See README documentation!");
        }
        // Write lock
        std::unique_lock lock(spat_lock);
        if ( use_ntcip_timestamp ) {
            set_timestamp_ntcip( ntcip_data.get_timestamp_seconds_of_day(), ntcip_data.spat_timestamp_msec);
        }
        else {
            set_timestamp_local();
        }
        update_intersection_state( ntcip_data );
    }
References ntcip::ntcip_1202_ext::get_timestamp_seconds_of_day(), intersections, phase_to_signal_group, set_timestamp_local(), set_timestamp_ntcip(), spat_lock, ntcip::ntcip_1202_ext::spat_timestamp_msec, and update_intersection_state().
update_intersection_state()
void signal_phase_and_timing::spat::update_intersection_state (ntcip::ntcip_1202_ext & ntcip_data)
Method to update the front entry in the intersections list of intersection_state(s) with the provided NTCIP SPaT data (Thread Safe).
Parameters
ntcip_data
Definition at line 120 of file spat.cpp.
{
        if ( !intersections.empty() ) {
            intersection_state &intersection = intersections.front();
            intersection.update_movements(ntcip_data, phase_to_signal_group);
            // Update Intersection Status
            intersection.status = ntcip_data.spat_intersection_status;
            // From V2X-Hub TODO: Investigate
            intersection.revision = 1;
        }
        else {
            throw signal_phase_and_timing_exception("Intersection State List is empty! Cannot populate status information!");
        }
    }
References intersections, phase_to_signal_group, and ntcip::ntcip_1202_ext::spat_intersection_status.
Referenced by update().
update_spat_with_candidate_dpp()
void signal_phase_and_timing::spat::update_spat_with_candidate_dpp (const streets_desired_phase_plan::streets_desired_phase_plan & candidate_dpp, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_state)
Update spat movement_event list with desired phase plan information.
Parameters
candidate_dpp desired phase plan .
tsc_state tsc state and signal group mapping information.
Definition at line 134 of file spat.cpp.
    {
        std::unique_lock lock(spat_lock);
        //Removing all the future movement events from each intersection state because the future movements event should be recalculated using desired phase plan
        intersections.front().clear_future_movement_events();
        auto states = intersections.front().states;
        // Loop through desired phase plan
        bool is_processing_first_desired_green = true;
        for (const auto &desired_sg_green_timing : candidate_dpp.desired_phase_plan)
        {
            if (desired_sg_green_timing.signal_groups.empty())
            {
                throw signal_phase_and_timing_exception("Desired phase plan signal group ids list is empty. No update.");
            }
            // Loop through current spat and assuming that current spat only has the current movement event and does not contain future movement events
            for (const auto &movement_state : states)
            {
                int current_signal_group_id = movement_state.signal_group;
                // Before we add future movement events to the movement event list, the current movement event list should only contains the current movement event
                if (movement_state.state_time_speed.size() > 1)
                {
                    throw signal_phase_and_timing_exception("Movement event list has more than one events, not usable when adding future movement events. Associated with Signal Group: " + std::to_string(current_signal_group_id));
                }
                // Get movement_state by reference. With this reference, it can update the original SPAT movement state list
                auto &cur_movement_state_ref = intersections.front().get_movement(current_signal_group_id);
                // Processing the next current or first desired future movement event from the desired phase plan
                if (is_processing_first_desired_green)
                {
                   process_first_desired_green(cur_movement_state_ref, desired_sg_green_timing, tsc_state);
                }
                else
                {
                    // Processing the next future desired future movement event from the desired phase plan
                    process_second_onward_desired_green(cur_movement_state_ref, desired_sg_green_timing, tsc_state);
                }
            }
            is_processing_first_desired_green = false;
        }
    }
References streets_desired_phase_plan::streets_desired_phase_plan::desired_phase_plan, intersections, process_first_desired_green(), process_second_onward_desired_green(), signal_phase_and_timing::movement_state::signal_group, spat_lock, signal_phase_and_timing::movement_state::state_time_speed, and to_string().
Member Data Documentation
intersections
std::list<intersection_state> signal_phase_and_timing::spat::intersections private
Sets of SPaT data (one per intersection).
Definition at line 36 of file spat.h.
Referenced by fromJson(), get_intersection(), initialize_intersection(), operator==(), set_intersection(), set_timestamp_local(), set_timestamp_ntcip(), toJson(), update(), update_intersection_state(), and update_spat_with_candidate_dpp().
name
std::string signal_phase_and_timing::spat::name private
Descriptive name for this collection.
Definition at line 32 of file spat.h.
Referenced by fromJson(), get_name(), operator==(), and toJson().
phase_to_signal_group
std::unordered_map<int, int> signal_phase_and_timing::spat::phase_to_signal_group private
Map of phase number(NTCIP) to signal group(J2735).
Definition at line 41 of file spat.h.
Referenced by initialize_intersection(), update(), and update_intersection_state().
spat_lock
std::shared_mutex signal_phase_and_timing::spat::spat_lock private
Read/Write lock for concurrent access for read operations and exclusive access for write operations.
Definition at line 46 of file spat.h.
Referenced by fromJson(), get_intersection(), get_name(), get_timestamp(), initialize_intersection(), set_intersection(), toJson(), update(), and update_spat_with_candidate_dpp().
timestamp
u_int32_t signal_phase_and_timing::spat::timestamp = 0 private
Timestamp in minutes of the UTC year (see J2735 SPaT message documentation for reference).
Definition at line 28 of file spat.h.
Referenced by fromJson(), get_timestamp(), operator==(), set_timestamp_local(), set_timestamp_ntcip(), and toJson().
The documentation for this class was generated from the following files:
streets_utils/streets_signal_phase_and_timing/include/spat.h
streets_utils/streets_signal_phase_and_timing/src/models/spat.cpp