Carma-streets: streets_vehicle_scheduler::signalized_vehicle_scheduler Class Reference
streets_vehicle_scheduler::signalized_vehicle_scheduler Class Reference
#include <signalized_vehicle_scheduler.h>
Public Member Functions
signalized_vehicle_scheduler ()=default
Construct a new signalized vehicle scheduler object.
~signalized_vehicle_scheduler () override=default
Destroy the signalized vehicle scheduler object.
void schedule_vehicles (std::unordered_map< std::string, streets_vehicles::vehicle > &vehicles, std::shared_ptr< intersection_schedule > &schedule) override
Method to schedule vehicles. Given and empty intersection_schedule shared pointer and a map of vehicles and vehicle ids. This method will populate the intersection schedule with a schedule for all vehicles in the vehicle map based on UC 3 scheduling logic to estimate vehicles' entering times to the intersection box based on the modified spat.
void set_initial_green_buffer (const uint64_t buffer)
Set the initial green buffer (ms). This value is used to account for the time it takes a vehicle before entering the intersection box at a green phase.
uint64_t get_initial_green_buffer () const
Get the initial green buffer (ms).
void set_final_green_buffer (const uint64_t buffer)
Set the final green buffer (ms). This value is used to account for safety. The assumption is that no vehicle shall enter the intersection box after the end of a green phase minus the final green buffer. entering the intersection box at a green phase.
uint64_t get_final_green_buffer () const
Get the final green buffer (ms).
std::shared_ptr< signal_phase_and_timing::spat > get_spat () const
Get the spat object.
void set_spat (std::shared_ptr< signal_phase_and_timing::spat > spat_info)
Set the spat object.
Public Member Functions inherited from streets_vehicle_scheduler::vehicle_scheduler
vehicle_scheduler ()=default
Construct a new vehicle scheduler object.
virtual ~vehicle_scheduler ()=default
Destroy the vehicle scheduler object.
virtual void schedule_vehicles (std::unordered_map< std::string, streets_vehicles::vehicle > &vehicles, std::shared_ptr< intersection_schedule > &schedule)=0
Virtual method to schedule vehicle. Different implementations of vehicle scheduler can implement custom business logic for scheduling vehicle while taking advantage of polymorphism to dynamically assign class at runtime.
std::shared_ptr< OpenAPI::OAIIntersection_info > get_intersection_info () const
Get the intersection info object.
void set_intersection_info (std::shared_ptr< OpenAPI::OAIIntersection_info > _intersection_info)
Set the intersection info object.
Private Member Functions
void schedule_dvs (const std::list< streets_vehicles::vehicle > &dvs, const std::shared_ptr< signalized_intersection_schedule > &schedule) const
Estimate the intersection departure times (dt's) for all currently Departing Vehicle (DVs) based on kinematic vehicle information and intersection geometry. Method assumes empty intersection_schedule is passed in. Method will add vehicle_schedule(s) for each DV in the vector.
void schedule_evs (std::list< streets_vehicles::vehicle > &evs, const std::shared_ptr< signalized_intersection_schedule > &schedule) const
Schedule all Entering Vehicles (EVs). Method first organizes all EVs into lists based on their entry lane. These list are ordered in ascending order with the vehicle closest to the intersection in a given lane being the first vehicle in that entry lanes vehicle list. Then, for each entry lane, an entering time (ET) for each EV in the entry lane is calculated sequentially starting from the first vehicle until in the list. ET is estimated based on the EV's earliest entering time (EET), its preceding vehicle's estimated ET, and the modifed spat.
void estimate_et (const streets_vehicles::vehicle &veh, const std::shared_ptr< signalized_vehicle_schedule > &preceding_veh, signalized_vehicle_schedule &sched, const signal_phase_and_timing::movement_state &move_state, const uint64_t schedule_timestamp) const
Estimate an entering time (ET) for a given Entering Vehicle (EV). ET is estimated based on the EV's earliest entering time (EET), its preceding vehicle's estimated ET, and the modifed spat.
uint64_t calculate_earliest_entering_time (const streets_vehicles::vehicle &veh) const
Method to use vehicle kinematic information to estimate earliest possible entering time (EET) for an entering vehicle (EV). Does not consider any other vehicles. Limiting factors are the vehicles current kinematic information, lane speed limits and vehicle acceleration and deceleration limits.
double calculate_distance_accel_and_decel (const streets_vehicles::vehicle &veh, const double max_speed, const double departure_speed) const
Calculate the distance required to speed up to lane speed limit with maximum acceleration and then decelerate to departure speed with maximum deceleration. This is used to calculate the earliest entering time (EET) for the vehicle.
double calculate_distance_accel_or_decel (const streets_vehicles::vehicle &veh, const double departure_speed) const
Calculate the distance required to speed up (slow down) to departure speed with maximum acceleration (maximum deceleration). If the departure speed is greater than the vehicle's current speed, the vehicle has to speed up with maximum acceleration. Otherwise, the vehicle has to slow down with maximum deceleration. This is used to calculate the earliest entering time (EET) for the vehicle.
double calculate_v_hat (const streets_vehicles::vehicle &veh, const double max_speed, const double departure_speed, const double delta_x, const double delta_x_prime, const double delta_x_zegond) const
Method to calculate v_hat. This is the joint speed between the acceleration and deceleration periods of a vehicle trajectory that is calculated to estimate the vehicle's earliest entering time (EET).
double calculate_acceleration_time (const streets_vehicles::vehicle &veh, const double v_hat, const double departure_speed, const double delta_x, const double delta_x_zegond) const
Method to calculate time interval necessary for accelerating to speed v_hat for a given vehicle. Will return 0 if there is no acceleration period.
double calculate_deceleration_time (const streets_vehicles::vehicle &veh, const double v_hat, const double departure_speed, const double delta_x, const double delta_x_zegond) const
Method to calculate time interval necessary for deceleration from v_hat to departure speed. Will return 0 if there is no deceleration period.
double calculate_cruising_time (const double v_hat, const double delta_x, const double delta_x_prime) const
Method to calculate time interval necessary for cruising at a constant speed v_hat (speed limit) greater than current vehicle speed. Will return 0 if there is no cruising period.
uint64_t calculate_min_headway (const streets_vehicles::vehicle &veh, const double speed) const
Calculate the minimum safety time headway required by the vehicle at a given speed.
uint64_t estimate_clearance_time (const streets_vehicles::vehicle &veh) const
Estimate clearance time of a vehicle given it's current speed.
signal_phase_and_timing::movement_state find_movement_state_for_lane (const OpenAPI::OAILanelet_info &entry_lane_info) const
find the movement state info from the modified spat for vehicles from a given entry lane. Note: The signalized_vehicle_scheduler is only capable of understanding intersection where all connection lanes from a single entry lane share a signal_group_id. Therefore, vehicles from an entry lane with different directions at the intersection box shall be able to receive protected green at the same time.
Private Attributes
std::shared_ptr< signal_phase_and_timing::spat > spat_ptr
A shared pointer to the modified_spat.
uint64_t initial_green_buffer
The configurable time interval at the beginning of a green phase in milliseconds that is considered for estimating vehicles' entering times. The earliest possible entering time during a phase is set to the beginning of the green phase plus the initial_green_buffer.
uint64_t final_green_buffer
The configurable time interval at the end of a green phase in milliseconds that is considered for estimating vehicles' entering times. The latest possible entering time during a phase is set to the end of the green phase minus the final_green_buffer.
Additional Inherited Members
Protected Member Functions inherited from streets_vehicle_scheduler::vehicle_scheduler
void estimate_vehicles_at_common_time (std::unordered_map< std::string, streets_vehicles::vehicle > &vehicles, const u_int64_t timestamp) const
Method to estimate all vehicle's speed and location at a common future time. The time needs to be time since epoch in milliseconds. To predict vehicle location and speed at future time, current kinematic information is used including speed and current acceleration.
OpenAPI::OAILanelet_info get_entry_lanelet_info (const streets_vehicles::vehicle &veh) const
Helper method to get entry lane OAILanelet_info from intersection information given a vehicle.
OpenAPI::OAILanelet_info get_link_lanelet_info (const streets_vehicles::vehicle &veh) const
Helper method to get link lane OAILanelet_info from intersection information given a vehicle.
Protected Attributes inherited from streets_vehicle_scheduler::vehicle_scheduler
std::shared_ptr< OpenAPI::OAIIntersection_info > intersection_info
shared pointer to intersection information required for scheduling.
Detailed Description
Definition at line 17 of file signalized_vehicle_scheduler.h.
Constructor & Destructor Documentation
signalized_vehicle_scheduler()
streets_vehicle_scheduler::signalized_vehicle_scheduler::signalized_vehicle_scheduler () default
Construct a new signalized vehicle scheduler object.
~signalized_vehicle_scheduler()
streets_vehicle_scheduler::signalized_vehicle_scheduler::~signalized_vehicle_scheduler () override default
Destroy the signalized vehicle scheduler object.
Member Function Documentation
calculate_acceleration_time()
double streets_vehicle_scheduler::signalized_vehicle_scheduler::calculate_acceleration_time (const streets_vehicles::vehicle & veh, const double v_hat, const double departure_speed, const double delta_x, const double delta_x_zegond) const private
Method to calculate time interval necessary for accelerating to speed v_hat for a given vehicle. Will return 0 if there is no acceleration period.
Parameters
veh vehicle for which to calculate the joint speed.
v_hat joint speed between the acceleration and deceleration periods.
departure_speed departure speed = speed limit of the vehicle's link lane.
delta_x distance between the vehicle and the stop bar at its entry lane
delta_x_zegond distance required to speed up (slow down) to departure speed with maximum acceleration (maximum deceleration).
Returns
double acceleration time interval in seconds.
Definition at line 334 of file signalized_vehicle_scheduler.cpp.
{
        double t_accel = 0.0;
        if (delta_x >= delta_x_zegond || departure_speed >= veh._cur_speed){
            if (v_hat >= veh._cur_speed) {
                t_accel = (v_hat - veh._cur_speed) / veh._accel_max;
            }
            else {
                SPDLOG_DEBUG("Negative acceleration time interval is calculated for vehicle {0}. The acceleration time interval is set to 0.", veh._id);
            }
        }
        return t_accel;
    }
References streets_vehicles::vehicle::_accel_max, streets_vehicles::vehicle::_cur_speed, and streets_vehicles::vehicle::_id.
Referenced by calculate_earliest_entering_time().
calculate_cruising_time()
double streets_vehicle_scheduler::signalized_vehicle_scheduler::calculate_cruising_time (const double v_hat, const double delta_x, const double delta_x_prime) const private
Method to calculate time interval necessary for cruising at a constant speed v_hat (speed limit) greater than current vehicle speed. Will return 0 if there is no cruising period.
Parameters
v_hat cruising speed\joint speed between the acceleration and deceleration periods. Usually lane speed limit, in m/s.
delta_x distance between the vehicle and the stop bar at its entry lane
delta_x_prime distance required to speed up to lane speed limit with maximum acceleration and then decelerate to departure speed with maximum deceleration. The difference between the distance to the stop bar and this distance is the part of the trajectory for which the vehicle can cruise at v_hat.
Returns
double cruising time interval in seconds.
Definition at line 370 of file signalized_vehicle_scheduler.cpp.
{
        if (delta_x > delta_x_prime) {
            return (delta_x - delta_x_prime) / v_hat;
        }
        return 0.0;
    }
Referenced by calculate_earliest_entering_time().
calculate_deceleration_time()
double streets_vehicle_scheduler::signalized_vehicle_scheduler::calculate_deceleration_time (const streets_vehicles::vehicle & veh, const double v_hat, const double departure_speed, const double delta_x, const double delta_x_zegond) const private
Method to calculate time interval necessary for deceleration from v_hat to departure speed. Will return 0 if there is no deceleration period.
Parameters
veh vehicle for which to calculate trajectory.
v_hat joint speed between the acceleration and deceleration periods.
departure_speed departure speed = speed limit of the vehicle's link lane.
delta_x distance between the vehicle and the stop bar at its entry lane
delta_x_zegond distance required to speed up (slow down) to departure speed with maximum acceleration (maximum deceleration).
Returns
double deceleration time interval in seconds.
Definition at line 348 of file signalized_vehicle_scheduler.cpp.
{
        double t_decel = 0.0;
        if (delta_x < delta_x_zegond && departure_speed < veh._cur_speed) {
            if (v_hat <= veh._cur_speed) {
                t_decel = (v_hat - veh._cur_speed) / veh._decel_max;
            }
            else {
                SPDLOG_DEBUG("Negative deceleration time interval is calculated for vehicle {0}. The deceleration time interval is set to 0.", veh._id);
            }
        }
        else if (delta_x >= delta_x_zegond) {
            if (v_hat >= departure_speed) {
                t_decel = (departure_speed - v_hat) / veh._decel_max;
            }
            else {
                SPDLOG_DEBUG("Negative deceleration time interval is calculated for vehicle {0}. The deceleration time interval is set to 0.", veh._id);
            }
        }
        return t_decel;
    }
References streets_vehicles::vehicle::_cur_speed, streets_vehicles::vehicle::_decel_max, and streets_vehicles::vehicle::_id.
Referenced by calculate_earliest_entering_time().
calculate_distance_accel_and_decel()
double streets_vehicle_scheduler::signalized_vehicle_scheduler::calculate_distance_accel_and_decel (const streets_vehicles::vehicle & veh, const double max_speed, const double departure_speed) const private
Calculate the distance required to speed up to lane speed limit with maximum acceleration and then decelerate to departure speed with maximum deceleration. This is used to calculate the earliest entering time (EET) for the vehicle.
Parameters
veh vehicle for which to calculate distance.
max_speed speed limit of the vehicle's entry lane.
departure_speed departure speed = speed limit of the vehicle's link lane.
Returns
double distance in meters
Definition at line 294 of file signalized_vehicle_scheduler.cpp.
{
        // calculate delta x prime
        double delta_x_prime = ((pow(max_speed, 2) - pow(veh._cur_speed, 2)) / (2 * veh._accel_max)) + ((pow(departure_speed, 2) - pow(max_speed, 2)) / (2 * veh._decel_max));
        return  delta_x_prime;
    }
References streets_vehicles::vehicle::_accel_max, streets_vehicles::vehicle::_cur_speed, and streets_vehicles::vehicle::_decel_max.
Referenced by calculate_earliest_entering_time().
calculate_distance_accel_or_decel()
double streets_vehicle_scheduler::signalized_vehicle_scheduler::calculate_distance_accel_or_decel (const streets_vehicles::vehicle & veh, const double departure_speed) const private
Calculate the distance required to speed up (slow down) to departure speed with maximum acceleration (maximum deceleration). If the departure speed is greater than the vehicle's current speed, the vehicle has to speed up with maximum acceleration. Otherwise, the vehicle has to slow down with maximum deceleration. This is used to calculate the earliest entering time (EET) for the vehicle.
Parameters
veh vehicle for which to calculate distance.
departure_speed departure speed = speed limit of the vehicle's link lane.
Returns
double distance in meters
Definition at line 301 of file signalized_vehicle_scheduler.cpp.
{
        // calculate delta x zegond
        double delta_x_zegond;
        if (veh._cur_speed <= departure_speed) {
            delta_x_zegond = (pow(departure_speed, 2) - pow(veh._cur_speed, 2)) / (2 * veh._accel_max);
        }
        else {
            delta_x_zegond = (pow(departure_speed, 2) - pow(veh._cur_speed, 2)) / (2 * veh._decel_max);
        }
        return  delta_x_zegond;
    }
References streets_vehicles::vehicle::_accel_max, streets_vehicles::vehicle::_cur_speed, and streets_vehicles::vehicle::_decel_max.
Referenced by calculate_earliest_entering_time().
calculate_earliest_entering_time()
uint64_t streets_vehicle_scheduler::signalized_vehicle_scheduler::calculate_earliest_entering_time (const streets_vehicles::vehicle & veh) const private
Method to use vehicle kinematic information to estimate earliest possible entering time (EET) for an entering vehicle (EV). Does not consider any other vehicles. Limiting factors are the vehicles current kinematic information, lane speed limits and vehicle acceleration and deceleration limits.
Parameters
veh vehicle for which to estimate EET.
Returns
uint64_t time in milliseconds.
Definition at line 247 of file signalized_vehicle_scheduler.cpp.
{
        if ( veh._cur_state == streets_vehicles::vehicle_state::EV) {
            // Distance to stop bar
            double delta_x = veh._cur_distance;
            // Get Entry Lane
            OpenAPI::OAILanelet_info entry_lane =  get_entry_lanelet_info( veh );
            // Get Link Lane
            OpenAPI::OAILanelet_info link_lane =  get_link_lanelet_info( veh );
            // Distance necessary to get to max speed and decelerate with decel_max to departure speed
            double delta_x_prime =  calculate_distance_accel_and_decel( veh, entry_lane.getSpeedLimit(), link_lane.getSpeedLimit() );
            // Distance necessary to get to the departure speed
            double delta_x_zegond =  calculate_distance_accel_or_decel( veh, link_lane.getSpeedLimit() );
            SPDLOG_DEBUG("Delta X = {0}, Delta X Prime = {1}, Delta X Zegond = {2}.", delta_x, delta_x_prime, delta_x_zegond);
            // Calculate v_hat
            double v_hat = calculate_v_hat(veh, entry_lane.getSpeedLimit(), link_lane.getSpeedLimit(), delta_x, delta_x_prime, delta_x_zegond);
            SPDLOG_DEBUG("V hat = {0}.", v_hat);
            // calculate planned acceleration time interval
            double t_accel = calculate_acceleration_time(veh, v_hat, link_lane.getSpeedLimit(), delta_x, delta_x_zegond);
            SPDLOG_DEBUG("T accel = {0}.",t_accel);
            // calculate planned deceleration time interval
            double t_decel = calculate_deceleration_time(veh, v_hat, link_lane.getSpeedLimit(), delta_x, delta_x_zegond);
            SPDLOG_DEBUG("T decel = {0}.",t_decel);
            // Calculate planned cruising time interval
            double t_cruising = calculate_cruising_time(v_hat, delta_x, delta_x_prime);
            SPDLOG_DEBUG("T cruising = {0}.",t_cruising);
            // calculate earliest entering time to stop bar
            double eet = t_accel + t_cruising + t_decel;
            if (eet <= 0) {
                SPDLOG_DEBUG("The estimated eet for vehicle {0} has a negative value = {1}!", veh._id, eet);
            }
            return static_cast<uint64_t>(ceil(eet * 1000.0)) + veh._cur_time;
        }
        else
        {
            SPDLOG_DEBUG("Cannot estimate the earliest entering time for vehicle {0} which is not an EV!", veh._id);
            throw scheduling_exception("Trying to calculate earliest entering time (EET) for a vehicle that is not an EV!");
        }
        return -1;
    }
References streets_vehicles::vehicle::_cur_distance, streets_vehicles::vehicle::_cur_state, streets_vehicles::vehicle::_cur_time, streets_vehicles::vehicle::_id, calculate_acceleration_time(), calculate_cruising_time(), calculate_deceleration_time(), calculate_distance_accel_and_decel(), calculate_distance_accel_or_decel(), calculate_v_hat(), streets_vehicles::EV, streets_vehicle_scheduler::vehicle_scheduler::get_entry_lanelet_info(), streets_vehicle_scheduler::vehicle_scheduler::get_link_lanelet_info(), and OpenAPI::OAILanelet_info::getSpeedLimit().
Referenced by estimate_et().
calculate_min_headway()
uint64_t streets_vehicle_scheduler::signalized_vehicle_scheduler::calculate_min_headway (const streets_vehicles::vehicle & veh, const double speed) const private
Calculate the minimum safety time headway required by the vehicle at a given speed.
Parameters
veh vehicle for which to calculate minimum safety time headway.
speed the assumed speed at which to calculate minimum safety time headway.
Returns
uint64_t minimum safety time headway in milliseconds.
Definition at line 378 of file signalized_vehicle_scheduler.cpp.
{
        return static_cast<uint64_t>(ceil( 1000*(veh._reaction_time + ((veh._length + veh._min_gap)/speed)) ));
    }
References streets_vehicles::vehicle::_length, streets_vehicles::vehicle::_min_gap, and streets_vehicles::vehicle::_reaction_time.
Referenced by estimate_et().
calculate_v_hat()
double streets_vehicle_scheduler::signalized_vehicle_scheduler::calculate_v_hat (const streets_vehicles::vehicle & veh, const double max_speed, const double departure_speed, const double delta_x, const double delta_x_prime, const double delta_x_zegond) const private
Method to calculate v_hat. This is the joint speed between the acceleration and deceleration periods of a vehicle trajectory that is calculated to estimate the vehicle's earliest entering time (EET).
Parameters
veh vehicle for which to calculate the joint speed.
max_speed speed limit of the vehicle's entry lane.
departure_speed departure speed = speed limit of the vehicle's link lane.
delta_x distance between the vehicle and the stop bar at its entry lane
delta_x_prime distance required to speed up to lane speed limit with maximum acceleration and then decelerate to departure speed with maximum deceleration.
delta_x_zegond distance required to speed up (slow down) to departure speed with maximum acceleration (maximum deceleration).
Returns
double v_hat in m/s
Definition at line 314 of file signalized_vehicle_scheduler.cpp.
{
        if (delta_x >= delta_x_prime) {
            return max_speed;
        }
        else if (delta_x_prime > delta_x && delta_x >= delta_x_zegond) {
            double numerator = (2 * delta_x * veh._decel_max * veh._accel_max) + (veh._decel_max * pow(veh._cur_speed, 2)) - (veh._accel_max * pow(departure_speed, 2));
            double denominator = veh._decel_max - veh._accel_max;
            return sqrt(numerator/denominator);
        }
        else {
            if (veh._cur_speed <= departure_speed) {
                return sqrt((2 * delta_x * veh._accel_max) + pow(veh._cur_speed, 2));
            }
            else {
                return sqrt((2 * delta_x * veh._decel_max) + pow(veh._cur_speed, 2));
            }
        }
    }
References streets_vehicles::vehicle::_accel_max, streets_vehicles::vehicle::_cur_speed, and streets_vehicles::vehicle::_decel_max.
Referenced by calculate_earliest_entering_time().
estimate_clearance_time()
uint64_t streets_vehicle_scheduler::signalized_vehicle_scheduler::estimate_clearance_time (const streets_vehicles::vehicle & veh) const private
Estimate clearance time of a vehicle given it's current speed.
Parameters
veh vehicle for which to estimate clearance time.
Returns
uint64_t clearance time in milliseconds.
Definition at line 384 of file signalized_vehicle_scheduler.cpp.
{
        // Get Link Lane
        OpenAPI::OAILanelet_info link_lane =  get_link_lanelet_info( veh );
        if ( veh._cur_state == streets_vehicles::vehicle_state::DV ) {
            return static_cast<uint64_t>( ceil(1000 * veh._cur_distance / veh._cur_speed) );
        }
        else {
            return static_cast<uint64_t>( ceil(1000 * link_lane.getLength() / link_lane.getSpeedLimit()) );
        }
    }
References streets_vehicles::vehicle::_cur_distance, streets_vehicles::vehicle::_cur_speed, streets_vehicles::vehicle::_cur_state, streets_vehicles::DV, streets_vehicle_scheduler::vehicle_scheduler::get_link_lanelet_info(), OpenAPI::OAILanelet_info::getLength(), and OpenAPI::OAILanelet_info::getSpeedLimit().
Referenced by estimate_et(), and schedule_dvs().
estimate_et()
void streets_vehicle_scheduler::signalized_vehicle_scheduler::estimate_et (const streets_vehicles::vehicle & veh, const std::shared_ptr< signalized_vehicle_schedule > & preceding_veh, signalized_vehicle_schedule & sched, const signal_phase_and_timing::movement_state & move_state, const uint64_t schedule_timestamp) const private
Estimate an entering time (ET) for a given Entering Vehicle (EV). ET is estimated based on the EV's earliest entering time (EET), its preceding vehicle's estimated ET, and the modifed spat.
Parameters
veh vehicle for which to estimate ET.
preceding_veh shared pointer of the preceding vehicle of the subject vehicle (veh)
sched signalized_intersection_schedule to add EV scheduling information to.
move_state movement state information that includes a list of current and pending phases.
schedule_timestamp timestamp of the current schedule in milliseconds.
estimate the earliest possible ET based on the current timestamp, the preceding vehicle's estimated ET, and the subject vehicle's minimum required safety time headway at tbe departure speed.
Definition at line 190 of file signalized_vehicle_scheduler.cpp.
{
        // Get link lanelet information for ev
        OpenAPI::OAILanelet_info link_lane = get_link_lanelet_info( veh );
        SPDLOG_DEBUG( "Link lanelet for vehicle {0} is {1}.", veh._id, link_lane.getId());
        // Calculate EET for vehicle
        uint64_t eet = calculate_earliest_entering_time(veh);
        SPDLOG_DEBUG( "EET for vehicle {0} is {1}." ,veh._id, eet );
        // Calculate min_headway
        uint64_t min_headway = calculate_min_headway( veh, link_lane.getSpeedLimit() );
        SPDLOG_DEBUG( "min headway for vehicle {0} is {1}.", veh._id, min_headway );
        uint64_t first_available_et;
        if (preceding_veh == nullptr) {
            first_available_et = schedule_timestamp;
        }
        else {
            first_available_et = std::max(schedule_timestamp, preceding_veh->et + min_headway);
        }
        // Check the movement_event list one by one until successfully estimating the vehicle's entering time (ET).
        // The assumption is that the movement_event list is sorted based on the movement_event timing.
        // (example: the second phase's start time shall be equal to the first phase's min_end_time).
        bool is_successful = false;
        uint64_t et;
        for (const auto &move_event : move_state.state_time_speed) {
            SPDLOG_DEBUG("Moving to the next movement event from the list! start time without buffer = {0}, end time without buffer = {1}", move_event.timing.get_epoch_start_time(), move_event.timing.get_epoch_min_end_time() );
            if (move_event.event_state == signal_phase_and_timing::movement_phase_state::protected_movement_allowed) {
                et = std::max(first_available_et, std::max(eet, move_event.timing.get_epoch_start_time() + initial_green_buffer));
                if ( et < move_event.timing.get_epoch_min_end_time() - final_green_buffer ) {
                    SPDLOG_DEBUG( "Successfully estimate an ET (within a green phase) for vehicle {0}. The estimated ET = {1}.", veh._id, et);
                    is_successful = true;
                    break;
                }
                SPDLOG_DEBUG( "The estimated ET for vehicle {0} is later than the end of the phase. Estimated ET = {1}, end of the phase", veh._id, et, move_event.timing.get_epoch_min_end_time() - final_green_buffer );
            }
        }
        // TBD area
        if (!is_successful) {
            et = std::max(first_available_et, std::max(eet, move_state.state_time_speed.back().timing.get_epoch_min_end_time() + initial_green_buffer));
            SPDLOG_DEBUG( "Successfully estimate an ET (within TBD area) for vehicle {0}. The estimated ET = {1}.", veh._id, et);
        }
        // Set schedule properties
        sched.v_id =  veh._id;
        sched.eet = eet;
        sched.et = et;
        sched.dt = sched.et + estimate_clearance_time( veh );
        sched.entry_lane =  veh._entry_lane_id;
        sched.link_id = veh._link_id;
        sched.state = streets_vehicles::vehicle_state::EV;
    }
References streets_vehicles::vehicle::_entry_lane_id, streets_vehicles::vehicle::_id, streets_vehicles::vehicle::_link_id, calculate_earliest_entering_time(), calculate_min_headway(), streets_vehicle_scheduler::signalized_vehicle_schedule::dt, streets_vehicle_scheduler::signalized_vehicle_schedule::eet, streets_vehicle_scheduler::vehicle_schedule::entry_lane, estimate_clearance_time(), streets_vehicle_scheduler::signalized_vehicle_schedule::et, streets_vehicles::EV, final_green_buffer, streets_vehicle_scheduler::vehicle_scheduler::get_link_lanelet_info(), OpenAPI::OAILanelet_info::getId(), OpenAPI::OAILanelet_info::getSpeedLimit(), initial_green_buffer, streets_vehicle_scheduler::vehicle_schedule::link_id, signal_phase_and_timing::protected_movement_allowed, streets_vehicle_scheduler::signalized_vehicle_schedule::state, signal_phase_and_timing::movement_state::state_time_speed, and streets_vehicle_scheduler::vehicle_schedule::v_id.
Referenced by schedule_evs().
find_movement_state_for_lane()
signal_phase_and_timing::movement_state streets_vehicle_scheduler::signalized_vehicle_scheduler::find_movement_state_for_lane (const OpenAPI::OAILanelet_info & entry_lane_info) const private
find the movement state info from the modified spat for vehicles from a given entry lane. Note: The signalized_vehicle_scheduler is only capable of understanding intersection where all connection lanes from a single entry lane share a signal_group_id. Therefore, vehicles from an entry lane with different directions at the intersection box shall be able to receive protected green at the same time.
Parameters
entry_lane_info entry lanelet lane.
Returns
signal_phase_and_timing::movement_state movement stat object.
Exceptions
if two or more connection link lanelets from a single entry lane have different signal_group_id, then the design does not satisfy the requirement of the signalized_vehicle_scheduler and thus, this method throws exception.
Definition at line 147 of file signalized_vehicle_scheduler.cpp.
{
        // check if all links connected to the entry lane have the same signal ids or not!
        uint8_t signal_group_id = 0;
        bool first_link_visited = false;
        auto connection_lanelet_ids = entry_lane_info.getConnectingLaneletIds();
        for ( const auto &lane : intersection_info->getLinkLanelets() ) {
            // check if the link lanelet's id (lane.getId()) is included in the list of connecting lanelet ids of the received entry lanelet.
            if ( std::find(connection_lanelet_ids.begin(), connection_lanelet_ids.end(), lane.getId()) != connection_lanelet_ids.end() ) {
                if ( !lane.getSignalGroupId() ) {
                    throw scheduling_exception("The connection link lanelet does not have a group_id!");
                }
                if (first_link_visited && lane.getSignalGroupId() != signal_group_id){
                    throw scheduling_exception("The link lanelets connected to the entry lane have "
                                                "different signal_group_ids! The signalized_vehicle_scheduler"
                                                " is only capable of understanding intersection where all connection"
                                                " lanes from a single entry lane share a signal_group_id!");
                }
                if (!first_link_visited) {
                    signal_group_id = lane.getSignalGroupId();
                    first_link_visited = true;
                }
            }
        }
        // find the movement_state object
        signal_phase_and_timing::movement_state move_state;
        if ( spat_ptr ) {
            for (const auto& ms : spat_ptr->get_intersection().states){
                if (ms.signal_group == signal_group_id) {
                    move_state = ms;
                    return move_state;
                }
            }
            throw scheduling_exception("Could not find the movement_state with the required signal_group_id!");
        }
        else {
            throw scheduling_exception("SPaT is not found!");
        }
        return move_state;
    }
References OpenAPI::OAILanelet_info::getConnectingLaneletIds(), streets_vehicle_scheduler::vehicle_scheduler::intersection_info, and spat_ptr.
Referenced by schedule_evs().
get_final_green_buffer()
uint64_t streets_vehicle_scheduler::signalized_vehicle_scheduler::get_final_green_buffer () const
Get the final green buffer (ms).
Returns
uint64_t final green buffer.
Definition at line 408 of file signalized_vehicle_scheduler.cpp.
{
        return final_green_buffer;
    }
References final_green_buffer.
get_initial_green_buffer()
uint64_t streets_vehicle_scheduler::signalized_vehicle_scheduler::get_initial_green_buffer () const
Get the initial green buffer (ms).
Returns
uint64_t initial green buffer.
Definition at line 400 of file signalized_vehicle_scheduler.cpp.
{
        return initial_green_buffer;
    }
References initial_green_buffer.
get_spat()
std::shared_ptr< signal_phase_and_timing::spat > streets_vehicle_scheduler::signalized_vehicle_scheduler::get_spat () const
Get the spat object.
Returns
std::shared_ptr<signal_phase_and_timing::spat> spat object
Definition at line 412 of file signalized_vehicle_scheduler.cpp.
{
        return spat_ptr;
    }
References spat_ptr.
schedule_dvs()
void streets_vehicle_scheduler::signalized_vehicle_scheduler::schedule_dvs (const std::list< streets_vehicles::vehicle > & dvs, const std::shared_ptr< signalized_intersection_schedule > & schedule) const private
Estimate the intersection departure times (dt's) for all currently Departing Vehicle (DVs) based on kinematic vehicle information and intersection geometry. Method assumes empty intersection_schedule is passed in. Method will add vehicle_schedule(s) for each DV in the vector.
Parameters
dvs vector of unscheduled DVs.
schedule signalized_intersection_schedule to add DV scheduling information to.
Definition at line 46 of file signalized_vehicle_scheduler.cpp.
{
        for ( const auto &departing_veh : dvs ) {
            SPDLOG_DEBUG("Scheduling the departure time for DV with ID {0} .", departing_veh._id);
            // get link lane info
            OpenAPI::OAILanelet_info lane_info =  get_link_lanelet_info( departing_veh );
            // calculate clearance time in milliseconds
            uint64_t clearance_time = estimate_clearance_time( departing_veh );
            signalized_vehicle_schedule veh_sched;
            // set id
            veh_sched.v_id = departing_veh._id;
            // set et
            veh_sched.et = departing_veh._actual_et;
            // departure time is equal to current time plus clearance time for DVs
            veh_sched.dt =  schedule->timestamp + clearance_time;
            // set state
            veh_sched.state = departing_veh._cur_state;
            // set vehicle link id
            veh_sched.link_id =  departing_veh._link_id;
            // set vehicle entry lane id
            veh_sched.entry_lane =  departing_veh._entry_lane_id;
            SPDLOG_DEBUG("Added schedule for DV {0} with dt {1}.", veh_sched.v_id, veh_sched.dt);
            // add vehicle_schedule
            schedule->vehicle_schedules.push_back(veh_sched);
        }
    }
References streets_vehicle_scheduler::signalized_vehicle_schedule::dt, streets_vehicle_scheduler::vehicle_schedule::entry_lane, estimate_clearance_time(), streets_vehicle_scheduler::signalized_vehicle_schedule::et, streets_vehicle_scheduler::vehicle_scheduler::get_link_lanelet_info(), streets_vehicle_scheduler::vehicle_schedule::link_id, streets_vehicle_scheduler::signalized_vehicle_schedule::state, and streets_vehicle_scheduler::vehicle_schedule::v_id.
Referenced by schedule_vehicles().
schedule_evs()
void streets_vehicle_scheduler::signalized_vehicle_scheduler::schedule_evs (std::list< streets_vehicles::vehicle > & evs, const std::shared_ptr< signalized_intersection_schedule > & schedule) const private
Schedule all Entering Vehicles (EVs). Method first organizes all EVs into lists based on their entry lane. These list are ordered in ascending order with the vehicle closest to the intersection in a given lane being the first vehicle in that entry lanes vehicle list. Then, for each entry lane, an entering time (ET) for each EV in the entry lane is calculated sequentially starting from the first vehicle until in the list. ET is estimated based on the EV's earliest entering time (EET), its preceding vehicle's estimated ET, and the modifed spat.
Parameters
evs list of all EVs.
schedule signalized_intersection_schedule to add EV scheduling information to.
Definition at line 78 of file signalized_vehicle_scheduler.cpp.
{
        // Sort vehicles based on distance
        evs.sort(distance_comparator);
        // Create a map of entry lane id keys and list of EVs in each lane.
        std::unordered_map<int, std::list<streets_vehicles::vehicle>> vehicle_lane_map;
        for ( const auto &entry_lane : intersection_info->getEntryLanelets() ) {
            std::list<streets_vehicles::vehicle> vehicles_in_lane;
            for ( const auto &ev : evs ) {
                if ( ev._entry_lane_id == entry_lane.getId()) {
                    SPDLOG_DEBUG("Adding vehicle {0} to EVs list in entry lane {1}", ev._id, ev._entry_lane_id);
                    vehicles_in_lane.push_back(ev);
                }
            }
            if ( !vehicles_in_lane.empty()) {
                vehicles_in_lane.sort(distance_comparator);
                vehicle_lane_map.try_emplace( entry_lane.getId(), vehicles_in_lane );
            }
            else {
                SPDLOG_DEBUG("No EVs in lane {0}.", static_cast<int>(entry_lane.getId()) );
            }
        }
        if ( vehicle_lane_map.empty() ) {
            throw scheduling_exception("Map of vehicles to be scheduled is empty but list of EVs to be scheduled is not!");
        }
        for ( const auto &[entry_lane, evs_in_lane] : vehicle_lane_map ) {
            SPDLOG_DEBUG("Scheduling EVs from entry lane {0} ", entry_lane);
            // Find the last DV from the entry lane
            std::shared_ptr<signalized_vehicle_schedule> preceding_veh = nullptr;
            for (const auto &veh_sched : schedule->vehicle_schedules ) {
                if ( veh_sched.entry_lane == entry_lane && veh_sched.state == streets_vehicles::vehicle_state::DV && (preceding_veh == nullptr || veh_sched.et < preceding_veh->et)) {
                    preceding_veh = std::make_shared<signalized_vehicle_schedule>(veh_sched);
                }
            }
            // Find the entry lane object
            OpenAPI::OAILanelet_info entry_lane_info;
            for ( const auto &lane : intersection_info->getEntryLanelets() ){
                if ( lane.getId() == entry_lane ) {
                    entry_lane_info = lane;
                    break;
                }
            }
            SPDLOG_DEBUG("The entry lane id = {0}", entry_lane_info.getId());
            // Get the movement_state object that connects to this entry lane
            signal_phase_and_timing::movement_state move_state = find_movement_state_for_lane(entry_lane_info);
            SPDLOG_DEBUG("The signal group id for the link lanelets connected to entry lane {0} = {1}", entry_lane_info.getId(), move_state.signal_group);
            for (const auto &ev : evs_in_lane){
                signalized_vehicle_schedule sched;
                SPDLOG_DEBUG( "Estimating schedule for {0}.", ev._id);
                estimate_et(ev, preceding_veh, sched, move_state, schedule->timestamp);
                // Add vehicle schedule to the schedule list.
                schedule->vehicle_schedules.push_back(sched);
                // Update the preceding vehicle schedule.
                preceding_veh = std::make_shared<signalized_vehicle_schedule>(sched);
            }
            SPDLOG_DEBUG("All vehicles in lane {0} have been scheduled!", entry_lane);
        }
    }
References streets_vehicle_scheduler::distance_comparator(), streets_vehicles::DV, estimate_et(), find_movement_state_for_lane(), OpenAPI::OAILanelet_info::getId(), streets_vehicle_scheduler::vehicle_scheduler::intersection_info, and signal_phase_and_timing::movement_state::signal_group.
Referenced by schedule_vehicles().
schedule_vehicles()
void streets_vehicle_scheduler::signalized_vehicle_scheduler::schedule_vehicles (std::unordered_map< std::string, streets_vehicles::vehicle > & vehicles, std::shared_ptr< intersection_schedule > & schedule) override virtual
Method to schedule vehicles. Given and empty intersection_schedule shared pointer and a map of vehicles and vehicle ids. This method will populate the intersection schedule with a schedule for all vehicles in the vehicle map based on UC 3 scheduling logic to estimate vehicles' entering times to the intersection box based on the modified spat.
Parameters
vehicles A map of the vehicles to schedule, with vehicle id as keys
schedule A signalize_intersection schedule shared pointer populated with a vehicle schedule for all EVs and DVs in the map.
Implements streets_vehicle_scheduler::vehicle_scheduler.
Definition at line 5 of file signalized_vehicle_scheduler.cpp.
{
        try {
            auto schedule = std::dynamic_pointer_cast<signalized_intersection_schedule> (i_sched);
            if ( vehicles.empty() ) {
                SPDLOG_DEBUG("No vehicles to schedule.");
                return;
            }
            // Estimate Vehicles at common time
            estimate_vehicles_at_common_time( vehicles, schedule->timestamp);
            // Create vectors of DVs and EVs
            std::list<streets_vehicles::vehicle> DVs;
            std::list<streets_vehicles::vehicle> EVs;
            for ( const auto &[v_id, veh] : vehicles) {
                if ( veh._cur_state == streets_vehicles::vehicle_state::EV) {
                    EVs.push_back(veh);
                }
                else if ( veh._cur_state == streets_vehicles::vehicle_state::DV ) {
                    DVs.push_back(veh);
                }
            }
            SPDLOG_DEBUG("Number of Entering Vehicles (EVs) to schedule are : {0} ", EVs.size());
            // Schedule DVs
            if ( !DVs.empty() )
                schedule_dvs( DVs, schedule);
            // Schedule EVs
            if ( !EVs.empty() )
                schedule_evs( EVs, schedule);
        }
        catch ( const streets_service::streets_configuration_exception &ex ) {
            SPDLOG_ERROR("signalized scheduler failure: {0} ", ex.what());
        }
    }
References streets_vehicles::DV, streets_vehicle_scheduler::vehicle_scheduler::estimate_vehicles_at_common_time(), streets_vehicles::EV, schedule_dvs(), and schedule_evs().
set_final_green_buffer()
void streets_vehicle_scheduler::signalized_vehicle_scheduler::set_final_green_buffer (const uint64_t buffer)
Set the final green buffer (ms). This value is used to account for safety. The assumption is that no vehicle shall enter the intersection box after the end of a green phase minus the final green buffer. entering the intersection box at a green phase.
Parameters
buffer final green buffer in milliseconds.
Definition at line 404 of file signalized_vehicle_scheduler.cpp.
{
        final_green_buffer = buffer;
    }
References final_green_buffer.
set_initial_green_buffer()
void streets_vehicle_scheduler::signalized_vehicle_scheduler::set_initial_green_buffer (const uint64_t buffer)
Set the initial green buffer (ms). This value is used to account for the time it takes a vehicle before entering the intersection box at a green phase.
Parameters
buffer initial green buffer in milliseconds.
Definition at line 396 of file signalized_vehicle_scheduler.cpp.
{
        initial_green_buffer = buffer;
    }
References initial_green_buffer.
set_spat()
void streets_vehicle_scheduler::signalized_vehicle_scheduler::set_spat (std::shared_ptr< signal_phase_and_timing::spat > spat_info)
Set the spat object.
Parameters
spat_info signal_phase_and_timing::spat object.
Definition at line 416 of file signalized_vehicle_scheduler.cpp.
{
        spat_ptr = spat_info;
    }
References spat_ptr.
Member Data Documentation
final_green_buffer
uint64_t streets_vehicle_scheduler::signalized_vehicle_scheduler::final_green_buffer private
The configurable time interval at the end of a green phase in milliseconds that is considered for estimating vehicles' entering times. The latest possible entering time during a phase is set to the end of the green phase minus the final_green_buffer.
Definition at line 39 of file signalized_vehicle_scheduler.h.
Referenced by estimate_et(), get_final_green_buffer(), and set_final_green_buffer().
initial_green_buffer
uint64_t streets_vehicle_scheduler::signalized_vehicle_scheduler::initial_green_buffer private
The configurable time interval at the beginning of a green phase in milliseconds that is considered for estimating vehicles' entering times. The earliest possible entering time during a phase is set to the beginning of the green phase plus the initial_green_buffer.
Definition at line 32 of file signalized_vehicle_scheduler.h.
Referenced by estimate_et(), get_initial_green_buffer(), and set_initial_green_buffer().
spat_ptr
std::shared_ptr<signal_phase_and_timing::spat> streets_vehicle_scheduler::signalized_vehicle_scheduler::spat_ptr private
A shared pointer to the modified_spat.
Definition at line 24 of file signalized_vehicle_scheduler.h.
Referenced by find_movement_state_for_lane(), get_spat(), and set_spat().
The documentation for this class was generated from the following files:
streets_utils/streets_vehicle_scheduler/include/signalized_vehicle_scheduler.h
streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp