Carma-streets: traffic_signal_controller_service::tsc_service Class Reference
traffic_signal_controller_service::tsc_service Class Reference
#include <tsc_service.h>
Public Member Functions
tsc_service ()=default
~tsc_service ()
tsc_service (const tsc_service &)=delete
tsc_service & operator= (const tsc_service &)=delete
bool initialize () override
Method to initialize the tsc_service.
bool initialize_snmp_client (const std::string &server_ip, const int server_port, const std::string &community, const int snmp_version, const int timeout)
Initialize SNMP Client to make SNMP calls to Traffic Signal Controller.
bool initialize_tsc_state (const std::shared_ptr< snmp_client > _snmp_client_ptr)
Initialize TSC State object which uses an SNMP Client to query initial information from the Traffic Signal Controller including default phase sequence, phase timing information, and phase number to signal group mapping.
bool enable_spat () const
Method to enable spat using the TSC Service SNMP Client.
bool initialize_spat_worker (const std::string &udp_socket_ip, const int udp_socket_port, const int timeout, const bool use_tsc_timestamp)
Initialize SPaT Worker which is responsible for standing up UDP Socket Listener and consuming Traffic Signal Controller NTCIP UDP SPaT messages and updating the SPaT object using this information.
bool initialize_intersection_client ()
Initialize Intersection Client used to query Intersection Model REST API for Intersection Name and Intersection ID for SPaT message.
void initialize_spat (const std::string &intersection_name, const int intersection_id, const std::unordered_map< int, int > &phase_number_to_signal_group)
Initialize SPaT pointer with intersection name, intersection id and phase number to signal group mapping not provided in NTCIP UDP messages from TSC but required for interpretation.
void start () override
Method to start all threads included in the tsc_service.
void produce_spat_json () const
Method to receive UDP data from traffic signal controller and broadcast spat JSON data to the carma-streets kafka broker.
void produce_tsc_config_json () const
Method to receive traffic signal controller configuration information from the tsc_state and broadcast spat JSON data to the carma-streets kafka broker.
void consume_desired_phase_plan ()
void consume_phase_control_schedule ()
Thread callback function to run the phase control schedule Kafka consumer to consume phase control schedule JSON message.
void control_tsc_phases ()
Method to control phases on the Traffic Signal Controller by sending OMIT and HOLD commands constructed to follow the desired phase plan. Calls set_tsc_hold_and_omit_forceoff_call.
void set_tsc_hold_and_omit_forceoff_call ()
Method to set HOLD and OMIT, CALL, FORCEOFF on the Traffic signal controller accorording to the desired phase plan/phase control schedule.
void configure_snmp_cmd_logger () const
Method to configure spdlog::logger for logging snmp control commands into daily rotating log file.
void configure_veh_ped_call_logger () const
ethod to configure spdlog::logger for logging vehicle and pedestrian calls on the traffic signal controller into daily rotating csvlog file.
void log_spat_latency (int &count, uint64_t &spat_processing_time, uint64_t spat_time_stamp) const
Method to log spat latency comparing spat time stamp to current time. Calculates and average over 20 messages then resets count and spat_processing_time.
Public Member Functions inherited from streets_service::streets_service
streets_service ()=default
Constructor.
~streets_service ()
Destructor stop time_consumer kafka producer if not null.
streets_service (const streets_service &)=delete
streets_service (streets_service &&)=delete
streets_service & operator= (const streets_service &)=delete
streets_service & operator= (const streets_service &&)=delete
virtual bool initialize ()
Method to initialize services members, singletons, kafka consumers and producers and any other connections required for service. Classes that extend this streets_service need to override this method and call the streets_service::initialize() in the override method.
virtual void start ()
Method to start all threads needed for the Streets Service. This includes but is not limited to any threads to consume/produce message to kafka, or poll internal/external resources. Classes that extend this streets_service need to override this method and call the streets_service::start() in the override method.
Private Member Functions
FRIEND_TEST (tsc_service_test, test_tsc_control)
FRIEND_TEST (tsc_service_test, test_produce_tsc_config_json_timeout)
FRIEND_TEST (tsc_service_test, test_init_kafka_consumer_producer)
FRIEND_TEST (tsc_service_test, test_configure_snmp_cmd_logger)
FRIEND_TEST (tsc_service_test, test_configure_veh_ped_call_logger)
Private Attributes
std::shared_ptr< kafka_clients::kafka_producer_worker > spat_producer
Kafka producer for spat JSON.
std::shared_ptr< kafka_clients::kafka_producer_worker > tsc_config_producer
Kafka producer for tsc_configuration_state JSON.
std::shared_ptr< kafka_clients::kafka_consumer_worker > desired_phase_plan_consumer
std::shared_ptr< kafka_clients::kafka_consumer_worker > phase_control_schedule_consumer
std::shared_ptr< spat_worker > spat_worker_ptr
spat_worker contains udp_socket_listener and consumes UDP data packets and updates spat accordingly.
std::shared_ptr< tsc_state > tsc_state_ptr
tsc_state queries and stores traffic signal controller configurations including phase sequence, signal group (J2735) to phase number (NTCIP) maping and red clearance, yellow change, min/max green times.
std::shared_ptr< monitor_desired_phase_plan > monitor_dpp_ptr
Object used to process and store desired phase plan consumed from kafka,.
std::shared_ptr< snmp_client > snmp_client_ptr
snmp_client used for making SNMP GET and SET calls th NTCIP OIDs to set and retrieve information from the traffic signal controller.
std::shared_ptr< signal_phase_and_timing::spat > spat_ptr
Pointer to spat object which is updated based on received UDP messsages from the traffic signal controller and broadcast on the carma-streets kafka broker as a JSON message.
std::shared_ptr< streets_phase_control_schedule::streets_phase_control_schedule > phase_control_schedule_ptr
Point to phase control schedule object which is updated based on the received JSON message from MMITSS Road side processor.
std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_config_state_ptr
Pointer to tsc_configuration_state object which is traffic signal controller configuration information obtained from the tsc_state worker and broadcast on the carma-streets kafka broker as a JSON message.
std::shared_ptr< intersection_client > intersection_client_ptr
Pointer to intersection_client used to query intersection information including name and id from the intersection_model REST API.
std::shared_ptr< control_tsc_state > control_tsc_state_ptr_
Pointer to the control_tsc_state worker responsible for make snmp HOLD and OMIT calls to follow the desired phase plan.
int tsc_config_producer_counter_ = 0
int tsc_config_send_attempts = 1
SPAT_PROJECTION_MODE spat_proj_mode = SPAT_PROJECTION_MODE::NO_PROJECTION
std::queue< streets_snmp_cmd::snmp_cmd_struct > tsc_set_command_queue_
int control_tsc_state_sleep_dur_ = 0
bool enable_snmp_cmd_logging_ = false
bool use_mmitss_mrp = false
Static Private Attributes
static const std::string SNMP_COMMAND_LOGGER_NAME = "snmp_command"
static const std::string VEH_PED_CALL_LOGGER_NAME = "veh_ped_call"
Friends
class tsc_service_test
Additional Inherited Members
Protected Member Functions inherited from streets_service::streets_service
bool initialize_kafka_producer (const std::string &producer_topic, std::shared_ptr< kafka_clients::kafka_producer_worker > &producer)
Helper method to initialize Kafka producer for a given topic.
bool initialize_kafka_consumer (const std::string &consumer_topic, std::shared_ptr< kafka_clients::kafka_consumer_worker > &consumer)
Helper method to initialise Kafka consumer. NOTE: Will assign consumer group id as service_name.
std::string get_system_config (const char *config_name, const std::string &default_val) const noexcept
Returns string value of environment variable with given name. If no value is found, returns default.
void consume_time_sync_message () const
Method to consume continously consume time sync messages from Kafka topic and update streets_clock_singleton with received data.
std::string get_service_name () const
Returns service name set in configuration file.
bool is_simulation_mode () const
Returns boolean if service is currently configured to be in simulation_mode. This corresponsds to the value of the environment variable SIMULATION_MODE. Simulation mode indicates whether the streets_clock_singleton uses simulation time for kafka or system time.
std::shared_ptr< spdlog::logger > create_daily_logger (const std::string &name, const std::string &extension=".log", const std::string &pattern="[%Y-%m-%d %H:%M:%S.%e] %v", const spdlog::level::level_enum &level=spdlog::level::info) const
Method to create SPDLOG Daily rotating file logger. The logger is accessible by calling spdlog::get(name). The log files created by this logger will include data and time in name and will be stored in the LOGS_DIRECTORY set path.
Detailed Description
Definition at line 29 of file tsc_service.h.
Constructor & Destructor Documentation
tsc_service() [1/2]
traffic_signal_controller_service::tsc_service::tsc_service () default
~tsc_service()
traffic_signal_controller_service::tsc_service::~tsc_service ()
Definition at line 483 of file tsc_service.cpp.
    {
        if (spat_producer)
        {
            SPDLOG_WARN("Stopping spat producer!");
            spat_producer->stop();
        }
        if(tsc_config_producer)
        {
            SPDLOG_WARN("Stopping tsc config producer!");
            tsc_config_producer->stop();
        }
        if (desired_phase_plan_consumer) {
            SPDLOG_WARN("Stopping desired phase plan consumer!");
            desired_phase_plan_consumer->stop();
        }
        if (phase_control_schedule_consumer) {
            SPDLOG_WARN("Stopping phase control consumer!");
            phase_control_schedule_consumer->stop();
        }
    }
References desired_phase_plan_consumer, phase_control_schedule_consumer, spat_producer, and tsc_config_producer.
tsc_service() [2/2]
traffic_signal_controller_service::tsc_service::tsc_service (const tsc_service &) delete
Member Function Documentation
configure_snmp_cmd_logger()
void traffic_signal_controller_service::tsc_service::configure_snmp_cmd_logger () const
Method to configure spdlog::logger for logging snmp control commands into daily rotating log file.
Definition at line 408 of file tsc_service.cpp.
    {
        try {
            create_daily_logger(SNMP_COMMAND_LOGGER_NAME, ".log", "[%H:%M:%S:%e ] %v", spdlog::level::info );
        }
        catch (const spdlog::spdlog_ex& ex)
        {
            SPDLOG_ERROR( "SNMP Command Logger initialization failed: {0}!",ex.what());
        }
    }
References streets_service::streets_service::create_daily_logger(), and SNMP_COMMAND_LOGGER_NAME.
Referenced by initialize().
configure_veh_ped_call_logger()
void traffic_signal_controller_service::tsc_service::configure_veh_ped_call_logger () const
ethod to configure spdlog::logger for logging vehicle and pedestrian calls on the traffic signal controller into daily rotating csvlog file.
Definition at line 419 of file tsc_service.cpp.
    {
        try {
            auto veh_ped_call_logger = create_daily_logger(VEH_PED_CALL_LOGGER_NAME, ".csv", "%v", spdlog::level::info );
        }
        catch (const spdlog::spdlog_ex& ex)
        {
            SPDLOG_ERROR( "Vehicle Pedestrian Call Logger initialization failed: {0}!",ex.what());
        }
        // TODO: Figure out how to termine if a new file was created or an existing file appended and only write column headers on new files
        // veh_ped_call_logger->info("Timestamp (ms), Vehicle Calls (Signal Group ID), Pedestrian Calls (Signal Group ID)");
    }
References streets_service::streets_service::create_daily_logger(), and VEH_PED_CALL_LOGGER_NAME.
Referenced by initialize().
consume_desired_phase_plan()
void traffic_signal_controller_service::tsc_service::consume_desired_phase_plan ()
Definition at line 271 of file tsc_service.cpp.
{
        desired_phase_plan_consumer->subscribe();
        while (desired_phase_plan_consumer->is_running())
        {
            const std::string payload = desired_phase_plan_consumer->consume(1000);
            if (payload.length() != 0)
            {
                SPDLOG_DEBUG("Consumed: {0}", payload);
                std::scoped_lock<std::mutex> lck{dpp_mtx};
                monitor_dpp_ptr->update_desired_phase_plan(payload);
                // update command queue
                if(monitor_dpp_ptr->get_desired_phase_plan_ptr()){
                    // Send desired phase plan to control_tsc_state
                    std::scoped_lock<std::mutex> snmp_cmd_lck(snmp_cmd_queue_mtx);
                    control_tsc_state_ptr_->update_tsc_control_queue(monitor_dpp_ptr->get_desired_phase_plan_ptr(), tsc_set_command_queue_);
                }
            }
        }
    }
References control_tsc_state_ptr_, desired_phase_plan_consumer, traffic_signal_controller_service::dpp_mtx, monitor_dpp_ptr, traffic_signal_controller_service::snmp_cmd_queue_mtx, and tsc_set_command_queue_.
Referenced by start().
consume_phase_control_schedule()
void traffic_signal_controller_service::tsc_service::consume_phase_control_schedule ()
Thread callback function to run the phase control schedule Kafka consumer to consume phase control schedule JSON message.
control_tsc_phases()
void traffic_signal_controller_service::tsc_service::control_tsc_phases ()
Method to control phases on the Traffic Signal Controller by sending OMIT and HOLD commands constructed to follow the desired phase plan. Calls set_tsc_hold_and_omit_forceoff_call.
Definition at line 316 of file tsc_service.cpp.
    {
        SPDLOG_INFO("Starting TSC Control Phases");
        try
        {
            while(true)
            {
                SPDLOG_INFO("Iterate TSC Control Phases for time {0}", streets_clock_singleton::time_in_ms());
                set_tsc_hold_and_omit_forceoff_call();
                streets_clock_singleton::sleep_for(control_tsc_state_sleep_dur_);
            }
        }
        catch(const control_tsc_state_exception &e){
            SPDLOG_ERROR("Encountered exception : \n {0}", e.what());
            if(!tsc_set_command_queue_.empty())
            {
                SPDLOG_ERROR("Removing front command from queue :  {0}", tsc_set_command_queue_.front().get_cmd_info());
                std::scoped_lock<std::mutex> snmp_cmd_lck(snmp_cmd_queue_mtx);
                tsc_set_command_queue_.pop();
            }
        }
    }
References control_tsc_state_sleep_dur_, set_tsc_hold_and_omit_forceoff_call(), streets_service::streets_clock_singleton::sleep_for(), traffic_signal_controller_service::snmp_cmd_queue_mtx, streets_service::streets_clock_singleton::time_in_ms(), and tsc_set_command_queue_.
Referenced by start().
enable_spat()
bool traffic_signal_controller_service::tsc_service::enable_spat () const
Method to enable spat using the TSC Service SNMP Client.
Returns
true if SET operation is successful.
false if SET operation is not successful.
Definition at line 153 of file tsc_service.cpp.
{
        // Enable SPaT
        streets_snmp_cmd::snmp_response_obj enable_spat;
        enable_spat.type = streets_snmp_cmd::RESPONSE_TYPE::INTEGER;
        enable_spat.val_int = 2;
        if (!snmp_client_ptr->process_snmp_request(ntcip_oids::ENABLE_SPAT_OID, streets_snmp_cmd::REQUEST_TYPE::SET, enable_spat)){
            SPDLOG_ERROR("Failed to enable SPaT broadcasting on Traffic Signal Controller!");
            return false;
        }
        SPDLOG_DEBUG("Enabled UDP broadcasting of NTCIP SPaT data from TSC!");
        return true;
    }
References enable_spat(), ntcip_oids::ENABLE_SPAT_OID, streets_snmp_cmd::INTEGER, streets_snmp_cmd::SET, and snmp_client_ptr.
Referenced by enable_spat(), and initialize().
FRIEND_TEST() [1/5]
traffic_signal_controller_service::tsc_service::FRIEND_TEST (tsc_service_test , test_configure_snmp_cmd_logger) private
FRIEND_TEST() [2/5]
traffic_signal_controller_service::tsc_service::FRIEND_TEST (tsc_service_test , test_configure_veh_ped_call_logger) private
FRIEND_TEST() [3/5]
traffic_signal_controller_service::tsc_service::FRIEND_TEST (tsc_service_test , test_init_kafka_consumer_producer) private
FRIEND_TEST() [4/5]
traffic_signal_controller_service::tsc_service::FRIEND_TEST (tsc_service_test , test_produce_tsc_config_json_timeout) private
FRIEND_TEST() [5/5]
traffic_signal_controller_service::tsc_service::FRIEND_TEST (tsc_service_test , test_tsc_control) private
initialize()
bool traffic_signal_controller_service::tsc_service::initialize () override virtual
Method to initialize the tsc_service.
Returns
true if successful.
false if not successful.
Reimplemented from streets_service::streets_service.
Definition at line 8 of file tsc_service.cpp.
{
        if (!streets_service::initialize()) {
            return false;
        }
        try
        {
            // Initialize SNMP Client
            std::string target_ip = streets_configuration::get_string_config("target_ip");
            int target_port = streets_configuration::get_int_config("target_port");
            std::string community = streets_configuration::get_string_config("community");
            int snmp_version = streets_configuration::get_int_config("snmp_version");
            int timeout = streets_configuration::get_int_config("snmp_timeout");
            if (!snmp_client_ptr && !initialize_snmp_client(target_ip, target_port, community, snmp_version, timeout)) {
                SPDLOG_ERROR("Failed to initialize snmp_client!");
                return false;
            }
            //  Initialize tsc configuration state kafka producer
            std::string tsc_config_topic_name = streets_configuration::get_string_config("tsc_config_producer_topic");
            if (!tsc_config_producer && !initialize_kafka_producer( tsc_config_topic_name, tsc_config_producer)) {
                SPDLOG_ERROR("Failed to initialize kafka tsc_config_producer!");
                return false;
            }
            //Initialize TSC State
            if (!initialize_tsc_state(snmp_client_ptr)){
                SPDLOG_ERROR("Failed to initialize tsc state");
                return false;
            }
            tsc_config_state_ptr = tsc_state_ptr->get_tsc_config_state();
            // Intialize spat kafka producer
            std::string spat_topic_name = streets_configuration::get_string_config("spat_producer_topic");
            if ( !spat_producer && !initialize_kafka_producer( spat_topic_name, spat_producer) ) {
                SPDLOG_ERROR("Failed to initialize kafka spat_producer!");
                return false;
            }
            std::string dpp_consumer_topic = streets_configuration::get_string_config("desired_phase_plan_consumer_topic");
            // TODO: Remove if no longer necessary for TM/TSP MMITSS Integration
            // use_mmitss_mrp = streets_configuration::get_boolean_config("use_mmitss_mrp");
            // -----------------------------------------------------------------------------
            auto spat_projection_int = streets_configuration::get_int_config("spat_projection_mode");
            spat_proj_mode = spat_projection_mode_from_int(spat_projection_int);
            // TODO: Remove if no longer necessary for TM/TSP MMITSS Integration
            // Phase control schedule(PCS) consumer topic
            // std::string pcs_consumer_topic = streets_configuration::get_string_config("phase_control_schedule_consumer_topic");
            // -----------------------------------------------------------------------------
            // Initialize DPP consumer and monitor
            if ( spat_proj_mode == SPAT_PROJECTION_MODE::DPP_PROJECTION ) {
                if (!desired_phase_plan_consumer && !initialize_kafka_consumer( dpp_consumer_topic, desired_phase_plan_consumer)) {
                    SPDLOG_ERROR("Failed to initialize kafka desired_phase_plan_consumer!");
                    return false;
                }
                monitor_dpp_ptr = std::make_shared<monitor_desired_phase_plan>( snmp_client_ptr );
                control_tsc_state_sleep_dur_ = streets_configuration::get_int_config("control_tsc_state_sleep_duration");
                // Initialize control_tsc_state ptr
                control_tsc_state_ptr_ = std::make_shared<control_tsc_state>(snmp_client_ptr, tsc_state_ptr);
            }
            // TODO: Remove if no longer necessary for TM/TSP MMITSS Integration
            // if( SPAT_PROJECTION_MODE::MMITSS_PHASE_SCHEDULE)
            //     if ( !phase_control_schedule_consumer && !initialize_kafka_consumer(pcs_consumer_topic, phase_control_schedule_consumer)){
            //         SPDLOG_ERROR("Failed to initialize kafka phase_control_schedule_consumer!");
            //         return false;
            //     }
            //      //Initialize phase control schedule
            //     phase_control_schedule_ptr = std::make_shared<streets_phase_control_schedule::streets_phase_control_schedule>();
            //     // Initialize control_tsc_state ptr
            //     control_tsc_state_sleep_dur_ = streets_configuration::get_int_config("control_tsc_state_sleep_duration");
            //     control_tsc_state_ptr_ = std::make_shared<control_tsc_state>(snmp_client_ptr, tsc_state_ptr);
            // }
            // ------------------------------------------------------------------------------------------------------------------
            // Initialize spat_worker
            std::string socket_ip = streets_configuration::get_string_config("udp_socket_ip");
            int socket_port = streets_configuration::get_int_config("udp_socket_port");
            int socket_timeout = streets_configuration::get_int_config("socket_timeout");
            bool use_msg_timestamp =  streets_configuration::get_boolean_config("use_tsc_timestamp");
            enable_snmp_cmd_logging_ = streets_configuration::get_boolean_config("enable_snmp_cmd_logging");
            if (!initialize_spat_worker(socket_ip, socket_port, socket_timeout, use_msg_timestamp)) {
                SPDLOG_ERROR("Failed to initialize SPaT Worker");
                return false;
            }
            // Initialize intersection_client
            if (!initialize_intersection_client()) {
                SPDLOG_ERROR("Failed to initialize intersection client");
                return false;
            }
            // Add all phases to a single map
            auto all_phases = tsc_state_ptr->get_vehicle_phase_map();
            auto ped_phases = tsc_state_ptr->get_ped_phase_map();
            // Insert pedestrian phases into map of vehicle phases.
            all_phases.insert(ped_phases.begin(), ped_phases.end());
            // Initialize spat ptr
            initialize_spat(intersection_client_ptr->get_intersection_name(), intersection_client_ptr->get_intersection_id(),
                                all_phases);
            if (enable_snmp_cmd_logging_)
            {
                configure_snmp_cmd_logger();
                configure_veh_ped_call_logger();
            }
            if (is_simulation_mode()) {
                // Trigger spat broadcasting for EVC on startup.
                enable_spat();
            }
            SPDLOG_INFO("Traffic Signal Controller Service initialized successfully!");
            return true;
        }
        catch (const streets_configuration_exception &ex)
        {
            SPDLOG_ERROR("Signal Optimization Service Initialization failure: {0} ", ex.what());
            return false;
        }
    }
References configure_snmp_cmd_logger(), configure_veh_ped_call_logger(), control_tsc_state_ptr_, control_tsc_state_sleep_dur_, desired_phase_plan_consumer, traffic_signal_controller_service::DPP_PROJECTION, enable_snmp_cmd_logging_, enable_spat(), streets_service::streets_configuration::get_boolean_config(), streets_service::streets_configuration::get_int_config(), streets_service::streets_configuration::get_string_config(), streets_service::streets_service::initialize(), initialize_intersection_client(), streets_service::streets_service::initialize_kafka_consumer(), streets_service::streets_service::initialize_kafka_producer(), initialize_snmp_client(), initialize_spat(), initialize_spat_worker(), initialize_tsc_state(), intersection_client_ptr, streets_service::streets_service::is_simulation_mode(), monitor_dpp_ptr, snmp_client_ptr, spat_producer, spat_proj_mode, traffic_signal_controller_service::spat_projection_mode_from_int(), tsc_config_producer, tsc_config_state_ptr, and tsc_state_ptr.
Referenced by main().
initialize_intersection_client()
bool traffic_signal_controller_service::tsc_service::initialize_intersection_client ()
Initialize Intersection Client used to query Intersection Model REST API for Intersection Name and Intersection ID for SPaT message.
Returns
true if initialization is successful.
false if initialization is not successful.
Definition at line 179 of file tsc_service.cpp.
{
        intersection_client_ptr = std::make_shared<intersection_client>();
        if ( !intersection_client_ptr->request_intersection_info() ) {
            SPDLOG_ERROR("Failed to retrieve intersection information from intersection model!");
            return false;
        }
        SPDLOG_DEBUG("Intersection client initialized successfully!");
        return true;
    }
References intersection_client_ptr.
Referenced by initialize().
initialize_snmp_client()
bool traffic_signal_controller_service::tsc_service::initialize_snmp_client (const std::string & server_ip, const int server_port, const std::string & community, const int snmp_version, const int timeout)
Initialize SNMP Client to make SNMP calls to Traffic Signal Controller.
Parameters
server_ip of Traffic Signal Controller.
server_port of Traffic Signal Controller NTCIP Server.
community of SNMP communication used.
snmp_version of SNMP communication used.
timeout timeout micro seconds of SNMP connection
Returns
true if initialization is successful.
false if initialization is not successful.
Definition at line 131 of file tsc_service.cpp.
{
        try {
            snmp_client_ptr = std::make_shared<snmp_client>(server_ip, server_port, community, snmp_version, timeout);
            SPDLOG_DEBUG("SNMP Client initialized!");
            return true;
        }
        catch (const snmp_client_exception &e) {
            SPDLOG_ERROR("Exception encountered initializing snmp client : \n {0}", e.what());
            return false;
        }
    }
References snmp_client_ptr.
Referenced by initialize().
initialize_spat()
void traffic_signal_controller_service::tsc_service::initialize_spat (const std::string & intersection_name, const int intersection_id, const std::unordered_map< int, int > & phase_number_to_signal_group)
Initialize SPaT pointer with intersection name, intersection id and phase number to signal group mapping not provided in NTCIP UDP messages from TSC but required for interpretation.
Parameters
intersection_name J2735 Intersection name
intersection_id J2735 Intersection ID
phase_number_to_signal_group map of phase numbers (NTCIP) to signal groups provided by TSC State
Definition at line 189 of file tsc_service.cpp.
{
        spat_ptr =  std::make_shared<signal_phase_and_timing::spat>();
        spat_ptr->initialize_intersection( intersection_name, intersection_id, phase_number_to_signal_group);
    }
References spat_ptr.
Referenced by initialize().
initialize_spat_worker()
bool traffic_signal_controller_service::tsc_service::initialize_spat_worker (const std::string & udp_socket_ip, const int udp_socket_port, const int timeout, const bool use_tsc_timestamp)
Initialize SPaT Worker which is responsible for standing up UDP Socket Listener and consuming Traffic Signal Controller NTCIP UDP SPaT messages and updating the SPaT object using this information.
Parameters
udp_socket_ip IP of localhost where UDP packets will be received.
udp_socket_port Port of localhost where UDP packets will be received.
timeout Timeout in seconds for UDP client. UDP socket will throw an exception if no messages are receive for timeount window.
use_tsc_timestamp bool flag to indicate whether to use TSC timestamp provided in UDP packet.
Returns
true if initialization is successful.
false if initialization is not successful.
Definition at line 166 of file tsc_service.cpp.
{
        spat_worker_ptr = std::make_shared<spat_worker>(udp_socket_ip, udp_socket_port, timeout, use_tsc_timestamp);
        // HTTP request to update intersection information
        if (!spat_worker_ptr->initialize())
        {
            SPDLOG_ERROR("Failed to initialize spat worker!");
            return false;
        }
        SPDLOG_DEBUG("Spat worker initialized successfully!");
        return true;
    }
References spat_worker_ptr.
Referenced by initialize().
initialize_tsc_state()
bool traffic_signal_controller_service::tsc_service::initialize_tsc_state (const std::shared_ptr< snmp_client > _snmp_client_ptr)
Initialize TSC State object which uses an SNMP Client to query initial information from the Traffic Signal Controller including default phase sequence, phase timing information, and phase number to signal group mapping.
Parameters
_snmp_client_ptr SNMP client to use for querying initial information.
Returns
true if initialization is successful.
false if initialization is not successful.
Definition at line 144 of file tsc_service.cpp.
{
        tsc_state_ptr = std::make_shared<tsc_state>(_snmp_client_ptr );
        if ( !tsc_state_ptr->initialize() ){
            SPDLOG_ERROR("Failed to initialize tsc_state!");
            return false;
        }
        SPDLOG_DEBUG("TSC State initialized!");
        return true;
    }
References tsc_state_ptr.
Referenced by initialize().
log_spat_latency()
void traffic_signal_controller_service::tsc_service::log_spat_latency (int & count, uint64_t & spat_processing_time, uint64_t spat_time_stamp) const
Method to log spat latency comparing spat time stamp to current time. Calculates and average over 20 messages then resets count and spat_processing_time.
Parameters
count reference passed in and incremented on each subsequent call.
spat_processing_time cumulative spat latency from future event project. Calculated by comparing spat time stamp to current time and summing over 20 messages.
spat_time_stamp the timestamp of the most recent processed spat message.
Definition at line 431 of file tsc_service.cpp.
{
        // Calculate and average spat processing time over 20 messages sent
        if (count <= 20 ) {
            uint64_t timestamp = streets_clock_singleton::time_in_ms();
            spat_processing_time += timestamp - spat_time_stamp;
            count++;
        }
        // Log result at 20 and clear counts
        if (count >= 20 ) {
            double total_processing_time = ((double)(spat_processing_time))/20.0;
            SPDLOG_INFO("SPat average processing time over 20 messages is {0} ms and total processing time for 20 messages is {1} ms!", total_processing_time, spat_processing_time);
            spat_processing_time = 0;
            count = 0;
        }
    }
References simulate_bsm::count, streets_service::streets_clock_singleton::time_in_ms(), and simulate_mobilityoperation::timestamp.
Referenced by produce_spat_json().
operator=()
tsc_service & traffic_signal_controller_service::tsc_service::operator= (const tsc_service &) delete
produce_spat_json()
void traffic_signal_controller_service::tsc_service::produce_spat_json () const
Method to receive UDP data from traffic signal controller and broadcast spat JSON data to the carma-streets kafka broker.
Definition at line 196 of file tsc_service.cpp.
{
        try {
            int count = 0;
            uint64_t spat_processing_time = 0;
            SPDLOG_DEBUG("Starting SPaT producer");
            while(spat_worker_ptr && tsc_state_ptr && spat_producer) {
                try {
                    spat_worker_ptr->receive_spat(spat_ptr);
                    SPDLOG_DEBUG("Current SPaT : {0} ", spat_ptr->toJson());
                    switch (spat_proj_mode)
                    {
                        case SPAT_PROJECTION_MODE::FIXED_TIMING_PROJECTION: {
                            tsc_state_ptr->add_future_movement_events(spat_ptr);
                            break;
                        }
                        case SPAT_PROJECTION_MODE::DPP_PROJECTION : {
                            std::scoped_lock<std::mutex> lck{dpp_mtx};
                            // throws desired phase plan exception when no previous green information present
                            monitor_dpp_ptr->update_spat_future_movement_events(spat_ptr, tsc_state_ptr);
                            break;
                        }
                        default: {
                            // Poll and log vehicle and pedestrian call information every 10 spat messages or at 10 Hz
                            if ( count%10 == 0) {
                                tsc_state_ptr->poll_vehicle_pedestrian_calls();
                                if(auto logger = spdlog::get(VEH_PED_CALL_LOGGER_NAME); logger != nullptr ){
                                    logger->info("{0}, {1}, {2}", streets_clock_singleton::time_in_ms(),
                                                    tsc_state_ptr->vector_to_string(tsc_state_ptr->get_vehicle_calls()),
                                                    tsc_state_ptr->vector_to_string(tsc_state_ptr->get_pedestrian_calls())
                                                );
                                }
                            }
                        }
                    }
                    if (spat_ptr && spat_producer) {
                        spat_producer->send(spat_ptr->toJson());
                        // No utility in calculating spat latency in simulation mode
                        if ( !this->is_simulation_mode() ) {
                           log_spat_latency(count, spat_processing_time, spat_ptr->get_intersection().get_epoch_timestamp()) ;
                        }
                    }
                }
                catch( const signal_phase_and_timing::signal_phase_and_timing_exception &e ) {
                    SPDLOG_ERROR("Encountered exception, spat not published : \n {0}", e.what());
                }
                catch( const traffic_signal_controller_service::monitor_desired_phase_plan_exception &e) {
                    SPDLOG_ERROR("Could not update movement events, spat not published. Encountered exception : \n {0}", e.what());
                }
                catch(const traffic_signal_controller_service::monitor_states_exception &e){
                    SPDLOG_ERROR("Could not update movement events, spat not published. Encountered exception : \n {0}", e.what());
                }
            }
            SPDLOG_WARN("Stopping produce_spat_json! Are pointers null: spat_worker {0}, spat_producer {1}, tsc_state {2}",
                spat_worker_ptr == nullptr, spat_ptr == nullptr, tsc_state_ptr == nullptr);
        }
        catch( const udp_socket_listener_exception &e) {
            SPDLOG_ERROR("Encountered exception : \n {0}", e.what());
        }
    }
References simulate_bsm::count, traffic_signal_controller_service::dpp_mtx, traffic_signal_controller_service::DPP_PROJECTION, traffic_signal_controller_service::FIXED_TIMING_PROJECTION, streets_service::streets_service::is_simulation_mode(), log_spat_latency(), monitor_dpp_ptr, spat_producer, spat_proj_mode, spat_ptr, spat_worker_ptr, streets_service::streets_clock_singleton::time_in_ms(), tsc_state_ptr, and VEH_PED_CALL_LOGGER_NAME.
Referenced by start().
produce_tsc_config_json()
void traffic_signal_controller_service::tsc_service::produce_tsc_config_json () const
Method to receive traffic signal controller configuration information from the tsc_state and broadcast spat JSON data to the carma-streets kafka broker.
Definition at line 257 of file tsc_service.cpp.
{
        try {
            while(tsc_config_producer->is_running() && tsc_config_state_ptr )
            {
                tsc_config_producer->send(tsc_config_state_ptr->toJson());
                streets_clock_singleton::sleep_for(10000); // Sleep for 10 second between publish
            }
        }
        catch( const streets_tsc_configuration::tsc_configuration_state_exception &e) {
            SPDLOG_ERROR("Encountered exception : \n {0}", e.what());
        }
    }
References streets_service::streets_clock_singleton::sleep_for(), tsc_config_producer, and tsc_config_state_ptr.
Referenced by start().
set_tsc_hold_and_omit_forceoff_call()
void traffic_signal_controller_service::tsc_service::set_tsc_hold_and_omit_forceoff_call ()
Method to set HOLD and OMIT, CALL, FORCEOFF on the Traffic signal controller accorording to the desired phase plan/phase control schedule.
Definition at line 339 of file tsc_service.cpp.
    {
        if(control_tsc_state_ptr_ && !tsc_set_command_queue_.empty())
        {
            //Clear all phase controls from the traffic signal controller
            SPDLOG_DEBUG("Clear all phase controls from TSC!");
            control_tsc_state_ptr_->run_clear_all_snmp_commands();
        }
        while(!tsc_set_command_queue_.empty())
        {
            auto current_command = tsc_set_command_queue_.front();
            SPDLOG_DEBUG("Checking if front command {0} is expired", current_command.get_cmd_info());
            //Check if event is expired
            long duration = current_command.start_time_ - streets_clock_singleton::time_in_ms();
            if(duration < 0){
                throw control_tsc_state_exception("SNMP set command is expired! Start time was "
                    + std::to_string(current_command.start_time_) + " and current time is "
                    + std::to_string(streets_clock_singleton::time_in_ms() ) + ".");
            }
            SPDLOG_DEBUG("Sleeping for {0}ms.", duration);
            streets_clock_singleton::sleep_for(duration);
            //After sleep duration, check the snmp queue again. If empty, stop the current command execution
            if(tsc_set_command_queue_.empty())
            {
                SPDLOG_DEBUG("SNMP command queue is empty, stop the current command execution: {0}", current_command.get_cmd_info());
                break;
            }
            //Check if queue commands has been updated
            else if (tsc_set_command_queue_.front().get_cmd_info() != current_command.get_cmd_info())
            {
                SPDLOG_DEBUG("SNMP command queue is updated with new schedule, stop the current command execution: {0}", current_command.get_cmd_info());
                break;
            }
            if(!control_tsc_state_ptr_)
            {
                throw control_tsc_state_exception("Control TSC state is not initialized.");
            }
            //Checking all the commands from the queue. If there are any commands executed at the same time as the current_command, and execute these commands now.
            while (!tsc_set_command_queue_.empty())
            {
                auto command_to_execute = tsc_set_command_queue_.front();
                if(command_to_execute.start_time_ == current_command.start_time_)
                {
                    if(control_tsc_state_ptr_ && !control_tsc_state_ptr_->run_snmp_cmd_set_request(command_to_execute))
                    {
                        throw control_tsc_state_exception("Could not set state for movement group in desired phase plan/phase control schedule.");
                    }
                    // Log command info sent
                    SPDLOG_INFO(command_to_execute.get_cmd_info());
                    if ( enable_snmp_cmd_logging_ ){
                        if(auto logger = spdlog::get("snmp_cmd_logger"); logger != nullptr ){
                            logger->info( command_to_execute.get_cmd_info());
                        }
                    }
                    //SNMP command Queue has no update nor has been cleared, pop the existing front command.
                    std::scoped_lock<std::mutex> snmp_cmd_lck(snmp_cmd_queue_mtx);
                    tsc_set_command_queue_.pop();
                }
                else
                {
                    break;
                }
            }
        }
    }
References control_tsc_state_ptr_, enable_snmp_cmd_logging_, streets_service::streets_clock_singleton::sleep_for(), traffic_signal_controller_service::snmp_cmd_queue_mtx, streets_service::streets_clock_singleton::time_in_ms(), to_string(), and tsc_set_command_queue_.
Referenced by control_tsc_phases().
start()
void traffic_signal_controller_service::tsc_service::start () override virtual
Method to start all threads included in the tsc_service.
Reimplemented from streets_service::streets_service.
Definition at line 448 of file tsc_service.cpp.
{
        streets_service::streets_service::start();
        SPDLOG_INFO("Starting TSC Service threads");
        std::thread tsc_config_thread(&tsc_service::produce_tsc_config_json, this);
        std::thread spat_t(&tsc_service::produce_spat_json, this);
        if ( spat_proj_mode == SPAT_PROJECTION_MODE::DPP_PROJECTION ) {
            std::thread desired_phase_plan_t(&tsc_service::consume_desired_phase_plan, this);
            SPDLOG_DEBUG("Thread joined to consume desired phase plan generated by carma-streets SO service.");
            desired_phase_plan_t.join();
            // Run tsc control phases
            std::thread control_phases_t(&tsc_service::control_tsc_phases, this);
            control_phases_t.join();
        }
        // TODO: Remove if no longer necessary for TM/TSP MMITSS Integration
        // An indicator to control whether launching a thread to consume carma-streets internal desired phase plan generated by singal optimization (SO) service
        // or a thread to consume MMITSS external phase control schedule generated by MRP (https://github.com/mmitss/mmitss-az)
        // if ( spat_proj_mode == SPAT_PROJECTION_MODE::MMITSS_PHASE_SCHEDULE ) {
        //     std::thread consume_phase_control_schedule_t(&tsc_service::consume_phase_control_schedule, this);
        //     SPDLOG_DEBUG("Thread joined to consume phase control schedule generated by MRP.");
        //     consume_phase_control_schedule_t.join();
        //     // Run tsc control phases
        //     std::thread control_phases_t(&tsc_service::control_tsc_phases, this);
        //     control_phases_t.join();
        // }
        // ---------------------------------------------------------------------------------------------------------------
        // Run threads as joint so that they dont overlap execution
        tsc_config_thread.join();
        spat_t.join();
    }
References consume_desired_phase_plan(), control_tsc_phases(), traffic_signal_controller_service::DPP_PROJECTION, produce_spat_json(), produce_tsc_config_json(), spat_proj_mode, and streets_service::streets_service::start().
Referenced by main().
Friends And Related Function Documentation
tsc_service_test
friend class tsc_service_test friend
Definition at line 121 of file tsc_service.h.
Member Data Documentation
control_tsc_state_ptr_
std::shared_ptr<control_tsc_state> traffic_signal_controller_service::tsc_service::control_tsc_state_ptr_ private
Pointer to the control_tsc_state worker responsible for make snmp HOLD and OMIT calls to follow the desired phase plan.
Definition at line 97 of file tsc_service.h.
Referenced by consume_desired_phase_plan(), initialize(), and set_tsc_hold_and_omit_forceoff_call().
control_tsc_state_sleep_dur_
int traffic_signal_controller_service::tsc_service::control_tsc_state_sleep_dur_ = 0 private
Definition at line 111 of file tsc_service.h.
Referenced by control_tsc_phases(), and initialize().
desired_phase_plan_consumer
std::shared_ptr<kafka_clients::kafka_consumer_worker> traffic_signal_controller_service::tsc_service::desired_phase_plan_consumer private
Definition at line 42 of file tsc_service.h.
Referenced by ~tsc_service(), consume_desired_phase_plan(), and initialize().
enable_snmp_cmd_logging_
bool traffic_signal_controller_service::tsc_service::enable_snmp_cmd_logging_ = false private
Definition at line 114 of file tsc_service.h.
Referenced by initialize(), and set_tsc_hold_and_omit_forceoff_call().
intersection_client_ptr
std::shared_ptr<intersection_client> traffic_signal_controller_service::tsc_service::intersection_client_ptr private
Pointer to intersection_client used to query intersection information including name and id from the intersection_model REST API.
Definition at line 91 of file tsc_service.h.
Referenced by initialize(), and initialize_intersection_client().
monitor_dpp_ptr
std::shared_ptr<monitor_desired_phase_plan> traffic_signal_controller_service::tsc_service::monitor_dpp_ptr private
Object used to process and store desired phase plan consumed from kafka,.
Definition at line 63 of file tsc_service.h.
Referenced by consume_desired_phase_plan(), initialize(), and produce_spat_json().
phase_control_schedule_consumer
std::shared_ptr<kafka_clients::kafka_consumer_worker> traffic_signal_controller_service::tsc_service::phase_control_schedule_consumer private
Definition at line 47 of file tsc_service.h.
Referenced by ~tsc_service().
phase_control_schedule_ptr
std::shared_ptr<streets_phase_control_schedule::streets_phase_control_schedule> traffic_signal_controller_service::tsc_service::phase_control_schedule_ptr private
Point to phase control schedule object which is updated based on the received JSON message from MMITSS Road side processor.
Definition at line 79 of file tsc_service.h.
snmp_client_ptr
std::shared_ptr<snmp_client> traffic_signal_controller_service::tsc_service::snmp_client_ptr private
snmp_client used for making SNMP GET and SET calls th NTCIP OIDs to set and retrieve information from the traffic signal controller.
Definition at line 68 of file tsc_service.h.
Referenced by enable_spat(), initialize(), and initialize_snmp_client().
SNMP_COMMAND_LOGGER_NAME
const std::string traffic_signal_controller_service::tsc_service::SNMP_COMMAND_LOGGER_NAME = "snmp_command" inline static private
Definition at line 116 of file tsc_service.h.
Referenced by configure_snmp_cmd_logger().
spat_producer
std::shared_ptr<kafka_clients::kafka_producer_worker> traffic_signal_controller_service::tsc_service::spat_producer private
Kafka producer for spat JSON.
Definition at line 34 of file tsc_service.h.
Referenced by ~tsc_service(), initialize(), and produce_spat_json().
spat_proj_mode
SPAT_PROJECTION_MODE traffic_signal_controller_service::tsc_service::spat_proj_mode = SPAT_PROJECTION_MODE::NO_PROJECTION private
Definition at line 105 of file tsc_service.h.
Referenced by initialize(), produce_spat_json(), and start().
spat_ptr
std::shared_ptr<signal_phase_and_timing::spat> traffic_signal_controller_service::tsc_service::spat_ptr private
Pointer to spat object which is updated based on received UDP messsages from the traffic signal controller and broadcast on the carma-streets kafka broker as a JSON message.
Definition at line 74 of file tsc_service.h.
Referenced by initialize_spat(), and produce_spat_json().
spat_worker_ptr
std::shared_ptr<spat_worker> traffic_signal_controller_service::tsc_service::spat_worker_ptr private
spat_worker contains udp_socket_listener and consumes UDP data packets and updates spat accordingly.
Definition at line 53 of file tsc_service.h.
Referenced by initialize_spat_worker(), and produce_spat_json().
tsc_config_producer
std::shared_ptr<kafka_clients::kafka_producer_worker> traffic_signal_controller_service::tsc_service::tsc_config_producer private
Kafka producer for tsc_configuration_state JSON.
Definition at line 38 of file tsc_service.h.
Referenced by ~tsc_service(), initialize(), and produce_tsc_config_json().
tsc_config_producer_counter_
int traffic_signal_controller_service::tsc_service::tsc_config_producer_counter_ = 0 private
Definition at line 100 of file tsc_service.h.
tsc_config_send_attempts
int traffic_signal_controller_service::tsc_service::tsc_config_send_attempts = 1 private
Definition at line 102 of file tsc_service.h.
tsc_config_state_ptr
std::shared_ptr<streets_tsc_configuration::tsc_configuration_state> traffic_signal_controller_service::tsc_service::tsc_config_state_ptr private
Pointer to tsc_configuration_state object which is traffic signal controller configuration information obtained from the tsc_state worker and broadcast on the carma-streets kafka broker as a JSON message.
Definition at line 85 of file tsc_service.h.
Referenced by initialize(), and produce_tsc_config_json().
tsc_set_command_queue_
std::queue<streets_snmp_cmd::snmp_cmd_struct> traffic_signal_controller_service::tsc_service::tsc_set_command_queue_ private
Definition at line 108 of file tsc_service.h.
Referenced by consume_desired_phase_plan(), control_tsc_phases(), and set_tsc_hold_and_omit_forceoff_call().
tsc_state_ptr
std::shared_ptr<tsc_state> traffic_signal_controller_service::tsc_service::tsc_state_ptr private
tsc_state queries and stores traffic signal controller configurations including phase sequence, signal group (J2735) to phase number (NTCIP) maping and red clearance, yellow change, min/max green times.
Definition at line 59 of file tsc_service.h.
Referenced by initialize(), initialize_tsc_state(), and produce_spat_json().
use_mmitss_mrp
bool traffic_signal_controller_service::tsc_service::use_mmitss_mrp = false private
Definition at line 133 of file tsc_service.h.
VEH_PED_CALL_LOGGER_NAME
const std::string traffic_signal_controller_service::tsc_service::VEH_PED_CALL_LOGGER_NAME = "veh_ped_call" inline static private
Definition at line 118 of file tsc_service.h.
Referenced by configure_veh_ped_call_logger(), and produce_spat_json().
The documentation for this class was generated from the following files:
tsc_client_service/include/tsc_service.h
tsc_client_service/src/tsc_service.cpp