Carma-streets: signal_opt_service::signal_opt_service Class Reference
signal_opt_service::signal_opt_service Class Reference
#include <signal_opt_service.h>
Public Member Functions
signal_opt_service ()=default
Initialize the consumer and producer configurations.
~signal_opt_service ()
stop the consumer and producer
bool initialize ()
Initialize the consumer and producer configurations.
void start ()
Create threads and consume messages.
void consume_spat (const std::shared_ptr< kafka_clients::kafka_consumer_worker > spat_consumer, const std::shared_ptr< signal_phase_and_timing::spat > _spat_ptr) const
Method to consume SPaT JSON from kafka consumer and update spat pointer.
void consume_vsi (const std::shared_ptr< kafka_clients::kafka_consumer_worker > vsi_consumer, const std::shared_ptr< streets_vehicles::vehicle_list > _vehicle_list_ptr) const
Method to consume vehicle status and intent JSON from kafka consumer and vehicle list pointer.
void consume_tsc_config (const std::shared_ptr< kafka_clients::kafka_consumer_worker > tsc_config_consumer, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > _tsc_config_ptr) const
Method to consume a single TSC Configuration JSON message from kafka and update the tsc configuration state pointer.
void produce_dpp (const std::shared_ptr< kafka_clients::kafka_producer_worker > dpp_producer, const std::shared_ptr< OpenAPI::OAIIntersection_info > _intersection_info_ptr, const std::shared_ptr< streets_vehicles::vehicle_list > _vehicle_list_ptr, const std::shared_ptr< signal_phase_and_timing::spat > _spat_ptr, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > _tsc_config_ptr, const std::shared_ptr< streets_signal_optimization::movement_groups > _movement_groups_ptr, const streets_signal_optimization::streets_desired_phase_plan_generator_configuration &_dpp_config, const int &_so_sleep_time) const
Method to produce desired phase plan Json to kafka.
void populate_movement_groups (std::shared_ptr< streets_signal_optimization::movement_groups > _groups, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_config) const
Method to use the tsc_config_state pointer from the signal_opt_message_worker to populate movement_groups pointer.
bool update_intersection_info (unsigned long sleep_millisecs, unsigned long int_client_request_attempts) const
Updating the intersection info.
void configure_csv_logger () const
Method to configure spdlog::logger for logging signal optimization metrics into daily rotating csv file.
void read_configuration_params ()
Method for reading the configuration parameters from manifest.json.
void remove_signal_groups (const std::shared_ptr< streets_signal_optimization::movement_groups > &movement_groups, const std::vector< uint > &rm_signal_groups) const
Remove list of provided signal groups from movement groups considered for signal optmization.
Private Member Functions
FRIEND_TEST (signal_opt_service, test_produce_dpp)
FRIEND_TEST (signal_opt_service, test_read_configuration_params)
Private Attributes
std::shared_ptr< signal_opt_messages_worker > _so_msgs_worker_ptr
std::shared_ptr< signal_opt_processing_worker > _so_processing_worker_ptr
std::string _bootstrap_server
std::string _spat_group_id
std::string _spat_topic_name
std::string _vsi_group_id
std::string _vsi_topic_name
std::string _tsc_config_group_id
std::string _tsc_config_topic_name
std::string _dpp_topic_name
std::string _so_log_path
std::string _so_log_filename
int _exp_delta
bool enable_so_logging = false
int so_sleep_time
uint64_t _time_to_yellow
std::vector< uint > ignore_signal_groups
std::shared_ptr< kafka_clients::kafka_consumer_worker > _vsi_consumer
std::shared_ptr< kafka_clients::kafka_consumer_worker > _spat_consumer
std::shared_ptr< kafka_clients::kafka_consumer_worker > _tsc_config_consumer
std::shared_ptr< kafka_clients::kafka_producer_worker > _dpp_producer
streets_signal_optimization::streets_desired_phase_plan_generator_configuration dpp_config
std::shared_ptr< streets_signal_optimization::movement_groups > movement_groups_ptr
std::shared_ptr< OpenAPI::OAIIntersection_info > intersection_info_ptr
std::shared_ptr< signal_phase_and_timing::spat > spat_ptr
std::shared_ptr< streets_vehicles::vehicle_list > vehicle_list_ptr
std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_configuration_ptr
Detailed Description
Definition at line 13 of file signal_opt_service.h.
Constructor & Destructor Documentation
signal_opt_service()
signal_opt_service::signal_opt_service::signal_opt_service () default
Initialize the consumer and producer configurations.
~signal_opt_service()
signal_opt_service::signal_opt_service::~signal_opt_service ()
stop the consumer and producer
Definition at line 456 of file signal_opt_service.cpp.
    {
        if (_spat_consumer)
        {
            _spat_consumer->stop();
        }
        if (_vsi_consumer)
        {
            _vsi_consumer->stop();
        }
        if (_tsc_config_consumer)
        {
            _tsc_config_consumer->stop();
        }
        if (_dpp_producer)
        {
            _dpp_producer->stop();
        }
    }
Member Function Documentation
configure_csv_logger()
void signal_opt_service::signal_opt_service::configure_csv_logger () const
Method to configure spdlog::logger for logging signal optimization metrics into daily rotating csv file.
Definition at line 361 of file signal_opt_service.cpp.
    {
        try{
            SPDLOG_INFO("csv log path: {0}", _so_log_path + _so_log_filename + ".csv");
            auto csv_logger = spdlog::daily_logger_mt<spdlog::async_factory>(
                "so_csv_logger",  // logger name
                _so_log_path + _so_log_filename +".csv",  // log file name and path
                23, // hours to rotate
                59 // minutes to rotate
                );
            // Only log log statement content
            csv_logger->set_pattern("%v");
            csv_logger->set_level(spdlog::level::info);
            csv_logger->flush_on(spdlog::level::info);
        }
        catch (const spdlog::spdlog_ex& ex)
        {
            spdlog::error( "Log initialization failed: {0}!",ex.what());
        }
    }
consume_spat()
void signal_opt_service::signal_opt_service::consume_spat (const std::shared_ptr< kafka_clients::kafka_consumer_worker > spat_consumer, const std::shared_ptr< signal_phase_and_timing::spat > _spat_ptr) const
Method to consume SPaT JSON from kafka consumer and update spat pointer.
Parameters
spat_consumer shared pointer to kafka consumer.
_spat_ptr shared pointer to spat object.
Definition at line 108 of file signal_opt_service.cpp.
{
        while( spat_consumer->is_running()) {
            const std::string payload = spat_consumer->consume(1000);
            if (!payload.empty()) {
                bool update = _so_msgs_worker_ptr->update_spat(payload,_spat_ptr);
                if ( !update ){
                    SPDLOG_CRITICAL("Failed to update SPaT with update {0}!", payload);
                }
            }
        }
    }
consume_tsc_config()
void signal_opt_service::signal_opt_service::consume_tsc_config (const std::shared_ptr< kafka_clients::kafka_consumer_worker > tsc_config_consumer, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > _tsc_config_ptr) const
Method to consume a single TSC Configuration JSON message from kafka and update the tsc configuration state pointer.
Parameters
tsc_config_consumer shared pointer to kafka consumer.
_tsc_config_ptr shared pointer to tsc configuration state pointer.
Definition at line 134 of file signal_opt_service.cpp.
{
        while( tsc_config_consumer->is_running()) {
            const std::string payload = tsc_config_consumer->consume(1000);
            if (!payload.empty()) {
                bool update = _so_msgs_worker_ptr->update_tsc_config(payload,_tsc_config_ptr);
                if (!update) {
                    SPDLOG_CRITICAL("Failed to update TSC Configuration with update {0}!", payload);
                }else {
                    // Stop consumer after receiving tsc_configuration information
                    SPDLOG_INFO("TSC Configuration sucessfully loaded : \n{0}", payload );
                    tsc_config_consumer->stop();
                    break;
                }
            }
        }
    }
consume_vsi()
void signal_opt_service::signal_opt_service::consume_vsi (const std::shared_ptr< kafka_clients::kafka_consumer_worker > vsi_consumer, const std::shared_ptr< streets_vehicles::vehicle_list > _vehicle_list_ptr) const
Method to consume vehicle status and intent JSON from kafka consumer and vehicle list pointer.
Parameters
vsi_consumer shared pointer to kafka consumer.
_vehicle_list_ptr shared pointer to vehicle list object.
Definition at line 121 of file signal_opt_service.cpp.
{
        while( vsi_consumer->is_running()) {
            const std::string payload = vsi_consumer->consume(1000);
            if (!payload.empty()) {
                bool update = _so_msgs_worker_ptr->update_vehicle_list(payload,_vehicle_list_ptr);
                if (!update) {
                    SPDLOG_CRITICAL("Failed to update Vehicle List with update {0}!", payload);
                }
            }
        }
    }
FRIEND_TEST() [1/2]
signal_opt_service::signal_opt_service::FRIEND_TEST (signal_opt_service , test_produce_dpp) private
FRIEND_TEST() [2/2]
signal_opt_service::signal_opt_service::FRIEND_TEST (signal_opt_service , test_read_configuration_params) private
initialize()
bool signal_opt_service::signal_opt_service::initialize ()
Initialize the consumer and producer configurations.
Definition at line 5 of file signal_opt_service.cpp.
    {
        try
        {
            read_configuration_params();
            _so_msgs_worker_ptr = std::make_shared<signal_opt_messages_worker>();
            _so_processing_worker_ptr = std::make_shared<signal_opt_processing_worker>();
            movement_groups_ptr = std::make_shared<streets_signal_optimization::movement_groups>();
            vehicle_list_ptr = std::make_shared<streets_vehicles::vehicle_list>();
            auto processor = std::make_shared<streets_vehicles::signalized_status_intent_processor>();
            processor->set_timeout(_exp_delta);
            vehicle_list_ptr->set_processor(processor);
            intersection_info_ptr = std::make_shared<OpenAPI::OAIIntersection_info>();
            spat_ptr = std::make_shared<signal_phase_and_timing::spat>();
            tsc_configuration_ptr = std::make_shared<streets_tsc_configuration::tsc_configuration_state>();
            // Kafka config
            auto client = std::make_unique<kafka_clients::kafka_client>();
            _spat_consumer = client->create_consumer(_bootstrap_server, _spat_topic_name, _spat_group_id);
            _vsi_consumer = client->create_consumer(_bootstrap_server, _vsi_topic_name, _vsi_group_id);
            _tsc_config_consumer = client->create_consumer(_bootstrap_server, _tsc_config_topic_name, _tsc_config_group_id);
            _dpp_producer = client->create_producer(_bootstrap_server, _dpp_topic_name);
            if (!_spat_consumer->init() || !_vsi_consumer->init() || !_tsc_config_consumer->init() )
            {
                SPDLOG_CRITICAL("kafka consumers ( _spat_consumer, _tsc_config_consumer  or _vsi_consumer ) initialize error!");
                return false;
            }
            else
            {
                _spat_consumer->subscribe();
                _vsi_consumer->subscribe();
                _tsc_config_consumer->subscribe();
                if (!_spat_consumer->is_running() || !_vsi_consumer->is_running() || !_tsc_config_consumer->is_running())
                {
                    SPDLOG_CRITICAL("kafka consumers ( _spat_consumer, _tsc_config_consumer or _vsi_consumer) is not running!");
                    return false;
                }
            }
            if(!_dpp_producer->init())
            {
                SPDLOG_CRITICAL("kafka producer (_dpp_producer) initialize error!");
                return false;
            }
            // Create logger
            if ( enable_so_logging ) {
                configure_csv_logger();
                _so_processing_worker_ptr->set_enable_so_logging(enable_so_logging);
            }
            // Service config
            auto sleep_millisecs = streets_service::streets_configuration::get_int_config("sleep_millisecs");
            auto int_client_request_attempts = streets_service::streets_configuration::get_int_config("int_client_request_attempts");
            // HTTP request to update intersection information
            if (!update_intersection_info(sleep_millisecs, int_client_request_attempts))
            {
                SPDLOG_CRITICAL("Failed to initialize signal_opt_service due to intersection client request failure!");
                return false;
            }
            //Configure signal_opt_processing_worker
            _so_processing_worker_ptr->configure_signal_opt_processing_worker(dpp_config);
            SPDLOG_INFO("signal_opt_service initialized successfully!!!");
            return true;
        }
        catch (const streets_service::streets_configuration_exception &ex)
        {
            SPDLOG_ERROR("Signal Optimization Service Initialization failure: {0} ", ex.what());
            return false;
        }
    }
References streets_service::streets_configuration::get_int_config().
Referenced by main().
populate_movement_groups()
void signal_opt_service::signal_opt_service::populate_movement_groups (std::shared_ptr< streets_signal_optimization::movement_groups > _groups, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_config) const
Method to use the tsc_config_state pointer from the signal_opt_message_worker to populate movement_groups pointer.
Parameters
movement_groups shared pointer to list of movement groups
tsc_config shared pointer to tsc configuration state object.
Definition at line 296 of file signal_opt_service.cpp.
    {
        if (tsc_config) {
            for (const auto &phase_config : tsc_config->tsc_config_list) {
                // If signal group has one or more concurrent phase
                if ( !phase_config.concurrent_signal_groups.empty() ) {
                    // Loop through concurrent phases and create a movement group for each pair
                    for (const auto &concur : phase_config.concurrent_signal_groups) {
                        streets_signal_optimization::movement_group new_group;
                        new_group.signal_groups = {phase_config.signal_group_id, concur};
                        // Initialize a flag for if this pair already exists in the movement groups in reverse.
                        bool already_added = false;
                        // loop through movement groups and set flag to true if pair already exists in reverse order.
                        for ( const auto &add_group: _groups->groups ) {
                            if ( add_group.signal_groups.second == new_group.signal_groups.first &&
                                    add_group.signal_groups.first == new_group.signal_groups.second) {
                                already_added = true;
                            }
                        }
                        // Only add a new pair if it does not already exist in movement groups in reverse.
                        if (!already_added) {
                            _groups->groups.push_back(new_group);
                        }
                    }
                }
                // If signal group does not have any concurrent phases add it as a movement group pair of between itself and 0 since
                // 0 is an invalid signal group
                else {
                    streets_signal_optimization::movement_group new_group;
                    // Add invalid signal group 0 as current signal group to indicate there is none.
                    new_group.signal_groups = { phase_config.signal_group_id, 0};
                    _groups->groups.push_back(new_group);
                }
            }
            SPDLOG_DEBUG("Movement Groups: ");
            for ( const auto &mg : _groups->groups) {
                SPDLOG_DEBUG("Signal Group {0} and Signal Group {1}.", mg.signal_groups.first, mg.signal_groups.second );
            }
            remove_signal_groups( _groups ,ignore_signal_groups);
        }
    }
References streets_signal_optimization::movement_group::signal_groups.
produce_dpp()
void signal_opt_service::signal_opt_service::produce_dpp (const std::shared_ptr< kafka_clients::kafka_producer_worker > dpp_producer, const std::shared_ptr< OpenAPI::OAIIntersection_info > _intersection_info_ptr, const std::shared_ptr< streets_vehicles::vehicle_list > _vehicle_list_ptr, const std::shared_ptr< signal_phase_and_timing::spat > _spat_ptr, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > _tsc_config_ptr, const std::shared_ptr< streets_signal_optimization::movement_groups > _movement_groups_ptr, const streets_signal_optimization::streets_desired_phase_plan_generator_configuration & _dpp_config, const int & _so_sleep_time) const
Method to produce desired phase plan Json to kafka.
Parameters
dpp_producer shared pointer to kafka producer.
_intersection_info_ptr shared pointer to intersection info object.
_vehicle_list_ptr shared pointer to vehicle list object.
_spat_ptr shared pointer to spat object.
_tsc_config_ptr shared pointer to tsc configuration state object.
_movement_groups_ptr shared pointer to movement groups object.
_dpp_config desired phase plan generator configuration object.
_so_sleep_time the time interval between two iterations of calling signal optimization libraries
If the number of future movement groups in the spat has changed compared to the previous step and it is less than or equal to the desired numNo vehicles presenter of future movement groups, run streets_signal_optimization libraries to get optimal desired_phase_plan.
Definition at line 152 of file signal_opt_service.cpp.
    {
        if (!_so_processing_worker_ptr->get_is_configured()) {
            _so_processing_worker_ptr->configure_signal_opt_processing_worker(_dpp_config);
        }
        int prev_future_move_group_count = 0;
        int current_future_move_group_count = 0;
        bool new_dpp_generated = false;
        // Keeps track of sequential SO iteration skips caused by percieved missing DPP data in spat.
        // TODO: More robust fix could use check last entry in sent DPP vs last entry in received spat
        // instead of future movement group counts/
        int sequential_skips_for_missing_dpp = 0;
        while ( dpp_producer->is_running() ) {
            auto current_timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
            SPDLOG_DEBUG("Signal Optimization iteration start time {0}!", current_timestamp);
            try{
                if ( _spat_ptr ) {
                    auto spat_lag =  current_timestamp - _spat_ptr->get_intersection().get_epoch_timestamp() ;
                        if ( spat_lag > 200 ) {
                            SPDLOG_WARN("Current SPat Lag exceends 200 ms!");
                        }
                    SPDLOG_DEBUG("Current spat lag is {0} ms!", spat_lag);
                }
                else {
                    SPDLOG_WARN("SPaT Pointer is unset, skipping SO Iteration");
                    std::this_thread::sleep_for(std::chrono::milliseconds(_so_sleep_time));
                    continue;
                }
            }
            catch( const signal_phase_and_timing::signal_phase_and_timing_exception &e) {
                SPDLOG_ERROR("Cannot interpret SPAT due to exception :  {0}", e.what());
                std::this_thread::sleep_for(std::chrono::milliseconds(_so_sleep_time));
                continue;
            }
            if ( !_vehicle_list_ptr->get_vehicles().empty() ) {
                streets_desired_phase_plan::streets_desired_phase_plan spat_dpp;
                try
                {
                    spat_dpp = _so_processing_worker_ptr->convert_spat_to_dpp(_spat_ptr, _movement_groups_ptr);
                }
                catch(const std::runtime_error &ex)
                {
                    SPDLOG_ERROR("Encountered Exception : {0} ", ex.what());
                    std::this_thread::sleep_for(std::chrono::milliseconds(_so_sleep_time));
                    continue;
                }
                SPDLOG_INFO("Base DPP is {0}", spat_dpp.toJson());
                current_future_move_group_count = static_cast<int>(spat_dpp.desired_phase_plan.size());
                if ( current_future_move_group_count < 1) {
                    SPDLOG_ERROR("DPP size is zero! Skipping SO iteration");
                    std::this_thread::sleep_for(std::chrono::milliseconds(_so_sleep_time));
                    continue;
                }
                if (new_dpp_generated) {
                    SPDLOG_INFO("Current number of movement groups represented in SPAT : {0}!", prev_future_move_group_count);
                    if (current_future_move_group_count > prev_future_move_group_count) {
                        new_dpp_generated = false;
                    }
                    else {
                        // Increment sequential skip count for each skip
                        sequential_skips_for_missing_dpp++;
                        SPDLOG_WARN("Skipping SO iteration {0}. Previously sent DPP is not yet reflected in SPaT!", sequential_skips_for_missing_dpp);
                        if (sequential_skips_for_missing_dpp > 5 ) {
                            // Log error and attempt to reset previous movement group count and new dpp generated flag if error occurs more than 5 times sequentially.
                            SPDLOG_ERROR("DPP producer is in error state, attempting to reset previous future movement group count {0} and new DPP generated flag {1}", new_dpp_generated, prev_future_move_group_count);
                            new_dpp_generated = false;
                            prev_future_move_group_count  = 0;
                        }
                        std::this_thread::sleep_for(std::chrono::milliseconds(_so_sleep_time));
                        continue;
                    }
                }
                // If we do not skip an iteration for this purpose, reset counter to 0
                sequential_skips_for_missing_dpp = 0;
                current_timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
                if ( current_timestamp > spat_dpp.desired_phase_plan.front().end_time ) {
                    SPDLOG_WARN("Spat DPP does not include current time!\n DPP : {0}",spat_dpp.toJson());
                    std::this_thread::sleep_for(std::chrono::milliseconds(_so_sleep_time));
                    continue;
                }
                auto time_to_yellow = spat_dpp.desired_phase_plan.front().end_time - current_timestamp;
                SPDLOG_INFO("Time to yellow is : {0}", time_to_yellow );
                // Check that time to yellow is within configured threshold and also above 200 ms to account for DPP transimission latency
                if ( time_to_yellow <= _time_to_yellow && time_to_yellow > 200 ) {
                    if (current_future_move_group_count <= dpp_config.desired_future_move_group_count ) {
                        SPDLOG_INFO("The number of future movement groups in the spat is {0} which is less than the max desired future movement groups {1}.",
                                                                    current_future_move_group_count-1, dpp_config.desired_future_move_group_count );
                        // Current movement group count includes current fix momvement group.
                        // Desired future movemement group count only includes future movement groups
                        streets_desired_phase_plan::streets_desired_phase_plan optimal_dpp =
                                    _so_processing_worker_ptr->select_optimal_dpp(_intersection_info_ptr,
                                                                                _spat_ptr,
                                                                                _tsc_config_ptr,
                                                                                _vehicle_list_ptr,
                                                                                _movement_groups_ptr,
                                                                                _dpp_config);
                        if (!optimal_dpp.desired_phase_plan.empty()) {
                            std::string msg_to_send = optimal_dpp.toJson();
                            /* produce the optimal desired phase plan to kafka */
                            dpp_producer->send(msg_to_send);
                            current_timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
                            SPDLOG_DEBUG("Signal Optimization iteration end time {0}!", current_timestamp);
                            prev_future_move_group_count = current_future_move_group_count;
                            new_dpp_generated = true;
                        }
                    }
                    else {
                        SPDLOG_INFO("The number of future movement groups in spat is greater than or equal to the desired number future movement groups");
                    }
                }
                else {
                    SPDLOG_WARN("Currently {0} ms to yellow! Waiting for {1} ms or lower time to yellow!", time_to_yellow, _time_to_yellow);
                }
            }
            else {
                SPDLOG_DEBUG("No vehicles present");
            }
            std::this_thread::sleep_for(std::chrono::milliseconds(_so_sleep_time));
        }
        SPDLOG_WARN("Stopping desired phase plan producer thread!");
        dpp_producer->stop();
    }
References streets_desired_phase_plan::streets_desired_phase_plan::desired_phase_plan, and streets_desired_phase_plan::streets_desired_phase_plan::toJson().
read_configuration_params()
void signal_opt_service::signal_opt_service::read_configuration_params ()
Method for reading the configuration parameters from manifest.json.
Definition at line 382 of file signal_opt_service.cpp.
    {
        // TODO: Replace initialization by extending streets_service_base and overiding initialize and start methods
        streets_service::streets_configuration::create("../manifest.json");
        _exp_delta = streets_service::streets_configuration::get_int_config("exp_delta");
        _bootstrap_server = streets_service::streets_configuration::get_string_config("bootstrap_server");
        _spat_topic_name = streets_service::streets_configuration::get_string_config("spat_consumer_topic");
        _spat_group_id = streets_service::streets_configuration::get_string_config("spat_group_id");
        _vsi_topic_name = streets_service::streets_configuration::get_string_config("vsi_consumer_topic");
        _vsi_group_id = streets_service::streets_configuration::get_string_config("vsi_group_id");
        _tsc_config_topic_name = streets_service::streets_configuration::get_string_config("tsc_config_consumer_topic");
        _tsc_config_group_id = streets_service::streets_configuration::get_string_config("tsc_config_group_id");
        _dpp_topic_name = streets_service::streets_configuration::get_string_config("dpp_producer_topic");
        _so_log_path = streets_service::streets_configuration::get_string_config("so_log_path");
        _so_log_filename = streets_service::streets_configuration::get_string_config("so_log_filename");
        enable_so_logging = streets_service::streets_configuration::get_boolean_config("enable_so_logging");
        so_sleep_time = streets_service::streets_configuration::get_int_config("signal_optimization_frequency");
        _time_to_yellow = streets_service::streets_configuration::get_int_config("time_before_yellow_change");
        dpp_config.initial_green_buffer = streets_service::streets_configuration::get_int_config("initial_green_buffer");
        dpp_config.final_green_buffer = streets_service::streets_configuration::get_int_config("final_green_buffer");
        dpp_config.et_inaccuracy_buffer = streets_service::streets_configuration::get_int_config("et_inaccuracy_buffer");
        dpp_config.queue_max_time_headway = streets_service::streets_configuration::get_int_config("queue_max_time_headway");
        dpp_config.so_radius = streets_service::streets_configuration::get_double_config("so_radius");
        dpp_config.min_green = streets_service::streets_configuration::get_int_config("min_green");
        dpp_config.max_green = streets_service::streets_configuration::get_int_config("max_green");
        dpp_config.desired_future_move_group_count = static_cast<uint8_t>(streets_service::streets_configuration::get_int_config("desired_future_move_group_count"));
        std::stringstream comma_separated_list (streets_service::streets_configuration::get_string_config("ignore_signal_groups"));
        while( comma_separated_list.good() )
        {
            std::string signal_group;
            getline( comma_separated_list, signal_group, ',' );
            SPDLOG_WARN("Adding signal group {0} to the list of ignored signal groups", std::stoi(signal_group));
            ignore_signal_groups.push_back( std::stoi(signal_group) );
        }
    }
References streets_service::streets_singleton< streets_configuration, std::string >::create(), streets_service::streets_configuration::get_boolean_config(), streets_service::streets_configuration::get_double_config(), streets_service::streets_configuration::get_int_config(), and streets_service::streets_configuration::get_string_config().
remove_signal_groups()
void signal_opt_service::signal_opt_service::remove_signal_groups (const std::shared_ptr< streets_signal_optimization::movement_groups > & movement_groups, const std::vector< uint > & rm_signal_groups) const
Remove list of provided signal groups from movement groups considered for signal optmization.
Parameters
_movement_groups collection of movement groups to remove signal groups from
rm_signal_groups signal groups to remove from movement groups.
Definition at line 420 of file signal_opt_service.cpp.
{
        SPDLOG_WARN("Attempting to ignore {0} signal groups!", rm_signal_groups.size());
        // Remove configured signal groups to ignore them
        for (const auto &ignore : rm_signal_groups) {
            SPDLOG_DEBUG("Removing {0} from size {1}!", ignore, _movement_groups->groups.size());
            auto mg_itr = _movement_groups->groups.begin();
            while ( mg_itr != _movement_groups->groups.end() ) {
                if ( mg_itr->signal_groups.first == ignore && mg_itr->signal_groups.second == 0) {
                    SPDLOG_WARN("Removing movement group with signal groups {0} , {1}", mg_itr->signal_groups.first, mg_itr->signal_groups.second);
                    mg_itr = _movement_groups->groups.erase(mg_itr);
                }
                else if (mg_itr->signal_groups.first != 0 &&  mg_itr->signal_groups.second == ignore) {
                    SPDLOG_WARN("Removing signal group from {0} signal groups {1} , {2}",ignore, mg_itr->signal_groups.first, mg_itr->signal_groups.second);
                    mg_itr->signal_groups.second = 0;
                    SPDLOG_WARN("New movement group includes signal groups {0} , {1}", mg_itr->signal_groups.first, mg_itr->signal_groups.second);
                    mg_itr++;
                }
                else if ( mg_itr->signal_groups.first == ignore && mg_itr->signal_groups.second != 0) {
                    SPDLOG_WARN("Removing signal group from {0} signal groups {1} , {2}",ignore, mg_itr->signal_groups.first, mg_itr->signal_groups.second);
                    mg_itr->signal_groups.first = mg_itr->signal_groups.second;
                    mg_itr->signal_groups.second = 0;
                    SPDLOG_WARN("New movement group includes signal groups {0} , {1}", mg_itr->signal_groups.first, mg_itr->signal_groups.second);
                    mg_itr++;
                }
                else {
                    SPDLOG_DEBUG("Ignored SG {0} is not present in MG ({1},{2})", ignore,mg_itr->signal_groups.first, mg_itr->signal_groups.second );
                    mg_itr++;
                }
            }
        }
    }
start()
void signal_opt_service::signal_opt_service::start ()
Create threads and consume messages.
Definition at line 83 of file signal_opt_service.cpp.
    {
        std::thread tsc_config_t(&signal_opt_service::consume_tsc_config, this, this->_tsc_config_consumer, this->tsc_configuration_ptr);
        // Block until TSC configuration information is received
        tsc_config_t.join();
        // After TSC configuration information is received, use it to determine movemement groups
        populate_movement_groups(movement_groups_ptr, tsc_configuration_ptr);
        // After movement groups are created, process vehicle status and intent and spat messages to
        // maintain information about current vehicle states and TSC state
        std::thread vsi_t(&signal_opt_service::consume_vsi,  this, this->_vsi_consumer, this->vehicle_list_ptr);
        std::thread spat_t(&signal_opt_service::consume_spat,this, this->_spat_consumer, this->spat_ptr);
        std::thread dpp_t(&signal_opt_service::produce_dpp, this, this->_dpp_producer,
                                                            this->intersection_info_ptr,
                                                            this->vehicle_list_ptr,
                                                            this->spat_ptr,
                                                            this->tsc_configuration_ptr,
                                                            this->movement_groups_ptr,
                                                            this->dpp_config,
                                                            this->so_sleep_time);
        // Running in parallel
        spat_t.join();
        vsi_t.join();
        dpp_t.join();
    }
Referenced by main().
update_intersection_info()
bool signal_opt_service::signal_opt_service::update_intersection_info (unsigned long sleep_millisecs, unsigned long int_client_request_attempts) const
Updating the intersection info.
Parameters
sleep_millisecs The current thread sleep for milliseconds after each update attempt
int_client_request_attempts The number of attempts for the loop
Returns
boolean. True if intersection information is updated, otherwise failed to update intersection information
Definition at line 342 of file signal_opt_service.cpp.
    {
        SPDLOG_INFO("Send client request to update intersection inforamtion every {0} ms for maximum {1} times.", sleep_millisecs, int_client_request_attempts);
        int attempt_count = 0;
        while (attempt_count < int_client_request_attempts)
        {
            // Send HTTP request, and update intersection information. If updated successfully, it returns true and exit the while loop.
            if (_so_msgs_worker_ptr && _so_msgs_worker_ptr->request_intersection_info(intersection_info_ptr))
            {
                return true;
            }
            std::this_thread::sleep_for(std::chrono::milliseconds(sleep_millisecs));
            attempt_count++;
        }
        // If failed to update the intersection information after certain numbers of attempts
        SPDLOG_ERROR("Updating Intersection information failed. ");
        return false;
    }
Member Data Documentation
_bootstrap_server
std::string signal_opt_service::signal_opt_service::_bootstrap_server private
Definition at line 19 of file signal_opt_service.h.
_dpp_producer
std::shared_ptr<kafka_clients::kafka_producer_worker> signal_opt_service::signal_opt_service::_dpp_producer private
Definition at line 38 of file signal_opt_service.h.
_dpp_topic_name
std::string signal_opt_service::signal_opt_service::_dpp_topic_name private
Definition at line 26 of file signal_opt_service.h.
_exp_delta
int signal_opt_service::signal_opt_service::_exp_delta private
Definition at line 29 of file signal_opt_service.h.
_so_log_filename
std::string signal_opt_service::signal_opt_service::_so_log_filename private
Definition at line 28 of file signal_opt_service.h.
_so_log_path
std::string signal_opt_service::signal_opt_service::_so_log_path private
Definition at line 27 of file signal_opt_service.h.
_so_msgs_worker_ptr
std::shared_ptr<signal_opt_messages_worker> signal_opt_service::signal_opt_service::_so_msgs_worker_ptr private
Definition at line 16 of file signal_opt_service.h.
_so_processing_worker_ptr
std::shared_ptr<signal_opt_processing_worker> signal_opt_service::signal_opt_service::_so_processing_worker_ptr private
Definition at line 17 of file signal_opt_service.h.
_spat_consumer
std::shared_ptr<kafka_clients::kafka_consumer_worker> signal_opt_service::signal_opt_service::_spat_consumer private
Definition at line 36 of file signal_opt_service.h.
_spat_group_id
std::string signal_opt_service::signal_opt_service::_spat_group_id private
Definition at line 20 of file signal_opt_service.h.
_spat_topic_name
std::string signal_opt_service::signal_opt_service::_spat_topic_name private
Definition at line 21 of file signal_opt_service.h.
_time_to_yellow
uint64_t signal_opt_service::signal_opt_service::_time_to_yellow private
Definition at line 32 of file signal_opt_service.h.
_tsc_config_consumer
std::shared_ptr<kafka_clients::kafka_consumer_worker> signal_opt_service::signal_opt_service::_tsc_config_consumer private
Definition at line 37 of file signal_opt_service.h.
_tsc_config_group_id
std::string signal_opt_service::signal_opt_service::_tsc_config_group_id private
Definition at line 24 of file signal_opt_service.h.
_tsc_config_topic_name
std::string signal_opt_service::signal_opt_service::_tsc_config_topic_name private
Definition at line 25 of file signal_opt_service.h.
_vsi_consumer
std::shared_ptr<kafka_clients::kafka_consumer_worker> signal_opt_service::signal_opt_service::_vsi_consumer private
Definition at line 35 of file signal_opt_service.h.
_vsi_group_id
std::string signal_opt_service::signal_opt_service::_vsi_group_id private
Definition at line 22 of file signal_opt_service.h.
_vsi_topic_name
std::string signal_opt_service::signal_opt_service::_vsi_topic_name private
Definition at line 23 of file signal_opt_service.h.
dpp_config
streets_signal_optimization::streets_desired_phase_plan_generator_configuration signal_opt_service::signal_opt_service::dpp_config private
Definition at line 40 of file signal_opt_service.h.
enable_so_logging
bool signal_opt_service::signal_opt_service::enable_so_logging = false private
Definition at line 30 of file signal_opt_service.h.
ignore_signal_groups
std::vector<uint> signal_opt_service::signal_opt_service::ignore_signal_groups private
Definition at line 33 of file signal_opt_service.h.
intersection_info_ptr
std::shared_ptr<OpenAPI::OAIIntersection_info> signal_opt_service::signal_opt_service::intersection_info_ptr private
Definition at line 42 of file signal_opt_service.h.
movement_groups_ptr
std::shared_ptr<streets_signal_optimization::movement_groups> signal_opt_service::signal_opt_service::movement_groups_ptr private
Definition at line 41 of file signal_opt_service.h.
so_sleep_time
int signal_opt_service::signal_opt_service::so_sleep_time private
Definition at line 31 of file signal_opt_service.h.
spat_ptr
std::shared_ptr<signal_phase_and_timing::spat> signal_opt_service::signal_opt_service::spat_ptr private
Definition at line 43 of file signal_opt_service.h.
tsc_configuration_ptr
std::shared_ptr<streets_tsc_configuration::tsc_configuration_state> signal_opt_service::signal_opt_service::tsc_configuration_ptr private
Definition at line 45 of file signal_opt_service.h.
vehicle_list_ptr
std::shared_ptr<streets_vehicles::vehicle_list> signal_opt_service::signal_opt_service::vehicle_list_ptr private
Definition at line 44 of file signal_opt_service.h.
The documentation for this class was generated from the following files:
signal_opt_service/include/signal_opt_service.h
signal_opt_service/src/signal_opt_service.cpp