Carma-streets: streets_service::streets_configuration Class Reference
streets_service::streets_configuration Class Reference
Streets Configuration singleton scoped object that parses manifest.json configuration file and offers static access to the configuration parameter values. Singleton also configures default multisink logger file and terminal logger.
#include <streets_configuration.h>
Static Public Member Functions
static std::string get_string_config (const std::string &config_param_name)
Retreive configuration parameter string value with provided name.
static int get_int_config (const std::string &config_param_name)
Retreive configuration parameter integer value with provided name.
static double get_double_config (const std::string &config_param_name)
Retreive configuration parameter double value with provide name.
static bool get_boolean_config (const std::string &config_param_name)
Retreive configuration parameter boolean value with provide name.
static std::string get_service_name ()
static void initialize_logger ()
Static method to initialize spdlog default logger.
Static Public Member Functions inherited from streets_service::streets_singleton< streets_configuration, std::string >
static streets_configuration & get_singleton ()
static streets_configuration & create (Args...args)
Method to intialize streets_singleton with constructor params ...Args of templated class.
Protected Member Functions
rapidjson::Document parse_configuration_file ()
Parse manifest.json configuration file for CARMA-Streets service and update configurations.
void update_configuration (const rapidjson::Document &doc)
Update configuration parameters using json Document.
void update_log_level (const rapidjson::Document &doc)
Update loglevel for logger using json Document.
void parse_configurations_array (const rapidjson::GenericArray< true, rapidjson::Value > &arr)
Helper method that reads the configurations array inside the manifest.json configuration file.
void configure_logger (const rapidjson::Document &doc)
Method to read service level configurations from manifest.json file to configure default logger and set log level.
void create_default_logger (const std::string &service_name) const
Method to configuration spdlog default multisink logger. Includes a file sink which rotates daily and terminal sink.
void set_loglevel (const std::string &loglevel) const
Method to set the spdlog::default.
void check_update ()
Method to check last modified time of file to see if a file update is necessary.
void set_service_name (const std::string &service_name)
Protected Member Functions inherited from streets_service::streets_singleton< streets_configuration, std::string >
streets_singleton ()=default
~streets_singleton ()=default
Static Protected Member Functions
static T & get_singleton ()
Private Member Functions
streets_configuration (const std::string &filepath="../manifest.json")
Constructor that takes filepath as a parameter.
Private Attributes
std::string filepath
std::mutex config_lock
std::map< std::string, configuration > configuration_map
std::time_t last_modified = 0
std::string _service_name
Friends
class streets_singleton< streets_configuration, std::string >
Additional Inherited Members
Public Member Functions inherited from streets_service::streets_singleton< streets_configuration, std::string >
streets_singleton (const streets_singleton &)=delete
streets_singleton (streets_singleton &&)=delete
streets_singleton & operator= (const streets_singleton &)=delete
streets_singleton & operator= (const streets_singleton &&)=delete
Static Protected Attributes inherited from streets_service::streets_singleton< streets_configuration, std::string >
static std::unique_ptr< streets_configuration > instance
Detailed Description
Streets Configuration singleton scoped object that parses manifest.json configuration file and offers static access to the configuration parameter values. Singleton also configures default multisink logger file and terminal logger.
Definition at line 27 of file streets_configuration.h.
Constructor & Destructor Documentation
streets_configuration()
streets_service::streets_configuration::streets_configuration (const std::string & filepath = "../manifest.json") explicit private
Constructor that takes filepath as a parameter.
Parameters
filepath relative path to manifest.json configuration file.
Definition at line 6 of file streets_configuration.cpp.
                                                                           : filepath(filepath){
        // Parse manifest.json configuration file into rapidjson::Document
        rapidjson::Document doc = parse_configuration_file();
        // Use service level configuration parameters from Document (i.e. loglevel and service_name)
        // to configure spdlog default logger (terminal and file sinks)
        configure_logger(doc);
        // Use configurations array to populate configuration map with service specific configuration
        // parameters from Document
        update_configuration(doc);
        SPDLOG_INFO("Printing Configuration Parameters ---------------------------------------");
        for(const auto& conf : configuration_map)
        {
            SPDLOG_INFO("{0} : {1} ", conf.first.c_str(), conf.second.value.c_str());
        }
    };
References configuration_map, configure_logger(), parse_configuration_file(), and update_configuration().
Member Function Documentation
check_update()
void streets_service::streets_configuration::check_update () protected
Method to check last modified time of file to see if a file update is necessary.
Exceptions
streets_configuration_exception if update_configurations fails.
Definition at line 212 of file streets_configuration.cpp.
{
        try {
            // Check last write time of manifest.json configuration file to see if updates have been made
            std::time_t time = boost::filesystem::last_write_time(filepath);
            SPDLOG_TRACE("Last Modified Time {0} vs Stored Last Modified Time {1}", time, last_modified);
            if ( time > last_modified) {
                // If updates have been made parse manifest.json into Document and update loglevel and
                // any changed configuration parameters.
                rapidjson::Document doc = parse_configuration_file();
                update_log_level(doc);
                update_configuration(doc);
                // Set new update time to the last update read
                last_modified = time;
            }
        }
        catch (const std::exception &e) {
            throw streets_configuration_exception(e.what());
        }
    }
References filepath, last_modified, parse_configuration_file(), update_configuration(), and update_log_level().
configure_logger()
void streets_service::streets_configuration::configure_logger (const rapidjson::Document & doc) protected
Method to read service level configurations from manifest.json file to configure default logger and set log level.
Parameters
doc rapidjson::Document containing parse manifest.json configuration file.
Definition at line 40 of file streets_configuration.cpp.
{
        if ( doc.HasMember("service_name") && doc.FindMember("service_name")->value.IsString() ) {
            set_service_name(doc.FindMember("service_name")->value.GetString());
            create_default_logger( _service_name );
        }
        else {
            SPDLOG_WARN("Parameter \"service_name\" missing/incorrectly formatted in manifest.json! Setting \"service_name\" to streets_service!");
            create_default_logger("streets_service");
        }
        if ( doc.HasMember("loglevel") && doc.FindMember("loglevel")->value.IsString() ) {
            set_loglevel( doc.FindMember("loglevel")->value.GetString() );
        }
        else {
            SPDLOG_WARN("Parameter \"loglevel\" missing/incorrectly formatted in manifest.json! Setting \"loglevel\" to INFO!");
            set_loglevel("info");
        }
    }
References _service_name, create_default_logger(), set_loglevel(), and set_service_name().
Referenced by streets_configuration().
create_default_logger()
void streets_service::streets_configuration::create_default_logger (const std::string & service_name) const protected
Method to configuration spdlog default multisink logger. Includes a file sink which rotates daily and terminal sink.
Parameters
service_name string which is obtained form the manifest.json configuration file and used as part of the naming convention for log files.
Definition at line 184 of file streets_configuration.cpp.
{
        try {
            // Create logger thread pool
            spdlog::init_thread_pool(8192, 1);
            // Create logger file and stdout sinks
            // Rotate files at 11:59 PM
            auto file_sink = std::make_shared<spdlog::sinks::daily_file_sink_mt>("../logs/" + service_name, 23, 59, false, 3);
            auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
            // Link thread pool and sinks to async logger
            auto logger = std::make_shared<spdlog::async_logger>("main",  spdlog::sinks_init_list({console_sink, file_sink}),spdlog::thread_pool());
            // Set pattern [2022-3-31 13:00:00.000] [loglevel] [file_name.cpp:123]
            logger->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%^%l%$] [%s:%#] %v");
            // Register logger and set as default
            spdlog::set_default_logger(logger);
            SPDLOG_INFO("Default Logger initialized!");
        }
        catch (const spdlog::spdlog_ex& ex)
        {
            SPDLOG_ERROR( "Log initialization failed: {0}!",ex.what());
        }
    };
Referenced by configure_logger().
get_boolean_config()
bool streets_service::streets_configuration::get_boolean_config (const std::string & config_param_name) static
Retreive configuration parameter boolean value with provide name.
Parameters
config_param_name configuration parameter name.
Exceptions
streets_configuration_exception if configuration is not of data_type BOOL.
Returns
bool configuration value.
Definition at line 150 of file streets_configuration.cpp.
{
        // Get Singleton
        auto &instance = get_singleton();
        // update  Singleton
        instance.check_update();
        // Get Configuration
        auto bool_config = instance.configuration_map.find(config_param_name);
        if ( bool_config->second.type == data_type::config_bool) {
            return bool_config->second.value.compare("true") == 0 ? true : false;
        }
        else {
            throw streets_service::streets_configuration_exception("Configuration parameter " + config_param_name + " is not data_type BOOL!");
        }
    }
References streets_service::config_bool, get_singleton(), and streets_service::streets_singleton< streets_configuration, std::string >::instance.
Referenced by message_services::services::vehicle_status_intent_service::initialize(), traffic_signal_controller_service::tsc_service::initialize(), scheduling_service::scheduling_service::initialize(), signal_opt_service::signal_opt_service::read_configuration_params(), and scheduling_service::scheduling_service::schedule_veh().
get_double_config()
double streets_service::streets_configuration::get_double_config (const std::string & config_param_name) static
Retreive configuration parameter double value with provide name.
Parameters
config_param_name configuration parameter name.
Exceptions
streets_configuration_exception if configuration is not of data_type DOUBLE.
Returns
double configuration value.
Definition at line 135 of file streets_configuration.cpp.
{
        // Get Singleton
        auto &instance = get_singleton();
        // update  Singleton
        instance.check_update();
        // Get Configuration
        auto double_config = instance.configuration_map.find(config_param_name);
        if ( double_config->second.type == data_type::config_double) {
            return std::stod(double_config->second.value);
        }
        else {
            throw streets_service::streets_configuration_exception("Configuration parameter " + config_param_name + " is not data_type DOUBLE!");
        }
    }
References streets_service::config_double, get_singleton(), and streets_service::streets_singleton< streets_configuration, std::string >::instance.
Referenced by scheduling_service::scheduling_service::config_vehicle_list(), main(), signal_opt_service::signal_opt_service::read_configuration_params(), and scheduling_service::scheduling_service::schedule_veh().
get_int_config()
int streets_service::streets_configuration::get_int_config (const std::string & config_param_name) static
Retreive configuration parameter integer value with provided name.
Parameters
config_param_name configuration parameter name.
Exceptions
streets_configuration_exception if configuration is not of data_type INTEGER.
Returns
int configuration value.
Definition at line 119 of file streets_configuration.cpp.
{
        // Get Singleton
        auto &instance = get_singleton();
        // update  Singleton
        instance.check_update();
        // Get Configuration
        auto int_config = instance.configuration_map.find(config_param_name);
        if ( int_config->second.type == data_type::config_int) {
            return std::stoi(int_config->second.value);
        }
        else {
            throw streets_service::streets_configuration_exception("Configuration parameter " + config_param_name + " is not data_type INTEGER!");
        }
    }
References streets_service::config_int, get_singleton(), and streets_service::streets_singleton< streets_configuration, std::string >::instance.
Referenced by scheduling_service::scheduling_service::config_scheduler(), scheduling_service::scheduling_service::config_vehicle_list(), message_services::services::vehicle_status_intent_service::initialize(), signal_opt_service::signal_opt_service::initialize(), traffic_signal_controller_service::tsc_service::initialize(), main(), and signal_opt_service::signal_opt_service::read_configuration_params().
get_service_name()
std::string streets_service::streets_configuration::get_service_name () static
Definition at line 165 of file streets_configuration.cpp.
{
        auto &instance = get_singleton();
        return instance._service_name;
    }
References get_singleton(), and streets_service::streets_singleton< streets_configuration, std::string >::instance.
Referenced by streets_service::streets_service::initialize().
get_singleton()
static T & streets_service::streets_singleton< T, Args >::get_singleton () static protected
Method for static singleton instance retrieval
Returns
T singleton instance
Referenced by get_boolean_config(), get_double_config(), get_int_config(), get_service_name(), get_string_config(), and initialize_logger().
get_string_config()
std::string streets_service::streets_configuration::get_string_config (const std::string & config_param_name) static
Retreive configuration parameter string value with provided name.
Parameters
config_param_name configuration parameter name.
Exceptions
streets_configuration_exception if configuration is not of data_type STRING.
Returns
string configuration value.
Definition at line 104 of file streets_configuration.cpp.
{
        // Get Singleton
        auto &instance = get_singleton();
        // update  Singleton
        instance.check_update();
        // Get Configuration
        auto string_config = instance.configuration_map.find(config_param_name);
        if ( string_config->second.type == data_type::config_string) {
            return string_config->second.value;
        }
        else {
            throw streets_service::streets_configuration_exception("Configuration parameter " + config_param_name + " is not data_type STRING!");
        }
    }
References streets_service::config_string, get_singleton(), and streets_service::streets_singleton< streets_configuration, std::string >::instance.
Referenced by scheduling_service::scheduling_service::config_scheduler(), scheduling_service::scheduling_service::config_vehicle_list(), scheduling_service::scheduling_service::configure_csv_logger(), message_services::services::vehicle_status_intent_service::initialize(), traffic_signal_controller_service::tsc_service::initialize(), scheduling_service::scheduling_service::initialize(), streets_service::streets_service::initialize_kafka_consumer(), streets_service::streets_service::initialize_kafka_producer(), main(), signal_opt_service::signal_opt_service::read_configuration_params(), scheduling_service::scheduling_worker::schedule_vehicles(), and scheduling_service::scheduling_service::start().
initialize_logger()
void streets_service::streets_configuration::initialize_logger () static
Static method to initialize spdlog default logger.
Definition at line 206 of file streets_configuration.cpp.
{
        auto &singleton = streets_configuration::get_singleton();
        auto doc = singleton.parse_configuration_file();
        singleton.configure_logger( doc );
    };
References get_singleton().
Referenced by main().
parse_configuration_file()
rapidjson::Document streets_service::streets_configuration::parse_configuration_file () protected
Parse manifest.json configuration file for CARMA-Streets service and update configurations.
Exceptions
streets_configuration_exception if cannot open manifest.json configuration file or has json parse error.
Returns
rapidjson::Document containing parsed manifest.json.
Definition at line 22 of file streets_configuration.cpp.
{
        // Open file
        std::ifstream file(filepath);
        if (!file.is_open()) {
            throw streets_service::streets_configuration_exception("Unable to open Streets configuration file " + filepath + " !");
        }
        // Add file contents to stream and parse stream into Document
        rapidjson::IStreamWrapper isw(file);
        rapidjson::Document doc;
        doc.ParseStream(isw);
        if (doc.HasParseError()){
            SPDLOG_ERROR("Error  : {0} Offset: {1} ", doc.GetParseError(), doc.GetErrorOffset());
            throw streets_service::streets_configuration_exception("Document parse error!");
        }
        file.close();
        return doc;
    };
References filepath.
Referenced by streets_configuration(), and check_update().
parse_configurations_array()
void streets_service::streets_configuration::parse_configurations_array (const rapidjson::GenericArray< true, rapidjson::Value > & arr) protected
Helper method that reads the configurations array inside the manifest.json configuration file.
Parameters
arr rapidjson::GenericArray holding values from configurations element of the manifest.json file.
Exceptions
streets_configuration_exception if configurations json object array is incorrectly formatted.
Definition at line 78 of file streets_configuration.cpp.
{
        std::unique_lock<std::mutex> lck(config_lock);
        for ( auto& cnf: arr ) {
            std::string property_name = cnf.FindMember("name")->value.GetString();
            auto val = configuration_map.find( property_name );
            if ( val != configuration_map.end() && cnf.IsObject()) {
                configuration config = val->second;
                configuration file_config;
                file_config.fromJson( cnf.GetObject());
                if ( config != file_config ) {
                    SPDLOG_INFO("Updating configuration {0}!", property_name);
                    configuration_map.erase(property_name);
                    configuration_map.insert(std::make_pair(property_name, file_config));
                }
            }
            else if ( val == configuration_map.end() && cnf.IsObject() ) {
                configuration file_config;
                file_config.fromJson(cnf.GetObject() );
                configuration_map.insert(std::make_pair(property_name, file_config));
            }
            else {
                throw streets_service::streets_configuration_exception("Configuration parameter " + property_name + " not properly formatted!");
            }
        }
    };
References config_lock, configuration_map, and streets_service::configuration::fromJson().
Referenced by update_configuration().
set_loglevel()
void streets_service::streets_configuration::set_loglevel (const std::string & loglevel) const protected
Method to set the spdlog::default.
Exceptions
streets_configuration_exception if default logger has not been configured and registered.
Definition at line 171 of file streets_configuration.cpp.
{
        // Get main logger and set loglevel
        auto main_logger = spdlog::get("main");
        if ( main_logger != nullptr ) {
            main_logger->set_level(spdlog::level::from_str(loglevel));
            spdlog::set_level(spdlog::level::from_str(loglevel));
            SPDLOG_INFO( "Log Level set to {0}!", spdlog::level::to_string_view(spdlog::get_level()));
        }
        else {
            throw streets_configuration_exception("Log Level set failed! No main logger configured!");
        }
    }
Referenced by configure_logger(), and update_log_level().
set_service_name()
void streets_service::streets_configuration::set_service_name (const std::string & service_name) protected
Definition at line 232 of file streets_configuration.cpp.
{
        _service_name = service_name;
    }
References _service_name.
Referenced by configure_logger().
update_configuration()
void streets_service::streets_configuration::update_configuration (const rapidjson::Document & doc) protected
Update configuration parameters using json Document.
Parameters
doc rapidjson::Document containing parsed manifest.json file.
Definition at line 58 of file streets_configuration.cpp.
{
        SPDLOG_DEBUG("Updating Configuration Map");
        if ( doc.FindMember("configurations")->value.IsArray() ) {
            parse_configurations_array(doc.FindMember("configurations")->value.GetArray());
        }
        else {
            SPDLOG_WARN("No configurations found in manifest.json!");
        }
    };
References parse_configurations_array().
Referenced by streets_configuration(), and check_update().
update_log_level()
void streets_service::streets_configuration::update_log_level (const rapidjson::Document & doc) protected
Update loglevel for logger using json Document.
Parameters
doc rapidjson::Document containing parsed manifest.json file.
Definition at line 68 of file streets_configuration.cpp.
{
        if ( doc.FindMember("loglevel")->value.IsString() ) {
            set_loglevel( doc.FindMember("loglevel")->value.GetString() );
        }
        else {
            SPDLOG_WARN("Parameter \"loglevel\" missing/incorrectly formatted in manifest.json! Setting \"loglevel\" to INFO!");
            set_loglevel("info");
        }
    };
References set_loglevel().
Referenced by check_update().
Friends And Related Function Documentation
streets_singleton< streets_configuration, std::string >
friend class streets_singleton< streets_configuration, std::string > friend
Definition at line 1 of file streets_configuration.h.
Member Data Documentation
_service_name
std::string streets_service::streets_configuration::_service_name private
Definition at line 39 of file streets_configuration.h.
Referenced by configure_logger(), and set_service_name().
config_lock
std::mutex streets_service::streets_configuration::config_lock private
Definition at line 33 of file streets_configuration.h.
Referenced by parse_configurations_array().
configuration_map
std::map< std::string, configuration > streets_service::streets_configuration::configuration_map private
Definition at line 35 of file streets_configuration.h.
Referenced by streets_configuration(), and parse_configurations_array().
filepath
std::string streets_service::streets_configuration::filepath private
Definition at line 31 of file streets_configuration.h.
Referenced by check_update(), and parse_configuration_file().
last_modified
std::time_t streets_service::streets_configuration::last_modified = 0 private
Definition at line 37 of file streets_configuration.h.
Referenced by check_update().
The documentation for this class was generated from the following files:
streets_utils/streets_service_configuration/include/streets_configuration.h
streets_utils/streets_service_configuration/src/streets_configuration.cpp