Carma-streets: IntersectionModelAPI::IntersectionModelHandler Class Reference
IntersectionModelAPI::IntersectionModelHandler Class Reference
#include <IntersectionModelHandler.h>
Public Slots
virtual void getConflictLanelets (qint32 link_lanelet_id) override
Get the Conflict Lanelets object.
virtual void getIntersectionInfo () override
Get the Intersection Info object.
virtual void listDepartureLanelets () override
Get the list of departure lanelets for the intersection.
virtual void listEntryLanelets () override
Get the list of entry lanelets for the intersection.
virtual void listLinkLanelets () override
Get the list of link lanelets for the intersection.
Public Slots inherited from OpenAPI::OAIDefaultApiHandler
virtual void getConflictLanelets (qint32 link_lanelet_id)
virtual void getIntersectionInfo ()
virtual void listDepartureLanelets ()
virtual void listEntryLanelets ()
virtual void listLinkLanelets ()
Public Member Functions
IntersectionModelHandler ()=default
IntersectionModelHandler (std::shared_ptr< intersection_model::intersection_model > int_worker)
~IntersectionModelHandler ()=default
Public Member Functions inherited from OpenAPI::OAIDefaultApiHandler
OAIDefaultApiHandler ()
virtual ~OAIDefaultApiHandler ()
Private Attributes
std::shared_ptr< intersection_model::intersection_model > int_worker_
Detailed Description
Definition at line 11 of file IntersectionModelHandler.h.
Constructor & Destructor Documentation
IntersectionModelHandler() [1/2]
IntersectionModelAPI::IntersectionModelHandler::IntersectionModelHandler () default
IntersectionModelHandler() [2/2]
IntersectionModelAPI::IntersectionModelHandler::IntersectionModelHandler (std::shared_ptr< intersection_model::intersection_model > int_worker)
Definition at line 6 of file IntersectionModelHandler.cpp.
                                                                                                                     : int_worker_(int_worker)
    {
        SPDLOG_DEBUG("IntersectionModelHandler constructor called");
    }
~IntersectionModelHandler()
IntersectionModelAPI::IntersectionModelHandler::~IntersectionModelHandler () default
Member Function Documentation
getConflictLanelets
void IntersectionModelAPI::IntersectionModelHandler::getConflictLanelets (qint32 link_lanelet_id) override virtual slot
Get the Conflict Lanelets object.
Parameters
link_lanelet_id
Definition at line 136 of file IntersectionModelHandler.cpp.
    {
        Q_UNUSED(link_lanelet_id);
        auto reqObj = qobject_cast<OpenAPI::OAIDefaultApiRequest *>(sender());
        if (reqObj != nullptr)
        {
            QList<OpenAPI::OAILanelet_info> res;
            // Only return the conflict lanelet ids when input is a link lanelet within an intersection
            if (int_worker_->is_valid_link_lanelet_id(link_lanelet_id))
            {
                std::vector<intersection_model::lanelet_info_t> link_lanelet_v = int_worker_->get_conflict_lanelets_info(link_lanelet_id);
                for (std::vector<intersection_model::lanelet_info_t>::iterator itr = link_lanelet_v.begin(); itr != link_lanelet_v.end(); itr++)
                {
                    OpenAPI::OAILanelet_info lanelet_info;
                    lanelet_info.setId(itr->id);
                    lanelet_info.setSpeedLimit(itr->speed_limit);
                    lanelet_info.setLength(itr->length);
                    lanelet_info.setSignalGroupId(itr->signal_group_id);
                    res.push_back(lanelet_info);
                }
                reqObj->getConflictLaneletsResponse(res);
            }
            else
            {
                QString err_msg = "Invalid link lanelet id parameter.";
                reqObj->getConflictLaneletsError(res, QNetworkReply::NetworkError::ContentAccessDenied, err_msg);
            }
        }
    }
References int_worker_, OpenAPI::OAILanelet_info::setId(), OpenAPI::OAILanelet_info::setLength(), OpenAPI::OAILanelet_info::setSignalGroupId(), and OpenAPI::OAILanelet_info::setSpeedLimit().
getIntersectionInfo
void IntersectionModelAPI::IntersectionModelHandler::getIntersectionInfo () override virtual slot
Get the Intersection Info object.
Definition at line 11 of file IntersectionModelHandler.cpp.
    {
        auto reqObj = qobject_cast<OpenAPI::OAIDefaultApiRequest *>(sender());
        if (reqObj != nullptr)
        {
            OpenAPI::OAIIntersection_info res;
            res.setId(int_worker_->get_intersection_info().intersection_id);
            res.setName(int_worker_->get_intersection_info().intersection_name.c_str());
            QList<OpenAPI::OAILanelet_info> departure_lanlets;
            intersection_model::intersection_info_t int_info = int_worker_->get_intersection_info();
            for (std::set<intersection_model::lanelet_info_t>::iterator itr = int_info.departure_lanelets_info.begin(); itr != int_info.departure_lanelets_info.end(); itr++)
            {
                OpenAPI::OAILanelet_info lanelet_info;
                lanelet_info.setId(itr->id);
                lanelet_info.setSpeedLimit(itr->speed_limit);
                lanelet_info.setLength(itr->length);
                departure_lanlets.push_back(lanelet_info);
            }
            res.setDepartureLanelets(departure_lanlets);
            QList<OpenAPI::OAILanelet_info> link_lanlets;
            for (std::vector<intersection_model::lanelet_info_t>::iterator itr = int_info.link_lanelets_info.begin(); itr != int_info.link_lanelets_info.end(); itr++)
            {
                OpenAPI::OAILanelet_info lanelet_info;
                lanelet_info.setId(itr->id);
                lanelet_info.setSpeedLimit(itr->speed_limit);
                lanelet_info.setSignalGroupId(itr->signal_group_id);
                // Update the llink lanelet_info with the list of conflict lanelets
                std::vector<intersection_model::lanelet_info_t> conflict_lanelet_info_v = int_worker_->get_conflict_lanelets_info(itr->id);
                QList<qint32> conflict_lanelet_ids;
                for (auto conflict_itr = conflict_lanelet_info_v.begin(); conflict_itr != conflict_lanelet_info_v.end(); conflict_itr++)
                {
                    conflict_lanelet_ids.push_back(conflict_itr->id);
                }
                lanelet_info.setConflictLaneletIds(conflict_lanelet_ids);
                lanelet_info.setLength(itr->length);
                link_lanlets.push_back(lanelet_info);
            }
            res.setLinkLanelets(link_lanlets);
            QList<OpenAPI::OAILanelet_info> entry_lanlets;
            for (std::vector<intersection_model::lanelet_info_t>::iterator itr = int_info.entering_lanelets_info.begin(); itr != int_info.entering_lanelets_info.end(); itr++)
            {
                OpenAPI::OAILanelet_info lanelet_info;
                lanelet_info.setId(itr->id);
                lanelet_info.setSpeedLimit(itr->speed_limit);
                lanelet_info.setLength(itr->length);
                QList<qint32> conn_lanelet_ids;
                for(const auto & conn_lane_id: itr->connecting_lanelet_ids)
                {
                    conn_lanelet_ids.push_back(conn_lane_id);
                }
                lanelet_info.setConnectingLaneletIds(conn_lanelet_ids);
                entry_lanlets.push_back(lanelet_info);
            }
            res.setEntryLanelets(entry_lanlets);
            reqObj->getIntersectionInfoResponse(res);
        }
    }
References intersection_model::intersection_info_t::departure_lanelets_info, intersection_model::intersection_info_t::entering_lanelets_info, int_worker_, intersection_model::intersection_info_t::link_lanelets_info, OpenAPI::OAILanelet_info::setConflictLaneletIds(), OpenAPI::OAILanelet_info::setConnectingLaneletIds(), OpenAPI::OAIIntersection_info::setDepartureLanelets(), OpenAPI::OAIIntersection_info::setEntryLanelets(), OpenAPI::OAIIntersection_info::setId(), OpenAPI::OAILanelet_info::setId(), OpenAPI::OAILanelet_info::setLength(), OpenAPI::OAIIntersection_info::setLinkLanelets(), OpenAPI::OAIIntersection_info::setName(), OpenAPI::OAILanelet_info::setSignalGroupId(), and OpenAPI::OAILanelet_info::setSpeedLimit().
listDepartureLanelets
void IntersectionModelAPI::IntersectionModelHandler::listDepartureLanelets () override virtual slot
Get the list of departure lanelets for the intersection.
Definition at line 72 of file IntersectionModelHandler.cpp.
    {
        auto reqObj = qobject_cast<OpenAPI::OAIDefaultApiRequest *>(sender());
        if (reqObj != nullptr)
        {
            QList<OpenAPI::OAILanelet_info> res;
            std::set<intersection_model::lanelet_info_t> departure_lanelet_v = int_worker_->get_departure_lanelets_info();
            for (std::set<intersection_model::lanelet_info_t>::iterator itr = departure_lanelet_v.begin(); itr != departure_lanelet_v.end(); itr++)
            {
                OpenAPI::OAILanelet_info lanelet_info;
                lanelet_info.setId(itr->id);
                lanelet_info.setSpeedLimit(itr->speed_limit);
                lanelet_info.setLength(itr->length);
                res.push_back(lanelet_info);
            }
            reqObj->listDepartureLaneletsResponse(res);
        }
    }
References int_worker_, OpenAPI::OAILanelet_info::setId(), OpenAPI::OAILanelet_info::setLength(), and OpenAPI::OAILanelet_info::setSpeedLimit().
listEntryLanelets
void IntersectionModelAPI::IntersectionModelHandler::listEntryLanelets () override virtual slot
Get the list of entry lanelets for the intersection.
Definition at line 91 of file IntersectionModelHandler.cpp.
    {
        auto reqObj = qobject_cast<OpenAPI::OAIDefaultApiRequest *>(sender());
        if (reqObj != nullptr)
        {
            QList<OpenAPI::OAILanelet_info> res;
            std::vector<intersection_model::lanelet_info_t> entry_lanelet_v = int_worker_->get_entry_lanelets_info();
            for (std::vector<intersection_model::lanelet_info_t>::iterator itr = entry_lanelet_v.begin(); itr != entry_lanelet_v.end(); itr++)
            {
                OpenAPI::OAILanelet_info lanelet_info;
                lanelet_info.setId(itr->id);
                lanelet_info.setSpeedLimit(itr->speed_limit);
                lanelet_info.setLength(itr->length);
                QList<qint32> conn_lanelet_ids;
                for(const auto & conn_lane_id: itr->connecting_lanelet_ids)
                {
                    conn_lanelet_ids.push_back(conn_lane_id);
                }
                lanelet_info.setConnectingLaneletIds(conn_lanelet_ids);
                res.push_back(lanelet_info);
            }
            reqObj->listEntryLaneletsResponse(res);
        }
    }
References int_worker_, OpenAPI::OAILanelet_info::setConnectingLaneletIds(), OpenAPI::OAILanelet_info::setId(), OpenAPI::OAILanelet_info::setLength(), and OpenAPI::OAILanelet_info::setSpeedLimit().
listLinkLanelets
void IntersectionModelAPI::IntersectionModelHandler::listLinkLanelets () override virtual slot
Get the list of link lanelets for the intersection.
Definition at line 116 of file IntersectionModelHandler.cpp.
    {
        auto reqObj = qobject_cast<OpenAPI::OAIDefaultApiRequest *>(sender());
        if (reqObj != nullptr)
        {
            QList<OpenAPI::OAILanelet_info> res;
            std::vector<intersection_model::lanelet_info_t> link_lanelet_v = int_worker_->get_link_lanelets_info();
            for (std::vector<intersection_model::lanelet_info_t>::iterator itr = link_lanelet_v.begin(); itr != link_lanelet_v.end(); itr++)
            {
                OpenAPI::OAILanelet_info lanelet_info;
                lanelet_info.setId(itr->id);
                lanelet_info.setSpeedLimit(itr->speed_limit);
                lanelet_info.setLength(itr->length);
                lanelet_info.setSignalGroupId(itr->signal_group_id);
                res.push_back(lanelet_info);
            }
            reqObj->listLinkLaneletsResponse(res);
        }
    }
References int_worker_, OpenAPI::OAILanelet_info::setId(), OpenAPI::OAILanelet_info::setLength(), OpenAPI::OAILanelet_info::setSignalGroupId(), and OpenAPI::OAILanelet_info::setSpeedLimit().
Member Data Documentation
int_worker_
std::shared_ptr<intersection_model::intersection_model> IntersectionModelAPI::IntersectionModelHandler::int_worker_ private
Definition at line 15 of file IntersectionModelHandler.h.
Referenced by getConflictLanelets(), getIntersectionInfo(), listDepartureLanelets(), listEntryLanelets(), and listLinkLanelets().
The documentation for this class was generated from the following files:
intersection_model/src/server/src/handlers/IntersectionModelHandler.h
intersection_model/src/server/src/handlers/IntersectionModelHandler.cpp