Carma-streets: traffic_signal_controller_service::tsc_state Class Reference
traffic_signal_controller_service::tsc_state Class Reference
#include <monitor_tsc_state.h>
Public Member Functions
tsc_state (std::shared_ptr< snmp_client > snmp_client)
Constructor for the tsc_state class.
std::unordered_map< int, signal_group_state > & get_signal_group_state_map ()
Return reference to signal group state map.
std::unordered_map< int, int > get_signal_group_to_ped_phase_map ()
Returns a map of signal group ids to pedestrian phases.
const std::unordered_map< int, int > & get_ped_phase_map ()
Returns a map of pedestrian phases to signal group ids.
const std::unordered_map< int, int > & get_vehicle_phase_map ()
Returns a map of pedestrian phases to signal group ids.
int get_phase_number (const int signal_group_id)
Get the phase number using signal group id.
int get_vehicle_signal_group_id (const int phase_number)
Get the signal group id using phase number.Only for vehicle phases.
bool initialize ()
Initialize tsc_state by making SNMP calls to TSC for phase sequence and timing information.
void add_future_movement_events (std::shared_ptr< signal_phase_and_timing::spat > spat_ptr)
Updates spat with future movement events for vehicle phases.
const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > & get_tsc_config_state () const
Returns a pointer to the tsc_config_state.
Private Member Functions
std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > define_tsc_config_state ()
Creates tsc_configuration_state object pointer which is used to forward configuration information required to understand ring and barrier information on the traffic signal controller. This includes signal_group_id, yellow_change duration, red_clearance and concurrent signal groups.
void get_channels (int max_channels, std::vector< int > &vehicle_channels, std::vector< int > &ped_channels) const
Creates vectors of channels (or signal group id) associated with a vehicle phase and a pedestrian. Ignores overlap, ped Overlap, queueJump and other (types defined in NTCIP1202 v03) Expects empty input arguments which are filled in by reference.
std::unordered_map< int, int > get_phases_associated_with_channel (const std::vector< int > &signal_group_ids) const
Creates a map of phases associated with a vehicle phase and a pedestrian phase.
std::vector< std::vector< int > > get_active_ring_sequences (int max_rings, std::unordered_map< int, int > &vehicle_phase_2signalgroup_map, int sequence=1) const
Method for getting populated rings in sequence (default sequence = 1). Sequence table contains multiple sequence plans, consisting of the phase sequence in each ring available in the traffic signal controller. We assume the active sequence plan is sequence number 1 by default.
void map_phase_and_signalgroup (const std::vector< std::vector< int > > &active_ring_sequences, std::unordered_map< int, int > &vehicle_phase_2signalgroup_map, std::unordered_map< int, int > &signal_group_2vehiclephase_map) const
Method for mapping vehicle phases and signal groups. Modifies non-const arguments by reference. Signal group map is expected to be passed empty. Vehicle phase map is expected to contain known vehicle phases. These are modified to only contain phases in the active ring sequence.
int get_max_channels () const
Method for getting maximum channels for the traffic signal controller.
int get_max_rings () const
Method for getting maximum rings for the traffic signal controller.
int get_min_green (int phase_num) const
Get minimum green time for a phase.
int get_max_green (int phase_num) const
Get maximum green time for a phase.
int get_yellow_duration (int phase_num) const
Get yellow duration time for a phase.
int get_red_clearance (int phase_num) const
Get red clearance time for a phase.
int get_red_duration (int phase_num)
Get red duration for a phase.
std::vector< int > get_following_phases (int phase_num, const std::vector< std::vector< int > > &active_ring_sequences) const
Get a sequence of phases following the given phase.
std::vector< int > get_concurrent_signal_groups (int phase_num)
The concurrent phases that the given phase can be green along with.
uint16_t convert_msepoch_to_hour_tenth_secs (uint64_t epoch_time_ms) const
Helper function to convert epoch time to hour-tenths time.
uint64_t convert_hour_tenth_secs2epoch_ts (uint16_t hour_tenth_secs) const
Helper function to convert hour-tenths time to epoch time.
signal_phase_and_timing::movement_event get_following_event (const signal_phase_and_timing::movement_event &current_event, uint64_t current_event_end_time, const signal_group_state &phase_state) const
Get predicted next movement event given a current event.
FRIEND_TEST (test_monitor_state, test_get_following_movement_events)
Private Attributes
std::shared_ptr< snmp_client > snmp_client_worker_
std::unordered_map< int, signal_group_state > signal_group_2tsc_state_map_
std::unordered_map< int, int > signal_group_2vehiclephase_map_
std::unordered_map< int, int > vehicle_phase_2signalgroup_map_
std::unordered_map< int, int > ped_phase_2signalgroup_map_
std::vector< int > phase_seq_ring1_
std::vector< int > phase_seq_ring2_
int required_following_movements_ = 3
int HOUR_TO_SECONDS_ = 3600
int SECOND_TO_MILLISECONDS_ = 1000
std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_config_state_ptr_
Pointer to tsc_configuration_state object which is traffic signal controller configuration information obtained from the tsc_state worker and broadcast on the carma-streets kafka broker as a JSON message.
Detailed Description
Definition at line 39 of file monitor_tsc_state.h.
Constructor & Destructor Documentation
tsc_state()
traffic_signal_controller_service::tsc_state::tsc_state (std::shared_ptr< snmp_client > snmp_client) explicit
Constructor for the tsc_state class.
Parameters
snmp_client A pointer to an snmp_client worker with a connection established to a traffic signal controller
Definition at line 5 of file monitor_tsc_state.cpp.
                                                               : snmp_client_worker_(snmp_client)
    {
    }
Member Function Documentation
add_future_movement_events()
void traffic_signal_controller_service::tsc_state::add_future_movement_events (std::shared_ptr< signal_phase_and_timing::spat > spat_ptr)
Updates spat with future movement events for vehicle phases.
Parameters
spat_ptr pointer to spat message to update
Returns
true if update was successful, false if it failed
Definition at line 150 of file monitor_tsc_state.cpp.
    {
        // Modify spat according to phase configuration
        // Note: Only first intersection is populated
        auto intersection_state = spat_ptr->get_intersection();
        for (auto movement : intersection_state.states)
        {
            int signal_group_id = movement.signal_group;
            // Assumption here is that the movement states have only one event, since this method adds future events to the list.
            //Throw exception is list size is great than 1
            if (movement.state_time_speed.size() > 1)
            {
                SPDLOG_ERROR("Event list has more than one events, not usable when adding future movement events. Associated with Signal Group: {0}", signal_group_id);
                throw monitor_states_exception("Event list has more than one events, not usable when adding future movement events. Associated with Signal Group:" + std::to_string(signal_group_id));
            }
            // Get movement_state by reference
            auto& current_movement = intersection_state.get_movement(signal_group_id);
            // Get start time as epoch time
            uint64_t start_time = movement.state_time_speed.front().timing.get_epoch_start_time();
            // Check if signal_group_id is associated with a vehicle phase : Only vehicle phases mapped to signal_group_states
            signal_group_state phase_state;
            if(signal_group_2tsc_state_map_.find(signal_group_id) == signal_group_2tsc_state_map_.end()){
                continue;
            }
            phase_state = signal_group_2tsc_state_map_[signal_group_id];
            uint64_t current_event_end_time_epoch = 0;
            signal_phase_and_timing::movement_event current_event = current_movement.state_time_speed.front();
            switch(current_event.event_state){
                case signal_phase_and_timing::movement_phase_state::stop_and_remain : //Red
                    current_event_end_time_epoch = start_time + phase_state.red_duration;
                    break;
                case signal_phase_and_timing::movement_phase_state::protected_movement_allowed : //Green
                    current_event_end_time_epoch = start_time + phase_state.green_duration;
                    break;
                case signal_phase_and_timing::movement_phase_state::protected_clearance : //Yellow
                    current_event_end_time_epoch = start_time + phase_state.yellow_duration;
                    break;
                default:
                    SPDLOG_DEBUG("This movement phase is not supported. Movement phase type: {0}", int(current_movement.state_time_speed.front().event_state));
                    throw monitor_states_exception("This movement phase is not supported. Movement phase type: " + std::to_string(int(current_movement.state_time_speed.front().event_state)));
            }
            // Update end_time for current_event
            current_movement.state_time_speed.front().timing.min_end_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time_epoch);
            current_movement.state_time_speed.front().timing.max_end_time = current_movement.state_time_speed.front().timing.min_end_time;
            for(int i = 0; i < required_following_movements_; ++i)
            {
                signal_phase_and_timing::movement_event next_event = get_following_event(current_event, current_event_end_time_epoch, phase_state);
                current_event = next_event;
                current_event_end_time_epoch = convert_hour_tenth_secs2epoch_ts(current_event.timing.min_end_time);
                //Add events to list
                current_movement.state_time_speed.push_back(next_event);
            }
        }
        spat_ptr->set_intersection(intersection_state);
    }
References convert_hour_tenth_secs2epoch_ts(), convert_msepoch_to_hour_tenth_secs(), signal_phase_and_timing::movement_event::event_state, get_following_event(), traffic_signal_controller_service::signal_group_state::green_duration, simulate_bsm::i, signal_phase_and_timing::time_change_details::min_end_time, signal_phase_and_timing::protected_clearance, signal_phase_and_timing::protected_movement_allowed, traffic_signal_controller_service::signal_group_state::red_duration, required_following_movements_, signal_group_2tsc_state_map_, signal_phase_and_timing::stop_and_remain, signal_phase_and_timing::movement_event::timing, to_string(), and traffic_signal_controller_service::signal_group_state::yellow_duration.
convert_hour_tenth_secs2epoch_ts()
uint64_t traffic_signal_controller_service::tsc_state::convert_hour_tenth_secs2epoch_ts (uint16_t hour_tenth_secs) const private
Helper function to convert hour-tenths time to epoch time.
Parameters
hour_tenth_secs tenths of a second in current or next hour
Returns
epoch time in milliseconds
Definition at line 574 of file monitor_tsc_state.cpp.
{
        auto tp = std::chrono::system_clock::now();
        auto duration = tp.time_since_epoch();
        auto hours_since_epoch = std::chrono::duration_cast<std::chrono::hours>(duration).count();
        auto epoch_start_time = hours_since_epoch * HOUR_TO_SECONDS_ * SECOND_TO_MILLISECONDS_ + hour_tenth_secs * 100;
        return epoch_start_time;
    }
References HOUR_TO_SECONDS_, and SECOND_TO_MILLISECONDS_.
Referenced by add_future_movement_events().
convert_msepoch_to_hour_tenth_secs()
uint16_t traffic_signal_controller_service::tsc_state::convert_msepoch_to_hour_tenth_secs (uint64_t epoch_time_ms) const private
Helper function to convert epoch time to hour-tenths time.
Parameters
epoch_time_ms epoch time in milliseconds
Returns
tenths of a second in current or next hour
Definition at line 566 of file monitor_tsc_state.cpp.
{
        auto system_time = std::chrono::system_clock::now();
        auto duration = system_time.time_since_epoch();
        auto hours_since_epoch = std::chrono::duration_cast<std::chrono::hours>(duration).count();
        auto hour_tenth_secs = (epoch_time_ms - (hours_since_epoch * HOUR_TO_SECONDS_ * SECOND_TO_MILLISECONDS_))/100;
        return static_cast<uint16_t>(hour_tenth_secs);
    }
References HOUR_TO_SECONDS_, and SECOND_TO_MILLISECONDS_.
Referenced by add_future_movement_events(), and get_following_event().
define_tsc_config_state()
std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > traffic_signal_controller_service::tsc_state::define_tsc_config_state () private
Creates tsc_configuration_state object pointer which is used to forward configuration information required to understand ring and barrier information on the traffic signal controller. This includes signal_group_id, yellow_change duration, red_clearance and concurrent signal groups.
Returns
shared ptr to tsc_config state
Definition at line 94 of file monitor_tsc_state.cpp.
    {
        streets_tsc_configuration::tsc_configuration_state tsc_config;
        for (const auto& [signal_group, state] : signal_group_2tsc_state_map_)
        {
            streets_tsc_configuration::signal_group_configuration signal_group_config;
            signal_group_config.signal_group_id = static_cast<uint8_t>(signal_group);
            signal_group_config.yellow_change_duration = static_cast<uint16_t>(state.yellow_duration);
            signal_group_config.red_clearance = static_cast<uint16_t>(state.red_clearance);
            for(auto concurrent_signal_group : state.concurrent_signal_groups){
                signal_group_config.concurrent_signal_groups.push_back(static_cast<uint8_t>(concurrent_signal_group));
            }
            tsc_config.tsc_config_list.push_back(signal_group_config);
        }
        return std::make_shared<streets_tsc_configuration::tsc_configuration_state>(tsc_config);
    }
References streets_tsc_configuration::signal_group_configuration::concurrent_signal_groups, streets_tsc_configuration::signal_group_configuration::red_clearance, signal_group_2tsc_state_map_, streets_tsc_configuration::signal_group_configuration::signal_group_id, streets_tsc_configuration::tsc_configuration_state::tsc_config_list, and streets_tsc_configuration::signal_group_configuration::yellow_change_duration.
Referenced by initialize().
FRIEND_TEST()
traffic_signal_controller_service::tsc_state::FRIEND_TEST (test_monitor_state , test_get_following_movement_events) private
get_active_ring_sequences()
std::vector< std::vector< int > > traffic_signal_controller_service::tsc_state::get_active_ring_sequences (int max_rings, std::unordered_map< int, int > & vehicle_phase_2signalgroup_map, int sequence = 1) const private
Method for getting populated rings in sequence (default sequence = 1). Sequence table contains multiple sequence plans, consisting of the phase sequence in each ring available in the traffic signal controller. We assume the active sequence plan is sequence number 1 by default.
Parameters
max_rings Maximum number of rings in the traffic signal controller
vehicle_phase_2signalgroup_map a map for all vehicle phases and signal groups associated with them
sequence The sequence number to check for active rings, defaults to 1
Returns
List of active rings in the traffic signal controller
Definition at line 341 of file monitor_tsc_state.cpp.
{
        std::vector<std::vector<int>> active_ring_sequences;
        // Read sequence data for rings
        request_type request_type = request_type::GET;
        for(int i = 1 ; i <= max_rings; ++i){
            int ring_num = i;
            std::vector<int> phase_seq;
            std::string phase_seq_oid= ntcip_oids::SEQUENCE_DATA + "." + std::to_string(sequence) + "." + std::to_string(ring_num);
            snmp_response_obj seq_data;
            seq_data.type = snmp_response_obj::response_type::STRING;
            snmp_client_worker_->process_snmp_request(phase_seq_oid, request_type, seq_data);
            //extract phase numbers from strings
            for(auto seq_val : seq_data.val_string)
            {
                auto phase = int(seq_val);
                if(vehicle_phase_2signalgroup_map.find(phase)!= vehicle_phase_2signalgroup_map.end() && phase != 0 ){
                    phase_seq.push_back(phase);
                }
            }
            if (!phase_seq.empty())
            {
                active_ring_sequences.push_back(phase_seq);
            }
            else{
                SPDLOG_DEBUG("No phases found in sequence {0} for ring {1}", sequence, ring_num);
            }
        }
        return active_ring_sequences;
    }
References traffic_signal_controller_service::GET, simulate_bsm::i, ntcip_oids::SEQUENCE_DATA, snmp_client_worker_, traffic_signal_controller_service::snmp_response_obj::STRING, to_string(), traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_string.
Referenced by initialize().
get_channels()
void traffic_signal_controller_service::tsc_state::get_channels (int max_channels, std::vector< int > & vehicle_channels, std::vector< int > & ped_channels) const private
Creates vectors of channels (or signal group id) associated with a vehicle phase and a pedestrian. Ignores overlap, ped Overlap, queueJump and other (types defined in NTCIP1202 v03) Expects empty input arguments which are filled in by reference.
Parameters
max_channels The maximum number of channels in the traffic signal controller.
vehicle_channels a vector of active vehicle phases associated with a channel
ped_channels a vector of active pedestrian phases associated with a channel
Definition at line 300 of file monitor_tsc_state.cpp.
{
        // Loop through channel control types and add channels with vehicle phase to list
        snmp_response_obj control_type;
        control_type.type = snmp_response_obj::response_type::INTEGER;
        request_type request_type = request_type::GET;
        for(int channel_num = 1; channel_num <= max_channels; ++channel_num)
        {
            std::string control_type_parameter_oid = ntcip_oids::CHANNEL_CONTROL_TYPE_PARAMETER + "." + std::to_string(channel_num);
            if(!snmp_client_worker_->process_snmp_request(control_type_parameter_oid, request_type, control_type))
            {
                throw snmp_client_exception("Failed to get channel control type");
            }
            if(control_type.val_int == 2) // If 2, phase is a vehicle phase
            {
                vehicle_channels.push_back(channel_num);
            }
            else if(control_type.val_int == 3) //If 3, phase is a pedestrian phase
            {
                ped_channels.push_back(channel_num);
            }
        }
        if(vehicle_channels.empty()){
            SPDLOG_WARN("Found no vehicle phases");
        }
        if(ped_channels.empty()){
            SPDLOG_DEBUG("Found no ped phases");
        }
        SPDLOG_DEBUG("Number of vehicle phase channels found: {0}", vehicle_channels.size());
        SPDLOG_DEBUG("Number of ped phase channels found: {0}", ped_channels.size());
    }
References ntcip_oids::CHANNEL_CONTROL_TYPE_PARAMETER, traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, snmp_client_worker_, to_string(), traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_int.
Referenced by initialize().
get_concurrent_signal_groups()
std::vector< int > traffic_signal_controller_service::tsc_state::get_concurrent_signal_groups (int phase_num) private
The concurrent phases that the given phase can be green along with.
Parameters
ring_num The phase for which the concurrent phases needs to be obtained
Returns
a vector of phases that may be concurrent with the given phase
Definition at line 513 of file monitor_tsc_state.cpp.
    {
        std::vector<int> concurrent_signal_groups;
        std::string concurrent_phases_oid = ntcip_oids::PHASE_CONCURRENCY + "." + std::to_string(phase_num);
        snmp_response_obj concurrent_phase_data;
        request_type request_type = request_type::GET;
        concurrent_phase_data.type = snmp_response_obj::response_type::STRING;
        snmp_client_worker_->process_snmp_request(concurrent_phases_oid, request_type, concurrent_phase_data);
        //extract phase numbers from strings
        for(auto con_phase :  concurrent_phase_data.val_string)
        {   if(con_phase != 0){
                concurrent_signal_groups.push_back(get_vehicle_signal_group_id(int(con_phase)));
            }
        }
        if(concurrent_signal_groups.empty())
        {
            SPDLOG_WARN("No concurrent signal groups found for phase {0}", phase_num);
        }
        return concurrent_signal_groups;
    }
References traffic_signal_controller_service::GET, get_vehicle_signal_group_id(), ntcip_oids::PHASE_CONCURRENCY, snmp_client_worker_, traffic_signal_controller_service::snmp_response_obj::STRING, to_string(), traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_string.
Referenced by initialize().
get_following_event()
signal_phase_and_timing::movement_event traffic_signal_controller_service::tsc_state::get_following_event (const signal_phase_and_timing::movement_event & current_event, uint64_t current_event_end_time, const signal_group_state & phase_state) const private
Get predicted next movement event given a current event.
Parameters
current_event movement_event from the next movement needs to be predicted
current_event_end_time End time of the current event in epoch time (milliseconds)
phase_state signal_group_state for the phase of which the movement events are a part
Returns
predicted next movement event
Definition at line 116 of file monitor_tsc_state.cpp.
    {
        signal_phase_and_timing::movement_event next_event;
        switch (current_event.event_state){
            case signal_phase_and_timing::movement_phase_state::protected_movement_allowed: //Green
                // Create next movement - yellow
                next_event.event_state = signal_phase_and_timing::movement_phase_state::protected_clearance;
                next_event.timing.start_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time);
                next_event.timing.min_end_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time + phase_state.yellow_duration);
                break;
            case signal_phase_and_timing::movement_phase_state::protected_clearance: //Yellow
                // Create next movement - red
                next_event.event_state = signal_phase_and_timing::movement_phase_state::stop_and_remain;
                next_event.timing.start_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time);
                next_event.timing.min_end_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time + phase_state.red_duration);
                break;
            case signal_phase_and_timing::movement_phase_state::stop_and_remain:  //Red
                // Create next movement - green
                next_event.event_state = signal_phase_and_timing::movement_phase_state::protected_movement_allowed;
                next_event.timing.start_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time);
                next_event.timing.min_end_time = convert_msepoch_to_hour_tenth_secs(current_event_end_time + phase_state.green_duration);
                break;
            default:
                SPDLOG_ERROR("This movement phase is not supported. Movement phase type: {0}", int(current_event.event_state));
                throw snmp_client_exception("Failed request for unsupported movement phase type: " + std::to_string(int(current_event.event_state)));
        }
        next_event.timing.max_end_time = next_event.timing.min_end_time;
        return next_event;
    }
References convert_msepoch_to_hour_tenth_secs(), signal_phase_and_timing::movement_event::event_state, traffic_signal_controller_service::signal_group_state::green_duration, signal_phase_and_timing::time_change_details::max_end_time, signal_phase_and_timing::time_change_details::min_end_time, signal_phase_and_timing::protected_clearance, signal_phase_and_timing::protected_movement_allowed, traffic_signal_controller_service::signal_group_state::red_duration, signal_phase_and_timing::time_change_details::start_time, signal_phase_and_timing::stop_and_remain, signal_phase_and_timing::movement_event::timing, to_string(), and traffic_signal_controller_service::signal_group_state::yellow_duration.
Referenced by add_future_movement_events().
get_following_phases()
std::vector< int > traffic_signal_controller_service::tsc_state::get_following_phases (int phase_num, const std::vector< std::vector< int > > & active_ring_sequences) const private
Get a sequence of phases following the given phase.
Parameters
phase_num The phase for which the sequence needs to be obtained
active_ring_sequences The sequence of phases in active rings in the traffic signal controller
Returns
a vector as a sequence of phases starting from the given phase
Definition at line 219 of file monitor_tsc_state.cpp.
    {
        std::vector<int> sequence;
        for(auto ring : active_ring_sequences)
        {
            for (int i = 0; i < ring.size(); ++i)
            {
                if (ring[i] == phase_num)
                {
                    sequence.insert(sequence.begin(), ring.begin() + i, ring.end());
                    sequence.insert(sequence.end(), ring.begin(), ring.begin() + i);
                    return sequence;
                }
            }
        }
        // No following phase information found
        throw snmp_client_exception("No following phases found");
    }
References simulate_bsm::i.
Referenced by initialize().
get_max_channels()
int traffic_signal_controller_service::tsc_state::get_max_channels () const private
Method for getting maximum channels for the traffic signal controller.
Returns
number of maximum channels in the traffic signal controller
Definition at line 391 of file monitor_tsc_state.cpp.
{
        request_type request_type = request_type::GET;
        snmp_response_obj max_channels_in_tsc;
        max_channels_in_tsc.type = snmp_response_obj::response_type::INTEGER;
        if(!snmp_client_worker_->process_snmp_request(ntcip_oids::MAX_CHANNELS, request_type, max_channels_in_tsc))
        {
            throw snmp_client_exception("Failed to get max channels!");
        }
        return (int) max_channels_in_tsc.val_int;
    }
References traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, ntcip_oids::MAX_CHANNELS, snmp_client_worker_, traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_int.
Referenced by initialize().
get_max_green()
int traffic_signal_controller_service::tsc_state::get_max_green (int phase_num) const private
Get maximum green time for a phase.
Parameters
phase_num The phase for which the maximum green needs to be requested
Returns
maximum green time in milliseconds
Definition at line 445 of file monitor_tsc_state.cpp.
    {
        request_type request_type = request_type::GET;
        std::string max_green_parameter_oid = ntcip_oids::MAXIMUM_GREEN + "." + std::to_string(phase_num);
        snmp_response_obj max_green;
        max_green.type = snmp_response_obj::response_type::INTEGER;
        snmp_client_worker_->process_snmp_request(max_green_parameter_oid, request_type, max_green);
        return (int) max_green.val_int * 1000; //Convert seconds to milliseconds
    }
References traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, ntcip_oids::MAXIMUM_GREEN, snmp_client_worker_, to_string(), traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_int.
Referenced by initialize().
get_max_rings()
int traffic_signal_controller_service::tsc_state::get_max_rings () const private
Method for getting maximum rings for the traffic signal controller.
Returns
number of maximum rings in the traffic signal controller
Definition at line 378 of file monitor_tsc_state.cpp.
{
        request_type request_type = request_type::GET;
        snmp_response_obj max_rings_in_tsc;
        max_rings_in_tsc.type = snmp_response_obj::response_type::INTEGER;
        if(!snmp_client_worker_->process_snmp_request(ntcip_oids::MAX_RINGS, request_type, max_rings_in_tsc))
        {
            throw snmp_client_exception("Failed to get max rings!");
        }
        return (int) max_rings_in_tsc.val_int;
    }
References traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, ntcip_oids::MAX_RINGS, snmp_client_worker_, traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_int.
Referenced by initialize().
get_min_green()
int traffic_signal_controller_service::tsc_state::get_min_green (int phase_num) const private
Get minimum green time for a phase.
Parameters
phase_num The phase for which the min green needs to be requested
Returns
minimum green time in milliseconds
Definition at line 432 of file monitor_tsc_state.cpp.
    {
        request_type request_type = request_type::GET;
        std::string min_green_parameter_oid = ntcip_oids::MINIMUM_GREEN + "." + std::to_string(phase_num);
        snmp_response_obj min_green;
        min_green.type = snmp_response_obj::response_type::INTEGER;
        snmp_client_worker_->process_snmp_request(min_green_parameter_oid, request_type, min_green);
        return (int) min_green.val_int * 1000; //Convert seconds to milliseconds
    }
References traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, ntcip_oids::MINIMUM_GREEN, snmp_client_worker_, to_string(), traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_int.
Referenced by initialize().
get_ped_phase_map()
const std::unordered_map< int, int > & traffic_signal_controller_service::tsc_state::get_ped_phase_map ()
Returns a map of pedestrian phases to signal group ids.
Returns
a map of pedestrian phases to signal group ids
Definition at line 539 of file monitor_tsc_state.cpp.
    {
        return ped_phase_2signalgroup_map_;
    }
References ped_phase_2signalgroup_map_.
get_phase_number()
int traffic_signal_controller_service::tsc_state::get_phase_number (const int signal_group_id)
Get the phase number using signal group id.
Parameters
signal_group_id
Returns
int
Exceptions
monitor_states_exception if signal group id is less than 1.
Definition at line 404 of file monitor_tsc_state.cpp.
{
        if (signal_group_id >= 1) {
            if ( signal_group_2vehiclephase_map_.find(signal_group_id) != signal_group_2vehiclephase_map_.end() ) {
                return signal_group_2vehiclephase_map_[signal_group_id];
            }
            else {
                throw monitor_states_exception("No phase number found for signal id " + std::to_string(signal_group_id) + "!");
            }
        }
        else {
            throw monitor_states_exception("Signal group ids less than 1 are invalid!");
        }
    }
References signal_group_2vehiclephase_map_, and to_string().
get_phases_associated_with_channel()
std::unordered_map< int, int > traffic_signal_controller_service::tsc_state::get_phases_associated_with_channel (const std::vector< int > & signal_group_ids) const private
Creates a map of phases associated with a vehicle phase and a pedestrian phase.
Parameters
signal_group_ids a map of known signal_group_ids/channels for vehicle or pedestrian to the corresponding phases
Returns
a mapping from phases to signal_group ids. Will return empty map if no phases associated with a vehicle or pedestrian are found.
Definition at line 271 of file monitor_tsc_state.cpp.
{
        std::unordered_map<int,int> phases_to_signal_group;
        request_type request_type = request_type::GET;
        for(int signal_group : signal_group_ids)
        {
            snmp_response_obj phase_num;
            phase_num.type = snmp_response_obj::response_type::INTEGER;
            // Control source returns the phase associated with the signal group. Channel and signal group id is synonymous according to the NTCIP documentation
            std::string control_source_parameter_oid = ntcip_oids::CHANNEL_CONTROL_SOURCE_PARAMETER + "." + std::to_string(signal_group);
            snmp_client_worker_->process_snmp_request(control_source_parameter_oid, request_type, phase_num);
            // According to NTCIP 1202 v03 returned value of 0 here would mean a phase is not associated with the signal_group
            if(phase_num.val_int != 0)
            {
                phases_to_signal_group.insert(std::make_pair(phase_num.val_int, signal_group));
            }
            else{
                throw monitor_states_exception("No phase found associated with signal_group {0}" + std::to_string(signal_group));
            }
            SPDLOG_TRACE("Found mapping between signal group: {0} and phase num: {1}", signal_group , phase_num.val_int );
        }
        return phases_to_signal_group;
    }
References ntcip_oids::CHANNEL_CONTROL_SOURCE_PARAMETER, traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, snmp_client_worker_, to_string(), traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_int.
Referenced by initialize().
get_red_clearance()
int traffic_signal_controller_service::tsc_state::get_red_clearance (int phase_num) const private
Get red clearance time for a phase.
Parameters
phase_num The phase for which the red clearance needs to be requested
Returns
red clearance time in milliseconds
Definition at line 471 of file monitor_tsc_state.cpp.
    {
        request_type get_request = request_type::GET;
        std::string red_clearance_oid = ntcip_oids::RED_CLEAR_PARAMETER + "." + std::to_string(phase_num);
        snmp_response_obj red_clearance;
        red_clearance.type = snmp_response_obj::response_type::INTEGER;
        snmp_client_worker_->process_snmp_request(red_clearance_oid, get_request, red_clearance);
        return (int) red_clearance.val_int * 100; //Convert to milliseconds. NTCIP returned value is in tenths of seconds
    }
References traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, ntcip_oids::RED_CLEAR_PARAMETER, snmp_client_worker_, to_string(), traffic_signal_controller_service::snmp_response_obj::type, and traffic_signal_controller_service::snmp_response_obj::val_int.
Referenced by initialize().
get_red_duration()
int traffic_signal_controller_service::tsc_state::get_red_duration (int phase_num) private
Get red duration for a phase.
Parameters
phase_num The phase for which the red duration needs to be requested
Returns
red duration time in milliseconds
Definition at line 484 of file monitor_tsc_state.cpp.
    {
        //red duration is calculated as red_clearance time for current phase + (green duration + yellow duration + red_clearance) for other phases in sequence
        // Find signal state associated with phase num
        int current_signal_group;
        current_signal_group = get_vehicle_signal_group_id(phase_num);
        auto current_signal_group_state = signal_group_2tsc_state_map_[current_signal_group];
        // Only add clearance time for current phase
        int red_duration = current_signal_group_state.red_clearance;
        for(auto phase : current_signal_group_state.phase_seq)
        {
            // Find state params for each phase in seq
            int seq_signal_group;
            seq_signal_group = get_vehicle_signal_group_id(phase);
            auto seq_signal_group_state = signal_group_2tsc_state_map_[seq_signal_group];
            if(phase == phase_num)
            {
                continue;
            }
            else{
                red_duration += seq_signal_group_state.green_duration + seq_signal_group_state.yellow_duration + seq_signal_group_state.red_clearance;
            }
        }
        return red_duration;
    }
References get_vehicle_signal_group_id(), and signal_group_2tsc_state_map_.
Referenced by initialize().
get_signal_group_state_map()
std::unordered_map< int, signal_group_state > & traffic_signal_controller_service::tsc_state::get_signal_group_state_map ()
Return reference to signal group state map.
Returns
std::unordered_map<int, signal_group_state>&
Definition at line 549 of file monitor_tsc_state.cpp.
    {
        return signal_group_2tsc_state_map_;
    }
References signal_group_2tsc_state_map_.
get_signal_group_to_ped_phase_map()
std::unordered_map< int, int > traffic_signal_controller_service::tsc_state::get_signal_group_to_ped_phase_map ()
Returns a map of signal group ids to pedestrian phases.
Returns
a map of signal group ids to pedestrian phases
Definition at line 554 of file monitor_tsc_state.cpp.
    {
        std::unordered_map<int,int> signal_group_to_ped_phase;
        for(auto it = ped_phase_2signalgroup_map_.begin(); it != ped_phase_2signalgroup_map_.end();){
            signal_group_to_ped_phase.insert(std::make_pair(it->second,it->first));
        }
        return signal_group_to_ped_phase;
    }
References ped_phase_2signalgroup_map_.
get_tsc_config_state()
const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > & traffic_signal_controller_service::tsc_state::get_tsc_config_state () const
Returns a pointer to the tsc_config_state.
Returns
pointer to the tsc_configuration_state used to forward configuration information required to understand ring and barrier information on the traffic signal controller. This includes signal_group_id, yellow_change duration, red_clearance and concurrent signal groups
Definition at line 111 of file monitor_tsc_state.cpp.
    {
        return tsc_config_state_ptr_;
    }
References tsc_config_state_ptr_.
get_vehicle_phase_map()
const std::unordered_map< int, int > & traffic_signal_controller_service::tsc_state::get_vehicle_phase_map ()
Returns a map of pedestrian phases to signal group ids.
Returns
a map of pedestrian phases to signal group ids
Definition at line 544 of file monitor_tsc_state.cpp.
    {
        return vehicle_phase_2signalgroup_map_;
    }
References vehicle_phase_2signalgroup_map_.
get_vehicle_signal_group_id()
int traffic_signal_controller_service::tsc_state::get_vehicle_signal_group_id (const int phase_number)
Get the signal group id using phase number.Only for vehicle phases.
Parameters
phase_number
Returns
int
Exceptions
monitor_states_exception if phase number is less than 1.
Definition at line 418 of file monitor_tsc_state.cpp.
{
        if (phase_number >= 1) {
            if ( vehicle_phase_2signalgroup_map_.find(phase_number) != vehicle_phase_2signalgroup_map_.end() ) {
                return vehicle_phase_2signalgroup_map_[phase_number];
            }
            else {
                throw monitor_states_exception("No signal group id found for phase number " + std::to_string(phase_number) + "!");
            }
        }
        else {
            throw monitor_states_exception("Phase numbers less than 1 are invalid!");
        }
    }
References phase_number, to_string(), and vehicle_phase_2signalgroup_map_.
Referenced by get_concurrent_signal_groups(), and get_red_duration().
get_yellow_duration()
int traffic_signal_controller_service::tsc_state::get_yellow_duration (int phase_num) const private
Get yellow duration time for a phase.
Parameters
phase_num The phase for which the yellow duration needs to be requested
Returns
yellow duration time in milliseconds
Definition at line 458 of file monitor_tsc_state.cpp.
    {
        request_type request_type = request_type::GET;
        std::string yellow_duration_oid = ntcip_oids::YELLOW_CHANGE_PARAMETER + "." + std::to_string(phase_num);
        snmp_response_obj yellow_duration;
        yellow_duration.type = snmp_response_obj::response_type::INTEGER;
        snmp_client_worker_ ->process_snmp_request(yellow_duration_oid, request_type, yellow_duration);
        return (int) yellow_duration.val_int * 100; //Convert to milliseconds. NTCIP returned value is in tenths of seconds
    }
References traffic_signal_controller_service::GET, traffic_signal_controller_service::snmp_response_obj::INTEGER, snmp_client_worker_, to_string(), traffic_signal_controller_service::snmp_response_obj::type, traffic_signal_controller_service::snmp_response_obj::val_int, and ntcip_oids::YELLOW_CHANGE_PARAMETER.
Referenced by initialize().
initialize()
bool traffic_signal_controller_service::tsc_state::initialize ()
Initialize tsc_state by making SNMP calls to TSC for phase sequence and timing information.
Returns
true if initialization is successful.
Definition at line 10 of file monitor_tsc_state.cpp.
{
        try {
            // Map signal group ids and phase nums
            //Get phase number given a signal group id
            int max_channels_in_tsc = get_max_channels();
            // Loop through all channels and check which are associated with a vehicle phase and pedestrian phase
            std::vector<int> vehicle_channels;
            std::vector<int> ped_channels;
            // Get channel source for each channel in TSC and allocate to vehicle/ped depending on source type
            get_channels(max_channels_in_tsc, vehicle_channels, ped_channels);
            // Get Phases associated with vehicle channels and pedestrian channels
            vehicle_phase_2signalgroup_map_ = get_phases_associated_with_channel(vehicle_channels);
            ped_phase_2signalgroup_map_ = get_phases_associated_with_channel(ped_channels);
            int max_rings_in_tsc = get_max_rings();
            // Get vehicle sequence for active phases. By default in sequence 1
            std::vector<std::vector<int>> active_ring_sequences = get_active_ring_sequences(max_rings_in_tsc, vehicle_phase_2signalgroup_map_);
            // Update vehicle phase map to only include phases in active ring sequence. Also construct signal group to vehicle phase map
            map_phase_and_signalgroup(active_ring_sequences, vehicle_phase_2signalgroup_map_, signal_group_2vehiclephase_map_);
            // Define state for each signal group
            for (const auto& [signal_group, vehicle_phase] : signal_group_2vehiclephase_map_)
            {
                int phase_num = vehicle_phase;
                signal_group_state state;
                state.phase_num = phase_num;
                state.max_green = get_max_green(phase_num);
                state.min_green = get_min_green(phase_num);
                state.yellow_duration = get_yellow_duration(phase_num);
                // Define green duration as min/max as decided in configuration
                state.green_duration = state.min_green;
                state.red_clearance = get_red_clearance(phase_num);
                state.phase_seq = get_following_phases(phase_num, active_ring_sequences);
                state.concurrent_signal_groups = get_concurrent_signal_groups(phase_num);
                auto pair = std::make_pair(signal_group, state);
                signal_group_2tsc_state_map_.insert(pair);
            }
            // Loop through states once other state parameters are defined to get the red duration
            for(auto& [signalgroup_id, state] : signal_group_2tsc_state_map_)
            {
                state.red_duration = get_red_duration(state.phase_num);
            }
            // Define tsc config state - Needed to construct message sent to SO service
            tsc_config_state_ptr_ = define_tsc_config_state();
            // Print signal_group map
            for (const auto& [signalgroup_id, phase] : signal_group_2vehiclephase_map_)
            {
                SPDLOG_DEBUG("Signal group id: {0} phase: {1}", signalgroup_id, phase);
            }
            // Print state map
            for (const auto& [signalgroup_id, state] : signal_group_2tsc_state_map_)
            {
                SPDLOG_DEBUG("Signal group id: {0}", signalgroup_id);
                SPDLOG_DEBUG("Phase num: {0}", state.phase_num);
                SPDLOG_DEBUG("Max green: {0}", state.max_green);
                SPDLOG_DEBUG("Min green: {0}", state.min_green);
                SPDLOG_DEBUG("Green Duration: {0}", state.green_duration);
                SPDLOG_DEBUG("yellow duration: {0}", state.yellow_duration);
                SPDLOG_DEBUG("Red clearance: {0}", state.red_clearance);
                SPDLOG_DEBUG("Red duration: {0}", state.red_duration);
                SPDLOG_DEBUG("Phase sequence:");
                for(auto phase : state.phase_seq){
                    SPDLOG_DEBUG("{0}", phase);
                }
                SPDLOG_DEBUG("Concurrent Signal Groups:");
                for(auto signal_group : state.concurrent_signal_groups){
                    SPDLOG_DEBUG("{0}", signal_group);
                }
            }
            return true;
        }catch ( const snmp_client_exception &e ) {
            SPDLOG_ERROR("Exception encounters during initialization: \n {0}",e.what());
            return false;
        }
    }
References traffic_signal_controller_service::signal_group_state::concurrent_signal_groups, define_tsc_config_state(), get_active_ring_sequences(), get_channels(), get_concurrent_signal_groups(), get_following_phases(), get_max_channels(), get_max_green(), get_max_rings(), get_min_green(), get_phases_associated_with_channel(), get_red_clearance(), get_red_duration(), get_yellow_duration(), traffic_signal_controller_service::signal_group_state::green_duration, map_phase_and_signalgroup(), traffic_signal_controller_service::signal_group_state::max_green, traffic_signal_controller_service::signal_group_state::min_green, ped_phase_2signalgroup_map_, traffic_signal_controller_service::signal_group_state::phase_num, traffic_signal_controller_service::signal_group_state::phase_seq, traffic_signal_controller_service::signal_group_state::red_clearance, signal_group_2tsc_state_map_, signal_group_2vehiclephase_map_, tsc_config_state_ptr_, vehicle_phase_2signalgroup_map_, and traffic_signal_controller_service::signal_group_state::yellow_duration.
map_phase_and_signalgroup()
void traffic_signal_controller_service::tsc_state::map_phase_and_signalgroup (const std::vector< std::vector< int > > & active_ring_sequences, std::unordered_map< int, int > & vehicle_phase_2signalgroup_map, std::unordered_map< int, int > & signal_group_2vehiclephase_map) const private
Method for mapping vehicle phases and signal groups. Modifies non-const arguments by reference. Signal group map is expected to be passed empty. Vehicle phase map is expected to contain known vehicle phases. These are modified to only contain phases in the active ring sequence.
Parameters
active_ring_sequences A list of phases from the traffic signal controller in rows corresponding to the ring number
vehicle_phase_2signalgroup_map a map for all vehicle phases and signal groups associated with them
signal_group_2vehiclephase_map Mapping from signal groups id to vehicle phases
Definition at line 242 of file monitor_tsc_state.cpp.
    {
        // Loop through all ring sequences and remove vehicle phase entries in map
        for(auto it = vehicle_phase_2signalgroup_map.begin(); it != vehicle_phase_2signalgroup_map.end();){
            auto phase = it->first;
            bool found_phase = false;
            for(auto ring : active_ring_sequences)
            {
                if(std::find(ring.begin(), ring.end(), phase) !=ring.end()){
                    found_phase = true;
                    break;
                }
            }
            if(!found_phase)
            {
                // if phase not found in active sequence, remove entry
                it = vehicle_phase_2signalgroup_map.erase(it);
            }
            else{
                // Add entry to signal to phase map
                signal_group_2vehiclephase_map.insert(std::make_pair(it->second, it->first));
                it++;
            }
        }
    }
Referenced by initialize().
Member Data Documentation
HOUR_TO_SECONDS_
int traffic_signal_controller_service::tsc_state::HOUR_TO_SECONDS_ = 3600 private
Definition at line 66 of file monitor_tsc_state.h.
Referenced by convert_hour_tenth_secs2epoch_ts(), and convert_msepoch_to_hour_tenth_secs().
ped_phase_2signalgroup_map_
std::unordered_map<int,int> traffic_signal_controller_service::tsc_state::ped_phase_2signalgroup_map_ private
Definition at line 55 of file monitor_tsc_state.h.
Referenced by get_ped_phase_map(), get_signal_group_to_ped_phase_map(), and initialize().
phase_seq_ring1_
std::vector<int> traffic_signal_controller_service::tsc_state::phase_seq_ring1_ private
Definition at line 58 of file monitor_tsc_state.h.
phase_seq_ring2_
std::vector<int> traffic_signal_controller_service::tsc_state::phase_seq_ring2_ private
Definition at line 60 of file monitor_tsc_state.h.
required_following_movements_
int traffic_signal_controller_service::tsc_state::required_following_movements_ = 3 private
Definition at line 63 of file monitor_tsc_state.h.
Referenced by add_future_movement_events().
SECOND_TO_MILLISECONDS_
int traffic_signal_controller_service::tsc_state::SECOND_TO_MILLISECONDS_ = 1000 private
Definition at line 67 of file monitor_tsc_state.h.
Referenced by convert_hour_tenth_secs2epoch_ts(), and convert_msepoch_to_hour_tenth_secs().
signal_group_2tsc_state_map_
std::unordered_map<int, signal_group_state> traffic_signal_controller_service::tsc_state::signal_group_2tsc_state_map_ private
Definition at line 46 of file monitor_tsc_state.h.
Referenced by add_future_movement_events(), define_tsc_config_state(), get_red_duration(), get_signal_group_state_map(), and initialize().
signal_group_2vehiclephase_map_
std::unordered_map<int, int> traffic_signal_controller_service::tsc_state::signal_group_2vehiclephase_map_ private
Definition at line 49 of file monitor_tsc_state.h.
Referenced by get_phase_number(), and initialize().
snmp_client_worker_
std::shared_ptr<snmp_client> traffic_signal_controller_service::tsc_state::snmp_client_worker_ private
Definition at line 43 of file monitor_tsc_state.h.
Referenced by get_active_ring_sequences(), get_channels(), get_concurrent_signal_groups(), get_max_channels(), get_max_green(), get_max_rings(), get_min_green(), get_phases_associated_with_channel(), get_red_clearance(), and get_yellow_duration().
tsc_config_state_ptr_
std::shared_ptr<streets_tsc_configuration::tsc_configuration_state> traffic_signal_controller_service::tsc_state::tsc_config_state_ptr_ private
Pointer to tsc_configuration_state object which is traffic signal controller configuration information obtained from the tsc_state worker and broadcast on the carma-streets kafka broker as a JSON message.
Definition at line 74 of file monitor_tsc_state.h.
Referenced by get_tsc_config_state(), and initialize().
vehicle_phase_2signalgroup_map_
std::unordered_map<int,int> traffic_signal_controller_service::tsc_state::vehicle_phase_2signalgroup_map_ private
Definition at line 52 of file monitor_tsc_state.h.
Referenced by get_vehicle_phase_map(), get_vehicle_signal_group_id(), and initialize().
The documentation for this class was generated from the following files:
tsc_client_service/include/monitor_tsc_state.h
tsc_client_service/src/monitor_tsc_state.cpp