Carma-streets: signal_opt_service::signal_opt_messages_worker Class Reference
signal_opt_service::signal_opt_messages_worker Class Reference
#include <signal_opt_messages_worker.h>
Public Member Functions
signal_opt_messages_worker ()
~signal_opt_messages_worker ()=default
bool update_vehicle_list (const std::string &vehicle_json, std::shared_ptr< streets_vehicles::vehicle_list > vehicle_list_ptr) const
Vehicle string from kafka stream in JSON format. Calling vehicle list library to persist vehicles.
bool update_spat (const std::string &spat_json, std::shared_ptr< signal_phase_and_timing::spat > spat_ptr) const
Spat string from kafka stream in JSON format. Updating the spat with the latest spat info calling the signal_phase_timing library.
bool update_tsc_config (const std::string &tsc_configuration, std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_configuration_ptr) const
Update tsc configuration state shared pointer using json string update.
bool request_intersection_info (std::shared_ptr< OpenAPI::OAIIntersection_info > _intersection_info) const
Send http GET request to intersection model at rate of configured HZ until it gets the valid (!= 0) signal group id from the intersection info. Updating the intersection info with the http response that has the valid signal group id, and stop sending any more GET request.
Detailed Description
Definition at line 23 of file signal_opt_messages_worker.h.
Constructor & Destructor Documentation
signal_opt_messages_worker()
signal_opt_service::signal_opt_messages_worker::signal_opt_messages_worker ()
Definition at line 5 of file signal_opt_messages_worker.cpp.
    {
        SPDLOG_DEBUG("Construct signal_opt_messages_worker");
    }
~signal_opt_messages_worker()
signal_opt_service::signal_opt_messages_worker::~signal_opt_messages_worker () default
Member Function Documentation
request_intersection_info()
bool signal_opt_service::signal_opt_messages_worker::request_intersection_info (std::shared_ptr< OpenAPI::OAIIntersection_info > _intersection_info) const
Send http GET request to intersection model at rate of configured HZ until it gets the valid (!= 0) signal group id from the intersection info. Updating the intersection info with the http response that has the valid signal group id, and stop sending any more GET request.
Parameters
_intersection_info shared pointer to the intersection info object.
Returns
true if intersection information is updated upon receiving valid signal group id.
false if intersection information is not updated.
Definition at line 53 of file signal_opt_messages_worker.cpp.
    {
        int invalid_signal_group_count = 0;
        bool signal_group_ids_valid = false;
        OpenAPI::OAIDefaultApi apiInstance;
        QEventLoop loop;
        connect(&apiInstance, &OpenAPI::OAIDefaultApi::getIntersectionInfoSignal, [ intersection_info_ptr,
                                                                                    &signal_group_ids_valid,
                                                                                    &invalid_signal_group_count,
                                                                                    &loop](const OpenAPI::OAIIntersection_info &int_info)
                {
                    SPDLOG_INFO("request_intersection_info receives intersection information. Checking signal group ids update...");
                    QList<OpenAPI::OAILanelet_info> ll_info_list = int_info.getLinkLanelets();
                    for(const auto& ll_info : ll_info_list)
                    {
                        invalid_signal_group_count += ll_info.getSignalGroupId() == 0 ? 1 : 0;
                    }
                    if(invalid_signal_group_count == 0)
                    {
                        //Update intersection info
                        intersection_info_ptr->setId(int_info.getId());
                        intersection_info_ptr->setName(int_info.getName());
                        intersection_info_ptr->setEntryLanelets(int_info.getEntryLanelets());
                        intersection_info_ptr->setLinkLanelets(int_info.getLinkLanelets());
                        intersection_info_ptr->setDepartureLanelets(int_info.getDepartureLanelets());
                        signal_group_ids_valid = true;
                        SPDLOG_INFO("Intersection information is updated with valid signal group ids! ");
                    }
                SPDLOG_INFO("Exit request_intersection_info.");
            loop.quit(); });
        connect(&apiInstance, &OpenAPI::OAIDefaultApi::getIntersectionInfoSignalE, [this, &signal_group_ids_valid, &invalid_signal_group_count, &loop](OpenAPI::OAIIntersection_info, QNetworkReply::NetworkError, QString error_str)
                {
                    SPDLOG_ERROR("Error happened while issuing intersection model GET information request : {0}",  error_str.toStdString());
                    loop.quit(); });
        apiInstance.getIntersectionInfo();
        QTimer::singleShot(5000, &loop, &QEventLoop::quit);
        loop.exec();
        return signal_group_ids_valid;
    }
References OpenAPI::OAIIntersection_info::getDepartureLanelets(), OpenAPI::OAIIntersection_info::getEntryLanelets(), OpenAPI::OAIIntersection_info::getId(), OpenAPI::OAIDefaultApi::getIntersectionInfo(), OpenAPI::OAIDefaultApi::getIntersectionInfoSignal(), OpenAPI::OAIDefaultApi::getIntersectionInfoSignalE(), OpenAPI::OAIIntersection_info::getLinkLanelets(), and OpenAPI::OAIIntersection_info::getName().
update_spat()
bool signal_opt_service::signal_opt_messages_worker::update_spat (const std::string & spat_json, std::shared_ptr< signal_phase_and_timing::spat > spat_ptr) const
Spat string from kafka stream in JSON format. Updating the spat with the latest spat info calling the signal_phase_timing library.
Parameters
spat_json Spat string from kafka stream in JSON format.
spat_ptr shared pointer to the spat object.
Returns
true if the Spat object is updated.
false if the Spat object is not updated.
Definition at line 22 of file signal_opt_messages_worker.cpp.
    {
        if (spat_ptr)
        {
            try {
                spat_ptr->fromJson(spat_json);
                return true;
            }
            catch( const signal_phase_and_timing::signal_phase_and_timing_exception &e) {
                SPDLOG_ERROR("Exception encountered during SPaT processing! \n {0}", e.what());
                return false;
            }
        }
        return false;
    }
update_tsc_config()
bool signal_opt_service::signal_opt_messages_worker::update_tsc_config (const std::string & tsc_configuration, std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_configuration_ptr) const
Update tsc configuration state shared pointer using json string update.
Parameters
tsc_configuration std::string json update
tsc_configuration_ptr shared pointer to tsc configuration state object.
Returns
true if tsc configuration state object is successfully updated using json update message.
false false if tsc configuration state object fails to update using json update message.
Definition at line 38 of file signal_opt_messages_worker.cpp.
{
        if (tsc_configuration_ptr) {
            try {
                tsc_configuration_ptr->fromJson(tsc_configuration);
                return true;
            }
            catch( const streets_tsc_configuration::tsc_configuration_state_exception &e) {
                SPDLOG_ERROR("Exception encountered during TSC Configuration processing! \n {0}", e.what());
                return false;
            }
        }
        return false;
    }
update_vehicle_list()
bool signal_opt_service::signal_opt_messages_worker::update_vehicle_list (const std::string & vehicle_json, std::shared_ptr< streets_vehicles::vehicle_list > vehicle_list_ptr) const
Vehicle string from kafka stream in JSON format. Calling vehicle list library to persist vehicles.
Parameters
vehicle_json Vehicle string from kafka stream in JSON format.
vehicle_list_ptr shared pointer to the vehicle list object.
Returns
true if the vehicle list is updated.
false if the vehilce list is not updated.
Definition at line 11 of file signal_opt_messages_worker.cpp.
    {
        if (vehicle_list_ptr)
        {
            vehicle_list_ptr->process_update(vehicle_json);
            return true;
        }
        return false;
    }
The documentation for this class was generated from the following files:
signal_opt_service/include/signal_opt_messages_worker.h
signal_opt_service/src/signal_opt_messages_worker.cpp