Carma-streets: streets_signal_optimization::streets_desired_phase_plan_arbitrator Class Reference
streets_signal_optimization::streets_desired_phase_plan_arbitrator Class Reference
#include <streets_desired_phase_plan_arbitrator.h>
Public Member Functions
streets_desired_phase_plan_arbitrator ()=default
~streets_desired_phase_plan_arbitrator ()=default
streets_desired_phase_plan::streets_desired_phase_plan select_optimal_dpp (const std::vector< streets_desired_phase_plan::streets_desired_phase_plan > &dpp_list, const std::shared_ptr< OpenAPI::OAIIntersection_info > intersection_info_ptr, const std::shared_ptr< signal_phase_and_timing::spat > spat_ptr, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_state, const std::shared_ptr< streets_vehicles::vehicle_list > veh_list_ptr, uint64_t initial_green_buffer, uint64_t final_green_buffer, const double so_radius) const
Iterate over all movement groups in each candidate desired phase plan and return optimal desired phase plan. Select optimal candidate desired phase plan based on delay measure (delay served/delay added). Delay is a vehicles EET - ET.
void update_spat_with_candidate_dpp (std::shared_ptr< signal_phase_and_timing::spat > local_spat_ptr, const streets_desired_phase_plan::streets_desired_phase_plan &candidate_dpp, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_state) const
Update the local copy of spat object with the desired phase plan.
void calculate_vehicle_schedules (std::shared_ptr< streets_vehicle_scheduler::intersection_schedule > schedule_ptr, std::shared_ptr< signal_phase_and_timing::spat > local_spat_ptr, const std::shared_ptr< streets_vehicles::vehicle_list > veh_list_ptr, const std::shared_ptr< OpenAPI::OAIIntersection_info > intersection_info_ptr, uint64_t initial_green_buffer, uint64_t final_green_buffer) const
Calculate vehicles' schedules with the signalized scheduler and the local spat object. The calculated vehicles' schedules will be stored in an object pointed by the schedule_ptr pointer.
float calculate_delay_measure (const std::shared_ptr< streets_vehicle_scheduler::signalized_intersection_schedule > schedule_ptr, const streets_desired_phase_plan::streets_desired_phase_plan &candidate_dpp) const
Calculate delay measure for each candidate desired phase plan choice.
streets_desired_phase_plan::streets_desired_phase_plan identify_ddp_by_delay_measures (const std::vector< streets_desired_phase_plan::streets_desired_phase_plan > &dpp_list, const std::unordered_map< int, float > &ddp_index_delay_measure_mappings) const
Find the desired phase plan based on the highest delay measure.
std::string dpp_delay_toCSV (const streets_desired_phase_plan::streets_desired_phase_plan &candidate_dpp, const u_int64_t candidate_vehicle_delay, const u_int64_t TBD_delay, const float delay_measure) const
Method to turn the delay calculation for a candidate desired phase plan to CSV string.
void set_enable_so_logging (const bool _enable_so_logging)
Method to set enable_so_logging.
Private Attributes
bool enable_so_logging = false
The bool flag to enable signal optimization calculation csv logging.
Detailed Description
Definition at line 15 of file streets_desired_phase_plan_arbitrator.h.
Constructor & Destructor Documentation
streets_desired_phase_plan_arbitrator()
streets_signal_optimization::streets_desired_phase_plan_arbitrator::streets_desired_phase_plan_arbitrator () default
~streets_desired_phase_plan_arbitrator()
streets_signal_optimization::streets_desired_phase_plan_arbitrator::~streets_desired_phase_plan_arbitrator () default
Member Function Documentation
calculate_delay_measure()
float streets_signal_optimization::streets_desired_phase_plan_arbitrator::calculate_delay_measure (const std::shared_ptr< streets_vehicle_scheduler::signalized_intersection_schedule > schedule_ptr, const streets_desired_phase_plan::streets_desired_phase_plan & candidate_dpp) const
Calculate delay measure for each candidate desired phase plan choice.
Parameters
schedule_ptr A schedule pointer that points to schedule object with list of vehicle schedules.
candidate_dpp The current candidate desired phase plan.
Returns
float The calculated delay measure.
Definition at line 102 of file streets_desired_phase_plan_arbitrator.cpp.
    {
        if (schedule_ptr->vehicle_schedules.empty())
        {
            throw(streets_desired_phase_plan_arbitrator_exception("Vehicle schedule cannot be empty. Vehicles maybe outside of the radius."));
        }
        u_int64_t TBD_delay = 0;
        u_int64_t candidate_vehicles_delay = 0;
        for (const auto &veh_schedule : schedule_ptr->vehicle_schedules)
        {
            // If find the vehicles’ schedule ET > candidate desired phase plan end time, these vehicles are considered TBD.
            if (veh_schedule.et > candidate_dpp.desired_phase_plan.back().end_time)
            {
                TBD_delay += veh_schedule.get_delay();
                SPDLOG_DEBUG("TBD veh_schedule v_ID= {0}, get_delay = {1}", veh_schedule.v_id, veh_schedule.get_delay());
            }
            // If find the vehicles’ schedule ET <= candidate desired phase plan end time and the vehicles’ schedule ET => candidate desired phase plan start time.
            else if (veh_schedule.et >= candidate_dpp.desired_phase_plan.back().start_time)
            {
                candidate_vehicles_delay += veh_schedule.get_delay();
                SPDLOG_DEBUG("candidate veh_schedule v_ID= {0}, get_delay = {1}", veh_schedule.v_id, veh_schedule.get_delay());
            }
        }
        // The minimum value of the calculated delay can be 1 millisecond.
        float delay_measure = (float)std::max(candidate_vehicles_delay, u_int64_t(1)) / (float)std::max(TBD_delay, u_int64_t(1));
        SPDLOG_DEBUG("calculated delay_measure (= candidate/TBD) = {0}", delay_measure);
        if (enable_so_logging) {
            auto logger = spdlog::get("so_csv_logger");
            SPDLOG_DEBUG("getting so_csv_logger!");
            if ( logger != nullptr ) {
                SPDLOG_DEBUG("logging info: {0} ", dpp_delay_toCSV(candidate_dpp, candidate_vehicles_delay, TBD_delay, delay_measure));
                logger->info( dpp_delay_toCSV(candidate_dpp, candidate_vehicles_delay, TBD_delay, delay_measure) );
            }
        }
        else {
            SPDLOG_WARN("so_csv_logger in arbitrator pointer is not enabled!");
        }
        return delay_measure;
    }
References streets_desired_phase_plan::streets_desired_phase_plan::desired_phase_plan, dpp_delay_toCSV(), and enable_so_logging.
Referenced by select_optimal_dpp().
calculate_vehicle_schedules()
void streets_signal_optimization::streets_desired_phase_plan_arbitrator::calculate_vehicle_schedules (std::shared_ptr< streets_vehicle_scheduler::intersection_schedule > schedule_ptr, std::shared_ptr< signal_phase_and_timing::spat > local_spat_ptr, const std::shared_ptr< streets_vehicles::vehicle_list > veh_list_ptr, const std::shared_ptr< OpenAPI::OAIIntersection_info > intersection_info_ptr, uint64_t initial_green_buffer, uint64_t final_green_buffer) const
Calculate vehicles' schedules with the signalized scheduler and the local spat object. The calculated vehicles' schedules will be stored in an object pointed by the schedule_ptr pointer.
Parameters
schedule_ptr An intialized schedule pointer to be updated by this function.
local_spat A local copy of spat object.
intersection_info_ptr The current intersection model intersection information.
veh_list The list of vehicles within the intersection communication radius.
initial_green_buffer A configuration parameter for green phase.
final_green_buffer A configuration parameter for green phase.
Definition at line 84 of file streets_desired_phase_plan_arbitrator.cpp.
    {
        auto scheduler_ptr = std::make_unique<streets_vehicle_scheduler::signalized_vehicle_scheduler>();
        scheduler_ptr->set_intersection_info(intersection_info_ptr);
        scheduler_ptr->set_spat(local_spat_ptr);
        scheduler_ptr->set_initial_green_buffer(initial_green_buffer);
        scheduler_ptr->set_final_green_buffer(final_green_buffer);
        auto vehicles = veh_list_ptr->get_vehicles();
        all_schedule_ptr->timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
        scheduler_ptr->schedule_vehicles(vehicles, all_schedule_ptr);
    }
Referenced by select_optimal_dpp().
dpp_delay_toCSV()
std::string streets_signal_optimization::streets_desired_phase_plan_arbitrator::dpp_delay_toCSV (const streets_desired_phase_plan::streets_desired_phase_plan & candidate_dpp, const u_int64_t candidate_vehicle_delay, const u_int64_t TBD_delay, const float delay_measure) const
Method to turn the delay calculation for a candidate desired phase plan to CSV string.
timestamp ,movement group x start time ,movement group x end time, movement group x signal groups, delay of vehicles that can enter the intersection box during the last movement group, delay of vehicles that cannot enter the intersection box during any movement group (ET within TBD), delay measure
Parameters
candidate_dpp A candidate desired phase plan from the dpp list.
candidate_vehicle_delay The delay of vehicles that can enter the intersection box during the last movement group.
TBD_delay The delay of vehicles that cannot enter the intersection box during any movement group (ET within TBD).
delay_measure candidate_vehicle_delay / TBD_delay
Returns
std::string CSV entry
Definition at line 175 of file streets_desired_phase_plan_arbitrator.cpp.
    {
        std::string so_info = "";
        // timestamp
        so_info += std::to_string(candidate_dpp.timestamp) + ",";
        // candidate vehicle delay
        so_info += std::to_string(candidate_vehicle_delay) + ",";
        // TBD delay
        so_info += std::to_string(TBD_delay) + ",";
        // delay measure
        so_info += std::to_string(delay_measure) + ",";
        //desired phase plan
        so_info += candidate_dpp.toJson();
        return so_info;
    }
References streets_desired_phase_plan::streets_desired_phase_plan::timestamp, to_string(), and streets_desired_phase_plan::streets_desired_phase_plan::toJson().
Referenced by calculate_delay_measure().
identify_ddp_by_delay_measures()
streets_desired_phase_plan::streets_desired_phase_plan streets_signal_optimization::streets_desired_phase_plan_arbitrator::identify_ddp_by_delay_measures (const std::vector< streets_desired_phase_plan::streets_desired_phase_plan > & dpp_list, const std::unordered_map< int, float > & ddp_index_delay_measure_mappings) const
Find the desired phase plan based on the highest delay measure.
Parameters
dpp_list A list of desired phase plan.
ddp_index_delay_measure_mappings A Map of desired phase plan index and delay measure values.
Returns
streets_desired_phase_plan::streets_desired_phase_plan.
Definition at line 148 of file streets_desired_phase_plan_arbitrator.cpp.
    {
        streets_desired_phase_plan::streets_desired_phase_plan dpp_result;
        if (!ddp_index_delay_measure_mappings.empty())
        {
            int dpp_index = ddp_index_delay_measure_mappings.begin()->first;
            float max_delay_measure = ddp_index_delay_measure_mappings.begin()->second;
            // Find the highest delay_measure value, and return its desired phase plan index
            for (const auto &[cur_dpp_index, delay_measure] : ddp_index_delay_measure_mappings)
            {
                SPDLOG_DEBUG("Curent Desired phase plan = {0} , delay measure = {1}", dpp_list.at(dpp_index).toJson(), delay_measure);
                if (max_delay_measure < delay_measure)
                {
                    max_delay_measure = delay_measure;
                    dpp_index = cur_dpp_index;
                }
            }
            dpp_result = dpp_list.at(dpp_index);
            SPDLOG_DEBUG("Curent Desired phase plan = {0} , MAX delay measure = {1}", dpp_list.at(dpp_index).toJson(), max_delay_measure);
        }
        return dpp_result;
    }
Referenced by select_optimal_dpp().
select_optimal_dpp()
streets_desired_phase_plan::streets_desired_phase_plan streets_signal_optimization::streets_desired_phase_plan_arbitrator::select_optimal_dpp (const std::vector< streets_desired_phase_plan::streets_desired_phase_plan > & dpp_list, const std::shared_ptr< OpenAPI::OAIIntersection_info > intersection_info_ptr, const std::shared_ptr< signal_phase_and_timing::spat > spat_ptr, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_state, const std::shared_ptr< streets_vehicles::vehicle_list > veh_list_ptr, uint64_t initial_green_buffer, uint64_t final_green_buffer, const double so_radius) const
Iterate over all movement groups in each candidate desired phase plan and return optimal desired phase plan. Select optimal candidate desired phase plan based on delay measure (delay served/delay added). Delay is a vehicles EET - ET.
Parameters
dpp_list List of candidate desired phase plan.
intersection_info_ptr The current intersection model intersection information.
spat_ptr The spat pointer that points to the latest spat information received from the Kafka stream.
tsc_state The Map of signal group and yellow change and red clearance duration values.
veh_list The list of vehicles within the intersection communication radius.
initial_green_buffer A configuration parameter for green phase.
final_green_buffer A configuration parameter for green phase.
so_radius The configurable distance in meters defined as the radius of the signal optimization (SO) area.
Definition at line 6 of file streets_desired_phase_plan_arbitrator.cpp.
    {
        streets_desired_phase_plan::streets_desired_phase_plan result;
        if (!dpp_list.empty())
        {
            if (spat_ptr == nullptr)
            {
                throw(streets_desired_phase_plan_arbitrator_exception("The spat pointer is nullptr."));
            }
            if(veh_list_ptr == nullptr)
            {
                throw(streets_desired_phase_plan_arbitrator_exception("The vehicle list pointer is nullptr."));
            }
            int dpp_index = 0;
            std::unordered_map<int, float> ddp_delay_measures;
            for (const auto &candidate_dpp : dpp_list)
            {
                // A copy of spat object into local variable, and update local spat with candidatedesired phase plan
                auto local_spat_ptr = std::make_shared<signal_phase_and_timing::spat>();
                auto intersection_state = spat_ptr->get_intersection();
                local_spat_ptr->set_intersection(intersection_state);
                update_spat_with_candidate_dpp(local_spat_ptr, candidate_dpp, tsc_state);
                // Given spat and vehicle list, estimate current vehicles' ET and EET from signalized intersection schedule
                auto all_schedule_ptr = std::make_shared<streets_vehicle_scheduler::signalized_intersection_schedule>();
                // set_timestamp for the all_schedule_ptr current Unix timestamp
                calculate_vehicle_schedules(all_schedule_ptr, local_spat_ptr, veh_list_ptr, intersection_info_ptr, initial_green_buffer, final_green_buffer);
                // Add vehicle schedules from all_schedule_ptr for vehicle that are in SO area.
                auto schedule_ptr = std::make_shared<streets_vehicle_scheduler::signalized_intersection_schedule>();
                schedule_ptr->timestamp = all_schedule_ptr->timestamp;
                for (const auto& veh_sched : all_schedule_ptr->vehicle_schedules) {
                    if (veh_sched.state == streets_vehicles::vehicle_state::EV && veh_list_ptr->get_vehicles().at(veh_sched.v_id)._cur_distance <= so_radius) {
                        schedule_ptr->vehicle_schedules.push_back(veh_sched);
                    }
                }
                // Given vehicles' ET and EET from signalized intersection schedule, Calculate vehicles' delay measure for the current candidatedesired phase plan
                float delay_measure = calculate_delay_measure(schedule_ptr, candidate_dpp);
                // Add delay measure and candidatedesired phase plan index mapping to a list
                ddp_delay_measures.insert({dpp_index, delay_measure});
                dpp_index++;
            }
            if (ddp_delay_measures.empty())
            {
                throw(streets_desired_phase_plan_arbitrator_exception("There is no desired phase plan and delay measures mapping."));
            }
            // Find the largest delay_measure value, and return final desired phase plan
            result = identify_ddp_by_delay_measures(dpp_list, ddp_delay_measures);
        }
        else
        {
            SPDLOG_WARN("The list of possible desired phase plan is empty.");
        }
        return result;
    }
References calculate_delay_measure(), calculate_vehicle_schedules(), streets_vehicles::EV, identify_ddp_by_delay_measures(), and update_spat_with_candidate_dpp().
set_enable_so_logging()
void streets_signal_optimization::streets_desired_phase_plan_arbitrator::set_enable_so_logging (const bool _enable_so_logging)
Method to set enable_so_logging.
Definition at line 197 of file streets_desired_phase_plan_arbitrator.cpp.
{
        enable_so_logging = _enable_so_logging;
    }
References enable_so_logging.
update_spat_with_candidate_dpp()
void streets_signal_optimization::streets_desired_phase_plan_arbitrator::update_spat_with_candidate_dpp (std::shared_ptr< signal_phase_and_timing::spat > local_spat_ptr, const streets_desired_phase_plan::streets_desired_phase_plan & candidate_dpp, const std::shared_ptr< streets_tsc_configuration::tsc_configuration_state > tsc_state) const
Update the local copy of spat object with the desired phase plan.
Parameters
local_spat A local copy of spat object.
candidate_dpp The current candidate desired phase plan.
tsc_state The Map of signal group and yellow change and red clearance duration values.
Definition at line 76 of file streets_desired_phase_plan_arbitrator.cpp.
    {
        local_spat_ptr->update_spat_with_candidate_dpp(candidate_dpp, tsc_state);
    }
Referenced by select_optimal_dpp().
Member Data Documentation
enable_so_logging
bool streets_signal_optimization::streets_desired_phase_plan_arbitrator::enable_so_logging = false private
The bool flag to enable signal optimization calculation csv logging.
Definition at line 21 of file streets_desired_phase_plan_arbitrator.h.
Referenced by calculate_delay_measure(), and set_enable_so_logging().
The documentation for this class was generated from the following files:
streets_utils/streets_signal_optimization/include/streets_desired_phase_plan_arbitrator.h
streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp