Carma-streets: streets_vehicle_scheduler::vehicle_scheduler Class Reference
streets_vehicle_scheduler::vehicle_scheduler Class Reference abstract
Abstract Class for extend to implement scheduling business logic.
#include <vehicle_scheduler.h>
Public Member Functions
vehicle_scheduler ()=default
Construct a new vehicle scheduler object.
virtual ~vehicle_scheduler ()=default
Destroy the vehicle scheduler object.
virtual void schedule_vehicles (std::unordered_map< std::string, streets_vehicles::vehicle > &vehicles, std::shared_ptr< intersection_schedule > &schedule)=0
Virtual method to schedule vehicle. Different implementations of vehicle scheduler can implement custom business logic for scheduling vehicle while taking advantage of polymorphism to dynamically assign class at runtime.
std::shared_ptr< OpenAPI::OAIIntersection_info > get_intersection_info () const
Get the intersection info object.
void set_intersection_info (std::shared_ptr< OpenAPI::OAIIntersection_info > _intersection_info)
Set the intersection info object.
Protected Member Functions
void estimate_vehicles_at_common_time (std::unordered_map< std::string, streets_vehicles::vehicle > &vehicles, const u_int64_t timestamp) const
Method to estimate all vehicle's speed and location at a common future time. The time needs to be time since epoch in milliseconds. To predict vehicle location and speed at future time, current kinematic information is used including speed and current acceleration.
OpenAPI::OAILanelet_info get_entry_lanelet_info (const streets_vehicles::vehicle &veh) const
Helper method to get entry lane OAILanelet_info from intersection information given a vehicle.
OpenAPI::OAILanelet_info get_link_lanelet_info (const streets_vehicles::vehicle &veh) const
Helper method to get link lane OAILanelet_info from intersection information given a vehicle.
Protected Attributes
std::shared_ptr< OpenAPI::OAIIntersection_info > intersection_info
shared pointer to intersection information required for scheduling.
Detailed Description
Abstract Class for extend to implement scheduling business logic.
Definition at line 20 of file vehicle_scheduler.h.
Constructor & Destructor Documentation
vehicle_scheduler()
streets_vehicle_scheduler::vehicle_scheduler::vehicle_scheduler () default
Construct a new vehicle scheduler object.
~vehicle_scheduler()
virtual streets_vehicle_scheduler::vehicle_scheduler::~vehicle_scheduler () virtual default
Destroy the vehicle scheduler object.
Member Function Documentation
estimate_vehicles_at_common_time()
void streets_vehicle_scheduler::vehicle_scheduler::estimate_vehicles_at_common_time (std::unordered_map< std::string, streets_vehicles::vehicle > & vehicles, const u_int64_t timestamp) const protected
Method to estimate all vehicle's speed and location at a common future time. The time needs to be time since epoch in milliseconds. To predict vehicle location and speed at future time, current kinematic information is used including speed and current acceleration.
Parameters
vehicles Vehicle for which to calculate future position and speed.
timestamp Current or future time in milliseconds since epoch
Exceptions
scheduling_exception if vehicle update time for any vehicle is more recent than timestamp.
Definition at line 49 of file vehicle_scheduler.cpp.
{
        std::vector<std::string> vehicles_to_remove;
        for ( auto &[v_id, veh]: vehicles) {
            // Time difference in seconds
            double delta_t = (((double)timestamp) - ((double)veh._cur_time))/1000.0;
            SPDLOG_TRACE("Schedule timestamp {0} vs vehicle timestamp {1}.", timestamp, veh._cur_time);
            if ( delta_t > 5 ) {
                SPDLOG_WARN("Vehicle update {0} is older than 5 s and no longer considered for scheduling!", veh._id);
                vehicles_to_remove.push_back(veh._id);
                continue;
            }
            else if ( delta_t > 0.2) {
                SPDLOG_WARN("Vehicle update {0} is older than 200 ms!", veh._id);
            }
            else if ( delta_t < 0) {
                SPDLOG_WARN("Timestamp {0} is earlier that latest vehicle {1} update timestamp {2}. Vehicles can only be scheduled for current or future time."
                            , timestamp, veh._id, veh._cur_time );
                vehicles_to_remove.push_back( veh._id);
                continue;
            }
            // estimate future speed.
            double v_final = veh._cur_speed + veh._cur_accel*delta_t;
            // estimate change in distance
            double delta_x = ((v_final + veh._cur_speed)/2.0)*delta_t;
            SPDLOG_TRACE("Setting speed for vehicle {0} from {1}m/s to {2}m/s.",
                            veh._id,
                            veh._cur_speed,
                            v_final );
            veh._cur_speed = v_final;
            veh._cur_time =  timestamp;
            // Estimate distance to end of lanelet
            if ( veh._cur_distance - delta_x >= 0.0) {
                SPDLOG_TRACE("Setting distance for vehicle {0} from {1}m to {2}m.",
                            veh._id,
                            veh._cur_distance,
                            veh._cur_distance-delta_x );
                veh._cur_distance -= delta_x;
            }
            else {
                // TODO: Could add lanelet transition estimation with intersection model information.
                veh._cur_distance =  0.0;
            }
            // Remove all future points not older than timestamp for estimation.
            for (auto it = veh._future_info.begin() ; it != veh._future_info.end(); it++ ) {
                if ( timestamp > it->timestamp ) {
                    veh._future_info.erase( it--);
                }
            }
        }
        // Remove Old vehicle from consideration
        for (const auto &vehicle : vehicles_to_remove) {
            vehicles.erase(vehicle);
        }
    }
References simulate_mobilityoperation::timestamp.
Referenced by streets_vehicle_scheduler::all_stop_vehicle_scheduler::schedule_vehicles(), and streets_vehicle_scheduler::signalized_vehicle_scheduler::schedule_vehicles().
get_entry_lanelet_info()
OpenAPI::OAILanelet_info streets_vehicle_scheduler::vehicle_scheduler::get_entry_lanelet_info (const streets_vehicles::vehicle & veh) const protected
Helper method to get entry lane OAILanelet_info from intersection information given a vehicle.
Parameters
veh Vehicle for which to find entry lane OAILanlet_info.
Returns
OpenAPI::OAILanelet_info for entry lane.
Definition at line 13 of file vehicle_scheduler.cpp.
{
        OpenAPI::OAILanelet_info entry_lane;
        bool is_found = false;
        for (const auto &lanelet : intersection_info->getEntryLanelets() ) {
            int lane_id =lanelet.getId();
            if ( lane_id == veh._entry_lane_id ) {
                entry_lane =  lanelet;
                is_found = true;
            }
        }
        if (!is_found) {
            throw scheduling_exception("No entry lane " + std::to_string(veh._cur_lane_id) + " found in intersection info!");
        }
        return entry_lane;
    }
References streets_vehicles::vehicle::_cur_lane_id, streets_vehicles::vehicle::_entry_lane_id, OpenAPI::OAILanelet_info::getId(), intersection_info, and to_string().
Referenced by streets_vehicle_scheduler::signalized_vehicle_scheduler::calculate_earliest_entering_time(), and streets_vehicle_scheduler::all_stop_vehicle_scheduler::estimate_earliest_time_to_stop_bar().
get_intersection_info()
std::shared_ptr< OpenAPI::OAIIntersection_info > streets_vehicle_scheduler::vehicle_scheduler::get_intersection_info () const
Get the intersection info object.
Returns
std::shared_ptr<OpenAPI::OAIIntersection_info>
Definition at line 4 of file vehicle_scheduler.cpp.
{
        return intersection_info;
    }
References intersection_info.
get_link_lanelet_info()
OpenAPI::OAILanelet_info streets_vehicle_scheduler::vehicle_scheduler::get_link_lanelet_info (const streets_vehicles::vehicle & veh) const protected
Helper method to get link lane OAILanelet_info from intersection information given a vehicle.
Parameters
veh Vehicle for which to find link lane OAILanlet_info.
Returns
OpenAPI::OAILanelet_info for link lane.
Definition at line 31 of file vehicle_scheduler.cpp.
{
        OpenAPI::OAILanelet_info link_lane;
        bool is_found = false;
        for ( const auto &lanelet : intersection_info->getLinkLanelets() ) {
            int lane_id = lanelet.getId();
            if ( lane_id == veh._link_id ) {
                link_lane =  lanelet;
                is_found = true;
            }
        }
        if (!is_found) {
            throw scheduling_exception("No link lane " + std::to_string(veh._cur_lane_id) + " found in intersection info!");
        }
        return link_lane;
    }
References streets_vehicles::vehicle::_cur_lane_id, streets_vehicles::vehicle::_link_id, OpenAPI::OAILanelet_info::getId(), intersection_info, and to_string().
Referenced by streets_vehicle_scheduler::signalized_vehicle_scheduler::calculate_earliest_entering_time(), streets_vehicle_scheduler::all_stop_vehicle_scheduler::consider_departure_position_permutation(), streets_vehicle_scheduler::signalized_vehicle_scheduler::estimate_clearance_time(), streets_vehicle_scheduler::all_stop_vehicle_scheduler::estimate_entering_time_for_ev(), streets_vehicle_scheduler::signalized_vehicle_scheduler::estimate_et(), streets_vehicle_scheduler::signalized_vehicle_scheduler::schedule_dvs(), streets_vehicle_scheduler::all_stop_vehicle_scheduler::schedule_dvs(), and streets_vehicle_scheduler::all_stop_vehicle_scheduler::schedule_evs().
schedule_vehicles()
virtual void streets_vehicle_scheduler::vehicle_scheduler::schedule_vehicles (std::unordered_map< std::string, streets_vehicles::vehicle > & vehicles, std::shared_ptr< intersection_schedule > & schedule) pure virtual
Virtual method to schedule vehicle. Different implementations of vehicle scheduler can implement custom business logic for scheduling vehicle while taking advantage of polymorphism to dynamically assign class at runtime.
Parameters
vehicles unordered map of vehicles to schedule.
schedule empty intersection_schedule shared pointer which is returned by reference to provide calculated scheduling information.
Implemented in streets_vehicle_scheduler::all_stop_vehicle_scheduler, and streets_vehicle_scheduler::signalized_vehicle_scheduler.
set_intersection_info()
void streets_vehicle_scheduler::vehicle_scheduler::set_intersection_info (std::shared_ptr< OpenAPI::OAIIntersection_info > _intersection_info)
Set the intersection info object.
Parameters
_intersection_info
Definition at line 8 of file vehicle_scheduler.cpp.
{
        intersection_info = _intersection_info;
    }
References intersection_info.
Member Data Documentation
intersection_info
std::shared_ptr<OpenAPI::OAIIntersection_info> streets_vehicle_scheduler::vehicle_scheduler::intersection_info protected
shared pointer to intersection information required for scheduling.
Definition at line 26 of file vehicle_scheduler.h.
Referenced by streets_vehicle_scheduler::signalized_vehicle_scheduler::find_movement_state_for_lane(), get_entry_lanelet_info(), get_intersection_info(), get_link_lanelet_info(), streets_vehicle_scheduler::all_stop_vehicle_scheduler::schedule_evs(), streets_vehicle_scheduler::signalized_vehicle_scheduler::schedule_evs(), and set_intersection_info().
The documentation for this class was generated from the following files:
streets_utils/streets_vehicle_scheduler/include/vehicle_scheduler.h
streets_utils/streets_vehicle_scheduler/src/vehicle_scheduler.cpp