Carma-streets: traffic_signal_controller_service::monitor_desired_phase_plan Class Reference
traffic_signal_controller_service::monitor_desired_phase_plan Class Reference
#include <monitor_desired_phase_plan.h>
Public Member Functions
monitor_desired_phase_plan (const std::shared_ptr< snmp_client > client)
Construct a new monitor desired phase plan object..
~monitor_desired_phase_plan ()=default
Destroy the monitor desired phase plan object.
void update_desired_phase_plan (const std::string &payload)
Update desired_phase_plan object with json received string message.
void update_spat_future_movement_events (std::shared_ptr< signal_phase_and_timing::spat > spat_ptr, const std::shared_ptr< tsc_state > tsc_state_ptr)
Update spat movement_event list with desired phase plan information.
std::shared_ptr< streets_desired_phase_plan::streets_desired_phase_plan > get_desired_phase_plan_ptr () const
Returns shared pointer to desired_phase_plan object.
void fix_upcoming_green (const std::shared_ptr< signal_phase_and_timing::spat > spat_ptr, const std::shared_ptr< tsc_state > tsc_state_ptr)
Method to represent the upcoming green, when no desired phase plan is present and the TSC is currently in YELLOW CHANGE or RED CLEARANCE. This is indicated by the SPaT not containing any movement states with GREEN/PROTECTED MOVEMENT ALLOWED as the current state. Using the SNMP Client to make a GET request to the PHASE_STATUS_GROUP_PHASE_NEXT OID (see ntcip_oids.h PHASE_STATUS_GROUP_PHASE_NEXT documentation for more information) we will determine which phases are next and project GREEN, YELLOW and RED events onto the SPaT for this next GREEN using phase configuration information (min green, yellow change, and red clearance) to set timing data. THe projected GREEN phase will be fixed to last the minimum GREEN duration.
void fix_upcoming_yell_red (const std::shared_ptr< signal_phase_and_timing::spat > spat_ptr, const std::shared_ptr< tsc_state > tsc_state_ptr, const std::vector< signal_phase_and_timing::movement_state > &green_phases) const
Method to represent yellow change and red clearance when no desired phase plan is present and the TSC is currently GREEN for a given phase. This method assumes the current green will continue for min_green time and adds future events for all signal groups to account for the current green, the following yellow change and red clearance. This method will add future events with this information to the current spat_ptr data. Upon successful execution a SPaT message that previously only had current state and start time information will included future state information assuming the current green ends at min green and is followed by a yellow change and red clearance.
void prune_expired_greens_from_dpp (const std::shared_ptr< streets_desired_phase_plan::streets_desired_phase_plan > &desired_phase_plan) const
Method to prune the desired phase plan of any entries for which the end time is less than the current time.
void update_last_green_served (const std::vector< signal_phase_and_timing::movement_state > &green_phases_present)
Method to update last greens served with currently present green movement states.
Private Member Functions
FRIEND_TEST (test_monitor_desired_phase_plan, test_spat_prediction_no_desired_phase_plan_cur_all_red)
FRIEND_TEST (test_monitor_desired_phase_plan, test_spat_prediction_no_desired_phase_plan_cur_yellow)
FRIEND_TEST (test_monitor_desired_phase_plan, update_last_green_served)
FRIEND_TEST (test_monitor_desired_phase_plan, fix_upcoming_green_exception)
Private Attributes
std::shared_ptr< streets_desired_phase_plan::streets_desired_phase_plan > desired_phase_plan_ptr
std::shared_ptr< snmp_client > _snmp_client
std::vector< signal_phase_and_timing::movement_state > last_green_served
Holds a vector of signal groups that represent the phases that were most recently green. This vector is used to determine which signal group is currently in red clearance.
Friends
class test_monitor_desired_phase_plan
Detailed Description
Definition at line 14 of file monitor_desired_phase_plan.h.
Constructor & Destructor Documentation
monitor_desired_phase_plan()
traffic_signal_controller_service::monitor_desired_phase_plan::monitor_desired_phase_plan (const std::shared_ptr< snmp_client > client) explicit
Construct a new monitor desired phase plan object..
Parameters
client shared pointer to an initialized SNMP client for NTCIP next phase group requests.
Definition at line 5 of file monitor_desired_phase_plan.cpp.
                                                                                                  :  _snmp_client(client) {
    }
~monitor_desired_phase_plan()
traffic_signal_controller_service::monitor_desired_phase_plan::~monitor_desired_phase_plan () default
Destroy the monitor desired phase plan object.
Member Function Documentation
fix_upcoming_green()
void traffic_signal_controller_service::monitor_desired_phase_plan::fix_upcoming_green (const std::shared_ptr< signal_phase_and_timing::spat > spat_ptr, const std::shared_ptr< tsc_state > tsc_state_ptr)
Method to represent the upcoming green, when no desired phase plan is present and the TSC is currently in YELLOW CHANGE or RED CLEARANCE. This is indicated by the SPaT not containing any movement states with GREEN/PROTECTED MOVEMENT ALLOWED as the current state. Using the SNMP Client to make a GET request to the PHASE_STATUS_GROUP_PHASE_NEXT OID (see ntcip_oids.h PHASE_STATUS_GROUP_PHASE_NEXT documentation for more information) we will determine which phases are next and project GREEN, YELLOW and RED events onto the SPaT for this next GREEN using phase configuration information (min green, yellow change, and red clearance) to set timing data. THe projected GREEN phase will be fixed to last the minimum GREEN duration.
Exceptions
monitor_desired_phase_plan_exception if last_green_served is empty
Parameters
spat_ptr shared pointer to the current spat information.
tsc_state_ptr shared pointer to the tsc state information including tsc phase configuration information.
Response value is 8 bit int in which each bit is interpreted individually as 1 or 0. 1 indicates that the vehicle phase for that bit is committed to be next. 0 indicates this phase is not committed to be next.
bit 0 represent vehicle phase 1 bit 1 represent vehicle phase 2 bit 2 represent vehicle phase 3 bit 3 represent vehicle phase 4 bit 4 represent vehicle phase 5 bit 5 represent vehicle phase 6 bit 6 represent vehicle phase 7 bit 7 represent vehicle phase 8
Definition at line 86 of file monitor_desired_phase_plan.cpp.
{
        // Find start time of next green
        bool is_yellow_change = false;
        // Start time for fixed up coming green
        uint64_t start_time_epoch_ms = 0;
        // Current time used for any calculations
        uint64_t cur_time_since_epoch = streets_service::streets_clock_singleton::time_in_ms();
        auto state = spat_ptr->get_intersection();
        std::vector<signal_phase_and_timing::movement_state> yellow_phase_present;
        // Check if current spat includes yellow clearance
        for (const auto &movement : state.states) {
            // Found yellow states
            if ( movement.state_time_speed.front().event_state == signal_phase_and_timing::movement_phase_state::protected_clearance ) {
                is_yellow_change = true;
                auto yellow_phase_configuration =tsc_state->get_signal_group_state_map().find(movement.signal_group)->second;
                // Start time of upcoming green will be start of yellow + yellow duration + red clearance
                uint64_t local_start_time_epoch = movement.state_time_speed.front().timing.get_epoch_start_time() + yellow_phase_configuration.yellow_duration + yellow_phase_configuration.red_clearance;
                if ( local_start_time_epoch > start_time_epoch_ms) {
                    // If there are multiple movement groups in yellow, start time will be the largest end of yellow + red clearance time
                    start_time_epoch_ms = local_start_time_epoch;
                }
                // If service starts on yellow change, set last green served to yellow change.
                yellow_phase_present.push_back( movement);
            }
        }
        if ( !yellow_phase_present.empty() ) {
            update_last_green_served(yellow_phase_present);
        }
        // If it does not include a green and does not include a yellow assume it is in all red clearance
        if ( !is_yellow_change ) {
            for (const auto &movement : state.states) {
                // If last green served is empty
                // TSC is in YELLOW CHANGE or RED CLEAR and monitor desired phase plan
                // has not yet encountered a green to store as last green served
                if (last_green_served.empty() ) {
                    throw monitor_desired_phase_plan_exception("No information on previous green!");
                }
                // Found red clearance states
                if ( (movement.signal_group == last_green_served.front().signal_group
                    || movement.signal_group == last_green_served.back().signal_group)
                    && movement.state_time_speed.front().event_state == signal_phase_and_timing::movement_phase_state::stop_and_remain ) {
                    auto red_phase_configuration =tsc_state->get_signal_group_state_map().find(movement.signal_group)->second;
                    // Start time is red clearance start + red clearance if start time is > current time
                    uint64_t local_start_time_epoch = movement.state_time_speed.front().timing.get_epoch_start_time() + red_phase_configuration.red_clearance;
                    // If red phase start + red clearance is greater than or equal to current time this phase is in red clearance
                    // and will get green next.
                    start_time_epoch_ms = local_start_time_epoch;
                    if ( local_start_time_epoch < cur_time_since_epoch ) {
                        SPDLOG_ERROR("Error state SPaT : {0}", spat_ptr->toJson());
                        SPDLOG_ERROR("Error state last green served : {0}, {1}", last_green_served.front().signal_group, last_green_served.back().signal_group);
                        throw monitor_desired_phase_plan_exception("Local start time is less than current time which means this is not an upcoming green!");
                    }
                }
            }
        }
        // Once start time is determine. We must determine next phase.
        streets_snmp_cmd::snmp_response_obj response;
        response.type = streets_snmp_cmd::RESPONSE_TYPE::INTEGER;
        _snmp_client->process_snmp_request(ntcip_oids::PHASE_STATUS_GROUP_PHASE_NEXT, streets_snmp_cmd::REQUEST_TYPE::GET, response );
        // Generate Desired Phase Plan with next green fixed.
        streets_desired_phase_plan::streets_desired_phase_plan one_fixed_green;
        one_fixed_green.timestamp = cur_time_since_epoch;
        streets_desired_phase_plan::signal_group2green_phase_timing fixed_green;
        fixed_green.start_time = start_time_epoch_ms;
        for (uint i = 0; i < 8; ++i) {
            if (((response.val_int >> i) & 1) == 1) {
                // Add any signal group for phase that has bit as 1
                auto signal_group_id = tsc_state->get_vehicle_signal_group_id(i+1);
                fixed_green.signal_groups.push_back(signal_group_id);
            }
        }
        if ( fixed_green.signal_groups.size() > 2 ) {
            throw monitor_desired_phase_plan_exception( "More than two phases were found to be next!");
        }
        else if ( fixed_green.signal_groups.size() < 1) {
            throw monitor_desired_phase_plan_exception("No signal groups were found to be next");
        }
        // Calculating the end of the fixed green by using min green configuration
        // for all signal groups included in the movement group that is assigned the
        // next green.
        uint64_t fixed_green_end_time_epoch_ms = 0;
        for ( const auto &s_g_id : fixed_green.signal_groups ) {
            auto sig_group_config = tsc_state->get_signal_group_state_map().find(s_g_id)->second;
            uint64_t local_end_time_epoch_ms = fixed_green.start_time + sig_group_config.min_green;
            if ( local_end_time_epoch_ms > fixed_green_end_time_epoch_ms ) {
                // find max of green start + min green to assign end time
                fixed_green_end_time_epoch_ms = local_end_time_epoch_ms;
            }
        }
        fixed_green.end_time = fixed_green_end_time_epoch_ms;
        one_fixed_green.desired_phase_plan.push_back(fixed_green);
        SPDLOG_DEBUG("Updating SPaT with fixed green : \n{0}", one_fixed_green.toJson());
        spat_ptr->update_spat_with_candidate_dpp(one_fixed_green, tsc_state->get_tsc_config_state());
    }
References _snmp_client, streets_desired_phase_plan::streets_desired_phase_plan::desired_phase_plan, streets_desired_phase_plan::signal_group2green_phase_timing::end_time, streets_snmp_cmd::GET, traffic_signal_controller_service::tsc_state::get_signal_group_state_map(), traffic_signal_controller_service::tsc_state::get_tsc_config_state(), traffic_signal_controller_service::tsc_state::get_vehicle_signal_group_id(), simulate_bsm::i, streets_snmp_cmd::INTEGER, last_green_served, ntcip_oids::PHASE_STATUS_GROUP_PHASE_NEXT, signal_phase_and_timing::protected_clearance, streets_desired_phase_plan::signal_group2green_phase_timing::signal_groups, streets_desired_phase_plan::signal_group2green_phase_timing::start_time, signal_phase_and_timing::stop_and_remain, streets_service::streets_clock_singleton::time_in_ms(), streets_desired_phase_plan::streets_desired_phase_plan::timestamp, streets_desired_phase_plan::streets_desired_phase_plan::toJson(), streets_snmp_cmd::snmp_response_obj::type, update_last_green_served(), and streets_snmp_cmd::snmp_response_obj::val_int.
Referenced by update_spat_future_movement_events().
fix_upcoming_yell_red()
void traffic_signal_controller_service::monitor_desired_phase_plan::fix_upcoming_yell_red (const std::shared_ptr< signal_phase_and_timing::spat > spat_ptr, const std::shared_ptr< tsc_state > tsc_state_ptr, const std::vector< signal_phase_and_timing::movement_state > & green_phases) const
Method to represent yellow change and red clearance when no desired phase plan is present and the TSC is currently GREEN for a given phase. This method assumes the current green will continue for min_green time and adds future events for all signal groups to account for the current green, the following yellow change and red clearance. This method will add future events with this information to the current spat_ptr data. Upon successful execution a SPaT message that previously only had current state and start time information will included future state information assuming the current green ends at min green and is followed by a yellow change and red clearance.
Exceptions
monitor_desired_phase_plan_exception if more than 2 green phases are passed to this method.
Parameters
spat_ptr SPaT data to include projected future events
tsc_state_ptr traffic signal controller configuration information like SG to phase number mapping, min green, yellow change and red clearance.
green_phases movement state objects of the phases that are currently green.
Definition at line 204 of file monitor_desired_phase_plan.cpp.
{
        streets_desired_phase_plan::signal_group2green_phase_timing fixed_green;
        if ( green_phases.size() > 2 || green_phases.size() < 1) {
            throw monitor_desired_phase_plan_exception( "More than two or less than one present phases were found to be green!");
        } else {
            for ( const auto &phase : green_phases ) {
                fixed_green.signal_groups.push_back(phase.signal_group);
            }
        }
        // Current time used for any calculations
        streets_desired_phase_plan::streets_desired_phase_plan one_fixed_green;
        uint64_t cur_time_since_epoch = streets_service::streets_clock_singleton::time_in_ms();
        auto state = spat_ptr->get_intersection();
        // Get green phase configuration to get min green.
        auto green_phase_config =tsc_state->get_signal_group_state_map().find(green_phases.front().signal_group)->second;
        // Generate Desired Phase Plan with next green fixed.
        one_fixed_green.timestamp = cur_time_since_epoch;
        fixed_green.start_time = green_phases.front().state_time_speed.front().timing.get_epoch_start_time();
        fixed_green.end_time =  fixed_green.start_time + green_phase_config.min_green;
        one_fixed_green.desired_phase_plan.push_back(fixed_green);
        SPDLOG_INFO("Updating SPaT with fixed green : \n{0}", one_fixed_green.toJson());
        spat_ptr->update_spat_with_candidate_dpp(one_fixed_green, tsc_state->get_tsc_config_state());
    }
References streets_desired_phase_plan::streets_desired_phase_plan::desired_phase_plan, streets_desired_phase_plan::signal_group2green_phase_timing::end_time, traffic_signal_controller_service::tsc_state::get_signal_group_state_map(), traffic_signal_controller_service::tsc_state::get_tsc_config_state(), streets_desired_phase_plan::signal_group2green_phase_timing::signal_groups, streets_desired_phase_plan::signal_group2green_phase_timing::start_time, streets_service::streets_clock_singleton::time_in_ms(), streets_desired_phase_plan::streets_desired_phase_plan::timestamp, and streets_desired_phase_plan::streets_desired_phase_plan::toJson().
Referenced by update_spat_future_movement_events().
FRIEND_TEST() [1/4]
traffic_signal_controller_service::monitor_desired_phase_plan::FRIEND_TEST (test_monitor_desired_phase_plan , fix_upcoming_green_exception) private
FRIEND_TEST() [2/4]
traffic_signal_controller_service::monitor_desired_phase_plan::FRIEND_TEST (test_monitor_desired_phase_plan , test_spat_prediction_no_desired_phase_plan_cur_all_red) private
FRIEND_TEST() [3/4]
traffic_signal_controller_service::monitor_desired_phase_plan::FRIEND_TEST (test_monitor_desired_phase_plan , test_spat_prediction_no_desired_phase_plan_cur_yellow) private
FRIEND_TEST() [4/4]
traffic_signal_controller_service::monitor_desired_phase_plan::FRIEND_TEST (test_monitor_desired_phase_plan , update_last_green_served) private
get_desired_phase_plan_ptr()
std::shared_ptr< streets_desired_phase_plan::streets_desired_phase_plan > traffic_signal_controller_service::monitor_desired_phase_plan::get_desired_phase_plan_ptr () const
Returns shared pointer to desired_phase_plan object.
Returns
std::shared_ptr<streets_desired_phase_plan::streets_desired_phase_plan>
Definition at line 14 of file monitor_desired_phase_plan.cpp.
    {
        return desired_phase_plan_ptr;
    }
References desired_phase_plan_ptr.
prune_expired_greens_from_dpp()
void traffic_signal_controller_service::monitor_desired_phase_plan::prune_expired_greens_from_dpp (const std::shared_ptr< streets_desired_phase_plan::streets_desired_phase_plan > & desired_phase_plan) const
Method to prune the desired phase plan of any entries for which the end time is less than the current time.
Parameters
desired_phase_plan desired phase plan shared pointer from which to prune expired entries.
Definition at line 232 of file monitor_desired_phase_plan.cpp.
{
        // Loop through the desired phase plan and remove an event if the end time is past current
            bool no_expired_events = false;
            uint64_t cur_time_since_epoch = streets_service::streets_clock_singleton::time_in_ms();
            while( !no_expired_events && dpp != nullptr && !dpp->desired_phase_plan.empty()){
                // Check first event in desired phase plan and remove if expired
                if(cur_time_since_epoch < dpp->desired_phase_plan.front().end_time){
                    no_expired_events = true;
                }
                else{
                    // Warning for removing entries from dpp
                    SPDLOG_WARN("Current time is greater than event end time {0}, removing expired entry from desired phase plan", dpp->desired_phase_plan.front().end_time);
                    dpp->desired_phase_plan.erase(dpp->desired_phase_plan.begin());
                }
            }
    }
References streets_service::streets_clock_singleton::time_in_ms().
Referenced by update_spat_future_movement_events().
update_desired_phase_plan()
void traffic_signal_controller_service::monitor_desired_phase_plan::update_desired_phase_plan (const std::string & payload)
Update desired_phase_plan object with json received string message.
Parameters
payload
Definition at line 8 of file monitor_desired_phase_plan.cpp.
    {
        desired_phase_plan_ptr = std::make_shared<streets_desired_phase_plan::streets_desired_phase_plan>();
        desired_phase_plan_ptr->fromJson(payload);
    }
References desired_phase_plan_ptr.
update_last_green_served()
void traffic_signal_controller_service::monitor_desired_phase_plan::update_last_green_served (const std::vector< signal_phase_and_timing::movement_state > & green_phases_present)
Method to update last greens served with currently present green movement states.
Exceptions
monitor_desired_phase_plan_exception if greens_phases_present empty.
Parameters
green_phases_present Currently present green phases in SPAT.
Definition at line 249 of file monitor_desired_phase_plan.cpp.
{
        if ( !green_phases_present.empty() ) {
            if ( last_green_served.empty() || green_phases_present.front().signal_group != last_green_served.front().signal_group ||
                        green_phases_present.back().signal_group != last_green_served.front().signal_group) {
                last_green_served = green_phases_present;
                SPDLOG_DEBUG("Last served greens set to {0} and {1}!",
                    last_green_served.front().signal_group,
                    last_green_served.size() == 1 ? 0 : last_green_served.back().signal_group );
            }
        }
        else {
            throw monitor_desired_phase_plan_exception("Green phases present is empty! Cannot update last served green");
        }
    }
References last_green_served.
Referenced by fix_upcoming_green(), and update_spat_future_movement_events().
update_spat_future_movement_events()
void traffic_signal_controller_service::monitor_desired_phase_plan::update_spat_future_movement_events (std::shared_ptr< signal_phase_and_timing::spat > spat_ptr, const std::shared_ptr< tsc_state > tsc_state_ptr)
Update spat movement_event list with desired phase plan information.
Parameters
spat_ptr shared pointer to spat object.
tsc_state_ptr shared pointer to tsc_state object.
Definition at line 19 of file monitor_desired_phase_plan.cpp.
    {
        if (tsc_state_ptr == nullptr ||
            spat_ptr == nullptr ||
            tsc_state_ptr->get_tsc_config_state() == nullptr ||
            tsc_state_ptr->get_tsc_config_state()->tsc_config_list.empty())
        {
            throw monitor_desired_phase_plan_exception("SPAT and TSC state pointers cannot be null. SKIP processing!");
        }
        if (spat_ptr->get_intersection().states.empty())
        {
            throw monitor_desired_phase_plan_exception("Intersections states cannot be empty!");
        }
        // If no current green -> then either yellow change or red clearance active
        // => Fix next green phase in SPaT
        std::vector<signal_phase_and_timing::movement_state> green_phases_present;
        auto state = spat_ptr->get_intersection();
        for (const auto &movement : state.states) {
            if ( movement.state_time_speed.front().event_state == signal_phase_and_timing::movement_phase_state::protected_movement_allowed) {
                green_phases_present.push_back(movement);
            }
        }
        // If no desired phase plan is currently set
        if (desired_phase_plan_ptr == nullptr || desired_phase_plan_ptr->desired_phase_plan.empty())
        {
            if ( green_phases_present.empty() ) {
                // Using next phase group NTCIP OID fix min green, yellow change and red clear for next green
                fix_upcoming_green(spat_ptr, tsc_state_ptr);
            }
            else {
                // Update last green served
                update_last_green_served(green_phases_present);
                // Fix min green, yellow change and red clear for current green
                fix_upcoming_yell_red(spat_ptr, tsc_state_ptr, green_phases_present);
            }
        }
        // If a desired phase plan is currently set
        else {
            // Remove expired entries from desired phase plan
            prune_expired_greens_from_dpp(desired_phase_plan_ptr);
            // If desired phase plan is not empty
            if ( !desired_phase_plan_ptr->desired_phase_plan.empty()) {
                // If desired phase plan not empty use it to project future movement events
                SPDLOG_INFO("Updating SPaT with SO requested DPP : \n{0}", desired_phase_plan_ptr->toJson());
                spat_ptr->update_spat_with_candidate_dpp(*desired_phase_plan_ptr, tsc_state_ptr->get_tsc_config_state());
            }
            // If desired phase plan is empty
            else  {
                if ( green_phases_present.empty() ) {
                    // Using next phase group NTCIP OID fix min green, yellow change and red clear for next green
                    fix_upcoming_green(spat_ptr, tsc_state_ptr);
                }
                // If any signal group is currently green
                else {
                    // Update last green served
                    update_last_green_served(green_phases_present);
                    // Fix min green, yellow change and red clear for current green
                    fix_upcoming_yell_red(spat_ptr, tsc_state_ptr, green_phases_present);
                }
            }
        }
    }
References desired_phase_plan_ptr, fix_upcoming_green(), fix_upcoming_yell_red(), signal_phase_and_timing::protected_movement_allowed, prune_expired_greens_from_dpp(), and update_last_green_served().
Friends And Related Function Documentation
test_monitor_desired_phase_plan
friend class test_monitor_desired_phase_plan friend
Definition at line 26 of file monitor_desired_phase_plan.h.
Member Data Documentation
_snmp_client
std::shared_ptr<snmp_client> traffic_signal_controller_service::monitor_desired_phase_plan::_snmp_client private
Definition at line 19 of file monitor_desired_phase_plan.h.
Referenced by fix_upcoming_green().
desired_phase_plan_ptr
std::shared_ptr<streets_desired_phase_plan::streets_desired_phase_plan> traffic_signal_controller_service::monitor_desired_phase_plan::desired_phase_plan_ptr private
Definition at line 17 of file monitor_desired_phase_plan.h.
Referenced by get_desired_phase_plan_ptr(), update_desired_phase_plan(), and update_spat_future_movement_events().
last_green_served
std::vector<signal_phase_and_timing::movement_state> traffic_signal_controller_service::monitor_desired_phase_plan::last_green_served private
Holds a vector of signal groups that represent the phases that were most recently green. This vector is used to determine which signal group is currently in red clearance.
Definition at line 24 of file monitor_desired_phase_plan.h.
Referenced by fix_upcoming_green(), and update_last_green_served().
The documentation for this class was generated from the following files:
tsc_client_service/include/monitor_desired_phase_plan.h
tsc_client_service/src/monitor_desired_phase_plan.cpp