Carma-streets: message_services::models::baseMessage Class Reference
message_services::models::baseMessage Class Reference abstract
#include <baseMessage.h>
Public Member Functions
virtual bool asJsonObject (rapidjson::Writer< rapidjson::StringBuffer > *writer) const =0
virtual std::string asJson () const
virtual bool fromJson (const std::string &jsonString)
virtual void fromJsonObject (const rapidjson::Value &obj)=0
Detailed Description
Definition at line 23 of file baseMessage.h.
Member Function Documentation
asJson()
std::string message_services::models::baseMessage::asJson () const virtual
Definition at line 7 of file baseMessage.cpp.
        {
            rapidjson::StringBuffer ss;
            rapidjson::Writer<rapidjson::StringBuffer> writer(ss);
            if (this->asJsonObject(&writer))
                return ss.GetString();
            return "";
        }
References asJsonObject().
asJsonObject()
virtual bool message_services::models::baseMessage::asJsonObject (rapidjson::Writer< rapidjson::StringBuffer > * writer) const pure virtual
Implemented in message_services::models::bsm, message_services::models::mobilityoperation, message_services::models::mobilitypath, and message_services::models::vehicle_status_intent.
Referenced by asJson().
fromJson()
bool message_services::models::baseMessage::fromJson (const std::string & jsonString) virtual
Definition at line 16 of file baseMessage.cpp.
        {
            rapidjson::Document doc;
            bool has_parse_error = doc.Parse(jsonString.c_str()).HasParseError() ? true : false;
            if (has_parse_error)
            {
                return false;
            }
            this->fromJsonObject(doc);
            return true;
        }
References fromJsonObject().
Referenced by message_services::workers::bsm_worker::process_incoming_msg(), message_services::workers::mobilityoperation_worker::process_incoming_msg(), and message_services::workers::mobilitypath_worker::process_incoming_msg().
fromJsonObject()
virtual void message_services::models::baseMessage::fromJsonObject (const rapidjson::Value & obj) pure virtual
Implemented in message_services::models::bsm, message_services::models::mobilityoperation, message_services::models::mobilitypath, and message_services::models::vehicle_status_intent.
Referenced by fromJson().
The documentation for this class was generated from the following files:
message_services/src/models/baseMessage.h
message_services/src/models/baseMessage.cpp