Carma-streets: scheduling_service::intersection_client Class Reference
scheduling_service::intersection_client Class Reference
#include <intersection_client.h>
Public Member Functions
bool update_intersection_info (const int sleep_millisecs, const int int_client_request_attempts)
Updating the intersection info.
bool request_intersection_info ()
Send http GET request to intersection model at rate of configured HZ until it gets the intersection info.
std::shared_ptr< OpenAPI::OAIIntersection_info > get_intersection_info () const
Get the intersection info object.
Private Attributes
std::shared_ptr< OpenAPI::OAIIntersection_info > intersection_info_ptr
Detailed Description
Definition at line 17 of file intersection_client.h.
Member Function Documentation
get_intersection_info()
std::shared_ptr< OpenAPI::OAIIntersection_info > intersection_client::get_intersection_info () const
Get the intersection info object.
Returns
std::shared_ptr<OpenAPI::OAIIntersection_info>
Definition at line 66 of file intersection_client.cpp.
    {
        return intersection_info_ptr;
    }
References intersection_info_ptr.
request_intersection_info()
bool intersection_client::request_intersection_info ()
Send http GET request to intersection model at rate of configured HZ until it gets the intersection info.
Returns
true if intersection information is updated.
false if intersection information is not updated.
Definition at line 28 of file intersection_client.cpp.
    {
        bool intersection_info_valid = false;
        OpenAPI::OAIDefaultApi apiInstance;
        QEventLoop loop;
        // Lambda expression slot for get intersection information signal ( See Qt Signal/Slot documentation)
        connect(&apiInstance, &OpenAPI::OAIDefaultApi::getIntersectionInfoSignal, [&intersection_info_valid, &loop, this]
            (const OpenAPI::OAIIntersection_info &int_info){
            SPDLOG_INFO("request_intersection_info succeed!");
            SPDLOG_DEBUG("intersection name: {0}", int_info.getName().toStdString());
            SPDLOG_DEBUG("intersection id: {0}", int_info.getId());
            intersection_info_ptr = std::make_shared<OpenAPI::OAIIntersection_info>(int_info);
            intersection_info_valid = true;
            loop.quit();
        });
        // Lambda expression slot for get intersection information error signal ( See Qt Signal/Slot documentation)
        connect(&apiInstance, &OpenAPI::OAIDefaultApi::getIntersectionInfoSignalE,
            [&intersection_info_valid, &loop, this]
                ( [[maybe_unused]] const OpenAPI::OAIIntersection_info &int_info, QNetworkReply::NetworkError error, QString error_str ){
            SPDLOG_ERROR("Error happened while issuing intersection model GET information request : {0} code : {1}",  error_str.toStdString(), error);
            intersection_info_valid = false;
            intersection_info_ptr = nullptr;
            loop.quit();
        });
        apiInstance.getIntersectionInfo();
        QTimer::singleShot(5000, &loop, &QEventLoop::quit);
        loop.exec();
        SPDLOG_INFO("Done with request_intersection_info");
        return intersection_info_valid;
    }
References OpenAPI::OAIIntersection_info::getId(), OpenAPI::OAIDefaultApi::getIntersectionInfo(), OpenAPI::OAIDefaultApi::getIntersectionInfoSignal(), OpenAPI::OAIDefaultApi::getIntersectionInfoSignalE(), OpenAPI::OAIIntersection_info::getName(), and intersection_info_ptr.
Referenced by update_intersection_info().
update_intersection_info()
bool intersection_client::update_intersection_info (const int sleep_millisecs, const int int_client_request_attempts)
Updating the intersection info.
Parameters
sleep_millisecs The current thread sleep for milliseconds after each update attempt.
int_client_request_attempts The number of attempts for the loop.
Returns
boolean. True if intersection information is updated, otherwise failed to update intersection information.
Definition at line 6 of file intersection_client.cpp.
    {
        auto sleep_secs = static_cast<unsigned int>(sleep_millisecs);
        int attempt_count = 0;
        while (attempt_count < int_client_request_attempts)
        {
            // Send HTTP request, and update intersection information. If updated successfully, it returns true and exit the while loop.
            if (request_intersection_info())
            {
                SPDLOG_INFO("Intersection information is updated successfuly! ");
                return true;
            }
            // sleep takes seconds
            std::this_thread::sleep_for(std::chrono::milliseconds(sleep_secs));
            attempt_count++;
        }
        // If failed to update the intersection information after certain numbers of attempts
        SPDLOG_ERROR("Updating Intersection information failed. ");
        return false;
    }
References request_intersection_info().
Member Data Documentation
intersection_info_ptr
std::shared_ptr<OpenAPI::OAIIntersection_info> scheduling_service::intersection_client::intersection_info_ptr private
Definition at line 21 of file intersection_client.h.
Referenced by get_intersection_info(), and request_intersection_info().
The documentation for this class was generated from the following files:
scheduling_service/include/intersection_client.h
scheduling_service/src/intersection_client.cpp