Carma-streets: scheduling_service::scheduling_service Class Reference
scheduling_service::scheduling_service Class Reference
#include <scheduling_service.h>
Public Member Functions
scheduling_service ()=default
Initialize.
~scheduling_service ()
stop the consumer and producer
bool initialize (const int sleep_millisecs, const int int_client_request_attempts)
Initialize the consumer, producer, and scheduling workers. Create a vehicle list and scheduler objects and configure them.
void start ()
Create 2 threads: The first thread consumes status and intent message and updates the vehicle list. The second thread schedule vehicles and produce the schedule plan.
bool config_vehicle_list ()
Create the vehicle list processor and configure it.
bool config_scheduler (std::shared_ptr< OpenAPI::OAIIntersection_info > intersection_info_ptr)
Configure the scheduler object.
void consume_msg () const
Consume the status and intent messages via kafka consumer.
void consume_spat () const
Consume the modified spat via kafka consumer.
void schedule_veh () const
Schedule vehicles and produce the schedule plan.
void configure_csv_logger () const
Method to configure spdlog::logger for logging scheduling metrics into daily rotating csv file.
void set_scheduling_worker (std::shared_ptr< scheduling_worker > sched_worker)
Set the scheduling worker object for unit testing.
void set_vehicle_list (std::shared_ptr< streets_vehicles::vehicle_list > veh_list)
Set the vehicle list object for unit testing.
void set_vehicle_scheduler (std::shared_ptr< streets_vehicle_scheduler::vehicle_scheduler > scheduler)
Set the vehicle scheduler object for unit testing.
void set_consumer_worker (std::shared_ptr< kafka_clients::kafka_consumer_worker > worker)
Set the consumer worker object for unit testing.
void set_producer_worker (std::shared_ptr< kafka_clients::kafka_producer_worker > worker)
Set the producer worker object for unit testing.
void set_spat_consumer_worker (std::shared_ptr< kafka_clients::kafka_consumer_worker > worker)
Set the spat consumer worker object for unit testing.
Private Attributes
std::string bootstrap_server
std::string group_id
std::string consumer_topic
std::string producer_topic
std::string spat_topic
std::shared_ptr< streets_vehicles::vehicle_list > vehicle_list_ptr
std::shared_ptr< streets_vehicle_scheduler::vehicle_scheduler > scheduler_ptr
std::shared_ptr< signal_phase_and_timing::spat > spat_ptr
std::shared_ptr< kafka_clients::kafka_consumer_worker > consumer_worker
std::shared_ptr< kafka_clients::kafka_consumer_worker > spat_consumer_worker
std::shared_ptr< kafka_clients::kafka_producer_worker > producer_worker
std::shared_ptr< scheduling_worker > _scheduling_worker
Detailed Description
Definition at line 26 of file scheduling_service.h.
Constructor & Destructor Documentation
scheduling_service()
scheduling_service::scheduling_service::scheduling_service () default
Initialize.
~scheduling_service()
scheduling_service::scheduling_service::~scheduling_service ()
stop the consumer and producer
Definition at line 292 of file scheduling_service.cpp.
    {
        if (consumer_worker)
        {
            SPDLOG_WARN("Stopping consumer worker!");
            consumer_worker->stop();
        }
        if (producer_worker)
        {
            SPDLOG_WARN("Stopping producer worker");
            producer_worker->stop();
        }
    }
Member Function Documentation
config_scheduler()
bool scheduling_service::scheduling_service::config_scheduler (std::shared_ptr< OpenAPI::OAIIntersection_info > intersection_info_ptr)
Configure the scheduler object.
Parameters
intersection_info_ptr an intersection_info object
Definition at line 138 of file scheduling_service.cpp.
    {
        std::string intersection_type =  streets_service::streets_configuration::get_string_config("intersection_type");
        if ( intersection_type.compare("stop_controlled_intersection") == 0) {
            scheduler_ptr = std::make_shared<streets_vehicle_scheduler::all_stop_vehicle_scheduler>();
            scheduler_ptr->set_intersection_info(intersection_info_ptr);
            std::dynamic_pointer_cast<streets_vehicle_scheduler::all_stop_vehicle_scheduler>(scheduler_ptr)->set_flexibility_limit(
                    streets_service::streets_configuration::get_int_config("flexibility_limit"));
            SPDLOG_DEBUG("All_stop scheduler is configured successfully! ");
            return true;
        }
        else if ( intersection_type.compare("signalized_intersection") == 0 ) {
            // first, initialize the spat_ptr.
            spat_ptr = std::make_shared<signal_phase_and_timing::spat>();
            // then, initialize the scheduler and configure it.
            scheduler_ptr = std::make_shared<streets_vehicle_scheduler::signalized_vehicle_scheduler>();
            scheduler_ptr->set_intersection_info(intersection_info_ptr);
            auto processor = std::dynamic_pointer_cast<streets_vehicle_scheduler::signalized_vehicle_scheduler>(scheduler_ptr);
            processor->set_spat(spat_ptr);
            processor->set_initial_green_buffer(streets_service::streets_configuration::get_int_config("initial_green_buffer"));
            processor->set_final_green_buffer(streets_service::streets_configuration::get_int_config("final_green_buffer"));
            SPDLOG_DEBUG("Signalized scheduler is configured successfully! ");
            return true;
        }
        else {
            SPDLOG_ERROR("Failed configuring Vehicle Scheduler. Scheduling Service does not support intersection_type : {0}!", intersection_type);
            return false;
        }
    }
References streets_service::streets_configuration::get_int_config(), and streets_service::streets_configuration::get_string_config().
config_vehicle_list()
bool scheduling_service::scheduling_service::config_vehicle_list ()
Create the vehicle list processor and configure it.
Definition at line 109 of file scheduling_service.cpp.
    {
        vehicle_list_ptr = std::make_shared<streets_vehicles::vehicle_list>();
        std::string intersection_type =  streets_service::streets_configuration::get_string_config("intersection_type");
        if ( intersection_type.compare("stop_controlled_intersection") == 0) {
            vehicle_list_ptr->set_processor(std::make_shared<streets_vehicles::all_stop_status_intent_processor>());
            auto processor = std::dynamic_pointer_cast<streets_vehicles::all_stop_status_intent_processor>(vehicle_list_ptr->get_processor());
            processor->set_stopping_distance(streets_service::streets_configuration::get_double_config("stop_distance"));
            processor->set_stopping_speed(streets_service::streets_configuration::get_double_config("stop_speed"));
            processor->set_timeout(streets_service::streets_configuration::get_int_config("exp_delta"));
            SPDLOG_DEBUG("The processor of the vehicle list object is set to all_stop_status_intent_processor successfully! ");
            return true;
        }
        else if (intersection_type.compare("signalized_intersection") == 0) {
            vehicle_list_ptr->set_processor(std::make_shared<streets_vehicles::signalized_status_intent_processor>());
            std::dynamic_pointer_cast<streets_vehicles::signalized_status_intent_processor>(vehicle_list_ptr->get_processor())->set_timeout(streets_service::streets_configuration::get_int_config("exp_delta"));
            SPDLOG_DEBUG("The processor of the vehicle list object is set to signalized_status_intent_processor successfully!");
            return true;
        }
        else {
            SPDLOG_ERROR("Failed configuring Vehicle List. Scheduling Service does not support intersection_type : {0}!", intersection_type);
            return false;
        }
    }
References streets_service::streets_configuration::get_double_config(), streets_service::streets_configuration::get_int_config(), and streets_service::streets_configuration::get_string_config().
configure_csv_logger()
void scheduling_service::scheduling_service::configure_csv_logger () const
Method to configure spdlog::logger for logging scheduling metrics into daily rotating csv file.
Definition at line 270 of file scheduling_service.cpp.
    {
        try{
            auto csv_logger = spdlog::daily_logger_mt<spdlog::async_factory>(
                "csv_logger",  // logger name
                streets_service::streets_configuration::get_string_config("schedule_log_path")+
                    streets_service::streets_configuration::get_string_config("schedule_log_filename") +".csv",  // log file name and path
                23, // hours to rotate
                59 // minutes to rotate
                );
            // Only log log statement content
            csv_logger->set_pattern("%v");
            csv_logger->set_level(spdlog::level::info);
            csv_logger->flush_on(spdlog::level::info);
        }
        catch (const spdlog::spdlog_ex& ex)
        {
            spdlog::error( "Log initialization failed: {0}!",ex.what());
        }
    }
References streets_service::streets_configuration::get_string_config().
consume_msg()
void scheduling_service::scheduling_service::consume_msg () const
Consume the status and intent messages via kafka consumer.
Definition at line 175 of file scheduling_service.cpp.
    {
        SPDLOG_INFO("Starting status and intent consumer thread.");
        while (consumer_worker->is_running())
        {
            const std::string payload = consumer_worker->consume(1000);
            if(payload.length() != 0 && vehicle_list_ptr)
            {
                vehicle_list_ptr->process_update(payload);
            }
        }
        SPDLOG_WARN("Stopping status and intent consumer thread!");
        consumer_worker->stop();
    }
consume_spat()
void scheduling_service::scheduling_service::consume_spat () const
Consume the modified spat via kafka consumer.
Definition at line 194 of file scheduling_service.cpp.
    {
        SPDLOG_INFO("Starting spat consumer thread.");
        while (spat_consumer_worker->is_running())
        {
            const std::string spat_msg = spat_consumer_worker->consume(1000);
            if(spat_msg.length() != 0 && spat_ptr)
            {
                try {
                    spat_ptr->fromJson(spat_msg);
                }
                catch(const signal_phase_and_timing::signal_phase_and_timing_exception &ex) {
                    SPDLOG_ERROR("Failure in reading the spat message : {0}", ex.what());
                }
            }
        }
        SPDLOG_WARN("Stopping spat consumer thread!");
        spat_consumer_worker->stop();
    }
initialize()
bool scheduling_service::scheduling_service::initialize (const int sleep_millisecs, const int int_client_request_attempts)
Initialize the consumer, producer, and scheduling workers. Create a vehicle list and scheduler objects and configure them.
Definition at line 5 of file scheduling_service.cpp.
    {
        try
        {
            auto client = std::make_shared<kafka_clients::kafka_client>();
            this -> bootstrap_server = streets_service::streets_configuration::get_string_config("bootstrap_server");
            this -> group_id = streets_service::streets_configuration::get_string_config("group_id");
            this -> consumer_topic = streets_service::streets_configuration::get_string_config("consumer_topic");
            this -> producer_topic = streets_service::streets_configuration::get_string_config("producer_topic");
            consumer_worker = client->create_consumer(bootstrap_server, consumer_topic, group_id);
            producer_worker  = client->create_producer(bootstrap_server, producer_topic);
            if(!consumer_worker->init())
            {
                SPDLOG_CRITICAL("kafka consumer initialize error");
                exit(EXIT_FAILURE);
                return false;
            }
            else
            {
                consumer_worker->subscribe();
                if(!consumer_worker->is_running())
                {
                    SPDLOG_CRITICAL("consumer_worker is not running");
                    exit(EXIT_FAILURE);
                    return false;
                }
            }
            // Create logger
            if ( streets_service::streets_configuration::get_boolean_config("enable_schedule_logging") ) {
                configure_csv_logger();
            }
            if(!producer_worker->init())
            {
                SPDLOG_CRITICAL("kafka producer initialize error");
                exit(EXIT_FAILURE);
                return false;
            }
            if ( streets_service::streets_configuration::get_string_config("intersection_type").compare("signalized_intersection") == 0 ) {
                this -> spat_topic = streets_service::streets_configuration::get_string_config("spat_topic");
                spat_consumer_worker = client->create_consumer(bootstrap_server, spat_topic, group_id);
                if(!spat_consumer_worker->init())
                {
                    SPDLOG_CRITICAL("kafka consumer initialize error");
                    exit(EXIT_FAILURE);
                    return false;
                }
                else
                {
                    spat_consumer_worker->subscribe();
                    if(!spat_consumer_worker->is_running())
                    {
                        SPDLOG_CRITICAL("spat_consumer_worker is not running");
                        exit(EXIT_FAILURE);
                        return false;
                    }
                }
            }
            config_vehicle_list();
            // HTTP request to update intersection information
            auto int_client = std::make_shared<intersection_client>();
            if (int_client->update_intersection_info(sleep_millisecs, int_client_request_attempts))
            {
                config_scheduler(int_client->get_intersection_info());
            }
            else
            {
                return false;
            }
            _scheduling_worker = std::make_shared<scheduling_worker>();
            SPDLOG_INFO("scheduling service initialized successfully!!!");
            return true;
        }
        catch ( const streets_service::streets_configuration_exception &ex ) {
            SPDLOG_ERROR("scheduling service Initialization failure: {0} ", ex.what());
            return false;
        }
    }
References streets_service::streets_configuration::get_boolean_config(), and streets_service::streets_configuration::get_string_config().
Referenced by main().
schedule_veh()
void scheduling_service::scheduling_service::schedule_veh () const
Schedule vehicles and produce the schedule plan.
Definition at line 216 of file scheduling_service.cpp.
    {
        SPDLOG_INFO("Starting scheduling thread.");
        if (!_scheduling_worker)
        {
            SPDLOG_CRITICAL("scheduling worker is not initialized");
            exit(EXIT_FAILURE);
        }
        auto scheduling_delta = u_int64_t(streets_service::streets_configuration::get_double_config("scheduling_delta") * 1000);
        int sch_count = 0;
        std::unordered_map<std::string, streets_vehicles::vehicle> veh_map;
        while (true)
        {
            auto current_timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
            SPDLOG_DEBUG("Schedule iteration start time {0}!", current_timestamp);
            SPDLOG_TRACE("schedule number #{0}", sch_count);
            auto next_schedule_time_epoch = std::chrono::system_clock::now() + std::chrono::milliseconds(scheduling_delta);
            veh_map = vehicle_list_ptr -> get_vehicles();
            try {
                auto int_schedule = _scheduling_worker->schedule_vehicles(veh_map, scheduler_ptr);
                if ( streets_service::streets_configuration::get_boolean_config("enable_schedule_logging") ) {
                    auto logger = spdlog::get("csv_logger");
                    if ( logger != nullptr && !veh_map.empty() ){
                        logger->info( int_schedule->toCSV());
                    }
                }
                std::string msg_to_send = int_schedule->toJson();
                /* produce the scheduling plan to kafka */
                producer_worker->send(msg_to_send);
                current_timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
                SPDLOG_DEBUG("Schedule iteration end time {0}!", current_timestamp);
            }
            catch( const streets_vehicle_scheduler::scheduling_exception &e) {
                SPDLOG_ERROR("Scheduling Exception: {0}",e.what());
            }
            sch_count += 1;
            // sleep until next schedule
            if (std::chrono::system_clock::now() < next_schedule_time_epoch){
                std::this_thread::sleep_until(next_schedule_time_epoch);
            }
        }
        SPDLOG_WARN("Stopping scheduling thread!");
        producer_worker->stop();
    }
References streets_service::streets_configuration::get_boolean_config(), and streets_service::streets_configuration::get_double_config().
set_consumer_worker()
void scheduling_service::scheduling_service::set_consumer_worker (std::shared_ptr< kafka_clients::kafka_consumer_worker > worker)
Set the consumer worker object for unit testing.
Parameters
worker
Definition at line 320 of file scheduling_service.cpp.
{
        consumer_worker = worker;
    }
set_producer_worker()
void scheduling_service::scheduling_service::set_producer_worker (std::shared_ptr< kafka_clients::kafka_producer_worker > worker)
Set the producer worker object for unit testing.
Parameters
worker
Definition at line 324 of file scheduling_service.cpp.
{
        producer_worker = worker;
    }
set_scheduling_worker()
void scheduling_service::scheduling_service::set_scheduling_worker (std::shared_ptr< scheduling_worker > sched_worker)
Set the scheduling worker object for unit testing.
Parameters
sched_worker
Definition at line 308 of file scheduling_service.cpp.
{
        _scheduling_worker = sched_worker;
    }
set_spat_consumer_worker()
void scheduling_service::scheduling_service::set_spat_consumer_worker (std::shared_ptr< kafka_clients::kafka_consumer_worker > worker)
Set the spat consumer worker object for unit testing.
Parameters
worker
Definition at line 328 of file scheduling_service.cpp.
{
        spat_consumer_worker = worker;
    }
set_vehicle_list()
void scheduling_service::scheduling_service::set_vehicle_list (std::shared_ptr< streets_vehicles::vehicle_list > veh_list)
Set the vehicle list object for unit testing.
Parameters
veh_list
Definition at line 312 of file scheduling_service.cpp.
{
        vehicle_list_ptr = veh_list;
    }
set_vehicle_scheduler()
void scheduling_service::scheduling_service::set_vehicle_scheduler (std::shared_ptr< streets_vehicle_scheduler::vehicle_scheduler > scheduler)
Set the vehicle scheduler object for unit testing.
Parameters
scheduler
Definition at line 316 of file scheduling_service.cpp.
{
        scheduler_ptr = scheduler;
    }
start()
void scheduling_service::scheduling_service::start ()
Create 2 threads: The first thread consumes status and intent message and updates the vehicle list. The second thread schedule vehicles and produce the schedule plan.
Definition at line 94 of file scheduling_service.cpp.
    {
        std::thread consumer_thread(&scheduling_service::consume_msg, this );
        std::thread scheduling_thread(&scheduling_service::schedule_veh, this);
        if ( streets_service::streets_configuration::get_string_config("intersection_type").compare("signalized_intersection") == 0 ) {
            std::thread spat_consumer_thread(&scheduling_service::consume_spat, this );
            spat_consumer_thread.join();
        }
        consumer_thread.join();
        scheduling_thread.join();
    }
References streets_service::streets_configuration::get_string_config().
Referenced by main().
Member Data Documentation
_scheduling_worker
std::shared_ptr<scheduling_worker> scheduling_service::scheduling_service::_scheduling_worker private
Definition at line 43 of file scheduling_service.h.
bootstrap_server
std::string scheduling_service::scheduling_service::bootstrap_server private
Definition at line 30 of file scheduling_service.h.
consumer_topic
std::string scheduling_service::scheduling_service::consumer_topic private
Definition at line 32 of file scheduling_service.h.
consumer_worker
std::shared_ptr<kafka_clients::kafka_consumer_worker> scheduling_service::scheduling_service::consumer_worker private
Definition at line 40 of file scheduling_service.h.
group_id
std::string scheduling_service::scheduling_service::group_id private
Definition at line 31 of file scheduling_service.h.
producer_topic
std::string scheduling_service::scheduling_service::producer_topic private
Definition at line 33 of file scheduling_service.h.
producer_worker
std::shared_ptr<kafka_clients::kafka_producer_worker> scheduling_service::scheduling_service::producer_worker private
Definition at line 42 of file scheduling_service.h.
scheduler_ptr
std::shared_ptr<streets_vehicle_scheduler::vehicle_scheduler> scheduling_service::scheduling_service::scheduler_ptr private
Definition at line 37 of file scheduling_service.h.
spat_consumer_worker
std::shared_ptr<kafka_clients::kafka_consumer_worker> scheduling_service::scheduling_service::spat_consumer_worker private
Definition at line 41 of file scheduling_service.h.
spat_ptr
std::shared_ptr<signal_phase_and_timing::spat> scheduling_service::scheduling_service::spat_ptr private
Definition at line 38 of file scheduling_service.h.
spat_topic
std::string scheduling_service::scheduling_service::spat_topic private
Definition at line 34 of file scheduling_service.h.
vehicle_list_ptr
std::shared_ptr<streets_vehicles::vehicle_list> scheduling_service::scheduling_service::vehicle_list_ptr private
Definition at line 36 of file scheduling_service.h.
The documentation for this class was generated from the following files:
scheduling_service/include/scheduling_service.h
scheduling_service/src/scheduling_service.cpp