Carma-streets: message_services::models::mobilityoperation Class Reference
message_services::models::mobilityoperation Class Reference
#include <mobilityoperation.h>
Public Member Functions
mobilityoperation ()
virtual ~mobilityoperation ()
virtual void fromJsonObject (const rapidjson::Value &obj)
virtual bool asJsonObject (rapidjson::Writer< rapidjson::StringBuffer > *writer) const
std::string get_value_from_strategy_params (std::string key) const
std::string generate_hash_bsm_msg_id (std::string temprary_id, long msg_count, long sec_mark)
std::string generate_hash_sender_timestamp_id (std::string sender_bsm_id, uint64_t timestamp)
std::string getStrategy_params () const
void setStrategy_params (std::string strategy_params)
std::string getStrategy () const
void setStrategy (std::string strategy)
mobility_header_t getHeader () const
void setHeader (mobility_header_t header)
Public Member Functions inherited from message_services::models::baseMessage
virtual bool asJsonObject (rapidjson::Writer< rapidjson::StringBuffer > *writer) const =0
virtual std::string asJson () const
virtual bool fromJson (const std::string &jsonString)
virtual void fromJsonObject (const rapidjson::Value &obj)=0
Public Attributes
std::time_t msg_received_timestamp_ = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count()
Private Attributes
mobility_header_t header
std::string strategy = ""
std::string strategy_params = ""
Friends
std::ostream & operator<< (std::ostream &out, mobilityoperation &mobilityoperation_obj)
Detailed Description
Definition at line 16 of file mobilityoperation.h.
Constructor & Destructor Documentation
mobilityoperation()
message_services::models::mobilityoperation::mobilityoperation ()
Definition at line 14 of file mobilityoperation.cpp.
                                             : strategy(""), strategy_params(""), header()
        {
        }
~mobilityoperation()
message_services::models::mobilityoperation::~mobilityoperation () virtual
Definition at line 18 of file mobilityoperation.cpp.
        {
        }
Member Function Documentation
asJsonObject()
bool message_services::models::mobilityoperation::asJsonObject (rapidjson::Writer< rapidjson::StringBuffer > * writer) const virtual
Implements message_services::models::baseMessage.
Definition at line 88 of file mobilityoperation.cpp.
        {
            try
            {
                writer->StartObject();
                writer->Key("header");
                writer->StartObject();
                writer->Key("sender_id");
                writer->String(this->getHeader().sender_id.c_str());
                writer->Key("recipient_id");
                writer->String(this->getHeader().recipient_id.c_str());
                writer->Key("plan_id");
                writer->String(this->getHeader().plan_id.c_str());
                writer->Key("timestamp");
                writer->Uint64(this->getHeader().timestamp);
                writer->EndObject();
                writer->Key("strategy_params");
                writer->String(this->getStrategy_params().c_str());
                writer->Key("strategy");
                writer->String(this->getStrategy().c_str());
                writer->EndObject();
                return true;
            }
            catch (std::exception &ex)
            {
                SPDLOG_CRITICAL("mobilityoperation model: {0} ", ex.what());
                return false;
            }
        }
References getHeader(), getStrategy(), getStrategy_params(), and simulate_mobilityoperation::timestamp.
fromJsonObject()
void message_services::models::mobilityoperation::fromJsonObject (const rapidjson::Value & obj) virtual
Implements message_services::models::baseMessage.
Definition at line 34 of file mobilityoperation.cpp.
        {
            if (obj.IsObject())
            {
                for (rapidjson::Value::ConstMemberIterator obj_itr = obj.MemberBegin(); obj_itr != obj.MemberEnd(); obj_itr++)
                {
                    if (obj_itr->value.IsObject() && boost::iequals(std::string(obj_itr->name.GetString()), std::string("metadata")))
                    {
                        mobility_header_t header;
                        for (rapidjson::Value::ConstMemberIterator header_itr = obj_itr->value.MemberBegin(); header_itr != obj_itr->value.MemberEnd(); header_itr++)
{
                            if (std::string(header_itr->name.GetString()) == std::string("hostStaticId"))
{
                                header.sender_id = header_itr->value.GetString();
                            }
                            if (std::string(header_itr->name.GetString()) == std::string("hostBSMId"))
{
                                header.sender_bsm_id = header_itr->value.GetString();
                            }
                            if (std::string(header_itr->name.GetString()) == std::string("planId"))
{
                                header.plan_id = (header_itr->value.GetString());
                            }
                            if (std::string(header_itr->name.GetString()) == std::string("targetStaticId"))
{
                                header.recipient_id = (header_itr->value.GetString());
                            }
                            if (std::string(header_itr->name.GetString()) == std::string("timestamp"))
{
                                header.timestamp = std::stol(header_itr->value.GetString());
                            }
                        }
                        setHeader(header);
                    }
                    if (obj_itr->value.IsString() && boost::iequals(std::string(obj_itr->name.GetString()), std::string("strategy")))
                    {
                        setStrategy(obj_itr->value.GetString());
                    }
                    if (obj_itr->value.IsString() && boost::iequals(std::string(obj_itr->name.GetString()), std::string("strategy_params")))
                    {
                        setStrategy_params(obj_itr->value.GetString());
                    }
                }
            }
        }
References header, simulate_phase_control_schedule::obj, message_services::models::mobility_header::plan_id, message_services::models::mobility_header::recipient_id, message_services::models::mobility_header::sender_bsm_id, message_services::models::mobility_header::sender_id, setHeader(), setStrategy(), setStrategy_params(), and message_services::models::mobility_header::timestamp.
generate_hash_bsm_msg_id()
std::string message_services::models::mobilityoperation::generate_hash_bsm_msg_id (std::string temprary_id, long msg_count, long sec_mark)
Definition at line 28 of file mobilityoperation.cpp.
        {
            std::stringstream hash_ss;
            hash_ss << temprary_id << msg_count << sec_mark;
            return hash_ss.str();
        }
Referenced by message_services::services::vehicle_status_intent_service::run().
generate_hash_sender_timestamp_id()
std::string message_services::models::mobilityoperation::generate_hash_sender_timestamp_id (std::string sender_bsm_id, uint64_t timestamp)
Definition at line 22 of file mobilityoperation.cpp.
        {
            std::stringstream hash_ss;
            hash_ss << sender_bsm_id << timestamp;
            return hash_ss.str();
        }
References simulate_mobilityoperation::timestamp.
Referenced by message_services::services::vehicle_status_intent_service::run().
get_value_from_strategy_params()
std::string message_services::models::mobilityoperation::get_value_from_strategy_params (std::string key) const
Definition at line 118 of file mobilityoperation.cpp.
        {
            const char *delimiter = ",:";
            std::string key_value_str = "";
            std::vector<std::string> key_value_v = {};
            std::stringstream strategy_params_stream(this->strategy_params);
            // strategy_params are key value pairs separate by comma
            while (std::getline(strategy_params_stream, key_value_str, *delimiter))
            {
                std::stringstream key_value_str_stream(key_value_str);
                std::string key_or_value = "";
                while (std::getline(key_value_str_stream, key_or_value, *(delimiter + 1)))
                {
                    boost::algorithm::trim(key_or_value);
                    key_value_v.push_back(key_or_value);
                }
                if (key_value_v.size() > 0 && key_value_v.front() == key)
                {
                    return key_value_v.back();
                }
                if (key_value_v.size() > 0)
                {
                    key_value_v.clear();
                }
                key_value_str = "";
            }
            return key_value_str;
        }
References strategy_params.
Referenced by message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent(), and message_services::services::vehicle_status_intent_service::run().
getHeader()
mobility_header_t message_services::models::mobilityoperation::getHeader () const
Definition at line 163 of file mobilityoperation.cpp.
        {
            return this->header;
        }
References header.
Referenced by asJsonObject(), message_services::services::vehicle_status_intent_service::compose_vehicle_status_intent(), and message_services::services::vehicle_status_intent_service::run().
getStrategy()
std::string message_services::models::mobilityoperation::getStrategy () const
Definition at line 179 of file mobilityoperation.cpp.
        {
            return this->strategy;
        }
References strategy.
Referenced by asJsonObject().
getStrategy_params()
std::string message_services::models::mobilityoperation::getStrategy_params () const
Definition at line 171 of file mobilityoperation.cpp.
        {
            return this->strategy_params;
        }
References strategy_params.
Referenced by asJsonObject().
setHeader()
void message_services::models::mobilityoperation::setHeader (mobility_header_t header)
Definition at line 167 of file mobilityoperation.cpp.
        {
            this->header = header;
        }
References header.
Referenced by fromJsonObject().
setStrategy()
void message_services::models::mobilityoperation::setStrategy (std::string strategy)
Definition at line 183 of file mobilityoperation.cpp.
        {
            this->strategy = strategy;
        }
References strategy.
Referenced by fromJsonObject().
setStrategy_params()
void message_services::models::mobilityoperation::setStrategy_params (std::string strategy_params)
Definition at line 175 of file mobilityoperation.cpp.
        {
            this->strategy_params = strategy_params;
        }
References strategy_params.
Referenced by fromJsonObject().
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & out, mobilityoperation & mobilityoperation_obj) friend
Definition at line 151 of file mobilityoperation.cpp.
        {
            out << std::fixed;
            out << std::setprecision(6);
            out << "mobilityoperation model: sender_id =  " << mobilityoperation_obj.header.sender_id
                      << ", sender_bsm_id =" << mobilityoperation_obj.header.sender_bsm_id
                      << ", timestamp = " << mobilityoperation_obj.header.timestamp
                      << ", sender id = " << mobilityoperation_obj.header.sender_id << ", strategy= " << mobilityoperation_obj.strategy
                      << ", strategy_params= " << mobilityoperation_obj.strategy_params << std::endl;
            return out;
        }
Member Data Documentation
header
mobility_header_t message_services::models::mobilityoperation::header private
Definition at line 21 of file mobilityoperation.h.
Referenced by fromJsonObject(), getHeader(), and setHeader().
msg_received_timestamp_
std::time_t message_services::models::mobilityoperation::msg_received_timestamp_ = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count()
Definition at line 30 of file mobilityoperation.h.
strategy
std::string message_services::models::mobilityoperation::strategy = "" private
Definition at line 22 of file mobilityoperation.h.
Referenced by getStrategy(), and setStrategy().
strategy_params
std::string message_services::models::mobilityoperation::strategy_params = "" private
Definition at line 23 of file mobilityoperation.h.
Referenced by get_value_from_strategy_params(), getStrategy_params(), and setStrategy_params().
The documentation for this class was generated from the following files:
message_services/src/models/mobilityoperation.h
message_services/src/models/mobilityoperation.cpp