Carma-streets: sensor_data_sharing_service::sds_service Class Reference
sensor_data_sharing_service::sds_service Class Reference
#include <sensor_data_sharing_service.hpp>
Public Member Functions
sds_service ()=default
~sds_service ()
bool initialize () override
Method to initialize the sds_service.
void start () override
Method to start all threads included in the tsc_service.
FRIEND_TEST (sensorDataSharingServiceTest, consumeDetections)
FRIEND_TEST (sensorDataSharingServiceTest, produceSdsms)
FRIEND_TEST (sensorDataSharingServiceTest, readLanelet2Map)
Public Member Functions inherited from streets_service::streets_service
streets_service ()=default
Constructor.
~streets_service ()
Destructor stop time_consumer kafka producer if not null.
streets_service (const streets_service &)=delete
streets_service (streets_service &&)=delete
streets_service & operator= (const streets_service &)=delete
streets_service & operator= (const streets_service &&)=delete
virtual bool initialize ()
Method to initialize services members, singletons, kafka consumers and producers and any other connections required for service. Classes that extend this streets_service need to override this method and call the streets_service::initialize() in the override method.
virtual void start ()
Method to start all threads needed for the Streets Service. This includes but is not limited to any threads to consume/produce message to kafka, or poll internal/external resources. Classes that extend this streets_service need to override this method and call the streets_service::start() in the override method.
Private Member Functions
bool initialize_kafka_consumers_producers ()
Initialize Kafka consumers and producers for sensor data sharing service.
void consume_detections ()
Loop to consume detections from kafka detection consumer. Will terminate if kafka consumer is no longer running.
void produce_sdsms ()
Loop to produce sensor data sharing messages from detected_objects. Loop will populate sensor data sharing message with most recent detection information, publish message and clear detected object map. Will terminate if kafka producer is no longer running.
bool read_lanelet_map (const std::string &filepath)
Method to read lanelet2 map.
streets_utils::messages::sdsm::sensor_data_sharing_msg create_sdsm ()
Method to create SDSM from detected objects.
Private Attributes
std::shared_ptr< kafka_clients::kafka_producer_worker > sdsm_producer
Kafka producer for SDSM JSON.
std::shared_ptr< kafka_clients::kafka_consumer_worker > detection_consumer
std::map< int, streets_utils::messages::detected_objects_msg::detected_objects_msg > detected_objects
Map of detected objects. New detections of existing objects will replace old detections.
std::shared_mutex detected_objects_lock
Mutex for thread safe operations on detected objects map.
lanelet::LaneletMapPtr map_ptr
Lanelet2 Map pointer.
std::unique_ptr< lanelet::projection::LocalFrameProjector > map_projector
WSG84 Map projection.
lanelet::GPSPoint sdsm_reference_point
Location of sensor.This is also the sensor's coordinate frame orignin meaning all offsets are interpreted relative to this location.
std::string _infrastructure_id
Infrastructure ID used as source ID for SDSM broadcast.
uint8_t _message_count = 0
Message count for SDSM.
Additional Inherited Members
Protected Member Functions inherited from streets_service::streets_service
bool initialize_kafka_producer (const std::string &producer_topic, std::shared_ptr< kafka_clients::kafka_producer_worker > &producer)
Helper method to initialize Kafka producer for a given topic.
bool initialize_kafka_consumer (const std::string &consumer_topic, std::shared_ptr< kafka_clients::kafka_consumer_worker > &consumer)
Helper method to initialise Kafka consumer. NOTE: Will assign consumer group id as service_name.
std::string get_system_config (const char *config_name, const std::string &default_val) const noexcept
Returns string value of environment variable with given name. If no value is found, returns default.
void consume_time_sync_message () const
Method to consume continously consume time sync messages from Kafka topic and update streets_clock_singleton with received data.
std::string get_service_name () const
Returns service name set in configuration file.
bool is_simulation_mode () const
Returns boolean if service is currently configured to be in simulation_mode. This corresponsds to the value of the environment variable SIMULATION_MODE. Simulation mode indicates whether the streets_clock_singleton uses simulation time for kafka or system time.
std::shared_ptr< spdlog::logger > create_daily_logger (const std::string &name, const std::string &extension=".log", const std::string &pattern="[%Y-%m-%d %H:%M:%S.%e] %v", const spdlog::level::level_enum &level=spdlog::level::info) const
Method to create SPDLOG Daily rotating file logger. The logger is accessible by calling spdlog::get(name). The log files created by this logger will include data and time in name and will be stored in the LOGS_DIRECTORY set path.
Detailed Description
Definition at line 53 of file sensor_data_sharing_service.hpp.
Constructor & Destructor Documentation
sds_service()
sensor_data_sharing_service::sds_service::sds_service () default
~sds_service()
sensor_data_sharing_service::sds_service::~sds_service ()
Definition at line 21 of file sensor_data_sharing_service.cpp.
{
        if (sdsm_producer)
        {
            SPDLOG_WARN("Stopping SDSM producer!");
            sdsm_producer->stop();
        }
        if(detection_consumer)
        {
            SPDLOG_WARN("Stopping Detection consumer!");
            detection_consumer->stop();
        }
    }
References detection_consumer, and sdsm_producer.
Member Function Documentation
consume_detections()
void sensor_data_sharing_service::sds_service::consume_detections () private
Loop to consume detections from kafka detection consumer. Will terminate if kafka consumer is no longer running.
Exceptions
std::runtime exception if detection_consumer == nullptr
Definition at line 87 of file sensor_data_sharing_service.cpp.
{
        if ( !detection_consumer ) {
            throw std::runtime_error("Detection consumer is null!");
        }
        SPDLOG_DEBUG("Attempting to consume detections ...");
        detection_consumer->subscribe();
        while ( detection_consumer->is_running() ) {
            try{
                const std::string payload = detection_consumer->consume(1000);
                if (payload.length() != 0)
                {
                    auto detected_object = streets_utils::messages::detected_objects_msg::from_json(payload);
                    // Get delay of detected object
                    auto delay = static_cast<int>(ss::streets_clock_singleton::time_in_ms()) - static_cast<int>(detected_object._timestamp);
                    SPDLOG_DEBUG("Detection Delay : {0}ms!", delay);
                    // if delay is greater than 500 ms skip detection to get more recent data
                    if ( delay >= 500 ) {
                        SPDLOG_WARN("Skipping incoming detection at {0}ms is not current or has invalid timestamp of {1}ms!" , ss::streets_clock_singleton::time_in_ms(), detected_object._timestamp );
                        continue;
                    }
                    // if delay is negative, and service is in simulation mode
                    // the detection message was processed before time sync message. Wait on time sync message
                    else if (is_simulation_mode() && delay < 0 ) {
                        SPDLOG_WARN("Current sim time {0} waiting for sim time {1}ms from detection ...",ss::streets_clock_singleton::time_in_ms(), detected_object._timestamp );
                        ss::streets_clock_singleton::sleep_for(abs(delay));
                    }
                    // If delay is negative and service is not in simulation mode
                    // indicates sensor and service are not time sychronized.
                    else if( delay < 0 ) {
                        SPDLOG_WARN(
                            R"(Current time is {0}ms and detection time stamp is {1}ms. Sensor Data Sharing Service and sensor producing detections to not appear to be time synchronized)",
                            ss::streets_clock_singleton::time_in_ms(),
                            detected_object._timestamp );
                    }
                    // Write Lock
                    std::unique_lock lock(detected_objects_lock);
                    detected_objects[detected_object._object_id] = detected_object;
                    SPDLOG_DEBUG("Detected Object List Size {0} after consumed: {1}", detected_objects.size(), payload);
                }
            }
            catch (const streets_utils::json_utils::json_parse_exception &e) {
                SPDLOG_ERROR("Exception occured consuming detection message : {0}", e.what());
            }
        }
        SPDLOG_ERROR("Something went wrong, no longer consuming detections." );
    }
References detected_objects, detected_objects_lock, detection_consumer, streets_utils::messages::detected_objects_msg::from_json(), streets_service::streets_service::is_simulation_mode(), streets_service::streets_clock_singleton::sleep_for(), and streets_service::streets_clock_singleton::time_in_ms().
Referenced by start().
create_sdsm()
streets_utils::messages::sdsm::sensor_data_sharing_msg sensor_data_sharing_service::sds_service::create_sdsm () private
Method to create SDSM from detected objects.
Returns
sensor_data_sharing_msg created from detected objects.
Definition at line 171 of file sensor_data_sharing_service.cpp.
{
        streets_utils::messages::sdsm::sensor_data_sharing_msg msg;
        // Read lock
        uint64_t timestamp = ss::streets_clock_singleton::time_in_ms();
        msg._time_stamp = to_sdsm_timestamp(timestamp);
        // Populate with rolling counter
        msg._msg_count = this->_message_count;
        // Populate with infrastructure id
        msg._source_id = this->_infrastructure_id;
        // Populate equipement type
        msg._equipment_type = sdsm::equipment_type::RSU;
        // Polulate ref position
        msg._ref_positon = to_position_3d(this->sdsm_reference_point);
        std::shared_lock lock(detected_objects_lock);
        for (const auto &[object_id, object] : detected_objects){
            auto ned_object = detected_object_enu_to_ned(object);
            auto detected_object_data = to_detected_object_data(ned_object,timestamp);
            // TODO: Update time offset. Currently CARMA-Streets detected object message does not support timestamp
            // This is a bug and needs to be addressed.
            msg._objects.push_back(detected_object_data);
        }
        return msg;
    }
References streets_utils::messages::sdsm::sensor_data_sharing_msg::_equipment_type, _infrastructure_id, _message_count, streets_utils::messages::sdsm::sensor_data_sharing_msg::_msg_count, streets_utils::messages::sdsm::sensor_data_sharing_msg::_objects, streets_utils::messages::sdsm::sensor_data_sharing_msg::_ref_positon, streets_utils::messages::sdsm::sensor_data_sharing_msg::_source_id, streets_utils::messages::sdsm::sensor_data_sharing_msg::_time_stamp, sensor_data_sharing_service::detected_object_enu_to_ned(), detected_objects, detected_objects_lock, sdsm_reference_point, streets_service::streets_clock_singleton::time_in_ms(), simulate_mobilityoperation::timestamp, sensor_data_sharing_service::to_detected_object_data(), sensor_data_sharing_service::to_position_3d(), and sensor_data_sharing_service::to_sdsm_timestamp().
Referenced by produce_sdsms().
FRIEND_TEST() [1/3]
sensor_data_sharing_service::sds_service::FRIEND_TEST (sensorDataSharingServiceTest , consumeDetections)
FRIEND_TEST() [2/3]
sensor_data_sharing_service::sds_service::FRIEND_TEST (sensorDataSharingServiceTest , produceSdsms)
FRIEND_TEST() [3/3]
sensor_data_sharing_service::sds_service::FRIEND_TEST (sensorDataSharingServiceTest , readLanelet2Map)
initialize()
bool sensor_data_sharing_service::sds_service::initialize () override virtual
Method to initialize the sds_service.
Returns
true if successful.
false if not successful.
Reimplemented from streets_service::streets_service.
Definition at line 36 of file sensor_data_sharing_service.cpp.
{
        if (!streets_service::initialize() ) {
            SPDLOG_ERROR("Failed to initialize streets service base!");
            return false;
        }
        SPDLOG_DEBUG("Intializing Sensor Data Sharing Service");
        const std::string lanlet2_map =  streets_service::get_system_config("LANELET2_MAP", "/home/carma-streets/MAP/Intersection.osm");
        if (!read_lanelet_map(lanlet2_map)){
            SPDLOG_ERROR("Failed to read lanlet2 map {0} !", lanlet2_map);
            return false;
        }
        // Read sensor configuration file and get WSG84 location/origin reference frame.
        const std::string sensor_config_file = streets_service::get_system_config("SENSOR_JSON_FILE_PATH", "/home/carma-streets/sensor_configurations/sensors.json");
        const std::string sensor_id = ss::streets_configuration::get_string_config("sensor_id");
        const lanelet::BasicPoint3d pose = parse_sensor_location(sensor_config_file, sensor_id);
        this->sdsm_reference_point =  this->map_projector->reverse(pose);
        // Initialize SDSM Kafka producer
        const std::string sdsm_topic = ss::streets_configuration::get_string_config("sdsm_producer_topic");
        const std::string detection_topic = ss::streets_configuration::get_string_config("detection_consumer_topic");
        const std::string sdsm_geo_reference = ss::streets_configuration::get_string_config("sdsm_geo_reference");
        // Get Infrastructure ID for SDSM messages
        this->_infrastructure_id =  streets_service::get_system_config("INFRASTRUCTURE_ID", "");
        return initialize_kafka_producer(sdsm_topic, sdsm_producer) && initialize_kafka_consumer(detection_topic, detection_consumer);
    }
References _infrastructure_id, detection_consumer, streets_service::streets_configuration::get_string_config(), streets_service::streets_service::initialize_kafka_consumer(), streets_service::streets_service::initialize_kafka_producer(), map_projector, sensor_data_sharing_service::parse_sensor_location(), read_lanelet_map(), sdsm_producer, and sdsm_reference_point.
Referenced by main().
initialize_kafka_consumers_producers()
bool sensor_data_sharing_service::sds_service::initialize_kafka_consumers_producers () private
Initialize Kafka consumers and producers for sensor data sharing service.
Returns
true if successful and false if unsuccessful.
produce_sdsms()
void sensor_data_sharing_service::sds_service::produce_sdsms () private
Loop to produce sensor data sharing messages from detected_objects. Loop will populate sensor data sharing message with most recent detection information, publish message and clear detected object map. Will terminate if kafka producer is no longer running.
Exceptions
std::runtime exception if sdsm_producer == nullptr
Definition at line 138 of file sensor_data_sharing_service.cpp.
{
        if ( !sdsm_producer )  {
            throw std::runtime_error("SDSM consumer is null!");
        }
        SPDLOG_INFO("Starting SDSM Producer!");
        while ( sdsm_producer->is_running() ) {
            try{
                if ( !detected_objects.empty() ) {
                    streets_utils::messages::sdsm::sensor_data_sharing_msg msg = create_sdsm();
                    const std::string json_msg = streets_utils::messages::sdsm::to_json(msg);
                    SPDLOG_DEBUG("Sending SDSM : {0}", json_msg);
                    sdsm_producer->send(json_msg);
                    // Message Count max is 127, reset after max value
                    if ( this->_message_count <= 127) {
                        this->_message_count++;
                    }else {
                        this->_message_count = 0;
                    }
                    // Write Lock
                    std::unique_lock lock(detected_objects_lock);
                    // Clear detected object
                    detected_objects.clear();
                }
            }
            catch( const streets_utils::json_utils::json_parse_exception &e) {
                SPDLOG_ERROR("Exception occurred producing SDSM : {0}", e.what());
            }
            ss::streets_clock_singleton::sleep_for(100); // Sleep for 100 ms between publish
        }
        SPDLOG_CRITICAL("SDSM Producers no longer running.");
    }
References _message_count, create_sdsm(), detected_objects, detected_objects_lock, sdsm_producer, streets_service::streets_clock_singleton::sleep_for(), and streets_utils::messages::sdsm::to_json().
Referenced by start().
read_lanelet_map()
bool sensor_data_sharing_service::sds_service::read_lanelet_map (const std::string & filepath) private
Method to read lanelet2 map.
Parameters
filepath to lanelet2 osm file.
Returns
true if successful.
Definition at line 62 of file sensor_data_sharing_service.cpp.
{
        try
        {
            int projector_type = 1;
            std::string target_frame;
            lanelet::ErrorMessages errors;
            // Parse geo reference info from the lanelet map (.osm)
            lanelet::io_handlers::AutowareOsmParser::parseMapParams(filepath, &projector_type, &target_frame);
            this->map_projector = std::make_unique<lanelet::projection::LocalFrameProjector>(target_frame.c_str());
            this->map_ptr = lanelet::load(filepath, *map_projector.get(), &errors);
            //
            if (!this->map_ptr->empty())
            {
                return true;
            }
        }
        catch (const lanelet::ParseError &ex)
        {
            SPDLOG_ERROR("Cannot read osm file {0}. Error message: {1} .", filepath, ex.what());
        }
        return false;
    }
References map_projector, and map_ptr.
Referenced by initialize().
start()
void sensor_data_sharing_service::sds_service::start () override virtual
Method to start all threads included in the tsc_service.
Reimplemented from streets_service::streets_service.
Definition at line 196 of file sensor_data_sharing_service.cpp.
{
        SPDLOG_DEBUG("Starting Sensor Data Sharing Service");
        streets_service::start();
        std::thread detection_thread(&sds_service::consume_detections, this);
        std::thread sdsm_thread(&sds_service::produce_sdsms, this);
        detection_thread.join();
        sdsm_thread.join();
    }
References consume_detections(), produce_sdsms(), and simulate_timestep::start.
Referenced by main().
Member Data Documentation
_infrastructure_id
std::string sensor_data_sharing_service::sds_service::_infrastructure_id private
Infrastructure ID used as source ID for SDSM broadcast.
Definition at line 90 of file sensor_data_sharing_service.hpp.
Referenced by create_sdsm(), and initialize().
_message_count
uint8_t sensor_data_sharing_service::sds_service::_message_count = 0 private
Message count for SDSM.
Definition at line 95 of file sensor_data_sharing_service.hpp.
Referenced by create_sdsm(), and produce_sdsms().
detected_objects
std::map<int,streets_utils::messages::detected_objects_msg::detected_objects_msg> sensor_data_sharing_service::sds_service::detected_objects private
Map of detected objects. New detections of existing objects will replace old detections.
Definition at line 66 of file sensor_data_sharing_service.hpp.
Referenced by consume_detections(), create_sdsm(), and produce_sdsms().
detected_objects_lock
std::shared_mutex sensor_data_sharing_service::sds_service::detected_objects_lock private
Mutex for thread safe operations on detected objects map.
Definition at line 70 of file sensor_data_sharing_service.hpp.
Referenced by consume_detections(), create_sdsm(), and produce_sdsms().
detection_consumer
std::shared_ptr<kafka_clients::kafka_consumer_worker> sensor_data_sharing_service::sds_service::detection_consumer private
Definition at line 62 of file sensor_data_sharing_service.hpp.
Referenced by ~sds_service(), consume_detections(), and initialize().
map_projector
std::unique_ptr<lanelet::projection::LocalFrameProjector> sensor_data_sharing_service::sds_service::map_projector private
WSG84 Map projection.
Definition at line 79 of file sensor_data_sharing_service.hpp.
Referenced by initialize(), and read_lanelet_map().
map_ptr
lanelet::LaneletMapPtr sensor_data_sharing_service::sds_service::map_ptr private
Lanelet2 Map pointer.
Definition at line 74 of file sensor_data_sharing_service.hpp.
Referenced by read_lanelet_map().
sdsm_producer
std::shared_ptr<kafka_clients::kafka_producer_worker> sensor_data_sharing_service::sds_service::sdsm_producer private
Kafka producer for SDSM JSON.
Definition at line 58 of file sensor_data_sharing_service.hpp.
Referenced by ~sds_service(), initialize(), and produce_sdsms().
sdsm_reference_point
lanelet::GPSPoint sensor_data_sharing_service::sds_service::sdsm_reference_point private
Location of sensor.This is also the sensor's coordinate frame orignin meaning all offsets are interpreted relative to this location.
Definition at line 85 of file sensor_data_sharing_service.hpp.
Referenced by create_sdsm(), and initialize().
The documentation for this class was generated from the following files:
sensor_data_sharing_service/include/sensor_data_sharing_service.hpp
sensor_data_sharing_service/src/sensor_data_sharing_service.cpp