Carma-streets: message_services/src/message_services.cpp File Reference
message_services.cpp File Reference
#include <thread>
#include "vehicle_status_intent_service.h"
#include "streets_configuration.h"
Functions
void vehicle_status_intent_service_call (std::shared_ptr< message_services::message_translations::message_lanelet2_translation > msg_translate_ptr)
int main (int argc, const char **argv)
Function Documentation
main()
int main (int argc, const char ** argv)
Definition at line 15 of file message_services.cpp.
{
    const std::string OSM_FILE_PATH = "../vector_map.osm";
    streets_service::streets_configuration::initialize_logger();
    //initialize lanelet2 message translation object
    auto msg_translate_ptr = std::make_shared<message_services::message_translations::message_lanelet2_translation>(OSM_FILE_PATH);
    std::thread vehicle_status_intent_service_t(vehicle_status_intent_service_call, std::ref(msg_translate_ptr));
    vehicle_status_intent_service_t.join();
    return 0;
}
References streets_service::streets_configuration::initialize_logger(), and vehicle_status_intent_service_call().
vehicle_status_intent_service_call()
void vehicle_status_intent_service_call (std::shared_ptr< message_services::message_translations::message_lanelet2_translation > msg_translate_ptr)
Definition at line 6 of file message_services.cpp.
{
    message_services::services::vehicle_status_intent_service s_v;
    if (s_v.initialize(msg_translate_ptr))
    {
        s_v.start();
    }
}
References message_services::services::vehicle_status_intent_service::initialize(), and message_services::services::vehicle_status_intent_service::start().
Referenced by main().