Carma-streets: streets_utils::json_utils Namespace Reference
streets_utils::json_utils Namespace Reference
Classes
class json_document_parse_error
class json_parse_exception
Runtime exception related to json_utils functions. Thrown when :
Functions
rapidjson::Document parse_json (const std::string &json)
Function to parse std::string JSON with RapidJSON with DOM parsing. Throws json_parse_exception if string is not valid json. Otherwise returns rapidjson::Document
rapidjson::Document parse_json_file (const std::string &filepath)
Function to parse file containing JSON with RapidJSON with DOM parsing. Throws json_parse_exception if string is not valid json. Otherwise returns rapidjson::Document
std::optional< int > parse_int_member (const std::string &member_name, const rapidjson::Value &obj, bool required)
Functions to retrieve int member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
std::optional< unsigned int > parse_uint_member (const std::string &member_name, const rapidjson::Value &obj, bool required)
Functions to retrieve uint member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
std::optional< bool > parse_bool_member (const std::string &member_name, const rapidjson::Value &obj, bool required)
Functions to retrieve bool member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
std::optional< std::string > parse_string_member (const std::string &member_name, const rapidjson::Value &obj, bool required)
Functions to retrieve std::string member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
std::optional< double > parse_double_member (const std::string &member_name, const rapidjson::Value &obj, bool required)
Functions to retrieve double member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
std::optional< rapidjson::Value::ConstObject > parse_object_member (const std::string &member_name, const rapidjson::Value &obj, bool required)
Functions to retrieve object member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
std::optional< rapidjson::Value::ConstArray > parse_array_member (const std::string &member_name, const rapidjson::Value &obj, bool required)
Functions to retrieve array member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
Function Documentation
parse_array_member()
std::optional< rapidjson::Value::ConstArray > streets_utils::json_utils::parse_array_member (const std::string & member_name, const rapidjson::Value & obj, bool required)
Functions to retrieve array member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
Parameters
member_name string member name to search for.
obj JSON object with member
required bool flag to indicate whether member is required by calling code.
Exceptions
json_parse_exception if member is required but not found.
Returns
std::optional<rapidjson::Value::ConstArray>
Definition at line 109 of file json_utils.cpp.
{
        if (obj.HasMember(member_name.c_str()) && obj.FindMember(member_name.c_str())->value.IsArray())
        {
            return obj[member_name.c_str()].GetArray();
        }
        else if (required)
        {
            throw json_parse_exception("Missing or incorrect type for required member " + member_name + "!");
        }
        return std::nullopt;
    }
References simulate_detected_object::obj.
Referenced by streets_utils::messages::detected_objects_msg::from_json(), and streets_utils::messages::sdsm::parse_detected_object_list().
parse_bool_member()
std::optional< bool > streets_utils::json_utils::parse_bool_member (const std::string & member_name, const rapidjson::Value & obj, bool required)
Functions to retrieve bool member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
Parameters
member_name string member name to search for.
obj JSON object with member
required bool flag to indicate whether member is required by calling code.
Exceptions
json_parse_exception if member is required but not found.
Returns
std::optional<boll>
Definition at line 58 of file json_utils.cpp.
{
        std::optional<bool> member;
        if (obj.HasMember(member_name.c_str()) && obj.FindMember(member_name.c_str())->value.IsBool())
        {
            member = obj[member_name.c_str()].GetBool();
        }
        else if (required)
        {
            throw json_parse_exception("Missing or incorrect type for required member " + member_name + "!");
        }
        return member;
    };
References simulate_detected_object::obj.
parse_double_member()
std::optional< double > streets_utils::json_utils::parse_double_member (const std::string & member_name, const rapidjson::Value & obj, bool required)
Functions to retrieve double member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
Parameters
member_name string member name to search for.
obj JSON object with member
required bool flag to indicate whether member is required by calling code.
Exceptions
json_parse_exception if member is required but not found.
Returns
std::optional<double>
Definition at line 84 of file json_utils.cpp.
{
        std::optional<double> member;
        if (obj.HasMember(member_name.c_str()) && obj.FindMember(member_name.c_str())->value.IsDouble())
        {
            member = obj[member_name.c_str()].GetDouble();
        }
        else if (required)
        {
            throw json_parse_exception("Missing or incorrect type for required member " + member_name + "!");
        }
        return member;
    };
References simulate_detected_object::obj.
Referenced by streets_utils::messages::detected_objects_msg::from_json(), streets_utils::messages::detected_objects_msg::parse_cartesian_3d(), sensor_data_sharing_service::parse_sensor_location(), streets_utils::messages::detected_objects_msg::parse_size(), and streets_utils::messages::detected_objects_msg::parse_vector3d().
parse_int_member()
std::optional< int > streets_utils::json_utils::parse_int_member (const std::string & member_name, const rapidjson::Value & obj, bool required)
Functions to retrieve int member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
Parameters
member_name string member name to search for.
obj JSON object with member
required bool flag to indicate whether member is required by calling code.
Exceptions
json_parse_exception if member is required but not found.
Returns
std::optional<int>
Definition at line 32 of file json_utils.cpp.
{
        std::optional<int64_t> member;
        if (obj.HasMember(member_name.c_str()) && obj.FindMember(member_name.c_str())->value.IsInt64())
        {
            member = obj[member_name.c_str()].GetInt64();
        }
        else if (required)
        {
            throw json_parse_exception("Missing or incorrect type for required member " + member_name + "!");
        }
        return member;
    }
References simulate_detected_object::obj.
Referenced by streets_utils::messages::sdsm::parse_acceleration_4_way(), streets_utils::messages::sdsm::parse_detected_object_data_common(), streets_utils::messages::sdsm::parse_position_3d(), streets_utils::messages::sdsm::parse_position_offset(), streets_utils::messages::sdsm::parse_time_stamp(), streets_utils::messages::sdsm::parse_vehicle_angular_velocity_set(), and streets_utils::messages::sdsm::parse_vehicle_attitude().
parse_json()
rapidjson::Document streets_utils::json_utils::parse_json (const std::string & json)
Function to parse std::string JSON with RapidJSON with DOM parsing. Throws json_parse_exception if string is not valid json. Otherwise returns rapidjson::Document
Parameters
json std::string JSON to parse
Exceptions
json_parse_exception if passed string is not valid json.
Returns
resulting rapidjson::Document
Definition at line 5 of file json_utils.cpp.
{
        rapidjson::Document obj;
        obj.Parse(json);
        if (obj.HasParseError())
        {
            // TODO: Change to json_document_parse_exception. Requires changes to services and unit tests
            throw json_parse_exception("Message JSON is misformatted. JSON parsing failed!");
        }
        return obj;
    }
References simulate_detected_object::obj.
Referenced by streets_utils::messages::detected_objects_msg::from_json(), and streets_utils::messages::sdsm::from_json().
parse_json_file()
rapidjson::Document streets_utils::json_utils::parse_json_file (const std::string & filepath)
Function to parse file containing JSON with RapidJSON with DOM parsing. Throws json_parse_exception if string is not valid json. Otherwise returns rapidjson::Document
Parameters
json std::string JSON to parse
Exceptions
json_parse_exception if passed string is not valid json.
Returns
resulting rapidjson::Document
Definition at line 16 of file json_utils.cpp.
{
         // Parse JSON configuration file
        std::ifstream file(filepath);
        if (!file.is_open()) {
            throw std::invalid_argument("Unable to open Streets configuration file " + filepath + " due to : " + strerror(errno) + ".");
        }
        // Add file contents to stream and parse stream into Document
        rapidjson::IStreamWrapper isw(file);
        rapidjson::Document doc;
        doc.ParseStream(isw);
        if (doc.HasParseError()){
            throw json_document_parse_error("Encounter document parse error while attempting to parse sensor configuration file " + filepath + "!", doc);
        }
        file.close();
        return doc;
    }
Referenced by sensor_data_sharing_service::parse_sensor_location().
parse_object_member()
std::optional< rapidjson::Value::ConstObject > streets_utils::json_utils::parse_object_member (const std::string & member_name, const rapidjson::Value & obj, bool required)
Functions to retrieve object member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
Parameters
member_name string member name to search for.
obj JSON object with member
required bool flag to indicate whether member is required by calling code.
Exceptions
json_parse_exception if member is required but not found.
Returns
std::optional<rapidJson::Value::ConstObject>
Definition at line 97 of file json_utils.cpp.
{
        if (obj.HasMember(member_name.c_str()) && obj.FindMember(member_name.c_str())->value.IsObject())
        {
            return obj[member_name.c_str()].GetObject();
        }
        else if (required)
        {
            throw json_parse_exception("Missing or incorrect type for required member " + member_name + "!");
        }
        return std::nullopt;
    }
References simulate_detected_object::obj.
Referenced by streets_utils::messages::detected_objects_msg::from_json(), streets_utils::messages::sdsm::from_json(), streets_utils::messages::sdsm::parse_detected_object_data_common(), streets_utils::messages::sdsm::parse_detected_object_data_optional(), streets_utils::messages::sdsm::parse_detected_object_list(), streets_utils::messages::sdsm::parse_detected_obstacle_data(), streets_utils::messages::sdsm::parse_detected_vehicle_data(), streets_utils::messages::sdsm::parse_detected_vru_data(), and sensor_data_sharing_service::parse_sensor_location().
parse_string_member()
std::optional< std::string > streets_utils::json_utils::parse_string_member (const std::string & member_name, const rapidjson::Value & obj, bool required)
Functions to retrieve std::string member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
Parameters
member_name string member name to search for.
obj JSON object with member
required bool flag to indicate whether member is required by calling code.
Exceptions
json_parse_exception if member is required but not found.
Returns
std::optional<std::string>
Definition at line 71 of file json_utils.cpp.
{
        std::optional<std::string> member;
        if (obj.HasMember(member_name.c_str()) && obj.FindMember(member_name.c_str())->value.IsString())
        {
            member = obj[member_name.c_str()].GetString();
        }
        else if (required)
        {
            throw json_parse_exception("Missing or incorrect type for required member " + member_name + "!");
        }
        return member;
    };
References simulate_detected_object::obj.
Referenced by streets_utils::messages::detected_objects_msg::from_json(), streets_utils::messages::sdsm::from_json(), streets_utils::messages::sdsm::parse_detected_vehicle_data(), and sensor_data_sharing_service::parse_sensor_location().
parse_uint_member()
std::optional< unsigned int > streets_utils::json_utils::parse_uint_member (const std::string & member_name, const rapidjson::Value & obj, bool required)
Functions to retrieve uint member values from JSON object RapidJSON with DOM parsing. Functions will return unintialized std::optional for optional members that are not found in JSON object and will throw json_parse_exception. for required members that are not found in JSON object.
Parameters
member_name string member name to search for.
obj JSON object with member
required bool flag to indicate whether member is required by calling code.
Exceptions
json_parse_exception if member is required but not found.
Returns
std::optional<unsigned int>
Definition at line 45 of file json_utils.cpp.
{
        std::optional<u_int64_t> member;
        if (obj.HasMember(member_name.c_str()) && obj.FindMember(member_name.c_str())->value.IsUint64())
        {
            member = obj[member_name.c_str()].GetUint64();
        }
        else if (required)
        {
            throw json_parse_exception("Missing or incorrect type for required member " + member_name + "!");
        }
        return member;
    };
References simulate_detected_object::obj.
Referenced by streets_utils::messages::detected_objects_msg::from_json(), streets_utils::messages::sdsm::from_json(), streets_utils::messages::sdsm::parse_detected_object_data_common(), streets_utils::messages::sdsm::parse_detected_vehicle_data(), streets_utils::messages::sdsm::parse_detected_vru_data(), streets_utils::messages::sdsm::parse_elevation_confidence(), streets_utils::messages::sdsm::parse_obstacle_size(), streets_utils::messages::sdsm::parse_obstacle_size_confidence(), streets_utils::messages::sdsm::parse_position_confidence_set(), streets_utils::messages::sdsm::parse_positional_accuracy(), streets_utils::messages::sdsm::parse_propelled_information(), streets_utils::messages::sdsm::parse_time_stamp(), streets_utils::messages::sdsm::parse_vehicle_angular_velocity_confidence_set(), streets_utils::messages::sdsm::parse_vehicle_attitude_confidence(), streets_utils::messages::sdsm::parse_vehicle_size(), and streets_utils::messages::sdsm::parse_vehicle_size_confidence().