Carma-streets: simulate_bsm_mobilityPath_mobilityoperation Namespace Reference
simulate_bsm_mobilityPath_mobilityoperation Namespace Reference
Functions
def read_json (json_name)
def produce_bsm ()
def produce_operation ()
def produce_mobility_path ()
Variables
bsm_th = threading.Thread(target=produce_bsm)
mobility_path_th = threading.Thread(target=produce_mobility_path)
mobility_operation_th = threading.Thread(target=produce_operation)
Function Documentation
produce_bsm()
def simulate_bsm_mobilityPath_mobilityoperation.produce_bsm ()
Definition at line 16 of file simulate_bsm_mobilityPath_mobilityoperation.py.
def produce_bsm():
    producer = KafkaProducer(bootstrap_servers=["127.0.0.1:9092"],
                             value_serializer=lambda x: json.dumps(x).encode('utf-8'))
    count = 100
    i = 0
    while(i < count):
        data = read_json('bsm_12_8.json')
        data["core_data"]["msg_count"] = str(i)
        data["core_data"]["speed"] = str(i)
        producer.send('v2xhub_bsm_in', value=data)
        print('Sent a bsm.')
        i += 1
        sleep(0.1)
        producer.flush()
References read_json().
produce_mobility_path()
def simulate_bsm_mobilityPath_mobilityoperation.produce_mobility_path ()
Definition at line 52 of file simulate_bsm_mobilityPath_mobilityoperation.py.
def produce_mobility_path():
    producer = KafkaProducer(bootstrap_servers=["127.0.0.1:9092"],
                             value_serializer=lambda x: json.dumps(x).encode('utf-8'))
    i = 0
    count = 100
    while(i < count):
        data = read_json('mobilitypath_12_8.json')
        timestamp = int(time.time())*1000 + i*100
        data["metadata"]["timestamp"] = str(timestamp)
        producer.send('v2xhub_mobility_path_in', value=data)
        print('Sent a mobilitypath.')
        i += 1
        sleep(0.1)
        producer.flush()
References read_json().
produce_operation()
def simulate_bsm_mobilityPath_mobilityoperation.produce_operation ()
Definition at line 32 of file simulate_bsm_mobilityPath_mobilityoperation.py.
def produce_operation():
    producer = KafkaProducer(bootstrap_servers=["127.0.0.1:9092"],
                             value_serializer=lambda x: json.dumps(x).encode('utf-8'))
    count = 100
    i = 0
    while(i < count):
        data = read_json('mobilityoperation_12_8.json')
        timestamp = int(time.time())*1000 + i*100
        data["metadata"]["timestamp"] = str(timestamp)
        strategy_params = "msg_count:" + \
            str(i) + ",access: 0,max_accel:1.500000,max_decel: -1.000000,react_time: 4.500000, min_gap: 5.000000, depart_pos: " \
            + str(i) + ",turn_direction:straight, sec_mark:37056"
        data["strategy_params"] = strategy_params
        producer.send('v2xhub_mobility_operation_in', value=data)
        print('Sent a mobilityoperation.')
        i += 1
        sleep(0.1)
        producer.flush()
References read_json().
read_json()
def simulate_bsm_mobilityPath_mobilityoperation.read_json (json_name)
Definition at line 9 of file simulate_bsm_mobilityPath_mobilityoperation.py.
def read_json(json_name):
    data = {}
    with open(json_name, "r") as json_file:
        data = json.load(json_file)
    return data
Referenced by produce_bsm(), produce_mobility_path(), and produce_operation().
Variable Documentation
bsm_th
simulate_bsm_mobilityPath_mobilityoperation.bsm_th = threading.Thread(target=produce_bsm)
Definition at line 69 of file simulate_bsm_mobilityPath_mobilityoperation.py.
mobility_operation_th
simulate_bsm_mobilityPath_mobilityoperation.mobility_operation_th = threading.Thread(target=produce_operation)
Definition at line 71 of file simulate_bsm_mobilityPath_mobilityoperation.py.
mobility_path_th
simulate_bsm_mobilityPath_mobilityoperation.mobility_path_th = threading.Thread(target=produce_mobility_path)
Definition at line 70 of file simulate_bsm_mobilityPath_mobilityoperation.py.