Carma-streets: streets_utils::messages::detected_objects_msg Namespace Reference
streets_utils::messages::detected_objects_msg Namespace Reference
Classes
struct cartesian_point
Struct for world frame coordinates.
struct detected_objects_msg
Sensor Detected Object information.
struct size
Struct for size dimensions.
struct vector_3d
3 dimensional vector struct.
Functions
detected_objects_msg from_json (const std::string &val)
cartesian_point parse_cartesian_3d (const rapidjson::Value &val)
std::vector< std::vector< double > > parse_covariance (const rapidjson::Value::ConstArray &val)
vector_3d parse_vector3d (const rapidjson::Value &val)
size parse_size (const rapidjson::Value &val)
Function Documentation
from_json()
detected_objects_msg streets_utils::messages::detected_objects_msg::from_json (const std::string & val)
Definition at line 20 of file detected_obj_msg_deserializer.cpp.
    {
        // Deserializes the incoming json message
        rapidjson::Document document = streets_utils::json_utils::parse_json(json);
        detected_objects_msg msg;
        msg._type = streets_utils::json_utils::parse_string_member("type",document, true).value();
        msg._confidence = streets_utils::json_utils::parse_double_member("confidence", document, true).value();
        msg._sensor_id = streets_utils::json_utils::parse_string_member("sensorId", document, true).value();
        msg._proj_string = streets_utils::json_utils::parse_string_member("projString", document, true).value();
        msg._object_id = streets_utils::json_utils::parse_uint_member("objectId", document, true).value();
        auto position_obj = streets_utils::json_utils::parse_object_member("position", document, true).value();
        msg._position = parse_cartesian_3d(position_obj);
        auto position_cov_obj = streets_utils::json_utils::parse_array_member("positionCovariance", document, true).value();
        msg._position_covariance = parse_covariance(position_cov_obj);
        auto velocity_obj = streets_utils::json_utils::parse_object_member("velocity", document, true).value();
        msg._velocity = parse_vector3d(velocity_obj);
        auto velocity_cov_obj = streets_utils::json_utils::parse_array_member("velocityCovariance", document, true).value();
        msg._velocity_covariance = parse_covariance(velocity_cov_obj);
        auto angular_velocity_obj = streets_utils::json_utils::parse_object_member("angularVelocity", document, true).value();
        msg._angular_velocity = parse_vector3d(angular_velocity_obj);
        auto angular_velocity_cov_obj = streets_utils::json_utils::parse_array_member("angularVelocityCovariance", document, true).value();
        msg._angular_velocity_covariance = parse_covariance(angular_velocity_cov_obj);
        auto size_obj = streets_utils::json_utils::parse_object_member("size", document, true).value();
        msg._size = parse_size(size_obj);
        msg._timestamp = streets_utils::json_utils::parse_uint_member("timestamp", document, true).value();
        return msg;
    }
References streets_utils::messages::detected_objects_msg::detected_objects_msg::_angular_velocity, streets_utils::messages::detected_objects_msg::detected_objects_msg::_angular_velocity_covariance, streets_utils::messages::detected_objects_msg::detected_objects_msg::_confidence, streets_utils::messages::detected_objects_msg::detected_objects_msg::_object_id, streets_utils::messages::detected_objects_msg::detected_objects_msg::_position, streets_utils::messages::detected_objects_msg::detected_objects_msg::_position_covariance, streets_utils::messages::detected_objects_msg::detected_objects_msg::_proj_string, streets_utils::messages::detected_objects_msg::detected_objects_msg::_sensor_id, streets_utils::messages::detected_objects_msg::detected_objects_msg::_size, streets_utils::messages::detected_objects_msg::detected_objects_msg::_timestamp, streets_utils::messages::detected_objects_msg::detected_objects_msg::_type, streets_utils::messages::detected_objects_msg::detected_objects_msg::_velocity, streets_utils::messages::detected_objects_msg::detected_objects_msg::_velocity_covariance, streets_utils::json_utils::parse_array_member(), parse_cartesian_3d(), parse_covariance(), streets_utils::json_utils::parse_double_member(), streets_utils::json_utils::parse_json(), streets_utils::json_utils::parse_object_member(), parse_size(), streets_utils::json_utils::parse_string_member(), streets_utils::json_utils::parse_uint_member(), and parse_vector3d().
Referenced by sensor_data_sharing_service::sds_service::consume_detections().
parse_cartesian_3d()
cartesian_point streets_utils::messages::detected_objects_msg::parse_cartesian_3d (const rapidjson::Value & val)
Definition at line 58 of file detected_obj_msg_deserializer.cpp.
    {
        cartesian_point point;
        try {
            point._x = streets_utils::json_utils::parse_double_member("x", val, true).value();
            point._y = streets_utils::json_utils::parse_double_member("y", val, true).value();
            point._z = streets_utils::json_utils::parse_double_member("z", val, true).value();
            return point;
        }
        catch (const streets_utils::json_utils::json_parse_exception &e) {
            throw streets_utils::json_utils::json_parse_exception("Parsing error occured during parsing of cartesian_3d: " + std::string(e.what()));
        }
    }
References streets_utils::messages::detected_objects_msg::cartesian_point::_x, streets_utils::messages::detected_objects_msg::cartesian_point::_y, streets_utils::messages::detected_objects_msg::cartesian_point::_z, and streets_utils::json_utils::parse_double_member().
Referenced by from_json().
parse_covariance()
std::vector< std::vector< double > > streets_utils::messages::detected_objects_msg::parse_covariance (const rapidjson::Value::ConstArray & val)
Definition at line 87 of file detected_obj_msg_deserializer.cpp.
    {
        // Initialize 3x3 covariance matrix
        std::vector<std::vector<double>> covariance;
        for (rapidjson::SizeType i = 0; i < val.Size(); i++)
        {
            const rapidjson::Value& row = val[i];
            std::vector<double> val_row;
            for (rapidjson::SizeType  j = 0; j < row.Size(); j++)
            {
                val_row.push_back(val[i][j].GetDouble());
            }
            covariance.push_back(val_row);
        }
        return covariance;
    }
References simulate_bsm::i.
Referenced by from_json().
parse_size()
size streets_utils::messages::detected_objects_msg::parse_size (const rapidjson::Value & val)
Definition at line 106 of file detected_obj_msg_deserializer.cpp.
    {
        size size_obj;
        try {
            size_obj._length = streets_utils::json_utils::parse_double_member("length", val, true).value();
            size_obj._height = streets_utils::json_utils::parse_double_member("height", val, true).value();
            size_obj._width = streets_utils::json_utils::parse_double_member("width", val, true).value();
        }
        catch (const streets_utils::json_utils::json_parse_exception &e) {
            throw streets_utils::json_utils::json_parse_exception("Parsing error occured during parsing of size: " + std::string(e.what()));
        }
        return size_obj;
    }
References streets_utils::messages::detected_objects_msg::size::_height, streets_utils::messages::detected_objects_msg::size::_length, streets_utils::messages::detected_objects_msg::size::_width, and streets_utils::json_utils::parse_double_member().
Referenced by from_json().
parse_vector3d()
vector_3d streets_utils::messages::detected_objects_msg::parse_vector3d (const rapidjson::Value & val)
Definition at line 72 of file detected_obj_msg_deserializer.cpp.
    {
        vector_3d vector;
        try {
            vector._x = streets_utils::json_utils::parse_double_member("x", val, true).value();
            vector._y = streets_utils::json_utils::parse_double_member("y", val, true).value();
            vector._z = streets_utils::json_utils::parse_double_member("z", val, true).value();
        }
        catch (const streets_utils::json_utils::json_parse_exception &e) {
            throw streets_utils::json_utils::json_parse_exception("Parsing error occured during parsing of vector3d: " + std::string(e.what()) );
        }
        return vector;
    }
References streets_utils::messages::detected_objects_msg::vector_3d::_x, streets_utils::messages::detected_objects_msg::vector_3d::_y, streets_utils::messages::detected_objects_msg::vector_3d::_z, and streets_utils::json_utils::parse_double_member().
Referenced by from_json().