Carma-streets: simulate_mobilityoperation Namespace Reference
simulate_mobilityoperation Namespace Reference
Functions
def read_json (json_name)
Variables
producer
int count = 10
int i = 0
def data = read_json('mobilityoperation.json')
string strategy_params = "msg_count:" + \
int timestamp = int(data["metadata"]["timestamp"]) + i
value
Function Documentation
read_json()
def simulate_mobilityoperation.read_json (json_name)
Definition at line 8 of file simulate_mobilityoperation.py.
def read_json(json_name):
    data = {}
    with open(json_name, "r") as json_file:
        data = json.load(json_file)
    return data
Variable Documentation
count
int simulate_mobilityoperation.count = 10
Definition at line 18 of file simulate_mobilityoperation.py.
data
def simulate_mobilityoperation.data = read_json('mobilityoperation.json')
Definition at line 21 of file simulate_mobilityoperation.py.
i
int simulate_mobilityoperation.i = 0
Definition at line 19 of file simulate_mobilityoperation.py.
producer
simulate_mobilityoperation.producer
Initial value:
=  KafkaProducer(bootstrap_servers=["127.0.0.1:9092"],
                             value_serializer=lambda x: json.dumps(x).encode('utf-8'))
Definition at line 16 of file simulate_mobilityoperation.py.
strategy_params
string simulate_mobilityoperation.strategy_params = "msg_count:" + \
Definition at line 22 of file simulate_mobilityoperation.py.
timestamp
int simulate_mobilityoperation.timestamp = int(data["metadata"]["timestamp"]) + i
Definition at line 26 of file simulate_mobilityoperation.py.
Referenced by message_services::models::mobilityoperation.asJsonObject(), message_services::models::mobilitypath.asJsonObject(), message_services::services::vehicle_status_intent_service.compose_vehicle_status_intent(), sensor_data_sharing_service::sds_service.create_sdsm(), streets_vehicle_scheduler::vehicle_scheduler.estimate_vehicles_at_common_time(), streets_desired_phase_plan::streets_desired_phase_plan.fromJson(), message_services::models::mobilityoperation.generate_hash_sender_timestamp_id(), message_services::models::mobilitypath.generate_hash_sender_timestamp_id(), traffic_signal_controller_service::tsc_service.log_spat_latency(), and streets_desired_phase_plan::streets_desired_phase_plan.toJson().
value
simulate_mobilityoperation.value
Definition at line 28 of file simulate_mobilityoperation.py.