var namespacestreets__signal__optimization =
[
    [ "streets_desired_phase_plan_arbitrator", "classstreets__signal__optimization_1_1streets__desired__phase__plan__arbitrator.html", "classstreets__signal__optimization_1_1streets__desired__phase__plan__arbitrator" ],
    [ "streets_desired_phase_plan_arbitrator_exception", "classstreets__signal__optimization_1_1streets__desired__phase__plan__arbitrator__exception.html", "classstreets__signal__optimization_1_1streets__desired__phase__plan__arbitrator__exception" ]
];