Carma-streets: streets_utils::messages::sdsm Namespace Reference
streets_utils::messages::sdsm Namespace Reference
Classes
struct acceleration_set_4_way
struct angular_velocity_confidence_set
struct angular_velocity_set
struct attitude
struct attitude_confidence
struct detected_object_data
struct detected_object_data_common
struct detected_obstacle_data
struct detected_vehicle_data
struct detected_vru_data
struct obstacle_size
struct obstacle_size_confidence
struct position_3d
struct position_confidence_set
struct position_offset
struct positional_accuracy
struct sensor_data_sharing_msg
struct time_stamp
struct vehicle_size
struct vehicle_size_confidence
Enumerations
enum class acceleration_confidence {
UNAVAILABLE = 0 , ACCL_100 = 1 , ACCL_10 = 2 , ACCL_5 = 3 ,
ACCL_1 = 4 , ACCL_0_1 = 5 , ACCL_0_05 = 6 , ACCL_0_01 = 7
}
enum class angular_velocity_confidence {
UNAVAILABLE = 0 , DEGSEC_100 = 1 , DEGSEC_10 = 2 , DEGSEC_05 = 3 ,
DEGSEC_01 = 4 , DEGSEC_0_1 = 5 , DEGSEC_0_05 = 6 , DEGSEC_0_01 = 7
}
enum class equipment_type { UNKNOWN = 0 , RSU = 1 , OBU = 2 , VRU = 3 }
enum class heading_confidence {
UNAVAILABLE = 0 , PREC_10_deg = 1 , PREC_05_deg = 2 , PREC_01_deg = 3 ,
PREC_0_1_deg = 4 , PREC_0_05_deg = 5 , PREC_0_01_deg = 6 , PREC_0_0125_deg = 7
}
enum class object_type { UNKNOWN = 0 , VEHICLE = 1 , VRU = 2 , ANIMAL = 3 }
enum class position_confidence {
UNAVAILABLE = 0 , A_500M = 1 , A_200M = 2 , A_100M = 3 ,
A_50M = 4 , A_20M = 5 , A_10M = 6 , A_5M = 7 ,
A_2M = 8 , A_1M = 9 , A_50CM = 10 , A_20CM = 11 ,
A_10CM = 12 , A_5CM = 13 , A_2CM = 14 , A_1CM = 15
}
enum class size_value_confidence {
UNAVAILABLE = 0 , SIZE_100 = 1 , SIZE_50 = 2 , SIZE_20 = 3 ,
SIZE_10 = 4 , SIZE_5 = 5 , SIZE_2 = 6 , SIZE_1 = 7 ,
SIZE_0_5 = 8 , SIZE_0_2 = 9 , SIZE_0_1 = 10 , SIZE_0_05 = 11 ,
SIZE_0_02 = 12 , SIZE_0_01 = 13
}
enum class speed_confidence {
UNAVAILABLE = 0 , PREC_100ms = 1 , PREC_10ms = 2 , PREC_5ms = 3 ,
PREC_1ms = 4 , PREC_0_1ms = 5 , PREC_0_05ms = 6 , PREC_0_01ms = 7
}
enum class time_confidence {
UNAVAILABLE = 0 , TIME_100_000 = 1 , TIME_050_000 = 2 , TIME_020_000 = 3 ,
TIME_010_000 = 4 , TIME_002_000 = 5 , TIME_001_000 = 6 , TIME_000_500 = 7 ,
TIME_000_200 = 8 , TIME_000_100 = 9 , TIME_000_050 = 10 , TIME_000_020 = 11 ,
TIME_000_010 = 12 , TIME_000_005 = 13 , TIME_000_002 = 14 , TIME_000_001 = 15 ,
TIME_000_000_5 = 16 , TIME_000_000_2 = 17 , TIME_000_000_1 = 18 , TIME_000_000_05 = 19 ,
TIME_000_000_02 = 20 , TIME_000_000_01 = 21 , TIME_000_000_005 = 22 , TIME_000_000_002 = 23 ,
TIME_000_000_001 = 24 , TIME_000_000_000_5 = 25 , TIME_000_000_000_2 = 26 , TIME_000_000_000_1 = 27 ,
TIME_000_000_000_05 = 28 , TIME_000_000_000_02 = 29 , TIME_000_000_000_01 = 30 , TIME_000_000_000_005 = 31 ,
TIME_000_000_000_002 = 32 , TIME_000_000_000_001 = 33 , TIME_000_000_000_000_5 = 34 , TIME_000_000_000_000_2 = 35 ,
TIME_000_000_000_000_1 = 36 , TIME_000_000_000_000_05 = 37 , TIME_000_000_000_000_02 = 38 , TIME_000_000_000_000_01 = 39
}
enum class animal_propelled_type { UNAVAILABLE = 0 , OTHER_TYPES = 1 , ANIMAL_MOUNTED = 2 , ANIMAL_DRAWN_CARRIAGE = 3 }
enum class attachment {
UNAVAILABLE = 0 , STROLLER = 1 , BICYLE_TRAILER = 2 , CART = 3 ,
WHEEL_CHAIR = 4 , OTHER_WALK_ASSIST_ATTACHMENTS = 5 , PET = 6
}
enum class human_propelled_type {
UNAVAILABLE = 0 , OTHER_TYPES = 1 , ON_FOOT = 2 , SKATEBOARD = 3 ,
PUSH_OR_KICK_SCOOTER = 4 , WHEELCHAIR = 5
}
enum class motorized_propelled_type {
UNAVAILABLE = 0 , OTHER_TYPES = 1 , WHEEL_CHAIR = 2 , BICYCLE = 3 ,
SCOOTER = 4 , SELF_BALANCING_DEVICE = 5
}
enum class personal_device_user_type {
UNAVAILABLE = 0 , PEDESTRIAN = 1 , PEDALCYCLIST = 2 , PUBLIC_SAFETY_WORKER = 3 ,
ANIMAL = 4
}
Functions
sensor_data_sharing_msg from_json (const std::string &val)
time_stamp parse_time_stamp (const rapidjson::Value &val)
position_3d parse_position_3d (const rapidjson::Value &val)
positional_accuracy parse_positional_accuracy (const rapidjson::Value &val)
std::optional< position_confidence > parse_elevation_confidence (const rapidjson::Value &val)
std::vector< detected_object_data > parse_detected_object_list (const rapidjson::Value &val)
detected_object_data_common parse_detected_object_data_common (const rapidjson::Value &val)
acceleration_set_4_way parse_acceleration_4_way (const rapidjson::Value &val)
std::optional< std::variant< detected_obstacle_data, detected_vehicle_data, detected_vru_data > > parse_detected_object_data_optional (const rapidjson::Value &val)
position_offset parse_position_offset (const rapidjson::Value &val)
position_confidence_set parse_position_confidence_set (const rapidjson::Value &val)
detected_obstacle_data parse_detected_obstacle_data (const rapidjson::Value &val)
detected_vehicle_data parse_detected_vehicle_data (const rapidjson::Value &val)
detected_vru_data parse_detected_vru_data (const rapidjson::Value &val)
obstacle_size parse_obstacle_size (const rapidjson::Value &val)
obstacle_size_confidence parse_obstacle_size_confidence (const rapidjson::Value &val)
std::optional< std::variant< human_propelled_type, motorized_propelled_type, animal_propelled_type > > parse_propelled_information (const rapidjson::Value &val)
attitude parse_vehicle_attitude (const rapidjson::Value &val)
attitude_confidence parse_vehicle_attitude_confidence (const rapidjson::Value &val)
angular_velocity_set parse_vehicle_angular_velocity_set (const rapidjson::Value &val)
angular_velocity_confidence_set parse_vehicle_angular_velocity_confidence_set (const rapidjson::Value &val)
vehicle_size parse_vehicle_size (const rapidjson::Value &val)
vehicle_size_confidence parse_vehicle_size_confidence (const rapidjson::Value &val)
acceleration_confidence acceleration_confidence_from_int (const unsigned int i)
angular_velocity_confidence angular_velocity_confidence_from_int (const unsigned int i)
equipment_type equipment_type_from_int (const unsigned int i)
Function to convert integers to equiment type. Default to UNKNOWN.
heading_confidence heading_confidence_from_int (const unsigned int i)
object_type object_type_from_int (const int i)
position_confidence position_confidence_from_int (const int i)
size_value_confidence size_value_confidence_from_int (const unsigned int i)
speed_confidence speed_confidence_from_int (const unsigned int i)
time_confidence time_confidence_from_int (const int i)
animal_propelled_type animal_propelled_type_from_int (const unsigned int i)
attachment attachment_from_int (const int i)
human_propelled_type human_propelled_type_from_int (const int i)
motorized_propelled_type motorized_propelled_type_from_int (const unsigned int i)
personal_device_user_type personal_device_user_type_from_int (const unsigned int i)
std::string to_json (const sensor_data_sharing_msg &val)
rapidjson::Value create_timestamp (const time_stamp &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_position_3d (const position_3d &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_positional_accuracy (const positional_accuracy &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_detected_object_list (const std::vector< detected_object_data > &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_detected_object_data (const detected_object_data &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_detected_object_data_common (const detected_object_data_common &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_detected_object_data_optional (const std::variant< detected_obstacle_data, detected_vehicle_data, detected_vru_data > &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_detected_obstacle_data (const detected_obstacle_data &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_obstacle_size (const obstacle_size &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_obstacle_size_confidence (const obstacle_size_confidence &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_detected_vru_data (const detected_vru_data &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_propelled_information (const std::variant< human_propelled_type, motorized_propelled_type, animal_propelled_type > &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_detected_vehicle_data (const detected_vehicle_data &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_vehicle_attitude (const attitude &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_vehicle_attitude_confidence (const attitude_confidence &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_angular_velocity (const angular_velocity_set &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_angular_velocity_confidence (const angular_velocity_confidence_set &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_vehicle_size (const vehicle_size &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_vehicle_size_confidence (const vehicle_size_confidence &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_accelaration_set_4_way (const acceleration_set_4_way &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_position_3d (const position_offset &val, rapidjson::Document::AllocatorType &allocator)
rapidjson::Value create_position_confidence_set (const position_confidence_set &val, rapidjson::Document::AllocatorType &allocator)
Enumeration Type Documentation
acceleration_confidence
enum class streets_utils::messages::sdsm::acceleration_confidence strong
Enumerator
UNAVAILABLE
ACCL_100
ACCL_10
ACCL_5
ACCL_1
ACCL_0_1
ACCL_0_05
ACCL_0_01
Definition at line 17 of file acceleration_confidence.hpp.
{
        UNAVAILABLE = 0,    // Not available
        ACCL_100 = 1,     // 100 m/s^2
        ACCL_10 = 2,      // 10 m/s^2
        ACCL_5 = 3,       // 5 m/s^2
        ACCL_1 = 4,       // 1 m/s^2
        ACCL_0_1 = 5,     // 0.1 m/s^2
        ACCL_0_05 = 6,    // 0.05 m/s^2
        ACCL_0_01 = 7     // 0.01 m/s^2
    };
angular_velocity_confidence
enum class streets_utils::messages::sdsm::angular_velocity_confidence strong
Enumerator
UNAVAILABLE
DEGSEC_100
DEGSEC_10
DEGSEC_05
DEGSEC_01
DEGSEC_0_1
DEGSEC_0_05
DEGSEC_0_01
Definition at line 17 of file angular_velocity_confidence.hpp.
{
        UNAVAILABLE = 0,
        DEGSEC_100 = 1,         // 100 degrees
        DEGSEC_10 = 2,          // 10 degrees
        DEGSEC_05 = 3,          // 5 degrees
        DEGSEC_01 = 4,          // 1 degrees
        DEGSEC_0_1 = 5,         // 0.1 degrees
        DEGSEC_0_05 = 6,        // 0.05 degrees
        DEGSEC_0_01 = 7,        // 0.01 degrees
    };
animal_propelled_type
enum class streets_utils::messages::sdsm::animal_propelled_type strong
Enumerator
UNAVAILABLE
OTHER_TYPES
ANIMAL_MOUNTED
ANIMAL_DRAWN_CARRIAGE
Definition at line 18 of file animal_propelled_type.hpp.
{
        UNAVAILABLE = 0,
        OTHER_TYPES = 1,
        ANIMAL_MOUNTED = 2,
        ANIMAL_DRAWN_CARRIAGE = 3,
    };
attachment
enum class streets_utils::messages::sdsm::attachment strong
Enumerator
UNAVAILABLE
STROLLER
BICYLE_TRAILER
CART
WHEEL_CHAIR
OTHER_WALK_ASSIST_ATTACHMENTS
PET
Definition at line 17 of file attachment.hpp.
{
        UNAVAILABLE = 0 ,
        STROLLER = 1,
        BICYLE_TRAILER = 2,
        CART = 3,
        WHEEL_CHAIR = 4,
        OTHER_WALK_ASSIST_ATTACHMENTS = 5,
        PET = 6
    };
equipment_type
enum class streets_utils::messages::sdsm::equipment_type strong
Enumerator
UNKNOWN
RSU
OBU
VRU
Definition at line 19 of file equipment_type.hpp.
{
        UNKNOWN = 0,
        RSU = 1,
        OBU= 2,
        VRU= 3
    };
heading_confidence
enum class streets_utils::messages::sdsm::heading_confidence strong
Enumerator
UNAVAILABLE
PREC_10_deg
PREC_05_deg
PREC_01_deg
PREC_0_1_deg
PREC_0_05_deg
PREC_0_01_deg
PREC_0_0125_deg
Definition at line 17 of file heading_confidence.hpp.
{
        UNAVAILABLE = 0,
        PREC_10_deg = 1,        // 10 degrees
        PREC_05_deg = 2,        // 5 degrees
        PREC_01_deg = 3,        // 1 degrees
        PREC_0_1_deg = 4,       // 0.1 degrees
        PREC_0_05_deg = 5,      // 0.05 degrees
        PREC_0_01_deg = 6,      // 0.01 degrees
        PREC_0_0125_deg = 7     // 0.0125 degrees
    };
human_propelled_type
enum class streets_utils::messages::sdsm::human_propelled_type strong
Enumerator
UNAVAILABLE
OTHER_TYPES
ON_FOOT
SKATEBOARD
PUSH_OR_KICK_SCOOTER
WHEELCHAIR
Definition at line 18 of file human_propelled_type.hpp.
{
        UNAVAILABLE = 0,
        OTHER_TYPES = 1,
        ON_FOOT = 2,
        SKATEBOARD = 3,
        PUSH_OR_KICK_SCOOTER = 4,
        WHEELCHAIR = 5
    };
motorized_propelled_type
enum class streets_utils::messages::sdsm::motorized_propelled_type strong
Enumerator
UNAVAILABLE
OTHER_TYPES
WHEEL_CHAIR
BICYCLE
SCOOTER
SELF_BALANCING_DEVICE
Definition at line 17 of file motorized_propelled_type.hpp.
{
        UNAVAILABLE = 0,
        OTHER_TYPES = 1,
        WHEEL_CHAIR = 2,
        BICYCLE = 3,
        SCOOTER = 4,
        SELF_BALANCING_DEVICE = 5
    };
object_type
enum class streets_utils::messages::sdsm::object_type strong
Enumerator
UNKNOWN
VEHICLE
VRU
ANIMAL
Definition at line 18 of file object_type.hpp.
{
        UNKNOWN = 0,
        VEHICLE = 1,
        VRU= 2,
        ANIMAL= 3
    };
personal_device_user_type
enum class streets_utils::messages::sdsm::personal_device_user_type strong
Enumerator
UNAVAILABLE
PEDESTRIAN
PEDALCYCLIST
PUBLIC_SAFETY_WORKER
ANIMAL
Definition at line 18 of file personal_device_user_type.hpp.
{
        UNAVAILABLE= 0,
        PEDESTRIAN = 1,
        PEDALCYCLIST = 2,
        PUBLIC_SAFETY_WORKER = 3,
        ANIMAL = 4
    };
position_confidence
enum class streets_utils::messages::sdsm::position_confidence strong
Enumerator
UNAVAILABLE
A_500M
A_200M
A_100M
A_50M
A_20M
A_10M
A_5M
A_2M
A_1M
A_50CM
A_20CM
A_10CM
A_5CM
A_2CM
A_1CM
Definition at line 17 of file position_confidence.hpp.
{
        UNAVAILABLE = 0,
        A_500M = 1,
        A_200M = 2,
        A_100M = 3,
        A_50M = 4,
        A_20M = 5,
        A_10M = 6,
        A_5M = 7,
        A_2M = 8,
        A_1M = 9,
        A_50CM = 10,
        A_20CM = 11,
        A_10CM = 12,
        A_5CM = 13,
        A_2CM = 14,
        A_1CM = 15
    };
size_value_confidence
enum class streets_utils::messages::sdsm::size_value_confidence strong
Enumerator
UNAVAILABLE
SIZE_100
SIZE_50
SIZE_20
SIZE_10
SIZE_5
SIZE_2
SIZE_1
SIZE_0_5
SIZE_0_2
SIZE_0_1
SIZE_0_05
SIZE_0_02
SIZE_0_01
Definition at line 17 of file size_value_confidence.hpp.
{
        UNAVAILABLE = 0,    // Not available
        SIZE_100 = 1,       // 100 meters
        SIZE_50 = 2,        // 50 meters
        SIZE_20 = 3,        // 20 meters
        SIZE_10 = 4,        // 10 meters
        SIZE_5 = 5,         // 5 meters
        SIZE_2 = 6,         // 2 meters
        SIZE_1 = 7,         // 1 meter
        SIZE_0_5 = 8,       // 50 centimeters
        SIZE_0_2 = 9,       // 20 centimeters
        SIZE_0_1 = 10,      // 10 centimeters
        SIZE_0_05 = 11,     // 5 centimeters
        SIZE_0_02 = 12,     // 2 centimeters
        SIZE_0_01 = 13      // 1 centimeters
    };
speed_confidence
enum class streets_utils::messages::sdsm::speed_confidence strong
Enumerator
UNAVAILABLE
PREC_100ms
PREC_10ms
PREC_5ms
PREC_1ms
PREC_0_1ms
PREC_0_05ms
PREC_0_01ms
Definition at line 17 of file speed_confidence.hpp.
{
        UNAVAILABLE = 0,    // Not available
        PREC_100ms = 1,     // 100 m/s
        PREC_10ms = 2,      // 10 m/s
        PREC_5ms = 3,       // 5 m/s
        PREC_1ms = 4,       // 1 m/s
        PREC_0_1ms = 5,     // 0.1 m/s
        PREC_0_05ms = 6,    // 0.05 m/s
        PREC_0_01ms = 7     // 0.01 m/s
    };
time_confidence
enum class streets_utils::messages::sdsm::time_confidence strong
Enumerator
UNAVAILABLE
TIME_100_000
TIME_050_000
TIME_020_000
TIME_010_000
TIME_002_000
TIME_001_000
TIME_000_500
TIME_000_200
TIME_000_100
TIME_000_050
TIME_000_020
TIME_000_010
TIME_000_005
TIME_000_002
TIME_000_001
TIME_000_000_5
TIME_000_000_2
TIME_000_000_1
TIME_000_000_05
TIME_000_000_02
TIME_000_000_01
TIME_000_000_005
TIME_000_000_002
TIME_000_000_001
TIME_000_000_000_5
TIME_000_000_000_2
TIME_000_000_000_1
TIME_000_000_000_05
TIME_000_000_000_02
TIME_000_000_000_01
TIME_000_000_000_005
TIME_000_000_000_002
TIME_000_000_000_001
TIME_000_000_000_000_5
TIME_000_000_000_000_2
TIME_000_000_000_000_1
TIME_000_000_000_000_05
TIME_000_000_000_000_02
TIME_000_000_000_000_01
Definition at line 17 of file time_confidence.hpp.
{
        UNAVAILABLE = 0,            // unvailable
        TIME_100_000 = 1,           // Better than 100 seconds
        TIME_050_000 = 2,           // Better than 50 seconds
        TIME_020_000 = 3,           // Better than 20 seconds
        TIME_010_000 = 4,           // Better than 10 seconds
        TIME_002_000 = 5,           // Better than 2 seconds
        TIME_001_000 = 6,           // Better than 1 seconds
        TIME_000_500 = 7,           // Better than 0.5 seconds
        TIME_000_200 = 8,           // Better than 0.2 seconds
        TIME_000_100 = 9,           // Better than 0.1 seconds
        TIME_000_050 = 10,          // Better than 0.05 seconds
        TIME_000_020 = 11,          // Better than 0.02 seconds
        TIME_000_010 = 12,          // Better than 0.01 seconds
        TIME_000_005 = 13,          // Better than 0.005 seconds
        TIME_000_002 = 14,          // Better than 0.002 seconds
        TIME_000_001 = 15,          // Better than 0.001 seconds
        TIME_000_000_5 = 16,        // Better than 0.0005 seconds
        TIME_000_000_2 = 17,        // Better than 0.0002 seconds
        TIME_000_000_1 = 18,        // Better than 0.0001 seconds
        TIME_000_000_05 = 19,       // Better than 0.00005 seconds
        TIME_000_000_02 = 20,       // Better than 0.00002 seconds
        TIME_000_000_01 = 21,       // Better than 0.00001 seconds
        TIME_000_000_005 = 22,      // Better than 0.000005 seconds
        TIME_000_000_002 = 23,      // Better than 0.000002 seconds
        TIME_000_000_001 = 24,      // Better than 0.000001 seconds
        TIME_000_000_000_5 = 25,    // Better than 0.0000005 seconds
        TIME_000_000_000_2 = 26,    // Better than 0.0000002 seconds
        TIME_000_000_000_1 = 27,    // Better than 0.0000001 seconds
        TIME_000_000_000_05 = 28,   // Better than 0.00000005 seconds
        TIME_000_000_000_02 = 29,   // Better than 0.00000002 seconds
        TIME_000_000_000_01 = 30,   // Better than 0.00000001 seconds
        TIME_000_000_000_005 = 31,  // Better than 0.000000005 seconds
        TIME_000_000_000_002 = 32,  // Better than 0.000000002 seconds
        TIME_000_000_000_001 = 33,  // Better than 0.000000001 seconds (Better than  one nano second)
        TIME_000_000_000_000_5 = 34,// Better than 0.0000000005 seconds
        TIME_000_000_000_000_2 = 35,// Better than 0.0000000002 seconds
        TIME_000_000_000_000_1 = 36,// Better than 0.0000000001 seconds
        TIME_000_000_000_000_05 = 37, // Better than 0.00000000005 seconds
        TIME_000_000_000_000_02 = 38, // Better than 0.00000000002 seconds
        TIME_000_000_000_000_01 = 39  // Better than 0.00000000001 Seconds
    };
Function Documentation
acceleration_confidence_from_int()
acceleration_confidence streets_utils::messages::sdsm::acceleration_confidence_from_int (const unsigned int i) inline
Definition at line 28 of file acceleration_confidence.hpp.
{
        switch (i)
        {
        case 0:
            return acceleration_confidence::UNAVAILABLE;
        case 1:
            return acceleration_confidence::ACCL_100;
        case 2:
            return acceleration_confidence::ACCL_10;
        case 3:
            return acceleration_confidence::ACCL_5;
        case 4:
            return acceleration_confidence::ACCL_1;
        case 5:
            return acceleration_confidence::ACCL_0_1;
        case 6:
            return acceleration_confidence::ACCL_0_05;
        case 7:
            return acceleration_confidence::ACCL_0_01;
        default:
            throw std::invalid_argument("Incompatible acceleration confidence value. Valid values : [0,7]");
        }
    };
References ACCL_0_01, ACCL_0_05, ACCL_0_1, ACCL_1, ACCL_10, ACCL_100, ACCL_5, simulate_bsm::i, and UNAVAILABLE.
Referenced by parse_detected_object_data_common().
angular_velocity_confidence_from_int()
angular_velocity_confidence streets_utils::messages::sdsm::angular_velocity_confidence_from_int (const unsigned int i) inline
Definition at line 28 of file angular_velocity_confidence.hpp.
{
        switch (i)
        {
        case 0:
            return angular_velocity_confidence::UNAVAILABLE;
        case 1:
            return angular_velocity_confidence::DEGSEC_100;
        case 2:
            return angular_velocity_confidence::DEGSEC_10;
        case 3:
            return angular_velocity_confidence::DEGSEC_05;
        case 4:
            return angular_velocity_confidence::DEGSEC_01;
        case 5:
            return angular_velocity_confidence::DEGSEC_0_1;
        case 6:
            return angular_velocity_confidence::DEGSEC_0_05;
        case 7:
            return angular_velocity_confidence::DEGSEC_0_01;
        default:
            throw std::invalid_argument("Incompatible angular velocity confidence value. Valid values : [0,7]");
        }
    };
References DEGSEC_01, DEGSEC_05, DEGSEC_0_01, DEGSEC_0_05, DEGSEC_0_1, DEGSEC_10, DEGSEC_100, simulate_bsm::i, and UNAVAILABLE.
Referenced by parse_detected_object_data_common(), and parse_vehicle_angular_velocity_confidence_set().
animal_propelled_type_from_int()
animal_propelled_type streets_utils::messages::sdsm::animal_propelled_type_from_int (const unsigned int i) inline
Definition at line 25 of file animal_propelled_type.hpp.
{
        switch (i)
        {
        case 0:
            return animal_propelled_type::UNAVAILABLE;
        case 1:
            return animal_propelled_type::OTHER_TYPES;
        case 2:
            return animal_propelled_type::ANIMAL_MOUNTED;
        case 3:
            return animal_propelled_type::ANIMAL_DRAWN_CARRIAGE;
        default:
            throw std::invalid_argument("Incompatible animal propelled type value. Valid values : [0,3]");
        }
    };
References ANIMAL_DRAWN_CARRIAGE, ANIMAL_MOUNTED, simulate_bsm::i, OTHER_TYPES, and UNAVAILABLE.
Referenced by parse_propelled_information().
attachment_from_int()
attachment streets_utils::messages::sdsm::attachment_from_int (const int i) inline
Definition at line 27 of file attachment.hpp.
{
        switch (i)
        {
        case 0:
            return attachment::UNAVAILABLE;
        case 1:
            return attachment::STROLLER;
        case 2:
            return attachment::BICYLE_TRAILER;
        case 3:
            return attachment::CART;
        case 4:
            return attachment::WHEEL_CHAIR;
        case 5:
            return attachment::OTHER_WALK_ASSIST_ATTACHMENTS;
        case 6:
            return attachment::PET;
        default:
            throw std::invalid_argument("Incompatible attachment value. Valid values : [0,6]");
        }
    }
References BICYLE_TRAILER, CART, simulate_bsm::i, OTHER_WALK_ASSIST_ATTACHMENTS, PET, STROLLER, UNAVAILABLE, and WHEEL_CHAIR.
Referenced by parse_detected_vru_data().
create_accelaration_set_4_way()
rapidjson::Value streets_utils::messages::sdsm::create_accelaration_set_4_way (const acceleration_set_4_way & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 154 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value accelaration_set_4_way_json(rapidjson::kObjectType);
        accelaration_set_4_way_json.AddMember("lat", val._lateral_accel, allocator);
        accelaration_set_4_way_json.AddMember("long", val._longitudinal_accel, allocator);
        accelaration_set_4_way_json.AddMember("vert", val._vertical_accel, allocator);
        accelaration_set_4_way_json.AddMember("yaw", val._yaw_rate, allocator);
        return accelaration_set_4_way_json;
    }
References streets_utils::messages::sdsm::acceleration_set_4_way::_lateral_accel, streets_utils::messages::sdsm::acceleration_set_4_way::_longitudinal_accel, streets_utils::messages::sdsm::acceleration_set_4_way::_vertical_accel, and streets_utils::messages::sdsm::acceleration_set_4_way::_yaw_rate.
Referenced by create_detected_object_data_common().
create_angular_velocity()
rapidjson::Value streets_utils::messages::sdsm::create_angular_velocity (const angular_velocity_set & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 319 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value data(rapidjson::kObjectType);
        data.AddMember("pitch_rate", static_cast<unsigned int>(val._pitch_rate), allocator);
        data.AddMember("roll_rate", static_cast<unsigned int>(val._roll_rate), allocator);
        return data;
    }
References streets_utils::messages::sdsm::angular_velocity_set::_pitch_rate, streets_utils::messages::sdsm::angular_velocity_set::_roll_rate, and simulate_bsm::data.
Referenced by create_detected_vehicle_data().
create_angular_velocity_confidence()
rapidjson::Value streets_utils::messages::sdsm::create_angular_velocity_confidence (const angular_velocity_confidence_set & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 326 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value data(rapidjson::kObjectType);
        if ( val._pitch_rate_confidence.has_value() ) {
            data.AddMember("pitch_rate_confidence", static_cast<unsigned int>(val._pitch_rate_confidence.value()), allocator);
        }
        if ( val._roll_rate_confidence.has_value() ) {
            data.AddMember("roll_rate_confidence", static_cast<unsigned int>(val._roll_rate_confidence.value()), allocator);
        }
        return data;
    }
References streets_utils::messages::sdsm::angular_velocity_confidence_set::_pitch_rate_confidence, streets_utils::messages::sdsm::angular_velocity_confidence_set::_roll_rate_confidence, and simulate_bsm::data.
Referenced by create_detected_vehicle_data().
create_detected_object_data()
rapidjson::Value streets_utils::messages::sdsm::create_detected_object_data (const detected_object_data & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 82 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value detected_object_data_json(rapidjson::kObjectType);
        rapidjson::Value object_data_json(rapidjson::kObjectType);
        // Create Common Data
        object_data_json.AddMember("detected_object_common_data",create_detected_object_data_common(val._detected_object_common_data,allocator), allocator );
        // Create Optional Data
        if ( val._detected_object_optional_data.has_value() )
            object_data_json.AddMember(
                    "detected_object_optional_data",
                    create_detected_object_data_optional(val._detected_object_optional_data.value(), allocator),
                    allocator);
        detected_object_data_json.AddMember("detected_object_data", object_data_json , allocator);
        return detected_object_data_json;
    }
References streets_utils::messages::sdsm::detected_object_data::_detected_object_common_data, streets_utils::messages::sdsm::detected_object_data::_detected_object_optional_data, create_detected_object_data_common(), and create_detected_object_data_optional().
Referenced by create_detected_object_list().
create_detected_object_data_common()
rapidjson::Value streets_utils::messages::sdsm::create_detected_object_data_common (const detected_object_data_common & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 98 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value detected_object_data_common_json(rapidjson::kObjectType);
        detected_object_data_common_json.AddMember("obj_type", static_cast<unsigned int >(val._object_type), allocator);
        detected_object_data_common_json.AddMember("object_id", val._object_id, allocator);
        detected_object_data_common_json.AddMember("obj_type_cfd", val._classification_confidence, allocator);
        detected_object_data_common_json.AddMember("measurement_time", val._time_measurement_offset, allocator);
        detected_object_data_common_json.AddMember("time_confidence", static_cast<unsigned int >(val._time_confidence), allocator);
        // Create Position
        detected_object_data_common_json.AddMember(
                    "pos",
                    create_position_3d( val._position_offset, allocator),
                    allocator);
        // Create Position Confidence
        detected_object_data_common_json.AddMember("pos_confidence", create_position_confidence_set(val._pos_confidence, allocator), allocator );
        detected_object_data_common_json.AddMember("speed", val._speed, allocator);
        detected_object_data_common_json.AddMember("speed_confidence", static_cast<unsigned int >(val._speed_confidence), allocator);
        if ( val._speed_z.has_value())
            detected_object_data_common_json.AddMember("speed_z", val._speed_z.value(), allocator);
        if ( val._speed_z_confidence.has_value())
            detected_object_data_common_json.AddMember(
                    "speed_confidence_z",
                    static_cast<unsigned int >(val._speed_z_confidence.value()),
                    allocator);
        detected_object_data_common_json.AddMember("heading", val._heading, allocator);
        detected_object_data_common_json.AddMember("heading_conf", static_cast<unsigned int >(val._heading_confidence), allocator);
        if (val._lateral_acceleration_confidence.has_value() ) {
            detected_object_data_common_json.AddMember(
                    "acc_cfd_x",
                    static_cast<unsigned int >(val._lateral_acceleration_confidence.value()),
                    allocator);
        if (val._longitudinal_acceleration_confidence.has_value() )
            detected_object_data_common_json.AddMember(
                    "acc_cfd_y",
                    static_cast<unsigned int >(val._longitudinal_acceleration_confidence.value()),
                    allocator);
        if (val._vertical_accelaration_confidence.has_value())
            detected_object_data_common_json.AddMember(
                    "acc_cfd_z",
                    static_cast<unsigned int >(val._vertical_accelaration_confidence.value()),
                    allocator);
        if (val._yaw_rate_confidence.has_value())
            detected_object_data_common_json.AddMember(
                    "acc_cfd_yaw",
                    static_cast<unsigned int >(val._yaw_rate_confidence.value()),
                    allocator);
        }
        if (val._acceleration_4_way.has_value()) {
            // Create accel_4_way
            detected_object_data_common_json.AddMember(
                    "accel_4_way",
                    create_accelaration_set_4_way(val._acceleration_4_way.value(), allocator),
                    allocator);
        }
        return detected_object_data_common_json;
    }
References streets_utils::messages::sdsm::detected_object_data_common::_acceleration_4_way, streets_utils::messages::sdsm::detected_object_data_common::_classification_confidence, streets_utils::messages::sdsm::detected_object_data_common::_heading, streets_utils::messages::sdsm::detected_object_data_common::_heading_confidence, streets_utils::messages::sdsm::detected_object_data_common::_lateral_acceleration_confidence, streets_utils::messages::sdsm::detected_object_data_common::_longitudinal_acceleration_confidence, streets_utils::messages::sdsm::detected_object_data_common::_object_id, streets_utils::messages::sdsm::detected_object_data_common::_object_type, streets_utils::messages::sdsm::detected_object_data_common::_pos_confidence, streets_utils::messages::sdsm::detected_object_data_common::_position_offset, streets_utils::messages::sdsm::detected_object_data_common::_speed, streets_utils::messages::sdsm::detected_object_data_common::_speed_confidence, streets_utils::messages::sdsm::detected_object_data_common::_speed_z, streets_utils::messages::sdsm::detected_object_data_common::_speed_z_confidence, streets_utils::messages::sdsm::detected_object_data_common::_time_confidence, streets_utils::messages::sdsm::detected_object_data_common::_time_measurement_offset, streets_utils::messages::sdsm::detected_object_data_common::_vertical_accelaration_confidence, streets_utils::messages::sdsm::detected_object_data_common::_yaw_rate_confidence, create_accelaration_set_4_way(), create_position_3d(), and create_position_confidence_set().
Referenced by create_detected_object_data().
create_detected_object_data_optional()
rapidjson::Value streets_utils::messages::sdsm::create_detected_object_data_optional (const std::variant< detected_obstacle_data, detected_vehicle_data, detected_vru_data > & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 179 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value detected_object_data_optional_json(rapidjson::kObjectType);
        if (std::holds_alternative<detected_obstacle_data>(val)) {
            detected_object_data_optional_json.AddMember("detected_obstacle_data",create_detected_obstacle_data(std::get<detected_obstacle_data>(val),allocator), allocator);
            return detected_object_data_optional_json;
        }
        else if (std::holds_alternative<detected_vehicle_data>(val)) {
            detected_object_data_optional_json.AddMember("detected_vehicle_data",create_detected_vehicle_data(std::get<detected_vehicle_data>(val),allocator), allocator);
            return detected_object_data_optional_json;
        }
        else if (std::holds_alternative<detected_vru_data>(val)) {
            detected_object_data_optional_json.AddMember("detected_vru_data",create_detected_vru_data(std::get<detected_vru_data>(val),allocator), allocator);
            return detected_object_data_optional_json;
        }
        else {
            throw json_utils::json_parse_exception("If present, detected optional data must include one of the following objects : detected obstacle data, detected vehicle data, detected vru data");
        }
    }
References create_detected_obstacle_data(), create_detected_vehicle_data(), and create_detected_vru_data().
Referenced by create_detected_object_data().
create_detected_object_list()
rapidjson::Value streets_utils::messages::sdsm::create_detected_object_list (const std::vector< detected_object_data > & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 72 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value detected_object_list_json(rapidjson::kArrayType);
        for (const auto &detected_obect : val) {
            // Create and push detected object data
            detected_object_list_json.PushBack(create_detected_object_data(detected_obect, allocator), allocator);
        }
        return detected_object_list_json;
    }
References create_detected_object_data().
Referenced by to_json().
create_detected_obstacle_data()
rapidjson::Value streets_utils::messages::sdsm::create_detected_obstacle_data (const detected_obstacle_data & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 199 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value data(rapidjson::kObjectType);
        data.AddMember("obst_size", create_obstacle_size(val._size, allocator), allocator);
        data.AddMember("obst_size_confidence", create_obstacle_size_confidence(val._size_confidence, allocator), allocator);
        return data;
    }
References streets_utils::messages::sdsm::detected_obstacle_data::_size, streets_utils::messages::sdsm::detected_obstacle_data::_size_confidence, create_obstacle_size(), create_obstacle_size_confidence(), and simulate_bsm::data.
Referenced by create_detected_object_data_optional().
create_detected_vehicle_data()
rapidjson::Value streets_utils::messages::sdsm::create_detected_vehicle_data (const detected_vehicle_data & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 246 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value data(rapidjson::kObjectType);
        if ( val.exterior_lights.has_value() ) {
            data.AddMember("lights", val.exterior_lights.value(), allocator);
        }
        if ( val._veh_attitude.has_value() ) {
            data.AddMember("veh_attitude", create_vehicle_attitude(val._veh_attitude.value(), allocator), allocator);
        }
        if ( val._attitude_confidence.has_value() ) {
            data.AddMember("veh_attitude_confidence", create_vehicle_attitude_confidence(val._attitude_confidence.value(), allocator), allocator);
        }
        if ( val._angular_velocity.has_value() ) {
            data.AddMember("veh_ang_vel", create_angular_velocity(val._angular_velocity.value(), allocator), allocator);
        }
        if ( val._angular_velocity_confidence.has_value() ){
            data.AddMember("veh_ang_vel_confidence", create_angular_velocity_confidence(val._angular_velocity_confidence.value(),allocator), allocator);
        }
        if ( val._size.has_value() ) {
            data.AddMember("size", create_vehicle_size(val._size.value(), allocator), allocator);
        }
        if ( val._size_confidence.has_value() ) {
            data.AddMember("vehicle_size_confidence", create_vehicle_size_confidence(val._size_confidence.value(), allocator), allocator);
        }
        if (val._vehicle_height.has_value() ) {
            data.AddMember("height", val._vehicle_height.value(), allocator);
        }
        if (val._vehicle_class.has_value() ) {
            data.AddMember("vehicle_class", val._vehicle_class.value(), allocator);
        }
        if ( val._classification_confidence.has_value() ) {
            data.AddMember("vehicle_class_conf", val._classification_confidence.value(), allocator);
        }
        return data;
    }
References streets_utils::messages::sdsm::detected_vehicle_data::_angular_velocity, streets_utils::messages::sdsm::detected_vehicle_data::_angular_velocity_confidence, streets_utils::messages::sdsm::detected_vehicle_data::_attitude_confidence, streets_utils::messages::sdsm::detected_vehicle_data::_classification_confidence, streets_utils::messages::sdsm::detected_vehicle_data::_size, streets_utils::messages::sdsm::detected_vehicle_data::_size_confidence, streets_utils::messages::sdsm::detected_vehicle_data::_veh_attitude, streets_utils::messages::sdsm::detected_vehicle_data::_vehicle_class, streets_utils::messages::sdsm::detected_vehicle_data::_vehicle_height, create_angular_velocity(), create_angular_velocity_confidence(), create_vehicle_attitude(), create_vehicle_attitude_confidence(), create_vehicle_size(), create_vehicle_size_confidence(), simulate_bsm::data, and streets_utils::messages::sdsm::detected_vehicle_data::exterior_lights.
Referenced by create_detected_object_data_optional().
create_detected_vru_data()
rapidjson::Value streets_utils::messages::sdsm::create_detected_vru_data (const detected_vru_data & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 229 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value data(rapidjson::kObjectType);
        if (val._personal_device_user_type.has_value() ) {
            data.AddMember("basic_type", static_cast<unsigned int>(val._personal_device_user_type.value()), allocator);
        }
        if (val._attachment.has_value() ) {
            data.AddMember("attachment", static_cast<unsigned int>(val._attachment.value()), allocator);
        }
        if (val._propulsion.has_value() ) {
            data.AddMember("propulsion", create_propelled_information(val._propulsion.value(), allocator), allocator);
        }
        if (val._attachment_radius.has_value() ) {
            data.AddMember("radius", val._attachment_radius.value(), allocator);
        }
        return data;
    }
References streets_utils::messages::sdsm::detected_vru_data::_attachment, streets_utils::messages::sdsm::detected_vru_data::_attachment_radius, streets_utils::messages::sdsm::detected_vru_data::_personal_device_user_type, streets_utils::messages::sdsm::detected_vru_data::_propulsion, create_propelled_information(), and simulate_bsm::data.
Referenced by create_detected_object_data_optional().
create_obstacle_size()
rapidjson::Value streets_utils::messages::sdsm::create_obstacle_size (const obstacle_size & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 206 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value data(rapidjson::kObjectType);
        data.AddMember("width", val._width, allocator);
        data.AddMember("length", val._length, allocator);
        // Optional Height
        if (val._height.has_value() ) {
            data.AddMember("height", val._height.value(), allocator);
        }
        return data;
    }
References streets_utils::messages::sdsm::obstacle_size::_height, streets_utils::messages::sdsm::obstacle_size::_length, streets_utils::messages::sdsm::obstacle_size::_width, and simulate_bsm::data.
Referenced by create_detected_obstacle_data().
create_obstacle_size_confidence()
rapidjson::Value streets_utils::messages::sdsm::create_obstacle_size_confidence (const obstacle_size_confidence & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 218 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value data(rapidjson::kObjectType);
        data.AddMember("width_confidence", static_cast<unsigned int>(val._width_confidence), allocator);
        data.AddMember("length_confidence", static_cast<unsigned int>(val._length_confidence), allocator);
        // Optional height
        if ( val._height_confidence.has_value()) {
            data.AddMember("height_confidence", static_cast<unsigned int>(val._height_confidence.value()), allocator);
        }
        return data;
    }
References streets_utils::messages::sdsm::obstacle_size_confidence::_height_confidence, streets_utils::messages::sdsm::obstacle_size_confidence::_length_confidence, streets_utils::messages::sdsm::obstacle_size_confidence::_width_confidence, and simulate_bsm::data.
Referenced by create_detected_obstacle_data().
create_position_3d() [1/2]
rapidjson::Value streets_utils::messages::sdsm::create_position_3d (const position_3d & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 55 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value position_3d_json(rapidjson::kObjectType);
        position_3d_json.AddMember("long", val._longitude, allocator);
        position_3d_json.AddMember("lat", val._latitude, allocator);
        if ( val._elevation.has_value() ) {
            position_3d_json.AddMember("elevation", val._elevation.value(), allocator);
        }
        return position_3d_json;
    }
References streets_utils::messages::sdsm::position_3d::_elevation, streets_utils::messages::sdsm::position_3d::_latitude, and streets_utils::messages::sdsm::position_3d::_longitude.
Referenced by create_detected_object_data_common(), and to_json().
create_position_3d() [2/2]
rapidjson::Value streets_utils::messages::sdsm::create_position_3d (const position_offset & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 163 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value position_3d_json(rapidjson::kObjectType);
        position_3d_json.AddMember("offset_x", val._offset_x, allocator);
        position_3d_json.AddMember("offset_y", val._offset_y, allocator);
        if ( val._offset_z.has_value()) {
            position_3d_json.AddMember("offset_z", val._offset_z.value(), allocator);
        }
        return position_3d_json;
    }
References streets_utils::messages::sdsm::position_offset::_offset_x, streets_utils::messages::sdsm::position_offset::_offset_y, and streets_utils::messages::sdsm::position_offset::_offset_z.
create_position_confidence_set()
rapidjson::Value streets_utils::messages::sdsm::create_position_confidence_set (const position_confidence_set & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 173 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value position_confidence_json(rapidjson::kObjectType);
        position_confidence_json.AddMember("pos",static_cast<unsigned int >(val._position_confidence), allocator);
        position_confidence_json.AddMember("elevation", static_cast<unsigned int >(val._elevation_confidence), allocator);
        return position_confidence_json;
    }
References streets_utils::messages::sdsm::position_confidence_set::_elevation_confidence, and streets_utils::messages::sdsm::position_confidence_set::_position_confidence.
Referenced by create_detected_object_data_common().
create_positional_accuracy()
rapidjson::Value streets_utils::messages::sdsm::create_positional_accuracy (const positional_accuracy & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 65 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value positional_accuracy_json(rapidjson::kObjectType);
        positional_accuracy_json.AddMember("semi_major", val._semi_major_axis_accuracy, allocator);
        positional_accuracy_json.AddMember("semi_minor", val._semi_minor_axis_accuracy, allocator);
        positional_accuracy_json.AddMember("orientation", val._semi_major_axis_orientation, allocator);
        return positional_accuracy_json;
    }
References streets_utils::messages::sdsm::positional_accuracy::_semi_major_axis_accuracy, streets_utils::messages::sdsm::positional_accuracy::_semi_major_axis_orientation, and streets_utils::messages::sdsm::positional_accuracy::_semi_minor_axis_accuracy.
Referenced by to_json().
create_propelled_information()
rapidjson::Value streets_utils::messages::sdsm::create_propelled_information (const std::variant< human_propelled_type, motorized_propelled_type, animal_propelled_type > & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 283 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value data(rapidjson::kObjectType);
        if ( std::holds_alternative<human_propelled_type>(val) ) {
            data.AddMember("human", static_cast<unsigned int>( std::get<human_propelled_type>(val)), allocator);
            return data;
        }
        else if ( std::holds_alternative<animal_propelled_type>(val) ) {
            data.AddMember("animal", static_cast<unsigned int>( std::get<animal_propelled_type>(val)), allocator);
            return data;
        }
        else if ( std::holds_alternative<motorized_propelled_type>(val) ) {
            data.AddMember("motor", static_cast<unsigned int>( std::get<motorized_propelled_type>(val)), allocator);
            return data;
        }
        else {
            throw json_utils::json_parse_exception("If present, propelled infromation must include one of the following objects : animal propelled type, motorized propelled type, human propelled type");
        }
    }
References simulate_bsm::data.
Referenced by create_detected_vru_data().
create_timestamp()
rapidjson::Value streets_utils::messages::sdsm::create_timestamp (const time_stamp & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 43 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value time_stamp_json(rapidjson::kObjectType);
        time_stamp_json.AddMember("second", val.second, allocator);
        time_stamp_json.AddMember("minute", val.minute, allocator);
        time_stamp_json.AddMember("hour", val.hour, allocator);
        time_stamp_json.AddMember("day", val.day, allocator);
        time_stamp_json.AddMember("month", val.month, allocator);
        time_stamp_json.AddMember("year", val.year, allocator);
        time_stamp_json.AddMember("offset", val.offset, allocator);
        return time_stamp_json;
    }
References streets_utils::messages::sdsm::time_stamp::day, streets_utils::messages::sdsm::time_stamp::hour, streets_utils::messages::sdsm::time_stamp::minute, streets_utils::messages::sdsm::time_stamp::month, streets_utils::messages::sdsm::time_stamp::offset, streets_utils::messages::sdsm::time_stamp::second, and streets_utils::messages::sdsm::time_stamp::year.
Referenced by to_json().
create_vehicle_attitude()
rapidjson::Value streets_utils::messages::sdsm::create_vehicle_attitude (const attitude & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 303 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value data(rapidjson::kObjectType);
        data.AddMember("pitch", val._pitch, allocator);
        data.AddMember("roll", val._roll, allocator);
        data.AddMember("yaw", val._yaw, allocator);
        return data;
    }
References streets_utils::messages::sdsm::attitude::_pitch, streets_utils::messages::sdsm::attitude::_roll, streets_utils::messages::sdsm::attitude::_yaw, and simulate_bsm::data.
Referenced by create_detected_vehicle_data().
create_vehicle_attitude_confidence()
rapidjson::Value streets_utils::messages::sdsm::create_vehicle_attitude_confidence (const attitude_confidence & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 311 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value data(rapidjson::kObjectType);
        data.AddMember("pitch_confidence", static_cast<unsigned int>(val._pitch_confidence), allocator);
        data.AddMember("roll_confidence", static_cast<unsigned int>(val._roll_confidence), allocator);
        data.AddMember("yaw_confidence", static_cast<unsigned int>(val._yaw_confidence), allocator);
        return data;
    }
References streets_utils::messages::sdsm::attitude_confidence::_pitch_confidence, streets_utils::messages::sdsm::attitude_confidence::_roll_confidence, streets_utils::messages::sdsm::attitude_confidence::_yaw_confidence, and simulate_bsm::data.
Referenced by create_detected_vehicle_data().
create_vehicle_size()
rapidjson::Value streets_utils::messages::sdsm::create_vehicle_size (const vehicle_size & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 337 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value data(rapidjson::kObjectType);
        data.AddMember("width", val._width, allocator);
        data.AddMember("length", val._length, allocator);
        return data;
    }
References streets_utils::messages::sdsm::vehicle_size::_length, streets_utils::messages::sdsm::vehicle_size::_width, and simulate_bsm::data.
Referenced by create_detected_vehicle_data().
create_vehicle_size_confidence()
rapidjson::Value streets_utils::messages::sdsm::create_vehicle_size_confidence (const vehicle_size_confidence & val, rapidjson::Document::AllocatorType & allocator)
Definition at line 344 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Value data(rapidjson::kObjectType);
        data.AddMember("vehicle_width_confidence", static_cast<unsigned int>(val._width_confidence), allocator);
        data.AddMember("vehicle_length_confidence", static_cast<unsigned int>(val._length_confidence), allocator);
        if ( val._height_confidence.has_value() ) {
            data.AddMember("vehicle_height_confidence", static_cast<unsigned int>(val._height_confidence.value()), allocator);
        }
        return data;
    }
References streets_utils::messages::sdsm::vehicle_size_confidence::_height_confidence, streets_utils::messages::sdsm::vehicle_size_confidence::_length_confidence, streets_utils::messages::sdsm::vehicle_size_confidence::_width_confidence, and simulate_bsm::data.
Referenced by create_detected_vehicle_data().
equipment_type_from_int()
equipment_type streets_utils::messages::sdsm::equipment_type_from_int (const unsigned int i) inline
Function to convert integers to equiment type. Default to UNKNOWN.
Parameters
i integer value of enum.
Returns
corresponding equipement type.
Definition at line 30 of file equipment_type.hpp.
{
        switch (i)
        {
        case 0:
            return equipment_type::UNKNOWN;
        case 1:
            return equipment_type::RSU;
        case 2:
            return equipment_type::OBU;
        case 3:
            return equipment_type::VRU;
        default:
            throw std::invalid_argument("Incompatible equipment type value. Valid values : [0,3]");
        }
    };
References simulate_bsm::i, OBU, RSU, UNKNOWN, and VRU.
Referenced by from_json().
from_json()
sensor_data_sharing_msg streets_utils::messages::sdsm::from_json (const std::string & val)
Definition at line 19 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        rapidjson::Document document = streets_utils::json_utils::parse_json(json);
        sensor_data_sharing_msg msg;
        msg._msg_count = parse_uint_member("msg_cnt", document, true).value();
        msg._source_id = parse_string_member("source_id", document, true).value();
        msg._equipment_type = equipment_type_from_int(parse_uint_member("equipment_type", document, true).value());
        msg._time_stamp = parse_time_stamp(parse_object_member("sdsm_time_stamp", document, true).value());
        msg._ref_positon = parse_position_3d(parse_object_member("ref_pos", document, true).value());
        msg._ref_position_confidence = parse_positional_accuracy(parse_object_member("ref_pos_xy_conf", document, true).value());
        msg._ref_position_elevation_confidence = parse_elevation_confidence( document);
        msg._objects = parse_detected_object_list(document);
        return msg;
    }
References streets_utils::messages::sdsm::sensor_data_sharing_msg::_equipment_type, streets_utils::messages::sdsm::sensor_data_sharing_msg::_msg_count, streets_utils::messages::sdsm::sensor_data_sharing_msg::_objects, streets_utils::messages::sdsm::sensor_data_sharing_msg::_ref_position_confidence, streets_utils::messages::sdsm::sensor_data_sharing_msg::_ref_position_elevation_confidence, streets_utils::messages::sdsm::sensor_data_sharing_msg::_ref_positon, streets_utils::messages::sdsm::sensor_data_sharing_msg::_source_id, streets_utils::messages::sdsm::sensor_data_sharing_msg::_time_stamp, equipment_type_from_int(), parse_detected_object_list(), parse_elevation_confidence(), streets_utils::json_utils::parse_json(), streets_utils::json_utils::parse_object_member(), parse_position_3d(), parse_positional_accuracy(), streets_utils::json_utils::parse_string_member(), parse_time_stamp(), streets_utils::json_utils::parse_uint_member(), and simulate_bsm::value.
heading_confidence_from_int()
heading_confidence streets_utils::messages::sdsm::heading_confidence_from_int (const unsigned int i) inline
Definition at line 28 of file heading_confidence.hpp.
{
        switch (i)
        {
        case 0:
            return heading_confidence::UNAVAILABLE;
        case 1:
            return heading_confidence::PREC_10_deg;
        case 2:
            return heading_confidence::PREC_05_deg;
        case 3:
            return heading_confidence::PREC_01_deg;
        case 4:
            return heading_confidence::PREC_0_1_deg;
        case 5:
            return heading_confidence::PREC_0_05_deg;
        case 6:
            return heading_confidence::PREC_0_01_deg;
        case 7:
            return heading_confidence::PREC_0_0125_deg;
        default:
            throw std::invalid_argument("Incompatible heading confidence value. Valid values : [0,7]");
        }
    };
References simulate_bsm::i, PREC_01_deg, PREC_05_deg, PREC_0_0125_deg, PREC_0_01_deg, PREC_0_05_deg, PREC_0_1_deg, PREC_10_deg, and UNAVAILABLE.
Referenced by parse_detected_object_data_common(), and parse_vehicle_attitude_confidence().
human_propelled_type_from_int()
human_propelled_type streets_utils::messages::sdsm::human_propelled_type_from_int (const int i) inline
Definition at line 27 of file human_propelled_type.hpp.
{
        switch (i)
        {
        case 0:
            return human_propelled_type::UNAVAILABLE;
        case 1:
            return human_propelled_type::OTHER_TYPES;
        case 2:
            return human_propelled_type::ON_FOOT;
        case 3:
            return human_propelled_type::SKATEBOARD;
        case 4:
            return human_propelled_type::PUSH_OR_KICK_SCOOTER;
        case 5:
            return human_propelled_type::WHEELCHAIR;
        default:
            throw std::invalid_argument("Incompatible human propelled type value. Valid values : [0,5]");
        }
    };
References simulate_bsm::i, ON_FOOT, OTHER_TYPES, PUSH_OR_KICK_SCOOTER, SKATEBOARD, UNAVAILABLE, and WHEELCHAIR.
Referenced by parse_propelled_information().
motorized_propelled_type_from_int()
motorized_propelled_type streets_utils::messages::sdsm::motorized_propelled_type_from_int (const unsigned int i) inline
Definition at line 26 of file motorized_propelled_type.hpp.
{
        switch (i)
        {
        case 0:
            return motorized_propelled_type::UNAVAILABLE;
        case 1:
            return motorized_propelled_type::OTHER_TYPES;
        case 2:
            return motorized_propelled_type::WHEEL_CHAIR;
        case 3:
            return motorized_propelled_type::BICYCLE;
        case 4:
            return motorized_propelled_type::SCOOTER;
        case 5:
            return motorized_propelled_type::SELF_BALANCING_DEVICE;
        default:
            throw std::invalid_argument("Incompatible motorized propelled type value. Valid values : [0,5]");
        }
    };
References BICYCLE, simulate_bsm::i, OTHER_TYPES, SCOOTER, SELF_BALANCING_DEVICE, UNAVAILABLE, and WHEEL_CHAIR.
Referenced by parse_propelled_information().
object_type_from_int()
object_type streets_utils::messages::sdsm::object_type_from_int (const int i) inline
Definition at line 25 of file object_type.hpp.
{
        switch (i)
        {
        case 0:
            return object_type::UNKNOWN;
        case 1:
            return object_type::VEHICLE;
        case 2:
            return object_type::VRU;
        case 3:
            return object_type::ANIMAL;
        default:
            throw std::invalid_argument("Incompatible object type value. Valid values : [0,3]");
        }
    };
References ANIMAL, simulate_bsm::i, UNKNOWN, VEHICLE, and VRU.
Referenced by parse_detected_object_data_common().
parse_acceleration_4_way()
acceleration_set_4_way streets_utils::messages::sdsm::parse_acceleration_4_way (const rapidjson::Value & val)
Definition at line 156 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        acceleration_set_4_way data;
        data._lateral_accel = parse_int_member("lat", val, true).value();
        data._longitudinal_accel = parse_int_member("long", val, true).value();
        data._vertical_accel = parse_int_member("vert", val, true).value();
        data._yaw_rate = parse_int_member("yaw", val, true).value();
        return data;
    }
References simulate_bsm::data, and streets_utils::json_utils::parse_int_member().
Referenced by parse_detected_object_data_common().
parse_detected_object_data_common()
detected_object_data_common streets_utils::messages::sdsm::parse_detected_object_data_common (const rapidjson::Value & val)
Definition at line 88 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        detected_object_data_common _detected_object_common_data;
        _detected_object_common_data._object_type = object_type_from_int(parse_uint_member("obj_type", val, true).value());
        _detected_object_common_data._classification_confidence = parse_uint_member("obj_type_cfd",val,true).value();
        _detected_object_common_data._object_id = parse_uint_member("object_id", val, true).value();
        _detected_object_common_data._time_measurement_offset = parse_int_member("measurement_time", val, true).value();
        _detected_object_common_data._time_confidence = time_confidence_from_int(parse_uint_member("time_confidence", val, true).value());
        _detected_object_common_data._position_offset = parse_position_offset(parse_object_member("pos" ,val, true).value());
        _detected_object_common_data._pos_confidence = parse_position_confidence_set(parse_object_member("pos_confidence", val, true).value());
        _detected_object_common_data._speed = parse_uint_member("speed", val, true).value();
        _detected_object_common_data._speed_confidence = speed_confidence_from_int(parse_uint_member("speed_confidence", val, true).value());
        // Optional
        _detected_object_common_data._speed_z = parse_uint_member("speed_z", val, false);
        // Optional enumeration
        if ( val.HasMember("speed_z_confidence")) {
            _detected_object_common_data._speed_z_confidence = speed_confidence_from_int( parse_uint_member("speed_z_confidence", val, true).value());
        }
        _detected_object_common_data._heading = parse_uint_member("heading", val, true).value();
        _detected_object_common_data._heading_confidence = heading_confidence_from_int(parse_uint_member("heading_conf", val, true).value());
        if ( val.HasMember("accel_4_way") )  {
            _detected_object_common_data._acceleration_4_way = parse_acceleration_4_way(parse_object_member("accel_4_way", val, false ).value());
            if ( val.HasMember("acc_cfd_x")) {
                _detected_object_common_data._lateral_acceleration_confidence = acceleration_confidence_from_int(parse_uint_member("acc_cfd_x", val, true).value());
            }
            if ( val.HasMember("acc_cfd_y")) {
                _detected_object_common_data._longitudinal_acceleration_confidence = acceleration_confidence_from_int(parse_uint_member("acc_cfd_y", val, true).value());
            }
            if ( val.HasMember("acc_cfd_z")) {
                _detected_object_common_data._vertical_accelaration_confidence = acceleration_confidence_from_int(parse_uint_member("acc_cfd_z", val, true).value());
            }
            if ( val.HasMember("acc_cfd_yaw")) {
                _detected_object_common_data._yaw_rate_confidence = angular_velocity_confidence_from_int(parse_uint_member("acc_cfd_yaw", val, true).value());
            }
        }
        return _detected_object_common_data;
    }
References streets_utils::messages::sdsm::detected_object_data_common::_acceleration_4_way, streets_utils::messages::sdsm::detected_object_data_common::_classification_confidence, streets_utils::messages::sdsm::detected_object_data_common::_heading, streets_utils::messages::sdsm::detected_object_data_common::_heading_confidence, streets_utils::messages::sdsm::detected_object_data_common::_lateral_acceleration_confidence, streets_utils::messages::sdsm::detected_object_data_common::_longitudinal_acceleration_confidence, streets_utils::messages::sdsm::detected_object_data_common::_object_id, streets_utils::messages::sdsm::detected_object_data_common::_object_type, streets_utils::messages::sdsm::detected_object_data_common::_pos_confidence, streets_utils::messages::sdsm::detected_object_data_common::_position_offset, streets_utils::messages::sdsm::detected_object_data_common::_speed, streets_utils::messages::sdsm::detected_object_data_common::_speed_confidence, streets_utils::messages::sdsm::detected_object_data_common::_speed_z, streets_utils::messages::sdsm::detected_object_data_common::_speed_z_confidence, streets_utils::messages::sdsm::detected_object_data_common::_time_confidence, streets_utils::messages::sdsm::detected_object_data_common::_time_measurement_offset, streets_utils::messages::sdsm::detected_object_data_common::_vertical_accelaration_confidence, streets_utils::messages::sdsm::detected_object_data_common::_yaw_rate_confidence, acceleration_confidence_from_int(), angular_velocity_confidence_from_int(), heading_confidence_from_int(), object_type_from_int(), parse_acceleration_4_way(), streets_utils::json_utils::parse_int_member(), streets_utils::json_utils::parse_object_member(), parse_position_confidence_set(), parse_position_offset(), streets_utils::json_utils::parse_uint_member(), speed_confidence_from_int(), time_confidence_from_int(), and simulate_bsm::value.
Referenced by parse_detected_object_list().
parse_detected_object_data_optional()
std::optional< std::variant< detected_obstacle_data, detected_vehicle_data, detected_vru_data > > streets_utils::messages::sdsm::parse_detected_object_data_optional (const rapidjson::Value & val)
Definition at line 125 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        std::optional<std::variant<detected_obstacle_data, detected_vehicle_data, detected_vru_data>> detected_optional_data;
        if (val.HasMember("detected_vehicle_data")){
            detected_optional_data = parse_detected_vehicle_data(parse_object_member("detected_vehicle_data", val, true).value());
        }
        else if (val.HasMember("detected_vru_data")) {
            detected_optional_data = parse_detected_vru_data(parse_object_member("detected_vru_data", val, true).value());
        }
        else if (val.HasMember("detected_obstacle_data") ) {
            detected_optional_data = parse_detected_obstacle_data(parse_object_member("detected_obstacle_data", val, true).value());
        }
        return detected_optional_data;
    }
References parse_detected_obstacle_data(), parse_detected_vehicle_data(), parse_detected_vru_data(), streets_utils::json_utils::parse_object_member(), and simulate_bsm::value.
Referenced by parse_detected_object_list().
parse_detected_object_list()
std::vector< detected_object_data > streets_utils::messages::sdsm::parse_detected_object_list (const rapidjson::Value & val)
Definition at line 73 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        std::vector<detected_object_data> detected_object_list;
        auto json_detected_object_list = parse_array_member("objects",val, true).value();
        for (const auto &object: json_detected_object_list){
            detected_object_data data;
            auto detected_object = parse_object_member("detected_object_data",object, true);
            data._detected_object_common_data = parse_detected_object_data_common(parse_object_member("detected_object_common_data", detected_object.value(), true).value());
            if ( auto data_optional = parse_object_member("detected_object_optional_data", detected_object.value(), false); data_optional.has_value()) {
                data._detected_object_optional_data = parse_detected_object_data_optional( data_optional.value() );
            }
            detected_object_list.push_back(data);
        }
        return detected_object_list;
    }
References simulate_bsm::data, streets_utils::json_utils::parse_array_member(), parse_detected_object_data_common(), parse_detected_object_data_optional(), and streets_utils::json_utils::parse_object_member().
Referenced by from_json().
parse_detected_obstacle_data()
detected_obstacle_data streets_utils::messages::sdsm::parse_detected_obstacle_data (const rapidjson::Value & val)
Definition at line 165 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        detected_obstacle_data data;
        data._size = parse_obstacle_size(parse_object_member("obst_size", val, true).value());
        data._size_confidence = parse_obstacle_size_confidence(parse_object_member("obst_size_confidence", val, true).value());
        return data;
    }
References simulate_bsm::data, streets_utils::json_utils::parse_object_member(), parse_obstacle_size(), parse_obstacle_size_confidence(), and simulate_bsm::value.
Referenced by parse_detected_object_data_optional().
parse_detected_vehicle_data()
detected_vehicle_data streets_utils::messages::sdsm::parse_detected_vehicle_data (const rapidjson::Value & val)
Definition at line 172 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        detected_vehicle_data data;
        data.exterior_lights = parse_string_member("lights", val, false); {
        if ( val.HasMember("veh_attitude"))
            data._veh_attitude = parse_vehicle_attitude(parse_object_member("veh_attitude", val, false).value());
        }
        if ( val.HasMember("veh_attitude_confidence")) {
            data._attitude_confidence = parse_vehicle_attitude_confidence(parse_object_member("veh_attitude_confidence", val, false).value());
        }
        if ( val.HasMember("veh_ang_vel")) {
            data._angular_velocity = parse_vehicle_angular_velocity_set(parse_object_member("veh_ang_vel", val, false).value());
        }
        if ( val.HasMember("veh_ang_vel_confidence")) {
            data._angular_velocity_confidence = parse_vehicle_angular_velocity_confidence_set(parse_object_member("veh_ang_vel_confidence", val, false).value());
        }
        if ( val.HasMember("size")) {
            data._size = parse_vehicle_size(parse_object_member("size", val, false).value());
        }
        if ( val.HasMember("vehicle_size_confidence")) {
            data._size_confidence = parse_vehicle_size_confidence(parse_object_member("vehicle_size_confidence", val, false).value());
        }
        data._vehicle_height = parse_uint_member("height", val, false);
        data._vehicle_class = parse_uint_member("vehicle_class", val, false);
        data._classification_confidence =  parse_uint_member("class_conf", val, false);
        return data;
    }
References simulate_bsm::data, streets_utils::json_utils::parse_object_member(), streets_utils::json_utils::parse_string_member(), streets_utils::json_utils::parse_uint_member(), parse_vehicle_angular_velocity_confidence_set(), parse_vehicle_angular_velocity_set(), parse_vehicle_attitude(), parse_vehicle_attitude_confidence(), parse_vehicle_size(), parse_vehicle_size_confidence(), and simulate_bsm::value.
Referenced by parse_detected_object_data_optional().
parse_detected_vru_data()
detected_vru_data streets_utils::messages::sdsm::parse_detected_vru_data (const rapidjson::Value & val)
Definition at line 249 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        detected_vru_data data;
        if ( auto basic_type_value = parse_uint_member("basic_type", val, false); basic_type_value.has_value() ) {
            data._personal_device_user_type = personal_device_user_type_from_int( basic_type_value.value());
        }
        if ( val.HasMember("propulsion") ) {
            data._propulsion = parse_propelled_information(parse_object_member("propulsion", val, true).value());
        }
        if (auto attachment_value = parse_uint_member("attachment", val, false); attachment_value.has_value()  ){
            data._attachment = attachment_from_int( attachment_value.value());
        }
        data._attachment_radius = parse_uint_member("radius", val, false);
        return data;
    }
References attachment_from_int(), simulate_bsm::data, streets_utils::json_utils::parse_object_member(), parse_propelled_information(), streets_utils::json_utils::parse_uint_member(), personal_device_user_type_from_int(), and simulate_bsm::value.
Referenced by parse_detected_object_data_optional().
parse_elevation_confidence()
std::optional< position_confidence > streets_utils::messages::sdsm::parse_elevation_confidence (const rapidjson::Value & val)
Definition at line 65 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        std::optional<position_confidence> _position_confidence;
        if (auto _position_confidence_value = parse_uint_member("ref_pos_el_conf", val, false); _position_confidence_value.has_value() ) {
            _position_confidence = position_confidence_from_int(_position_confidence_value.value());
        }
        return _position_confidence;
    }
References streets_utils::json_utils::parse_uint_member(), and position_confidence_from_int().
Referenced by from_json().
parse_obstacle_size()
obstacle_size streets_utils::messages::sdsm::parse_obstacle_size (const rapidjson::Value & val)
Definition at line 282 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        obstacle_size data;
        data._length = parse_uint_member("length", val, true).value();
        data._width = parse_uint_member("width", val, true).value();
        // Optional height
        data._height = parse_uint_member("height", val, true);
        return data;
    }
References simulate_bsm::data, and streets_utils::json_utils::parse_uint_member().
Referenced by parse_detected_obstacle_data().
parse_obstacle_size_confidence()
obstacle_size_confidence streets_utils::messages::sdsm::parse_obstacle_size_confidence (const rapidjson::Value & val)
Definition at line 291 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        obstacle_size_confidence data;
        data._length_confidence = size_value_confidence_from_int( parse_uint_member("length_confidence", val, true).value());
        data._width_confidence = size_value_confidence_from_int( parse_uint_member("width_confidence", val, true).value());
        // Optional height value
        if ( auto height_confidence_value = parse_uint_member("height_confidence", val, false); height_confidence_value.has_value() ){
            data._height_confidence = size_value_confidence_from_int( parse_uint_member("height_confidence", val, true).value());
        }
        return data;
    }
References simulate_bsm::data, streets_utils::json_utils::parse_uint_member(), size_value_confidence_from_int(), and simulate_bsm::value.
Referenced by parse_detected_obstacle_data().
parse_position_3d()
position_3d streets_utils::messages::sdsm::parse_position_3d (const rapidjson::Value & val)
Definition at line 46 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        position_3d _position_3d;
        _position_3d._longitude = parse_int_member("long", val, true).value();
        _position_3d._latitude = parse_int_member("lat", val, true).value();
        // parse optional elevation
        _position_3d._elevation = parse_int_member("elevation", val, false);
        return _position_3d;
    }
References streets_utils::messages::sdsm::position_3d::_elevation, streets_utils::messages::sdsm::position_3d::_latitude, streets_utils::messages::sdsm::position_3d::_longitude, and streets_utils::json_utils::parse_int_member().
Referenced by from_json().
parse_position_confidence_set()
position_confidence_set streets_utils::messages::sdsm::parse_position_confidence_set (const rapidjson::Value & val)
Definition at line 149 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        position_confidence_set data;
        data._position_confidence = position_confidence_from_int( parse_uint_member("pos", val, true).value());
        data._elevation_confidence = position_confidence_from_int( parse_uint_member("elevation", val, true).value());
        return data;
    }
References simulate_bsm::data, streets_utils::json_utils::parse_uint_member(), position_confidence_from_int(), and simulate_bsm::value.
Referenced by parse_detected_object_data_common().
parse_position_offset()
position_offset streets_utils::messages::sdsm::parse_position_offset (const rapidjson::Value & val)
Definition at line 140 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        position_offset data;
        data._offset_x = parse_int_member("offset_x", val, true).value();
        data._offset_y = parse_int_member("offset_y", val, true).value();
        data._offset_y = parse_int_member("offset_y", val, true).value();
        return data;
    }
References simulate_bsm::data, and streets_utils::json_utils::parse_int_member().
Referenced by parse_detected_object_data_common().
parse_positional_accuracy()
positional_accuracy streets_utils::messages::sdsm::parse_positional_accuracy (const rapidjson::Value & val)
Definition at line 56 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        positional_accuracy _positional_accuracy;
        _positional_accuracy._semi_major_axis_accuracy = parse_uint_member("semi_major", val, true).value();
        _positional_accuracy._semi_minor_axis_accuracy = parse_uint_member("semi_minor", val, true).value();
        _positional_accuracy._semi_major_axis_orientation = parse_uint_member("orientation",val, true).value();
        return _positional_accuracy;
    }
References streets_utils::messages::sdsm::positional_accuracy::_semi_major_axis_accuracy, streets_utils::messages::sdsm::positional_accuracy::_semi_major_axis_orientation, streets_utils::messages::sdsm::positional_accuracy::_semi_minor_axis_accuracy, and streets_utils::json_utils::parse_uint_member().
Referenced by from_json().
parse_propelled_information()
std::optional< std::variant< human_propelled_type, motorized_propelled_type, animal_propelled_type > > streets_utils::messages::sdsm::parse_propelled_information (const rapidjson::Value & val)
Definition at line 264 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        std::optional<std::variant<human_propelled_type, motorized_propelled_type, animal_propelled_type>> data;
        if (val.HasMember("human")) {
            data = human_propelled_type_from_int(parse_uint_member("human", val, true).value());
        }
        else if (val.HasMember("animal")) {
            data = animal_propelled_type_from_int(parse_uint_member("animal", val, true).value());
        }
        else if (val.HasMember("motor")) {
            data = motorized_propelled_type_from_int(parse_uint_member("motor", val, true).value());
        }
        else {
            throw json_parse_exception("Propelled information requires one of the following to be define: human propelled type, animal propelled type, motorized propelled type.");
        }
        return data;
    }
References animal_propelled_type_from_int(), simulate_bsm::data, human_propelled_type_from_int(), motorized_propelled_type_from_int(), streets_utils::json_utils::parse_uint_member(), and simulate_bsm::value.
Referenced by parse_detected_vru_data().
parse_time_stamp()
time_stamp streets_utils::messages::sdsm::parse_time_stamp (const rapidjson::Value & val)
Definition at line 33 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        time_stamp _time_stamp;
        _time_stamp.offset = parse_int_member("offset", val, true).value();
        _time_stamp.second = parse_uint_member("second", val, true).value();
        _time_stamp.minute = parse_uint_member("minute", val, true).value();
        _time_stamp.hour = parse_uint_member("hour", val, true).value();
        _time_stamp.day = parse_uint_member("day", val, true).value();
        _time_stamp.month = parse_uint_member("month", val, true).value();
        _time_stamp.year = parse_uint_member("year", val, true).value();
        return _time_stamp;
    }
References streets_utils::messages::sdsm::time_stamp::day, streets_utils::messages::sdsm::time_stamp::hour, streets_utils::messages::sdsm::time_stamp::minute, streets_utils::messages::sdsm::time_stamp::month, streets_utils::messages::sdsm::time_stamp::offset, streets_utils::json_utils::parse_int_member(), streets_utils::json_utils::parse_uint_member(), streets_utils::messages::sdsm::time_stamp::second, and streets_utils::messages::sdsm::time_stamp::year.
Referenced by from_json().
parse_vehicle_angular_velocity_confidence_set()
angular_velocity_confidence_set streets_utils::messages::sdsm::parse_vehicle_angular_velocity_confidence_set (const rapidjson::Value & val)
Definition at line 217 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        angular_velocity_confidence_set data;
        data._pitch_rate_confidence = angular_velocity_confidence_from_int( parse_uint_member("pitch_rate_confidence", val, true).value());
        data._roll_rate_confidence = angular_velocity_confidence_from_int( parse_uint_member("roll_rate_confidence", val, true).value());
        return data;
    }
References angular_velocity_confidence_from_int(), simulate_bsm::data, streets_utils::json_utils::parse_uint_member(), and simulate_bsm::value.
Referenced by parse_detected_vehicle_data().
parse_vehicle_angular_velocity_set()
angular_velocity_set streets_utils::messages::sdsm::parse_vehicle_angular_velocity_set (const rapidjson::Value & val)
Definition at line 209 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        angular_velocity_set data;
        data._pitch_rate = parse_int_member("pitch_rate", val, true).value();
        data._roll_rate = parse_int_member("roll_rate", val, true).value();
        return data;
    }
References simulate_bsm::data, and streets_utils::json_utils::parse_int_member().
Referenced by parse_detected_vehicle_data().
parse_vehicle_attitude()
attitude streets_utils::messages::sdsm::parse_vehicle_attitude (const rapidjson::Value & val)
Definition at line 241 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        attitude data;
        data._pitch = parse_int_member("pitch", val, true).value();
        data._roll = parse_int_member("roll", val, true).value();
        data._yaw = parse_int_member("yaw", val, true).value();
        return data;
    }
References simulate_bsm::data, and streets_utils::json_utils::parse_int_member().
Referenced by parse_detected_vehicle_data().
parse_vehicle_attitude_confidence()
attitude_confidence streets_utils::messages::sdsm::parse_vehicle_attitude_confidence (const rapidjson::Value & val)
Definition at line 200 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        attitude_confidence data;
        data._pitch_confidence = heading_confidence_from_int(parse_uint_member("pitch_confidence", val, true).value());
        data._roll_confidence = heading_confidence_from_int(parse_uint_member("roll_confidence", val, true).value());
        data._yaw_confidence = heading_confidence_from_int(parse_uint_member("yaw_confidence", val, true).value());
        return data;
    }
References simulate_bsm::data, heading_confidence_from_int(), streets_utils::json_utils::parse_uint_member(), and simulate_bsm::value.
Referenced by parse_detected_vehicle_data().
parse_vehicle_size()
vehicle_size streets_utils::messages::sdsm::parse_vehicle_size (const rapidjson::Value & val)
Definition at line 224 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        vehicle_size data;
        data._length = parse_uint_member("length", val, true).value();
        data._width = parse_uint_member("width", val, true).value();
        return data;
    }
References simulate_bsm::data, and streets_utils::json_utils::parse_uint_member().
Referenced by parse_detected_vehicle_data().
parse_vehicle_size_confidence()
vehicle_size_confidence streets_utils::messages::sdsm::parse_vehicle_size_confidence (const rapidjson::Value & val)
Definition at line 231 of file sensor_data_sharing_msg_json_deserializer.cpp.
{
        vehicle_size_confidence data;
        data._width_confidence = size_value_confidence_from_int(parse_uint_member("vehicle_width_confidence", val, true).value());
        data._length_confidence = size_value_confidence_from_int(parse_uint_member("vehicle_length_confidence", val, true).value());
        if (auto height_confidence_val = parse_uint_member("vehicle_height_confidence", val, false); height_confidence_val.has_value()) {
            data._height_confidence = size_value_confidence(height_confidence_val.value());
        }
        return data;
    }
References simulate_bsm::data, streets_utils::json_utils::parse_uint_member(), size_value_confidence_from_int(), and simulate_bsm::value.
Referenced by parse_detected_vehicle_data().
personal_device_user_type_from_int()
personal_device_user_type streets_utils::messages::sdsm::personal_device_user_type_from_int (const unsigned int i) inline
Definition at line 26 of file personal_device_user_type.hpp.
{
        switch (i)
        {
        case 0:
            return personal_device_user_type::UNAVAILABLE;
        case 1:
            return personal_device_user_type::PEDESTRIAN;
        case 2:
            return personal_device_user_type::PEDALCYCLIST;
        case 3:
            return personal_device_user_type::PUBLIC_SAFETY_WORKER;
        case 4:
            return personal_device_user_type::ANIMAL;
        default:
            throw std::invalid_argument("Incompatible personal devvice user type value. Valid values : [0,4]");
        }
    };
References ANIMAL, simulate_bsm::i, PEDALCYCLIST, PEDESTRIAN, PUBLIC_SAFETY_WORKER, and UNAVAILABLE.
Referenced by parse_detected_vru_data().
position_confidence_from_int()
position_confidence streets_utils::messages::sdsm::position_confidence_from_int (const int i) inline
Definition at line 37 of file position_confidence.hpp.
{
        switch (i)
        {
        case 0:
            return position_confidence::UNAVAILABLE;
        case 1:
            return position_confidence::A_500M;
        case 2:
            return position_confidence::A_200M;
        case 3:
            return position_confidence::A_100M;
        case 4:
            return position_confidence::A_50M;
        case 5:
            return position_confidence::A_20M;
        case 6:
            return position_confidence::A_10M;
        case 7:
            return position_confidence::A_5M;
        case 8:
            return position_confidence::A_2M;
        case 9:
            return position_confidence::A_1M;
        case 10:
            return position_confidence::A_50CM;
        case 11:
            return position_confidence::A_20CM;
        case 12:
            return position_confidence::A_10CM;
        case 13:
            return position_confidence::A_5CM;
        case 14:
            return position_confidence::A_2CM;
        case 15:
            return position_confidence::A_1CM;
        default:
            throw std::invalid_argument("Incompatible position confidence value. Valid values : [0,15]");
        }
    };
References A_100M, A_10CM, A_10M, A_1CM, A_1M, A_200M, A_20CM, A_20M, A_2CM, A_2M, A_500M, A_50CM, A_50M, A_5CM, A_5M, simulate_bsm::i, and UNAVAILABLE.
Referenced by parse_elevation_confidence(), and parse_position_confidence_set().
size_value_confidence_from_int()
size_value_confidence streets_utils::messages::sdsm::size_value_confidence_from_int (const unsigned int i) inline
Definition at line 34 of file size_value_confidence.hpp.
{
        switch (i)
        {
        case 0:
            return size_value_confidence::UNAVAILABLE;
        case 1:
            return size_value_confidence::SIZE_100;
        case 2:
            return size_value_confidence::SIZE_50;
        case 3:
            return size_value_confidence::SIZE_20;
        case 4:
            return size_value_confidence::SIZE_10;
        case 5:
            return size_value_confidence::SIZE_5;
        case 6:
            return size_value_confidence::SIZE_2;
        case 7:
            return size_value_confidence::SIZE_1;
        case 8:
            return size_value_confidence::SIZE_0_5;
        case 9:
            return size_value_confidence::SIZE_0_2;
        case 10:
            return size_value_confidence::SIZE_0_1;
        case 11:
            return size_value_confidence::SIZE_0_05;
        case 12:
            return size_value_confidence::SIZE_0_02;
        case 13:
            return size_value_confidence::SIZE_0_01;
        default:
            throw std::invalid_argument("Incompatible size confidence value. Valid values : [0,13]");
        }
    }
References simulate_bsm::i, SIZE_0_01, SIZE_0_02, SIZE_0_05, SIZE_0_1, SIZE_0_2, SIZE_0_5, SIZE_1, SIZE_10, SIZE_100, SIZE_2, SIZE_20, SIZE_5, SIZE_50, and UNAVAILABLE.
Referenced by parse_obstacle_size_confidence(), and parse_vehicle_size_confidence().
speed_confidence_from_int()
speed_confidence streets_utils::messages::sdsm::speed_confidence_from_int (const unsigned int i) inline
Definition at line 28 of file speed_confidence.hpp.
{
        switch (i)
        {
        case 0:
            return speed_confidence::UNAVAILABLE;
        case 1:
            return speed_confidence::PREC_100ms;
        case 2:
            return speed_confidence::PREC_10ms;
        case 3:
            return speed_confidence::PREC_5ms;
        case 4:
            return speed_confidence::PREC_1ms;
        case 5:
            return speed_confidence::PREC_0_1ms;
        case 6:
            return speed_confidence::PREC_0_05ms;
        case 7:
            return speed_confidence::PREC_0_01ms;
        default:
            throw std::invalid_argument("Incompatible speed confidence value. Valid values : [0,7]");
        }
    };
References simulate_bsm::i, PREC_0_01ms, PREC_0_05ms, PREC_0_1ms, PREC_100ms, PREC_10ms, PREC_1ms, PREC_5ms, and UNAVAILABLE.
Referenced by parse_detected_object_data_common().
time_confidence_from_int()
time_confidence streets_utils::messages::sdsm::time_confidence_from_int (const int i) inline
Definition at line 60 of file time_confidence.hpp.
{
        switch (i)
        {
        case 0:
            return time_confidence::UNAVAILABLE;
        case 1:
            return time_confidence::TIME_100_000;
        case 2:
            return time_confidence::TIME_050_000 ;
        case 3:
            return time_confidence::TIME_020_000 ;
        case 4:
            return time_confidence::TIME_010_000 ;
        case 5:
            return time_confidence::TIME_002_000 ;
        case 6:
            return time_confidence::TIME_001_000 ;
        case 7:
            return time_confidence::TIME_000_500 ;
        case 8:
            return time_confidence::TIME_000_200 ;
        case 9:
            return time_confidence::TIME_000_100 ;
        case 10:
            return time_confidence::TIME_000_050 ;
        case 11:
            return time_confidence::TIME_000_020 ;
        case 12:
            return time_confidence::TIME_000_010 ;
        case 13:
            return time_confidence::TIME_000_005 ;
        case 14:
            return time_confidence::TIME_000_002 ;
        case 15:
            return time_confidence::TIME_000_001 ;
        case 16:
            return time_confidence::TIME_000_000_5;
        case 17:
            return time_confidence::TIME_000_000_2;
        case 18:
            return time_confidence::TIME_000_000_1;
        case 19:
            return time_confidence::TIME_000_000_05;
        case 20:
            return time_confidence::TIME_000_000_02;
        case 21:
            return time_confidence::TIME_000_000_01;
        case 22:
            return time_confidence::TIME_000_000_005;
        case 23:
            return time_confidence::TIME_000_000_002;
        case 24:
            return time_confidence::TIME_000_000_001;
        case 25:
            return time_confidence::TIME_000_000_000_5;
        case 26:
            return time_confidence::TIME_000_000_000_2;
        case 27:
            return time_confidence::TIME_000_000_000_1;
        case 28:
            return time_confidence::TIME_000_000_000_05;
        case 29:
            return time_confidence::TIME_000_000_000_02;
        case 30:
            return time_confidence::TIME_000_000_000_01;
        case 31:
            return time_confidence::TIME_000_000_000_005;
        case 32:
            return time_confidence::TIME_000_000_000_002;
        case 33:
            return time_confidence::TIME_000_000_000_001;
        case 34:
            return time_confidence::TIME_000_000_000_000_5;
        case 35:
            return time_confidence::TIME_000_000_000_000_2;
        case 36:
            return time_confidence::TIME_000_000_000_000_1;
        case 37:
            return time_confidence::TIME_000_000_000_000_05;
        case 38:
            return time_confidence::TIME_000_000_000_000_02;
        case 39:
            return time_confidence::TIME_000_000_000_000_01;
        default:
            throw std::invalid_argument("Incompatible time confidence value. Valid values : [0,39]");
        }
    };
References simulate_bsm::i, TIME_000_000_000_000_01, TIME_000_000_000_000_02, TIME_000_000_000_000_05, TIME_000_000_000_000_1, TIME_000_000_000_000_2, TIME_000_000_000_000_5, TIME_000_000_000_001, TIME_000_000_000_002, TIME_000_000_000_005, TIME_000_000_000_01, TIME_000_000_000_02, TIME_000_000_000_05, TIME_000_000_000_1, TIME_000_000_000_2, TIME_000_000_000_5, TIME_000_000_001, TIME_000_000_002, TIME_000_000_005, TIME_000_000_01, TIME_000_000_02, TIME_000_000_05, TIME_000_000_1, TIME_000_000_2, TIME_000_000_5, TIME_000_001, TIME_000_002, TIME_000_005, TIME_000_010, TIME_000_020, TIME_000_050, TIME_000_100, TIME_000_200, TIME_000_500, TIME_001_000, TIME_002_000, TIME_010_000, TIME_020_000, TIME_050_000, TIME_100_000, and UNAVAILABLE.
Referenced by parse_detected_object_data_common().
to_json()
std::string streets_utils::messages::sdsm::to_json (const sensor_data_sharing_msg & val)
Definition at line 18 of file sensor_data_sharing_msg_json_serializer.cpp.
{
        rapidjson::Document doc;
        rapidjson::Value sdsm_json(rapidjson::kObjectType);
        sdsm_json.AddMember("msg_cnt", msg._msg_count, doc.GetAllocator());
        sdsm_json.AddMember("source_id", msg._source_id, doc.GetAllocator());
        sdsm_json.AddMember("equipment_type", static_cast<int>(msg._equipment_type), doc.GetAllocator());
        // Construct SDSM Time Stamp JSON Object
        auto time_stamp_json = create_timestamp(msg._time_stamp, doc.GetAllocator());
        sdsm_json.AddMember("sdsm_time_stamp", time_stamp_json, doc.GetAllocator());
        // Construct reference position JSON Object
        auto position_3d_json = create_position_3d( msg._ref_positon, doc.GetAllocator() );
        sdsm_json.AddMember("ref_pos", position_3d_json, doc.GetAllocator());
        sdsm_json.AddMember("ref_pos_xy_conf", create_positional_accuracy( msg._ref_position_confidence, doc.GetAllocator()), doc.GetAllocator());
        if ( msg._ref_position_elevation_confidence.has_value() )
            sdsm_json.AddMember("ref_pos_el_conf", static_cast<unsigned int >(msg._ref_position_elevation_confidence.value()), doc.GetAllocator());
        // Construct object list
        sdsm_json.AddMember("objects", create_detected_object_list(msg._objects, doc.GetAllocator()), doc.GetAllocator());
        rapidjson::StringBuffer buffer;
        rapidjson::Writer<rapidjson::StringBuffer> writer(buffer);
        sdsm_json.Accept(writer);
        return buffer.GetString();
    }
References streets_utils::messages::sdsm::sensor_data_sharing_msg::_equipment_type, streets_utils::messages::sdsm::sensor_data_sharing_msg::_msg_count, streets_utils::messages::sdsm::sensor_data_sharing_msg::_objects, streets_utils::messages::sdsm::sensor_data_sharing_msg::_ref_position_confidence, streets_utils::messages::sdsm::sensor_data_sharing_msg::_ref_position_elevation_confidence, streets_utils::messages::sdsm::sensor_data_sharing_msg::_ref_positon, streets_utils::messages::sdsm::sensor_data_sharing_msg::_source_id, streets_utils::messages::sdsm::sensor_data_sharing_msg::_time_stamp, create_detected_object_list(), create_position_3d(), create_positional_accuracy(), and create_timestamp().
Referenced by sensor_data_sharing_service::sds_service::produce_sdsms().