Carma-streets: simulate_bsm_mobilityPath Namespace Reference
simulate_bsm_mobilityPath Namespace Reference
Functions
def read_json (json_name)
def produce_bsm ()
def produce_mobility_path ()
Variables
bsm_th = threading.Thread(target=produce_bsm)
mobility_path_th = threading.Thread(target=produce_mobility_path)
Function Documentation
produce_bsm()
def simulate_bsm_mobilityPath.produce_bsm ()
Definition at line 16 of file simulate_bsm_mobilityPath.py.
def produce_bsm():
    producer = KafkaProducer(bootstrap_servers=["127.0.0.1:9092"],
                             value_serializer=lambda x: json.dumps(x).encode('utf-8'))
    count = 10
    i = 0
    while(i < count):
        data = read_json('bsm.json')
        data["core_data"]["msg_count"] = str(i)
        data["core_data"]["speed"] = str(i)
        producer.send('v2xhub_bsm_in', value=data)
        print('Sent a bsm.')
        i += 1
        producer.flush()
References read_json().
produce_mobility_path()
def simulate_bsm_mobilityPath.produce_mobility_path ()
Definition at line 31 of file simulate_bsm_mobilityPath.py.
def produce_mobility_path():
    producer = KafkaProducer(bootstrap_servers=["127.0.0.1:9092"],
                             value_serializer=lambda x: json.dumps(x).encode('utf-8'))
    i = 0
    count = 10
    while(i < count):
        data = read_json('mobilitypath.json')
        timestamp = int(data["metadata"]["timestamp"]) + i
        data["metadata"]["timestamp"] = str(timestamp)
        producer.send('v2xhub_mobility_path_in', value=data)
        print('Sent a mobilitypath.')
        i += 1
        producer.flush()
References read_json().
read_json()
def simulate_bsm_mobilityPath.read_json (json_name)
Definition at line 9 of file simulate_bsm_mobilityPath.py.
def read_json(json_name):
    data = {}
    with open(json_name, "r") as json_file:
        data = json.load(json_file)
    return data
Referenced by produce_bsm(), and produce_mobility_path().
Variable Documentation
bsm_th
simulate_bsm_mobilityPath.bsm_th = threading.Thread(target=produce_bsm)
Definition at line 47 of file simulate_bsm_mobilityPath.py.
mobility_path_th
simulate_bsm_mobilityPath.mobility_path_th = threading.Thread(target=produce_mobility_path)
Definition at line 48 of file simulate_bsm_mobilityPath.py.