Carma-streets: streets_vehicle_scheduler Namespace Reference
streets_vehicle_scheduler Namespace Reference
Classes
struct all_stop_intersection_schedule
Struct to store vehicle schedules for all vehicle in an intersection. Includes a timestamp in milliseconds since epoch. Also includes a get_delay method that will get each vehicle schedules delay and sum them for a total intersection delay. Delay is the difference between scheduled Entering Time (et) and scheduled Stopping time (st) and represents the time a vehicle would be waiting at the stop bar before gaining access to the intersection.
struct all_stop_vehicle_schedule
Object to represent all_stop schedule for single vehicle.
class all_stop_vehicle_scheduler
struct intersection_schedule
Struct to store vehicle schedules for all vehicle in an intersection. Includes a timestamp in milliseconds since epoch. Also includes a get_delay method that will get each vehicle schedules delay and sum them for a total intersection delay. Delay is the difference between scheduled Entering Time (et) and scheduled Stopping time (st) and represents the time a vehicle would be waiting at the stop bar before gaining access to the intersection.
class scheduling_exception
Runtime error related to processing status intent vehicle updates.
struct signalized_intersection_schedule
Struct to store vehicle schedules for all vehicle in an intersection. Includes a timestamp in milliseconds since epoch.
struct signalized_vehicle_schedule
Object to represent schedule for single vehicle.
class signalized_vehicle_scheduler
struct vehicle_schedule
Object to represent schedule for single vehicle.
class vehicle_scheduler
Abstract Class for extend to implement scheduling business logic.
Functions
bool departure_position_comparator (const streets_vehicles::vehicle &prev_veh, const streets_vehicles::vehicle &next_veh)
Comparator for vehicle collections. Used for sorting vehicle objects in a collection in ascending order with respect to their departure position value. Values lower than one are treated as unset and order last after the largest positive departure position.
bool st_comparator (const streets_vehicles::vehicle &prev_veh, const streets_vehicles::vehicle &next_veh)
Comparator for vehicle collections. Used for sorting vehicle objects in a collection in ascending order with respect to their stopping time value.
bool distance_comparator (const streets_vehicles::vehicle &prev_veh, const streets_vehicles::vehicle &next_veh)
Comparator for vehicle collections. Used for sorting vehicle objects in a collection in ascending order with respect to their distance value.
bool delay_comparator (const std::shared_ptr< all_stop_intersection_schedule > &prev_sched, const std::shared_ptr< all_stop_intersection_schedule > &next_sched)
Comparator for intersection_schedule collections. Used for sorting intersection_schedule objects in a collection in ascending order with respect to their delay value.
bool et_comparator (const signalized_vehicle_schedule &prev_sched, const signalized_vehicle_schedule &next_sched)
Comparator for vehicle collections. Used for sorting vehicle objects in a collection in ascending order with respect to their et value.
Function Documentation
delay_comparator()
bool streets_vehicle_scheduler::delay_comparator (const std::shared_ptr< all_stop_intersection_schedule > & prev_sched, const std::shared_ptr< all_stop_intersection_schedule > & next_sched)
Comparator for intersection_schedule collections. Used for sorting intersection_schedule objects in a collection in ascending order with respect to their delay value.
Parameters
prev_sched first intersection_schedule.
next_sched next intersection_schedule.
Returns
true if first should come before next.
false if first should not come before next.
Definition at line 33 of file vehicle_sorting.cpp.
{
        return prev_sched->get_delay() < next_sched->get_delay();
    }
Referenced by streets_vehicle_scheduler::all_stop_vehicle_scheduler::schedule_rdvs().
departure_position_comparator()
bool streets_vehicle_scheduler::departure_position_comparator (const streets_vehicles::vehicle & prev_veh, const streets_vehicles::vehicle & next_veh)
Comparator for vehicle collections. Used for sorting vehicle objects in a collection in ascending order with respect to their departure position value. Values lower than one are treated as unset and order last after the largest positive departure position.
Parameters
prev_veh first vehicle.
next_veh next vehicle.
Returns
true if first should come before next.
false if first should not come before next.
Definition at line 4 of file vehicle_sorting.cpp.
{
        // -1 indicates unassigned departure position which should be last when sorted in ascending order
        if ((prev_veh._departure_position < 1  && next_veh._departure_position < 1) ||  prev_veh._departure_position < 1) {
            return prev_veh._departure_position > next_veh._departure_position;
        }
        else {
            return prev_veh._departure_position < next_veh._departure_position;
        }
    }
References streets_vehicles::vehicle::_departure_position.
Referenced by streets_vehicle_scheduler::all_stop_vehicle_scheduler::schedule_dvs(), and streets_vehicle_scheduler::all_stop_vehicle_scheduler::schedule_rdvs().
distance_comparator()
bool streets_vehicle_scheduler::distance_comparator (const streets_vehicles::vehicle & prev_veh, const streets_vehicles::vehicle & next_veh)
Comparator for vehicle collections. Used for sorting vehicle objects in a collection in ascending order with respect to their distance value.
Parameters
prev_veh first vehicle.
next_veh next vehicle.
Returns
true if first should come before next.
false if first should not come before next.
Definition at line 29 of file vehicle_sorting.cpp.
{
        return prev_veh._cur_distance < next_veh._cur_distance;
    }
References streets_vehicles::vehicle::_cur_distance.
Referenced by streets_vehicle_scheduler::all_stop_vehicle_scheduler::schedule_evs(), and streets_vehicle_scheduler::signalized_vehicle_scheduler::schedule_evs().
et_comparator()
bool streets_vehicle_scheduler::et_comparator (const signalized_vehicle_schedule & prev_sched, const signalized_vehicle_schedule & next_sched)
Comparator for vehicle collections. Used for sorting vehicle objects in a collection in ascending order with respect to their et value.
Parameters
prev_sched first vehicle schedule.
next_sched next vehicle schedule.
Returns
true if first should come before next.
false if first should not come before next.
Definition at line 37 of file vehicle_sorting.cpp.
{
        return prev_sched.et < next_sched.et;
    }
References streets_vehicle_scheduler::signalized_vehicle_schedule::et.
Referenced by streets_signal_optimization::streets_desired_phase_plan_generator::get_schedules_in_tbd_per_lane().
st_comparator()
bool streets_vehicle_scheduler::st_comparator (const streets_vehicles::vehicle & prev_veh, const streets_vehicles::vehicle & next_veh)
Comparator for vehicle collections. Used for sorting vehicle objects in a collection in ascending order with respect to their stopping time value.
Parameters
prev_veh first vehicle.
next_veh next vehicle.
Returns
true if first should come before next.
false if first should not come before next.
Exceptions
scheduling_exception if stopping time is 0 which is an invalid stopping time and can not be sorted.
Definition at line 14 of file vehicle_sorting.cpp.
{
        // -1 indicates unassigned departure position which should be last when sorted in ascending order
        if (prev_veh._actual_st == 0  || next_veh._actual_st == 0) {
            if ( prev_veh._actual_st < 1)
                throw scheduling_exception("Vehicle " + prev_veh._id + " has invalid actual st of " + std::to_string(prev_veh._actual_st) + "!");
            else if ( next_veh._actual_st < 1 )
                throw scheduling_exception("Vehicle " + next_veh._id + " has invalid actual st of " + std::to_string(next_veh._actual_st) + "!");
            return true;
        }
        else {
            return prev_veh._actual_st < next_veh._actual_st;
        }
    }
References streets_vehicles::vehicle::_actual_st, streets_vehicles::vehicle::_id, and to_string().