Carma-streets: sensor_data_sharing_service Namespace Reference
sensor_data_sharing_service Namespace Reference
Classes
class sds_service
Functions
streets_utils::messages::sdsm::time_stamp to_sdsm_timestamp (const uint64_t _epoch_time_ms)
convert epoch millisecond timestamp to sdsm timestamp object
streets_utils::messages::sdsm::detected_object_data to_detected_object_data (const streets_utils::messages::detected_objects_msg::detected_objects_msg &msg)
convert detected_object_msg to sdsm detection_object_data.
streets_utils::messages::sdsm::object_type to_object_type (const std::string &detection_type)
convert string detection type to sdsm object_type.
unsigned int to_heading (const streets_utils::messages::detected_objects_msg::vector_3d &velocity)
Convert XY velocity into 2 dimensional heading measured in 0.0125 degree units.
streets_utils::messages::sdsm::position_confidence_set to_position_confidence_set (const std::vector< std::vector< double > > &_position_covariance)
Convert position covariance to position confidence set which includes positionXY confidence and position z confidence.
streets_utils::messages::sdsm::speed_confidence to_xy_speed_confidence (const std::vector< std::vector< double > > &velocity_covariance)
Convert velocity covariance to xy speed confidence.
streets_utils::messages::sdsm::speed_confidence to_z_speed_confidence (const std::vector< std::vector< double > > &velocity_covariance)
Convert velocity covariance to z speed confidence.
streets_utils::messages::sdsm::speed_confidence to_speed_confidence (const double accuracy)
Convert accuracy value to speed confidence enumeration. To minimize error in conversion, method rounds up/down to the nearest enum value.
streets_utils::messages::sdsm::angular_velocity_confidence to_yaw_rate_confidence (const std::vector< std::vector< double > > &angular_velocity_covariance)
Convert angular velocity covariance to angular velocity confidence.
streets_utils::messages::sdsm::position_confidence to_position_confidence (const double accuracy)
Convert accuracy value to position confidence enumeration. To minimize error in conversion, method rounds up/down to the nearest enum value.
streets_utils::messages::sdsm::angular_velocity_confidence to_angular_velocity_confidence (const double accuracy)
Convert accuracy value to angular velocity confidence enumeration. To minimize error in conversion, method rounds up/down to the nearest enum value.
int to_yaw_rate (const double yaw_rate_radians_per_second)
Convert yaw rate in radians per second to 100ths of a degree per second.
lanelet::BasicPoint3d parse_sensor_location (const std::string &filepath, const std::string &sensor_id)
Method to parse sensor configuration json file.
streets_utils::messages::sdsm::position_3d to_position_3d (const lanelet::GPSPoint &ref_position)
Variables
const std::map< std::string, streets_utils::messages::sdsm::object_type, std::less<> > sdsm_object_types
Map of detection types to SDSM object types.
const int MILLISECONDS_TO_MICROSECONDS = 1000
const int SECONDS_TO_MILLISECONDS = 1000
const int METERS_TO_CM = 100
const int METERS_TO_5_CM = 20
const int METERS_TO_10_CM = 10
const int METERS_PER_SECOND_TO_2_CM_PER_SECOND = 50
Function Documentation
parse_sensor_location()
lanelet::BasicPoint3d sensor_data_sharing_service::parse_sensor_location (const std::string & filepath, const std::string & sensor_id)
Method to parse sensor configuration json file.
Parameters
filepath absolute or relative file path.
sensor_id ID of sensor to get location from.
Returns
cartesian location of sensor described in json configuration file.
Definition at line 18 of file sensor_configuration_parser.cpp.
{
        // Parse JSON configuration file
        auto doc = streets_utils::json_utils::parse_json_file(filepath);
        if (!doc.IsArray()) {
            throw streets_utils::json_utils::json_parse_exception("Invadid format for sensor configuration file "  + filepath
                + ". Sensor configuration file should contain an array of json sensor configurations!");
        }
        bool found = false;
        lanelet::BasicPoint3d sensor_location;
        for (auto itr = doc.Begin(); itr != doc.End(); ++itr) {
            // Access the data in the object
            auto sensor_config_id = streets_utils::json_utils::parse_string_member("sensorId",  itr->GetObject(), true ).value();
            if ( sensor_config_id == sensor_id ) {
                found = true;
                auto location = streets_utils::json_utils::parse_object_member("location",  itr->GetObject(), true ).value();
                sensor_location = lanelet::BasicPoint3d{
                    streets_utils::json_utils::parse_double_member("x",  location, true ).value(),
                    streets_utils::json_utils::parse_double_member("y",  location, true ).value(),
                    streets_utils::json_utils::parse_double_member("z",  location, true ).value()
                    };
            }
        }
        if (!found) {
            throw streets_utils::json_utils::json_parse_exception("Did not find sensor with id " + sensor_id + " in sensor configuration file " + filepath + "!");
        }
        return sensor_location;
    }
References streets_utils::json_utils::parse_double_member(), streets_utils::json_utils::parse_json_file(), streets_utils::json_utils::parse_object_member(), and streets_utils::json_utils::parse_string_member().
Referenced by sensor_data_sharing_service::sds_service::initialize().
to_angular_velocity_confidence()
streets_utils::messages::sdsm::angular_velocity_confidence sensor_data_sharing_service::to_angular_velocity_confidence (const double accuracy)
Convert accuracy value to angular velocity confidence enumeration. To minimize error in conversion, method rounds up/down to the nearest enum value.
Parameters
accuracy
Returns
angular velocity confidence
Definition at line 244 of file detected_object_to_sdsm_converter.cpp.
{
         if ( accuracy >= 55) {
            return streets_utils::messages::sdsm::angular_velocity_confidence::DEGSEC_100;
        }
        else if (accuracy >= 7.5) {
            return streets_utils::messages::sdsm::angular_velocity_confidence::DEGSEC_10;
        }
        else if (accuracy >= 3) {
            return streets_utils::messages::sdsm::angular_velocity_confidence::DEGSEC_05;
        }
        else if (accuracy >= .55) {
            return streets_utils::messages::sdsm::angular_velocity_confidence::DEGSEC_01;
        }
        else if (accuracy >= .075) {
            return streets_utils::messages::sdsm::angular_velocity_confidence::DEGSEC_0_1;
        }
        else if (accuracy >= .03) {
            return streets_utils::messages::sdsm::angular_velocity_confidence::DEGSEC_0_05;
        }
        else {
            // This is the lowest speed confidence the SDSM can reflect
            return streets_utils::messages::sdsm::angular_velocity_confidence::DEGSEC_0_01;
        }
    }
References streets_utils::messages::sdsm::DEGSEC_01, streets_utils::messages::sdsm::DEGSEC_05, streets_utils::messages::sdsm::DEGSEC_0_01, streets_utils::messages::sdsm::DEGSEC_0_05, streets_utils::messages::sdsm::DEGSEC_0_1, streets_utils::messages::sdsm::DEGSEC_10, and streets_utils::messages::sdsm::DEGSEC_100.
Referenced by to_yaw_rate_confidence().
to_detected_object_data()
streets_utils::messages::sdsm::detected_object_data sensor_data_sharing_service::to_detected_object_data (const streets_utils::messages::detected_objects_msg::detected_objects_msg & msg)
convert detected_object_msg to sdsm detection_object_data.
Returns
streets_utils::messages::sdsm::detected_object_data.
Definition at line 36 of file detected_object_to_sdsm_converter.cpp.
{
        streets_utils::messages::sdsm::detected_object_data detected_object;
        detected_object._detected_object_common_data._object_type = to_object_type(msg._type);
        if (detected_object._detected_object_common_data._object_type == streets_utils::messages::sdsm::object_type::VEHICLE ) {
            streets_utils::messages::sdsm::detected_vehicle_data optional_data;
            // Size in cm
            streets_utils::messages::sdsm::vehicle_size veh_size;
            veh_size._length= static_cast<unsigned int>(msg._size._length*METERS_TO_CM);
            veh_size._width= static_cast<unsigned int>(msg._size._width*METERS_TO_CM);
            optional_data._size = veh_size;
            // Height in 5 cm
            optional_data._vehicle_height = static_cast<unsigned int>(msg._size._height * METERS_TO_5_CM);
            detected_object._detected_object_optional_data = optional_data;
        }
        else if ( detected_object._detected_object_common_data._object_type == streets_utils::messages::sdsm::object_type::VRU ) {
            streets_utils::messages::sdsm::detected_vru_data optional_data;
            // Populate Optional VRU data
            detected_object._detected_object_optional_data = optional_data;
        }
        else if (detected_object._detected_object_common_data._object_type == streets_utils::messages::sdsm::object_type::UNKNOWN ){
            streets_utils::messages::sdsm::detected_obstacle_data optional_data;
            // size dimensions in units of 0.1 m
            streets_utils::messages::sdsm::obstacle_size obs_size;
            obs_size._length = static_cast<unsigned int>(msg._size._length*METERS_TO_10_CM);
            obs_size._width = static_cast<unsigned int>(msg._size._width*METERS_TO_10_CM);
            obs_size._height = static_cast<unsigned int>(msg._size._height*METERS_TO_10_CM);
            optional_data._size = obs_size;
            detected_object._detected_object_optional_data = optional_data;
        }
        detected_object._detected_object_common_data._classification_confidence = static_cast<unsigned int>(msg._confidence*100);
        // TODO: Change Detected Object ID to int
        detected_object._detected_object_common_data._object_id = msg._object_id;
        // Units are 0.1 m
        detected_object._detected_object_common_data._position_offset._offset_x = static_cast<unsigned int>(msg._position._x*METERS_TO_10_CM);
        detected_object._detected_object_common_data._position_offset._offset_y = static_cast<unsigned int>(msg._position._y*METERS_TO_10_CM);
        detected_object._detected_object_common_data._position_offset._offset_z = static_cast<unsigned int>(msg._position._z*METERS_TO_10_CM);
        // Position Confidence
        detected_object._detected_object_common_data._pos_confidence = to_position_confidence_set(msg._position_covariance);
        // Units are 0.02 m/s
        detected_object._detected_object_common_data._speed = static_cast<unsigned int>(std::hypot( msg._velocity._x* METERS_PER_SECOND_TO_2_CM_PER_SECOND,  msg._velocity._y* METERS_PER_SECOND_TO_2_CM_PER_SECOND));
        // Speed confidence
        detected_object._detected_object_common_data._speed_confidence = to_xy_speed_confidence(msg._velocity_covariance);
        // Speed Z
        detected_object._detected_object_common_data._speed_z = static_cast<unsigned int>(fabs(msg._velocity._z)* METERS_PER_SECOND_TO_2_CM_PER_SECOND);
        // Speed Z confidence
        detected_object._detected_object_common_data._speed_z_confidence = to_z_speed_confidence(msg._velocity_covariance);
        // Heading
        detected_object._detected_object_common_data._heading = to_heading(msg._velocity);
        // TODO: how to calculate heading confidence without orientation covariance
        // Possible approximation is velocity covariance since we are using that currently
        // Currently hard coding value
        detected_object._detected_object_common_data._heading_confidence = streets_utils::messages::sdsm::heading_confidence::PREC_10_deg;
        // Yaw rate
        detected_object._detected_object_common_data._acceleration_4_way->_yaw_rate = to_yaw_rate(msg._angular_velocity._z);
        // Yaw rate confidence
        detected_object._detected_object_common_data._yaw_rate_confidence = to_yaw_rate_confidence(msg._angular_velocity_covariance);
        return detected_object;
    }
References streets_utils::messages::sdsm::detected_object_data_common::_acceleration_4_way, streets_utils::messages::detected_objects_msg::detected_objects_msg::_angular_velocity, streets_utils::messages::detected_objects_msg::detected_objects_msg::_angular_velocity_covariance, streets_utils::messages::sdsm::detected_object_data_common::_classification_confidence, streets_utils::messages::detected_objects_msg::detected_objects_msg::_confidence, streets_utils::messages::sdsm::detected_object_data::_detected_object_common_data, streets_utils::messages::sdsm::detected_object_data::_detected_object_optional_data, streets_utils::messages::sdsm::detected_object_data_common::_heading, streets_utils::messages::sdsm::detected_object_data_common::_heading_confidence, streets_utils::messages::detected_objects_msg::size::_height, streets_utils::messages::sdsm::obstacle_size::_height, streets_utils::messages::detected_objects_msg::size::_length, streets_utils::messages::sdsm::obstacle_size::_length, streets_utils::messages::sdsm::vehicle_size::_length, streets_utils::messages::detected_objects_msg::detected_objects_msg::_object_id, streets_utils::messages::sdsm::detected_object_data_common::_object_id, streets_utils::messages::sdsm::detected_object_data_common::_object_type, streets_utils::messages::sdsm::position_offset::_offset_x, streets_utils::messages::sdsm::position_offset::_offset_y, streets_utils::messages::sdsm::position_offset::_offset_z, streets_utils::messages::sdsm::detected_object_data_common::_pos_confidence, streets_utils::messages::detected_objects_msg::detected_objects_msg::_position, streets_utils::messages::detected_objects_msg::detected_objects_msg::_position_covariance, streets_utils::messages::sdsm::detected_object_data_common::_position_offset, streets_utils::messages::detected_objects_msg::detected_objects_msg::_size, streets_utils::messages::sdsm::detected_obstacle_data::_size, streets_utils::messages::sdsm::detected_vehicle_data::_size, streets_utils::messages::sdsm::detected_object_data_common::_speed, streets_utils::messages::sdsm::detected_object_data_common::_speed_confidence, streets_utils::messages::sdsm::detected_object_data_common::_speed_z, streets_utils::messages::sdsm::detected_object_data_common::_speed_z_confidence, streets_utils::messages::detected_objects_msg::detected_objects_msg::_type, streets_utils::messages::sdsm::detected_vehicle_data::_vehicle_height, streets_utils::messages::detected_objects_msg::detected_objects_msg::_velocity, streets_utils::messages::detected_objects_msg::detected_objects_msg::_velocity_covariance, streets_utils::messages::detected_objects_msg::size::_width, streets_utils::messages::sdsm::obstacle_size::_width, streets_utils::messages::sdsm::vehicle_size::_width, streets_utils::messages::detected_objects_msg::cartesian_point::_x, streets_utils::messages::detected_objects_msg::vector_3d::_x, streets_utils::messages::detected_objects_msg::cartesian_point::_y, streets_utils::messages::detected_objects_msg::vector_3d::_y, streets_utils::messages::sdsm::detected_object_data_common::_yaw_rate_confidence, streets_utils::messages::detected_objects_msg::cartesian_point::_z, streets_utils::messages::detected_objects_msg::vector_3d::_z, METERS_PER_SECOND_TO_2_CM_PER_SECOND, METERS_TO_10_CM, METERS_TO_5_CM, METERS_TO_CM, streets_utils::messages::sdsm::PREC_10_deg, to_heading(), to_object_type(), to_position_confidence_set(), to_xy_speed_confidence(), to_yaw_rate(), to_yaw_rate_confidence(), to_z_speed_confidence(), streets_utils::messages::sdsm::UNKNOWN, streets_utils::messages::sdsm::VEHICLE, and streets_utils::messages::sdsm::VRU.
Referenced by sensor_data_sharing_service::sds_service::create_sdsm().
to_heading()
unsigned int sensor_data_sharing_service::to_heading (const streets_utils::messages::detected_objects_msg::vector_3d & velocity)
Convert XY velocity into 2 dimensional heading measured in 0.0125 degree units.
Parameters
velocity vector of velocity
Returns
2 dimensional heading in units of 0.0125 degrees
Definition at line 176 of file detected_object_to_sdsm_converter.cpp.
{
        auto heading_radians = std::atan2(velocity._y,velocity._x);
        auto heading_degrees = heading_radians*(180/M_PI);
        // If angle is negative 360 + (-negative angle)
        if ( heading_degrees < 0 ) {
            heading_degrees = 360 + heading_degrees;
        }
        // in units (x)  = 0.0125 degrees
        // 28800 x = 360 degrees
        return static_cast<unsigned int>(heading_degrees * (28800/360));
    }
References streets_utils::messages::detected_objects_msg::vector_3d::_x, and streets_utils::messages::detected_objects_msg::vector_3d::_y.
Referenced by to_detected_object_data().
to_object_type()
streets_utils::messages::sdsm::object_type sensor_data_sharing_service::to_object_type (const std::string & detection_type)
convert string detection type to sdsm object_type.
Parameters
detection_type string detection classification for detection message.
Returns
streets_utils::messages::sdsm::object_type
Definition at line 101 of file detected_object_to_sdsm_converter.cpp.
{
        if ( sdsm_object_types.find(detection_type) != sdsm_object_types.end()) {
            return sdsm_object_types.at(detection_type);
        }
        return streets_utils::messages::sdsm::object_type::UNKNOWN;
    }
References sdsm_object_types, and streets_utils::messages::sdsm::UNKNOWN.
Referenced by to_detected_object_data().
to_position_3d()
streets_utils::messages::sdsm::position_3d sensor_data_sharing_service::to_position_3d (const lanelet::GPSPoint & ref_position)
Definition at line 177 of file sensor_data_sharing_service.cpp.
{
        streets_utils::messages::sdsm::position_3d position;
        // Convert to 1/10 of microdegrees
        position._longitude = static_cast<int>(ref_position.lon * 1e7);
        position._latitude = static_cast<int>(ref_position.lat *1e7);
        // Convert 0.1 meters
        position._elevation = static_cast<int>(ref_position.ele * 10);
        return position;
    }
References streets_utils::messages::sdsm::position_3d::_elevation, streets_utils::messages::sdsm::position_3d::_latitude, and streets_utils::messages::sdsm::position_3d::_longitude.
Referenced by sensor_data_sharing_service::sds_service::create_sdsm().
to_position_confidence()
streets_utils::messages::sdsm::position_confidence sensor_data_sharing_service::to_position_confidence (const double accuracy)
Convert accuracy value to position confidence enumeration. To minimize error in conversion, method rounds up/down to the nearest enum value.
Parameters
accuracy
Returns
position confidence enumeration
Definition at line 125 of file detected_object_to_sdsm_converter.cpp.
{
        // Check to see if accuracy is greater than or equal to half way between to confidence enumeration
        if ( accuracy >= 350) {
            return streets_utils::messages::sdsm::position_confidence::A_500M;
        }
        else if (accuracy >= 150) {
            return streets_utils::messages::sdsm::position_confidence::A_200M;
        }
        else if (accuracy >= 75) {
            return streets_utils::messages::sdsm::position_confidence::A_100M;
        }
        else if (accuracy >= 35) {
            return streets_utils::messages::sdsm::position_confidence::A_50M;
        }
        else if (accuracy >= 15) {
            return streets_utils::messages::sdsm::position_confidence::A_20M;
        }
        else if (accuracy >= 7.5) {
            return streets_utils::messages::sdsm::position_confidence::A_10M;
        }
        else if (accuracy >= 3.5) {
            return streets_utils::messages::sdsm::position_confidence::A_5M;
        }
        else if (accuracy >= 1.5) {
            return streets_utils::messages::sdsm::position_confidence::A_2M;
        }
        else if (accuracy >= 0.75) {
            return streets_utils::messages::sdsm::position_confidence::A_1M;
        }
        else if (accuracy >= 0.35) {
            return streets_utils::messages::sdsm::position_confidence::A_50CM;
        }
        else if (accuracy >= 0.15) {
            return streets_utils::messages::sdsm::position_confidence::A_20CM;
        }
        else if (accuracy >= 0.075) {
            return streets_utils::messages::sdsm::position_confidence::A_10CM;
        }
        else if (accuracy >= 0.035) {
            return streets_utils::messages::sdsm::position_confidence::A_5CM;
        }
        else if (accuracy >= 0.015) {
            return streets_utils::messages::sdsm::position_confidence::A_2CM;
        }
        else {
            // This is the lowest position confidence the SDSM can reflect
            return streets_utils::messages::sdsm::position_confidence::A_1CM;
        }
    }
References streets_utils::messages::sdsm::A_100M, streets_utils::messages::sdsm::A_10CM, streets_utils::messages::sdsm::A_10M, streets_utils::messages::sdsm::A_1CM, streets_utils::messages::sdsm::A_1M, streets_utils::messages::sdsm::A_200M, streets_utils::messages::sdsm::A_20CM, streets_utils::messages::sdsm::A_20M, streets_utils::messages::sdsm::A_2CM, streets_utils::messages::sdsm::A_2M, streets_utils::messages::sdsm::A_500M, streets_utils::messages::sdsm::A_50CM, streets_utils::messages::sdsm::A_50M, streets_utils::messages::sdsm::A_5CM, and streets_utils::messages::sdsm::A_5M.
Referenced by to_position_confidence_set().
to_position_confidence_set()
streets_utils::messages::sdsm::position_confidence_set sensor_data_sharing_service::to_position_confidence_set (const std::vector< std::vector< double > > & _position_covariance)
Convert position covariance to position confidence set which includes positionXY confidence and position z confidence.
Parameters
_position_covariance
Returns
position confidence set.
Definition at line 108 of file detected_object_to_sdsm_converter.cpp.
{
        auto x_variance = _position_covariance[0][0];
        auto y_variance = _position_covariance[1][1];
        auto z_variance = _position_covariance[2][2];
        // Assuming normal distribution and 95 % confidence interval (From J3224 Specification documentation of all accuracy/confidence measures)
        // +/- 2*variance to achieve 95% confidence interval.
        // TODO: If position variance x is different from y how do we handle this? For now assuming X variance is the same as Y and justing using
        // X
        // Multiply variance by 2 get 95% confidence interval for normal distribution
        auto xy_accuracy = sqrt(x_variance) * 2 ;
        auto z_accuracy = sqrt(z_variance) * 2;
        streets_utils::messages::sdsm::position_confidence_set position_confidence_set;
        position_confidence_set._position_confidence =  to_position_confidence(xy_accuracy);
        position_confidence_set._elevation_confidence = to_position_confidence(z_accuracy);
        return position_confidence_set;
    }
References streets_utils::messages::sdsm::position_confidence_set::_elevation_confidence, streets_utils::messages::sdsm::position_confidence_set::_position_confidence, and to_position_confidence().
Referenced by to_detected_object_data().
to_sdsm_timestamp()
streets_utils::messages::sdsm::time_stamp sensor_data_sharing_service::to_sdsm_timestamp (const uint64_t _epoch_time_ms)
convert epoch millisecond timestamp to sdsm timestamp object
Returns
streets_utils::messages::sdsm::time_stamp.
Definition at line 18 of file detected_object_to_sdsm_converter.cpp.
{
        streets_utils::messages::sdsm::time_stamp sdsm_timestamp;
        // From millisecond time stamp
        boost::posix_time::ptime posix_time = boost::posix_time::from_time_t(_epoch_time_ms/SECONDS_TO_MILLISECONDS) +
                                        boost::posix_time::millisec( _epoch_time_ms % SECONDS_TO_MILLISECONDS);
        sdsm_timestamp.year = posix_time.date().year();
        sdsm_timestamp.month = posix_time.date().month();
        sdsm_timestamp.day = posix_time.date().day();
        sdsm_timestamp.hour = (unsigned int) posix_time.time_of_day().hours();
        sdsm_timestamp.minute = (unsigned int) posix_time.time_of_day().minutes();
        // Milliseconds of the current minute. The SDSM field is named seconds but is in the unit of milliseconds (see DDateTime from J2735).
        // Fractional_seconds returns microseconds from the current second since default time resolution is microseconds
        sdsm_timestamp.second = (unsigned int) (posix_time.time_of_day().seconds()*SECONDS_TO_MILLISECONDS + posix_time.time_of_day().fractional_seconds()/MILLISECONDS_TO_MICROSECONDS);
        return sdsm_timestamp;
    }
References streets_utils::messages::sdsm::time_stamp::day, streets_utils::messages::sdsm::time_stamp::hour, MILLISECONDS_TO_MICROSECONDS, streets_utils::messages::sdsm::time_stamp::minute, streets_utils::messages::sdsm::time_stamp::month, streets_utils::messages::sdsm::time_stamp::second, SECONDS_TO_MILLISECONDS, and streets_utils::messages::sdsm::time_stamp::year.
Referenced by sensor_data_sharing_service::sds_service::create_sdsm().
to_speed_confidence()
streets_utils::messages::sdsm::speed_confidence sensor_data_sharing_service::to_speed_confidence (const double accuracy)
Convert accuracy value to speed confidence enumeration. To minimize error in conversion, method rounds up/down to the nearest enum value.
Parameters
accuracy
Returns
speed confidence enumeration
Definition at line 210 of file detected_object_to_sdsm_converter.cpp.
{
         // Check to see if accuracy is greater than or equal to half way between to confidence enumeration
        if ( accuracy >= 55) {
            return streets_utils::messages::sdsm::speed_confidence::PREC_100ms;
        }
        else if (accuracy >= 7.5) {
            return streets_utils::messages::sdsm::speed_confidence::PREC_10ms;
        }
        else if (accuracy >= 3) {
            return streets_utils::messages::sdsm::speed_confidence::PREC_5ms;
        }
        else if (accuracy >= .55) {
            return streets_utils::messages::sdsm::speed_confidence::PREC_1ms;
        }
        else if (accuracy >= .075) {
            return streets_utils::messages::sdsm::speed_confidence::PREC_0_1ms;
        }
        else if (accuracy >= .03) {
            return streets_utils::messages::sdsm::speed_confidence::PREC_0_05ms;
        }
        else {
            // This is the lowest speed confidence the SDSM can reflect
            return streets_utils::messages::sdsm::speed_confidence::PREC_0_01ms;
        }
    }
References streets_utils::messages::sdsm::PREC_0_01ms, streets_utils::messages::sdsm::PREC_0_05ms, streets_utils::messages::sdsm::PREC_0_1ms, streets_utils::messages::sdsm::PREC_100ms, streets_utils::messages::sdsm::PREC_10ms, streets_utils::messages::sdsm::PREC_1ms, and streets_utils::messages::sdsm::PREC_5ms.
Referenced by to_xy_speed_confidence(), and to_z_speed_confidence().
to_xy_speed_confidence()
streets_utils::messages::sdsm::speed_confidence sensor_data_sharing_service::to_xy_speed_confidence (const std::vector< std::vector< double > > & velocity_covariance)
Convert velocity covariance to xy speed confidence.
Parameters
velocity_covariance
Returns
xy speed confidence
Definition at line 188 of file detected_object_to_sdsm_converter.cpp.
{
        auto x_variance = velocity_covariance[0][0];
        auto y_variance = velocity_covariance[1][1];
        // Assuming normal distribution and 95 % confidence interval (From J3224 Specification documentation of all accuracy/confidence measures)
        // +/- 2*variance to achieve 95% confidence interval.
        // TODO: If position variance x is different from y how do we handle this? For now assuming X variance is the same as Y and justing using
        // X
        // Multiply variance by 2 get 95% confidence interval for normal distribution
        auto xy_accuracy = sqrt(x_variance) * 2 ;
        return to_speed_confidence(xy_accuracy);
    }
References to_speed_confidence().
Referenced by to_detected_object_data().
to_yaw_rate()
int sensor_data_sharing_service::to_yaw_rate (const double yaw_rate_radians_per_second)
Convert yaw rate in radians per second to 100ths of a degree per second.
Parameters
yaw_rate_radians_per_second
Returns
yaw rate in 0.01 degrees/second.
Definition at line 269 of file detected_object_to_sdsm_converter.cpp.
{
        // Return in units of 0.01 degrees per second;
        return static_cast<int>( yaw_rate_radians_per_second * (180/(M_PI)) * 100);
    }
Referenced by to_detected_object_data().
to_yaw_rate_confidence()
streets_utils::messages::sdsm::angular_velocity_confidence sensor_data_sharing_service::to_yaw_rate_confidence (const std::vector< std::vector< double > > & angular_velocity_covariance)
Convert angular velocity covariance to angular velocity confidence.
Parameters
angular_velocity_covariance
Returns
angular velocity confidence
Definition at line 237 of file detected_object_to_sdsm_converter.cpp.
{
        auto z_variance = angular_velocity_covariance[2][2];
        auto z_accuracy = sqrt(z_variance) * 2 ;
        return to_angular_velocity_confidence(z_accuracy);
    }
References to_angular_velocity_confidence().
Referenced by to_detected_object_data().
to_z_speed_confidence()
streets_utils::messages::sdsm::speed_confidence sensor_data_sharing_service::to_z_speed_confidence (const std::vector< std::vector< double > > & velocity_covariance)
Convert velocity covariance to z speed confidence.
Parameters
velocity_covariance
Returns
z speed confidence
Definition at line 200 of file detected_object_to_sdsm_converter.cpp.
{
        auto z_variance = velocity_covariance[2][2];
        // Assuming normal distribution and 95 % confidence interval (From J3224 Specification documentation of all accuracy/confidence measures)
        // +/- 2*variance to achieve 95% confidence interval.
        // Multiply variance by 2 get 95% confidence interval for normal distribution
        auto z_accuracy = sqrt(z_variance) * 2 ;
        return to_speed_confidence(z_accuracy);
    }
References to_speed_confidence().
Referenced by to_detected_object_data().
Variable Documentation
METERS_PER_SECOND_TO_2_CM_PER_SECOND
const int sensor_data_sharing_service::METERS_PER_SECOND_TO_2_CM_PER_SECOND = 50 inline
Definition at line 47 of file detected_object_to_sdsm_converter.hpp.
Referenced by to_detected_object_data().
METERS_TO_10_CM
const int sensor_data_sharing_service::METERS_TO_10_CM = 10 inline
Definition at line 45 of file detected_object_to_sdsm_converter.hpp.
Referenced by to_detected_object_data().
METERS_TO_5_CM
const int sensor_data_sharing_service::METERS_TO_5_CM = 20 inline
Definition at line 43 of file detected_object_to_sdsm_converter.hpp.
Referenced by to_detected_object_data().
METERS_TO_CM
const int sensor_data_sharing_service::METERS_TO_CM = 100 inline
Definition at line 41 of file detected_object_to_sdsm_converter.hpp.
Referenced by to_detected_object_data().
MILLISECONDS_TO_MICROSECONDS
const int sensor_data_sharing_service::MILLISECONDS_TO_MICROSECONDS = 1000 inline
Definition at line 37 of file detected_object_to_sdsm_converter.hpp.
Referenced by to_sdsm_timestamp().
sdsm_object_types
const std::map<std::string, streets_utils::messages::sdsm::object_type, std::less<> > sensor_data_sharing_service::sdsm_object_types inline
Initial value:
= {
        {"CAR",streets_utils::messages::sdsm::object_type::VEHICLE },
        {"VAN",streets_utils::messages::sdsm::object_type::VEHICLE },
        {"TRUCK",streets_utils::messages::sdsm::object_type::VEHICLE },
        {"PEDESTRIAN",streets_utils::messages::sdsm::object_type::VRU },
        {"CYCLIST",streets_utils::messages::sdsm::object_type::VRU },
        {"MOTORCYCLE",streets_utils::messages::sdsm::object_type::VRU },
    }
Map of detection types to SDSM object types.
Definition at line 28 of file detected_object_to_sdsm_converter.hpp.
Referenced by to_object_type().
SECONDS_TO_MILLISECONDS
const int sensor_data_sharing_service::SECONDS_TO_MILLISECONDS = 1000 inline
Definition at line 39 of file detected_object_to_sdsm_converter.hpp.
Referenced by to_sdsm_timestamp().