Carma-streets: streets_utils/streets_signal_phase_and_timing/include/ntcip_1202_ext.h File Reference
ntcip_1202_ext.h File Reference
#include <netinet/in.h>
#include <iostream>
#include <sstream>
#include <bitset>
#include "ntcip_1202_ext_phasetime.h"
#include "signal_phase_and_timing_exception.h"
Classes
struct ntcip::ntcip_1202_ext
Namespaces
namespace ntcip
Functions
struct ntcip::ntcip_1202_ext ntcip::__attribute__ ((packed))
bool get_phase_red_status (const int phase_number) const
Returns red state of phase.
bool get_phase_yellow_status (const int phase_number) const
Returns yellow state of phase.
bool get_phase_green_status (const int phase_number) const
Returns green state of phase.
bool get_phase_dont_walk (const int phase_number) const
Returns dont walk state of phase. Only applies to pedestrian phases.
bool get_phase_ped_clear (const int phase_number) const
Returns pedestrian clear state of phase. Only applies to pedestrian phases.
bool get_phase_walk (const int phase_number) const
Returns walk state of phase. Only applies to pedestrian phases.
bool get_overlap_red_status (const int phase_number) const
Returns red overlap state of phase.
bool get_overlap_yellow_status (const int phase_number) const
Returns yellow overlap state of phase.
bool get_overlap_green_status (const int phase_number) const
Returns green overlap state of phase.
bool get_phase_flashing_status (const int phase_number) const
Returns flashing state of phase.
bool get_overlap_flashing_status (const int phase_number) const
Returns flashing state of overlap phase.
bool get_spat_pedestrian_call (const int phase_number) const
Returns state of pedestrian calls on phase.
bool get_spat_pedestrian_detect (const int phase_number) const
Returns state of pedestrian detect on phase.
uint32_t get_timestamp_seconds_of_day () const
Returns 3 bytes translated into seconds of the UTC day message timestamp.
ntcip_1202_ext_phasetime & get_phasetime (const int phase_number)
Returns reference to ntcip_1202_ext_phasetime of phase.
std::string to_string () const
Returns std::string representation of ntcip_1202_ext message including phase_times array.
Variables
int8_t header = 0
header
int8_t num_of_phases = 0
number of phases
ntcip_1202_ext_phasetime phase_times [16]
phase_time object for each phase
uint16_t phase_status_group_reds = 0
int where each bit indicates whether that phase is red (1-16)
uint16_t phase_status_group_yellows = 0
int where each bit indicates whether that phase is yellow (1-16)
uint16_t phase_status_group_greens = 0
int where each bit indicates whether that phase is green (1-16)
uint16_t phase_status_group_dont_walks = 0
int where each bit indicates whether that phase is dont walk (Pedestrian Phases) (1-16)
uint16_t phase_status_group_ped_clears = 0
int where each bit indicates whether that phase is pedestrian clear (Pedestrian Phases) (1-16)
uint16_t phase_status_group_walks = 0
int where each bit indicates whether that phase is walk (Pedestrian Phases) (1-16)
uint16_t overlap_status_group_reds = 0
int where each bit indicates whether that overlap is red (1-16)
uint16_t overlap_status_group_yellows = 0
int where each bit indicates whether that overlap is yellow (1-16)
uint16_t overlap_status_group_greens = 0
int where each bit indicates whether that overlap is green (1-16)
uint16_t flashing_output_phase_status = 0
int where each bit indicates whether that phase is flashing (1-16)
uint16_t flashing_output_overlap_status = 0
int where each bit indicates whether that overlap is flashing (1-16)
uint8_t spat_intersection_status = 0
bit string for intersection status
uint8_t timebase_asc_action_status = 0
current action plan
uint8_t spat_discontinuous_change_flag = 0
upper 5 bits are msg version
uint8_t spat_message_seq_counter = 0
lower byte of up-time in deciseconds
u_char spat_timestamp_second_byte1 = 0
u_char spat_timestamp_second_byte2 = 0
u_char spat_timestamp_second_byte3 = 0
uint16_t spat_timestamp_msec = 0
milliseconds of current second
uint16_t spat_pedestrian_call = 0
int where each bit indicates whether there is a pedestrian call on a phase (Pedestrian Phases) (1-16)
uint16_t spat_pedestrian_detect = 0
int where each bit indicates whether there is a pedestrian detect on a phase (Pedestrian Phases) (1-16)
Function Documentation
get_overlap_flashing_status()
bool __attribute__::get_overlap_flashing_status (const int phase_number) const
Returns flashing state of overlap phase.
Parameters
phase_number
Returns
true
false
get_overlap_green_status()
bool __attribute__::get_overlap_green_status (const int phase_number) const
Returns green overlap state of phase.
Parameters
phase_number
Returns
true
false
get_overlap_red_status()
bool __attribute__::get_overlap_red_status (const int phase_number) const
Returns red overlap state of phase.
Parameters
phase_number
Returns
true
false
get_overlap_yellow_status()
bool __attribute__::get_overlap_yellow_status (const int phase_number) const
Returns yellow overlap state of phase.
Parameters
phase_number
Returns
true
false
get_phase_dont_walk()
bool __attribute__::get_phase_dont_walk (const int phase_number) const
Returns dont walk state of phase. Only applies to pedestrian phases.
Parameters
phase_number of phase.
Returns
true if phase is dont walk.
false if phase is not dont walk.
get_phase_flashing_status()
bool __attribute__::get_phase_flashing_status (const int phase_number) const
Returns flashing state of phase.
Parameters
phase_number of phase.
Returns
true if phase is flashing.
false if phase is not flashing.
get_phase_green_status()
bool __attribute__::get_phase_green_status (const int phase_number) const
Returns green state of phase.
Parameters
phase_number of phase.
Returns
true if phase is green.
false if phase is not green.
get_phase_ped_clear()
bool __attribute__::get_phase_ped_clear (const int phase_number) const
Returns pedestrian clear state of phase. Only applies to pedestrian phases.
Parameters
phase_number of phase.
Returns
true if phase is pedestrian clear.
false if phase is not pedestrian clear.
get_phase_red_status()
bool __attribute__::get_phase_red_status (const int phase_number) const
Returns red state of phase.
Parameters
phase_number of phase.
Returns
true if phase is red.
false if phase is not red.
get_phase_walk()
bool __attribute__::get_phase_walk (const int phase_number) const
Returns walk state of phase. Only applies to pedestrian phases.
Parameters
phase_number of phase/
Returns
true if phase is walk.
false if phase is not walk.
get_phase_yellow_status()
bool __attribute__::get_phase_yellow_status (const int phase_number) const
Returns yellow state of phase.
Parameters
phase_number of phase.
Returns
true if phase is yellow.
false if phase is not yellow.
get_phasetime()
ntcip_1202_ext_phasetime & __attribute__::get_phasetime (const int phase_number)
Returns reference to ntcip_1202_ext_phasetime of phase.
Parameters
phase_number of phase
Returns
ntcip_1202_ext_phasetime&
get_spat_pedestrian_call()
bool __attribute__::get_spat_pedestrian_call (const int phase_number) const
Returns state of pedestrian calls on phase.
Parameters
phase_number
Returns
true
false
get_spat_pedestrian_detect()
bool __attribute__::get_spat_pedestrian_detect (const int phase_number) const
Returns state of pedestrian detect on phase.
Parameters
phase_number
Returns
true
false
get_timestamp_seconds_of_day()
uint32_t __attribute__::get_timestamp_seconds_of_day () const
Returns 3 bytes translated into seconds of the UTC day message timestamp.
Returns
uint32_t message timestamp in seconds of UTC day
to_string()
std::string __attribute__::to_string () const
Returns std::string representation of ntcip_1202_ext message including phase_times array.
Returns
std::string
Referenced by traffic_signal_controller_service::snmp_client::snmp_client(), traffic_signal_controller_service::tsc_state::add_future_movement_events(), message_services::models::bsm::asJsonObject(), streets_signal_optimization::streets_desired_phase_plan_generator::convert_spat_to_dpp(), streets_signal_optimization::streets_desired_phase_plan_arbitrator::dpp_delay_toCSV(), streets_signal_optimization::streets_desired_phase_plan_generator::find_signal_group_for_entry_lane(), streets_signal_optimization::streets_desired_phase_plan_generator::find_tbd_start_time(), streets_service::configuration::fromJson(), traffic_signal_controller_service::tsc_state::get_active_ring_sequences(), traffic_signal_controller_service::tsc_state::get_channels(), traffic_signal_controller_service::tsc_state::get_concurrent_signal_groups(), streets_vehicle_scheduler::vehicle_scheduler::get_entry_lanelet_info(), traffic_signal_controller_service::tsc_state::get_following_event(), streets_vehicle_scheduler::vehicle_scheduler::get_link_lanelet_info(), traffic_signal_controller_service::tsc_state::get_max_green(), traffic_signal_controller_service::tsc_state::get_min_green(), signal_phase_and_timing::intersection_state::get_movement(), traffic_signal_controller_service::tsc_state::get_phase_number(), traffic_signal_controller_service::tsc_state::get_phases_associated_with_channel(), ntcip::ntcip_1202_ext::get_phasetime(), traffic_signal_controller_service::tsc_state::get_red_clearance(), traffic_signal_controller_service::tsc_state::get_vehicle_signal_group_id(), traffic_signal_controller_service::tsc_state::get_yellow_duration(), traffic_signal_controller_service::udp_socket_listener::initialize(), traffic_signal_controller_service::snmp_client::process_snmp_request(), streets_vehicles::all_stop_status_intent_processor::read_est_path(), streets_vehicles::all_stop_status_intent_processor::read_metadata(), traffic_signal_controller_service::udp_socket_listener::receive(), streets_vehicle_scheduler::st_comparator(), ntcip::ntcip_1202_ext::to_string(), ntcip::ntcip_1202_ext_phasetime::to_string(), streets_vehicle_scheduler::all_stop_intersection_schedule::toCSV(), streets_vehicle_scheduler::signalized_intersection_schedule::toCSV(), signal_phase_and_timing::time_change_details::toJson(), signal_phase_and_timing::spat::update_spat_with_candidate_dpp(), and streets_signal_optimization::streets_desired_phase_plan_generator::verify_movement_group_list().
Variable Documentation
flashing_output_overlap_status
uint16_t flashing_output_overlap_status = 0
int where each bit indicates whether that overlap is flashing (1-16)
Definition at line 27 of file ntcip_1202_ext.h.
flashing_output_phase_status
uint16_t flashing_output_phase_status = 0
int where each bit indicates whether that phase is flashing (1-16)
Definition at line 25 of file ntcip_1202_ext.h.
header
int8_t header = 0
header
Definition at line 1 of file ntcip_1202_ext.h.
num_of_phases
int8_t num_of_phases = 0
number of phases
Definition at line 3 of file ntcip_1202_ext.h.
overlap_status_group_greens
uint16_t overlap_status_group_greens = 0
int where each bit indicates whether that overlap is green (1-16)
Definition at line 23 of file ntcip_1202_ext.h.
overlap_status_group_reds
uint16_t overlap_status_group_reds = 0
int where each bit indicates whether that overlap is red (1-16)
Definition at line 19 of file ntcip_1202_ext.h.
overlap_status_group_yellows
uint16_t overlap_status_group_yellows = 0
int where each bit indicates whether that overlap is yellow (1-16)
Definition at line 21 of file ntcip_1202_ext.h.
phase_status_group_dont_walks
uint16_t phase_status_group_dont_walks = 0
int where each bit indicates whether that phase is dont walk (Pedestrian Phases) (1-16)
Definition at line 13 of file ntcip_1202_ext.h.
phase_status_group_greens
uint16_t phase_status_group_greens = 0
int where each bit indicates whether that phase is green (1-16)
Definition at line 11 of file ntcip_1202_ext.h.
phase_status_group_ped_clears
uint16_t phase_status_group_ped_clears = 0
int where each bit indicates whether that phase is pedestrian clear (Pedestrian Phases) (1-16)
Definition at line 15 of file ntcip_1202_ext.h.
phase_status_group_reds
uint16_t phase_status_group_reds = 0
int where each bit indicates whether that phase is red (1-16)
Definition at line 7 of file ntcip_1202_ext.h.
phase_status_group_walks
uint16_t phase_status_group_walks = 0
int where each bit indicates whether that phase is walk (Pedestrian Phases) (1-16)
Definition at line 17 of file ntcip_1202_ext.h.
phase_status_group_yellows
uint16_t phase_status_group_yellows = 0
int where each bit indicates whether that phase is yellow (1-16)
Definition at line 9 of file ntcip_1202_ext.h.
phase_times
ntcip_1202_ext_phasetime phase_times[16]
phase_time object for each phase
Definition at line 5 of file ntcip_1202_ext.h.
spat_discontinuous_change_flag
uint8_t spat_discontinuous_change_flag = 0
upper 5 bits are msg version
Definition at line 33 of file ntcip_1202_ext.h.
spat_intersection_status
uint8_t spat_intersection_status = 0
bit string for intersection status
Definition at line 29 of file ntcip_1202_ext.h.
spat_message_seq_counter
uint8_t spat_message_seq_counter = 0
lower byte of up-time in deciseconds
Definition at line 35 of file ntcip_1202_ext.h.
spat_pedestrian_call
uint16_t spat_pedestrian_call = 0
int where each bit indicates whether there is a pedestrian call on a phase (Pedestrian Phases) (1-16)
Definition at line 43 of file ntcip_1202_ext.h.
spat_pedestrian_detect
uint16_t spat_pedestrian_detect = 0
int where each bit indicates whether there is a pedestrian detect on a phase (Pedestrian Phases) (1-16)
Definition at line 45 of file ntcip_1202_ext.h.
spat_timestamp_msec
uint16_t spat_timestamp_msec = 0
milliseconds of current second
Definition at line 41 of file ntcip_1202_ext.h.
spat_timestamp_second_byte1
u_char spat_timestamp_second_byte1 = 0
3 bytes for second of the UTC day
Definition at line 37 of file ntcip_1202_ext.h.
spat_timestamp_second_byte2
u_char spat_timestamp_second_byte2 = 0
Definition at line 38 of file ntcip_1202_ext.h.
spat_timestamp_second_byte3
u_char spat_timestamp_second_byte3 = 0
Definition at line 39 of file ntcip_1202_ext.h.
timebase_asc_action_status
uint8_t timebase_asc_action_status = 0
current action plan
Definition at line 31 of file ntcip_1202_ext.h.