Carma-streets: streets_phase_control_schedule::streets_phase_control_command Struct Reference
streets_phase_control_schedule::streets_phase_control_command Struct Reference
This struct provides command information received from MMITSS. (https://github.com/mmitss/mmitss-az/tree/master/src/mrp/traffic-controller-interface). The command will be translated into carma-streets snmp_command structure and sent to the Traffic signal controller.
#include <streets_phase_control_command.h>
Public Member Functions
streets_phase_control_command ()=default
streets_phase_control_command (const std::string &command_type_str, int command_phase, uint64_t command_start_time, uint64_t command_end_time)
void set_command_type (const std::string &command_type_str)
Set the command type variable.
~streets_phase_control_command ()=default
std::string COMMAND_TYPE_to_string (COMMAND_TYPE command_type) noexcept
Public Attributes
COMMAND_TYPE command_type
int command_phase = 0
uint64_t command_start_time = 0
uint64_t command_end_time = 0
Friends
std::ostream & operator<< (std::ostream &os, const streets_phase_control_command &command)
Detailed Description
This struct provides command information received from MMITSS. (https://github.com/mmitss/mmitss-az/tree/master/src/mrp/traffic-controller-interface). The command will be translated into carma-streets snmp_command structure and sent to the Traffic signal controller.
Definition at line 25 of file streets_phase_control_command.h.
Constructor & Destructor Documentation
streets_phase_control_command() [1/2]
streets_phase_control_schedule::streets_phase_control_command::streets_phase_control_command () default
streets_phase_control_command() [2/2]
streets_phase_control_schedule::streets_phase_control_command::streets_phase_control_command (const std::string & command_type_str, int command_phase, uint64_t command_start_time, uint64_t command_end_time)
Definition at line 6 of file streets_phase_control_command.cpp.
        : command_phase(phase), command_start_time(start_time), command_end_time(end_time)
    {
        set_command_type(command_type_str);
    }
References set_command_type().
~streets_phase_control_command()
streets_phase_control_schedule::streets_phase_control_command::~streets_phase_control_command () default
Member Function Documentation
COMMAND_TYPE_to_string()
std::string streets_phase_control_schedule::streets_phase_control_command::COMMAND_TYPE_to_string (COMMAND_TYPE command_type) noexcept
Definition at line 74 of file streets_phase_control_command.cpp.
    {
        std::string command_type_str;
        switch (command_type)
        {
        case streets_phase_control_schedule::COMMAND_TYPE::CALL_VEH_PHASES:
            command_type_str = "call_veh";
            break;
        case streets_phase_control_schedule::COMMAND_TYPE::CALL_PED_PHASES:
            command_type_str = "call_ped";
            break;
        case streets_phase_control_schedule::COMMAND_TYPE::FORCEOFF_PHASES:
            command_type_str = "forceoff";
            break;
        case streets_phase_control_schedule::COMMAND_TYPE::HOLD_VEH_PHASES:
            command_type_str = "hold";
            break;
        case streets_phase_control_schedule::COMMAND_TYPE::OMIT_VEH_PHASES:
            command_type_str = "omit_veh";
            break;
        case streets_phase_control_schedule::COMMAND_TYPE::OMIT_PED_PHASES:
            command_type_str = "omit_ped";
            break;
        }
        return command_type_str;
    }
References streets_phase_control_schedule::CALL_PED_PHASES, streets_phase_control_schedule::CALL_VEH_PHASES, streets_phase_control_schedule::FORCEOFF_PHASES, streets_phase_control_schedule::HOLD_VEH_PHASES, streets_phase_control_schedule::OMIT_PED_PHASES, and streets_phase_control_schedule::OMIT_VEH_PHASES.
Referenced by streets_snmp_cmd::streets_snmp_cmd_converter::print_two_dimension_map().
set_command_type()
void streets_phase_control_schedule::streets_phase_control_command::set_command_type (const std::string & command_type_str)
Set the command type variable.
Parameters
string command type in string format
Definition at line 12 of file streets_phase_control_command.cpp.
    {
        if (command_type_str == "call_veh")
        {
            command_type = COMMAND_TYPE::CALL_VEH_PHASES;
        }
        else if (command_type_str == "call_ped")
        {
            command_type = COMMAND_TYPE::CALL_PED_PHASES;
        }
        else if (command_type_str == "forceoff")
        {
            command_type = COMMAND_TYPE::FORCEOFF_PHASES;
        }
        else if (command_type_str == "hold")
        {
            command_type = COMMAND_TYPE::HOLD_VEH_PHASES;
        }
        else if (command_type_str == "omit_veh")
        {
            command_type = COMMAND_TYPE::OMIT_VEH_PHASES;
        }
        else if (command_type_str == "omit_ped")
        {
            command_type = COMMAND_TYPE::OMIT_PED_PHASES;
        }
        else
        {
            throw streets_phase_control_schedule::streets_phase_control_schedule_exception("Invalid command type");
        }
    }
References streets_phase_control_schedule::CALL_PED_PHASES, streets_phase_control_schedule::CALL_VEH_PHASES, command_type, streets_phase_control_schedule::FORCEOFF_PHASES, streets_phase_control_schedule::HOLD_VEH_PHASES, streets_phase_control_schedule::OMIT_PED_PHASES, and streets_phase_control_schedule::OMIT_VEH_PHASES.
Referenced by streets_phase_control_command().
Friends And Related Function Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const streets_phase_control_command & command) friend
Definition at line 44 of file streets_phase_control_command.cpp.
    {
        std::string command_type_str;
        switch (command.command_type)
        {
        case COMMAND_TYPE::CALL_VEH_PHASES:
            command_type_str = "call_veh";
            break;
        case COMMAND_TYPE::CALL_PED_PHASES:
            command_type_str = "call_ped";
            break;
        case COMMAND_TYPE::FORCEOFF_PHASES:
            command_type_str = "forceoff";
            break;
        case COMMAND_TYPE::HOLD_VEH_PHASES:
            command_type_str = "hold";
            break;
        case COMMAND_TYPE::OMIT_VEH_PHASES:
            command_type_str = "omit_veh";
            break;
        case COMMAND_TYPE::OMIT_PED_PHASES:
            command_type_str = "omit_ped";
            break;
        default:
            break;
        }
        os << "Command type: " << command_type_str << ", command phase: " << command.command_phase << ", start time: " << command.command_start_time << ", end time: " << std::setprecision(17) << command.command_end_time;
        return os;
    }
Member Data Documentation
command_end_time
uint64_t streets_phase_control_schedule::streets_phase_control_command::command_end_time = 0
Definition at line 30 of file streets_phase_control_command.h.
command_phase
int streets_phase_control_schedule::streets_phase_control_command::command_phase = 0
Definition at line 28 of file streets_phase_control_command.h.
Referenced by streets_snmp_cmd::streets_snmp_cmd_converter::add_phase_control_schedule_command_to_two_dimension_map().
command_start_time
uint64_t streets_phase_control_schedule::streets_phase_control_command::command_start_time = 0
Definition at line 29 of file streets_phase_control_command.h.
command_type
COMMAND_TYPE streets_phase_control_schedule::streets_phase_control_command::command_type
Definition at line 27 of file streets_phase_control_command.h.
Referenced by streets_snmp_cmd::streets_snmp_cmd_converter::add_phase_control_schedule_command_to_two_dimension_map(), and set_command_type().
The documentation for this struct was generated from the following files:
streets_utils/streets_phase_control_schedule/include/streets_phase_control_command.h
streets_utils/streets_phase_control_schedule/src/models/streets_phase_control_command.cpp