Carma-streets: signal_phase_and_timing::time_change_details Struct Reference
signal_phase_and_timing::time_change_details Struct Reference
#include <time_change_details.h>
Public Member Functions
rapidjson::Value toJson (rapidjson::Document::AllocatorType &allocator) const
Serialize Time Change Details object to rapidjson::Value for writing as JSON string.
void fromJson (const rapidjson::Value &val)
Deserialize Time Change Details JSON into Time Change Details object.
bool operator== (const time_change_details &other) const
Equals operator to asses whether two objects contain equivalent data.
bool operator!= (const time_change_details &other) const
Returns the inverse of equals operator.
uint64_t convert_hour_tenth_secs2epoch_ts (uint16_t hour_tenth_secs) const
Convert current hours of the year and milliseconds of the current hours into epoch timestamp in milliseconds.
uint64_t get_epoch_start_time () const
Get the epoch timestamp of the start timestamp.
uint64_t get_epoch_min_end_time () const
Get the epoch timestamp of the min end timestamp.
uint64_t get_epoch_max_end_time () const
Get the epoch timestamp of the max end timestamp.
uint64_t get_epoch_next_time () const
Get the epoch timestamp of the next end timestamp
uint16_t convert_msepoch_to_hour_tenth_secs (uint64_t epoch_time_ms) const
Convert epoch timestamp in milliseconds into tenths of seconds of the current UTC hour. Any value that results in tenths of seconds greater than 36000 will be set to 36000 (See TimeMark J2735 definition).
void set_start_time (uint64_t epoch_time_ms)
Set start_time for movement_event. Method expects epoch time in milliseconds and converts to tenths of seconds from current hour. Any value that results in tenths of seconds greater than 36000 will be set to 36000 (See TimeMark J2735 definition).
void set_min_end_time (uint64_t epoch_time_ms)
Set min_end_time for movement event. Method expects epoch time in milliseconds and converts to tenths of seconds from current hour. Any value that results in tenths of seconds greater than 36000 will be set to 36000 (See TimeMark J2735 definition).
void set_max_end_time (uint64_t epoch_time_ms)
Set min_end_time for movement event. Method expects epoch time in milliseconds and converts to tenths of seconds from current hour. Any value that results in tenths of seconds greater than 36000 will be set to 36000 (See TimeMark J2735 definition).
void set_next_time (uint64_t epoch_time_ms)
Set next_time for movement event. Method expects epoch time in milliseconds and converts to tenths of seconds from current hour. Any value that results in tenths of seconds greater than 36000 will be set to 36000 (See TimeMark J2735 definition).
Public Attributes
int HOUR_TO_SECONDS = 3600
int SECOND_TO_MILLISECONDS = 1000
uint16_t start_time = 36001
When this phase first started. (tenths of a second in current or next hour)
uint16_t min_end_time = 36001
Expected shortest end time. (tenths of a second in current or next hour)
uint16_t max_end_time = 36001
Expected longest end time. (tenths of a second in current or next hour)
uint16_t likely_time = 36001
Best predicted value based on other data (tenths of a second in current or next hour)
uint8_t confidence = 0
Applies to the above time interval only – Value Probability – 0 21% – 1 36% – 2 47% – 3 56% – 4 62% – 5 68% – 6 73% – 7 77% – 8 81% – 9 85% – 10 88% – 11 91% – 12 94% – 13 96% – 14 98% – 15 100%.
uint16_t next_time = 36001
A rough estimate of time when this phase may next occur. (tenths of a second in current or next hour)
Detailed Description
Definition at line 10 of file time_change_details.h.
Member Function Documentation
convert_hour_tenth_secs2epoch_ts()
uint64_t signal_phase_and_timing::time_change_details::convert_hour_tenth_secs2epoch_ts (uint16_t hour_tenth_secs) const
Convert current hours of the year and milliseconds of the current hours into epoch timestamp in milliseconds.
Parameters
hour_tenth_secs The tenth of seconds of the current hour
Returns
uint64_t epoch timestamp in milliseconds
Definition at line 101 of file time_change_details.cpp.
{
        auto hours_since_epoch = std::floor(streets_service::streets_clock_singleton::time_in_ms()/ (HOUR_TO_SECONDS * SECOND_TO_MILLISECONDS) );
        auto epoch_start_time = hours_since_epoch * HOUR_TO_SECONDS * SECOND_TO_MILLISECONDS + hour_tenth_secs * 100;
        return epoch_start_time;
    }
References HOUR_TO_SECONDS, SECOND_TO_MILLISECONDS, and streets_service::streets_clock_singleton::time_in_ms().
Referenced by get_epoch_max_end_time(), get_epoch_min_end_time(), get_epoch_next_time(), and get_epoch_start_time().
convert_msepoch_to_hour_tenth_secs()
uint16_t signal_phase_and_timing::time_change_details::convert_msepoch_to_hour_tenth_secs (uint64_t epoch_time_ms) const
Convert epoch timestamp in milliseconds into tenths of seconds of the current UTC hour. Any value that results in tenths of seconds greater than 36000 will be set to 36000 (See TimeMark J2735 definition).
Parameters
hour_tenth_secs The tenth of seconds of the current hour
Returns
uint64_t epoch timestamp in milliseconds
Definition at line 107 of file time_change_details.cpp.
{
        auto hours_since_epoch = std::floor(streets_service::streets_clock_singleton::time_in_ms()/ (HOUR_TO_SECONDS * SECOND_TO_MILLISECONDS) );
        auto hours_since_epoch_ms = hours_since_epoch * HOUR_TO_SECONDS * SECOND_TO_MILLISECONDS;
        uint64_t tenth_seconds_from_current_hour;
        if ( hours_since_epoch_ms > epoch_time_ms ) {
            SPDLOG_WARN("Epoch time provided {0} is smaller than the current UTC hour time {1}! SPaT cannot represent a time from a previous hour. Approximating time as beginning of current hour."
                , epoch_time_ms, hours_since_epoch_ms);
            tenth_seconds_from_current_hour = 0;
        }
        else {
            tenth_seconds_from_current_hour = (epoch_time_ms - hours_since_epoch_ms )/100;
        }
        // TimeMark Max value is 36001 and 36001 is reserved for invalid unknown times (see J2737 TimeMark message documentation).
        // Relevant section
        //         TimeMark ::= INTEGER (0..36001)
        //          -- Tenths of a second in the current or next hour
        //          -- In units of 1/10th second from UTC time
        //          -- A range of 0~36000 covers one hour
        //          -- The values 35991..35999 are used when a leap second occurs
        //          -- The value 36000 is used to indicate time >3600 seconds
        //          -- 36001 is to be used when value undefined or unknown
        //          -- Note that this is NOT expressed in GPS time
        //          -- or in local time
        if ( tenth_seconds_from_current_hour >= 36000) {
            SPDLOG_WARN("Approximating {0} as 36000! TimeMark maximum value is 36000!", tenth_seconds_from_current_hour);
            tenth_seconds_from_current_hour = 36000;
        }
        return static_cast<uint16_t>(tenth_seconds_from_current_hour);
    }
References HOUR_TO_SECONDS, SECOND_TO_MILLISECONDS, and streets_service::streets_clock_singleton::time_in_ms().
Referenced by set_max_end_time(), set_min_end_time(), set_next_time(), and set_start_time().
fromJson()
void signal_phase_and_timing::time_change_details::fromJson (const rapidjson::Value & val)
Deserialize Time Change Details JSON into Time Change Details object.
Parameters
val Time Change Details JSON.
Definition at line 43 of file time_change_details.cpp.
{
        if ( val.IsObject() ) {
            if ( val.HasMember("start_time") && val["start_time"].IsUint() && val["start_time"].GetUint() <= 36000 ) {
                // OPTIONAL see J2735 TimeChangeDetails definition but required for CARMA Streets future phase information
                start_time =  static_cast<uint16_t>(val["start_time"].GetUint());
            }
            else {
               throw signal_phase_and_timing_exception("TimeChangeDetails contains missing/invalid required start_time property!");
            }
            if (val.HasMember("min_end_time") && val["min_end_time"].IsUint() && val["min_end_time"].GetUint() <= 36000) {
                // REQUIRED see J2735 TimeChangeDetails definition
                min_end_time = static_cast<uint16_t>(val["min_end_time"].GetUint());
            }
            else {
               throw signal_phase_and_timing_exception("TimeChangeDetails contains missing/invalid required min_end_time property!");
            }
            if (val.HasMember("max_end_time") && val["max_end_time"].IsUint() && val["max_end_time"].GetUint() <= 36000) {
                // OPTIONAL see J2735 TimeChangeDetails definition
                max_end_time = static_cast<uint16_t>(val["max_end_time"].GetUint());
            }
            else if ( val.HasMember("max_end_time") && val["max_end_time"].IsUint() && val["max_end_time"].GetUint() > 36000) {
                SPDLOG_TRACE("Skipping invalid value {0} for max_end_time! Valid range (0-36000).", val["max_end_time"].GetUint());
            }
            if (val.HasMember("likely_time") &&  val["likely_time"].IsUint() && val["likely_time"].GetUint() <= 36000 ) {
                // OPTIONAL see J2735 TimeChangeDetails definition
                likely_time = static_cast<uint16_t>(val["likely_time"].GetInt() );
            }
            else if ( val.HasMember("likely_time") && val["likely_time"].IsUint() && val["likely_time"].GetUint() > 36000) {
                SPDLOG_TRACE("Skipping invalid value {0} for likely_time! Valid range (0-36000).", val["likely_time"].GetUint());
            }
            if ( val.HasMember("confidence") && val["confidence"].IsUint() ) {
                // OPTIONAL see J2735 TimeChangeDetails definition
                confidence = static_cast<uint8_t>(val["confidence"].GetUint());
            }
            if (  val.HasMember("next_time") && val["next_time"].IsUint() && val["next_time"].GetUint() <= 36000) {
                // OPTIONAL see J2735 TimeChangeDetails definition
                next_time = static_cast<uint16_t>(val["next_time"].GetUint());
            }
            else if (val.HasMember("next_time") && val["next_time"].IsUint() && val["next_time"].GetUint() > 36000) {
                SPDLOG_TRACE("Skipping invalid value {0} for next_time! Valid range (0-36000).", val["next_time"].GetUint());
            }
        }
    }
References confidence, likely_time, max_end_time, min_end_time, next_time, and start_time.
Referenced by signal_phase_and_timing::movement_event::fromJson().
get_epoch_max_end_time()
uint64_t signal_phase_and_timing::time_change_details::get_epoch_max_end_time () const
Get the epoch timestamp of the max end timestamp.
Returns
** uint64_t epoch timestamp in unit of milliseconds
Definition at line 145 of file time_change_details.cpp.
{
        return convert_hour_tenth_secs2epoch_ts(max_end_time);
    }
References convert_hour_tenth_secs2epoch_ts(), and max_end_time.
get_epoch_min_end_time()
uint64_t signal_phase_and_timing::time_change_details::get_epoch_min_end_time () const
Get the epoch timestamp of the min end timestamp.
Returns
** uint64_t epoch timestamp in unit of milliseconds
Definition at line 141 of file time_change_details.cpp.
{
        return convert_hour_tenth_secs2epoch_ts(min_end_time);
    }
References convert_hour_tenth_secs2epoch_ts(), and min_end_time.
Referenced by traffic_signal_controller_service::tsc_state::add_future_movement_events().
get_epoch_next_time()
uint64_t signal_phase_and_timing::time_change_details::get_epoch_next_time () const
Get the epoch timestamp of the next end timestamp
Returns
** uint64_t epoch timestamp in unit of milliseconds
Definition at line 149 of file time_change_details.cpp.
{
       return convert_hour_tenth_secs2epoch_ts(next_time);
    }
References convert_hour_tenth_secs2epoch_ts(), and next_time.
get_epoch_start_time()
uint64_t signal_phase_and_timing::time_change_details::get_epoch_start_time () const
Get the epoch timestamp of the start timestamp.
Returns
** uint64_t epoch timestamp in unit of milliseconds
Definition at line 137 of file time_change_details.cpp.
{
        return convert_hour_tenth_secs2epoch_ts(start_time);
    }
References convert_hour_tenth_secs2epoch_ts(), and start_time.
operator!=()
bool signal_phase_and_timing::time_change_details::operator!= (const time_change_details & other) const
Returns the inverse of equals operator.
Parameters
other second object to compare current object with.
Returns
true if both objects do not contain equivalent data.
false if both objects do contain equivalent data.
Definition at line 97 of file time_change_details.cpp.
{
        return !operator==(other);
    }
References operator==().
operator==()
bool signal_phase_and_timing::time_change_details::operator== (const time_change_details & other) const
Equals operator to asses whether two objects contain equivalent data.
Parameters
compare second object to compare current object with.
Returns
true if both object contain equivalent data.
false if not.
Definition at line 92 of file time_change_details.cpp.
{
        return start_time == other.start_time && min_end_time == other.min_end_time && max_end_time == other.max_end_time
            && likely_time == other.likely_time && confidence == other.confidence;
    }
References confidence, likely_time, max_end_time, min_end_time, and start_time.
Referenced by operator!=().
set_max_end_time()
void signal_phase_and_timing::time_change_details::set_max_end_time (uint64_t epoch_time_ms)
Set min_end_time for movement event. Method expects epoch time in milliseconds and converts to tenths of seconds from current hour. Any value that results in tenths of seconds greater than 36000 will be set to 36000 (See TimeMark J2735 definition).
Parameters
epoch_time_ms max_end time for movement_event in millisecond epoch time.
Definition at line 161 of file time_change_details.cpp.
{
        max_end_time =  convert_msepoch_to_hour_tenth_secs(epoch_time_ms);
    }
References convert_msepoch_to_hour_tenth_secs(), and max_end_time.
Referenced by traffic_signal_controller_service::tsc_state::get_following_event().
set_min_end_time()
void signal_phase_and_timing::time_change_details::set_min_end_time (uint64_t epoch_time_ms)
Set min_end_time for movement event. Method expects epoch time in milliseconds and converts to tenths of seconds from current hour. Any value that results in tenths of seconds greater than 36000 will be set to 36000 (See TimeMark J2735 definition).
Parameters
epoch_time_ms min_end time for movement_event in millisecond epoch time.
Definition at line 157 of file time_change_details.cpp.
{
        min_end_time = convert_msepoch_to_hour_tenth_secs(epoch_time_ms);
    }
References convert_msepoch_to_hour_tenth_secs(), and min_end_time.
Referenced by traffic_signal_controller_service::tsc_state::get_following_event(), and signal_phase_and_timing::spat::populate_movement_event().
set_next_time()
void signal_phase_and_timing::time_change_details::set_next_time (uint64_t epoch_time_ms)
Set next_time for movement event. Method expects epoch time in milliseconds and converts to tenths of seconds from current hour. Any value that results in tenths of seconds greater than 36000 will be set to 36000 (See TimeMark J2735 definition).
Parameters
epoch_time_ms next_time for movement_event in millisecond epoch time.
Definition at line 165 of file time_change_details.cpp.
{
        next_time =  convert_msepoch_to_hour_tenth_secs(epoch_time_ms);
    }
References convert_msepoch_to_hour_tenth_secs(), and next_time.
set_start_time()
void signal_phase_and_timing::time_change_details::set_start_time (uint64_t epoch_time_ms)
Set start_time for movement_event. Method expects epoch time in milliseconds and converts to tenths of seconds from current hour. Any value that results in tenths of seconds greater than 36000 will be set to 36000 (See TimeMark J2735 definition).
Parameters
epoch_time_ms start_time for movement_event in millisecond epoch time.
Definition at line 153 of file time_change_details.cpp.
{
        start_time = convert_msepoch_to_hour_tenth_secs(epoch_time_ms);
    }
References convert_msepoch_to_hour_tenth_secs(), and start_time.
Referenced by traffic_signal_controller_service::tsc_state::get_following_event(), and signal_phase_and_timing::spat::populate_movement_event().
toJson()
rapidjson::Value signal_phase_and_timing::time_change_details::toJson (rapidjson::Document::AllocatorType & allocator) const
Serialize Time Change Details object to rapidjson::Value for writing as JSON string.
Returns
rapidjson::Value serialize Time Change Details object
Definition at line 5 of file time_change_details.cpp.
{
        // Create time change detail JSON value
        rapidjson::Value detail(rapidjson::kObjectType);
        // Populate
        // OPTIONAL see J2735 TimeChangeDetails definition but required for CARMA Streets future phase information
        if ( start_time >= 36001 ) {
           throw signal_phase_and_timing_exception("TimeChangeDetails has invalid value of " + std::to_string(min_end_time) + " for start_time property! Valid range (0-36000).");
        }
        detail.AddMember("start_time", start_time,allocator);
        // value represents unknow see J2735 spec
        if (min_end_time >= 36001 ) {
            throw signal_phase_and_timing_exception("TimeChangeDetails has invalid value of " + std::to_string(min_end_time) + " for min_end_time property! Valid range (0-36000).");
        }
        detail.AddMember("min_end_time", min_end_time,allocator);
        // value represents unknow see J2735 spec
        if (max_end_time <= 36000) {
            detail.AddMember("max_end_time",max_end_time,allocator);
        } else {
            SPDLOG_TRACE("Skipping invalid value {0} for max_end_time! Valid range (0-36000).", max_end_time);
        }
        // value represents unknow see J2735 spec
        if (likely_time <= 36000) {
            detail.AddMember("likely_time", likely_time, allocator);
        }
        else {
            SPDLOG_TRACE("Skipping invalid value {0} for likely_time! Valid range (0-36000).", likely_time);
        }
        detail.AddMember("confidence", confidence, allocator);
        // value represents unknow see J2735 spec
        if (next_time <= 36000) {
            detail.AddMember("next_time", next_time, allocator);
        }
        else {
            SPDLOG_TRACE("Skipping invalid value {0} for next_time! Valid range (0-36000).", next_time);
        }
        return detail;
    }
References confidence, likely_time, max_end_time, min_end_time, next_time, start_time, and to_string().
Referenced by signal_phase_and_timing::movement_event::toJson().
Member Data Documentation
confidence
uint8_t signal_phase_and_timing::time_change_details::confidence = 0
Applies to the above time interval only – Value Probability – 0 21% – 1 36% – 2 47% – 3 56% – 4 62% – 5 68% – 6 73% – 7 77% – 8 81% – 9 85% – 10 88% – 11 91% – 12 94% – 13 96% – 14 98% – 15 100%.
Definition at line 49 of file time_change_details.h.
Referenced by fromJson(), operator==(), and toJson().
HOUR_TO_SECONDS
int signal_phase_and_timing::time_change_details::HOUR_TO_SECONDS = 3600
Definition at line 11 of file time_change_details.h.
Referenced by convert_hour_tenth_secs2epoch_ts(), and convert_msepoch_to_hour_tenth_secs().
likely_time
uint16_t signal_phase_and_timing::time_change_details::likely_time = 36001
Best predicted value based on other data (tenths of a second in current or next hour)
Definition at line 28 of file time_change_details.h.
Referenced by fromJson(), operator==(), and toJson().
max_end_time
uint16_t signal_phase_and_timing::time_change_details::max_end_time = 36001
Expected longest end time. (tenths of a second in current or next hour)
Definition at line 24 of file time_change_details.h.
Referenced by fromJson(), get_epoch_max_end_time(), operator==(), set_max_end_time(), toJson(), and signal_phase_and_timing::intersection_state::update_movement_state().
min_end_time
uint16_t signal_phase_and_timing::time_change_details::min_end_time = 36001
Expected shortest end time. (tenths of a second in current or next hour)
Definition at line 20 of file time_change_details.h.
Referenced by fromJson(), get_epoch_min_end_time(), operator==(), set_min_end_time(), toJson(), and signal_phase_and_timing::intersection_state::update_movement_state().
next_time
uint16_t signal_phase_and_timing::time_change_details::next_time = 36001
A rough estimate of time when this phase may next occur. (tenths of a second in current or next hour)
Definition at line 54 of file time_change_details.h.
Referenced by fromJson(), get_epoch_next_time(), set_next_time(), and toJson().
SECOND_TO_MILLISECONDS
int signal_phase_and_timing::time_change_details::SECOND_TO_MILLISECONDS = 1000
Definition at line 12 of file time_change_details.h.
Referenced by convert_hour_tenth_secs2epoch_ts(), and convert_msepoch_to_hour_tenth_secs().
start_time
uint16_t signal_phase_and_timing::time_change_details::start_time = 36001
When this phase first started. (tenths of a second in current or next hour)
Definition at line 16 of file time_change_details.h.
Referenced by fromJson(), get_epoch_start_time(), operator==(), set_start_time(), toJson(), and signal_phase_and_timing::intersection_state::update_movement_state().
The documentation for this struct was generated from the following files:
streets_utils/streets_signal_phase_and_timing/include/time_change_details.h
streets_utils/streets_signal_phase_and_timing/src/models/time_change_details.cpp