Carma-streets: ntcip::ntcip_1202_ext_phasetime Struct Reference
ntcip::ntcip_1202_ext_phasetime Struct Reference
#include <ntcip_1202_ext_phasetime.h>
Public Member Functions
uint16_t get_spat_veh_min_time_to_change () const
Get spat_veh_min_time_to_change and convert from network byte order to host byte order.
uint16_t get_spat_veh_max_time_to_change () const
Get spat_veh_max_time_to_change and convert from network byte order to host byte order.
uint16_t get_spat_ped_min_time_to_change () const
Get spat_ped_min_time_to_change and convert from network byte order to host byte order.
uint16_t get_spat_ped_max_time_to_change () const
Get spat_ped_max_time_to_change and convert from network byte order to host byte order.
uint16_t get_spat_ovlp_min_time_to_change () const
Get spatOvlpMinTimeToChange and convert from network byte order to host byte order.
uint16_t get_spat_ovp_max_time_to_change () const
Get spat_ovp_max_time_to_change and convert from netwrok byte order to host byte order.
std::string to_string () const
Convert information to string.
Public Attributes
uint8_t phase_number = 0
Phase number (NTCIP) of phase.
uint16_t spat_veh_min_time_to_change = 0
Time offset in deciseconds to min end time elapse for vehicle phase. DO NOT use member directly, stored in Network Byte Order. Use getter to intpret correctly.
uint16_t spat_veh_max_time_to_change = 0
Time offset in deciseconds to max end time elapse for vehicle phase. DO NOT use member directly, stored in Network Byte Order. Use getter to intpret correctly.
uint16_t spat_ped_min_time_to_change = 0
Time offset in deciseconds to min end time elapse for pedestrian phase. DO NOT use member directly, stored in Network Byte Order. Use getter to intpret correctly.
uint16_t spat_ped_max_time_to_change = 0
Time offset in deciseconds to max end time elapse for pedestrian phase. DO NOT use member directly, stored in Network Byte Order. Use getter to intpret correctly.
uint16_t spat_ovlp_min_time_to_change = 0
Time offset in deciseconds to min end time elapse for overlap. DO NOT use member directly, stored in Network Byte Order. Use getter to intpret correctly.
uint16_t spat_ovp_max_time_to_change = 0
Time offset in deciseconds to max end time elapse for overlap. DO NOT use member directly, stored in Network Byte Order. Use getter to intpret correctly.
Detailed Description
Definition at line 8 of file ntcip_1202_ext_phasetime.h.
Member Function Documentation
get_spat_ovlp_min_time_to_change()
uint16_t ntcip::ntcip_1202_ext_phasetime::get_spat_ovlp_min_time_to_change () const
Get spatOvlpMinTimeToChange and convert from network byte order to host byte order.
Returns
uint16_t
Definition at line 32 of file ntcip_1202_ext_phasetime.cpp.
{
        return ntohs(spat_ovlp_min_time_to_change);
    }
References spat_ovlp_min_time_to_change.
Referenced by to_string().
get_spat_ovp_max_time_to_change()
uint16_t ntcip::ntcip_1202_ext_phasetime::get_spat_ovp_max_time_to_change () const
Get spat_ovp_max_time_to_change and convert from netwrok byte order to host byte order.
Returns
uint16_t
Definition at line 36 of file ntcip_1202_ext_phasetime.cpp.
{
        return ntohs(spat_ovp_max_time_to_change);
    }
References spat_ovp_max_time_to_change.
Referenced by to_string().
get_spat_ped_max_time_to_change()
uint16_t ntcip::ntcip_1202_ext_phasetime::get_spat_ped_max_time_to_change () const
Get spat_ped_max_time_to_change and convert from network byte order to host byte order.
Returns
uint16_t
Definition at line 28 of file ntcip_1202_ext_phasetime.cpp.
{
        return ntohs(spat_ped_max_time_to_change);
    }
References spat_ped_max_time_to_change.
Referenced by to_string().
get_spat_ped_min_time_to_change()
uint16_t ntcip::ntcip_1202_ext_phasetime::get_spat_ped_min_time_to_change () const
Get spat_ped_min_time_to_change and convert from network byte order to host byte order.
Returns
uint16_t
Definition at line 24 of file ntcip_1202_ext_phasetime.cpp.
{
        return ntohs(spat_ped_min_time_to_change);
    }
References spat_ped_min_time_to_change.
Referenced by to_string().
get_spat_veh_max_time_to_change()
uint16_t ntcip::ntcip_1202_ext_phasetime::get_spat_veh_max_time_to_change () const
Get spat_veh_max_time_to_change and convert from network byte order to host byte order.
Returns
uint16_t
Definition at line 20 of file ntcip_1202_ext_phasetime.cpp.
{
        return ntohs(spat_veh_max_time_to_change);
    }
References spat_veh_max_time_to_change.
Referenced by to_string(), and signal_phase_and_timing::intersection_state::update_movement_state().
get_spat_veh_min_time_to_change()
uint16_t ntcip::ntcip_1202_ext_phasetime::get_spat_veh_min_time_to_change () const
Get spat_veh_min_time_to_change and convert from network byte order to host byte order.
Returns
uint16_t
Definition at line 16 of file ntcip_1202_ext_phasetime.cpp.
{
        return ntohs(spat_veh_min_time_to_change);
    }
References spat_veh_min_time_to_change.
Referenced by to_string(), and signal_phase_and_timing::intersection_state::update_movement_state().
to_string()
std::string ntcip::ntcip_1202_ext_phasetime::to_string () const
Convert information to string.
Returns
std::string
Definition at line 4 of file ntcip_1202_ext_phasetime.cpp.
{
        std::string message;
        message.append("phase_number: " + std::to_string(phase_number) +  "\n");
        message.append("spat_veh_min_time_to_change: " + std::to_string(get_spat_veh_min_time_to_change()) + "\n");
        message.append("spat_veh_max_time_to_change: " + std::to_string(get_spat_veh_max_time_to_change()) + "\n" );
        message.append("spat_ped_min_time_to_change: " + std::to_string(get_spat_ped_min_time_to_change()) + "\n");
        message.append("spat_ped_max_time_to_change: " + std::to_string(get_spat_ped_max_time_to_change()) + "\n");
        message.append("spat_ovlp_min_time_to_change: " + std::to_string(get_spat_ovlp_min_time_to_change()) + "\n");
        message.append("spat_ovp_max_time_to_change: " + std::to_string(get_spat_ovp_max_time_to_change()) + "\n");
        return message;
    }
References get_spat_ovlp_min_time_to_change(), get_spat_ovp_max_time_to_change(), get_spat_ped_max_time_to_change(), get_spat_ped_min_time_to_change(), get_spat_veh_max_time_to_change(), get_spat_veh_min_time_to_change(), phase_number, and to_string().
Member Data Documentation
phase_number
uint8_t ntcip::ntcip_1202_ext_phasetime::phase_number = 0
Phase number (NTCIP) of phase.
Definition at line 11 of file ntcip_1202_ext_phasetime.h.
Referenced by to_string().
spat_ovlp_min_time_to_change
uint16_t ntcip::ntcip_1202_ext_phasetime::spat_ovlp_min_time_to_change = 0
Time offset in deciseconds to min end time elapse for overlap. DO NOT use member directly, stored in Network Byte Order. Use getter to intpret correctly.
Definition at line 36 of file ntcip_1202_ext_phasetime.h.
Referenced by get_spat_ovlp_min_time_to_change().
spat_ovp_max_time_to_change
uint16_t ntcip::ntcip_1202_ext_phasetime::spat_ovp_max_time_to_change = 0
Time offset in deciseconds to max end time elapse for overlap. DO NOT use member directly, stored in Network Byte Order. Use getter to intpret correctly.
Definition at line 41 of file ntcip_1202_ext_phasetime.h.
Referenced by get_spat_ovp_max_time_to_change().
spat_ped_max_time_to_change
uint16_t ntcip::ntcip_1202_ext_phasetime::spat_ped_max_time_to_change = 0
Time offset in deciseconds to max end time elapse for pedestrian phase. DO NOT use member directly, stored in Network Byte Order. Use getter to intpret correctly.
Definition at line 31 of file ntcip_1202_ext_phasetime.h.
Referenced by get_spat_ped_max_time_to_change().
spat_ped_min_time_to_change
uint16_t ntcip::ntcip_1202_ext_phasetime::spat_ped_min_time_to_change = 0
Time offset in deciseconds to min end time elapse for pedestrian phase. DO NOT use member directly, stored in Network Byte Order. Use getter to intpret correctly.
Definition at line 26 of file ntcip_1202_ext_phasetime.h.
Referenced by get_spat_ped_min_time_to_change().
spat_veh_max_time_to_change
uint16_t ntcip::ntcip_1202_ext_phasetime::spat_veh_max_time_to_change = 0
Time offset in deciseconds to max end time elapse for vehicle phase. DO NOT use member directly, stored in Network Byte Order. Use getter to intpret correctly.
Definition at line 21 of file ntcip_1202_ext_phasetime.h.
Referenced by get_spat_veh_max_time_to_change().
spat_veh_min_time_to_change
uint16_t ntcip::ntcip_1202_ext_phasetime::spat_veh_min_time_to_change = 0
Time offset in deciseconds to min end time elapse for vehicle phase. DO NOT use member directly, stored in Network Byte Order. Use getter to intpret correctly.
Definition at line 16 of file ntcip_1202_ext_phasetime.h.
Referenced by get_spat_veh_min_time_to_change().
The documentation for this struct was generated from the following files:
streets_utils/streets_signal_phase_and_timing/include/ntcip_1202_ext_phasetime.h
streets_utils/streets_signal_phase_and_timing/src/models/ntcip_1202_ext_phasetime.cpp