Carma-streets: signal_phase_and_timing::intersection_state Struct Reference
signal_phase_and_timing::intersection_state Struct Reference
#include <intersection_state.h>
Public Member Functions
rapidjson::Value toJson (rapidjson::Document::AllocatorType &allocator) const
Serialize Intersection State object to rapidjson::Value for writing as JSON string.
void fromJson (const rapidjson::Value &val)
Deserialize Intersection State JSON into Intersection State object.
bool operator== (const intersection_state &other) const
Equals operator to asses whether two objects contain equivalent data.
bool operator!= (const intersection_state &other) const
Returns the inverse of equals operator.
uint64_t convert_min_mills2epoch_ts (uint32_t moy_ll, uint16_t min_mills_timestamp) const
Convert current mimutes of the year and milliseconds of the current minute into epoch timestamp in milliseconds.
uint64_t get_epoch_timestamp () const
Get the epoch timestamp of the intersection state timestamp.
void set_timestamp_ntcip (const uint32_t second_of_day, const uint16_t millisecond_of_second)
Set timestamp for intersection state based on NTCIP SPaT UDP message timestamp which is transmitted as second of the UTC day and millisecond of the UTC second. This information can be combined with the unix host time day of the year to get minute of the UTC year and millisecond of the UTC minute (J2735 Intersection State timeStamp units).
void set_timestamp_local ()
Set timestamp for intersection state based on host machine unix time.
void update_movement_state (ntcip::ntcip_1202_ext &spat_data, const int signal_group_id, const int phase_number)
Method to update movement_state with signal_group_id using ntcip spat data.
void update_movements (ntcip::ntcip_1202_ext &spat_data, const std::unordered_map< int, int > &phase_number_to_signal_group)
Clears old movement event data for all movement_states. Adds one movement_event to the state_time_speed list as the current event for each movement state. Then calls update_movement_state on every phase number/signal group mapping included in the phase_number to signal group map. This method is meant to be executed each time a nticp_1202_ext UDP packet is received to update the current movement event data of each phase with the timing information received.
void clear_future_movement_events ()
Clears the future movement events for each movement state, and only leave the current movement events.
movement_state & get_movement (const int signal_group_id)
Return reference to movement_state for signal group.
void initialize_movement_states (const std::unordered_map< int, int > &phase_number_to_signal_group)
Initialize list<movement_state> to include a movement for each phase_numer/signal_group entry in the phase number to signal group map. This method is meant to be run once, while initializing the spat object to contain movement states for all relevant signal groups.
uint16_t convert_offset (const uint16_t offset_tenths_of_sec) const
Convert time offset (in tenths of seconds) from current time (NTCIP SPaT timing information units) to tenths of seconds from current hour (J2735 SPaT timing information units). For reference please see J2735 and NTCIP documentation.
Public Attributes
int MIN_TO_SECONDS = 60
int SECOND_TO_MILLISECONDS = 1000
std::string name
Descriptive name for this collection.
uint16_t id = 0
A globally unique value set and consisting of regionID and intersection ID assignment. Provides unique mapping to the intersection MAP in question which provides complete location and approach/move/lane data.
uint8_t revision = 0
uint8_t status
BIT String of IntersectionStatusObject:
uint32_t moy = 0
Minute of current UTC year.
uint16_t time_stamp = 0
Millisecond point in the current UTC minute that this message was created.
std::list< int > enabled_lanes
A list of unique lane ID for each lane object which is active. Refers to dynamic MAP contents.
std::list< movement_state > states
Each Movement is given in turn and contains its signal phase state, mapping to the lanes it applies to, and point in time it will and. It may contain both active and future states.
std::list< connection_maneuver_assist > maneuver_assist_list
Assist Data.
Detailed Description
Definition at line 17 of file intersection_state.h.
Member Function Documentation
clear_future_movement_events()
void signal_phase_and_timing::intersection_state::clear_future_movement_events ()
Clears the future movement events for each movement state, and only leave the current movement events.
Definition at line 286 of file intersection_state.cpp.
    {
         for ( auto &move_state : states ) {
            // If movement event list is empty, create a current event.
            if ( move_state.state_time_speed.empty()) {
                // Add current movement_event
                movement_event cur_event;
                move_state.state_time_speed.push_front(cur_event);
            }
            // If movement event list contains future events, clear future events.
            if ( move_state.state_time_speed.size() > 1) {
                // Clear all movement events except current (front)
                movement_event cur_event = move_state.state_time_speed.front();
                move_state.state_time_speed.clear();
                move_state.state_time_speed.push_front(cur_event);
            }
        }
    }
References states.
convert_min_mills2epoch_ts()
uint64_t signal_phase_and_timing::intersection_state::convert_min_mills2epoch_ts (uint32_t moy_ll, uint16_t min_mills_timestamp) const
Convert current mimutes of the year and milliseconds of the current minute into epoch timestamp in milliseconds.
Parameters
moy_ll The current minutes of the year
min_mills_timestamp The milliseconds of the current minute
Returns
uint64_t epoch timestamp in milliseconds
Definition at line 136 of file intersection_state.cpp.
{
        //Calculate timestamp for beginning of the year
        std::chrono::system_clock::time_point now{std::chrono::milliseconds(streets_service::streets_clock_singleton::time_in_ms())};
        time_t tt = std::chrono::system_clock::to_time_t(now);
        tm utctime;
        gmtime_r(&tt, &utctime);
        auto timeinfo = tm();
        timeinfo.tm_year = utctime.tm_year;
        timeinfo.tm_mon = 0; //January
        timeinfo.tm_mday = 1; //1st
        timeinfo.tm_hour = 0; //00
        timeinfo.tm_min = 0; //00
        timeinfo.tm_sec = 0; //00
        time_t year_begin_utc_t = timegm(&timeinfo);
        auto year_begin_utc_tp = std::chrono::system_clock::from_time_t(year_begin_utc_t);
        auto year_begin_utc_timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(year_begin_utc_tp.time_since_epoch()).count();
        auto epoch_timestamp = year_begin_utc_timestamp + static_cast<long>(moy_ll) * MIN_TO_SECONDS * SECOND_TO_MILLISECONDS + min_mills_timestamp;
        return epoch_timestamp;
    }
References MIN_TO_SECONDS, SECOND_TO_MILLISECONDS, and streets_service::streets_clock_singleton::time_in_ms().
Referenced by get_epoch_timestamp().
convert_offset()
uint16_t signal_phase_and_timing::intersection_state::convert_offset (const uint16_t offset_tenths_of_sec) const
Convert time offset (in tenths of seconds) from current time (NTCIP SPaT timing information units) to tenths of seconds from current hour (J2735 SPaT timing information units). For reference please see J2735 and NTCIP documentation.
Parameters
offset_tenths_of_sec tenths of seconds from current time.
Returns
uint16_t tenths of seconds from current hour.
Definition at line 304 of file intersection_state.cpp.
{
        // Convert tenths of seconds to milliseconds
        int offset_ms = offset_tenths_of_seconds * 100;
        std::chrono::system_clock::time_point nowTimePoint {std::chrono::milliseconds(streets_service::streets_clock_singleton::time_in_ms())};
        std::chrono::system_clock::time_point nowPlusOffsetTimePoint = nowTimePoint +  std::chrono::milliseconds(offset_ms);
        std::chrono::system_clock::duration tp = nowPlusOffsetTimePoint.time_since_epoch();
        std::chrono::hours h =  std::chrono::duration_cast<std::chrono::hours>(tp);
        tp -= h;
        std::chrono::minutes m =  std::chrono::duration_cast<std::chrono::minutes>(tp);
        tp -= m;
        std::chrono::seconds s =  std::chrono::duration_cast<std::chrono::seconds>(tp);
        tp -= s;
        std::chrono::milliseconds ms = std::chrono::duration_cast<std::chrono::milliseconds>(tp);
        double fractionSeconds = ((double)s.count()) + ((double)ms.count()/1000.0);
        double retTimeD = ((double)(m.count() * 60) + fractionSeconds) * 10.0;
        SPDLOG_TRACE("Converted offset {0} to {1}", offset_tenths_of_seconds, retTimeD);
        return (uint16_t) retTimeD;
    }
References streets_service::streets_clock_singleton::time_in_ms().
Referenced by update_movement_state().
fromJson()
void signal_phase_and_timing::intersection_state::fromJson (const rapidjson::Value & val)
Deserialize Intersection State JSON into Intersection State object.
Parameters
val Intersection State JSON.
Definition at line 54 of file intersection_state.cpp.
{
        if ( val.IsObject() ) {
            if ( val.FindMember("name")->value.IsString() ) {
                // OPTIONAL see J2735 IntersectionState definition
                name =  val["name"].GetString();
            }
            if ( val.HasMember("id") && val["id"].IsUint()) {
                // REQUIRED see J2735 IntersectionState definition
                id =  static_cast<uint16_t>(val["id"].GetUint());
            }
            else {
               throw signal_phase_and_timing_exception("IntersectionState is missing required id property!");
            }
            if ( val.HasMember("revision") && val["revision"].IsUint()) {
                // REQUIRED see J2735 IntersectionState definition
                revision =  static_cast<uint8_t>(val["revision"].GetUint());
            }
            else {
               throw signal_phase_and_timing_exception("IntersectionState is missing required revision property!");
            }
            if ( val.FindMember("status")->value.IsUint()) {
                // REQUIRED see J2735 IntersectionState definition
                status =  (uint8_t) val["status"].GetUint();
            }
            else {
               throw signal_phase_and_timing_exception("IntersectionState is missing required status property!");
            }
            if ( val.HasMember("moy") &&  val["moy"].IsUint()) {
                // OPTIONAL see J2735 IntersectionState definition but required for CARMA-Streets
                moy = val["moy"].GetUint();
            }
            else {
               throw signal_phase_and_timing_exception("IntersectionState is missing required moy property!");
            }
            if ( val.HasMember("time_stamp") && val["time_stamp"].IsUint()) {
                // OPTIONAL see J2735 IntersectionState definition but required for CARMA-Streets
                time_stamp =  static_cast<uint16_t>(val["time_stamp"].GetUint());
            }
            else {
               throw signal_phase_and_timing_exception("IntersectionState is missing required time_stamp property!");
            }
            if ( val.FindMember("enabled_lanes")->value.IsArray() ) {
                // OPTIONAL see J2735 IntersectionState definition
                enabled_lanes.clear();
                for (const auto &lane: val["enabled_lanes"].GetArray()) {
                    enabled_lanes.push_back(lane.GetInt());
                }
            }
            if ( val.FindMember("states")->value.IsArray() ) {
                // REQUIRED see J2735 IntersectionState definition
                states.clear();
                for (const auto &movement_st: val["states"].GetArray()) {
                    movement_state move_state;
                    move_state.fromJson( movement_st );
                    states.push_back( move_state);
                }
            }
            else {
               throw signal_phase_and_timing_exception("IntersectionState is missing required states property!");
            }
            if ( val.FindMember("maneuver_assist_list")->value.IsArray() ) {
                // OPTIONAL see J2735 IntersectionState definition
                maneuver_assist_list.clear();
                for (const auto &state: val["maneuver_assist_list"].GetArray()) {
                    connection_maneuver_assist maneuver;
                    maneuver.fromJson( state );
                    maneuver_assist_list.push_back( maneuver);
                }
            }
        }
    }
References enabled_lanes, signal_phase_and_timing::connection_maneuver_assist::fromJson(), signal_phase_and_timing::movement_state::fromJson(), maneuver_assist_list, moy, name, revision, states, status, and time_stamp.
Referenced by signal_phase_and_timing::spat::fromJson().
get_epoch_timestamp()
uint64_t signal_phase_and_timing::intersection_state::get_epoch_timestamp () const
Get the epoch timestamp of the intersection state timestamp.
Returns
** uint64_t epoch timestamp in unit of milliseconds
Definition at line 156 of file intersection_state.cpp.
{
       auto epoch_timestamp = convert_min_mills2epoch_ts(moy, time_stamp);
       return epoch_timestamp;
    }
References convert_min_mills2epoch_ts(), moy, and time_stamp.
get_movement()
movement_state & signal_phase_and_timing::intersection_state::get_movement (const int signal_group_id)
Return reference to movement_state for signal group.
Parameters
signal_group_id
Returns
movement_state&
Definition at line 185 of file intersection_state.cpp.
{
        for ( auto it = states.begin(); it != states.end(); it++) {
            if ( it->signal_group ==  signal_group_id ) {
                return *it;
            }
        }
        throw signal_phase_and_timing_exception("No movement_state found for movement with signal group id " + std::to_string(signal_group_id) + "!");
    }
References states, and to_string().
Referenced by streets_signal_optimization::streets_desired_phase_plan_generator::convert_spat_to_dpp(), and update_movement_state().
initialize_movement_states()
void signal_phase_and_timing::intersection_state::initialize_movement_states (const std::unordered_map< int, int > & phase_number_to_signal_group)
Initialize list<movement_state> to include a movement for each phase_numer/signal_group entry in the phase number to signal group map. This method is meant to be run once, while initializing the spat object to contain movement states for all relevant signal groups.
Parameters
phase_number_to_signal_group std::unordered_map<int,int> of phase number (keys) to signal group (values). Map used to translate phase_number (NTCIP) to signal group (J2735).
Definition at line 194 of file intersection_state.cpp.
{
        if (!states.empty()) {
            states.clear();
        }
        for (const auto &phase_2_sig_group : phase_number_to_signal_group) {
            movement_state state;
            state.signal_group = (uint8_t) phase_2_sig_group.second;
            states.push_back(state);
        }
    }
References signal_phase_and_timing::movement_state::signal_group, and states.
Referenced by signal_phase_and_timing::spat::initialize_intersection().
operator!=()
bool signal_phase_and_timing::intersection_state::operator!= (const intersection_state & other) const
Returns the inverse of equals operator.
Parameters
other second object to compare current object with.
Returns
true if both objects do not contain equivalent data.
false if both objects do contain equivalent data.
Definition at line 132 of file intersection_state.cpp.
{
        return !operator==(compare);
    }
References operator==().
operator==()
bool signal_phase_and_timing::intersection_state::operator== (const intersection_state & other) const
Equals operator to asses whether two objects contain equivalent data.
Parameters
compare second object to compare current object with.
Returns
true if both object contain equivalent data.
false if not.
Definition at line 126 of file intersection_state.cpp.
{
        return name == other.name && id == other.id && revision == other.revision && status == other.status &&
            moy && other.moy && time_stamp == other.time_stamp && enabled_lanes == other.enabled_lanes
            && states == other.states && maneuver_assist_list == other.maneuver_assist_list;
    }
References enabled_lanes, id, maneuver_assist_list, moy, name, revision, states, status, and time_stamp.
Referenced by operator!=().
set_timestamp_local()
void signal_phase_and_timing::intersection_state::set_timestamp_local ()
Set timestamp for intersection state based on host machine unix time.
Definition at line 173 of file intersection_state.cpp.
{
        std::chrono::system_clock::time_point now {std::chrono::milliseconds(streets_service::streets_clock_singleton::time_in_ms())};
        time_t tt = std::chrono::system_clock::to_time_t(now);
        tm utc_tm;
        gmtime_r(&tt, &utc_tm);
        moy = (uint32_t)(utc_tm.tm_yday*60*24 + utc_tm.tm_hour*60 + utc_tm.tm_min);
        auto millisecond_of_second = std::chrono::duration_cast<std::chrono::milliseconds>(now.time_since_epoch()).count() % 1000;
        // Millisecond of second + second of minute * 1000
        time_stamp = (uint16_t)(millisecond_of_second + utc_tm.tm_sec*1000);
    }
References moy, streets_service::streets_clock_singleton::time_in_ms(), and time_stamp.
set_timestamp_ntcip()
void signal_phase_and_timing::intersection_state::set_timestamp_ntcip (const uint32_t second_of_day, const uint16_t millisecond_of_second)
Set timestamp for intersection state based on NTCIP SPaT UDP message timestamp which is transmitted as second of the UTC day and millisecond of the UTC second. This information can be combined with the unix host time day of the year to get minute of the UTC year and millisecond of the UTC minute (J2735 Intersection State timeStamp units).
Parameters
second_of_day second of the UTC year.
millisecond_of_second millisecond of the UTC second.
Definition at line 161 of file intersection_state.cpp.
{
        std::chrono::system_clock::time_point now {std::chrono::milliseconds(streets_service::streets_clock_singleton::time_in_ms())};
        time_t tt = std::chrono::system_clock::to_time_t(now);
        tm utc_tm;
        gmtime_r(&tt, &utc_tm);
        // Day of the year * 24 hours * 60 minutes + second of the day / 60 = minute of the year
        moy = (uint32_t)(utc_tm.tm_yday*24*60+ trunc(second_of_day/ 60));
        // Remaineder of (second of the day/ 60 ) * 1000 + millisecond of the current second
        time_stamp = ((second_of_day%60)*1000) + millisecond_of_second;
    }
References moy, streets_service::streets_clock_singleton::time_in_ms(), and time_stamp.
toJson()
rapidjson::Value signal_phase_and_timing::intersection_state::toJson (rapidjson::Document::AllocatorType & allocator) const
Serialize Intersection State object to rapidjson::Value for writing as JSON string.
Returns
rapidjson::Value serialize Intersection State object
Definition at line 5 of file intersection_state.cpp.
{
        // Create intersection state JSON value
        rapidjson::Value state(rapidjson::kObjectType);
        // Populate
        // OPTIONAL see J2735 IntersectionState definition
        state.AddMember("name", name, allocator);
        // REQUIRED see J2735 IntersectionState definition
        if (id == 0 ) {
            throw signal_phase_and_timing_exception("IntersectionState is missing required id property!");
        }
        state.AddMember("id", id, allocator);
        state.AddMember("revision", revision, allocator);
        // REQUIRED see J2735 IntersectionState definition
        state.AddMember("status", status, allocator);
        // OPTIONAL see J2735 IntersectionState definition but required for CARMA-Streets
        state.AddMember("moy", moy, allocator);
        // OPTIONAL see J2735 IntersectionState definition but required for CARMA-Streets
        state.AddMember("time_stamp", time_stamp, allocator);
        // OPTIONAL see J2735 IntersectionState definition
        if ( !enabled_lanes.empty() ) {
            rapidjson::Value lane_list(rapidjson::kArrayType);
            for (const auto &lane_id : enabled_lanes) {
                lane_list.PushBack(lane_id, allocator);
            }
            state.AddMember("enabled_lanes", lane_list, allocator);
        }
        // REQUIRED see J2735 IntersectionState definition
        if ( !states.empty() ) {
            rapidjson::Value states_list(rapidjson::kArrayType);
            for (const auto &move_state : states) {
                states_list.PushBack(move_state.toJson(allocator), allocator);
            }
            state.AddMember("states", states_list, allocator);
        }
        else {
               throw signal_phase_and_timing_exception("IntersectionState is missing required states property!");
        }
        // OPTIONAL see J2735 IntersectionState definition
        if ( !maneuver_assist_list.empty() ) {
            rapidjson::Value maneuver_list(rapidjson::kArrayType);
            for (const auto &maneuver : maneuver_assist_list) {
                maneuver_list.PushBack(maneuver.toJson(allocator), allocator);
            }
            state.AddMember("maneuver_assist_list", maneuver_list, allocator);
        }
        return state;
    }
References enabled_lanes, maneuver_assist_list, moy, name, revision, states, status, and time_stamp.
update_movement_state()
void signal_phase_and_timing::intersection_state::update_movement_state (ntcip::ntcip_1202_ext & spat_data, const int signal_group_id, const int phase_number)
Method to update movement_state with signal_group_id using ntcip spat data.
Parameters
spat_data NTCIP SPaT data.
signal_group_id signal group id of movement to update.
Definition at line 205 of file intersection_state.cpp.
{
        movement_state &movement = get_movement(signal_group_id);
        // Get current movement_event
        movement_event &cur_event = movement.state_time_speed.front();
        // Set event state
        bool is_flashing = spat_data.get_phase_flashing_status( phase_number );
        if ( spat_data.get_phase_red_status(phase_number) ) {
            if (is_flashing) {
                if ( cur_event.event_state !=  movement_phase_state::stop_then_proceed ) {
                    SPDLOG_DEBUG("Setting start time to current time");
                    cur_event.timing.start_time = convert_offset(0);
                }
                cur_event.event_state = movement_phase_state::stop_then_proceed;
            }else {
                if ( cur_event.event_state !=  movement_phase_state::stop_and_remain ) {
                    SPDLOG_DEBUG("Setting start time to current time");
                    cur_event.timing.start_time = convert_offset(0);
                }
                cur_event.event_state =  movement_phase_state::stop_and_remain;
            }
        }
        else if ( spat_data.get_phase_yellow_status( phase_number ) ) {
            if ( is_flashing ) {
                if ( cur_event.event_state !=  movement_phase_state::caution_conflicting_traffic ) {
                    SPDLOG_DEBUG("Setting start time to current time");
                    cur_event.timing.start_time = convert_offset(0);
                }
                cur_event.event_state =  movement_phase_state::caution_conflicting_traffic;
            }else {
                if ( cur_event.event_state !=  movement_phase_state::protected_clearance ) {
                    SPDLOG_DEBUG("Setting start time to current time");
                    cur_event.timing.start_time = convert_offset(0);
                }
                cur_event.event_state =  movement_phase_state::protected_clearance;
            }
        }
        else if ( spat_data.get_phase_green_status(phase_number)) {
            // TODO: Add Support Permissive Green Phase
            if ( cur_event.event_state !=  movement_phase_state::protected_movement_allowed ) {
                    SPDLOG_DEBUG("Setting start time to current time");
                    cur_event.timing.start_time = convert_offset(0);
            }
            cur_event.event_state = movement_phase_state::protected_movement_allowed;
        }
        else {
            if ( cur_event.event_state !=  movement_phase_state::dark ) {
                    SPDLOG_DEBUG("Setting start time to current time");
                    cur_event.timing.start_time = convert_offset(0);
            }
            cur_event.event_state = movement_phase_state::dark;
        }
        // Set event timing
        cur_event.timing.max_end_time = convert_offset(spat_data.get_phasetime(phase_number).get_spat_veh_max_time_to_change());
        cur_event.timing.min_end_time = convert_offset(spat_data.get_phasetime(phase_number).get_spat_veh_min_time_to_change());
    }
References signal_phase_and_timing::caution_conflicting_traffic, convert_offset(), signal_phase_and_timing::dark, signal_phase_and_timing::movement_event::event_state, get_movement(), ntcip::ntcip_1202_ext::get_phase_flashing_status(), ntcip::ntcip_1202_ext::get_phase_green_status(), ntcip::ntcip_1202_ext::get_phase_red_status(), ntcip::ntcip_1202_ext::get_phase_yellow_status(), ntcip::ntcip_1202_ext::get_phasetime(), ntcip::ntcip_1202_ext_phasetime::get_spat_veh_max_time_to_change(), ntcip::ntcip_1202_ext_phasetime::get_spat_veh_min_time_to_change(), signal_phase_and_timing::time_change_details::max_end_time, signal_phase_and_timing::time_change_details::min_end_time, phase_number, signal_phase_and_timing::protected_clearance, signal_phase_and_timing::protected_movement_allowed, signal_phase_and_timing::time_change_details::start_time, signal_phase_and_timing::movement_state::state_time_speed, signal_phase_and_timing::stop_and_remain, signal_phase_and_timing::stop_then_proceed, and signal_phase_and_timing::movement_event::timing.
Referenced by update_movements().
update_movements()
void signal_phase_and_timing::intersection_state::update_movements (ntcip::ntcip_1202_ext & spat_data, const std::unordered_map< int, int > & phase_number_to_signal_group)
Clears old movement event data for all movement_states. Adds one movement_event to the state_time_speed list as the current event for each movement state. Then calls update_movement_state on every phase number/signal group mapping included in the phase_number to signal group map. This method is meant to be executed each time a nticp_1202_ext UDP packet is received to update the current movement event data of each phase with the timing information received.
Parameters
spat_data UDP TSC information.
phase_number_to_signal_group phase number to signal group map.
Definition at line 263 of file intersection_state.cpp.
{
        for ( auto &move_state : states ) {
            // If movement event list is empty, create a current event.
            if ( move_state.state_time_speed.empty()) {
                // Add current movement_event
                movement_event cur_event;
                move_state.state_time_speed.push_front(cur_event);
            }
            // If movement event list contains future events, clear future events.
            if ( move_state.state_time_speed.size() > 1) {
                // Clear all movement events except current (front)
                movement_event cur_event = move_state.state_time_speed.front();
                move_state.state_time_speed.clear();
                move_state.state_time_speed.push_front(cur_event);
            }
        }
        for ( const auto &phase_2_signal_group : phase_number_to_signal_group ) {
            update_movement_state(spat_data, phase_2_signal_group.second, phase_2_signal_group.first);
        }
    }
References states, and update_movement_state().
Member Data Documentation
enabled_lanes
std::list<int> signal_phase_and_timing::intersection_state::enabled_lanes
A list of unique lane ID for each lane object which is active. Refers to dynamic MAP contents.
Definition at line 89 of file intersection_state.h.
Referenced by fromJson(), operator==(), and toJson().
id
uint16_t signal_phase_and_timing::intersection_state::id = 0
A globally unique value set and consisting of regionID and intersection ID assignment. Provides unique mapping to the intersection MAP in question which provides complete location and approach/move/lane data.
Definition at line 32 of file intersection_state.h.
Referenced by signal_phase_and_timing::spat::initialize_intersection(), and operator==().
maneuver_assist_list
std::list<connection_maneuver_assist> signal_phase_and_timing::intersection_state::maneuver_assist_list
Assist Data.
Definition at line 100 of file intersection_state.h.
Referenced by fromJson(), operator==(), and toJson().
MIN_TO_SECONDS
int signal_phase_and_timing::intersection_state::MIN_TO_SECONDS = 60
Definition at line 19 of file intersection_state.h.
Referenced by convert_min_mills2epoch_ts().
moy
uint32_t signal_phase_and_timing::intersection_state::moy = 0
Minute of current UTC year.
Definition at line 81 of file intersection_state.h.
Referenced by fromJson(), get_epoch_timestamp(), operator==(), set_timestamp_local(), set_timestamp_ntcip(), and toJson().
name
std::string signal_phase_and_timing::intersection_state::name
Descriptive name for this collection.
Definition at line 25 of file intersection_state.h.
Referenced by fromJson(), signal_phase_and_timing::spat::initialize_intersection(), operator==(), and toJson().
revision
uint8_t signal_phase_and_timing::intersection_state::revision = 0
Definition at line 34 of file intersection_state.h.
Referenced by fromJson(), operator==(), and toJson().
SECOND_TO_MILLISECONDS
int signal_phase_and_timing::intersection_state::SECOND_TO_MILLISECONDS = 1000
Definition at line 20 of file intersection_state.h.
Referenced by convert_min_mills2epoch_ts().
states
std::list<movement_state> signal_phase_and_timing::intersection_state::states
Each Movement is given in turn and contains its signal phase state, mapping to the lanes it applies to, and point in time it will and. It may contain both active and future states.
Definition at line 95 of file intersection_state.h.
Referenced by clear_future_movement_events(), fromJson(), get_movement(), initialize_movement_states(), operator==(), toJson(), and update_movements().
status
uint8_t signal_phase_and_timing::intersection_state::status
BIT String of IntersectionStatusObject:
manualControlIsEnabled (0), – Timing reported is per programmed values, etc. but person – at cabinet can manually request that certain intervals are – terminated early (e.g. green). stopTimeIsActivated (1), – And all counting/timing has stopped. failureFlash (2), – Above to be used for any detected hardware failures, – e.g. conflict monitor as well as for police flash preemptIsActive (3), signalPriorityIsActive (4),
– Additional states fixedTimeOperation (5), – Schedule of signals is based on time only – (i.e. the state can be calculated) trafficDependentOperation (6), – Operation is based on different levels of traffic parameters – (requests, duration of gaps or more complex parameters) standbyOperation (7), – Controller: partially switched off or partially amber flashing failureMode (8), – Controller has a problem or failure in operation off (9), – Controller is switched off – Related to MAP and SPAT bindings recentMAPmessageUpdate (10), – Map revision with content changes recentChangeInMAPassignedLanesIDsUsed (11), – Change in MAP's assigned lanes used (lane changes) – Changes in the active lane list description noValidMAPisAvailableAtThisTime (12), – MAP (and various lanes indexes) not available noValidSPATisAvailableAtThisTime (13) – SPAT system is not working at this time
– Bits 14,15 reserved at this time and shall be zero } (SIZE(16))
Definition at line 77 of file intersection_state.h.
Referenced by fromJson(), operator==(), and toJson().
time_stamp
uint16_t signal_phase_and_timing::intersection_state::time_stamp = 0
Millisecond point in the current UTC minute that this message was created.
Definition at line 85 of file intersection_state.h.
Referenced by fromJson(), get_epoch_timestamp(), operator==(), set_timestamp_local(), set_timestamp_ntcip(), and toJson().
The documentation for this struct was generated from the following files:
streets_utils/streets_signal_phase_and_timing/include/intersection_state.h
streets_utils/streets_signal_phase_and_timing/src/models/intersection_state.cpp