Carma-cloud: cc.ws.GeoSvc Class Reference
cc.ws.GeoSvc Class Reference
Classes
class HashWays
class Sim
class SimWay
class Way
Public Member Functions
GeoSvc ()
void init ()
void run ()
void doPost (HttpServletRequest oReq, HttpServletResponse oRep) throws IOException
Protected Attributes
String m_sOsmFile
Static Package Functions
[static initializer]
Package Attributes
ArrayList< HashWays > m_oHashWays
ArrayList< Way > m_oInitWays
double[] m_dInitBounds = new double[]{-77.209426, 38.931905, -77.127627, 38.967285}
int m_nInitSims = 100
Private Attributes
final ArrayList< SimWay > m_oSimWays = new ArrayList()
final Timer m_oTimer = new Timer()
Static Private Attributes
static final ByteBuffer ID_BUFFER = ByteBuffer.allocate(8)
static final StringPool STRING_POOL = new StringPool()
static SecureRandom RNG
Detailed Description
Definition at line 25 of file GeoSvc.java.
Constructor & Destructor Documentation
GeoSvc()
cc.ws.GeoSvc.GeoSvc () inline
Definition at line 52 of file GeoSvc.java.
    {
    }
Member Function Documentation
[static initializer]()
cc.ws.GeoSvc.[static initializer] inline static package
References cc.ws.GeoSvc.RNG.
doPost()
void cc.ws.GeoSvc.doPost (HttpServletRequest oReq, HttpServletResponse oRep) throws IOException inline
Definition at line 160 of file GeoSvc.java.
    {
        Session oSess = SessMgr.getSession(oReq);
        if (oSess == null)
        {
            oRep.sendError(401);
            return;
        }
        String sPath = oReq.getPathInfo();
        if (sPath.contains("bounds") || sPath.contains("segpts"))
        {
            try (JsonGenerator oJson = Json.createGenerator(oRep.getOutputStream()))
            {
                oJson.writeStartObject(); // start JSON object
                int nZoom = Integer.parseInt(oReq.getParameter("zoom"));
                int[] nHash = new int[]{Integer.parseInt(oReq.getParameter("hash"))};
                int nIndex = Collections.binarySearch(m_oHashWays, nHash);
                if (nIndex >= 0)
                {
                    HashWays oWays = m_oHashWays.get(nIndex);
                    if (sPath.contains("bounds"))
                    {
                        if (nZoom >= 13) // should be highways and highway links
{
                            oJson.writeStartObject("13"); // min acceptable zoom level
                            for (Way oWay : oWays)
{
                                if (oWay.m_sType.contains("motorway") || oWay.m_sType.contains("trunk"))
                                    oWay.printBounds(oJson);
                            }
                            oJson.writeEnd();
                        }
                        if (nZoom >= 16) // should be surface streets
{
                            oJson.writeStartObject("16"); // min acceptable zoom level
                            for (Way oWay : oWays)
{
                                if (!oWay.m_sType.contains("motorway") && !oWay.m_sType.contains("trunk"))
                                    oWay.printBounds(oJson);
                            }
                            oJson.writeEnd();
                        }
                    }
                    else if (sPath.contains("segpts"))
                    {
                        oWays.forEach(oWay -> {oWay.printDetail(oJson);});
                    }
                }
                oJson.writeEnd(); // end JSON object
            }
        }
        else if (sPath.contains("sim"))
        {
            try (JsonGenerator oJson = Json.createGenerator(oRep.getOutputStream()))
            {
                oJson.writeStartObject();
                synchronized(m_oSimWays) // ensure updates are complete
                {
                    for (SimWay oSimWay : m_oSimWays)
                    {
                        oJson.writeStartArray(oSimWay.m_sId);
                        oJson.write(oSimWay.m_dLat);
                        oJson.write(oSimWay.m_dLon);
                        oJson.writeEnd();
                    }
                }
                oJson.writeEnd();
            }
        }
    }
References cc.ws.SessMgr.getSession(), cc.ws.GeoSvc.m_oHashWays, and cc.ws.GeoSvc.m_oSimWays.
init()
void cc.ws.GeoSvc.init () inline
Definition at line 58 of file GeoSvc.java.
    {
        ServletConfig oConfig = getServletConfig();
        String sInitBounds = oConfig.getInitParameter("initbounds");
        if (sInitBounds != null && sInitBounds.length() > 0)
        {
            String[] sBounds = sInitBounds.split(",");
            for (int i = 0; i < m_dInitBounds.length; i++)
                m_dInitBounds[i] = Double.parseDouble(sBounds[i]);
        }
        String sInitSims = oConfig.getInitParameter("initsims");
        if (sInitSims != null && sInitSims.length() > 0)
            m_nInitSims = Integer.parseInt(sInitSims);
        String sOsmFile = oConfig.getInitParameter("osmfile");
        if (sOsmFile != null && sOsmFile.length() > 0)
        {
            m_sOsmFile = sOsmFile;
            new Thread(this).start();
        }
    }
References cc.ws.GeoSvc.m_dInitBounds, cc.ws.GeoSvc.m_nInitSims, and cc.ws.GeoSvc.m_sOsmFile.
run()
void cc.ws.GeoSvc.run () inline
Definition at line 81 of file GeoSvc.java.
    {
        try
        {
            File oDir = new File(m_sOsmFile);
            if (oDir.isFile())
                return;
            int[] nHash = new int[1]; // hash mutable integer wrapper
            ArrayList<HashWays> oHashWays = new ArrayList();
            ArrayList<Way> oInitWays = new ArrayList();
            ArrayList<String> oPool = new ArrayList(); // reused local string pool
            File[] oFiles = oDir.listFiles();
            for (File oFile : oFiles)
            {
                if (!oFile.getName().endsWith(".bin"))
                    continue; // ignore other files
                System.out.print(oFile.getName());
                long lNow = System.currentTimeMillis();
                DataInputStream oIn = new DataInputStream(new BufferedInStream(new FileInputStream(oFile)));
                int nCount = oIn.readInt(); // local pool string count
                oPool.clear(); // reuse local string pool
                oPool.ensureCapacity(nCount);
                while (nCount-- > 0) // merge local strings into main pool
                    oPool.add(STRING_POOL.intern(oIn.readUTF()));
                nCount = oIn.readInt(); // number of ways to read
                while (nCount-- > 0)
                {
                    Way oWay = new Way(oPool, oIn);
//                  String sType = oWay.m_sType; // filter non-highways
//                  if (sType == null || (sType.compareTo("motorway") != 0 && sType.compareTo("trunk") != 0))
//                      continue;
                    int nXmin = Geo.scale(oWay.m_nLonMin);
                    int nXmax = Geo.scale(oWay.m_nLonMax);
                    int nYmin = Geo.scale(oWay.m_nLatMin);
                    int nYmax = Geo.scale(oWay.m_nLatMax);
                    if (Geo.boundingBoxesIntersect(m_dInitBounds[0], m_dInitBounds[1], m_dInitBounds[2], m_dInitBounds[3],
                                                Geo.fromIntDeg(oWay.m_nLonMin), Geo.fromIntDeg(oWay.m_nLatMin), Geo.fromIntDeg(oWay.m_nLonMax), Geo.fromIntDeg(oWay.m_nLatMax)))
                        oInitWays.add(oWay);
                    for (int nX = nXmin; nX <= nXmax; nX++) // include max endpoint
                    {
                        for (int nY = nYmin; nY <= nYmax; nY++) // include max endpoint
{
                            nHash[0] = (nX << 16) + nY; // lon shift left 16 bits and add lat
                            int nIndex = Collections.binarySearch(oHashWays, nHash);
                            if (nIndex < 0)
{
                                nIndex = ~nIndex;
                                oHashWays.add(nIndex, new HashWays(nHash[0]));
                            }
                            oHashWays.get(nIndex).add(oWay); // child class maintains set
                        }
                    }
                }
                System.out.print(" ");
                System.out.println(System.currentTimeMillis() - lNow);
            }
            m_oHashWays = oHashWays; // set servlet reference
            m_oInitWays = oInitWays;
            int nSims = 1000;
            while (nSims-- > 0) // create simulated vehicles
                m_oSimWays.add(new SimWay());
            m_oTimer.scheduleAtFixedRate(new Sim(), 0L, 1000L); // update positions
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.util.Geo.boundingBoxesIntersect(), cc.util.Geo.fromIntDeg(), cc.util.StringPool.intern(), cc.ws.GeoSvc.m_dInitBounds, cc.ws.GeoSvc.Way.m_nLatMax, cc.ws.GeoSvc.Way.m_nLatMin, cc.ws.GeoSvc.Way.m_nLonMax, cc.ws.GeoSvc.Way.m_nLonMin, cc.ws.GeoSvc.m_oHashWays, cc.ws.GeoSvc.m_oInitWays, cc.ws.GeoSvc.m_oSimWays, cc.ws.GeoSvc.m_oTimer, cc.ws.GeoSvc.m_sOsmFile, cc.util.Geo.scale(), and cc.ws.GeoSvc.STRING_POOL.
Member Data Documentation
ID_BUFFER
final ByteBuffer cc.ws.GeoSvc.ID_BUFFER = ByteBuffer.allocate(8) static private
Definition at line 27 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.Way.Way().
m_dInitBounds
double [] cc.ws.GeoSvc.m_dInitBounds = new double[]{-77.209426, 38.931905, -77.127627, 38.967285} package
Definition at line 36 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.init(), and cc.ws.GeoSvc.run().
m_nInitSims
int cc.ws.GeoSvc.m_nInitSims = 100 package
Definition at line 37 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.init().
m_oHashWays
ArrayList<HashWays> cc.ws.GeoSvc.m_oHashWays package
Definition at line 34 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.doPost(), cc.ws.GeoSvc.SimWay.nextWay(), and cc.ws.GeoSvc.run().
m_oInitWays
ArrayList<Way> cc.ws.GeoSvc.m_oInitWays package
Definition at line 35 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.SimWay.initWay(), and cc.ws.GeoSvc.run().
m_oSimWays
final ArrayList<SimWay> cc.ws.GeoSvc.m_oSimWays = new ArrayList() private
Definition at line 31 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.doPost(), cc.ws.GeoSvc.run(), and cc.ws.GeoSvc.Sim.run().
m_oTimer
final Timer cc.ws.GeoSvc.m_oTimer = new Timer() private
Definition at line 32 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.run().
m_sOsmFile
String cc.ws.GeoSvc.m_sOsmFile protected
Definition at line 33 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.init(), and cc.ws.GeoSvc.run().
RNG
SecureRandom cc.ws.GeoSvc.RNG static private
Definition at line 29 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.SimWay.SimWay(), cc.ws.GeoSvc.[static initializer](), cc.ws.GeoSvc.SimWay.initWay(), and cc.ws.GeoSvc.SimWay.nextWay().
STRING_POOL
final StringPool cc.ws.GeoSvc.STRING_POOL = new StringPool() static private
Definition at line 28 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.run().
The documentation for this class was generated from the following file:
src/cc/ws/GeoSvc.java