Carma-cloud: cc.util.TileLayerBuilder Class Reference
cc.util.TileLayerBuilder Class Reference
Public Member Functions
TileLayerBuilder (int nX, int nY, int nZ)
Public Attributes
VectorTile.Tile.Layer.Builder m_oLayerBuilder
VectorTile.Tile.Feature.Builder m_oFeatureBuilder
VectorTile.Tile.Value.Builder m_oValueBuilder
double[] m_dTileBounds
double[] m_dClippingBounds
int m_nExtent
int[] m_nCur
int[] m_nPointBuffer
Area m_oPolyClip
int m_nX
int m_nY
int m_nZ
Detailed Description
Author
aaron.cherney
Definition at line 17 of file TileLayerBuilder.java.
Constructor & Destructor Documentation
TileLayerBuilder()
cc.util.TileLayerBuilder.TileLayerBuilder (int nX, int nY, int nZ) inline
Definition at line 32 of file TileLayerBuilder.java.
    {
        m_nX = nX;
        m_nY = nY;
        m_nZ = nZ;
        m_dTileBounds = new double[4];
        Mercator oM = Mercator.getInstance();
        oM.tileBounds(nX, nY, nZ, m_dTileBounds); // get the meter bounds of the requested tile
        double dPadding = oM.resolution(nZ) * 8;
        m_dClippingBounds = new double[4];
        m_dClippingBounds[0] = m_dTileBounds[0] - dPadding;
        m_dClippingBounds[1] = m_dTileBounds[1] - dPadding;
        m_dClippingBounds[2] = m_dTileBounds[2] + dPadding;
        m_dClippingBounds[3] = m_dTileBounds[3] + dPadding;
        m_oLayerBuilder = VectorTile.Tile.Layer.newBuilder();
        m_oFeatureBuilder = VectorTile.Tile.Feature.newBuilder();
        m_oValueBuilder = VectorTile.Tile.Value.newBuilder();
        m_nExtent = 4096;
        m_nCur = new int[2];
        m_nPointBuffer = Arrays.newIntArray(1024);
        Path2D.Double oTilePath = new Path2D.Double(); // create clipping boundary
        oTilePath.moveTo(m_dClippingBounds[0], m_dClippingBounds[3]);
        oTilePath.lineTo(m_dClippingBounds[2], m_dClippingBounds[3]);
        oTilePath.lineTo(m_dClippingBounds[2], m_dClippingBounds[1]);
        oTilePath.lineTo(m_dClippingBounds[0], m_dClippingBounds[1]);
        oTilePath.closePath();
        m_oPolyClip = new Area(oTilePath);
        m_oLayerBuilder.setVersion(2);
        m_oLayerBuilder.setExtent(m_nExtent);
    }
References cc.geosrv.Mercator.getInstance(), cc.util.TileLayerBuilder.m_dClippingBounds, cc.util.TileLayerBuilder.m_dTileBounds, cc.util.TileLayerBuilder.m_nCur, cc.util.TileLayerBuilder.m_nExtent, cc.util.TileLayerBuilder.m_nPointBuffer, cc.util.TileLayerBuilder.m_nX, cc.util.TileLayerBuilder.m_nY, cc.util.TileLayerBuilder.m_nZ, cc.util.TileLayerBuilder.m_oFeatureBuilder, cc.util.TileLayerBuilder.m_oLayerBuilder, cc.util.TileLayerBuilder.m_oPolyClip, cc.util.TileLayerBuilder.m_oValueBuilder, cc.vector_tile.VectorTile.Tile.Value.newBuilder(), cc.vector_tile.VectorTile.Tile.Feature.newBuilder(), cc.vector_tile.VectorTile.Tile.Layer.newBuilder(), cc.util.Arrays.newIntArray(), cc.geosrv.Mercator.resolution(), and cc.geosrv.Mercator.tileBounds().
Member Data Documentation
m_dClippingBounds
double [] cc.util.TileLayerBuilder.m_dClippingBounds
Definition at line 23 of file TileLayerBuilder.java.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder().
m_dTileBounds
double [] cc.util.TileLayerBuilder.m_dTileBounds
Definition at line 22 of file TileLayerBuilder.java.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder().
m_nCur
int [] cc.util.TileLayerBuilder.m_nCur
Definition at line 25 of file TileLayerBuilder.java.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder().
m_nExtent
int cc.util.TileLayerBuilder.m_nExtent
Definition at line 24 of file TileLayerBuilder.java.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder().
m_nPointBuffer
int [] cc.util.TileLayerBuilder.m_nPointBuffer
Definition at line 26 of file TileLayerBuilder.java.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder().
m_nX
int cc.util.TileLayerBuilder.m_nX
Definition at line 28 of file TileLayerBuilder.java.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder().
m_nY
int cc.util.TileLayerBuilder.m_nY
Definition at line 29 of file TileLayerBuilder.java.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder().
m_nZ
int cc.util.TileLayerBuilder.m_nZ
Definition at line 30 of file TileLayerBuilder.java.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder().
m_oFeatureBuilder
VectorTile.Tile.Feature.Builder cc.util.TileLayerBuilder.m_oFeatureBuilder
Definition at line 20 of file TileLayerBuilder.java.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder().
m_oLayerBuilder
VectorTile.Tile.Layer.Builder cc.util.TileLayerBuilder.m_oLayerBuilder
Definition at line 19 of file TileLayerBuilder.java.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder().
m_oPolyClip
Area cc.util.TileLayerBuilder.m_oPolyClip
Definition at line 27 of file TileLayerBuilder.java.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder().
m_oValueBuilder
VectorTile.Tile.Value.Builder cc.util.TileLayerBuilder.m_oValueBuilder
Definition at line 21 of file TileLayerBuilder.java.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder().
The documentation for this class was generated from the following file:
src/cc/util/TileLayerBuilder.java