Carma-cloud: cc.ws.TimeSource Class Reference
cc.ws.TimeSource Class Reference
Public Member Functions
long currentTimeMillis ()
Static Public Member Functions
static TimeSource getInstance ()
Protected Member Functions
TimeSource ()
Package Functions
TimeSource (boolean bSim)
Package Attributes
long m_lSimTime
Private Attributes
boolean m_bSim
Static Private Attributes
static TimeSource g_oInstance
Detailed Description
Definition at line 4 of file TimeSource.java.
Constructor & Destructor Documentation
TimeSource() [1/2]
cc.ws.TimeSource.TimeSource () inline protected
Definition at line 12 of file TimeSource.java.
    {
    }
TimeSource() [2/2]
cc.ws.TimeSource.TimeSource (boolean bSim) inline package
Definition at line 17 of file TimeSource.java.
    {
        m_bSim = bSim;
        g_oInstance = this;
    }
References cc.ws.TimeSource.g_oInstance, and cc.ws.TimeSource.m_bSim.
Member Function Documentation
currentTimeMillis()
long cc.ws.TimeSource.currentTimeMillis () inline
Definition at line 30 of file TimeSource.java.
    {
        if (m_bSim)
            return m_lSimTime;
        return System.currentTimeMillis();
    }
References cc.ws.TimeSource.m_bSim, and cc.ws.TimeSource.m_lSimTime.
Referenced by cc.ws.CtrlTiles.addControl(), cc.ws.CtrlTiles.doGet(), cc.ws.SimFederate.doPost(), cc.ws.TcmReqServlet.run(), and cc.ws.CtrlTiles.saveEdit().
getInstance()
static TimeSource cc.ws.TimeSource.getInstance () inline static
Definition at line 24 of file TimeSource.java.
    {
        return g_oInstance;
    }
References cc.ws.TimeSource.g_oInstance.
Referenced by cc.ws.CtrlTiles.addControl(), cc.ws.CtrlTiles.doGet(), cc.ws.TcmReqServlet.run(), and cc.ws.CtrlTiles.saveEdit().
Member Data Documentation
g_oInstance
TimeSource cc.ws.TimeSource.g_oInstance static private
Definition at line 6 of file TimeSource.java.
Referenced by cc.ws.TimeSource.TimeSource(), and cc.ws.TimeSource.getInstance().
m_bSim
boolean cc.ws.TimeSource.m_bSim private
Definition at line 8 of file TimeSource.java.
Referenced by cc.ws.TimeSource.TimeSource(), and cc.ws.TimeSource.currentTimeMillis().
m_lSimTime
long cc.ws.TimeSource.m_lSimTime package
Definition at line 9 of file TimeSource.java.
Referenced by cc.ws.TimeSource.currentTimeMillis().
The documentation for this class was generated from the following file:
src/cc/ws/TimeSource.java