Carma-cloud: cc.geosrv.xodr.rdmk.RoadMark Class Reference
cc.geosrv.xodr.rdmk.RoadMark Class Reference
Public Member Functions
RoadMark (String sType, String sColor, double dS)
void createLinesForTile (Proj oProj, double[] dPoint, int nId)
int compareTo (RoadMark o)
Static Public Member Functions
static RoadMark getRoadMark (double dDist, ArrayList< RoadMark > oRoadMarks)
static int getColor (String sColor)
static int getType (String sType)
static String getColor (int nColor)
static String getType (int nType)
static void setSolidSolid (double dValue)
static void setBrokenSpace (double dValue)
static void setBrokenLine (double dValue)
Public Attributes
int m_nType
double[] m_dLine
ArrayList< double[]> m_oTileLines
int m_nColor
double m_dS
Static Public Attributes
static String[] COLORS
Static Private Attributes
static String[] TYPES
static double g_dSolidSolidWidth
static double g_dBrokenSpace
static double g_dBrokenLine
Detailed Description
Author
aaron.cherney
Definition at line 18 of file RoadMark.java.
Constructor & Destructor Documentation
RoadMark()
cc.geosrv.xodr.rdmk.RoadMark.RoadMark (String sType, String sColor, double dS) inline
Definition at line 57 of file RoadMark.java.
    {
        m_dLine = Arrays.newDoubleArray();
        m_dLine = Arrays.add(m_dLine, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
        m_nType = getType(sType);
        m_nColor = getColor(sColor);
        m_dS = dS;
    }
References cc.util.Arrays.add(), cc.geosrv.xodr.rdmk.RoadMark.getColor(), cc.geosrv.xodr.rdmk.RoadMark.getType(), cc.geosrv.xodr.rdmk.RoadMark.m_dLine, cc.geosrv.xodr.rdmk.RoadMark.m_dS, cc.geosrv.xodr.rdmk.RoadMark.m_nColor, cc.geosrv.xodr.rdmk.RoadMark.m_nType, and cc.util.Arrays.newDoubleArray().
Member Function Documentation
compareTo()
int cc.geosrv.xodr.rdmk.RoadMark.compareTo (RoadMark o) inline
Definition at line 322 of file RoadMark.java.
    {
        return Double.compare(m_dS, o.m_dS);
    }
References cc.geosrv.xodr.rdmk.RoadMark.m_dS.
Referenced by cc.geosrv.xodr.rdmk.RoadMark.getColor(), and cc.geosrv.xodr.rdmk.RoadMark.getType().
createLinesForTile()
void cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile (Proj oProj, double[] dPoint, int nId) inline
Definition at line 122 of file RoadMark.java.
    {
        double[] dSegment = new double[4];
        m_oTileLines = new ArrayList();
        switch (m_nType)
        {
            case 1:
            {
                double[] dLeft = Arrays.newDoubleArray(Arrays.size(m_dLine));
                double[] dRight = Arrays.newDoubleArray(Arrays.size(m_dLine));
                dLeft = Arrays.add(dLeft, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                dRight = Arrays.add(dRight, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                double dHeading = Double.NaN;
                Iterator<double[]> oIt = Arrays.iterator(m_dLine, dSegment, 5, 2);
                while (oIt.hasNext())
                {
                    oIt.next();
                    if (Geo.distance(dSegment[0], dSegment[1], dSegment[2], dSegment[3]) < 0.01) // if the distance between points is less than 1 cm skip
                        continue;
                    dHeading = Geo.heading(dSegment[0], dSegment[1], dSegment[2], dSegment[3]);
                    if (Double.isNaN(dHeading))
                        continue;
                    dRight = Geometry.addProjectedPoint(dSegment[0] - Math.sin(dHeading) * g_dSolidSolidWidth, dSegment[1] + Math.cos(dHeading) * g_dSolidSolidWidth, dRight, oProj, dPoint);
                    dLeft = Geometry.addProjectedPoint(dSegment[0] - Math.sin(dHeading - Math.PI) * g_dSolidSolidWidth, dSegment[1] + Math.cos(dHeading - Math.PI) * g_dSolidSolidWidth, dLeft, oProj, dPoint);
                }
                dRight = Geometry.addProjectedPoint(dSegment[2] - Math.sin(dHeading) * g_dSolidSolidWidth, dSegment[3] + Math.cos(dHeading) * g_dSolidSolidWidth, dRight, oProj, dPoint);
                dLeft = Geometry.addProjectedPoint(dSegment[2] - Math.sin(dHeading - Math.PI) * g_dSolidSolidWidth, dSegment[3] + Math.cos(dHeading - Math.PI) * g_dSolidSolidWidth, dLeft, oProj, dPoint);
                m_oTileLines.add(dRight);
                m_oTileLines.add(dLeft);
                break;
            }
            case 2:
            {
                double dLength = 0.0;
                Iterator<double[]> oIt = Arrays.iterator(m_dLine, dSegment, 5, 2);
                while (oIt.hasNext())
                {
                    oIt.next();
                    double dDist = Geo.distance(dSegment[0], dSegment[1], dSegment[2], dSegment[3]);
                    if (dDist < 0.01) // if the distance between points is less than 1 cm skip
                        continue;
                    dLength += dDist;
                }
                int nMarks = (int)Math.floor(dLength / (g_dBrokenSpace + g_dBrokenLine));
                double dMarkLength = (g_dBrokenSpace + g_dBrokenSpace) * nMarks;
                double dOffset = (dLength - dMarkLength) / 2;
                oIt = Arrays.iterator(m_dLine, dSegment, 5, 2);
                dLength = 0.0;
                double dCurrent = dOffset;
                boolean bSpace = true;
                double[] dLine = Arrays.newDoubleArray();
                while (oIt.hasNext())
                {
                    oIt.next();
                    double dDist = Geo.distance(dSegment[0], dSegment[1], dSegment[2], dSegment[3]);
                    if (dDist < 0.01)
                        continue;
                    dCurrent += dDist;
                    if (bSpace)
                    {
                        if (dCurrent >= g_dBrokenSpace)
{
                            bSpace = false;
                            dCurrent = 0.0;
                            dLine = Arrays.newDoubleArray();
                            dLine = Arrays.add(dLine, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                        }
                    }
                    else
                    {
                        if (dCurrent >= g_dBrokenLine)
{
                            bSpace = true;
                            dCurrent = 0.0;
                            m_oTileLines.add(dLine);
                        }
                        else
                            dLine = Geometry.addProjectedPoint(dSegment[0], dSegment[1], dLine, oProj, dPoint);
                    }
                }
                break;
            }
            case 4 :
            case 5 :
            {
                double dSolidAngle = 0;
                double dBrokenAngle = 0;
                if (m_nType == 5)
                    dBrokenAngle = -Math.PI;
                else
                    dSolidAngle = -Math.PI;
                double dLength = 0.0;
                Iterator<double[]> oIt = Arrays.iterator(m_dLine, dSegment, 5, 2);
                while (oIt.hasNext())
                {
                    oIt.next();
                    double dDist = Geo.distance(dSegment[0], dSegment[1], dSegment[2], dSegment[3]);
                    if (dDist < 0.01) // if the distance between points is less than 1 cm skip
                        continue;
                    dLength += dDist;
                }
                int nMarks = (int)Math.floor(dLength / (g_dBrokenSpace + g_dBrokenLine));
                double dMarkLength = (g_dBrokenSpace + g_dBrokenSpace) * nMarks;
                double dOffset = (dLength - dMarkLength) / 2;
                oIt = Arrays.iterator(m_dLine, dSegment, 5, 2);
                dLength = 0.0;
                double dCurrent = dOffset;
                boolean bSpace = true;
                double[] dLine = Arrays.newDoubleArray();
                while (oIt.hasNext())
                {
                    oIt.next();
                    double dDist = Geo.distance(dSegment[0], dSegment[1], dSegment[2], dSegment[3]);
                    if (dDist < 0.01)
                        continue;
                    dCurrent += dDist;
                    if (bSpace)
                    {
                        if (dCurrent >= g_dBrokenSpace)
{
                            bSpace = false;
                            dCurrent = 0.0;
                            dLine = Arrays.newDoubleArray();
                            dLine = Arrays.add(dLine, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                        }
                    }
                    else
                    {
                        if (dCurrent >= g_dBrokenLine)
{
                            bSpace = true;
                            dCurrent = 0.0;
                            m_oTileLines.add(dLine);
                        }
                        else
{
                            double dHeading = Geo.heading(dSegment[0], dSegment[1], dSegment[2], dSegment[3]);
                            if (Double.isNaN(dHeading))
                                continue;
                            dHeading += dBrokenAngle;
                            dLine = Geometry.addProjectedPoint(dSegment[0] - Math.sin(dHeading) * g_dSolidSolidWidth, dSegment[1] + Math.cos(dHeading) * g_dSolidSolidWidth, dLine, oProj, dPoint);
                        }
                    }
                }
                double[] dSolid = Arrays.newDoubleArray(Arrays.size(m_dLine));
                dSolid = Arrays.add(dSolid, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                double dHeading = Double.NaN;
                oIt = Arrays.iterator(m_dLine, dSegment, 5, 2);
                while (oIt.hasNext())
                {
                    oIt.next();
                    if (Geo.distance(dSegment[0], dSegment[1], dSegment[2], dSegment[3]) < 0.01) // if the distance between points is less than 1 cm skip
                        continue;
                    dHeading = Geo.heading(dSegment[0], dSegment[1], dSegment[2], dSegment[3]);
                    if (Double.isNaN(dHeading))
                        continue;
                    dHeading += dSolidAngle;
                    dSolid = Geometry.addProjectedPoint(dSegment[0] - Math.sin(dHeading) * g_dSolidSolidWidth, dSegment[1] + Math.cos(dHeading) * g_dSolidSolidWidth, dSolid, oProj, dPoint);
                }
                dSolid = Geometry.addProjectedPoint(dSegment[2] - Math.sin(dHeading) * g_dSolidSolidWidth, dSegment[3] + Math.cos(dHeading) * g_dSolidSolidWidth, dSolid, oProj, dPoint);
                m_oTileLines.add(dSolid);
                break;
            }
            default:
            {
                double[] dLine = Arrays.newDoubleArray(Arrays.size(m_dLine));
                double[] dReuse = new double[2];
                Iterator<double[]> oIt = Arrays.iterator(m_dLine, dReuse, 5, 2);
                while (oIt.hasNext())
                {
                    oIt.next();
                    dLine = Geometry.addProjectedPoint(dReuse[0], dReuse[1], dLine, oProj, dPoint);
                }
                m_oTileLines.add(dLine);
                break;
            }
        }
    }
References cc.util.Arrays.add(), cc.geosrv.xodr.rdmk.Geometry.addProjectedPoint(), cc.util.Geo.distance(), cc.geosrv.xodr.rdmk.RoadMark.g_dBrokenLine, cc.geosrv.xodr.rdmk.RoadMark.g_dBrokenSpace, cc.geosrv.xodr.rdmk.RoadMark.g_dSolidSolidWidth, cc.util.Geo.heading(), cc.util.Arrays.iterator(), cc.geosrv.xodr.rdmk.RoadMark.m_dLine, cc.geosrv.xodr.rdmk.RoadMark.m_nType, cc.geosrv.xodr.rdmk.RoadMark.m_oTileLines, cc.util.Arrays.newDoubleArray(), and cc.util.Arrays.size().
getColor() [1/2]
static String cc.geosrv.xodr.rdmk.RoadMark.getColor (int nColor) inline static
Definition at line 110 of file RoadMark.java.
    {
        return COLORS[nColor];
    }
References cc.geosrv.xodr.rdmk.RoadMark.COLORS.
getColor() [2/2]
static int cc.geosrv.xodr.rdmk.RoadMark.getColor (String sColor) inline static
Definition at line 81 of file RoadMark.java.
    {
        if (sColor == null)
            return 0;
        int nIndex = COLORS.length;
        while (nIndex-- > 0)
        {
            if (COLORS[nIndex].compareTo(sColor) == 0)
                return nIndex;
        }
        return 0; // return 0 which is "standard" if there is no match
    }
References cc.geosrv.xodr.rdmk.RoadMark.COLORS, and cc.geosrv.xodr.rdmk.RoadMark.compareTo().
Referenced by cc.geosrv.xodr.rdmk.RoadMark.RoadMark().
getRoadMark()
static RoadMark cc.geosrv.xodr.rdmk.RoadMark.getRoadMark (double dDist, ArrayList< RoadMark > oRoadMarks) inline static
Definition at line 67 of file RoadMark.java.
    {
        int nIndex = oRoadMarks.size();
        while (nIndex-- > 0)
        {
            RoadMark oTemp = oRoadMarks.get(nIndex);
            if (dDist >= oTemp.m_dS)
                return oTemp;
        }
        return null;
    }
References cc.geosrv.xodr.rdmk.RoadMark.m_dS.
Referenced by cc.geosrv.xodr.rdmk.Geometry.addLanePoints().
getType() [1/2]
static String cc.geosrv.xodr.rdmk.RoadMark.getType (int nType) inline static
Definition at line 116 of file RoadMark.java.
    {
        return TYPES[nType];
    }
References cc.geosrv.xodr.rdmk.RoadMark.TYPES.
getType() [2/2]
static int cc.geosrv.xodr.rdmk.RoadMark.getType (String sType) inline static
Definition at line 97 of file RoadMark.java.
    {
        int nIndex = TYPES.length;
        while (nIndex-- > 0)
        {
            if (TYPES[nIndex].compareTo(sType) == 0)
                return nIndex;
        }
        return 0; // return 0 which is "none" if there is no match
    }
References cc.geosrv.xodr.rdmk.RoadMark.compareTo(), and cc.geosrv.xodr.rdmk.RoadMark.TYPES.
Referenced by cc.geosrv.xodr.rdmk.RoadMark.RoadMark(), and cc.ctrl.proc.ProcLatPerm.proc().
setBrokenLine()
static void cc.geosrv.xodr.rdmk.RoadMark.setBrokenLine (double dValue) inline static
Definition at line 315 of file RoadMark.java.
    {
        g_dBrokenLine = dValue;
    }
References cc.geosrv.xodr.rdmk.RoadMark.g_dBrokenLine.
setBrokenSpace()
static void cc.geosrv.xodr.rdmk.RoadMark.setBrokenSpace (double dValue) inline static
Definition at line 310 of file RoadMark.java.
    {
        g_dBrokenSpace = dValue;
    }
References cc.geosrv.xodr.rdmk.RoadMark.g_dBrokenSpace.
setSolidSolid()
static void cc.geosrv.xodr.rdmk.RoadMark.setSolidSolid (double dValue) inline static
Definition at line 304 of file RoadMark.java.
    {
        g_dSolidSolidWidth = dValue;
    }
References cc.geosrv.xodr.rdmk.RoadMark.g_dSolidSolidWidth.
Member Data Documentation
COLORS
String [] cc.geosrv.xodr.rdmk.RoadMark.COLORS static
Initial value:
= new String[]
    {
        "standard",
        "blue",
        "green",
        "red",
        "white",
        "yellow",
        "orange"
    }
Definition at line 36 of file RoadMark.java.
Referenced by cc.geosrv.xodr.rdmk.RoadMark.getColor(), and cc.ctrl.proc.ProcLatPerm.renderTiledData().
g_dBrokenLine
double cc.geosrv.xodr.rdmk.RoadMark.g_dBrokenLine static private
Definition at line 55 of file RoadMark.java.
Referenced by cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile(), and cc.geosrv.xodr.rdmk.RoadMark.setBrokenLine().
g_dBrokenSpace
double cc.geosrv.xodr.rdmk.RoadMark.g_dBrokenSpace static private
Definition at line 54 of file RoadMark.java.
Referenced by cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile(), and cc.geosrv.xodr.rdmk.RoadMark.setBrokenSpace().
g_dSolidSolidWidth
double cc.geosrv.xodr.rdmk.RoadMark.g_dSolidSolidWidth static private
Definition at line 53 of file RoadMark.java.
Referenced by cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile(), and cc.geosrv.xodr.rdmk.RoadMark.setSolidSolid().
m_dLine
double [] cc.geosrv.xodr.rdmk.RoadMark.m_dLine
Definition at line 49 of file RoadMark.java.
Referenced by cc.geosrv.xodr.rdmk.RoadMark.RoadMark(), and cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile().
m_dS
double cc.geosrv.xodr.rdmk.RoadMark.m_dS
Definition at line 52 of file RoadMark.java.
Referenced by cc.geosrv.xodr.rdmk.RoadMark.RoadMark(), cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.geosrv.xodr.rdmk.RoadMark.compareTo(), and cc.geosrv.xodr.rdmk.RoadMark.getRoadMark().
m_nColor
int cc.geosrv.xodr.rdmk.RoadMark.m_nColor
Definition at line 51 of file RoadMark.java.
Referenced by cc.geosrv.xodr.rdmk.RoadMark.RoadMark().
m_nType
int cc.geosrv.xodr.rdmk.RoadMark.m_nType
Definition at line 48 of file RoadMark.java.
Referenced by cc.geosrv.xodr.rdmk.RoadMark.RoadMark(), and cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile().
m_oTileLines
ArrayList<double[]> cc.geosrv.xodr.rdmk.RoadMark.m_oTileLines
Definition at line 50 of file RoadMark.java.
Referenced by cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile().
TYPES
String [] cc.geosrv.xodr.rdmk.RoadMark.TYPES static private
Initial value:
= new String[]
    {
        "none",
        "solid",
        "broken",
        "solid solid",
        "solid broken",
        "broken solid",
        "broken broken",
        "botts dots",
        "grass",
        "curb",
        "custom",
        "edge"
    }
Definition at line 20 of file RoadMark.java.
Referenced by cc.geosrv.xodr.rdmk.RoadMark.getType().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/rdmk/RoadMark.java