Carma-cloud: cc.ctrl.proc.ProcDirection Class Reference
cc.ctrl.proc.ProcDirection Class Reference
Public Member Functions
ProcDirection (String sLineArcDir, String sXodrDir)
void parseMetadata (Path oSource) throws Exception
void proc (String sLineArcsFile, double dTol) throws Exception
ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
ProcCtrl (String sLineArcDir)
void parseMetadata (String sSource) throws Exception
abstract void parseMetadata (Path oSource) throws Exception
void process (String sLineArcsFile, double dTol) throws Exception
abstract ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Static Public Member Functions
static void renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
Static Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
static void setStaticVariables (double dStep, String sDir, String sTdFF, int nZoom)
static void updateTiles (ArrayList< int[]> oTiles, ArrayList< int[]> oCtrlTiles)
static void updateTileRange (int[] nTileIndices, int[] nTmpTiles)
static ArrayList< CtrlLineArcs > combineLaneByRoad (ArrayList< CtrlLineArcs > oLineArcs, double dTol)
static void writeIndexFile (ArrayList< TrafCtrl > oCtrls, int nX, int nY) throws IOException
static void updateIndex (String sIndexFile, TrafCtrl oCtrl, long lTimestamp) throws IOException
static void renderCtrls (String sCtrlType, ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
static boolean deleteControl (String sId) throws Exception
static boolean deleteControl (TrafCtrl oCtrl)
static ArrayList< TrafCtrl > getCurrentControls (int nCtrlType, double dMinLon, double dMinLat, double dMaxLon, double dMaxLat, boolean bLoadFullGeo)
Private Attributes
HashMap< String, String > m_oJunctions
String m_sXodrDir
Static Private Attributes
static final double[][] ARROW = new double[][]{new double[]{-0.5,0.0,0.5,0.0}, new double[]{0.15,0.35,0.5,0.0,0.15,-0.35}}
Additional Inherited Members
Public Attributes inherited from cc.ctrl.proc.ProcCtrl
String m_sLineArcDir
Static Public Attributes inherited from cc.ctrl.proc.ProcCtrl
static final Object INDEXLOCK = new Object()
static double g_dExplodeStep
static String g_sTrafCtrlDir
static String g_sTdFileFormat
static String g_sGeolanesDir
static int g_nDefaultZoom = Integer.MIN_VALUE
static final byte CC = 0
static final byte RSM = 1
static final byte IHP2 = 2
abstract void proc (String sLineArcsFile, double dTol) throws Exception
Static Protected Member Functions inherited from cc.ctrl.proc.ProcCtrl
static boolean checkTileRange (int[] nTileIndices)
Static Protected Attributes inherited from cc.ctrl.proc.ProcCtrl
static final double WIDTHTH = 1.5
static final double LENLOWTH = 75.0
static final double STOPLINEENDOFFSET = 0.6
static final double STOPLINELATOFFSET = 0.1
static double[][] NUMBERS
static Comparator< int[]> LANETYPECOMP
static final HashMap< String, double[]> CHARS = new HashMap()
Static Package Functions inherited from cc.ctrl.proc.ProcCtrl
[static initializer]
static double getCoordAndHeadingAtLength (double[] dPoints, double dLength, boolean bReverse, double[] dPoint)
static int getStopLine (TrafCtrl oCtrl, ArrayList< double[]> oStops)
Detailed Description
Author
aaron.cherney
Definition at line 38 of file ProcDirection.java.
Constructor & Destructor Documentation
ProcDirection()
cc.ctrl.proc.ProcDirection.ProcDirection (String sLineArcDir, String sXodrDir) inline
Definition at line 44 of file ProcDirection.java.
    {
        super(sLineArcDir);
        m_sXodrDir = sXodrDir;
    }
References cc.ctrl.proc.ProcDirection.m_sXodrDir.
Member Function Documentation
combine()
ArrayList< CtrlLineArcs > cc.ctrl.proc.ProcDirection.combine (ArrayList< CtrlLineArcs > oLanes, double dTol) inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 97 of file ProcDirection.java.
    {
        ArrayList<CtrlLineArcs> oLanesByRoads = ProcCtrl.combineLaneByRoad(oLanes, dTol);
        Collections.sort(oLanesByRoads, CtrlLineArcs.CMPBYLANE);
        ArrayList<CtrlLineArcs> oCombined = new ArrayList();
        int nIndex = oLanesByRoads.size();
        while (nIndex-- > 0)
        {
            CtrlLineArcs oCla = oLanesByRoads.get(nIndex);
            String sRoadId = Integer.toString(XodrUtil.getRoadId(oCla.m_nLaneId));
            if (m_oJunctions.containsKey(sRoadId))
            {
                oLanesByRoads.remove(nIndex);
                oCombined.add(oCla);
            }
        }
        int nLimit = oLanesByRoads.size();
        double dSqTol = dTol * dTol;
        for (int nOuter = 0; nOuter < nLimit; nOuter++)
        {
            CtrlLineArcs oCur = oLanesByRoads.get(nOuter);
            for (int nInner = 0; nInner < nLimit; nInner++)
            {
                if (nOuter == nInner)
                    continue;
                CtrlLineArcs oCmp = oLanesByRoads.get(nInner);
                if (oCmp.m_nLaneType != oCur.m_nLaneType)
                    continue;
                int nConnect = oCur.connects(oCmp, dSqTol);
                if (nConnect == CtrlLineArcs.CON_TEND_OSTART || nConnect == CtrlLineArcs.CON_TSTART_OEND) // the pts of both lines are in the same direction
                {
                    oCur.combine(oCmp, nConnect); // combine the points of oCmp into oCur's point array
                    oLanesByRoads.remove(nInner);
                    --nLimit;
                    nInner = -1; // start inner loop over
                }
            }
            oCombined.add(oCur);
        }
        return oCombined;
    }
References cc.ctrl.CtrlLineArcs.CMPBYLANE, cc.ctrl.CtrlLineArcs.combine(), cc.ctrl.proc.ProcCtrl.combineLaneByRoad(), cc.ctrl.CtrlLineArcs.CON_TEND_OSTART, cc.ctrl.CtrlLineArcs.CON_TSTART_OEND, cc.ctrl.CtrlLineArcs.connects(), cc.geosrv.xodr.XodrUtil.getRoadId(), cc.ctrl.CtrlLineArcs.m_nLaneId, cc.ctrl.CtrlLineArcs.m_nLaneType, and cc.ctrl.proc.ProcDirection.m_oJunctions.
Referenced by cc.ctrl.proc.ProcDirection.proc().
parseMetadata()
void cc.ctrl.proc.ProcDirection.parseMetadata (Path oSource) throws Exception inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 52 of file ProcDirection.java.
    {
        m_oJunctions = new XodrJunctionParser().parseXodrIntersections(oSource);
    }
References cc.ctrl.proc.ProcDirection.m_oJunctions, and cc.geosrv.xodr.XodrJunctionParser.parseXodrIntersections().
Referenced by cc.ctrl.proc.ProcDirection.proc().
proc()
void cc.ctrl.proc.ProcDirection.proc (String sLineArcsFile, double dTol) throws Exception inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 60 of file ProcDirection.java.
    {
        try
        {
            parseMetadata(Paths.get(m_sXodrDir + sLineArcsFile.substring(sLineArcsFile.lastIndexOf("/")).replace(".bin", ".xodr")));
            ArrayList<TrafCtrl> oCtrls = new ArrayList();
            ArrayList<CtrlLineArcs> oLineArcs = new ArrayList();
            try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(Paths.get(sLineArcsFile)))))
            {
                while (oIn.available() > 0)
                {
                    oLineArcs.add(new CtrlLineArcs(oIn));
                }
            }
            oLineArcs = combine(oLineArcs, dTol);
            ArrayList<int[]> nTiles = new ArrayList();
            int nShoulder = XodrUtil.getLaneType("shoulder");
            for (CtrlLineArcs oCLA : oLineArcs)
            {
                TrafCtrl oCtrl = new TrafCtrl("direction", "forward", 0, oCLA.m_dLineArcs, "", true, CC);
                if (oCLA.m_nLaneType != nShoulder)
                    oCtrls.add(oCtrl);
                oCtrl.write(g_sTrafCtrlDir, g_dExplodeStep, g_nDefaultZoom, CC);
                updateTiles(nTiles, oCtrl.m_oFullGeo.m_oTiles);
            }
            renderTiledData(oCtrls, nTiles);
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.ctrl.proc.ProcCtrl.CC, cc.ctrl.proc.ProcDirection.combine(), cc.ctrl.proc.ProcCtrl.g_dExplodeStep, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTrafCtrlDir, cc.geosrv.xodr.XodrUtil.getLaneType(), cc.ctrl.TrafCtrl.m_oFullGeo, cc.ctrl.CtrlGeo.m_oTiles, cc.ctrl.proc.ProcDirection.m_sXodrDir, cc.util.FileUtil.newInputStream(), cc.ctrl.proc.ProcDirection.parseMetadata(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcCtrl.updateTiles(), and cc.ctrl.TrafCtrl.write().
renderTiledData()
static void cc.ctrl.proc.ProcDirection.renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException inline static
Definition at line 144 of file ProcDirection.java.
    {
        String[] sEmpty = new String[0];
        TdLayer oLayer = new TdLayer("direction", sEmpty, sEmpty, TdLayer.LINESTRING);
        int[] nTags = new int[0];
        double[] dPt = new double[2];
        double[] dPoint = new double[2];
        double[] dLine = new double[ARROW[0].length + 1];
        double[] dHead = new double[ARROW[1].length + 1];
        dLine[0] = dLine.length;
        dHead[0] = dHead.length;
        int nLinePts = ARROW[0].length / 2;
        int nHeadPts = ARROW[1].length / 2;
        for (int[] nTile : nTiles)
        {
            int nX = nTile[0];
            int nY = nTile[1];
            Files.createDirectories(Paths.get(String.format(g_sTdFileFormat, nX, 0, 0, 0)).getParent(), FileUtil.DIRPERS);
            writeIndexFile(oCtrls, nX, nY);
            oLayer.clear();
            double[] dClipBounds = TileUtil.getClippingBounds(g_nDefaultZoom, nX, nY);
            for (TrafCtrl oCtrl : oCtrls)
            {
                CtrlGeo oFullGeo = oCtrl.m_oFullGeo;
                if (Collections.binarySearch(oFullGeo.m_oTiles, nTile, Mercator.TILECOMP) < 0 || oFullGeo.m_dLength < LENLOWTH || oFullGeo.m_dAverageWidth < WIDTHTH)
                    continue;
                int nArrows = 2 + ((int)(oFullGeo.m_dLength / LENLOWTH) - 1) * 2;
                double dPercentStep = 1.0 / (nArrows + 1);
                for (int nIndex = 1; nIndex <= nArrows; nIndex++)
                {
                    boolean bForward = TrafCtrlEnums.getCtrlVal("direction", "forward") == MathUtil.bytesToInt(oCtrl.m_yControlValue);
                    double dHdg = getCoordAndHeadingAtLength(oFullGeo.m_dC, oFullGeo.m_dLength * dPercentStep * nIndex, !bForward, dPt);
                    if (Double.isNaN(dHdg))
                        continue;
                    AffineTransform oAt = new AffineTransform();
                    oAt.translate(dPt[0], dPt[1]);
                    oAt.rotate(dHdg, 0, 0);
                    oAt.transform(ARROW[0], 0, dLine, 1, nLinePts);
                    oAt.transform(ARROW[1], 0, dHead, 1, nHeadPts);
                    double[] dArrowBounds = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE};
                    Iterator<double[]> oIt = Arrays.iterator(dLine, dPoint, 1, 2);
                    while (oIt.hasNext())
                    {
                        oIt.next();
                        Geo.updateBounds(dPoint[0], dPoint[1], dArrowBounds);
                    }
                    oIt = Arrays.iterator(dHead, dPoint, 1, 2);
                    while (oIt.hasNext())
                    {
                        oIt.next();
                        Geo.updateBounds(dPoint[0], dPoint[1], dArrowBounds);
                    }
                    if (Geo.boundingBoxesIntersect(dClipBounds[0], dClipBounds[1], dClipBounds[2], dClipBounds[3], dArrowBounds[0], dArrowBounds[1], dArrowBounds[2], dArrowBounds[3]))
                    {
                        oLayer.add(new TdFeature(dLine, nTags, oCtrl));
                        oLayer.add(new TdFeature(dHead, nTags, oCtrl));
                    }
                }
                if (!oLayer.isEmpty())
                {
                    try (DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(String.format(g_sTdFileFormat, nX, g_nDefaultZoom, nX, nY)), FileUtil.APPENDTO, FileUtil.FILEPERS))))
                    {
                        oLayer.write(oOut);
                    }
                }
            }
        }
    }
References cc.util.FileUtil.APPENDTO, cc.ctrl.proc.ProcDirection.ARROW, cc.util.Geo.boundingBoxesIntersect(), cc.util.MathUtil.bytesToInt(), cc.util.FileUtil.DIRPERS, cc.util.FileUtil.FILEPERS, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTdFileFormat, cc.util.TileUtil.getClippingBounds(), cc.ctrl.proc.ProcCtrl.getCoordAndHeadingAtLength(), cc.ctrl.TrafCtrlEnums.getCtrlVal(), cc.util.Arrays.iterator(), cc.ctrl.proc.ProcCtrl.LENLOWTH, cc.ctrl.proc.TdLayer.LINESTRING, cc.ctrl.CtrlGeo.m_dAverageWidth, cc.ctrl.CtrlGeo.m_dC, cc.ctrl.CtrlGeo.m_dLength, cc.ctrl.CtrlGeo.m_oTiles, cc.util.FileUtil.newOutputStream(), cc.geosrv.Mercator.TILECOMP, cc.util.Geo.updateBounds(), cc.ctrl.proc.ProcCtrl.WIDTHTH, cc.ctrl.proc.TdLayer.write(), and cc.ctrl.proc.ProcCtrl.writeIndexFile().
Referenced by cc.ctrl.CreateCtrls.createCtrl(), cc.ctrl.RenderCtrl.main(), cc.ctrl.proc.ProcDirection.proc(), cc.ctrl.proc.ProcCtrl.renderCtrls(), and cc.ws.CtrlTiles.splitLineArcs().
Member Data Documentation
ARROW
final double [][] cc.ctrl.proc.ProcDirection.ARROW = new double[][]{new double[]{-0.5,0.0,0.5,0.0}, new double[]{0.15,0.35,0.5,0.0,0.15,-0.35}} static private
Definition at line 42 of file ProcDirection.java.
Referenced by cc.ctrl.proc.ProcDirection.renderTiledData().
m_oJunctions
HashMap<String, String> cc.ctrl.proc.ProcDirection.m_oJunctions private
Definition at line 40 of file ProcDirection.java.
Referenced by cc.ctrl.proc.ProcDirection.combine(), and cc.ctrl.proc.ProcDirection.parseMetadata().
m_sXodrDir
String cc.ctrl.proc.ProcDirection.m_sXodrDir private
Definition at line 41 of file ProcDirection.java.
Referenced by cc.ctrl.proc.ProcDirection.ProcDirection(), and cc.ctrl.proc.ProcDirection.proc().
The documentation for this class was generated from the following file:
src/cc/ctrl/proc/ProcDirection.java