Carma-cloud: cc.ws.RsmServlet Class Reference
cc.ws.RsmServlet Class Reference
Public Member Functions
void init (ServletConfig oConfig) throws ServletException
void destroy ()
Private Attributes
RsmCollect m_oCollector
Timer m_oTimer
String m_sRsmFile
Detailed Description
Author
aaron.cherney
Definition at line 28 of file RsmServlet.java.
Member Function Documentation
destroy()
void cc.ws.RsmServlet.destroy () inline
Definition at line 94 of file RsmServlet.java.
    {
        try
        {
            m_oCollector.writeCurrent();
        }
        catch (IOException oEx)
        {
        }
        m_oTimer.cancel();
    }
References cc.ws.RsmServlet.m_oCollector, cc.ws.RsmServlet.m_oTimer, and cc.rsm.RsmCollect.writeCurrent().
init()
void cc.ws.RsmServlet.init (ServletConfig oConfig) throws ServletException inline
Definition at line 35 of file RsmServlet.java.
    {
        String sUser = oConfig.getInitParameter("user");
        String sPw = oConfig.getInitParameter("pw");
        String sBaseUrl = oConfig.getInitParameter("url");
        String sFile = oConfig.getInitParameter("file");
        HashMap<String, double[]> oAdjustmentMap = new HashMap();
        Enumeration<String> oParas = oConfig.getInitParameterNames();
        while (oParas.hasMoreElements())
        {
            String sPara = oParas.nextElement();
            if (sPara.startsWith("rsm-"))
            {
                String[] sVals = oConfig.getInitParameter(sPara).split(",");
                String sName = sPara.substring("rsm-".length());
                oAdjustmentMap.put(sName, new double[]{Double.parseDouble(sVals[0]), Double.parseDouble(sVals[1])});
            }
        }
        String[] sVals = oConfig.getInitParameter("defaultoffsets").split(",");
        oAdjustmentMap.put("default", new double[]{Double.parseDouble(sVals[0]), Double.parseDouble(sVals[1])});
        m_sRsmFile = sFile;
        int nPeriod = Integer.parseInt(oConfig.getInitParameter("period")); // unit is minutes
        if (sUser == null || sPw == null || sBaseUrl == null || sFile == null)
        {
            throw new ServletException("Invalid configuration");
        }
        m_oTimer = new Timer();
        m_oCollector = new RsmCollect(sUser, sPw, sBaseUrl, sFile, oAdjustmentMap);
        try
        {
            Files.createDirectories(Paths.get(sFile).getParent());
            m_oCollector.readCurrent();
        }
        catch (IOException oEx)
        {
            throw new ServletException(oEx);
        }
        m_oCollector.run();
        GregorianCalendar oCal = new GregorianCalendar(TimeZone.getTimeZone("UTC"));
        oCal.set(Calendar.MILLISECOND, 0);
        oCal.set(Calendar.SECOND, 0);
        oCal.set(Calendar.MINUTE, (oCal.get(Calendar.MINUTE) / nPeriod) * nPeriod + nPeriod); // determine the next execution period with no midnight offset
        m_oTimer.scheduleAtFixedRate(m_oCollector, oCal.getTime(), 60 * 1000 * nPeriod);
//      try
//      {
//          new RsmParser().parseRequest(new BufferedInputStream(Files.newInputStream(Paths.get("/home/cherneya/rsm-xml--tfhrc-example--main-road--1-of-3.xml"))));
//          new RsmParser().parseRequest(new BufferedInputStream(Files.newInputStream(Paths.get("/home/cherneya/rsm-xml--accuracy-test-1--prairie-center-cir--1-of-3.xml"))));
//      }
//      catch (Exception oEx)
//      {
//          throw new ServletException(oEx);
//      }
    }
References cc.ws.RsmServlet.m_oCollector, cc.ws.RsmServlet.m_oTimer, cc.ws.RsmServlet.m_sRsmFile, cc.rsm.RsmCollect.readCurrent(), and cc.rsm.RsmCollect.run().
Member Data Documentation
m_oCollector
RsmCollect cc.ws.RsmServlet.m_oCollector private
Definition at line 30 of file RsmServlet.java.
Referenced by cc.ws.RsmServlet.destroy(), and cc.ws.RsmServlet.init().
m_oTimer
Timer cc.ws.RsmServlet.m_oTimer private
Definition at line 31 of file RsmServlet.java.
Referenced by cc.ws.RsmServlet.destroy(), and cc.ws.RsmServlet.init().
m_sRsmFile
String cc.ws.RsmServlet.m_sRsmFile private
Definition at line 32 of file RsmServlet.java.
Referenced by cc.ws.RsmServlet.init().
The documentation for this class was generated from the following file:
src/cc/ws/RsmServlet.java