Carma-cloud: cc.geosrv.xodr.geo.XodrGeoParser Class Reference
cc.geosrv.xodr.geo.XodrGeoParser Class Reference
Public Member Functions
XodrGeoParser (String sTrackFile)
void startCDATA ()
void endCDATA () throws SAXException
void characters (char[] cBuf, int nPos, int nLen)
void startElement (String sUri, String sLocalName, String sQname, Attributes iAtt) throws SAXException
void endElement (String sUri, String sLocalName, String sQname) throws SAXException
boolean parseXodrToCLA (Path oXodrFile, String sDir) throws Exception
Protected Attributes
boolean m_bCdata
double m_dS
double m_dX
double m_dY
double m_dH
double m_dL
Road m_oRoad
LaneSection m_oLaneSection
Lane m_oLane
Proj m_oProj
final double[] m_dPoint = new double[2]
final StringBuilder m_sBuf = new StringBuilder()
final ArrayList< CtrlLineArcs > m_oCtrlLineArcs = new ArrayList()
String m_sCtrlFile
String m_sBaseDir
double m_dMaxStep = 0.06
double m_dLineTol = 0.1
boolean m_bSignal
double[] m_dBB = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE}
SimpleDateFormat m_oSDF = new SimpleDateFormat("HH:mm:ss:SSS")
boolean m_bLane = false
int m_nShort = 0
int m_nRoads = 0
String m_sTrackFile
boolean m_bSkip = false
Private Member Functions
void writeClas (String sType)
void writeTrack ()
void writeSpeeds (Road oRoad)
Detailed Description
Author
Federal Highway Administration
Definition at line 33 of file XodrGeoParser.java.
Constructor & Destructor Documentation
XodrGeoParser()
cc.geosrv.xodr.geo.XodrGeoParser.XodrGeoParser (String sTrackFile) inline
Definition at line 62 of file XodrGeoParser.java.
    {
        super();
        m_sTrackFile = sTrackFile;
    }
References cc.geosrv.xodr.geo.XodrGeoParser.m_sTrackFile.
Member Function Documentation
characters()
void cc.geosrv.xodr.geo.XodrGeoParser.characters (char[] cBuf, int nPos, int nLen) inline
Definition at line 96 of file XodrGeoParser.java.
    {
        if (m_bCdata)
            m_sBuf.append(cBuf, nPos, nLen);
    }
References cc.geosrv.xodr.geo.XodrGeoParser.m_bCdata, and cc.geosrv.xodr.geo.XodrGeoParser.m_sBuf.
endCDATA()
void cc.geosrv.xodr.geo.XodrGeoParser.endCDATA () throws SAXException inline
Definition at line 78 of file XodrGeoParser.java.
    {
        try
        {
            Text.removeWhitespace(m_sBuf);
            m_oProj = new Proj(m_sBuf.toString(), "epsg:3785"); // projection object used to convert xodr geometry to spherical mercator
//          m_oProj = new Proj(m_sBuf.toString(), "epsg:4326"); // projection object used to convert xodr geometry to lon/lats
        }
        catch (Exception oEx)
        {
            throw new SAXException(oEx);
        }
        m_bCdata = false;
    }
References cc.geosrv.xodr.geo.XodrGeoParser.m_bCdata, cc.geosrv.xodr.geo.XodrGeoParser.m_oProj, cc.geosrv.xodr.geo.XodrGeoParser.m_sBuf, and cc.util.Text.removeWhitespace().
endElement()
void cc.geosrv.xodr.geo.XodrGeoParser.endElement (String sUri, String sLocalName, String sQname) throws SAXException inline
Definition at line 209 of file XodrGeoParser.java.
    {
        switch (sQname)
        {
            case "road":
            {
                if (m_bSkip)
                    break;
//              if (++m_nRoads > 1)
//                  break;
                if (m_oRoad.m_oLaneOffsets.isEmpty())
                    m_oRoad.m_oLaneOffsets.add(new LaneOffset(0.0, 0.0, 0.0, 0.0, 0.0));
                Collections.sort(m_oRoad.m_oLaneOffsets);
                Collections.sort(m_oRoad.m_oGeometries);
                m_oRoad.adjustSections(m_dMaxStep);
                if (m_oRoad.m_oGeometries.isEmpty())
                {
                    System.out.println(String.format("Road %d has no geometries.", m_oRoad.m_nId));
                    break;
                }
                m_oRoad.createPoints(m_dMaxStep, m_oProj);
                m_oRoad.setLaneIds(m_dMaxStep);
                m_oRoad.getDirectionCtrlLineArcs(m_oCtrlLineArcs, m_dLineTol);
//              int nLanes = 0;
//              System.out.println(String.format("%2.7f, %2.7f", Mercator.xToLon(m_oRoad.m_dTrack[5]), Mercator.yToLat(m_oRoad.m_dTrack[6])));
//              ++m_nRoads;
//              if (m_oRoad.m_dLength >= 5)
//                  break;
//              if (m_oRoad.m_dLength < 5)
//                  ++m_nShort;
                if (m_oRoad.m_dLength < m_dMaxStep)
                {
                    System.out.println(String.format("%d\t\t%f", m_oRoad.m_nId, m_oRoad.m_dLength));
                    break;
                }
//              for (LaneSection oS : m_oRoad)
//              {
//                  int nTemp = oS.m_oLeft.size() + oS.m_oRight.size();
//                  if (nTemp > nLanes)
//                      nLanes = nTemp;
//              }
//              if (nLanes < 3)
//              {
//                  System.out.println(String.format("%d\t\t%d", m_oRoad.m_nId, nLanes));
//                  break;
//              }
//              System.out.println(String.format("%d has %d lanes", m_oRoad.m_nId, nLanes));
                writeClas("direction");
                m_oCtrlLineArcs.clear();
//              m_oRoad.getPavementCtrlLineArcs(m_oCtrlLineArcs, m_dLineTol);
//              writeClas("pavement");
//              writeTrack();
                writeSpeeds(m_oRoad);
//              System.out.println(String.format("%d\t\t%s", m_oRoad.m_nId, m_oSDF.format(System.currentTimeMillis())));
                break;
            }
            case "laneSection":
            {
                m_oLaneSection.sortLanes();
                m_oRoad.add(m_oLaneSection);
                break;
            }
            case "lane":
            {
                Collections.sort(m_oLane);
                if (m_oLane.m_nLaneIndex == 0)
                    m_oLaneSection.m_oCenter = m_oLane;
                m_oLaneSection.add(m_oLane);
                m_bLane = false;
                break;
            }
            default:
                break;
        }
    }
References cc.geosrv.xodr.geo.LaneSection.add(), cc.geosrv.xodr.geo.Road.adjustSections(), cc.geosrv.xodr.geo.Road.createPoints(), cc.geosrv.xodr.geo.Road.getDirectionCtrlLineArcs(), cc.geosrv.xodr.geo.XodrGeoParser.m_bLane, cc.geosrv.xodr.geo.XodrGeoParser.m_bSkip, cc.geosrv.xodr.geo.Road.m_dLength, cc.geosrv.xodr.geo.XodrGeoParser.m_dLineTol, cc.geosrv.xodr.geo.XodrGeoParser.m_dMaxStep, cc.geosrv.xodr.geo.Road.m_nId, cc.geosrv.xodr.geo.Lane.m_nLaneIndex, cc.geosrv.xodr.geo.XodrGeoParser.m_oCtrlLineArcs, cc.geosrv.xodr.geo.Road.m_oGeometries, cc.geosrv.xodr.geo.XodrGeoParser.m_oLane, cc.geosrv.xodr.geo.Road.m_oLaneOffsets, cc.geosrv.xodr.geo.XodrGeoParser.m_oLaneSection, cc.geosrv.xodr.geo.XodrGeoParser.m_oProj, cc.geosrv.xodr.geo.XodrGeoParser.m_oRoad, cc.geosrv.xodr.geo.Road.setLaneIds(), cc.geosrv.xodr.geo.LaneSection.sortLanes(), cc.geosrv.xodr.geo.XodrGeoParser.writeClas(), and cc.geosrv.xodr.geo.XodrGeoParser.writeSpeeds().
parseXodrToCLA()
boolean cc.geosrv.xodr.geo.XodrGeoParser.parseXodrToCLA (Path oXodrFile, String sDir) throws Exception inline
Definition at line 471 of file XodrGeoParser.java.
    {
        if (!sDir.endsWith("/"))
            sDir += '/';
        m_sBaseDir = sDir;
        Path oDir = Paths.get(sDir);
        Files.createDirectories(oDir, FileUtil.DIRPERS);
        Files.createDirectories(Paths.get(m_sBaseDir + "pavement"), FileUtil.DIRPERS);
        Files.createDirectories(Paths.get(m_sBaseDir + "direction"), FileUtil.DIRPERS);
        m_sCtrlFile = oXodrFile.getFileName().toString().replace(".xodr", ".bin");
        boolean bProcess = true;
        Path oPavementFile = Paths.get(m_sBaseDir + "pavement/" + m_sCtrlFile);
        Path oLaneFile = Paths.get(m_sBaseDir + "direction/" + m_sCtrlFile);
        if (Files.exists(oLaneFile) && Files.isRegularFile(oLaneFile))
            bProcess = false;
        if (bProcess)
        {
            System.out.println(oXodrFile.toString());
            if (Files.exists(oPavementFile) && Files.isRegularFile(oPavementFile))
               Files.delete(oPavementFile);
            if (Files.exists(oLaneFile) && Files.isRegularFile(oLaneFile))
                Files.delete(oLaneFile);
            XMLReader iXmlReader = SAXParserFactory.newInstance().
            newSAXParser().getXMLReader();
            iXmlReader.setContentHandler(this);
            iXmlReader.setProperty("http://xml.org/sax/properties/lexical-handler", this);
            iXmlReader.parse(new InputSource(new BufferedInputStream(Files.newInputStream(oXodrFile))));
        }
//      double[] dBounds = new double[4];
//      try (BufferedWriter oOut = new BufferedWriter(Channels.newWriter(Files.newByteChannel(Paths.get("/dev/shm/19tiles.csv"), FileUtil.APPENDTO, FileUtil.FILEPERS), "UTF-8")))
//      {
//          for (int nX = 149783; nX <= 149787; nX++)
//          {
//              for (int nY = 200452; nY <= 200474; nY++)
//              {
//                  oOut.append(String.format("19,%d,%d", nX, nY));
//                  Mercator.getInstance().tileBounds(nX, nY, 19, dBounds);
//                  oOut.append(String.format(",%7.2f,%7.2f,%7.2f,%7.2f\n", dBounds[0], dBounds[1], dBounds[2], dBounds[3]));
//              }
//          }
//      }
//      double dMidX = (m_dBB[0] + m_dBB[2]) / 2;
//      double dMidY = (m_dBB[1] + m_dBB[3]) / 2;
//      System.out.println(Mercator.xToLon(dMidX) + " " + Mercator.yToLat(dMidY));
//      System.out.println(String.format("%d roads out of %d less than 5 meters", m_nShort, m_nRoads));
        return bProcess;
    }
References cc.util.FileUtil.DIRPERS, cc.geosrv.xodr.geo.XodrGeoParser.m_sBaseDir, and cc.geosrv.xodr.geo.XodrGeoParser.m_sCtrlFile.
startCDATA()
void cc.geosrv.xodr.geo.XodrGeoParser.startCDATA () inline
Definition at line 70 of file XodrGeoParser.java.
    {
        m_sBuf.setLength(0);
        m_bCdata = true;
    }
References cc.geosrv.xodr.geo.XodrGeoParser.m_bCdata, and cc.geosrv.xodr.geo.XodrGeoParser.m_sBuf.
startElement()
void cc.geosrv.xodr.geo.XodrGeoParser.startElement (String sUri, String sLocalName, String sQname, Attributes iAtt) throws SAXException inline
Definition at line 104 of file XodrGeoParser.java.
    {
        try
        {
            switch (sQname)
            {
                case "road":
                {
                    m_bSkip = false;
                    m_oCtrlLineArcs.clear();
                    m_oRoad = new Road(Integer.parseInt(iAtt.getValue("id")), Double.parseDouble(iAtt.getValue("length"))); // new road geometry
//                  System.out.println(String.format("%d\t%5.2f\t%s", m_oRoad.m_nId, m_oRoad.m_dLength, m_oSDF.format(System.currentTimeMillis())));
                    Arrays.add(m_oRoad.m_dTrack, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                    Arrays.add(m_oRoad.m_dLaneZero, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                    Arrays.add(m_oRoad.m_dNoProj, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                    break;
                }
                case "geometry":
                {
                    m_dS = XodrUtil.parseDouble(iAtt.getValue("s"));
                    m_dX = XodrUtil.parseDouble(iAtt.getValue("x"));
                    m_dY = XodrUtil.parseDouble(iAtt.getValue("y"));
                    m_dH = XodrUtil.parseDouble(iAtt.getValue("hdg"));
                    m_dL = XodrUtil.parseDouble(iAtt.getValue("length"));
                    break;
                }
                case "spiral":
                case "line":
                {
                    if (Double.isFinite(m_dS) && Double.isFinite(m_dX) && Double.isFinite(m_dY) && Double.isFinite(m_dH) && Double.isFinite(m_dL))
                        m_oRoad.m_oGeometries.add(new Line(m_dS, m_dX, m_dY, m_dH, m_dL));
                    break;
                }
                case "arc":
                {
                    double dCurvature = XodrUtil.parseDouble(iAtt.getValue("curvature"));
                    if (Double.isFinite(m_dS) && Double.isFinite(m_dX) && Double.isFinite(m_dY) && Double.isFinite(m_dH) && Double.isFinite(m_dL))
                        m_oRoad.m_oGeometries.add(new Arc(m_dS, m_dX, m_dY, m_dH, m_dL, dCurvature));
                    break;
                }
                case "laneOffset":
                {
                    double dS = XodrUtil.parseDouble(iAtt.getValue("s"));
                    double dA = XodrUtil.parseDouble(iAtt.getValue("a"));
                    double dB = XodrUtil.parseDouble(iAtt.getValue("b"));
                    double dC = XodrUtil.parseDouble(iAtt.getValue("c"));
                    double dD = XodrUtil.parseDouble(iAtt.getValue("d"));
                    if (Double.isFinite(dS) && Double.isFinite(dA) && Double.isFinite(dB) && Double.isFinite(dC) && Double.isFinite(dD))
                        m_oRoad.m_oLaneOffsets.add(new LaneOffset(dS, dA, dB, dC, dD));
                    break;
                }
                case "laneSection":
                {
                    double dS = XodrUtil.parseDouble(iAtt.getValue("s"));
                    if (Double.isFinite(dS))
                        m_oLaneSection = new LaneSection(dS, m_oRoad.size());
                    break;
                }
                case "lane":
                {
                    m_oLane = new Lane(Integer.parseInt(iAtt.getValue("id")), iAtt.getValue("type"), m_oRoad.m_nId, m_oRoad.size(), m_oRoad.m_nMaxSpeed);
                    m_bLane = true;
                    break;
                }
                case "width":
                {
                    double dS = XodrUtil.parseDouble(iAtt.getValue("sOffset"));
                    double dA = XodrUtil.parseDouble(iAtt.getValue("a"));
                    double dB = XodrUtil.parseDouble(iAtt.getValue("b"));
                    double dC = XodrUtil.parseDouble(iAtt.getValue("c"));
                    double dD = XodrUtil.parseDouble(iAtt.getValue("d"));
                    if (Double.isFinite(dS) && Double.isFinite(dA) && Double.isFinite(dB) && Double.isFinite(dC) && Double.isFinite(dD))
                        m_oLane.add(new LaneWidth(dS, dA, dB, dC, dD));
                    break;
                }
                case "speed":
                {
                    double dMax = XodrUtil.parseDouble(iAtt.getValue("max"));
                    if (Double.isFinite(dMax))
                    {
                        if (m_bLane)
                            m_oLane.m_nMaxSpeed = (int)dMax;
                        else
                            m_oRoad.m_nMaxSpeed = (int)dMax;
                    }
                }
                default:
                    break;
            }
        }
        catch (Exception oEx)
        {
            System.out.println("Error parsing Road " + m_oRoad.m_nId);
            oEx.printStackTrace();
            m_bSkip = true;
        }
    }
References cc.util.Arrays.add(), cc.geosrv.xodr.geo.XodrGeoParser.m_bLane, cc.geosrv.xodr.geo.XodrGeoParser.m_bSkip, cc.geosrv.xodr.geo.XodrGeoParser.m_dH, cc.geosrv.xodr.geo.XodrGeoParser.m_dL, cc.geosrv.xodr.geo.Road.m_dLaneZero, cc.geosrv.xodr.geo.Road.m_dNoProj, cc.geosrv.xodr.geo.XodrGeoParser.m_dS, cc.geosrv.xodr.geo.Road.m_dTrack, cc.geosrv.xodr.geo.XodrGeoParser.m_dX, cc.geosrv.xodr.geo.XodrGeoParser.m_dY, cc.geosrv.xodr.geo.Road.m_nId, cc.geosrv.xodr.geo.Road.m_nMaxSpeed, cc.geosrv.xodr.geo.XodrGeoParser.m_oCtrlLineArcs, cc.geosrv.xodr.geo.Road.m_oGeometries, cc.geosrv.xodr.geo.XodrGeoParser.m_oLane, cc.geosrv.xodr.geo.Road.m_oLaneOffsets, cc.geosrv.xodr.geo.XodrGeoParser.m_oLaneSection, cc.geosrv.xodr.geo.XodrGeoParser.m_oRoad, and cc.geosrv.xodr.XodrUtil.parseDouble().
writeClas()
void cc.geosrv.xodr.geo.XodrGeoParser.writeClas (String sType) inline private
Definition at line 289 of file XodrGeoParser.java.
    {
        try (DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(m_sBaseDir + sType + "/" + m_sCtrlFile), FileUtil.APPENDTO, FileUtil.FILEPERS))))
        {
            for (CtrlLineArcs oCLA : m_oCtrlLineArcs)
                oCLA.write(oOut);
        }
        catch (IOException oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.util.FileUtil.APPENDTO, cc.util.FileUtil.FILEPERS, cc.geosrv.xodr.geo.XodrGeoParser.m_oCtrlLineArcs, cc.geosrv.xodr.geo.XodrGeoParser.m_sBaseDir, cc.geosrv.xodr.geo.XodrGeoParser.m_sCtrlFile, and cc.util.FileUtil.newOutputStream().
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement().
writeSpeeds()
void cc.geosrv.xodr.geo.XodrGeoParser.writeSpeeds (Road oRoad) inline private
Definition at line 405 of file XodrGeoParser.java.
    {
        ArrayList<Lane> oLaneList = new ArrayList();
        ArrayList<Lane> oLanesToWrite = new ArrayList();
        for (LaneSection oS : oRoad)
        {
            oS.getLanes(oLaneList);
            for (Lane oLane : oLaneList)
            {
                if (oLane.m_nLaneIndex == 0)
                    continue;
                int nIndex = Collections.binarySearch(oLanesToWrite, oLane);
                if (nIndex < 0)
                    oLanesToWrite.add(~nIndex, oLane);
            }
        }
        try (DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(m_sBaseDir + "direction/" + m_sCtrlFile + ".spd"), FileUtil.APPENDTO, FileUtil.FILEPERS))))
        {
            for (Lane oLane : oLanesToWrite)
            {
                oOut.writeInt(XodrUtil.getLaneId(oRoad.m_nId, oLane.m_nLaneIdByRoad));
                oOut.writeInt(oLane.m_nMaxSpeed);
            }
        }
        catch (IOException oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.util.FileUtil.APPENDTO, cc.util.FileUtil.FILEPERS, cc.geosrv.xodr.XodrUtil.getLaneId(), cc.geosrv.xodr.geo.Road.m_nId, cc.geosrv.xodr.geo.XodrGeoParser.m_sBaseDir, cc.geosrv.xodr.geo.XodrGeoParser.m_sCtrlFile, and cc.util.FileUtil.newOutputStream().
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement().
writeTrack()
void cc.geosrv.xodr.geo.XodrGeoParser.writeTrack () inline private
Definition at line 303 of file XodrGeoParser.java.
    {
        ArrayList<double[]> dLines = new ArrayList();
        dLines.add(m_oRoad.m_dTrack);
//      Iterator<double[]> it = Arrays.iterator(m_oRoad.m_dNoProj, new double[6], 5, 3);
//      int n = 0;
//      while (it.hasNext())
//      {
//          double[] dSeg = it.next();
//          double dDist = Geo.distance(dSeg[0], dSeg[1], dSeg[3], dSeg[4]);
//          double dHdg = Geo.heading(dSeg[0], dSeg[1], dSeg[3], dSeg[4]);
//          System.out.println(String.format("%d\t%3.4f\t%3.4f\t%3.4f\t%3.4f", n++, dDist, dHdg, dSeg[0], dSeg[1]));
//      }
//      dLines.add(m_oRoad.m_dLaneZero);
        for (LaneSection oS : m_oRoad)
        {
            ArrayList<Lane> oLanes = new ArrayList();
            oS.getLanes(oLanes);
            for (Lane oLane : oLanes)
            {
                if (oLane.m_nLaneIndex == 0)
                    continue;
                dLines.add(oLane.m_dCenter);
//              dLines.add(oLane.m_dOuterW);
            }
        }
        try (DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(m_sTrackFile), FileUtil.APPENDTO, FileUtil.FILEPERS))))
        {
            oOut.writeInt(m_oRoad.m_dGeoPoints.size());
            for (double[] dPt : m_oRoad.m_dGeoPoints)
            {
                oOut.writeDouble(dPt[0]);
                oOut.writeDouble(dPt[1]);
            }
            oOut.writeInt(m_oRoad.m_dLSPoints.size());
            for (double[] dPt : m_oRoad.m_dLSPoints)
            {
                oOut.writeDouble(dPt[0]);
                oOut.writeDouble(dPt[1]);
            }
            oOut.writeInt(m_oRoad.m_dLWPoints.size());
            for (double[] dPt : m_oRoad.m_dLWPoints)
            {
                oOut.writeDouble(dPt[0]);
                oOut.writeDouble(dPt[1]);
            }
            oOut.writeInt(m_oRoad.m_dPerps.size());
            for (double[] dPt : m_oRoad.m_dPerps)
            {
                oOut.writeDouble(dPt[0]);
                oOut.writeDouble(dPt[1]);
                oOut.writeDouble(dPt[2]);
                oOut.writeDouble(dPt[3]);
            }
            oOut.writeInt(dLines.size());
            for (double[] dTrack : dLines)
            {
    //          double[] dTrack = m_oRoad.m_dTrack;
                if (dTrack[1] < m_dBB[0])
                    m_dBB[0] = dTrack[1];
                if (dTrack[2] < m_dBB[1])
                    m_dBB[1] = dTrack[2];
                if (dTrack[3] > m_dBB[2])
                    m_dBB[2] = dTrack[3];
                if (dTrack[4] > m_dBB[3])
                    m_dBB[3] = dTrack[4];
                    oOut.writeInt(m_oRoad.m_nId);
                    int nOrds = (Arrays.size(dTrack) - 5) / 3 * 2;
                    oOut.writeInt(nOrds);
                    for (int i = 1; i < 5; i++)
                        oOut.writeDouble(dTrack[i]);
                    Iterator<double[]> oIt = Arrays.iterator(dTrack, new double[3], 5, 3);
                    double[] dPt = oIt.next();
                    int nCount = 0;
                    double dPx = dPt[0];
                    double dPy = dPt[1];
                    oOut.writeDouble(dPx);
                    oOut.writeDouble(dPy);
                    while (oIt.hasNext())
                    {
                        oIt.next();
                        double dX = dPt[0];
                        double dY = dPt[1];
                        oOut.writeDouble(dX);
                        oOut.writeDouble(dY);
//                      System.out.println(String.format("%d\t%1.4f\t%1.4f", nCount++, Geo.distance(dPx, dPy, dX, dY), Geo.heading(dPx, dPy, dX, dY)));
                        dPx = dX;
                        dPy = dY;
                    }
                }
        }
        catch (IOException oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.util.FileUtil.APPENDTO, cc.util.FileUtil.FILEPERS, cc.util.Arrays.iterator(), cc.geosrv.xodr.geo.XodrGeoParser.m_dBB, cc.geosrv.xodr.geo.Road.m_dGeoPoints, cc.geosrv.xodr.geo.Road.m_dLSPoints, cc.geosrv.xodr.geo.Road.m_dLWPoints, cc.geosrv.xodr.geo.Road.m_dPerps, cc.geosrv.xodr.geo.Road.m_dTrack, cc.geosrv.xodr.geo.Road.m_nId, cc.geosrv.xodr.geo.XodrGeoParser.m_oRoad, cc.geosrv.xodr.geo.XodrGeoParser.m_sTrackFile, cc.util.FileUtil.newOutputStream(), and cc.util.Arrays.size().
Member Data Documentation
m_bCdata
boolean cc.geosrv.xodr.geo.XodrGeoParser.m_bCdata protected
Definition at line 35 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.characters(), cc.geosrv.xodr.geo.XodrGeoParser.endCDATA(), and cc.geosrv.xodr.geo.XodrGeoParser.startCDATA().
m_bLane
boolean cc.geosrv.xodr.geo.XodrGeoParser.m_bLane = false protected
Definition at line 55 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement(), and cc.geosrv.xodr.geo.XodrGeoParser.startElement().
m_bSignal
boolean cc.geosrv.xodr.geo.XodrGeoParser.m_bSignal protected
Definition at line 52 of file XodrGeoParser.java.
m_bSkip
boolean cc.geosrv.xodr.geo.XodrGeoParser.m_bSkip = false protected
Definition at line 59 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement(), and cc.geosrv.xodr.geo.XodrGeoParser.startElement().
m_dBB
double [] cc.geosrv.xodr.geo.XodrGeoParser.m_dBB = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE} protected
Definition at line 53 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
m_dH
double cc.geosrv.xodr.geo.XodrGeoParser.m_dH protected
Definition at line 39 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.startElement().
m_dL
double cc.geosrv.xodr.geo.XodrGeoParser.m_dL protected
Definition at line 40 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.startElement().
m_dLineTol
double cc.geosrv.xodr.geo.XodrGeoParser.m_dLineTol = 0.1 protected
Definition at line 51 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement().
m_dMaxStep
double cc.geosrv.xodr.geo.XodrGeoParser.m_dMaxStep = 0.06 protected
Definition at line 50 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement().
m_dPoint
final double [] cc.geosrv.xodr.geo.XodrGeoParser.m_dPoint = new double[2] protected
Definition at line 45 of file XodrGeoParser.java.
m_dS
double cc.geosrv.xodr.geo.XodrGeoParser.m_dS protected
Definition at line 36 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.startElement().
m_dX
double cc.geosrv.xodr.geo.XodrGeoParser.m_dX protected
Definition at line 37 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.startElement().
m_dY
double cc.geosrv.xodr.geo.XodrGeoParser.m_dY protected
Definition at line 38 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.startElement().
m_nRoads
int cc.geosrv.xodr.geo.XodrGeoParser.m_nRoads = 0 protected
Definition at line 57 of file XodrGeoParser.java.
m_nShort
int cc.geosrv.xodr.geo.XodrGeoParser.m_nShort = 0 protected
Definition at line 56 of file XodrGeoParser.java.
m_oCtrlLineArcs
final ArrayList<CtrlLineArcs> cc.geosrv.xodr.geo.XodrGeoParser.m_oCtrlLineArcs = new ArrayList() protected
Definition at line 47 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement(), cc.geosrv.xodr.geo.XodrGeoParser.startElement(), and cc.geosrv.xodr.geo.XodrGeoParser.writeClas().
m_oLane
Lane cc.geosrv.xodr.geo.XodrGeoParser.m_oLane protected
Definition at line 43 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement(), and cc.geosrv.xodr.geo.XodrGeoParser.startElement().
m_oLaneSection
LaneSection cc.geosrv.xodr.geo.XodrGeoParser.m_oLaneSection protected
Definition at line 42 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement(), and cc.geosrv.xodr.geo.XodrGeoParser.startElement().
m_oProj
Proj cc.geosrv.xodr.geo.XodrGeoParser.m_oProj protected
Definition at line 44 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endCDATA(), and cc.geosrv.xodr.geo.XodrGeoParser.endElement().
m_oRoad
Road cc.geosrv.xodr.geo.XodrGeoParser.m_oRoad protected
Definition at line 41 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement(), cc.geosrv.xodr.geo.XodrGeoParser.startElement(), and cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
m_oSDF
SimpleDateFormat cc.geosrv.xodr.geo.XodrGeoParser.m_oSDF = new SimpleDateFormat("HH:mm:ss:SSS") protected
Definition at line 54 of file XodrGeoParser.java.
m_sBaseDir
String cc.geosrv.xodr.geo.XodrGeoParser.m_sBaseDir protected
Definition at line 49 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.parseXodrToCLA(), cc.geosrv.xodr.geo.XodrGeoParser.writeClas(), and cc.geosrv.xodr.geo.XodrGeoParser.writeSpeeds().
m_sBuf
final StringBuilder cc.geosrv.xodr.geo.XodrGeoParser.m_sBuf = new StringBuilder() protected
Definition at line 46 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.characters(), cc.geosrv.xodr.geo.XodrGeoParser.endCDATA(), and cc.geosrv.xodr.geo.XodrGeoParser.startCDATA().
m_sCtrlFile
String cc.geosrv.xodr.geo.XodrGeoParser.m_sCtrlFile protected
Definition at line 48 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.parseXodrToCLA(), cc.geosrv.xodr.geo.XodrGeoParser.writeClas(), and cc.geosrv.xodr.geo.XodrGeoParser.writeSpeeds().
m_sTrackFile
String cc.geosrv.xodr.geo.XodrGeoParser.m_sTrackFile protected
Definition at line 58 of file XodrGeoParser.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.XodrGeoParser(), and cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/geo/XodrGeoParser.java