Carma-cloud: cc.util.Gpc Class Reference
cc.util.Gpc Class Reference
Static Public Member Functions
static void main (String[] sArgs) throws Exception
Static Public Attributes
static final int DIFF = 0
static final int INT = 1
static final int XOR = 2
static final int UNION = 3
Static Package Functions
[static initializer]
Private Member Functions
Gpc ()
Static Private Member Functions
static native long newPolygon (int nLen, int nOffset, double[] dOrds)
static native int[] getBoundedPolygon (long lGpcPolygon, int nExtra, double[][] dPolygons)
static native int[] getPolygon (long lGpcPolygon, int nReserve, double[][] dPolygons)
static native int op (int nOp, long lGpcPolygonSubject, long lGpcPolygonClip)
static native void freePolygon (long lGpcPolygon)
Detailed Description
Definition at line 4 of file Gpc.java.
Constructor & Destructor Documentation
Gpc()
cc.util.Gpc.Gpc () inline private
Definition at line 18 of file Gpc.java.
    {
    }
Member Function Documentation
[static initializer]()
cc.util.Gpc.[static initializer] inline static package
freePolygon()
static native void cc.util.Gpc.freePolygon (long lGpcPolygon) static private
Release native library allocated polygon. Typically the subject polygon of performed operations.
Parameters
lGpcPolygon the handle to the native library polygon to be freed
Referenced by cc.util.Gpc.main().
getBoundedPolygon()
static native int[] cc.util.Gpc.getBoundedPolygon (long lGpcPolygon, int nExtra, double dPolygons[][]) static private
Copies the set of external polygon vertices specified by handle to an array of double array ordinates in x/y order, and inserts the number of ordinates and computed bounding box in the first five values.
The returned integer array specifies if a polygon at the corresponding index is considered a hole. 0 indicates a solid polygon and 1 indicates a hole.
Note that additional array elements may contain random data.
Parameters
lGpcPolygon a handle to the native library polygon
nExtra reserve additional values for custom purposes
dPolygons an array of polygons represented by double arrays of x/y ordinates, the top level array should be allocated in Java, the native library allocates the second level arrays
Returns
integer array that matches the count of polygons and indicates if a polygon is considered a hole
getPolygon()
static native int[] cc.util.Gpc.getPolygon (long lGpcPolygon, int nReserve, double dPolygons[][]) static private
Copies the set of external polygon vertices specified by handle to an array of double array ordinates in x/y order, reserving any additional
elements requested at the beginning of the array.
The returned integer array specifies if a polygon at the corresponding index is considered a hole. 0 indicates a solid polygon and 1 indicates a hole.
Note that additional array elements may contain random data.
Parameters
lGpcPolygon a handle to the native library polygon
nReserve reserve additional values for custom purposes
dPolygons an array of polygons represented by double arrays of x/y ordinates, the top level array should be allocated in Java, the native library allocates the second level arrays
Returns
integer array that matches the count of polygons and indicates if a polygon is considered a hole
Referenced by cc.util.Gpc.main().
main()
static void cc.util.Gpc.main (String[] sArgs) throws Exception inline static
Definition at line 107 of file Gpc.java.
    {
        double[] dOrds1 = new double[]{0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 0.0, 1.0, 0.0};
        double[] dOrds2 = new double[]{0.0, 1.0, 0.0, 2.0, 1.0, 2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0};
        long lPoly1 = Gpc.newPolygon(dOrds1.length, 0, dOrds1);
        long lPoly2 = Gpc.newPolygon(dOrds2.length, 0, dOrds2);
        int nCount = Gpc.op(Gpc.UNION, lPoly1, lPoly2);
        double[][] dPolygons = new double[nCount][];
        int[] nHoles = Gpc.getPolygon(lPoly1, 0, dPolygons);
        Gpc.freePolygon(lPoly1);
        for (int nIndex = 0; nIndex < nHoles.length; nIndex++)
            System.out.println(nHoles[nIndex]);
        for (double[] dPolygon : dPolygons)
        {
            System.out.println();
            for (int nIndex = 0; nIndex < dPolygon.length; nIndex++)
                System.out.println(dPolygon[nIndex]);
        }
    }
References cc.util.Gpc.freePolygon(), cc.util.Gpc.getPolygon(), cc.util.Gpc.newPolygon(), cc.util.Gpc.op(), and cc.util.Gpc.UNION.
newPolygon()
static native long cc.util.Gpc.newPolygon (int nLen, int nOffset, double[] dOrds) static private
Allocates a new polygon in the native library, and copies the number of ordinates specified by length from the array ordinates in x/y order starting at the offset position.
Parameters
nLen the number of double values to copy
nOffset starting index of double array
dOrds double array of values in x/y order
Returns
handle to native library allocated polygon
Referenced by cc.util.Gpc.main().
op()
static native int cc.util.Gpc.op (int nOp, long lGpcPolygonSubject, long lGpcPolygonClip) static private
Perform polygon clipping operation. Supported operations are difference, intersection, exclusive or, and union. The subject polygon handle will remain unchanged and point to the resulting polygon. The clip polygon will be automatically released.
Parameters
nOp enumerated value specifying the operation to perform
lGpcPolygonSubject a handle to the first native library polygon for the operation
lGpcPolygonClip a handle to the second native library polygon for the operation
Returns
the count of polygons in the resulting set
Referenced by cc.util.Gpc.main().
Member Data Documentation
DIFF
final int cc.util.Gpc.DIFF = 0 static
Definition at line 6 of file Gpc.java.
INT
final int cc.util.Gpc.INT = 1 static
Definition at line 7 of file Gpc.java.
UNION
final int cc.util.Gpc.UNION = 3 static
Definition at line 9 of file Gpc.java.
Referenced by cc.util.Gpc.main().
XOR
final int cc.util.Gpc.XOR = 2 static
Definition at line 8 of file Gpc.java.
The documentation for this class was generated from the following file:
src/cc/util/Gpc.java