Carma-cloud: cc.util.CsvReader Class Reference
cc.util.CsvReader Class Reference
Public Member Functions
CsvReader (InputStream oInputStream, int nCols)
CsvReader (InputStream oInputStream)
CsvReader (InputStream oInputStream, char cDelim)
int readLine () throws IOException
boolean isNull (int nCol) throws IndexOutOfBoundsException
double parseDouble (int nCol) throws IndexOutOfBoundsException, NumberFormatException
long parseLong (int nCol) throws IndexOutOfBoundsException, NumberFormatException
float parseFloat (int nCol) throws IndexOutOfBoundsException, NumberFormatException
int parseInt (int nCol) throws IndexOutOfBoundsException, NumberFormatException
String parseString (int nCol) throws IndexOutOfBoundsException
int parseString (StringBuilder sBuf, int nCol) throws IndexOutOfBoundsException, NullPointerException
Public Member Functions inherited from cc.util.BufferedInStream
BufferedInStream (InputStream oInputStream, int nSize)
BufferedInStream (InputStream oInputStream)
int read () throws IOException
int read (byte[] yBuf, int nOff, int nLen) throws IOException
long skip (long lBytes) throws IOException
Protected Attributes
int m_nCol
int[] m_nColEnds
StringBuilder m_sBuf = new StringBuilder(BUFFER_SIZE)
char m_cDelim = ','
Static Protected Attributes
static final int DEFAULT_COLS = 80
Static Protected Attributes inherited from cc.util.BufferedInStream
static final int BUFFER_SIZE = 8192
Private Member Functions
void addCol ()
int getStart (int nCol)
int getEnd (int nCol)
Detailed Description
Definition at line 7 of file CsvReader.java.
Constructor & Destructor Documentation
CsvReader() [1/3]
cc.util.CsvReader.CsvReader (InputStream oInputStream, int nCols) inline
Definition at line 16 of file CsvReader.java.
    {
        super(oInputStream);
        m_nColEnds = new int[nCols];
    }
References cc.util.CsvReader.m_nColEnds.
CsvReader() [2/3]
cc.util.CsvReader.CsvReader (InputStream oInputStream) inline
Definition at line 23 of file CsvReader.java.
    {
        this(oInputStream, DEFAULT_COLS);
    }
References cc.util.CsvReader.DEFAULT_COLS.
CsvReader() [3/3]
cc.util.CsvReader.CsvReader (InputStream oInputStream, char cDelim) inline
Definition at line 29 of file CsvReader.java.
    {
        this(oInputStream, DEFAULT_COLS);
        m_cDelim = cDelim;
    }
References cc.util.CsvReader.DEFAULT_COLS, and cc.util.CsvReader.m_cDelim.
Member Function Documentation
addCol()
void cc.util.CsvReader.addCol () inline private
Definition at line 63 of file CsvReader.java.
    {
        if (m_nCol == m_nColEnds.length) // extend column end array
        {
            int[] nColEnds = new int[m_nCol * 2];
            System.arraycopy(m_nColEnds, 0, nColEnds, 0, m_nCol);
            m_nColEnds = nColEnds;
        }
        m_nColEnds[m_nCol++] = m_sBuf.length();
    }
References cc.util.CsvReader.m_nCol, cc.util.CsvReader.m_nColEnds, and cc.util.CsvReader.m_sBuf.
Referenced by cc.util.CsvReader.readLine().
getEnd()
int cc.util.CsvReader.getEnd (int nCol) inline private
Definition at line 88 of file CsvReader.java.
    {
        if (nCol < m_nCol)
            return m_nColEnds[nCol];
        return -1; // force index out of bounds
    }
References cc.util.CsvReader.m_nCol, and cc.util.CsvReader.m_nColEnds.
Referenced by cc.util.CsvReader.isNull(), cc.util.CsvReader.parseDouble(), cc.util.CsvReader.parseInt(), cc.util.CsvReader.parseLong(), and cc.util.CsvReader.parseString().
getStart()
int cc.util.CsvReader.getStart (int nCol) inline private
Definition at line 75 of file CsvReader.java.
    {
        if (nCol < m_nCol)
        {
            if (nCol == 0)
                return 0;
            return m_nColEnds[nCol - 1];
        }
        return -1; // force index out of bounds
    }
References cc.util.CsvReader.m_nCol, and cc.util.CsvReader.m_nColEnds.
Referenced by cc.util.CsvReader.isNull(), cc.util.CsvReader.parseDouble(), cc.util.CsvReader.parseInt(), cc.util.CsvReader.parseLong(), and cc.util.CsvReader.parseString().
isNull()
boolean cc.util.CsvReader.isNull (int nCol) throws IndexOutOfBoundsException inline
Definition at line 97 of file CsvReader.java.
    {
        return (getEnd(nCol) - getStart(nCol) == 0);
    }
References cc.util.CsvReader.getEnd(), and cc.util.CsvReader.getStart().
parseDouble()
double cc.util.CsvReader.parseDouble (int nCol) throws IndexOutOfBoundsException, NumberFormatException inline
Definition at line 104 of file CsvReader.java.
    {
        return Text.parseDouble(m_sBuf, getStart(nCol), getEnd(nCol));
    }
References cc.util.CsvReader.getEnd(), cc.util.CsvReader.getStart(), cc.util.CsvReader.m_sBuf, and cc.util.Text.parseDouble().
Referenced by cc.util.CsvReader.parseFloat().
parseFloat()
float cc.util.CsvReader.parseFloat (int nCol) throws IndexOutOfBoundsException, NumberFormatException inline
Definition at line 118 of file CsvReader.java.
    {
        return (float)parseDouble(nCol);
    }
References cc.util.CsvReader.parseDouble().
parseInt()
int cc.util.CsvReader.parseInt (int nCol) throws IndexOutOfBoundsException, NumberFormatException inline
Definition at line 125 of file CsvReader.java.
    {
        return Text.parseInt(m_sBuf, getStart(nCol), getEnd(nCol));
    }
References cc.util.CsvReader.getEnd(), cc.util.CsvReader.getStart(), cc.util.CsvReader.m_sBuf, and cc.util.Text.parseInt().
parseLong()
long cc.util.CsvReader.parseLong (int nCol) throws IndexOutOfBoundsException, NumberFormatException inline
Definition at line 111 of file CsvReader.java.
    {
        return Text.parseLong(m_sBuf, getStart(nCol), getEnd(nCol));
    }
References cc.util.CsvReader.getEnd(), cc.util.CsvReader.getStart(), cc.util.CsvReader.m_sBuf, and cc.util.Text.parseLong().
parseString() [1/2]
String cc.util.CsvReader.parseString (int nCol) throws IndexOutOfBoundsException inline
Definition at line 132 of file CsvReader.java.
    {
        return m_sBuf.substring(getStart(nCol), getEnd(nCol));
    }
References cc.util.CsvReader.getEnd(), cc.util.CsvReader.getStart(), and cc.util.CsvReader.m_sBuf.
Referenced by cc.ws.User.User(), and cc.ws.Handler.update().
parseString() [2/2]
int cc.util.CsvReader.parseString (StringBuilder sBuf, int nCol) throws IndexOutOfBoundsException, NullPointerException inline
Definition at line 139 of file CsvReader.java.
    {
        sBuf.setLength(0); // clear provided buffer
        sBuf.append(m_sBuf, getStart(nCol), getEnd(nCol));
        return sBuf.length();
    }
References cc.util.CsvReader.getEnd(), cc.util.CsvReader.getStart(), and cc.util.CsvReader.m_sBuf.
readLine()
int cc.util.CsvReader.readLine () throws IOException inline
Definition at line 36 of file CsvReader.java.
    {
        m_nCol = 0; // reset column index
        m_sBuf.setLength(0); // reset line buffer
        boolean bGo = true;
        int nChar;
        while (bGo && (nChar = read()) >= 0) // don't advance on line complete
        {
            if (nChar == m_cDelim || nChar < ' ')
            {
                bGo = (nChar != '\n');
                if (nChar != '\r') // ignore carriage return
                    addCol(); // column found
            }
            else
                m_sBuf.append((char)nChar);
        }
        if (bGo && m_nCol > 0) // check for missing final newline
            addCol();
        return m_nCol; // discovered column count
    }
References cc.util.CsvReader.addCol(), cc.util.CsvReader.m_cDelim, cc.util.CsvReader.m_nCol, cc.util.CsvReader.m_sBuf, and cc.util.BufferedInStream.read().
Member Data Documentation
DEFAULT_COLS
final int cc.util.CsvReader.DEFAULT_COLS = 80 static protected
Definition at line 9 of file CsvReader.java.
Referenced by cc.util.CsvReader.CsvReader().
m_cDelim
char cc.util.CsvReader.m_cDelim = ',' protected
Definition at line 14 of file CsvReader.java.
Referenced by cc.util.CsvReader.CsvReader(), and cc.util.CsvReader.readLine().
m_nCol
int cc.util.CsvReader.m_nCol protected
Definition at line 11 of file CsvReader.java.
Referenced by cc.util.CsvReader.addCol(), cc.util.CsvReader.getEnd(), cc.util.CsvReader.getStart(), and cc.util.CsvReader.readLine().
m_nColEnds
int [] cc.util.CsvReader.m_nColEnds protected
Definition at line 12 of file CsvReader.java.
Referenced by cc.util.CsvReader.CsvReader(), cc.util.CsvReader.addCol(), cc.util.CsvReader.getEnd(), and cc.util.CsvReader.getStart().
m_sBuf
StringBuilder cc.util.CsvReader.m_sBuf = new StringBuilder(BUFFER_SIZE) protected
Definition at line 13 of file CsvReader.java.
Referenced by cc.util.CsvReader.addCol(), cc.util.CsvReader.parseDouble(), cc.util.CsvReader.parseInt(), cc.util.CsvReader.parseLong(), cc.util.CsvReader.parseString(), and cc.util.CsvReader.readLine().
The documentation for this class was generated from the following file:
src/cc/util/CsvReader.java