Carma-cloud: cc.geosrv.xodr.XodrUtil Class Reference
cc.geosrv.xodr.XodrUtil Class Reference abstract
Static Public Member Functions
static int getLaneType (String sType)
static String getLaneType (int nType)
static int getLaneId (int nRoadId, int nLaneIdByRoad)
static long getLaneSectionId (int nRoadId, int nSectionId, int nLaneIndex)
static int getLaneIndex (long lLaneSectionId)
static int getRoadId (int nLaneId)
static void splitLaneSectionId (long lLaneSectionId, int nPos, int[] nArray)
static void main (String[] sArgs)
static double parseDouble (String sVal)
Static Public Attributes
static String[] LANETYPES
Detailed Description
Author
aaron.cherney
Definition at line 14 of file XodrUtil.java.
Member Function Documentation
getLaneId()
static int cc.geosrv.xodr.XodrUtil.getLaneId (int nRoadId, int nLaneIdByRoad) inline static
Definition at line 64 of file XodrUtil.java.
    {
        int nId = nRoadId;
        nId <<= 16;
        nId |= (nLaneIdByRoad & 0xff);
        return nId;
    }
Referenced by cc.ctrl.CtrlLineArcs.CtrlLineArcs(), and cc.geosrv.xodr.geo.XodrGeoParser.writeSpeeds().
getLaneIndex()
static int cc.geosrv.xodr.XodrUtil.getLaneIndex (long lLaneSectionId) inline static
Definition at line 86 of file XodrUtil.java.
    {
        return (byte)(lLaneSectionId & 0xff);
    }
Referenced by cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcStop.combine(), cc.ctrl.proc.ProcYield.combine(), and cc.util.Geo.main().
getLaneSectionId()
static long cc.geosrv.xodr.XodrUtil.getLaneSectionId (int nRoadId, int nSectionId, int nLaneIndex) inline static
Definition at line 74 of file XodrUtil.java.
    {
        long lId = nRoadId;
        lId <<= 16;
        lId |= (nSectionId & 0xff);
        lId <<= 8;
        lId |= (nLaneIndex & 0xff);
        return lId;
    }
Referenced by cc.ctrl.CtrlLineArcs.CtrlLineArcs(), cc.geosrv.xodr.rdmk.Road.getRdMkCtrlLineArcs(), and cc.geosrv.xodr.XodrUtil.main().
getLaneType() [1/2]
static String cc.geosrv.xodr.XodrUtil.getLaneType (int nType) inline static
Definition at line 58 of file XodrUtil.java.
    {
        return LANETYPES[nType];
    }
References cc.geosrv.xodr.XodrUtil.LANETYPES.
getLaneType() [2/2]
static int cc.geosrv.xodr.XodrUtil.getLaneType (String sType) inline static
Definition at line 45 of file XodrUtil.java.
    {
        int nIndex = LANETYPES.length;
        while (nIndex-- > 0)
        {
            if (LANETYPES[nIndex].compareTo(sType) == 0)
                return nIndex;
        }
        return 0; // return 0 which is "none" if there is no match
    }
References cc.geosrv.xodr.XodrUtil.LANETYPES.
Referenced by cc.geosrv.xodr.rdmk.Lane.Lane(), cc.geosrv.xodr.geo.Lane.Lane(), cc.geosrv.xodr.pvmt.Lane.Lane(), cc.ws.CtrlTiles.addControl(), cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.ctrl.CreateCtrls.createCtrl(), cc.geosrv.xodr.pvmt.LaneSection.createPavement(), cc.geosrv.xodr.geo.Road.getPavementCtrlLineArcs(), cc.geosrv.xodr.pvmt.Road.getPavementCtrlLineArcs(), cc.geosrv.xodr.pvmt.Road.getShoulderCtrlLineArcs(), cc.geosrv.xodr.pvmt.LaneSection.getShoulders(), cc.ctrl.proc.ProcClosed.proc(), cc.ctrl.proc.ProcClosing.proc(), cc.ctrl.proc.ProcDirection.proc(), cc.ctrl.proc.ProcLatPerm.proc(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ctrl.proc.ProcOpening.proc(), cc.ctrl.proc.ProcStop.proc(), cc.ctrl.proc.ProcPavement.renderTiledData(), cc.geosrv.xodr.rdmk.LaneSection.sortLanes(), and cc.ws.CtrlTiles.splitLineArcs().
getRoadId()
static int cc.geosrv.xodr.XodrUtil.getRoadId (int nLaneId) inline static
Definition at line 92 of file XodrUtil.java.
    {
        return nLaneId >> 16;
    }
Referenced by cc.ctrl.proc.ProcDebug.combine(), cc.ctrl.proc.ProcDirection.combine(), cc.ctrl.proc.ProcMaxSpeed.combine(), cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcStop.combine(), cc.ctrl.proc.ProcYield.combine(), cc.util.Geo.main(), and cc.ctrl.proc.ProcMaxSpeed.proc().
main()
static void cc.geosrv.xodr.XodrUtil.main (String[] sArgs) inline static
Definition at line 105 of file XodrUtil.java.
    {
        long lId = getLaneSectionId(272, 1, -1);
        int[] nSearch = new int[2];
        nSearch[0] = (int)((lId >> 32) & 0xffffffff);
        nSearch[1] = (int)(lId & 0xffffffff);
        System.out.println(nSearch[0]);
        System.out.println(nSearch[1]);
        long lNew = nSearch[0];
        lNew <<= 32;
        lNew |= nSearch[1];
        System.out.println(lNew);
    }
References cc.geosrv.xodr.XodrUtil.getLaneSectionId().
parseDouble()
static double cc.geosrv.xodr.XodrUtil.parseDouble (String sVal) inline static
Definition at line 120 of file XodrUtil.java.
    {
        if (sVal.endsWith("inf"))
            sVal = sVal.replace("inf", "Infinity");
        return Double.parseDouble(sVal);
    }
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.startElement(), cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
splitLaneSectionId()
static void cc.geosrv.xodr.XodrUtil.splitLaneSectionId (long lLaneSectionId, int nPos, int[] nArray) inline static
Definition at line 98 of file XodrUtil.java.
    {
        nArray[nPos] = (int)((lLaneSectionId >> 32) & 0xffffffff);
        nArray[nPos + 1] = (int)(lLaneSectionId & 0xffffffff);
    }
Referenced by cc.geosrv.xodr.rdmk.Road.getRdMkCtrlLineArcs(), and cc.ctrl.proc.ProcLatPerm.proc().
Member Data Documentation
LANETYPES
String [] cc.geosrv.xodr.XodrUtil.LANETYPES static
Initial value:
= new String[]
    {
        "none",
        "driving",
        "stop",
        "shoulder",
        "biking",
        "sidewalk",
        "border",
        "restricted",
        "parking",
        "bidirectional",
        "median",
        "special1",
        "special2",
        "special3",
        "roadWorks",
        "tram",
        "rail",
        "entry",
        "exit",
        "offRamp",
        "onRamp",
        "connectingRamp",
        "bus",
        "taxi",
        "HOV"
    }
Definition at line 16 of file XodrUtil.java.
Referenced by cc.geosrv.xodr.XodrUtil.getLaneType().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/XodrUtil.java