Carma-cloud: cc.geosrv.xodr.geo.Geometry Class Reference
cc.geosrv.xodr.geo.Geometry Class Reference abstract
Public Member Functions
Geometry (double dS, double dX, double dY, double dH, double dL)
abstract void addPoints (Road oRoad, double dMaxStep, boolean bIncludeEnd, Proj oProj, double[] dProjPt)
void addLanePoints (Road oRoad, double dHdg, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, LaneSection oLaneSection, Proj oProj, double[] dProjPt)
int compareTo (Geometry o)
Public Attributes
double m_dS
double m_dX
double m_dY
double m_dHdg
double m_dL
Static Public Attributes
static int COUNT = 0
static double PX
static double PY
Static Package Functions
static double[] addProjectedPoint (double dX, double dY, double[] dPts, Proj oProj, double[] dPoint)
Private Member Functions
void addLanePoints (LaneSection oLaneSection, ArrayList< Lane > oLanes, double dTangent, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, Proj oProj, double[] dProjPt, Road oRoad)
Detailed Description
Author
Federal Highway Administration
Definition at line 18 of file Geometry.java.
Constructor & Destructor Documentation
Geometry()
cc.geosrv.xodr.geo.Geometry.Geometry (double dS, double dX, double dY, double dH, double dL) inline
Definition at line 29 of file Geometry.java.
    {
        m_dS = dS;
        m_dX = dX;
        m_dY = dY;
        m_dHdg = dH;
        m_dL = dL;
    }
References cc.geosrv.xodr.geo.Geometry.m_dHdg, cc.geosrv.xodr.geo.Geometry.m_dL, cc.geosrv.xodr.geo.Geometry.m_dS, cc.geosrv.xodr.geo.Geometry.m_dX, and cc.geosrv.xodr.geo.Geometry.m_dY.
Member Function Documentation
addLanePoints() [1/2]
void cc.geosrv.xodr.geo.Geometry.addLanePoints (LaneSection oLaneSection, ArrayList< Lane > oLanes, double dTangent, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, Proj oProj, double[] dProjPt, Road oRoad) inline private
Definition at line 60 of file Geometry.java.
    {
        double dXPrevLane = dXLaneZero;
        double dYPrevLane = dYLaneZero;
        oProj.cs2cs(dXPrevLane, dYPrevLane, dProjPt);
        double dXProjPrevLane = dProjPt[0];
        double dYProjPrevLane = dProjPt[1];
        for (Lane oLane : oLanes)
        {
            if (Arrays.size(oLane.m_dCenter) == 251)
                System.currentTimeMillis();
            double dPx = dXProjPrevLane;
            double dPy = dYProjPrevLane;
            double dLengthAlongSection = dLengthAlongRoad - oLaneSection.m_dS;
            LaneWidth oLaneWidth = LaneWidth.getLaneWidth(dLengthAlongSection, oLane);
            double dT = MathUtil.cubic(dLengthAlongSection - oLaneWidth.m_dS, oLaneWidth.m_dA, oLaneWidth.m_dB, oLaneWidth.m_dC, oLaneWidth.m_dD);
            double dXNextLane = dXPrevLane + Math.cos(dTangent) * dT;
            double dYNextLane = dYPrevLane + Math.sin(dTangent) * dT;
            oLane.m_dOuter = addProjectedPoint(dXNextLane, dYNextLane, oLane.m_dOuter, oProj, dProjPt);
            oLane.m_dOuterW = Arrays.addAndUpdate(oLane.m_dOuterW, dProjPt[0], dProjPt[1]);
            oLane.m_dOuterW = Arrays.add(oLane.m_dOuterW, 0);
            double dProjW = Geo.distance(dXProjPrevLane, dYProjPrevLane, dProjPt[0], dProjPt[1]);
            dXProjPrevLane = dProjPt[0];
            dYProjPrevLane = dProjPt[1];
            double dXPath = (dXPrevLane + dXNextLane) / 2;
            double dYPath = (dYPrevLane + dYNextLane) / 2;
            oLane.m_dCenter = addProjectedPoint(dXPath, dYPath, oLane.m_dCenter, oProj, dProjPt);
//          if (oLane.m_nLaneIndex == 2)
//          {
//              if (dProjPt[0] < -8555840.6442 && dProjPt[0] > -8555840.7746 && dProjPt[1] > 4686050.6342 && dProjPt[1] < 4686050.8053)
//                  System.currentTimeMillis();
//          }
            if (this instanceof Arc)
            {
                oRoad.m_dPerps.add(new double[]{dPx, dPy, dXProjPrevLane, dYProjPrevLane});
            }
            if (oLaneWidth.m_dS != oLane.m_dLastLaneWidth)
            {
                oLane.m_dLastLaneWidth = oLaneWidth.m_dS;
                oRoad.m_dLWPoints.add(new double[]{dProjPt[0], dProjPt[1]});
            }
            dXPrevLane = dXNextLane;
            dYPrevLane = dYNextLane;
            oLane.m_dCenter = Arrays.add(oLane.m_dCenter, dProjW);
        }
    }
References cc.util.Arrays.add(), cc.util.Arrays.addAndUpdate(), cc.geosrv.xodr.geo.Geometry.addProjectedPoint(), cc.geosrv.Proj.cs2cs(), cc.util.MathUtil.cubic(), cc.util.Geo.distance(), cc.geosrv.xodr.geo.LaneWidth.getLaneWidth(), cc.geosrv.xodr.geo.LaneWidth.m_dA, cc.geosrv.xodr.geo.LaneWidth.m_dB, cc.geosrv.xodr.geo.LaneWidth.m_dC, cc.geosrv.xodr.geo.LaneWidth.m_dD, cc.geosrv.xodr.geo.Road.m_dLWPoints, cc.geosrv.xodr.geo.Road.m_dPerps, cc.geosrv.xodr.geo.LaneSection.m_dS, cc.geosrv.xodr.geo.LaneWidth.m_dS, and cc.util.Arrays.size().
addLanePoints() [2/2]
void cc.geosrv.xodr.geo.Geometry.addLanePoints (Road oRoad, double dHdg, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, LaneSection oLaneSection, Proj oProj, double[] dProjPt) inline
Definition at line 41 of file Geometry.java.
    {
        oProj.cs2cs(dXLaneZero, dYLaneZero, dProjPt);
        if (oRoad.m_dLastGeo != m_dS)
        {
            oRoad.m_dLastGeo = m_dS;
            oRoad.m_dGeoPoints.add(new double[]{dProjPt[0], dProjPt[1]});
        }
        if (oRoad.m_dLastSection != oLaneSection.m_dS)
        {
            oRoad.m_dLastSection = oLaneSection.m_dS;
            oRoad.m_dLSPoints.add(new double[]{dProjPt[0], dProjPt[1]});
        }
        oLaneSection.m_oCenter.m_dOuter = Arrays.addAndUpdate(oLaneSection.m_oCenter.m_dOuter, dProjPt[0], dProjPt[1]);
        addLanePoints(oLaneSection, oLaneSection.m_oLeft, dHdg + Math.PI / 2, dXLaneZero, dYLaneZero, dLengthAlongRoad, oProj, dProjPt, oRoad);
        addLanePoints(oLaneSection, oLaneSection.m_oRight, dHdg - Math.PI / 2, dXLaneZero, dYLaneZero, dLengthAlongRoad, oProj, dProjPt, oRoad);
    }
References cc.util.Arrays.addAndUpdate(), cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.Proj.cs2cs(), cc.geosrv.xodr.geo.Road.m_dGeoPoints, cc.geosrv.xodr.geo.Road.m_dLastGeo, cc.geosrv.xodr.geo.Road.m_dLastSection, cc.geosrv.xodr.geo.Road.m_dLSPoints, cc.geosrv.xodr.geo.Lane.m_dOuter, cc.geosrv.xodr.geo.Geometry.m_dS, cc.geosrv.xodr.geo.LaneSection.m_dS, cc.geosrv.xodr.geo.LaneSection.m_oCenter, cc.geosrv.xodr.geo.LaneSection.m_oLeft, and cc.geosrv.xodr.geo.LaneSection.m_oRight.
Referenced by cc.geosrv.xodr.geo.Geometry.addLanePoints(), and cc.geosrv.xodr.geo.Line.addPoints().
addPoints()
abstract void cc.geosrv.xodr.geo.Geometry.addPoints (Road oRoad, double dMaxStep, boolean bIncludeEnd, Proj oProj, double[] dProjPt) abstract
Reimplemented in cc.geosrv.xodr.geo.Arc, and cc.geosrv.xodr.geo.Line.
addProjectedPoint()
static double[] cc.geosrv.xodr.geo.Geometry.addProjectedPoint (double dX, double dY, double[] dPts, Proj oProj, double[] dPoint) inline static package
Definition at line 112 of file Geometry.java.
    {
        oProj.cs2cs(dX, dY, dPoint);
        dX = dPoint[0]; // transform coordinates
        dY = dPoint[1]; // and set local reference
        dPts = Arrays.addAndUpdate(dPts, dX, dY);
        return dPts;
    }
References cc.util.Arrays.addAndUpdate(), and cc.geosrv.Proj.cs2cs().
Referenced by cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.xodr.geo.Arc.addPoints(), and cc.geosrv.xodr.geo.Line.addPoints().
compareTo()
int cc.geosrv.xodr.geo.Geometry.compareTo (Geometry o) inline
Definition at line 122 of file Geometry.java.
    {
        return Double.compare(m_dS, o.m_dS);
    }
References cc.geosrv.xodr.geo.Geometry.m_dS.
Member Data Documentation
COUNT
int cc.geosrv.xodr.geo.Geometry.COUNT = 0 static
Definition at line 25 of file Geometry.java.
m_dHdg
double cc.geosrv.xodr.geo.Geometry.m_dHdg
Definition at line 23 of file Geometry.java.
Referenced by cc.geosrv.xodr.geo.Geometry.Geometry(), cc.geosrv.xodr.geo.Arc.addPoints(), and cc.geosrv.xodr.geo.Line.addPoints().
m_dL
double cc.geosrv.xodr.geo.Geometry.m_dL
Definition at line 24 of file Geometry.java.
Referenced by cc.geosrv.xodr.geo.Geometry.Geometry(), cc.geosrv.xodr.geo.Arc.addPoints(), and cc.geosrv.xodr.geo.Line.addPoints().
m_dS
double cc.geosrv.xodr.geo.Geometry.m_dS
Definition at line 20 of file Geometry.java.
Referenced by cc.geosrv.xodr.geo.Geometry.Geometry(), cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.xodr.geo.Arc.addPoints(), cc.geosrv.xodr.geo.Line.addPoints(), and cc.geosrv.xodr.geo.Geometry.compareTo().
m_dX
double cc.geosrv.xodr.geo.Geometry.m_dX
Definition at line 21 of file Geometry.java.
Referenced by cc.geosrv.xodr.geo.Geometry.Geometry(), cc.geosrv.xodr.geo.Arc.addPoints(), and cc.geosrv.xodr.geo.Line.addPoints().
m_dY
double cc.geosrv.xodr.geo.Geometry.m_dY
Definition at line 22 of file Geometry.java.
Referenced by cc.geosrv.xodr.geo.Geometry.Geometry(), cc.geosrv.xodr.geo.Arc.addPoints(), and cc.geosrv.xodr.geo.Line.addPoints().
PX
double cc.geosrv.xodr.geo.Geometry.PX static
Definition at line 26 of file Geometry.java.
PY
double cc.geosrv.xodr.geo.Geometry.PY static
Definition at line 27 of file Geometry.java.
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/geo/Geometry.java