Carma-cloud: cc.geosrv.xodr.XodrSignalParser Class Reference
cc.geosrv.xodr.XodrSignalParser Class Reference
Public Member Functions
XodrSignalParser (String[] sSignalTypes)
void startElement (String sUri, String sLocalName, String sQname, Attributes iAtt) throws SAXException
void endElement (String sUri, String sLocalName, String sQname) throws SAXException
void parseSignalData (Path oXodrFile, ArrayList< Junction > oJunctions, ArrayList< Signal > oSignals) throws Exception
Public Attributes
String[] m_sSignalTypes
Package Attributes
ArrayList< Signal > m_oSignals = new ArrayList()
ArrayList< Junction > m_oJunctions = new ArrayList()
HashMap< Integer, ArrayList< String > > m_oSigRefs = new HashMap()
int m_nRoadId
Junction m_oJunction
Connection m_oConnection
Detailed Description
Author
aaron.cherney
Definition at line 27 of file XodrSignalParser.java.
Constructor & Destructor Documentation
XodrSignalParser()
cc.geosrv.xodr.XodrSignalParser.XodrSignalParser (String[] sSignalTypes) inline
Definition at line 37 of file XodrSignalParser.java.
    {
        super();
        m_sSignalTypes = sSignalTypes;
        Arrays.sort(sSignalTypes);
    }
References cc.geosrv.xodr.XodrSignalParser.m_sSignalTypes.
Member Function Documentation
endElement()
void cc.geosrv.xodr.XodrSignalParser.endElement (String sUri, String sLocalName, String sQname) throws SAXException inline
Definition at line 104 of file XodrSignalParser.java.
    {
        switch (sQname)
        {
            case "junction":
            {
                m_oJunctions.add(m_oJunction);
            }
            case "connection":
            {
                m_oJunction.add(m_oConnection);
            }
            default:
                break;
        }
    }
References cc.geosrv.xodr.XodrSignalParser.m_oConnection, cc.geosrv.xodr.XodrSignalParser.m_oJunction, and cc.geosrv.xodr.XodrSignalParser.m_oJunctions.
parseSignalData()
void cc.geosrv.xodr.XodrSignalParser.parseSignalData (Path oXodrFile, ArrayList< Junction > oJunctions, ArrayList< Signal > oSignals) throws Exception inline
Definition at line 123 of file XodrSignalParser.java.
    {
        XMLReader iXmlReader = SAXParserFactory.newInstance().
            newSAXParser().getXMLReader();
        iXmlReader.setContentHandler(this);
        iXmlReader.setProperty("http://xml.org/sax/properties/lexical-handler", this);
        iXmlReader.parse(new InputSource(new BufferedInputStream(Files.newInputStream(oXodrFile))));
        Signal oSearch = new Signal();
        for (Entry<Integer, ArrayList<String>> oEntry : m_oSigRefs.entrySet())
        {
            for (String sSigId : oEntry.getValue())
            {
                oSearch.m_sId = sSigId;
                int nIndex = Collections.binarySearch(m_oSignals, oSearch);
                if (nIndex < 0)
                    continue;
                m_oSignals.get(nIndex).addRoadId(oEntry.getKey());
            }
        }
        oJunctions.addAll(m_oJunctions);
        oSignals.addAll(m_oSignals);
    }
References cc.geosrv.xodr.XodrSignalParser.m_oJunctions, cc.geosrv.xodr.XodrSignalParser.m_oSignals, and cc.geosrv.xodr.XodrSignalParser.m_oSigRefs.
Referenced by cc.ctrl.proc.ProcSignal.parseMetadata(), cc.ctrl.proc.ProcStop.parseMetadata(), and cc.ctrl.proc.ProcYield.parseMetadata().
startElement()
void cc.geosrv.xodr.XodrSignalParser.startElement (String sUri, String sLocalName, String sQname, Attributes iAtt) throws SAXException inline
Definition at line 46 of file XodrSignalParser.java.
    {
        try
        {
            switch (sQname)
            {
                case "road":
                {
                    m_nRoadId = Integer.parseInt(iAtt.getValue("id"));
                    break;
                }
                case "signal":
                {
                    Signal oTemp = new Signal(iAtt.getValue("id"), iAtt.getValue("orientation"), m_nRoadId, iAtt.getValue("type"), iAtt.getValue("dynamic"), iAtt.getValue("name"));
                    if (Arrays.binarySearch(m_sSignalTypes, oTemp.m_sType) >= 0 || Arrays.binarySearch(m_sSignalTypes, oTemp.m_sName) >= 0) // filter on signal types we want
                    {
                        int nIndex = Collections.binarySearch(m_oSignals, oTemp);
                        if (nIndex < 0)
                            m_oSignals.add(~nIndex, oTemp);
                    }
                    break;
                }
                case "signalReference":
                {
                    if (!m_oSigRefs.containsKey(m_nRoadId))
                        m_oSigRefs.put(m_nRoadId, new ArrayList());
                    m_oSigRefs.get(m_nRoadId).add(iAtt.getValue("id"));
                    break;
                }
                case "junction":
                {
                    m_oJunction = new Junction(iAtt.getValue("name"), iAtt.getValue("id"), iAtt.getValue("type"));
                    break;
                }
                case "connection":
                {
                    m_oConnection = new Connection(iAtt.getValue("id"), iAtt.getValue("incomingRoad"), iAtt.getValue("connectingRoad"), iAtt.getValue("contactPoint"), iAtt.getValue("connectionMaster"), iAtt.getValue("type"));
                    break;
                }
                case "laneLink":
                {
                    m_oConnection.m_nFromLane = Integer.parseInt(iAtt.getValue("from"));
                    m_oConnection.m_nToLane = Integer.parseInt(iAtt.getValue("to"));
                }
                default:
                    break;
            }
        }
        catch (Exception oEx)
        {
            throw new SAXException(oEx);
        }
    }
References cc.util.Arrays.binarySearch(), cc.geosrv.xodr.XodrSignalParser.m_nRoadId, cc.geosrv.xodr.XodrSignalParser.m_oConnection, cc.geosrv.xodr.XodrSignalParser.m_oJunction, cc.geosrv.xodr.XodrSignalParser.m_oSignals, cc.geosrv.xodr.XodrSignalParser.m_oSigRefs, cc.geosrv.xodr.Signal.m_sName, cc.geosrv.xodr.XodrSignalParser.m_sSignalTypes, and cc.geosrv.xodr.Signal.m_sType.
Member Data Documentation
m_nRoadId
int cc.geosrv.xodr.XodrSignalParser.m_nRoadId package
Definition at line 32 of file XodrSignalParser.java.
Referenced by cc.geosrv.xodr.XodrSignalParser.startElement().
m_oConnection
Connection cc.geosrv.xodr.XodrSignalParser.m_oConnection package
Definition at line 34 of file XodrSignalParser.java.
Referenced by cc.geosrv.xodr.XodrSignalParser.endElement(), and cc.geosrv.xodr.XodrSignalParser.startElement().
m_oJunction
Junction cc.geosrv.xodr.XodrSignalParser.m_oJunction package
Definition at line 33 of file XodrSignalParser.java.
Referenced by cc.geosrv.xodr.XodrSignalParser.endElement(), and cc.geosrv.xodr.XodrSignalParser.startElement().
m_oJunctions
ArrayList<Junction> cc.geosrv.xodr.XodrSignalParser.m_oJunctions = new ArrayList() package
Definition at line 30 of file XodrSignalParser.java.
Referenced by cc.geosrv.xodr.XodrSignalParser.endElement(), and cc.geosrv.xodr.XodrSignalParser.parseSignalData().
m_oSignals
ArrayList<Signal> cc.geosrv.xodr.XodrSignalParser.m_oSignals = new ArrayList() package
Definition at line 29 of file XodrSignalParser.java.
Referenced by cc.geosrv.xodr.XodrSignalParser.parseSignalData(), and cc.geosrv.xodr.XodrSignalParser.startElement().
m_oSigRefs
HashMap<Integer, ArrayList<String> > cc.geosrv.xodr.XodrSignalParser.m_oSigRefs = new HashMap() package
Definition at line 31 of file XodrSignalParser.java.
Referenced by cc.geosrv.xodr.XodrSignalParser.parseSignalData(), and cc.geosrv.xodr.XodrSignalParser.startElement().
m_sSignalTypes
String [] cc.geosrv.xodr.XodrSignalParser.m_sSignalTypes
Definition at line 35 of file XodrSignalParser.java.
Referenced by cc.geosrv.xodr.XodrSignalParser.XodrSignalParser(), and cc.geosrv.xodr.XodrSignalParser.startElement().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/XodrSignalParser.java