Carma-cloud: cc.ctrl.RenderCtrl Class Reference
cc.ctrl.RenderCtrl Class Reference
Static Public Member Functions
static void main (String[] sArgs) throws Exception
Detailed Description
Author
aaron.cherney
Definition at line 28 of file RenderCtrl.java.
Member Function Documentation
main()
static void cc.ctrl.RenderCtrl.main (String[] sArgs) throws Exception inline static
Definition at line 30 of file RenderCtrl.java.
    {
        long lNow = System.currentTimeMillis();
        String sFile = sArgs[0];
        double dExplodeStep = Double.parseDouble(sArgs[1]); // 0.06
        String sTrafCtrlDir = sArgs[2]; // /opt/tomcat/work/carmacloud/traf_ctrls
        String sTdFF = sArgs[3]; // /opt/tomcat/work/carmacloud/td/%d/ctrls_%d_%d_%d.bin
        int nZoom = Integer.parseInt(sArgs[4]);
        ProcCtrl.setStaticVariables(dExplodeStep, sTrafCtrlDir, sTdFF, nZoom);
        TrafCtrl oCtrl = null;
        try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(Files.newInputStream(Paths.get(sFile)))))
        {
            oCtrl = new TrafCtrl(oIn, true, true);
        }
        ArrayList<int[]> nTiles = new ArrayList();
        ProcCtrl.updateTiles(nTiles, oCtrl.m_oFullGeo.m_oTiles);
        for (int[] nTile : nTiles)
        {
            String sIndex = String.format(sTdFF, nTile[0], nZoom, nTile[0], nTile[1]) + ".ndx";
            ProcCtrl.updateIndex(sIndex, oCtrl, lNow);
        }
        oCtrl.m_yId = null;
        oCtrl.write(sTrafCtrlDir, dExplodeStep, nZoom, ProcCtrl.CC);
        ArrayList<TrafCtrl> oCtrls = new ArrayList();
        oCtrls.add(oCtrl);
        String sCtrl = TrafCtrlEnums.CTRLS[oCtrl.m_nControlType][0];
        switch (sCtrl)
        {
            case "signal":
            {
                ProcSignal.renderTiledData(oCtrls, nTiles);
                break;
            }
            case "stop":
            {
                ProcStop.renderTiledData(oCtrls, nTiles);
                break;
            }
            case "yield":
            {
                ProcYield.renderTiledData(oCtrls, nTiles);
                break;
            }
            case "notowing":
            {
                break;
            }
            case "restricted":
            {
                break;
            }
            case "closed":
            {
                ProcClosed.renderTiledData(oCtrls, nTiles);
                break;
            }
            case "chains":
            {
                break;
            }
            case "direction":
            {
                ProcDirection.renderTiledData(oCtrls, nTiles);
                break;
            }
            case "lataffinity":
            {
                break;
            }
            case "latperm":
            {
                ProcLatPerm.renderTiledData(oCtrls, nTiles, new int[]{2, 4, 4});
                break;
            }
            case "opening":
            {
                ProcOpening.renderTiledData(oCtrls, nTiles);
                break;
            }
            case "closing":
            {
                ProcClosing.renderTiledData(oCtrls, nTiles);
                break;
            }
            case "parking":
            {
                break;
            }
            case "minspeed":
            {
                break;
            }
            case "maxspeed":
            {
                ProcMaxSpeed.renderTiledData(oCtrls, nTiles);
                break;
            }
            case "minhdwy":
            {
                break;
            }
            case "maxvehmass":
            {
                break;
            }
            case "maxvehheight":
            {
                break;
            }
            case "maxvehwidth":
            {
                break;
            }
            case "maxvehlength":
            {
                break;
            }
            case "maxaxles":
            {
                break;
            }
            case "minvehocc":
            {
                break;
            }
        }
    }
References cc.ctrl.proc.ProcCtrl.CC, cc.ctrl.TrafCtrlEnums.CTRLS, cc.ctrl.TrafCtrl.m_nControlType, cc.ctrl.TrafCtrl.m_oFullGeo, cc.ctrl.CtrlGeo.m_oTiles, cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.ctrl.proc.ProcCtrl.setStaticVariables(), cc.ctrl.proc.ProcCtrl.updateIndex(), cc.ctrl.proc.ProcCtrl.updateTiles(), and cc.ctrl.TrafCtrl.write().
The documentation for this class was generated from the following file:
src/cc/ctrl/RenderCtrl.java