Carma-cloud: cc.geosrv.Mercator Class Reference
cc.geosrv.Mercator Class Reference
Public Member Functions
void metersToLonLat (double dX, double dY, double[] dLatLon)
void pixelsToMeters (double dXp, double dYp, int nZoom, double[] dMeters)
void metersToPixels (double dXm, double dYm, int nZoom, double[] dPixels)
void pixelsToTile (double dXp, double dYp, int[] nTiles)
void tileBounds (double dXt, double dYt, int nZoom, double[] dBounds)
void tileBoundsCm (double dXt, double dYt, int nZoom, int[] nCms)
void lonLatBounds (double dXt, double dYt, int nZoom, double[] dBounds)
void lonLatToTile (double dLon, double dLat, int nZoom, int[] nTiles)
void metersToTile (double dXm, double dYm, int nZoom, int[] nTiles, double[] dPixels)
void metersToTile (double dXm, double dYm, int nZoom, int[] nTiles)
double resolution (int nZoom)
Static Public Member Functions
static Mercator getInstance ()
static int getExtent (int nZoom)
static double lonToMeters (double dLon)
static double latToMeters (double dLat)
static int lonToCm (double dLon)
static int latToCm (double dLat)
static int mToCm (double dM)
static double xToLon (double dX)
static double yToLat (double dY)
static void lonLatToMeters (double dLon, double dLat, double[] dMeters)
static double eMercX (double lon)
static double eMercY (double lat)
static double eLon (double dX)
static double eLat (double dY)
static void main (String[] sArgs)
Static Public Attributes
static final double PI_OVER_TWO = Math.PI / 2.0
static final double MAX_LAT = 85.05112877980659
static final double MIN_LAT = -MAX_LAT
static final double MAX_LON = 180
static final double MIN_LON = -MAX_LON
static Comparator< int[]> TILECOMP
Static Package Functions
[static initializer]
Package Attributes
int m_nTileSize
double m_dInitRes
Private Member Functions
Mercator ()
Mercator (int nTileSize)
Private Attributes
final double[] RES = new double[24]
Static Private Attributes
static final int[] POW = new int[24]
static final double R_MAJOR = 6378137.0
static final double R_MINOR = 6356752.3142
static final double R_RATIO = R_MINOR / R_MAJOR
static final double ECC = Math.sqrt(1.0 - (R_RATIO * R_RATIO))
static final double ECC_OVER_TWO = ECC / 2.0
static final double ORIGIN_SHIFT = Math.PI * R_MAJOR
static final double ORIGIN_SHIFT_DIVIDED_BY_180 = ORIGIN_SHIFT / 180.0
static final double PI_OVER_180 = Math.PI / 180.0
static final double PI_OVER_360 = PI_OVER_180 / 2.0
static BigDecimal ONEHUNDRED = new BigDecimal(100.0)
static Mercator INSTANCE = new Mercator()
Detailed Description
Author
Federal Highway Administration
Definition at line 18 of file Mercator.java.
Constructor & Destructor Documentation
Mercator() [1/2]
cc.geosrv.Mercator.Mercator () inline private
Definition at line 58 of file Mercator.java.
    {
        this(256);
    }
Referenced by cc.geosrv.Mercator.getInstance().
Mercator() [2/2]
cc.geosrv.Mercator.Mercator (int nTileSize) inline private
Definition at line 64 of file Mercator.java.
    {
        m_nTileSize = nTileSize;
        m_dInitRes = 2.0 * ORIGIN_SHIFT / m_nTileSize;
        for (int nIndex = 0; nIndex < RES.length; nIndex++)
            RES[nIndex] = m_dInitRes / POW[nIndex];
    }
References cc.geosrv.Mercator.m_dInitRes, cc.geosrv.Mercator.m_nTileSize, cc.geosrv.Mercator.ORIGIN_SHIFT, cc.geosrv.Mercator.POW, and cc.geosrv.Mercator.RES.
Member Function Documentation
[static initializer]()
cc.geosrv.Mercator.[static initializer] inline static package
References cc.geosrv.Mercator.POW.
eLat()
static double cc.geosrv.Mercator.eLat (double dY) inline static
Definition at line 255 of file Mercator.java.
    {
        double ts = Math.exp(-dY / R_MAJOR);
        double phi = PI_OVER_TWO - 2 * Math.atan(ts);
        double dphi = 1.0;
        for (int i = 0; Math.abs(dphi) > 0.000000001 && i < 15; i++)
        {
            double con = ECC * Math.sin(phi);
            dphi = PI_OVER_TWO - 2 * Math.atan(ts * Math.pow((1.0 - con) / (1.0 + con), ECC_OVER_TWO)) - phi;
            phi += dphi;
        }
        return Math.toDegrees(phi);
    }
References cc.geosrv.Mercator.ECC, cc.geosrv.Mercator.ECC_OVER_TWO, cc.geosrv.Mercator.PI_OVER_TWO, and cc.geosrv.Mercator.R_MAJOR.
eLon()
static double cc.geosrv.Mercator.eLon (double dX) inline static
Definition at line 249 of file Mercator.java.
    {
        return Math.toDegrees(dX / R_MAJOR);
    }
References cc.geosrv.Mercator.R_MAJOR.
eMercX()
static double cc.geosrv.Mercator.eMercX (double lon) inline static
Definition at line 229 of file Mercator.java.
{
        return R_MAJOR * Math.toRadians(lon);
    }
References cc.geosrv.Mercator.R_MAJOR.
eMercY()
static double cc.geosrv.Mercator.eMercY (double lat) inline static
Definition at line 233 of file Mercator.java.
{
        if (lat > 89.5) {
            lat = 89.5;
        }
        if (lat < -89.5) {
            lat = -89.5;
        }
        double phi = Math.toRadians(lat);
        double con = ECC * Math.sin(phi);
        con = Math.pow(((1.0-con)/(1.0+con)), ECC_OVER_TWO);
        double ts = Math.tan(0.5 * ((PI_OVER_TWO) - phi))/con;
        double y = 0 - R_MAJOR * Math.log(ts);
        return y;
    }
References cc.geosrv.Mercator.ECC, cc.geosrv.Mercator.ECC_OVER_TWO, cc.geosrv.Mercator.PI_OVER_TWO, and cc.geosrv.Mercator.R_MAJOR.
getExtent()
static int cc.geosrv.Mercator.getExtent (int nZoom) inline static
Definition at line 80 of file Mercator.java.
    {
        return POW[nZoom] * 256;
    }
References cc.geosrv.Mercator.POW.
getInstance()
static Mercator cc.geosrv.Mercator.getInstance () inline static
Definition at line 73 of file Mercator.java.
    {
        if (INSTANCE == null)
            INSTANCE = new Mercator();
        return INSTANCE;
    }
References cc.geosrv.Mercator.Mercator(), and cc.geosrv.Mercator.INSTANCE.
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.util.TileLayerBuilder.TileLayerBuilder(), cc.ws.CtrlTiles.doGet(), cc.ws.ValidateXodrTiles.doGet(), cc.ws.WxPoly.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.util.TileUtil.getClippingBounds(), cc.ctrl.proc.ProcCtrl.getCurrentControls(), cc.util.TileUtil.getTileBounds(), cc.ctrl.CtrlGeo.readPtsUpdateTiles(), and cc.ws.TcmReqServlet.run().
latToCm()
static int cc.geosrv.Mercator.latToCm (double dLat) inline static
Definition at line 104 of file Mercator.java.
    {
        return (int)(latToMeters(dLat) * 100 + 0.5);
    }
References cc.geosrv.Mercator.latToMeters().
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ctrl.TrafCtrl.preparePoints(), cc.ctrl.proc.ProcDebug.renderTiledData(), and cc.ctrl.TrafCtrl.toMercatorPoints().
latToMeters()
static double cc.geosrv.Mercator.latToMeters (double dLat) inline static
Definition at line 92 of file Mercator.java.
    {
        return Math.log(Math.tan((90.0 + dLat) * PI_OVER_360)) * R_MAJOR;
    }
References cc.geosrv.Mercator.PI_OVER_360, and cc.geosrv.Mercator.R_MAJOR.
Referenced by cc.ihp.IHPResponse.IHPResponse(), cc.ihp.Subsegment.Subsegment(), cc.util.TileUtil.addLinestring(), cc.util.TileUtil.addPointToFeature(), cc.ctrl.CreateCtrls.createCtrl(), cc.ws.WxPoly.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcCtrl.getCurrentControls(), cc.geosrv.Mercator.latToCm(), cc.geosrv.Mercator.lonLatToMeters(), cc.geosrv.Mercator.main(), cc.util.TestPath.main1(), cc.ws.TcmReqServlet.run(), and cc.ctrl.TcBounds.setCorners().
lonLatBounds()
void cc.geosrv.Mercator.lonLatBounds (double dXt, double dYt, int nZoom, double[] dBounds) inline
Definition at line 184 of file Mercator.java.
    {
        double[] dMeterBounds = new double[4];
        tileBounds(dXt, dYt, nZoom, dMeterBounds);
        double[] dLonLat = new double[2];
        metersToLonLat(dMeterBounds[0], dMeterBounds[1], dLonLat);
        dBounds[0] = dLonLat[0];
        dBounds[1] = dLonLat[1];
        metersToLonLat(dMeterBounds[2], dMeterBounds[3], dLonLat);
        dBounds[2] = dLonLat[0];
        dBounds[3] = dLonLat[1];
    }
References cc.geosrv.Mercator.metersToLonLat(), and cc.geosrv.Mercator.tileBounds().
lonLatToMeters()
static void cc.geosrv.Mercator.lonLatToMeters (double dLon, double dLat, double[] dMeters) inline static
Definition at line 130 of file Mercator.java.
    {
        dMeters[0] = lonToMeters(dLon);
        dMeters[1] = latToMeters(dLat);
    }
References cc.geosrv.Mercator.latToMeters(), and cc.geosrv.Mercator.lonToMeters().
Referenced by cc.geosrv.Mercator.lonLatToTile().
lonLatToTile()
void cc.geosrv.Mercator.lonLatToTile (double dLon, double dLat, int nZoom, int[] nTiles) inline
Definition at line 198 of file Mercator.java.
    {
        double[] dTemp = new double[2];
        lonLatToMeters(dLon, dLat, dTemp);
        metersToPixels(dTemp[0], dTemp[1], nZoom, dTemp);
        pixelsToTile(dTemp[0], dTemp[1], nTiles);
        nTiles[1] = POW[nZoom] - nTiles[1] - 1;
    }
References cc.geosrv.Mercator.lonLatToMeters(), cc.geosrv.Mercator.metersToPixels(), cc.geosrv.Mercator.pixelsToTile(), and cc.geosrv.Mercator.POW.
Referenced by cc.ws.WxPoly.doPost(), and cc.ctrl.proc.ProcCtrl.getCurrentControls().
lonToCm()
static int cc.geosrv.Mercator.lonToCm (double dLon) inline static
Definition at line 98 of file Mercator.java.
    {
        return (int)(lonToMeters(dLon) * 100 + 0.5);
    }
References cc.geosrv.Mercator.lonToMeters().
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ctrl.TrafCtrl.preparePoints(), cc.ctrl.proc.ProcDebug.renderTiledData(), and cc.ctrl.TrafCtrl.toMercatorPoints().
lonToMeters()
static double cc.geosrv.Mercator.lonToMeters (double dLon) inline static
Definition at line 86 of file Mercator.java.
    {
        return dLon * ORIGIN_SHIFT_DIVIDED_BY_180;
    }
References cc.geosrv.Mercator.ORIGIN_SHIFT_DIVIDED_BY_180.
Referenced by cc.ihp.IHPResponse.IHPResponse(), cc.ihp.Subsegment.Subsegment(), cc.util.TileUtil.addLinestring(), cc.util.TileUtil.addPointToFeature(), cc.ctrl.CreateCtrls.createCtrl(), cc.ws.WxPoly.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcCtrl.getCurrentControls(), cc.geosrv.Mercator.lonLatToMeters(), cc.geosrv.Mercator.lonToCm(), cc.geosrv.Mercator.main(), cc.util.TestPath.main1(), cc.ws.TcmReqServlet.run(), and cc.ctrl.TcBounds.setCorners().
main()
static void cc.geosrv.Mercator.main (String[] sArgs) inline static
Definition at line 270 of file Mercator.java.
    {
        double dX1 = Mercator.lonToMeters(-77.21813410520554);
        double dY1 = Mercator.latToMeters(38.912404525183945);
        double dX2 = Mercator.lonToMeters(-77.21815925091505);
        double dY2 = Mercator.latToMeters(38.91181284515318);
        double[] dPixels = new double[2];
        double[] dBounds = new double[4];
        INSTANCE.tileBounds(74843, 100268, 18, dBounds);
        INSTANCE.metersToPixels(dBounds[0], dBounds[1], 18, dPixels);
        double dPx1 = dPixels[0];
        double dPy1 = dPixels[1];
        INSTANCE.metersToPixels(dBounds[2], dBounds[3], 18, dPixels);
        double dPx2 = dPixels[0];
        double dPy2 = dPixels[1];
        System.out.println(dPx2 - dPx1);
        System.out.println(dPy2 - dPy1);
        System.out.println(dBounds[2] - dBounds[0]);
        System.out.println((dBounds[3] - dBounds[1]) / 512);
        System.out.println(Geo.distance(dX1, dY1, dX2, dY2));
    }
References cc.util.Geo.distance(), cc.geosrv.Mercator.INSTANCE, cc.geosrv.Mercator.latToMeters(), cc.geosrv.Mercator.lonToMeters(), cc.geosrv.Mercator.metersToPixels(), and cc.geosrv.Mercator.tileBounds().
metersToLonLat()
void cc.geosrv.Mercator.metersToLonLat (double dX, double dY, double[] dLatLon) inline
Definition at line 137 of file Mercator.java.
    {
        dLatLon[0] = dX / ORIGIN_SHIFT * 180.0;
        dLatLon[1] = dY / ORIGIN_SHIFT * 180.0;
        dLatLon[1] = 180.0 / Math.PI * (2 * Math.atan(Math.exp(dLatLon[1] * PI_OVER_180)) - PI_OVER_TWO);
    }
References cc.geosrv.Mercator.ORIGIN_SHIFT, cc.geosrv.Mercator.PI_OVER_180, and cc.geosrv.Mercator.PI_OVER_TWO.
Referenced by cc.geosrv.Mercator.lonLatBounds().
metersToPixels()
void cc.geosrv.Mercator.metersToPixels (double dXm, double dYm, int nZoom, double[] dPixels) inline
Definition at line 151 of file Mercator.java.
    {
        double dRes = resolution(nZoom);
        dPixels[0] = (dXm + ORIGIN_SHIFT) / dRes;
        dPixels[1] = (dYm + ORIGIN_SHIFT) / dRes;
    }
References cc.geosrv.Mercator.ORIGIN_SHIFT, and cc.geosrv.Mercator.resolution().
Referenced by cc.geosrv.Mercator.lonLatToTile(), cc.geosrv.Mercator.main(), and cc.geosrv.Mercator.metersToTile().
metersToTile() [1/2]
void cc.geosrv.Mercator.metersToTile (double dXm, double dYm, int nZoom, int[] nTiles) inline
Definition at line 216 of file Mercator.java.
    {
        metersToTile(dXm, dYm, nZoom, nTiles, new double[2]);
    }
References cc.geosrv.Mercator.metersToTile().
metersToTile() [2/2]
void cc.geosrv.Mercator.metersToTile (double dXm, double dYm, int nZoom, int[] nTiles, double[] dPixels) inline
Definition at line 208 of file Mercator.java.
    {
        metersToPixels(dXm, dYm, nZoom, dPixels);
        pixelsToTile(dPixels[0], dPixels[1], nTiles);
        nTiles[1] = POW[nZoom] - nTiles[1] - 1;
    }
References cc.geosrv.Mercator.metersToPixels(), cc.geosrv.Mercator.pixelsToTile(), and cc.geosrv.Mercator.POW.
Referenced by cc.ws.CtrlTiles.doGet(), cc.ws.ValidateXodrTiles.doGet(), cc.ihp.IHP.generateSpeedControls(), cc.geosrv.Mercator.metersToTile(), cc.ws.TcmReqServlet.run(), and cc.ctrl.CtrlGeo.updateTiles().
mToCm()
static int cc.geosrv.Mercator.mToCm (double dM) inline static
Definition at line 110 of file Mercator.java.
    {
        BigDecimal dBd = new BigDecimal(Double.toString(dM));
        dBd = dBd.setScale(2, RoundingMode.HALF_UP);
        return (int)dBd.multiply(ONEHUNDRED).doubleValue();
    }
References cc.geosrv.Mercator.ONEHUNDRED.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), and cc.ctrl.TrafCtrl.preparePoints().
pixelsToMeters()
void cc.geosrv.Mercator.pixelsToMeters (double dXp, double dYp, int nZoom, double[] dMeters) inline
Definition at line 144 of file Mercator.java.
    {
        double dRes = resolution(nZoom);
        dMeters[0] = dXp * dRes - ORIGIN_SHIFT;
        dMeters[1] = -(dYp * dRes - ORIGIN_SHIFT);
    }
References cc.geosrv.Mercator.ORIGIN_SHIFT, and cc.geosrv.Mercator.resolution().
Referenced by cc.geosrv.Mercator.tileBounds().
pixelsToTile()
void cc.geosrv.Mercator.pixelsToTile (double dXp, double dYp, int[] nTiles) inline
Definition at line 158 of file Mercator.java.
    {
        nTiles[0] = (int)((Math.ceil(dXp / m_nTileSize)) - 1);
        nTiles[1] = (int)((Math.ceil(dYp / m_nTileSize)) - 1);
    }
References cc.geosrv.Mercator.m_nTileSize.
Referenced by cc.geosrv.Mercator.lonLatToTile(), and cc.geosrv.Mercator.metersToTile().
resolution()
double cc.geosrv.Mercator.resolution (int nZoom) inline
Definition at line 222 of file Mercator.java.
    {
//      return m_dInitRes / POW[nZoom];
        return RES[nZoom];
    }
References cc.geosrv.Mercator.RES.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder(), cc.util.TileUtil.getClippingBounds(), cc.geosrv.Mercator.metersToPixels(), and cc.geosrv.Mercator.pixelsToMeters().
tileBounds()
void cc.geosrv.Mercator.tileBounds (double dXt, double dYt, int nZoom, double[] dBounds) inline
Definition at line 164 of file Mercator.java.
    {
        double[] dMeters = new double[2];
        pixelsToMeters(dXt * m_nTileSize, dYt * m_nTileSize, nZoom, dMeters);
        dBounds[0] = dMeters[0];
        dBounds[3] = dMeters[1];
        pixelsToMeters((dXt + 1) * m_nTileSize, (dYt + 1) * m_nTileSize, nZoom, dMeters);
        dBounds[2] = dMeters[0];
        dBounds[1] = dMeters[1];
    }
References cc.geosrv.Mercator.m_nTileSize, and cc.geosrv.Mercator.pixelsToMeters().
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder(), cc.util.TileUtil.getTileBounds(), cc.geosrv.Mercator.lonLatBounds(), cc.geosrv.Mercator.main(), and cc.geosrv.Mercator.tileBoundsCm().
tileBoundsCm()
void cc.geosrv.Mercator.tileBoundsCm (double dXt, double dYt, int nZoom, int[] nCms) inline
Definition at line 176 of file Mercator.java.
    {
        double[] dBounds = new double[4];
        tileBounds(dXt, dYt, nZoom, dBounds);
        for (int nIndex = 0; nIndex < nCms.length; nIndex++)
            nCms[nIndex] = (int)(dBounds[nIndex] * 100 + 0.5);
    }
References cc.geosrv.Mercator.tileBounds().
xToLon()
static double cc.geosrv.Mercator.xToLon (double dX) inline static
Definition at line 117 of file Mercator.java.
    {
        return dX / ORIGIN_SHIFT * 180.0;
    }
References cc.geosrv.Mercator.ORIGIN_SHIFT.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ws.GeoLanes.doPost(), cc.util.SimpleHull.getConvexHull(), cc.ihp.IHP.getGeo(), cc.util.TestPath.main(), cc.ctrl.CtrlGeo.readPtsLonLats(), cc.ctrl.TcBounds.setCorners(), and cc.ctrl.proc.ProcDebug.writeGeoLanes().
yToLat()
static double cc.geosrv.Mercator.yToLat (double dY) inline static
Definition at line 123 of file Mercator.java.
    {
        double dLat = dY / ORIGIN_SHIFT * 180.0;
        return 180.0 / Math.PI * (2 * Math.atan(Math.exp(dLat * PI_OVER_180)) - PI_OVER_TWO);
    }
References cc.geosrv.Mercator.ORIGIN_SHIFT, cc.geosrv.Mercator.PI_OVER_180, and cc.geosrv.Mercator.PI_OVER_TWO.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ws.GeoLanes.doPost(), cc.util.SimpleHull.getConvexHull(), cc.ihp.IHP.getGeo(), cc.util.TestPath.main(), cc.ctrl.CtrlGeo.readPtsLonLats(), cc.ctrl.TcBounds.setCorners(), and cc.ctrl.proc.ProcDebug.writeGeoLanes().
Member Data Documentation
ECC
final double cc.geosrv.Mercator.ECC = Math.sqrt(1.0 - (R_RATIO * R_RATIO)) static private
Definition at line 31 of file Mercator.java.
Referenced by cc.geosrv.Mercator.eLat(), and cc.geosrv.Mercator.eMercY().
ECC_OVER_TWO
final double cc.geosrv.Mercator.ECC_OVER_TWO = ECC / 2.0 static private
Definition at line 32 of file Mercator.java.
Referenced by cc.geosrv.Mercator.eLat(), and cc.geosrv.Mercator.eMercY().
INSTANCE
Mercator cc.geosrv.Mercator.INSTANCE = new Mercator() static private
Definition at line 44 of file Mercator.java.
Referenced by cc.geosrv.Mercator.getInstance(), and cc.geosrv.Mercator.main().
m_dInitRes
double cc.geosrv.Mercator.m_dInitRes package
Definition at line 47 of file Mercator.java.
Referenced by cc.geosrv.Mercator.Mercator().
m_nTileSize
int cc.geosrv.Mercator.m_nTileSize package
Definition at line 46 of file Mercator.java.
Referenced by cc.geosrv.Mercator.Mercator(), cc.geosrv.Mercator.pixelsToTile(), and cc.geosrv.Mercator.tileBounds().
MAX_LAT
final double cc.geosrv.Mercator.MAX_LAT = 85.05112877980659 static
Definition at line 38 of file Mercator.java.
MAX_LON
final double cc.geosrv.Mercator.MAX_LON = 180 static
Definition at line 40 of file Mercator.java.
MIN_LAT
final double cc.geosrv.Mercator.MIN_LAT = -MAX_LAT static
Definition at line 39 of file Mercator.java.
MIN_LON
final double cc.geosrv.Mercator.MIN_LON = -MAX_LON static
Definition at line 41 of file Mercator.java.
ONEHUNDRED
BigDecimal cc.geosrv.Mercator.ONEHUNDRED = new BigDecimal(100.0) static private
Definition at line 42 of file Mercator.java.
Referenced by cc.geosrv.Mercator.mToCm().
ORIGIN_SHIFT
final double cc.geosrv.Mercator.ORIGIN_SHIFT = Math.PI * R_MAJOR static private
Definition at line 34 of file Mercator.java.
Referenced by cc.geosrv.Mercator.Mercator(), cc.geosrv.Mercator.metersToLonLat(), cc.geosrv.Mercator.metersToPixels(), cc.geosrv.Mercator.pixelsToMeters(), cc.geosrv.Mercator.xToLon(), and cc.geosrv.Mercator.yToLat().
ORIGIN_SHIFT_DIVIDED_BY_180
final double cc.geosrv.Mercator.ORIGIN_SHIFT_DIVIDED_BY_180 = ORIGIN_SHIFT / 180.0 static private
Definition at line 35 of file Mercator.java.
Referenced by cc.geosrv.Mercator.lonToMeters().
PI_OVER_180
final double cc.geosrv.Mercator.PI_OVER_180 = Math.PI / 180.0 static private
Definition at line 36 of file Mercator.java.
Referenced by cc.geosrv.Mercator.metersToLonLat(), and cc.geosrv.Mercator.yToLat().
PI_OVER_360
final double cc.geosrv.Mercator.PI_OVER_360 = PI_OVER_180 / 2.0 static private
Definition at line 37 of file Mercator.java.
Referenced by cc.geosrv.Mercator.latToMeters().
PI_OVER_TWO
final double cc.geosrv.Mercator.PI_OVER_TWO = Math.PI / 2.0 static
Definition at line 33 of file Mercator.java.
Referenced by cc.geosrv.xodr.geo.Arc.addPoints(), cc.geosrv.xodr.pvmt.Arc.addPoints(), cc.geosrv.xodr.rdmk.Arc.addPoints(), cc.util.Geo.combineLineArcs(), cc.geosrv.Mercator.eLat(), cc.geosrv.Mercator.eMercY(), cc.geosrv.Mercator.metersToLonLat(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ws.CtrlTiles.splitLineArcs(), and cc.geosrv.Mercator.yToLat().
POW
final int [] cc.geosrv.Mercator.POW = new int[24] static private
Definition at line 20 of file Mercator.java.
Referenced by cc.geosrv.Mercator.Mercator(), cc.geosrv.Mercator.[static initializer](), cc.geosrv.Mercator.getExtent(), cc.geosrv.Mercator.lonLatToTile(), and cc.geosrv.Mercator.metersToTile().
R_MAJOR
final double cc.geosrv.Mercator.R_MAJOR = 6378137.0 static private
Definition at line 28 of file Mercator.java.
Referenced by cc.geosrv.Mercator.eLat(), cc.geosrv.Mercator.eLon(), cc.geosrv.Mercator.eMercX(), cc.geosrv.Mercator.eMercY(), and cc.geosrv.Mercator.latToMeters().
R_MINOR
final double cc.geosrv.Mercator.R_MINOR = 6356752.3142 static private
Definition at line 29 of file Mercator.java.
R_RATIO
final double cc.geosrv.Mercator.R_RATIO = R_MINOR / R_MAJOR static private
Definition at line 30 of file Mercator.java.
RES
final double [] cc.geosrv.Mercator.RES = new double[24] private
Definition at line 27 of file Mercator.java.
Referenced by cc.geosrv.Mercator.Mercator(), and cc.geosrv.Mercator.resolution().
TILECOMP
Comparator<int[]> cc.geosrv.Mercator.TILECOMP static
Initial value:
= (int[] o1, int[] o2) ->
    {
        int nReturn = o1[0] - o2[0];
        if (nReturn == 0)
            nReturn = o1[1] - o2[1];
        return nReturn;
    }
Definition at line 48 of file Mercator.java.
Referenced by cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.ctrl.proc.ProcDebugOutlines.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcPavement.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.ctrl.proc.ProcCtrl.updateTiles(), and cc.ctrl.CtrlGeo.updateTiles().
The documentation for this class was generated from the following file:
src/cc/geosrv/Mercator.java