Carma-cloud: cc.util.Introsort Class Reference
cc.util.Introsort Class Reference
Static Public Member Functions
static< T extends Comparable<? super T > void usort (List< T > iList)
static< T > void usort (List< T > iList, Comparator< T > iCompare)
static< T > void usort (List< T > iList, Comparator< T > iCompare, int nBegin, int nEnd)
static< T > int binarySearch (List< T > iList, T oKey, Comparator< T > iCompare)
static< T > int binarySearch (List< T > iList, T oKey, int nLow, int nHigh, Comparator< T > iCompare)
static int floor (int nValue, int nPrecision)
Private Member Functions
Introsort ()
Static Private Member Functions
static< T > void introsortLoop (List< T > iList, Comparator< T > iCompare, int nLo, int nHi, int nDepthLimit)
static< T > int partition (List< T > iList, Comparator< T > iCompare, int nLo, int nHi, T oT)
static< T > T medianof3 (List< T > iList, Comparator< T > iCompare, int nLo, int mid, int nHi)
static< T > void heapsort (List< T > iList, Comparator< T > iCompare, int nLo, int nHi)
static< T > void downheap (List< T > iList, Comparator< T > iCompare, int i, int n, int nLo)
static< T > void insertionsort (List< T > iList, Comparator< T > iCompare, int nLo, int nHi)
Static Private Attributes
static int SIZE_THRESHOLD = 17
Detailed Description
Introsort algorithm. Modified quicksort algorithm, that attempts to avoid the degenerate case when supplied a nearly-sorted input. The modification is that when this degenerate case is detected, heap-sort and insertion sort take over to avoid this worst case. Operates in the worst case O(nlgn).
This class also provides search methods, and number manipulators.
Definition at line 20 of file Introsort.java.
Constructor & Destructor Documentation
Introsort()
cc.util.Introsort.Introsort () inline private
Default Constructor
Creates new instances of Introsort.
Definition at line 35 of file Introsort.java.
    {
    }
Member Function Documentation
binarySearch() [1/2]
static< T > int cc.util.Introsort.binarySearch (List< T > iList, T oKey, Comparator< T > iCompare) inline static
Wraps Introsort#binarySearch(List, Object, int, int, Comparator), providing a high and low value that enclose the entire list.
Parameters
<T> templated type.
iList list to search, sorted in ascending order.
oKey item to search for.
iCompare comparator the list items are ordered by.
Returns
negative value if the key isn't found, otherwise the index of the key in the provided list.
Definition at line 292 of file Introsort.java.
    {
        return binarySearch(iList, oKey, 0, iList.size(), iCompare);
    }
References cc.util.Introsort.binarySearch().
Referenced by cc.util.Introsort.binarySearch().
binarySearch() [2/2]
static< T > int cc.util.Introsort.binarySearch (List< T > iList, T oKey, int nLow, int nHigh, Comparator< T > iCompare) inline static
Binary search algorithm. Searches the provided array for the supplied key.
Parameters
<T> templated type.
iList list to search, sorted in ascending order.
oKey item to search for.
nLow low value for midpoint calculation.
nHigh high value for midpoint calculation.
iCompare comparator the list items are ordered by.
Returns
negative value if the key isn't found, otherwise the index of the key in the provided list.
Definition at line 312 of file Introsort.java.
    {
        --nHigh;
        while (nLow <= nHigh)
        {
            int nMid = (nLow + nHigh) >>> 1;
            int nCompare = iCompare.compare(iList.get(nMid), oKey);
            if (nCompare < 0)
                nLow = nMid + 1;
            else if (nCompare > 0)
                nHigh = nMid - 1;
            else
                return nMid; // key found
        }
        return -(nLow + 1); // key not found
    }
downheap()
static< T > void cc.util.Introsort.downheap (List< T > iList, Comparator< T > iCompare, int i, int n, int nLo) inline static private
Down heap algorithm. Bubbles items down.
Parameters
<T> templated type.
iList list to sort.
iCompare comparator the list items are ordered by.
i where to start.
n how far down to heap down.
nLo low value.
Definition at line 228 of file Introsort.java.
    {
        T oT = iList.get(nLo + i - 1);
        int child = 0;
        while (i <= n / 2)
        {
            child = 2 * i;
            if (child < n && iCompare.compare(iList.get(nLo + child - 1),
               iList.get(nLo + child)) < 0)
                child++;
            if (iCompare.compare(oT, iList.get(nLo + child - 1)) >= 0)
                break;
            iList.set(nLo + i - 1, iList.get(nLo + child - 1));
            i = child;
        }
        iList.set(nLo + i - 1, oT);
    }
Referenced by cc.util.Introsort.heapsort().
floor()
static int cc.util.Introsort.floor (int nValue, int nPrecision) inline static
Maps the provided value to the nearest multiple of the supplied precision, that's less than the value.
Ex: given a value of 17, and a grid size (precision) of 5, the value would be mapped into index 15.
Parameters
nValue the value to floor
nPrecision the grid size.
Returns
the floored index.
Definition at line 344 of file Introsort.java.
    {
        // this integer flooring method returns the next smallest integer
        int nFlooredValue = nValue / nPrecision * nPrecision;
        // correct for negative numbers
        // ensure the value was not previously floored,
        // or this operation will return the wrong result
        if (nValue < 0 && nFlooredValue != nValue)
            nFlooredValue -= nPrecision;
        return nFlooredValue;
    }
heapsort()
static< T > void cc.util.Introsort.heapsort (List< T > iList, Comparator< T > iCompare, int nLo, int nHi) inline static private
Heapsort algorithm. Sorts list[nLo...nHi] in the order defined by the comparator.
Parameters
<T> templated type.
iList the list to sort.
iCompare comparator to order the list by.
nLo smallest index.
nHi largest index.
Definition at line 201 of file Introsort.java.
    {
        int n = nHi - nLo;
        for (int i = n / 2; i >= 1; i--)
        {
            downheap(iList, iCompare, i, n, nLo);
        }
        for (int i = n; i > 1; i--)
        {
            Collections.swap(iList, nLo, nLo + i - 1);
            downheap(iList, iCompare, 1, i - 1, nLo);
        }
    }
References cc.util.Introsort.downheap().
Referenced by cc.util.Introsort.introsortLoop().
insertionsort()
static< T > void cc.util.Introsort.insertionsort (List< T > iList, Comparator< T > iCompare, int nLo, int nHi) inline static private
Insertion sort algorithm. Sorts list in ascending order.
Parameters
<T> templated type.
iList list to sort.
iCompare comparator to compare objects in the list.
nLo lower bound of the section of the list to sort.
nHi upper bound of the section of the list to sort.
Definition at line 260 of file Introsort.java.
    {
        int j;
        T oT;
        for (int i = nLo; i < nHi; i++)
        {
            j = i;
            oT = iList.get(i);
            while (j != nLo && iCompare.compare(oT, iList.get(j - 1)) < 0)
            {
                iList.set(j, iList.get(j - 1));
                j--;
            }
            iList.set(j, oT);
        }
    }
Referenced by cc.util.Introsort.usort().
introsortLoop()
static< T > void cc.util.Introsort.introsortLoop (List< T > iList, Comparator< T > iCompare, int nLo, int nHi, int nDepthLimit) inline static private
Quicksort algorithm modified for Introsort. While the section to sort is greater than the configured size-threshold, this method recursively partitions the list ordering the value as it partitions, until the recursion depth is met, then heapsort is invoked to finish the sorting.
Parameters
<T> template type.
iList list to sort.
iCompare comparator to sort the list by.
nLo lower index of the section of the list to sort.
nHi upper index of the section of the list to sort.
nDepthLimit
Definition at line 99 of file Introsort.java.
    {
        while (nHi - nLo > SIZE_THRESHOLD)
        {
            if (nDepthLimit == 0)
            {
                heapsort(iList, iCompare, nLo, nHi);
                return;
            }
            --nDepthLimit;
            int p = partition(iList, iCompare, nLo, nHi, medianof3(iList,
               iCompare, nLo, nLo + ((nHi - nLo) / 2) + 1, nHi - 1));
            introsortLoop(iList, iCompare, p, nHi, nDepthLimit);
            nHi = p;
        }
    }
References cc.util.Introsort.heapsort(), cc.util.Introsort.introsortLoop(), cc.util.Introsort.medianof3(), cc.util.Introsort.partition(), and cc.util.Introsort.SIZE_THRESHOLD.
Referenced by cc.util.Introsort.introsortLoop(), and cc.util.Introsort.usort().
medianof3()
static< T > T cc.util.Introsort.medianof3 (List< T > iList, Comparator< T > iCompare, int nLo, int mid, int nHi) inline static private
Determines the median value of three list items at the provided indices.
Parameters
<T> templated type.
iList list containing the items to
iCompare comparartor the list items are ordered by.
nLo index 1 of the median test.
mid index 2 of the median test.
nHi index 3 of the median test.
Returns
the median of the three values in the lists at the 3 provided indices.
Definition at line 165 of file Introsort.java.
    {
        if (iCompare.compare(iList.get(mid), iList.get(nLo)) < 0)
        {
            if (iCompare.compare(iList.get(nHi), iList.get(mid)) < 0)
                return iList.get(mid);
            if (iCompare.compare(iList.get(nHi), iList.get(nLo)) < 0)
                return iList.get(nHi);
            return iList.get(nLo);
        }
        if (iCompare.compare(iList.get(nHi), iList.get(mid)) < 0)
        {
            if (iCompare.compare(iList.get(nHi), iList.get(nLo)) < 0)
                return iList.get(nLo);
            return iList.get(nHi);
        }
        return iList.get(mid);
    }
Referenced by cc.util.Introsort.introsortLoop().
partition()
static< T > int cc.util.Introsort.partition (List< T > iList, Comparator< T > iCompare, int nLo, int nHi, T oT) inline static private
Moves all values that are less than the partition value to the left (smaller index) of the partition value, values greater are moved to the right (bigger index) of the partition value.
Parameters
<T> templated type
iList list to partition
iCompare comparator to partition the list by
nLo lower index of the section of the list to partition
nHi upper index of the section of the list to partition
oT value to partition the list by
Returns
index of the partition value, after partitioning
Definition at line 132 of file Introsort.java.
    {
        for (;;)
        {
            while (iCompare.compare(iList.get(nLo), oT) < 0)
                nLo++;
            --nHi;
            while (iCompare.compare(oT, iList.get(nHi)) < 0)
                --nHi;
            if (nLo >= nHi)
                return nLo;
            Collections.swap(iList, nLo, nHi);
            nLo++;
        }
    }
Referenced by cc.util.Introsort.introsortLoop().
usort() [1/3]
static< T extends Comparable<? super T > void cc.util.Introsort.usort (List< T > iList) inline static
Definition at line 40 of file Introsort.java.
    {
        Comparator<T> oComp = (T o1, T o2) -> o1.compareTo(o2);
        usort(iList, oComp);
    }
References cc.util.Introsort.usort().
Referenced by cc.ws.CtrlTiles.doGet(), cc.ws.ValidateXodrTiles.doGet(), cc.ws.GeoLanes.doPost(), cc.ws.WxPoly.doPost(), cc.ctrl.proc.ProcCtrl.getCurrentControls(), and cc.util.Introsort.usort().
usort() [2/3]
static< T > void cc.util.Introsort.usort (List< T > iList, Comparator< T > iCompare) inline static
Wraps Introsort#usort(List, Comparator, int, int) passing the appropriate begin-end values.
Parameters
<T> template type.
iList list to sort.
iCompare comparator to sort the list by.
Definition at line 55 of file Introsort.java.
    {
        usort(iList, iCompare, 0, iList.size());
    }
References cc.util.Introsort.usort().
usort() [3/3]
static< T > void cc.util.Introsort.usort (List< T > iList, Comparator< T > iCompare, int nBegin, int nEnd) inline static
Calculates a recursion depth and uses introsort for that depth, then uses insertion sort for the remaining unordered portion of the list.
Parameters
<T> template type.
iList list to sort.
iCompare comparator to sort list by.
nBegin lower index of the section of the list to sort.
nEnd upper index of the section of the list to sort.
Definition at line 71 of file Introsort.java.
    {
        if (nBegin < nEnd)
        {
            int nSize = 0;
            for (int nValue = nEnd - nBegin; nValue != 1; nValue >>= 1)
                ++nSize;
            introsortLoop(iList, iCompare, nBegin, nEnd, 2 * nSize);
            insertionsort(iList, iCompare, nBegin, nEnd);
        }
    }
References cc.util.Introsort.insertionsort(), and cc.util.Introsort.introsortLoop().
Member Data Documentation
SIZE_THRESHOLD
int cc.util.Introsort.SIZE_THRESHOLD = 17 static private
Introsort only sorts sections greater than or equal to this size.
Definition at line 26 of file Introsort.java.
Referenced by cc.util.Introsort.introsortLoop().
The documentation for this class was generated from the following file:
src/cc/util/Introsort.java