Carma-cloud: cc.ctrl.proc.ProcDebug Class Reference
cc.ctrl.proc.ProcDebug Class Reference
Public Member Functions
ProcDebug (String sLineArcDir, String sXodrDir)
void parseMetadata (Path oSource) throws Exception
void proc (String sLineArcsFile, double dTol)
ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
ProcCtrl (String sLineArcDir)
void parseMetadata (String sSource) throws Exception
abstract void parseMetadata (Path oSource) throws Exception
void process (String sLineArcsFile, double dTol) throws Exception
abstract ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Static Public Member Functions
static void renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
Static Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
static void setStaticVariables (double dStep, String sDir, String sTdFF, int nZoom)
static void updateTiles (ArrayList< int[]> oTiles, ArrayList< int[]> oCtrlTiles)
static void updateTileRange (int[] nTileIndices, int[] nTmpTiles)
static ArrayList< CtrlLineArcs > combineLaneByRoad (ArrayList< CtrlLineArcs > oLineArcs, double dTol)
static void writeIndexFile (ArrayList< TrafCtrl > oCtrls, int nX, int nY) throws IOException
static void updateIndex (String sIndexFile, TrafCtrl oCtrl, long lTimestamp) throws IOException
static void renderCtrls (String sCtrlType, ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
static boolean deleteControl (String sId) throws Exception
static boolean deleteControl (TrafCtrl oCtrl)
static ArrayList< TrafCtrl > getCurrentControls (int nCtrlType, double dMinLon, double dMinLat, double dMaxLon, double dMaxLat, boolean bLoadFullGeo)
Static Private Member Functions
static void writeGeoLanes (TrafCtrl oCtrl) throws IOException
Private Attributes
HashMap< String, String > m_oJunctions
String m_sXodrDir
Additional Inherited Members
Public Attributes inherited from cc.ctrl.proc.ProcCtrl
String m_sLineArcDir
Static Public Attributes inherited from cc.ctrl.proc.ProcCtrl
static final Object INDEXLOCK = new Object()
static double g_dExplodeStep
static String g_sTrafCtrlDir
static String g_sTdFileFormat
static String g_sGeolanesDir
static int g_nDefaultZoom = Integer.MIN_VALUE
static final byte CC = 0
static final byte RSM = 1
static final byte IHP2 = 2
abstract void proc (String sLineArcsFile, double dTol) throws Exception
Static Protected Member Functions inherited from cc.ctrl.proc.ProcCtrl
static boolean checkTileRange (int[] nTileIndices)
Static Protected Attributes inherited from cc.ctrl.proc.ProcCtrl
static final double WIDTHTH = 1.5
static final double LENLOWTH = 75.0
static final double STOPLINEENDOFFSET = 0.6
static final double STOPLINELATOFFSET = 0.1
static double[][] NUMBERS
static Comparator< int[]> LANETYPECOMP
static final HashMap< String, double[]> CHARS = new HashMap()
Static Package Functions inherited from cc.ctrl.proc.ProcCtrl
[static initializer]
static double getCoordAndHeadingAtLength (double[] dPoints, double dLength, boolean bReverse, double[] dPoint)
static int getStopLine (TrafCtrl oCtrl, ArrayList< double[]> oStops)
Detailed Description
Author
aaron.cherney
Definition at line 37 of file ProcDebug.java.
Constructor & Destructor Documentation
ProcDebug()
cc.ctrl.proc.ProcDebug.ProcDebug (String sLineArcDir, String sXodrDir) inline
Definition at line 43 of file ProcDebug.java.
    {
        super(sLineArcDir);
        m_sXodrDir = sXodrDir;
    }
References cc.ctrl.proc.ProcDebug.m_sXodrDir.
Member Function Documentation
combine()
ArrayList< CtrlLineArcs > cc.ctrl.proc.ProcDebug.combine (ArrayList< CtrlLineArcs > oLanes, double dTol) inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 93 of file ProcDebug.java.
    {
        ArrayList<CtrlLineArcs> oLanesByRoads = ProcCtrl.combineLaneByRoad(oLanes, dTol);
        Collections.sort(oLanesByRoads, CtrlLineArcs.CMPBYLANE);
        ArrayList<CtrlLineArcs> oCombined = new ArrayList();
        int nIndex = oLanesByRoads.size();
        while (nIndex-- > 0)
        {
            CtrlLineArcs oCla = oLanesByRoads.get(nIndex);
            String sRoadId = Integer.toString(XodrUtil.getRoadId(oCla.m_nLaneId));
            if (m_oJunctions.containsKey(sRoadId))
            {
                oLanesByRoads.remove(nIndex);
                oCombined.add(oCla);
            }
        }
        int nLimit = oLanesByRoads.size();
        double dSqTol = dTol * dTol;
        for (int nOuter = 0; nOuter < nLimit; nOuter++)
        {
            CtrlLineArcs oCur = oLanesByRoads.get(nOuter);
            for (int nInner = 0; nInner < nLimit; nInner++)
            {
                if (nOuter == nInner)
                    continue;
                CtrlLineArcs oCmp = oLanesByRoads.get(nInner);
                if (oCmp.m_nLaneType != oCur.m_nLaneType)
                    continue;
                int nConnect = oCur.connects(oCmp, dSqTol);
                if (nConnect == CtrlLineArcs.CON_TEND_OSTART || nConnect == CtrlLineArcs.CON_TSTART_OEND) // the pts of both lines are in the same direction
                {
                    oCur.combine(oCmp, nConnect); // combine the points of oCmp into oCur's point array
                    oLanesByRoads.remove(nInner);
                    nInner = -1; // start inner loop over
                    --nLimit;
                }
            }
            oCombined.add(oCur);
        }
        return oCombined;
    }
References cc.ctrl.CtrlLineArcs.CMPBYLANE, cc.ctrl.CtrlLineArcs.combine(), cc.ctrl.proc.ProcCtrl.combineLaneByRoad(), cc.ctrl.CtrlLineArcs.CON_TEND_OSTART, cc.ctrl.CtrlLineArcs.CON_TSTART_OEND, cc.ctrl.CtrlLineArcs.connects(), cc.geosrv.xodr.XodrUtil.getRoadId(), cc.ctrl.CtrlLineArcs.m_nLaneId, cc.ctrl.CtrlLineArcs.m_nLaneType, and cc.ctrl.proc.ProcDebug.m_oJunctions.
Referenced by cc.ctrl.proc.ProcDebug.proc().
parseMetadata()
void cc.ctrl.proc.ProcDebug.parseMetadata (Path oSource) throws Exception inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 51 of file ProcDebug.java.
    {
        m_oJunctions = new XodrJunctionParser().parseXodrIntersections(oSource);
    }
References cc.ctrl.proc.ProcDebug.m_oJunctions, and cc.geosrv.xodr.XodrJunctionParser.parseXodrIntersections().
Referenced by cc.ctrl.proc.ProcDebug.proc().
proc()
void cc.ctrl.proc.ProcDebug.proc (String sLineArcsFile, double dTol) inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 59 of file ProcDebug.java.
    {
        try
        {
            parseMetadata(Paths.get(m_sXodrDir + sLineArcsFile.substring(sLineArcsFile.lastIndexOf("/")).replace(".bin", ".xodr")));
            ArrayList<TrafCtrl> oCtrls = new ArrayList();
            ArrayList<CtrlLineArcs> oLineArcs = new ArrayList();
            try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(Paths.get(sLineArcsFile)))))
            {
                while (oIn.available() > 0)
                {
                    oLineArcs.add(new CtrlLineArcs(oIn));
                }
            }
            oLineArcs = combine(oLineArcs, dTol);
            ArrayList<int[]> oTiles = new ArrayList();
            for (CtrlLineArcs oCLA : oLineArcs)
            {
                TrafCtrl oCtrl = new TrafCtrl("debug", "", 0, oCLA.m_dLineArcs, "", false, CC);
                oCtrls.add(oCtrl);
                oCtrl.write(g_sTrafCtrlDir, g_dExplodeStep, g_nDefaultZoom, CC);
                updateTiles(oTiles, oCtrl.m_oFullGeo.m_oTiles);
            }
            renderTiledData(oCtrls, oTiles);
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.ctrl.proc.ProcCtrl.CC, cc.ctrl.proc.ProcDebug.combine(), cc.ctrl.proc.ProcCtrl.g_dExplodeStep, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTrafCtrlDir, cc.ctrl.TrafCtrl.m_oFullGeo, cc.ctrl.CtrlGeo.m_oTiles, cc.ctrl.proc.ProcDebug.m_sXodrDir, cc.util.FileUtil.newInputStream(), cc.ctrl.proc.ProcDebug.parseMetadata(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.ctrl.proc.ProcCtrl.updateTiles(), and cc.ctrl.TrafCtrl.write().
renderTiledData()
static void cc.ctrl.proc.ProcDebug.renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException inline static
Definition at line 141 of file ProcDebug.java.
    {
        String[] sEmpty = new String[0];
        TdLayer oPoints = new TdLayer("debug-p", new String[]{"color"}, new String[]{"black", "blue", "red"}, TdLayer.POINT);
        TdLayer oCenters = new TdLayer("debug-c", sEmpty, sEmpty, TdLayer.LINESTRING);
        for (TrafCtrl oCtrl : oCtrls)
        {
            writeGeoLanes(oCtrl);
        }
//      ArrayList<EncodedGeo> oGeos = new ArrayList();
//      StringBuilder sBuf = new StringBuilder(16);
//      EncodedGeo oSearch = new EncodedGeo(sBuf);
//      for (TrafCtrl oCtrl : oCtrls)
//      {
//          TrafCtrl.getId(oCtrl.m_yId, sBuf);
//          EncodedGeo oGeo = new EncodedGeo(sBuf.toString());
//          oGeo.add(getEncodedLonLats(oCtrl.m_oFullGeo.m_dNT));
//          oGeo.add(getEncodedLonLats(oCtrl.m_oFullGeo.m_dC));
//          oGeo.add(getEncodedLonLats(oCtrl.m_oFullGeo.m_dPT));
//          int nIndex = Collections.binarySearch(oGeos, oGeo);
//          if (nIndex < 0)
//          {
//              oGeos.add(~nIndex, oGeo);
//          }
//      }
        ArrayList<double[]> oClipped = new ArrayList();
        int[] nTags = new int[2];
        int[] nCenterTags = new int[0];
//      int[] nCenterTags = new int[]{0, 0, 1, 1, 2, 2};
        double[] dCenter = new double[2];
        double[] dSeg = new double[6];
        double[] dPts = Arrays.newDoubleArray();
        double[] dPt = Arrays.newDoubleArray();
        for (int[] nTile : nTiles)
        {
            int nX = nTile[0];
            int nY = nTile[1];
            Files.createDirectories(Paths.get(String.format(g_sTdFileFormat, nX, 0, 0, 0)).getParent(), FileUtil.DIRPERS);
            writeIndexFile(oCtrls, nX, nY);
            oPoints.clear();
            oCenters.clear();
    //              ArrayList<String> oEncodedLonLats = new ArrayList();
            double[] dClipBounds = TileUtil.getClippingBounds(g_nDefaultZoom, nX, nY);
    //              for (TrafCtrl oCtrl : oCtrls)
    //              {
    //                  if (!Geo.boundingBoxesIntersect(oCtrl.m_oFullGeo.m_dBB, dClipBounds))
    //                     continue;
    //                  TrafCtrl.getId(oCtrl.m_yId, sBuf);
    //                  for (String sLonLats : oGeos.get(Collections.binarySearch(oGeos, oSearch)))
    //                  {
    //                      int nSearch = Collections.binarySearch(oEncodedLonLats, sLonLats);
    //                      if (nSearch < 0)
    //                          oEncodedLonLats.add(~nSearch, sLonLats);
    //                  }
    //              }
    //              String[] sLayerLonLats = new String[oEncodedLonLats.size()];
    //              for (int nIndex = 0; nIndex < sLayerLonLats.length; nIndex++)
    //                  sLayerLonLats[nIndex] = oEncodedLonLats.get(nIndex);
    //              TdLayer oCenters = new TdLayer("debug-c", new String[]{"nt", "c", "pt"}, sLayerLonLats, TdLayer.LINESTRING);
            for (TrafCtrl oCtrl : oCtrls)
            {
                if (Collections.binarySearch(oCtrl.m_oFullGeo.m_oTiles, nTile, Mercator.TILECOMP) < 0)
                    continue;
                oClipped.clear();
    //                  TrafCtrl.getId(oCtrl.m_yId, sBuf);
    //                  EncodedGeo oGeo = oGeos.get(Collections.binarySearch(oGeos, oSearch));
    //                  nCenterTags[1] = Collections.binarySearch(oEncodedLonLats, oGeo.get(0));
    //                  nCenterTags[3] = Collections.binarySearch(oEncodedLonLats, oGeo.get(1));
    //                  nCenterTags[5] = Collections.binarySearch(oEncodedLonLats, oGeo.get(2));
                TileUtil.clipLineString(oCtrl.m_oFullGeo.m_dC, dClipBounds, oClipped);
                for (double[] dLine : oClipped)
                {
                    oCenters.add(new TdFeature(dLine, nCenterTags, oCtrl));
                }
                int nNumPts = oCtrl.size();
                dPts[0] = 1;
                dPts = Arrays.ensureCapacity(dPts, nNumPts * 2);
                int nPrevX = Mercator.lonToCm(Geo.fromIntDeg(oCtrl.m_nLon));
                int nPrevY = Mercator.latToCm(Geo.fromIntDeg(oCtrl.m_nLat));
                for (int nIndex = 0; nIndex < oCtrl.size(); nIndex++)
                {
                    TrafCtrlPt oTemp = oCtrl.get(nIndex);
                    int nXCo = oTemp.m_nX + nPrevX;
                    int nYCo = oTemp.m_nY + nPrevY;
                    dPts = Arrays.add(dPts, nXCo / 100.0, nYCo / 100.0); // convert mercator cm to mercator meters
                    nPrevX = nXCo;
                    nPrevY = nYCo;
                }
                Iterator<double[]> oIt = Arrays.iterator(dPts, dSeg, 1, 4);
                while (oIt.hasNext())
                {
                    oIt.next();
                    if (Geo.isInside(dSeg[0], dSeg[1], dClipBounds[3], dClipBounds[2], dClipBounds[1], dClipBounds[0], 0))
                    {
                        nTags[1] = 0;
                        dPt = Arrays.add(dPt, dSeg[0], dSeg[1]);
                        oPoints.add(new TdFeature(dPt, nTags, oCtrl));
                        dPt[0] = 1;
                    }
                    if (Geo.isInside(dSeg[2], dSeg[3], dClipBounds[3], dClipBounds[2], dClipBounds[1], dClipBounds[0], 0))
                    {
                        double dR = Geo.circle(dSeg[0], dSeg[1], dSeg[2], dSeg[3], dSeg[4], dSeg[5], dCenter);
                        if (Double.isFinite(dR) && dR < 10000)
                            nTags[1] = 1;
                        else
                            nTags[1] = 2;
                        dPt = Arrays.add(dPt, dSeg[2], dSeg[3]);
                        oPoints.add(new TdFeature(dPt, nTags, oCtrl));
                        dPt[0] = 1;
                    }
                }
                if (Geo.isInside(dSeg[4], dSeg[5], dClipBounds[3], dClipBounds[2], dClipBounds[1], dClipBounds[0], 0))
                {
                    nTags[1] = 0;
                    dPt = Arrays.add(dPt, dSeg[4], dSeg[5]);
                    oPoints.add(new TdFeature(dPt, nTags, oCtrl));
                    dPt[0] = 1;
                }
            }
            if (!oPoints.isEmpty())
            {
                try (DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(String.format(g_sTdFileFormat, nX, g_nDefaultZoom, nX, nY)), FileUtil.APPENDTO, FileUtil.FILEPERS))))
                {
                    oPoints.write(oOut);
                    oCenters.write(oOut);
                }
            }
        }
    }
References cc.util.Arrays.add(), cc.util.FileUtil.APPENDTO, cc.util.Geo.circle(), cc.util.TileUtil.clipLineString(), cc.util.FileUtil.DIRPERS, cc.util.Arrays.ensureCapacity(), cc.util.FileUtil.FILEPERS, cc.util.Geo.fromIntDeg(), cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTdFileFormat, cc.util.TileUtil.getClippingBounds(), cc.util.Geo.isInside(), cc.util.Arrays.iterator(), cc.geosrv.Mercator.latToCm(), cc.ctrl.proc.TdLayer.LINESTRING, cc.geosrv.Mercator.lonToCm(), cc.util.Arrays.newDoubleArray(), cc.util.FileUtil.newOutputStream(), cc.ctrl.proc.TdLayer.POINT, cc.geosrv.Mercator.TILECOMP, cc.ctrl.proc.TdLayer.write(), cc.ctrl.proc.ProcDebug.writeGeoLanes(), and cc.ctrl.proc.ProcCtrl.writeIndexFile().
Referenced by cc.ctrl.proc.ProcDebug.proc(), and cc.ws.CtrlTiles.splitLineArcs().
writeGeoLanes()
static void cc.ctrl.proc.ProcDebug.writeGeoLanes (TrafCtrl oCtrl) throws IOException inline static private
Definition at line 283 of file ProcDebug.java.
    {
        StringBuilder sBuf = new StringBuilder();
        sBuf.append("{");
        sBuf.append("\"a\":[");
        double[] dPts = oCtrl.m_oFullGeo.m_dPT;
        double[] dPt = new double[2];
        Iterator<double[]> oIt = Arrays.iterator(dPts, dPt, 1, 2);
        oIt.next();
        int nPrevX = Geo.toIntDeg(Mercator.xToLon(dPt[0]));
        int nPrevY = Geo.toIntDeg(Mercator.yToLat(dPt[1]));
        sBuf.append(nPrevX).append(",").append(nPrevY);
        while (oIt.hasNext())
        {
            oIt.next();
            int nX = Geo.toIntDeg(Mercator.xToLon(dPt[0]));
            int nY = Geo.toIntDeg(Mercator.yToLat(dPt[1]));
            sBuf.append(",").append(nX - nPrevX).append(",").append(nY- nPrevY);
            nPrevX = nX;
            nPrevY = nY;
        }
        sBuf.append("],");
        sBuf.append("\"b\":[");
        dPts = oCtrl.m_oFullGeo.m_dNT;
        oIt = Arrays.iterator(dPts, dPt, 1, 2);
        oIt.next();
        nPrevX = Geo.toIntDeg(Mercator.xToLon(dPt[0]));
        nPrevY = Geo.toIntDeg(Mercator.yToLat(dPt[1]));
        sBuf.append(nPrevX).append(",").append(nPrevY);
        while (oIt.hasNext())
        {
            oIt.next();
            int nX = Geo.toIntDeg(Mercator.xToLon(dPt[0]));
            int nY = Geo.toIntDeg(Mercator.yToLat(dPt[1]));
            sBuf.append(",").append(nX - nPrevX).append(",").append(nY- nPrevY);
            nPrevX = nX;
            nPrevY = nY;
        }
        sBuf.append("],");
        sBuf.append("\"c\":[");
        dPts = oCtrl.m_oFullGeo.m_dC;
        oIt = Arrays.iterator(dPts, dPt, 1, 2);
        oIt.next();
        nPrevX = Geo.toIntDeg(Mercator.xToLon(dPt[0]));
        nPrevY = Geo.toIntDeg(Mercator.yToLat(dPt[1]));
        sBuf.append(nPrevX).append(",").append(nPrevY);
        while (oIt.hasNext())
        {
            oIt.next();
            int nX = Geo.toIntDeg(Mercator.xToLon(dPt[0]));
            int nY = Geo.toIntDeg(Mercator.yToLat(dPt[1]));
            sBuf.append(",").append(nX - nPrevX).append(",").append(nY- nPrevY);
            nPrevX = nX;
            nPrevY = nY;
        }
        sBuf.append("]");
        sBuf.append("}");
        Path oPath = Paths.get(g_sGeolanesDir + TrafCtrl.getId(oCtrl.m_yId));
        Files.createDirectories(oPath.getParent(), FileUtil.DIRPERS);
        try (BufferedWriter oOut = new BufferedWriter(Channels.newWriter(Files.newByteChannel(oPath, FileUtil.WRITE, FileUtil.FILEPERS), "UTF-8")))
        {
            oOut.append(sBuf);
        }
    }
References cc.util.FileUtil.DIRPERS, cc.util.FileUtil.FILEPERS, cc.ctrl.proc.ProcCtrl.g_sGeolanesDir, cc.ctrl.TrafCtrl.getId(), cc.util.Arrays.iterator(), cc.util.Geo.toIntDeg(), cc.util.FileUtil.WRITE, cc.geosrv.Mercator.xToLon(), and cc.geosrv.Mercator.yToLat().
Referenced by cc.ctrl.proc.ProcDebug.renderTiledData().
Member Data Documentation
m_oJunctions
HashMap<String, String> cc.ctrl.proc.ProcDebug.m_oJunctions private
Definition at line 40 of file ProcDebug.java.
Referenced by cc.ctrl.proc.ProcDebug.combine(), and cc.ctrl.proc.ProcDebug.parseMetadata().
m_sXodrDir
String cc.ctrl.proc.ProcDebug.m_sXodrDir private
Definition at line 41 of file ProcDebug.java.
Referenced by cc.ctrl.proc.ProcDebug.ProcDebug(), and cc.ctrl.proc.ProcDebug.proc().
The documentation for this class was generated from the following file:
src/cc/ctrl/proc/ProcDebug.java