Carma-cloud: cc.ctrl.proc.ProcClosing Class Reference
cc.ctrl.proc.ProcClosing Class Reference
Public Member Functions
ProcClosing (String sLineArcDir)
void parseMetadata (Path oSource) throws Exception
ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
ProcCtrl (String sLineArcDir)
void parseMetadata (String sSource) throws Exception
abstract void parseMetadata (Path oSource) throws Exception
void process (String sLineArcsFile, double dTol) throws Exception
abstract ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Static Public Member Functions
static void renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> oTiles) throws IOException
Static Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
static void setStaticVariables (double dStep, String sDir, String sTdFF, int nZoom)
static void updateTiles (ArrayList< int[]> oTiles, ArrayList< int[]> oCtrlTiles)
static void updateTileRange (int[] nTileIndices, int[] nTmpTiles)
static ArrayList< CtrlLineArcs > combineLaneByRoad (ArrayList< CtrlLineArcs > oLineArcs, double dTol)
static void writeIndexFile (ArrayList< TrafCtrl > oCtrls, int nX, int nY) throws IOException
static void updateIndex (String sIndexFile, TrafCtrl oCtrl, long lTimestamp) throws IOException
static void renderCtrls (String sCtrlType, ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
static boolean deleteControl (String sId) throws Exception
static boolean deleteControl (TrafCtrl oCtrl)
static ArrayList< TrafCtrl > getCurrentControls (int nCtrlType, double dMinLon, double dMinLat, double dMaxLon, double dMaxLat, boolean bLoadFullGeo)
Protected Member Functions
void proc (String sLineArcsFile, double dTol) throws Exception
abstract void proc (String sLineArcsFile, double dTol) throws Exception
Additional Inherited Members
Public Attributes inherited from cc.ctrl.proc.ProcCtrl
String m_sLineArcDir
Static Public Attributes inherited from cc.ctrl.proc.ProcCtrl
static final Object INDEXLOCK = new Object()
static double g_dExplodeStep
static String g_sTrafCtrlDir
static String g_sTdFileFormat
static String g_sGeolanesDir
static int g_nDefaultZoom = Integer.MIN_VALUE
static final byte CC = 0
static final byte RSM = 1
static final byte IHP2 = 2
Static Protected Member Functions inherited from cc.ctrl.proc.ProcCtrl
static boolean checkTileRange (int[] nTileIndices)
Static Protected Attributes inherited from cc.ctrl.proc.ProcCtrl
static final double WIDTHTH = 1.5
static final double LENLOWTH = 75.0
static final double STOPLINEENDOFFSET = 0.6
static final double STOPLINELATOFFSET = 0.1
static double[][] NUMBERS
static Comparator< int[]> LANETYPECOMP
static final HashMap< String, double[]> CHARS = new HashMap()
Static Package Functions inherited from cc.ctrl.proc.ProcCtrl
[static initializer]
static double getCoordAndHeadingAtLength (double[] dPoints, double dLength, boolean bReverse, double[] dPoint)
static int getStopLine (TrafCtrl oCtrl, ArrayList< double[]> oStops)
Detailed Description
Author
aaron.cherney
Definition at line 32 of file ProcClosing.java.
Constructor & Destructor Documentation
ProcClosing()
cc.ctrl.proc.ProcClosing.ProcClosing (String sLineArcDir) inline
Definition at line 34 of file ProcClosing.java.
    {
        super(sLineArcDir);
    }
Member Function Documentation
combine()
ArrayList< CtrlLineArcs > cc.ctrl.proc.ProcClosing.combine (ArrayList< CtrlLineArcs > oLanes, double dTol) inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 165 of file ProcClosing.java.
    {
        return oLanes;
    }
parseMetadata()
void cc.ctrl.proc.ProcClosing.parseMetadata (Path oSource) throws Exception inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 40 of file ProcClosing.java.
    {
    }
proc()
void cc.ctrl.proc.ProcClosing.proc (String sLineArcsFile, double dTol) throws Exception inline protected
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 47 of file ProcClosing.java.
    {
        try
        {
            ArrayList<TrafCtrl> oCtrls = new ArrayList();
            ArrayList<CtrlLineArcs> oLineArcs = new ArrayList();
            try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(Paths.get(sLineArcsFile)))))
            {
                while (oIn.available() > 0)
                {
                    oLineArcs.add(new CtrlLineArcs(oIn));
                }
            }
            ArrayList<int[]> oTiles = new ArrayList();
            for (CtrlLineArcs oCLA : oLineArcs)
            {
                String sType = XodrUtil.getLaneType(oCLA.m_nLaneType);
                if (!sType.contains("special1"))
                    continue;
                TrafCtrl oCtrl = new TrafCtrl("closing", sType.contains("1") ? "right" : "left", 0, oCLA.m_dLineArcs, "", true, CC);
                oCtrls.add(oCtrl);
                oCtrl.write(g_sTrafCtrlDir, g_dExplodeStep, g_nDefaultZoom, CC);
                updateTiles(oTiles, oCtrl.m_oFullGeo.m_oTiles);
            }
            renderTiledData(oCtrls, oTiles);
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.ctrl.proc.ProcCtrl.CC, cc.ctrl.proc.ProcCtrl.g_dExplodeStep, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTrafCtrlDir, cc.geosrv.xodr.XodrUtil.getLaneType(), cc.ctrl.TrafCtrl.m_oFullGeo, cc.ctrl.CtrlGeo.m_oTiles, cc.util.FileUtil.newInputStream(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.ctrl.proc.ProcCtrl.updateTiles(), and cc.ctrl.TrafCtrl.write().
renderTiledData()
static void cc.ctrl.proc.ProcClosing.renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> oTiles) throws IOException inline static
Definition at line 81 of file ProcClosing.java.
    {
        String[] sEmpty = new String[0];
        TdLayer oLayer = new TdLayer("closing-poly", sEmpty, sEmpty, TdLayer.POLYGON);
        TdLayer oLayerOutline  = new TdLayer("closing-outline", sEmpty, sEmpty, TdLayer.LINESTRING);
        int[] nTags = new int[0];
        ArrayList<double[]> dTapers = new ArrayList();
        for (TrafCtrl oCtrl : oCtrls)
        {
            int nPoints = (int)(oCtrl.m_oFullGeo.m_dLength / 0.2) + 1;
            double dPercent = 1.0 / nPoints;
            int nCount = 0;
            double[] dC = oCtrl.m_oFullGeo.m_dC;
            int nCtrlVal = MathUtil.bytesToInt(oCtrl.m_yControlValue);
            boolean bRight = TrafCtrlEnums.getCtrlVal("closing", "right") == nCtrlVal;
            double[] dStraight = bRight ? oCtrl.m_oFullGeo.m_dNT : oCtrl.m_oFullGeo.m_dPT;
            int nLimit = Arrays.size(dC) - 2;
            double dDist = 0.0;
            double[] dTaper = Arrays.newDoubleArray(nPoints * 2);
            dTaper = Arrays.add(dTaper, dStraight[1], dStraight[2]);
            for (int nIndex = 1; nIndex < nLimit; nIndex += 2)
            {
                double dX1 = dC[nIndex];
                double dY1 = dC[nIndex + 1];
                double dX2 = dC[nIndex + 2];
                double dY2 = dC[nIndex + 3];
                dDist += Geo.distance(dX1, dY1, dX2, dY2);
                if (dDist >= 0.2)
                {
                    dDist = 0.0;
                    double dX3 = dStraight[nIndex];
                    double dY3 = dStraight[nIndex + 1];
                    double dHeading = Geo.heading(dX3, dY3, dX1, dY1);
                    double dOffset = Geo.distance(dX3, dY3, dX1, dY1) * 2 * dPercent * ++nCount;
                    dTaper = Arrays.add(dTaper, dX3 + Math.cos(dHeading) * dOffset, dY3 + Math.sin(dHeading) * dOffset);
                }
            }
            if (bRight)
            {
                dTapers.add(dTaper);
                dTapers.add(dStraight);
            }
            else
            {
                dTapers.add(dStraight);
                dTapers.add(dTaper);
            }
        }
        for (int[] nTile : oTiles)
        {
            int nX = nTile[0];
            int nY = nTile[1];
            Files.createDirectories(Paths.get(String.format(g_sTdFileFormat, nX, 0, 0, 0)).getParent(), FileUtil.DIRPERS);
            writeIndexFile(oCtrls, nX, nY);
            oLayer.clear();
            oLayerOutline.clear();
            int nTaperCnt = 0;
            for (TrafCtrl oCtrl : oCtrls)
            {
                if (Collections.binarySearch(oCtrl.m_oFullGeo.m_oTiles, nTile, Mercator.TILECOMP) < 0)
                {
                    nTaperCnt += 2;
                    continue;
                }
                double[] dPoly = Geo.createPolygon(dTapers.get(nTaperCnt++), dTapers.get(nTaperCnt++));
                oLayer.add(new TdFeature(dPoly, nTags, oCtrl));
                dPoly = Arrays.add(dPoly, dPoly[1], dPoly[2]);
                oLayerOutline.add(new TdFeature(dPoly, nTags, oCtrl));
            }
            if (!oLayer.isEmpty())
            {
                try (DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(String.format(g_sTdFileFormat, nX, g_nDefaultZoom, nX, nY)), FileUtil.APPENDTO, FileUtil.FILEPERS))))
                {
                    oLayer.write(oOut);
                    oLayerOutline.write(oOut);
                }
            }
        }
    }
References cc.util.Arrays.add(), cc.util.FileUtil.APPENDTO, cc.util.MathUtil.bytesToInt(), cc.util.Geo.createPolygon(), cc.util.FileUtil.DIRPERS, cc.util.Geo.distance(), cc.util.FileUtil.FILEPERS, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTdFileFormat, cc.ctrl.TrafCtrlEnums.getCtrlVal(), cc.util.Geo.heading(), cc.ctrl.proc.TdLayer.LINESTRING, cc.util.Arrays.newDoubleArray(), cc.util.FileUtil.newOutputStream(), cc.ctrl.proc.TdLayer.POLYGON, cc.util.Arrays.size(), cc.geosrv.Mercator.TILECOMP, cc.ctrl.proc.TdLayer.write(), and cc.ctrl.proc.ProcCtrl.writeIndexFile().
Referenced by cc.ctrl.CreateCtrls.createCtrl(), cc.ctrl.RenderCtrl.main(), cc.ctrl.proc.ProcClosing.proc(), and cc.ctrl.proc.ProcCtrl.renderCtrls().
The documentation for this class was generated from the following file:
src/cc/ctrl/proc/ProcClosing.java