Carma-cloud: cc.ctrl.proc.ProcLatPerm Class Reference
cc.ctrl.proc.ProcLatPerm Class Reference
Public Member Functions
ProcLatPerm (String sLineArcDir)
void parseMetadata (Path oSource) throws Exception
int getInnerLatPerm (String sRdMkType, String sLaneType, boolean bSameDir)
int getOuterLatPerm (String sRdMkType, String sLaneType, boolean bSameDir)
ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
ProcCtrl (String sLineArcDir)
void parseMetadata (String sSource) throws Exception
abstract void parseMetadata (Path oSource) throws Exception
void process (String sLineArcsFile, double dTol) throws Exception
abstract ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Static Public Member Functions
static void renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles, int[] nLineColors) throws IOException
Static Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
static void setStaticVariables (double dStep, String sDir, String sTdFF, int nZoom)
static void updateTiles (ArrayList< int[]> oTiles, ArrayList< int[]> oCtrlTiles)
static void updateTileRange (int[] nTileIndices, int[] nTmpTiles)
static ArrayList< CtrlLineArcs > combineLaneByRoad (ArrayList< CtrlLineArcs > oLineArcs, double dTol)
static void writeIndexFile (ArrayList< TrafCtrl > oCtrls, int nX, int nY) throws IOException
static void updateIndex (String sIndexFile, TrafCtrl oCtrl, long lTimestamp) throws IOException
static void renderCtrls (String sCtrlType, ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
static boolean deleteControl (String sId) throws Exception
static boolean deleteControl (TrafCtrl oCtrl)
static ArrayList< TrafCtrl > getCurrentControls (int nCtrlType, double dMinLon, double dMinLat, double dMaxLon, double dMaxLat, boolean bLoadFullGeo)
Protected Member Functions
void proc (String sLineArcsFile, double dTol) throws Exception
abstract void proc (String sLineArcsFile, double dTol) throws Exception
Static Private Member Functions
static void createDashedLine (double[] dLine, ArrayList< double[]> oLines, boolean bOuter)
Private Attributes
ArrayList< int[]> m_oRdMkInfo = new ArrayList()
int[] m_nColors = Arrays.newIntArray()
Static Private Attributes
static double RDMKOFFSET = 0.16
static double BROKENSPACE = 9.144
static double BROKENLINE = 3.048
static Comparator< int[]> RDMKCOMP
Additional Inherited Members
Public Attributes inherited from cc.ctrl.proc.ProcCtrl
String m_sLineArcDir
Static Public Attributes inherited from cc.ctrl.proc.ProcCtrl
static final Object INDEXLOCK = new Object()
static double g_dExplodeStep
static String g_sTrafCtrlDir
static String g_sTdFileFormat
static String g_sGeolanesDir
static int g_nDefaultZoom = Integer.MIN_VALUE
static final byte CC = 0
static final byte RSM = 1
static final byte IHP2 = 2
Static Protected Member Functions inherited from cc.ctrl.proc.ProcCtrl
static boolean checkTileRange (int[] nTileIndices)
Static Protected Attributes inherited from cc.ctrl.proc.ProcCtrl
static final double WIDTHTH = 1.5
static final double LENLOWTH = 75.0
static final double STOPLINEENDOFFSET = 0.6
static final double STOPLINELATOFFSET = 0.1
static double[][] NUMBERS
static Comparator< int[]> LANETYPECOMP
static final HashMap< String, double[]> CHARS = new HashMap()
Static Package Functions inherited from cc.ctrl.proc.ProcCtrl
[static initializer]
static double getCoordAndHeadingAtLength (double[] dPoints, double dLength, boolean bReverse, double[] dPoint)
static int getStopLine (TrafCtrl oCtrl, ArrayList< double[]> oStops)
Detailed Description
Author
aaron.cherney
Definition at line 36 of file ProcLatPerm.java.
Constructor & Destructor Documentation
ProcLatPerm()
cc.ctrl.proc.ProcLatPerm.ProcLatPerm (String sLineArcDir) inline
Definition at line 53 of file ProcLatPerm.java.
    {
        super(sLineArcDir);
    }
Member Function Documentation
combine()
ArrayList< CtrlLineArcs > cc.ctrl.proc.ProcLatPerm.combine (ArrayList< CtrlLineArcs > oLanes, double dTol) inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 218 of file ProcLatPerm.java.
    {
        return oLanes;
    }
createDashedLine()
static void cc.ctrl.proc.ProcLatPerm.createDashedLine (double[] dLine, ArrayList< double[]> oLines, boolean bOuter) inline static private
Definition at line 354 of file ProcLatPerm.java.
    {
        double dTangent = bOuter ? Math.PI / 2 : -Math.PI / 2;
        double dLength = 0.0;
        double[] dSegment = new double[4];
        Iterator<double[]> oIt = Arrays.iterator(dLine, dSegment, 1, 2);
        while (oIt.hasNext())
        {
            oIt.next();
            dLength += Geo.distance(dSegment[0], dSegment[1], dSegment[2], dSegment[3]);
        }
        int nMarks = (int)Math.floor(dLength / (BROKENSPACE + BROKENLINE));
        double dMarkLength = (BROKENSPACE + BROKENLINE) * nMarks;
        double dOffset = (dLength - dMarkLength) / 2;
        oIt = Arrays.iterator(dLine, dSegment, 1, 2);
        dLength = 0.0;
        double dCurrent = dOffset;
        boolean bSpace = true;
        double[] dDash = Arrays.newDoubleArray();
        while (oIt.hasNext())
        {
            oIt.next();
            double dDist = Geo.distance(dSegment[0], dSegment[1], dSegment[2], dSegment[3]);
            dCurrent += dDist;
            if (bSpace)
            {
                if (dCurrent >= BROKENSPACE)
                {
                    bSpace = false;
                    dCurrent = 0.0;
                    dDash = Arrays.newDoubleArray();
                    dDash = Arrays.add(dDash, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                }
            }
            else
            {
                if (dCurrent >= BROKENLINE)
                {
                    bSpace = true;
                    dCurrent = 0.0;
                    oLines.add(dDash);
                }
                else
                {
                    double dHdg = Geo.heading(dSegment[0], dSegment[1], dSegment[2], dSegment[3]);
                    double dAngle = dHdg + dTangent;
                    dDash = Arrays.addAndUpdate(dDash, dSegment[0] + Math.cos(dAngle) * RDMKOFFSET, dSegment[1] + Math.sin(dAngle) * RDMKOFFSET);
                }
            }
        }
    }
References cc.util.Arrays.add(), cc.util.Arrays.addAndUpdate(), cc.ctrl.proc.ProcLatPerm.BROKENLINE, cc.ctrl.proc.ProcLatPerm.BROKENSPACE, cc.util.Geo.distance(), cc.util.Geo.heading(), cc.util.Arrays.iterator(), cc.util.Arrays.newDoubleArray(), and cc.ctrl.proc.ProcLatPerm.RDMKOFFSET.
Referenced by cc.ctrl.proc.ProcLatPerm.renderTiledData().
getInnerLatPerm()
int cc.ctrl.proc.ProcLatPerm.getInnerLatPerm (String sRdMkType, String sLaneType, boolean bSameDir) inline
Definition at line 145 of file ProcLatPerm.java.
    {
        String sVal = "none";
        switch (sLaneType)
        {
            case "offRamp":
            case "driving":
            {
                if (bSameDir)
                {
                    sVal = "permitted";
                }
                else
                {
//                  if (sLaneType.endsWith("solid")) // broken solid, solid, and solid solid
//                      return TrafCtrlEnums.getCtrlVal("latperm", "none");
                    if (sLaneType.endsWith("broken"))
                        sVal = "passing-only";
                }
                break;
            }
            case "onRamp":
            case "shoulder":
            {
                if (bSameDir)
                    sVal = "emergency-only";
            }
//          case "restricted":
//          case "none":
//          default:
        }
        return TrafCtrlEnums.getCtrlVal("latperm", sVal); //"none", "permitted", "passing-only", "emergency-only"
    }
References cc.ctrl.TrafCtrlEnums.getCtrlVal().
Referenced by cc.ctrl.proc.ProcLatPerm.proc().
getOuterLatPerm()
int cc.ctrl.proc.ProcLatPerm.getOuterLatPerm (String sRdMkType, String sLaneType, boolean bSameDir) inline
Definition at line 181 of file ProcLatPerm.java.
    {
        String sVal = "none";
        switch (sLaneType)
        {
            case "offRamp":
            case "driving":
            {
                if (bSameDir)
                {
                    sVal = "permitted";
                }
                else
                {
//                  if (sLaneType.startsWith("solid")) // broken solid, solid, and solid solid
//                      return TrafCtrlEnums.getCtrlVal("latperm", "none");
                    if (sLaneType.startsWith("broken"))
                        sVal = "passing-only";
                }
                break;
            }
            case "onRamp":
            case "shoulder":
            {
                if (bSameDir)
                    sVal = "emergency-only";
            }
//          case "restricted":
//          case "none":
//          default:
        }
        return TrafCtrlEnums.getCtrlVal("latperm", sVal); //"none", "permitted", "passing-only", "emergency-only"
    }
References cc.ctrl.TrafCtrlEnums.getCtrlVal().
Referenced by cc.ctrl.proc.ProcLatPerm.proc().
parseMetadata()
void cc.ctrl.proc.ProcLatPerm.parseMetadata (Path oSource) throws Exception inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 60 of file ProcLatPerm.java.
    {
        m_oRdMkInfo.clear();
        m_nColors[0] = 1;
        try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(oSource))))
        {
            while (oIn.available() > 0)
            {
                int[] nTemp = new int[oIn.readInt()]; // read number elements
                nTemp[0] = oIn.readInt(); // read first 4 bytes of id
                nTemp[1] = oIn.readInt(); // read second 4 bytes of id
                int nIndex = 3; // start at 3, index 2 will hold which set of tags is ready to be used
                while (nIndex < nTemp.length)
                    nTemp[nIndex++] = oIn.readInt();
                m_oRdMkInfo.add(nTemp);
            }
        }
        Collections.sort(m_oRdMkInfo, RDMKCOMP);
    }
References cc.ctrl.proc.ProcLatPerm.m_nColors, cc.ctrl.proc.ProcLatPerm.m_oRdMkInfo, cc.util.FileUtil.newInputStream(), and cc.ctrl.proc.ProcLatPerm.RDMKCOMP.
Referenced by cc.ctrl.proc.ProcLatPerm.proc().
proc()
void cc.ctrl.proc.ProcLatPerm.proc (String sLineArcsFile, double dTol) throws Exception inline protected
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 83 of file ProcLatPerm.java.
    {
        try
        {
            parseMetadata(Paths.get(sLineArcsFile + ".meta"));
            ArrayList<TrafCtrl> oCtrls = new ArrayList();
            ArrayList<CtrlLineArcs> oLineArcs = new ArrayList();
            try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(Paths.get(sLineArcsFile)))))
            {
                while (oIn.available() > 0)
                {
                    oLineArcs.add(new CtrlLineArcs(oIn));
                }
            }
            ArrayList<int[]> oTiles = new ArrayList();
            int[] nSearch = new int[2];
            int nShoulder = XodrUtil.getLaneType("shoulder");
            for (CtrlLineArcs oCLA : oLineArcs)
            {
                XodrUtil.splitLaneSectionId(oCLA.m_lLaneSectionId, 0, nSearch);
                int nSIndex = Collections.binarySearch(m_oRdMkInfo, nSearch, RDMKCOMP);
                int[] nTags = m_oRdMkInfo.get(nSIndex);
                int nIndex = nTags[2]++;
                nIndex = 3 + nIndex * 8;
                if (nIndex == nTags.length)
                {
                    System.out.println(oCLA.m_lLaneSectionId);
                }
                int nInnerMarkType = nTags[nIndex++];
                int nInnerColor = nTags[nIndex++];
                int nInnerRoadType = nTags[nIndex++];
                boolean bSameInnerDir = nTags[nIndex++] == 0;
                int nOuterMarkType = nTags[nIndex++];
                int nOuterColor = nTags[nIndex++];
                int nOuterRoadType = nTags[nIndex++];
                boolean bSameOuterDir = nTags[nIndex] == 0;
                String sRoadMark = RoadMark.getType(nInnerMarkType);
                String sLaneType = XodrUtil.getLaneType(nInnerRoadType);
                int nCtrlVal = getInnerLatPerm(sRoadMark, sLaneType, bSameInnerDir);
                nCtrlVal <<= 16;
                sRoadMark = RoadMark.getType(nOuterMarkType);
                sLaneType = XodrUtil.getLaneType(nOuterRoadType);
                nCtrlVal |= (getOuterLatPerm(sRoadMark, sLaneType, bSameOuterDir) & 0xff);
                TrafCtrl oCtrl = new TrafCtrl("latperm", nCtrlVal, 0, oCLA.m_dLineArcs, "", true, CC);
                if (oCLA.m_nLaneType != nShoulder)
                {
                    oCtrls.add(oCtrl);
                    m_nColors = Arrays.add(m_nColors, nInnerColor, nOuterColor);
                }
                oCtrl.write(g_sTrafCtrlDir, g_dExplodeStep, g_nDefaultZoom, CC);
                updateTiles(oTiles, oCtrl.m_oFullGeo.m_oTiles);
            }
            renderTiledData(oCtrls, oTiles, m_nColors);
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.util.Arrays.add(), cc.ctrl.proc.ProcCtrl.CC, cc.ctrl.proc.ProcCtrl.g_dExplodeStep, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTrafCtrlDir, cc.ctrl.proc.ProcLatPerm.getInnerLatPerm(), cc.geosrv.xodr.XodrUtil.getLaneType(), cc.ctrl.proc.ProcLatPerm.getOuterLatPerm(), cc.geosrv.xodr.rdmk.RoadMark.getType(), cc.ctrl.proc.ProcLatPerm.m_nColors, cc.ctrl.TrafCtrl.m_oFullGeo, cc.ctrl.proc.ProcLatPerm.m_oRdMkInfo, cc.ctrl.CtrlGeo.m_oTiles, cc.util.FileUtil.newInputStream(), cc.ctrl.proc.ProcLatPerm.parseMetadata(), cc.ctrl.proc.ProcLatPerm.RDMKCOMP, cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.geosrv.xodr.XodrUtil.splitLaneSectionId(), cc.ctrl.proc.ProcCtrl.updateTiles(), and cc.ctrl.TrafCtrl.write().
renderTiledData()
static void cc.ctrl.proc.ProcLatPerm.renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles, int[] nLineColors) throws IOException inline static
Definition at line 224 of file ProcLatPerm.java.
    {
        HashMap<String, ArrayList<double[]>> oCtrlInners = new HashMap();
        HashMap<String, ArrayList<double[]>> oCtrlOuters = new HashMap();
        int nNone = TrafCtrlEnums.getCtrlVal("latperm", "none");
        int nEmergency = TrafCtrlEnums.getCtrlVal("latperm", "emergency-only");
        double[] dSeg = new double[4];
        for (TrafCtrl oCtrl : oCtrls)
        {
            if (oCtrl.m_oFullGeo.m_dAverageWidth < WIDTHTH)
                continue;
            int nOuterVal = ((oCtrl.m_yControlValue[2] & 0xff) << 8) | (oCtrl.m_yControlValue[3] & 0xff);
            int nInnerVal = ((oCtrl.m_yControlValue[0] & 0xff) << 8) | (oCtrl.m_yControlValue[1] & 0xff);
            double[] dInner = oCtrl.m_oFullGeo.m_dPT;
            double[] dOuter = oCtrl.m_oFullGeo.m_dNT;
            String sId = TrafCtrl.getId(oCtrl.m_yId);
            oCtrlInners.put(sId, new ArrayList());
            oCtrlOuters.put(sId, new ArrayList());
            if (nOuterVal == nNone || nOuterVal == nEmergency)
            {
                Iterator<double[]> oIt = Arrays.iterator(dOuter, dSeg, 1, 2);
                double dHdg = 0.0;
                double dTangent = Math.PI / 2;
                double[] dOffsetLine = Arrays.newDoubleArray(Arrays.size(dOuter));
                dOffsetLine = Arrays.add(dOffsetLine, new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                while (oIt.hasNext())
                {
                    oIt.next();
                    dHdg = Geo.heading(dSeg[0], dSeg[1], dSeg[2], dSeg[3]);
                    double dAngle = dHdg + dTangent;
                    double dX = Math.cos(dAngle) * RDMKOFFSET;
                    double dY = Math.sin(dAngle) * RDMKOFFSET;
                    dOffsetLine = Arrays.addAndUpdate(dOffsetLine, dSeg[0] + dX, dSeg[1] + dY);
                }
                oCtrlOuters.get(sId).add(dOffsetLine);
            }
            else
            {
                createDashedLine(dOuter, oCtrlOuters.get(sId), true);
            }
            if (nInnerVal == nNone || nInnerVal == nEmergency)
            {
                Iterator<double[]> oIt = Arrays.iterator(dInner, dSeg, 1, 2);
                double dHdg = 0.0;
                double dTangent = -Math.PI / 2;
                double[] dOffsetLine = Arrays.newDoubleArray(Arrays.size(dInner));
                dOffsetLine = Arrays.add(dOffsetLine, new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                while (oIt.hasNext())
                {
                    oIt.next();
                    dHdg = Geo.heading(dSeg[0], dSeg[1], dSeg[2], dSeg[3]);
                    double dAngle = dHdg + dTangent;
                    double dX = Math.cos(dAngle) * RDMKOFFSET;
                    double dY = Math.sin(dAngle) * RDMKOFFSET;
                    dOffsetLine = Arrays.addAndUpdate(dOffsetLine, dSeg[0] + dX, dSeg[1] + dY);
                }
                oCtrlInners.get(sId).add(dOffsetLine);
            }
            else
            {
                createDashedLine(dInner, oCtrlInners.get(sId), false);
            }
        }
        TdLayer oLayer = new TdLayer("latperm", new String[]{"color"}, RoadMark.COLORS, TdLayer.LINESTRING);
        int[] nOuterTags = new int[2];
        int[] nInnerTags = new int[2];
        int[] nColors = new int[2];
        ArrayList<double[]> oClipped = new ArrayList();
        for (int[] nTile : nTiles)
        {
            int nX = nTile[0];
            int nY = nTile[1];
            Files.createDirectories(Paths.get(String.format(g_sTdFileFormat, nX, 0, 0, 0)).getParent(), FileUtil.DIRPERS);
            writeIndexFile(oCtrls, nX, nY);
            oLayer.clear();
            double[] dClipBounds = TileUtil.getClippingBounds(g_nDefaultZoom, nX, nY);
            Iterator<int[]> oColorIt = Arrays.iterator(nLineColors, nColors, 1, 2);
            for (TrafCtrl oCtrl : oCtrls)
            {
                oColorIt.next();
                if (Collections.binarySearch(oCtrl.m_oFullGeo.m_oTiles, nTile, Mercator.TILECOMP) < 0 || oCtrl.m_oFullGeo.m_dAverageWidth < WIDTHTH)
                    continue;
                nInnerTags[1] = nColors[0];
                nOuterTags[1] = nColors[1];
                String sId = TrafCtrl.getId(oCtrl.m_yId);
                ArrayList<double[]> dInners = oCtrlInners.get(sId);
                ArrayList<double[]> dOuters = oCtrlOuters.get(sId);
                for (double[] dInner : dInners)
                {
                    if (!Geo.boundingBoxesIntersect(dClipBounds[0], dClipBounds[1], dClipBounds[2], dClipBounds[3], dInner[1], dInner[2], dInner[3], dInner[4]))
                        continue;
                    oClipped.clear();
                    TileUtil.clipLineString(dInner, 5, dClipBounds, oClipped);
                    for (double[] dClipped : oClipped)
                    {
                        oLayer.add(new TdFeature(dClipped, nInnerTags, oCtrl));
                    }
                }
                for (double[] dOuter : dOuters)
                {
                    if (!Geo.boundingBoxesIntersect(dClipBounds[0], dClipBounds[1], dClipBounds[2], dClipBounds[3], dOuter[1], dOuter[2], dOuter[3], dOuter[4]))
                        continue;
                    oClipped.clear();
                    TileUtil.clipLineString(dOuter, 5, dClipBounds, oClipped);
                    for (double[] dClipped : oClipped)
                    {
                        oLayer.add(new TdFeature(dClipped, nOuterTags, oCtrl));
                    }
                }
            }
            if (!oLayer.isEmpty())
            {
                try (DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(String.format(g_sTdFileFormat, nX, g_nDefaultZoom, nX, nY)), FileUtil.APPENDTO, FileUtil.FILEPERS))))
                {
                    oLayer.write(oOut);
                }
            }
        }
    }
References cc.util.Arrays.add(), cc.util.Arrays.addAndUpdate(), cc.util.FileUtil.APPENDTO, cc.util.Geo.boundingBoxesIntersect(), cc.util.TileUtil.clipLineString(), cc.geosrv.xodr.rdmk.RoadMark.COLORS, cc.ctrl.proc.ProcLatPerm.createDashedLine(), cc.util.FileUtil.DIRPERS, cc.util.FileUtil.FILEPERS, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTdFileFormat, cc.util.TileUtil.getClippingBounds(), cc.ctrl.TrafCtrlEnums.getCtrlVal(), cc.ctrl.TrafCtrl.getId(), cc.util.Geo.heading(), cc.util.Arrays.iterator(), cc.ctrl.proc.TdLayer.LINESTRING, cc.util.Arrays.newDoubleArray(), cc.util.FileUtil.newOutputStream(), cc.ctrl.proc.ProcLatPerm.RDMKOFFSET, cc.util.Arrays.size(), cc.geosrv.Mercator.TILECOMP, cc.ctrl.proc.ProcCtrl.WIDTHTH, cc.ctrl.proc.TdLayer.write(), and cc.ctrl.proc.ProcCtrl.writeIndexFile().
Referenced by cc.ctrl.CreateCtrls.createCtrl(), cc.ctrl.RenderCtrl.main(), cc.ctrl.proc.ProcLatPerm.proc(), cc.ctrl.proc.ProcCtrl.renderCtrls(), and cc.ws.CtrlTiles.splitLineArcs().
Member Data Documentation
BROKENLINE
double cc.ctrl.proc.ProcLatPerm.BROKENLINE = 3.048 static private
Definition at line 41 of file ProcLatPerm.java.
Referenced by cc.ctrl.proc.ProcLatPerm.createDashedLine().
BROKENSPACE
double cc.ctrl.proc.ProcLatPerm.BROKENSPACE = 9.144 static private
Definition at line 40 of file ProcLatPerm.java.
Referenced by cc.ctrl.proc.ProcLatPerm.createDashedLine().
m_nColors
int [] cc.ctrl.proc.ProcLatPerm.m_nColors = Arrays.newIntArray() private
Definition at line 43 of file ProcLatPerm.java.
Referenced by cc.ctrl.proc.ProcLatPerm.parseMetadata(), and cc.ctrl.proc.ProcLatPerm.proc().
m_oRdMkInfo
ArrayList<int[]> cc.ctrl.proc.ProcLatPerm.m_oRdMkInfo = new ArrayList() private
Definition at line 42 of file ProcLatPerm.java.
Referenced by cc.ctrl.proc.ProcLatPerm.parseMetadata(), and cc.ctrl.proc.ProcLatPerm.proc().
RDMKCOMP
Comparator<int[]> cc.ctrl.proc.ProcLatPerm.RDMKCOMP static private
Initial value:
= (int[] n1, int[] n2) ->
    {
        int nRet = Integer.compare(n1[1], n2[1]);
        if (nRet == 0)
            nRet = Integer.compare(n1[0], n2[0]);
        return nRet;
    }
Definition at line 44 of file ProcLatPerm.java.
Referenced by cc.ctrl.proc.ProcLatPerm.parseMetadata(), and cc.ctrl.proc.ProcLatPerm.proc().
RDMKOFFSET
double cc.ctrl.proc.ProcLatPerm.RDMKOFFSET = 0.16 static private
Definition at line 39 of file ProcLatPerm.java.
Referenced by cc.ctrl.proc.ProcLatPerm.createDashedLine(), and cc.ctrl.proc.ProcLatPerm.renderTiledData().
The documentation for this class was generated from the following file:
src/cc/ctrl/proc/ProcLatPerm.java