Carma-cloud: cc.ctrl.proc.ProcSignal Class Reference
cc.ctrl.proc.ProcSignal Class Reference
Public Member Functions
ProcSignal (String sLineArcDir, String sXodrDir)
void parseMetadata (Path oSource) throws Exception
void proc (String sLineArcsFile, double dTol)
ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
ProcCtrl (String sLineArcDir)
void parseMetadata (String sSource) throws Exception
abstract void parseMetadata (Path oSource) throws Exception
void process (String sLineArcsFile, double dTol) throws Exception
abstract ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Static Public Member Functions
static void renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
Static Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
static void setStaticVariables (double dStep, String sDir, String sTdFF, int nZoom)
static void updateTiles (ArrayList< int[]> oTiles, ArrayList< int[]> oCtrlTiles)
static void updateTileRange (int[] nTileIndices, int[] nTmpTiles)
static ArrayList< CtrlLineArcs > combineLaneByRoad (ArrayList< CtrlLineArcs > oLineArcs, double dTol)
static void writeIndexFile (ArrayList< TrafCtrl > oCtrls, int nX, int nY) throws IOException
static void updateIndex (String sIndexFile, TrafCtrl oCtrl, long lTimestamp) throws IOException
static void renderCtrls (String sCtrlType, ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
static boolean deleteControl (String sId) throws Exception
static boolean deleteControl (TrafCtrl oCtrl)
static ArrayList< TrafCtrl > getCurrentControls (int nCtrlType, double dMinLon, double dMinLat, double dMaxLon, double dMaxLat, boolean bLoadFullGeo)
Private Attributes
ArrayList< Junction > m_oJunctions = new ArrayList()
ArrayList< Signal > m_oSignals = new ArrayList()
int[] m_nInterPaths = Arrays.newIntArray()
int[] m_nSignalRoads = Arrays.newIntArray()
ArrayList< RoadPaths > m_oIncomingRoads = new ArrayList()
String m_sXodrDir
Static Private Attributes
static final double[][] SIGNAL
static final String[] COLORS = new String[]{"g", "y", "r"}
static double MINLEN = 53.0
static String[] SIGNAL_TYPES = new String[]{"1000001", "1000009", "1000010", "1000011"}
Additional Inherited Members
Public Attributes inherited from cc.ctrl.proc.ProcCtrl
String m_sLineArcDir
Static Public Attributes inherited from cc.ctrl.proc.ProcCtrl
static final Object INDEXLOCK = new Object()
static double g_dExplodeStep
static String g_sTrafCtrlDir
static String g_sTdFileFormat
static String g_sGeolanesDir
static int g_nDefaultZoom = Integer.MIN_VALUE
static final byte CC = 0
static final byte RSM = 1
static final byte IHP2 = 2
abstract void proc (String sLineArcsFile, double dTol) throws Exception
Static Protected Member Functions inherited from cc.ctrl.proc.ProcCtrl
static boolean checkTileRange (int[] nTileIndices)
Static Protected Attributes inherited from cc.ctrl.proc.ProcCtrl
static final double WIDTHTH = 1.5
static final double LENLOWTH = 75.0
static final double STOPLINEENDOFFSET = 0.6
static final double STOPLINELATOFFSET = 0.1
static double[][] NUMBERS
static Comparator< int[]> LANETYPECOMP
static final HashMap< String, double[]> CHARS = new HashMap()
Static Package Functions inherited from cc.ctrl.proc.ProcCtrl
[static initializer]
static double getCoordAndHeadingAtLength (double[] dPoints, double dLength, boolean bReverse, double[] dPoint)
static int getStopLine (TrafCtrl oCtrl, ArrayList< double[]> oStops)
Detailed Description
Author
aaron.cherney
Definition at line 39 of file ProcSignal.java.
Constructor & Destructor Documentation
ProcSignal()
cc.ctrl.proc.ProcSignal.ProcSignal (String sLineArcDir, String sXodrDir) inline
Definition at line 57 of file ProcSignal.java.
    {
        super(sLineArcDir);
        m_sXodrDir = sXodrDir;
    }
References cc.ctrl.proc.ProcSignal.m_sXodrDir.
Member Function Documentation
combine()
ArrayList< CtrlLineArcs > cc.ctrl.proc.ProcSignal.combine (ArrayList< CtrlLineArcs > oLanes, double dTol) inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 151 of file ProcSignal.java.
    {
        ArrayList<CtrlLineArcs> oLanesByRoads = ProcCtrl.combineLaneByRoad(oLanes, dTol);
        Collections.sort(oLanesByRoads, CtrlLineArcs.CMPBYLANE);
        ArrayList<CtrlLineArcs> oCombined = new ArrayList();
        ArrayList<CtrlLineArcs> oInRoadsToSignals = new ArrayList();
        int nIndex = oLanesByRoads.size();
        RoadPaths oRPSearch = new RoadPaths();
        ArrayList<Signal> oSignals = new ArrayList();
        while (nIndex-- > 0)
        {
            int nRoadId = XodrUtil.getRoadId(oLanesByRoads.get(nIndex).m_nLaneId);
            oRPSearch.m_nRoadId = nRoadId;
            int nSearchIndex;
            if (Arrays.binarySearch(m_nInterPaths, nRoadId) >= 0)
            {
                oLanesByRoads.remove(nIndex);
            }
            else if ((nSearchIndex = Collections.binarySearch(m_oIncomingRoads, oRPSearch)) >= 0)
            {
                oSignals.clear();
                RoadPaths oRoadPaths = m_oIncomingRoads.get(nSearchIndex);
                int nLaneIndex = XodrUtil.getLaneIndex(oLanesByRoads.get(nIndex).m_lLaneSectionId);
                for (Signal oSignal : m_oSignals)
                {
                    boolean bAdded = false;
                    Iterator<int[]> oIt = Arrays.iterator(oSignal.m_nRoads, new int[1], 1, 1);
                    while (oIt.hasNext())
                    {
                        int nConnPath = oIt.next()[0];
                        for (Connection oConn : oRoadPaths.m_oConns)
{
                            if (oConn.m_nConnRoad == nConnPath)
{
                                if (nLaneIndex == oConn.m_nFromLane)
{
                                    oSignals.add(oSignal);
                                    bAdded = true;
                                    break;
                                }
                            }
                        }
                        if (bAdded)
                            break;
                    }
                }
                boolean bHasSignal = false;
                boolean bPosLaneIndex = nLaneIndex > 0;
                for (Signal oSignal : oSignals)
                {
                    if (oSignal.m_nOri == Signal.BOTHORI)
                    {
                        bHasSignal = true;
                        break;
                    }
                    else if (oSignal.m_nOri == Signal.POSORI)
                    {
                        if (bPosLaneIndex)
{
                            bHasSignal = true;
                            break;
                        }
                    }
                    else if (oSignal.m_nOri == Signal.NEGORI)
                    {
                        if (!bPosLaneIndex)
{
                            bHasSignal = true;
                            break;
                        }
                    }
                }
                if (bHasSignal)
                    oInRoadsToSignals.add(oLanesByRoads.get(nIndex));
                oLanesByRoads.remove(nIndex);
            }
        }
        int nOuterLimit = oInRoadsToSignals.size();
        int nInnerLimit = oLanesByRoads.size();
        double dSqTol = dTol * dTol;
        for (int nOuter = 0; nOuter < nOuterLimit; nOuter++)
        {
            oSignals.clear();
            CtrlLineArcs oCur = oInRoadsToSignals.get(nOuter);
            double dLen = CtrlLineArcs.getLen(oCur.m_dLineArcs);
            boolean bAdded = false;
            if (dLen >= MINLEN)
            {
                oCombined.add(oCur);
                continue;
            }
            for (int nInner = 0; nInner < nInnerLimit; nInner++)
            {
                CtrlLineArcs oCmp = oLanesByRoads.get(nInner);
                int nConnect = oCur.connects(oCmp, dSqTol);
                if (nConnect == CtrlLineArcs.CON_TSTART_OEND) // the other linearc connects at the start of this linearc
                {
                    double dOtherLen = CtrlLineArcs.getLen(oCmp.m_dLineArcs);
                    if (dLen + dOtherLen < MINLEN)
                    {
                        oCur.combine(oCmp, nConnect); // combine the points of oCmp into oCur's point array
                        oLanesByRoads.remove(nInner);
                        --nInnerLimit;
                        nInner = -1; // start inner loop over
                    }
                    else
                    {
                        double[] dLineArc = oCmp.m_dLineArcs;
                        double[] dPartial = Arrays.newDoubleArray();
                        double[] dCenter = new double[2];
                        nIndex = Arrays.size(dLineArc) - 9;
                        dPartial = Arrays.add(dPartial, dLineArc[nIndex + 6], dLineArc[nIndex + 7]);
                        dPartial = Arrays.add(dPartial, dLineArc[nIndex + 8]);
                        for (;nIndex >= 5; nIndex -= 6)
{
                            if (dLen >= MINLEN)
{
                                nConnect = oCur.connects(dLineArc, dSqTol);
                                oCur.combine(dLineArc, nConnect);
                                oCombined.add(oCur);
                                bAdded = true;
                                break;
                            }
                            double dX3 = dLineArc[nIndex];
                            double dY3 = dLineArc[nIndex + 1];
                            double dX2 = dLineArc[nIndex + 3];
                            double dY2 = dLineArc[nIndex + 4];
                            double dX1 = dLineArc[nIndex + 6];
                            double dY1 = dLineArc[nIndex + 7];
                            dPartial = Arrays.add(dPartial, dX2, dY2);
                            dPartial = Arrays.add(dPartial, dLineArc[nIndex + 5]);
                            dPartial = Arrays.add(dPartial, dX3, dY3);
                            dPartial = Arrays.add(dPartial, dLineArc[nIndex + 2]);
                            double dR = Geo.circle(dX1, dY1, dX2, dY2, dX3, dY3, dCenter);
                            if (!Double.isFinite(dR) || dR >= 10000) // expand line
{
                                dLen += Geo.distance(dX1, dY1, dX3, dY3);
                            }
                            else
{
                                int nRightHand = Geo.rightHand(dX2, dY2, dX1, dY1, dX3, dY3);
                                double dC = -nRightHand / dR;
                                double dCmAngleStep = dC / 100;
                                double dCmAngleStepMag = Math.abs(dCmAngleStep);
                                double dH = dCenter[0];
                                double dK = dCenter[1];
                                double dHdg = Geo.heading(dH, dK, dX1, dY1);
                                int nSteps = 0;
                                double dPrevX = dX1;
                                double dPrevY = dY1;
                                double dPrevAngle = Geo.angle(dPrevX, dPrevY, dH, dK, dX3, dY3);
                                while (dPrevAngle > dCmAngleStepMag)
{
                                    dPrevX = dH + dR * Math.cos(dHdg + dCmAngleStep * ++nSteps);
                                    dPrevY = dK + dR * Math.sin(dHdg + dCmAngleStep * nSteps);
                                    dLen += 0.01;
                                    dPrevAngle = Geo.angle(dPrevX, dPrevY, dH, dK, dX3, dY3);
                                }
                                double dLastAngle = Geo.angle(dPrevX, dPrevY, dH, dK, dX3, dY3);
                                dLen += dLastAngle * dR;
                            }
                        }
                    }
                }
            }
            if (!bAdded)
                oCombined.add(oCur);
        }
        return oCombined;
    }
References cc.util.Arrays.add(), cc.util.Geo.angle(), cc.util.Arrays.binarySearch(), cc.geosrv.xodr.Signal.BOTHORI, cc.util.Geo.circle(), cc.ctrl.CtrlLineArcs.CMPBYLANE, cc.ctrl.CtrlLineArcs.combine(), cc.ctrl.proc.ProcCtrl.combineLaneByRoad(), cc.ctrl.CtrlLineArcs.CON_TSTART_OEND, cc.ctrl.CtrlLineArcs.connects(), cc.util.Geo.distance(), cc.geosrv.xodr.XodrUtil.getLaneIndex(), cc.ctrl.CtrlLineArcs.getLen(), cc.geosrv.xodr.XodrUtil.getRoadId(), cc.util.Geo.heading(), cc.util.Arrays.iterator(), cc.ctrl.CtrlLineArcs.m_dLineArcs, cc.geosrv.xodr.Connection.m_nConnRoad, cc.geosrv.xodr.Connection.m_nFromLane, cc.ctrl.proc.ProcSignal.m_nInterPaths, cc.ctrl.proc.RoadPaths.m_oConns, cc.ctrl.proc.ProcSignal.m_oIncomingRoads, cc.ctrl.proc.ProcSignal.m_oSignals, cc.ctrl.proc.ProcSignal.MINLEN, cc.geosrv.xodr.Signal.NEGORI, cc.util.Arrays.newDoubleArray(), cc.geosrv.xodr.Signal.POSORI, cc.util.Geo.rightHand(), and cc.util.Arrays.size().
Referenced by cc.ctrl.proc.ProcSignal.proc().
parseMetadata()
void cc.ctrl.proc.ProcSignal.parseMetadata (Path oSource) throws Exception inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 65 of file ProcSignal.java.
    {
        m_oJunctions.clear();
        m_oSignals.clear();
        m_nInterPaths[0] = 1;
        m_nSignalRoads[0] = 1;
        m_oIncomingRoads.clear();
        new XodrSignalParser(SIGNAL_TYPES).parseSignalData(oSource, m_oJunctions, m_oSignals);
        for (Signal oSignal : m_oSignals)
        {
            Iterator<int[]> oIt = Arrays.iterator(oSignal.m_nRoads, new int[1], 1, 1);
            while (oIt.hasNext())
            {
                int nRoad = oIt.next()[0];
                int nIndex = Arrays.binarySearch(m_nSignalRoads, nRoad);
                if (nIndex < 0)
                    m_nSignalRoads = Arrays.insert(m_nSignalRoads, nRoad, ~nIndex);
            }
        }
        RoadPaths oSearch = new RoadPaths();
        for (Junction oJunc : m_oJunctions)
        {
            for (Connection oConn : oJunc)
            {
                int nIndex = Arrays.binarySearch(m_nInterPaths, oConn.m_nConnRoad);
                if (nIndex < 0)
                    m_nInterPaths = Arrays.insert(m_nInterPaths, oConn.m_nConnRoad, ~nIndex);
                oSearch.m_nRoadId = oConn.m_nInRoad;
                nIndex = Collections.binarySearch(m_oIncomingRoads, oSearch);
                if (nIndex < 0)
                {
                    nIndex = ~nIndex;
                    m_oIncomingRoads.add(nIndex, new RoadPaths(oConn.m_nInRoad));
                }
                if (Arrays.binarySearch(m_nSignalRoads, oConn.m_nConnRoad) >= 0)
                {
                    RoadPaths oTemp = m_oIncomingRoads.get(nIndex);
                    oTemp.addConnection(oConn);
                }
            }
        }
    }
References cc.ctrl.proc.RoadPaths.addConnection(), cc.util.Arrays.binarySearch(), cc.util.Arrays.insert(), cc.util.Arrays.iterator(), cc.ctrl.proc.ProcSignal.m_nInterPaths, cc.ctrl.proc.ProcSignal.m_nSignalRoads, cc.ctrl.proc.ProcSignal.m_oIncomingRoads, cc.ctrl.proc.ProcSignal.m_oJunctions, cc.ctrl.proc.ProcSignal.m_oSignals, cc.geosrv.xodr.XodrSignalParser.parseSignalData(), and cc.ctrl.proc.ProcSignal.SIGNAL_TYPES.
Referenced by cc.ctrl.proc.ProcSignal.proc().
proc()
void cc.ctrl.proc.ProcSignal.proc (String sLineArcsFile, double dTol) inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 114 of file ProcSignal.java.
    {
        try
        {
            parseMetadata(Paths.get(m_sXodrDir + sLineArcsFile.substring(sLineArcsFile.lastIndexOf("/")).replace(".bin", ".xodr")));
            ArrayList<TrafCtrl> oCtrls = new ArrayList();
            ArrayList<CtrlLineArcs> oLineArcs = new ArrayList();
            try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(Paths.get(sLineArcsFile)))))
            {
                while (oIn.available() > 0)
                {
                    oLineArcs.add(new CtrlLineArcs(oIn));
                }
            }
            oLineArcs = combine(oLineArcs, dTol);
            ArrayList<int[]> oTiles = new ArrayList();
            SecureRandom oRng = new SecureRandom();
            byte[] yBytes = new byte[8];
            for (CtrlLineArcs oCLA : oLineArcs)
            {
                oRng.nextBytes(yBytes);
                TrafCtrl oCtrl = new TrafCtrl("signal", yBytes, 0, oCLA.m_dLineArcs, CC);
                oCtrls.add(oCtrl);
                oCtrl.write(g_sTrafCtrlDir, g_dExplodeStep, g_nDefaultZoom, CC);
                updateTiles(oTiles, oCtrl.m_oFullGeo.m_oTiles);
            }
            renderTiledData(oCtrls, oTiles);
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.ctrl.proc.ProcCtrl.CC, cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcCtrl.g_dExplodeStep, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTrafCtrlDir, cc.ctrl.TrafCtrl.m_oFullGeo, cc.ctrl.CtrlGeo.m_oTiles, cc.ctrl.proc.ProcSignal.m_sXodrDir, cc.util.FileUtil.newInputStream(), cc.ctrl.proc.ProcSignal.parseMetadata(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcCtrl.updateTiles(), and cc.ctrl.TrafCtrl.write().
renderTiledData()
static void cc.ctrl.proc.ProcSignal.renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException inline static
Definition at line 332 of file ProcSignal.java.
    {
        String[] sEmpty = new String[0];
        TdLayer oLights = new TdLayer("signal-lights", new String[]{"color"}, COLORS, TdLayer.POLYGON);
        TdLayer oBody = new TdLayer("signal-body", sEmpty, sEmpty, TdLayer.POLYGON);
        TdLayer oStopLine = new TdLayer("signal-sl", sEmpty, sEmpty, TdLayer.POLYGON);
        int[] nLightTags = new int[2];
        int[] nEmptyTags = new int[0];
        double[] dPt = new double[2];
        double[][] dPolys = new double[SIGNAL.length][];
        int[] nPts = new int[dPolys.length];
        for (int nIndex = 0; nIndex< dPolys.length; nIndex++)
        {
            double[] dTemp = new double[SIGNAL[nIndex].length + 1];
            dTemp[0] = dTemp.length;
            nPts[nIndex] =  SIGNAL[nIndex].length / 2;
            dPolys[nIndex] = dTemp;
        }
        ArrayList<double[]> dStopLines = new ArrayList();
        for (int[] nTile : nTiles)
        {
            int nX = nTile[0];
            int nY = nTile[1];
            Files.createDirectories(Paths.get(String.format(g_sTdFileFormat, nX, 0, 0, 0)).getParent(), FileUtil.DIRPERS);
            writeIndexFile(oCtrls, nX, nY);
            oLights.clear();
            oBody.clear();
            oStopLine.clear();
            dStopLines.clear();
            double[] dClipBounds = TileUtil.getClippingBounds(g_nDefaultZoom, nX, nY);
            for (TrafCtrl oCtrl : oCtrls)
            {
                CtrlGeo oFullGeo = oCtrl.m_oFullGeo;
                if (Collections.binarySearch(oFullGeo.m_oTiles, nTile, Mercator.TILECOMP) < 0 || oFullGeo.m_dAverageWidth < WIDTHTH)
                    continue;
                double[] dC = oFullGeo.m_dC;
                int nSize = Arrays.size(dC);
                int nIndex = getStopLine(oCtrl, dStopLines);
                double[] dStopLine = dStopLines.get(dStopLines.size() - 1);
                double[] dBoundingBox = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE};
                Iterator<double[]> oIt = Arrays.iterator(dStopLine, new double[2], 1, 2);
                while (oIt.hasNext())
                {
                    double[] dPoint = oIt.next();
                    if (dPoint[0] < dBoundingBox[0])
                        dBoundingBox[0] = dPoint[0];
                    if (dPoint[1] < dBoundingBox[1])
                        dBoundingBox[1] = dPoint[1];
                    if (dPoint[0] > dBoundingBox[2])
                        dBoundingBox[2] = dPoint[0];
                    if (dPoint[1] > dBoundingBox[3])
                        dBoundingBox[3] = dPoint[1];
                }
                if (Geo.boundingBoxesIntersect(dBoundingBox, dClipBounds))
                {
                    oStopLine.add(new TdFeature(dStopLine, nEmptyTags, oCtrl));
                }
                double dLen = 0.0;
                while (dLen < 0.5 && nIndex > 3)
                {
                    double dX1 = dC[nIndex];
                    double dY1 = dC[nIndex + 1];
                    double dX2 = dC[nIndex + 2];
                    double dY2 = dC[nIndex + 3];
                    dLen += Geo.distance(dX1, dY1, dX2, dY2);
                    nIndex -= 2;
                }
                double dX1 = dC[nIndex];
                double dY1 = dC[nIndex + 1];
                double dX2 = dC[nSize - 2];
                double dY2 = dC[nSize - 1];
                double dHdg = Geo.heading(dX1, dY1, dX2, dY2);
                if (Double.isNaN(dHdg))
                    continue;
                // offset from center line
                dPt[0] = dX1 + Math.sin(dHdg) * 0.5; // cos(x - pi/2) = sin(x)
                dPt[1] = dY1 - Math.cos(dHdg) * 0.5; // sin(x - pi/2) = -cos(x)
                double[] dBodyBoundingBox = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE};
                AffineTransform oAt = new AffineTransform();
                oAt.translate(dPt[0], dPt[1]);
                oAt.rotate(dHdg, 0, 0);
                oAt.transform(SIGNAL[0], 0, dPolys[0], 1, nPts[0]);
                oIt = Arrays.iterator(dPolys[0], new double[2], 1, 2);
                while (oIt.hasNext())
                {
                    double[] dPoint = oIt.next();
                    if (dPoint[0] < dBodyBoundingBox[0])
                        dBodyBoundingBox[0] = dPoint[0];
                    if (dPoint[1] < dBodyBoundingBox[1])
                        dBodyBoundingBox[1] = dPoint[1];
                    if (dPoint[0] > dBodyBoundingBox[2])
                        dBodyBoundingBox[2] = dPoint[0];
                    if (dPoint[1] > dBodyBoundingBox[3])
                        dBodyBoundingBox[3] = dPoint[1];
                }
                if (!Geo.boundingBoxesIntersect(dBodyBoundingBox[0], dBodyBoundingBox[1], dBodyBoundingBox[2], dBodyBoundingBox[3], dClipBounds[0], dClipBounds[1], dClipBounds[2], dClipBounds[3]))
                   continue;
                oBody.add(new TdFeature(dPolys[0], nEmptyTags, oCtrl));
                for (int i = 1; i < dPolys.length; i++)
                {
                    oAt.transform(SIGNAL[i], 0, dPolys[i], 1, nPts[i]);
                    nLightTags[1] = i - 1;
                    oLights.add(new TdFeature(dPolys[i], nLightTags, oCtrl));
                }
            }
            if (!oLights.isEmpty() || !oBody.isEmpty() || !oStopLine.isEmpty())
            {
                try (DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(String.format(g_sTdFileFormat, nX, g_nDefaultZoom, nX, nY)), FileUtil.APPENDTO, FileUtil.FILEPERS))))
                {
                    oLights.write(oOut);
                    oBody.write(oOut);
                    oStopLine.write(oOut);
                }
            }
        }
    }
References cc.util.FileUtil.APPENDTO, cc.util.Geo.boundingBoxesIntersect(), cc.ctrl.proc.ProcSignal.COLORS, cc.util.FileUtil.DIRPERS, cc.util.Geo.distance(), cc.util.FileUtil.FILEPERS, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTdFileFormat, cc.util.TileUtil.getClippingBounds(), cc.ctrl.proc.ProcCtrl.getStopLine(), cc.util.Geo.heading(), cc.util.Arrays.iterator(), cc.ctrl.CtrlGeo.m_dAverageWidth, cc.ctrl.CtrlGeo.m_dC, cc.ctrl.CtrlGeo.m_oTiles, cc.util.FileUtil.newOutputStream(), cc.ctrl.proc.TdLayer.POLYGON, cc.ctrl.proc.ProcSignal.SIGNAL, cc.util.Arrays.size(), cc.geosrv.Mercator.TILECOMP, cc.ctrl.proc.ProcCtrl.WIDTHTH, cc.ctrl.proc.TdLayer.write(), and cc.ctrl.proc.ProcCtrl.writeIndexFile().
Referenced by cc.ctrl.CreateCtrls.createCtrl(), cc.ctrl.RenderCtrl.main(), cc.ctrl.proc.ProcSignal.proc(), and cc.ctrl.proc.ProcCtrl.renderCtrls().
Member Data Documentation
COLORS
final String [] cc.ctrl.proc.ProcSignal.COLORS = new String[]{"g", "y", "r"} static private
Definition at line 47 of file ProcSignal.java.
Referenced by cc.ctrl.proc.ProcSignal.renderTiledData().
m_nInterPaths
int [] cc.ctrl.proc.ProcSignal.m_nInterPaths = Arrays.newIntArray() private
Definition at line 50 of file ProcSignal.java.
Referenced by cc.ctrl.proc.ProcSignal.combine(), and cc.ctrl.proc.ProcSignal.parseMetadata().
m_nSignalRoads
int [] cc.ctrl.proc.ProcSignal.m_nSignalRoads = Arrays.newIntArray() private
Definition at line 51 of file ProcSignal.java.
Referenced by cc.ctrl.proc.ProcSignal.parseMetadata().
m_oIncomingRoads
ArrayList<RoadPaths> cc.ctrl.proc.ProcSignal.m_oIncomingRoads = new ArrayList() private
Definition at line 52 of file ProcSignal.java.
Referenced by cc.ctrl.proc.ProcSignal.combine(), and cc.ctrl.proc.ProcSignal.parseMetadata().
m_oJunctions
ArrayList<Junction> cc.ctrl.proc.ProcSignal.m_oJunctions = new ArrayList() private
Definition at line 48 of file ProcSignal.java.
Referenced by cc.ctrl.proc.ProcSignal.parseMetadata().
m_oSignals
ArrayList<Signal> cc.ctrl.proc.ProcSignal.m_oSignals = new ArrayList() private
Definition at line 49 of file ProcSignal.java.
Referenced by cc.ctrl.proc.ProcSignal.combine(), and cc.ctrl.proc.ProcSignal.parseMetadata().
m_sXodrDir
String cc.ctrl.proc.ProcSignal.m_sXodrDir private
Definition at line 53 of file ProcSignal.java.
Referenced by cc.ctrl.proc.ProcSignal.ProcSignal(), and cc.ctrl.proc.ProcSignal.proc().
MINLEN
double cc.ctrl.proc.ProcSignal.MINLEN = 53.0 static private
Definition at line 54 of file ProcSignal.java.
Referenced by cc.ctrl.proc.ProcSignal.combine().
SIGNAL
final double [][] cc.ctrl.proc.ProcSignal.SIGNAL static private
Initial value:
= new double[][]{
                                           new double[]{-0.45, 0.15, 0.45, 0.15, 0.45, -0.15, -0.45, -0.15},
                                           new double[]{-0.33, 0.11, -0.27, 0.11, -0.23, 0.09, -0.21, 0.07, -0.19, 0.03, -0.19, -0.03, -0.21, -0.07, -0.23, -0.09, -0.27, -0.11, -0.33, -0.11, -0.37, -0.09, -0.39, -0.07, -0.41, -0.03, -0.41, 0.03, -0.39, 0.07, -0.37, 0.09},
                                           new double[]{-0.03, 0.11, 0.03, 0.11, 0.07, 0.09, 0.09, 0.07, 0.11, 0.03, 0.11, -0.03, 0.09, -0.07, 0.07, -0.09, 0.03, -0.11, -0.03, -0.11, -0.07, -0.09, -0.09, -0.07, -0.11, -0.03, -0.11, 0.03, -0.09, 0.07, -0.07, 0.09},
                                           new double[]{0.27, 0.11, 0.33, 0.11, 0.37, 0.09, 0.39, 0.07, 0.41, 0.03, 0.41, -0.03, 0.39, -0.07, 0.37, -0.09, 0.33, -0.11, 0.27, -0.11, 0.23, -0.09, 0.21, -0.07, 0.19, -0.03, 0.19, 0.03, 0.21, 0.07, 0.23, 0.09}
                                           }
Definition at line 41 of file ProcSignal.java.
Referenced by cc.ctrl.proc.ProcSignal.renderTiledData().
SIGNAL_TYPES
String [] cc.ctrl.proc.ProcSignal.SIGNAL_TYPES = new String[]{"1000001", "1000009", "1000010", "1000011"} static private
Definition at line 55 of file ProcSignal.java.
Referenced by cc.ctrl.proc.ProcSignal.parseMetadata().
The documentation for this class was generated from the following file:
src/cc/ctrl/proc/ProcSignal.java