Carma-cloud: cc.util.Units Class Reference
cc.util.Units Class Reference
Classes
class UnitConv
class UnitConvR
Public Member Functions
void init (String sFilename)
double convert (String sFromUnit, String sToUnit, double dVal)
UnitConv getConversion (String sFromUnit, String sToUnit)
Static Public Member Functions
static Units getInstance ()
Private Member Functions
Units ()
Static Private Attributes
static Units g_oInstance = new Units()
Detailed Description
Definition at line 8 of file Units.java.
Constructor & Destructor Documentation
Units()
cc.util.Units.Units () inline private
Default Constructor connects units file contained in the config file to query the units contained there. It then iterates through the units stored in the file, adding both forward and reverse conversions to (m_oUnits) the list of units contained in the Units class.
Definition at line 48 of file Units.java.
    {
    }
Member Function Documentation
convert()
double cc.util.Units.convert (String sFromUnit, String sToUnit, double dVal) inline
Attempts to convert the given value from one unit to another.
Parameters
sFromUnit The unit to convert from
sToUnit The unit to convert to
dVal the value to convert
Returns
The converted value if conversion was possible. If conversion isn't possible (due to either of the unit Strings being null, the unit Strings being equal to each other, or not having a conversion defined for the given units) the original value is returned.
Definition at line 74 of file Units.java.
    {
        if (sFromUnit == null || sToUnit == null || sFromUnit.compareTo(sToUnit) == 0)
            return dVal;
        UnitConv oUnitConv = getConversion(sFromUnit, sToUnit);
        if (oUnitConv == null)
            return dVal;
        return oUnitConv.convert(dVal);
    }
References cc.util.Units.UnitConv.convert(), and cc.util.Units.getConversion().
Referenced by cc.ws.CtrlTiles.addControl(), cc.ws.GeoLanes.doPost(), cc.ws.WxPoly.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ihp.IHP.readDetectors(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), and cc.ws.CtrlTiles.saveEdit().
getConversion()
UnitConv cc.util.Units.getConversion (String sFromUnit, String sToUnit) inline
This method searches the list of conversion for the conversion between the supplied units.
Parameters
sFromUnit The unit to convert from.
sToUnit The unit to convert to.
Returns
Null when either of the supplied units are null, if the supplied units are the same, or if the conversion is not stored in the conversion list. Else it returns the queried conversion.
Definition at line 96 of file Units.java.
    {
        for (UnitConv oUnitConv : this)
        {
            if (oUnitConv.m_sFromUnit.compareTo(sFromUnit) == 0)
            {
                if (oUnitConv.m_sToUnit.compareTo(sToUnit) == 0)
                    return oUnitConv;
            }
        }
        return null;
    }
References cc.util.Units.UnitConv.m_sFromUnit, and cc.util.Units.UnitConv.m_sToUnit.
Referenced by cc.util.Units.convert().
getInstance()
static Units cc.util.Units.getInstance () inline static
Retrieves the singleton instance of Units.
Returns
The instance of Units.
Definition at line 58 of file Units.java.
    {
        return g_oInstance;
    }
References cc.util.Units.g_oInstance.
Referenced by cc.ws.CtrlTiles.addControl(), cc.ws.GeoLanes.doPost(), cc.ws.WxPoly.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ws.CtrlTiles.init(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ihp.IHP.readDetectors(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), and cc.ws.CtrlTiles.saveEdit().
init()
void cc.util.Units.init (String sFilename) inline
Definition at line 16 of file Units.java.
    {
        try (CsvReader oIn = new CsvReader(new FileInputStream(sFilename)))
        {
            while (oIn.readLine() > 0)
            {
                UnitConv oUnitConv = new UnitConv(oIn);
                int nIndex = Collections.binarySearch(this, oUnitConv);
                if (nIndex < 0)
                    add(~nIndex, oUnitConv);
                oUnitConv = new UnitConvR(oIn);
                nIndex = Collections.binarySearch(this, oUnitConv);
                if (nIndex < 0)
                    add(~nIndex, oUnitConv);
            }
        }
        catch (Exception oException)
        {
            oException.printStackTrace();
        }
    }
Referenced by cc.ws.CtrlTiles.init().
Member Data Documentation
g_oInstance
Units cc.util.Units.g_oInstance = new Units() static private
The singleton instance of Units.
Definition at line 14 of file Units.java.
Referenced by cc.util.Units.getInstance().
The documentation for this class was generated from the following file:
src/cc/util/Units.java