Carma-cloud: cc.rsu.BoundingBoxUtils Class Reference
cc.rsu.BoundingBoxUtils Class Reference
Static Public Member Functions
static double[] calculateBoundingBoxCoordinates (Position centerLoc, double radius)
static double calculate_earth_radius (double latRad)
Detailed Description
Definition at line 6 of file BoundingBoxUtils.java.
Member Function Documentation
calculate_earth_radius()
static double cc.rsu.BoundingBoxUtils.calculate_earth_radius (double latRad) inline static
Definition at line 41 of file BoundingBoxUtils.java.
{
        double wgsa = 6378137.0; // meter
        double wgsb = 6356752.314; // meter
        double f1 = Math.pow((Math.pow(wgsa, 2) * Math.cos(latRad)), 2);
        double f2 = Math.pow((Math.pow(wgsb, 2) * Math.sin(latRad)), 2);
        double f3 = Math.pow((wgsa * Math.cos(latRad)), 2);
        double f4 = Math.pow((wgsb * Math.sin(latRad)), 2);
        double earth_radius = Math.sqrt((f1 + f2) / (f3 + f4));
        return earth_radius;
    }
Referenced by cc.rsu.BoundingBoxUtils.calculateBoundingBoxCoordinates().
calculateBoundingBoxCoordinates()
static double[] cc.rsu.BoundingBoxUtils.calculateBoundingBoxCoordinates (Position centerLoc, double radius) inline static
Definition at line 16 of file BoundingBoxUtils.java.
{
        double DEGREES_TO_RADIANS = Math.PI / 180.0;
        double RADIANS_TO_DEGREES = 180.0 / Math.PI;
        double[] result = new double[4];
        double latRad = Math.toRadians(centerLoc.getLatitude());
        double lonRad = Math.toRadians(centerLoc.getlongitude());
        double earth_radius = calculate_earth_radius(latRad);
        double p_radius = earth_radius * Math.cos(latRad);
        double latRad_min = latRad - radius / earth_radius;
        double latRad_max = latRad + radius / earth_radius;
        double lonRad_min = lonRad - radius / p_radius;
        double lonRad_max = lonRad + radius / p_radius;
        result[0] = RADIANS_TO_DEGREES * latRad_min;
        result[1] = RADIANS_TO_DEGREES * lonRad_min;
        result[2] = RADIANS_TO_DEGREES * latRad_max;
        result[3] = RADIANS_TO_DEGREES * lonRad_max;
        return result;
    }
References cc.rsu.BoundingBoxUtils.calculate_earth_radius(), cc.rsu.Position.getLatitude(), and cc.rsu.Position.getlongitude().
Referenced by cc.rsu.RSUBoundingbox.RSUBoundingbox().
The documentation for this class was generated from the following file:
src/cc/rsu/BoundingBoxUtils.java