Carma-cloud: cc.geosrv.xodr.rdmk.Lane Class Reference
cc.geosrv.xodr.rdmk.Lane Class Reference
Public Member Functions
Lane ()
Lane (int nId, String sType, int nRoadId, int nSectionId)
Public Attributes
int m_nLaneIndex
ArrayList< double[]> m_dCenters = new ArrayList()
int m_nRoadId
int m_nSectionId
int m_nLaneIdByRoad
ArrayList< RoadMark > m_oOuterRoadMarks = new ArrayList()
ArrayList< RoadMark > m_oInnerRoadMarks
double m_dLastOuterRdMkS = Double.MAX_VALUE
double m_dLastInnerRdMkS = Double.MAX_VALUE
int[] m_nRdMkTags = Arrays.newIntArray()
int m_nRdMkCnt = 0
int m_nType
Static Private Attributes
static String[] TYPES
Detailed Description
Author
aaron.cherney
Definition at line 16 of file Lane.java.
Constructor & Destructor Documentation
Lane() [1/2]
cc.geosrv.xodr.rdmk.Lane.Lane () inline
Definition at line 59 of file Lane.java.
    {
        super();
    }
Lane() [2/2]
cc.geosrv.xodr.rdmk.Lane.Lane (int nId, String sType, int nRoadId, int nSectionId) inline
Definition at line 65 of file Lane.java.
    {
        this();
        m_nType = XodrUtil.getLaneType(sType);
        m_nLaneIndex = nId;
        m_nRoadId = nRoadId;
        m_nSectionId = nSectionId;
    }
References cc.geosrv.xodr.XodrUtil.getLaneType(), cc.geosrv.xodr.rdmk.Lane.m_nLaneIndex, cc.geosrv.xodr.rdmk.Lane.m_nRoadId, cc.geosrv.xodr.rdmk.Lane.m_nSectionId, and cc.geosrv.xodr.rdmk.Lane.m_nType.
Member Data Documentation
m_dCenters
ArrayList<double[]> cc.geosrv.xodr.rdmk.Lane.m_dCenters = new ArrayList()
Definition at line 47 of file Lane.java.
Referenced by cc.geosrv.xodr.rdmk.Geometry.addLanePoints().
m_dLastInnerRdMkS
double cc.geosrv.xodr.rdmk.Lane.m_dLastInnerRdMkS = Double.MAX_VALUE
Definition at line 54 of file Lane.java.
Referenced by cc.geosrv.xodr.rdmk.Geometry.addLanePoints().
m_dLastOuterRdMkS
double cc.geosrv.xodr.rdmk.Lane.m_dLastOuterRdMkS = Double.MAX_VALUE
Definition at line 53 of file Lane.java.
Referenced by cc.geosrv.xodr.rdmk.Geometry.addLanePoints().
m_nLaneIdByRoad
int cc.geosrv.xodr.rdmk.Lane.m_nLaneIdByRoad
Definition at line 50 of file Lane.java.
m_nLaneIndex
int cc.geosrv.xodr.rdmk.Lane.m_nLaneIndex
Definition at line 46 of file Lane.java.
Referenced by cc.geosrv.xodr.rdmk.Lane.Lane(), cc.geosrv.xodr.rdmk.LaneSection.add(), cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement().
m_nRdMkCnt
int cc.geosrv.xodr.rdmk.Lane.m_nRdMkCnt = 0
Definition at line 56 of file Lane.java.
m_nRdMkTags
int [] cc.geosrv.xodr.rdmk.Lane.m_nRdMkTags = Arrays.newIntArray()
Definition at line 55 of file Lane.java.
Referenced by cc.geosrv.xodr.rdmk.Geometry.addLanePoints().
m_nRoadId
int cc.geosrv.xodr.rdmk.Lane.m_nRoadId
Definition at line 48 of file Lane.java.
Referenced by cc.geosrv.xodr.rdmk.Lane.Lane().
m_nSectionId
int cc.geosrv.xodr.rdmk.Lane.m_nSectionId
Definition at line 49 of file Lane.java.
Referenced by cc.geosrv.xodr.rdmk.Lane.Lane().
m_nType
int cc.geosrv.xodr.rdmk.Lane.m_nType
Definition at line 57 of file Lane.java.
Referenced by cc.geosrv.xodr.rdmk.Lane.Lane(), and cc.geosrv.xodr.rdmk.Geometry.addLanePoints().
m_oInnerRoadMarks
ArrayList<RoadMark> cc.geosrv.xodr.rdmk.Lane.m_oInnerRoadMarks
Definition at line 52 of file Lane.java.
Referenced by cc.geosrv.xodr.rdmk.Geometry.addLanePoints().
m_oOuterRoadMarks
ArrayList<RoadMark> cc.geosrv.xodr.rdmk.Lane.m_oOuterRoadMarks = new ArrayList()
Definition at line 51 of file Lane.java.
Referenced by cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.geosrv.xodr.rdmk.LaneSection.setInnerRoadMarks(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
TYPES
String [] cc.geosrv.xodr.rdmk.Lane.TYPES static private
Initial value:
= new String[]
    {
        "none",
        "driving",
        "stop",
        "shoulder",
        "biking",
        "sidewalk",
        "border",
        "restricted",
        "parking",
        "bidirectional",
        "median",
        "special1",
        "special2",
        "special3",
        "roadWorks",
        "tram",
        "rail",
        "entry",
        "exit",
        "offRamp",
        "onRamp",
        "connectingRamp",
        "bus",
        "taxi",
        "HOV"
    }
Definition at line 18 of file Lane.java.
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/rdmk/Lane.java