Carma-cloud: cc.rsm.RsmCollect Class Reference
cc.rsm.RsmCollect Class Reference
Classes
class RsmRecord
Public Member Functions
RsmCollect (String sUser, String sPw, String sBaseUrl, String sOutputFile, HashMap< String, double[]> oLonLatAdjustments)
void run ()
void writeCurrent () throws IOException
void readCurrent () throws IOException
boolean getToken ()
boolean xmlList (boolean bLog)
boolean xmlFile (RsmRecord oRec)
Static Protected Attributes
static final Logger LOGGER = LogManager.getRootLogger()
Private Attributes
String m_sToken = ""
String m_sUser
String m_sPw
String m_sBaseUrl = "https://wzdc-rest-api.azurewebsites.net"
String m_sOutputFile
final String REQTOKEN = "/auth/token/"
final String RSMXML = "/rsm-xml"
final ArrayList< RsmRecord > m_oCurrentRsms = new ArrayList()
final int ENDTAG = 1
final int VALUES = 2
final AtomicBoolean m_bRunning = new AtomicBoolean()
HashMap< String, double[]> m_oLonLatAdjustments
Detailed Description
Author
aaron.cherney
Definition at line 43 of file RsmCollect.java.
Constructor & Destructor Documentation
RsmCollect()
cc.rsm.RsmCollect.RsmCollect (String sUser, String sPw, String sBaseUrl, String sOutputFile, HashMap< String, double[]> oLonLatAdjustments) inline
Definition at line 61 of file RsmCollect.java.
    {
        m_sUser = sUser;
        m_sPw = sPw;
        m_sBaseUrl = sBaseUrl;
        m_sOutputFile = sOutputFile;
        m_oLonLatAdjustments = oLonLatAdjustments;
        m_bRunning.set(false);
    }
References cc.rsm.RsmCollect.m_bRunning, cc.rsm.RsmCollect.m_oLonLatAdjustments, cc.rsm.RsmCollect.m_sBaseUrl, cc.rsm.RsmCollect.m_sOutputFile, cc.rsm.RsmCollect.m_sPw, and cc.rsm.RsmCollect.m_sUser.
Member Function Documentation
getToken()
boolean cc.rsm.RsmCollect.getToken () inline
Definition at line 170 of file RsmCollect.java.
    {
        try
        {
            URL oUrl = new URL(m_sBaseUrl + REQTOKEN);
            HttpURLConnection oConn = (HttpURLConnection)oUrl.openConnection();
            oConn.setRequestMethod("POST");
            oConn.setDoOutput(true);
            oConn.addRequestProperty("accept", "application/json");
            oConn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
            StringBuilder sReq = new StringBuilder();
            sReq.append("grant_type=&");
            sReq.append("username=").append(URLEncoder.encode(m_sUser, "UTF-8")).append('&');
            sReq.append("password=").append(URLEncoder.encode(m_sPw, "UTF-8")).append('&');
            sReq.append("scope=&client_secret=");
            byte[] yOut = sReq.toString().getBytes(StandardCharsets.UTF_8);
            oConn.setFixedLengthStreamingMode(yOut.length);
            oConn.connect();
            try (OutputStream oOut = oConn.getOutputStream())
            {
                oOut.write(yOut);
            }
            StringBuilder sBuf = new StringBuilder();
            try (BufferedInputStream oIn = new BufferedInputStream(oConn.getInputStream()))
            {
                int nByte;
                while ((nByte = oIn.read()) >= 0)
                    sBuf.append((char)nByte);
            }
            int nStart = sBuf.indexOf("\"access_token\":\"") + "\"access_token\":\"".length();
            m_sToken = sBuf.substring(nStart, sBuf.indexOf("\"", nStart));
            return true;
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
            return false;
        }
    }
References cc.rsm.RsmCollect.m_sBaseUrl, cc.rsm.RsmCollect.m_sPw, cc.rsm.RsmCollect.m_sToken, cc.rsm.RsmCollect.m_sUser, and cc.rsm.RsmCollect.REQTOKEN.
Referenced by cc.rsm.RsmCollect.run().
readCurrent()
void cc.rsm.RsmCollect.readCurrent () throws IOException inline
Definition at line 136 of file RsmCollect.java.
    {
        Path oPath = Paths.get(m_sOutputFile);
        if (!Files.exists(oPath))
            return;
        try (CsvReader oIn = new CsvReader(Files.newInputStream(oPath)))
        {
            while (oIn.readLine() > 0)
            {
                m_oCurrentRsms.add(new RsmRecord(oIn.parseString(0), oIn.parseString(1)));
            }
        }
        Collections.sort(m_oCurrentRsms);
    }
References cc.rsm.RsmCollect.m_oCurrentRsms, and cc.rsm.RsmCollect.m_sOutputFile.
Referenced by cc.ws.RsmServlet.init().
run()
void cc.rsm.RsmCollect.run () inline
Definition at line 73 of file RsmCollect.java.
    {
        if (!m_bRunning.compareAndSet(false, true))
        {
            LOGGER.debug("Collecting rsm did not run. Already running");
            return;
        }
        if (!getToken())
        {
            m_bRunning.set(false);
            return;
        }
        int nAdded = 0;
        int nRemoved = 0;
        if (xmlList(true))
        {
            int nIndex = m_oCurrentRsms.size();
            while (nIndex-- > 0)
            {
                RsmRecord oRec = m_oCurrentRsms.get(nIndex);
                if (oRec.m_bNew)
                {
                    xmlFile(oRec);
                    ++nAdded;
                }
                else if (!oRec.m_bCurrent)
                {
                    m_oCurrentRsms.remove(nIndex);
                    oRec.cleanup();
                    ++nRemoved;
                }
            }
        }
        m_bRunning.set(false);
        StringBuilder sMsg = new StringBuilder("RSM ");
        sMsg.append(nAdded);
        sMsg.append(" added ");
        sMsg.append(nRemoved);
        sMsg.append(" removed ");
        sMsg.append(m_oCurrentRsms.size());
        sMsg.append(" total");
        LOGGER.debug(sMsg);
    }
References cc.rsm.RsmCollect.RsmRecord.cleanup(), cc.rsm.RsmCollect.getToken(), cc.rsm.RsmCollect.LOGGER, cc.rsm.RsmCollect.RsmRecord.m_bCurrent, cc.rsm.RsmCollect.RsmRecord.m_bNew, cc.rsm.RsmCollect.m_bRunning, cc.rsm.RsmCollect.m_oCurrentRsms, cc.rsm.RsmCollect.xmlFile(), and cc.rsm.RsmCollect.xmlList().
Referenced by cc.ws.RsmServlet.init().
writeCurrent()
void cc.rsm.RsmCollect.writeCurrent () throws IOException inline
Definition at line 121 of file RsmCollect.java.
    {
        try (BufferedWriter oOut = new BufferedWriter(Channels.newWriter(Files.newByteChannel(Paths.get(m_sOutputFile), FileUtil.WRITE), "UTF-8")))
        {
            int nLimit = m_oCurrentRsms.size();
            for (int nIndex = 0; nIndex < nLimit; nIndex++)
            {
                RsmRecord oRec = m_oCurrentRsms.get(nIndex);
                oOut.append(oRec.m_sId).append(',').append(oRec.m_sFile).append('\n');
            }
        }
    }
References cc.rsm.RsmCollect.m_oCurrentRsms, cc.rsm.RsmCollect.RsmRecord.m_sFile, cc.rsm.RsmCollect.RsmRecord.m_sId, cc.rsm.RsmCollect.m_sOutputFile, and cc.util.FileUtil.WRITE.
Referenced by cc.ws.RsmServlet.destroy().
xmlFile()
boolean cc.rsm.RsmCollect.xmlFile (RsmRecord oRec) inline
Definition at line 257 of file RsmCollect.java.
    {
        try
        {
            URL oUrl = new URL(m_sBaseUrl + RSMXML + "/" + oRec.m_sFile);
            HttpURLConnection oConn = (HttpURLConnection)oUrl.openConnection();
            oConn.setRequestMethod("GET");
            oConn.addRequestProperty("accept", "application/json");
            oConn.setRequestProperty("Authorization", "Bearer " + m_sToken);
            StringBuilder sBuf = new StringBuilder();
            try (BufferedInputStream oIn = new BufferedInputStream(oConn.getInputStream()))
            {
                int nByte;
                while ((nByte = oIn.read()) >= 0)
                    sBuf.append((char)nByte);
            }
            int nStart = 0;
            while (nStart >= 0)
            {
                nStart = sBuf.indexOf("\"source_name\":\"", nStart);
                if (nStart < 0)
                    break;
                nStart += "\"source_name\":\"".length();
                int nEnd = sBuf.indexOf("\"", nStart);
                int nSlash = sBuf.lastIndexOf("/", nEnd);
                if (nSlash > nStart)
                    nStart = nSlash + 1;
                String sFilename = sBuf.substring(nStart, nEnd);
                nStart = sBuf.indexOf("\"data\":\"", nStart) + "\"data\":\"".length();
                nEnd = sBuf.indexOf("</RoadsideSafetyMessage>", nStart) + "</RoadsideSafetyMessage>".length();
                int nState = ENDTAG;
                StringBuilder sXml = new StringBuilder();
                for (int nIndex = nStart; nIndex < nEnd; nIndex++)
                {
                    char cChar = sBuf.charAt(nIndex);
                    switch (cChar)
                    {
                        case '>':
{
                            nState = ENDTAG;
                            sXml.append(cChar);
                            break;
                        }
                        case '\\':
{
                            char cNext = sBuf.charAt(++nIndex);
                            switch (cNext)
{
                                case 'n':
{
                                    if (nState != ENDTAG)
                                        sXml.append('\\').append('n');
                                    break;
                                }
                                case 't':
{
                                    if (nState != ENDTAG)
                                        sXml.append('\\').append('t');
                                    break;
                                }
                                default:
{
                                    sXml.append(cNext);
                                    break;
                                }
                            }
                            break;
                        }
                        case ' ':
{
                            if (nState == ENDTAG)
                                break;
                        }
                        default:
{
                            sXml.append(cChar);
                            nState = VALUES;
                            break;
                        }
                    }
                }
//              try (BufferedWriter oOut = Files.newBufferedWriter(Paths.get(m_sOutputDir + "/" + sFilename), StandardCharsets.UTF_8))
//              {
//                  oOut.append(sXml);
//              }
                double[] dAdjusts = m_oLonLatAdjustments.get("default");
                int[] nAdjusts = new int[] {Geo.toIntDeg(dAdjusts[0]), Geo.toIntDeg(dAdjusts[1])};
                for (Map.Entry<String, double[]> oEntry : m_oLonLatAdjustments.entrySet())
                {
                    if (sFilename.startsWith(oEntry.getKey()))
                    {
                        dAdjusts = oEntry.getValue();
                        nAdjusts = new int[]{Geo.toIntDeg(dAdjusts[0]), Geo.toIntDeg(dAdjusts[1])};
                        break;
                    }
                }
                ArrayList<TrafCtrl> oCtrls = new RsmParser(nAdjusts).parseRequest(new ByteArrayInputStream(sXml.toString().getBytes(StandardCharsets.UTF_8)));
                for (TrafCtrl oCtrl : oCtrls)
                    oRec.m_yIds.add(oCtrl.m_yId);
                Text.removeCtrlChars(sXml);
                sXml.insert(0, ' ');
                sXml.insert(0, sFilename);
                LOGGER.debug(sXml);
            }
            return true;
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
            return false;
        }
    }
References cc.rsm.RsmCollect.ENDTAG, cc.rsm.RsmCollect.LOGGER, cc.rsm.RsmCollect.m_oLonLatAdjustments, cc.rsm.RsmCollect.m_sBaseUrl, cc.rsm.RsmCollect.RsmRecord.m_sFile, cc.rsm.RsmCollect.m_sToken, cc.rsm.RsmCollect.RsmRecord.m_yIds, cc.rsm.RsmParser.parseRequest(), cc.util.Text.removeCtrlChars(), cc.rsm.RsmCollect.RSMXML, cc.util.Geo.toIntDeg(), and cc.rsm.RsmCollect.VALUES.
Referenced by cc.rsm.RsmCollect.run().
xmlList()
boolean cc.rsm.RsmCollect.xmlList (boolean bLog) inline
Definition at line 212 of file RsmCollect.java.
    {
        try
        {
            URL oUrl = new URL(m_sBaseUrl + RSMXML);
            HttpURLConnection oConn = (HttpURLConnection)oUrl.openConnection();
            oConn.setRequestMethod("GET");
            oConn.addRequestProperty("accept", "application/json");
            oConn.setRequestProperty("Authorization", "Bearer " + m_sToken);
            StringBuilder sBuf = new StringBuilder();
            m_oCurrentRsms.forEach(oRec -> {oRec.m_bCurrent = false; oRec.m_bNew = false;});
            try (BufferedInputStream oIn = new BufferedInputStream(oConn.getInputStream()))
            {
                int nByte;
                while ((nByte = oIn.read()) >= 0)
                    sBuf.append((char)nByte);
            }
            int nStart = sBuf.indexOf("\"data\":[");
            while (nStart >= 0)
            {
                nStart = sBuf.indexOf("\"name\":\"", nStart);
                if (nStart < 0)
                    break;
                nStart += "\"name\":\"".length();
                String sName = sBuf.substring(nStart, sBuf.indexOf("\"", nStart));
                nStart = sBuf.indexOf("\"id\":\"", nStart) + "\"id\":\"".length();
                RsmRecord oRec = new RsmRecord(sBuf.substring(nStart, sBuf.indexOf("\"", nStart)), sName);
                int nIndex = Collections.binarySearch(m_oCurrentRsms, oRec);
                if (nIndex < 0)
                    m_oCurrentRsms.add(~nIndex, oRec);
                else
                    m_oCurrentRsms.get(nIndex).m_bCurrent = true;
            }
            return true;
        }
        catch (Exception oEx)
        {
            if (bLog)
                oEx.printStackTrace();
            return false;
        }
    }
References cc.rsm.RsmCollect.m_oCurrentRsms, cc.rsm.RsmCollect.m_sBaseUrl, cc.rsm.RsmCollect.m_sToken, and cc.rsm.RsmCollect.RSMXML.
Referenced by cc.rsm.RsmCollect.run().
Member Data Documentation
ENDTAG
final int cc.rsm.RsmCollect.ENDTAG = 1 private
Definition at line 55 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.xmlFile().
LOGGER
final Logger cc.rsm.RsmCollect.LOGGER = LogManager.getRootLogger() static protected
Definition at line 45 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.RsmRecord.cleanup(), cc.rsm.RsmCollect.run(), and cc.rsm.RsmCollect.xmlFile().
m_bRunning
final AtomicBoolean cc.rsm.RsmCollect.m_bRunning = new AtomicBoolean() private
Definition at line 57 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.RsmCollect(), and cc.rsm.RsmCollect.run().
m_oCurrentRsms
final ArrayList<RsmRecord> cc.rsm.RsmCollect.m_oCurrentRsms = new ArrayList() private
Definition at line 54 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.readCurrent(), cc.rsm.RsmCollect.run(), cc.rsm.RsmCollect.writeCurrent(), and cc.rsm.RsmCollect.xmlList().
m_oLonLatAdjustments
HashMap<String, double[]> cc.rsm.RsmCollect.m_oLonLatAdjustments private
Definition at line 58 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.RsmCollect(), and cc.rsm.RsmCollect.xmlFile().
m_sBaseUrl
String cc.rsm.RsmCollect.m_sBaseUrl = "https://wzdc-rest-api.azurewebsites.net" private
Definition at line 50 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.RsmCollect(), cc.rsm.RsmCollect.getToken(), cc.rsm.RsmCollect.xmlFile(), and cc.rsm.RsmCollect.xmlList().
m_sOutputFile
String cc.rsm.RsmCollect.m_sOutputFile private
Definition at line 51 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.RsmCollect(), cc.rsm.RsmCollect.readCurrent(), and cc.rsm.RsmCollect.writeCurrent().
m_sPw
String cc.rsm.RsmCollect.m_sPw private
Definition at line 49 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.RsmCollect(), and cc.rsm.RsmCollect.getToken().
m_sToken
String cc.rsm.RsmCollect.m_sToken = "" private
Definition at line 47 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.getToken(), cc.rsm.RsmCollect.xmlFile(), and cc.rsm.RsmCollect.xmlList().
m_sUser
String cc.rsm.RsmCollect.m_sUser private
Definition at line 48 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.RsmCollect(), and cc.rsm.RsmCollect.getToken().
REQTOKEN
final String cc.rsm.RsmCollect.REQTOKEN = "/auth/token/" private
Definition at line 52 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.getToken().
RSMXML
final String cc.rsm.RsmCollect.RSMXML = "/rsm-xml" private
Definition at line 53 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.xmlFile(), and cc.rsm.RsmCollect.xmlList().
VALUES
final int cc.rsm.RsmCollect.VALUES = 2 private
Definition at line 56 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.xmlFile().
The documentation for this class was generated from the following file:
src/cc/rsm/RsmCollect.java