Carma-cloud: cc.util.Geo Class Reference
cc.util.Geo Class Reference abstract
Static Public Member Functions
static double[] reverseOrder (double[] dPoly)
static int scale (int nVal)
static int getHash (int nLat, int nLon)
static double fromIntDeg (int nOrd)
static int toIntDeg (double dOrd)
static double toMeters (int nOrd)
static double distance (int nXi, int nYi, int nXj, int nYj)
static double distance (double dXi, double dYi, double dXj, double dYj)
static double sqDist (double dXi, double dYi, double dXj, double dYj)
static boolean boundingBoxesIntersect (double[] dBb1, double[] dBb2)
static boolean boundingBoxesIntersect (double dXmin1, double dYmin1, double dXmax1, double dYmax1, double dXmin2, double dYmin2, double dXmax2, double dYmax2)
static boolean isInside (int nX, int nY, int nT, int nR, int nB, int nL, int nTol)
static boolean isInside (double dX, double dY, double dT, double dR, double dB, double dL, double dTol)
static boolean isInBoundingBox (double dX, double dY, double dX1, double dY1, double dX2, double dY2)
static boolean polylineInside (int[] nPolygon, int[] nPolyline)
static boolean isInsidePolygon (int[] nPolyPoints, double nX, double nY)
static boolean polylineInside (double[] dPolygon, double[] dPolyline)
static boolean isInsidePolygon (double[] dPolyPoints, double dX, double dY)
static boolean isInsidePolygon (double[] dPoly, double dX, double dY, int nStart)
static double polylineDist (double[] dPolyline, int nStart, int nStep)
static double distAlongLine (double[] dPts, double[] dSeg, double dX, double dY)
static boolean collinear (int nX1, int nY1, int nX2, int nY2, int nX3, int nY3, int nTol)
static boolean collinear (double dX1, double dY1, double dX2, double dY2, double dX3, double dY3, double dTol)
static boolean collinear (double dX1, double dY1, double dX2, double dY2, double dX3, double dY3)
static double angle (double dX1, double dY1, double dX2, double dY2)
static double angle (double dX1, double dY1, double dX2, double dY2, double dX3, double dY3)
static double heading (double dX1, double dY1, double dX2, double dY2)
static boolean isClockwise (double[] dPoly, int nStart)
static boolean isClockwise (Area oPoly)
static double perpDist (double dX, double dY, double dX1, double dY1, double dX2, double dY2)
static double[] combineLines (double[] dPts, double dTol)
static double[] combineLineArcs (double[] dPts, double dTol)
static double[] combineArcs (double[] dPts, double dTol)
static double[] simplify (double[] dPts, double dMaxStep)
static void updateBounds (double dX, double dY, double[] dBounds)
static void updateBoundingBox (double[] dUpdate, double[] dPts)
static double circle (double dX1, double dY1, double dX2, double dY2, double dX3, double dY3, double[] dCenter)
static int rightHand (double dX, double dY, double dX1, double dY1, double dX2, double dY2)
static void arcMdpt (double dH, double dK, double dR, double dX1, double dY1, double dX2, double dY2, double dXa, double dYa, double[] dMdpt)
static double[] createPolygon (double[] dInOrder, double[] dReverseOrder)
static void untwist (double[] dPoints)
static void main (String[] sArgs) throws Exception
static Area getArea (double[] dPath, int nStart)
static double distanceFromLatLon (double dLat1, double dLon1, double dLat2, double dLon2)
static boolean ctrlIntersectBounds (double[] dBounds, TrafCtrl oCtrl, int nPtStep)
Static Public Attributes
static final double EARTH_MINOR_RADIUS = 6356752.0
static final double EARTH_MAJOR_RADIUS = 6378137.0
static final double EARTH_FLATTENING = EARTH_MINOR_RADIUS / EARTH_MAJOR_RADIUS
static final double CIRCLE_TOL = 0.001
static final double M_TOL = 1.0E-10
static final double EARTH_RADIUS_KM = 6371
static final double PIOVER180 = Math.PI / 180
Private Member Functions
Geo ()
Detailed Description
Definition at line 15 of file Geo.java.
Constructor & Destructor Documentation
Geo()
cc.util.Geo.Geo () inline private
Definition at line 25 of file Geo.java.
    {
    }
Member Function Documentation
angle() [1/2]
static double cc.util.Geo.angle (double dX1, double dY1, double dX2, double dY2) inline static
Definition at line 343 of file Geo.java.
    {
        return angle(dX1 + 1, dY1, dX1, dY1, dX2, dY2);
    }
References cc.util.Geo.angle().
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.util.Geo.angle(), cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcStop.combine(), cc.ctrl.proc.ProcYield.combine(), cc.ctrl.CtrlLineArcs.getLen(), cc.util.Geo.heading(), and cc.ws.CtrlTiles.splitLineArcs().
angle() [2/2]
static double cc.util.Geo.angle (double dX1, double dY1, double dX2, double dY2, double dX3, double dY3) inline static
Definition at line 349 of file Geo.java.
    {
        double dUi = dX1 - dX2;
        double dUj = dY1 - dY2;
        double dVi = dX3 - dX2;
        double dVj = dY3 - dY2;
        double dDot = dUi * dVi + dUj * dVj;
        double dLenU = Math.sqrt(dUi * dUi + dUj * dUj);
        double dLenV = Math.sqrt(dVi * dVi + dVj * dVj);
        if (dLenU == 0 || dLenV == 0) // prevent division by zero
            return Double.NaN;
        double dValue = dDot / (dLenU * dLenV);
        dValue = MathUtil.round(dValue, 12); // round to help prevent value outside of the domain of arccos
        if (dValue > 1 || dValue < -1) // prevent domain error for arcos
            return Double.NaN;
        return Math.acos(dValue); // return value in radians
    }
References cc.util.MathUtil.round().
arcMdpt()
static void cc.util.Geo.arcMdpt (double dH, double dK, double dR, double dX1, double dY1, double dX2, double dY2, double dXa, double dYa, double[] dMdpt) inline static
Definition at line 1037 of file Geo.java.
    {
        double dMidCX = (dX1 + dX2) / 2;
        double dMidCY = (dY1 + dY2) / 2;
        int nRH1 = rightHand(dXa, dYa, dX1, dY1, dX2, dY2);
        double dAngle;
        if (dH == dMidCX && dK == dMidCY)
            dAngle = heading(dH, dK, dX1, dY1) - Math.PI / 2;
        else
            dAngle = heading(dH, dK, dMidCX, dMidCY);
        double dX = dH + dR * Math.cos(dAngle);
        double dY = dK + dR * Math.sin(dAngle);
        int nRH2 = rightHand(dX, dY, dX1, dY1, dX2, dY2);
        if (nRH1 != nRH2)
        {
            dAngle += Math.PI;
            dX = dH + dR * Math.cos(dAngle);
            dY = dK + dR * Math.sin(dAngle);
        }
        dMdpt[0] = dX;
        dMdpt[1] = dY;
    }
References cc.util.Geo.heading(), and cc.util.Geo.rightHand().
boundingBoxesIntersect() [1/2]
static boolean cc.util.Geo.boundingBoxesIntersect (double dXmin1, double dYmin1, double dXmax1, double dYmax1, double dXmin2, double dYmin2, double dXmax2, double dYmax2) inline static
Definition at line 103 of file Geo.java.
    {
        return dYmax1 >= dYmin2 && dYmin1 <= dYmax2 && dXmax1 >= dXmin2 && dXmin1 <= dXmax2;
    }
boundingBoxesIntersect() [2/2]
static boolean cc.util.Geo.boundingBoxesIntersect (double[] dBb1, double[] dBb2) inline static
Definition at line 97 of file Geo.java.
    {
        return boundingBoxesIntersect(dBb1[0], dBb1[1], dBb1[2], dBb1[3], dBb2[0], dBb2[1], dBb2[2], dBb2[3]);
    }
References cc.util.Geo.boundingBoxesIntersect().
Referenced by cc.util.Geo.boundingBoxesIntersect(), cc.util.TileUtil.clipLineString(), cc.ws.TrackTiles.doGet(), cc.ws.WxPoly.doPost(), cc.ctrl.proc.ProcCtrl.getCurrentControls(), cc.util.TileUtil.includeInTile(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ws.GeoSvc.run(), cc.ws.TcmReqServlet.run(), and cc.ctrl.proc.ProcCtrl.writeIndexFile().
circle()
static double cc.util.Geo.circle (double dX1, double dY1, double dX2, double dY2, double dX3, double dY3, double[] dCenter) inline static
Definition at line 980 of file Geo.java.
    {
        double dDist1 = distance(dX1, dY1, dX2, dY2);
        double dDeltaX1 = dX2 - dX1;
        if (MathUtil.compareTol(dDeltaX1, 0.0, dDist1 * CIRCLE_TOL) == 0) // first two points make a vertical line, switch points
        {
            double dTempX = dX2;
            double dTempY = dY2;
            dX2 = dX3;
            dY2 = dY3;
            dX3 = dTempX;
            dY3 = dTempY;
            dDeltaX1 = dX2 - dX1;
            dDist1 = distance(dX1, dY1, dX2, dY2);
            if (MathUtil.compareTol(dDeltaX1, 0.0, dDist1 * CIRCLE_TOL) == 0) // all 3 points make a vertical line, no valid circle
            {
                dCenter[0] = dCenter[1] = Double.NaN;
                return Double.NaN;
            }
        }
        double dDeltaX2 = dX3 - dX2;
        double dDeltaY2 = dY3 - dY2;
        double dDeltaY1 = dY2 - dY1;
        double dM1 = dDeltaY1 / dDeltaX1;
        double dM2 = dDeltaY2 / dDeltaX2;
        if (MathUtil.compareTol(dM1, dM2, 0.0001) == 0) // parallel lines, no valid circle
        {
            dCenter[0] = dCenter[1] = Double.NaN;
            return Double.NaN;
        }
        dCenter[0] = (dM1 * dM2 * (dY1 - dY3) + dM2 * (dX1 + dX2) - dM1 * (dX2 + dX3)) / (2 * (dM2 - dM1));
        dCenter[1] = -1 * (dCenter[0] - (dX1 + dX2) / 2) / dM1 + (dY1 + dY2) / 2;
        return distance(dX1, dY1, dCenter[0], dCenter[1]); // calculate radius
    }
References cc.util.Geo.CIRCLE_TOL, cc.util.MathUtil.compareTol(), and cc.util.Geo.distance().
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcStop.combine(), cc.ctrl.proc.ProcYield.combine(), cc.util.Geo.combineArcs(), cc.util.Geo.combineLines(), cc.ctrl.CtrlLineArcs.getLen(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.util.Geo.simplify(), and cc.ws.CtrlTiles.splitLineArcs().
collinear() [1/3]
static boolean cc.util.Geo.collinear (double dX1, double dY1, double dX2, double dY2, double dX3, double dY3) inline static
Definition at line 337 of file Geo.java.
    {
        return collinear(dX1, dY1, dX2, dY2, dX3, dY3, 0.0000001);
    }
References cc.util.Geo.collinear().
collinear() [2/3]
static boolean cc.util.Geo.collinear (double dX1, double dY1, double dX2, double dY2, double dX3, double dY3, double dTol) inline static
Definition at line 331 of file Geo.java.
    {
        return Math.abs(dX1 * (dY2 - dY3) + dX2 * (dY3 - dY1) + dX3 * (dY1 - dY2)) < dTol;
    }
collinear() [3/3]
static boolean cc.util.Geo.collinear (int nX1, int nY1, int nX2, int nY2, int nX3, int nY3, int nTol) inline static
Definition at line 325 of file Geo.java.
    {
        return Math.abs(nX1 * (nY2 - nY3) + nX2 * (nY3 - nY1) + nX3 * (nY1 - nY2)) < nTol;
    }
Referenced by cc.util.Geo.collinear(), and cc.util.Geo.distAlongLine().
combineArcs()
static double[] cc.util.Geo.combineArcs (double[] dPts, double dTol) inline static
Definition at line 677 of file Geo.java.
    {
        double[] dRet = Arrays.newDoubleArray(Arrays.size(dPts) / 2);
        dRet = Arrays.add(dRet, new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
        double[] dSeg = new double[9];
        double[] dCurPt = new double[3];
        double[] dCurArc = Arrays.newDoubleArray();
        double[] dSavePts = new double[9];
        double[] dCenter = new double[2];
        int nRightHand = 0;
        Iterator<double[]> oIt = Arrays.iterator(dPts, dSeg, 5, 6);
        while (oIt.hasNext())
        {
            oIt.next();
            double dR = Geo.circle(dSeg[0], dSeg[1], dSeg[3], dSeg[4], dSeg[6], dSeg[7], dCenter); // determine if current segment is line or arc
            if (Double.isFinite(dR) && dR < 10000) // current segment is a line
            {
                if (Arrays.size(dCurArc) == 1) // initialize current arc and endpoints and right hand
                {
                    dCurArc = Arrays.add(dCurArc, dSeg[0], dSeg[1]);
                    dCurArc = Arrays.add(dCurArc, dSeg[2]);
                    dSavePts[0] = dSeg[0];
                    dSavePts[1] = dSeg[1];
                    dSavePts[2] = dSeg[2];
                    dSavePts[3] = dSeg[3];
                    dSavePts[4] = dSeg[4];
                    dSavePts[5] = dSeg[5];
                    dSavePts[6] = dSeg[6];
                    dSavePts[7] = dSeg[7];
                    dSavePts[8] = dSeg[8];
                    nRightHand = rightHand(dSeg[3], dSeg[4], dSeg[0], dSeg[1], dSeg[6], dSeg[7]);
                }
                int nTempRH = rightHand(dSeg[3], dSeg[4], dSeg[0], dSeg[1], dSeg[6], dSeg[7]);
                if (nTempRH != nRightHand) // curve is on the other side of the line compared to the current arc
                { // so finish the current arc and re-initialize it to the current seg
                    nRightHand = nTempRH;
                    dRet = Arrays.addAndUpdate(dRet, dSavePts[0], dSavePts[1]); // only add the first point
                    dRet = Arrays.add(dRet, dSavePts[2]);
                    dRet = Arrays.addAndUpdate(dRet, dSavePts[3], dSavePts[4]); // and the midpoint
                    dRet = Arrays.add(dRet, dSavePts[5]); // the last point will be added by the next line or arc
                    dCurArc[0] = 1; // reset the current arc, save points
                    dCurArc = Arrays.add(dCurArc, dSeg[0], dSeg[1]);
                    dCurArc = Arrays.add(dCurArc, dSeg[2]);
                    dSavePts[0] = dSeg[0];
                    dSavePts[1] = dSeg[1];
                    dSavePts[2] = dSeg[2];
                    dSavePts[3] = dSeg[3];
                    dSavePts[4] = dSeg[4];
                    dSavePts[5] = dSeg[5];
                    dSavePts[6] = dSeg[6];
                    dSavePts[7] = dSeg[7];
                    dSavePts[8] = dSeg[8];
                }
                dCurArc = Arrays.add(dCurArc, dSeg[3], dSeg[4]); // add the midpoint
                dCurArc = Arrays.add(dCurArc, dSeg[5]);
                dCurArc = Arrays.add(dCurArc, dSeg[6], dSeg[7]); // and the last point of the current seg
                dCurArc = Arrays.add(dCurArc, dSeg[8]);
                int nSize = Arrays.size(dCurArc);
                if (nSize > 10) // if more than 1 arc has been added to the current line
                {
                    double dX1 = dCurArc[1]; // set start point
                    double dY1 = dCurArc[2];
                    double dX2 = dCurArc[nSize - 3]; //set end point
                    double dY2 = dCurArc[nSize - 2];
                    int nCount = 0;
                    double dTotalDist = 0.0;
                    Iterator<double[]> oCur = Arrays.iterator(dCurArc, dCurPt, 4, 6); // for control point (mid point of each arc) in the current arc, starting with the 2nd point
                    while (oCur.hasNext())
                    {
                        oCur.next();
                        dTotalDist += perpDist(dCurPt[0], dCurPt[1], dX1, dY1, dX2, dY2);
                        ++nCount;
                    }
                    double dAverageDist = dTotalDist / nCount;
                    double dHdg = heading(dX1, dY1, dX2, dY2);
                    double dMidLineX = (dX1 + dX2) / 2;
                    double dMidLineY = (dY1 + dY2) / 2;
                    double dMidArcX;
                    double dMidArcY;
                    if (nRightHand > 0)
                    {
                        dMidArcX = dMidLineX + Math.sin(dHdg) * dAverageDist;
                        dMidArcY = dMidLineY - Math.cos(dHdg) * dAverageDist;
                    }
                    else
                    {
                        dMidArcX = dMidLineX - Math.sin(dHdg) * dAverageDist;
                        dMidArcY = dMidLineY + Math.cos(dHdg) * dAverageDist;
                    }
                    dR = circle(dX1, dY1, dMidArcX, dMidArcY, dX2, dY2, dCenter);
                    oCur = Arrays.iterator(dCurArc, dCurPt, 4, 6);
                    boolean bWithinTol = true;
                    while (oCur.hasNext())
                    {
                        oCur.next();
                        dHdg = heading(dCenter[0], dCenter[1], dCurPt[0], dCurPt[1]);
                        double dX = dCenter[0] + dR * Math.cos(dHdg);
                        double dY = dCenter[1] + dR * Math.sin(dHdg);
                        if (distance(dX, dY, dCurPt[0], dCurPt[1]) > dTol)
{
                            bWithinTol = false;
                            break;
                        }
                    }
                    if (bWithinTol) // points are still within tolerance, so save endpoints and midpoint
                    {
                        dSavePts[0] = dX1;
                        dSavePts[1] = dY1;
                        dSavePts[2] = dCurArc[3];
                        dSavePts[3] = dMidArcX;
                        dSavePts[4] = dMidArcY;
                        dSavePts[5] = dCurArc[nSize / 3 / 2 * 3 + 3];
                        dSavePts[6] = dX2;
                        dSavePts[7] = dY2;
                        dSavePts[8] = dCurArc[nSize - 1];
                    }
                    else // points are no longer within tolerance, so add the last saved endpoints and midpoint to the final set of points
                    {
                        dRet = Arrays.addAndUpdate(dRet, dSavePts[0], dSavePts[1]); // only add the first point
                        dRet = Arrays.add(dRet, dSavePts[2]);
                        dRet = Arrays.addAndUpdate(dRet, dSavePts[3], dSavePts[4]); // and the midpoint
                        dRet = Arrays.add(dRet, dSavePts[5]); // the last point will be added by the next line or arc
                        dCurArc[0] = 1; // reset the current arc, save points, and right hand value
                        dCurArc = Arrays.add(dCurArc, dSavePts[6], dSavePts[7]);
                        dCurArc = Arrays.add(dCurArc, dSavePts[8]);
                        dSavePts[0] = dSavePts[6];
                        dSavePts[1] = dSavePts[7];
                        dSavePts[2] = dSavePts[8];
                        dSavePts[3] = dSeg[3];
                        dSavePts[4] = dSeg[4];
                        dSavePts[5] = dSeg[5];
                        dSavePts[6] = dSeg[6];
                        dSavePts[7] = dSeg[7];
                        dSavePts[8] = dSeg[8];
                        dCurArc = Arrays.add(dCurArc, dSeg[3], dSeg[4]); // add the midpoint
                        dCurArc = Arrays.add(dCurArc, dSeg[5]);
                        dCurArc = Arrays.add(dCurArc, dSeg[6], dSeg[7]); // and the last point of the current seg
                        dCurArc = Arrays.add(dCurArc, dSeg[8]);
                        nRightHand = rightHand(dSeg[3], dSeg[4], dSeg[0], dSeg[1], dSeg[6], dSeg[7]);
                    }
                }
            }
            else // current segment is line
            {
                if (Arrays.size(dCurArc) >= 10) // finish the current arc
                {
                    dRet = Arrays.addAndUpdate(dRet, dSavePts[0], dSavePts[1]); // only add the first point
                    dRet = Arrays.add(dRet, dSavePts[2]);
                    dRet = Arrays.addAndUpdate(dRet, dSavePts[3], dSavePts[4]); // and the midpoint
                    dRet = Arrays.add(dRet, dSavePts[5]); // the last point will be added by the next line or arc
                }
                dCurArc[0] = 1; // reset current arc
                dRet = Arrays.addAndUpdate(dRet, dSeg[0], dSeg[1]); // add the first point
                dRet = Arrays.add(dRet, dSeg[2]);
                dRet = Arrays.addAndUpdate(dRet, dSeg[3], dSeg[4]); // and the midpoint of line
                dRet = Arrays.add(dRet, dSeg[5]); // the last point will be added by the next line or arc
            }
        }
        dRet = Arrays.addAndUpdate(dRet, dSeg[6], dSeg[7]); // always add the last point. it will finish the last arc or line
        dRet = Arrays.add(dRet, dSeg[8]);
        return dRet;
    }
References cc.util.Arrays.add(), cc.util.Arrays.addAndUpdate(), cc.util.Geo.circle(), cc.util.Geo.distance(), cc.util.Geo.heading(), cc.util.Arrays.iterator(), cc.util.Arrays.newDoubleArray(), cc.util.Geo.perpDist(), cc.util.Geo.rightHand(), and cc.util.Arrays.size().
Referenced by cc.util.Geo.main().
combineLineArcs()
static double[] cc.util.Geo.combineLineArcs (double[] dPts, double dTol) inline static
Definition at line 573 of file Geo.java.
    {
        int nLimit = Arrays.size(dPts);
        double[] dRet = Arrays.newDoubleArray(nLimit / 10);
        dRet = Arrays.add(dRet, new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
        int nStart = 5; // start at 5 to skip bounding box and insertion point
        int nEnd = nStart + 6; // each point is 3 ordinates (x,y,w), skip two poitns
        double dPrevDist = Double.NaN;
        while (nEnd < nLimit)
        {
            double dMaxDist = -Double.MAX_VALUE;
            double dX1 = dPts[nStart];
            double dY1 = dPts[nStart + 1];
            double dX2 = dPts[nEnd];
            double dY2 = dPts[nEnd + 1];
            for (int nTest = nStart + 3; nTest < nEnd; nTest += 3)
            {
                double dDist = perpDist(dPts[nTest], dPts[nTest + 1], dX1, dY1, dX2, dY2);
                if (dDist > dMaxDist)
                    dMaxDist = dDist;
            }
            if (dMaxDist > dTol)
            {
                nEnd -= 3;
                double dMidX = (dX1 + dX2) / 2;
                double dMidY = (dY1 + dY2) / 2;
                boolean bArc = true;
                int nFirstSide = rightHand(dPts[nStart + 3], dPts[nStart + 4], dX1, dY1, dX2, dY2);
                for (int nTest = nStart + 6; nTest < nEnd; nTest += 3)
                {
                    if (rightHand(dPts[nTest], dPts[nTest + 1], dX1, dY1, dX2, dY2) != nFirstSide)
                    {
                        bArc = false;
                        break;
                    }
                }
                dRet = Arrays.addAndUpdate(dRet, dX1, dY1);
                dRet = Arrays.add(dRet, dPts[nStart + 2]);
                if (bArc)
                {
                    double dPerpAngle = heading(dX1, dY1, dX2, dY2) + (nFirstSide * Mercator.PI_OVER_TWO);
                    dMidX += dPrevDist * Math.cos(dPerpAngle);
                    dMidY += dPrevDist * Math.sin(dPerpAngle);
                }
                int nMidWidth = (nEnd - nStart) / 3;
                double dMidWidth;
                if (nMidWidth % 2 == 0)
                {
                    dMidWidth = dPts[nStart + nMidWidth / 2 * 3 + 2];
                }
                else
                {
                    int nFirstIndex = nStart + nMidWidth / 2 * 3 + 2;
                    int nSecondIndex = nFirstIndex + 3;
                    dMidWidth = (dPts[nFirstIndex] + dPts[nSecondIndex]) / 2;
                }
                dRet = Arrays.addAndUpdate(dRet, dMidX, dMidY);
                dRet = Arrays.add(dRet, dMidWidth);
                nStart = nEnd;
                nEnd = nStart + 6;
                dPrevDist = Double.NaN;
            }
            else
            {
                dPrevDist = dMaxDist;
                nEnd += 3;
            }
        }
        if (Double.isNaN(dPrevDist) || dPrevDist < dTol)
        {
            nEnd -= 3;
            dRet = Arrays.addAndUpdate(dRet, dPts[nStart], dPts[nStart + 1]);
            dRet = Arrays.add(dRet, dPts[nStart + 2]);
            double dMidX = (dPts[nStart] + dPts[nEnd]) / 2;
            double dMidY = (dPts[nStart + 1] + dPts[nEnd + 1]) / 2;
            int nMidWidth = (nEnd - nStart) / 3;
            double dMidWidth;
            if (nMidWidth % 2 == 0)
            {
                dMidWidth = dPts[nStart + nMidWidth / 2 * 3 + 2];
            }
            else
            {
                int nFirstIndex = nStart + nMidWidth / 2 * 3 + 2;
                int nSecondIndex = nFirstIndex + 3;
                dMidWidth = (dPts[nFirstIndex] + dPts[nSecondIndex]) / 2;
            }
            dRet = Arrays.addAndUpdate(dRet, dMidX, dMidY);
            dRet = Arrays.add(dRet, dMidWidth);
        }
        dRet = Arrays.addAndUpdate(dRet, dPts[nLimit - 3], dPts[nLimit - 2]);
        dRet = Arrays.add(dRet, dPts[nLimit - 1]);
        return dRet;
    }
References cc.util.Arrays.add(), cc.util.Arrays.addAndUpdate(), cc.util.Geo.heading(), cc.util.Arrays.newDoubleArray(), cc.util.Geo.perpDist(), cc.geosrv.Mercator.PI_OVER_TWO, cc.util.Geo.rightHand(), and cc.util.Arrays.size().
Referenced by cc.ctrl.CtrlLineArcs.CtrlLineArcs().
combineLines()
static double[] cc.util.Geo.combineLines (double[] dPts, double dTol) inline static
Definition at line 461 of file Geo.java.
    {
        double[] dRet = Arrays.newDoubleArray(Arrays.size(dPts) / 2);
        dRet = Arrays.add(dRet, new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
        double[] dSeg = new double[9];
        double[] dCurPt = new double[3];
        double[] dCurLine = Arrays.newDoubleArray();
        double[] dEndPts = new double[6];
        double[] dCenter = new double[2];
        Iterator<double[]> oIt = Arrays.iterator(dPts, dSeg, 5, 6);
        while (oIt.hasNext())
        {
            oIt.next();
            double dR = Geo.circle(dSeg[0], dSeg[1], dSeg[3], dSeg[4], dSeg[6], dSeg[7], dCenter); // determine if current segment is line or arc
            if (!Double.isFinite(dR) || dR >= 10000) // current segment is a line
            {
                if (Arrays.size(dCurLine) == 1) // initialize current line and endpoints
                {
                    dCurLine = Arrays.add(dCurLine, dSeg[0], dSeg[1]);
                    dCurLine = Arrays.add(dCurLine, dSeg[2]);
                    dEndPts[0] = dSeg[0];
                    dEndPts[1] = dSeg[1];
                    dEndPts[2] = dSeg[2];
                    dEndPts[3] = dSeg[6];
                    dEndPts[4] = dSeg[7];
                    dEndPts[5] = dSeg[8];
                }
                dCurLine = Arrays.add(dCurLine, dSeg[3], dSeg[4]); // add the midpoint
                dCurLine = Arrays.add(dCurLine, dSeg[5]);
                dCurLine = Arrays.add(dCurLine, dSeg[6], dSeg[7]); // and the last point of the current seg
                dCurLine = Arrays.add(dCurLine, dSeg[8]);
                int nSize = Arrays.size(dCurLine);
                if (nSize > 10) // if more than 1 line has been added to the current line
                {
                    double dX1 = dCurLine[1]; // set start point
                    double dY1 = dCurLine[2];
                    double dX2 = dCurLine[nSize - 3]; //set end point
                    double dY2 = dCurLine[nSize - 2];
                    int nCount = 0;
                    double dTotalDist = 0.0;
                    Iterator<double[]> oCur = Arrays.iterator(dCurLine, dCurPt, 4, 3); // for each point in the current line, starting with the 2nd point
                    while (oCur.hasNext())
                    {
                        oCur.next();
                        dTotalDist += perpDist(dCurPt[0], dCurPt[1], dX1, dY1, dX2, dY2);
                        ++nCount;
                    }
                    --nCount; // subtract one off because we did the distance of the endpoint which should be zero and we dont want it to skew the average
                    if (dTotalDist / nCount <= dTol) // points are still within tolerance, so save endpoints
                    {
                        dEndPts[0] = dX1;
                        dEndPts[1] = dY1;
                        dEndPts[2] = dCurLine[3];
                        dEndPts[3] = dX2;
                        dEndPts[4] = dY2;
                        dEndPts[5] = dCurLine[nSize - 1];
                    }
                    else // points are no longer within tolerance, so use the last saved endpoint to calculate a midpoint and add to the final set of points
                    {
                        double dHdg = heading(dEndPts[0], dEndPts[1], dEndPts[3], dEndPts[4]);
                        double dDist = distance(dEndPts[0], dEndPts[1], dEndPts[3], dEndPts[4]);
                        double dMidX = dEndPts[0] + dDist * Math.cos(dHdg);
                        double dMidY = dEndPts[1] + dDist * Math.sin(dHdg);
                        double dMidW = (dEndPts[2] + dEndPts[5]) / 2;
                        dRet = Arrays.addAndUpdate(dRet, dEndPts[0], dEndPts[1]); // only add the first point
                        dRet = Arrays.add(dRet, dEndPts[2]);
                        dRet = Arrays.addAndUpdate(dRet, dMidX, dMidY); // and the midpoint
                        dRet = Arrays.add(dRet, dMidW); // the last point will be added by the next line or arc
                        dCurLine[0] = 1; // reset the current line and the endpoints
                        dCurLine = Arrays.add(dCurLine, dEndPts[3], dEndPts[4]);
                        dCurLine = Arrays.add(dCurLine, dEndPts[5]);
                        dEndPts[0] = dEndPts[3];
                        dEndPts[1] = dEndPts[4];
                        dEndPts[2] = dEndPts[5];
                        dEndPts[3] = dSeg[6];
                        dEndPts[4] = dSeg[7];
                        dEndPts[5] = dSeg[8];
                        dCurLine = Arrays.add(dCurLine, dSeg[3], dSeg[4]); // add the midpoint
                        dCurLine = Arrays.add(dCurLine, dSeg[5]);
                        dCurLine = Arrays.add(dCurLine, dSeg[6], dSeg[7]); // and the last point of the current seg
                        dCurLine = Arrays.add(dCurLine, dSeg[8]);
                    }
                }
            }
            else // current segment is arc
            {
                if (Arrays.size(dCurLine) >= 10) // save the current line
                {
                    double dHdg = heading(dEndPts[0], dEndPts[1], dEndPts[3], dEndPts[4]);
                    double dDist = distance(dEndPts[0], dEndPts[1], dEndPts[3], dEndPts[4]) / 2;
                    double dMidX = dEndPts[0] + dDist * Math.cos(dHdg);
                    double dMidY = dEndPts[1] + dDist * Math.sin(dHdg);
                    double dMidW = (dEndPts[2] + dEndPts[5]) / 2;
                    dRet = Arrays.addAndUpdate(dRet, dEndPts[0], dEndPts[1]); // only add the first point
                    dRet = Arrays.add(dRet, dEndPts[2]);
                    dRet = Arrays.addAndUpdate(dRet, dMidX, dMidY); // and the midpoint
                    dRet = Arrays.add(dRet, dMidW); // the last point will be added by the next line or arc
                }
                dCurLine[0] = 1; // reset current line
                dRet = Arrays.addAndUpdate(dRet, dSeg[0], dSeg[1]); // add the first point
                dRet = Arrays.add(dRet, dSeg[2]);
                dRet = Arrays.addAndUpdate(dRet, dSeg[3], dSeg[4]); // and the midpoint of arc
                dRet = Arrays.add(dRet, dSeg[5]); // the last point will be added by the next line or arc
            }
        }
        dRet = Arrays.addAndUpdate(dRet, dSeg[6], dSeg[7]); // always add the last point. it will finish the last arc or line
        dRet = Arrays.add(dRet, dSeg[8]);
        return dRet;
    }
References cc.util.Arrays.add(), cc.util.Arrays.addAndUpdate(), cc.util.Geo.circle(), cc.util.Geo.distance(), cc.util.Geo.heading(), cc.util.Arrays.iterator(), cc.util.Arrays.newDoubleArray(), cc.util.Geo.perpDist(), and cc.util.Arrays.size().
Referenced by cc.util.Geo.main().
createPolygon()
static double[] cc.util.Geo.createPolygon (double[] dInOrder, double[] dReverseOrder) inline static
Definition at line 1063 of file Geo.java.
    {
        int nInOrderLimit = Arrays.size(dInOrder);
        int nReverseOrderLimit = Arrays.size(dReverseOrder);
        double[] dPoly = Arrays.newDoubleArray(nInOrderLimit + nReverseOrderLimit);
        for (int i = 1; i < nInOrderLimit;)
            dPoly = Arrays.add(dPoly, dInOrder[i++], dInOrder[i++]);
        for (int i = nReverseOrderLimit - 2; i >= 1; i -= 2)
            dPoly = Arrays.add(dPoly, dReverseOrder[i], dReverseOrder[i + 1]);
        return dPoly;
    }
References cc.util.Arrays.add(), cc.util.Arrays.newDoubleArray(), and cc.util.Arrays.size().
Referenced by cc.ihp.Subsegment.Subsegment(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcPavement.renderTiledData(), and cc.ctrl.proc.ProcClosing.renderTiledData().
ctrlIntersectBounds()
static boolean cc.util.Geo.ctrlIntersectBounds (double[] dBounds, TrafCtrl oCtrl, int nPtStep) inline static
Definition at line 1230 of file Geo.java.
    {
        double[] dC = oCtrl.m_oFullGeo.m_dC;
        double[] dNt = oCtrl.m_oFullGeo.m_dNT;
        double[] dPt = oCtrl.m_oFullGeo.m_dPT;
        int nStep = nPtStep * 2;
        int nSize = Arrays.size(dC);
        for (int nIndex = 1; nIndex < nSize; nIndex += nStep)
        {
            if (Geo.isInsidePolygon(dBounds, dC[nIndex], dC[nIndex + 1]) && Geo.isInsidePolygon(dBounds, dNt[nIndex], dNt[nIndex + 1]) && Geo.isInsidePolygon(dBounds, dPt[nIndex], dPt[nIndex + 1]))
                return true;
        }
        return Geo.isInsidePolygon(dBounds, dC[nSize - 2], dC[nSize - 1]) && Geo.isInsidePolygon(dBounds, dNt[nSize - 2], dNt[nSize - 1]) && Geo.isInsidePolygon(dBounds, dPt[nSize - 2], dPt[nSize - 1]);
    }
References cc.util.Geo.isInsidePolygon(), cc.ctrl.CtrlGeo.m_dC, cc.ctrl.CtrlGeo.m_dNT, cc.ctrl.CtrlGeo.m_dPT, cc.ctrl.TrafCtrl.m_oFullGeo, and cc.util.Arrays.size().
Referenced by cc.ws.TcmReqServlet.run().
distAlongLine()
static double cc.util.Geo.distAlongLine (double[] dPts, double[] dSeg, double dX, double dY) inline static
Definition at line 307 of file Geo.java.
    {
        double dDist = 0.0;
        Iterator<double[]> oIt = Arrays.iterator(dPts, dSeg, 1, 2);
        while (oIt.hasNext())
        {
            oIt.next();
            if (isInBoundingBox(dX, dY, dSeg[1], dSeg[0], dSeg[3], dSeg[2]) && collinear(dX, dY, dSeg[1], dSeg[0], dSeg[3], dSeg[2]))
            {
                dDist += distance(dX, dY, dSeg[1], dSeg[0]);
                return dDist;
            }
            dDist += distance(dSeg[1], dSeg[0], dSeg[3], dSeg[2]);
        }
        return Double.NaN;
    }
References cc.util.Geo.collinear(), cc.util.Geo.distance(), cc.util.Geo.isInBoundingBox(), and cc.util.Arrays.iterator().
Referenced by cc.ws.EventMgr.doMsgs().
distance() [1/2]
static double cc.util.Geo.distance (double dXi, double dYi, double dXj, double dYj) inline static
Definition at line 77 of file Geo.java.
    {
        return Math.sqrt(sqDist(dXi, dYi, dXj, dYj));
//      double dXd = dXj - dXi; // correct distance by latitude
//      double dYd = dYj - dYi;
//      return Math.sqrt(dXd * dXd + dYd * dYd);
    }
References cc.util.Geo.sqDist().
distance() [2/2]
static double cc.util.Geo.distance (int nXi, int nYi, int nXj, int nYj) inline static
Definition at line 71 of file Geo.java.
    {
        return distance(toMeters(nXi), toMeters(nYi), toMeters(nXj), toMeters(nYj));
    }
References cc.util.Geo.distance(), and cc.util.Geo.toMeters().
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ihp.Subsegment.Subsegment(), cc.ws.GeoSvc.Way.Way(), cc.ws.CtrlTiles.addControl(), cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.pvmt.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.xodr.pvmt.Arc.addLanePoints(), cc.util.Geo.circle(), cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcStop.combine(), cc.ctrl.proc.ProcYield.combine(), cc.util.Geo.combineArcs(), cc.util.Geo.combineLines(), cc.ctrl.CreateCtrls.createCtrl(), cc.ctrl.proc.ProcLatPerm.createDashedLine(), cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile(), cc.geosrv.xodr.geo.LaneSection.createPavement(), cc.geosrv.xodr.pvmt.LaneSection.createPavement(), cc.util.Geo.distAlongLine(), cc.util.Geo.distance(), cc.ctrl.proc.ProcCtrl.getCoordAndHeadingAtLength(), cc.ctrl.CtrlLineArcs.getLen(), cc.geosrv.xodr.pvmt.LaneSection.getShoulders(), cc.ctrl.proc.ProcCtrl.getStopLine(), cc.geosrv.Mercator.main(), cc.util.Geo.polylineDist(), cc.ctrl.TrafCtrl.preparePoints(), cc.ctrl.proc.ProcClosed.renderLines(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.geosrv.xodr.geo.Road.setLaneIds(), cc.geosrv.xodr.pvmt.Road.setLaneIds(), cc.geosrv.xodr.rdmk.Road.setLaneIds(), cc.util.Geo.simplify(), and cc.ws.CtrlTiles.splitLineArcs().
distanceFromLatLon()
static double cc.util.Geo.distanceFromLatLon (double dLat1, double dLon1, double dLat2, double dLon2) inline static
Adapted from the Haversine formula
Parameters
dLat1
dLon1
dLat2
dLon2
Returns
Definition at line 1221 of file Geo.java.
    {
        double dLat = (dLat2 - dLat1) * PIOVER180;
        double dLon = (dLon2 - dLon1) * PIOVER180;
        double dA = Math.sin(dLat / 2) * Math.sin(dLat /2) + Math.cos(dLat1 * PIOVER180) * Math.cos(dLat2 * PIOVER180) * Math.sin(dLon / 2) * Math.sin(dLon / 2);
        return 2 * EARTH_RADIUS_KM * Math.asin(Math.sqrt(dA));
    }
References cc.util.Geo.EARTH_RADIUS_KM, and cc.util.Geo.PIOVER180.
fromIntDeg()
static double cc.util.Geo.fromIntDeg (int nOrd) inline static
Definition at line 53 of file Geo.java.
    {
        return ((double)nOrd) / 10000000.0;
    }
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.util.TestPath.main1(), cc.rsm.RsmParser.parseRequest(), cc.ctrl.TrafCtrl.preparePoints(), cc.ws.GeoSvc.Way.printBounds(), cc.ws.GeoSvc.Way.printDetail(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.ws.GeoSvc.run(), cc.ws.TcmReqServlet.run(), cc.ihp.IHPRequest.sendRequest(), cc.ctrl.TcBounds.setCorners(), cc.ws.GeoSvc.SimWay.setLoc(), and cc.ctrl.TrafCtrl.toMercatorPoints().
getArea()
static Area cc.util.Geo.getArea (double[] dPath, int nStart) inline static
Definition at line 1193 of file Geo.java.
    {
        if (Arrays.size(dPath) - nStart < 6) // must have at least 3 points
            return null;
        Path2D.Double oPath = new Path2D.Double();
        double[] dPt = new double[2];
        Iterator<double[]> oIt = Arrays.iterator(dPath, dPt, nStart, 2);
        oIt.next();
        oPath.moveTo(dPt[0], dPt[1]);
        while (oIt.hasNext())
        {
            oIt.next();
            oPath.lineTo(dPt[0], dPt[1]);
        }
        oPath.closePath();
        return new Area(oPath);
    }
References cc.util.Arrays.iterator(), and cc.util.Arrays.size().
Referenced by cc.ws.CtrlTiles.doGet(), and cc.ws.ValidateXodrTiles.doGet().
getHash()
static int cc.util.Geo.getHash (int nLat, int nLon) inline static
Definition at line 47 of file Geo.java.
    {
        return (scale(nLon) << 16) + scale(nLat);
    }
References cc.util.Geo.scale().
Referenced by cc.ws.GeoSvc.SimWay.nextWay().
heading()
static double cc.util.Geo.heading (double dX1, double dY1, double dX2, double dY2) inline static
Definition at line 369 of file Geo.java.
    {
        double dRads = angle(dX1, dY1, dX2, dY2);
        if (dY1 > dY2)
            dRads = 2 * Math.PI - dRads;
        return dRads;
    }
References cc.util.Geo.angle().
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ihp.Subsegment.Subsegment(), cc.ctrl.TrafCtrl.TrafCtrl(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.xodr.pvmt.Arc.addLanePoints(), cc.util.Geo.arcMdpt(), cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcStop.combine(), cc.ctrl.proc.ProcYield.combine(), cc.util.Geo.combineArcs(), cc.util.Geo.combineLineArcs(), cc.util.Geo.combineLines(), cc.ctrl.proc.ProcLatPerm.createDashedLine(), cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile(), cc.ctrl.proc.ProcCtrl.getCoordAndHeadingAtLength(), cc.ctrl.CtrlLineArcs.getLen(), cc.ctrl.proc.ProcCtrl.getStopLine(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), and cc.ws.CtrlTiles.splitLineArcs().
isClockwise() [1/2]
static boolean cc.util.Geo.isClockwise (Area oPoly) inline static
Definition at line 394 of file Geo.java.
    {
        double[] dCoords = new double[2];
        double[] dPrev = new double[2];
        double[] dFirst = new double[2];
        double dWinding = 0;
        PathIterator oIt = oPoly.getPathIterator(null);
        while (!oIt.isDone()) // first determine which parts of multi-path are polygons and holes
        {
            switch (oIt.currentSegment(dCoords))
            {
                case PathIterator.SEG_MOVETO:
                {
                    dWinding = 0;
                    System.arraycopy(dCoords, 0, dFirst, 0, 2);
                    System.arraycopy(dCoords, 0, dPrev, 0, 2);
                    break;
                }
                case PathIterator.SEG_LINETO:
                {
                    dWinding += ((dCoords[0] - dPrev[0]) * (dCoords[1] + dPrev[1]));
                    System.arraycopy(dCoords, 0, dPrev, 0, 2);
                    break;
                }
                case PathIterator.SEG_CLOSE:
                {
                    dWinding += ((dFirst[0] - dCoords[0]) * (dFirst[1] + dCoords[1]));
                    break;
                }
            }
            oIt.next();
        }
        return dWinding > 0;
    }
isClockwise() [2/2]
static boolean cc.util.Geo.isClockwise (double[] dPoly, int nStart) inline static
Definition at line 379 of file Geo.java.
    {
        double dWinding = 0;
        double[] dLine = new double[4];
        Iterator<double[]> oIt = Arrays.iterator(dPoly, dLine, nStart, 2);
        while (oIt.hasNext())
        {
            oIt.next();
            dWinding += (dLine[2] - dLine[0]) * (dLine[3] + dLine[1]);
        }
        dWinding += (dPoly[nStart] - dLine[2]) * (dPoly[nStart + 1] + dLine[3]); // have to calculate the last edge
        return dWinding > 0;
    }
References cc.util.Arrays.iterator().
Referenced by cc.ctrl.proc.ProcClosed.renderTiledData(), and cc.ctrl.proc.ProcPavement.renderTiledData().
isInBoundingBox()
static boolean cc.util.Geo.isInBoundingBox (double dX, double dY, double dX1, double dY1, double dX2, double dY2) inline static
Definition at line 166 of file Geo.java.
    {
        if (dX1 > dX2)
        {
            double dTemp = dX1;
            dX1 = dX2;
            dX2 = dTemp;
        }
        if (dY1 > dY2)
        {
            double dTemp = dY1;
            dY1 = dY2;
            dY2 = dTemp;
        }
        return dX >= dX1 && dX <= dX2 && dY >= dY1 && dY <= dY2;
    }
Referenced by cc.ihp.IHPResponse.IHPResponse(), cc.util.Geo.distAlongLine(), cc.ihp.IHP.generateSpeedControls(), and cc.ihp.Subsegment.pointInside().
isInside() [1/2]
static boolean cc.util.Geo.isInside (double dX, double dY, double dT, double dR, double dB, double dL, double dTol) inline static
Determines if the specified point is within the specified boundary. A specified tolerance adjusts the compared region as needed
Parameters
dX x coordinate of point
dY y coordinate of point
dT y value of the top of the region
dR x value of the right side of the region
dB y value of the bottom of the region
dL x value of the left side of the region
dTol the allowed margin for a point to be considered inside
Returns
true if the point is inside or on the rectangular region
Definition at line 158 of file Geo.java.
    {
        return (dX >= dL - dTol && dX <= dR + dTol
           && dY >= dB - dTol && dY <= dT + dTol);
    }
isInside() [2/2]
static boolean cc.util.Geo.isInside (int nX, int nY, int nT, int nR, int nB, int nL, int nTol) inline static
Determines if the specified point is within the specified boundary. A specified tolerance adjusts the compared region as needed.
Parameters
nX x coordinate of point
nY y coordinate of point
nT y value of the top of the region
nR x value of the right side of the region
nB y value of the bottom of the region
nL x value of the left side of the region
nTol the allowed margin for a point to be considered inside
Returns
true if the point is inside or on the rectangular region
Definition at line 122 of file Geo.java.
    {
        if (nR < nL) // swap the left and right bounds as needed
        {
            nR ^= nL;
            nL ^= nR;
            nR ^= nL;
        }
        if (nT < nB) // swap the top and bottom bounds as needed
        {
            nT ^= nB;
            nB ^= nT;
            nT ^= nB;
        }
        // expand the bounds by the tolerance
        return (nX >= nL - nTol && nX <= nR + nTol
           && nY >= nB - nTol && nY <= nT + nTol);
    }
Referenced by cc.util.TileUtil.clipLineString(), cc.ws.CtrlTiles.doGet(), cc.ws.TrackTiles.doGet(), cc.ws.ValidateXodrTiles.doGet(), and cc.ctrl.proc.ProcDebug.renderTiledData().
isInsidePolygon() [1/3]
static boolean cc.util.Geo.isInsidePolygon (double[] dPoly, double dX, double dY, int nStart) inline static
Definition at line 271 of file Geo.java.
    {
        int nCount = 0;
        double[] dSeg = new double[4];
        Iterator<double[]> oIt = Arrays.iterator(dPoly, dSeg, nStart, 2);
        while (oIt.hasNext())
        {
            oIt.next();
            double dX1 = dSeg[0];
            double dY1 = dSeg[1];
            double dX2 = dSeg[2];
            double dY2 = dSeg[3];
            if ((dY1 < dY && dY2 >= dY || dY2 < dY && dY1 >= dY)
               && (dX1 <= dX || dX2 <= dX)
               && (dX1 + (dY - dY1) / (dY2 - dY1) * (dX2 - dX1) < dX))
                ++nCount;
        }
        return (nCount & 1) != 0;
    }
References cc.util.Arrays.iterator().
isInsidePolygon() [2/3]
static boolean cc.util.Geo.isInsidePolygon (double[] dPolyPoints, double dX, double dY) inline static
Determines if a given x,y coordinate is inside the polygon defined by the array.
Parameters
dPolyPoints array of coordinates that define a polygon. Order is [x1, y1, x2, y2, ..., x1, y1]
dX x coordinate of the point
dY y coordinate of the point
Returns
true if the point is inside the polygon, otherwise false
Definition at line 251 of file Geo.java.
    {
        int nCount = 0;
        int nEnd = dPolyPoints.length - 2;
        for (int nPos = 0; nPos < nEnd; nPos += 2)
        {
            double dX1 = dPolyPoints[nPos];
            double dX2 = dPolyPoints[nPos + 2];
            double dY1 = dPolyPoints[nPos + 1];
            double dY2 = dPolyPoints[nPos + 3];
            if ((dY1 < dY && dY2 >= dY || dY2 < dY && dY1 >= dY)
               && (dX1 <= dX || dX2 <= dX)
               && (dX1 + (dY - dY1) / (dY2 - dY1) * (dX2 - dX1) < dX))
                ++nCount;
        }
        return (nCount & 1) != 0;
    }
isInsidePolygon() [3/3]
static boolean cc.util.Geo.isInsidePolygon (int[] nPolyPoints, double nX, double nY) inline static
Determines if a given x,y coordinate is inside the polygon defined by the array.
Parameters
nPolyPoints array of coordinates that define a polygon. Order is [x1, y1, x2, y2, ..., x1, y1]
nX x coordinate of the point
nY y coordinate of the point
Returns
true if the point is inside the polygon, otherwise false
Definition at line 208 of file Geo.java.
    {
        int nCount = 0;
        int nEnd = nPolyPoints.length - 2;
        for (int nPos = 0; nPos < nEnd; nPos += 2)
        {
            int nX1 = nPolyPoints[nPos];
            int nX2 = nPolyPoints[nPos + 2];
            int nY1 = nPolyPoints[nPos + 1];
            int nY2 = nPolyPoints[nPos + 3];
            if ((nY1 < nY && nY2 >= nY || nY2 < nY && nY1 >= nY)
               && (nX1 <= nX || nX2 <= nX)
               && (nX1 + (nY - nY1) / (nY2 - nY1) * (nX2 - nX1) < nX))
                ++nCount;
        }
        return (nCount & 1) != 0;
    }
Referenced by cc.util.Geo.ctrlIntersectBounds(), cc.ihp.IHP.generateSpeedControls(), cc.ihp.Subsegment.pointInside(), and cc.util.Geo.polylineInside().
main()
static void cc.util.Geo.main (String[] sArgs) throws Exception inline static
Definition at line 1109 of file Geo.java.
    {
//      double[] dA = Arrays.newDoubleArray();
//      dA = Arrays.add(dA, 1, 2);
//      dA = Arrays.add(dA, 3);
//      dA = Arrays.add(dA, 1, 2);
//      dA = Arrays.add(dA, 3);
//      dA = Arrays.add(dA, 1, 2);
//      dA = Arrays.add(dA, 3);
//      System.out.println(Arrays.size(dA));
//      if (true)
//          return;
        try (DataInputStream oIn = new DataInputStream(new BufferedInStream(FileUtil.newInputStream(Paths.get("C:/Users/aaron.cherney/Documents/centi2and25.bin")))))
        {
            while (oIn.available() > 0)
            {
                CtrlLineArcs oCla = new CtrlLineArcs(oIn);
                int nRoadId = XodrUtil.getRoadId(oCla.m_nLaneId);
                int nLaneIndex = XodrUtil.getLaneIndex(oCla.m_lLaneSectionId);
                if (nRoadId != 24 || nLaneIndex != -1)
                    continue;
//              int nOrds = oIn.readInt();
//              double[] dPts = Arrays.newDoubleArray(nOrds);
//              for (int nIndex = 0; nIndex < nOrds; nIndex += 2)
//              {
//                  dPts = Arrays.add(dPts, oIn.readDouble(), oIn.readDouble());
//              }
                double[] dSim = simplify(oCla.m_dLineArcs, 0.05);
                double[] dCombine = combineLines(dSim, 0.05);
                double[] dCombineArc = combineArcs(dSim, 0.05);
                System.out.println(Arrays.size(oCla.m_dLineArcs));
                System.out.println(Arrays.size(dSim));
                System.out.println(Arrays.size(dCombine));
                System.out.println(Arrays.size(dCombineArc));
                Iterator<double[]> oIt = Arrays.iterator(dSim, new double[3], 5, 3);
//              while (oIt.hasNext())
//              {
//                  double[] dPt = oIt.next();
//                  System.out.println(String.format("%3.8f\t%3.8f\t%3.8f", dPt[0], dPt[1], dPt[2]));
//              }
            }
        }
    }
References cc.util.Geo.combineArcs(), cc.util.Geo.combineLines(), cc.geosrv.xodr.XodrUtil.getLaneIndex(), cc.geosrv.xodr.XodrUtil.getRoadId(), cc.util.Arrays.iterator(), cc.ctrl.CtrlLineArcs.m_dLineArcs, cc.ctrl.CtrlLineArcs.m_lLaneSectionId, cc.ctrl.CtrlLineArcs.m_nLaneId, cc.util.FileUtil.newInputStream(), cc.util.Geo.simplify(), and cc.util.Arrays.size().
perpDist()
static double cc.util.Geo.perpDist (double dX, double dY, double dX1, double dY1, double dX2, double dY2) inline static
Definition at line 432 of file Geo.java.
    {
        double dXd = dX2 - dX1;
        double dYd = dY2 - dY1;
        double dXp = dX - dX1;
        double dYp = dY - dY1;
        if (dXd == 0 && dYd == 0) // line segment is a point
            return Math.sqrt(dXp * dXp + dYp * dYp); // dist between the points
        double dU = dXp * dXd + dYp * dYd;
        double dV = dXd * dXd + dYd * dYd;
        if (dU < 0 || dU > dV) // nearest point is not on the line
        {
            return Double.NaN;
        }
        // find the perpendicular intersection of the point on the line
        dXp = dX1 + (dU * dXd / dV);
        dYp = dY1 + (dU * dYd / dV);
        dXd = dX - dXp; // calculate the distance
        dYd = dY - dYp; // between the point and the intersection
        return Math.sqrt(dXd * dXd + dYd * dYd);
    }
Referenced by cc.util.Geo.combineArcs(), cc.util.Geo.combineLineArcs(), and cc.util.Geo.combineLines().
polylineDist()
static double cc.util.Geo.polylineDist (double[] dPolyline, int nStart, int nStep) inline static
Definition at line 293 of file Geo.java.
    {
        Iterator<double[]> oIt = Arrays.iterator(dPolyline, new double[nStep * 2], nStart, nStep);
        double dTotalDist = 0.0;
        while (oIt.hasNext())
        {
            double[] dSeg = oIt.next();
            dTotalDist += distance(dSeg[0], dSeg[1], dSeg[nStep], dSeg[nStep + 1]);
        }
        return dTotalDist;
    }
References cc.util.Geo.distance(), and cc.util.Arrays.iterator().
polylineInside() [1/2]
static boolean cc.util.Geo.polylineInside (double[] dPolygon, double[] dPolyline) inline static
Definition at line 228 of file Geo.java.
    {
        Iterator<double[]> oIt = Arrays.iterator(dPolyline, new double[2], 1, 2);
        while (oIt.hasNext())
        {
            double[] nPt = oIt.next();
            if (isInsidePolygon(dPolygon, nPt[0], nPt[1]))
                return true;
        }
        return false;
    }
References cc.util.Geo.isInsidePolygon(), and cc.util.Arrays.iterator().
polylineInside() [2/2]
static boolean cc.util.Geo.polylineInside (int[] nPolygon, int[] nPolyline) inline static
Definition at line 185 of file Geo.java.
    {
        Iterator<int[]> oIt = Arrays.iterator(nPolyline, new int[2], 1, 2);
        while (oIt.hasNext())
        {
            int[] nPt = oIt.next();
            if (isInsidePolygon(nPolygon, nPt[0], nPt[1]))
                return true;
        }
        return false;
    }
References cc.util.Geo.isInsidePolygon(), and cc.util.Arrays.iterator().
reverseOrder()
static double[] cc.util.Geo.reverseOrder (double[] dPoly) inline static
Definition at line 30 of file Geo.java.
    {
        int nLimit = Arrays.size(dPoly);
        double[] dRet = Arrays.newDoubleArray(nLimit);
        for (int i = nLimit - 2; i >= 1; i -= 2)
            dRet = Arrays.add(dRet, dPoly[i], dPoly[i + 1]);
        return dRet;
    }
References cc.util.Arrays.add(), cc.util.Arrays.newDoubleArray(), and cc.util.Arrays.size().
Referenced by cc.ctrl.proc.ProcClosed.renderTiledData(), and cc.ctrl.proc.ProcPavement.renderTiledData().
rightHand()
static int cc.util.Geo.rightHand (double dX, double dY, double dX1, double dY1, double dX2, double dY2) inline static
Definition at line 1019 of file Geo.java.
    {
        double dXp = dX - dX1;
        double dXd = dX2 - dX1;
        double dYp = dY - dY1;
        double dYd = dY2 - dY1;
        double dVal = (dXd * dYp) - (dYd * dXp);
        if (dVal > 0)
            return 1;
        else if (dVal < 0)
            return -1;
        return 0;
    }
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.util.Geo.arcMdpt(), cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcStop.combine(), cc.ctrl.proc.ProcYield.combine(), cc.util.Geo.combineArcs(), cc.util.Geo.combineLineArcs(), cc.ctrl.CtrlLineArcs.getLen(), and cc.ws.CtrlTiles.splitLineArcs().
scale()
static int cc.util.Geo.scale (int nVal) inline static
Definition at line 41 of file Geo.java.
    {
        return (int)Math.floor(((double)nVal) / 100000.0); // OSM geo-coordinates have 7 decimal places
    }
Referenced by cc.util.Geo.getHash(), and cc.ws.GeoSvc.run().
simplify()
static double[] cc.util.Geo.simplify (double[] dPts, double dMaxStep) inline static
Definition at line 845 of file Geo.java.
    {
        double[] dRet = Arrays.newDoubleArray(Arrays.size(dPts) / 2);
        System.arraycopy(dPts, 1, dRet, 1, 4); // copy bounding box
        dRet[0] = 5;
        if (Arrays.size(dPts) < 15) // [ins, bb1, bb2, bb3, bb4, p1x, p1y, p1w, p2x, p2y, p2w, p3x, p3y, p3w]
        {
            double[] dPt = new double[3];
            Iterator<double[]> oIt = Arrays.iterator(dPts, dPt, 5, 3);
            while(oIt.hasNext())
            {
                oIt.next();
                dRet = Arrays.add(dRet, dPt);
            }
            return dRet;
        }
        double[] dSeg = new double[9];
        Iterator<double[]> oIt = Arrays.iterator(dPts, dSeg, 5, 3);
        dRet = Arrays.add(dRet, dPts[5], dPts[6]); // add first x,y
        dRet = Arrays.add(dRet, dPts[7]);  // add first w
        double[] dCenter = new double[2];
        double dH = dCenter[0];
        double dK = dCenter[1];
        int nCurIndex = 8;
        int nLastAdded = 5;
        while(oIt.hasNext())
        {
            oIt.next();
            double dR = Geo.circle(dSeg[0], dSeg[1], dSeg[3], dSeg[4], dSeg[6], dSeg[7], dCenter); // determine current segment is co-arc
            if (!Double.isFinite(dR) || dR >= 10000) // current segment is a line
            {
                if (Double.isFinite(dH)) // last segment was an arc, so finish it
                {
                    int nMidIndex = (nCurIndex - nLastAdded) / 3 / 2 * 3 + nLastAdded;
                    if (nMidIndex == nLastAdded)
                    {
                        dH = dCenter[0];
                        dK = dCenter[1];
                        nCurIndex += 3;
                        continue;
                    }
                    dRet = Arrays.add(dRet, dPts[nMidIndex], dPts[nMidIndex + 1]);
                    dRet = Arrays.add(dRet, dPts[nMidIndex + 2]);
                    dRet = Arrays.add(dRet, dSeg[3], dSeg[4]); // add last point of the arc
                    dRet = Arrays.add(dRet, dSeg[5]);
                    nLastAdded = nCurIndex;
                }
                dH = dK = Double.NaN; // reset the previous center, do not need to add a point for the current segment
            }
            else // current segment is not a line
            {
                if (!Double.isFinite(dH)) // last segment was a line, so finish it
                {
                    int nMidIndex = (nCurIndex - nLastAdded) / 3 / 2 * 3 + nLastAdded;
                    dRet = Arrays.add(dRet, dPts[nMidIndex], dPts[nMidIndex + 1]);
                    dRet = Arrays.add(dRet, dPts[nMidIndex + 2]);
                    nLastAdded = nCurIndex;
                }
                else // last segment was an arc
                {
                    if (Geo.distance(dH, dK, dCenter[0], dCenter[1]) < dMaxStep) // same center, so co-arc
                    {
                        nCurIndex += 3;
                        continue; // do nothing
                    }
                    else // last segment was not co-arc, so finish it
                    {
                        int nMidIndex = (nCurIndex - nLastAdded) / 3 / 2 * 3 + nLastAdded;
                        if (nMidIndex == nLastAdded)
{
                            dH = dCenter[0];
                            dK = dCenter[1];
                            nCurIndex += 3;
                            continue;
                        }
                        dRet = Arrays.add(dRet, dPts[nMidIndex], dPts[nMidIndex + 1]);
                        dRet = Arrays.add(dRet, dPts[nMidIndex + 2]);
                        nLastAdded = nCurIndex;
                    }
                }
                dRet = Arrays.add(dRet, dSeg[3], dSeg[4]); // add the last point of the previous segment
                dRet = Arrays.add(dRet, dSeg[5]);
                dH = dCenter[0];
                dK = dCenter[1];
            }
            nCurIndex += 3;
        }
        if (Double.isFinite(dH)) // finish the last segment, if the previous center is finite, it is an arc
        {
            int nMidIndex = (nCurIndex - nLastAdded) / 3 / 2 * 3 + nLastAdded;
            dRet = Arrays.add(dRet, dPts[nMidIndex], dPts[nMidIndex + 1]);
            dRet = Arrays.add(dRet, dPts[nMidIndex + 2]);
        }
        else // otherwise a line
        {
            int nMidIndex = (nCurIndex - nLastAdded) / 3 / 2 * 3 + nLastAdded;
            dRet = Arrays.add(dRet, dPts[nMidIndex], dPts[nMidIndex + 1]);
            dRet = Arrays.add(dRet, dPts[nMidIndex + 2]);
        }
        dRet = Arrays.add(dRet, dSeg[6], dSeg[7]); // add last x,y
        dRet = Arrays.add(dRet, dSeg[8]);
        return dRet;
    }
References cc.util.Arrays.add(), cc.util.Geo.circle(), cc.util.Geo.distance(), cc.util.Arrays.iterator(), cc.util.Arrays.newDoubleArray(), and cc.util.Arrays.size().
Referenced by cc.util.Geo.main().
sqDist()
static double cc.util.Geo.sqDist (double dXi, double dYi, double dXj, double dYj) inline static
Definition at line 89 of file Geo.java.
    {
        double dXd = dXj - dXi;
        double dYd = dYj - dYi;
        return dXd * dXd + dYd * dYd;
    }
Referenced by cc.ctrl.CtrlLineArcs.connects(), and cc.util.Geo.distance().
toIntDeg()
static int cc.util.Geo.toIntDeg (double dOrd) inline static
Definition at line 59 of file Geo.java.
    {
        return (int)(dOrd * 10000000.0);
    }
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ws.GeoLanes.doPost(), cc.ihp.IHPRequest.main(), cc.ctrl.CtrlGeo.readPtsLonLats(), cc.ctrl.TcBounds.setCorners(), cc.ctrl.proc.ProcDebug.writeGeoLanes(), and cc.rsm.RsmCollect.xmlFile().
toMeters()
static double cc.util.Geo.toMeters (int nOrd) inline static
Definition at line 65 of file Geo.java.
    {
        return ((double)nOrd) / 100.0;
    }
Referenced by cc.util.Geo.distance().
untwist()
static void cc.util.Geo.untwist (double[] dPoints) inline static
Parameters
dPoints Array of length 10 which is a closed polygon [x0, y0, x1, y1, x2, y2, x3, y3, x0, y0
Definition at line 1082 of file Geo.java.
    {
        double[] dInter = new double[2];
        MathUtil.getIntersection(dPoints[0], dPoints[1], dPoints[2], dPoints[3], dPoints[4], dPoints[5], dPoints[6], dPoints[7], dInter); // check edge 0-1 and edge 2-3 for intersection
        if (Double.isFinite(dInter[0]))
        {
            dInter[0] = dPoints[2]; // store swap point
            dInter[1] = dPoints[3];
            dPoints[2] = dPoints[4]; // swap points 1 and 2
            dPoints[3] = dPoints[5];
            dPoints[4] = dInter[0];
            dPoints[5] = dInter[1];
            return;
        }
        MathUtil.getIntersection(dPoints[0], dPoints[1], dPoints[6], dPoints[7], dPoints[2], dPoints[3], dPoints[4], dPoints[5], dInter); // check edge 0-3 and edge 1-2 for intersection
        if (Double.isFinite(dInter[0]))
        {
            dInter[0] = dPoints[4]; // store swap point
            dInter[1] = dPoints[5];
            dPoints[4] = dPoints[6]; // swap points 2 and 3
            dPoints[5] = dPoints[7];
            dPoints[6] = dInter[0];
            dPoints[7] = dInter[1];
        }
    }
References cc.util.MathUtil.getIntersection().
Referenced by cc.util.TestPath.main(), and cc.ws.TcmReqServlet.run().
updateBoundingBox()
static void cc.util.Geo.updateBoundingBox (double[] dUpdate, double[] dPts) inline static
Definition at line 964 of file Geo.java.
    {
        if (dPts[1] < dUpdate[1])
            dUpdate[1] = dPts[1];
        if (dPts[2] < dUpdate[2])
            dUpdate[2] = dPts[2];
        if (dPts[3] > dUpdate[3])
            dUpdate[3] = dPts[3];
        if (dPts[4] > dUpdate[4])
            dUpdate[4] = dPts[4];
    }
updateBounds()
static void cc.util.Geo.updateBounds (double dX, double dY, double[] dBounds) inline static
Definition at line 952 of file Geo.java.
    {
        if (dX < dBounds[0])
            dBounds[0] = dX;
        if (dY < dBounds[1])
            dBounds[1] = dY;
        if (dX > dBounds[2])
            dBounds[2] = dX;
        if (dY > dBounds[3])
            dBounds[3] = dY;
    }
Referenced by cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), and cc.ctrl.proc.ProcMaxSpeed.renderTiledData().
Member Data Documentation
CIRCLE_TOL
final double cc.util.Geo.CIRCLE_TOL = 0.001 static
Definition at line 20 of file Geo.java.
Referenced by cc.util.Geo.circle().
EARTH_FLATTENING
final double cc.util.Geo.EARTH_FLATTENING = EARTH_MINOR_RADIUS / EARTH_MAJOR_RADIUS static
Definition at line 19 of file Geo.java.
EARTH_MAJOR_RADIUS
final double cc.util.Geo.EARTH_MAJOR_RADIUS = 6378137.0 static
Definition at line 18 of file Geo.java.
EARTH_MINOR_RADIUS
final double cc.util.Geo.EARTH_MINOR_RADIUS = 6356752.0 static
Definition at line 17 of file Geo.java.
EARTH_RADIUS_KM
final double cc.util.Geo.EARTH_RADIUS_KM = 6371 static
Definition at line 22 of file Geo.java.
Referenced by cc.util.Geo.distanceFromLatLon().
M_TOL
final double cc.util.Geo.M_TOL = 1.0E-10 static
Definition at line 21 of file Geo.java.
PIOVER180
final double cc.util.Geo.PIOVER180 = Math.PI / 180 static
Definition at line 23 of file Geo.java.
Referenced by cc.util.Geo.distanceFromLatLon().
The documentation for this class was generated from the following file:
src/cc/util/Geo.java