Carma-cloud: cc.util.MathUtil Class Reference
cc.util.MathUtil Class Reference abstract
Static Public Member Functions
static void getIntersection (double dPx, double dPy, double dEnd1x, double dEnd1y, double dQx, double dQy, double dEnd2x, double dEnd2y, double[] dInter)
static double[] addIntersection (double[] dPoints, double dX1, double dY1, double dX2, double dY2, double[] dLonLats)
static double cross (double dVx, double dVy, double dWx, double dWy)
static int compareTol (double d1, double d2, double dTol)
static int compareTol (int n1, int n2, int nTol)
static double cubic (double dX, double dA, double dB, double dC, double dD)
static double normalizeRadians (double dRad)
static byte[] doubleToBytes (double dDouble, byte[] yBytes)
static byte[] longToBytes (long lLong, byte[] yBytes)
static byte[] intToBytes (int nInt, byte[] yBytes)
static int bytesToInt (byte[] yBytes)
static double round (double dVal, int nPlaces)
static void main (String[] s)
Static Public Attributes
static double TWOPI = Math.PI * 2
Detailed Description
Author
Federal Highway Administration
Definition at line 18 of file MathUtil.java.
Member Function Documentation
addIntersection()
static double[] cc.util.MathUtil.addIntersection (double[] dPoints, double dX1, double dY1, double dX2, double dY2, double[] dLonLats) inline static
Definition at line 47 of file MathUtil.java.
    {
        double[] dPoint = new double[2];
        getIntersection(dX1, dY1, dX2, dY2, dLonLats[0], dLonLats[1], dLonLats[0], dLonLats[3], dPoint); // check left edge
        if (!Double.isNaN(dPoint[0]))
            return Arrays.addAndUpdate(dPoints, dPoint[0], dPoint[1]);
        getIntersection(dX1, dY1, dX2, dY2, dLonLats[0], dLonLats[3], dLonLats[2], dLonLats[3], dPoint); // check top edge
        if (!Double.isNaN(dPoint[0]))
            return Arrays.addAndUpdate(dPoints, dPoint[0], dPoint[1]);
        getIntersection(dX1, dY1, dX2, dY2, dLonLats[2], dLonLats[3], dLonLats[2], dLonLats[1], dPoint); // check right edge
        if (!Double.isNaN(dPoint[0]))
            return Arrays.addAndUpdate(dPoints, dPoint[0], dPoint[1]);
        getIntersection(dX1, dY1, dX2, dY2, dLonLats[2], dLonLats[1], dLonLats[0], dLonLats[1], dPoint); // check bot edge
        if (!Double.isNaN(dPoint[0]))
            return Arrays.addAndUpdate(dPoints, dPoint[0], dPoint[1]);
        return dPoints; // no intersections
    }
References cc.util.Arrays.addAndUpdate(), and cc.util.MathUtil.getIntersection().
bytesToInt()
static int cc.util.MathUtil.bytesToInt (byte[] yBytes) inline static
Definition at line 152 of file MathUtil.java.
    {
        return ((yBytes[0] & 0xff) << 24) |
               ((yBytes[1] & 0xff) << 16) |
               ((yBytes[2] & 0xff) << 8) |
               ((yBytes[3] & 0xff));
    }
Referenced by cc.ws.WxPoly.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.TrafCtrlEnums.getCtrlValString(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcPavement.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.ws.CtrlTiles.saveEdit(), and cc.ctrl.TrafCtrl.writeJson().
compareTol() [1/2]
static int cc.util.MathUtil.compareTol (double d1, double d2, double dTol) inline static
Definition at line 76 of file MathUtil.java.
    {
        if (d2 > d1)
        {
            if (d2 - d1 > dTol)
                return -1;
        }
        else if (d1 - d2 > dTol)
            return 1;
        return 0;
    }
Referenced by cc.util.Geo.circle(), and cc.ctrl.CtrlLineArcs.connects().
compareTol() [2/2]
static int cc.util.MathUtil.compareTol (int n1, int n2, int nTol) inline static
Definition at line 89 of file MathUtil.java.
    {
        if (n2 > n1)
        {
            if (n2 - n1 > nTol)
                return -1;
        }
        else if (n1 - n2 > nTol)
            return 1;
        return 0;
    }
cross()
static double cc.util.MathUtil.cross (double dVx, double dVy, double dWx, double dWy) inline static
Definition at line 70 of file MathUtil.java.
    {
        return dVx * dWy - dVy * dWx;
    }
Referenced by cc.util.MathUtil.getIntersection().
cubic()
static double cc.util.MathUtil.cubic (double dX, double dA, double dB, double dC, double dD) inline static
Definition at line 102 of file MathUtil.java.
    {
        return dA + (dB * dX) + (dC * dX * dX) + (dD * dX * dX * dX);
    }
Referenced by cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.pvmt.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.xodr.pvmt.Arc.addLanePoints(), cc.geosrv.xodr.geo.Arc.addPoints(), cc.geosrv.xodr.geo.Line.addPoints(), cc.geosrv.xodr.pvmt.Arc.addPoints(), cc.geosrv.xodr.pvmt.Line.addPoints(), cc.geosrv.xodr.rdmk.Arc.addPoints(), and cc.geosrv.xodr.rdmk.Line.addPoints().
doubleToBytes()
static byte[] cc.util.MathUtil.doubleToBytes (double dDouble, byte[] yBytes) inline static
Definition at line 119 of file MathUtil.java.
    {
        long lLong = Double.doubleToLongBits(dDouble);
        return longToBytes(lLong, yBytes);
    }
References cc.util.MathUtil.longToBytes().
getIntersection()
static void cc.util.MathUtil.getIntersection (double dPx, double dPy, double dEnd1x, double dEnd1y, double dQx, double dQy, double dEnd2x, double dEnd2y, double[] dInter) inline static
Definition at line 23 of file MathUtil.java.
    {
        dInter[0] = Double.NaN;
        dInter[1] = Double.NaN;
        double dDeltaQPx = dQx - dPx;
        double dDeltaQPy = dQy - dPy;
        double dRx = dEnd1x - dPx;
        double dRy = dEnd1y - dPy;
        double dSx = dEnd2x - dQx;
        double dSy = dEnd2y - dQy;
        double dRCrossS = cross(dRx, dRy, dSx, dSy);
        if (dRCrossS == 0)
            return;
        double dT = cross(dDeltaQPx, dDeltaQPy, dSx, dSy) / dRCrossS;
        if (dT < 0 || dT > 1)
            return;
        double dU = cross(dDeltaQPx, dDeltaQPy, dRx, dRy) / dRCrossS;
        if (dU < 0 || dU > 1)
            return;
        dInter[0] = dPx + dT * dRx;
        dInter[1] = dPy + dT * dRy;
    }
References cc.util.MathUtil.cross().
Referenced by cc.util.MathUtil.addIntersection(), and cc.util.Geo.untwist().
intToBytes()
static byte[] cc.util.MathUtil.intToBytes (int nInt, byte[] yBytes) inline static
Definition at line 141 of file MathUtil.java.
    {
        yBytes[0] = (byte)(nInt >> 24);
        yBytes[1] = (byte)(nInt >> 16);
        yBytes[2] = (byte)(nInt >> 8);
        yBytes[3] = (byte)nInt;
        return yBytes;
    }
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), and cc.util.MathUtil.main().
longToBytes()
static byte[] cc.util.MathUtil.longToBytes (long lLong, byte[] yBytes) inline static
Definition at line 126 of file MathUtil.java.
    {
        yBytes[0] = (byte)(lLong >> 56);
        yBytes[1] = (byte)(lLong >> 48);
        yBytes[2] = (byte)(lLong >> 40);
        yBytes[3] = (byte)(lLong >> 32);
        yBytes[4] = (byte)(lLong >> 24);
        yBytes[5] = (byte)(lLong >> 16);
        yBytes[6] = (byte)(lLong >> 8);
        yBytes[7] = (byte)lLong;
        return yBytes;
    }
Referenced by cc.util.MathUtil.doubleToBytes().
main()
static void cc.util.MathUtil.main (String[] s) inline static
Definition at line 168 of file MathUtil.java.
    {
//      byte[] yBytes = new byte[]{0, 1, 0, 2};
//      ArrayList<String> sVals = new ArrayList();
//      TrafCtrlEnums.getCtrlValString("latperm", yBytes, sVals);
//      for (String sVal : sVals)
//          System.out.println(sVal);
        int nCount = 0;
        int nVal1 = 2;
        nVal1 <<= 16;
        nVal1 |= (1 & 0xff);
        int nVal2 = 1;
        nVal2 <<= 16;
        nVal2 |= (2 & 0xff);
        ArrayList<String> sVals = new ArrayList();
        byte[] yBytes = new byte[4];
        MathUtil.intToBytes(nVal2, yBytes);
        TrafCtrlEnums.getCtrlValString("latperm", yBytes, sVals);
        sVals.forEach(sVal -> System.out.println(sVal));
    }
References cc.ctrl.TrafCtrlEnums.getCtrlValString(), and cc.util.MathUtil.intToBytes().
normalizeRadians()
static double cc.util.MathUtil.normalizeRadians (double dRad) inline static
Definition at line 108 of file MathUtil.java.
    {
        if (dRad < 0)
            return dRad + Math.ceil(-dRad / TWOPI) * TWOPI;
        else if (dRad >= TWOPI)
            return dRad - Math.floor(dRad / TWOPI) * TWOPI;
        return dRad;
    }
References cc.util.MathUtil.TWOPI.
round()
static double cc.util.MathUtil.round (double dVal, int nPlaces) inline static
Definition at line 161 of file MathUtil.java.
    {
        BigDecimal dBd = new BigDecimal(Double.toString(dVal));
        dBd = dBd.setScale(nPlaces, RoundingMode.HALF_UP);
        return dBd.doubleValue();
    }
Referenced by cc.util.Geo.angle().
Member Data Documentation
TWOPI
double cc.util.MathUtil.TWOPI = Math.PI * 2 static
Definition at line 20 of file MathUtil.java.
Referenced by cc.util.MathUtil.normalizeRadians().
The documentation for this class was generated from the following file:
src/cc/util/MathUtil.java