Carma-cloud: cc.ctrl.proc.ProcCtrl Class Reference
cc.ctrl.proc.ProcCtrl Class Reference abstract
Public Member Functions
ProcCtrl (String sLineArcDir)
void parseMetadata (String sSource) throws Exception
abstract void parseMetadata (Path oSource) throws Exception
void process (String sLineArcsFile, double dTol) throws Exception
abstract ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Static Public Member Functions
static void setStaticVariables (double dStep, String sDir, String sTdFF, int nZoom)
static void updateTiles (ArrayList< int[]> oTiles, ArrayList< int[]> oCtrlTiles)
static void updateTileRange (int[] nTileIndices, int[] nTmpTiles)
static ArrayList< CtrlLineArcs > combineLaneByRoad (ArrayList< CtrlLineArcs > oLineArcs, double dTol)
static void writeIndexFile (ArrayList< TrafCtrl > oCtrls, int nX, int nY) throws IOException
static void updateIndex (String sIndexFile, TrafCtrl oCtrl, long lTimestamp) throws IOException
static void renderCtrls (String sCtrlType, ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
static boolean deleteControl (String sId) throws Exception
static boolean deleteControl (TrafCtrl oCtrl)
static ArrayList< TrafCtrl > getCurrentControls (int nCtrlType, double dMinLon, double dMinLat, double dMaxLon, double dMaxLat, boolean bLoadFullGeo)
Public Attributes
String m_sLineArcDir
Static Public Attributes
static final Object INDEXLOCK = new Object()
static double g_dExplodeStep
static String g_sTrafCtrlDir
static String g_sTdFileFormat
static String g_sGeolanesDir
static int g_nDefaultZoom = Integer.MIN_VALUE
static final byte CC = 0
static final byte RSM = 1
static final byte IHP2 = 2
Protected Member Functions
abstract void proc (String sLineArcsFile, double dTol) throws Exception
Static Protected Member Functions
static boolean checkTileRange (int[] nTileIndices)
Static Protected Attributes
static final double WIDTHTH = 1.5
static final double LENLOWTH = 75.0
static final double STOPLINEENDOFFSET = 0.6
static final double STOPLINELATOFFSET = 0.1
static double[][] NUMBERS
static Comparator< int[]> LANETYPECOMP
static final HashMap< String, double[]> CHARS = new HashMap()
Static Package Functions
[static initializer]
static double getCoordAndHeadingAtLength (double[] dPoints, double dLength, boolean bReverse, double[] dPoint)
static int getStopLine (TrafCtrl oCtrl, ArrayList< double[]> oStops)
Detailed Description
Author
aaron.cherney
Definition at line 40 of file ProcCtrl.java.
Constructor & Destructor Documentation
ProcCtrl()
cc.ctrl.proc.ProcCtrl.ProcCtrl (String sLineArcDir) inline
Definition at line 88 of file ProcCtrl.java.
    {
        m_sLineArcDir = sLineArcDir;
    }
References cc.ctrl.proc.ProcCtrl.m_sLineArcDir.
Member Function Documentation
[static initializer]()
cc.ctrl.proc.ProcCtrl.[static initializer] inline static package
checkTileRange()
static boolean cc.ctrl.proc.ProcCtrl.checkTileRange (int[] nTileIndices) inline static protected
Definition at line 123 of file ProcCtrl.java.
    {
        return (Math.abs(nTileIndices[2] - nTileIndices[0]) > 1000 || Math.abs(nTileIndices[3] - nTileIndices[1]) > 1000);
    }
combine()
abstract ArrayList< CtrlLineArcs > cc.ctrl.proc.ProcCtrl.combine (ArrayList< CtrlLineArcs > oLanes, double dTol) abstract
Reimplemented in cc.ctrl.proc.ProcClosed, cc.ctrl.proc.ProcClosing, cc.ctrl.proc.ProcDebug, cc.ctrl.proc.ProcDebugOutlines, cc.ctrl.proc.ProcDirection, cc.ctrl.proc.ProcHeadway, cc.ctrl.proc.ProcLatPerm, cc.ctrl.proc.ProcMaxPlatoonSize, cc.ctrl.proc.ProcMaxSpeed, cc.ctrl.proc.ProcMinPlatoonHdwy, cc.ctrl.proc.ProcOpening, cc.ctrl.proc.ProcPavement, cc.ctrl.proc.ProcSignal, cc.ctrl.proc.ProcStop, and cc.ctrl.proc.ProcYield.
combineLaneByRoad()
static ArrayList< CtrlLineArcs > cc.ctrl.proc.ProcCtrl.combineLaneByRoad (ArrayList< CtrlLineArcs > oLineArcs, double dTol) inline static
Definition at line 153 of file ProcCtrl.java.
    {
        Collections.sort(oLineArcs, CtrlLineArcs.CMPBYLANE);
        int nLastId = oLineArcs.get(0).m_nLaneId;
        ArrayList<CtrlLineArcs> oCombined = new ArrayList();
        ArrayList<CtrlLineArcs> oCurrRoad = new ArrayList();
        oCurrRoad.add(oLineArcs.get(0));
        double dSqTol = dTol * dTol;
        int nLimit = oLineArcs.size();
        for (int nIndex = 1; nIndex <= nLimit; nIndex++)
        {
            CtrlLineArcs oTemp = nIndex == nLimit ? null : oLineArcs.get(nIndex);
            if (oTemp == null || nLastId != oTemp.m_nLaneId)
            {
                CtrlLineArcs oRoad = oCurrRoad.get(0);
                boolean bDone = false;
                while (!bDone) // the order of the parts of the road are not guaranteed keep trying to combine parts until none are left
                {
                    bDone = true;
                    int nRoadIndex = oCurrRoad.size();
                    while (nRoadIndex-- > 1)
                    {
                        int nConnect = oRoad.connects(oCurrRoad.get(nRoadIndex), dSqTol);
                        if (nConnect > 0)
{
                            oRoad.combine(oCurrRoad.get(nRoadIndex), nConnect);
                            oCurrRoad.remove(nRoadIndex);
                            bDone = false;
                            break;
                        }
                    }
                }
                oCombined.add(oRoad);
                for (int nRoadIndex = 1; nRoadIndex < oCurrRoad.size(); nRoadIndex++) // if for some reason a part of the road didnt get combined, add the part so we don't lose geometry
                {
                    oCurrRoad.get(nRoadIndex).m_nLaneId = Integer.MIN_VALUE;
                    oCombined.add(oCurrRoad.get(nRoadIndex));
                }
                oCurrRoad.clear(); // start of new road
                if (oTemp != null)
                    nLastId = oTemp.m_nLaneId;
            }
            oCurrRoad.add(oTemp);
        }
        return oCombined;
    }
References cc.ctrl.CtrlLineArcs.CMPBYLANE, cc.ctrl.CtrlLineArcs.combine(), cc.ctrl.CtrlLineArcs.connects(), and cc.ctrl.CtrlLineArcs.m_nLaneId.
Referenced by cc.ctrl.proc.ProcDebug.combine(), cc.ctrl.proc.ProcDirection.combine(), cc.ctrl.proc.ProcMaxSpeed.combine(), cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcStop.combine(), cc.ctrl.proc.ProcYield.combine(), and cc.ws.CtrlTiles.splitLineArcs().
deleteControl() [1/2]
static boolean cc.ctrl.proc.ProcCtrl.deleteControl (String sId) throws Exception inline static
Definition at line 411 of file ProcCtrl.java.
    {
        String sFile = g_sTrafCtrlDir + sId + ".bin";
        TrafCtrl oOriginalCtrl;
        try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(Paths.get(sFile)))))
        {
            oOriginalCtrl = new TrafCtrl(oIn, true, true);
        }
        return deleteControl(oOriginalCtrl);
    }
References cc.ctrl.proc.ProcCtrl.deleteControl(), cc.ctrl.proc.ProcCtrl.g_sTrafCtrlDir, and cc.util.FileUtil.newInputStream().
Referenced by cc.ws.CtrlTiles.deleteControl(), and cc.ctrl.proc.ProcCtrl.deleteControl().
deleteControl() [2/2]
static boolean cc.ctrl.proc.ProcCtrl.deleteControl (TrafCtrl oCtrl) inline static
Definition at line 425 of file ProcCtrl.java.
    {
        synchronized (INDEXLOCK)
        {
            try
            {
                for (int[] nTile : oCtrl.m_oFullGeo.m_oTiles)
                {
                    String sIndex = String.format(g_sTdFileFormat, nTile[0], g_nDefaultZoom, nTile[0], nTile[1]) + ".ndx";
                    ProcCtrl.updateIndex(sIndex, oCtrl, System.currentTimeMillis() - 10);
                }
            }
            catch (Exception oEx)
            {
                oEx.printStackTrace();
                return false;
            }
        }
        return true;
    }
References cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTdFileFormat, cc.ctrl.proc.ProcCtrl.INDEXLOCK, cc.ctrl.TrafCtrl.m_oFullGeo, cc.ctrl.CtrlGeo.m_oTiles, and cc.ctrl.proc.ProcCtrl.updateIndex().
getCoordAndHeadingAtLength()
static double cc.ctrl.proc.ProcCtrl.getCoordAndHeadingAtLength (double[] dPoints, double dLength, boolean bReverse, double[] dPoint) inline static package
Definition at line 201 of file ProcCtrl.java.
    {
        double dTotalLen = 0.0;
        dPoint[0] = dPoint[1] = Double.NaN;
        double dHdg = Double.NaN;
        int nSegSize = 22;
        int nEndX = nSegSize - 2;
        int nEndY = nSegSize - 1;
        Iterator<double[]> oIt = Arrays.iterator(dPoints, new double[nSegSize], 5, nSegSize - 2);
        while (oIt.hasNext())
        {
            double[] dSeg = oIt.next();
            double dLen = Geo.distance(dSeg[0], dSeg[1], dSeg[nEndX], dSeg[nEndY]);
            dTotalLen += dLen;
            if (dTotalLen > dLength)
            {
                dPoint[0] = (dSeg[0] + dSeg[nEndX]) / 2;
                dPoint[1] = (dSeg[1] + dSeg[nEndY]) / 2;
                dHdg = Geo.heading(dSeg[0], dSeg[1], dSeg[nEndX], dSeg[nEndY]);
                break;
            }
        }
        if (!Double.isNaN(dHdg) && bReverse)
            dHdg -= Math.PI;
        return dHdg;
    }
References cc.util.Geo.distance(), cc.util.Geo.heading(), and cc.util.Arrays.iterator().
Referenced by cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), and cc.ctrl.proc.ProcMaxSpeed.renderTiledData().
getCurrentControls()
static ArrayList< TrafCtrl > cc.ctrl.proc.ProcCtrl.getCurrentControls (int nCtrlType, double dMinLon, double dMinLat, double dMaxLon, double dMaxLat, boolean bLoadFullGeo) inline static
Definition at line 447 of file ProcCtrl.java.
    {
        ArrayList<TrafCtrl> oCtrls = new ArrayList();
        try
        {
            long lNow = System.currentTimeMillis();
            Mercator oM = Mercator.getInstance();
            int[] nTiles = new int[2];
            oM.lonLatToTile(dMinLon, dMaxLat, g_nDefaultZoom, nTiles);
            int nStartX = nTiles[0];
            int nStartY = nTiles[1];
            oM.lonLatToTile(dMaxLon, dMinLat, g_nDefaultZoom, nTiles);
            double[] dMercBounds = new double[]{Mercator.lonToMeters(dMinLon), Mercator.latToMeters(dMinLat), Mercator.lonToMeters(dMaxLon), Mercator.latToMeters(dMaxLat)};
            ArrayList<byte[]> oIds = new ArrayList();
            for (int nX = nStartX; nX <= nTiles[0]; nX++)
            {
                for (int nY = nStartY; nY <= nTiles[1]; nY++)
                {
                    Path oIndexFile = Paths.get(String.format(g_sTdFileFormat, nX, g_nDefaultZoom, nX, nY) + ".ndx");
                    try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(oIndexFile))))
                    {
                        while (oIn.available() > 0)
{
                            CtrlIndex oIndex = new CtrlIndex(oIn);
                            if (nCtrlType == oIndex.m_nType || nCtrlType == Integer.MIN_VALUE && (oIndex.m_lStart >= lNow || oIndex.m_lEnd > lNow) && Geo.boundingBoxesIntersect(oIndex.m_dBB, dMercBounds))
                                oIds.add(oIndex.m_yId);
                        }
                    }
                }
            }
            Introsort.usort(oIds, TrafCtrl.ID_COMP);
            StringBuilder sIdBuf = new StringBuilder();
            byte[] yPrev = new byte[16];
            yPrev[0] = -1;
            for (byte[] yId : oIds)
            {
                if (TrafCtrl.ID_COMP.compare(yPrev, yId) == 0)
                    continue;
                yPrev = yId;
                TrafCtrl.getId(yId, sIdBuf);
                TrafCtrl oCtrl;
                Path oPath = Paths.get(g_sTrafCtrlDir + sIdBuf.toString() + ".bin");
                try (DataInputStream oCtrlIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(oPath))))
                {
                    oCtrl = new TrafCtrl(oCtrlIn, bLoadFullGeo, false);
                }
                if (oCtrl.m_yId[0] != ProcCtrl.CC)
                    continue;
                oCtrls.add(oCtrl);
            }
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
        }
        return oCtrls;
    }
References cc.util.Geo.boundingBoxesIntersect(), cc.ctrl.proc.ProcCtrl.CC, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTdFileFormat, cc.ctrl.proc.ProcCtrl.g_sTrafCtrlDir, cc.ctrl.TrafCtrl.getId(), cc.geosrv.Mercator.getInstance(), cc.ctrl.TrafCtrl.ID_COMP, cc.geosrv.Mercator.latToMeters(), cc.geosrv.Mercator.lonLatToTile(), cc.geosrv.Mercator.lonToMeters(), cc.ctrl.CtrlIndex.m_dBB, cc.ctrl.CtrlIndex.m_lEnd, cc.ctrl.CtrlIndex.m_lStart, cc.ctrl.CtrlIndex.m_nType, cc.ctrl.CtrlIndex.m_yId, cc.ctrl.TrafCtrl.m_yId, cc.util.FileUtil.newInputStream(), and cc.util.Introsort.usort().
getStopLine()
static int cc.ctrl.proc.ProcCtrl.getStopLine (TrafCtrl oCtrl, ArrayList< double[]> oStops) inline static package
Definition at line 230 of file ProcCtrl.java.
    {
        double[] dStop = Arrays.newDoubleArray(8);
        double[] dPT = oCtrl.m_oFullGeo.m_dPT;
        double[] dNT = oCtrl.m_oFullGeo.m_dNT;
        double[] dC = oCtrl.m_oFullGeo.m_dC;
        int nIndex = Arrays.size(dC) - 2;
        double dAngle = Geo.heading(dPT[nIndex], dPT[nIndex + 1], dC[nIndex], dC[nIndex + 1]);
        dStop = Arrays.add(dStop, dPT[nIndex] + Math.cos(dAngle) * STOPLINELATOFFSET, dPT[nIndex + 1] + Math.sin(dAngle) * STOPLINELATOFFSET);
        dAngle += Math.PI;
        dStop = Arrays.add(dStop, dNT[nIndex] + Math.cos(dAngle) * STOPLINELATOFFSET, dNT[nIndex + 1] + Math.sin(dAngle) * STOPLINELATOFFSET);
        nIndex -= 2;
        double dLen = 0.0;
        while (dLen < STOPLINEENDOFFSET && nIndex > 3)
        {
            double dX1 = dC[nIndex];
            double dY1 = dC[nIndex + 1];
            double dX2 = dC[nIndex + 2];
            double dY2 = dC[nIndex + 3];
            dLen += Geo.distance(dX1, dY1, dX2, dY2);
            nIndex -= 2;
        }
        dAngle = Geo.heading(dNT[nIndex], dNT[nIndex + 1], dC[nIndex], dC[nIndex + 1]);
        dStop = Arrays.add(dStop, dNT[nIndex] + Math.cos(dAngle) * STOPLINELATOFFSET, dNT[nIndex + 1] + Math.sin(dAngle) * STOPLINELATOFFSET);
        dAngle -= Math.PI;
        dStop = Arrays.add(dStop, dPT[nIndex] + Math.cos(dAngle) * STOPLINELATOFFSET, dPT[nIndex + 1] + Math.sin(dAngle) * STOPLINELATOFFSET);
        oStops.add(dStop);
        return nIndex;
    }
References cc.util.Arrays.add(), cc.util.Geo.distance(), cc.util.Geo.heading(), cc.ctrl.CtrlGeo.m_dC, cc.ctrl.CtrlGeo.m_dNT, cc.ctrl.CtrlGeo.m_dPT, cc.ctrl.TrafCtrl.m_oFullGeo, cc.util.Arrays.newDoubleArray(), cc.util.Arrays.size(), and cc.ctrl.proc.ProcCtrl.STOPLINELATOFFSET.
Referenced by cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), and cc.ctrl.proc.ProcYield.renderTiledData().
parseMetadata() [1/2]
abstract void cc.ctrl.proc.ProcCtrl.parseMetadata (Path oSource) throws Exception abstract
Reimplemented in cc.ctrl.proc.ProcClosed, cc.ctrl.proc.ProcClosing, cc.ctrl.proc.ProcDebug, cc.ctrl.proc.ProcDebugOutlines, cc.ctrl.proc.ProcDirection, cc.ctrl.proc.ProcHeadway, cc.ctrl.proc.ProcLatPerm, cc.ctrl.proc.ProcMaxPlatoonSize, cc.ctrl.proc.ProcMaxSpeed, cc.ctrl.proc.ProcMinPlatoonHdwy, cc.ctrl.proc.ProcOpening, cc.ctrl.proc.ProcPavement, cc.ctrl.proc.ProcSignal, cc.ctrl.proc.ProcStop, and cc.ctrl.proc.ProcYield.
parseMetadata() [2/2]
void cc.ctrl.proc.ProcCtrl.parseMetadata (String sSource) throws Exception inline
Definition at line 94 of file ProcCtrl.java.
    {
        parseMetadata(Paths.get(sSource));
    }
References cc.ctrl.proc.ProcCtrl.parseMetadata().
Referenced by cc.ctrl.proc.ProcCtrl.parseMetadata().
proc()
abstract void cc.ctrl.proc.ProcCtrl.proc (String sLineArcsFile, double dTol) throws Exception abstract protected
Reimplemented in cc.ctrl.proc.ProcClosed, cc.ctrl.proc.ProcClosing, cc.ctrl.proc.ProcDebug, cc.ctrl.proc.ProcDebugOutlines, cc.ctrl.proc.ProcDirection, cc.ctrl.proc.ProcHeadway, cc.ctrl.proc.ProcLatPerm, cc.ctrl.proc.ProcMaxPlatoonSize, cc.ctrl.proc.ProcMaxSpeed, cc.ctrl.proc.ProcMinPlatoonHdwy, cc.ctrl.proc.ProcOpening, cc.ctrl.proc.ProcPavement, cc.ctrl.proc.ProcSignal, cc.ctrl.proc.ProcStop, and cc.ctrl.proc.ProcYield.
Referenced by cc.ctrl.proc.ProcCtrl.process().
process()
void cc.ctrl.proc.ProcCtrl.process (String sLineArcsFile, double dTol) throws Exception inline
Definition at line 101 of file ProcCtrl.java.
    {
        if (g_nDefaultZoom == Integer.MIN_VALUE)
            throw new Exception("Static variables not initialized.");
        proc(sLineArcsFile, dTol);
    }
References cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, and cc.ctrl.proc.ProcCtrl.proc().
renderCtrls()
static void cc.ctrl.proc.ProcCtrl.renderCtrls (String sCtrlType, ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException inline static
Definition at line 318 of file ProcCtrl.java.
    {
        switch (sCtrlType)
        {
            case "signal":
            {
                ProcSignal.renderTiledData(oCtrls, nTiles);
                break;
            }
            case "stop":
            {
                ProcStop.renderTiledData(oCtrls, nTiles);
                break;
            }
            case "yield":
            {
                ProcYield.renderTiledData(oCtrls, nTiles);
                break;
            }
//          case "notowing":
//              break;
//          case "restricted":
//              break;
            case "closed":
            {
                ProcClosed.renderTiledData(oCtrls, nTiles);
                break;
            }
//          case "chains":
//              break;
            case "direction":
            {
                ProcDirection.renderTiledData(oCtrls, nTiles);
                break;
            }
//          case "lataffinity":
//              break;
            case "latperm":
            {
                ProcLatPerm.renderTiledData(oCtrls, nTiles, new int[]{2, 4, 4});
                break;
            }
            case "opening":
            {
                ProcOpening.renderTiledData(oCtrls, nTiles);
                break;
            }
            case "closing":
            {
                ProcClosing.renderTiledData(oCtrls, nTiles);
                break;
            }
//          case "parking":
//              break;
//          case "minspeed":
//              break;
            case "maxspeed":
            {
                ProcMaxSpeed.renderTiledData(oCtrls, nTiles);
                break;
            }
            case "minhdwy":
            {
                ProcHeadway.renderTiledData(oCtrls, nTiles);
                break;
            }
//          case "maxvehmass":
//              break;
//          case "maxvehheight":
//              break;
//          case "maxvehwidth":
//              break;
//          case "maxvehlength":
//              break;
//          case "maxaxles":
//              break;
//          case "minvehocc":
//              break;
            case "minplatoonhdwy":
            {
                ProcMinPlatoonHdwy.renderTiledData(oCtrls, nTiles);
                break;
            }
            case "maxplatoonsize":
            {
                ProcMaxPlatoonSize.renderTiledData(oCtrls, nTiles);
                break;
            }
        }
    }
References cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxPlatoonSize.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcMinPlatoonHdwy.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), and cc.ctrl.proc.ProcClosing.renderTiledData().
Referenced by cc.ws.CtrlTiles.addControl(), cc.ihp.IHP.execute(), and cc.ws.CtrlTiles.saveEdit().
setStaticVariables()
static void cc.ctrl.proc.ProcCtrl.setStaticVariables (double dStep, String sDir, String sTdFF, int nZoom) inline static
Definition at line 113 of file ProcCtrl.java.
    {
        g_dExplodeStep = dStep;
        g_sTrafCtrlDir = sDir;
        g_sTdFileFormat = sTdFF;
        g_nDefaultZoom = nZoom;
        g_sGeolanesDir = sTdFF.substring(0, sTdFF.indexOf("/td/") + 1) + "geolanes";
    }
References cc.ctrl.proc.ProcCtrl.g_dExplodeStep, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sGeolanesDir, cc.ctrl.proc.ProcCtrl.g_sTdFileFormat, and cc.ctrl.proc.ProcCtrl.g_sTrafCtrlDir.
Referenced by cc.ws.CtrlTiles.init(), and cc.ctrl.RenderCtrl.main().
updateIndex()
static void cc.ctrl.proc.ProcCtrl.updateIndex (String sIndexFile, TrafCtrl oCtrl, long lTimestamp) throws IOException inline static
Definition at line 288 of file ProcCtrl.java.
    {
        Path oIndexFile = Paths.get(sIndexFile);
        int nPos = 0;
        byte[] yIdBuf = new byte[16];
        long lSize = Files.size(oIndexFile);
        try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(oIndexFile))))
        {
            while (oIn.available() > 0)
            {
                oIn.skipBytes(4); // skip type (int)
                oIn.read(yIdBuf);
                if (TrafCtrl.ID_COMP.compare(yIdBuf, oCtrl.m_yId) == 0)
                    break;
                oIn.skipBytes(32); // skip both timestamps (2 longs) and bounding box (4 ints)
                nPos += 52;
            }
        }
        if (nPos >= lSize)
            throw new IOException("Id not found");
        try (RandomAccessFile oRaf = new RandomAccessFile(sIndexFile, "rw"))
        {
            oRaf.seek(nPos + 28); // want to edit the end timestamp, so seek to the record position and skip type(4) id(16) startts(8)
            oRaf.writeLong(lTimestamp);
        }
    }
References cc.ctrl.TrafCtrl.ID_COMP, and cc.util.FileUtil.newInputStream().
Referenced by cc.rsm.RsmCollect.RsmRecord.cleanup(), cc.ctrl.proc.ProcCtrl.deleteControl(), cc.ctrl.RenderCtrl.main(), and cc.ws.CtrlTiles.saveEdit().
updateTileRange()
static void cc.ctrl.proc.ProcCtrl.updateTileRange (int[] nTileIndices, int[] nTmpTiles) inline static
Definition at line 140 of file ProcCtrl.java.
    {
        if (nTmpTiles[0] < nTileIndices[0])
            nTileIndices[0] = nTmpTiles[0];
        if (nTmpTiles[1] < nTileIndices[1])
            nTileIndices[1] = nTmpTiles[1];
        if (nTmpTiles[2] > nTileIndices[2])
            nTileIndices[2] = nTmpTiles[2];
        if (nTmpTiles[3] > nTileIndices[3])
            nTileIndices[3] = nTmpTiles[3];
    }
updateTiles()
static void cc.ctrl.proc.ProcCtrl.updateTiles (ArrayList< int[]> oTiles, ArrayList< int[]> oCtrlTiles) inline static
Definition at line 129 of file ProcCtrl.java.
    {
        for (int[] nCtrlTile : oCtrlTiles)
        {
            int nIndex = Collections.binarySearch(oTiles, nCtrlTile, Mercator.TILECOMP);
            if (nIndex < 0)
                oTiles.add(~nIndex, nCtrlTile);
        }
    }
References cc.geosrv.Mercator.TILECOMP.
Referenced by cc.ctrl.CreateCtrls.createCtrl(), cc.ws.WxPoly.doPost(), cc.ihp.IHP.execute(), cc.ctrl.RenderCtrl.main(), cc.ctrl.proc.ProcClosed.proc(), cc.ctrl.proc.ProcClosing.proc(), cc.ctrl.proc.ProcDebug.proc(), cc.ctrl.proc.ProcDebugOutlines.proc(), cc.ctrl.proc.ProcDirection.proc(), cc.ctrl.proc.ProcLatPerm.proc(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ctrl.proc.ProcOpening.proc(), cc.ctrl.proc.ProcPavement.proc(), cc.ctrl.proc.ProcSignal.proc(), cc.ctrl.proc.ProcStop.proc(), cc.ctrl.proc.ProcYield.proc(), and cc.ws.CtrlTiles.splitLineArcs().
writeIndexFile()
static void cc.ctrl.proc.ProcCtrl.writeIndexFile (ArrayList< TrafCtrl > oCtrls, int nX, int nY) throws IOException inline static
Definition at line 262 of file ProcCtrl.java.
    {
        ArrayList<TrafCtrl> oToWrite = new ArrayList();
        double[] dClipBounds = TileUtil.getClippingBounds(g_nDefaultZoom, nX, nY);
        for (TrafCtrl oCtrl : oCtrls)
        {
            if (!Geo.boundingBoxesIntersect(oCtrl.m_oFullGeo.m_dBB, dClipBounds))
                continue;
            if (TileUtil.includeInTile(oCtrl.m_oFullGeo, dClipBounds))
                oToWrite.add(oCtrl);
        }
        if (oToWrite.isEmpty())
            return;
        try (DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(String.format(g_sTdFileFormat, nX, g_nDefaultZoom, nX, nY) + ".ndx"), FileUtil.APPENDTO, FileUtil.FILEPERS))))
        {
            for (TrafCtrl oCtrl : oToWrite)
            {
                oCtrl.writeIndex(oOut);
            }
        }
    }
References cc.util.FileUtil.APPENDTO, cc.util.Geo.boundingBoxesIntersect(), cc.util.FileUtil.FILEPERS, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTdFileFormat, cc.util.TileUtil.getClippingBounds(), cc.util.TileUtil.includeInTile(), and cc.util.FileUtil.newOutputStream().
Referenced by cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.ctrl.proc.ProcDebugOutlines.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxPlatoonSize.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcMinPlatoonHdwy.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcPavement.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), and cc.ctrl.proc.ProcClosing.renderTiledData().
Member Data Documentation
CC
final byte cc.ctrl.proc.ProcCtrl.CC = 0 static
Definition at line 48 of file ProcCtrl.java.
Referenced by cc.ws.CtrlTiles.addControl(), cc.ctrl.CreateCtrls.createCtrl(), cc.ws.WxPoly.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcCtrl.getCurrentControls(), cc.ctrl.RenderCtrl.main(), cc.ctrl.proc.ProcClosed.proc(), cc.ctrl.proc.ProcClosing.proc(), cc.ctrl.proc.ProcDebug.proc(), cc.ctrl.proc.ProcDebugOutlines.proc(), cc.ctrl.proc.ProcDirection.proc(), cc.ctrl.proc.ProcLatPerm.proc(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ctrl.proc.ProcOpening.proc(), cc.ctrl.proc.ProcPavement.proc(), cc.ctrl.proc.ProcSignal.proc(), cc.ctrl.proc.ProcStop.proc(), cc.ctrl.proc.ProcYield.proc(), cc.ws.CtrlTiles.saveEdit(), and cc.ws.CtrlTiles.splitLineArcs().
CHARS
final HashMap<String, double[]> cc.ctrl.proc.ProcCtrl.CHARS = new HashMap() static protected
Definition at line 72 of file ProcCtrl.java.
Referenced by cc.ctrl.proc.ProcHeadway.renderTiledData(), and cc.ctrl.proc.ProcMaxSpeed.renderTiledData().
g_dExplodeStep
double cc.ctrl.proc.ProcCtrl.g_dExplodeStep static
Definition at line 43 of file ProcCtrl.java.
Referenced by cc.ws.CtrlTiles.addControl(), cc.ctrl.CreateCtrls.createCtrl(), cc.ws.WxPoly.doPost(), cc.ihp.IHP.execute(), cc.ws.TcmReqServlet.init(), cc.ctrl.TrafCtrl.preparePoints(), cc.ctrl.proc.ProcClosed.proc(), cc.ctrl.proc.ProcClosing.proc(), cc.ctrl.proc.ProcDebug.proc(), cc.ctrl.proc.ProcDebugOutlines.proc(), cc.ctrl.proc.ProcDirection.proc(), cc.ctrl.proc.ProcLatPerm.proc(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ctrl.proc.ProcOpening.proc(), cc.ctrl.proc.ProcPavement.proc(), cc.ctrl.proc.ProcSignal.proc(), cc.ctrl.proc.ProcStop.proc(), cc.ctrl.proc.ProcYield.proc(), cc.ws.CtrlTiles.saveEdit(), cc.ctrl.proc.ProcCtrl.setStaticVariables(), and cc.ws.CtrlTiles.splitLineArcs().
g_nDefaultZoom
int cc.ctrl.proc.ProcCtrl.g_nDefaultZoom = Integer.MIN_VALUE static
Definition at line 47 of file ProcCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ws.CtrlTiles.addControl(), cc.rsm.RsmCollect.RsmRecord.cleanup(), cc.ctrl.CreateCtrls.createCtrl(), cc.ctrl.proc.ProcCtrl.deleteControl(), cc.ihp.IHP.execute(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcCtrl.getCurrentControls(), cc.ctrl.proc.ProcClosed.proc(), cc.ctrl.proc.ProcClosing.proc(), cc.ctrl.proc.ProcDebug.proc(), cc.ctrl.proc.ProcDebugOutlines.proc(), cc.ctrl.proc.ProcDirection.proc(), cc.ctrl.proc.ProcLatPerm.proc(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ctrl.proc.ProcOpening.proc(), cc.ctrl.proc.ProcPavement.proc(), cc.ctrl.proc.ProcSignal.proc(), cc.ctrl.proc.ProcStop.proc(), cc.ctrl.proc.ProcYield.proc(), cc.ctrl.proc.ProcCtrl.process(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.ctrl.proc.ProcDebugOutlines.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcPavement.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.ws.CtrlTiles.saveEdit(), cc.ctrl.proc.ProcCtrl.setStaticVariables(), cc.ws.CtrlTiles.splitLineArcs(), and cc.ctrl.proc.ProcCtrl.writeIndexFile().
g_sGeolanesDir
String cc.ctrl.proc.ProcCtrl.g_sGeolanesDir static
Definition at line 46 of file ProcCtrl.java.
Referenced by cc.ctrl.proc.ProcCtrl.setStaticVariables(), and cc.ctrl.proc.ProcDebug.writeGeoLanes().
g_sTdFileFormat
String cc.ctrl.proc.ProcCtrl.g_sTdFileFormat static
Definition at line 45 of file ProcCtrl.java.
Referenced by cc.rsm.RsmCollect.RsmRecord.cleanup(), cc.ctrl.proc.ProcCtrl.deleteControl(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcCtrl.getCurrentControls(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.ctrl.proc.ProcDebugOutlines.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxPlatoonSize.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcMinPlatoonHdwy.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcPavement.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.ctrl.proc.ProcCtrl.setStaticVariables(), and cc.ctrl.proc.ProcCtrl.writeIndexFile().
g_sTrafCtrlDir
String cc.ctrl.proc.ProcCtrl.g_sTrafCtrlDir static
Definition at line 44 of file ProcCtrl.java.
Referenced by cc.ws.CtrlTiles.addControl(), cc.ctrl.CreateCtrls.createCtrl(), cc.ctrl.proc.ProcCtrl.deleteControl(), cc.ihp.IHP.execute(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcCtrl.getCurrentControls(), cc.ctrl.proc.ProcClosed.proc(), cc.ctrl.proc.ProcClosing.proc(), cc.ctrl.proc.ProcDebug.proc(), cc.ctrl.proc.ProcDebugOutlines.proc(), cc.ctrl.proc.ProcDirection.proc(), cc.ctrl.proc.ProcLatPerm.proc(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ctrl.proc.ProcOpening.proc(), cc.ctrl.proc.ProcPavement.proc(), cc.ctrl.proc.ProcSignal.proc(), cc.ctrl.proc.ProcStop.proc(), cc.ctrl.proc.ProcYield.proc(), cc.ws.CtrlTiles.saveEdit(), cc.ctrl.proc.ProcCtrl.setStaticVariables(), and cc.ws.CtrlTiles.splitLineArcs().
IHP2
final byte cc.ctrl.proc.ProcCtrl.IHP2 = 2 static
Definition at line 50 of file ProcCtrl.java.
Referenced by cc.ihp.IHP.execute(), and cc.ihp.IHP.generateSpeedControls().
INDEXLOCK
final Object cc.ctrl.proc.ProcCtrl.INDEXLOCK = new Object() static
Definition at line 42 of file ProcCtrl.java.
Referenced by cc.ctrl.proc.ProcCtrl.deleteControl().
LANETYPECOMP
Comparator<int[]> cc.ctrl.proc.ProcCtrl.LANETYPECOMP static protected
Initial value:
= (int[] n1, int[] n2) ->
    {
        return Integer.compare(n1[0], n2[0]);
    }
Definition at line 68 of file ProcCtrl.java.
LENLOWTH
final double cc.ctrl.proc.ProcCtrl.LENLOWTH = 75.0 static protected
Definition at line 52 of file ProcCtrl.java.
Referenced by cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), and cc.ctrl.proc.ProcMaxSpeed.renderTiledData().
m_sLineArcDir
String cc.ctrl.proc.ProcCtrl.m_sLineArcDir
Definition at line 86 of file ProcCtrl.java.
Referenced by cc.ctrl.proc.ProcCtrl.ProcCtrl().
NUMBERS
double [][] cc.ctrl.proc.ProcCtrl.NUMBERS static protected
Initial value:
= new double[][]
    {
        new double[]{-0.1, 0.3, 0.1, 0.3, 0.2, 0.2, 0.2, -0.2, 0.1, -0.3, -0.1, -0.3, -0.2, -0.2, -0.2, 0.2, -0.1, 0.3},
        new double[]{-0.1, 0.2, 0.0, 0.3, 0.0, -0.3, -0.1, -0.3, 0.1, -0.3},
        new double[]{-0.2, 0.2, -0.1, 0.3, 0.1, 0.3, 0.2, 0.2, 0.2, 0.1, 0.1, 0.0, -0.1, 0.0, -0.2, -0.1, -0.2, -0.3, 0.2, -0.3},
        new double[]{-0.2, 0.2, -0.1, 0.3, 0.1, 0.3, 0.2, 0.2, 0.2, 0.1, 0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.2, -0.1, 0.2, -0.2, 0.1, -0.3, -0.1, -0.3, -0.2, -0.2},
        new double[]{0.2, -0.1, -0.2, -0.1, -0.2, 0.0, 0.1, 0.3, 0.1, -0.3},
        new double[]{0.2, 0.3, -0.2, 0.3, -0.2, 0.0, 0.1, 0.0, 0.2, -0.1, 0.2, -0.2, 0.1, -0.3, -0.2, -0.3},
        new double[]{0.1, 0.3, 0.0, 0.3, -0.2, 0.1, -0.2, -0.2, -0.1, -0.3, 0.1, -0.3, 0.2, -0.2, 0.2, -0.1, 0.1, 0.0, -0.2, 0.0},
        new double[]{-0.2, 0.3, 0.2, 0.3, 0.2, 0.2, 0.0, 0.0, -0.1, -0.2, -0.1, -0.3},
        new double[]{-0.1, 0.0, -0.2, 0.1, -0.2, 0.2, -0.1, 0.3, 0.1, 0.3, 0.2, 0.2, 0.2, 0.1, 0.1, 0.0, 0.2, -0.1, 0.2, -0.2, 0.1, -0.3, -0.1, -0.3, -0.2, -0.2, -0.2, -0.1, -0.1, 0.0, 0.1, 0.0},
        new double[]{0.2, 0.0, -0.1, 0.0, -0.2, 0.1, -0.2, 0.2, -0.1, 0.3, 0.1, 0.3, 0.2, 0.2, 0.2, -0.1, 0.0, -0.3, -0.1, -0.3}
    }
Definition at line 55 of file ProcCtrl.java.
Referenced by cc.ctrl.proc.ProcHeadway.renderTiledData(), and cc.ctrl.proc.ProcMaxSpeed.renderTiledData().
RSM
final byte cc.ctrl.proc.ProcCtrl.RSM = 1 static
Definition at line 49 of file ProcCtrl.java.
Referenced by cc.rsm.RsmParser.parseRequest().
STOPLINEENDOFFSET
final double cc.ctrl.proc.ProcCtrl.STOPLINEENDOFFSET = 0.6 static protected
Definition at line 53 of file ProcCtrl.java.
STOPLINELATOFFSET
final double cc.ctrl.proc.ProcCtrl.STOPLINELATOFFSET = 0.1 static protected
Definition at line 54 of file ProcCtrl.java.
Referenced by cc.ctrl.proc.ProcCtrl.getStopLine().
WIDTHTH
final double cc.ctrl.proc.ProcCtrl.WIDTHTH = 1.5 static protected
Definition at line 51 of file ProcCtrl.java.
Referenced by cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), and cc.ctrl.proc.ProcLatPerm.renderTiledData().
The documentation for this class was generated from the following file:
src/cc/ctrl/proc/ProcCtrl.java