Carma-cloud: cc.ihp.IHPRequest Class Reference
cc.ihp.IHPRequest Class Reference
Public Member Functions
IHPRequest ()
IHPRequest (InputStream oIn)
void sendRequest ()
Static Public Member Functions
static void main (String[] sArgs) throws Exception
Package Attributes
String m_sRequestId
String m_sDeviceId
String m_sDeviceType
ArrayList< int[]> m_oGeometry = new ArrayList()
Detailed Description
Author
aaron.cherney
Definition at line 25 of file IHPRequest.java.
Constructor & Destructor Documentation
IHPRequest() [1/2]
cc.ihp.IHPRequest.IHPRequest () inline
Definition at line 51 of file IHPRequest.java.
    {
    }
Referenced by cc.ihp.IHPRequest.main().
IHPRequest() [2/2]
cc.ihp.IHPRequest.IHPRequest (InputStream oIn) inline
Parameters
in
Definition at line 60 of file IHPRequest.java.
    {
        JSONObject oRequest = new JSONObject(new JSONTokener(oIn));
        JSONObject oInfo = oRequest.getJSONObject("general_info");
        m_sRequestId = oInfo.optString("request_id", null);
        m_sDeviceId = oInfo.optString("device_id", null);
        m_sDeviceType = oInfo.optString("device_type", null);
        JSONArray oLayers = oRequest.getJSONArray("layer_request");
        for (int nIndex = 0; nIndex < oLayers.length(); nIndex++)
        {
            JSONObject oLayer = oLayers.getJSONObject(nIndex);
        }
    }
References cc.ihp.IHPRequest.m_sDeviceId, cc.ihp.IHPRequest.m_sDeviceType, and cc.ihp.IHPRequest.m_sRequestId.
Member Function Documentation
main()
static void cc.ihp.IHPRequest.main (String[] sArgs) throws Exception inline static
Parameters
sArgs
Exceptions
Exception
Definition at line 116 of file IHPRequest.java.
    {
        IHPRequest oReq = new IHPRequest();
        oReq.m_sDeviceId = "CARMA_CLOUD";
        oReq.m_sDeviceType = "carma-cloud";
        oReq.m_sRequestId = "9db9df03-09cb-4a0a-bcb1-ff751f32a6dd";
        int[] nGeo = Arrays.newIntArray();
        try (BufferedReader oIn = Files.newBufferedReader(Paths.get("C:/Users/aaron.cherney/Documents/IMRCP/stlouis.geojson"), StandardCharsets.UTF_8))
        {
            JSONArray oThing = new JSONArray(new JSONTokener(oIn)).getJSONObject(0).getJSONObject("geometry").getJSONArray("coordinates").getJSONArray(0);
            for (int nIndex = 0; nIndex < oThing.length(); nIndex++)
            {
                double dLon = oThing.getJSONArray(nIndex).getDouble(0);
                double dLat = oThing.getJSONArray(nIndex).getDouble(1);
                nGeo = Arrays.add(nGeo, Geo.toIntDeg(dLon), Geo.toIntDeg(dLat));
            }
        }
        oReq.m_oGeometry = new ArrayList();
        oReq.m_oGeometry.add(nGeo);
        oReq.sendRequest();
    }
References cc.ihp.IHPRequest.IHPRequest(), cc.util.Arrays.add(), cc.ihp.IHPRequest.m_oGeometry, cc.util.Arrays.newIntArray(), cc.ihp.IHPRequest.sendRequest(), and cc.util.Geo.toIntDeg().
sendRequest()
void cc.ihp.IHPRequest.sendRequest () inline
Definition at line 77 of file IHPRequest.java.
    {
        JSONObject oRequest = new JSONObject();
        JSONObject oInfo = new JSONObject();
        oInfo.put("request_id", m_sRequestId);
        oInfo.put("device_id", m_sDeviceId);
        oInfo.put("device_type", m_sDeviceType);
        oRequest.put("general_info", oInfo);
        JSONArray oLayerRequests = new JSONArray();
        JSONObject oDataLayer = new JSONObject();
        oDataLayer.put("layer", "mvd-data");
        JSONObject oRegion = new JSONObject();
        oRegion.put("type", "polygons");
        JSONArray oPolygons = new JSONArray();
        for (int nIndex = 0; nIndex < m_oGeometry.size(); nIndex++)
        {
            JSONArray oRing = new JSONArray();
            int[] nRing = m_oGeometry.get(nIndex);
            Iterator<int[]> oIt = Arrays.iterator(nRing, new int[2], 1, 2);
            while (oIt.hasNext())
            {
                int[] nPt = oIt.next();
                oRing.put(new JSONArray(new double[]{Geo.fromIntDeg(nPt[0]), Geo.fromIntDeg(nPt[1])}));
            }
            oPolygons.put(oRing);
        }
        oRegion.put("polygons", oPolygons);
        oDataLayer.put("region", oRegion);
        oLayerRequests.put(oDataLayer);
        oRequest.put("layer_requests", oLayerRequests);
        System.out.print(oRequest.toString(2));
    }
References cc.util.Geo.fromIntDeg(), cc.util.Arrays.iterator(), cc.ihp.IHPRequest.m_oGeometry, cc.ihp.IHPRequest.m_sDeviceId, cc.ihp.IHPRequest.m_sDeviceType, and cc.ihp.IHPRequest.m_sRequestId.
Referenced by cc.ihp.IHPRequest.main().
Member Data Documentation
m_oGeometry
ArrayList<int[]> cc.ihp.IHPRequest.m_oGeometry = new ArrayList() package
Request geometry
Definition at line 46 of file IHPRequest.java.
Referenced by cc.ihp.IHPRequest.main(), and cc.ihp.IHPRequest.sendRequest().
m_sDeviceId
String cc.ihp.IHPRequest.m_sDeviceId package
Device identifier
Definition at line 36 of file IHPRequest.java.
Referenced by cc.ihp.IHPRequest.IHPRequest(), and cc.ihp.IHPRequest.sendRequest().
m_sDeviceType
String cc.ihp.IHPRequest.m_sDeviceType package
Device type
Definition at line 41 of file IHPRequest.java.
Referenced by cc.ihp.IHPRequest.IHPRequest(), and cc.ihp.IHPRequest.sendRequest().
m_sRequestId
String cc.ihp.IHPRequest.m_sRequestId package
Request identifier
Definition at line 31 of file IHPRequest.java.
Referenced by cc.ihp.IHPRequest.IHPRequest(), and cc.ihp.IHPRequest.sendRequest().
The documentation for this class was generated from the following file:
src/cc/ihp/IHPRequest.java