Carma-cloud: cc.ws.TcmReqServlet.TileIds Class Reference
cc.ws.TcmReqServlet.TileIds Class Reference
Public Member Functions
int compareTo (TileIds o)
int compareTo (TileIds o)
Package Functions
TileIds ()
TileIds (int nX, int nY, int nInitSize)
void setIndices (int nX, int nY)
TileIds ()
TileIds (int nX, int nY)
void setIndices (int nX, int nY)
Package Attributes
int m_nX
int m_nY
Detailed Description
Definition at line 263 of file TcmReqServlet.java.
Constructor & Destructor Documentation
TileIds() [1/4]
cc.ws.TcmReqServlet.TileIds.TileIds () inline package
Definition at line 269 of file TcmReqServlet.java.
        {
        }
TileIds() [2/4]
cc.ws.TcmReqServlet.TileIds.TileIds (int nX, int nY, int nInitSize) inline package
Definition at line 274 of file TcmReqServlet.java.
        {
            super(nInitSize);
            setIndices(nX, nY);
        }
References cc.ws.TcmReqServlet.TileIds.setIndices().
TileIds() [3/4]
cc.ws.TcmReqServlet.TileIds.TileIds () inline package
Definition at line 309 of file TcmReqServlet.java.
        {
        }
TileIds() [4/4]
cc.ws.TcmReqServlet.TileIds.TileIds (int nX, int nY) inline package
Definition at line 314 of file TcmReqServlet.java.
        {
            setIndices(nX, nY);
        }
References cc.ws.TcmReqServlet.TileIds.setIndices().
Member Function Documentation
compareTo() [1/2]
int cc.ws.TcmReqServlet.TileIds.compareTo (TileIds o) inline
Definition at line 289 of file TcmReqServlet.java.
        {
            int nReturn = Integer.compare(m_nX, o.m_nX);
            if (nReturn == 0)
                nReturn = Integer.compare(m_nY, o.m_nY);
            return nReturn;
        }
References cc.ws.TcmReqServlet.TileIds.m_nX, and cc.ws.TcmReqServlet.TileIds.m_nY.
compareTo() [2/2]
int cc.ws.TcmReqServlet.TileIds.compareTo (TileIds o) inline
Definition at line 328 of file TcmReqServlet.java.
        {
            int nReturn = Integer.compare(m_nX, o.m_nX);
            if (nReturn == 0)
                nReturn = Integer.compare(m_nY, o.m_nY);
            return nReturn;
        }
References cc.ws.TcmReqServlet.TileIds.m_nX, and cc.ws.TcmReqServlet.TileIds.m_nY.
setIndices() [1/2]
void cc.ws.TcmReqServlet.TileIds.setIndices (int nX, int nY) inline package
Definition at line 281 of file TcmReqServlet.java.
        {
            m_nX = nX;
            m_nY = nY;
        }
References cc.ws.TcmReqServlet.TileIds.m_nX, and cc.ws.TcmReqServlet.TileIds.m_nY.
Referenced by cc.ws.TcmReqServlet.TileIds.TileIds(), cc.ws.TcmReqServlet.doPost(), and cc.ws.TcmReqServlet.run().
setIndices() [2/2]
void cc.ws.TcmReqServlet.TileIds.setIndices (int nX, int nY) inline package
Definition at line 320 of file TcmReqServlet.java.
        {
            m_nX = nX;
            m_nY = nY;
        }
References cc.ws.TcmReqServlet.TileIds.m_nX, and cc.ws.TcmReqServlet.TileIds.m_nY.
Member Data Documentation
m_nX
int cc.ws.TcmReqServlet.TileIds.m_nX package
Definition at line 265 of file TcmReqServlet.java.
Referenced by cc.ws.TcmReqServlet.TileIds.compareTo(), and cc.ws.TcmReqServlet.TileIds.setIndices().
m_nY
int cc.ws.TcmReqServlet.TileIds.m_nY package
Definition at line 266 of file TcmReqServlet.java.
Referenced by cc.ws.TcmReqServlet.TileIds.compareTo(), and cc.ws.TcmReqServlet.TileIds.setIndices().
The documentation for this class was generated from the following files:
src/cc/ws/TcmReqServlet.java
TcmReqServlet.java