Carma-cloud: cc.geosrv.xodr.geo.Arc Class Reference
cc.geosrv.xodr.geo.Arc Class Reference
Public Member Functions
Arc (double dS, double dX, double dY, double dH, double dL, double dC)
void addPoints (Road oRoad, double dMaxStep, boolean bIncludeEnd, Proj oProj, double[] dProjPt)
void addLanePoints (Road oRoad, double dHdg, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, LaneSection oLaneSection, Proj oProj, double[] dProjPt, double dH, double dK, double dR, double dAngle)
Public Member Functions inherited from cc.geosrv.xodr.geo.Geometry
Geometry (double dS, double dX, double dY, double dH, double dL)
abstract void addPoints (Road oRoad, double dMaxStep, boolean bIncludeEnd, Proj oProj, double[] dProjPt)
void addLanePoints (Road oRoad, double dHdg, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, LaneSection oLaneSection, Proj oProj, double[] dProjPt)
int compareTo (Geometry o)
Public Attributes
double m_dC
Public Attributes inherited from cc.geosrv.xodr.geo.Geometry
double m_dS
double m_dX
double m_dY
double m_dHdg
double m_dL
Private Member Functions
void addLanePoints (LaneSection oLaneSection, ArrayList< Lane > oLanes, double dTangent, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, Proj oProj, double[] dProjPt, Road oRoad, double dH, double dK, double dR, double dAngle)
Additional Inherited Members
Static Public Attributes inherited from cc.geosrv.xodr.geo.Geometry
static int COUNT = 0
static double PX
static double PY
Static Package Functions inherited from cc.geosrv.xodr.geo.Geometry
static double[] addProjectedPoint (double dX, double dY, double[] dPts, Proj oProj, double[] dPoint)
Detailed Description
Author
Federal Highway Administration
Definition at line 20 of file Arc.java.
Constructor & Destructor Documentation
Arc()
cc.geosrv.xodr.geo.Arc.Arc (double dS, double dX, double dY, double dH, double dL, double dC) inline
Definition at line 24 of file Arc.java.
    {
        super(dS, dX, dY, dH, dL);
        m_dC = dC;
    }
References cc.geosrv.xodr.geo.Arc.m_dC.
Member Function Documentation
addLanePoints() [1/2]
void cc.geosrv.xodr.geo.Arc.addLanePoints (LaneSection oLaneSection, ArrayList< Lane > oLanes, double dTangent, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, Proj oProj, double[] dProjPt, Road oRoad, double dH, double dK, double dR, double dAngle) inline private
Definition at line 109 of file Arc.java.
    {
        double dXPrevLane = dXLaneZero;
        double dYPrevLane = dYLaneZero;
        oProj.cs2cs(dXPrevLane, dYPrevLane, dProjPt);
        double dXProjPrevLane = dProjPt[0];
        double dYProjPrevLane = dProjPt[1];
        for (Lane oLane : oLanes)
        {
            double dPx = dXProjPrevLane;
            double dPy = dYProjPrevLane;
            double dLengthAlongSection = dLengthAlongRoad - oLaneSection.m_dS;
            LaneWidth oLaneWidth = LaneWidth.getLaneWidth(dLengthAlongSection, oLane);
            double dT = MathUtil.cubic(dLengthAlongSection - oLaneWidth.m_dS, oLaneWidth.m_dA, oLaneWidth.m_dB, oLaneWidth.m_dC, oLaneWidth.m_dD);
            double dHdg = dR > 0 ? Geo.heading(dH, dK, dXPrevLane, dYPrevLane) : Geo.heading(dXPrevLane, dYPrevLane, dH, dK);
            double dOuterH = dH + Math.cos(dHdg) * dT;
            double dOuterK = dK + Math.sin(dHdg) * dT;
//          double dOuterR = dR > 0 ? dR + dT : dR - dT;
            double dXNextLane = dOuterH + Math.cos(dAngle) * dR;
            double dYNextLane = dOuterK + Math.sin(dAngle) * dR;
//          double dXNextLane = dOuterH + Math.cos(dAngle) * dR;
//          double dYNextLane = dOuterK + Math.sin(dAngle) * dR;
            oLane.m_dOuter = addProjectedPoint(dXNextLane, dYNextLane, oLane.m_dOuter, oProj, dProjPt);
            oLane.m_dOuterW = Arrays.addAndUpdate(oLane.m_dOuterW, dProjPt[0], dProjPt[1]);
            oLane.m_dOuterW = Arrays.add(oLane.m_dOuterW, 0);
            double dProjW = Geo.distance(dXProjPrevLane, dYProjPrevLane, dProjPt[0], dProjPt[1]);
            dXProjPrevLane = dProjPt[0];
            dYProjPrevLane = dProjPt[1];
            double dXPath = (dXPrevLane + dXNextLane) / 2;
            double dYPath = (dYPrevLane + dYNextLane) / 2;
            oLane.m_dCenter = addProjectedPoint(dXPath, dYPath, oLane.m_dCenter, oProj, dProjPt);
            if (this instanceof Arc)
            {
                oRoad.m_dPerps.add(new double[]{dPx, dPy, dXProjPrevLane, dYProjPrevLane});
            }
            if (oLaneWidth.m_dS != oLane.m_dLastLaneWidth)
            {
                oLane.m_dLastLaneWidth = oLaneWidth.m_dS;
                oRoad.m_dLWPoints.add(new double[]{dProjPt[0], dProjPt[1]});
            }
            dXPrevLane = dXNextLane;
            dYPrevLane = dYNextLane;
            oLane.m_dCenter = Arrays.add(oLane.m_dCenter, dProjW);
        }
    }
References cc.util.Arrays.add(), cc.util.Arrays.addAndUpdate(), cc.geosrv.xodr.geo.Geometry.addProjectedPoint(), cc.geosrv.Proj.cs2cs(), cc.util.MathUtil.cubic(), cc.util.Geo.distance(), cc.geosrv.xodr.geo.LaneWidth.getLaneWidth(), cc.util.Geo.heading(), cc.geosrv.xodr.geo.LaneWidth.m_dA, cc.geosrv.xodr.geo.LaneWidth.m_dB, cc.geosrv.xodr.geo.LaneWidth.m_dC, cc.geosrv.xodr.geo.LaneWidth.m_dD, cc.geosrv.xodr.geo.Road.m_dLWPoints, cc.geosrv.xodr.geo.Road.m_dPerps, cc.geosrv.xodr.geo.LaneSection.m_dS, and cc.geosrv.xodr.geo.LaneWidth.m_dS.
addLanePoints() [2/2]
void cc.geosrv.xodr.geo.Arc.addLanePoints (Road oRoad, double dHdg, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, LaneSection oLaneSection, Proj oProj, double[] dProjPt, double dH, double dK, double dR, double dAngle) inline
Definition at line 95 of file Arc.java.
    {
        oProj.cs2cs(dXLaneZero, dYLaneZero, dProjPt);
        if (oRoad.m_dLastGeo != m_dS)
        {
            oRoad.m_dLastGeo = m_dS;
            oRoad.m_dGeoPoints.add(new double[]{dProjPt[0], dProjPt[1]});
        }
        oLaneSection.m_oCenter.m_dOuter = Arrays.addAndUpdate(oLaneSection.m_oCenter.m_dOuter, dProjPt[0], dProjPt[1]);
        addLanePoints(oLaneSection, oLaneSection.m_oLeft, dHdg + Math.PI / 2, dXLaneZero, dYLaneZero, dLengthAlongRoad, oProj, dProjPt, oRoad, dH, dK, dR, dAngle);
        addLanePoints(oLaneSection, oLaneSection.m_oRight, dHdg - Math.PI / 2, dXLaneZero, dYLaneZero, dLengthAlongRoad, oProj, dProjPt, oRoad, dH, dK, dR, dAngle);
    }
References cc.util.Arrays.addAndUpdate(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.Proj.cs2cs(), cc.geosrv.xodr.geo.Road.m_dGeoPoints, cc.geosrv.xodr.geo.Road.m_dLastGeo, cc.geosrv.xodr.geo.Lane.m_dOuter, cc.geosrv.xodr.geo.Geometry.m_dS, cc.geosrv.xodr.geo.LaneSection.m_oCenter, cc.geosrv.xodr.geo.LaneSection.m_oLeft, and cc.geosrv.xodr.geo.LaneSection.m_oRight.
Referenced by cc.geosrv.xodr.geo.Arc.addLanePoints(), and cc.geosrv.xodr.geo.Arc.addPoints().
addPoints()
void cc.geosrv.xodr.geo.Arc.addPoints (Road oRoad, double dMaxStep, boolean bIncludeEnd, Proj oProj, double[] dProjPt) inline
Reimplemented from cc.geosrv.xodr.geo.Geometry.
Definition at line 32 of file Arc.java.
    {
        try
        {
            int nLimit;
            double dEndDistOnRoad = m_dS + m_dL;
            ArrayDeque<LaneSection> oDeque = new ArrayDeque();
            oRoad.getLaneSections(oDeque, m_dS, dEndDistOnRoad);
            double dR = 1.0 / m_dC;
            double dH = m_dX + dR * Math.cos(m_dHdg + Mercator.PI_OVER_TWO);
            double dK = m_dY + dR * Math.sin(m_dHdg + Mercator.PI_OVER_TWO);
            double dInitTheta = m_dHdg + 3.0 * Mercator.PI_OVER_TWO;
            double dTotalAngle = 0;
            while (!oDeque.isEmpty())
            {
                LaneSection oSection = oDeque.removeFirst();
                double dStart = Math.max(m_dS, oSection.m_dS);
                double dEnd = oDeque.isEmpty() ? dEndDistOnRoad : oDeque.getFirst().m_dS;
                double dLength = dEnd - dStart;
                if (dMaxStep > dLength)
                    nLimit = 1;
                else
                    nLimit = (int)(dLength / dMaxStep) + 1;
                double dTheta = dLength * m_dC;
                oRoad.m_dLaneZero = Arrays.ensureCapacity(oRoad.m_dLaneZero, nLimit * 2);
                oRoad.m_dTrack = Arrays.ensureCapacity(oRoad.m_dTrack, nLimit * 2);
                oRoad.m_dNoProj = Arrays.ensureCapacity(oRoad.m_dNoProj, nLimit * 2);
                double dAngleStep = dTheta / nLimit;
                double dLengthStep = dLength / nLimit;
                if (bIncludeEnd) // add last point for last section and last geometry
                    ++nLimit;
                for (int i = 0; i < nLimit; i++)
                {
                    double dAngle = dInitTheta + dTotalAngle;
                    dTotalAngle += dAngleStep;
                    double dX = dH + dR * Math.cos(dAngle);
                    double dY = dK + dR * Math.sin(dAngle);
                    oRoad.m_dTrack = addProjectedPoint(dX, dY, oRoad.m_dTrack, oProj, dProjPt);
                    oRoad.m_dTrack = Arrays.add(oRoad.m_dTrack, 0);
                    double dLengthAlongRoad = dLengthStep * i + dStart;
                    LaneOffset oLaneOffset = LaneOffset.getLaneOffset(dLengthAlongRoad, oRoad.m_oLaneOffsets);
                    double dHdg = m_dHdg + dTotalAngle;
                    double dT = MathUtil.cubic(dLengthAlongRoad - oLaneOffset.m_dS, oLaneOffset.m_dA, oLaneOffset.m_dB, oLaneOffset.m_dC, oLaneOffset.m_dD);
                    double dXLaneZero = dX - Math.sin(dHdg) * dT;
                    double dYLaneZero = dY + Math.cos(dHdg) * dT;
                    oRoad.m_dLaneZero = addProjectedPoint(dXLaneZero, dYLaneZero, oRoad.m_dLaneZero, oProj, dProjPt);
                    oRoad.m_dLaneZero = Arrays.add(oRoad.m_dLaneZero, 0);
                    addLanePoints(oRoad, dHdg, dXLaneZero, dYLaneZero, dLengthAlongRoad, oSection, oProj, dProjPt);
                }
                dTotalAngle -= dAngleStep;
            }
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.util.Arrays.add(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.xodr.geo.Geometry.addProjectedPoint(), cc.util.MathUtil.cubic(), cc.util.Arrays.ensureCapacity(), cc.geosrv.xodr.geo.LaneOffset.getLaneOffset(), cc.geosrv.xodr.geo.Road.getLaneSections(), cc.geosrv.xodr.geo.LaneOffset.m_dA, cc.geosrv.xodr.geo.LaneOffset.m_dB, cc.geosrv.xodr.geo.Arc.m_dC, cc.geosrv.xodr.geo.LaneOffset.m_dC, cc.geosrv.xodr.geo.LaneOffset.m_dD, cc.geosrv.xodr.geo.Geometry.m_dHdg, cc.geosrv.xodr.geo.Geometry.m_dL, cc.geosrv.xodr.geo.Road.m_dLaneZero, cc.geosrv.xodr.geo.Road.m_dNoProj, cc.geosrv.xodr.geo.Geometry.m_dS, cc.geosrv.xodr.geo.LaneOffset.m_dS, cc.geosrv.xodr.geo.LaneSection.m_dS, cc.geosrv.xodr.geo.Road.m_dTrack, cc.geosrv.xodr.geo.Geometry.m_dX, cc.geosrv.xodr.geo.Geometry.m_dY, cc.geosrv.xodr.geo.Road.m_oLaneOffsets, and cc.geosrv.Mercator.PI_OVER_TWO.
Member Data Documentation
m_dC
double cc.geosrv.xodr.geo.Arc.m_dC
Definition at line 22 of file Arc.java.
Referenced by cc.geosrv.xodr.geo.Arc.Arc(), and cc.geosrv.xodr.geo.Arc.addPoints().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/geo/Arc.java