Carma-cloud: cc.ws.RSUServlet Class Reference
cc.ws.RSUServlet Class Reference
Public Member Functions
void init (ServletConfig config) throws ServletException
void doPost (HttpServletRequest oReq, HttpServletResponse oRes) throws IOException
void doDelete (HttpServletRequest oReq, HttpServletResponse oRes) throws IOException
void destroy ()
Static Protected Attributes
static final Logger LOGGER = LogManager.getLogger(RSUServlet.class)
Private Member Functions
int listRSU (HttpServletRequest oReq, JSONObject oResponse)
int identifyRSU (HttpServletRequest oReq, JSONObject oResponse) throws Exception
int registerRSU (HttpServletRequest oReq, JSONObject oResponse) throws Exception
int listBSMReq (HttpServletRequest oReq, JSONObject oResponse) throws Exception
Private Attributes
int bsmReqDuration = 0
int bsmReqCheckPeriod = 0
Static Private Attributes
static final String V2XHUB_PORT = "v2xhub_port"
static final String RSULIST = "RSUList"
static final String BSMREQLIST = "RSUList"
static final String BSMTIMER = "bsmtimer"
Detailed Description
Definition at line 39 of file RSUServlet.java.
Member Function Documentation
destroy()
void cc.ws.RSUServlet.destroy () inline
Definition at line 165 of file RSUServlet.java.
{
        Timer timer = (Timer) getServletContext().getAttribute(BSMTIMER);
        if (timer != null) {
            timer.cancel();
        }
        getServletContext().removeAttribute(BSMTIMER);
        if (getServletContext().getAttribute(RSULIST) != null) {
            getServletContext().removeAttribute(RSULIST);
        }
        if (getServletContext().getAttribute(BSMREQLIST) != null) {
            getServletContext().removeAttribute(BSMREQLIST);
        }
    }
References cc.ws.RSUServlet.BSMREQLIST, cc.ws.RSUServlet.BSMTIMER, and cc.ws.RSUServlet.RSULIST.
doDelete()
void cc.ws.RSUServlet.doDelete (HttpServletRequest oReq, HttpServletResponse oRes) throws IOException inline
Handler DELETE request
Definition at line 126 of file RSUServlet.java.
{
        Session oSession = SessMgr.getSession(oReq);
        JSONObject oResponse = new JSONObject();
        if (oSession == null) // request must contain a valid session token
        {
            oRes.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
        } else {
            if (oReq.getParameter(V2XHUB_PORT) != null) {// Get RSU location list
                ArrayList<RSULocation> rsu_list = (ArrayList<RSULocation>) getServletContext().getAttribute(RSULIST);
                ArrayList<RSULocation> rsu_list_update = new ArrayList<RSULocation>();
                if (rsu_list != null) {
                    for (RSULocation rsu : rsu_list) {
                        if (rsu.v2xhub_port.equals(oReq.getParameter(V2XHUB_PORT))) {
                            continue;
                        }
                        rsu_list_update.add(rsu);
                    }
                    getServletContext().setAttribute(RSULIST, rsu_list_update);
                    JSONArray rsuArr = RSUService.serializeRSUList(rsu_list_update);
                    oResponse.put(RSULIST, rsuArr);
                    oRes.setStatus(HttpServletResponse.SC_OK);
                }
            } else {
                oRes.setStatus(HttpServletResponse.SC_BAD_REQUEST);
                LOGGER.error("Cannot delete RSU!");
            }
        }
        try (PrintWriter oOut = oRes.getWriter()) // write error messages to the JSON response
        {
            oResponse.write(oOut);
        }
    }
References cc.ws.SessMgr.getSession(), cc.ws.RSUServlet.LOGGER, cc.ws.RSUServlet.RSULIST, cc.rsu.RSUService.serializeRSUList(), and cc.ws.RSUServlet.V2XHUB_PORT.
doPost()
void cc.ws.RSUServlet.doPost (HttpServletRequest oReq, HttpServletResponse oRes) throws IOException inline
Handler POST request
Definition at line 81 of file RSUServlet.java.
{
        String[] sUriParts = oReq.getRequestURI().split("/");
        String sMethod = sUriParts[sUriParts.length - 1]; // determine what type of request is made
        oRes.setContentType("application/json"); // all responses are json
        JSONObject oResponse = new JSONObject();
        int nStatus;
        // call the correct method depending on the request
        try {
            if (sMethod.compareTo("register") == 0) {
                nStatus = registerRSU(oReq, oResponse);
                oResponse.put("status", nStatus);
            } else if (sMethod.compareTo("req") == 0) {
                nStatus = identifyRSU(oReq, oResponse);
            } else if (sMethod.compareTo("list") == 0) {
                nStatus = listRSU(oReq, oResponse);
            } else if (sMethod.compareTo("bsm") == 0) {
                nStatus = listBSMReq(oReq, oResponse);
            } else {
                nStatus = HttpServletResponse.SC_UNAUTHORIZED;
            }
            oRes.setStatus(nStatus);
            try (PrintWriter oOut = oRes.getWriter()) // always write the JSON response
            {
                oResponse.write(oOut);
            } catch (IOException oInner) {
                oRes.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
                LOGGER.error("Failed to write response for " + sMethod);
            }
        } catch (Exception oEx) {
            oRes.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
            LOGGER.error(oEx.getMessage() + " during " + sMethod);
            String sErr = oEx.getMessage() + " during " + sMethod;
            oResponse.put("error", sErr);
            try (PrintWriter oOut = oRes.getWriter()) // write error messages to the JSON response
            {
                oResponse.write(oOut);
            }
        }
    }
References cc.ws.RSUServlet.identifyRSU(), cc.ws.RSUServlet.listBSMReq(), cc.ws.RSUServlet.listRSU(), cc.ws.RSUServlet.LOGGER, and cc.ws.RSUServlet.registerRSU().
identifyRSU()
int cc.ws.RSUServlet.identifyRSU (HttpServletRequest oReq, JSONObject oResponse) throws Exception inline private
Definition at line 204 of file RSUServlet.java.
{
        StringBuilder sReq = new StringBuilder();
        try (BufferedInputStream oIn = new BufferedInputStream(oReq.getInputStream())) {
            int nByte = 0;
            while ((nByte = oIn.read()) >= 0) {
                sReq.append((char) nByte);
            }
        }
        // Tracking list for BSM request
        BSMRequestParser parser = new BSMRequestParser();
        BSMRequest newBsmReq = parser
                .parseRequest(new ByteArrayInputStream(sReq.toString().getBytes(StandardCharsets.UTF_8)));
        ArrayList<BSMRequest> updatedBsmReqsList = new ArrayList<BSMRequest>();
        Boolean isIgnore = false;
        try {
            // Already processed existing BSM list
            ArrayList<BSMRequest> existingBsmReqList = (ArrayList<BSMRequest>) getServletContext()
                    .getAttribute(BSMREQLIST);
            if (existingBsmReqList != null) {
                // Check if the new BSM already processed. If processed, ignore the BSM request
                // and update existing matching BSM request update time to now
                for (BSMRequest bsmReq : existingBsmReqList) {
                    if (bsmReq.getId().equals(newBsmReq.getId())) {
                        LOGGER.debug("IGNORE already Processed BSM: " + newBsmReq.getId());
                        bsmReq.setLast_update_at(Instant.now());
                        isIgnore = true;
                    }
                    updatedBsmReqsList.add(bsmReq);
                }
            }
        } catch (NullPointerException oEx) {
            LOGGER.error("No existing BSM");
        }
        if (isIgnore) {
            // Update the tracking list
            getServletContext().setAttribute(BSMREQLIST, updatedBsmReqsList);
            return HttpServletResponse.SC_CONFLICT;
        }
        // Processing BSM request
        ExecutorService singleExector = Executors.newSingleThreadExecutor();
        singleExector.submit(new RSUIdentificationTask(newBsmReq));
        singleExector.shutdown();
        // Add newly processed BSM request to tracking list
        newBsmReq.setLast_update_at(Instant.now());
        updatedBsmReqsList.add(newBsmReq);
        getServletContext().setAttribute(BSMREQLIST, updatedBsmReqsList);
        return HttpServletResponse.SC_OK;
    }
References cc.ws.RSUServlet.BSMREQLIST, cc.rsu.BSMRequest.getId(), cc.ws.RSUServlet.LOGGER, cc.rsu.BSMRequestParser.parseRequest(), and cc.rsu.BSMRequest.setLast_update_at().
Referenced by cc.ws.RSUServlet.doPost().
init()
void cc.ws.RSUServlet.init (ServletConfig config) throws ServletException inline
Definition at line 48 of file RSUServlet.java.
{
        super.init(config);
        bsmReqDuration = Integer.parseInt(config.getInitParameter("bsmReqDuration"));
        bsmReqCheckPeriod = Integer.parseInt(config.getInitParameter("bsmReqCheckPeriod"));
        LOGGER.info("bsm duration parameter (second):" + bsmReqDuration);
        LOGGER.info("bsm check period parameter (second):" + bsmReqCheckPeriod);
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                ArrayList<BSMRequest> bsmReqList = (ArrayList<BSMRequest>) getServletContext().getAttribute(BSMREQLIST);
                ArrayList<BSMRequest> newBsmReqList = new ArrayList<BSMRequest>();
                // clear up old BSM request in the list
                if (bsmReqList != null) {
                    LOGGER.debug("BSM Request List size: " + bsmReqList.size());
                    for (BSMRequest bsmReq : bsmReqList) {
                        if ((Instant.now().toEpochMilli() - bsmReq.getLast_update_at().toEpochMilli())
                                / 1000 < bsmReqDuration) {
                            newBsmReqList.add(bsmReq);
                        }
                    }
                    getServletContext().setAttribute(BSMREQLIST, newBsmReqList);
                }
            }
        }, 0, bsmReqCheckPeriod * 1000L);
        getServletContext().setAttribute(BSMTIMER, timer);
    }
References cc.ws.RSUServlet.bsmReqCheckPeriod, cc.ws.RSUServlet.bsmReqDuration, cc.ws.RSUServlet.BSMREQLIST, cc.ws.RSUServlet.BSMTIMER, and cc.ws.RSUServlet.LOGGER.
listBSMReq()
int cc.ws.RSUServlet.listBSMReq (HttpServletRequest oReq, JSONObject oResponse) throws Exception inline private
Definition at line 291 of file RSUServlet.java.
{
        Session oSession = SessMgr.getSession(oReq);
        if (oSession == null) // request must contain a valid session token
        {
            return HttpServletResponse.SC_UNAUTHORIZED;
        }
        try {
            ArrayList<RSULocation> bsmReqList = (ArrayList<RSULocation>) getServletContext().getAttribute(BSMREQLIST);
            JSONArray bsmReqArr = RSUService.serializeRSUList(bsmReqList);
            oResponse.put(BSMREQLIST, bsmReqArr);
        } catch (NullPointerException oEx) {
            oResponse.put(BSMREQLIST, new JSONArray());
            return HttpServletResponse.SC_OK;
        }
        return HttpServletResponse.SC_OK;
    }
References cc.ws.RSUServlet.BSMREQLIST, cc.ws.SessMgr.getSession(), and cc.rsu.RSUService.serializeRSUList().
Referenced by cc.ws.RSUServlet.doPost().
listRSU()
int cc.ws.RSUServlet.listRSU (HttpServletRequest oReq, JSONObject oResponse) inline private
Request for a list of RSUs
Definition at line 182 of file RSUServlet.java.
{
        Session oSession = SessMgr.getSession(oReq);
        if (oSession == null) // request must contain a valid session token
        {
            return HttpServletResponse.SC_UNAUTHORIZED;
        }
        // Get RSU location list
        try {
            ArrayList<RSULocation> rsu_list = (ArrayList<RSULocation>) getServletContext().getAttribute(RSULIST);
            JSONArray rsuArr = RSUService.serializeRSUList(rsu_list);
            oResponse.put(RSULIST, rsuArr);
        } catch (NullPointerException oEx) {
            oResponse.put(RSULIST, new JSONArray());
            return HttpServletResponse.SC_OK;
        }
        return HttpServletResponse.SC_OK;
    }
References cc.ws.SessMgr.getSession(), cc.ws.RSUServlet.RSULIST, and cc.rsu.RSUService.serializeRSUList().
Referenced by cc.ws.RSUServlet.doPost().
registerRSU()
int cc.ws.RSUServlet.registerRSU (HttpServletRequest oReq, JSONObject oResponse) throws Exception inline private
Request to register RSU with the server
Definition at line 259 of file RSUServlet.java.
{
        StringBuilder sReq = new StringBuilder();
        try (BufferedInputStream oIn = new BufferedInputStream(oReq.getInputStream())) {
            int nByte = 0;
            while ((nByte = oIn.read()) >= 0) {
                sReq.append((char) nByte);
            }
        }
        LOGGER.debug(sReq);
        // Update RSU location list
        ArrayList<RSULocation> existing_rsus = new ArrayList<RSULocation>();
        try {
            existing_rsus = (ArrayList<RSULocation>) getServletContext().getAttribute(RSULIST);
        } catch (NullPointerException oEx) {
            LOGGER.debug("No existing RSU");
        }
        ArrayList<RSULocation> updated_rsus = RSUService.RegisteringRSU(sReq, existing_rsus);
        if (updated_rsus != null) {
            getServletContext().setAttribute(RSULIST, updated_rsus);
            LOGGER.debug(updated_rsus);
        }
        return HttpServletResponse.SC_OK;
    }
References cc.ws.RSUServlet.LOGGER, cc.rsu.RSUService.RegisteringRSU(), and cc.ws.RSUServlet.RSULIST.
Referenced by cc.ws.RSUServlet.doPost().
Member Data Documentation
bsmReqCheckPeriod
int cc.ws.RSUServlet.bsmReqCheckPeriod = 0 private
Definition at line 46 of file RSUServlet.java.
Referenced by cc.ws.RSUServlet.init().
bsmReqDuration
int cc.ws.RSUServlet.bsmReqDuration = 0 private
Definition at line 45 of file RSUServlet.java.
Referenced by cc.ws.RSUServlet.init().
BSMREQLIST
final String cc.ws.RSUServlet.BSMREQLIST = "RSUList" static private
Definition at line 43 of file RSUServlet.java.
Referenced by cc.ws.RSUServlet.destroy(), cc.ws.RSUServlet.identifyRSU(), cc.ws.RSUServlet.init(), and cc.ws.RSUServlet.listBSMReq().
BSMTIMER
final String cc.ws.RSUServlet.BSMTIMER = "bsmtimer" static private
Definition at line 44 of file RSUServlet.java.
Referenced by cc.ws.RSUServlet.destroy(), and cc.ws.RSUServlet.init().
LOGGER
final Logger cc.ws.RSUServlet.LOGGER = LogManager.getLogger(RSUServlet.class) static protected
Definition at line 40 of file RSUServlet.java.
Referenced by cc.ws.RSUServlet.doDelete(), cc.ws.RSUServlet.doPost(), cc.ws.RSUServlet.identifyRSU(), cc.ws.RSUServlet.init(), and cc.ws.RSUServlet.registerRSU().
RSULIST
final String cc.ws.RSUServlet.RSULIST = "RSUList" static private
Definition at line 42 of file RSUServlet.java.
Referenced by cc.ws.RSUServlet.destroy(), cc.ws.RSUServlet.doDelete(), cc.ws.RSUServlet.listRSU(), and cc.ws.RSUServlet.registerRSU().
V2XHUB_PORT
final String cc.ws.RSUServlet.V2XHUB_PORT = "v2xhub_port" static private
Definition at line 41 of file RSUServlet.java.
Referenced by cc.ws.RSUServlet.doDelete().
The documentation for this class was generated from the following file:
src/cc/ws/RSUServlet.java