Carma-cloud: cc.geosrv.Proj Class Reference
cc.geosrv.Proj Class Reference
Classes
class NullProj
Public Member Functions
Proj (String sFromCs, String sToCs) throws NullPointerException
void cs2cs (double dX, double dY, double[] dPoint)
void finalize () throws Throwable
native void proj (long lJniProj, double dX, double dY, double[] dPoint)
Static Public Attributes
static NullProj NULLPROJ = new NullProj()
Protected Member Functions
Proj ()
Package Functions
[instance initializer]
Private Member Functions
native long init (String sFromCs, String sToCs)
native void free (long lJniProj)
Private Attributes
long m_lJniProj
Detailed Description
Definition at line 4 of file Proj.java.
Constructor & Destructor Documentation
Proj() [1/2]
cc.geosrv.Proj.Proj () inline protected
Definition at line 14 of file Proj.java.
    {
    }
Proj() [2/2]
cc.geosrv.Proj.Proj (String sFromCs, String sToCs) throws NullPointerException inline
Definition at line 19 of file Proj.java.
    {
        m_lJniProj = init(sFromCs, sToCs);
        if (m_lJniProj == 0L)
            throw new NullPointerException();
    }
References cc.geosrv.Proj.init(), and cc.geosrv.Proj.m_lJniProj.
Member Function Documentation
[instance initializer]()
cc.geosrv.Proj.[instance initializer] inline package
cs2cs()
void cc.geosrv.Proj.cs2cs (double dX, double dY, double[] dPoint) inline
Reimplemented in cc.geosrv.Proj.NullProj.
Definition at line 28 of file Proj.java.
    {
        proj(m_lJniProj, dX, dY, dPoint);
    }
References cc.geosrv.Proj.m_lJniProj, and cc.geosrv.Proj.proj().
Referenced by cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.pvmt.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.xodr.pvmt.Arc.addLanePoints(), cc.geosrv.xodr.geo.Geometry.addProjectedPoint(), cc.geosrv.xodr.pvmt.Geometry.addProjectedPoint(), cc.geosrv.xodr.rdmk.Geometry.addProjectedPoint(), cc.util.TestPath.main1(), and cc.rsm.RsmParser.parseRequest().
finalize()
void cc.geosrv.Proj.finalize () throws Throwable inline
Definition at line 35 of file Proj.java.
    {
        super.finalize();
        if (m_lJniProj != 0L)
            free(m_lJniProj);
        m_lJniProj = 0L;
    }
References cc.geosrv.Proj.free(), and cc.geosrv.Proj.m_lJniProj.
free()
native void cc.geosrv.Proj.free (long lJniProj) private
Referenced by cc.geosrv.Proj.finalize().
init()
native long cc.geosrv.Proj.init (String sFromCs, String sToCs) private
Referenced by cc.geosrv.Proj.Proj().
proj()
native void cc.geosrv.Proj.proj (long lJniProj, double dX, double dY, double[] dPoint)
Referenced by cc.geosrv.Proj.cs2cs().
Member Data Documentation
m_lJniProj
long cc.geosrv.Proj.m_lJniProj private
Definition at line 6 of file Proj.java.
Referenced by cc.geosrv.Proj.Proj(), cc.geosrv.Proj.cs2cs(), and cc.geosrv.Proj.finalize().
NULLPROJ
NullProj cc.geosrv.Proj.NULLPROJ = new NullProj() static
Definition at line 7 of file Proj.java.
The documentation for this class was generated from the following file:
src/cc/geosrv/Proj.java