Carma-cloud: cc.ws.Handler Class Reference
cc.ws.Handler Class Reference
Static Public Member Functions
static void update (String[] sObj, int nCols, CsvReader oIn)
static void writeJson (PrintWriter oOut, String sId, String sData)
static String getJsonString (String sData, String sTag)
static String getJsonArray (String sData, String sTag)
Protected Member Functions
void doPost (HttpServletRequest oReq, HttpServletResponse oRep) throws ServletException, IOException
Static Protected Attributes
static Comparator< String[]> STR_ARR_COMP = (String[] o1, String[] o2) -> o1[0].compareTo(o2[0])
static final SimpleDateFormat ISO8601Sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'")
Static Package Functions
[static initializer]
Detailed Description
Definition at line 17 of file Handler.java.
Member Function Documentation
[static initializer]()
cc.ws.Handler.[static initializer] inline static package
doPost()
void cc.ws.Handler.doPost (HttpServletRequest oReq, HttpServletResponse oRep) throws ServletException, IOException inline protected
Definition at line 28 of file Handler.java.
    {
        try
        {
            Session oSess = SessMgr.getSession(oReq);
            if (oSess == null)
            {
                oRep.sendError(401);
                return;
            }
            StringBuilder sMethod = new StringBuilder("do");
            String sAction = oReq.getPathInfo();
            sMethod.append(sAction);
            if (sMethod.charAt(2) == '/') // remove leading "/"
                sMethod.deleteCharAt(2);
            sMethod.setCharAt(2, Character.toUpperCase(sMethod.charAt(2))); // upper case the first character of the action
            if (Text.compare(sMethod, "doPost") == 0)
            {
                oRep.sendError(401);
                return;
            }
            for (Method oMethod : getClass().getDeclaredMethods())
            {
                if (Text.compare(sMethod, oMethod.getName()) == 0)
                {
                    try (PrintWriter oOut = oRep.getWriter())
                    {
                        oMethod.invoke(this, oSess, oReq, oOut);
                        return;
                    }
                }
            }
            oRep.sendError(401);
        }
        catch (Exception oEx)
        {
            oRep.sendError(409);
        }
    }
References cc.util.Text.compare(), and cc.ws.SessMgr.getSession().
getJsonArray()
static String cc.ws.Handler.getJsonArray (String sData, String sTag) inline static
Definition at line 105 of file Handler.java.
    {
        StringBuilder sBuffer = new StringBuilder(sTag);
        sBuffer.insert(0, "\"");
        sBuffer.append("\":[");
        sTag = sBuffer.toString();
        int nStart = sData.indexOf(sTag);
        if (nStart < 0)
            return null;
        nStart += sTag.length();
        int nEnd = sData.indexOf("]", nStart);
        return sData.substring(nStart, nEnd).replaceAll("\"", "");
    }
Referenced by cc.ws.EventMgr.doMsgs().
getJsonString()
static String cc.ws.Handler.getJsonString (String sData, String sTag) inline static
Definition at line 88 of file Handler.java.
    {
        StringBuilder sBuffer = new StringBuilder(sTag);
        sBuffer.insert(0, "\"");
        sBuffer.append("\":\"");
        sTag = sBuffer.toString();
        int nStart = sData.indexOf(sTag);
        if (nStart < 0)
            return null; // tag doesn't exist
        nStart += sTag.length();
        int nEnd = sData.indexOf("\"", nStart);
        if (nEnd < 0)
            return null;
        return sData.substring(nStart, nEnd);
    }
Referenced by cc.ws.EventMgr.filterEvent().
update()
static void cc.ws.Handler.update (String[] sObj, int nCols, CsvReader oIn) inline static
Definition at line 74 of file Handler.java.
    {
        int nLimit = Math.min(nCols, sObj.length);
        for (int i = 0; i < nLimit; i++)
            sObj[i] = oIn.parseString(i);
    }
References cc.util.CsvReader.parseString().
Referenced by cc.ws.EventMgr.run(), and cc.ws.RopMgr.run().
writeJson()
static void cc.ws.Handler.writeJson (PrintWriter oOut, String sId, String sData) inline static
Definition at line 82 of file Handler.java.
    {
        oOut.write(String.format("\"%s\":%s", sId, sData));
    }
Referenced by cc.ws.EventMgr.doDetail(), cc.ws.RopMgr.doDetails(), cc.ws.EventMgr.doList(), cc.ws.EventMgr.doMsgs(), cc.ws.RopMgr.doNull(), cc.ws.EventMgr.doSave(), and cc.ws.RopMgr.doSave().
Member Data Documentation
ISO8601Sdf
final SimpleDateFormat cc.ws.Handler.ISO8601Sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'") static protected
Definition at line 20 of file Handler.java.
Referenced by cc.ws.EventMgr.doSave(), and cc.ws.RopMgr.doSave().
STR_ARR_COMP
Comparator<String[]> cc.ws.Handler.STR_ARR_COMP = (String[] o1, String[] o2) -> o1[0].compareTo(o2[0]) static protected
Definition at line 19 of file Handler.java.
Referenced by cc.ws.EventMgr.doDetail(), cc.ws.RopMgr.doDetails(), cc.ws.EventMgr.doSave(), cc.ws.RopMgr.doSave(), cc.ws.EventMgr.run(), and cc.ws.RopMgr.run().
The documentation for this class was generated from the following file:
src/cc/ws/Handler.java