Carma-cloud: cc.ws.TcmReqServlet Class Reference
cc.ws.TcmReqServlet Class Reference
Classes
class TileIds
Public Member Functions
void init (ServletConfig oConfig)
void doPost (HttpServletRequest oReq, HttpServletResponse oRes) throws ServletException, IOException
void run ()
Static Protected Attributes
static final Logger LOGGER = LogManager.getLogger(TcmReqServlet.class)
Static Package Functions
[static initializer]
Private Attributes
int m_nExplodeDistForXml = 0
boolean m_bRemoveWidth = false
int m_nPolyStep = 50
Static Private Attributes
static int[] IGNORE_CTRLS
Detailed Description
Author
aaron.cherney
Definition at line 49 of file TcmReqServlet.java.
Member Function Documentation
[static initializer]()
cc.ws.TcmReqServlet.[static initializer] inline static package
References cc.ctrl.TrafCtrlEnums.getCtrl(), and cc.ws.TcmReqServlet.IGNORE_CTRLS.
doPost()
void cc.ws.TcmReqServlet.doPost (HttpServletRequest oReq, HttpServletResponse oRes) throws ServletException, IOException inline
Definition at line 89 of file TcmReqServlet.java.
    {
        StringBuilder sReq = new StringBuilder(1024);
        sReq.append(oReq.getRemoteAddr());
        try (BufferedInputStream oIn = new BufferedInputStream(oReq.getInputStream()))
        {
            int nByte;
            while ((nByte = oIn.read()) >= 0)
                sReq.append((char)nByte);
        }
        new Thread(this, sReq.toString()).start();
        LOGGER.debug(sReq);
    }
References cc.ws.TcmReqServlet.LOGGER.
init()
void cc.ws.TcmReqServlet.init (ServletConfig oConfig) inline
Definition at line 65 of file TcmReqServlet.java.
    {
        String sRemoveWidth = oConfig.getInitParameter("removewidth");
        if (sRemoveWidth != null)
            m_bRemoveWidth = Boolean.parseBoolean(sRemoveWidth);
        String sExplodeDistForXml = oConfig.getInitParameter("xmldist");
        if (sExplodeDistForXml != null)
        {
            int nExplode = Integer.parseInt(sExplodeDistForXml);
            if (nExplode == 0)
                return;
            if (nExplode < ProcCtrl.g_dExplodeStep * 100)
                nExplode = (int)(ProcCtrl.g_dExplodeStep * 100);
            m_nExplodeDistForXml = nExplode;
        }
        String sPolyStep = oConfig.getInitParameter("polystep");
        if (sPolyStep != null)
            m_nPolyStep = Integer.parseInt(sPolyStep);
    }
References cc.ctrl.proc.ProcCtrl.g_dExplodeStep, cc.ws.TcmReqServlet.m_bRemoveWidth, cc.ws.TcmReqServlet.m_nExplodeDistForXml, and cc.ws.TcmReqServlet.m_nPolyStep.
run()
void cc.ws.TcmReqServlet.run () inline
Definition at line 107 of file TcmReqServlet.java.
    {
        try
        {
            long lNow = TimeSource.getInstance().currentTimeMillis();
            String sReq = Thread.currentThread().getName();
            int nPos = sReq.indexOf('<');
            String sHost = sReq.substring(0, nPos);
            sReq = sReq.substring(nPos);
            TcmReqParser oReqParser;
            if (sReq.contains("<tcrV01>"))
                oReqParser = new TcmReqParser();
            else
                oReqParser = new TcmReqParser2();
            TcmReq oTcmReq = oReqParser.parseRequest(new ByteArrayInputStream(sReq.getBytes(StandardCharsets.UTF_8)));
            ArrayList<TrafCtrl> oResCtrls = new ArrayList();
            ArrayList<TileIds> oTiles = new ArrayList(50);
            ArrayList<byte[]> oProcessed = new ArrayList(1000);
            TrafCtrl oTrafCtrlSearch = new TrafCtrl();
            oTrafCtrlSearch.m_yId = new byte[16];
            TileIds oTileIdsSearch = new TileIds();
            int nMsgTot = 0;
            for (TcBounds oBounds : oTcmReq.m_oBounds)
            {
                double[] dTcMercBounds = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE};
                double[] dCorners = new double[oBounds.m_nCorners.length];
                for (int nIndex = 0; nIndex < oBounds.m_nCorners.length;)
                {
                    double dX = Mercator.lonToMeters(Geo.fromIntDeg(oBounds.m_nCorners[nIndex]));
                    dCorners[nIndex++] = dX;
                    double dY = Mercator.latToMeters(Geo.fromIntDeg(oBounds.m_nCorners[nIndex]));
                    dCorners[nIndex++] = dY;
                    if (dX < dTcMercBounds[0])
                        dTcMercBounds[0] = dX;
                    if (dY < dTcMercBounds[1])
                        dTcMercBounds[1] = dY;
                    if (dX > dTcMercBounds[2])
                        dTcMercBounds[2] = dX;
                    if (dY > dTcMercBounds[3])
                        dTcMercBounds[3] = dY;
                }
                Geo.untwist(dCorners);
                Mercator oM = Mercator.getInstance();
                int[] nTiles = new int[2];
                int[] nTileIndices = new int[4];
                oM.metersToTile(dTcMercBounds[0], dTcMercBounds[3], CtrlTiles.g_nZoom, nTiles); // determine the tiles the bounds intersect
                nTileIndices[0] = nTiles[0];
                nTileIndices[1] = nTiles[1];
                oM.metersToTile(dTcMercBounds[2], dTcMercBounds[1], CtrlTiles.g_nZoom, nTiles);
                nTileIndices[2] = nTiles[0];
                nTileIndices[3] = nTiles[1];
                for (int nTileX = nTileIndices[0]; nTileX <= nTileIndices[2]; nTileX++) // for each tile
                {
                    for (int nTileY = nTileIndices[1]; nTileY <= nTileIndices[3]; nTileY++)
                    {
                        Path oIndexFile = Paths.get(String.format(CtrlTiles.g_sTdFileFormat, nTileX, CtrlTiles.g_nZoom, nTileX, nTileY) + ".ndx");
                        if (!Files.exists(oIndexFile)) // check if the index file exists
                            continue;
                        oTileIdsSearch.setIndices(nTileX, nTileY);
                        int nIndex = Collections.binarySearch(oTiles, oTileIdsSearch);
                        if (nIndex < 0) // if the tile index file has not been loaded
{
                            TileIds oTile = new TileIds(nTileX, nTileY, 1000);
                            nIndex = ~nIndex;
                            oTiles.add(nIndex, oTile);
                            try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(oIndexFile)))) // read the index file to find which controls are in the tile
{
                                while (oIn.available() > 0)
{
                                    CtrlIndex oIndex = new CtrlIndex(oIn);
                                    if (oBounds.m_lOldest <= oIndex.m_lStart && oIndex.m_lEnd > lNow && java.util.Arrays.binarySearch(IGNORE_CTRLS, oIndex.m_nType) < 0 && Geo.boundingBoxesIntersect(dTcMercBounds, oIndex.m_dBB)) // skip out controls and control types to ignore
                                        oTile.add(oIndex.m_yId);
                                }
                            }
                        }
                        TileIds oTile = oTiles.get(nIndex);
                        oResCtrls.ensureCapacity(oResCtrls.size() + oTile.size());
                        for (byte[] yId : oTile)
{
                            int nProcessIndex = Collections.binarySearch(oProcessed, yId, TrafCtrl.ID_COMP);
                            if (nProcessIndex < 0)
                                oProcessed.add(~nProcessIndex, yId);
                            else
                                continue;
                            String sFile = CtrlTiles.g_sCtrlDir + TrafCtrl.getId(yId) + ".bin";
                            Path oCtrlFile = Paths.get(sFile);
                            if (!Files.exists(oCtrlFile))
                                continue;
                            TrafCtrl oCtrl;
                            try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(oCtrlFile))))
{
                                oCtrl = new TrafCtrl(oIn, true, false);
                            }
                            if (Geo.ctrlIntersectBounds(dCorners, oCtrl, m_nPolyStep))
{
                                oResCtrls.add(oCtrl);
                                oCtrl.preparePoints(m_nExplodeDistForXml);
                                nMsgTot += (oCtrl.size() / 256 + 1);
                            }
                        }
                    }
                }
            }
            int nMsgCount = 1;
            if (oReqParser.m_bList)
                nMsgTot = oResCtrls.size();
            StringBuilder sBuf = new StringBuilder(nMsgTot * 2048);
            for (int nCtrlIndex = 0; nCtrlIndex < oResCtrls.size(); nCtrlIndex++)
            {
                TrafCtrl oCtrl = oResCtrls.get(nCtrlIndex);
                int nParts = oCtrl.size() / 256 + 1;
                if (oReqParser.m_bList)
                    nParts = 1;
                for (int nIndex = 0; nIndex < nParts; nIndex++)
                {
                    if (nIndex == 0)
                        oCtrl.getXml(sBuf, oTcmReq.m_sReqId, oTcmReq.m_nReqSeq, nMsgCount, nMsgTot, oTcmReq.m_sVersion, true, 0, m_bRemoveWidth, oReqParser.m_bList);
                    else
                        oCtrl.getXml(sBuf, oTcmReq.m_sReqId, oTcmReq.m_nReqSeq, nMsgCount, nMsgTot, oTcmReq.m_sVersion, false, nIndex * 256 - 1, m_bRemoveWidth, oReqParser.m_bList);
                    ++nMsgCount;
                    if (!oReqParser.m_bList)
                    {
                        HttpURLConnection oHttpClient = (HttpURLConnection)new URL(String.format("http://%s:%d/tcmreply", sHost, oReqParser.m_nPort)).openConnection();
                        oHttpClient.setFixedLengthStreamingMode(sBuf.length());
                        oHttpClient.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
                        oHttpClient.setDoOutput(true);
                        oHttpClient.setRequestMethod("POST");
                        oHttpClient.setConnectTimeout(1000);
                        try
{
                            oHttpClient.connect(); // send post request
                            try (BufferedWriter oOut = new BufferedWriter(new OutputStreamWriter(oHttpClient.getOutputStream())))
{
                                oOut.append(sBuf);
                            }
                            oHttpClient.disconnect();
                        }
                        catch (Exception oEx)
{
                            oEx.printStackTrace();
                        }
                        LOGGER.debug(sBuf);
                    }
                }
            }
            if (oReqParser.m_bList)
            {
                String sUrl = String.format("http://%s:%d/tcmreply", sHost, oReqParser.m_nPort);
                HttpURLConnection oHttpClient = (HttpURLConnection)new URL(sUrl).openConnection();
                oHttpClient.setRequestProperty("Content-Encoding", "gzip");
                oHttpClient.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
                oHttpClient.setDoOutput(true);
                oHttpClient.setRequestMethod("POST");
                oHttpClient.setConnectTimeout(1000);
                try (ByteArrayOutputStream oBaos = new ByteArrayOutputStream(sBuf.length()))
                {
                    try (BufferedWriter oOut = new BufferedWriter(new OutputStreamWriter(new GZIPOutputStream(oBaos))))
                    {
                        oOut.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?><TrafficControlMessageList>").append(sBuf).append("</TrafficControlMessageList>");
                    }
                    oHttpClient.setFixedLengthStreamingMode(oBaos.size());
                    try
                    {
                        oHttpClient.connect(); // send post request
                        try (BufferedOutputStream oOut = new BufferedOutputStream(oHttpClient.getOutputStream()))
{
                            oOut.write(oBaos.toByteArray());
                        }
                        oHttpClient.disconnect();
                    }
                    catch (Exception oEx)
                    {
                        LOGGER.error(sUrl, oEx);
                    }
                }
                sBuf.insert(0, "<?xml version=\"1.0\" encoding=\"UTF-8\"?><TrafficControlMessageList>");
                sBuf.append("</TrafficControlMessageList>");
                LOGGER.debug(sBuf);
            }
        }
        catch (Exception oEx)
        {
            LOGGER.error(oEx, oEx);
        }
    }
References cc.util.Geo.boundingBoxesIntersect(), cc.util.Geo.ctrlIntersectBounds(), cc.ws.TimeSource.currentTimeMillis(), cc.util.Geo.fromIntDeg(), cc.ws.CtrlTiles.g_nZoom, cc.ws.CtrlTiles.g_sTdFileFormat, cc.ctrl.TrafCtrl.getId(), cc.geosrv.Mercator.getInstance(), cc.ws.TimeSource.getInstance(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.ID_COMP, cc.ws.TcmReqServlet.IGNORE_CTRLS, cc.geosrv.Mercator.latToMeters(), cc.ws.TcmReqServlet.LOGGER, cc.geosrv.Mercator.lonToMeters(), cc.ctrl.TcmReqParser.m_bList, cc.ws.TcmReqServlet.m_bRemoveWidth, cc.ctrl.CtrlIndex.m_dBB, cc.ctrl.CtrlIndex.m_lEnd, cc.ctrl.TcBounds.m_lOldest, cc.ctrl.CtrlIndex.m_lStart, cc.ctrl.TcBounds.m_nCorners, cc.ws.TcmReqServlet.m_nExplodeDistForXml, cc.ws.TcmReqServlet.m_nPolyStep, cc.ctrl.TcmReqParser.m_nPort, cc.ctrl.TcmReq.m_nReqSeq, cc.ctrl.CtrlIndex.m_nType, cc.ctrl.TcmReq.m_oBounds, cc.ctrl.TcmReq.m_sReqId, cc.ctrl.TcmReq.m_sVersion, cc.ctrl.CtrlIndex.m_yId, cc.geosrv.Mercator.metersToTile(), cc.util.FileUtil.newInputStream(), cc.ctrl.TcmReqParser.parseRequest(), cc.ctrl.TrafCtrl.preparePoints(), cc.ws.TcmReqServlet.TileIds.setIndices(), and cc.util.Geo.untwist().
Member Data Documentation
IGNORE_CTRLS
int [] cc.ws.TcmReqServlet.IGNORE_CTRLS static private
Definition at line 56 of file TcmReqServlet.java.
Referenced by cc.ws.TcmReqServlet.[static initializer](), and cc.ws.TcmReqServlet.run().
LOGGER
final Logger cc.ws.TcmReqServlet.LOGGER = LogManager.getLogger(TcmReqServlet.class) static protected
Definition at line 51 of file TcmReqServlet.java.
Referenced by cc.ws.TcmReqServlet.doPost(), and cc.ws.TcmReqServlet.run().
m_bRemoveWidth
boolean cc.ws.TcmReqServlet.m_bRemoveWidth = false private
Definition at line 54 of file TcmReqServlet.java.
Referenced by cc.ws.TcmReqServlet.init(), and cc.ws.TcmReqServlet.run().
m_nExplodeDistForXml
int cc.ws.TcmReqServlet.m_nExplodeDistForXml = 0 private
Definition at line 53 of file TcmReqServlet.java.
Referenced by cc.ws.TcmReqServlet.init(), and cc.ws.TcmReqServlet.run().
m_nPolyStep
int cc.ws.TcmReqServlet.m_nPolyStep = 50 private
Definition at line 55 of file TcmReqServlet.java.
Referenced by cc.ws.TcmReqServlet.init(), and cc.ws.TcmReqServlet.run().
The documentation for this class was generated from the following file:
src/cc/ws/TcmReqServlet.java