Carma-cloud: cc.geosrv.xodr.geo.Road Class Reference
cc.geosrv.xodr.geo.Road Class Reference
Public Member Functions
Road (int nId, double dLength)
void adjustSections (double dMaxStep)
void createPoints (double dMaxStep, Proj oProj)
void setLaneIds (double dMaxStep)
void getDirectionCtrlLineArcs (ArrayList< CtrlLineArcs > oCtrlLineArcs, double dMaxStep)
void getPavementCtrlLineArcs (ArrayList< CtrlLineArcs > oCtrlLineArcs, double dMaxStep)
void getLaneSections (ArrayDeque< LaneSection > oSections, double dStart, double dEnd)
Public Attributes
int m_nId
double m_dLength
double[] m_dNoProj
double[] m_dTrack
double[] m_dLaneZero
double[] m_dBounds = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE}
double m_dLastGeo = Double.MAX_VALUE
double m_dLastSection = Double.MAX_VALUE
int m_nMaxSpeed
ArrayList< double[]> m_dGeoPoints = new ArrayList()
ArrayList< double[]> m_dLSPoints = new ArrayList()
ArrayList< double[]> m_dLWPoints = new ArrayList()
ArrayList< double[]> m_dPerps = new ArrayList()
Protected Member Functions
Road ()
Package Attributes
ArrayList< LaneOffset > m_oLaneOffsets = new ArrayList()
ArrayList< Geometry > m_oGeometries = new ArrayList()
Detailed Description
Author
Federal Highway Administration
Definition at line 21 of file Road.java.
Constructor & Destructor Documentation
Road() [1/2]
cc.geosrv.xodr.geo.Road.Road () inline protected
Definition at line 39 of file Road.java.
    {
    }
Road() [2/2]
cc.geosrv.xodr.geo.Road.Road (int nId, double dLength) inline
Definition at line 45 of file Road.java.
    {
        m_nId = nId;
        m_dLength = dLength;
        m_dTrack = Arrays.newDoubleArray();
        m_dLaneZero = Arrays.newDoubleArray();
        m_dNoProj = Arrays.newDoubleArray();
    }
References cc.geosrv.xodr.geo.Road.m_dLaneZero, cc.geosrv.xodr.geo.Road.m_dLength, cc.geosrv.xodr.geo.Road.m_dNoProj, cc.geosrv.xodr.geo.Road.m_dTrack, cc.geosrv.xodr.geo.Road.m_nId, and cc.util.Arrays.newDoubleArray().
Member Function Documentation
adjustSections()
void cc.geosrv.xodr.geo.Road.adjustSections (double dMaxStep) inline
Definition at line 55 of file Road.java.
    {
        int nIndex = size();
        if (nIndex == 1)
            return;
        double dPrevOffset = m_dLength;
        while (nIndex-- > 0)
        {
            double dSectionLength = dPrevOffset - get(nIndex).m_dS;
            if (dSectionLength < dMaxStep)
                remove(nIndex);
            else
                dPrevOffset = get(nIndex).m_dS;
        }
        if (get(0).m_dS != 0.0)
            get(0).m_dS = 0;
    }
References cc.geosrv.xodr.geo.Road.m_dLength.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement().
createPoints()
void cc.geosrv.xodr.geo.Road.createPoints (double dMaxStep, Proj oProj) inline
Definition at line 76 of file Road.java.
    {
        Collections.sort(m_oGeometries);
        double[] dProjPt = new double[2];
        for (int nIndex = 0; nIndex < m_oGeometries.size() - 1; nIndex++)
            m_oGeometries.get(nIndex).addPoints(this, dMaxStep, false, oProj, dProjPt);
        m_oGeometries.get(m_oGeometries.size() - 1).addPoints(this, dMaxStep, true, oProj, dProjPt);
    }
References cc.geosrv.xodr.geo.Road.m_oGeometries.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement().
getDirectionCtrlLineArcs()
void cc.geosrv.xodr.geo.Road.getDirectionCtrlLineArcs (ArrayList< CtrlLineArcs > oCtrlLineArcs, double dMaxStep) inline
Definition at line 142 of file Road.java.
    {
        ArrayList<Lane> oLanes = new ArrayList();
        for (LaneSection oSection : this)
        {
            oSection.getLanes(oLanes);
            for (Lane oLane : oLanes)
            {
                if (oLane.m_nLaneIndex == 0) // skip zero width center lane
                {
                    continue;
                }
                oCtrlLineArcs.add(new CtrlLineArcs(oLane, dMaxStep));
            }
        }
    }
References cc.geosrv.xodr.geo.LaneSection.getLanes().
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement().
getLaneSections()
void cc.geosrv.xodr.geo.Road.getLaneSections (ArrayDeque< LaneSection > oSections, double dStart, double dEnd) inline
Definition at line 172 of file Road.java.
    {
        oSections.clear();
        int nIndex = size();
        double dSectionEnd = m_dLength;
        while (nIndex-- > 0)
        {
            LaneSection oTemp = get(nIndex);
            if (dStart < dSectionEnd && dEnd > oTemp.m_dS)
                oSections.addFirst(oTemp);
            dSectionEnd = oTemp.m_dS;
        }
    }
References cc.geosrv.xodr.geo.Road.m_dLength, and cc.geosrv.xodr.geo.LaneSection.m_dS.
Referenced by cc.geosrv.xodr.geo.Arc.addPoints(), and cc.geosrv.xodr.geo.Line.addPoints().
getPavementCtrlLineArcs()
void cc.geosrv.xodr.geo.Road.getPavementCtrlLineArcs (ArrayList< CtrlLineArcs > oCtrlLineArcs, double dMaxStep) inline
Definition at line 161 of file Road.java.
    {
        int nType = XodrUtil.getLaneType("driving");
        for (LaneSection oSection : this)
        {
            oSection.createPavement();
            oCtrlLineArcs.add(new CtrlLineArcs(m_nId, oSection.m_nId, 0, 0, nType, oSection.m_dPavement, dMaxStep));
        }
    }
References cc.geosrv.xodr.geo.LaneSection.createPavement(), cc.geosrv.xodr.XodrUtil.getLaneType(), cc.geosrv.xodr.geo.LaneSection.m_dPavement, cc.geosrv.xodr.geo.LaneSection.m_nId, and cc.geosrv.xodr.geo.Road.m_nId.
setLaneIds()
void cc.geosrv.xodr.geo.Road.setLaneIds (double dMaxStep) inline
Definition at line 86 of file Road.java.
    {
        double dTol = dMaxStep * 2;
        ArrayList<Lane> oPrevLanes = new ArrayList();
        get(0).getLanes(oPrevLanes);
        int nNextId = Integer.MIN_VALUE;
        for (Lane oLane : oPrevLanes)
        {
            oLane.m_nLaneIdByRoad = oLane.m_nLaneIndex;
            int nComp = Math.abs(oLane.m_nLaneIndex);
            if (nComp > nNextId)
                nNextId = nComp;
        }
        for (int nIndex = 1; nIndex < size(); nIndex++)
        {
            ArrayList<Lane> oCurrLanes = new ArrayList();
            get(nIndex).getLanes(oCurrLanes);
            for (Lane oCurr: oCurrLanes)
            {
                if (oCurr.m_nLaneIndex == 0)
                    continue;
                double[] dCurr = oCurr.m_dCenter;
                oCurr.m_nLaneIdByRoad = Integer.MIN_VALUE;
                for (Lane oPrev: oPrevLanes)
                {
                    if (oPrev.m_nLaneIndex == 0)
                        continue;
                    double[] dPrev = oPrev.m_dCenter;
                    int nSize = Arrays.size(dPrev);
                    double dDist = Geo.distance(dCurr[5], dCurr[6], dPrev[nSize - 3], dPrev[nSize - 2]);
//                  if (dDist > dTol)
//                      System.out.println(dDist);
                    if (dDist <= dTol && oCurr.m_nLaneType == oPrev.m_nLaneType)
                    {
                        oCurr.m_nLaneIdByRoad = oPrev.m_nLaneIdByRoad;
                        break;
                    }
                }
                if (oCurr.m_nLaneIdByRoad == Integer.MIN_VALUE)
                {
                    ++nNextId;
                    if (oCurr.m_nLaneIndex < 0)
                        oCurr.m_nLaneIdByRoad = -nNextId;
                    else
                        oCurr.m_nLaneIdByRoad = nNextId;
                }
            }
            oPrevLanes.clear();
            oPrevLanes.addAll(oCurrLanes);
        }
    }
References cc.util.Geo.distance(), and cc.util.Arrays.size().
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement().
Member Data Documentation
m_dBounds
double [] cc.geosrv.xodr.geo.Road.m_dBounds = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE}
Definition at line 28 of file Road.java.
m_dGeoPoints
ArrayList<double[]> cc.geosrv.xodr.geo.Road.m_dGeoPoints = new ArrayList()
Definition at line 34 of file Road.java.
Referenced by cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addLanePoints(), and cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
m_dLaneZero
double [] cc.geosrv.xodr.geo.Road.m_dLaneZero
Definition at line 27 of file Road.java.
Referenced by cc.geosrv.xodr.geo.Road.Road(), cc.geosrv.xodr.geo.Arc.addPoints(), cc.geosrv.xodr.geo.Line.addPoints(), and cc.geosrv.xodr.geo.XodrGeoParser.startElement().
m_dLastGeo
double cc.geosrv.xodr.geo.Road.m_dLastGeo = Double.MAX_VALUE
Definition at line 31 of file Road.java.
Referenced by cc.geosrv.xodr.geo.Geometry.addLanePoints(), and cc.geosrv.xodr.geo.Arc.addLanePoints().
m_dLastSection
double cc.geosrv.xodr.geo.Road.m_dLastSection = Double.MAX_VALUE
Definition at line 32 of file Road.java.
Referenced by cc.geosrv.xodr.geo.Geometry.addLanePoints().
m_dLength
double cc.geosrv.xodr.geo.Road.m_dLength
Definition at line 24 of file Road.java.
Referenced by cc.geosrv.xodr.geo.Road.Road(), cc.geosrv.xodr.geo.Road.adjustSections(), cc.geosrv.xodr.geo.XodrGeoParser.endElement(), and cc.geosrv.xodr.geo.Road.getLaneSections().
m_dLSPoints
ArrayList<double[]> cc.geosrv.xodr.geo.Road.m_dLSPoints = new ArrayList()
Definition at line 35 of file Road.java.
Referenced by cc.geosrv.xodr.geo.Geometry.addLanePoints(), and cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
m_dLWPoints
ArrayList<double[]> cc.geosrv.xodr.geo.Road.m_dLWPoints = new ArrayList()
Definition at line 36 of file Road.java.
Referenced by cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addLanePoints(), and cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
m_dNoProj
double [] cc.geosrv.xodr.geo.Road.m_dNoProj
Definition at line 25 of file Road.java.
Referenced by cc.geosrv.xodr.geo.Road.Road(), cc.geosrv.xodr.geo.Arc.addPoints(), cc.geosrv.xodr.geo.Line.addPoints(), and cc.geosrv.xodr.geo.XodrGeoParser.startElement().
m_dPerps
ArrayList<double[]> cc.geosrv.xodr.geo.Road.m_dPerps = new ArrayList()
Definition at line 37 of file Road.java.
Referenced by cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addLanePoints(), and cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
m_dTrack
double [] cc.geosrv.xodr.geo.Road.m_dTrack
Definition at line 26 of file Road.java.
Referenced by cc.geosrv.xodr.geo.Road.Road(), cc.geosrv.xodr.geo.Arc.addPoints(), cc.geosrv.xodr.geo.Line.addPoints(), cc.geosrv.xodr.geo.XodrGeoParser.startElement(), and cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
m_nId
int cc.geosrv.xodr.geo.Road.m_nId
Definition at line 23 of file Road.java.
Referenced by cc.geosrv.xodr.geo.Road.Road(), cc.geosrv.xodr.geo.XodrGeoParser.endElement(), cc.geosrv.xodr.geo.Road.getPavementCtrlLineArcs(), cc.geosrv.xodr.geo.XodrGeoParser.startElement(), cc.geosrv.xodr.geo.XodrGeoParser.writeSpeeds(), and cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
m_nMaxSpeed
int cc.geosrv.xodr.geo.Road.m_nMaxSpeed
Definition at line 33 of file Road.java.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.startElement().
m_oGeometries
ArrayList<Geometry> cc.geosrv.xodr.geo.Road.m_oGeometries = new ArrayList() package
Definition at line 30 of file Road.java.
Referenced by cc.geosrv.xodr.geo.Road.createPoints(), cc.geosrv.xodr.geo.XodrGeoParser.endElement(), and cc.geosrv.xodr.geo.XodrGeoParser.startElement().
m_oLaneOffsets
ArrayList<LaneOffset> cc.geosrv.xodr.geo.Road.m_oLaneOffsets = new ArrayList() package
Definition at line 29 of file Road.java.
Referenced by cc.geosrv.xodr.geo.Arc.addPoints(), cc.geosrv.xodr.geo.Line.addPoints(), cc.geosrv.xodr.geo.XodrGeoParser.endElement(), and cc.geosrv.xodr.geo.XodrGeoParser.startElement().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/geo/Road.java