Carma-cloud: cc.rsm.RsmCollect.RsmRecord Class Reference
cc.rsm.RsmCollect.RsmRecord Class Reference
Public Member Functions
int compareTo (RsmRecord o)
void cleanup ()
Package Functions
RsmRecord (String sId, String sFile)
Package Attributes
String m_sId
String m_sFile
boolean m_bCurrent = true
boolean m_bNew = true
ArrayList< byte[]> m_yIds = new ArrayList()
Detailed Description
Definition at line 372 of file RsmCollect.java.
Constructor & Destructor Documentation
RsmRecord()
cc.rsm.RsmCollect.RsmRecord.RsmRecord (String sId, String sFile) inline package
Definition at line 382 of file RsmCollect.java.
        {
            m_sId = sId;
            m_sFile = sFile;
        }
References cc.rsm.RsmCollect.RsmRecord.m_sFile, and cc.rsm.RsmCollect.RsmRecord.m_sId.
Member Function Documentation
cleanup()
void cc.rsm.RsmCollect.RsmRecord.cleanup () inline
Definition at line 396 of file RsmCollect.java.
        {
            for (byte[] yId : m_yIds)
            {
                try
                {
                    long lNow = System.currentTimeMillis() - 10;
                    String sId = TrafCtrl.getId(yId);
                    String sFile = ProcCtrl.g_sTrafCtrlDir + sId + ".bin";
                    TrafCtrl oCtrl;
                    try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(Paths.get(sFile)))))
                    {
                        oCtrl = new TrafCtrl(oIn, true, true);
                    }
                    synchronized (this)
                    {
                        for (int[] nTile : oCtrl.m_oFullGeo.m_oTiles)
{
                            String sIndex = String.format(ProcCtrl.g_sTdFileFormat, nTile[0], ProcCtrl.g_nDefaultZoom, nTile[0], nTile[1]) + ".ndx";
                            ProcCtrl.updateIndex(sIndex, oCtrl, lNow);
                        }
                    }
                }
                catch (Exception oEx)
                {
                    LOGGER.error("Error removing TrafCtrls for RSM file: " + m_sFile);
                }
            }
        }
References cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTdFileFormat, cc.ctrl.TrafCtrl.getId(), cc.rsm.RsmCollect.LOGGER, cc.ctrl.TrafCtrl.m_oFullGeo, cc.ctrl.CtrlGeo.m_oTiles, cc.rsm.RsmCollect.RsmRecord.m_sFile, cc.rsm.RsmCollect.RsmRecord.m_yIds, cc.util.FileUtil.newInputStream(), and cc.ctrl.proc.ProcCtrl.updateIndex().
Referenced by cc.rsm.RsmCollect.run().
compareTo()
int cc.rsm.RsmCollect.RsmRecord.compareTo (RsmRecord o) inline
Definition at line 390 of file RsmCollect.java.
        {
            return m_sId.compareTo(o.m_sId);
        }
References cc.rsm.RsmCollect.RsmRecord.m_sId.
Member Data Documentation
m_bCurrent
boolean cc.rsm.RsmCollect.RsmRecord.m_bCurrent = true package
Definition at line 376 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.run().
m_bNew
boolean cc.rsm.RsmCollect.RsmRecord.m_bNew = true package
Definition at line 377 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.run().
m_sFile
String cc.rsm.RsmCollect.RsmRecord.m_sFile package
Definition at line 375 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.RsmRecord.RsmRecord(), cc.rsm.RsmCollect.RsmRecord.cleanup(), cc.rsm.RsmCollect.writeCurrent(), and cc.rsm.RsmCollect.xmlFile().
m_sId
String cc.rsm.RsmCollect.RsmRecord.m_sId package
Definition at line 374 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.RsmRecord.RsmRecord(), cc.rsm.RsmCollect.RsmRecord.compareTo(), and cc.rsm.RsmCollect.writeCurrent().
m_yIds
ArrayList<byte[]> cc.rsm.RsmCollect.RsmRecord.m_yIds = new ArrayList() package
Definition at line 378 of file RsmCollect.java.
Referenced by cc.rsm.RsmCollect.RsmRecord.cleanup(), and cc.rsm.RsmCollect.xmlFile().
The documentation for this class was generated from the following file:
src/cc/rsm/RsmCollect.java