Carma-cloud: cc.vector_tile.VectorTile.Tile Class Reference
cc.vector_tile.VectorTile.Tile Class Reference
Classes
class Builder
class Feature
interface FeatureOrBuilder
enum GeomType
class Layer
interface LayerOrBuilder
class Value
interface ValueOrBuilder
Public Member Functions
java.util.List< cc.vector_tile.VectorTile.Tile.Layer > getLayersList ()
java.util.List<? extends cc.vector_tile.VectorTile.Tile.LayerOrBuilder > getLayersOrBuilderList ()
int getLayersCount ()
cc.vector_tile.VectorTile.Tile.Layer getLayers (int index)
cc.vector_tile.VectorTile.Tile.LayerOrBuilder getLayersOrBuilder (int index)
java.util.List< cc.vector_tile.VectorTile.Tile.Layer > getLayersList ()
cc.vector_tile.VectorTile.Tile.Layer getLayers (int index)
int getLayersCount ()
Static Public Member Functions
static cc.vector_tile.VectorTile.Tile parseFrom (java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile parseFrom (java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile parseFrom (java.io.InputStream input) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (cc.vector_tile.VectorTile.Tile prototype)
static cc.vector_tile.VectorTile.Tile getDefaultInstance ()
static com.google.protobuf.Parser< Tile > parser ()
Static Public Attributes
static final int LAYERS_FIELD_NUMBER = 3
Protected Member Functions
final java.lang.Object dynamicMethod (com.google.protobuf.GeneratedMessageLite.MethodToInvoke method, java.lang.Object arg0, java.lang.Object arg1)
Static Package Functions
[static initializer]
[static initializer]
Private Member Functions
Tile ()
void ensureLayersIsMutable ()
void setLayers (int index, cc.vector_tile.VectorTile.Tile.Layer value)
void setLayers (int index, cc.vector_tile.VectorTile.Tile.Layer.Builder builderForValue)
void addLayers (cc.vector_tile.VectorTile.Tile.Layer value)
void addLayers (int index, cc.vector_tile.VectorTile.Tile.Layer value)
void addLayers (cc.vector_tile.VectorTile.Tile.Layer.Builder builderForValue)
void addLayers (int index, cc.vector_tile.VectorTile.Tile.Layer.Builder builderForValue)
void addAllLayers (java.lang.Iterable<? extends cc.vector_tile.VectorTile.Tile.Layer > values)
void clearLayers ()
void removeLayers (int index)
Private Attributes
com.google.protobuf.Internal.ProtobufList< cc.vector_tile.VectorTile.Tile.Layer > layers_
byte memoizedIsInitialized = 2
Static Private Attributes
static final cc.vector_tile.VectorTile.Tile DEFAULT_INSTANCE
static volatile com.google.protobuf.Parser< Tile > PARSER
Detailed Description
Protobuf type vector_tile.Tile
Definition at line 34 of file VectorTile.java.
Constructor & Destructor Documentation
Tile()
cc.vector_tile.VectorTile.Tile.Tile () inline private
Definition at line 39 of file VectorTile.java.
                   {
      layers_ = emptyProtobufList();
    }
References cc.vector_tile.VectorTile.Tile.layers_.
Referenced by cc.vector_tile.VectorTile.Tile.[static initializer]().
Member Function Documentation
[static initializer]() [1/2]
cc.vector_tile.VectorTile.Tile.[static initializer] inline static package
[static initializer]() [2/2]
cc.vector_tile.VectorTile.Tile.[static initializer] inline static package
References cc.vector_tile.VectorTile.Tile.Tile(), and cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
addAllLayers()
void cc.vector_tile.VectorTile.Tile.addAllLayers (java.lang.Iterable<? extends cc.vector_tile.VectorTile.Tile.Layer > values) inline private
repeated .vector_tile.Tile.Layer layers = 3;
Definition at line 3496 of file VectorTile.java.
{
      ensureLayersIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, layers_);
    }
References cc.vector_tile.VectorTile.Tile.ensureLayersIsMutable(), and cc.vector_tile.VectorTile.Tile.layers_.
addLayers() [1/4]
void cc.vector_tile.VectorTile.Tile.addLayers (cc.vector_tile.VectorTile.Tile.Layer value) inline private
repeated .vector_tile.Tile.Layer layers = 3;
Definition at line 3459 of file VectorTile.java.
{
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLayersIsMutable();
      layers_.add(value);
    }
References cc.vector_tile.VectorTile.Tile.ensureLayersIsMutable(), and cc.vector_tile.VectorTile.Tile.layers_.
addLayers() [2/4]
void cc.vector_tile.VectorTile.Tile.addLayers (cc.vector_tile.VectorTile.Tile.Layer.Builder builderForValue) inline private
repeated .vector_tile.Tile.Layer layers = 3;
Definition at line 3480 of file VectorTile.java.
{
      ensureLayersIsMutable();
      layers_.add(builderForValue.build());
    }
References cc.vector_tile.VectorTile.Tile.ensureLayersIsMutable(), and cc.vector_tile.VectorTile.Tile.layers_.
addLayers() [3/4]
void cc.vector_tile.VectorTile.Tile.addLayers (int index, cc.vector_tile.VectorTile.Tile.Layer value) inline private
repeated .vector_tile.Tile.Layer layers = 3;
Definition at line 3469 of file VectorTile.java.
{
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLayersIsMutable();
      layers_.add(index, value);
    }
References cc.vector_tile.VectorTile.Tile.ensureLayersIsMutable(), and cc.vector_tile.VectorTile.Tile.layers_.
addLayers() [4/4]
void cc.vector_tile.VectorTile.Tile.addLayers (int index, cc.vector_tile.VectorTile.Tile.Layer.Builder builderForValue) inline private
repeated .vector_tile.Tile.Layer layers = 3;
Definition at line 3488 of file VectorTile.java.
{
      ensureLayersIsMutable();
      layers_.add(index, builderForValue.build());
    }
References cc.vector_tile.VectorTile.Tile.ensureLayersIsMutable(), and cc.vector_tile.VectorTile.Tile.layers_.
clearLayers()
void cc.vector_tile.VectorTile.Tile.clearLayers () inline private
repeated .vector_tile.Tile.Layer layers = 3;
Definition at line 3505 of file VectorTile.java.
{
      layers_ = emptyProtobufList();
    }
References cc.vector_tile.VectorTile.Tile.layers_.
dynamicMethod()
final java.lang.Object cc.vector_tile.VectorTile.Tile.dynamicMethod (com.google.protobuf.GeneratedMessageLite.MethodToInvoke method, java.lang.Object arg0, java.lang.Object arg1) inline protected
Definition at line 3716 of file VectorTile.java.
{
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new cc.vector_tile.VectorTile.Tile();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "layers_",
              cc.vector_tile.VectorTile.Tile.Layer.class,
            };
            java.lang.String info =
                "\u0001\u0001\u0000\u0000\u0003\u0003\u0001\u0000\u0001\u0001\u0003\u041b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<cc.vector_tile.VectorTile.Tile> parser = PARSER;
          if (parser == null) {
            synchronized (cc.vector_tile.VectorTile.Tile.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }
References cc.vector_tile.VectorTile.VectorTile(), cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE, cc.vector_tile.VectorTile.Tile.memoizedIsInitialized, cc.vector_tile.VectorTile.Tile.PARSER, and cc.vector_tile.VectorTile.Tile.parser().
ensureLayersIsMutable()
void cc.vector_tile.VectorTile.Tile.ensureLayersIsMutable () inline private
Definition at line 3430 of file VectorTile.java.
{
      if (!layers_.isModifiable()) {
        layers_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(layers_);
       }
    }
References cc.vector_tile.VectorTile.Tile.layers_.
Referenced by cc.vector_tile.VectorTile.Tile.addAllLayers(), cc.vector_tile.VectorTile.Tile.addLayers(), cc.vector_tile.VectorTile.Tile.removeLayers(), and cc.vector_tile.VectorTile.Tile.setLayers().
getDefaultInstance()
static cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.getDefaultInstance () inline static
Definition at line 3776 of file VectorTile.java.
{
      return DEFAULT_INSTANCE;
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
getLayers()
cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.getLayers (int index) inline
repeated .vector_tile.Tile.Layer layers = 3;
Implements cc.vector_tile.VectorTile.TileOrBuilder.
Definition at line 3420 of file VectorTile.java.
{
      return layers_.get(index);
    }
References cc.vector_tile.VectorTile.Tile.layers_.
getLayersCount()
int cc.vector_tile.VectorTile.Tile.getLayersCount () inline
repeated .vector_tile.Tile.Layer layers = 3;
Implements cc.vector_tile.VectorTile.TileOrBuilder.
Definition at line 3413 of file VectorTile.java.
{
      return layers_.size();
    }
References cc.vector_tile.VectorTile.Tile.layers_.
getLayersList()
java.util.List< cc.vector_tile.VectorTile.Tile.Layer > cc.vector_tile.VectorTile.Tile.getLayersList () inline
repeated .vector_tile.Tile.Layer layers = 3;
Implements cc.vector_tile.VectorTile.TileOrBuilder.
Definition at line 3399 of file VectorTile.java.
{
      return layers_;
    }
References cc.vector_tile.VectorTile.Tile.layers_.
getLayersOrBuilder()
cc.vector_tile.VectorTile.Tile.LayerOrBuilder cc.vector_tile.VectorTile.Tile.getLayersOrBuilder (int index) inline
repeated .vector_tile.Tile.Layer layers = 3;
Definition at line 3426 of file VectorTile.java.
                   {
      return layers_.get(index);
    }
References cc.vector_tile.VectorTile.Tile.layers_.
getLayersOrBuilderList()
java.util.List<? extends cc.vector_tile.VectorTile.Tile.LayerOrBuilder > cc.vector_tile.VectorTile.Tile.getLayersOrBuilderList () inline
repeated .vector_tile.Tile.Layer layers = 3;
Definition at line 3406 of file VectorTile.java.
{
      return layers_;
    }
References cc.vector_tile.VectorTile.Tile.layers_.
newBuilder() [1/2]
static Builder cc.vector_tile.VectorTile.Tile.newBuilder () inline static
Definition at line 3590 of file VectorTile.java.
{
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
Referenced by cc.ws.CtrlTiles.doGet(), cc.ws.TrackTiles.doGet(), and cc.ws.ValidateXodrTiles.doGet().
newBuilder() [2/2]
static Builder cc.vector_tile.VectorTile.Tile.newBuilder (cc.vector_tile.VectorTile.Tile prototype) inline static
Definition at line 3593 of file VectorTile.java.
{
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
parseDelimitedFrom() [1/2]
static cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 3566 of file VectorTile.java.
{
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE, and cc.vector_tile.VectorTile.Tile.parseDelimitedFrom().
Referenced by cc.vector_tile.VectorTile.Tile.parseDelimitedFrom().
parseDelimitedFrom() [2/2]
static cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 3570 of file VectorTile.java.
{
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE, and cc.vector_tile.VectorTile.Tile.parseDelimitedFrom().
parseFrom() [1/10]
static cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 3542 of file VectorTile.java.
{
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
parseFrom() [2/10]
static cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 3547 of file VectorTile.java.
{
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
parseFrom() [3/10]
static cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 3529 of file VectorTile.java.
{
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
parseFrom() [4/10]
static cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 3535 of file VectorTile.java.
{
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
parseFrom() [5/10]
static cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 3576 of file VectorTile.java.
{
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
parseFrom() [6/10]
static cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 3582 of file VectorTile.java.
{
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
parseFrom() [7/10]
static cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 3554 of file VectorTile.java.
{
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
parseFrom() [8/10]
static cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 3559 of file VectorTile.java.
{
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
parseFrom() [9/10]
static cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.parseFrom (java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 3516 of file VectorTile.java.
{
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
parseFrom() [10/10]
static cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.parseFrom (java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 3522 of file VectorTile.java.
{
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
parser()
static com.google.protobuf.Parser< Tile > cc.vector_tile.VectorTile.Tile.parser () inline static
Definition at line 3782 of file VectorTile.java.
{
      return DEFAULT_INSTANCE.getParserForType();
    }
References cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE.
Referenced by cc.vector_tile.VectorTile.Tile.dynamicMethod().
removeLayers()
void cc.vector_tile.VectorTile.Tile.removeLayers (int index) inline private
repeated .vector_tile.Tile.Layer layers = 3;
Definition at line 3511 of file VectorTile.java.
{
      ensureLayersIsMutable();
      layers_.remove(index);
    }
References cc.vector_tile.VectorTile.Tile.ensureLayersIsMutable(), and cc.vector_tile.VectorTile.Tile.layers_.
setLayers() [1/2]
void cc.vector_tile.VectorTile.Tile.setLayers (int index, cc.vector_tile.VectorTile.Tile.Layer value) inline private
repeated .vector_tile.Tile.Layer layers = 3;
Definition at line 3440 of file VectorTile.java.
{
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLayersIsMutable();
      layers_.set(index, value);
    }
References cc.vector_tile.VectorTile.Tile.ensureLayersIsMutable(), and cc.vector_tile.VectorTile.Tile.layers_.
setLayers() [2/2]
void cc.vector_tile.VectorTile.Tile.setLayers (int index, cc.vector_tile.VectorTile.Tile.Layer.Builder builderForValue) inline private
repeated .vector_tile.Tile.Layer layers = 3;
Definition at line 3451 of file VectorTile.java.
{
      ensureLayersIsMutable();
      layers_.set(index, builderForValue.build());
    }
References cc.vector_tile.VectorTile.Tile.ensureLayersIsMutable(), and cc.vector_tile.VectorTile.Tile.layers_.
Member Data Documentation
DEFAULT_INSTANCE
final cc.vector_tile.VectorTile.Tile cc.vector_tile.VectorTile.Tile.DEFAULT_INSTANCE static private
Definition at line 3765 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Builder.Builder(), cc.vector_tile.VectorTile.Tile.[static initializer](), cc.vector_tile.VectorTile.Tile.dynamicMethod(), cc.vector_tile.VectorTile.Tile.getDefaultInstance(), cc.vector_tile.VectorTile.Tile.newBuilder(), cc.vector_tile.VectorTile.Tile.parseDelimitedFrom(), cc.vector_tile.VectorTile.Tile.parseFrom(), and cc.vector_tile.VectorTile.Tile.parser().
layers_
com.google.protobuf.Internal.ProtobufList<cc.vector_tile.VectorTile.Tile.Layer> cc.vector_tile.VectorTile.Tile.layers_ private
Definition at line 3394 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Tile(), cc.vector_tile.VectorTile.Tile.addAllLayers(), cc.vector_tile.VectorTile.Tile.addLayers(), cc.vector_tile.VectorTile.Tile.clearLayers(), cc.vector_tile.VectorTile.Tile.ensureLayersIsMutable(), cc.vector_tile.VectorTile.Tile.getLayers(), cc.vector_tile.VectorTile.Tile.getLayersCount(), cc.vector_tile.VectorTile.Tile.getLayersList(), cc.vector_tile.VectorTile.Tile.getLayersOrBuilder(), cc.vector_tile.VectorTile.Tile.getLayersOrBuilderList(), cc.vector_tile.VectorTile.Tile.removeLayers(), and cc.vector_tile.VectorTile.Tile.setLayers().
LAYERS_FIELD_NUMBER
final int cc.vector_tile.VectorTile.Tile.LAYERS_FIELD_NUMBER = 3 static
Definition at line 3393 of file VectorTile.java.
memoizedIsInitialized
byte cc.vector_tile.VectorTile.Tile.memoizedIsInitialized = 2 private
Definition at line 3713 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.dynamicMethod().
PARSER
volatile com.google.protobuf.Parser<Tile> cc.vector_tile.VectorTile.Tile.PARSER static private
Definition at line 3780 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.dynamicMethod().
The documentation for this class was generated from the following file:
src/cc/vector_tile/VectorTile.java