Carma-cloud: cc.geosrv.xodr.rdmk.Geometry Class Reference
cc.geosrv.xodr.rdmk.Geometry Class Reference abstract
Public Member Functions
Geometry (double dS, double dX, double dY, double dH, double dL)
abstract void addPoints (Road oRoad, double dMaxStep, boolean bIncludeEnd, Proj oProj, double[] dProjPt)
void addLanePoints (Road oRoad, double dHdg, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, LaneSection oLaneSection, Proj oProj, double[] dProjPt)
int compareTo (Geometry o)
Public Attributes
double m_dS
double m_dX
double m_dY
double m_dHdg
double m_dL
Static Package Functions
static double[] addProjectedPoint (double dX, double dY, double[] dPts, Proj oProj, double[] dPoint)
Private Member Functions
void addLanePoints (LaneSection oLaneSection, ArrayList< Lane > oLanes, double dTangent, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, Proj oProj, double[] dProjPt)
Detailed Description
Author
aaron.cherney
Definition at line 19 of file Geometry.java.
Constructor & Destructor Documentation
Geometry()
cc.geosrv.xodr.rdmk.Geometry.Geometry (double dS, double dX, double dY, double dH, double dL) inline
Definition at line 27 of file Geometry.java.
    {
        m_dS = dS;
        m_dX = dX;
        m_dY = dY;
        m_dHdg = dH;
        m_dL = dL;
    }
References cc.geosrv.xodr.rdmk.Geometry.m_dHdg, cc.geosrv.xodr.rdmk.Geometry.m_dL, cc.geosrv.xodr.rdmk.Geometry.m_dS, cc.geosrv.xodr.rdmk.Geometry.m_dX, and cc.geosrv.xodr.rdmk.Geometry.m_dY.
Member Function Documentation
addLanePoints() [1/2]
void cc.geosrv.xodr.rdmk.Geometry.addLanePoints (LaneSection oLaneSection, ArrayList< Lane > oLanes, double dTangent, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, Proj oProj, double[] dProjPt) inline private
Definition at line 46 of file Geometry.java.
    {
        double dXPrevLane = dXLaneZero;
        double dYPrevLane = dYLaneZero;
        oProj.cs2cs(dXPrevLane, dYPrevLane, dProjPt);
        double dXProjPrevLane = dProjPt[0];
        double dYProjPrevLane = dProjPt[1];
        for (int nIndex = 1; nIndex < oLanes.size() - 1; nIndex++)  // center lane is index 0, null is last index
        {
            Lane oLane = oLanes.get(nIndex);
            double dLengthAlongSection = dLengthAlongRoad - oLaneSection.m_dS;
            RoadMark oInnerRdMk = RoadMark.getRoadMark(dLengthAlongSection, oLane.m_oInnerRoadMarks);
            RoadMark oOuterRdMk = RoadMark.getRoadMark(dLengthAlongSection, oLane.m_oOuterRoadMarks);
            if (oInnerRdMk.m_dS != oLane.m_dLastInnerRdMkS || oOuterRdMk.m_dS != oLane.m_dLastOuterRdMkS)
            {
                Lane oInner = oLanes.get(nIndex - 1);
                Lane oOuter = oLanes.get(nIndex + 1);
                double[] dCenter = Arrays.newDoubleArray();
                dCenter = Arrays.add(dCenter, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                oLane.m_dCenters.add(dCenter);
                oLane.m_dLastInnerRdMkS = oInnerRdMk.m_dS;
                oLane.m_dLastOuterRdMkS = oOuterRdMk.m_dS;
                int nNone = XodrUtil.getLaneType("none");
                int nInnerDir = 1;
                int nOuterDir = 1;
                int nInnerLaneType;
                int nOuterLaneType;
                if (oInner == null)
                {
                    nInnerLaneType = nNone;
                }
                else
                {
                    nInnerLaneType = oInner.m_nType;
                    if (oLane.m_nLaneIndex > 0 && oInner.m_nLaneIndex > 0 ||
                        oLane.m_nLaneIndex < 0 && oInner.m_nLaneIndex < 0)
                        nInnerDir = 0;
                }
                if (oOuter == null)
                {
                    nOuterLaneType = nNone;
                }
                else
                {
                    nOuterLaneType = oOuter.m_nType;
                    if (oLane.m_nLaneIndex > 0 && oOuter.m_nLaneIndex > 0 ||
                        oLane.m_nLaneIndex < 0 && oOuter.m_nLaneIndex < 0)
                        nOuterDir = 0;
                }
                oLane.m_nRdMkTags = Arrays.add(oLane.m_nRdMkTags, new int[]{oInnerRdMk.m_nType, oInnerRdMk.m_nColor, nInnerLaneType, nInnerDir});
                oLane.m_nRdMkTags = Arrays.add(oLane.m_nRdMkTags, new int[]{oOuterRdMk.m_nType, oOuterRdMk.m_nColor, nOuterLaneType, nOuterDir});
            }
            double[] dCenter = oLane.m_dCenters.get(oLane.m_dCenters.size() - 1);
            LaneWidth oLaneWidth = LaneWidth.getLaneWidth(dLengthAlongSection, oLane);
            double dT = MathUtil.cubic(dLengthAlongSection - oLaneWidth.m_dS, oLaneWidth.m_dA, oLaneWidth.m_dB, oLaneWidth.m_dC, oLaneWidth.m_dD);
            double dXNextLane = dXPrevLane + Math.cos(dTangent) * dT;
            double dYNextLane = dYPrevLane + Math.sin(dTangent) * dT;
            oProj.cs2cs(dXNextLane, dYNextLane, dProjPt);
            double dProjW = Geo.distance(dXProjPrevLane, dYProjPrevLane, dProjPt[0], dProjPt[1]);
            dXProjPrevLane = dProjPt[0];
            dYProjPrevLane = dProjPt[1];
            double dXPath = (dXPrevLane + dXNextLane) / 2;
            double dYPath = (dYPrevLane + dYNextLane) / 2;
            dCenter = addProjectedPoint(dXPath, dYPath, dCenter, oProj, dProjPt);
            dCenter = Arrays.add(dCenter, dProjW);
            oLane.m_dCenters.set(oLane.m_dCenters.size() - 1, dCenter);
            dXPrevLane = dXNextLane;
            dYPrevLane = dYNextLane;
        }
    }
References cc.util.Arrays.add(), cc.geosrv.xodr.rdmk.Geometry.addProjectedPoint(), cc.geosrv.Proj.cs2cs(), cc.util.MathUtil.cubic(), cc.util.Geo.distance(), cc.geosrv.xodr.XodrUtil.getLaneType(), cc.geosrv.xodr.rdmk.LaneWidth.getLaneWidth(), cc.geosrv.xodr.rdmk.RoadMark.getRoadMark(), cc.geosrv.xodr.rdmk.LaneWidth.m_dA, cc.geosrv.xodr.rdmk.LaneWidth.m_dB, cc.geosrv.xodr.rdmk.LaneWidth.m_dC, cc.geosrv.xodr.rdmk.Lane.m_dCenters, cc.geosrv.xodr.rdmk.LaneWidth.m_dD, cc.geosrv.xodr.rdmk.Lane.m_dLastInnerRdMkS, cc.geosrv.xodr.rdmk.Lane.m_dLastOuterRdMkS, cc.geosrv.xodr.rdmk.LaneSection.m_dS, cc.geosrv.xodr.rdmk.LaneWidth.m_dS, cc.geosrv.xodr.rdmk.RoadMark.m_dS, cc.geosrv.xodr.rdmk.Lane.m_nLaneIndex, cc.geosrv.xodr.rdmk.Lane.m_nRdMkTags, cc.geosrv.xodr.rdmk.Lane.m_nType, cc.geosrv.xodr.rdmk.Lane.m_oInnerRoadMarks, cc.geosrv.xodr.rdmk.Lane.m_oOuterRoadMarks, and cc.util.Arrays.newDoubleArray().
addLanePoints() [2/2]
void cc.geosrv.xodr.rdmk.Geometry.addLanePoints (Road oRoad, double dHdg, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, LaneSection oLaneSection, Proj oProj, double[] dProjPt) inline
Definition at line 39 of file Geometry.java.
    {
        addLanePoints(oLaneSection, oLaneSection.m_oLeft, dHdg + Math.PI / 2, dXLaneZero, dYLaneZero, dLengthAlongRoad, oProj, dProjPt);
        addLanePoints(oLaneSection, oLaneSection.m_oRight, dHdg - Math.PI / 2, dXLaneZero, dYLaneZero, dLengthAlongRoad, oProj, dProjPt);
    }
References cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.geosrv.xodr.rdmk.LaneSection.m_oLeft, and cc.geosrv.xodr.rdmk.LaneSection.m_oRight.
Referenced by cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.geosrv.xodr.rdmk.Arc.addPoints(), and cc.geosrv.xodr.rdmk.Line.addPoints().
addPoints()
abstract void cc.geosrv.xodr.rdmk.Geometry.addPoints (Road oRoad, double dMaxStep, boolean bIncludeEnd, Proj oProj, double[] dProjPt) abstract
Reimplemented in cc.geosrv.xodr.rdmk.Arc, and cc.geosrv.xodr.rdmk.Line.
addProjectedPoint()
static double[] cc.geosrv.xodr.rdmk.Geometry.addProjectedPoint (double dX, double dY, double[] dPts, Proj oProj, double[] dPoint) inline static package
Definition at line 118 of file Geometry.java.
    {
        oProj.cs2cs(dX, dY, dPoint);
        dX = dPoint[0]; // transform coordinates
        dY = dPoint[1]; // and set local reference
        dPts = Arrays.addAndUpdate(dPts, dX, dY);
        return dPts;
    }
References cc.util.Arrays.addAndUpdate(), and cc.geosrv.Proj.cs2cs().
Referenced by cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.geosrv.xodr.rdmk.Arc.addPoints(), cc.geosrv.xodr.rdmk.Line.addPoints(), and cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile().
compareTo()
int cc.geosrv.xodr.rdmk.Geometry.compareTo (Geometry o) inline
Definition at line 128 of file Geometry.java.
    {
        return Double.compare(m_dS, o.m_dS);
    }
References cc.geosrv.xodr.rdmk.Geometry.m_dS.
Member Data Documentation
m_dHdg
double cc.geosrv.xodr.rdmk.Geometry.m_dHdg
Definition at line 24 of file Geometry.java.
Referenced by cc.geosrv.xodr.rdmk.Geometry.Geometry(), cc.geosrv.xodr.rdmk.Arc.addPoints(), and cc.geosrv.xodr.rdmk.Line.addPoints().
m_dL
double cc.geosrv.xodr.rdmk.Geometry.m_dL
Definition at line 25 of file Geometry.java.
Referenced by cc.geosrv.xodr.rdmk.Geometry.Geometry(), cc.geosrv.xodr.rdmk.Arc.addPoints(), and cc.geosrv.xodr.rdmk.Line.addPoints().
m_dS
double cc.geosrv.xodr.rdmk.Geometry.m_dS
Definition at line 21 of file Geometry.java.
Referenced by cc.geosrv.xodr.rdmk.Geometry.Geometry(), cc.geosrv.xodr.rdmk.Arc.addPoints(), cc.geosrv.xodr.rdmk.Line.addPoints(), and cc.geosrv.xodr.rdmk.Geometry.compareTo().
m_dX
double cc.geosrv.xodr.rdmk.Geometry.m_dX
Definition at line 22 of file Geometry.java.
Referenced by cc.geosrv.xodr.rdmk.Geometry.Geometry(), cc.geosrv.xodr.rdmk.Arc.addPoints(), and cc.geosrv.xodr.rdmk.Line.addPoints().
m_dY
double cc.geosrv.xodr.rdmk.Geometry.m_dY
Definition at line 23 of file Geometry.java.
Referenced by cc.geosrv.xodr.rdmk.Geometry.Geometry(), cc.geosrv.xodr.rdmk.Arc.addPoints(), and cc.geosrv.xodr.rdmk.Line.addPoints().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/rdmk/Geometry.java