Carma-cloud: cc.ihp.Subsegment Class Reference
cc.ihp.Subsegment Class Reference
Public Member Functions
Subsegment (CsvReader oIn, int nCols) throws IOException
void reset ()
boolean pointInside (double dX, double dY)
void generateStats ()
final void updateBoundingBox (double dX, double dY, double[] dBb)
void updateDetectors (double dSpeedLimit, double d15th, double d85th, double dDensity, double dVolume)
Public Attributes
double[] m_dCenterLine
double[] m_dGeo
double[] m_dBb
double[] m_dSpeeds = Arrays.newDoubleArray()
double m_dVolume
double m_dDensity
double m_d85th
double m_d15th
double m_dLength = 0
int m_nMaxSpeed
double m_dTarCtrlSpeed
double m_dAdvisorySpeed
double m_dPreviousAdvisorySpeed
double m_dPreviousDensity
TrafCtrl m_oCtrl = null
Detailed Description
This class represents a Subsegment of a Corridor used in the IHP2 Speed Harmonization Algorithm
Author
aaron.cherney
Definition at line 23 of file Subsegment.java.
Constructor & Destructor Documentation
Subsegment()
cc.ihp.Subsegment.Subsegment (CsvReader oIn, int nCols) throws IOException inline
Constructor for Subsegment that reads parses a line from the corridor file
Parameters
oIn CsvReader that has already called readLine() and has the current line in its buffer to parse
nCols number of columns read for the current line
Exceptions
IOException
Definition at line 119 of file Subsegment.java.
    {
        double[] dC = Arrays.newDoubleArray();
        double[] dPT = Arrays.newDoubleArray();
        double[] dNT = Arrays.newDoubleArray();
        double[] dBb = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE};
        for (int nIndex = 0; nIndex < nCols;)
        {
            double dX = Mercator.lonToMeters(oIn.parseDouble(nIndex++));
            double dY = Mercator.latToMeters(oIn.parseDouble(nIndex++));
            double dW = oIn.parseDouble(nIndex++);
            dC = Arrays.add(dC, new double[]{dX, dY, dW});
        }
        m_dCenterLine = Arrays.newDoubleArray(Arrays.size(dC) * 2);
        m_dCenterLine = Arrays.add(m_dCenterLine, new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
        double[] dSeg = new double[6];
        double dHeading = 0;
        Iterator<double[]> oIt = Arrays.iterator(dC, dSeg, 1, 3);
        while (oIt.hasNext())
        {
            oIt.next();
            dHeading = Geo.heading(dSeg[0], dSeg[1], dSeg[3], dSeg[4]);
            double dW = dSeg[2] / 2;
            double dXPrime = dSeg[0] + Math.sin(dHeading) * dW; // cos(x - pi/2) = sin(x)
            double dYPrime = dSeg[1] - Math.cos(dHeading) * dW; // sin(x - pi/2) = -cos(x)
            dNT = Arrays.add(dNT, dXPrime, dYPrime);
            updateBoundingBox(dXPrime, dYPrime, dBb);
            dXPrime = dSeg[0] - Math.sin(dHeading) * dW; // cos(x + pi/2 = -sin(x)
            dYPrime = dSeg[1] + Math.cos(dHeading) * dW; // sin(x + pi/2) = cos(x)
            dPT = Arrays.add(dPT, dXPrime, dYPrime);
            updateBoundingBox(dXPrime, dYPrime, dBb);
            m_dLength += Geo.distance(dSeg[0], dSeg[1], dSeg[3], dSeg[4]);
            m_dCenterLine = Arrays.add(m_dCenterLine, new double[]{dSeg[0], dSeg[1], dSeg[2]});
            m_dCenterLine = Arrays.add(m_dCenterLine, new double[]{(dSeg[0] + dSeg[3]) / 2, (dSeg[1] + dSeg[4]) / 2, dSeg[2]});
        }
        m_dCenterLine = Arrays.add(m_dCenterLine, new double[]{dSeg[3], dSeg[4], dSeg[5]});
        double dW = dSeg[5] / 2;
        double dXPrime = dSeg[3] + Math.sin(dHeading) * dW; // cos(x - pi/2) = sin(x)
        double dYPrime = dSeg[4] - Math.cos(dHeading) * dW; // sin(x - pi/2) = -cos(x)
        dNT = Arrays.add(dNT, dXPrime, dYPrime);
        updateBoundingBox(dXPrime, dYPrime, dBb);
        dXPrime = dSeg[3] - Math.sin(dHeading) * dW; // cos(x + pi/2 = -sin(x)
        dYPrime = dSeg[4] + Math.cos(dHeading) * dW; // sin(x + pi/2) = cos(x)
        dPT = Arrays.add(dPT, dXPrime, dYPrime);
        updateBoundingBox(dXPrime, dYPrime, dBb);
        m_dGeo = Geo.createPolygon(dPT, dNT);
        m_dGeo = Arrays.add(m_dGeo, m_dGeo[1], m_dGeo[2]);
        m_dBb = dBb;
    }
References cc.util.Arrays.add(), cc.util.Geo.createPolygon(), cc.util.Geo.distance(), cc.util.Geo.heading(), cc.util.Arrays.iterator(), cc.geosrv.Mercator.latToMeters(), cc.geosrv.Mercator.lonToMeters(), cc.ihp.Subsegment.m_dBb, cc.ihp.Subsegment.m_dCenterLine, cc.ihp.Subsegment.m_dGeo, cc.ihp.Subsegment.m_dLength, cc.util.Arrays.newDoubleArray(), cc.util.Arrays.size(), and cc.ihp.Subsegment.updateBoundingBox().
Member Function Documentation
generateStats()
void cc.ihp.Subsegment.generateStats () inline
Calculates the 15th and 85th percentiles speeds from the current speed observations
Definition at line 215 of file Subsegment.java.
    {
        int nCount = Arrays.size(m_dSpeeds) - 1;
        java.util.Arrays.sort(m_dSpeeds, 1, nCount + 1);
        int nIndex = (int)Math.round(0.85 * nCount);
        if (nIndex >= nCount)
            nIndex = nCount - 1;
        m_d85th = m_dSpeeds[nIndex + 1];
        nIndex = (int)Math.round(0.15 * nCount);
        if (nIndex >= nCount)
            nIndex = nCount - 1;
        m_d15th = m_dSpeeds[nIndex + 1];
    }
References cc.ihp.Subsegment.m_d15th, cc.ihp.Subsegment.m_d85th, cc.ihp.Subsegment.m_dSpeeds, and cc.util.Arrays.size().
pointInside()
boolean cc.ihp.Subsegment.pointInside (double dX, double dY) inline
Tests if the given point in Mercator meters is inside the subsegment
Parameters
dX x coordinate
dY y coordinate
Returns
true if the point is inside the polygon that represents the subsegment otherwise false
Definition at line 201 of file Subsegment.java.
    {
        if (Geo.isInBoundingBox(dX, dY, m_dBb[0], m_dBb[1], m_dBb[2], m_dBb[3])) // quick bounding box test
        {
            return Geo.isInsidePolygon(m_dBb, dX, dY, 1);
        }
        return false;
    }
References cc.util.Geo.isInBoundingBox(), cc.util.Geo.isInsidePolygon(), and cc.ihp.Subsegment.m_dBb.
reset()
void cc.ihp.Subsegment.reset () inline
Called at the start of each algorithm run to reset the necessary values for the algorithm
Definition at line 182 of file Subsegment.java.
    {
        m_dSpeeds[0] = 1;
        m_dVolume = 0;
        m_nMaxSpeed = Integer.MIN_VALUE;
        m_dPreviousDensity = m_dDensity;
        m_dPreviousAdvisorySpeed = m_dAdvisorySpeed;
        m_dDensity = 0;
        m_oCtrl = null;
        clear();
    }
References cc.ihp.Subsegment.m_dAdvisorySpeed, cc.ihp.Subsegment.m_dDensity, cc.ihp.Subsegment.m_dPreviousAdvisorySpeed, cc.ihp.Subsegment.m_dPreviousDensity, cc.ihp.Subsegment.m_dSpeeds, cc.ihp.Subsegment.m_dVolume, cc.ihp.Subsegment.m_nMaxSpeed, and cc.ihp.Subsegment.m_oCtrl.
updateBoundingBox()
final void cc.ihp.Subsegment.updateBoundingBox (double dX, double dY, double[] dBb) inline
Updates the bounding box of the subsegment using the given coordinates
Parameters
dX x coordinate in Mercator meters
dY y coordinate in Mercator meters
dBb Array containing the bounding box with the following format: [min_x, min_y, max_x, max_y]
Definition at line 238 of file Subsegment.java.
    {
        if (dX < dBb[0])
            dBb[0] = dX;
        if (dY < dBb[1])
            dBb[1] = dY;
        if (dX > dBb[2])
            dBb[2] = dX;
        if (dY > dBb[3])
            dBb[3] = dY;
    }
Referenced by cc.ihp.Subsegment.Subsegment().
updateDetectors()
void cc.ihp.Subsegment.updateDetectors (double dSpeedLimit, double d15th, double d85th, double dDensity, double dVolume) inline
Updates the values for the current time interval the speed harmonization algorithm is being ran for
Parameters
dSpeedLimit speed limit in m/s
d15th 15th percentile speed in m/s
d85th 85th percentile speed in m/2
dDensity density 0 <= x <= 1
dVolume volume in veh/h/lane
Definition at line 259 of file Subsegment.java.
    {
        m_nMaxSpeed = (int)Math.round(dSpeedLimit);
        m_d15th = d15th;
        m_d85th = d85th;
        m_dDensity = dDensity;
        m_dVolume = dVolume;
    }
References cc.ihp.Subsegment.m_d15th, cc.ihp.Subsegment.m_d85th, cc.ihp.Subsegment.m_dDensity, cc.ihp.Subsegment.m_dVolume, and cc.ihp.Subsegment.m_nMaxSpeed.
Referenced by cc.ihp.IHP.readDetectors().
Member Data Documentation
m_d15th
double cc.ihp.Subsegment.m_d15th
Calculated 15th percentile of speeds in the subsegment for the current time interval
Definition at line 74 of file Subsegment.java.
Referenced by cc.ihp.IHP.generateSpeedControls(), cc.ihp.Subsegment.generateStats(), and cc.ihp.Subsegment.updateDetectors().
m_d85th
double cc.ihp.Subsegment.m_d85th
Calculated 85th percentile of speeds in the subsegment for the current time interval
Definition at line 69 of file Subsegment.java.
Referenced by cc.ihp.IHP.generateSpeedControls(), cc.ihp.Subsegment.generateStats(), and cc.ihp.Subsegment.updateDetectors().
m_dAdvisorySpeed
double cc.ihp.Subsegment.m_dAdvisorySpeed
Advisory speed used when generating new traffic controls. Calculated by equations 6,7, and 8
Definition at line 95 of file Subsegment.java.
Referenced by cc.ihp.IHP.generateSpeedControls(), and cc.ihp.Subsegment.reset().
m_dBb
double [] cc.ihp.Subsegment.m_dBb
Array containing the bounding box of the subsegment in Mercator meters in order min_x, min_y, max_x, max_y
Definition at line 47 of file Subsegment.java.
Referenced by cc.ihp.Subsegment.Subsegment(), cc.ihp.Corridor.add(), and cc.ihp.Subsegment.pointInside().
m_dCenterLine
double [] cc.ihp.Subsegment.m_dCenterLine
Growable array that contains the center line of the subsegment described by 3 coordinate points (x, y, width) in Mercator meters
See also
cc.util.Arrays
Definition at line 32 of file Subsegment.java.
Referenced by cc.ihp.Subsegment.Subsegment(), and cc.ihp.IHP.generateSpeedControls().
m_dDensity
double cc.ihp.Subsegment.m_dDensity
Traffic density veh/m/lane
Definition at line 64 of file Subsegment.java.
Referenced by cc.ihp.Subsegment.reset(), and cc.ihp.Subsegment.updateDetectors().
m_dGeo
double [] cc.ihp.Subsegment.m_dGeo
Growable array that contains the points in Mercator meters that define the polygon(edges) of the subsegment. Points are in clockwise order and the polygon is closed (first point is the same as last point)
See also
cc.util.Arrays
Definition at line 41 of file Subsegment.java.
Referenced by cc.ihp.Subsegment.Subsegment().
m_dLength
double cc.ihp.Subsegment.m_dLength = 0
Length of the center line of the subsegment in Mercator meters
Definition at line 79 of file Subsegment.java.
Referenced by cc.ihp.Subsegment.Subsegment(), and cc.ihp.IHP.generateSpeedControls().
m_dPreviousAdvisorySpeed
double cc.ihp.Subsegment.m_dPreviousAdvisorySpeed
The advisory speed from the last run of the algorithm
Definition at line 100 of file Subsegment.java.
Referenced by cc.ihp.IHP.generateSpeedControls(), and cc.ihp.Subsegment.reset().
m_dPreviousDensity
double cc.ihp.Subsegment.m_dPreviousDensity
The density from the last run of the algorithm
Definition at line 105 of file Subsegment.java.
Referenced by cc.ihp.Subsegment.reset().
m_dSpeeds
double [] cc.ihp.Subsegment.m_dSpeeds = Arrays.newDoubleArray()
Growable array that contains speed observations for the current time interval
See also
cc.util.Arrays
Definition at line 54 of file Subsegment.java.
Referenced by cc.ihp.Subsegment.generateStats(), and cc.ihp.Subsegment.reset().
m_dTarCtrlSpeed
double cc.ihp.Subsegment.m_dTarCtrlSpeed
Target speed calculated by equation 4
Definition at line 89 of file Subsegment.java.
Referenced by cc.ihp.IHP.generateSpeedControls().
m_dVolume
double cc.ihp.Subsegment.m_dVolume
Traffic volume in veh/s/lane
Definition at line 59 of file Subsegment.java.
Referenced by cc.ihp.IHP.generateSpeedControls(), cc.ihp.Subsegment.reset(), and cc.ihp.Subsegment.updateDetectors().
m_nMaxSpeed
int cc.ihp.Subsegment.m_nMaxSpeed
Speed limit of the subsegment
Definition at line 84 of file Subsegment.java.
Referenced by cc.ihp.IHP.generateSpeedControls(), cc.ihp.Subsegment.reset(), and cc.ihp.Subsegment.updateDetectors().
m_oCtrl
TrafCtrl cc.ihp.Subsegment.m_oCtrl = null
Reference to the traffic control created by the algorithm for this subsegment
Definition at line 110 of file Subsegment.java.
Referenced by cc.ihp.Subsegment.reset().
The documentation for this class was generated from the following file:
src/cc/ihp/Subsegment.java