Carma-cloud: cc.geosrv.xodr.XodrJunctionParser Class Reference
cc.geosrv.xodr.XodrJunctionParser Class Reference
Public Member Functions
XodrJunctionParser ()
void startElement (String sUri, String sLocalName, String sQname, Attributes iAtt) throws SAXException
HashMap< String, String > parseXodrIntersections (Path oXodrFile) throws Exception
Package Attributes
HashMap< String, String > m_oJunctionMap = new HashMap()
Detailed Description
Author
aaron.cherney
Definition at line 23 of file XodrJunctionParser.java.
Constructor & Destructor Documentation
XodrJunctionParser()
cc.geosrv.xodr.XodrJunctionParser.XodrJunctionParser () inline
Definition at line 27 of file XodrJunctionParser.java.
    {
        super();
    }
Member Function Documentation
parseXodrIntersections()
HashMap< String, String > cc.geosrv.xodr.XodrJunctionParser.parseXodrIntersections (Path oXodrFile) throws Exception inline
Definition at line 62 of file XodrJunctionParser.java.
    {
        XMLReader iXmlReader = SAXParserFactory.newInstance().
            newSAXParser().getXMLReader();
        iXmlReader.setContentHandler(this);
        iXmlReader.setProperty("http://xml.org/sax/properties/lexical-handler", this);
        iXmlReader.parse(new InputSource(new BufferedInputStream(Files.newInputStream(oXodrFile))));
        return m_oJunctionMap;
    }
References cc.geosrv.xodr.XodrJunctionParser.m_oJunctionMap.
Referenced by cc.ctrl.proc.ProcDebug.parseMetadata(), cc.ctrl.proc.ProcDirection.parseMetadata(), and cc.ctrl.proc.ProcMaxSpeed.proc().
startElement()
void cc.geosrv.xodr.XodrJunctionParser.startElement (String sUri, String sLocalName, String sQname, Attributes iAtt) throws SAXException inline
Definition at line 34 of file XodrJunctionParser.java.
    {
        try
        {
            switch (sQname)
            {
                case "road":
                {
                    String sJunc = iAtt.getValue("junction");
                    if (sJunc != null && sJunc.compareTo("-1") != 0)
                        m_oJunctionMap.put(iAtt.getValue("id"), sJunc);
                    break;
                }
                default:
                    break;
            }
        }
        catch (Exception oEx)
        {
            throw new SAXException(oEx);
        }
    }
References cc.geosrv.xodr.XodrJunctionParser.m_oJunctionMap.
Member Data Documentation
m_oJunctionMap
HashMap<String, String> cc.geosrv.xodr.XodrJunctionParser.m_oJunctionMap = new HashMap() package
Definition at line 25 of file XodrJunctionParser.java.
Referenced by cc.geosrv.xodr.XodrJunctionParser.parseXodrIntersections(), and cc.geosrv.xodr.XodrJunctionParser.startElement().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/XodrJunctionParser.java