Carma-cloud: cc.util.FileUtil Class Reference
cc.util.FileUtil Class Reference abstract
Static Public Member Functions
static OutputStream newOutputStream (Path oPath) throws IOException
static OutputStream newOutputStream (Path oPath, Set< StandardOpenOption >oOpts, FileAttribute<?>... oAttrs) throws IOException
static InputStream newInputStream (Path oPath) throws IOException
Static Public Attributes
static FileAttribute[] DIRPERS
static FileAttribute[] FILEPERS
static Set< StandardOpenOption > APPENDTO = EnumSet.of(StandardOpenOption.WRITE, StandardOpenOption.CREATE, StandardOpenOption.APPEND)
static Set< StandardOpenOption > WRITE = EnumSet.of(StandardOpenOption.WRITE, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING)
static Set< StandardOpenOption > READ = EnumSet.of(StandardOpenOption.READ)
Detailed Description
Author
aaron.cherney
Definition at line 25 of file FileUtil.java.
Member Function Documentation
newInputStream()
static InputStream cc.util.FileUtil.newInputStream (Path oPath) throws IOException inline static
Definition at line 53 of file FileUtil.java.
    {
        return Channels.newInputStream(Files.newByteChannel(oPath, READ));
    }
References cc.util.FileUtil.READ.
Referenced by cc.ws.CtrlTiles.addControl(), cc.rsm.RsmCollect.RsmRecord.cleanup(), cc.ctrl.CreateCtrls.createCtrl(), cc.ctrl.proc.ProcCtrl.deleteControl(), cc.ws.CtrlTiles.doGet(), cc.ws.TrackTiles.doGet(), cc.ws.ValidateXodrTiles.doGet(), cc.ws.GeoLanes.doPost(), cc.ws.WxPoly.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcCtrl.getCurrentControls(), cc.util.Geo.main(), cc.ctrl.proc.ProcLatPerm.parseMetadata(), cc.ctrl.proc.ProcMaxSpeed.parseMetadata(), cc.ctrl.proc.ProcClosed.proc(), cc.ctrl.proc.ProcClosing.proc(), cc.ctrl.proc.ProcDebug.proc(), cc.ctrl.proc.ProcDebugOutlines.proc(), cc.ctrl.proc.ProcDirection.proc(), cc.ctrl.proc.ProcLatPerm.proc(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ctrl.proc.ProcOpening.proc(), cc.ctrl.proc.ProcPavement.proc(), cc.ctrl.proc.ProcSignal.proc(), cc.ctrl.proc.ProcStop.proc(), cc.ctrl.proc.ProcYield.proc(), cc.ws.TcmReqServlet.run(), cc.ws.CtrlTiles.saveEdit(), and cc.ctrl.proc.ProcCtrl.updateIndex().
newOutputStream() [1/2]
static OutputStream cc.util.FileUtil.newOutputStream (Path oPath) throws IOException inline static
Definition at line 39 of file FileUtil.java.
    {
        return newOutputStream(oPath, WRITE, FILEPERS);
    }
References cc.util.FileUtil.FILEPERS, cc.util.FileUtil.newOutputStream(), and cc.util.FileUtil.WRITE.
Referenced by cc.util.FileUtil.newOutputStream(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.ctrl.proc.ProcDebugOutlines.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcPavement.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.ctrl.TrafCtrl.writeBin(), cc.geosrv.xodr.geo.XodrGeoParser.writeClas(), cc.geosrv.xodr.pvmt.XodrPvmtParser.writeClas(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.writeClas(), cc.ctrl.proc.ProcCtrl.writeIndexFile(), cc.geosrv.xodr.geo.XodrGeoParser.writeSpeeds(), and cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
newOutputStream() [2/2]
static OutputStream cc.util.FileUtil.newOutputStream (Path oPath, Set< StandardOpenOption > oOpts, FileAttribute<?>... oAttrs) throws IOException inline static
Definition at line 46 of file FileUtil.java.
    {
        return Channels.newOutputStream(Files.newByteChannel(oPath, oOpts, oAttrs));
    }
Member Data Documentation
APPENDTO
Set<StandardOpenOption> cc.util.FileUtil.APPENDTO = EnumSet.of(StandardOpenOption.WRITE, StandardOpenOption.CREATE, StandardOpenOption.APPEND) static
Definition at line 34 of file FileUtil.java.
Referenced by cc.ws.TcmReplyServlet.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.ctrl.proc.ProcDebugOutlines.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcPavement.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.geosrv.xodr.geo.XodrGeoParser.writeClas(), cc.geosrv.xodr.pvmt.XodrPvmtParser.writeClas(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.writeClas(), cc.ctrl.proc.ProcCtrl.writeIndexFile(), cc.geosrv.xodr.geo.XodrGeoParser.writeSpeeds(), and cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
DIRPERS
FileAttribute [] cc.util.FileUtil.DIRPERS static
Initial value:
= new FileAttribute[]{PosixFilePermissions.asFileAttribute(EnumSet.of(PosixFilePermission.OWNER_READ,
        PosixFilePermission.OWNER_EXECUTE, PosixFilePermission.OWNER_WRITE,
        PosixFilePermission.GROUP_EXECUTE, PosixFilePermission.GROUP_READ,
        PosixFilePermission.OTHERS_READ, PosixFilePermission.OTHERS_EXECUTE))}
Definition at line 27 of file FileUtil.java.
Referenced by cc.ihp.IHP.generateSpeedControls(), cc.ws.CtrlTiles.init(), cc.ws.ValidateXodrTiles.init(), cc.geosrv.xodr.geo.XodrGeoParser.parseXodrToCLA(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.parseXodrToCLA(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.ctrl.proc.ProcDebugOutlines.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxPlatoonSize.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcMinPlatoonHdwy.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcPavement.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.ihp.IHP.saveParameters(), cc.ctrl.TrafCtrl.writeBin(), cc.ctrl.proc.ProcDebug.writeGeoLanes(), and cc.ctrl.TrafCtrl.writeJson().
FILEPERS
FileAttribute [] cc.util.FileUtil.FILEPERS static
Initial value:
= new FileAttribute[]{PosixFilePermissions.asFileAttribute(EnumSet.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE,
        PosixFilePermission.GROUP_READ, PosixFilePermission.OTHERS_READ))}
Definition at line 31 of file FileUtil.java.
Referenced by cc.ihp.IHP.generateSpeedControls(), cc.util.FileUtil.newOutputStream(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.ctrl.proc.ProcDebugOutlines.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcPavement.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.ihp.IHP.saveGeo(), cc.ihp.IHP.updateDetectors(), cc.geosrv.xodr.geo.XodrGeoParser.writeClas(), cc.geosrv.xodr.pvmt.XodrPvmtParser.writeClas(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.writeClas(), cc.ctrl.proc.ProcDebug.writeGeoLanes(), cc.ctrl.proc.ProcCtrl.writeIndexFile(), cc.ctrl.TrafCtrl.writeJson(), cc.geosrv.xodr.geo.XodrGeoParser.writeSpeeds(), and cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
READ
Set<StandardOpenOption> cc.util.FileUtil.READ = EnumSet.of(StandardOpenOption.READ) static
Definition at line 36 of file FileUtil.java.
Referenced by cc.util.FileUtil.newInputStream().
WRITE
Set<StandardOpenOption> cc.util.FileUtil.WRITE = EnumSet.of(StandardOpenOption.WRITE, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING) static
Definition at line 35 of file FileUtil.java.
Referenced by cc.util.FileUtil.newOutputStream(), cc.ihp.IHP.saveGeo(), cc.ihp.IHP.saveParameters(), cc.ihp.IHP.updateDetectors(), cc.rsm.RsmCollect.writeCurrent(), cc.ctrl.proc.ProcDebug.writeGeoLanes(), and cc.ctrl.TrafCtrl.writeJson().
The documentation for this class was generated from the following file:
src/cc/util/FileUtil.java