Carma-cloud: cc.geosrv.xodr.rdmk.Arc Class Reference
cc.geosrv.xodr.rdmk.Arc Class Reference
Public Member Functions
Arc (double dS, double dX, double dY, double dH, double dL, double dC)
void addPoints (Road oRoad, double dMaxStep, boolean bIncludeEnd, Proj oProj, double[] dProjPt)
Public Member Functions inherited from cc.geosrv.xodr.rdmk.Geometry
Geometry (double dS, double dX, double dY, double dH, double dL)
abstract void addPoints (Road oRoad, double dMaxStep, boolean bIncludeEnd, Proj oProj, double[] dProjPt)
void addLanePoints (Road oRoad, double dHdg, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, LaneSection oLaneSection, Proj oProj, double[] dProjPt)
int compareTo (Geometry o)
Public Attributes
double m_dC
Public Attributes inherited from cc.geosrv.xodr.rdmk.Geometry
double m_dS
double m_dX
double m_dY
double m_dHdg
double m_dL
Additional Inherited Members
Static Package Functions inherited from cc.geosrv.xodr.rdmk.Geometry
static double[] addProjectedPoint (double dX, double dY, double[] dPts, Proj oProj, double[] dPoint)
Detailed Description
Author
aaron.cherney
Definition at line 18 of file Arc.java.
Constructor & Destructor Documentation
Arc()
cc.geosrv.xodr.rdmk.Arc.Arc (double dS, double dX, double dY, double dH, double dL, double dC) inline
Definition at line 22 of file Arc.java.
    {
        super(dS, dX, dY, dH, dL);
        m_dC = dC;
    }
References cc.geosrv.xodr.rdmk.Arc.m_dC.
Member Function Documentation
addPoints()
void cc.geosrv.xodr.rdmk.Arc.addPoints (Road oRoad, double dMaxStep, boolean bIncludeEnd, Proj oProj, double[] dProjPt) inline
Reimplemented from cc.geosrv.xodr.rdmk.Geometry.
Definition at line 30 of file Arc.java.
    {
        try
        {
            int nLimit;
            double dEndDistOnRoad = m_dS + m_dL;
            ArrayDeque<LaneSection> oDeque = new ArrayDeque();
            oRoad.getLaneSections(oDeque, m_dS, dEndDistOnRoad);
            double dR = 1.0 / m_dC;
            double dH = m_dX + dR * Math.cos(m_dHdg + Mercator.PI_OVER_TWO);
            double dK = m_dY + dR * Math.sin(m_dHdg + Mercator.PI_OVER_TWO);
            double dInitTheta = m_dHdg + 3.0 * Mercator.PI_OVER_TWO;
            double dTotalAngle = 0;
            while (!oDeque.isEmpty())
            {
                LaneSection oSection = oDeque.removeFirst();
                double dStart = Math.max(m_dS, oSection.m_dS);
                double dEnd = oDeque.isEmpty() ? dEndDistOnRoad : oDeque.getFirst().m_dS;
                double dLength = dEnd - dStart;
                if (dMaxStep > dLength)
                    nLimit = 1;
                else
                    nLimit = (int)(dLength / dMaxStep) + 1;
                double dTheta = dLength * m_dC;
                oRoad.m_dLaneZero = Arrays.ensureCapacity(oRoad.m_dLaneZero, nLimit * 2);
                oRoad.m_dTrack = Arrays.ensureCapacity(oRoad.m_dTrack, nLimit * 2);
                double dAngleStep = dTheta / nLimit;
                double dLengthStep = dLength / nLimit;
                if (bIncludeEnd && oDeque.isEmpty()) // add last point for last section and last geometry
                    ++nLimit;
                for (int i = 0; i < nLimit; i++)
                {
                    double dAngle = dInitTheta + dTotalAngle;
                    dTotalAngle += dAngleStep;
                    double dX = dH + dR * Math.cos(dAngle);
                    double dY = dK + dR * Math.sin(dAngle);
                    oRoad.m_dTrack = addProjectedPoint(dX, dY, oRoad.m_dTrack, oProj, dProjPt);
                    oRoad.m_dTrack = Arrays.add(oRoad.m_dTrack, 0);
                    double dLengthAlongRoad = dLengthStep * i + dStart;
                    LaneOffset oLaneOffset = LaneOffset.getLaneOffset(dLengthAlongRoad, oRoad.m_oLaneOffsets);
                    double dHdg = m_dHdg + dTotalAngle;
                    double dT = MathUtil.cubic(dLengthAlongRoad - oLaneOffset.m_dS, oLaneOffset.m_dA, oLaneOffset.m_dB, oLaneOffset.m_dC, oLaneOffset.m_dD);
                    double dXLaneZero = dX - Math.sin(dHdg) * dT;
                    double dYLaneZero = dY + Math.cos(dHdg) * dT;
                    oRoad.m_dLaneZero = addProjectedPoint(dXLaneZero, dYLaneZero, oRoad.m_dLaneZero, oProj, dProjPt);
                    oRoad.m_dLaneZero = Arrays.add(oRoad.m_dLaneZero, 0);
                    addLanePoints(oRoad, dHdg, dXLaneZero, dYLaneZero, dLengthAlongRoad, oSection, oProj, dProjPt);
                }
                dTotalAngle -= dAngleStep;
            }
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.util.Arrays.add(), cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.geosrv.xodr.rdmk.Geometry.addProjectedPoint(), cc.util.MathUtil.cubic(), cc.util.Arrays.ensureCapacity(), cc.geosrv.xodr.rdmk.LaneOffset.getLaneOffset(), cc.geosrv.xodr.rdmk.Road.getLaneSections(), cc.geosrv.xodr.rdmk.LaneOffset.m_dA, cc.geosrv.xodr.rdmk.LaneOffset.m_dB, cc.geosrv.xodr.rdmk.Arc.m_dC, cc.geosrv.xodr.rdmk.LaneOffset.m_dC, cc.geosrv.xodr.rdmk.LaneOffset.m_dD, cc.geosrv.xodr.rdmk.Geometry.m_dHdg, cc.geosrv.xodr.rdmk.Geometry.m_dL, cc.geosrv.xodr.rdmk.Road.m_dLaneZero, cc.geosrv.xodr.rdmk.Geometry.m_dS, cc.geosrv.xodr.rdmk.LaneOffset.m_dS, cc.geosrv.xodr.rdmk.LaneSection.m_dS, cc.geosrv.xodr.rdmk.Road.m_dTrack, cc.geosrv.xodr.rdmk.Geometry.m_dX, cc.geosrv.xodr.rdmk.Geometry.m_dY, cc.geosrv.xodr.rdmk.Road.m_oLaneOffsets, and cc.geosrv.Mercator.PI_OVER_TWO.
Member Data Documentation
m_dC
double cc.geosrv.xodr.rdmk.Arc.m_dC
Definition at line 20 of file Arc.java.
Referenced by cc.geosrv.xodr.rdmk.Arc.Arc(), and cc.geosrv.xodr.rdmk.Arc.addPoints().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/rdmk/Arc.java