Carma-cloud: cc.ctrl.proc.ProcMaxSpeed Class Reference
cc.ctrl.proc.ProcMaxSpeed Class Reference
Classes
class SpdMapping
Public Member Functions
ProcMaxSpeed (String sLineArcDir, String sXodrDir)
void parseMetadata (Path oSource) throws Exception
ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
ProcCtrl (String sLineArcDir)
void parseMetadata (String sSource) throws Exception
abstract void parseMetadata (Path oSource) throws Exception
void process (String sLineArcsFile, double dTol) throws Exception
abstract ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Static Public Member Functions
static void renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
Static Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
static void setStaticVariables (double dStep, String sDir, String sTdFF, int nZoom)
static void updateTiles (ArrayList< int[]> oTiles, ArrayList< int[]> oCtrlTiles)
static void updateTileRange (int[] nTileIndices, int[] nTmpTiles)
static ArrayList< CtrlLineArcs > combineLaneByRoad (ArrayList< CtrlLineArcs > oLineArcs, double dTol)
static void writeIndexFile (ArrayList< TrafCtrl > oCtrls, int nX, int nY) throws IOException
static void updateIndex (String sIndexFile, TrafCtrl oCtrl, long lTimestamp) throws IOException
static void renderCtrls (String sCtrlType, ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
static boolean deleteControl (String sId) throws Exception
static boolean deleteControl (TrafCtrl oCtrl)
static ArrayList< TrafCtrl > getCurrentControls (int nCtrlType, double dMinLon, double dMinLat, double dMaxLon, double dMaxLat, boolean bLoadFullGeo)
Protected Member Functions
void proc (String sLineArcsFile, double dTol) throws Exception
abstract void proc (String sLineArcsFile, double dTol) throws Exception
Private Attributes
String m_sXodrDir
ArrayList< SpdMapping > m_oSpds
HashMap< String, String > m_oJunctions
Static Private Attributes
static double[] SIGN = new double[]{-0.5, 0.33, 0.5, 0.33, 0.5, -0.33, -0.5, -0.33}
static int DEFAULTSPD = 25
Additional Inherited Members
Public Attributes inherited from cc.ctrl.proc.ProcCtrl
String m_sLineArcDir
Static Public Attributes inherited from cc.ctrl.proc.ProcCtrl
static final Object INDEXLOCK = new Object()
static double g_dExplodeStep
static String g_sTrafCtrlDir
static String g_sTdFileFormat
static String g_sGeolanesDir
static int g_nDefaultZoom = Integer.MIN_VALUE
static final byte CC = 0
static final byte RSM = 1
static final byte IHP2 = 2
Static Protected Member Functions inherited from cc.ctrl.proc.ProcCtrl
static boolean checkTileRange (int[] nTileIndices)
Static Protected Attributes inherited from cc.ctrl.proc.ProcCtrl
static final double WIDTHTH = 1.5
static final double LENLOWTH = 75.0
static final double STOPLINEENDOFFSET = 0.6
static final double STOPLINELATOFFSET = 0.1
static double[][] NUMBERS
static Comparator< int[]> LANETYPECOMP
static final HashMap< String, double[]> CHARS = new HashMap()
Static Package Functions inherited from cc.ctrl.proc.ProcCtrl
[static initializer]
static double getCoordAndHeadingAtLength (double[] dPoints, double dLength, boolean bReverse, double[] dPoint)
static int getStopLine (TrafCtrl oCtrl, ArrayList< double[]> oStops)
Detailed Description
Author
aaron.cherney
Definition at line 40 of file ProcMaxSpeed.java.
Constructor & Destructor Documentation
ProcMaxSpeed()
cc.ctrl.proc.ProcMaxSpeed.ProcMaxSpeed (String sLineArcDir, String sXodrDir) inline
Definition at line 49 of file ProcMaxSpeed.java.
    {
        super(sLineArcDir);
        m_sXodrDir = sXodrDir;
    }
References cc.ctrl.proc.ProcMaxSpeed.m_sXodrDir.
Member Function Documentation
combine()
ArrayList< CtrlLineArcs > cc.ctrl.proc.ProcMaxSpeed.combine (ArrayList< CtrlLineArcs > oLanes, double dTol) inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 109 of file ProcMaxSpeed.java.
    {
        ArrayList<CtrlLineArcs> oLanesByRoads = ProcCtrl.combineLaneByRoad(oLanes, dTol);
        Collections.sort(oLanesByRoads, CtrlLineArcs.CMPBYLANE);
        ArrayList<CtrlLineArcs> oCombined = new ArrayList();
        int nIndex = oLanesByRoads.size();
        SpdMapping oSearch = new SpdMapping();
        while (nIndex-- > 0)
        {
            CtrlLineArcs oCla = oLanesByRoads.get(nIndex);
            String sRoadId = Integer.toString(XodrUtil.getRoadId(oCla.m_nLaneId));
            if (m_oJunctions.containsKey(sRoadId))
            {
                oLanesByRoads.remove(nIndex);
                oCombined.add(oCla);
            }
        }
        int nLimit = oLanesByRoads.size();
        double dSqTol = dTol * dTol;
        for (int nOuter = 0; nOuter < nLimit; nOuter++)
        {
            CtrlLineArcs oCur = oLanesByRoads.get(nOuter);
            for (int nInner = 0; nInner < nLimit; nInner++)
            {
                if (nOuter == nInner)
                    continue;
                CtrlLineArcs oCmp = oLanesByRoads.get(nInner);
                if (oCmp.m_nLaneType != oCur.m_nLaneType)
                    continue;
                int nConnect = oCur.connects(oCmp, dSqTol);
                if (nConnect == CtrlLineArcs.CON_TEND_OSTART || nConnect == CtrlLineArcs.CON_TSTART_OEND) // the pts of both lines are in the same direction
                {
                    oSearch.m_nId = oCur.m_nLaneId;
                    int nSearchIndex = Collections.binarySearch(m_oSpds, oSearch);
                    int nCurSpeed = nSearchIndex >= 0 ? m_oSpds.get(nSearchIndex).m_nSpd : DEFAULTSPD;
                    oSearch.m_nId = oCmp.m_nLaneId;
                    nSearchIndex = Collections.binarySearch(m_oSpds, oSearch);
                    int nCmpSpeed = nSearchIndex >= 0 ? m_oSpds.get(nSearchIndex).m_nSpd : DEFAULTSPD;
                    if (nCurSpeed != nCmpSpeed)
                        continue;
                    oCur.combine(oCmp, nConnect); // combine the points of oCmp into oCur's point array
                    oLanesByRoads.remove(nInner);
                    --nLimit;
                    nInner = -1; // start inner loop over
                }
            }
            oCombined.add(oCur);
        }
        return oCombined;
    }
References cc.ctrl.CtrlLineArcs.CMPBYLANE, cc.ctrl.CtrlLineArcs.combine(), cc.ctrl.proc.ProcCtrl.combineLaneByRoad(), cc.ctrl.CtrlLineArcs.CON_TEND_OSTART, cc.ctrl.CtrlLineArcs.CON_TSTART_OEND, cc.ctrl.CtrlLineArcs.connects(), cc.ctrl.proc.ProcMaxSpeed.DEFAULTSPD, cc.geosrv.xodr.XodrUtil.getRoadId(), cc.ctrl.CtrlLineArcs.m_nLaneId, cc.ctrl.CtrlLineArcs.m_nLaneType, cc.ctrl.proc.ProcMaxSpeed.m_oJunctions, and cc.ctrl.proc.ProcMaxSpeed.m_oSpds.
Referenced by cc.ctrl.proc.ProcMaxSpeed.proc().
parseMetadata()
void cc.ctrl.proc.ProcMaxSpeed.parseMetadata (Path oSource) throws Exception inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 56 of file ProcMaxSpeed.java.
    {
        m_oSpds = new ArrayList();
        try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(oSource))))
        {
            while (oIn.available() > 0)
            {
                SpdMapping oTemp = new SpdMapping(oIn.readInt(), oIn.readInt());
                int nIndex = Collections.binarySearch(m_oSpds, oTemp);
                if (nIndex < 0)
                    m_oSpds.add(~nIndex, oTemp);
            }
        }
    }
References cc.ctrl.proc.ProcMaxSpeed.m_oSpds, and cc.util.FileUtil.newInputStream().
Referenced by cc.ctrl.proc.ProcMaxSpeed.proc().
proc()
void cc.ctrl.proc.ProcMaxSpeed.proc (String sLineArcsFile, double dTol) throws Exception inline protected
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 73 of file ProcMaxSpeed.java.
    {
        parseMetadata(Paths.get(sLineArcsFile + ".spd"));
        m_oJunctions = new XodrJunctionParser().parseXodrIntersections(Paths.get(m_sXodrDir + sLineArcsFile.substring(sLineArcsFile.lastIndexOf("/")).replace(".bin", ".xodr")));
        ArrayList<TrafCtrl> oCtrls = new ArrayList();
        ArrayList<CtrlLineArcs> oLineArcs = new ArrayList();
        try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(Paths.get(sLineArcsFile)))))
        {
            while (oIn.available() > 0)
            {
                oLineArcs.add(new CtrlLineArcs(oIn));
            }
        }
        oLineArcs = combine(oLineArcs, dTol);
        ArrayList<int[]> oTiles = new ArrayList();
        int nShoulder = XodrUtil.getLaneType("shoulder");
        SpdMapping oSearch = new SpdMapping();
        for (CtrlLineArcs oCLA : oLineArcs)
        {
            oSearch.m_nId = oCLA.m_nLaneId;
            int nIndex = Collections.binarySearch(m_oSpds, oSearch);
            int nSpeed = nIndex >= 0 ? m_oSpds.get(nIndex).m_nSpd : DEFAULTSPD;
            String[] sUnits = TrafCtrlEnums.UNITS[TrafCtrlEnums.getCtrl("maxspeed")];
            nSpeed = (int)Math.round(Units.getInstance().convert(sUnits[1], sUnits[0], nSpeed));
            TrafCtrl oCtrl = new TrafCtrl("maxspeed", nSpeed, 0, oCLA.m_dLineArcs, "", true, CC);
            String sRoadId = Integer.toString(XodrUtil.getRoadId(oCLA.m_nLaneId));
            if (oCLA.m_nLaneType != nShoulder && !m_oJunctions.containsKey(sRoadId))
                oCtrls.add(oCtrl);
            oCtrl.write(g_sTrafCtrlDir, g_dExplodeStep, g_nDefaultZoom, CC);
            updateTiles(oTiles, oCtrl.m_oFullGeo.m_oTiles);
        }
        renderTiledData(oCtrls, oTiles);
    }
References cc.ctrl.proc.ProcCtrl.CC, cc.ctrl.proc.ProcMaxSpeed.combine(), cc.util.Units.convert(), cc.ctrl.proc.ProcMaxSpeed.DEFAULTSPD, cc.ctrl.proc.ProcCtrl.g_dExplodeStep, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTrafCtrlDir, cc.ctrl.TrafCtrlEnums.getCtrl(), cc.util.Units.getInstance(), cc.geosrv.xodr.XodrUtil.getLaneType(), cc.geosrv.xodr.XodrUtil.getRoadId(), cc.ctrl.TrafCtrl.m_oFullGeo, cc.ctrl.proc.ProcMaxSpeed.m_oJunctions, cc.ctrl.proc.ProcMaxSpeed.m_oSpds, cc.ctrl.CtrlGeo.m_oTiles, cc.ctrl.proc.ProcMaxSpeed.m_sXodrDir, cc.util.FileUtil.newInputStream(), cc.ctrl.proc.ProcMaxSpeed.parseMetadata(), cc.geosrv.xodr.XodrJunctionParser.parseXodrIntersections(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.TrafCtrlEnums.UNITS, cc.ctrl.proc.ProcCtrl.updateTiles(), and cc.ctrl.TrafCtrl.write().
renderTiledData()
static void cc.ctrl.proc.ProcMaxSpeed.renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException inline static
Definition at line 165 of file ProcMaxSpeed.java.
    {
        String[] sEmpty = new String[0];
        TdLayer oLayer = new TdLayer("maxspeed", new String[]{"color"}, new String[]{"white", "yellow"}, TdLayer.POLYGON);
        TdLayer oNumbers = new TdLayer("maxspeed-numbers", sEmpty, sEmpty, TdLayer.LINESTRING);
        int[] nEmpty = new int[0];
        int[] nTags = new int[2];
        double[] dPt = new double[2];
        double[] dPoint = new double[2];
        double[] dSign = new double[SIGN.length + 1];
        double[][] dNumbers = new double[NUMBERS.length][];
        int[] nNumbersPts = new int[NUMBERS.length];
        for (int nIndex = 0; nIndex < NUMBERS.length; nIndex++)
        {
            double[] dTemp = new double[NUMBERS[nIndex].length + 1];
            dTemp[0] = dTemp.length;
            dNumbers[nIndex] = dTemp;
            nNumbersPts[nIndex] = NUMBERS[nIndex].length / 2;
        }
        dSign[0] = dSign.length;
        int nSignPts = SIGN.length / 2;
        HashMap<String, double[]> oChars = new HashMap();
        HashMap<String, Integer> oCharPts = new HashMap();
        for (Entry<String, double[]> oEntry : CHARS.entrySet())
        {
            double[] dTemp = new double[oEntry.getValue().length + 1];
            dTemp[0] = dTemp.length;
            oChars.put(oEntry.getKey(), dTemp);
            oCharPts.put(oEntry.getKey(), oEntry.getValue().length / 2);
        }
        String[] sUnits = TrafCtrlEnums.UNITS[TrafCtrlEnums.getCtrl("maxspeed")];
        Units oUnits = Units.getInstance();
        for (int[] nTile : nTiles)
        {
            int nX = nTile[0];
            int nY = nTile[1];
            Files.createDirectories(Paths.get(String.format(g_sTdFileFormat, nX, 0, 0, 0)).getParent(), FileUtil.DIRPERS);
            writeIndexFile(oCtrls, nX, nY);
            oLayer.clear();
            double[] dClipBounds = TileUtil.getClippingBounds(g_nDefaultZoom, nX, nY);
            for (TrafCtrl oCtrl : oCtrls)
            {
                CtrlGeo oFullGeo = oCtrl.m_oFullGeo;
                if (Collections.binarySearch(oFullGeo.m_oTiles, nTile, Mercator.TILECOMP) < 0 || oFullGeo.m_dLength < LENLOWTH || oFullGeo.m_dAverageWidth < WIDTHTH)
                    continue;
                double dHdg = getCoordAndHeadingAtLength(oFullGeo.m_dC, 5.0, false, dPt);
                if (Double.isNaN(dHdg))
                    continue;
                double dOffsetAngle;
                if (oCtrl.m_bRegulatory)
                {
                    nTags[1] = 0;
                    dOffsetAngle = Math.PI / 2;
                }
                else
                {
                    nTags[1] = 1;
                    dOffsetAngle = -Math.PI / 2;
                }
                dPt[0] += Math.cos(dHdg + dOffsetAngle);
                dPt[1] += Math.sin(dHdg + dOffsetAngle);
                double dXc = dPt[0];
                double dYc = dPt[1];
                AffineTransform oAt = new AffineTransform();
                oAt.translate(dPt[0], dPt[1]);
                oAt.rotate(dHdg, 0, 0);
                oAt.transform(SIGN, 0, dSign, 1, nSignPts);
                double[] dSignBounds = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE};
                Iterator<double[]> oIt = Arrays.iterator(dSign, dPoint, 1, 2);
                while (oIt.hasNext())
                {
                    oIt.next();
                    Geo.updateBounds(dPoint[0], dPoint[1], dSignBounds);
                }
                nTags[1] = oCtrl.m_bRegulatory ? 0 : 1;
                if (Geo.boundingBoxesIntersect(dClipBounds, dSignBounds))
                {
                    oLayer.add(new TdFeature(dSign, nTags, oCtrl));
                    dPt[0] = dXc;
                    dPt[1] = dYc;
                    dPt[0] += Math.cos(dHdg + Mercator.PI_OVER_TWO) * 0.15;
                    dPt[1] += Math.sin(dHdg + Mercator.PI_OVER_TWO) * 0.15;
                    oAt = new AffineTransform();
                    oAt.translate(dPt[0], dPt[1]);
                    oAt.rotate(dHdg - Mercator.PI_OVER_TWO, 0, 0);
                    oAt.scale(0.45, 0.45);
                    String sVal = Integer.toString((int)Math.round(oUnits.convert(sUnits[0], sUnits[1], MathUtil.bytesToInt(oCtrl.m_yControlValue))));
                    if (sVal.length() == 1) // speed limit zero exception
                        sVal = "0" + sVal;
                    int nNumber = Integer.parseInt(Character.toString(sVal.charAt(0)));
                    oAt.transform(NUMBERS[nNumber], 0, dNumbers[nNumber], 1, nNumbersPts[nNumber]);
                    oNumbers.add(new TdFeature(dNumbers[nNumber], nEmpty, oCtrl));
                    dPt[0] = dXc;
                    dPt[1] = dYc;
                    dPt[0] += Math.cos(dHdg - Mercator.PI_OVER_TWO) * 0.15;
                    dPt[1] += Math.sin(dHdg - Mercator.PI_OVER_TWO) * 0.15;
                    oAt = new AffineTransform();
                    oAt.translate(dPt[0], dPt[1]);
                    oAt.rotate(dHdg - Mercator.PI_OVER_TWO, 0, 0);
                    oAt.scale(0.45, 0.45);
                    nNumber = Integer.parseInt(Character.toString(sVal.charAt(1)));
                    oAt.transform(NUMBERS[nNumber], 0, dNumbers[nNumber], 1, nNumbersPts[nNumber]);
                    oNumbers.add(new TdFeature(dNumbers[nNumber], nEmpty, oCtrl));
                    dPt[0] = dXc;
                    dPt[1] = dYc;
                    dPt[0] += Math.cos(dHdg) * 0.33;
                    dPt[1] += Math.sin(dHdg) * 0.33;
                    oAt = new AffineTransform();
                    oAt.translate(dPt[0], dPt[1]);
                    oAt.rotate(dHdg - Mercator.PI_OVER_TWO, 0, 0);
                    oAt.scale(0.45, 0.45);
                    oAt.transform(CHARS.get("A"), 0, oChars.get("A"), 1, oCharPts.get("A"));
                    oNumbers.add(new TdFeature(oChars.get("A"), nEmpty, oCtrl));
                    dPt[0] = dXc;
                    dPt[1] = dYc;
                    dPt[0] += Math.cos(dHdg) * 0.33;
                    dPt[1] += Math.sin(dHdg) * 0.33;
                    dPt[0] += Math.cos(dHdg + Mercator.PI_OVER_TWO) * 0.2;
                    dPt[1] += Math.sin(dHdg + Mercator.PI_OVER_TWO) * 0.2;
                    oAt = new AffineTransform();
                    oAt.translate(dPt[0], dPt[1]);
                    oAt.rotate(dHdg - Mercator.PI_OVER_TWO, 0, 0);
                    oAt.scale(0.45, 0.45);
                    oAt.transform(CHARS.get("M"), 0, oChars.get("M"), 1, oCharPts.get("M"));
                    oNumbers.add(new TdFeature(oChars.get("M"), nEmpty, oCtrl));
                    dPt[0] = dXc;
                    dPt[1] = dYc;
                    dPt[0] += Math.cos(dHdg) * 0.33;
                    dPt[1] += Math.sin(dHdg) * 0.33;
                    dPt[0] += Math.cos(dHdg - Mercator.PI_OVER_TWO) * 0.2;
                    dPt[1] += Math.sin(dHdg - Mercator.PI_OVER_TWO) * 0.2;
                    oAt = new AffineTransform();
                    oAt.translate(dPt[0], dPt[1]);
                    oAt.rotate(dHdg - Mercator.PI_OVER_TWO, 0, 0);
                    oAt.scale(0.45, 0.45);
                    oAt.transform(CHARS.get("X"), 0, oChars.get("X"), 1, oCharPts.get("X"));
                    oNumbers.add(new TdFeature(oChars.get("X"), nEmpty, oCtrl));
                    dPt[0] = dXc;
                    dPt[1] = dYc;
                    dPt[0] += Math.cos(dHdg) * -0.33;
                    dPt[1] += Math.sin(dHdg) * -0.33;
                    oAt = new AffineTransform();
                    oAt.translate(dPt[0], dPt[1]);
                    oAt.rotate(dHdg - Mercator.PI_OVER_TWO, 0, 0);
                    oAt.scale(0.45, 0.45);
                    oAt.transform(CHARS.get("P"), 0, oChars.get("P"), 1, oCharPts.get("P"));
                    oNumbers.add(new TdFeature(oChars.get("P"), nEmpty, oCtrl));
                    dPt[0] = dXc;
                    dPt[1] = dYc;
                    dPt[0] += Math.cos(dHdg) * -0.33;
                    dPt[1] += Math.sin(dHdg) * -0.33;
                    dPt[0] += Math.cos(dHdg + Mercator.PI_OVER_TWO) * 0.2;
                    dPt[1] += Math.sin(dHdg + Mercator.PI_OVER_TWO) * 0.2;
                    oAt = new AffineTransform();
                    oAt.translate(dPt[0], dPt[1]);
                    oAt.rotate(dHdg - Mercator.PI_OVER_TWO, 0, 0);
                    oAt.scale(0.45, 0.45);
                    oAt.transform(CHARS.get("M"), 0, oChars.get("M"), 1, oCharPts.get("M"));
                    oNumbers.add(new TdFeature(oChars.get("M"), nEmpty, oCtrl));
                    dPt[0] = dXc;
                    dPt[1] = dYc;
                    dPt[0] += Math.cos(dHdg) * -0.33;
                    dPt[1] += Math.sin(dHdg) * -0.33;
                    dPt[0] += Math.cos(dHdg - Mercator.PI_OVER_TWO) * 0.2;
                    dPt[1] += Math.sin(dHdg - Mercator.PI_OVER_TWO) * 0.2;
                    oAt = new AffineTransform();
                    oAt.translate(dPt[0], dPt[1]);
                    oAt.rotate(dHdg - Mercator.PI_OVER_TWO, 0, 0);
                    oAt.scale(0.45, 0.45);
                    oAt.transform(CHARS.get("H"), 0, oChars.get("H"), 1, oCharPts.get("H"));
                    oNumbers.add(new TdFeature(oChars.get("H"), nEmpty, oCtrl));
                }
            }
            if (!oLayer.isEmpty())
            {
                try (DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(String.format(g_sTdFileFormat, nX, g_nDefaultZoom, nX, nY)), FileUtil.APPENDTO, FileUtil.FILEPERS))))
                {
                    oLayer.write(oOut);
                    oNumbers.write(oOut);
                }
            }
        }
    }
References cc.util.FileUtil.APPENDTO, cc.util.Geo.boundingBoxesIntersect(), cc.util.MathUtil.bytesToInt(), cc.ctrl.proc.ProcCtrl.CHARS, cc.util.Units.convert(), cc.util.FileUtil.DIRPERS, cc.util.FileUtil.FILEPERS, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTdFileFormat, cc.util.TileUtil.getClippingBounds(), cc.ctrl.proc.ProcCtrl.getCoordAndHeadingAtLength(), cc.ctrl.TrafCtrlEnums.getCtrl(), cc.util.Units.getInstance(), cc.util.Arrays.iterator(), cc.ctrl.proc.ProcCtrl.LENLOWTH, cc.ctrl.proc.TdLayer.LINESTRING, cc.ctrl.CtrlGeo.m_dAverageWidth, cc.ctrl.CtrlGeo.m_dC, cc.ctrl.CtrlGeo.m_dLength, cc.ctrl.CtrlGeo.m_oTiles, cc.util.FileUtil.newOutputStream(), cc.ctrl.proc.ProcCtrl.NUMBERS, cc.geosrv.Mercator.PI_OVER_TWO, cc.ctrl.proc.TdLayer.POLYGON, cc.ctrl.proc.ProcMaxSpeed.SIGN, cc.geosrv.Mercator.TILECOMP, cc.ctrl.TrafCtrlEnums.UNITS, cc.util.Geo.updateBounds(), cc.ctrl.proc.ProcCtrl.WIDTHTH, cc.ctrl.proc.TdLayer.write(), and cc.ctrl.proc.ProcCtrl.writeIndexFile().
Referenced by cc.ctrl.CreateCtrls.createCtrl(), cc.ws.WxPoly.doPost(), cc.ctrl.RenderCtrl.main(), cc.rsm.RsmParser.parseRequest(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ctrl.proc.ProcCtrl.renderCtrls(), and cc.ws.CtrlTiles.splitLineArcs().
Member Data Documentation
DEFAULTSPD
int cc.ctrl.proc.ProcMaxSpeed.DEFAULTSPD = 25 static private
Definition at line 46 of file ProcMaxSpeed.java.
Referenced by cc.ctrl.proc.ProcMaxSpeed.combine(), and cc.ctrl.proc.ProcMaxSpeed.proc().
m_oJunctions
HashMap<String, String> cc.ctrl.proc.ProcMaxSpeed.m_oJunctions private
Definition at line 44 of file ProcMaxSpeed.java.
Referenced by cc.ctrl.proc.ProcMaxSpeed.combine(), and cc.ctrl.proc.ProcMaxSpeed.proc().
m_oSpds
ArrayList<SpdMapping> cc.ctrl.proc.ProcMaxSpeed.m_oSpds private
Definition at line 43 of file ProcMaxSpeed.java.
Referenced by cc.ctrl.proc.ProcMaxSpeed.combine(), cc.ctrl.proc.ProcMaxSpeed.parseMetadata(), and cc.ctrl.proc.ProcMaxSpeed.proc().
m_sXodrDir
String cc.ctrl.proc.ProcMaxSpeed.m_sXodrDir private
Definition at line 42 of file ProcMaxSpeed.java.
Referenced by cc.ctrl.proc.ProcMaxSpeed.ProcMaxSpeed(), and cc.ctrl.proc.ProcMaxSpeed.proc().
SIGN
double [] cc.ctrl.proc.ProcMaxSpeed.SIGN = new double[]{-0.5, 0.33, 0.5, 0.33, 0.5, -0.33, -0.5, -0.33} static private
Definition at line 45 of file ProcMaxSpeed.java.
Referenced by cc.ctrl.proc.ProcMaxSpeed.renderTiledData().
The documentation for this class was generated from the following file:
src/cc/ctrl/proc/ProcMaxSpeed.java