Carma-cloud: cc.geosrv.xodr.geo.Line Class Reference
cc.geosrv.xodr.geo.Line Class Reference
Public Member Functions
Line (double dS, double dX, double dY, double dH, double dL)
void addPoints (Road oRoad, double dMaxStep, boolean bIncludeEnd, Proj oProj, double[] dProjPt)
Public Member Functions inherited from cc.geosrv.xodr.geo.Geometry
Geometry (double dS, double dX, double dY, double dH, double dL)
abstract void addPoints (Road oRoad, double dMaxStep, boolean bIncludeEnd, Proj oProj, double[] dProjPt)
void addLanePoints (Road oRoad, double dHdg, double dXLaneZero, double dYLaneZero, double dLengthAlongRoad, LaneSection oLaneSection, Proj oProj, double[] dProjPt)
int compareTo (Geometry o)
Additional Inherited Members
Public Attributes inherited from cc.geosrv.xodr.geo.Geometry
double m_dS
double m_dX
double m_dY
double m_dHdg
double m_dL
Static Public Attributes inherited from cc.geosrv.xodr.geo.Geometry
static int COUNT = 0
static double PX
static double PY
Static Package Functions inherited from cc.geosrv.xodr.geo.Geometry
static double[] addProjectedPoint (double dX, double dY, double[] dPts, Proj oProj, double[] dPoint)
Detailed Description
Author
Federal Highway Administration
Definition at line 17 of file Line.java.
Constructor & Destructor Documentation
Line()
cc.geosrv.xodr.geo.Line.Line (double dS, double dX, double dY, double dH, double dL) inline
Definition at line 19 of file Line.java.
    {
        super(dS, dX, dY, dH, dL);
    }
Member Function Documentation
addPoints()
void cc.geosrv.xodr.geo.Line.addPoints (Road oRoad, double dMaxStep, boolean bIncludeEnd, Proj oProj, double[] dProjPt) inline
Reimplemented from cc.geosrv.xodr.geo.Geometry.
Definition at line 26 of file Line.java.
    {
        try
        {
            int nLimit;
            double dStep;
            double dEndDistOnRoad = m_dS + m_dL;
            ArrayDeque<LaneSection> oDeque = new ArrayDeque();
            oRoad.getLaneSections(oDeque, m_dS, dEndDistOnRoad);
            while (!oDeque.isEmpty())
            {
                LaneSection oSection = oDeque.removeFirst();
                if ((int)oSection.m_dS == 88)
                    System.currentTimeMillis();
                double dStart = Math.max(m_dS, oSection.m_dS);
                double dEnd = oDeque.isEmpty() ? dEndDistOnRoad : oDeque.getFirst().m_dS;
                double dLength = dEnd - dStart;
                double dLengthAlongGeo = dStart - m_dS;
                double dStartX = m_dX + dLengthAlongGeo * Math.cos(m_dHdg);
                double dStartY = m_dY + dLengthAlongGeo * Math.sin(m_dHdg);
                if (dMaxStep > dLength)
                {
                    nLimit = 1;
                    dStep = dLength;
                }
                else
                {
                    nLimit = (int)(dLength / dMaxStep) + 1;
                    dStep = dLength / nLimit;
                }
                oRoad.m_dTrack = Arrays.ensureCapacity(oRoad.m_dTrack, nLimit * 2);
                oRoad.m_dLaneZero = Arrays.ensureCapacity(oRoad.m_dLaneZero, nLimit * 2);
                oRoad.m_dNoProj = Arrays.ensureCapacity(oRoad.m_dNoProj, nLimit * 2);
                double dDeltaX = dStep * Math.cos(m_dHdg);
                double dDeltaY = dStep * Math.sin(m_dHdg);
                if (bIncludeEnd)
                    ++nLimit;
                for (int i = 0; i < nLimit; i++)
                {
                    double dX = dStartX + dDeltaX * i;
                    double dY = dStartY + dDeltaY * i;
                    oRoad.m_dTrack = addProjectedPoint(dX, dY, oRoad.m_dTrack, oProj, dProjPt);
                    oRoad.m_dTrack = Arrays.add(oRoad.m_dTrack, 0);
                    oRoad.m_dNoProj = Arrays.addAndUpdate(oRoad.m_dNoProj, dX, dY);
                    oRoad.m_dNoProj = Arrays.add(oRoad.m_dNoProj, 0);
                    double dLengthAlongRoad = dStep * i + dStart;
                    LaneOffset oLaneOffset = LaneOffset.getLaneOffset(dLengthAlongRoad, oRoad.m_oLaneOffsets);
                    double dT = MathUtil.cubic(dLengthAlongRoad - oLaneOffset.m_dS, oLaneOffset.m_dA, oLaneOffset.m_dB, oLaneOffset.m_dC, oLaneOffset.m_dD);
                    double dXLaneZero = dX - Math.sin(m_dHdg) * dT;
                    double dYLaneZero = dY + Math.cos(m_dHdg) * dT;
                    oRoad.m_dLaneZero = addProjectedPoint(dXLaneZero, dYLaneZero, oRoad.m_dLaneZero, oProj, dProjPt);
                    oRoad.m_dLaneZero = Arrays.add(oRoad.m_dLaneZero, 0);
                    addLanePoints(oRoad, m_dHdg, dXLaneZero, dYLaneZero, dLengthAlongRoad, oSection, oProj, dProjPt);
                }
            }
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.util.Arrays.add(), cc.util.Arrays.addAndUpdate(), cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Geometry.addProjectedPoint(), cc.util.MathUtil.cubic(), cc.util.Arrays.ensureCapacity(), cc.geosrv.xodr.geo.LaneOffset.getLaneOffset(), cc.geosrv.xodr.geo.Road.getLaneSections(), cc.geosrv.xodr.geo.LaneOffset.m_dA, cc.geosrv.xodr.geo.LaneOffset.m_dB, cc.geosrv.xodr.geo.LaneOffset.m_dC, cc.geosrv.xodr.geo.LaneOffset.m_dD, cc.geosrv.xodr.geo.Geometry.m_dHdg, cc.geosrv.xodr.geo.Geometry.m_dL, cc.geosrv.xodr.geo.Road.m_dLaneZero, cc.geosrv.xodr.geo.Road.m_dNoProj, cc.geosrv.xodr.geo.Geometry.m_dS, cc.geosrv.xodr.geo.LaneOffset.m_dS, cc.geosrv.xodr.geo.LaneSection.m_dS, cc.geosrv.xodr.geo.Road.m_dTrack, cc.geosrv.xodr.geo.Geometry.m_dX, cc.geosrv.xodr.geo.Geometry.m_dY, and cc.geosrv.xodr.geo.Road.m_oLaneOffsets.
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/geo/Line.java