Carma-cloud: cc.vector_tile.VectorTile.Tile.Layer Class Reference
cc.vector_tile.VectorTile.Tile.Layer Class Reference
Classes
class Builder
Public Member Functions
boolean hasVersion ()
int getVersion ()
boolean hasName ()
java.lang.String getName ()
com.google.protobuf.ByteString getNameBytes ()
java.util.List< cc.vector_tile.VectorTile.Tile.Feature > getFeaturesList ()
java.util.List<? extends cc.vector_tile.VectorTile.Tile.FeatureOrBuilder > getFeaturesOrBuilderList ()
int getFeaturesCount ()
cc.vector_tile.VectorTile.Tile.Feature getFeatures (int index)
cc.vector_tile.VectorTile.Tile.FeatureOrBuilder getFeaturesOrBuilder (int index)
java.util.List< java.lang.String > getKeysList ()
int getKeysCount ()
java.lang.String getKeys (int index)
com.google.protobuf.ByteString getKeysBytes (int index)
java.util.List< cc.vector_tile.VectorTile.Tile.Value > getValuesList ()
java.util.List<? extends cc.vector_tile.VectorTile.Tile.ValueOrBuilder > getValuesOrBuilderList ()
int getValuesCount ()
cc.vector_tile.VectorTile.Tile.Value getValues (int index)
cc.vector_tile.VectorTile.Tile.ValueOrBuilder getValuesOrBuilder (int index)
boolean hasExtent ()
int getExtent ()
boolean hasVersion ()
int getVersion ()
boolean hasName ()
java.lang.String getName ()
com.google.protobuf.ByteString getNameBytes ()
java.util.List< cc.vector_tile.VectorTile.Tile.Feature > getFeaturesList ()
cc.vector_tile.VectorTile.Tile.Feature getFeatures (int index)
int getFeaturesCount ()
java.util.List< java.lang.String > getKeysList ()
int getKeysCount ()
java.lang.String getKeys (int index)
com.google.protobuf.ByteString getKeysBytes (int index)
java.util.List< cc.vector_tile.VectorTile.Tile.Value > getValuesList ()
cc.vector_tile.VectorTile.Tile.Value getValues (int index)
int getValuesCount ()
boolean hasExtent ()
int getExtent ()
Static Public Member Functions
static cc.vector_tile.VectorTile.Tile.Layer parseFrom (java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile.Layer parseFrom (java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile.Layer parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile.Layer parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile.Layer parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile.Layer parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile.Layer parseFrom (java.io.InputStream input) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile.Layer parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile.Layer parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile.Layer parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile.Layer parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile.Layer parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (cc.vector_tile.VectorTile.Tile.Layer prototype)
static cc.vector_tile.VectorTile.Tile.Layer getDefaultInstance ()
static com.google.protobuf.Parser< Layer > parser ()
Static Public Attributes
static final int VERSION_FIELD_NUMBER = 15
static final int NAME_FIELD_NUMBER = 1
static final int FEATURES_FIELD_NUMBER = 2
static final int KEYS_FIELD_NUMBER = 3
static final int VALUES_FIELD_NUMBER = 4
static final int EXTENT_FIELD_NUMBER = 5
Protected Member Functions
final java.lang.Object dynamicMethod (com.google.protobuf.GeneratedMessageLite.MethodToInvoke method, java.lang.Object arg0, java.lang.Object arg1)
Static Package Functions
[static initializer]
[static initializer]
Private Member Functions
Layer ()
void setVersion (int value)
void clearVersion ()
void setName (java.lang.String value)
void clearName ()
void setNameBytes (com.google.protobuf.ByteString value)
void ensureFeaturesIsMutable ()
void setFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature value)
void setFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature.Builder builderForValue)
void addFeatures (cc.vector_tile.VectorTile.Tile.Feature value)
void addFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature value)
void addFeatures (cc.vector_tile.VectorTile.Tile.Feature.Builder builderForValue)
void addFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature.Builder builderForValue)
void addAllFeatures (java.lang.Iterable<? extends cc.vector_tile.VectorTile.Tile.Feature > values)
void clearFeatures ()
void removeFeatures (int index)
void ensureKeysIsMutable ()
void setKeys (int index, java.lang.String value)
void addKeys (java.lang.String value)
void addAllKeys (java.lang.Iterable< java.lang.String > values)
void clearKeys ()
void addKeysBytes (com.google.protobuf.ByteString value)
void ensureValuesIsMutable ()
void setValues (int index, cc.vector_tile.VectorTile.Tile.Value value)
void setValues (int index, cc.vector_tile.VectorTile.Tile.Value.Builder builderForValue)
void addValues (cc.vector_tile.VectorTile.Tile.Value value)
void addValues (int index, cc.vector_tile.VectorTile.Tile.Value value)
void addValues (cc.vector_tile.VectorTile.Tile.Value.Builder builderForValue)
void addValues (int index, cc.vector_tile.VectorTile.Tile.Value.Builder builderForValue)
void addAllValues (java.lang.Iterable<? extends cc.vector_tile.VectorTile.Tile.Value > values)
void clearValues ()
void removeValues (int index)
void setExtent (int value)
void clearExtent ()
Private Attributes
int bitField0_
int version_
java.lang.String name_
com.google.protobuf.Internal.ProtobufList< cc.vector_tile.VectorTile.Tile.Feature > features_
com.google.protobuf.Internal.ProtobufList< java.lang.String > keys_
com.google.protobuf.Internal.ProtobufList< cc.vector_tile.VectorTile.Tile.Value > values_
int extent_
byte memoizedIsInitialized = 2
Static Private Attributes
static final cc.vector_tile.VectorTile.Tile.Layer DEFAULT_INSTANCE
static volatile com.google.protobuf.Parser< Layer > PARSER
Detailed Description
Layers are described in section 4.1 of the specification
Protobuf type vector_tile.Tile.Layer
Definition at line 1984 of file VectorTile.java.
Constructor & Destructor Documentation
Layer()
cc.vector_tile.VectorTile.Tile.Layer.Layer () inline private
Definition at line 1989 of file VectorTile.java.
                      {
        version_ = 1;
        name_ = "";
        features_ = emptyProtobufList();
        keys_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
        values_ = emptyProtobufList();
        extent_ = 4096;
      }
References cc.vector_tile.VectorTile.Tile.Layer.extent_, cc.vector_tile.VectorTile.Tile.Layer.features_, cc.vector_tile.VectorTile.Tile.Layer.keys_, cc.vector_tile.VectorTile.Tile.Layer.name_, cc.vector_tile.VectorTile.Tile.Layer.values_, and cc.vector_tile.VectorTile.Tile.Layer.version_.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.[static initializer]().
Member Function Documentation
[static initializer]() [1/2]
cc.vector_tile.VectorTile.Tile.Layer.[static initializer] inline static package
[static initializer]() [2/2]
cc.vector_tile.VectorTile.Tile.Layer.[static initializer] inline static package
References cc.vector_tile.VectorTile.Tile.Layer.Layer(), and cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
addAllFeatures()
void cc.vector_tile.VectorTile.Tile.Layer.addAllFeatures (java.lang.Iterable<? extends cc.vector_tile.VectorTile.Tile.Feature > values) inline private
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2262 of file VectorTile.java.
{
        ensureFeaturesIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
            values, features_);
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureFeaturesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.features_.
addAllKeys()
void cc.vector_tile.VectorTile.Tile.Layer.addAllKeys (java.lang.Iterable< java.lang.String > values) inline private
Dictionary encoding for keys
repeated string keys = 3;
Definition at line 2381 of file VectorTile.java.
{
        ensureKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
            values, keys_);
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureKeysIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.keys_.
addAllValues()
void cc.vector_tile.VectorTile.Tile.Layer.addAllValues (java.lang.Iterable<? extends cc.vector_tile.VectorTile.Tile.Value > values) inline private
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 2564 of file VectorTile.java.
{
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
            values, values_);
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureValuesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.values_.
addFeatures() [1/4]
void cc.vector_tile.VectorTile.Tile.Layer.addFeatures (cc.vector_tile.VectorTile.Tile.Feature value) inline private
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2209 of file VectorTile.java.
{
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeaturesIsMutable();
        features_.add(value);
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureFeaturesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.features_.
addFeatures() [2/4]
void cc.vector_tile.VectorTile.Tile.Layer.addFeatures (cc.vector_tile.VectorTile.Tile.Feature.Builder builderForValue) inline private
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2238 of file VectorTile.java.
{
        ensureFeaturesIsMutable();
        features_.add(builderForValue.build());
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureFeaturesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.features_.
addFeatures() [3/4]
void cc.vector_tile.VectorTile.Tile.Layer.addFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature value) inline private
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2223 of file VectorTile.java.
{
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeaturesIsMutable();
        features_.add(index, value);
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureFeaturesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.features_.
addFeatures() [4/4]
void cc.vector_tile.VectorTile.Tile.Layer.addFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature.Builder builderForValue) inline private
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2250 of file VectorTile.java.
{
        ensureFeaturesIsMutable();
        features_.add(index, builderForValue.build());
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureFeaturesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.features_.
addKeys()
void cc.vector_tile.VectorTile.Tile.Layer.addKeys (java.lang.String value) inline private
Dictionary encoding for keys
repeated string keys = 3;
Definition at line 2366 of file VectorTile.java.
{
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeysIsMutable();
        keys_.add(value);
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureKeysIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.keys_.
addKeysBytes()
void cc.vector_tile.VectorTile.Tile.Layer.addKeysBytes (com.google.protobuf.ByteString value) inline private
Dictionary encoding for keys
repeated string keys = 3;
Definition at line 2404 of file VectorTile.java.
{
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeysIsMutable();
        keys_.add(value.toStringUtf8());
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureKeysIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.keys_.
addValues() [1/4]
void cc.vector_tile.VectorTile.Tile.Layer.addValues (cc.vector_tile.VectorTile.Tile.Value value) inline private
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 2511 of file VectorTile.java.
{
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.add(value);
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureValuesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.values_.
addValues() [2/4]
void cc.vector_tile.VectorTile.Tile.Layer.addValues (cc.vector_tile.VectorTile.Tile.Value.Builder builderForValue) inline private
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 2540 of file VectorTile.java.
{
        ensureValuesIsMutable();
        values_.add(builderForValue.build());
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureValuesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.values_.
addValues() [3/4]
void cc.vector_tile.VectorTile.Tile.Layer.addValues (int index, cc.vector_tile.VectorTile.Tile.Value value) inline private
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 2525 of file VectorTile.java.
{
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.add(index, value);
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureValuesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.values_.
addValues() [4/4]
void cc.vector_tile.VectorTile.Tile.Layer.addValues (int index, cc.vector_tile.VectorTile.Tile.Value.Builder builderForValue) inline private
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 2552 of file VectorTile.java.
{
        ensureValuesIsMutable();
        values_.add(index, builderForValue.build());
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureValuesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.values_.
clearExtent()
void cc.vector_tile.VectorTile.Tile.Layer.clearExtent () inline private
Although this is an "optional" field it is required by the specification.
See https://github.com/mapbox/vector-tile-spec/issues/47
optional uint32 extent = 5 [default = 4096];
Definition at line 2638 of file VectorTile.java.
{
        bitField0_ = (bitField0_ & ~0x00000004);
        extent_ = 4096;
      }
References cc.vector_tile.VectorTile.Tile.Layer.bitField0_, and cc.vector_tile.VectorTile.Tile.Layer.extent_.
clearFeatures()
void cc.vector_tile.VectorTile.Tile.Layer.clearFeatures () inline private
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2275 of file VectorTile.java.
{
        features_ = emptyProtobufList();
      }
References cc.vector_tile.VectorTile.Tile.Layer.features_.
clearKeys()
void cc.vector_tile.VectorTile.Tile.Layer.clearKeys () inline private
Dictionary encoding for keys
repeated string keys = 3;
Definition at line 2394 of file VectorTile.java.
{
        keys_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      }
References cc.vector_tile.VectorTile.Tile.Layer.keys_.
clearName()
void cc.vector_tile.VectorTile.Tile.Layer.clearName () inline private
required string name = 1;
Definition at line 2095 of file VectorTile.java.
{
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
      }
References cc.vector_tile.VectorTile.Tile.Layer.bitField0_, cc.vector_tile.VectorTile.Tile.Layer.getDefaultInstance(), and cc.vector_tile.VectorTile.Tile.Layer.name_.
clearValues()
void cc.vector_tile.VectorTile.Tile.Layer.clearValues () inline private
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 2577 of file VectorTile.java.
{
        values_ = emptyProtobufList();
      }
References cc.vector_tile.VectorTile.Tile.Layer.values_.
clearVersion()
void cc.vector_tile.VectorTile.Tile.Layer.clearVersion () inline private
Any compliant implementation must first read the version
number encoded in this message and choose the correct
implementation for this version number before proceeding to
decode other parts of this message.
required uint32 version = 15 [default = 1];
Definition at line 2052 of file VectorTile.java.
{
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 1;
      }
References cc.vector_tile.VectorTile.Tile.Layer.bitField0_, and cc.vector_tile.VectorTile.Tile.Layer.version_.
dynamicMethod()
final java.lang.Object cc.vector_tile.VectorTile.Tile.Layer.dynamicMethod (com.google.protobuf.GeneratedMessageLite.MethodToInvoke method, java.lang.Object arg0, java.lang.Object arg1) inline protected
Definition at line 3314 of file VectorTile.java.
{
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new cc.vector_tile.VectorTile.Tile.Layer();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case BUILD_MESSAGE_INFO: {
              java.lang.Object[] objects = new java.lang.Object[] {
                "bitField0_",
                "name_",
                "features_",
                cc.vector_tile.VectorTile.Tile.Feature.class,
                "keys_",
                "values_",
                cc.vector_tile.VectorTile.Tile.Value.class,
                "extent_",
                "version_",
              };
              java.lang.String info =
                  "\u0001\u0006\u0000\u0001\u0001\u000f\u0006\u0000\u0003\u0003\u0001\u0508\u0001\u0002" +
                  "\u001b\u0003\u001a\u0004\u041b\u0005\u000b\u0002\u000f\u050b\u0000";
              return newMessageInfo(DEFAULT_INSTANCE, info, objects);
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<cc.vector_tile.VectorTile.Tile.Layer> parser = PARSER;
            if (parser == null) {
              synchronized (cc.vector_tile.VectorTile.Tile.Layer.class) {
                parser = PARSER;
                if (parser == null) {
                  parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return memoizedIsInitialized;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }
References cc.vector_tile.VectorTile.VectorTile(), cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE, cc.vector_tile.VectorTile.Tile.Layer.memoizedIsInitialized, cc.vector_tile.VectorTile.Tile.Layer.PARSER, and cc.vector_tile.VectorTile.Tile.Layer.parser().
ensureFeaturesIsMutable()
void cc.vector_tile.VectorTile.Tile.Layer.ensureFeaturesIsMutable () inline private
Definition at line 2168 of file VectorTile.java.
{
        if (!features_.isModifiable()) {
          features_ =
              com.google.protobuf.GeneratedMessageLite.mutableCopy(features_);
         }
      }
References cc.vector_tile.VectorTile.Tile.Layer.features_.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.addAllFeatures(), cc.vector_tile.VectorTile.Tile.Layer.addFeatures(), cc.vector_tile.VectorTile.Tile.Layer.removeFeatures(), and cc.vector_tile.VectorTile.Tile.Layer.setFeatures().
ensureKeysIsMutable()
void cc.vector_tile.VectorTile.Tile.Layer.ensureKeysIsMutable () inline private
Definition at line 2338 of file VectorTile.java.
{
        if (!keys_.isModifiable()) {
          keys_ =
              com.google.protobuf.GeneratedMessageLite.mutableCopy(keys_);
         }
      }
References cc.vector_tile.VectorTile.Tile.Layer.keys_.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.addAllKeys(), cc.vector_tile.VectorTile.Tile.Layer.addKeys(), cc.vector_tile.VectorTile.Tile.Layer.addKeysBytes(), and cc.vector_tile.VectorTile.Tile.Layer.setKeys().
ensureValuesIsMutable()
void cc.vector_tile.VectorTile.Tile.Layer.ensureValuesIsMutable () inline private
Definition at line 2470 of file VectorTile.java.
{
        if (!values_.isModifiable()) {
          values_ =
              com.google.protobuf.GeneratedMessageLite.mutableCopy(values_);
         }
      }
References cc.vector_tile.VectorTile.Tile.Layer.values_.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.addAllValues(), cc.vector_tile.VectorTile.Tile.Layer.addValues(), cc.vector_tile.VectorTile.Tile.Layer.removeValues(), and cc.vector_tile.VectorTile.Tile.Layer.setValues().
getDefaultInstance()
static cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.getDefaultInstance () inline static
Definition at line 3382 of file VectorTile.java.
{
        return DEFAULT_INSTANCE;
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.clearName().
getExtent()
int cc.vector_tile.VectorTile.Tile.Layer.getExtent () inline
Although this is an "optional" field it is required by the specification.
See https://github.com/mapbox/vector-tile-spec/issues/47
optional uint32 extent = 5 [default = 4096];
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2615 of file VectorTile.java.
{
        return extent_;
      }
References cc.vector_tile.VectorTile.Tile.Layer.extent_.
getFeatures()
cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Layer.getFeatures (int index) inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2154 of file VectorTile.java.
{
        return features_.get(index);
      }
References cc.vector_tile.VectorTile.Tile.Layer.features_.
getFeaturesCount()
int cc.vector_tile.VectorTile.Tile.Layer.getFeaturesCount () inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2143 of file VectorTile.java.
{
        return features_.size();
      }
References cc.vector_tile.VectorTile.Tile.Layer.features_.
getFeaturesList()
java.util.List< cc.vector_tile.VectorTile.Tile.Feature > cc.vector_tile.VectorTile.Tile.Layer.getFeaturesList () inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2121 of file VectorTile.java.
{
        return features_;
      }
References cc.vector_tile.VectorTile.Tile.Layer.features_.
getFeaturesOrBuilder()
cc.vector_tile.VectorTile.Tile.FeatureOrBuilder cc.vector_tile.VectorTile.Tile.Layer.getFeaturesOrBuilder (int index) inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2164 of file VectorTile.java.
                     {
        return features_.get(index);
      }
References cc.vector_tile.VectorTile.Tile.Layer.features_.
getFeaturesOrBuilderList()
java.util.List<? extends cc.vector_tile.VectorTile.Tile.FeatureOrBuilder > cc.vector_tile.VectorTile.Tile.Layer.getFeaturesOrBuilderList () inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2132 of file VectorTile.java.
{
        return features_;
      }
References cc.vector_tile.VectorTile.Tile.Layer.features_.
getKeys()
java.lang.String cc.vector_tile.VectorTile.Tile.Layer.getKeys (int index) inline
Dictionary encoding for keys
repeated string keys = 3;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2322 of file VectorTile.java.
{
        return keys_.get(index);
      }
References cc.vector_tile.VectorTile.Tile.Layer.keys_.
getKeysBytes()
com.google.protobuf.ByteString cc.vector_tile.VectorTile.Tile.Layer.getKeysBytes (int index) inline
Dictionary encoding for keys
repeated string keys = 3;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2334 of file VectorTile.java.
{
        return com.google.protobuf.ByteString.copyFromUtf8(
            keys_.get(index));
      }
References cc.vector_tile.VectorTile.Tile.Layer.keys_.
getKeysCount()
int cc.vector_tile.VectorTile.Tile.Layer.getKeysCount () inline
Dictionary encoding for keys
repeated string keys = 3;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2311 of file VectorTile.java.
{
        return keys_.size();
      }
References cc.vector_tile.VectorTile.Tile.Layer.keys_.
getKeysList()
java.util.List< java.lang.String > cc.vector_tile.VectorTile.Tile.Layer.getKeysList () inline
Dictionary encoding for keys
repeated string keys = 3;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2300 of file VectorTile.java.
{
        return keys_;
      }
References cc.vector_tile.VectorTile.Tile.Layer.keys_.
getName()
java.lang.String cc.vector_tile.VectorTile.Tile.Layer.getName () inline
required string name = 1;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2070 of file VectorTile.java.
{
        return name_;
      }
References cc.vector_tile.VectorTile.Tile.Layer.name_.
getNameBytes()
com.google.protobuf.ByteString cc.vector_tile.VectorTile.Tile.Layer.getNameBytes () inline
required string name = 1;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2078 of file VectorTile.java.
{
        return com.google.protobuf.ByteString.copyFromUtf8(name_);
      }
References cc.vector_tile.VectorTile.Tile.Layer.name_.
getValues()
cc.vector_tile.VectorTile.Tile.Value cc.vector_tile.VectorTile.Tile.Layer.getValues (int index) inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2456 of file VectorTile.java.
{
        return values_.get(index);
      }
References cc.vector_tile.VectorTile.Tile.Layer.values_.
getValuesCount()
int cc.vector_tile.VectorTile.Tile.Layer.getValuesCount () inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2445 of file VectorTile.java.
{
        return values_.size();
      }
References cc.vector_tile.VectorTile.Tile.Layer.values_.
getValuesList()
java.util.List< cc.vector_tile.VectorTile.Tile.Value > cc.vector_tile.VectorTile.Tile.Layer.getValuesList () inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2423 of file VectorTile.java.
{
        return values_;
      }
References cc.vector_tile.VectorTile.Tile.Layer.values_.
getValuesOrBuilder()
cc.vector_tile.VectorTile.Tile.ValueOrBuilder cc.vector_tile.VectorTile.Tile.Layer.getValuesOrBuilder (int index) inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 2466 of file VectorTile.java.
                     {
        return values_.get(index);
      }
References cc.vector_tile.VectorTile.Tile.Layer.values_.
getValuesOrBuilderList()
java.util.List<? extends cc.vector_tile.VectorTile.Tile.ValueOrBuilder > cc.vector_tile.VectorTile.Tile.Layer.getValuesOrBuilderList () inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 2434 of file VectorTile.java.
{
        return values_;
      }
References cc.vector_tile.VectorTile.Tile.Layer.values_.
getVersion()
int cc.vector_tile.VectorTile.Tile.Layer.getVersion () inline
Any compliant implementation must first read the version
number encoded in this message and choose the correct
implementation for this version number before proceeding to
decode other parts of this message.
required uint32 version = 15 [default = 1];
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2025 of file VectorTile.java.
{
        return version_;
      }
References cc.vector_tile.VectorTile.Tile.Layer.version_.
hasExtent()
boolean cc.vector_tile.VectorTile.Tile.Layer.hasExtent () inline
Although this is an "optional" field it is required by the specification.
See https://github.com/mapbox/vector-tile-spec/issues/47
optional uint32 extent = 5 [default = 4096];
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2603 of file VectorTile.java.
{
        return ((bitField0_ & 0x00000004) != 0);
      }
References cc.vector_tile.VectorTile.Tile.Layer.bitField0_.
hasName()
boolean cc.vector_tile.VectorTile.Tile.Layer.hasName () inline
required string name = 1;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2063 of file VectorTile.java.
{
        return ((bitField0_ & 0x00000002) != 0);
      }
References cc.vector_tile.VectorTile.Tile.Layer.bitField0_.
hasVersion()
boolean cc.vector_tile.VectorTile.Tile.Layer.hasVersion () inline
Any compliant implementation must first read the version
number encoded in this message and choose the correct
implementation for this version number before proceeding to
decode other parts of this message.
required uint32 version = 15 [default = 1];
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2011 of file VectorTile.java.
{
        return ((bitField0_ & 0x00000001) != 0);
      }
References cc.vector_tile.VectorTile.Tile.Layer.bitField0_.
newBuilder() [1/2]
static Builder cc.vector_tile.VectorTile.Tile.Layer.newBuilder () inline static
Definition at line 2717 of file VectorTile.java.
{
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder(), cc.ws.CtrlTiles.doGet(), cc.ws.TrackTiles.doGet(), and cc.ws.ValidateXodrTiles.doGet().
newBuilder() [2/2]
static Builder cc.vector_tile.VectorTile.Tile.Layer.newBuilder (cc.vector_tile.VectorTile.Tile.Layer prototype) inline static
Definition at line 2720 of file VectorTile.java.
{
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
parseDelimitedFrom() [1/2]
static cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 2693 of file VectorTile.java.
{
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE, and cc.vector_tile.VectorTile.Tile.Layer.parseDelimitedFrom().
Referenced by cc.vector_tile.VectorTile.Tile.Layer.parseDelimitedFrom().
parseDelimitedFrom() [2/2]
static cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 2697 of file VectorTile.java.
{
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE, and cc.vector_tile.VectorTile.Tile.Layer.parseDelimitedFrom().
parseFrom() [1/10]
static cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 2669 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
parseFrom() [2/10]
static cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 2674 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
parseFrom() [3/10]
static cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 2656 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
parseFrom() [4/10]
static cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 2662 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
parseFrom() [5/10]
static cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 2703 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
parseFrom() [6/10]
static cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 2709 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
parseFrom() [7/10]
static cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 2681 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
parseFrom() [8/10]
static cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 2686 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
parseFrom() [9/10]
static cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.parseFrom (java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 2643 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
parseFrom() [10/10]
static cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.parseFrom (java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 2649 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
parser()
static com.google.protobuf.Parser< Layer > cc.vector_tile.VectorTile.Tile.Layer.parser () inline static
Definition at line 3388 of file VectorTile.java.
{
        return DEFAULT_INSTANCE.getParserForType();
      }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.dynamicMethod().
removeFeatures()
void cc.vector_tile.VectorTile.Tile.Layer.removeFeatures (int index) inline private
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2285 of file VectorTile.java.
{
        ensureFeaturesIsMutable();
        features_.remove(index);
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureFeaturesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.features_.
removeValues()
void cc.vector_tile.VectorTile.Tile.Layer.removeValues (int index) inline private
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 2587 of file VectorTile.java.
{
        ensureValuesIsMutable();
        values_.remove(index);
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureValuesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.values_.
setExtent()
void cc.vector_tile.VectorTile.Tile.Layer.setExtent (int value) inline private
Although this is an "optional" field it is required by the specification.
See https://github.com/mapbox/vector-tile-spec/issues/47
optional uint32 extent = 5 [default = 4096];
Definition at line 2626 of file VectorTile.java.
{
        bitField0_ |= 0x00000004;
        extent_ = value;
      }
References cc.vector_tile.VectorTile.Tile.Layer.bitField0_, and cc.vector_tile.VectorTile.Tile.Layer.extent_.
setFeatures() [1/2]
void cc.vector_tile.VectorTile.Tile.Layer.setFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature value) inline private
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2182 of file VectorTile.java.
{
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeaturesIsMutable();
        features_.set(index, value);
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureFeaturesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.features_.
setFeatures() [2/2]
void cc.vector_tile.VectorTile.Tile.Layer.setFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature.Builder builderForValue) inline private
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2197 of file VectorTile.java.
{
        ensureFeaturesIsMutable();
        features_.set(index, builderForValue.build());
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureFeaturesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.features_.
setKeys()
void cc.vector_tile.VectorTile.Tile.Layer.setKeys (int index, java.lang.String value) inline private
Dictionary encoding for keys
repeated string keys = 3;
Definition at line 2351 of file VectorTile.java.
{
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeysIsMutable();
        keys_.set(index, value);
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureKeysIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.keys_.
setName()
void cc.vector_tile.VectorTile.Tile.Layer.setName (java.lang.String value) inline private
required string name = 1;
Definition at line 2084 of file VectorTile.java.
{
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
      }
References cc.vector_tile.VectorTile.Tile.Layer.bitField0_, and cc.vector_tile.VectorTile.Tile.Layer.name_.
setNameBytes()
void cc.vector_tile.VectorTile.Tile.Layer.setNameBytes (com.google.protobuf.ByteString value) inline private
required string name = 1;
Definition at line 2102 of file VectorTile.java.
{
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value.toStringUtf8();
      }
References cc.vector_tile.VectorTile.Tile.Layer.bitField0_, and cc.vector_tile.VectorTile.Tile.Layer.name_.
setValues() [1/2]
void cc.vector_tile.VectorTile.Tile.Layer.setValues (int index, cc.vector_tile.VectorTile.Tile.Value value) inline private
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 2484 of file VectorTile.java.
{
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.set(index, value);
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureValuesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.values_.
setValues() [2/2]
void cc.vector_tile.VectorTile.Tile.Layer.setValues (int index, cc.vector_tile.VectorTile.Tile.Value.Builder builderForValue) inline private
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 2499 of file VectorTile.java.
{
        ensureValuesIsMutable();
        values_.set(index, builderForValue.build());
      }
References cc.vector_tile.VectorTile.Tile.Layer.ensureValuesIsMutable(), and cc.vector_tile.VectorTile.Tile.Layer.values_.
setVersion()
void cc.vector_tile.VectorTile.Tile.Layer.setVersion (int value) inline private
Any compliant implementation must first read the version
number encoded in this message and choose the correct
implementation for this version number before proceeding to
decode other parts of this message.
required uint32 version = 15 [default = 1];
Definition at line 2038 of file VectorTile.java.
{
        bitField0_ |= 0x00000001;
        version_ = value;
      }
References cc.vector_tile.VectorTile.Tile.Layer.bitField0_, and cc.vector_tile.VectorTile.Tile.Layer.version_.
Member Data Documentation
bitField0_
int cc.vector_tile.VectorTile.Tile.Layer.bitField0_ private
Definition at line 1997 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.clearExtent(), cc.vector_tile.VectorTile.Tile.Layer.clearName(), cc.vector_tile.VectorTile.Tile.Layer.clearVersion(), cc.vector_tile.VectorTile.Tile.Layer.hasExtent(), cc.vector_tile.VectorTile.Tile.Layer.hasName(), cc.vector_tile.VectorTile.Tile.Layer.hasVersion(), cc.vector_tile.VectorTile.Tile.Layer.setExtent(), cc.vector_tile.VectorTile.Tile.Layer.setName(), cc.vector_tile.VectorTile.Tile.Layer.setNameBytes(), and cc.vector_tile.VectorTile.Tile.Layer.setVersion().
DEFAULT_INSTANCE
final cc.vector_tile.VectorTile.Tile.Layer cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE static private
Definition at line 3371 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.Builder.Builder(), cc.vector_tile.VectorTile.Tile.Layer.[static initializer](), cc.vector_tile.VectorTile.Tile.Layer.dynamicMethod(), cc.vector_tile.VectorTile.Tile.Layer.getDefaultInstance(), cc.vector_tile.VectorTile.Tile.Layer.newBuilder(), cc.vector_tile.VectorTile.Tile.Layer.parseDelimitedFrom(), cc.vector_tile.VectorTile.Tile.Layer.parseFrom(), and cc.vector_tile.VectorTile.Tile.Layer.parser().
extent_
int cc.vector_tile.VectorTile.Tile.Layer.extent_ private
Definition at line 2593 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.Layer(), cc.vector_tile.VectorTile.Tile.Layer.clearExtent(), cc.vector_tile.VectorTile.Tile.Layer.getExtent(), and cc.vector_tile.VectorTile.Tile.Layer.setExtent().
EXTENT_FIELD_NUMBER
final int cc.vector_tile.VectorTile.Tile.Layer.EXTENT_FIELD_NUMBER = 5 static
Definition at line 2592 of file VectorTile.java.
features_
com.google.protobuf.Internal.ProtobufList<cc.vector_tile.VectorTile.Tile.Feature> cc.vector_tile.VectorTile.Tile.Layer.features_ private
Definition at line 2112 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.Layer(), cc.vector_tile.VectorTile.Tile.Layer.addAllFeatures(), cc.vector_tile.VectorTile.Tile.Layer.addFeatures(), cc.vector_tile.VectorTile.Tile.Layer.clearFeatures(), cc.vector_tile.VectorTile.Tile.Layer.ensureFeaturesIsMutable(), cc.vector_tile.VectorTile.Tile.Layer.getFeatures(), cc.vector_tile.VectorTile.Tile.Layer.getFeaturesCount(), cc.vector_tile.VectorTile.Tile.Layer.getFeaturesList(), cc.vector_tile.VectorTile.Tile.Layer.getFeaturesOrBuilder(), cc.vector_tile.VectorTile.Tile.Layer.getFeaturesOrBuilderList(), cc.vector_tile.VectorTile.Tile.Layer.removeFeatures(), and cc.vector_tile.VectorTile.Tile.Layer.setFeatures().
FEATURES_FIELD_NUMBER
final int cc.vector_tile.VectorTile.Tile.Layer.FEATURES_FIELD_NUMBER = 2 static
Definition at line 2111 of file VectorTile.java.
keys_
com.google.protobuf.Internal.ProtobufList<java.lang.String> cc.vector_tile.VectorTile.Tile.Layer.keys_ private
Definition at line 2291 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.Layer(), cc.vector_tile.VectorTile.Tile.Layer.addAllKeys(), cc.vector_tile.VectorTile.Tile.Layer.addKeys(), cc.vector_tile.VectorTile.Tile.Layer.addKeysBytes(), cc.vector_tile.VectorTile.Tile.Layer.clearKeys(), cc.vector_tile.VectorTile.Tile.Layer.ensureKeysIsMutable(), cc.vector_tile.VectorTile.Tile.Layer.getKeys(), cc.vector_tile.VectorTile.Tile.Layer.getKeysBytes(), cc.vector_tile.VectorTile.Tile.Layer.getKeysCount(), cc.vector_tile.VectorTile.Tile.Layer.getKeysList(), and cc.vector_tile.VectorTile.Tile.Layer.setKeys().
KEYS_FIELD_NUMBER
final int cc.vector_tile.VectorTile.Tile.Layer.KEYS_FIELD_NUMBER = 3 static
Definition at line 2290 of file VectorTile.java.
memoizedIsInitialized
byte cc.vector_tile.VectorTile.Tile.Layer.memoizedIsInitialized = 2 private
Definition at line 3311 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.dynamicMethod().
name_
java.lang.String cc.vector_tile.VectorTile.Tile.Layer.name_ private
Definition at line 2058 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.Layer(), cc.vector_tile.VectorTile.Tile.Layer.clearName(), cc.vector_tile.VectorTile.Tile.Layer.getName(), cc.vector_tile.VectorTile.Tile.Layer.getNameBytes(), cc.vector_tile.VectorTile.Tile.Layer.setName(), and cc.vector_tile.VectorTile.Tile.Layer.setNameBytes().
NAME_FIELD_NUMBER
final int cc.vector_tile.VectorTile.Tile.Layer.NAME_FIELD_NUMBER = 1 static
Definition at line 2057 of file VectorTile.java.
PARSER
volatile com.google.protobuf.Parser<Layer> cc.vector_tile.VectorTile.Tile.Layer.PARSER static private
Definition at line 3386 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.dynamicMethod().
values_
com.google.protobuf.Internal.ProtobufList<cc.vector_tile.VectorTile.Tile.Value> cc.vector_tile.VectorTile.Tile.Layer.values_ private
Definition at line 2414 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.Layer(), cc.vector_tile.VectorTile.Tile.Layer.addAllValues(), cc.vector_tile.VectorTile.Tile.Layer.addValues(), cc.vector_tile.VectorTile.Tile.Layer.clearValues(), cc.vector_tile.VectorTile.Tile.Layer.ensureValuesIsMutable(), cc.vector_tile.VectorTile.Tile.Layer.getValues(), cc.vector_tile.VectorTile.Tile.Layer.getValuesCount(), cc.vector_tile.VectorTile.Tile.Layer.getValuesList(), cc.vector_tile.VectorTile.Tile.Layer.getValuesOrBuilder(), cc.vector_tile.VectorTile.Tile.Layer.getValuesOrBuilderList(), cc.vector_tile.VectorTile.Tile.Layer.removeValues(), and cc.vector_tile.VectorTile.Tile.Layer.setValues().
VALUES_FIELD_NUMBER
final int cc.vector_tile.VectorTile.Tile.Layer.VALUES_FIELD_NUMBER = 4 static
Definition at line 2413 of file VectorTile.java.
version_
int cc.vector_tile.VectorTile.Tile.Layer.version_ private
Definition at line 1999 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Layer.Layer(), cc.vector_tile.VectorTile.Tile.Layer.clearVersion(), cc.vector_tile.VectorTile.Tile.Layer.getVersion(), and cc.vector_tile.VectorTile.Tile.Layer.setVersion().
VERSION_FIELD_NUMBER
final int cc.vector_tile.VectorTile.Tile.Layer.VERSION_FIELD_NUMBER = 15 static
Definition at line 1998 of file VectorTile.java.
The documentation for this class was generated from the following file:
src/cc/vector_tile/VectorTile.java