Carma-cloud: cc.ctrl.TcBounds Class Reference
cc.ctrl.TcBounds Class Reference
Public Member Functions
void setCorners (int[] nXs, int[] nYs, int nScale)
Public Attributes
long m_lOldest
int[] m_nCorners = new int[10]
int[] m_nBB = new int[] {Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MIN_VALUE, Integer.MIN_VALUE}
Private Member Functions
void setBB ()
Detailed Description
Author
aaron.cherney
Definition at line 15 of file TcBounds.java.
Member Function Documentation
setBB()
void cc.ctrl.TcBounds.setBB () inline private
Definition at line 37 of file TcBounds.java.
    {
        for (int nIndex = 2; nIndex < m_nCorners.length;)
        {
            int nLon = m_nCorners[nIndex++];
            int nLat = m_nCorners[nIndex++];
            if (nLon < m_nBB[0])
                m_nBB[0] = nLon;
            if (nLat < m_nBB[1])
                m_nBB[1] = nLat;
            if (nLon > m_nBB[2])
                m_nBB[2] = nLon;
            if (nLat > m_nBB[3])
                m_nBB[3] = nLat;
        }
    }
References cc.ctrl.TcBounds.m_nBB, and cc.ctrl.TcBounds.m_nCorners.
Referenced by cc.ctrl.TcBounds.setCorners().
setCorners()
void cc.ctrl.TcBounds.setCorners (int[] nXs, int[] nYs, int nScale) inline
Definition at line 21 of file TcBounds.java.
    {
        double dX = Mercator.lonToMeters(Geo.fromIntDeg(m_nCorners[0])); // index 0 is origin lon
        double dY = Mercator.latToMeters(Geo.fromIntDeg(m_nCorners[1])); // index 1 is origin lat
        double dMultiplier = Math.pow(10, nScale);
        for (int i = 0; i < nXs.length; i++)
        {
            m_nCorners[i * 2 + 2] = Geo.toIntDeg(Mercator.xToLon(dX + nXs[i] * dMultiplier));
            m_nCorners[i * 2 + 3] = Geo.toIntDeg(Mercator.yToLat(dY + nYs[i] * dMultiplier));
        }
        m_nCorners[8] = m_nCorners[0];
        m_nCorners[9] = m_nCorners[1];
        setBB();
    }
References cc.util.Geo.fromIntDeg(), cc.geosrv.Mercator.latToMeters(), cc.geosrv.Mercator.lonToMeters(), cc.ctrl.TcBounds.m_nCorners, cc.ctrl.TcBounds.setBB(), cc.util.Geo.toIntDeg(), cc.geosrv.Mercator.xToLon(), and cc.geosrv.Mercator.yToLat().
Referenced by cc.ctrl.TcmReqParser.endElement(), and cc.ctrl.TcmReqParser2.endElement().
Member Data Documentation
m_lOldest
long cc.ctrl.TcBounds.m_lOldest
Definition at line 17 of file TcBounds.java.
Referenced by cc.ws.TcmReqServlet.run().
m_nBB
int [] cc.ctrl.TcBounds.m_nBB = new int[] {Integer.MAX_VALUE, Integer.MAX_VALUE, Integer.MIN_VALUE, Integer.MIN_VALUE}
Definition at line 19 of file TcBounds.java.
Referenced by cc.ctrl.TcBounds.setBB().
m_nCorners
int [] cc.ctrl.TcBounds.m_nCorners = new int[10]
Definition at line 18 of file TcBounds.java.
Referenced by cc.ctrl.TcmReqParser.endElement(), cc.ctrl.TcmReqParser2.endElement(), cc.ws.TcmReqServlet.run(), cc.ctrl.TcBounds.setBB(), and cc.ctrl.TcBounds.setCorners().
The documentation for this class was generated from the following file:
src/cc/ctrl/TcBounds.java