Carma-cloud: cc.ws.UserMgr Class Reference
cc.ws.UserMgr Class Reference
Public Member Functions
UserMgr ()
void init ()
void doPost (HttpServletRequest oReq, HttpServletResponse oRep)
Static Public Member Functions
static void main (String[] sArgs)
Protected Attributes
ArrayList< User > m_oCreds = new ArrayList()
Static Protected Attributes
static final Object LOCK = new Object()
static MessageDigest DIGEST
Static Package Functions
[static initializer]
static void getSecurePassword (String sPass, byte[] ySalt, StringBuilder sBuf)
Detailed Description
Definition at line 16 of file UserMgr.java.
Constructor & Destructor Documentation
UserMgr()
cc.ws.UserMgr.UserMgr () inline
Definition at line 33 of file UserMgr.java.
    {
    }
Member Function Documentation
[static initializer]()
cc.ws.UserMgr.[static initializer] inline static package
doPost()
void cc.ws.UserMgr.doPost (HttpServletRequest oReq, HttpServletResponse oRep) inline
Definition at line 55 of file UserMgr.java.
    {
        StringBuilder sBuf = new StringBuilder("{\n");
        String sPath = oReq.getPathInfo();
        if (sPath.contains("login"))
        {
            String sUname = oReq.getParameter("uname");
            String sPword = oReq.getParameter("pword");
            if (sUname != null && sUname.length() > 0 && sPword != null && sPword.length() > 0)
            {
                int nIndex = Collections.binarySearch(m_oCreds, sUname);
                if (nIndex >= 0)
                {
                    User oUser = m_oCreds.get(nIndex);
                    StringBuilder sSecPass = new StringBuilder();
                    getSecurePassword(sPword, oUser.m_ySalt, sSecPass);
                    if (Text.compare(oUser.m_sPass, sSecPass) == 0)
                    {
                        Session oSess = SessMgr.getSession(oReq, true);
                        oSess.m_oUser = oUser; // save credentials in session
                        sBuf.append("\t\"token\": \"").append(oSess.m_sToken).append("\"\n");
                    }
                }
            }
        }
        else
        {
            Session oSess = SessMgr.getSession(oReq);
            if (sPath.contains("check"))
            {
                if (oSess != null)
                    sBuf.append("\t\"token\": \"").append(oSess.m_sToken).append("\"\n");
            }
            else if (sPath.contains("logout"))
            {
                    SessMgr.removeSession(oSess);
            }
            else if (sPath.contains("update"))
            {
            }
        }
        sBuf.append("}\n");
        try (ServletOutputStream oOut = oRep.getOutputStream())
        {
            for (int nIndex = 0; nIndex < sBuf.length(); nIndex++)
                oOut.print(sBuf.charAt(nIndex));
        }
        catch (Exception oEx)
        {
        }
    }
References cc.util.Text.compare(), cc.ws.UserMgr.getSecurePassword(), cc.ws.SessMgr.getSession(), cc.ws.UserMgr.m_oCreds, cc.ws.User.m_sPass, cc.ws.Session.m_sToken, cc.ws.User.m_ySalt, and cc.ws.SessMgr.removeSession().
getSecurePassword()
static void cc.ws.UserMgr.getSecurePassword (String sPass, byte[] ySalt, StringBuilder sBuf) inline static package
Definition at line 109 of file UserMgr.java.
    {
        synchronized(LOCK)
        {
            DIGEST.reset();
            DIGEST.update(ySalt);
            Text.toHexString(DIGEST.digest(sPass.getBytes()), sBuf);
        }
    }
References cc.ws.UserMgr.DIGEST, cc.ws.UserMgr.LOCK, and cc.util.Text.toHexString().
Referenced by cc.ws.UserMgr.doPost(), and cc.ws.UserMgr.main().
init()
void cc.ws.UserMgr.init () inline
Definition at line 39 of file UserMgr.java.
    {
        ServletConfig oConf = getServletConfig();
        try (CsvReader oCsv = new CsvReader(new FileInputStream(oConf.getInitParameter("pwdfile"))))
        {
            while (oCsv.readLine() > 0)
                m_oCreds.add(new User(oCsv));
        }
        catch (Exception oEx)
        {
        }
        Collections.sort(m_oCreds, new User());
    }
References cc.ws.UserMgr.m_oCreds.
main()
static void cc.ws.UserMgr.main (String[] sArgs) inline static
Definition at line 120 of file UserMgr.java.
    {
        String sUser = sArgs[0];
        String sPass = sArgs[1];
        byte[] ySalt = new byte[32]; // use 256-bit algorithm
        try
        {
            java.security.SecureRandom.getInstance("SHA1PRNG").nextBytes(ySalt);
            StringBuilder sBuf = new StringBuilder();
            UserMgr.getSecurePassword(sPass, ySalt, sBuf);
            System.out.print(sUser);
            System.out.print(",");
            System.out.print(Text.toHexString(ySalt));
            System.out.print(",");
            System.out.print(sBuf.toString());
            System.out.print(",");
            System.out.println("abcdefghijklmnopqrstWvwxyz");
        }
        catch (Exception oEx)
        {
        }
    }
References cc.ws.UserMgr.getSecurePassword(), and cc.util.Text.toHexString().
Member Data Documentation
DIGEST
MessageDigest cc.ws.UserMgr.DIGEST static protected
Definition at line 19 of file UserMgr.java.
Referenced by cc.ws.UserMgr.getSecurePassword().
LOCK
final Object cc.ws.UserMgr.LOCK = new Object() static protected
Definition at line 18 of file UserMgr.java.
Referenced by cc.ws.UserMgr.getSecurePassword().
m_oCreds
ArrayList<User> cc.ws.UserMgr.m_oCreds = new ArrayList() protected
Definition at line 20 of file UserMgr.java.
Referenced by cc.ws.UserMgr.doPost(), and cc.ws.UserMgr.init().
The documentation for this class was generated from the following file:
src/cc/ws/UserMgr.java