Carma-cloud: cc.util.Arrays Class Reference
cc.util.Arrays Class Reference abstract
Classes
class DoubleGroupIterator
class GroupIterator
class IntGroupIterator
Static Public Member Functions
static double[] newDoubleArray ()
static double[] newDoubleArray (int nCapacity)
static Iterator< double[]> iterator (double[] dSrc, double[] dDest, int nStart, int nStep)
static double[] ensureCapacity (double[] dVals, int nDemand)
static int size (double[] dVals)
static double[] add (double[] dVals, double d1)
static double[] add (double[] dVals, double d1, double d2)
static double[] addAndUpdate (double[] dVals, double d1, double d2)
static double[] add (double[] dVals, double[] dMore)
static int[] newIntArray ()
static int[] newIntArray (int nCapacity)
static Iterator< int[]> iterator (int[] nSrc, int[] nDest, int nStart, int nStep)
static int[] ensureCapacity (int[] nVals, int nDemand)
static int size (int[] nVals)
static int[] add (int[] nVals, int n1)
static int[] add (int[] nVals, int n1, int n2)
static int[] add (int[] nVals, int[] nMore)
static int[] insert (int[] nVals, int n1, int nIndex)
static int binarySearch (int[] nVals, int n1)
static void printArray (double[] dArray, int nStart, PrintStream oPrint) throws Exception
static void printArray (int[] nArray, int nStart, PrintStream oPrint) throws Exception
Private Member Functions
Arrays ()
Static Private Attributes
static final int DEFAULT_CAPACITY = 12
Detailed Description
Author
bryan.krueger
Definition at line 11 of file Arrays.java.
Constructor & Destructor Documentation
Arrays()
cc.util.Arrays.Arrays () inline private
Definition at line 16 of file Arrays.java.
    {
    }
Member Function Documentation
add() [1/6]
static double[] cc.util.Arrays.add (double[] dVals, double d1) inline static
Definition at line 58 of file Arrays.java.
    {
        dVals = ensureCapacity(dVals, 1);
        dVals[(int)dVals[0]] = d1; // current insertion position
        dVals[0] += 1.0; // update position
        return dVals;
    }
References cc.util.Arrays.ensureCapacity().
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ctrl.CtrlLineArcs.CtrlLineArcs(), cc.geosrv.xodr.geo.Lane.Lane(), cc.geosrv.xodr.pvmt.Lane.Lane(), cc.geosrv.xodr.rdmk.RoadMark.RoadMark(), cc.geosrv.xodr.Signal.Signal(), cc.ihp.Subsegment.Subsegment(), cc.ctrl.proc.TdFeature.TdFeature(), cc.ihp.Detector.add(), cc.util.Arrays.addAndUpdate(), cc.ws.CtrlTiles.addControl(), cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.pvmt.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.xodr.pvmt.Arc.addLanePoints(), cc.util.TileUtil.addLinestring(), cc.util.TileUtil.addMercLinestring(), cc.util.TileUtil.addMercPolygon(), cc.geosrv.xodr.geo.Arc.addPoints(), cc.geosrv.xodr.geo.Line.addPoints(), cc.geosrv.xodr.pvmt.Arc.addPoints(), cc.geosrv.xodr.pvmt.Line.addPoints(), cc.geosrv.xodr.rdmk.Arc.addPoints(), cc.geosrv.xodr.rdmk.Line.addPoints(), cc.util.TileUtil.addPolygon(), cc.util.TileUtil.clipCtrlGeoForTile(), cc.util.TileUtil.clipLineString(), cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcStop.combine(), cc.ctrl.proc.ProcYield.combine(), cc.ctrl.CtrlLineArcs.combine(), cc.util.Geo.combineArcs(), cc.util.Geo.combineLineArcs(), cc.util.Geo.combineLines(), cc.ctrl.CreateCtrls.createCtrl(), cc.ctrl.proc.ProcLatPerm.createDashedLine(), cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile(), cc.geosrv.xodr.geo.LaneSection.createPavement(), cc.geosrv.xodr.pvmt.LaneSection.createPavement(), cc.util.Geo.createPolygon(), cc.ws.TrackTiles.doGet(), cc.rsm.RsmParser.endElement(), cc.ws.EventMgr.filterEvent(), cc.ihp.IHP.generateSpeedControls(), cc.geosrv.xodr.rdmk.Road.getRdMkCtrlLineArcs(), cc.geosrv.xodr.pvmt.LaneSection.getShoulders(), cc.ctrl.proc.ProcCtrl.getStopLine(), cc.ihp.IHPRequest.main(), cc.util.TestPath.main1(), cc.rsm.RsmParser.parseRequest(), cc.ctrl.proc.ProcLatPerm.proc(), cc.ctrl.CtrlGeo.readPts(), cc.ctrl.CtrlGeo.readPtsLonLats(), cc.ctrl.CtrlGeo.readPtsUpdateTiles(), cc.ctrl.proc.ProcClosed.renderLines(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.ctrl.proc.ProcDebugOutlines.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.util.Geo.reverseOrder(), cc.util.Geo.simplify(), cc.ws.CtrlTiles.splitLineArcs(), cc.geosrv.xodr.geo.XodrGeoParser.startElement(), cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement(), cc.ctrl.TrafCtrl.toMercatorPoints(), and cc.util.TileUtil.writePointBuffer().
add() [2/6]
static double[] cc.util.Arrays.add (double[] dVals, double d1, double d2) inline static
Definition at line 67 of file Arrays.java.
    {
        dVals = ensureCapacity(dVals, 2);
        int nIndex = (int)dVals[0]; // current insertion position
        dVals[nIndex++] = d1;
        dVals[nIndex++] = d2;
        dVals[0] = (double)nIndex; // track insertion position
        return dVals;
    }
References cc.util.Arrays.ensureCapacity().
add() [3/6]
static double[] cc.util.Arrays.add (double[] dVals, double[] dMore) inline static
Definition at line 93 of file Arrays.java.
    {
        dVals = ensureCapacity(dVals, dMore.length);
        int nIndex = (int)dVals[0]; // current insertion position
        System.arraycopy(dMore, 0, dVals, nIndex, dMore.length);
        dVals[0] = nIndex + dMore.length; // track insertion position
        return dVals;
    }
References cc.util.Arrays.ensureCapacity().
add() [4/6]
static int[] cc.util.Arrays.add (int[] nVals, int n1) inline static
Definition at line 140 of file Arrays.java.
    {
        nVals = ensureCapacity(nVals, 1);
        nVals[nVals[0]] = n1; // current insertion position
        ++nVals[0]; // update position
        return nVals;
    }
References cc.util.Arrays.ensureCapacity().
add() [5/6]
static int[] cc.util.Arrays.add (int[] nVals, int n1, int n2) inline static
Definition at line 149 of file Arrays.java.
    {
        nVals = ensureCapacity(nVals, 2);
        int nIndex = nVals[0]; // current insertion position
        nVals[nIndex++] = n1;
        nVals[nIndex++] = n2;
        nVals[0] = nIndex; // track insertion position
        return nVals;
    }
References cc.util.Arrays.ensureCapacity().
add() [6/6]
static int[] cc.util.Arrays.add (int[] nVals, int[] nMore) inline static
Definition at line 160 of file Arrays.java.
    {
        nVals = ensureCapacity(nVals, nMore.length);
        int nIndex = nVals[0]; // current insertion position
        System.arraycopy(nMore, 0, nVals, nIndex, nMore.length);
        nVals[0] = nIndex + nMore.length; // track insertion position
        return nVals;
    }
References cc.util.Arrays.ensureCapacity().
addAndUpdate()
static double[] cc.util.Arrays.addAndUpdate (double[] dVals, double d1, double d2) inline static
Definition at line 78 of file Arrays.java.
    {
        dVals = add(dVals, d1, d2);
        if (d1 < dVals[1]) // update bounding box stored in indeces 1-4
            dVals[1] = d1;
        if (d2 < dVals[2])
            dVals[2] = d2;
        if (d1 > dVals[3])
            dVals[3] = d1;
        if (d2 > dVals[4])
            dVals[4] = d2;
        return dVals;
    }
References cc.util.Arrays.add().
Referenced by cc.ws.CtrlTiles.addControl(), cc.util.MathUtil.addIntersection(), cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.pvmt.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.xodr.pvmt.Arc.addLanePoints(), cc.geosrv.xodr.geo.Line.addPoints(), cc.geosrv.xodr.geo.Geometry.addProjectedPoint(), cc.geosrv.xodr.pvmt.Geometry.addProjectedPoint(), cc.geosrv.xodr.rdmk.Geometry.addProjectedPoint(), cc.util.Geo.combineArcs(), cc.util.Geo.combineLineArcs(), cc.util.Geo.combineLines(), cc.ctrl.CreateCtrls.createCtrl(), cc.ctrl.proc.ProcLatPerm.createDashedLine(), cc.geosrv.xodr.geo.LaneSection.createPavement(), cc.geosrv.xodr.pvmt.LaneSection.createPavement(), cc.ws.TrackTiles.doGet(), cc.geosrv.xodr.pvmt.LaneSection.getShoulders(), cc.rsm.RsmParser.parseRequest(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), and cc.ctrl.TrafCtrl.toMercatorPoints().
binarySearch()
static int cc.util.Arrays.binarySearch (int[] nVals, int n1) inline static
Definition at line 180 of file Arrays.java.
    {
        return java.util.Arrays.binarySearch(nVals, 1, nVals[0], n1);
    }
Referenced by cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcStop.combine(), cc.ctrl.proc.ProcYield.combine(), cc.ctrl.proc.ProcSignal.parseMetadata(), cc.ctrl.proc.ProcStop.parseMetadata(), cc.ctrl.proc.ProcYield.parseMetadata(), and cc.geosrv.xodr.XodrSignalParser.startElement().
ensureCapacity() [1/2]
static double[] cc.util.Arrays.ensureCapacity (double[] dVals, int nDemand) inline static
Definition at line 41 of file Arrays.java.
    {
        if ((int)dVals[0] + nDemand < dVals.length)
            return dVals; // no changes needed
        double[] dNew = new double[nDemand + (3 * dVals.length >> 1)];
        System.arraycopy(dVals, 0, dNew, 0, (int)dVals[0]);
        return dNew;
    }
Referenced by cc.util.Arrays.add(), cc.geosrv.xodr.geo.Arc.addPoints(), cc.geosrv.xodr.geo.Line.addPoints(), cc.geosrv.xodr.pvmt.Arc.addPoints(), cc.geosrv.xodr.pvmt.Line.addPoints(), cc.geosrv.xodr.rdmk.Arc.addPoints(), cc.geosrv.xodr.rdmk.Line.addPoints(), cc.ctrl.CtrlLineArcs.combine(), cc.util.Arrays.insert(), cc.ctrl.CtrlGeo.readPtsLonLats(), and cc.ctrl.proc.ProcDebug.renderTiledData().
ensureCapacity() [2/2]
static int[] cc.util.Arrays.ensureCapacity (int[] nVals, int nDemand) inline static
Definition at line 123 of file Arrays.java.
    {
        if (nVals[0] + nDemand < nVals.length)
            return nVals; // no changes needed
        int[] nNew = new int[nDemand + (3 * nVals.length >> 1)];
        System.arraycopy(nVals, 0, nNew, 0, nVals[0]);
        return nNew;
    }
insert()
static int[] cc.util.Arrays.insert (int[] nVals, int n1, int nIndex) inline static
Definition at line 170 of file Arrays.java.
    {
        nVals = ensureCapacity(nVals, 1);
        System.arraycopy(nVals, nIndex, nVals, nIndex + 1, nVals[0] - nIndex);
        nVals[nIndex] = n1;
        ++nVals[0];
        return nVals;
    }
References cc.util.Arrays.ensureCapacity().
Referenced by cc.geosrv.xodr.Signal.addRoadId(), cc.geosrv.xodr.rdmk.Road.getRdMkCtrlLineArcs(), cc.ctrl.proc.ProcSignal.parseMetadata(), cc.ctrl.proc.ProcStop.parseMetadata(), and cc.ctrl.proc.ProcYield.parseMetadata().
iterator() [1/2]
static Iterator< double[]> cc.util.Arrays.iterator (double[] dSrc, double[] dDest, int nStart, int nStep) inline static
Definition at line 35 of file Arrays.java.
    {
        return new DoubleGroupIterator(dSrc, dDest, nStart, nStep);
    }
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ctrl.CtrlLineArcs.CtrlLineArcs(), cc.ihp.Subsegment.Subsegment(), cc.ctrl.TrafCtrl.TrafCtrl(), cc.util.TileUtil.addMercLinestring(), cc.util.TileUtil.addMercPolygon(), cc.util.TileUtil.clipCtrlGeoForTile(), cc.util.TileUtil.clipLineString(), cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcYield.combine(), cc.util.Geo.combineArcs(), cc.util.Geo.combineLines(), cc.ctrl.proc.ProcLatPerm.createDashedLine(), cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile(), cc.util.Geo.distAlongLine(), cc.ws.GeoLanes.doPost(), cc.ws.EventMgr.filterEvent(), cc.ihp.IHP.generateSpeedControls(), cc.util.Geo.getArea(), cc.ctrl.proc.ProcCtrl.getCoordAndHeadingAtLength(), cc.ihp.IHP.getGeo(), cc.ctrl.CtrlLineArcs.getLen(), cc.geosrv.xodr.rdmk.Road.getRdMkCtrlLineArcs(), cc.util.TileUtil.includeInTile(), cc.util.Geo.isClockwise(), cc.util.Geo.isInsidePolygon(), cc.util.Geo.main(), cc.util.TestPath.main1(), cc.ctrl.proc.ProcSignal.parseMetadata(), cc.ctrl.proc.ProcStop.parseMetadata(), cc.ctrl.proc.ProcYield.parseMetadata(), cc.rsm.RsmParser.parseRequest(), cc.util.Geo.polylineDist(), cc.util.Geo.polylineInside(), cc.util.Arrays.printArray(), cc.ctrl.proc.ProcClosed.renderLines(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ihp.IHPRequest.sendRequest(), cc.util.Geo.simplify(), cc.ws.CtrlTiles.splitLineArcs(), cc.ctrl.CtrlLineArcs.write(), cc.ctrl.proc.TdFeature.write(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.writeClas(), cc.ctrl.proc.ProcDebug.writeGeoLanes(), cc.util.TileUtil.writePointBuffer(), cc.ctrl.CtrlGeo.writePts(), cc.geosrv.xodr.geo.Lane.writePts(), cc.geosrv.xodr.pvmt.Lane.writePts(), and cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
iterator() [2/2]
static Iterator< int[]> cc.util.Arrays.iterator (int[] nSrc, int[] nDest, int nStart, int nStep) inline static
Definition at line 117 of file Arrays.java.
    {
        return new IntGroupIterator(nSrc, nDest, nStart, nStep);
    }
newDoubleArray() [1/2]
static double[] cc.util.Arrays.newDoubleArray () inline static
Definition at line 21 of file Arrays.java.
    {
        return newDoubleArray(DEFAULT_CAPACITY);
    }
References cc.util.Arrays.DEFAULT_CAPACITY, and cc.util.Arrays.newDoubleArray().
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ctrl.CtrlLineArcs.CtrlLineArcs(), cc.geosrv.xodr.geo.Lane.Lane(), cc.geosrv.xodr.pvmt.Lane.Lane(), cc.geosrv.xodr.geo.Road.Road(), cc.geosrv.xodr.pvmt.Road.Road(), cc.geosrv.xodr.rdmk.Road.Road(), cc.geosrv.xodr.rdmk.RoadMark.RoadMark(), cc.ihp.Subsegment.Subsegment(), cc.ctrl.proc.TdFeature.TdFeature(), cc.ws.CtrlTiles.addControl(), cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.util.TileUtil.clipLineString(), cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcStop.combine(), cc.ctrl.proc.ProcYield.combine(), cc.ctrl.CtrlLineArcs.combine(), cc.util.Geo.combineArcs(), cc.util.Geo.combineLineArcs(), cc.util.Geo.combineLines(), cc.ctrl.CreateCtrls.createCtrl(), cc.ctrl.proc.ProcLatPerm.createDashedLine(), cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile(), cc.geosrv.xodr.geo.LaneSection.createPavement(), cc.geosrv.xodr.pvmt.LaneSection.createPavement(), cc.util.Geo.createPolygon(), cc.ws.TrackTiles.doGet(), cc.ws.EventMgr.doList(), cc.ws.EventMgr.doMsgs(), cc.geosrv.xodr.pvmt.LaneSection.getShoulders(), cc.ctrl.proc.ProcCtrl.getStopLine(), cc.util.TestPath.main1(), cc.util.Arrays.newDoubleArray(), cc.rsm.RsmParser.parseRequest(), cc.ctrl.CtrlGeo.readPts(), cc.ctrl.CtrlGeo.readPtsUpdateTiles(), cc.ctrl.proc.ProcClosed.renderLines(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDebug.renderTiledData(), cc.ctrl.proc.ProcDebugOutlines.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcPavement.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.util.Geo.reverseOrder(), cc.util.Geo.simplify(), cc.ws.CtrlTiles.splitLineArcs(), and cc.ctrl.TrafCtrl.toMercatorPoints().
newDoubleArray() [2/2]
static double[] cc.util.Arrays.newDoubleArray (int nCapacity) inline static
Definition at line 27 of file Arrays.java.
    {
        double[] dVals = new double[++nCapacity]; // reserve slot for size
        dVals[0] = 1.0; // initial position is always one
        return dVals;
    }
newIntArray() [1/2]
static int[] cc.util.Arrays.newIntArray () inline static
Definition at line 103 of file Arrays.java.
    {
        return newIntArray(DEFAULT_CAPACITY);
    }
References cc.util.Arrays.DEFAULT_CAPACITY, and cc.util.Arrays.newIntArray().
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder(), cc.ws.CtrlTiles.doGet(), cc.ws.TrackTiles.doGet(), cc.ws.ValidateXodrTiles.doGet(), cc.ihp.IHPRequest.main(), cc.util.TestPath.main1(), cc.util.Arrays.newIntArray(), cc.ws.CtrlTiles.splitLineArcs(), cc.rsm.RsmParser.startElement(), and cc.util.TileUtil.writePointBuffer().
newIntArray() [2/2]
static int[] cc.util.Arrays.newIntArray (int nCapacity) inline static
Definition at line 109 of file Arrays.java.
    {
        int[] nVals = new int[++nCapacity]; // reserve slot for size
        nVals[0] = 1; // initial position is always one
        return nVals;
    }
printArray() [1/2]
static void cc.util.Arrays.printArray (double[] dArray, int nStart, PrintStream oPrint) throws Exception inline static
Definition at line 186 of file Arrays.java.
    {
        Iterator<double[]> oIt = iterator(dArray, new double[1], nStart, 1);
        boolean bWrite = oIt.hasNext();
        if (bWrite)
        {
            double[] dVal = oIt.next();
            oPrint.append(Double.toString(dVal[0]));
        }
        while (oIt.hasNext())
        {
            double[] dVal = oIt.next();
            oPrint.append(",").append(Double.toString(dVal[0]));
        }
        if (bWrite)
            oPrint.append("\n");
    }
References cc.util.Arrays.iterator().
printArray() [2/2]
static void cc.util.Arrays.printArray (int[] nArray, int nStart, PrintStream oPrint) throws Exception inline static
Definition at line 205 of file Arrays.java.
    {
        Iterator<int[]> oIt = iterator(nArray, new int[1], nStart, 1);
        boolean bWrite = oIt.hasNext();
        if (bWrite)
        {
            int[] nVal = oIt.next();
            oPrint.append(Integer.toString(nVal[0]));
        }
        while (oIt.hasNext())
        {
            int[] nVal = oIt.next();
            oPrint.append(",").append(Integer.toString(nVal[0]));
        }
        if (bWrite)
            oPrint.append("\n");
    }
References cc.util.Arrays.iterator().
size() [1/2]
static int cc.util.Arrays.size (double[] dVals) inline static
Definition at line 52 of file Arrays.java.
    {
        return (int)dVals[0];
    }
Referenced by cc.ctrl.CtrlLineArcs.CtrlLineArcs(), cc.ihp.Subsegment.Subsegment(), cc.ctrl.proc.TdFeature.TdFeature(), cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.util.TileUtil.clipCtrlGeoForTile(), cc.util.TileUtil.clipLineString(), cc.ctrl.proc.ProcSignal.combine(), cc.ctrl.proc.ProcStop.combine(), cc.ctrl.proc.ProcYield.combine(), cc.ctrl.CtrlLineArcs.combine(), cc.util.Geo.combineArcs(), cc.util.Geo.combineLineArcs(), cc.util.Geo.combineLines(), cc.ctrl.CtrlLineArcs.connects(), cc.geosrv.xodr.rdmk.RoadMark.createLinesForTile(), cc.geosrv.xodr.geo.LaneSection.createPavement(), cc.geosrv.xodr.pvmt.LaneSection.createPavement(), cc.ctrl.CtrlGeo.createPolygon(), cc.util.Geo.createPolygon(), cc.util.Geo.ctrlIntersectBounds(), cc.ihp.Subsegment.generateStats(), cc.util.Geo.getArea(), cc.ctrl.proc.TdFeature.getBytesToSkip(), cc.geosrv.xodr.pvmt.LaneSection.getShoulders(), cc.ctrl.proc.ProcCtrl.getStopLine(), cc.util.Geo.main(), cc.util.TestPath.main1(), cc.rsm.RsmParser.parseRequest(), cc.ctrl.TrafCtrl.preparePoints(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDebugOutlines.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ctrl.proc.ProcStop.renderTiledData(), cc.ctrl.proc.ProcYield.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ctrl.proc.ProcClosing.renderTiledData(), cc.util.Geo.reverseOrder(), cc.geosrv.xodr.geo.Road.setLaneIds(), cc.geosrv.xodr.pvmt.Road.setLaneIds(), cc.geosrv.xodr.rdmk.Road.setLaneIds(), cc.util.Geo.simplify(), cc.ws.CtrlTiles.splitLineArcs(), cc.ctrl.CtrlLineArcs.write(), cc.ctrl.proc.TdFeature.write(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.writeClas(), cc.util.TileUtil.writePointBuffer(), cc.ctrl.CtrlGeo.writePts(), and cc.geosrv.xodr.geo.XodrGeoParser.writeTrack().
size() [2/2]
static int cc.util.Arrays.size (int[] nVals) inline static
Definition at line 134 of file Arrays.java.
    {
        return nVals[0];
    }
Member Data Documentation
DEFAULT_CAPACITY
final int cc.util.Arrays.DEFAULT_CAPACITY = 12 static private
Definition at line 13 of file Arrays.java.
Referenced by cc.util.Arrays.newDoubleArray(), and cc.util.Arrays.newIntArray().
The documentation for this class was generated from the following file:
src/cc/util/Arrays.java