Carma-cloud: cc.ws.ReplayMgr Class Reference
cc.ws.ReplayMgr Class Reference
Classes
class Storm
Public Member Functions
ReplayMgr ()
void init ()
void run ()
void doPost (HttpServletRequest oReq, HttpServletResponse oRep) throws IOException
Protected Attributes
String m_sStormFile
Private Attributes
final ArrayList< Storm > m_oStorms = new ArrayList()
Detailed Description
Definition at line 15 of file ReplayMgr.java.
Constructor & Destructor Documentation
ReplayMgr()
cc.ws.ReplayMgr.ReplayMgr () inline
Definition at line 21 of file ReplayMgr.java.
    {
    }
Member Function Documentation
doPost()
void cc.ws.ReplayMgr.doPost (HttpServletRequest oReq, HttpServletResponse oRep) throws IOException inline
Definition at line 89 of file ReplayMgr.java.
    {
        Session oSess = SessMgr.getSession(oReq);
        if (oSess == null)
        {
            oRep.sendError(401);
            return;
        }
        try (JsonGenerator oJson = Json.createGenerator(oRep.getOutputStream()))
        {
            oJson.writeStartArray(); // start outer JSON array
            for (Storm oStorm : m_oStorms)
            {
                oJson.writeStartArray(); // start record
                oJson.write(oStorm.m_sStart).write(oStorm.m_sEnd).write(oStorm.m_sHours).
                    write(oStorm.m_nAvg).write(oStorm.m_nMax).write("");
                oJson.writeEnd(); // end record
            }
            oJson.writeEnd(); // end outer JSON array
        }
    }
References cc.ws.SessMgr.getSession(), and cc.ws.ReplayMgr.m_oStorms.
init()
void cc.ws.ReplayMgr.init () inline
Definition at line 27 of file ReplayMgr.java.
    {
        String sStormFile = getServletConfig().getInitParameter("stormfile");
        if (sStormFile != null && sStormFile.length() > 0)
        {
            m_sStormFile = sStormFile;
            new Thread(this).start();
        }
    }
References cc.ws.ReplayMgr.m_sStormFile.
run()
void cc.ws.ReplayMgr.run () inline
Definition at line 39 of file ReplayMgr.java.
    {
        int nCells = Integer.MIN_VALUE;
        try (CsvReader oIn = new CsvReader(new FileInputStream(m_sStormFile)))
        {
            SimpleDateFormat oFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");
            StringBuilder sBuf = new StringBuilder();
            oIn.readLine(); // skip header: start end avg max min
            while (oIn.readLine() > 0)
            {
                oIn.parseString(sBuf, 0); // get start date as string
                String sStart = sBuf.toString();
                oIn.parseString(sBuf, 1); // get end date as string
                String sEnd = sBuf.toString();
                double dDur = oFormat.parse(sEnd).getTime() - oFormat.parse(sStart).getTime();
                Storm oStorm = new Storm();
                oStorm.m_sStart = sStart;
                oStorm.m_sEnd = sEnd;
                oStorm.m_sHours = String.format("%03.1f", dDur / 3600000.0);
                oStorm.m_nAvg = (int)Math.round(oIn.parseDouble(2));
                oStorm.m_nMax = oIn.parseInt(3);
                oStorm.m_nMin = oIn.parseInt(4);
                m_oStorms.add(oStorm);
                if (oStorm.m_nMax > nCells)
                    nCells = oStorm.m_nMax; // find greatest cell count
            }
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
        }
        if (nCells <= 0)
            return;
        for (Storm oStorm : m_oStorms)
        {
            oStorm.m_nAvg = 100 * oStorm.m_nAvg / nCells;
            oStorm.m_nMin = 100 * oStorm.m_nMin / nCells;
            oStorm.m_nMax = 100 * oStorm.m_nMax / nCells;
        }
    }
References cc.ws.ReplayMgr.Storm.m_nMax, cc.ws.ReplayMgr.m_oStorms, and cc.ws.ReplayMgr.m_sStormFile.
Member Data Documentation
m_oStorms
final ArrayList<Storm> cc.ws.ReplayMgr.m_oStorms = new ArrayList() private
Definition at line 18 of file ReplayMgr.java.
Referenced by cc.ws.ReplayMgr.doPost(), and cc.ws.ReplayMgr.run().
m_sStormFile
String cc.ws.ReplayMgr.m_sStormFile protected
Definition at line 17 of file ReplayMgr.java.
Referenced by cc.ws.ReplayMgr.init(), and cc.ws.ReplayMgr.run().
The documentation for this class was generated from the following file:
src/cc/ws/ReplayMgr.java