Carma-cloud: cc.vector_tile.VectorTile.Tile.Feature Class Reference
cc.vector_tile.VectorTile.Tile.Feature Class Reference
Classes
class Builder
Public Member Functions
boolean hasId ()
long getId ()
java.util.List< java.lang.Integer > getTagsList ()
int getTagsCount ()
int getTags (int index)
boolean hasType ()
cc.vector_tile.VectorTile.Tile.GeomType getType ()
java.util.List< java.lang.Integer > getGeometryList ()
int getGeometryCount ()
int getGeometry (int index)
boolean hasId ()
long getId ()
java.util.List< java.lang.Integer > getTagsList ()
int getTagsCount ()
int getTags (int index)
boolean hasType ()
cc.vector_tile.VectorTile.Tile.GeomType getType ()
java.util.List< java.lang.Integer > getGeometryList ()
int getGeometryCount ()
int getGeometry (int index)
Static Public Member Functions
static cc.vector_tile.VectorTile.Tile.Feature parseFrom (java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile.Feature parseFrom (java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile.Feature parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile.Feature parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile.Feature parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile.Feature parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException
static cc.vector_tile.VectorTile.Tile.Feature parseFrom (java.io.InputStream input) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile.Feature parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile.Feature parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile.Feature parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile.Feature parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException
static cc.vector_tile.VectorTile.Tile.Feature parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException
static Builder newBuilder ()
static Builder newBuilder (cc.vector_tile.VectorTile.Tile.Feature prototype)
static cc.vector_tile.VectorTile.Tile.Feature getDefaultInstance ()
static com.google.protobuf.Parser< Feature > parser ()
Static Public Attributes
static final int ID_FIELD_NUMBER = 1
static final int TAGS_FIELD_NUMBER = 2
static final int TYPE_FIELD_NUMBER = 3
static final int GEOMETRY_FIELD_NUMBER = 4
Protected Member Functions
final java.lang.Object dynamicMethod (com.google.protobuf.GeneratedMessageLite.MethodToInvoke method, java.lang.Object arg0, java.lang.Object arg1)
Static Package Functions
[static initializer]
[static initializer]
Private Member Functions
Feature ()
void setId (long value)
void clearId ()
void ensureTagsIsMutable ()
void setTags (int index, int value)
void addTags (int value)
void addAllTags (java.lang.Iterable<? extends java.lang.Integer > values)
void clearTags ()
void setType (cc.vector_tile.VectorTile.Tile.GeomType value)
void clearType ()
void ensureGeometryIsMutable ()
void setGeometry (int index, int value)
void addGeometry (int value)
void addAllGeometry (java.lang.Iterable<? extends java.lang.Integer > values)
void clearGeometry ()
Private Attributes
int bitField0_
long id_
com.google.protobuf.Internal.IntList tags_
int tagsMemoizedSerializedSize = -1
int type_
com.google.protobuf.Internal.IntList geometry_
int geometryMemoizedSerializedSize = -1
Static Private Attributes
static final cc.vector_tile.VectorTile.Tile.Feature DEFAULT_INSTANCE
static volatile com.google.protobuf.Parser< Feature > PARSER
Detailed Description
Features are described in section 4.2 of the specification
Protobuf type vector_tile.Tile.Feature
Definition at line 1058 of file VectorTile.java.
Constructor & Destructor Documentation
Feature()
cc.vector_tile.VectorTile.Tile.Feature.Feature () inline private
Definition at line 1063 of file VectorTile.java.
{
        tags_ = emptyIntList();
        geometry_ = emptyIntList();
      }
References cc.vector_tile.VectorTile.Tile.Feature.geometry_, and cc.vector_tile.VectorTile.Tile.Feature.tags_.
Referenced by cc.vector_tile.VectorTile.Tile.Feature.[static initializer]().
Member Function Documentation
[static initializer]() [1/2]
cc.vector_tile.VectorTile.Tile.Feature.[static initializer] inline static package
[static initializer]() [2/2]
cc.vector_tile.VectorTile.Tile.Feature.[static initializer] inline static package
References cc.vector_tile.VectorTile.Tile.Feature.Feature(), and cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
addAllGeometry()
void cc.vector_tile.VectorTile.Tile.Feature.addAllGeometry (java.lang.Iterable<? extends java.lang.Integer > values) inline private
Contains a stream of commands and parameters (vertices).
A detailed description on geometry encoding is located in
section 4.3 of the specification.
repeated uint32 geometry = 4 [packed = true];
Definition at line 1346 of file VectorTile.java.
{
        ensureGeometryIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
            values, geometry_);
      }
References cc.vector_tile.VectorTile.Tile.Feature.ensureGeometryIsMutable(), and cc.vector_tile.VectorTile.Tile.Feature.geometry_.
addAllTags()
void cc.vector_tile.VectorTile.Tile.Feature.addAllTags (java.lang.Iterable<? extends java.lang.Integer > values) inline private
Tags of this feature are encoded as repeated pairs of
integers.
A detailed description of tags is located in sections
4.2 and 4.4 of the specification
repeated uint32 tags = 2 [packed = true];
Definition at line 1190 of file VectorTile.java.
{
        ensureTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
            values, tags_);
      }
References cc.vector_tile.VectorTile.Tile.Feature.ensureTagsIsMutable(), and cc.vector_tile.VectorTile.Tile.Feature.tags_.
addGeometry()
void cc.vector_tile.VectorTile.Tile.Feature.addGeometry (int value) inline private
Contains a stream of commands and parameters (vertices).
A detailed description on geometry encoding is located in
section 4.3 of the specification.
repeated uint32 geometry = 4 [packed = true];
Definition at line 1333 of file VectorTile.java.
{
        ensureGeometryIsMutable();
        geometry_.addInt(value);
      }
References cc.vector_tile.VectorTile.Tile.Feature.ensureGeometryIsMutable(), and cc.vector_tile.VectorTile.Tile.Feature.geometry_.
addTags()
void cc.vector_tile.VectorTile.Tile.Feature.addTags (int value) inline private
Tags of this feature are encoded as repeated pairs of
integers.
A detailed description of tags is located in sections
4.2 and 4.4 of the specification
repeated uint32 tags = 2 [packed = true];
Definition at line 1176 of file VectorTile.java.
{
        ensureTagsIsMutable();
        tags_.addInt(value);
      }
References cc.vector_tile.VectorTile.Tile.Feature.ensureTagsIsMutable(), and cc.vector_tile.VectorTile.Tile.Feature.tags_.
clearGeometry()
void cc.vector_tile.VectorTile.Tile.Feature.clearGeometry () inline private
Contains a stream of commands and parameters (vertices).
A detailed description on geometry encoding is located in
section 4.3 of the specification.
repeated uint32 geometry = 4 [packed = true];
Definition at line 1361 of file VectorTile.java.
{
        geometry_ = emptyIntList();
      }
References cc.vector_tile.VectorTile.Tile.Feature.geometry_.
clearId()
void cc.vector_tile.VectorTile.Tile.Feature.clearId () inline private
optional uint64 id = 1 [default = 0];
Definition at line 1094 of file VectorTile.java.
{
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
      }
References cc.vector_tile.VectorTile.Tile.Feature.bitField0_, and cc.vector_tile.VectorTile.Tile.Feature.id_.
clearTags()
void cc.vector_tile.VectorTile.Tile.Feature.clearTags () inline private
Tags of this feature are encoded as repeated pairs of
integers.
A detailed description of tags is located in sections
4.2 and 4.4 of the specification
repeated uint32 tags = 2 [packed = true];
Definition at line 1206 of file VectorTile.java.
{
        tags_ = emptyIntList();
      }
References cc.vector_tile.VectorTile.Tile.Feature.tags_.
clearType()
void cc.vector_tile.VectorTile.Tile.Feature.clearType () inline private
The type of geometry stored in this feature.
optional .vector_tile.Tile.GeomType type = 3 [default = UNKNOWN];
Definition at line 1256 of file VectorTile.java.
{
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
      }
References cc.vector_tile.VectorTile.Tile.Feature.bitField0_, and cc.vector_tile.VectorTile.Tile.Feature.type_.
dynamicMethod()
final java.lang.Object cc.vector_tile.VectorTile.Tile.Feature.dynamicMethod (com.google.protobuf.GeneratedMessageLite.MethodToInvoke method, java.lang.Object arg0, java.lang.Object arg1) inline protected
Definition at line 1753 of file VectorTile.java.
{
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new cc.vector_tile.VectorTile.Tile.Feature();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case BUILD_MESSAGE_INFO: {
              java.lang.Object[] objects = new java.lang.Object[] {
                "bitField0_",
                "id_",
                "tags_",
                "type_",
                cc.vector_tile.VectorTile.Tile.GeomType.internalGetVerifier(),
                "geometry_",
              };
              java.lang.String info =
                  "\u0001\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0002\u0000\u0001\u0003\u0000\u0002" +
                  "+\u0003\f\u0001\u0004+";
              return newMessageInfo(DEFAULT_INSTANCE, info, objects);
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<cc.vector_tile.VectorTile.Tile.Feature> parser = PARSER;
            if (parser == null) {
              synchronized (cc.vector_tile.VectorTile.Tile.Feature.class) {
                parser = PARSER;
                if (parser == null) {
                  parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }
References cc.vector_tile.VectorTile.VectorTile(), cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE, cc.vector_tile.VectorTile.Tile.Feature.PARSER, and cc.vector_tile.VectorTile.Tile.Feature.parser().
ensureGeometryIsMutable()
void cc.vector_tile.VectorTile.Tile.Feature.ensureGeometryIsMutable () inline private
Definition at line 1304 of file VectorTile.java.
{
        if (!geometry_.isModifiable()) {
          geometry_ =
              com.google.protobuf.GeneratedMessageLite.mutableCopy(geometry_);
         }
      }
References cc.vector_tile.VectorTile.Tile.Feature.geometry_.
Referenced by cc.vector_tile.VectorTile.Tile.Feature.addAllGeometry(), cc.vector_tile.VectorTile.Tile.Feature.addGeometry(), and cc.vector_tile.VectorTile.Tile.Feature.setGeometry().
ensureTagsIsMutable()
void cc.vector_tile.VectorTile.Tile.Feature.ensureTagsIsMutable () inline private
Definition at line 1145 of file VectorTile.java.
{
        if (!tags_.isModifiable()) {
          tags_ =
              com.google.protobuf.GeneratedMessageLite.mutableCopy(tags_);
         }
      }
References cc.vector_tile.VectorTile.Tile.Feature.tags_.
Referenced by cc.vector_tile.VectorTile.Tile.Feature.addAllTags(), cc.vector_tile.VectorTile.Tile.Feature.addTags(), and cc.vector_tile.VectorTile.Tile.Feature.setTags().
getDefaultInstance()
static cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.getDefaultInstance () inline static
Definition at line 1817 of file VectorTile.java.
{
        return DEFAULT_INSTANCE;
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
getGeometry()
int cc.vector_tile.VectorTile.Tile.Feature.getGeometry (int index) inline
Contains a stream of commands and parameters (vertices).
A detailed description on geometry encoding is located in
section 4.3 of the specification.
repeated uint32 geometry = 4 [packed = true];
Implements cc.vector_tile.VectorTile.Tile.FeatureOrBuilder.
Definition at line 1300 of file VectorTile.java.
{
        return geometry_.getInt(index);
      }
References cc.vector_tile.VectorTile.Tile.Feature.geometry_.
getGeometryCount()
int cc.vector_tile.VectorTile.Tile.Feature.getGeometryCount () inline
Contains a stream of commands and parameters (vertices).
A detailed description on geometry encoding is located in
section 4.3 of the specification.
repeated uint32 geometry = 4 [packed = true];
Implements cc.vector_tile.VectorTile.Tile.FeatureOrBuilder.
Definition at line 1287 of file VectorTile.java.
{
        return geometry_.size();
      }
References cc.vector_tile.VectorTile.Tile.Feature.geometry_.
getGeometryList()
java.util.List< java.lang.Integer > cc.vector_tile.VectorTile.Tile.Feature.getGeometryList () inline
Contains a stream of commands and parameters (vertices).
A detailed description on geometry encoding is located in
section 4.3 of the specification.
repeated uint32 geometry = 4 [packed = true];
Implements cc.vector_tile.VectorTile.Tile.FeatureOrBuilder.
Definition at line 1274 of file VectorTile.java.
{
        return geometry_;
      }
References cc.vector_tile.VectorTile.Tile.Feature.geometry_.
getId()
long cc.vector_tile.VectorTile.Tile.Feature.getId () inline
optional uint64 id = 1 [default = 0];
Implements cc.vector_tile.VectorTile.Tile.FeatureOrBuilder.
Definition at line 1081 of file VectorTile.java.
{
        return id_;
      }
References cc.vector_tile.VectorTile.Tile.Feature.id_.
getTags()
int cc.vector_tile.VectorTile.Tile.Feature.getTags (int index) inline
Tags of this feature are encoded as repeated pairs of
integers.
A detailed description of tags is located in sections
4.2 and 4.4 of the specification
repeated uint32 tags = 2 [packed = true];
Implements cc.vector_tile.VectorTile.Tile.FeatureOrBuilder.
Definition at line 1141 of file VectorTile.java.
{
        return tags_.getInt(index);
      }
References cc.vector_tile.VectorTile.Tile.Feature.tags_.
getTagsCount()
int cc.vector_tile.VectorTile.Tile.Feature.getTagsCount () inline
Tags of this feature are encoded as repeated pairs of
integers.
A detailed description of tags is located in sections
4.2 and 4.4 of the specification
repeated uint32 tags = 2 [packed = true];
Implements cc.vector_tile.VectorTile.Tile.FeatureOrBuilder.
Definition at line 1127 of file VectorTile.java.
{
        return tags_.size();
      }
References cc.vector_tile.VectorTile.Tile.Feature.tags_.
getTagsList()
java.util.List< java.lang.Integer > cc.vector_tile.VectorTile.Tile.Feature.getTagsList () inline
Tags of this feature are encoded as repeated pairs of
integers.
A detailed description of tags is located in sections
4.2 and 4.4 of the specification
repeated uint32 tags = 2 [packed = true];
Implements cc.vector_tile.VectorTile.Tile.FeatureOrBuilder.
Definition at line 1113 of file VectorTile.java.
{
        return tags_;
      }
References cc.vector_tile.VectorTile.Tile.Feature.tags_.
getType()
cc.vector_tile.VectorTile.Tile.GeomType cc.vector_tile.VectorTile.Tile.Feature.getType () inline
The type of geometry stored in this feature.
optional .vector_tile.Tile.GeomType type = 3 [default = UNKNOWN];
Implements cc.vector_tile.VectorTile.Tile.FeatureOrBuilder.
Definition at line 1231 of file VectorTile.java.
{
        cc.vector_tile.VectorTile.Tile.GeomType result = cc.vector_tile.VectorTile.Tile.GeomType.forNumber(type_);
        return result == null ? cc.vector_tile.VectorTile.Tile.GeomType.UNKNOWN : result;
      }
References cc.vector_tile.VectorTile.Tile.GeomType.GeomType(), and cc.vector_tile.VectorTile.Tile.Feature.type_.
hasId()
boolean cc.vector_tile.VectorTile.Tile.Feature.hasId () inline
optional uint64 id = 1 [default = 0];
Implements cc.vector_tile.VectorTile.Tile.FeatureOrBuilder.
Definition at line 1074 of file VectorTile.java.
{
        return ((bitField0_ & 0x00000001) != 0);
      }
References cc.vector_tile.VectorTile.Tile.Feature.bitField0_.
hasType()
boolean cc.vector_tile.VectorTile.Tile.Feature.hasType () inline
The type of geometry stored in this feature.
optional .vector_tile.Tile.GeomType type = 3 [default = UNKNOWN];
Implements cc.vector_tile.VectorTile.Tile.FeatureOrBuilder.
Definition at line 1220 of file VectorTile.java.
{
        return ((bitField0_ & 0x00000002) != 0);
      }
References cc.vector_tile.VectorTile.Tile.Feature.bitField0_.
newBuilder() [1/2]
static Builder cc.vector_tile.VectorTile.Tile.Feature.newBuilder () inline static
Definition at line 1439 of file VectorTile.java.
{
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
Referenced by cc.util.TileLayerBuilder.TileLayerBuilder(), cc.ws.CtrlTiles.doGet(), cc.ws.TrackTiles.doGet(), and cc.ws.ValidateXodrTiles.doGet().
newBuilder() [2/2]
static Builder cc.vector_tile.VectorTile.Tile.Feature.newBuilder (cc.vector_tile.VectorTile.Tile.Feature prototype) inline static
Definition at line 1442 of file VectorTile.java.
{
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
parseDelimitedFrom() [1/2]
static cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.parseDelimitedFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 1415 of file VectorTile.java.
{
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE, and cc.vector_tile.VectorTile.Tile.Feature.parseDelimitedFrom().
Referenced by cc.vector_tile.VectorTile.Tile.Feature.parseDelimitedFrom().
parseDelimitedFrom() [2/2]
static cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.parseDelimitedFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1419 of file VectorTile.java.
{
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE, and cc.vector_tile.VectorTile.Tile.Feature.parseDelimitedFrom().
parseFrom() [1/10]
static cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.parseFrom (byte[] data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1391 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
parseFrom() [2/10]
static cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.parseFrom (byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1396 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
parseFrom() [3/10]
static cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.parseFrom (com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1378 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
parseFrom() [4/10]
static cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.parseFrom (com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1384 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
parseFrom() [5/10]
static cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.parseFrom (com.google.protobuf.CodedInputStream input) throws java.io.IOException inline static
Definition at line 1425 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
parseFrom() [6/10]
static cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.parseFrom (com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1431 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
parseFrom() [7/10]
static cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.parseFrom (java.io.InputStream input) throws java.io.IOException inline static
Definition at line 1403 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
parseFrom() [8/10]
static cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.parseFrom (java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException inline static
Definition at line 1408 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
parseFrom() [9/10]
static cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.parseFrom (java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1365 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
parseFrom() [10/10]
static cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.parseFrom (java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException inline static
Definition at line 1371 of file VectorTile.java.
{
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
parser()
static com.google.protobuf.Parser< Feature > cc.vector_tile.VectorTile.Tile.Feature.parser () inline static
Definition at line 1823 of file VectorTile.java.
{
        return DEFAULT_INSTANCE.getParserForType();
      }
References cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE.
Referenced by cc.vector_tile.VectorTile.Tile.Feature.dynamicMethod().
setGeometry()
void cc.vector_tile.VectorTile.Tile.Feature.setGeometry (int index, int value) inline private
Contains a stream of commands and parameters (vertices).
A detailed description on geometry encoding is located in
section 4.3 of the specification.
repeated uint32 geometry = 4 [packed = true];
Definition at line 1319 of file VectorTile.java.
{
        ensureGeometryIsMutable();
        geometry_.setInt(index, value);
      }
References cc.vector_tile.VectorTile.Tile.Feature.ensureGeometryIsMutable(), and cc.vector_tile.VectorTile.Tile.Feature.geometry_.
setId()
void cc.vector_tile.VectorTile.Tile.Feature.setId (long value) inline private
optional uint64 id = 1 [default = 0];
Definition at line 1087 of file VectorTile.java.
{
        bitField0_ |= 0x00000001;
        id_ = value;
      }
References cc.vector_tile.VectorTile.Tile.Feature.bitField0_, and cc.vector_tile.VectorTile.Tile.Feature.id_.
setTags()
void cc.vector_tile.VectorTile.Tile.Feature.setTags (int index, int value) inline private
Tags of this feature are encoded as repeated pairs of
integers.
A detailed description of tags is located in sections
4.2 and 4.4 of the specification
repeated uint32 tags = 2 [packed = true];
Definition at line 1161 of file VectorTile.java.
{
        ensureTagsIsMutable();
        tags_.setInt(index, value);
      }
References cc.vector_tile.VectorTile.Tile.Feature.ensureTagsIsMutable(), and cc.vector_tile.VectorTile.Tile.Feature.tags_.
setType()
void cc.vector_tile.VectorTile.Tile.Feature.setType (cc.vector_tile.VectorTile.Tile.GeomType value) inline private
The type of geometry stored in this feature.
optional .vector_tile.Tile.GeomType type = 3 [default = UNKNOWN];
Definition at line 1242 of file VectorTile.java.
{
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
      }
References cc.vector_tile.VectorTile.Tile.Feature.bitField0_, and cc.vector_tile.VectorTile.Tile.Feature.type_.
Member Data Documentation
bitField0_
int cc.vector_tile.VectorTile.Tile.Feature.bitField0_ private
Definition at line 1067 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Feature.clearId(), cc.vector_tile.VectorTile.Tile.Feature.clearType(), cc.vector_tile.VectorTile.Tile.Feature.hasId(), cc.vector_tile.VectorTile.Tile.Feature.hasType(), cc.vector_tile.VectorTile.Tile.Feature.setId(), and cc.vector_tile.VectorTile.Tile.Feature.setType().
DEFAULT_INSTANCE
final cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Feature.DEFAULT_INSTANCE static private
Definition at line 1806 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Feature.Builder.Builder(), cc.vector_tile.VectorTile.Tile.Feature.[static initializer](), cc.vector_tile.VectorTile.Tile.Feature.dynamicMethod(), cc.vector_tile.VectorTile.Tile.Feature.getDefaultInstance(), cc.vector_tile.VectorTile.Tile.Feature.newBuilder(), cc.vector_tile.VectorTile.Tile.Feature.parseDelimitedFrom(), cc.vector_tile.VectorTile.Tile.Feature.parseFrom(), and cc.vector_tile.VectorTile.Tile.Feature.parser().
geometry_
com.google.protobuf.Internal.IntList cc.vector_tile.VectorTile.Tile.Feature.geometry_ private
Definition at line 1262 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Feature.Feature(), cc.vector_tile.VectorTile.Tile.Feature.addAllGeometry(), cc.vector_tile.VectorTile.Tile.Feature.addGeometry(), cc.vector_tile.VectorTile.Tile.Feature.clearGeometry(), cc.vector_tile.VectorTile.Tile.Feature.ensureGeometryIsMutable(), cc.vector_tile.VectorTile.Tile.Feature.getGeometry(), cc.vector_tile.VectorTile.Tile.Feature.getGeometryCount(), cc.vector_tile.VectorTile.Tile.Feature.getGeometryList(), and cc.vector_tile.VectorTile.Tile.Feature.setGeometry().
GEOMETRY_FIELD_NUMBER
final int cc.vector_tile.VectorTile.Tile.Feature.GEOMETRY_FIELD_NUMBER = 4 static
Definition at line 1261 of file VectorTile.java.
geometryMemoizedSerializedSize
int cc.vector_tile.VectorTile.Tile.Feature.geometryMemoizedSerializedSize = -1 private
Definition at line 1303 of file VectorTile.java.
id_
long cc.vector_tile.VectorTile.Tile.Feature.id_ private
Definition at line 1069 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Feature.clearId(), cc.vector_tile.VectorTile.Tile.Feature.getId(), and cc.vector_tile.VectorTile.Tile.Feature.setId().
ID_FIELD_NUMBER
final int cc.vector_tile.VectorTile.Tile.Feature.ID_FIELD_NUMBER = 1 static
Definition at line 1068 of file VectorTile.java.
PARSER
volatile com.google.protobuf.Parser<Feature> cc.vector_tile.VectorTile.Tile.Feature.PARSER static private
Definition at line 1821 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Feature.dynamicMethod().
tags_
com.google.protobuf.Internal.IntList cc.vector_tile.VectorTile.Tile.Feature.tags_ private
Definition at line 1100 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Feature.Feature(), cc.vector_tile.VectorTile.Tile.Feature.addAllTags(), cc.vector_tile.VectorTile.Tile.Feature.addTags(), cc.vector_tile.VectorTile.Tile.Feature.clearTags(), cc.vector_tile.VectorTile.Tile.Feature.ensureTagsIsMutable(), cc.vector_tile.VectorTile.Tile.Feature.getTags(), cc.vector_tile.VectorTile.Tile.Feature.getTagsCount(), cc.vector_tile.VectorTile.Tile.Feature.getTagsList(), and cc.vector_tile.VectorTile.Tile.Feature.setTags().
TAGS_FIELD_NUMBER
final int cc.vector_tile.VectorTile.Tile.Feature.TAGS_FIELD_NUMBER = 2 static
Definition at line 1099 of file VectorTile.java.
tagsMemoizedSerializedSize
int cc.vector_tile.VectorTile.Tile.Feature.tagsMemoizedSerializedSize = -1 private
Definition at line 1144 of file VectorTile.java.
type_
int cc.vector_tile.VectorTile.Tile.Feature.type_ private
Definition at line 1211 of file VectorTile.java.
Referenced by cc.vector_tile.VectorTile.Tile.Feature.clearType(), cc.vector_tile.VectorTile.Tile.Feature.getType(), and cc.vector_tile.VectorTile.Tile.Feature.setType().
TYPE_FIELD_NUMBER
final int cc.vector_tile.VectorTile.Tile.Feature.TYPE_FIELD_NUMBER = 3 static
Definition at line 1210 of file VectorTile.java.
The documentation for this class was generated from the following file:
src/cc/vector_tile/VectorTile.java