Carma-cloud: cc.ws.SessMgr Class Reference
cc.ws.SessMgr Class Reference
Public Member Functions
SessMgr ()
void init ()
Static Public Member Functions
static Session getSession (HttpServletRequest oReq)
Static Package Functions
static Session getSession (HttpServletRequest oReq, boolean bCreate)
static void removeSession (Session oSess)
Static Package Attributes
static long TIMEOUT = 1800000
static final ArrayList< Session > SESSIONS = new ArrayList()
Detailed Description
Definition at line 12 of file SessMgr.java.
Constructor & Destructor Documentation
SessMgr()
cc.ws.SessMgr.SessMgr () inline
Definition at line 18 of file SessMgr.java.
    {
    }
Member Function Documentation
getSession() [1/2]
static Session cc.ws.SessMgr.getSession (HttpServletRequest oReq) inline static
Definition at line 33 of file SessMgr.java.
    {
        return getSession(oReq, false);
    }
References cc.ws.SessMgr.getSession().
Referenced by cc.ws.GeoSvc.doPost(), cc.ws.Handler.doPost(), cc.ws.ReplayMgr.doPost(), cc.ws.UserMgr.doPost(), cc.ihp.IHP.doPost(), cc.ws.CtrlTiles.doPost(), cc.ws.GeoLanes.doPost(), and cc.ws.SessMgr.getSession().
getSession() [2/2]
static Session cc.ws.SessMgr.getSession (HttpServletRequest oReq, boolean bCreate) inline static package
Definition at line 39 of file SessMgr.java.
    {
        String sToken = oReq.getParameter("token");
        if (sToken == null)
            sToken = "";
        Session oSess = null;
        synchronized(SESSIONS)
        {
            int nIndex = Collections.binarySearch(SESSIONS, sToken);
            if (nIndex >= 0)
            {
                oSess = SESSIONS.get(nIndex);
                if (oSess.m_lUpdate < System.currentTimeMillis())
                {
                    SESSIONS.remove(nIndex);
                    return null;
                }
            }
            else if (bCreate)
            {
                byte[] yBytes = new byte[16];
                try
                {
                    SecureRandom oRng = SecureRandom.getInstance("SHA1PRNG");
                    do
                    {
                        oRng.nextBytes(yBytes); // ensure no duplicates
                        oSess = new Session(Text.toHexString(yBytes));
                        nIndex = Collections.binarySearch(SESSIONS, oSess, oSess);
                    }
                    while (nIndex >= 0);
                    SESSIONS.add(~nIndex, oSess); // save new session
                }
                catch (Exception oEx)
                {
                }
            }
        }
        if (oSess != null)
            oSess.m_lUpdate = System.currentTimeMillis() + TIMEOUT;
        return oSess;
    }
References cc.ws.Session.m_lUpdate, cc.ws.SessMgr.SESSIONS, cc.ws.SessMgr.TIMEOUT, and cc.util.Text.toHexString().
init()
void cc.ws.SessMgr.init () inline
Definition at line 24 of file SessMgr.java.
    {
        ServletConfig oConf = getServletConfig();
        String sExp = oConf.getInitParameter("timeout");
        if (sExp != null)
            TIMEOUT = Text.parseInt(sExp);
    }
References cc.util.Text.parseInt(), and cc.ws.SessMgr.TIMEOUT.
removeSession()
static void cc.ws.SessMgr.removeSession (Session oSess) inline static package
Definition at line 86 of file SessMgr.java.
    {
        if (oSess == null)
            return;
        synchronized(SESSIONS)
        {
            int nIndex = Collections.binarySearch(SESSIONS, oSess, oSess);
            if (nIndex >= 0)
                SESSIONS.remove(nIndex);
        }
    }
References cc.ws.SessMgr.SESSIONS.
Referenced by cc.ws.UserMgr.doPost().
Member Data Documentation
SESSIONS
final ArrayList<Session> cc.ws.SessMgr.SESSIONS = new ArrayList() static package
Definition at line 15 of file SessMgr.java.
Referenced by cc.ws.SessMgr.getSession(), and cc.ws.SessMgr.removeSession().
TIMEOUT
long cc.ws.SessMgr.TIMEOUT = 1800000 static package
Definition at line 14 of file SessMgr.java.
Referenced by cc.ws.SessMgr.getSession(), and cc.ws.SessMgr.init().
The documentation for this class was generated from the following file:
src/cc/ws/SessMgr.java