Carma-cloud: cc.ws.RopMgr Class Reference
cc.ws.RopMgr Class Reference
Public Member Functions
void init ()
void run ()
Protected Member Functions
void doNull (Session oSess, HttpServletRequest oReq, PrintWriter oOut)
void doSave (Session oSess, HttpServletRequest oReq, PrintWriter oOut) throws IOException
void doDetails (Session oSess, HttpServletRequest oReq, PrintWriter oOut) throws IOException
Protected Member Functions inherited from cc.ws.Handler
void doPost (HttpServletRequest oReq, HttpServletResponse oRep) throws ServletException, IOException
Protected Attributes
String m_sRopFile
ArrayList< String[]> m_oRops = new ArrayList()
Additional Inherited Members
Static Public Member Functions inherited from cc.ws.Handler
static void update (String[] sObj, int nCols, CsvReader oIn)
static void writeJson (PrintWriter oOut, String sId, String sData)
static String getJsonString (String sData, String sTag)
static String getJsonArray (String sData, String sTag)
Static Protected Attributes inherited from cc.ws.Handler
static Comparator< String[]> STR_ARR_COMP = (String[] o1, String[] o2) -> o1[0].compareTo(o2[0])
static final SimpleDateFormat ISO8601Sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'")
Static Package Functions inherited from cc.ws.Handler
[static initializer]
Detailed Description
Author
Federal Highway Administration
Definition at line 23 of file RopMgr.java.
Member Function Documentation
doDetails()
void cc.ws.RopMgr.doDetails (Session oSess, HttpServletRequest oReq, PrintWriter oOut) throws IOException inline protected
Definition at line 149 of file RopMgr.java.
    {
        String sRopIds = oReq.getParameter("rops");
        if (sRopIds == null || m_oRops.isEmpty())
        {
            oOut.write("{}");
            return;
        }
        String[] sIds = sRopIds.split(",");
        oOut.write("{");
        String[] sSearch = new String[1];
        int nCount = 0;
        synchronized (m_oRops)
        {
            for (String sId : sIds)
            {
                sSearch[0] = sId;
                int nIndex = Collections.binarySearch(m_oRops, sSearch, STR_ARR_COMP);
                if (nIndex < 0)
                    continue;
                String[] sRop = m_oRops.get(nIndex);
                if (nCount++ > 0)
                    oOut.write(",");
                writeJson(oOut, sRop[0], sRop[sRop.length - 1]);
            }
        }
        oOut.write("}");
    }
References cc.ws.RopMgr.m_oRops, cc.ws.Handler.STR_ARR_COMP, and cc.ws.Handler.writeJson().
doNull()
void cc.ws.RopMgr.doNull (Session oSess, HttpServletRequest oReq, PrintWriter oOut) inline protected
Definition at line 69 of file RopMgr.java.
    {
        oOut.write("{");
        synchronized (m_oRops)
        {
            int nSize = m_oRops.size();
            if (nSize > 0)
            {
                String[] sRop = m_oRops.get(0);
                writeJson(oOut, sRop[0], sRop[sRop.length - 1]);
                for (int i = 1; i < nSize; i++)
                {
                    sRop = m_oRops.get(i);
                    oOut.write(",");
                    writeJson(oOut, sRop[0], sRop[sRop.length - 1]); // {"uuid" : JSON, "uuid" : JSON, ...}
                }
            }
        }
        oOut.write("}");
    }
References cc.ws.RopMgr.m_oRops, and cc.ws.Handler.writeJson().
doSave()
void cc.ws.RopMgr.doSave (Session oSess, HttpServletRequest oReq, PrintWriter oOut) throws IOException inline protected
Definition at line 91 of file RopMgr.java.
    {
        String[] sRop;
        synchronized (m_oRops)
        {
            String[] sSearch = new String[1];
            sSearch[0] = oReq.getParameter("id");
            if (sSearch[0] == null || sSearch[0].length() == 0) // no id so create a new one
                sSearch[0] = Text.getUUID();
            StringBuilder sBuffer = new StringBuilder(oReq.getParameter("data"));
            int nBufferIndex = sBuffer.length();
            while (nBufferIndex-- > 0)
            {
                char cChar = sBuffer.charAt(nBufferIndex);
                if (cChar == '\t' || cChar == '\n')
                    sBuffer.deleteCharAt(nBufferIndex);
            }
            if (sBuffer.indexOf("\"status\"") < 0) // add default status of unused to json
            {
                Text.removeWhitespace(sBuffer);
                sBuffer.insert(sBuffer.lastIndexOf("}"), ",\"status\":\"U\"");
            }
            int nIndex = Collections.binarySearch(m_oRops, sSearch, STR_ARR_COMP);
            if (nIndex < 0)
            {
                nIndex = ~nIndex;
                m_oRops.add(nIndex, new String[]{sSearch[0], oSess.m_oUser.m_sUser, null, null}); // create new array
            }
            sRop = m_oRops.get(nIndex);
            synchronized (ISO8601Sdf)
            {
                sRop[2] = ISO8601Sdf.format(System.currentTimeMillis());
            }
            sRop[3] = sBuffer.toString();
            if (sRop[3].contains("\"status\":\"D\"")) // remove from list if the status is deleted
                m_oRops.remove(nIndex);
            try (BufferedWriter oFileOut = new BufferedWriter(new FileWriter(m_sRopFile, true)))
            {
                oFileOut.write(sRop[0]);
                for (int i = 1; i < sRop.length; i++)
                {
                    oFileOut.write("\t");
                    oFileOut.write(sRop[i]);
                }
                oFileOut.write("\n");
            }
        }
        oOut.write("{");
        writeJson(oOut, sRop[0], sRop[sRop.length - 1]); // id:data
        oOut.write("}");
    }
References cc.util.Text.getUUID(), cc.ws.Handler.ISO8601Sdf, cc.ws.RopMgr.m_oRops, cc.ws.RopMgr.m_sRopFile, cc.util.Text.removeWhitespace(), cc.ws.Handler.STR_ARR_COMP, and cc.ws.Handler.writeJson().
init()
void cc.ws.RopMgr.init () inline
Definition at line 30 of file RopMgr.java.
    {
        String sRopFile = getServletConfig().getInitParameter("ropfile");
        if (sRopFile != null && sRopFile.length() > 0)
        {
            m_sRopFile = sRopFile;
            new Thread(this).start();
        }
    }
References cc.ws.RopMgr.m_sRopFile.
run()
void cc.ws.RopMgr.run () inline
Definition at line 42 of file RopMgr.java.
    {
        try (CsvReader oIn = new CsvReader(new FileInputStream(m_sRopFile), '\t'))
        {
            int nCols;
            String[] sSearch = new String[1];
            synchronized(m_oRops)
            {
                while ((nCols = oIn.readLine()) > 0)
                {
                    sSearch[0] = oIn.parseString(0);
                    int nIndex = Collections.binarySearch(m_oRops, sSearch, STR_ARR_COMP); // search for id in list
                    if (nIndex < 0)
                    {
                        nIndex = ~nIndex;
                        m_oRops.add(nIndex, new String[nCols]); // right now we have uuid,user,timestamp,status,JSON
                    }
                    update(m_oRops.get(nIndex), nCols, oIn); // replace with most recent update
                }
            }
        }
        catch (Exception oEx)
        {
        }
    }
References cc.ws.RopMgr.m_oRops, cc.ws.RopMgr.m_sRopFile, cc.ws.Handler.STR_ARR_COMP, and cc.ws.Handler.update().
Member Data Documentation
m_oRops
ArrayList<String[]> cc.ws.RopMgr.m_oRops = new ArrayList() protected
Definition at line 26 of file RopMgr.java.
Referenced by cc.ws.RopMgr.doDetails(), cc.ws.RopMgr.doNull(), cc.ws.RopMgr.doSave(), and cc.ws.RopMgr.run().
m_sRopFile
String cc.ws.RopMgr.m_sRopFile protected
Definition at line 25 of file RopMgr.java.
Referenced by cc.ws.RopMgr.doSave(), cc.ws.RopMgr.init(), and cc.ws.RopMgr.run().
The documentation for this class was generated from the following file:
src/cc/ws/RopMgr.java