Carma-cloud: cc.ctrl.proc.TdFeature Class Reference
cc.ctrl.proc.TdFeature Class Reference
Public Member Functions
TdFeature (double[] dGeo, int[] nTags, TrafCtrl oCtrl)
TdFeature (double[] dGeo, int[] nTags, byte[] yId)
TdFeature (DataInputStream oIn, int nTags, byte[] yId) throws IOException
TdFeature (DataInputStream oIn, int nTags) throws IOException
void write (DataOutputStream oOut) throws IOException
int getBytesToSkip ()
Public Attributes
double[] m_dGeo
int[] m_nTags
byte[] m_yCtrlId
Detailed Description
Author
aaron.cherney
Definition at line 19 of file TdFeature.java.
Constructor & Destructor Documentation
TdFeature() [1/4]
cc.ctrl.proc.TdFeature.TdFeature (double[] dGeo, int[] nTags, TrafCtrl oCtrl) inline
Definition at line 25 of file TdFeature.java.
    {
        this(dGeo, nTags, oCtrl.m_yId);
    }
References cc.ctrl.TrafCtrl.m_yId.
TdFeature() [2/4]
cc.ctrl.proc.TdFeature.TdFeature (double[] dGeo, int[] nTags, byte[] yId) inline
Definition at line 31 of file TdFeature.java.
    {
        m_dGeo = Arrays.newDoubleArray(Arrays.size(dGeo) -1 );
        System.arraycopy(dGeo, 0, m_dGeo, 0, m_dGeo.length);
        m_nTags = new int[nTags.length];
        System.arraycopy(nTags, 0, m_nTags, 0, nTags.length);
        m_yCtrlId = new byte[yId.length];
        System.arraycopy(yId, 0, m_yCtrlId, 0, yId.length);
    }
References cc.ctrl.proc.TdFeature.m_dGeo, cc.ctrl.proc.TdFeature.m_nTags, cc.ctrl.proc.TdFeature.m_yCtrlId, cc.util.Arrays.newDoubleArray(), and cc.util.Arrays.size().
TdFeature() [3/4]
cc.ctrl.proc.TdFeature.TdFeature (DataInputStream oIn, int nTags, byte[] yId) throws IOException inline
Definition at line 42 of file TdFeature.java.
    {
        m_yCtrlId = new byte[yId.length];
        System.arraycopy(yId, 0, m_yCtrlId, 0, yId.length);
        m_nTags = new int[nTags];
        for (int nIndex = 0; nIndex < nTags; nIndex++)
            m_nTags[nIndex] = oIn.readInt();
        int nOrdinates = oIn.readInt();
        double[] dGeo = Arrays.newDoubleArray(nOrdinates + 1);
        for (int nIndex = 0; nIndex < nOrdinates; nIndex++)
            dGeo = Arrays.add(dGeo, oIn.readDouble());
        m_dGeo = dGeo; // save local variable to member variable
    }
References cc.util.Arrays.add(), cc.ctrl.proc.TdFeature.m_dGeo, cc.ctrl.proc.TdFeature.m_nTags, cc.ctrl.proc.TdFeature.m_yCtrlId, and cc.util.Arrays.newDoubleArray().
TdFeature() [4/4]
cc.ctrl.proc.TdFeature.TdFeature (DataInputStream oIn, int nTags) throws IOException inline
Definition at line 59 of file TdFeature.java.
    {
        m_yCtrlId = new byte[16];
        oIn.read(m_yCtrlId);
        oIn.skipBytes(4); // skip the bytes to skip number
        m_nTags = new int[nTags];
        for (int nIndex = 0; nIndex < nTags; nIndex++)
            m_nTags[nIndex] = oIn.readInt();
        int nOrdinates = oIn.readInt();
        double[] dGeo = Arrays.newDoubleArray(nOrdinates + 1);
        for (int nIndex = 0; nIndex < nOrdinates; nIndex++)
            dGeo = Arrays.add(dGeo, oIn.readDouble());
        m_dGeo = dGeo; // save local variable to member variable
    }
References cc.util.Arrays.add(), cc.ctrl.proc.TdFeature.m_dGeo, cc.ctrl.proc.TdFeature.m_nTags, cc.ctrl.proc.TdFeature.m_yCtrlId, and cc.util.Arrays.newDoubleArray().
Member Function Documentation
getBytesToSkip()
int cc.ctrl.proc.TdFeature.getBytesToSkip () inline
Definition at line 92 of file TdFeature.java.
    {
        int nTotalBytes = m_nTags.length * 4; // 4 bytes for each int in tags
        nTotalBytes += 4; // 4 bytes for number of ordinates
        nTotalBytes += (Arrays.size(m_dGeo) - 1) * 8; // 8 bytes for each double ordinate
        return nTotalBytes;
    }
References cc.ctrl.proc.TdFeature.m_dGeo, and cc.util.Arrays.size().
Referenced by cc.ctrl.proc.TdFeature.write().
write()
void cc.ctrl.proc.TdFeature.write (DataOutputStream oOut) throws IOException inline
Definition at line 77 of file TdFeature.java.
    {
        oOut.write(m_yCtrlId);
        oOut.writeInt(getBytesToSkip());
        for (int nTag : m_nTags)
            oOut.writeInt(nTag);
        oOut.writeInt(Arrays.size(m_dGeo) - 1);
        Iterator<double[]> oIt = Arrays.iterator(m_dGeo, new double[1], 1, 1);
        while (oIt.hasNext())
        {
            oOut.writeDouble(oIt.next()[0]);
        }
    }
References cc.ctrl.proc.TdFeature.getBytesToSkip(), cc.util.Arrays.iterator(), cc.ctrl.proc.TdFeature.m_dGeo, cc.ctrl.proc.TdFeature.m_nTags, cc.ctrl.proc.TdFeature.m_yCtrlId, and cc.util.Arrays.size().
Referenced by cc.ctrl.proc.TdLayer.write().
Member Data Documentation
m_dGeo
double [] cc.ctrl.proc.TdFeature.m_dGeo
Definition at line 21 of file TdFeature.java.
Referenced by cc.ctrl.proc.TdFeature.TdFeature(), cc.ctrl.proc.TdFeature.getBytesToSkip(), and cc.ctrl.proc.TdFeature.write().
m_nTags
int [] cc.ctrl.proc.TdFeature.m_nTags
Definition at line 22 of file TdFeature.java.
Referenced by cc.ctrl.proc.TdFeature.TdFeature(), and cc.ctrl.proc.TdFeature.write().
m_yCtrlId
byte [] cc.ctrl.proc.TdFeature.m_yCtrlId
Definition at line 23 of file TdFeature.java.
Referenced by cc.ctrl.proc.TdFeature.TdFeature(), and cc.ctrl.proc.TdFeature.write().
The documentation for this class was generated from the following file:
src/cc/ctrl/proc/TdFeature.java