Carma-cloud: cc.ctrl.TrafCtrlEnums Class Reference
cc.ctrl.TrafCtrlEnums Class Reference abstract
Static Public Member Functions
static int getVtype (String sVType)
static int getCtrl (String sCtrl)
static int getCtrlVal (String sCtrl, String sVal)
static void getCtrlValString (String sCtrl, byte[] yVal, ArrayList< String > sVals)
static void getCtrlValString (int nCtrl, byte[] yVal, ArrayList< String > sVals)
Static Public Attributes
static final String[][] CTRLS
static final String[][] UNITS
static final char[] DAYCHARS
static final String[] DAYS
static final String[] VTYPES
static final String[][] VTYPEGROUPS
Private Member Functions
TrafCtrlEnums ()
Detailed Description
Definition at line 8 of file TrafCtrlEnums.java.
Constructor & Destructor Documentation
TrafCtrlEnums()
cc.ctrl.TrafCtrlEnums.TrafCtrlEnums () inline private
Definition at line 111 of file TrafCtrlEnums.java.
    {
    }
Member Function Documentation
getCtrl()
static int cc.ctrl.TrafCtrlEnums.getCtrl (String sCtrl) inline static
Definition at line 128 of file TrafCtrlEnums.java.
    {
        int nIndex = CTRLS.length;
        while (nIndex-- > 0)
        {
            if (sCtrl.compareTo(CTRLS[nIndex][0]) == 0)
                return nIndex;
        }
        return Integer.MIN_VALUE;
    }
References cc.ctrl.TrafCtrlEnums.CTRLS.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ws.TcmReqServlet.[static initializer](), cc.ws.CtrlTiles.addControl(), cc.ws.WxPoly.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.TrafCtrlEnums.getCtrlVal(), cc.ctrl.TrafCtrlEnums.getCtrlValString(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), and cc.ws.CtrlTiles.saveEdit().
getCtrlVal()
static int cc.ctrl.TrafCtrlEnums.getCtrlVal (String sCtrl, String sVal) inline static
Definition at line 140 of file TrafCtrlEnums.java.
    {
        int nIndex = getCtrl(sCtrl);
        if (nIndex >= 0)
        {
            String[] sVals = CTRLS[nIndex];
            nIndex = sVals.length;
            while (nIndex-- > 1) // first value (index 0) is ctrl type
            {
                if (sVal.compareTo(sVals[nIndex]) == 0)
                    return nIndex;
            }
        }
        return Integer.MIN_VALUE;
    }
References cc.ctrl.TrafCtrlEnums.CTRLS, and cc.ctrl.TrafCtrlEnums.getCtrl().
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.proc.ProcLatPerm.getInnerLatPerm(), cc.ctrl.proc.ProcLatPerm.getOuterLatPerm(), cc.rsm.RsmParser.parseRequest(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcOpening.renderTiledData(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), and cc.ctrl.proc.ProcClosing.renderTiledData().
getCtrlValString() [1/2]
static void cc.ctrl.TrafCtrlEnums.getCtrlValString (int nCtrl, byte[] yVal, ArrayList< String > sVals) inline static
Definition at line 163 of file TrafCtrlEnums.java.
    {
        sVals.add(CTRLS[nCtrl][0]); // ctrl name
        if (nCtrl == getCtrl("signal"))
        {
            sVals.add(Text.toHexString(yVal));
            return;
        }
        if (CTRLS[nCtrl].length == 1) // not enumerated type
        {
            if (yVal.length > 0) // negative values aren't valid
                sVals.add(Integer.toString(MathUtil.bytesToInt(yVal)));
            return;
        }
        int nLatPerm = getCtrl("latperm");
        if (nCtrl == nLatPerm)
        {
            sVals.add(CTRLS[nCtrl][((yVal[2] & 0xff) << 8) | (yVal[3] & 0xff)]); // outer
//          sVals.add(CTRLS[nCtrl][(nVal & 0xffff)]);
            sVals.add(CTRLS[nCtrl][0]);
            sVals.add(CTRLS[nCtrl][((yVal[0] & 0xff) << 8) | (yVal[1] & 0xff)]); // inner
//          sVals.add(CTRLS[nCtrl][((nVal >> 16) & 0xffff)]);
        }
        else
        {
            sVals.add(CTRLS[nCtrl][MathUtil.bytesToInt(yVal)]);
        }
    }
References cc.util.MathUtil.bytesToInt(), cc.ctrl.TrafCtrlEnums.CTRLS, cc.ctrl.TrafCtrlEnums.getCtrl(), and cc.util.Text.toHexString().
getCtrlValString() [2/2]
static void cc.ctrl.TrafCtrlEnums.getCtrlValString (String sCtrl, byte[] yVal, ArrayList< String > sVals) inline static
Definition at line 157 of file TrafCtrlEnums.java.
    {
        getCtrlValString(getCtrl(sCtrl), yVal, sVals);
    }
References cc.ctrl.TrafCtrlEnums.getCtrl(), and cc.ctrl.TrafCtrlEnums.getCtrlValString().
Referenced by cc.ws.GeoLanes.doPost(), cc.ctrl.TrafCtrlEnums.getCtrlValString(), cc.ctrl.TrafCtrl.getXml(), cc.util.MathUtil.main(), and cc.ws.CtrlTiles.saveEdit().
getVtype()
static int cc.ctrl.TrafCtrlEnums.getVtype (String sVType) inline static
Definition at line 116 of file TrafCtrlEnums.java.
    {
        int nIndex = VTYPES.length;
        while (nIndex-- > 0)
        {
            if (sVType.compareTo(VTYPES[nIndex]) == 0)
                return nIndex;
        }
        return Integer.MIN_VALUE;
    }
References cc.ctrl.TrafCtrlEnums.VTYPES.
Member Data Documentation
CTRLS
final String [][] cc.ctrl.TrafCtrlEnums.CTRLS static
Initial value:
= new String[][]
    {
        {"signal"},
        {"stop"},
        {"yield"},
        {"notowing"},
        {"restricted"},
        {"closed", "open", "notopen", "taperleft", "taperright", "openleft", "openright"},
        {"chains", "no", "permitted", "required"},
        {"direction", "forward", "reverse"},
        {"lataffinity", "left", "right"},
        {"latperm", "none", "permitted", "passing-only", "emergency-only"},
        {"parking", "no", "parallel", "angled"},
        {"minspeed"},
        {"maxspeed"},
        {"minhdwy"},
        {"maxvehmass"},
        {"maxvehheight"},
        {"maxvehwidth"},
        {"maxvehlength"},
        {"maxaxles"},
        {"minvehocc"},
        {"pavement"},
        {"debug"},
        {"maxplatoonsize"},
        {"minplatoonhdwy"}
    }
Definition at line 10 of file TrafCtrlEnums.java.
Referenced by cc.ws.CtrlTiles.addControl(), cc.ctrl.CreateCtrls.createCtrl(), cc.ws.CtrlTiles.doPost(), cc.ws.GeoLanes.doPost(), cc.ctrl.TrafCtrlEnums.getCtrl(), cc.ctrl.TrafCtrlEnums.getCtrlVal(), cc.ctrl.TrafCtrlEnums.getCtrlValString(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.RenderCtrl.main(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ws.CtrlTiles.saveEdit(), and cc.ctrl.TrafCtrl.writeJson().
DAYCHARS
final char [] cc.ctrl.TrafCtrlEnums.DAYCHARS static
Initial value:
= new char[]
    {
        'S', 'M', 'T', 'W', 'R', 'F', 'A'
    }
Definition at line 67 of file TrafCtrlEnums.java.
Referenced by cc.ctrl.TrafCtrl.writeJson().
DAYS
final String [] cc.ctrl.TrafCtrlEnums.DAYS static
Initial value:
= new String[]
    {
        "sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"
    }
Definition at line 73 of file TrafCtrlEnums.java.
UNITS
final String [][] cc.ctrl.TrafCtrlEnums.UNITS static
Initial value:
= new String[][]
    {
        new String[0],
        new String[0],
        new String[0],
        new String[0],
        new String[0],
        new String[0],
        new String[0],
        new String[0],
        new String[0],
        new String[0],
        new String[0],
        new String[]{"dm/s", "mph", "kph"},
        new String[]{"dm/s", "mph", "kph"},
        new String[]{"dm", "ft", "m"},
        new String[]{"kg", "lb", "kg"},
        new String[]{"dm", "ft", "m"},
        new String[]{"dm", "ft", "m"},
        new String[]{"dm", "ft", "m"},
        new String[0],
        new String[0],
        new String[0],
        new String[0],
        new String[0],
        new String[]{"dm", "ft", "m"}
    }
Definition at line 39 of file TrafCtrlEnums.java.
Referenced by cc.ws.CtrlTiles.addControl(), cc.ws.CtrlTiles.doPost(), cc.ws.GeoLanes.doPost(), cc.ws.WxPoly.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), and cc.ws.CtrlTiles.saveEdit().
VTYPEGROUPS
final String [][] cc.ctrl.TrafCtrlEnums.VTYPEGROUPS static
Initial value:
= new String[][]
    {
        new String[]{"no motor", "pedestrian", "bicycle"},
        new String[]{"motor bikes", "micromobile", "motorcycle"},
        new String[]{"small vehicles", "passenger-car", "light-truck-van"},
        new String[]{"large vehicles", "bus", "two-axle-six-tire-single-unit-truck", "three-axle-single-unit-truck", "four-or-more-axle-single-unit-truck", "four-or-fewer-axle-single-trailer-truck", "five-axle-single-trailer-truck", "six-or-more-axle-single-trailer-truck", "five-or-fewer-axle-multi-trailer-truck", "six-axle-multi-trailer-truck", "seven-or-more-axle-multi-trailer-truck"},
        new String[]{"other", "rail", "unclassified"}
    }
Definition at line 101 of file TrafCtrlEnums.java.
Referenced by cc.ws.CtrlTiles.doPost().
VTYPES
final String [] cc.ctrl.TrafCtrlEnums.VTYPES static
Initial value:
= new String[]
    {
        "pedestrian",
        "bicycle",
        "micromobile",
        "motorcycle",
        "passenger-car",
        "light-truck-van",
        "bus",
        "two-axle-six-tire-single-unit-truck",
        "three-axle-single-unit-truck",
        "four-or-more-axle-single-unit-truck",
        "four-or-fewer-axle-single-trailer-truck",
        "five-axle-single-trailer-truck",
        "six-or-more-axle-single-trailer-truck",
        "five-or-fewer-axle-multi-trailer-truck",
        "six-axle-multi-trailer-truck",
        "seven-or-more-axle-multi-trailer-truck",
        "rail",
        "unclassified"
    }
Definition at line 78 of file TrafCtrlEnums.java.
Referenced by cc.ws.CtrlTiles.doPost(), cc.ctrl.TrafCtrlEnums.getVtype(), cc.ctrl.TrafCtrl.getXml(), and cc.ctrl.TrafCtrl.writeJson().
The documentation for this class was generated from the following file:
src/cc/ctrl/TrafCtrlEnums.java