Carma-cloud: cc.vector_tile.VectorTile.Tile.Layer.Builder Class Reference
cc.vector_tile.VectorTile.Tile.Layer.Builder Class Reference
Public Member Functions
boolean hasVersion ()
int getVersion ()
Builder setVersion (int value)
Builder clearVersion ()
boolean hasName ()
java.lang.String getName ()
com.google.protobuf.ByteString getNameBytes ()
Builder setName (java.lang.String value)
Builder clearName ()
Builder setNameBytes (com.google.protobuf.ByteString value)
java.util.List< cc.vector_tile.VectorTile.Tile.Feature > getFeaturesList ()
int getFeaturesCount ()
cc.vector_tile.VectorTile.Tile.Feature getFeatures (int index)
Builder setFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature value)
Builder setFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature.Builder builderForValue)
Builder addFeatures (cc.vector_tile.VectorTile.Tile.Feature value)
Builder addFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature value)
Builder addFeatures (cc.vector_tile.VectorTile.Tile.Feature.Builder builderForValue)
Builder addFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature.Builder builderForValue)
Builder addAllFeatures (java.lang.Iterable<? extends cc.vector_tile.VectorTile.Tile.Feature > values)
Builder clearFeatures ()
Builder removeFeatures (int index)
java.util.List< java.lang.String > getKeysList ()
int getKeysCount ()
java.lang.String getKeys (int index)
com.google.protobuf.ByteString getKeysBytes (int index)
Builder setKeys (int index, java.lang.String value)
Builder addKeys (java.lang.String value)
Builder addAllKeys (java.lang.Iterable< java.lang.String > values)
Builder clearKeys ()
Builder addKeysBytes (com.google.protobuf.ByteString value)
java.util.List< cc.vector_tile.VectorTile.Tile.Value > getValuesList ()
int getValuesCount ()
cc.vector_tile.VectorTile.Tile.Value getValues (int index)
Builder setValues (int index, cc.vector_tile.VectorTile.Tile.Value value)
Builder setValues (int index, cc.vector_tile.VectorTile.Tile.Value.Builder builderForValue)
Builder addValues (cc.vector_tile.VectorTile.Tile.Value value)
Builder addValues (int index, cc.vector_tile.VectorTile.Tile.Value value)
Builder addValues (cc.vector_tile.VectorTile.Tile.Value.Builder builderForValue)
Builder addValues (int index, cc.vector_tile.VectorTile.Tile.Value.Builder builderForValue)
Builder addAllValues (java.lang.Iterable<? extends cc.vector_tile.VectorTile.Tile.Value > values)
Builder clearValues ()
Builder removeValues (int index)
boolean hasExtent ()
int getExtent ()
Builder setExtent (int value)
Builder clearExtent ()
boolean hasVersion ()
int getVersion ()
boolean hasName ()
java.lang.String getName ()
com.google.protobuf.ByteString getNameBytes ()
java.util.List< cc.vector_tile.VectorTile.Tile.Feature > getFeaturesList ()
cc.vector_tile.VectorTile.Tile.Feature getFeatures (int index)
int getFeaturesCount ()
java.util.List< java.lang.String > getKeysList ()
int getKeysCount ()
java.lang.String getKeys (int index)
com.google.protobuf.ByteString getKeysBytes (int index)
java.util.List< cc.vector_tile.VectorTile.Tile.Value > getValuesList ()
cc.vector_tile.VectorTile.Tile.Value getValues (int index)
int getValuesCount ()
boolean hasExtent ()
int getExtent ()
Private Member Functions
Builder ()
Detailed Description
Layers are described in section 4.1 of the specification
Protobuf type vector_tile.Tile.Layer
Definition at line 2731 of file VectorTile.java.
Constructor & Destructor Documentation
Builder()
cc.vector_tile.VectorTile.Tile.Layer.Builder.Builder () inline private
Definition at line 2737 of file VectorTile.java.
{
          super(DEFAULT_INSTANCE);
        }
References cc.vector_tile.VectorTile.Tile.Layer.DEFAULT_INSTANCE.
Member Function Documentation
addAllFeatures()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.addAllFeatures (java.lang.Iterable<? extends cc.vector_tile.VectorTile.Tile.Feature > values) inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2967 of file VectorTile.java.
{
          copyOnWrite();
          instance.addAllFeatures(values);
          return this;
        }
addAllKeys()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.addAllKeys (java.lang.Iterable< java.lang.String > values) inline
Dictionary encoding for keys
repeated string keys = 3;
Definition at line 3078 of file VectorTile.java.
{
          copyOnWrite();
          instance.addAllKeys(values);
          return this;
        }
addAllValues()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.addAllValues (java.lang.Iterable<? extends cc.vector_tile.VectorTile.Tile.Value > values) inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 3227 of file VectorTile.java.
{
          copyOnWrite();
          instance.addAllValues(values);
          return this;
        }
addFeatures() [1/4]
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.addFeatures (cc.vector_tile.VectorTile.Tile.Feature value) inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2916 of file VectorTile.java.
{
          copyOnWrite();
          instance.addFeatures(value);
          return this;
        }
addFeatures() [2/4]
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.addFeatures (cc.vector_tile.VectorTile.Tile.Feature.Builder builderForValue) inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2941 of file VectorTile.java.
{
          copyOnWrite();
          instance.addFeatures(builderForValue);
          return this;
        }
addFeatures() [3/4]
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.addFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature value) inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2928 of file VectorTile.java.
{
          copyOnWrite();
          instance.addFeatures(index, value);
          return this;
        }
addFeatures() [4/4]
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.addFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature.Builder builderForValue) inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2954 of file VectorTile.java.
{
          copyOnWrite();
          instance.addFeatures(index, builderForValue);
          return this;
        }
addKeys()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.addKeys (java.lang.String value) inline
Dictionary encoding for keys
repeated string keys = 3;
Definition at line 3065 of file VectorTile.java.
{
          copyOnWrite();
          instance.addKeys(value);
          return this;
        }
addKeysBytes()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.addKeysBytes (com.google.protobuf.ByteString value) inline
Dictionary encoding for keys
repeated string keys = 3;
Definition at line 3103 of file VectorTile.java.
{
          copyOnWrite();
          instance.addKeysBytes(value);
          return this;
        }
addValues() [1/4]
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.addValues (cc.vector_tile.VectorTile.Tile.Value value) inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 3176 of file VectorTile.java.
{
          copyOnWrite();
          instance.addValues(value);
          return this;
        }
addValues() [2/4]
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.addValues (cc.vector_tile.VectorTile.Tile.Value.Builder builderForValue) inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 3201 of file VectorTile.java.
{
          copyOnWrite();
          instance.addValues(builderForValue);
          return this;
        }
addValues() [3/4]
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.addValues (int index, cc.vector_tile.VectorTile.Tile.Value value) inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 3188 of file VectorTile.java.
{
          copyOnWrite();
          instance.addValues(index, value);
          return this;
        }
addValues() [4/4]
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.addValues (int index, cc.vector_tile.VectorTile.Tile.Value.Builder builderForValue) inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 3214 of file VectorTile.java.
{
          copyOnWrite();
          instance.addValues(index, builderForValue);
          return this;
        }
clearExtent()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.clearExtent () inline
Although this is an "optional" field it is required by the specification.
See https://github.com/mapbox/vector-tile-spec/issues/47
optional uint32 extent = 5 [default = 4096];
Definition at line 3303 of file VectorTile.java.
{
          copyOnWrite();
          instance.clearExtent();
          return this;
        }
clearFeatures()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.clearFeatures () inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2980 of file VectorTile.java.
{
          copyOnWrite();
          instance.clearFeatures();
          return this;
        }
clearKeys()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.clearKeys () inline
Dictionary encoding for keys
repeated string keys = 3;
Definition at line 3091 of file VectorTile.java.
{
          copyOnWrite();
          instance.clearKeys();
          return this;
        }
clearName()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.clearName () inline
required string name = 1;
Definition at line 2835 of file VectorTile.java.
{
          copyOnWrite();
          instance.clearName();
          return this;
        }
clearValues()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.clearValues () inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 3240 of file VectorTile.java.
{
          copyOnWrite();
          instance.clearValues();
          return this;
        }
clearVersion()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.clearVersion () inline
Any compliant implementation must first read the version
number encoded in this message and choose the correct
implementation for this version number before proceeding to
decode other parts of this message.
required uint32 version = 15 [default = 1];
Definition at line 2795 of file VectorTile.java.
{
          copyOnWrite();
          instance.clearVersion();
          return this;
        }
getExtent()
int cc.vector_tile.VectorTile.Tile.Layer.Builder.getExtent () inline
Although this is an "optional" field it is required by the specification.
See https://github.com/mapbox/vector-tile-spec/issues/47
optional uint32 extent = 5 [default = 4096];
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 3279 of file VectorTile.java.
{
          return instance.getExtent();
        }
getFeatures()
cc.vector_tile.VectorTile.Tile.Feature cc.vector_tile.VectorTile.Tile.Layer.Builder.getFeatures (int index) inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2880 of file VectorTile.java.
{
          return instance.getFeatures(index);
        }
getFeaturesCount()
int cc.vector_tile.VectorTile.Tile.Layer.Builder.getFeaturesCount () inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2870 of file VectorTile.java.
{
          return instance.getFeaturesCount();
        }
getFeaturesList()
java.util.List< cc.vector_tile.VectorTile.Tile.Feature > cc.vector_tile.VectorTile.Tile.Layer.Builder.getFeaturesList () inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2858 of file VectorTile.java.
{
          return java.util.Collections.unmodifiableList(
              instance.getFeaturesList());
        }
getKeys()
java.lang.String cc.vector_tile.VectorTile.Tile.Layer.Builder.getKeys (int index) inline
Dictionary encoding for keys
repeated string keys = 3;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 3030 of file VectorTile.java.
{
          return instance.getKeys(index);
        }
getKeysBytes()
com.google.protobuf.ByteString cc.vector_tile.VectorTile.Tile.Layer.Builder.getKeysBytes (int index) inline
Dictionary encoding for keys
repeated string keys = 3;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 3042 of file VectorTile.java.
{
          return instance.getKeysBytes(index);
        }
getKeysCount()
int cc.vector_tile.VectorTile.Tile.Layer.Builder.getKeysCount () inline
Dictionary encoding for keys
repeated string keys = 3;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 3019 of file VectorTile.java.
{
          return instance.getKeysCount();
        }
getKeysList()
java.util.List< java.lang.String > cc.vector_tile.VectorTile.Tile.Layer.Builder.getKeysList () inline
Dictionary encoding for keys
repeated string keys = 3;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 3007 of file VectorTile.java.
{
          return java.util.Collections.unmodifiableList(
              instance.getKeysList());
        }
getName()
java.lang.String cc.vector_tile.VectorTile.Tile.Layer.Builder.getName () inline
required string name = 1;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2812 of file VectorTile.java.
{
          return instance.getName();
        }
getNameBytes()
com.google.protobuf.ByteString cc.vector_tile.VectorTile.Tile.Layer.Builder.getNameBytes () inline
required string name = 1;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2820 of file VectorTile.java.
{
          return instance.getNameBytes();
        }
getValues()
cc.vector_tile.VectorTile.Tile.Value cc.vector_tile.VectorTile.Tile.Layer.Builder.getValues (int index) inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 3140 of file VectorTile.java.
{
          return instance.getValues(index);
        }
getValuesCount()
int cc.vector_tile.VectorTile.Tile.Layer.Builder.getValuesCount () inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 3130 of file VectorTile.java.
{
          return instance.getValuesCount();
        }
getValuesList()
java.util.List< cc.vector_tile.VectorTile.Tile.Value > cc.vector_tile.VectorTile.Tile.Layer.Builder.getValuesList () inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 3118 of file VectorTile.java.
{
          return java.util.Collections.unmodifiableList(
              instance.getValuesList());
        }
getVersion()
int cc.vector_tile.VectorTile.Tile.Layer.Builder.getVersion () inline
Any compliant implementation must first read the version
number encoded in this message and choose the correct
implementation for this version number before proceeding to
decode other parts of this message.
required uint32 version = 15 [default = 1];
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2767 of file VectorTile.java.
{
          return instance.getVersion();
        }
hasExtent()
boolean cc.vector_tile.VectorTile.Tile.Layer.Builder.hasExtent () inline
Although this is an "optional" field it is required by the specification.
See https://github.com/mapbox/vector-tile-spec/issues/47
optional uint32 extent = 5 [default = 4096];
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 3267 of file VectorTile.java.
{
          return instance.hasExtent();
        }
hasName()
boolean cc.vector_tile.VectorTile.Tile.Layer.Builder.hasName () inline
required string name = 1;
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2805 of file VectorTile.java.
{
          return instance.hasName();
        }
hasVersion()
boolean cc.vector_tile.VectorTile.Tile.Layer.Builder.hasVersion () inline
Any compliant implementation must first read the version
number encoded in this message and choose the correct
implementation for this version number before proceeding to
decode other parts of this message.
required uint32 version = 15 [default = 1];
Implements cc.vector_tile.VectorTile.Tile.LayerOrBuilder.
Definition at line 2753 of file VectorTile.java.
{
          return instance.hasVersion();
        }
removeFeatures()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.removeFeatures (int index) inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2992 of file VectorTile.java.
{
          copyOnWrite();
          instance.removeFeatures(index);
          return this;
        }
removeValues()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.removeValues (int index) inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 3252 of file VectorTile.java.
{
          copyOnWrite();
          instance.removeValues(index);
          return this;
        }
setExtent()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.setExtent (int value) inline
Although this is an "optional" field it is required by the specification.
See https://github.com/mapbox/vector-tile-spec/issues/47
optional uint32 extent = 5 [default = 4096];
Definition at line 3290 of file VectorTile.java.
{
          copyOnWrite();
          instance.setExtent(value);
          return this;
        }
Referenced by cc.ws.CtrlTiles.doGet(), cc.ws.TrackTiles.doGet(), and cc.ws.ValidateXodrTiles.doGet().
setFeatures() [1/2]
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.setFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature value) inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2890 of file VectorTile.java.
{
          copyOnWrite();
          instance.setFeatures(index, value);
          return this;
        }
setFeatures() [2/2]
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.setFeatures (int index, cc.vector_tile.VectorTile.Tile.Feature.Builder builderForValue) inline
The actual features in this tile.
repeated .vector_tile.Tile.Feature features = 2;
Definition at line 2903 of file VectorTile.java.
{
          copyOnWrite();
          instance.setFeatures(index, builderForValue);
          return this;
        }
setKeys()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.setKeys (int index, java.lang.String value) inline
Dictionary encoding for keys
repeated string keys = 3;
Definition at line 3052 of file VectorTile.java.
{
          copyOnWrite();
          instance.setKeys(index, value);
          return this;
        }
setName()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.setName (java.lang.String value) inline
required string name = 1;
Definition at line 2826 of file VectorTile.java.
{
          copyOnWrite();
          instance.setName(value);
          return this;
        }
Referenced by cc.ws.TrackTiles.doGet().
setNameBytes()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.setNameBytes (com.google.protobuf.ByteString value) inline
required string name = 1;
Definition at line 2843 of file VectorTile.java.
{
          copyOnWrite();
          instance.setNameBytes(value);
          return this;
        }
setValues() [1/2]
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.setValues (int index, cc.vector_tile.VectorTile.Tile.Value value) inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 3150 of file VectorTile.java.
{
          copyOnWrite();
          instance.setValues(index, value);
          return this;
        }
setValues() [2/2]
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.setValues (int index, cc.vector_tile.VectorTile.Tile.Value.Builder builderForValue) inline
Dictionary encoding for values
repeated .vector_tile.Tile.Value values = 4;
Definition at line 3163 of file VectorTile.java.
{
          copyOnWrite();
          instance.setValues(index, builderForValue);
          return this;
        }
setVersion()
Builder cc.vector_tile.VectorTile.Tile.Layer.Builder.setVersion (int value) inline
Any compliant implementation must first read the version
number encoded in this message and choose the correct
implementation for this version number before proceeding to
decode other parts of this message.
required uint32 version = 15 [default = 1];
Definition at line 2780 of file VectorTile.java.
{
          copyOnWrite();
          instance.setVersion(value);
          return this;
        }
Referenced by cc.ws.CtrlTiles.doGet(), cc.ws.TrackTiles.doGet(), and cc.ws.ValidateXodrTiles.doGet().
The documentation for this class was generated from the following file:
src/cc/vector_tile/VectorTile.java