Carma-cloud: cc.rsu.BSMRequestParser Class Reference
cc.rsu.BSMRequestParser Class Reference
Public Member Functions
BSMRequestParser ()
void characters (char[] cBuf, int nPos, int nLen)
void startElement (String sUri, String sLocalName, String sQname, Attributes iAtt)
void endElement (String sUri, String sLocalName, String sQname) throws SAXException
BSMRequest parseRequest (InputStream oIn)
Protected Attributes
BSMRequest bsmReq
Position loc = null
ArrayList< Position > route = null
StringBuilder m_sbuf = new StringBuilder()
double TENTH_MICRO_DEG_PER_DEG = 10000000.0
Detailed Description
Definition at line 16 of file BSMRequestParser.java.
Constructor & Destructor Documentation
BSMRequestParser()
cc.rsu.BSMRequestParser.BSMRequestParser () inline
Definition at line 23 of file BSMRequestParser.java.
{
        super();
    }
Member Function Documentation
characters()
void cc.rsu.BSMRequestParser.characters (char[] cBuf, int nPos, int nLen) inline
Definition at line 28 of file BSMRequestParser.java.
{
        m_sbuf.setLength(0);
        m_sbuf.append(cBuf, nPos, nLen);
    }
References cc.rsu.BSMRequestParser.m_sbuf.
endElement()
void cc.rsu.BSMRequestParser.endElement (String sUri, String sLocalName, String sQname) throws SAXException inline
Definition at line 53 of file BSMRequestParser.java.
{
        switch (sQname.toLowerCase()) {
        case "bsmrequest":
            break;
        case "id":
            bsmReq.setId(m_sbuf.toString());
            break;
        case "route":
            bsmReq.setRoute(route);
            break;
        case "point":
            route.add(loc);
            break;
        case "latitude":
                /***
                 * /ASN.1 Representation:
                 * Latitude ::= INTEGER (-900000000..900000001)
                 * Longitude ::= INTEGER (-1799999999..1800000001)
                 * The incoming latitude and longitude values need to be devided (in 1/10th micodegree) by 10000000.0 before passing it on to the rest of the system
                 */
            loc.setLatitude((Long.parseLong(m_sbuf.toString()) / TENTH_MICRO_DEG_PER_DEG));
            break;
        case "longitude":
            loc.setlongitude((Long.parseLong(m_sbuf.toString()) / TENTH_MICRO_DEG_PER_DEG));
            break;
        default:
            break;
        }
    }
References cc.rsu.BSMRequestParser.bsmReq, cc.rsu.BSMRequestParser.loc, cc.rsu.BSMRequestParser.m_sbuf, cc.rsu.BSMRequestParser.route, cc.rsu.BSMRequest.setId(), cc.rsu.Position.setLatitude(), cc.rsu.Position.setlongitude(), cc.rsu.BSMRequest.setRoute(), and cc.rsu.BSMRequestParser.TENTH_MICRO_DEG_PER_DEG.
parseRequest()
BSMRequest cc.rsu.BSMRequestParser.parseRequest (InputStream oIn) inline
Definition at line 83 of file BSMRequestParser.java.
{
        try {
            bsmReq = new BSMRequest();
            XMLReader iXmlReader = SAXParserFactory.newInstance().newSAXParser().getXMLReader();
            iXmlReader.setContentHandler(this);
            iXmlReader.parse(new InputSource(oIn));
            return bsmReq;
        } catch (SAXException e) {
            e.printStackTrace();
        } catch (ParserConfigurationException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
References cc.rsu.BSMRequestParser.bsmReq.
Referenced by cc.ws.RSUServlet.requestRSU().
startElement()
void cc.rsu.BSMRequestParser.startElement (String sUri, String sLocalName, String sQname, Attributes iAtt) inline
Definition at line 34 of file BSMRequestParser.java.
{
        switch (sQname.toLowerCase()) {
        case "bsmrequest":
            break;
        case "id":
            break;
        case "route":
            if (route == null) {
                route = new ArrayList<>();
            }
            break;
        case "point":
            loc = new Position();
        default:
            break;
        }
    }
References cc.rsu.BSMRequestParser.loc, and cc.rsu.BSMRequestParser.route.
Member Data Documentation
bsmReq
BSMRequest cc.rsu.BSMRequestParser.bsmReq protected
Definition at line 17 of file BSMRequestParser.java.
Referenced by cc.rsu.BSMRequestParser.endElement(), and cc.rsu.BSMRequestParser.parseRequest().
loc
Position cc.rsu.BSMRequestParser.loc = null protected
Definition at line 18 of file BSMRequestParser.java.
Referenced by cc.rsu.BSMRequestParser.endElement(), and cc.rsu.BSMRequestParser.startElement().
m_sbuf
StringBuilder cc.rsu.BSMRequestParser.m_sbuf = new StringBuilder() protected
Definition at line 20 of file BSMRequestParser.java.
Referenced by cc.rsu.BSMRequestParser.characters(), and cc.rsu.BSMRequestParser.endElement().
route
ArrayList<Position> cc.rsu.BSMRequestParser.route = null protected
Definition at line 19 of file BSMRequestParser.java.
Referenced by cc.rsu.BSMRequestParser.endElement(), and cc.rsu.BSMRequestParser.startElement().
TENTH_MICRO_DEG_PER_DEG
double cc.rsu.BSMRequestParser.TENTH_MICRO_DEG_PER_DEG = 10000000.0 protected
Definition at line 21 of file BSMRequestParser.java.
Referenced by cc.rsu.BSMRequestParser.endElement().
The documentation for this class was generated from the following file:
src/cc/rsu/BSMRequestParser.java