Carma-cloud: cc.rsu.GeodesicCartesianConverter Class Reference
cc.rsu.GeodesicCartesianConverter Class Reference
Public Member Functions
Position cartesian2Geodesic (Point point)
Point geodesic2Cartesian (Position location)
Static Public Attributes
static final double RADIANS_TO_DEGREES = 180.0 / Math.PI
static final double DEGREES_TO_RADIANS = Math.PI / 180.0
Protected Attributes
final double Rea = 6378137.0
final double Rea_sqr = Rea * Rea
final double f = 1.0 / 298.257223563
final double Reb = Rea * (1.0 - f)
final double Reb_sqr = Reb * Reb
final double e = 0.08181919084262149
final double e_sqr = e * e
final double e_p = 0.08209443794969568
Detailed Description
Definition at line 3 of file GeodesicCartesianConverter.java.
Member Function Documentation
cartesian2Geodesic()
Position cc.rsu.GeodesicCartesianConverter.cartesian2Geodesic (Point point) inline
Converts a given 3d cartesian point into a WSG-84 geodesic location The provided point should be defined relative to a frame
Parameters
point The cartesian point to be converted
Returns
The calculated WSG-84 geodesic location
Definition at line 23 of file GeodesicCartesianConverter.java.
{
        double x = point.getX();
        double y = point.getY();
        double z = point.getZ();
        // Calculate lat,lon,alt
        double p = Math.sqrt((x * x) + (y * y));
        // Handle special case of poles
        if (p < 1.0e-10) {
            double poleLat = z < 0 ? -90 : 90;
            double poleLon = 0;
            double poleAlt = z < 0 ? -z - Reb : z - Reb;
            return new Position(poleLat, poleLon, poleAlt);
        }
        double theta = Math.atan((z * Rea) / (p * Reb));
        double lon = 2.0 * Math.atan(y / (x + p));
        double lat = Math.atan((z + (e_p * e_p) * Reb * Math.pow(Math.sin(theta), 3))
                / (p - e_sqr * Rea * Math.pow(Math.cos(theta), 3)));
        double cosLat = Math.cos(lat);
        double sinLat = Math.sin(lat);
        double N = Rea_sqr / Math.sqrt(Rea_sqr * cosLat * cosLat + Reb_sqr * sinLat * sinLat);
        double alt = (p / cosLat) - N;
        return new Position(Math.toDegrees(lat), Math.toDegrees(lon), alt);
    }
References cc.rsu.GeodesicCartesianConverter.e, cc.rsu.GeodesicCartesianConverter.e_p, cc.rsu.GeodesicCartesianConverter.e_sqr, cc.rsu.Point.getX(), cc.rsu.Point.getY(), cc.rsu.Point.getZ(), cc.rsu.GeodesicCartesianConverter.Rea, cc.rsu.GeodesicCartesianConverter.Rea_sqr, cc.rsu.GeodesicCartesianConverter.Reb, and cc.rsu.GeodesicCartesianConverter.Reb_sqr.
geodesic2Cartesian()
Point cc.rsu.GeodesicCartesianConverter.geodesic2Cartesian (Position location) inline
Converts a given WSG-84 geodesic location into a 3d cartesian point The returned 3d point is defined relative to a frame
Parameters
location The geodesic location to convert
Returns
The calculated 3d point
Definition at line 57 of file GeodesicCartesianConverter.java.
{
        double lonRad = Math.toRadians(location.getlongitude());
        double latRad = Math.toRadians(location.getLatitude());
        double alt = location.getAltitude();
        double sinLat = Math.sin(latRad);
        double sinLon = Math.sin(lonRad);
        double cosLat = Math.cos(latRad);
        double cosLon = Math.cos(lonRad);
        double Ne = Rea / Math.sqrt(1.0 - e_sqr * sinLat * sinLat);// The prime vertical radius of curvature
        double x = (Ne + alt) * cosLat * cosLon;
        double y = (Ne + alt) * cosLat * sinLon;
        double z = (Ne * (1 - e_sqr) + alt) * sinLat;
        return new Point(x, y, z);
    }
References cc.rsu.GeodesicCartesianConverter.e_sqr, cc.rsu.Position.getAltitude(), cc.rsu.Position.getLatitude(), cc.rsu.Position.getlongitude(), and cc.rsu.GeodesicCartesianConverter.Rea.
Referenced by cc.rsu.RSUBoundingbox.RSUBoundingbox(), and cc.rsu.RSUIdentificationTask.call().
Member Data Documentation
DEGREES_TO_RADIANS
final double cc.rsu.GeodesicCartesianConverter.DEGREES_TO_RADIANS = Math.PI / 180.0 static
Definition at line 15 of file GeodesicCartesianConverter.java.
e
final double cc.rsu.GeodesicCartesianConverter.e = 0.08181919084262149 protected
Definition at line 9 of file GeodesicCartesianConverter.java.
Referenced by cc.rsu.GeodesicCartesianConverter.cartesian2Geodesic().
e_p
final double cc.rsu.GeodesicCartesianConverter.e_p = 0.08209443794969568 protected
Definition at line 12 of file GeodesicCartesianConverter.java.
Referenced by cc.rsu.GeodesicCartesianConverter.cartesian2Geodesic().
e_sqr
final double cc.rsu.GeodesicCartesianConverter.e_sqr = e * e protected
Definition at line 11 of file GeodesicCartesianConverter.java.
Referenced by cc.rsu.GeodesicCartesianConverter.cartesian2Geodesic(), and cc.rsu.GeodesicCartesianConverter.geodesic2Cartesian().
f
final double cc.rsu.GeodesicCartesianConverter.f = 1.0 / 298.257223563 protected
Definition at line 6 of file GeodesicCartesianConverter.java.
RADIANS_TO_DEGREES
final double cc.rsu.GeodesicCartesianConverter.RADIANS_TO_DEGREES = 180.0 / Math.PI static
Definition at line 14 of file GeodesicCartesianConverter.java.
Rea
final double cc.rsu.GeodesicCartesianConverter.Rea = 6378137.0 protected
Definition at line 4 of file GeodesicCartesianConverter.java.
Referenced by cc.rsu.GeodesicCartesianConverter.cartesian2Geodesic(), and cc.rsu.GeodesicCartesianConverter.geodesic2Cartesian().
Rea_sqr
final double cc.rsu.GeodesicCartesianConverter.Rea_sqr = Rea * Rea protected
Definition at line 5 of file GeodesicCartesianConverter.java.
Referenced by cc.rsu.GeodesicCartesianConverter.cartesian2Geodesic().
Reb
final double cc.rsu.GeodesicCartesianConverter.Reb = Rea * (1.0 - f) protected
Definition at line 7 of file GeodesicCartesianConverter.java.
Referenced by cc.rsu.GeodesicCartesianConverter.cartesian2Geodesic().
Reb_sqr
final double cc.rsu.GeodesicCartesianConverter.Reb_sqr = Reb * Reb protected
Definition at line 8 of file GeodesicCartesianConverter.java.
Referenced by cc.rsu.GeodesicCartesianConverter.cartesian2Geodesic().
The documentation for this class was generated from the following file:
src/cc/rsu/GeodesicCartesianConverter.java