Carma-cloud: cc.ctrl.proc.ProcHeadway Class Reference
cc.ctrl.proc.ProcHeadway Class Reference
Public Member Functions
ProcHeadway (String sLineArcDir)
void parseMetadata (Path oSource) throws Exception
ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
ProcCtrl (String sLineArcDir)
void parseMetadata (String sSource) throws Exception
abstract void parseMetadata (Path oSource) throws Exception
void process (String sLineArcsFile, double dTol) throws Exception
abstract ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Static Public Member Functions
static void renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
Static Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
static void setStaticVariables (double dStep, String sDir, String sTdFF, int nZoom)
static void updateTiles (ArrayList< int[]> oTiles, ArrayList< int[]> oCtrlTiles)
static void updateTileRange (int[] nTileIndices, int[] nTmpTiles)
static ArrayList< CtrlLineArcs > combineLaneByRoad (ArrayList< CtrlLineArcs > oLineArcs, double dTol)
static void writeIndexFile (ArrayList< TrafCtrl > oCtrls, int nX, int nY) throws IOException
static void updateIndex (String sIndexFile, TrafCtrl oCtrl, long lTimestamp) throws IOException
static void renderCtrls (String sCtrlType, ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
static boolean deleteControl (String sId) throws Exception
static boolean deleteControl (TrafCtrl oCtrl)
static ArrayList< TrafCtrl > getCurrentControls (int nCtrlType, double dMinLon, double dMinLat, double dMaxLon, double dMaxLat, boolean bLoadFullGeo)
Protected Member Functions
void proc (String sLineArcsFile, double dTol) throws Exception
abstract void proc (String sLineArcsFile, double dTol) throws Exception
Static Private Attributes
static final double[] SYMBOL = new double[]{0.6, 0.4, -0.6, 0.4, 0.0, 0.4, -0.2, 0.2, 0.0, 0.4, 0.0, -0.4}
Additional Inherited Members
Public Attributes inherited from cc.ctrl.proc.ProcCtrl
String m_sLineArcDir
Static Public Attributes inherited from cc.ctrl.proc.ProcCtrl
static final Object INDEXLOCK = new Object()
static double g_dExplodeStep
static String g_sTrafCtrlDir
static String g_sTdFileFormat
static String g_sGeolanesDir
static int g_nDefaultZoom = Integer.MIN_VALUE
static final byte CC = 0
static final byte RSM = 1
static final byte IHP2 = 2
Static Protected Member Functions inherited from cc.ctrl.proc.ProcCtrl
static boolean checkTileRange (int[] nTileIndices)
Static Protected Attributes inherited from cc.ctrl.proc.ProcCtrl
static final double WIDTHTH = 1.5
static final double LENLOWTH = 75.0
static final double STOPLINEENDOFFSET = 0.6
static final double STOPLINELATOFFSET = 0.1
static double[][] NUMBERS
static Comparator< int[]> LANETYPECOMP
static final HashMap< String, double[]> CHARS = new HashMap()
Static Package Functions inherited from cc.ctrl.proc.ProcCtrl
[static initializer]
static double getCoordAndHeadingAtLength (double[] dPoints, double dLength, boolean bReverse, double[] dPoint)
static int getStopLine (TrafCtrl oCtrl, ArrayList< double[]> oStops)
Detailed Description
Author
aaron.cherney
Definition at line 37 of file ProcHeadway.java.
Constructor & Destructor Documentation
ProcHeadway()
cc.ctrl.proc.ProcHeadway.ProcHeadway (String sLineArcDir) inline
Definition at line 42 of file ProcHeadway.java.
    {
        super(sLineArcDir);
    }
Member Function Documentation
combine()
ArrayList< CtrlLineArcs > cc.ctrl.proc.ProcHeadway.combine (ArrayList< CtrlLineArcs > oLanes, double dTol) inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 197 of file ProcHeadway.java.
    {
        return null;
    }
parseMetadata()
void cc.ctrl.proc.ProcHeadway.parseMetadata (Path oSource) throws Exception inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 187 of file ProcHeadway.java.
    {
    }
proc()
void cc.ctrl.proc.ProcHeadway.proc (String sLineArcsFile, double dTol) throws Exception inline protected
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 192 of file ProcHeadway.java.
    {
    }
renderTiledData()
static void cc.ctrl.proc.ProcHeadway.renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException inline static
Definition at line 47 of file ProcHeadway.java.
    {
        String[] sEmpty = new String[0];
        TdLayer oLayer = new TdLayer("minhdwy", sEmpty, sEmpty, TdLayer.LINESTRING);
        int[] nTags = new int[0];
        double[] dPt = new double[2];
        double[] dPoint = new double[2];
        double[][] dNumbers = new double[NUMBERS.length][];
        int[] nNumbersPts = new int[NUMBERS.length];
        for (int nIndex = 0; nIndex < NUMBERS.length; nIndex++)
        {
            double[] dTemp = new double[NUMBERS[nIndex].length + 1];
            dTemp[0] = dTemp.length;
            dNumbers[nIndex] = dTemp;
            nNumbersPts[nIndex] = NUMBERS[nIndex].length / 2;
        }
        HashMap<String, double[]> oChars = new HashMap();
        HashMap<String, Integer> oCharPts = new HashMap();
        for (Map.Entry<String, double[]> oEntry : CHARS.entrySet())
        {
            double[] dTemp = new double[oEntry.getValue().length + 1];
            dTemp[0] = dTemp.length;
            oChars.put(oEntry.getKey(), dTemp);
            oCharPts.put(oEntry.getKey(), oEntry.getValue().length / 2);
        }
        double[] dSymbol1 = new double[SYMBOL.length + 1];
        double[] dSymbol2 = new double[SYMBOL.length + 1];
        dSymbol1[0] = dSymbol1.length;
        dSymbol2[0] = dSymbol2.length;
        int nSymbolPts = SYMBOL.length / 2;
        Units oUnits = Units.getInstance();
        String[] sUnits = TrafCtrlEnums.UNITS[TrafCtrlEnums.getCtrl("minhdwy")];
        for (int[] nTile : nTiles)
        {
            int nX = nTile[0];
            int nY = nTile[1];
            Files.createDirectories(Paths.get(String.format(g_sTdFileFormat, nX, 0, 0, 0)).getParent(), FileUtil.DIRPERS);
            writeIndexFile(oCtrls, nX, nY);
            oLayer.clear();
            double[] dClipBounds = TileUtil.getClippingBounds(g_nDefaultZoom, nX, nY);
            DecimalFormat oDf = new DecimalFormat("#.#");
            for (TrafCtrl oCtrl : oCtrls)
            {
                CtrlGeo oFullGeo = oCtrl.m_oFullGeo;
                if (Collections.binarySearch(oFullGeo.m_oTiles, nTile, Mercator.TILECOMP) < 0 || oFullGeo.m_dLength < LENLOWTH || oFullGeo.m_dAverageWidth < WIDTHTH)
                    continue;
                double dHdg = getCoordAndHeadingAtLength(oFullGeo.m_dC, oFullGeo.m_dLength / 2.0, false, dPt);
                if (Double.isNaN(dHdg))
                    continue;
                double dPTAngle = dHdg + Mercator.PI_OVER_TWO;
                double dXc = dPt[0];
                double dYc = dPt[1];
                dPt[0] += Math.cos(dHdg) * 0.8;
                dPt[1] += Math.sin(dHdg) * 0.8;
                AffineTransform oAt = new AffineTransform();
                oAt.translate(dPt[0], dPt[1]);
                oAt.rotate(dHdg - Mercator.PI_OVER_TWO, 0, 0);
                oAt.transform(SYMBOL, 0, dSymbol1, 1, nSymbolPts);
                dPt[0] = dXc;
                dPt[1] = dYc;
                dPt[0] -= Math.cos(dHdg) * 0.8;
                dPt[1] -= Math.sin(dHdg) * 0.8;
                oAt = new AffineTransform();
                oAt.translate(dPt[0], dPt[1]);
                oAt.rotate(dHdg + Mercator.PI_OVER_TWO, 0, 0);
                oAt.transform(SYMBOL, 0, dSymbol2, 1, nSymbolPts);
                double[] dBounds = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE};
                Iterator<double[]> oIt = Arrays.iterator(dSymbol1, dPoint, 1, 2);
                while (oIt.hasNext())
                {
                    oIt.next();
                    Geo.updateBounds(dPoint[0], dPoint[1], dBounds);
                }
                oIt = Arrays.iterator(dSymbol2, dPoint, 1, 2);
                while (oIt.hasNext())
                {
                    oIt.next();
                    Geo.updateBounds(dPoint[0], dPoint[1], dBounds);
                }
                if (Geo.boundingBoxesIntersect(dClipBounds[0], dClipBounds[1], dClipBounds[2], dClipBounds[3], dBounds[0], dBounds[1], dBounds[2], dBounds[3]))
                {
                    oLayer.add(new TdFeature(dSymbol1, nTags, oCtrl));
                    oLayer.add(new TdFeature(dSymbol2, nTags, oCtrl));
                    int nVal = (int)Math.round(oUnits.convert(sUnits[0], sUnits[1], MathUtil.bytesToInt(oCtrl.m_yControlValue)));
                    String sVal = oDf.format(nVal) + "ft";
                    int nLimit = sVal.length();
                    double dStep = -0.3;
                    double dOffset = -0.45 + (nLimit * 0.3);
                    for (int nIndex = 0; nIndex < sVal.length(); nIndex++)
                    {
                        char cChar = sVal.charAt(nIndex);
                        double dMultiplier = dOffset + (dStep * nIndex);
                        dPt[0] = dXc;
                        dPt[1] = dYc;
                        dPt[0] += Math.cos(dPTAngle) * dMultiplier;
                        dPt[1] += Math.sin(dPTAngle) * dMultiplier;
                        oAt = new AffineTransform();
                        oAt.translate(dPt[0], dPt[1]);
                        oAt.rotate(dHdg - Mercator.PI_OVER_TWO, 0, 0);
                        if (Character.isDigit(cChar))
{
                            oAt.scale(0.45, 0.45);
                            int nNumber = Character.getNumericValue(cChar);
                            oAt.transform(NUMBERS[nNumber], 0, dNumbers[nNumber], 1, nNumbersPts[nNumber]);
                            oLayer.add(new TdFeature(dNumbers[nNumber], nTags, oCtrl));
                        }
                        else
{
                            oAt.scale(0.65, 0.65);
                            String sChar = Character.toString(cChar);
                            oAt.transform(CHARS.get(sChar), 0, oChars.get(sChar), 1, oCharPts.get(sChar));
                            oLayer.add(new TdFeature(oChars.get(sChar), nTags, oCtrl));
                        }
                    }
                }
            }
            if (!oLayer.isEmpty())
            {
                try (DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(String.format(g_sTdFileFormat, nX, g_nDefaultZoom, nX, nY)), FileUtil.APPENDTO, FileUtil.FILEPERS))))
                {
                    oLayer.write(oOut);
                }
            }
        }
    }
References cc.util.FileUtil.APPENDTO, cc.util.Geo.boundingBoxesIntersect(), cc.util.MathUtil.bytesToInt(), cc.ctrl.proc.ProcCtrl.CHARS, cc.util.Units.convert(), cc.util.FileUtil.DIRPERS, cc.util.FileUtil.FILEPERS, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTdFileFormat, cc.util.TileUtil.getClippingBounds(), cc.ctrl.proc.ProcCtrl.getCoordAndHeadingAtLength(), cc.ctrl.TrafCtrlEnums.getCtrl(), cc.util.Units.getInstance(), cc.util.Arrays.iterator(), cc.ctrl.proc.ProcCtrl.LENLOWTH, cc.ctrl.proc.TdLayer.LINESTRING, cc.ctrl.CtrlGeo.m_dAverageWidth, cc.ctrl.CtrlGeo.m_dC, cc.ctrl.CtrlGeo.m_dLength, cc.ctrl.CtrlGeo.m_oTiles, cc.util.FileUtil.newOutputStream(), cc.ctrl.proc.ProcCtrl.NUMBERS, cc.geosrv.Mercator.PI_OVER_TWO, cc.ctrl.proc.ProcHeadway.SYMBOL, cc.geosrv.Mercator.TILECOMP, cc.ctrl.TrafCtrlEnums.UNITS, cc.util.Geo.updateBounds(), cc.ctrl.proc.ProcCtrl.WIDTHTH, cc.ctrl.proc.TdLayer.write(), and cc.ctrl.proc.ProcCtrl.writeIndexFile().
Referenced by cc.ctrl.proc.ProcCtrl.renderCtrls().
Member Data Documentation
SYMBOL
final double [] cc.ctrl.proc.ProcHeadway.SYMBOL = new double[]{0.6, 0.4, -0.6, 0.4, 0.0, 0.4, -0.2, 0.2, 0.0, 0.4, 0.0, -0.4} static private
Definition at line 41 of file ProcHeadway.java.
Referenced by cc.ctrl.proc.ProcHeadway.renderTiledData().
The documentation for this class was generated from the following file:
src/cc/ctrl/proc/ProcHeadway.java