Carma-cloud: cc.geosrv.xodr.pvmt.XodrPvmtParser Class Reference
cc.geosrv.xodr.pvmt.XodrPvmtParser Class Reference
Public Member Functions
XodrPvmtParser ()
void startCDATA ()
void endCDATA () throws SAXException
void characters (char[] cBuf, int nPos, int nLen)
void startElement (String sUri, String sLocalName, String sQname, Attributes iAtt) throws SAXException
void endElement (String sUri, String sLocalName, String sQname) throws SAXException
void parseXodrToCLA (Path oXodrFile, String sDir) throws Exception
Protected Attributes
boolean m_bCdata
double m_dS
double m_dX
double m_dY
double m_dH
double m_dL
Road m_oRoad
LaneSection m_oLaneSection
Lane m_oLane
Proj m_oProj
final double[] m_dPoint = new double[2]
final StringBuilder m_sBuf = new StringBuilder()
final ArrayList< CtrlLineArcs > m_oCtrlLineArcs = new ArrayList()
String m_sCtrlFile
String m_sBaseDir
double m_dMaxStep = 0.06
double m_dLineTol = 0.1
boolean m_bSignal
double[] m_dBB = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE}
SimpleDateFormat m_oSDF = new SimpleDateFormat("HH:mm:ss:SSS")
boolean m_bLane = false
int m_nShort = 0
int m_nRoads = 0
boolean m_bSkip = false
Private Member Functions
void writeClas (String sType)
Detailed Description
Author
Federal Highway Administration
Definition at line 36 of file XodrPvmtParser.java.
Constructor & Destructor Documentation
XodrPvmtParser()
cc.geosrv.xodr.pvmt.XodrPvmtParser.XodrPvmtParser () inline
Definition at line 64 of file XodrPvmtParser.java.
    {
        super();
    }
Member Function Documentation
characters()
void cc.geosrv.xodr.pvmt.XodrPvmtParser.characters (char[] cBuf, int nPos, int nLen) inline
Definition at line 97 of file XodrPvmtParser.java.
    {
        if (m_bCdata)
            m_sBuf.append(cBuf, nPos, nLen);
    }
References cc.geosrv.xodr.pvmt.XodrPvmtParser.m_bCdata, and cc.geosrv.xodr.pvmt.XodrPvmtParser.m_sBuf.
endCDATA()
void cc.geosrv.xodr.pvmt.XodrPvmtParser.endCDATA () throws SAXException inline
Definition at line 79 of file XodrPvmtParser.java.
    {
        try
        {
            Text.removeWhitespace(m_sBuf);
            m_oProj = new Proj(m_sBuf.toString(), "epsg:3785"); // projection object used to convert xodr geometry to spherical mercator
//          m_oProj = new Proj(m_sBuf.toString(), "epsg:4326"); // projection object used to convert xodr geometry to lon/lats
        }
        catch (Exception oEx)
        {
            throw new SAXException(oEx);
        }
        m_bCdata = false;
    }
References cc.geosrv.xodr.pvmt.XodrPvmtParser.m_bCdata, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oProj, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_sBuf, and cc.util.Text.removeWhitespace().
endElement()
void cc.geosrv.xodr.pvmt.XodrPvmtParser.endElement (String sUri, String sLocalName, String sQname) throws SAXException inline
Definition at line 197 of file XodrPvmtParser.java.
    {
        switch (sQname)
        {
            case "road":
            {
                if (m_bSkip)
                    break;
                if (m_oRoad.m_oLaneOffsets.isEmpty())
                    m_oRoad.m_oLaneOffsets.add(new LaneOffset(0.0, 0.0, 0.0, 0.0, 0.0));
                Collections.sort(m_oRoad.m_oLaneOffsets);
                Collections.sort(m_oRoad.m_oGeometries);
                if (m_oRoad.m_oGeometries.isEmpty())
                {
//                  System.out.println(String.format("Road %d has no geometries.", m_oRoad.m_nId));
                    break;
                }
                m_oRoad.adjustSections(m_dMaxStep);
                m_oRoad.createPoints(m_dMaxStep, m_oProj);
                m_oRoad.setLaneIds(m_dMaxStep);
                for (LaneSection oS : m_oRoad)
                    oS.setInnerPaths();
                m_oRoad.getPavementCtrlLineArcs(m_oCtrlLineArcs, m_dLineTol);
                m_oRoad.getShoulderCtrlLineArcs(m_oCtrlLineArcs, m_dLineTol);
                writeClas("pavement");
                break;
            }
            case "laneSection":
            {
                m_oLaneSection.sortLanes();
                m_oRoad.add(m_oLaneSection);
                break;
            }
            case "lane":
            {
                Collections.sort(m_oLane);
                if (m_oLane.m_nLaneIndex == 0)
                    m_oLaneSection.m_oCenter = m_oLane;
                m_oLaneSection.add(m_oLane);
                m_bLane = false;
                break;
            }
            default:
                break;
        }
    }
References cc.geosrv.xodr.pvmt.LaneSection.add(), cc.geosrv.xodr.pvmt.Road.adjustSections(), cc.geosrv.xodr.pvmt.Road.createPoints(), cc.geosrv.xodr.pvmt.Road.getPavementCtrlLineArcs(), cc.geosrv.xodr.pvmt.Road.getShoulderCtrlLineArcs(), cc.geosrv.xodr.pvmt.XodrPvmtParser.m_bLane, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_bSkip, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dLineTol, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dMaxStep, cc.geosrv.xodr.pvmt.Lane.m_nLaneIndex, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oCtrlLineArcs, cc.geosrv.xodr.pvmt.Road.m_oGeometries, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oLane, cc.geosrv.xodr.pvmt.Road.m_oLaneOffsets, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oLaneSection, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oProj, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oRoad, cc.geosrv.xodr.pvmt.Road.setLaneIds(), cc.geosrv.xodr.pvmt.LaneSection.sortLanes(), and cc.geosrv.xodr.pvmt.XodrPvmtParser.writeClas().
parseXodrToCLA()
void cc.geosrv.xodr.pvmt.XodrPvmtParser.parseXodrToCLA (Path oXodrFile, String sDir) throws Exception inline
Definition at line 260 of file XodrPvmtParser.java.
    {
        if (!sDir.endsWith("/"))
            sDir += '/';
        m_sBaseDir = sDir;
        if (!Files.exists(oXodrFile))
        {
            String sPvmtFile = oXodrFile.toString();
            String sXodrFile = sPvmtFile.substring(0, sPvmtFile.lastIndexOf("."));
            oXodrFile = Paths.get(sXodrFile);
            m_sCtrlFile = sXodrFile.substring(sXodrFile.lastIndexOf("/") + 1).replace(".xodr", ".bin.pvmt");
        }
        else
        {
            m_sCtrlFile = oXodrFile.getFileName().toString().replace(".xodr.pvmt", ".bin.pvmt");
        }
        XMLReader iXmlReader = SAXParserFactory.newInstance().
        newSAXParser().getXMLReader();
        iXmlReader.setContentHandler(this);
        iXmlReader.setProperty("http://xml.org/sax/properties/lexical-handler", this);
        iXmlReader.parse(new InputSource(new BufferedInputStream(Files.newInputStream(oXodrFile))));
    }
References cc.geosrv.xodr.pvmt.XodrPvmtParser.m_sBaseDir, and cc.geosrv.xodr.pvmt.XodrPvmtParser.m_sCtrlFile.
Referenced by cc.ctrl.proc.ProcPavement.parseMetadata().
startCDATA()
void cc.geosrv.xodr.pvmt.XodrPvmtParser.startCDATA () inline
Definition at line 71 of file XodrPvmtParser.java.
    {
        m_sBuf.setLength(0);
        m_bCdata = true;
    }
References cc.geosrv.xodr.pvmt.XodrPvmtParser.m_bCdata, and cc.geosrv.xodr.pvmt.XodrPvmtParser.m_sBuf.
startElement()
void cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement (String sUri, String sLocalName, String sQname, Attributes iAtt) throws SAXException inline
Definition at line 105 of file XodrPvmtParser.java.
    {
        try
        {
            switch (sQname)
            {
                case "road":
                {
                    m_bSkip = false;
                    m_oCtrlLineArcs.clear();
                    m_oRoad = new Road(Integer.parseInt(iAtt.getValue("id")), Double.parseDouble(iAtt.getValue("length"))); // new road geometry
                    Arrays.add(m_oRoad.m_dTrack, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                    Arrays.add(m_oRoad.m_dLaneZero, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                    break;
                }
                case "geometry":
                {
                    m_dS = XodrUtil.parseDouble(iAtt.getValue("s"));
                    m_dX = XodrUtil.parseDouble(iAtt.getValue("x"));
                    m_dY = XodrUtil.parseDouble(iAtt.getValue("y"));
                    m_dH = XodrUtil.parseDouble(iAtt.getValue("hdg"));
                    m_dL = XodrUtil.parseDouble(iAtt.getValue("length"));
                    break;
                }
                case "spiral":
                case "line":
                {
                    if (Double.isFinite(m_dS) && Double.isFinite(m_dX) && Double.isFinite(m_dY) && Double.isFinite(m_dH) && Double.isFinite(m_dL))
                        m_oRoad.m_oGeometries.add(new Line(m_dS, m_dX, m_dY, m_dH, m_dL));
                    break;
                }
                case "arc":
                {
                    double dCurvature = XodrUtil.parseDouble(iAtt.getValue("curvature"));
                    if (Double.isFinite(m_dS) && Double.isFinite(m_dX) && Double.isFinite(m_dY) && Double.isFinite(m_dH) && Double.isFinite(m_dL))
                        m_oRoad.m_oGeometries.add(new Arc(m_dS, m_dX, m_dY, m_dH, m_dL, dCurvature));
                    break;
                }
                case "laneOffset":
                {
                    double dS = XodrUtil.parseDouble(iAtt.getValue("s"));
                    double dA = XodrUtil.parseDouble(iAtt.getValue("a"));
                    double dB = XodrUtil.parseDouble(iAtt.getValue("b"));
                    double dC = XodrUtil.parseDouble(iAtt.getValue("c"));
                    double dD = XodrUtil.parseDouble(iAtt.getValue("d"));
                    if (Double.isFinite(dS) && Double.isFinite(dA) && Double.isFinite(dB) && Double.isFinite(dC) && Double.isFinite(dD))
                        m_oRoad.m_oLaneOffsets.add(new LaneOffset(dS, dA, dB, dC, dD));
                    break;
                }
                case "laneSection":
                {
                    double dS = XodrUtil.parseDouble(iAtt.getValue("s"));
                    if (Double.isFinite(dS))
                        m_oLaneSection = new LaneSection(dS, m_oRoad.size());
                    break;
                }
                case "lane":
                {
                    m_oLane = new Lane(Integer.parseInt(iAtt.getValue("id")), iAtt.getValue("type"), m_oRoad.m_nId, m_oRoad.size(), m_oRoad.m_nMaxSpeed);
                    m_bLane = true;
                    break;
                }
                case "width":
                {
                    double dS = XodrUtil.parseDouble(iAtt.getValue("sOffset"));
                    double dA = XodrUtil.parseDouble(iAtt.getValue("a"));
                    double dB = XodrUtil.parseDouble(iAtt.getValue("b"));
                    double dC = XodrUtil.parseDouble(iAtt.getValue("c"));
                    double dD = XodrUtil.parseDouble(iAtt.getValue("d"));
                    if (Double.isFinite(dS) && Double.isFinite(dA) && Double.isFinite(dB) && Double.isFinite(dC) && Double.isFinite(dD))
                        m_oLane.add(new LaneWidth(dS, dA, dB, dC, dD));
                    break;
                }
                default:
                    break;
            }
        }
        catch (Exception oEx)
        {
            System.out.println("Error parsing Road " + m_oRoad.m_nId);
            oEx.printStackTrace();
            m_bSkip = true;
        }
    }
References cc.util.Arrays.add(), cc.geosrv.xodr.pvmt.XodrPvmtParser.m_bLane, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_bSkip, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dH, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dL, cc.geosrv.xodr.pvmt.Road.m_dLaneZero, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dS, cc.geosrv.xodr.pvmt.Road.m_dTrack, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dX, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dY, cc.geosrv.xodr.pvmt.Road.m_nId, cc.geosrv.xodr.pvmt.Road.m_nMaxSpeed, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oCtrlLineArcs, cc.geosrv.xodr.pvmt.Road.m_oGeometries, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oLane, cc.geosrv.xodr.pvmt.Road.m_oLaneOffsets, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oLaneSection, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oRoad, and cc.geosrv.xodr.XodrUtil.parseDouble().
writeClas()
void cc.geosrv.xodr.pvmt.XodrPvmtParser.writeClas (String sType) inline private
Definition at line 246 of file XodrPvmtParser.java.
    {
        try (DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(m_sBaseDir + sType + "/" + m_sCtrlFile), FileUtil.APPENDTO, FileUtil.FILEPERS))))
        {
            for (CtrlLineArcs oCLA : m_oCtrlLineArcs)
                oCLA.write(oOut);
        }
        catch (IOException oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.util.FileUtil.APPENDTO, cc.util.FileUtil.FILEPERS, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oCtrlLineArcs, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_sBaseDir, cc.geosrv.xodr.pvmt.XodrPvmtParser.m_sCtrlFile, and cc.util.FileUtil.newOutputStream().
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.endElement().
Member Data Documentation
m_bCdata
boolean cc.geosrv.xodr.pvmt.XodrPvmtParser.m_bCdata protected
Definition at line 38 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.characters(), cc.geosrv.xodr.pvmt.XodrPvmtParser.endCDATA(), and cc.geosrv.xodr.pvmt.XodrPvmtParser.startCDATA().
m_bLane
boolean cc.geosrv.xodr.pvmt.XodrPvmtParser.m_bLane = false protected
Definition at line 58 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.endElement(), and cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement().
m_bSignal
boolean cc.geosrv.xodr.pvmt.XodrPvmtParser.m_bSignal protected
Definition at line 55 of file XodrPvmtParser.java.
m_bSkip
boolean cc.geosrv.xodr.pvmt.XodrPvmtParser.m_bSkip = false protected
Definition at line 61 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.endElement(), and cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement().
m_dBB
double [] cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dBB = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE} protected
Definition at line 56 of file XodrPvmtParser.java.
m_dH
double cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dH protected
Definition at line 42 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement().
m_dL
double cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dL protected
Definition at line 43 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement().
m_dLineTol
double cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dLineTol = 0.1 protected
Definition at line 54 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.endElement().
m_dMaxStep
double cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dMaxStep = 0.06 protected
Definition at line 53 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.endElement().
m_dPoint
final double [] cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dPoint = new double[2] protected
Definition at line 48 of file XodrPvmtParser.java.
m_dS
double cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dS protected
Definition at line 39 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement().
m_dX
double cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dX protected
Definition at line 40 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement().
m_dY
double cc.geosrv.xodr.pvmt.XodrPvmtParser.m_dY protected
Definition at line 41 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement().
m_nRoads
int cc.geosrv.xodr.pvmt.XodrPvmtParser.m_nRoads = 0 protected
Definition at line 60 of file XodrPvmtParser.java.
m_nShort
int cc.geosrv.xodr.pvmt.XodrPvmtParser.m_nShort = 0 protected
Definition at line 59 of file XodrPvmtParser.java.
m_oCtrlLineArcs
final ArrayList<CtrlLineArcs> cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oCtrlLineArcs = new ArrayList() protected
Definition at line 50 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.endElement(), cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement(), and cc.geosrv.xodr.pvmt.XodrPvmtParser.writeClas().
m_oLane
Lane cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oLane protected
Definition at line 46 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.endElement(), and cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement().
m_oLaneSection
LaneSection cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oLaneSection protected
Definition at line 45 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.endElement(), and cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement().
m_oProj
Proj cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oProj protected
Definition at line 47 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.endCDATA(), and cc.geosrv.xodr.pvmt.XodrPvmtParser.endElement().
m_oRoad
Road cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oRoad protected
Definition at line 44 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.endElement(), and cc.geosrv.xodr.pvmt.XodrPvmtParser.startElement().
m_oSDF
SimpleDateFormat cc.geosrv.xodr.pvmt.XodrPvmtParser.m_oSDF = new SimpleDateFormat("HH:mm:ss:SSS") protected
Definition at line 57 of file XodrPvmtParser.java.
m_sBaseDir
String cc.geosrv.xodr.pvmt.XodrPvmtParser.m_sBaseDir protected
Definition at line 52 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.parseXodrToCLA(), and cc.geosrv.xodr.pvmt.XodrPvmtParser.writeClas().
m_sBuf
final StringBuilder cc.geosrv.xodr.pvmt.XodrPvmtParser.m_sBuf = new StringBuilder() protected
Definition at line 49 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.characters(), cc.geosrv.xodr.pvmt.XodrPvmtParser.endCDATA(), and cc.geosrv.xodr.pvmt.XodrPvmtParser.startCDATA().
m_sCtrlFile
String cc.geosrv.xodr.pvmt.XodrPvmtParser.m_sCtrlFile protected
Definition at line 51 of file XodrPvmtParser.java.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.parseXodrToCLA(), and cc.geosrv.xodr.pvmt.XodrPvmtParser.writeClas().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/pvmt/XodrPvmtParser.java