Carma-cloud: cc.geosrv.xodr.rdmk.XodrRoadMarkParser Class Reference
cc.geosrv.xodr.rdmk.XodrRoadMarkParser Class Reference
Public Member Functions
XodrRoadMarkParser ()
void startCDATA ()
void endCDATA () throws SAXException
void characters (char[] cBuf, int nPos, int nLen)
void startElement (String sUri, String sLocalName, String sQname, Attributes iAtt) throws SAXException
void endElement (String sUri, String sLocalName, String sQname) throws SAXException
void parseXodrToCLA (Path oXodrFile, String sDir) throws Exception
Protected Attributes
boolean m_bCdata
double m_dS
double m_dX
double m_dY
double m_dH
double m_dL
Road m_oRoad
LaneSection m_oLaneSection
Lane m_oLane
Proj m_oProj
final double[] m_dPoint = new double[2]
final StringBuilder m_sBuf = new StringBuilder()
final ArrayList< CtrlLineArcs > m_oCtrlLineArcs = new ArrayList()
String m_sCtrlFile
String m_sBaseDir
double m_dMaxStep = 0.06
double m_dLineTol = 0.1
boolean m_bSignal
boolean m_bSkip = false
Package Attributes
ArrayList< int[]> m_oRdMkInfo = new ArrayList()
Private Member Functions
void writeClas (String sType)
Detailed Description
Author
aaron.cherney
Definition at line 35 of file XodrRoadMarkParser.java.
Constructor & Destructor Documentation
XodrRoadMarkParser()
cc.geosrv.xodr.rdmk.XodrRoadMarkParser.XodrRoadMarkParser () inline
Definition at line 59 of file XodrRoadMarkParser.java.
    {
        super();
    }
Member Function Documentation
characters()
void cc.geosrv.xodr.rdmk.XodrRoadMarkParser.characters (char[] cBuf, int nPos, int nLen) inline
Definition at line 92 of file XodrRoadMarkParser.java.
    {
        if (m_bCdata)
            m_sBuf.append(cBuf, nPos, nLen);
    }
References cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_bCdata, and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_sBuf.
endCDATA()
void cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endCDATA () throws SAXException inline
Definition at line 74 of file XodrRoadMarkParser.java.
    {
        try
        {
            Text.removeWhitespace(m_sBuf);
            m_oProj = new Proj(m_sBuf.toString(), "epsg:3785"); // projection object used to convert xodr geometry to spherical mercator
//          m_oProj = new Proj(m_sBuf.toString(), "epsg:4326"); // projection object used to convert xodr geometry to lon/lats
        }
        catch (Exception oEx)
        {
            throw new SAXException(oEx);
        }
        m_bCdata = false;
    }
References cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_bCdata, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oProj, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_sBuf, and cc.util.Text.removeWhitespace().
endElement()
void cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement (String sUri, String sLocalName, String sQname) throws SAXException inline
Definition at line 198 of file XodrRoadMarkParser.java.
    {
        switch (sQname)
        {
            case "road":
            {
                if (m_bSkip)
                    break;
                if (m_oRoad.m_oLaneOffsets.isEmpty())
                    m_oRoad.m_oLaneOffsets.add(new LaneOffset(0.0, 0.0, 0.0, 0.0, 0.0));
                Collections.sort(m_oRoad.m_oLaneOffsets);
                Collections.sort(m_oRoad.m_oGeometries);
                if (m_oRoad.m_oGeometries.isEmpty())
                {
//                  System.out.println(String.format("Road %d has no geometries.", m_oRoad.m_nId));
                    break;
                }
                m_oRoad.adjustSections(m_dMaxStep);
//              m_oRoad.setInnerRoadMarks();
                m_oRoad.createPoints(m_dMaxStep, m_oProj);
                int nLanes = 0;
                if (m_oRoad.m_dLength < m_dMaxStep)
                {
                    System.out.println(String.format("%d\t\t%f", m_oRoad.m_nId, m_oRoad.m_dLength));
                    break;
                }
                for (LaneSection oS : m_oRoad)
                {
                    int nTemp = oS.m_oLeft.size() + oS.m_oRight.size();
                    if (nTemp > nLanes)
                        nLanes = nTemp;
                }
                if (nLanes < 3)
                {
//                  System.out.println(String.format("%d\t\t%d", m_oRoad.m_nId, nLanes));
                    break;
                }
                m_oRoad.setLaneIds(m_dMaxStep);
                m_oRoad.getRdMkCtrlLineArcs(m_oCtrlLineArcs, m_dLineTol, m_oRdMkInfo);
                writeClas("rdmks");
                break;
            }
            case "laneSection":
            {
                m_oLaneSection.sortLanes();
                m_oRoad.add(m_oLaneSection);
                break;
            }
            case "lane":
            {
                Collections.sort(m_oLane);
                if (m_oLane.m_nLaneIndex == 0)
                    m_oLaneSection.m_oCenter = m_oLane;
                m_oLaneSection.add(m_oLane);
                break;
            }
            default:
                break;
        }
    }
References cc.geosrv.xodr.rdmk.LaneSection.add(), cc.geosrv.xodr.rdmk.Road.adjustSections(), cc.geosrv.xodr.rdmk.Road.createPoints(), cc.geosrv.xodr.rdmk.Road.getRdMkCtrlLineArcs(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_bSkip, cc.geosrv.xodr.rdmk.Road.m_dLength, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dLineTol, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dMaxStep, cc.geosrv.xodr.rdmk.Road.m_nId, cc.geosrv.xodr.rdmk.Lane.m_nLaneIndex, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oCtrlLineArcs, cc.geosrv.xodr.rdmk.Road.m_oGeometries, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oLane, cc.geosrv.xodr.rdmk.Road.m_oLaneOffsets, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oLaneSection, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oProj, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oRdMkInfo, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oRoad, cc.geosrv.xodr.rdmk.Road.setLaneIds(), cc.geosrv.xodr.rdmk.LaneSection.sortLanes(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.writeClas().
parseXodrToCLA()
void cc.geosrv.xodr.rdmk.XodrRoadMarkParser.parseXodrToCLA (Path oXodrFile, String sDir) throws Exception inline
Definition at line 290 of file XodrRoadMarkParser.java.
    {
        if (!sDir.endsWith("/"))
            sDir += '/';
        m_sBaseDir = sDir;
        Path oDir = Paths.get(sDir);
        Files.createDirectories(oDir, FileUtil.DIRPERS);
        Files.createDirectories(Paths.get(m_sBaseDir + "rdmks"), FileUtil.DIRPERS);
        m_sCtrlFile = oXodrFile.getFileName().toString().replace(".xodr", ".bin");
        Path oRdMkFile = Paths.get(m_sBaseDir + "rdmks/" + m_sCtrlFile);
        if (Files.exists(oRdMkFile) && Files.isRegularFile(oRdMkFile))
           Files.delete(oRdMkFile);
        XMLReader iXmlReader = SAXParserFactory.newInstance().
        newSAXParser().getXMLReader();
        iXmlReader.setContentHandler(this);
        iXmlReader.setProperty("http://xml.org/sax/properties/lexical-handler", this);
        iXmlReader.parse(new InputSource(new BufferedInputStream(Files.newInputStream(oXodrFile))));
    }
References cc.util.FileUtil.DIRPERS, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_sBaseDir, and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_sCtrlFile.
Referenced by cc.ws.CtrlTiles.init(), and cc.ws.ValidateXodrTiles.init().
startCDATA()
void cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startCDATA () inline
Definition at line 66 of file XodrRoadMarkParser.java.
    {
        m_sBuf.setLength(0);
        m_bCdata = true;
    }
References cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_bCdata, and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_sBuf.
startElement()
void cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement (String sUri, String sLocalName, String sQname, Attributes iAtt) throws SAXException inline
Definition at line 100 of file XodrRoadMarkParser.java.
    {
        try
        {
            switch (sQname)
            {
                case "road":
                {
                    m_bSkip = false;
                    m_oCtrlLineArcs.clear();
                    m_oRdMkInfo.clear();
                    m_oRoad = new Road(Integer.parseInt(iAtt.getValue("id")), Double.parseDouble(iAtt.getValue("length"))); // new road geometry
                    Arrays.add(m_oRoad.m_dTrack, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                    Arrays.add(m_oRoad.m_dLaneZero, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                    break;
                }
                case "geometry":
                {
                    m_dS = XodrUtil.parseDouble(iAtt.getValue("s"));
                    m_dX = XodrUtil.parseDouble(iAtt.getValue("x"));
                    m_dY = XodrUtil.parseDouble(iAtt.getValue("y"));
                    m_dH = XodrUtil.parseDouble(iAtt.getValue("hdg"));
                    m_dL = XodrUtil.parseDouble(iAtt.getValue("length"));
                    break;
                }
                case "spiral":
                case "line":
                {
                    if (Double.isFinite(m_dS) && Double.isFinite(m_dX) && Double.isFinite(m_dY) && Double.isFinite(m_dH) && Double.isFinite(m_dL))
                        m_oRoad.m_oGeometries.add(new Line(m_dS, m_dX, m_dY, m_dH, m_dL));
                    break;
                }
                case "arc":
                {
                    double dCurvature = XodrUtil.parseDouble(iAtt.getValue("curvature"));
                    if (Double.isFinite(m_dS) && Double.isFinite(m_dX) && Double.isFinite(m_dY) && Double.isFinite(m_dH) && Double.isFinite(m_dL))
                        m_oRoad.m_oGeometries.add(new Arc(m_dS, m_dX, m_dY, m_dH, m_dL, dCurvature));
                    break;
                }
                case "laneOffset":
                {
                    double dS = XodrUtil.parseDouble(iAtt.getValue("s"));
                    double dA = XodrUtil.parseDouble(iAtt.getValue("a"));
                    double dB = XodrUtil.parseDouble(iAtt.getValue("b"));
                    double dC = XodrUtil.parseDouble(iAtt.getValue("c"));
                    double dD = XodrUtil.parseDouble(iAtt.getValue("d"));
                    if (Double.isFinite(dS) && Double.isFinite(dA) && Double.isFinite(dB) && Double.isFinite(dC) && Double.isFinite(dD))
                        m_oRoad.m_oLaneOffsets.add(new LaneOffset(dS, dA, dB, dC, dD));
                    break;
                }
                case "laneSection":
                {
                    double dS = XodrUtil.parseDouble(iAtt.getValue("s"));
                    if (Double.isFinite(dS))
                        m_oLaneSection = new LaneSection(dS, m_oRoad.size());
                    break;
                }
                case "lane":
                {
                    m_oLane = new Lane(Integer.parseInt(iAtt.getValue("id")), iAtt.getValue("type"), m_oRoad.m_nId, m_oRoad.size());
                    break;
                }
                case "width":
                {
                    double dS = XodrUtil.parseDouble(iAtt.getValue("sOffset"));
                    double dA = XodrUtil.parseDouble(iAtt.getValue("a"));
                    double dB = XodrUtil.parseDouble(iAtt.getValue("b"));
                    double dC = XodrUtil.parseDouble(iAtt.getValue("c"));
                    double dD = XodrUtil.parseDouble(iAtt.getValue("d"));
                    if (Double.isFinite(dS) && Double.isFinite(dA) && Double.isFinite(dB) && Double.isFinite(dC) && Double.isFinite(dD))
                        m_oLane.add(new LaneWidth(dS, dA, dB, dC, dD));
                    break;
                }
                case "roadMark":
                {
                    double dOffset = XodrUtil.parseDouble(iAtt.getValue("sOffset"));
                    if (Double.isFinite(dOffset))
                        m_oLane.m_oOuterRoadMarks.add(new RoadMark(iAtt.getValue("type"), iAtt.getValue("color"), dOffset));
                }
                default:
                    break;
            }
        }
        catch (Exception oEx)
        {
            System.out.println("Error parsing Road " + m_oRoad.m_nId);
            oEx.printStackTrace();
            m_bSkip = true;
        }
    }
References cc.util.Arrays.add(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_bSkip, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dH, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dL, cc.geosrv.xodr.rdmk.Road.m_dLaneZero, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dS, cc.geosrv.xodr.rdmk.Road.m_dTrack, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dX, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dY, cc.geosrv.xodr.rdmk.Road.m_nId, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oCtrlLineArcs, cc.geosrv.xodr.rdmk.Road.m_oGeometries, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oLane, cc.geosrv.xodr.rdmk.Road.m_oLaneOffsets, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oLaneSection, cc.geosrv.xodr.rdmk.Lane.m_oOuterRoadMarks, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oRdMkInfo, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oRoad, and cc.geosrv.xodr.XodrUtil.parseDouble().
writeClas()
void cc.geosrv.xodr.rdmk.XodrRoadMarkParser.writeClas (String sType) inline private
Definition at line 261 of file XodrRoadMarkParser.java.
    {
        try
        (
           DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(m_sBaseDir + sType + "/" + m_sCtrlFile), FileUtil.APPENDTO, FileUtil.FILEPERS)));
           DataOutputStream oMeta = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(m_sBaseDir + sType + "/" + m_sCtrlFile + ".meta"), FileUtil.APPENDTO, FileUtil.FILEPERS)))
        )
        {
            for (CtrlLineArcs oCLA : m_oCtrlLineArcs)
            {
                oCLA.write(oOut);
            }
            for (int[] nTags : m_oRdMkInfo)
            {
                Iterator<int[]> oIt = Arrays.iterator(nTags, new int[1], 1, 1);
                oMeta.writeInt(Arrays.size(nTags));
                while (oIt.hasNext())
                {
                    oMeta.writeInt(oIt.next()[0]);
                }
            }
        }
        catch (IOException oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.util.FileUtil.APPENDTO, cc.util.FileUtil.FILEPERS, cc.util.Arrays.iterator(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oCtrlLineArcs, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oRdMkInfo, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_sBaseDir, cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_sCtrlFile, cc.util.FileUtil.newOutputStream(), and cc.util.Arrays.size().
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement().
Member Data Documentation
m_bCdata
boolean cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_bCdata protected
Definition at line 37 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.characters(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endCDATA(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startCDATA().
m_bSignal
boolean cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_bSignal protected
Definition at line 54 of file XodrRoadMarkParser.java.
m_bSkip
boolean cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_bSkip = false protected
Definition at line 56 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
m_dH
double cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dH protected
Definition at line 41 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
m_dL
double cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dL protected
Definition at line 42 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
m_dLineTol
double cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dLineTol = 0.1 protected
Definition at line 53 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement().
m_dMaxStep
double cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dMaxStep = 0.06 protected
Definition at line 52 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement().
m_dPoint
final double [] cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dPoint = new double[2] protected
Definition at line 47 of file XodrRoadMarkParser.java.
m_dS
double cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dS protected
Definition at line 38 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
m_dX
double cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dX protected
Definition at line 39 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
m_dY
double cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_dY protected
Definition at line 40 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
m_oCtrlLineArcs
final ArrayList<CtrlLineArcs> cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oCtrlLineArcs = new ArrayList() protected
Definition at line 49 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.writeClas().
m_oLane
Lane cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oLane protected
Definition at line 45 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
m_oLaneSection
LaneSection cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oLaneSection protected
Definition at line 44 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
m_oProj
Proj cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oProj protected
Definition at line 46 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endCDATA(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement().
m_oRdMkInfo
ArrayList<int[]> cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oRdMkInfo = new ArrayList() package
Definition at line 55 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.writeClas().
m_oRoad
Road cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_oRoad protected
Definition at line 43 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
m_sBaseDir
String cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_sBaseDir protected
Definition at line 51 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.parseXodrToCLA(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.writeClas().
m_sBuf
final StringBuilder cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_sBuf = new StringBuilder() protected
Definition at line 48 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.characters(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endCDATA(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startCDATA().
m_sCtrlFile
String cc.geosrv.xodr.rdmk.XodrRoadMarkParser.m_sCtrlFile protected
Definition at line 50 of file XodrRoadMarkParser.java.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.parseXodrToCLA(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.writeClas().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/rdmk/XodrRoadMarkParser.java