Carma-cloud: cc.rsu.BSMRequest Class Reference
cc.rsu.BSMRequest Class Reference
Public Member Functions
String getV2xhub_port ()
void setV2xhub_port (String v2xhub_port)
String getId ()
void setId (String id)
ArrayList< Position > getRoute ()
void setRoute (ArrayList< Position > route)
Instant getLast_update_at ()
void setLast_update_at (Instant last_update_at)
BSMRequest ()
BSMRequest (String id, ArrayList< Position > route)
String toString ()
Public Attributes
String v2xhub_port
Private Attributes
String id
ArrayList< Position > route
Instant last_update_at
Detailed Description
Definition at line 10 of file BSMRequest.java.
Constructor & Destructor Documentation
BSMRequest() [1/2]
cc.rsu.BSMRequest.BSMRequest () inline
constructor
Definition at line 72 of file BSMRequest.java.
{
        super();
        route = new ArrayList<Position>();
    }
References cc.rsu.BSMRequest.route.
BSMRequest() [2/2]
cc.rsu.BSMRequest.BSMRequest (String id, ArrayList< Position > route) inline
Parameters
id BSM Hex
route a list of positions
Definition at line 81 of file BSMRequest.java.
{
        super();
        this.id = id;
        this.route = route;
    }
References cc.rsu.BSMRequest.id, and cc.rsu.BSMRequest.route.
Member Function Documentation
getId()
String cc.rsu.BSMRequest.getId () inline
Returns
BSM hex
Definition at line 30 of file BSMRequest.java.
{
        return id;
    }
References cc.rsu.BSMRequest.id.
Referenced by cc.rsu.HTTPClientTask.call(), cc.rsu.RSUIdentificationTask.call(), and cc.ws.RSUServlet.requestRSU().
getLast_update_at()
Instant cc.rsu.BSMRequest.getLast_update_at () inline
Returns
last update timestamp
Definition at line 58 of file BSMRequest.java.
{
        return last_update_at;
    }
References cc.rsu.BSMRequest.last_update_at.
getRoute()
ArrayList< Position > cc.rsu.BSMRequest.getRoute () inline
Returns
Return list of positions that form a vehicle route
Definition at line 44 of file BSMRequest.java.
{
        return route;
    }
References cc.rsu.BSMRequest.route.
Referenced by cc.rsu.RSUIdentificationTask.call(), and cc.ws.RSUServlet.requestRSU().
getV2xhub_port()
String cc.rsu.BSMRequest.getV2xhub_port () inline
Definition at line 19 of file BSMRequest.java.
{
        return v2xhub_port;
    }
References cc.rsu.BSMRequest.v2xhub_port.
setId()
void cc.rsu.BSMRequest.setId (String id) inline
Definition at line 37 of file BSMRequest.java.
{
        this.id = id;
    }
References cc.rsu.BSMRequest.id.
Referenced by cc.rsu.BSMRequestParser.endElement().
setLast_update_at()
void cc.rsu.BSMRequest.setLast_update_at (Instant last_update_at) inline
Parameters
last_update_at
Definition at line 65 of file BSMRequest.java.
{
        this.last_update_at = last_update_at;
    }
References cc.rsu.BSMRequest.last_update_at.
Referenced by cc.ws.RSUServlet.requestRSU().
setRoute()
void cc.rsu.BSMRequest.setRoute (ArrayList< Position > route) inline
Parameters
update route
Definition at line 51 of file BSMRequest.java.
{
        this.route = route;
    }
References cc.rsu.BSMRequest.route.
Referenced by cc.rsu.BSMRequestParser.endElement().
setV2xhub_port()
void cc.rsu.BSMRequest.setV2xhub_port (String v2xhub_port) inline
Definition at line 23 of file BSMRequest.java.
{
        this.v2xhub_port = v2xhub_port;
    }
References cc.rsu.BSMRequest.v2xhub_port.
toString()
String cc.rsu.BSMRequest.toString () inline
Definition at line 88 of file BSMRequest.java.
{
        return "BSMRequest [v2xhub_port="+ v2xhub_port + ", id=" + id + ", route=" + route + ", last_update_at=" + last_update_at + "]";
    }
References cc.rsu.BSMRequest.last_update_at, cc.rsu.BSMRequest.route, and cc.rsu.BSMRequest.v2xhub_port.
Member Data Documentation
id
String cc.rsu.BSMRequest.id private
Definition at line 12 of file BSMRequest.java.
Referenced by cc.rsu.BSMRequest.BSMRequest(), cc.rsu.BSMRequest.getId(), and cc.rsu.BSMRequest.setId().
last_update_at
Instant cc.rsu.BSMRequest.last_update_at private
Definition at line 15 of file BSMRequest.java.
Referenced by cc.rsu.BSMRequest.getLast_update_at(), cc.rsu.BSMRequest.setLast_update_at(), and cc.rsu.BSMRequest.toString().
route
ArrayList<Position> cc.rsu.BSMRequest.route private
Definition at line 14 of file BSMRequest.java.
Referenced by cc.rsu.BSMRequest.BSMRequest(), cc.rsu.BSMRequest.getRoute(), cc.rsu.BSMRequest.setRoute(), and cc.rsu.BSMRequest.toString().
v2xhub_port
String cc.rsu.BSMRequest.v2xhub_port
Definition at line 17 of file BSMRequest.java.
Referenced by cc.rsu.BSMRequest.getV2xhub_port(), cc.rsu.BSMRequest.setV2xhub_port(), and cc.rsu.BSMRequest.toString().
The documentation for this class was generated from the following file:
src/cc/rsu/BSMRequest.java