Carma-cloud: cc.geosrv.xodr.geo.LaneSection Class Reference
cc.geosrv.xodr.geo.LaneSection Class Reference
Public Member Functions
LaneSection ()
LaneSection (double dS, int nId)
void setInnerPaths ()
void add (Lane oLane)
void sortLanes ()
void getLanes (ArrayList< Lane > oLaneList)
void createPavement ()
Static Public Member Functions
static LaneSection getLaneSection (double dDist, ArrayList< LaneSection > oLaneSections)
Public Attributes
double m_dS
ArrayList< Lane > m_oLeft = new ArrayList()
ArrayList< Lane > m_oRight = new ArrayList()
Lane m_oCenter
int m_nId
double[] m_dPavement
ArrayList< double[]> m_oShoulders = new ArrayList()
Private Member Functions
void setInnerPaths (ArrayList< Lane > oLanes)
Static Private Attributes
static Comparator< Lane > LEFTLANES = (Lane o1, Lane o2) -> Integer.compare(o1.m_nLaneIndex, o2.m_nLaneIndex)
static Comparator< Lane > RIGHTLANES = (Lane o1, Lane o2) -> Integer.compare(o2.m_nLaneIndex, o1.m_nLaneIndex)
Detailed Description
Author
Federal Highway Administration
Definition at line 18 of file LaneSection.java.
Constructor & Destructor Documentation
LaneSection() [1/2]
cc.geosrv.xodr.geo.LaneSection.LaneSection () inline
Definition at line 30 of file LaneSection.java.
    {
    }
LaneSection() [2/2]
cc.geosrv.xodr.geo.LaneSection.LaneSection (double dS, int nId) inline
Definition at line 34 of file LaneSection.java.
    {
        m_dS = dS;
        m_nId = nId;
    }
References cc.geosrv.xodr.geo.LaneSection.m_dS, and cc.geosrv.xodr.geo.LaneSection.m_nId.
Member Function Documentation
add()
void cc.geosrv.xodr.geo.LaneSection.add (Lane oLane) inline
Definition at line 60 of file LaneSection.java.
    {
        if (oLane.m_nLaneIndex > 0)
            m_oLeft.add(oLane);
        else if (oLane.m_nLaneIndex < 0)
            m_oRight.add(oLane);
    }
References cc.geosrv.xodr.geo.Lane.m_nLaneIndex, cc.geosrv.xodr.geo.LaneSection.m_oLeft, and cc.geosrv.xodr.geo.LaneSection.m_oRight.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement().
createPavement()
void cc.geosrv.xodr.geo.LaneSection.createPavement () inline
Definition at line 99 of file LaneSection.java.
    {
        ArrayList<Lane> oLanes = new ArrayList();
        getLanes(oLanes);
        Collections.sort(oLanes, LEFTLANES);
        double[] dEdgeR = oLanes.get(0).m_dOuter;
        double[] dEdgeL = oLanes.get(oLanes.size() - 1).m_dOuter;
        double[] dPavementCenter = Arrays.newDoubleArray(Arrays.size(dEdgeL));
        dPavementCenter = Arrays.add(dPavementCenter, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
        int nLimit = Arrays.size(dEdgeR);
        for (int nIndex = 5; nIndex < nLimit; nIndex += 2)
        {
            double dXr = dEdgeR[nIndex];
            double dYr = dEdgeR[nIndex + 1];
            double dXl = dEdgeL[nIndex];
            double dYl = dEdgeL[nIndex + 1];
            double dPathX = (dXr + dXl) / 2;
            double dPathY = (dYr + dYl) / 2;
            double dW = Geo.distance(dXr, dYr, dXl, dYl);
            dPavementCenter = Arrays.addAndUpdate(dPavementCenter, dPathX, dPathY);
            dPavementCenter = Arrays.add(dPavementCenter, dW);
        }
        m_dPavement = dPavementCenter; // save local reference
    }
References cc.util.Arrays.add(), cc.util.Arrays.addAndUpdate(), cc.util.Geo.distance(), cc.geosrv.xodr.geo.LaneSection.getLanes(), cc.geosrv.xodr.geo.LaneSection.LEFTLANES, cc.geosrv.xodr.geo.LaneSection.m_dPavement, cc.util.Arrays.newDoubleArray(), and cc.util.Arrays.size().
Referenced by cc.geosrv.xodr.geo.Road.getPavementCtrlLineArcs().
getLanes()
void cc.geosrv.xodr.geo.LaneSection.getLanes (ArrayList< Lane > oLaneList) inline
Definition at line 90 of file LaneSection.java.
    {
        oLaneList.clear();
        oLaneList.add(m_oCenter);
        oLaneList.addAll(m_oLeft);
        oLaneList.addAll(m_oRight);
    }
References cc.geosrv.xodr.geo.LaneSection.m_oCenter, cc.geosrv.xodr.geo.LaneSection.m_oLeft, and cc.geosrv.xodr.geo.LaneSection.m_oRight.
Referenced by cc.geosrv.xodr.geo.LaneSection.createPavement(), and cc.geosrv.xodr.geo.Road.getDirectionCtrlLineArcs().
getLaneSection()
static LaneSection cc.geosrv.xodr.geo.LaneSection.getLaneSection (double dDist, ArrayList< LaneSection > oLaneSections) inline static
Definition at line 76 of file LaneSection.java.
    {
        int nIndex = oLaneSections.size();
        while (nIndex-- > 0)
        {
            LaneSection oTemp = oLaneSections.get(nIndex);
            if (dDist >= oTemp.m_dS)
                return oTemp;
        }
        return oLaneSections.get(0);
    }
References cc.geosrv.xodr.geo.LaneSection.m_dS.
setInnerPaths() [1/2]
void cc.geosrv.xodr.geo.LaneSection.setInnerPaths () inline
Definition at line 41 of file LaneSection.java.
    {
        setInnerPaths(m_oLeft);
        setInnerPaths(m_oRight);
    }
References cc.geosrv.xodr.geo.LaneSection.m_oLeft, cc.geosrv.xodr.geo.LaneSection.m_oRight, and cc.geosrv.xodr.geo.LaneSection.setInnerPaths().
Referenced by cc.geosrv.xodr.geo.LaneSection.setInnerPaths().
setInnerPaths() [2/2]
void cc.geosrv.xodr.geo.LaneSection.setInnerPaths (ArrayList< Lane > oLanes) inline private
Definition at line 48 of file LaneSection.java.
    {
        int nSize = oLanes.size();
        if (nSize > 0)
        {
            oLanes.get(0).m_dInner = m_oCenter.m_dOuter;
            for (int i = 1; i < nSize; i++)
                oLanes.get(i).m_dInner = oLanes.get(i - 1).m_dOuter;
        }
    }
References cc.geosrv.xodr.geo.Lane.m_dOuter, and cc.geosrv.xodr.geo.LaneSection.m_oCenter.
sortLanes()
void cc.geosrv.xodr.geo.LaneSection.sortLanes () inline
Definition at line 69 of file LaneSection.java.
    {
        Collections.sort(m_oLeft, LEFTLANES);
        Collections.sort(m_oRight, RIGHTLANES);
    }
References cc.geosrv.xodr.geo.LaneSection.LEFTLANES, cc.geosrv.xodr.geo.LaneSection.m_oLeft, cc.geosrv.xodr.geo.LaneSection.m_oRight, and cc.geosrv.xodr.geo.LaneSection.RIGHTLANES.
Referenced by cc.geosrv.xodr.geo.XodrGeoParser.endElement().
Member Data Documentation
LEFTLANES
Comparator<Lane> cc.geosrv.xodr.geo.LaneSection.LEFTLANES = (Lane o1, Lane o2) -> Integer.compare(o1.m_nLaneIndex, o2.m_nLaneIndex) static private
Definition at line 24 of file LaneSection.java.
Referenced by cc.geosrv.xodr.geo.LaneSection.createPavement(), and cc.geosrv.xodr.geo.LaneSection.sortLanes().
m_dPavement
double [] cc.geosrv.xodr.geo.LaneSection.m_dPavement
Definition at line 27 of file LaneSection.java.
Referenced by cc.geosrv.xodr.geo.LaneSection.createPavement(), and cc.geosrv.xodr.geo.Road.getPavementCtrlLineArcs().
m_dS
double cc.geosrv.xodr.geo.LaneSection.m_dS
Definition at line 20 of file LaneSection.java.
Referenced by cc.geosrv.xodr.geo.LaneSection.LaneSection(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addPoints(), cc.geosrv.xodr.geo.Line.addPoints(), cc.geosrv.xodr.geo.LaneSection.getLaneSection(), and cc.geosrv.xodr.geo.Road.getLaneSections().
m_nId
int cc.geosrv.xodr.geo.LaneSection.m_nId
Definition at line 26 of file LaneSection.java.
Referenced by cc.geosrv.xodr.geo.LaneSection.LaneSection(), and cc.geosrv.xodr.geo.Road.getPavementCtrlLineArcs().
m_oCenter
Lane cc.geosrv.xodr.geo.LaneSection.m_oCenter
Definition at line 23 of file LaneSection.java.
Referenced by cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.xodr.geo.LaneSection.getLanes(), and cc.geosrv.xodr.geo.LaneSection.setInnerPaths().
m_oLeft
ArrayList<Lane> cc.geosrv.xodr.geo.LaneSection.m_oLeft = new ArrayList()
Definition at line 21 of file LaneSection.java.
Referenced by cc.geosrv.xodr.geo.LaneSection.add(), cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.xodr.geo.LaneSection.getLanes(), cc.geosrv.xodr.geo.LaneSection.setInnerPaths(), and cc.geosrv.xodr.geo.LaneSection.sortLanes().
m_oRight
ArrayList<Lane> cc.geosrv.xodr.geo.LaneSection.m_oRight = new ArrayList()
Definition at line 22 of file LaneSection.java.
Referenced by cc.geosrv.xodr.geo.LaneSection.add(), cc.geosrv.xodr.geo.Geometry.addLanePoints(), cc.geosrv.xodr.geo.Arc.addLanePoints(), cc.geosrv.xodr.geo.LaneSection.getLanes(), cc.geosrv.xodr.geo.LaneSection.setInnerPaths(), and cc.geosrv.xodr.geo.LaneSection.sortLanes().
m_oShoulders
ArrayList<double[]> cc.geosrv.xodr.geo.LaneSection.m_oShoulders = new ArrayList()
Definition at line 28 of file LaneSection.java.
RIGHTLANES
Comparator<Lane> cc.geosrv.xodr.geo.LaneSection.RIGHTLANES = (Lane o1, Lane o2) -> Integer.compare(o2.m_nLaneIndex, o1.m_nLaneIndex) static private
Definition at line 25 of file LaneSection.java.
Referenced by cc.geosrv.xodr.geo.LaneSection.sortLanes().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/geo/LaneSection.java