Carma-cloud: cc.util.SimpleHull Class Reference
cc.util.SimpleHull Class Reference
Classes
class BottomLeft
Public Member Functions
SimpleHull ()
void getConvexHull (boolean bClockwise, int nOffset, double[] dPts)
void getConvexHull (Point2D.Double[] oPts)
int compare (Point2D.Double oLhs, Point2D.Double oRhs)
Protected Attributes
Point2D.Double m_oInPt
BottomLeft m_oComp = new BottomLeft()
Detailed Description
Definition at line 9 of file SimpleHull.java.
Constructor & Destructor Documentation
SimpleHull()
cc.util.SimpleHull.SimpleHull () inline
Definition at line 15 of file SimpleHull.java.
    {
    }
Member Function Documentation
compare()
int cc.util.SimpleHull.compare (Point2D.Double oLhs, Point2D.Double oRhs) inline
Definition at line 75 of file SimpleHull.java.
    {
    double dCp = (oLhs.x - m_oInPt.x) * (oRhs.y - m_oInPt.y) -
            (oRhs.x - m_oInPt.x) * (oLhs.y - m_oInPt.y);
    if (dCp < 0.0)
        return 1;
        return -1;
    }
References cc.util.SimpleHull.m_oInPt.
getConvexHull() [1/2]
void cc.util.SimpleHull.getConvexHull (boolean bClockwise, int nOffset, double[] dPts) inline
Definition at line 20 of file SimpleHull.java.
    {
        int nSize = (dPts.length - nOffset) >> 1;
        if (nSize < 3)
            return; // need at least 3 points
        int nPos = nOffset; // convert to Point2D.Double array
        Point2D.Double[] oPts = new Point2D.Double[nSize];
        for (int nIndex = 0; nIndex < nSize; nIndex++)
            oPts[nIndex] = new Point2D.Double(dPts[nPos++], dPts[nPos++]);
        getConvexHull(oPts); // adjust points for convex hull
        nPos = nOffset; // copy reordered points back to array
        for (int nIndex = 0; nIndex < nSize; nIndex++) // keep counter-clockwise order
        {
            Point2D.Double oPt = oPts[nIndex];
            System.out.append(String.format("[%2.7f,%2.7f],", Mercator.xToLon(oPt.x), Mercator.yToLat(oPt.y)));
//          dPts[nPos++] = oPt.x;
//          dPts[nPos++] = oPt.y;
        }
        System.out.println();
        if (bClockwise)
        {
            while (nSize-- > 0) // reverse default counter-clockwise order
            {
                Point2D.Double oPt = oPts[nSize];
                System.out.append(String.format("[%2.7f,%2.7f],", Mercator.xToLon(oPt.x), Mercator.yToLat(oPt.y)));
                dPts[nPos++] = oPt.x;
                dPts[nPos++] = oPt.y;
            }
        }
        else
        {
            for (int nIndex = 0; nIndex < nSize; nIndex++) // keep counter-clockwise order
            {
                Point2D.Double oPt = oPts[nIndex];
                System.out.append(String.format("[%2.7f,%2.7f],", Mercator.xToLon(oPt.x), Mercator.yToLat(oPt.y)));
                dPts[nPos++] = oPt.x;
                dPts[nPos++] = oPt.y;
            }
        }
        System.out.println();
    }
References cc.util.SimpleHull.getConvexHull(), cc.geosrv.Mercator.xToLon(), and cc.geosrv.Mercator.yToLat().
Referenced by cc.util.SimpleHull.getConvexHull().
getConvexHull() [2/2]
void cc.util.SimpleHull.getConvexHull (Point2D.Double[] oPts) inline
Definition at line 66 of file SimpleHull.java.
    {
        Arrays.sort(oPts, m_oComp); // sort extreme bottom-left point to top
        m_oInPt = oPts[0]; // exclude bottom-left point
        Arrays.sort(oPts, 1, oPts.length, this); // sort by increasing angles counter-clockwise
    }
References cc.util.SimpleHull.m_oComp, and cc.util.SimpleHull.m_oInPt.
Member Data Documentation
m_oComp
BottomLeft cc.util.SimpleHull.m_oComp = new BottomLeft() protected
Definition at line 12 of file SimpleHull.java.
Referenced by cc.util.SimpleHull.getConvexHull().
m_oInPt
Point2D.Double cc.util.SimpleHull.m_oInPt protected
Definition at line 11 of file SimpleHull.java.
Referenced by cc.util.SimpleHull.compare(), and cc.util.SimpleHull.getConvexHull().
The documentation for this class was generated from the following file:
src/cc/util/SimpleHull.java