Carma-cloud: cc.ctrl.CtrlGeo Class Reference
cc.ctrl.CtrlGeo Class Reference
Public Member Functions
final void updateBoundingBox (double dX, double dY)
Area createPolygon ()
Static Public Member Functions
static final void updateTiles (double dX, double dY, Mercator oM, ArrayList< int[]> oTiles, int[] nTile, double[] dPixel, int nZoom)
static void writePts (DataOutputStream oOut, double[] dPts) throws IOException
static int[] readPtsLonLats (DataInputStream oIn, int[] nPts) throws IOException
Public Attributes
double[] m_dNT
double[] m_dC
double[] m_dPT
double[] m_dBB = new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE}
ArrayList< int[]> m_oTiles = new ArrayList()
double m_dLength
double m_dAverageWidth = 0.0
double[] m_dDebugNT
double[] m_dDebugPT
Package Functions
CtrlGeo (DataInputStream oIn, boolean bUpdateTiles, int nZoom) throws IOException
CtrlGeo (TrafCtrl oCtrl, double dMaxStep, int nZoom) throws Exception
Package Attributes
int m_nZoom
Static Private Member Functions
static double[] readPtsUpdateTiles (DataInputStream oIn, double[] dPts, ArrayList< int[]> nTiles, int nZoom) throws IOException
static double[] readPts (DataInputStream oIn, double[] dPts) throws IOException
Detailed Description
Author
aaron.cherney
Definition at line 24 of file CtrlGeo.java.
Constructor & Destructor Documentation
CtrlGeo() [1/2]
cc.ctrl.CtrlGeo.CtrlGeo (DataInputStream oIn, boolean bUpdateTiles, int nZoom) throws IOException inline package
Definition at line 48 of file CtrlGeo.java.
    {
        m_nZoom = nZoom;
        for (int nIndex = 0; nIndex < m_dBB.length; nIndex++)
            m_dBB[nIndex] = oIn.readInt() / 100.0; // convert mercator cm to mercator meters
        m_dLength = oIn.readDouble();
        m_dAverageWidth = oIn.readDouble();
        if (bUpdateTiles)
        {
            m_dC = readPtsUpdateTiles(oIn, m_dC, m_oTiles, m_nZoom);
            m_dNT = readPtsUpdateTiles(oIn, m_dNT, m_oTiles, m_nZoom);
            m_dPT = readPtsUpdateTiles(oIn, m_dPT, m_oTiles, m_nZoom);
        }
        else
        {
            m_dC = readPts(oIn, m_dC);
            m_dNT = readPts(oIn, m_dNT);
            m_dPT = readPts(oIn, m_dPT);
        }
    }
References cc.ctrl.CtrlGeo.m_dAverageWidth, cc.ctrl.CtrlGeo.m_dBB, cc.ctrl.CtrlGeo.m_dC, cc.ctrl.CtrlGeo.m_dLength, cc.ctrl.CtrlGeo.m_dNT, cc.ctrl.CtrlGeo.m_dPT, cc.ctrl.CtrlGeo.m_nZoom, cc.ctrl.CtrlGeo.m_oTiles, cc.ctrl.CtrlGeo.readPts(), and cc.ctrl.CtrlGeo.readPtsUpdateTiles().
CtrlGeo() [2/2]
cc.ctrl.CtrlGeo.CtrlGeo (TrafCtrl oCtrl, double dMaxStep, int nZoom) throws Exception inline package
Definition at line 72 of file CtrlGeo.java.
    {
        m_nZoom = nZoom;
        int nNumPts = oCtrl.size();
        double dTotalLength = 0.0;
        double[] dPts = Arrays.newDoubleArray(nNumPts * 3);
        double[] dSeg = new double[9]; // used to store the current line/arc
        int nPrevX = Mercator.lonToCm(Geo.fromIntDeg(oCtrl.m_nLon));
        int nPrevY = Mercator.latToCm(Geo.fromIntDeg(oCtrl.m_nLat));
        int nPrevW = oCtrl.m_nWidth;
        int[] nTile = new int[2];
        double[] dPixel = new double[2];
        double[] dCenter = new double[2];
        Mercator oM = Mercator.getInstance();
        double dTotalWidth = 0.0;
        for (int nIndex = 0; nIndex < nNumPts; nIndex++)
        {
            TrafCtrlPt oTemp = oCtrl.get(nIndex);
            int nX = oTemp.m_nX + nPrevX;
            int nY = oTemp.m_nY + nPrevY;
            int nW = oTemp.m_nW + nPrevW;
            dPts = Arrays.add(dPts, nX / 100.0, nY / 100.0); // convert mercator cm to mercator meters
            double dW = nW /100.0;
            dTotalWidth += dW;
            dPts = Arrays.add(dPts, dW);
            nPrevX = nX;
            nPrevY = nY;
            nPrevW = nW;
        }
        m_dAverageWidth = dTotalWidth / nNumPts;
        double dLastTangent = 0;
        double[] dNT = Arrays.newDoubleArray(nNumPts * 2);
        m_dC = Arrays.newDoubleArray(nNumPts * 2);
        double[] dPT = Arrays.newDoubleArray(nNumPts * 2);
        m_dDebugNT = Arrays.newDoubleArray(nNumPts * 2);
        m_dDebugPT = Arrays.newDoubleArray(nNumPts * 2);
        Iterator<double[]> oIt = Arrays.iterator(dPts, dSeg, 1, 6);
        int nCount = 0;
        while (oIt.hasNext())
        {
            oIt.next();
            double dR = Geo.circle(dSeg[0], dSeg[1], dSeg[3], dSeg[4], dSeg[6], dSeg[7], dCenter);
            if (!Double.isFinite(dR) || dR >= 10000) // expand line
            {
                int nLimit;
                double dStep;
                double dLength = Geo.distance(dSeg[0], dSeg[1], dSeg[6], dSeg[7]);
                dTotalLength += dLength;
                if (dMaxStep > dLength)
                    nLimit = 1;
                else
                    nLimit = (int)(dLength / dMaxStep) + 1;
                int nHalfLimit = nLimit / 2;
                if (nHalfLimit == 0)
                    ++nHalfLimit;
                double dW1Step = (dSeg[5] - dSeg[2]) / nHalfLimit;
                double dW2Step = (dSeg[8] - dSeg[5]) / nHalfLimit;
                dStep = dLength / nLimit;
                double dHeading = Geo.heading(dSeg[0], dSeg[1], dSeg[6], dSeg[7]);
                if (Double.isNaN(dHeading) || dLength == 0.0)
                    continue;
                dLastTangent = dHeading;
                double dDeltaX = dStep * Math.cos(dHeading);
                double dDeltaY = dStep * Math.sin(dHeading);
                for (int i = 0; i < nLimit; i++)
                {
                    double dX = dSeg[0] + dDeltaX * i;
                    double dY = dSeg[1] + dDeltaY * i;
                    double dW = i < nHalfLimit ? dSeg[2] + dW1Step * i : dSeg[5] + dW2Step * (i - nHalfLimit);
                    dW /= 2;
                    m_dC = Arrays.add(m_dC, dX, dY);
//                  updateTileIndices(dX, dY, oM, m_nTileIndices, nTile, m_nZoom);
//                  updateBoundingBox((int)dX, (int)dY);
                    // calculate negative tangent path by subtracting pi/2 to heading
                    double dXPrime = dX + Math.sin(dHeading) * dW; // cos(x - pi/2) = sin(x)
                    double dYPrime = dY - Math.cos(dHeading) * dW; // sin(x - pi/2) = -cos(x)
                    dNT = Arrays.add(dNT, dXPrime, dYPrime);
                    updateTiles(dXPrime, dYPrime, oM, m_oTiles, nTile, dPixel, m_nZoom);
                    updateBoundingBox(dXPrime, dYPrime);
                    if (i == 0 || i == nLimit - 1)
                        m_dDebugNT = Arrays.add(m_dDebugNT, dXPrime, dYPrime);
                    // calculate positive tangent path by adding pi/2 to heading
                    dXPrime = dX - Math.sin(dHeading) * dW; // cos(x + pi/2 = -sin(x)
                    dYPrime = dY + Math.cos(dHeading) * dW; // sin(x + pi/2) = cos(x)
                    dPT = Arrays.add(dPT, dXPrime, dYPrime);
                    updateTiles(dXPrime, dYPrime, oM, m_oTiles, nTile, dPixel, m_nZoom);
                    updateBoundingBox(dXPrime, dYPrime);
                    if (i == 0 || i == nLimit - 1)
                        m_dDebugPT = Arrays.add(m_dDebugPT, dXPrime, dYPrime);
                }
            }
            else // expand arc
            {
                int nRightHand = Geo.rightHand(dSeg[3], dSeg[4], dSeg[0], dSeg[1], dSeg[6], dSeg[7]);
                double dRForCalcs = dR * -nRightHand;
                double dC = 1 / dRForCalcs;
                double dCmAngleStep = dC / 100;
//              double dCmAngleStepMag = Math.abs(dCmAngleStep);
                double dH = dCenter[0];
                double dK = dCenter[1];
                double dHdg = Geo.heading(dH, dK, dSeg[0], dSeg[1]);
//              double dLength = 0;
//              int nSteps = 0;
//              double dTheta = 0;
//              double dPrevX = dSeg[0];
//              double dPrevY = dSeg[1];
//              double dPrevAngle = Geo.angle(dPrevX, dPrevY, dH, dK, dSeg[6], dSeg[7]);
//              while (dPrevAngle > dCmAngleStepMag)
//              {
//                  dPrevX = dH + dR * Math.cos(dHdg + dCmAngleStep * ++nSteps);
//                  dPrevY = dK + dR * Math.sin(dHdg + dCmAngleStep * nSteps);
//                  dLength += 0.01;
//                  dTheta += dCmAngleStep;
//                  dPrevAngle = Geo.angle(dPrevX, dPrevY, dH, dK, dSeg[6], dSeg[7]);
//              }
//              double dLastAngle = Geo.angle(dPrevX, dPrevY, dH, dK, dSeg[6], dSeg[7]);
//              dLength += dLastAngle * dR;
//              dTheta += dLastAngle * -nRightHand;
//              dTotalLength += dLength;
                double dTheta = dCmAngleStep;
                double dDist;
                while (true)
                {
                    double dCirX = dH + dR * Math.cos(dHdg + dTheta);
                    double dCirY = dK + dR * Math.sin(dHdg + dTheta);
                    dDist = Geo.distance(dSeg[6], dSeg[7], dCirX, dCirY);
//                  dLength += 0.01;
                    if (dDist > 0.02)
                        dTheta += dCmAngleStep;
                    else
                    {
                        if (nRightHand == Geo.rightHand(dCirX, dCirY, dSeg[0], dSeg[1], dSeg[6], dSeg[7]))
                            dTheta += -nRightHand * Geo.angle(dCirX, dCirY, dH, dK, dSeg[6], dSeg[7]);
                        else
                            dTheta -= -nRightHand * Geo.angle(dCirX, dCirY, dH, dK, dSeg[6], dSeg[7]);
                        break;
                    }
                }
                double dLength = dTheta * dRForCalcs;
                dTotalLength += dLength;
                int nLimit;
                if (dMaxStep > dLength)
                    nLimit = 1;
                else
                    nLimit = (int)(dLength / dMaxStep) + 1;
                int nHalfLimit = nLimit / 2;
                if (nHalfLimit == 0)
                    ++nHalfLimit;
                double dW1Step = (dSeg[5] - dSeg[2]) / nHalfLimit;
                double dW2Step = (dSeg[8] - dSeg[5]) / nHalfLimit;
                double dAngleStep = dTheta / nLimit;
                double dTanAdd = dAngleStep > 0 ? Math.PI / 2 : -Math.PI / 2;
                dAngleStep = dTheta / nLimit;
                double dTotalAngle = 0;
                for (int i = 0; i < nLimit; i++)
                {
                    double dAngle = dHdg + dTotalAngle;
                    double dX = dH + dR * Math.cos(dAngle);
                    double dY = dK + dR * Math.sin(dAngle);
                    double dW = i < nHalfLimit ? dSeg[2] + dW1Step * i : dSeg[5] + dW2Step * (i - nHalfLimit); // interpolate the width
                    dW /= 2;
                    double dTangent = dAngle + dTanAdd;
                    m_dC = Arrays.add(m_dC, dX, dY);
//                  updateTileIndices(dX, dY, oM, m_nTileIndices, nTile, m_nZoom);
//                  updateBoundingBox((int)dX, (int)dY);
                    // calculate negative tangent path by subtracting pi/2 to heading
                    double dXPrime = dX + Math.sin(dTangent) * dW; // cos(x - pi/2) = sin(x)
                    double dYPrime = dY - Math.cos(dTangent) * dW; // sin(x - pi/2) = -cos(x)
                    dNT = Arrays.add(dNT, dXPrime, dYPrime);
                    updateTiles(dXPrime, dYPrime, oM, m_oTiles, nTile, dPixel, m_nZoom);
                    updateBoundingBox(dXPrime, dYPrime);
                    if (i == 0 || i == nLimit - 1)
                        m_dDebugNT = Arrays.add(m_dDebugNT, dXPrime, dYPrime);
                    // calculate postive tangent path by adding pi/2 to heading
                    dXPrime = dX - Math.sin(dTangent) * dW; // cos(x + pi/2 = -sin(x)
                    dYPrime = dY + Math.cos(dTangent) * dW; // sin(x + pi/2) = cos(x)
                    dPT = Arrays.add(dPT, dXPrime, dYPrime);
                    updateTiles(dXPrime, dYPrime, oM, m_oTiles, nTile, dPixel, m_nZoom);
                    updateBoundingBox(dXPrime, dYPrime);
                    if (i == 0 || i == nLimit - 1)
                        m_dDebugPT = Arrays.add(m_dDebugPT, dXPrime, dYPrime);
                    dTotalAngle += dAngleStep;
                }
                dLastTangent = dHdg + dTotalAngle + dTanAdd;
            }
        }
        // always add the last point since the last point of each linearc is usually the first point of the next linearc
        m_dC = Arrays.add(m_dC, dSeg[6], dSeg[7]);
//      updateTileIndices(oLast.m_nX, oLast.m_nY, oM, m_nTileIndices, nTile, m_nZoom);
//      updateBoundingBox(oLast.m_nX, oLast.m_nY);
        // calculate negative tangent path by subtracting pi/2 to heading
        double dW = dSeg[8] / 2;
        double dXPrime = dSeg[6] + Math.sin(dLastTangent) * dW; // cos(x - pi/2) = sin(x)
        double dYPrime = dSeg[7] - Math.cos(dLastTangent) * dW; // sin(x - pi/2) = -cos(x)
        dNT = Arrays.add(dNT, dXPrime, dYPrime);
        updateTiles(dXPrime, dYPrime, oM, m_oTiles, nTile, dPixel, m_nZoom);
        updateBoundingBox(dXPrime, dYPrime);
        // calculate postive tangent path by adding pi/2 to heading
        dXPrime = dSeg[6] - Math.sin(dLastTangent) * dW; // cos(x + pi/2 = -sin(x)
        dYPrime = dSeg[7] + Math.cos(dLastTangent) * dW; // sin(x + pi/2) = cos(x)
        dPT = Arrays.add(dPT, dXPrime, dYPrime);
        updateTiles(dXPrime, dYPrime, oM, m_oTiles, nTile, dPixel, m_nZoom);
        updateBoundingBox(dXPrime, dYPrime);
        m_dLength = dTotalLength;
//      Iterator<double[]> oC = Arrays.iterator(dPT, new double[4], 1, 2);
//      double dPrevHdg = Geo.heading(dPT[1], dPT[2], dPT[3], dPT[4]);
//      double dPrevLen = Geo.distance(dPT[1], dPT[2], dPT[3], dPT[4]);
//      nCount = 0;
//      while (oC.hasNext())
//      {
//          dSeg = oC.next();
//          double dHdg = Geo.heading(dSeg[0], dSeg[1], dSeg[2], dSeg[3]);
//          double dLen = Geo.distance(dSeg[0], dSeg[1], dSeg[2], dSeg[3]);
//          System.out.println(String.format("%d\t%f\t%f\t%1.7f\t%1.7f", nCount, dSeg[0], dSeg[1], dHdg, dLen));
//          if (Math.abs(dHdg - dPrevHdg) > 1)
//              System.out.println(String.format("fail\t%d\t%1.7f%17f", nCount, dPrevHdg, dPrevLen));
//          ++nCount;
//          dPrevHdg = dHdg;
//          dPrevLen = dLen;
//      }
        m_dPT = dPT;
        m_dNT = dNT;
    }
References cc.util.Arrays.add(), cc.util.Geo.angle(), cc.util.Geo.circle(), cc.util.Geo.distance(), cc.util.Geo.fromIntDeg(), cc.geosrv.Mercator.getInstance(), cc.util.Geo.heading(), cc.util.Arrays.iterator(), cc.geosrv.Mercator.latToCm(), cc.geosrv.Mercator.lonToCm(), cc.ctrl.CtrlGeo.m_dAverageWidth, cc.ctrl.CtrlGeo.m_dC, cc.ctrl.CtrlGeo.m_dDebugNT, cc.ctrl.CtrlGeo.m_dDebugPT, cc.ctrl.CtrlGeo.m_dLength, cc.ctrl.CtrlGeo.m_dNT, cc.ctrl.CtrlGeo.m_dPT, cc.ctrl.CtrlGeo.m_nZoom, cc.ctrl.CtrlGeo.m_oTiles, cc.util.Arrays.newDoubleArray(), cc.util.Geo.rightHand(), cc.ctrl.CtrlGeo.updateBoundingBox(), and cc.ctrl.CtrlGeo.updateTiles().
Member Function Documentation
createPolygon()
Area cc.ctrl.CtrlGeo.createPolygon () inline
Definition at line 434 of file CtrlGeo.java.
    {
        double[] dInOrder = m_dPT;
        double[] dReverseOrder = m_dNT;
        int nInOrderLimit = Arrays.size(dInOrder);
        int nReverseOrderLimit = Arrays.size(dReverseOrder);
        Path2D.Double dPoly = new Path2D.Double();
        dPoly.moveTo(dInOrder[5], dInOrder[6]);
        for (int i = 7; i < nInOrderLimit;)
            dPoly.lineTo(dInOrder[i++], dInOrder[i++]);
        for (int i = nReverseOrderLimit - 2; i >= 5; i -= 2)
            dPoly.lineTo(dReverseOrder[i], dReverseOrder[i + 1]);
        dPoly.closePath();
        return new Area(dPoly);
    }
References cc.ctrl.CtrlGeo.m_dNT, cc.ctrl.CtrlGeo.m_dPT, and cc.util.Arrays.size().
readPts()
static double[] cc.ctrl.CtrlGeo.readPts (DataInputStream oIn, double[] dPts) throws IOException inline static private
Definition at line 391 of file CtrlGeo.java.
    {
        int nLen = oIn.readInt(); // read array length
        dPts = Arrays.newDoubleArray(nLen); // create new growable array
        int nPrevX = oIn.readInt(); // read first point, these values are in mercator cm
        int nPrevY = oIn.readInt();
        dPts = Arrays.add(dPts, nPrevX / 100.0, nPrevY / 100.0); // add first point, converting them to mercator meters
        for (int nIndex = 2; nIndex < nLen; nIndex += 2)
        {
            int nX = nPrevX + oIn.readByte(); // calculate the rest of the points by using deltas
            int nY = nPrevY + oIn.readByte();
            dPts = Arrays.add(dPts, nX / 100.0, nY / 100.0); // convert them to mercator meters
            nPrevX = nX;
            nPrevY = nY;
        }
        return dPts;
    }
References cc.util.Arrays.add(), and cc.util.Arrays.newDoubleArray().
Referenced by cc.ctrl.CtrlGeo.CtrlGeo().
readPtsLonLats()
static int[] cc.ctrl.CtrlGeo.readPtsLonLats (DataInputStream oIn, int[] nPts) throws IOException inline static
Definition at line 412 of file CtrlGeo.java.
    {
        int nLen = oIn.readInt(); // read array length
        nPts = Arrays.ensureCapacity(nPts, nLen); // create new growable array
        int nPrevX = oIn.readInt(); // read first point
        int nPrevY = oIn.readInt();
        nPts = Arrays.add(nPts, Geo.toIntDeg(Mercator.xToLon(nPrevX / 100.0)), Geo.toIntDeg(Mercator.yToLat(nPrevY / 100.0))); // add first point
        for (int nIndex = 2; nIndex < nLen; nIndex += 2)
        {
            int nX = nPrevX + oIn.readByte(); // calculate the rest of the points by using deltas
            int nY = nPrevY + oIn.readByte();
            nPts = Arrays.add(nPts, Geo.toIntDeg(Mercator.xToLon(nPrevX / 100.0)), Geo.toIntDeg(Mercator.yToLat(nPrevY / 100.0)));
            nPrevX = nX;
            nPrevY = nY;
        }
        return nPts;
    }
References cc.util.Arrays.add(), cc.util.Arrays.ensureCapacity(), cc.util.Geo.toIntDeg(), cc.geosrv.Mercator.xToLon(), and cc.geosrv.Mercator.yToLat().
readPtsUpdateTiles()
static double[] cc.ctrl.CtrlGeo.readPtsUpdateTiles (DataInputStream oIn, double[] dPts, ArrayList< int[]> nTiles, int nZoom) throws IOException inline static private
Definition at line 362 of file CtrlGeo.java.
    {
        int[] nTile = new int[2];
        double[] dPixel = new double[2];
        Mercator oM = Mercator.getInstance();
        double dXPrime;
        double dYPrime;
        int nLen = oIn.readInt(); // read array length
        dPts = Arrays.newDoubleArray(nLen); // create new growable array
        int nPrevX = oIn.readInt(); // read first point, these values are in mercator cm
        int nPrevY = oIn.readInt();
        dPts = Arrays.add(dPts, nPrevX / 100.0, nPrevY / 100.0); // add first point, converting them to mercator meters
        for (int nIndex = 2; nIndex < nLen; nIndex += 2)
        {
            int nX = nPrevX + oIn.readByte(); // calculate the rest of the points by using deltas
            int nY = nPrevY + oIn.readByte();
            dXPrime = nX / 100.0;
            dYPrime = nY / 100.0;
            dPts = Arrays.add(dPts, nX / 100.0, nY / 100.0); // convert them to mercator meters
            updateTiles(dXPrime, dYPrime, oM, nTiles, nTile, dPixel, nZoom);
            nPrevX = nX;
            nPrevY = nY;
        }
        return dPts;
    }
References cc.util.Arrays.add(), cc.geosrv.Mercator.getInstance(), cc.util.Arrays.newDoubleArray(), and cc.ctrl.CtrlGeo.updateTiles().
Referenced by cc.ctrl.CtrlGeo.CtrlGeo().
updateBoundingBox()
final void cc.ctrl.CtrlGeo.updateBoundingBox (double dX, double dY) inline
Definition at line 326 of file CtrlGeo.java.
    {
        if (dX < m_dBB[0])
            m_dBB[0] = dX;
        if (dY < m_dBB[1])
            m_dBB[1] = dY;
        if (dX > m_dBB[2])
            m_dBB[2] = dX;
        if (dY > m_dBB[3])
            m_dBB[3] = dY;
    }
References cc.ctrl.CtrlGeo.m_dBB.
Referenced by cc.ctrl.CtrlGeo.CtrlGeo().
updateTiles()
static final void cc.ctrl.CtrlGeo.updateTiles (double dX, double dY, Mercator oM, ArrayList< int[]> oTiles, int[] nTile, double[] dPixel, int nZoom) inline static
Definition at line 314 of file CtrlGeo.java.
    {
        oM.metersToTile(dX, dY, nZoom, nTile);
        int nIndex = Collections.binarySearch(oTiles, nTile, Mercator.TILECOMP);
        if (nIndex < 0)
        {
            int[] nNew = new int[]{nTile[0], nTile[1]};
            oTiles.add(~nIndex, nNew);
        }
    }
References cc.geosrv.Mercator.metersToTile(), and cc.geosrv.Mercator.TILECOMP.
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), and cc.ctrl.CtrlGeo.readPtsUpdateTiles().
writePts()
static void cc.ctrl.CtrlGeo.writePts (DataOutputStream oOut, double[] dPts) throws IOException inline static
Definition at line 339 of file CtrlGeo.java.
    {
        oOut.writeInt(Arrays.size(dPts) - 1);
        int nPrevX = (int)(dPts[1] * 100.0 + 0.5); // convert mercator meters to mercator cms, rounding to nearest cm
        int nPrevY = (int)(dPts[2] * 100.0 + 0.5);
        oOut.writeInt(nPrevX);
        oOut.writeInt(nPrevY);
        Iterator<double[]> oIt = Arrays.iterator(dPts, new double[2], 3, 2);
        int nCurX;
        int nCurY;
        while (oIt.hasNext())
        {
            double[] dPt = oIt.next();
            nCurX = (int)(dPt[0] * 100.0 + 0.5); // convert mercator meters to mercator cms, rounding to nearest cm
            nCurY = (int)(dPt[1] * 100.0 + 0.5);
            oOut.writeByte(nCurX - nPrevX); // write the deltas in the file
            oOut.writeByte(nCurY - nPrevY);
            nPrevX = nCurX;
            nPrevY = nCurY;
        }
    }
References cc.util.Arrays.iterator(), and cc.util.Arrays.size().
Referenced by cc.ctrl.TrafCtrl.writeBin().
Member Data Documentation
m_dAverageWidth
double cc.ctrl.CtrlGeo.m_dAverageWidth = 0.0
Definition at line 43 of file CtrlGeo.java.
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), and cc.ctrl.TrafCtrl.writeBin().
m_dBB
double [] cc.ctrl.CtrlGeo.m_dBB = new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE}
Definition at line 39 of file CtrlGeo.java.
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ctrl.CtrlGeo.updateBoundingBox(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeIndex().
m_dC
double [] cc.ctrl.CtrlGeo.m_dC
center path
Definition at line 33 of file CtrlGeo.java.
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ws.CtrlTiles.addControl(), cc.util.TileUtil.clipCtrlGeoForTile(), cc.util.Geo.ctrlIntersectBounds(), cc.ctrl.proc.ProcCtrl.getStopLine(), cc.ctrl.TrafCtrl.preparePoints(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), and cc.ctrl.TrafCtrl.writeBin().
m_dDebugNT
double [] cc.ctrl.CtrlGeo.m_dDebugNT
Definition at line 44 of file CtrlGeo.java.
Referenced by cc.ctrl.CtrlGeo.CtrlGeo().
m_dDebugPT
double [] cc.ctrl.CtrlGeo.m_dDebugPT
Definition at line 45 of file CtrlGeo.java.
Referenced by cc.ctrl.CtrlGeo.CtrlGeo().
m_dLength
double cc.ctrl.CtrlGeo.m_dLength
Definition at line 42 of file CtrlGeo.java.
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), and cc.ctrl.TrafCtrl.writeBin().
m_dNT
double [] cc.ctrl.CtrlGeo.m_dNT
negative tangent path
Definition at line 29 of file CtrlGeo.java.
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ws.CtrlTiles.addControl(), cc.util.TileUtil.clipCtrlGeoForTile(), cc.ctrl.CtrlGeo.createPolygon(), cc.util.Geo.ctrlIntersectBounds(), cc.ws.GeoLanes.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcCtrl.getStopLine(), cc.util.TileUtil.includeInTile(), cc.ctrl.TrafCtrl.preparePoints(), and cc.ctrl.TrafCtrl.writeBin().
m_dPT
double [] cc.ctrl.CtrlGeo.m_dPT
positive tangent path
Definition at line 37 of file CtrlGeo.java.
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.util.TileUtil.clipCtrlGeoForTile(), cc.ctrl.CtrlGeo.createPolygon(), cc.util.Geo.ctrlIntersectBounds(), cc.ws.GeoLanes.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcCtrl.getStopLine(), cc.util.TileUtil.includeInTile(), cc.ctrl.proc.ProcClosed.renderTiledData(), and cc.ctrl.TrafCtrl.writeBin().
m_nZoom
int cc.ctrl.CtrlGeo.m_nZoom package
Definition at line 41 of file CtrlGeo.java.
Referenced by cc.ctrl.CtrlGeo.CtrlGeo().
m_oTiles
ArrayList<int[]> cc.ctrl.CtrlGeo.m_oTiles = new ArrayList()
Definition at line 40 of file CtrlGeo.java.
Referenced by cc.ctrl.CtrlGeo.CtrlGeo(), cc.ws.CtrlTiles.addControl(), cc.rsm.RsmCollect.RsmRecord.cleanup(), cc.ctrl.CreateCtrls.createCtrl(), cc.ctrl.proc.ProcCtrl.deleteControl(), cc.ws.WxPoly.doPost(), cc.ctrl.RenderCtrl.main(), cc.rsm.RsmParser.parseRequest(), cc.ctrl.proc.ProcClosed.proc(), cc.ctrl.proc.ProcClosing.proc(), cc.ctrl.proc.ProcDebug.proc(), cc.ctrl.proc.ProcDebugOutlines.proc(), cc.ctrl.proc.ProcDirection.proc(), cc.ctrl.proc.ProcLatPerm.proc(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ctrl.proc.ProcOpening.proc(), cc.ctrl.proc.ProcPavement.proc(), cc.ctrl.proc.ProcSignal.proc(), cc.ctrl.proc.ProcStop.proc(), cc.ctrl.proc.ProcYield.proc(), cc.ctrl.proc.ProcDirection.renderTiledData(), cc.ctrl.proc.ProcHeadway.renderTiledData(), cc.ctrl.proc.ProcMaxSpeed.renderTiledData(), cc.ctrl.proc.ProcSignal.renderTiledData(), cc.ws.CtrlTiles.saveEdit(), and cc.ws.CtrlTiles.splitLineArcs().
The documentation for this class was generated from the following file:
src/cc/ctrl/CtrlGeo.java