Carma-cloud: cc.geosrv.xodr.rdmk.Road Class Reference
cc.geosrv.xodr.rdmk.Road Class Reference
Public Member Functions
Road (int nId, double dLength)
void adjustSections (double dMaxStep)
void createPoints (double dMaxStep, Proj oProj)
void setLaneIds (double dMaxStep)
void getRdMkCtrlLineArcs (ArrayList< CtrlLineArcs > oCtrlLineArcs, double dMaxStep, ArrayList< int[]> oRdMkInfo)
void getLaneSections (ArrayDeque< LaneSection > oSections, double dStart, double dEnd)
Public Attributes
int m_nId
double m_dLength
double[] m_dTrack
double[] m_dLaneZero
double[] m_dBounds = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE}
Protected Member Functions
Road ()
Package Attributes
ArrayList< LaneOffset > m_oLaneOffsets = new ArrayList()
ArrayList< Geometry > m_oGeometries = new ArrayList()
Static Private Attributes
static Comparator< int[]> RDMKCOMP
Detailed Description
Author
aaron.cherney
Definition at line 23 of file Road.java.
Constructor & Destructor Documentation
Road() [1/2]
cc.geosrv.xodr.rdmk.Road.Road () inline protected
Definition at line 39 of file Road.java.
    {
    }
Road() [2/2]
cc.geosrv.xodr.rdmk.Road.Road (int nId, double dLength) inline
Definition at line 45 of file Road.java.
    {
        m_nId = nId;
        m_dLength = dLength;
        m_dTrack = Arrays.newDoubleArray();
        m_dLaneZero = Arrays.newDoubleArray();
    }
References cc.geosrv.xodr.rdmk.Road.m_dLaneZero, cc.geosrv.xodr.rdmk.Road.m_dLength, cc.geosrv.xodr.rdmk.Road.m_dTrack, cc.geosrv.xodr.rdmk.Road.m_nId, and cc.util.Arrays.newDoubleArray().
Member Function Documentation
adjustSections()
void cc.geosrv.xodr.rdmk.Road.adjustSections (double dMaxStep) inline
Definition at line 54 of file Road.java.
    {
        int nIndex = size();
        if (nIndex == 1)
            return;
        double dPrevOffset = m_dLength;
        while (nIndex-- > 0)
        {
            double dSectionLength = dPrevOffset - get(nIndex).m_dS;
            if (dSectionLength < dMaxStep)
                remove(nIndex);
            else
                dPrevOffset = get(nIndex).m_dS;
        }
        if (get(0).m_dS != 0.0)
            get(0).m_dS = 0;
    }
References cc.geosrv.xodr.rdmk.Road.m_dLength.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement().
createPoints()
void cc.geosrv.xodr.rdmk.Road.createPoints (double dMaxStep, Proj oProj) inline
Definition at line 82 of file Road.java.
    {
        Collections.sort(m_oGeometries);
        double[] dProjPt = new double[2];
        for (int nIndex = 0; nIndex < m_oGeometries.size() - 1; nIndex++)
            m_oGeometries.get(nIndex).addPoints(this, dMaxStep, false, oProj, dProjPt);
        m_oGeometries.get(m_oGeometries.size() - 1).addPoints(this, dMaxStep, true, oProj, dProjPt);
    }
References cc.geosrv.xodr.rdmk.Road.m_oGeometries.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement().
getLaneSections()
void cc.geosrv.xodr.rdmk.Road.getLaneSections (ArrayDeque< LaneSection > oSections, double dStart, double dEnd) inline
Definition at line 189 of file Road.java.
    {
        oSections.clear();
        int nIndex = size();
        double dSectionEnd = m_dLength;
        while (nIndex-- > 0)
        {
            LaneSection oTemp = get(nIndex);
            if (dStart < dSectionEnd && dEnd > oTemp.m_dS)
                oSections.addFirst(oTemp);
            dSectionEnd = oTemp.m_dS;
        }
    }
References cc.geosrv.xodr.rdmk.Road.m_dLength, and cc.geosrv.xodr.rdmk.LaneSection.m_dS.
Referenced by cc.geosrv.xodr.rdmk.Arc.addPoints(), and cc.geosrv.xodr.rdmk.Line.addPoints().
getRdMkCtrlLineArcs()
void cc.geosrv.xodr.rdmk.Road.getRdMkCtrlLineArcs (ArrayList< CtrlLineArcs > oCtrlLineArcs, double dMaxStep, ArrayList< int[]> oRdMkInfo) inline
Definition at line 148 of file Road.java.
    {
        ArrayList<Lane> oLanes = new ArrayList();
        int[] nSearch = new int[3];
        for (LaneSection oSection : this)
        {
            oSection.getLanes(oLanes);
            for (Lane oLane : oLanes)
            {
                if (oLane.m_nLaneIndex == 0) // skip zero width center lane
                {
                    continue;
                }
                XodrUtil.splitLaneSectionId(XodrUtil.getLaneSectionId(m_nId, oSection.m_nId, oLane.m_nLaneIndex), 1, nSearch);
                int nIndex = Collections.binarySearch(oRdMkInfo, nSearch, RDMKCOMP);
                if (nIndex < 0)
                {
                    oLane.m_nRdMkTags = Arrays.insert(oLane.m_nRdMkTags, nSearch[1], 1);
                    oLane.m_nRdMkTags = Arrays.insert(oLane.m_nRdMkTags, nSearch[2], 2);
                    oRdMkInfo.add(~nIndex, oLane.m_nRdMkTags);
                }
                else
                {
                    int[] nRdMkInfo = oRdMkInfo.get(nIndex);
                    Iterator<int[]> oIt = Arrays.iterator(oLane.m_nRdMkTags, new int[8], 1, 8);
                    while (oIt.hasNext())
                    {
                        int[] nTags = oIt.next();
                        nRdMkInfo = Arrays.add(nRdMkInfo, nTags);
                    }
                }
                for (double[] dCenter : oLane.m_dCenters)
                {
                    oCtrlLineArcs.add(new CtrlLineArcs(m_nId, oSection.m_nId, oLane.m_nLaneIndex, oLane.m_nLaneIdByRoad, oLane.m_nType, dCenter, dMaxStep));
                }
            }
        }
    }
References cc.util.Arrays.add(), cc.geosrv.xodr.rdmk.LaneSection.getLanes(), cc.geosrv.xodr.XodrUtil.getLaneSectionId(), cc.util.Arrays.insert(), cc.util.Arrays.iterator(), cc.geosrv.xodr.rdmk.LaneSection.m_nId, cc.geosrv.xodr.rdmk.Road.m_nId, cc.geosrv.xodr.rdmk.Road.RDMKCOMP, and cc.geosrv.xodr.XodrUtil.splitLaneSectionId().
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement().
setLaneIds()
void cc.geosrv.xodr.rdmk.Road.setLaneIds (double dMaxStep) inline
Definition at line 92 of file Road.java.
    {
        double dTol = dMaxStep * 2;
        ArrayList<Lane> oPrevLanes = new ArrayList();
        get(0).getLanes(oPrevLanes);
        int nNextId = Integer.MIN_VALUE;
        for (Lane oLane : oPrevLanes)
        {
            oLane.m_nLaneIdByRoad = oLane.m_nLaneIndex;
            int nComp = Math.abs(oLane.m_nLaneIndex);
            if (nComp > nNextId)
                nNextId = nComp;
        }
        for (int nIndex = 1; nIndex < size(); nIndex++)
        {
            ArrayList<Lane> oCurrLanes = new ArrayList();
            get(nIndex).getLanes(oCurrLanes);
            for (Lane oCurr: oCurrLanes)
            {
                if (oCurr.m_nLaneIndex == 0)
                    continue;
                double[] dCurr = oCurr.m_dCenters.get(0);
                oCurr.m_nLaneIdByRoad = Integer.MIN_VALUE;
                for (Lane oPrev: oPrevLanes)
                {
                    if (oPrev.m_nLaneIndex == 0)
                        continue;
                    double[] dPrev = oPrev.m_dCenters.get(oPrev.m_dCenters.size() - 1);
                    int nSize = Arrays.size(dPrev);
                    double dDist = Geo.distance(dCurr[5], dCurr[6], dPrev[nSize - 3], dPrev[nSize - 2]);
//                  if (dDist > dTol)
//                      System.out.println(dDist);
                    if (dDist <= dTol && oCurr.m_nType == oCurr.m_nType)
                    {
                        oCurr.m_nLaneIdByRoad = oPrev.m_nLaneIdByRoad;
                        break;
                    }
                }
                if (oCurr.m_nLaneIdByRoad == Integer.MIN_VALUE)
                {
                    ++nNextId;
                    if (oCurr.m_nLaneIndex < 0)
                        oCurr.m_nLaneIdByRoad = -nNextId;
                    else
                        oCurr.m_nLaneIdByRoad = nNextId;
                }
            }
            oPrevLanes.clear();
            oPrevLanes.addAll(oCurrLanes);
        }
    }
References cc.util.Geo.distance(), and cc.util.Arrays.size().
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement().
Member Data Documentation
m_dBounds
double [] cc.geosrv.xodr.rdmk.Road.m_dBounds = new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE}
Definition at line 29 of file Road.java.
m_dLaneZero
double [] cc.geosrv.xodr.rdmk.Road.m_dLaneZero
Definition at line 28 of file Road.java.
Referenced by cc.geosrv.xodr.rdmk.Road.Road(), cc.geosrv.xodr.rdmk.Arc.addPoints(), cc.geosrv.xodr.rdmk.Line.addPoints(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
m_dLength
double cc.geosrv.xodr.rdmk.Road.m_dLength
Definition at line 26 of file Road.java.
Referenced by cc.geosrv.xodr.rdmk.Road.Road(), cc.geosrv.xodr.rdmk.Road.adjustSections(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement(), and cc.geosrv.xodr.rdmk.Road.getLaneSections().
m_dTrack
double [] cc.geosrv.xodr.rdmk.Road.m_dTrack
Definition at line 27 of file Road.java.
Referenced by cc.geosrv.xodr.rdmk.Road.Road(), cc.geosrv.xodr.rdmk.Arc.addPoints(), cc.geosrv.xodr.rdmk.Line.addPoints(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
m_nId
int cc.geosrv.xodr.rdmk.Road.m_nId
Definition at line 25 of file Road.java.
Referenced by cc.geosrv.xodr.rdmk.Road.Road(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement(), cc.geosrv.xodr.rdmk.Road.getRdMkCtrlLineArcs(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
m_oGeometries
ArrayList<Geometry> cc.geosrv.xodr.rdmk.Road.m_oGeometries = new ArrayList() package
Definition at line 31 of file Road.java.
Referenced by cc.geosrv.xodr.rdmk.Road.createPoints(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
m_oLaneOffsets
ArrayList<LaneOffset> cc.geosrv.xodr.rdmk.Road.m_oLaneOffsets = new ArrayList() package
Definition at line 30 of file Road.java.
Referenced by cc.geosrv.xodr.rdmk.Arc.addPoints(), cc.geosrv.xodr.rdmk.Line.addPoints(), cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.startElement().
RDMKCOMP
Comparator<int[]> cc.geosrv.xodr.rdmk.Road.RDMKCOMP static private
Initial value:
= (int[] n1, int[] n2) ->
    {
        int nRet = Integer.compare(n1[2], n2[2]);
        if (nRet == 0)
            nRet = Integer.compare(n1[1], n2[1]);
        return nRet;
    }
Definition at line 32 of file Road.java.
Referenced by cc.geosrv.xodr.rdmk.Road.getRdMkCtrlLineArcs().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/rdmk/Road.java