Carma-cloud: cc.rsu.RSUService Class Reference
cc.rsu.RSUService Class Reference
Public Member Functions
RSUService ()
Static Public Member Functions
static ArrayList< RSUBoundingbox > RegisteringRSU (StringBuilder sReq, ArrayList< RSUBoundingbox > existingRsus, double boundingBoxRadius)
static JSONArray serializeRSUList (ArrayList< RSUBoundingbox > rsuList)
static JSONArray serializeBSMList (ArrayList< BSMRequest > bsmReqList)
Static Protected Attributes
static final Logger LOGGER = LogManager.getRootLogger()
Detailed Description
Definition at line 13 of file RSUService.java.
Constructor & Destructor Documentation
RSUService()
cc.rsu.RSUService.RSUService () inline
Definition at line 16 of file RSUService.java.
{
        super();
    }
Member Function Documentation
RegisteringRSU()
static ArrayList< RSUBoundingbox > cc.rsu.RSUService.RegisteringRSU (StringBuilder sReq, ArrayList< RSUBoundingbox > existingRsus, double boundingBoxRadius) inline static
Parameters
sReq New RSU request sent by v2xhub
existingRsus The list of existing RSU locations and their bounding boxes
boundingBoxRadius in meter
Returns
The updated list of RSU locations
Definition at line 28 of file RSUService.java.
{
        RSULocationParser parser = new RSULocationParser();
        RSULocation newRSULoc = parser
                .parseRequest(new ByteArrayInputStream(sReq.toString().getBytes(StandardCharsets.UTF_8)));
        if (newRSULoc != null) {
            if (existingRsus == null) {
                existingRsus = new ArrayList<RSUBoundingbox>();
            } else {
                // check if the new RSU is already registered. If yes, replace existing RSU with
                // new request RSU. Each RSU is connected to one v2xhub which identified v2xhub
                // port
                for (int i = 0; i < existingRsus.size(); i++) {
                    if (existingRsus.get(i).getCenterLoc().v2xhub_port.equals(newRSULoc.v2xhub_port)) {
                        existingRsus.remove(i);
                    }
                }
            }
            // Update RSU register timestamp
            newRSULoc.last_update_at = Instant.now();
            RSUBoundingbox newRSUBoundingBox = new RSUBoundingbox(newRSULoc, boundingBoxRadius);
            existingRsus.add(newRSUBoundingBox);
        } else {
            LOGGER.debug("Cannot parse new RSU Register request.");
        }
        return existingRsus;
    }
References cc.rsu.RSUService.LOGGER, cc.rsu.RSULocationParser.parseRequest(), and cc.rsu.RSULocation.v2xhub_port.
Referenced by cc.ws.RSUServlet.registerRSU().
serializeBSMList()
static JSONArray cc.rsu.RSUService.serializeBSMList (ArrayList< BSMRequest > bsmReqList) inline static
Parameters
bsmReqList An array list of BSMRequest object
Returns
Serialized JSONArray that contains the list of BSM Request
Definition at line 84 of file RSUService.java.
{
        JSONArray rsuArr = new JSONArray();
        if (bsmReqList != null) {
            for (BSMRequest item : bsmReqList) {
                JSONObject rsuJson = new JSONObject();
                rsuJson.put("id", item.getId());
                JSONArray routeArr = new JSONArray();
                for (Position p : item.getRoute()) {
                    JSONArray pointArr = new JSONArray();
                    pointArr.put(p.getLatitude());
                    pointArr.put(p.getlongitude());
                    routeArr.put(pointArr);
                }
                rsuJson.put("route", routeArr);
                rsuJson.put("last_update_at", item.getLast_update_at());
                rsuArr.put(rsuJson);
            }
        }
        return rsuArr;
    }
Referenced by cc.ws.RSUServlet.listBSMReq().
serializeRSUList()
static JSONArray cc.rsu.RSUService.serializeRSUList (ArrayList< RSUBoundingbox > rsuList) inline static
Parameters
rsuList An array list of RSUBoundingbox object
Returns
Serialized JSONArray that contains the list of RSUs
Definition at line 63 of file RSUService.java.
{
        JSONArray rsuArr = new JSONArray();
        if (rsuList != null) {
            for (RSUBoundingbox item : rsuList) {
                JSONObject rsuJson = new JSONObject();
                rsuJson.put("id", item.getCenterLoc().id);
                rsuJson.put("latitude", item.getCenterLoc().latitude);
                rsuJson.put("longitude", item.getCenterLoc().longitude);
                rsuJson.put("v2xhub_port", item.getCenterLoc().v2xhub_port);
                rsuJson.put("last_update_at", item.getCenterLoc().last_update_at);
                rsuJson.put("bounding_box_coordinates", item.getBoundingBoxLatLngCoordinates());
                rsuArr.put(rsuJson);
            }
        }
        return rsuArr;
    }
Referenced by cc.ws.RSUServlet.doDelete(), and cc.ws.RSUServlet.listRSU().
Member Data Documentation
LOGGER
final Logger cc.rsu.RSUService.LOGGER = LogManager.getRootLogger() static protected
Definition at line 14 of file RSUService.java.
Referenced by cc.rsu.RSUService.RegisteringRSU().
The documentation for this class was generated from the following file:
src/cc/rsu/RSUService.java