Carma-cloud: cc.util.Text Class Reference
cc.util.Text Class Reference abstract
Static Public Member Functions
static void removeCtrlChars (StringBuilder sBuffer)
static void removeWhitespace (StringBuilder sBuffer)
static long parseLong (CharSequence iCharSeq)
static long parseLong (CharSequence iCharSeq, int nPos, int nEndPos) throws NumberFormatException
static int parseInt (CharSequence iCharSeq)
static int parseInt (CharSequence iCharSeq, int nPos, int nEndPos) throws NumberFormatException
static double parseDouble (CharSequence iCharSeq, int nPos, int nEndPos) throws IndexOutOfBoundsException, NumberFormatException
static double parseDouble (CharSequence iCharSeq)
static int compare (CharSequence iSeqL, CharSequence iSeqR)
static int compareIgnoreCase (CharSequence iSeqL, CharSequence iSeqR)
static boolean startsWith (CharSequence iSource, CharSequence iPrefix)
static boolean endsWith (CharSequence iSource, CharSequence iSuffix)
static String toHexString (byte[] yBytes)
static void toHexString (byte[] yBytes, StringBuilder sBuf)
static String toHexString (byte[] yBytes, int nOffset, int nLength)
static void toHexString (byte[] yBytes, int nOffset, int nLength, StringBuilder sBuf)
static byte[] fromHexString (StringBuilder sBuf)
static void replaceAll (StringBuilder sBuffer, String sSearch, String sReplace)
static int getBytes (byte[] yBuffer, CharSequence iCharSeq)
static String truncate (String sValue, int nLength)
static String getUUID ()
Static Public Attributes
static final Base64.Encoder B64ENC = Base64.getUrlEncoder().withoutPadding()
static final Comparator< CharSequence > CHAR_SEQ_COMP = (CharSequence o1, CharSequence o2) -> compare(o1, o2)
Private Member Functions
Text ()
Static Private Attributes
static final char[] HEX_CHARS
static final int DIGIT_OFFSET = 48
static final int MIN_EXPONENT = -323
static final int MAX_EXPONENT = 308
static final int INIT_CHAR = 0
static final int DECIMAL = 1
static final int FRACTION = 2
static final int EXPONENT = 3
static final int PARSE_END = 4
static final String POS_INF = "\u221E"
static final String NEG_INF = "-\u221E"
static final String POS_INFINITY = "Infinity"
static final String NEG_INFINITY = "-Infinity"
static final String NAN = "NaN"
static final ByteBuffer UUID_BUFFER = ByteBuffer.allocate(16)
Detailed Description
Provides methods to parse strings to extract numerical values. Also contains methods to format and compare character sequences.
Definition at line 13 of file Text.java.
Constructor & Destructor Documentation
Text()
cc.util.Text.Text () inline private
Default Constructor
Creates new instances of Text
Definition at line 96 of file Text.java.
        {
    }
Member Function Documentation
compare()
static int cc.util.Text.compare (CharSequence iSeqL, CharSequence iSeqR) inline static
Lexicographically compare two character sequences. Using the character sequence interface enables the mixing of comparisons between String, StringBuffer, and StringBuilder objects. The character values at each index of the sequences is compared up to the minimum number of available characters. The sequence lengths determine the comparison when the contents otherwise appear to be equal.
Parameters
iSeqL the first character sequence to be compared
iSeqR the second character sequence to be compared
Returns
a negative integer, zero, or a positive integer as the first argument is less than, equal to, or greater than the second
Definition at line 444 of file Text.java.
{
        int nCompare = 0;
        int nIndex = -1;
        int nLimit = Math.min(iSeqL.length(), iSeqR.length());
        while (nCompare == 0 && ++nIndex < nLimit)
            nCompare = (iSeqL.charAt(nIndex) - iSeqR.charAt(nIndex));
        if (nCompare == 0)
            nCompare = (iSeqL.length() - iSeqR.length());
        return nCompare;
    }
Referenced by cc.ws.Handler.doPost(), cc.ws.UserMgr.doPost(), and cc.util.Text.parseDouble().
compareIgnoreCase()
static int cc.util.Text.compareIgnoreCase (CharSequence iSeqL, CharSequence iSeqR) inline static
Lexicographically compare two character sequences. Comparison is performed without regard to differing character case.
Parameters
iSeqL the first character sequence to be compared
iSeqR the second character sequence to be compared
Returns
a negative integer, zero, or a positive integer as the first argument is less than, equal to, or greater than the second
Definition at line 468 of file Text.java.
{
        int nCompare = 0;
        int nIndex = -1;
        int nLimit = Math.min(iSeqL.length(), iSeqR.length());
        while (nCompare == 0 && ++nIndex < nLimit)
            nCompare =
                    (
                            Character.toLowerCase(iSeqL.charAt(nIndex)) -
                                    Character.toLowerCase(iSeqR.charAt(nIndex))
                    );
        if (nCompare == 0)
            nCompare = (iSeqL.length() - iSeqR.length());
        return nCompare;
    }
endsWith()
static boolean cc.util.Text.endsWith (CharSequence iSource, CharSequence iSuffix) inline static
Tests if the source character sequence ends with the suffix character sequence.
Parameters
iSource the character sequence to check
iSuffix the search character sequence
Returns
true if the characters at the end of the source match the characters in the suffix. false otherwise.
Definition at line 521 of file Text.java.
{
        int nIndex = iSuffix.length();
        int nSrcIndex = iSource.length();
        // the source cannot end with a pattern with more characters
        if (nIndex > nSrcIndex)
            return false;
        // compare each characters starting at the end of the sequence
        boolean bMatch = true;
        while (bMatch && nIndex-- > 0)
            bMatch = (iSource.charAt(--nSrcIndex) == iSuffix.charAt(nIndex));
        return bMatch;
    }
fromHexString()
static byte[] cc.util.Text.fromHexString (StringBuilder sBuf) inline static
Converts a hexadecimal sequence into a byte array
Parameters
sBuf String buffer holding hexadecimal characters.
Returns
A byte array containing the interpreted bytes.
Definition at line 603 of file Text.java.
        {
            if (sBuf == null || sBuf.length() == 0)
                return null;
            if (sBuf.length() % 2 != 0)
                sBuf.append("0");
            byte[] yBytes = new byte[sBuf.length() / 2];
            for (int nIndex = 0; nIndex < yBytes.length; nIndex++)
            {
                int nPos = nIndex * 2;
                yBytes[nIndex] = (byte)((Character.digit(sBuf.charAt(nPos), 16) << 4) +
                    Character.digit(sBuf.charAt(nPos + 1), 16));
            }
            return yBytes;
    }
Referenced by cc.ws.User.User().
getBytes()
static int cc.util.Text.getBytes (byte[] yBuffer, CharSequence iCharSeq) inline static
Copies the contents of a character sequence into the provided byte buffer. No locale translation is performed. This is mostly useful for UTF-8 and ASCII encoded strings.
Parameters
yBuffer The byte buffer where characters are copied.
iCharSeq The sequence of characters to convert to bytes.
Returns
The number of bytes copied into the buffer.
Definition at line 650 of file Text.java.
{
        // determine the maximum the available capacity
        int nLength = iCharSeq.length();
        if (nLength > yBuffer.length)
            nLength = yBuffer.length;
        for (int nIndex = 0; nIndex < nLength; nIndex++)
            yBuffer[nIndex] = (byte) iCharSeq.charAt(nIndex);
        return nLength;
    }
getUUID()
static String cc.util.Text.getUUID () inline static
Definition at line 679 of file Text.java.
    {
        UUID oUuid = UUID.randomUUID();
        synchronized(UUID_BUFFER) // shared byte buffer
        {
            UUID_BUFFER.clear();
            UUID_BUFFER.putLong(oUuid.getMostSignificantBits());
            UUID_BUFFER.putLong(oUuid.getLeastSignificantBits());
            return B64ENC.encodeToString(UUID_BUFFER.array());
        }
    }
References cc.util.Text.B64ENC, and cc.util.Text.UUID_BUFFER.
Referenced by cc.ws.EventMgr.doSave(), and cc.ws.RopMgr.doSave().
parseDouble() [1/2]
static double cc.util.Text.parseDouble (CharSequence iCharSeq) inline static
Converts the character sequence into a double value.
Parameters
iCharSeq a set of characters to be converted into a double value
Returns
the converted double value.
Definition at line 310 of file Text.java.
{
        // first test for expected string names
        if (compare(iCharSeq, POS_INF) == 0 ||
                compare(iCharSeq, POS_INFINITY) == 0)
            return Double.POSITIVE_INFINITY;
        if (compare(iCharSeq, NEG_INF) == 0 ||
                compare(iCharSeq, NEG_INFINITY) == 0)
            return Double.NEGATIVE_INFINITY;
        if (compare(iCharSeq, NAN) == 0)
            return Double.NaN;
        int nExponent = 0;
        double dSign = 1.0;
        double dValue = 0.0;
        double dMultiplier = 0.1;
        double dFraction = 0.0;
        // valid characters for a double are -, +, ., digits, E, and e
        int nIndex = 0;
        int nState = INIT_CHAR;
        while (nIndex < iCharSeq.length() && nState != PARSE_END) {
            char cDigit = iCharSeq.charAt(nIndex++);
            switch (nState) {
                // the digits test is first since it is the most likely
                // parseInt cannot be used due to potential leading zeros
                // in the decimal and fractional parts, i.e. -0.00763
                case DECIMAL: {
                    if (Character.isDigit(cDigit)) {
                        // shift any existing value
                        dValue *= 10.0;
                        dValue += (cDigit - DIGIT_OFFSET);
                    } else {
                        // switch to other states for the double interpretation
                        switch (cDigit) {
                            case '.':
                                nState = FRACTION;
                                break;
                            case 'e':
                            case 'E':
                                nState = EXPONENT;
                                break;
                            default:
                                nState = PARSE_END;
                                break;
                        }
                    }
                }
                break;
                case FRACTION: {
                    if (Character.isDigit(cDigit)) {
                        dFraction += (cDigit - DIGIT_OFFSET) * dMultiplier;
                        dMultiplier *= 0.1;
                    } else if (cDigit == 'e' || cDigit == 'E')
                        nState = EXPONENT;
                    else
                        nState = PARSE_END;
                }
                break;
                // the exponent state is able to use the parseInt method
                // as any fractional exponent will be ignored
                case EXPONENT: {
                    nExponent = parseInt(iCharSeq, --nIndex, iCharSeq.length());
                    nState = PARSE_END;
                }
                break;
                // the initial character test is only performed once
                case INIT_CHAR: {
                    switch (cDigit) {
                        case '-': {
                            dSign = -1.0;
                            nState = DECIMAL;
                        }
                        break;
                        case '+': {
                            dSign = 1.0;
                            nState = DECIMAL;
                        }
                        break;
                        case '.':
                            nState = FRACTION;
                            break;
                        default: {
                            if (Character.isDigit(cDigit)) {
                                // back up one character to test for digits
                                --nIndex;
                                nState = DECIMAL;
                            } else
                                nState = PARSE_END;
                        }
                    }
                }
            }
        }
        // only generate an exponent when necessary
        double dExponent = 1.0;
        if (nExponent != 0) {
            // check the limits of the exponent
            if (nExponent < MIN_EXPONENT)
                nExponent = MIN_EXPONENT;
            if (nExponent > MAX_EXPONENT)
                nExponent = MAX_EXPONENT;
            dExponent = Math.pow(10.0, (double) nExponent);
        }
        return (dSign * (dValue + dFraction) * dExponent);
    }
References cc.util.Text.compare(), cc.util.Text.DECIMAL, cc.util.Text.DIGIT_OFFSET, cc.util.Text.EXPONENT, cc.util.Text.FRACTION, cc.util.Text.INIT_CHAR, cc.util.Text.MAX_EXPONENT, cc.util.Text.MIN_EXPONENT, cc.util.Text.NAN, cc.util.Text.NEG_INF, cc.util.Text.NEG_INFINITY, cc.util.Text.PARSE_END, cc.util.Text.parseInt(), cc.util.Text.POS_INF, and cc.util.Text.POS_INFINITY.
parseDouble() [2/2]
static double cc.util.Text.parseDouble (CharSequence iCharSeq, int nPos, int nEndPos) throws IndexOutOfBoundsException, NumberFormatException inline static
Definition at line 262 of file Text.java.
    {
        boolean bNeg = (iCharSeq.charAt(nPos) == '-');
        if (bNeg) // test for sign character
            ++nPos;
        double dVal = 0.0;
        while (nPos < nEndPos && iCharSeq.charAt(nPos) != '.')
        {
            int nDigit = iCharSeq.charAt(nPos++) - DIGIT_OFFSET; // map char value
            if (nDigit < 0 || nDigit > 9) // check for non-numeric chars
                throw new NumberFormatException();
            dVal *= 10.0; // shift existing value
            dVal += nDigit; // add new digit value
        }
        if (nPos < nEndPos && iCharSeq.charAt(nPos++) == '.') // fractional part check
        {
            double dDiv = 1.0;
            double dFrac = 0.0;
            while (nPos < nEndPos)
            {
                int nDigit = iCharSeq.charAt(nPos++) - DIGIT_OFFSET; // map char value
                if (nDigit < 0 || nDigit > 9) // check for non-numeric chars
                    throw new NumberFormatException();
                dDiv *= 10.0; // track decimal places
                dFrac *= 10.0; // shift existing value
                dFrac += nDigit; // add new digit value
            }
            dVal += dFrac / dDiv; // expensive division operator
        }
        if (bNeg)
            return -dVal;
        return dVal;
    }
References cc.util.Text.DIGIT_OFFSET.
Referenced by cc.util.CsvReader.parseDouble().
parseInt() [1/2]
static int cc.util.Text.parseInt (CharSequence iCharSeq) inline static
Wraps Text#parseInt(java.lang.CharSequence, int, int) to convert the sequence from beginning to end.
Parameters
iCharSeq a set of characters to be converted into an integer value
Returns
the decimal integer value represented by the character sequence.
Definition at line 205 of file Text.java.
{
        return parseInt(iCharSeq, 0, iCharSeq.length());
    }
References cc.util.Text.parseInt().
Referenced by cc.ws.SessMgr.init(), cc.util.Text.parseDouble(), cc.util.Text.parseInt(), and cc.util.CsvReader.parseInt().
parseInt() [2/2]
static int cc.util.Text.parseInt (CharSequence iCharSeq, int nPos, int nEndPos) throws NumberFormatException inline static
Parses the character sequence argument as a signed decimal integer. The characters in the sequence must all be decimal digits, except that the first character may be an ASCII minus sign '-' ('\u002D') to indicate a negative value.
Parameters
iCharSeq a set of characters to be converted into an integer value
nPos the position in the sequence where conversion begins
nEndPos the sequence position where conversion stops (exclusive)
Returns
the decimal integer value represented by the character sequence
Exceptions
NumberFormatException if the character sequence does not contain characters that can be converted to a decimal integer
Definition at line 223 of file Text.java.
{
        int nSign = 1;
        int nValue = 0;
        // valid characters for an integer are -, +, and digits
        int nState = INIT_CHAR;
        while (nPos < nEndPos && nState != PARSE_END) {
            char cDigit = iCharSeq.charAt(nPos++);
            switch (nState) {
                // the digits test is first since it is the most likely
                case DECIMAL: {
                    if (Character.isDigit(cDigit)) {
                        // shift any existing value
                        nValue *= 10;
                        nValue += (cDigit - DIGIT_OFFSET);
                    } else
                        throw new NumberFormatException("Illegal character '" +
                                iCharSeq.charAt(--nPos) + "' for integer " +
                                "expression at position " + nPos + ".");
                }
                break;
                // the initial character test is only performed once
                case INIT_CHAR: {
                    nState = DECIMAL;
                    if (cDigit == '-')
                        nSign = -1;
                    else
                        // back up one character to test for digits
                        --nPos;
                }
            }
        }
        return (nSign * nValue);
    }
References cc.util.Text.DECIMAL, cc.util.Text.DIGIT_OFFSET, cc.util.Text.INIT_CHAR, and cc.util.Text.PARSE_END.
parseLong() [1/2]
static long cc.util.Text.parseLong (CharSequence iCharSeq) inline static
Wraps Text#parseInt(java.lang.CharSequence, int, int) to convert the sequence from beginning to end.
Parameters
iCharSeq a set of characters to be converted into a long value
Returns
the decimal long value represented by the character sequence.
Definition at line 152 of file Text.java.
{
        return parseLong(iCharSeq, 0, iCharSeq.length());
    }
References cc.util.Text.parseLong().
Referenced by cc.util.Text.parseLong(), and cc.util.CsvReader.parseLong().
parseLong() [2/2]
static long cc.util.Text.parseLong (CharSequence iCharSeq, int nPos, int nEndPos) throws NumberFormatException inline static
Parses the character sequence argument as a signed decimal long. The characters in the sequence must all be decimal digits, except that the first character may be an ASCII minus sign '-' ('\u002D') to indicate a negative value.
Parameters
iCharSeq a set of characters to be converted into an integer value
nPos the position in the sequence where conversion begins
nEndPos the sequence position where conversion stops (exclusive)
Returns
the decimal long value represented by the character sequence
Exceptions
NumberFormatException if the character sequence does not contain characters that can be converted to a decimal long
Definition at line 170 of file Text.java.
{
        // test for the sign character
        boolean bNegative = (iCharSeq.charAt(nPos) == '-');
        if (bNegative)
            ++nPos;
        int nDigit = 0;
        long lValue = 0L;
        while (nPos < nEndPos) {
            // map the character value to the numeric value
            nDigit = iCharSeq.charAt(nPos++) - DIGIT_OFFSET;
            // test for characters that are not numbers
            if (nDigit < 0 || nDigit > 9)
                throw new NumberFormatException();
            // shift the existing value and add the new digit value
            lValue *= 10L;
            lValue += nDigit;
        }
        if (bNegative)
            return -lValue;
        return lValue;
    }
References cc.util.Text.DIGIT_OFFSET.
removeCtrlChars()
static void cc.util.Text.removeCtrlChars (StringBuilder sBuffer) inline static
Removes control characters from the buffer.
Parameters
sBuffer the string to remove control characters from.
Definition at line 106 of file Text.java.
        {
            int nLen = sBuffer.length();
            while (nLen-- > 0)
            {
                if (Character.isISOControl(sBuffer.charAt(nLen)))
                    sBuffer.deleteCharAt(nLen);
            }
        }
Referenced by cc.rsm.RsmCollect.xmlFile().
removeWhitespace()
static void cc.util.Text.removeWhitespace (StringBuilder sBuffer) inline static
Removes whitespace from the provided string builder.
Parameters
sBuffer the string to remove whitespace from.
Definition at line 122 of file Text.java.
{
        // only remove whitespace if there is something to scan
        if (sBuffer.length() > 0) {
            // reverse iterate to the first non-whitespace character
            int nIndex = sBuffer.length();
            while (nIndex-- > 0 &&
                    Character.isWhitespace(sBuffer.charAt(nIndex))) ;
            // remove the trailing whitespace segment
            sBuffer.delete(++nIndex, sBuffer.length());
            // forward iterate to the first non-whitespace character
            nIndex = 0;
            while (nIndex < sBuffer.length() &&
                    Character.isWhitespace(sBuffer.charAt(nIndex++))) ;
            // remove the leading whitespace segment
            if (nIndex > 0)
                sBuffer.delete(0, --nIndex);
        }
    }
Referenced by cc.ws.RopMgr.doSave(), cc.geosrv.xodr.geo.XodrGeoParser.endCDATA(), cc.geosrv.xodr.pvmt.XodrPvmtParser.endCDATA(), and cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endCDATA().
replaceAll()
static void cc.util.Text.replaceAll (StringBuilder sBuffer, String sSearch, String sReplace) inline static
Replaces all occurrences of the search string within the supplied buffer with the replacement string.
Parameters
sBuffer StringBuilder buffer containing text to be searched.
sSearch Search string to find in the buffer.
sReplace Replacement string to substitute for the search string.
Definition at line 630 of file Text.java.
{
        int nIndex = 0;
        while ((nIndex = sBuffer.indexOf(sSearch, nIndex)) >= 0) {
            sBuffer.replace(nIndex, nIndex + sSearch.length(), sReplace);
            // move start point after the replacement to enable recursion
            nIndex += sReplace.length();
        }
    }
startsWith()
static boolean cc.util.Text.startsWith (CharSequence iSource, CharSequence iPrefix) inline static
Tests if the source character sequence begins with the prefix character sequence.
Parameters
iSource the character sequence to check
iPrefix the search character sequence
Returns
true if the initial source characters match the characters in the prefix. false otherwise.
Definition at line 496 of file Text.java.
{
        int nIndex = iPrefix.length();
        // the source cannot start with a pattern with more characters
        if (nIndex > iSource.length())
            return false;
        // compare each characters starting at the end of the sequence
        boolean bMatch = true;
        while (bMatch && nIndex-- > 0)
            bMatch = (iSource.charAt(nIndex) == iPrefix.charAt(nIndex));
        return bMatch;
    }
toHexString() [1/4]
static String cc.util.Text.toHexString (byte[] yBytes) inline static
Converts a byte array into a hexadecimal string
Parameters
yBytes Byte array containing data to be converted.
Returns
Hexadecimal string that represents the supplied byte data.
Definition at line 544 of file Text.java.
        {
            return toHexString(yBytes, 0, yBytes.length);
    }
References cc.util.Text.toHexString().
Referenced by cc.ctrl.TrafCtrlEnums.getCtrlValString(), cc.ctrl.TrafCtrl.getId(), cc.ws.UserMgr.getSecurePassword(), cc.ws.SessMgr.getSession(), cc.ctrl.TrafCtrl.getXml(), cc.ws.UserMgr.main(), cc.ws.CtrlTiles.splitLineArcs(), cc.util.Text.toHexString(), cc.ctrl.TrafCtrl.write(), and cc.ctrl.TrafCtrl.writeJson().
toHexString() [2/4]
static String cc.util.Text.toHexString (byte[] yBytes, int nOffset, int nLength) inline static
Converts a byte array into a hexadecimal string
Parameters
yBytes Byte array containing data to be converted.
nOffset The position within the array to begin converting.
nLength The number of bytes to be converted.
Returns
Hexadecimal string that represents the supplied byte data.
Definition at line 570 of file Text.java.
        {
            StringBuilder sBuf = new StringBuilder();
            toHexString(yBytes, nOffset, nLength, sBuf);
            return sBuf.toString();
        }
References cc.util.Text.toHexString().
toHexString() [3/4]
static void cc.util.Text.toHexString (byte[] yBytes, int nOffset, int nLength, StringBuilder sBuf) inline static
Converts a byte array into a hexadecimal string
Parameters
yBytes Byte array containing data to be converted.
nOffset The position within the array to begin converting.
nLength The number of bytes to be converted.
sBuf String buffer that holds the converted characters.
Definition at line 586 of file Text.java.
        {
            for (; nOffset < nLength; nOffset++)
            {
                sBuf.append(HEX_CHARS[((yBytes[nOffset] & 0xf0) >> 4)]);
                sBuf.append(HEX_CHARS[(yBytes[nOffset] & 0x0f)]);
            }
    }
References cc.util.Text.HEX_CHARS.
toHexString() [4/4]
static void cc.util.Text.toHexString (byte[] yBytes, StringBuilder sBuf) inline static
Converts a byte array into a hexadecimal string
Parameters
yBytes Byte array containing data to be converted.
sBuf String buffer that holds the converted characters.
Definition at line 556 of file Text.java.
        {
            toHexString(yBytes, 0, yBytes.length, sBuf);
    }
References cc.util.Text.toHexString().
truncate()
static String cc.util.Text.truncate (String sValue, int nLength) inline static
Truncates the passed string value if it is longer than the passed length, or returns the original value if it isn't.
Parameters
sValue The value to truncate
nLength The maximum length of the truncated string.
Returns
The truncated string
Definition at line 671 of file Text.java.
{
        if(sValue == null || sValue.length() <= nLength)
          return sValue;
        else
          return sValue.substring(0, nLength);
    }
Referenced by cc.ws.CtrlTiles.addControl(), cc.ctrl.TrafCtrl.getXml(), and cc.ws.CtrlTiles.saveEdit().
Member Data Documentation
B64ENC
final Base64.Encoder cc.util.Text.B64ENC = Base64.getUrlEncoder().withoutPadding() static
Convenience Base64 URL encoder without padding
Definition at line 83 of file Text.java.
Referenced by cc.ws.GeoSvc.SimWay.SimWay(), cc.ws.GeoSvc.Way.Way(), and cc.util.Text.getUUID().
CHAR_SEQ_COMP
final Comparator<CharSequence> cc.util.Text.CHAR_SEQ_COMP = (CharSequence o1, CharSequence o2) -> compare(o1, o2) static
Definition at line 87 of file Text.java.
DECIMAL
final int cc.util.Text.DECIMAL = 1 static private
State Constant marking decimal.
Definition at line 43 of file Text.java.
Referenced by cc.util.Text.parseDouble(), and cc.util.Text.parseInt().
DIGIT_OFFSET
final int cc.util.Text.DIGIT_OFFSET = 48 static private
Digit offset.
Definition at line 26 of file Text.java.
Referenced by cc.util.Text.parseDouble(), cc.util.Text.parseInt(), and cc.util.Text.parseLong().
EXPONENT
final int cc.util.Text.EXPONENT = 3 static private
State Constant marking exponents.
Definition at line 51 of file Text.java.
Referenced by cc.util.Text.parseDouble().
FRACTION
final int cc.util.Text.FRACTION = 2 static private
State Constant marking fraction.
Definition at line 47 of file Text.java.
Referenced by cc.util.Text.parseDouble().
HEX_CHARS
final char [] cc.util.Text.HEX_CHARS static private
Initial value:
=
            {
                    '0', '1', '2', '3', '4', '5', '6', '7',
                    '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'
            }
Lower-case character set used to encode a byte array as a hex string.
Definition at line 18 of file Text.java.
Referenced by cc.util.Text.toHexString().
INIT_CHAR
final int cc.util.Text.INIT_CHAR = 0 static private
State Constant marking initial character.
Definition at line 39 of file Text.java.
Referenced by cc.util.Text.parseDouble(), and cc.util.Text.parseInt().
MAX_EXPONENT
final int cc.util.Text.MAX_EXPONENT = 308 static private
Maximum exponent limit.
Definition at line 34 of file Text.java.
Referenced by cc.util.Text.parseDouble().
MIN_EXPONENT
final int cc.util.Text.MIN_EXPONENT = -323 static private
Minimum exponent limit.
Definition at line 30 of file Text.java.
Referenced by cc.util.Text.parseDouble().
NAN
final String cc.util.Text.NAN = "NaN" static private
Not a number - string name constant used to convert strings to doubles
Definition at line 79 of file Text.java.
Referenced by cc.util.Text.parseDouble().
NEG_INF
final String cc.util.Text.NEG_INF = "-\u221E" static private
Negative infinity - unicode constant used to convert strings to doubles
Definition at line 64 of file Text.java.
Referenced by cc.util.Text.parseDouble().
NEG_INFINITY
final String cc.util.Text.NEG_INFINITY = "-Infinity" static private
Negative infinity - string name constant used to convert strings to doubles
Definition at line 74 of file Text.java.
Referenced by cc.util.Text.parseDouble().
PARSE_END
final int cc.util.Text.PARSE_END = 4 static private
State Constant marking end of string.
Definition at line 55 of file Text.java.
Referenced by cc.util.Text.parseDouble(), and cc.util.Text.parseInt().
POS_INF
final String cc.util.Text.POS_INF = "\u221E" static private
Positive infinity - unicode constant used to convert strings to doubles
Definition at line 60 of file Text.java.
Referenced by cc.util.Text.parseDouble().
POS_INFINITY
final String cc.util.Text.POS_INFINITY = "Infinity" static private
Positive infinity - string name constant used to convert strings to doubles
Definition at line 69 of file Text.java.
Referenced by cc.util.Text.parseDouble().
UUID_BUFFER
final ByteBuffer cc.util.Text.UUID_BUFFER = ByteBuffer.allocate(16) static private
Definition at line 85 of file Text.java.
Referenced by cc.util.Text.getUUID().
The documentation for this class was generated from the following file:
src/cc/util/Text.java