Carma-cloud: cc.rsu.RSULocationParser Class Reference
cc.rsu.RSULocationParser Class Reference
Public Member Functions
RSULocationParser ()
void characters (char[] cBuf, int nPos, int nLen)
void startElement (String sUri, String sLocalName, String sQname, Attributes iAtt)
void endElement (String sUri, String sLocalName, String sQname) throws SAXException
RSULocation parseRequest (InputStream oIn)
Protected Attributes
RSULocation rsu_loc
StringBuilder m_sbuf = new StringBuilder()
double HUNDREDTH_MICRO_DEG_PER_DEG = 100000000.0
Detailed Description
Parse RSU location request in XML format and populate RSULocation object
Definition at line 18 of file RSULocationParser.java.
Constructor & Destructor Documentation
RSULocationParser()
cc.rsu.RSULocationParser.RSULocationParser () inline
Definition at line 23 of file RSULocationParser.java.
{
        super();
    }
Member Function Documentation
characters()
void cc.rsu.RSULocationParser.characters (char[] cBuf, int nPos, int nLen) inline
Definition at line 28 of file RSULocationParser.java.
{
        m_sbuf.setLength(0);
        m_sbuf.append(cBuf, nPos, nLen);
    }
References cc.rsu.RSULocationParser.m_sbuf.
endElement()
void cc.rsu.RSULocationParser.endElement (String sUri, String sLocalName, String sQname) throws SAXException inline
Definition at line 52 of file RSULocationParser.java.
{
        switch (sQname.toLowerCase()) {
            case "rsulocationrequest":
                break;
            case "id":
                rsu_loc.id = m_sbuf.toString();
                break;
            case "latitude":
                rsu_loc.latitude = (Long.parseLong(m_sbuf.toString()) / HUNDREDTH_MICRO_DEG_PER_DEG);
                break;
            case "longitude":
                rsu_loc.longitude = (Long.parseLong(m_sbuf.toString()) / HUNDREDTH_MICRO_DEG_PER_DEG);
                break;
            case "v2xhubport":
                rsu_loc.v2xhub_port = m_sbuf.toString();
                break;
            default:
                break;
        }
    }
References cc.rsu.RSULocationParser.HUNDREDTH_MICRO_DEG_PER_DEG, and cc.rsu.RSULocationParser.m_sbuf.
parseRequest()
RSULocation cc.rsu.RSULocationParser.parseRequest (InputStream oIn) inline
Definition at line 73 of file RSULocationParser.java.
{
        try {
            rsu_loc = new RSULocation();
            XMLReader iXmlReader = SAXParserFactory.newInstance().newSAXParser().getXMLReader();
            iXmlReader.setContentHandler(this);
            iXmlReader.parse(new InputSource(oIn));
            return rsu_loc;
        } catch (SAXException e) {
            e.printStackTrace();
        } catch (ParserConfigurationException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
References cc.rsu.RSULocationParser.rsu_loc.
Referenced by cc.rsu.RSUService.RegisteringRSU().
startElement()
void cc.rsu.RSULocationParser.startElement (String sUri, String sLocalName, String sQname, Attributes iAtt) inline
Definition at line 34 of file RSULocationParser.java.
{
        switch (sQname.toLowerCase()) {
            case "rsulocationrequest":
                break;
            case "id":
                break;
            case "latitude":
                break;
            case "longitude":
                break;
            case "v2xhubport":
                break;
            default:
                break;
        }
    }
Member Data Documentation
HUNDREDTH_MICRO_DEG_PER_DEG
double cc.rsu.RSULocationParser.HUNDREDTH_MICRO_DEG_PER_DEG = 100000000.0 protected
Definition at line 21 of file RSULocationParser.java.
Referenced by cc.rsu.RSULocationParser.endElement().
m_sbuf
StringBuilder cc.rsu.RSULocationParser.m_sbuf = new StringBuilder() protected
Definition at line 20 of file RSULocationParser.java.
Referenced by cc.rsu.RSULocationParser.characters(), and cc.rsu.RSULocationParser.endElement().
rsu_loc
RSULocation cc.rsu.RSULocationParser.rsu_loc protected
Definition at line 19 of file RSULocationParser.java.
Referenced by cc.rsu.RSULocationParser.parseRequest().
The documentation for this class was generated from the following file:
src/cc/rsu/RSULocationParser.java