Carma-cloud: cc.rsu.RSUIdentificationTask Class Reference
cc.rsu.RSUIdentificationTask Class Reference
Public Member Functions
RSUIdentificationTask ()
RSUIdentificationTask (BSMRequest bsmReq, ArrayList< RSUBoundingbox > RSUs)
Void call () throws Exception
Private Attributes
BSMRequest incomingBSMReq = null
ArrayList< RSUBoundingbox > registeredRSUs = null
Static Private Attributes
static final Logger LOGGER = LogManager.getLogger(RSUIdentificationTask.class)
Detailed Description
Process incoming BSM request and determine the emergency response vehicle future path, and identify the RSU along the emergency response vehicle(ERV) future path. Note: The BSM has the route that consist of a series of lat/lon to describe ERV future path
Definition at line 18 of file RSUIdentificationTask.java.
Constructor & Destructor Documentation
RSUIdentificationTask() [1/2]
cc.rsu.RSUIdentificationTask.RSUIdentificationTask () inline
Definition at line 23 of file RSUIdentificationTask.java.
{
    }
RSUIdentificationTask() [2/2]
cc.rsu.RSUIdentificationTask.RSUIdentificationTask (BSMRequest bsmReq, ArrayList< RSUBoundingbox > RSUs) inline
Definition at line 26 of file RSUIdentificationTask.java.
{
        incomingBSMReq = bsmReq;
        registeredRSUs = RSUs;
    }
References cc.rsu.RSUIdentificationTask.incomingBSMReq, and cc.rsu.RSUIdentificationTask.registeredRSUs.
Member Function Documentation
call()
Void cc.rsu.RSUIdentificationTask.call () throws Exception inline
Definition at line 36 of file RSUIdentificationTask.java.
{
        long start_ts = Instant.now().toEpochMilli();
        LOGGER.info("Task to process BSM request: " + incomingBSMReq);
        // Convert geodetic locations to x,y,z
        ArrayList<Point> points = new ArrayList<>();
        GeodesicCartesianConverter converter = new GeodesicCartesianConverter();
        for (Position loc : incomingBSMReq.getRoute()) {
            points.add(converter.geodesic2Cartesian(loc));
        }
        // Calculate bounding boxes with two adjacent points
        ArrayList<BoundingBox> boundingBoxes = new ArrayList<>();
        for (int i = 0; i < points.size() - 1; i++) {
            boundingBoxes.add(new BoundingBox(points.get(i), points.get(i + 1)));
        }
        LOGGER.debug("Generated number of bounding boxes from BSM request: " + boundingBoxes.size());
        // Comparing the bounding boxes from BSM request with register RSU bounding
        // boxes. If an RSU bounding box intersects with any of BSM request bounding
        // boxes, the RSU is along the future path
        //NOTE: For the carma-cloud registered RSUs, it needs additional consideration for those RSUs (RSUs, geofences, etc.) in a certain requested region.
        if (registeredRSUs != null && registeredRSUs.size() > 0) {
            ArrayList<RSUBoundingbox> identifiedRSUs = new ArrayList<>();
            String identifiedRSUNames = "";
            for (RSUBoundingbox rsuBoundingBox : registeredRSUs) {
                BoundingBox bBox = rsuBoundingBox.getBoundingBox();
                for (BoundingBox bsmBoxOther : boundingBoxes) {
                    if (bBox.intersects(bsmBoxOther)) {
                        identifiedRSUs.add(rsuBoundingBox);
                        identifiedRSUNames += rsuBoundingBox.getCenterLoc().id +",";
                        LOGGER.debug("Identified RSU location: " + rsuBoundingBox.getCenterLoc().toString());
                        break;
                    }
                }
            }
            LOGGER.info("FER-14: Identified numbers of RSU: " + identifiedRSUs.size() + "; RSU Names: " + identifiedRSUNames + "; BSM:" + incomingBSMReq.getId());
            // sent BSM hex to the identified RSUs
            ExecutorService singleExector = Executors.newSingleThreadExecutor();
            singleExector.submit(new HTTPClientTask(identifiedRSUs, incomingBSMReq));
            singleExector.shutdown();
        } else {
            LOGGER.info("No RSU is registered!");
        }
        long end_ts = Instant.now().toEpochMilli();
        LOGGER.warn("FER-13-2: TOTAL BSM PROCESS time (ms): " + (end_ts - start_ts) + "; BSM:" + incomingBSMReq.getId());
        return null;
    }
References cc.rsu.GeodesicCartesianConverter.geodesic2Cartesian(), cc.rsu.BSMRequest.getId(), cc.rsu.BSMRequest.getRoute(), cc.rsu.RSUIdentificationTask.incomingBSMReq, cc.rsu.BoundingBox.intersects(), cc.rsu.RSUIdentificationTask.LOGGER, and cc.rsu.RSUIdentificationTask.registeredRSUs.
Member Data Documentation
incomingBSMReq
BSMRequest cc.rsu.RSUIdentificationTask.incomingBSMReq = null private
Definition at line 20 of file RSUIdentificationTask.java.
Referenced by cc.rsu.RSUIdentificationTask.RSUIdentificationTask(), and cc.rsu.RSUIdentificationTask.call().
LOGGER
final Logger cc.rsu.RSUIdentificationTask.LOGGER = LogManager.getLogger(RSUIdentificationTask.class) static private
Definition at line 19 of file RSUIdentificationTask.java.
Referenced by cc.rsu.RSUIdentificationTask.call().
registeredRSUs
ArrayList<RSUBoundingbox> cc.rsu.RSUIdentificationTask.registeredRSUs = null private
Definition at line 21 of file RSUIdentificationTask.java.
Referenced by cc.rsu.RSUIdentificationTask.RSUIdentificationTask(), and cc.rsu.RSUIdentificationTask.call().
The documentation for this class was generated from the following file:
src/cc/rsu/RSUIdentificationTask.java