Carma-cloud: cc.ws.GeoSvc.SimWay Class Reference
cc.ws.GeoSvc.SimWay Class Reference
Package Functions
void update ()
Package Attributes
String m_sId
Way m_oWay
double m_dSpeed
double m_dDist
double m_dLat
double m_dLon
Private Member Functions
SimWay ()
void initWay ()
double getSpeed ()
void setLoc (double dTrgt)
void nextWay (double dTrgt)
Detailed Description
Definition at line 390 of file GeoSvc.java.
Constructor & Destructor Documentation
SimWay()
cc.ws.GeoSvc.SimWay.SimWay () inline private
Definition at line 400 of file GeoSvc.java.
        {
            byte[] yId = new byte[3];
            RNG.nextBytes(yId); // create 4-char base64 random id
            m_sId = Text.B64ENC.encodeToString(yId);
            initWay();
        }
References cc.util.Text.B64ENC, cc.ws.GeoSvc.SimWay.initWay(), cc.ws.GeoSvc.SimWay.m_sId, and cc.ws.GeoSvc.RNG.
Member Function Documentation
getSpeed()
double cc.ws.GeoSvc.SimWay.getSpeed () inline private
Definition at line 441 of file GeoSvc.java.
        {
            String sType = m_oWay.m_sType;
            if (sType.compareTo("motorway") == 0)
                return 30.0; // ~67 mph
            else if (sType.compareTo("primary") == 0)
                return 25.0; // ~56 mph
            else if (sType.compareTo("secondary") == 0)
                return 21.0; // ~47 mph
            else
                return 13.0; // ~30 mph
        }
References cc.ws.GeoSvc.SimWay.m_oWay, and cc.ws.GeoSvc.Way.m_sType.
Referenced by cc.ws.GeoSvc.SimWay.initWay(), and cc.ws.GeoSvc.SimWay.nextWay().
initWay()
void cc.ws.GeoSvc.SimWay.initWay () inline private
Definition at line 409 of file GeoSvc.java.
        {
            do // may take a while to start
            {
                m_oWay = m_oInitWays.get(RNG.nextInt(m_oInitWays.size()));
            }
            while (m_oWay.m_sType.compareTo("motorway") != 0 &&
                m_oWay.m_sType.compareTo("primary") != 0);
//          Way oNewWay = null;
//          while (oNewWay == null)
//          {
//              for (HashWays oHashWays : m_oHashWays)
//              {
//                  for (Way oWay : oHashWays)
//                  {
//                      if (oWay.m_sId.compareTo("AAAAAALMGiE") == 0)
//                          oNewWay = oWay;
//                  }
//              }
//          }
//          m_oWay = oNewWay;
            setLoc(RNG.nextInt(100) * m_oWay.m_dLens[0] / 100.0); // random location
            double dSpeed = getSpeed();
            if (!m_oWay.m_bOneWay && RNG.nextBoolean())
                    dSpeed = -dSpeed; // random direction of travel
            m_dSpeed = -dSpeed; // negative for testing only
        }
References cc.ws.GeoSvc.SimWay.getSpeed(), cc.ws.GeoSvc.Way.m_bOneWay, cc.ws.GeoSvc.Way.m_dLens, cc.ws.GeoSvc.SimWay.m_dSpeed, cc.ws.GeoSvc.m_oInitWays, cc.ws.GeoSvc.SimWay.m_oWay, cc.ws.GeoSvc.Way.m_sType, cc.ws.GeoSvc.RNG, and cc.ws.GeoSvc.SimWay.setLoc().
Referenced by cc.ws.GeoSvc.SimWay.SimWay(), and cc.ws.GeoSvc.SimWay.nextWay().
nextWay()
void cc.ws.GeoSvc.SimWay.nextWay (double dTrgt) inline private
Definition at line 479 of file GeoSvc.java.
        {
            int nLat;
            int nLon;
            if (dTrgt < 0.0) // traveling opposite of node order
            {
                nLat = m_oWay.m_nPoints[0]; // use first point
                nLon = m_oWay.m_nPoints[1]; // for comparison
            }
            else // traveling in node order
            {
                dTrgt -= m_oWay.m_dLens[0]; // leftover distance for next way
                nLat = m_oWay.m_nPoints[m_oWay.m_nPoints.length - 2]; // use last point
                nLon = m_oWay.m_nPoints[m_oWay.m_nPoints.length - 1]; // for comparison
            }
            int[] nHash = new int[]{Geo.getHash(nLat, nLon)}; // find way search set
            int nIndex = Collections.binarySearch(m_oHashWays, nHash);
            if (nIndex >= 0)
            {
                int nInsert = 0;
                ArrayList<Way> oWays = new ArrayList(); // candidate ways
                for (Way oWay : m_oHashWays.get(nIndex))
                {
                    int[] nPts = oWay.m_nPoints;
                    if (nPts[0] == nLat && nPts[1] == nLon)
                        oWays.add(nInsert++, oWay); // insert first point match at top
                    else if (nPts[nPts.length - 2] == nLat &&
                        nPts[nPts.length - 1] == nLon && !oWay.m_bOneWay)
                        oWays.add(oWay); // add last point match to bottom excluding do-not-enter
                }
                nIndex = oWays.size();
                if (nIndex > 1) // remove current way when possible
                {
                    while (nIndex-- > 0)
                    {
                        if (oWays.get(nIndex) == m_oWay)
{
                            oWays.remove(nIndex);
                            if (nIndex < nInsert) // adjust insert point
                                --nInsert;
                        }
                    }
                }
                if (!oWays.isEmpty()) // at least the current way should exist
                {
                    if (oWays.size() == 1)
                        nIndex = 0; // no random choice possible
                    else
                        nIndex = RNG.nextInt(oWays.size());
                    m_oWay = oWays.get(nIndex);
                    double dSpeed = getSpeed(); // set distance on new way
                    double dLen = m_oWay.m_dLens[0];
                    if (dTrgt < 0.0)
                    {
                        if (nIndex < nInsert) // starting at first point
                            dTrgt = -dTrgt; // need positive distance
                        else // starting at last point subtract distance
{
                            dTrgt = dLen + dTrgt;
                            dSpeed = -dSpeed; // reverse direction
                        }
                    }
                    else
                    {
                        if (nIndex >= nInsert) // starting at last point
{
                            dTrgt = dLen - dTrgt;
                            dSpeed = -dSpeed; // reverse direction
                        }
                    }
                    m_dSpeed = dSpeed; // save way speed
                    if (dTrgt < 0.0 || dTrgt > dLen) // chosen way is too short
                        dTrgt = dLen / 2.0; // just pick the mid-point
                    setLoc(dTrgt); // set position on new way
                    return;
                }
            }
            initWay(); // restart somewhere else
        }
References cc.util.Geo.getHash(), cc.ws.GeoSvc.SimWay.getSpeed(), cc.ws.GeoSvc.SimWay.initWay(), cc.ws.GeoSvc.Way.m_dLens, cc.ws.GeoSvc.SimWay.m_dSpeed, cc.ws.GeoSvc.Way.m_nPoints, cc.ws.GeoSvc.m_oHashWays, cc.ws.GeoSvc.SimWay.m_oWay, cc.ws.GeoSvc.RNG, and cc.ws.GeoSvc.SimWay.setLoc().
Referenced by cc.ws.GeoSvc.SimWay.update().
setLoc()
void cc.ws.GeoSvc.SimWay.setLoc (double dTrgt) inline private
Definition at line 455 of file GeoSvc.java.
        {
            int[] nPts = m_oWay.m_nPoints; // set local references
            double[] dLens = m_oWay.m_dLens;
            int nLen = 1; // index 0 contains total length
            double dDist = 0.0;
            while (dDist <= dTrgt && nLen < dLens.length)
                dDist += dLens[nLen++];
            double dCurrLen = dLens[--nLen]; // reverse extra loop increment
            dDist -= dCurrLen;
            int nPos = nLen * 2;
            double dOff = (dTrgt - dDist) / dCurrLen; // percent along current length
            int nX = nPts[nPos - 1]; // lat lon ordering
            int nY = nPts[nPos - 2];
            m_dLat = Geo.fromIntDeg(nY + (int)Math.round(dOff * (nPts[nPos] - nY)));
            m_dLon = Geo.fromIntDeg(nX + (int)Math.round(dOff * (nPts[nPos + 1] - nX)));
            m_dDist = dTrgt; // current distance matches target
        }
References cc.util.Geo.fromIntDeg(), cc.ws.GeoSvc.SimWay.m_dDist, cc.ws.GeoSvc.SimWay.m_dLat, cc.ws.GeoSvc.Way.m_dLens, cc.ws.GeoSvc.SimWay.m_dLon, cc.ws.GeoSvc.Way.m_nPoints, and cc.ws.GeoSvc.SimWay.m_oWay.
Referenced by cc.ws.GeoSvc.SimWay.initWay(), cc.ws.GeoSvc.SimWay.nextWay(), and cc.ws.GeoSvc.SimWay.update().
update()
void cc.ws.GeoSvc.SimWay.update () inline package
Definition at line 565 of file GeoSvc.java.
        {
            double dTrgt = m_dDist + m_dSpeed;
            if (dTrgt < 0.0 || dTrgt > m_oWay.m_dLens[0])
                nextWay(dTrgt);
            else
                setLoc(dTrgt);
//          if (m_oWay.m_bOneWay && m_dSpeed < 0.0) // last resort error state check
//          { // this will murder the log file
//              System.out.print(m_sId);
//              System.out.print(' ');
//              System.out.print(m_dLat);
//              System.out.print(' ');
//              System.out.print(m_dLon);
//              System.out.print(' ');
//              System.out.println(m_oWay.m_sName);
//          }
        }
References cc.ws.GeoSvc.SimWay.m_dDist, cc.ws.GeoSvc.Way.m_dLens, cc.ws.GeoSvc.SimWay.m_dSpeed, cc.ws.GeoSvc.SimWay.m_oWay, cc.ws.GeoSvc.SimWay.nextWay(), and cc.ws.GeoSvc.SimWay.setLoc().
Member Data Documentation
m_dDist
double cc.ws.GeoSvc.SimWay.m_dDist package
Definition at line 395 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.SimWay.setLoc(), and cc.ws.GeoSvc.SimWay.update().
m_dLat
double cc.ws.GeoSvc.SimWay.m_dLat package
Definition at line 396 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.SimWay.setLoc().
m_dLon
double cc.ws.GeoSvc.SimWay.m_dLon package
Definition at line 397 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.SimWay.setLoc().
m_dSpeed
double cc.ws.GeoSvc.SimWay.m_dSpeed package
Definition at line 394 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.SimWay.initWay(), cc.ws.GeoSvc.SimWay.nextWay(), and cc.ws.GeoSvc.SimWay.update().
m_oWay
Way cc.ws.GeoSvc.SimWay.m_oWay package
Definition at line 393 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.SimWay.getSpeed(), cc.ws.GeoSvc.SimWay.initWay(), cc.ws.GeoSvc.SimWay.nextWay(), cc.ws.GeoSvc.SimWay.setLoc(), and cc.ws.GeoSvc.SimWay.update().
m_sId
String cc.ws.GeoSvc.SimWay.m_sId package
Definition at line 392 of file GeoSvc.java.
Referenced by cc.ws.GeoSvc.SimWay.SimWay().
The documentation for this class was generated from the following file:
src/cc/ws/GeoSvc.java