Carma-cloud: cc.rsu.Position Class Reference
cc.rsu.Position Class Reference
Public Member Functions
int hashCode ()
boolean equals (Object obj)
Position ()
Position (double latitude, double longitude)
Position (double latitude, double longitude, double altitude)
double getAltitude ()
void setAltitude (double altitude)
double getLatitude ()
void setLatitude (double latitude)
double getlongitude ()
void setlongitude (double longitude)
String toString ()
Private Attributes
double latitude
double longitude
double altitude = 0
Detailed Description
Definition at line 7 of file Position.java.
Constructor & Destructor Documentation
Position() [1/3]
cc.rsu.Position.Position () inline
Definition at line 29 of file Position.java.
                      {
        super();
    }
Referenced by cc.rsu.Position.equals().
Position() [2/3]
cc.rsu.Position.Position (double latitude, double longitude) inline
Definition at line 33 of file Position.java.
{
        super();
        this.latitude = latitude;
        this.longitude = longitude;
    }
References cc.rsu.Position.latitude, and cc.rsu.Position.longitude.
Position() [3/3]
cc.rsu.Position.Position (double latitude, double longitude, double altitude) inline
Definition at line 39 of file Position.java.
{
        super();
        this.latitude = latitude;
        this.longitude = longitude;
        this.altitude = altitude;
    }
References cc.rsu.Position.altitude, cc.rsu.Position.latitude, and cc.rsu.Position.longitude.
Member Function Documentation
equals()
boolean cc.rsu.Position.equals (Object obj) inline
Definition at line 18 of file Position.java.
{
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Position other = (Position) obj;
        return latitude == other.latitude && longitude == other.longitude;
    }
References cc.rsu.Position.Position(), cc.rsu.Position.latitude, and cc.rsu.Position.longitude.
getAltitude()
double cc.rsu.Position.getAltitude () inline
Definition at line 46 of file Position.java.
{
        return altitude;
    }
References cc.rsu.Position.altitude.
Referenced by cc.rsu.GeodesicCartesianConverter.geodesic2Cartesian().
getLatitude()
double cc.rsu.Position.getLatitude () inline
Definition at line 54 of file Position.java.
{
        return latitude;
    }
References cc.rsu.Position.latitude.
Referenced by cc.rsu.BoundingBoxUtils.calculateBoundingBoxCoordinates(), and cc.rsu.GeodesicCartesianConverter.geodesic2Cartesian().
getlongitude()
double cc.rsu.Position.getlongitude () inline
Definition at line 62 of file Position.java.
{
        return longitude;
    }
References cc.rsu.Position.longitude.
Referenced by cc.rsu.BoundingBoxUtils.calculateBoundingBoxCoordinates(), and cc.rsu.GeodesicCartesianConverter.geodesic2Cartesian().
hashCode()
int cc.rsu.Position.hashCode () inline
Definition at line 13 of file Position.java.
{
        return Objects.hash(latitude, longitude);
    }
References cc.rsu.Position.latitude, and cc.rsu.Position.longitude.
setAltitude()
void cc.rsu.Position.setAltitude (double altitude) inline
Definition at line 50 of file Position.java.
{
        this.altitude = altitude;
    }
References cc.rsu.Position.altitude.
setLatitude()
void cc.rsu.Position.setLatitude (double latitude) inline
Definition at line 58 of file Position.java.
{
        this.latitude = latitude;
    }
References cc.rsu.Position.latitude.
Referenced by cc.rsu.BSMRequestParser.endElement().
setlongitude()
void cc.rsu.Position.setlongitude (double longitude) inline
Definition at line 66 of file Position.java.
{
        this.longitude = longitude;
    }
References cc.rsu.Position.longitude.
Referenced by cc.rsu.BSMRequestParser.endElement().
toString()
String cc.rsu.Position.toString () inline
Definition at line 71 of file Position.java.
{
        return "Position [latitude=" + latitude + ", longitude=" + longitude + "]";
    }
References cc.rsu.Position.latitude, and cc.rsu.Position.longitude.
Member Data Documentation
altitude
double cc.rsu.Position.altitude = 0 private
Definition at line 10 of file Position.java.
Referenced by cc.rsu.Position.Position(), cc.rsu.Position.getAltitude(), and cc.rsu.Position.setAltitude().
latitude
double cc.rsu.Position.latitude private
Definition at line 8 of file Position.java.
Referenced by cc.rsu.Position.Position(), cc.rsu.Position.equals(), cc.rsu.Position.getLatitude(), cc.rsu.Position.hashCode(), cc.rsu.Position.setLatitude(), and cc.rsu.Position.toString().
longitude
double cc.rsu.Position.longitude private
Definition at line 9 of file Position.java.
Referenced by cc.rsu.Position.Position(), cc.rsu.Position.equals(), cc.rsu.Position.getlongitude(), cc.rsu.Position.hashCode(), cc.rsu.Position.setlongitude(), and cc.rsu.Position.toString().
The documentation for this class was generated from the following file:
src/cc/rsu/Position.java