Carma-cloud: cc.geosrv.xodr.rdmk.LaneSection Class Reference
cc.geosrv.xodr.rdmk.LaneSection Class Reference
Public Member Functions
LaneSection ()
LaneSection (double dS, int nId)
void setInnerRoadMarks ()
void add (Lane oLane)
void sortLanes ()
void getLanes (ArrayList< Lane > oLaneList)
Static Public Member Functions
static LaneSection getLaneSection (double dDist, ArrayList< LaneSection > oLaneSections)
Public Attributes
double m_dS
ArrayList< Lane > m_oLeft = new ArrayList()
ArrayList< Lane > m_oRight = new ArrayList()
Lane m_oCenter
int m_nId
Private Member Functions
void setInnerRoadMarks (ArrayList< Lane > oLanes)
Static Private Attributes
static Comparator< Lane > LEFTLANES = (Lane o1, Lane o2) -> Integer.compare(o1.m_nLaneIndex, o2.m_nLaneIndex)
static Comparator< Lane > RIGHTLANES = (Lane o1, Lane o2) -> Integer.compare(o2.m_nLaneIndex, o1.m_nLaneIndex)
Detailed Description
Author
aaron.cherney
Definition at line 17 of file LaneSection.java.
Constructor & Destructor Documentation
LaneSection() [1/2]
cc.geosrv.xodr.rdmk.LaneSection.LaneSection () inline
Definition at line 27 of file LaneSection.java.
    {
    }
LaneSection() [2/2]
cc.geosrv.xodr.rdmk.LaneSection.LaneSection (double dS, int nId) inline
Definition at line 31 of file LaneSection.java.
    {
        m_dS = dS;
        m_nId = nId;
    }
References cc.geosrv.xodr.rdmk.LaneSection.m_dS, and cc.geosrv.xodr.rdmk.LaneSection.m_nId.
Member Function Documentation
add()
void cc.geosrv.xodr.rdmk.LaneSection.add (Lane oLane) inline
Definition at line 59 of file LaneSection.java.
    {
        if (oLane.m_nLaneIndex > 0)
            m_oLeft.add(oLane);
        else if (oLane.m_nLaneIndex < 0)
            m_oRight.add(oLane);
    }
References cc.geosrv.xodr.rdmk.Lane.m_nLaneIndex, cc.geosrv.xodr.rdmk.LaneSection.m_oLeft, and cc.geosrv.xodr.rdmk.LaneSection.m_oRight.
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement().
getLanes()
void cc.geosrv.xodr.rdmk.LaneSection.getLanes (ArrayList< Lane > oLaneList) inline
Definition at line 111 of file LaneSection.java.
    {
        oLaneList.clear();
        oLaneList.add(m_oCenter);
        for (int nIndex = 1; nIndex < m_oLeft.size() - 1; nIndex++)
            oLaneList.add(m_oLeft.get(nIndex));
        for (int nIndex = 1; nIndex < m_oRight.size() - 1; nIndex++)
            oLaneList.add(m_oRight.get(nIndex));
    }
References cc.geosrv.xodr.rdmk.LaneSection.m_oCenter, cc.geosrv.xodr.rdmk.LaneSection.m_oLeft, and cc.geosrv.xodr.rdmk.LaneSection.m_oRight.
Referenced by cc.geosrv.xodr.rdmk.Road.getRdMkCtrlLineArcs().
getLaneSection()
static LaneSection cc.geosrv.xodr.rdmk.LaneSection.getLaneSection (double dDist, ArrayList< LaneSection > oLaneSections) inline static
Definition at line 97 of file LaneSection.java.
    {
        int nIndex = oLaneSections.size();
        while (nIndex-- > 0)
        {
            LaneSection oTemp = oLaneSections.get(nIndex);
            if (dDist >= oTemp.m_dS)
                return oTemp;
        }
        return oLaneSections.get(0);
    }
References cc.geosrv.xodr.rdmk.LaneSection.m_dS.
setInnerRoadMarks() [1/2]
void cc.geosrv.xodr.rdmk.LaneSection.setInnerRoadMarks () inline
Definition at line 38 of file LaneSection.java.
    {
        setInnerRoadMarks(m_oLeft);
        setInnerRoadMarks(m_oRight);
    }
References cc.geosrv.xodr.rdmk.LaneSection.m_oLeft, cc.geosrv.xodr.rdmk.LaneSection.m_oRight, and cc.geosrv.xodr.rdmk.LaneSection.setInnerRoadMarks().
Referenced by cc.geosrv.xodr.rdmk.LaneSection.setInnerRoadMarks(), and cc.geosrv.xodr.rdmk.LaneSection.sortLanes().
setInnerRoadMarks() [2/2]
void cc.geosrv.xodr.rdmk.LaneSection.setInnerRoadMarks (ArrayList< Lane > oLanes) inline private
Definition at line 45 of file LaneSection.java.
    {
        int nSize = oLanes.size();
        if (nSize > 0)
        {
            oLanes.get(0).m_oInnerRoadMarks = m_oCenter.m_oOuterRoadMarks;
            for (int i = 1; i < nSize; i++)
            {
                oLanes.get(i).m_oInnerRoadMarks = oLanes.get(i - 1).m_oOuterRoadMarks;
            }
        }
    }
References cc.geosrv.xodr.rdmk.LaneSection.m_oCenter, and cc.geosrv.xodr.rdmk.Lane.m_oOuterRoadMarks.
sortLanes()
void cc.geosrv.xodr.rdmk.LaneSection.sortLanes () inline
Definition at line 68 of file LaneSection.java.
    {
        boolean bLeftEmpty = m_oLeft.isEmpty();
        boolean bRightEmpty = m_oRight.isEmpty();
        boolean bCenterNone = m_oCenter.m_nType == XodrUtil.getLaneType("none");
        Collections.sort(m_oLeft, LEFTLANES);
        setInnerRoadMarks(m_oLeft);
        m_oLeft.add(null);
        if (bRightEmpty) // there are no right lanes, so add null to mean latperm is none
            m_oLeft.add(0, null);
        else if (bCenterNone) // if center is none, use the first right lane
            m_oLeft.add(0, m_oRight.get(0));
        else
            m_oLeft.add(0, m_oCenter);
        Collections.sort(m_oRight, RIGHTLANES);
        setInnerRoadMarks(m_oRight);
        m_oRight.add(null);
        if (bLeftEmpty) // there are no left lanes, so add null to mean latperm is none
            m_oRight.add(0, null);
        else if (bCenterNone) // if center is none, use the first left lane, which is now position 1 since we insert at position 0 above
            m_oRight.add(0, m_oLeft.get(1));
        else
            m_oRight.add(0, m_oCenter);
    }
References cc.geosrv.xodr.XodrUtil.getLaneType(), cc.geosrv.xodr.rdmk.LaneSection.LEFTLANES, cc.geosrv.xodr.rdmk.LaneSection.m_oCenter, cc.geosrv.xodr.rdmk.LaneSection.m_oLeft, cc.geosrv.xodr.rdmk.LaneSection.m_oRight, cc.geosrv.xodr.rdmk.LaneSection.RIGHTLANES, and cc.geosrv.xodr.rdmk.LaneSection.setInnerRoadMarks().
Referenced by cc.geosrv.xodr.rdmk.XodrRoadMarkParser.endElement().
Member Data Documentation
LEFTLANES
Comparator<Lane> cc.geosrv.xodr.rdmk.LaneSection.LEFTLANES = (Lane o1, Lane o2) -> Integer.compare(o1.m_nLaneIndex, o2.m_nLaneIndex) static private
Definition at line 23 of file LaneSection.java.
Referenced by cc.geosrv.xodr.rdmk.LaneSection.sortLanes().
m_dS
double cc.geosrv.xodr.rdmk.LaneSection.m_dS
Definition at line 19 of file LaneSection.java.
Referenced by cc.geosrv.xodr.rdmk.LaneSection.LaneSection(), cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.geosrv.xodr.rdmk.Arc.addPoints(), cc.geosrv.xodr.rdmk.Line.addPoints(), cc.geosrv.xodr.rdmk.LaneSection.getLaneSection(), and cc.geosrv.xodr.rdmk.Road.getLaneSections().
m_nId
int cc.geosrv.xodr.rdmk.LaneSection.m_nId
Definition at line 25 of file LaneSection.java.
Referenced by cc.geosrv.xodr.rdmk.LaneSection.LaneSection(), and cc.geosrv.xodr.rdmk.Road.getRdMkCtrlLineArcs().
m_oCenter
Lane cc.geosrv.xodr.rdmk.LaneSection.m_oCenter
Definition at line 22 of file LaneSection.java.
Referenced by cc.geosrv.xodr.rdmk.LaneSection.getLanes(), cc.geosrv.xodr.rdmk.LaneSection.setInnerRoadMarks(), and cc.geosrv.xodr.rdmk.LaneSection.sortLanes().
m_oLeft
ArrayList<Lane> cc.geosrv.xodr.rdmk.LaneSection.m_oLeft = new ArrayList()
Definition at line 20 of file LaneSection.java.
Referenced by cc.geosrv.xodr.rdmk.LaneSection.add(), cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.geosrv.xodr.rdmk.LaneSection.getLanes(), cc.geosrv.xodr.rdmk.LaneSection.setInnerRoadMarks(), and cc.geosrv.xodr.rdmk.LaneSection.sortLanes().
m_oRight
ArrayList<Lane> cc.geosrv.xodr.rdmk.LaneSection.m_oRight = new ArrayList()
Definition at line 21 of file LaneSection.java.
Referenced by cc.geosrv.xodr.rdmk.LaneSection.add(), cc.geosrv.xodr.rdmk.Geometry.addLanePoints(), cc.geosrv.xodr.rdmk.LaneSection.getLanes(), cc.geosrv.xodr.rdmk.LaneSection.setInnerRoadMarks(), and cc.geosrv.xodr.rdmk.LaneSection.sortLanes().
RIGHTLANES
Comparator<Lane> cc.geosrv.xodr.rdmk.LaneSection.RIGHTLANES = (Lane o1, Lane o2) -> Integer.compare(o2.m_nLaneIndex, o1.m_nLaneIndex) static private
Definition at line 24 of file LaneSection.java.
Referenced by cc.geosrv.xodr.rdmk.LaneSection.sortLanes().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/rdmk/LaneSection.java