Carma-cloud: cc.vector_tile.VectorTile Class Reference
cc.vector_tile.VectorTile Class Reference
Classes
class Tile
interface TileOrBuilder
Static Public Member Functions
static void registerAllExtensions (com.google.protobuf.ExtensionRegistryLite registry)
Static Package Functions
[static initializer]
Private Member Functions
VectorTile ()
Detailed Description
Definition at line 6 of file VectorTile.java.
Constructor & Destructor Documentation
VectorTile()
cc.vector_tile.VectorTile.VectorTile () inline private
Definition at line 7 of file VectorTile.java.
{}
Referenced by cc.vector_tile.VectorTile.Tile.Value.dynamicMethod(), cc.vector_tile.VectorTile.Tile.Feature.dynamicMethod(), cc.vector_tile.VectorTile.Tile.Layer.dynamicMethod(), and cc.vector_tile.VectorTile.Tile.dynamicMethod().
Member Function Documentation
[static initializer]()
cc.vector_tile.VectorTile.[static initializer] inline static package
registerAllExtensions()
static void cc.vector_tile.VectorTile.registerAllExtensions (com.google.protobuf.ExtensionRegistryLite registry) inline static
Definition at line 8 of file VectorTile.java.
{
  }
The documentation for this class was generated from the following file:
src/cc/vector_tile/VectorTile.java