Carma-cloud: cc.ctrl.TrafCtrl Class Reference
cc.ctrl.TrafCtrl Class Reference
Public Member Functions
TrafCtrl ()
TrafCtrl (String sControlType, int nControlValue, long lTime, TrafCtrl oCtrl, String sLabel, boolean bReg, byte ySrc)
TrafCtrl (String sControlType, int nControlValue, ArrayList< Integer > nVTypes, long lTime, long lStart, TrafCtrl oCtrl, String sLabel, boolean bReg, byte ySrc)
TrafCtrl (String sControlType, String sControlValue, long lTime, TrafCtrl oCtrl, String sLabel, boolean bReg, byte ySrc)
TrafCtrl (String sControlType, int nControlValue, ArrayList< Integer > nVtypes, long lTime, long lStart, double[] dLineArcs, String sLabel, boolean bReg, byte ySrc)
TrafCtrl (String sControlType, int nControlValue, long lTime, double[] dLineArcs, String sLabel, boolean bReg, byte ySrc)
TrafCtrl (String sControlType, byte[] yControlValue, long lTime, double[] dLineArcs, byte ySrc)
TrafCtrl (String sControlType, long lTime, double[] dLineArcs)
TrafCtrl (String sControlType, String sControlValue, long lTime, double[] dLineArcs, String sLabel, boolean bReg, byte ySrc)
TrafCtrl (DataInputStream oIn, boolean bLoadGeo, boolean bSetTiles) throws Exception
void write (String sPath, double dExplodeStep, int nZoom, byte ySrc) throws Exception
void writeIndex (DataOutputStream oOut) throws IOException
void getXml (StringBuilder sBuf, String sReqId, int nReqSeq, int nMsgNum, int nMsgTot, String sVersion, boolean bIncludeParams, int nPtsIndex, boolean bRemoveWidth, boolean bList) throws IOException
double[] toMercatorPoints ()
void preparePoints (int nExplodeDist)
int compareTo (TrafCtrl o)
Static Public Member Functions
static String getId (byte[] yId)
static void getId (byte[] yId, StringBuilder sBuf)
Public Attributes
byte[] m_yId
final ArrayList< Integer > m_nVTypes = new ArrayList()
long m_lStart
long m_lEnd = Long.MAX_VALUE
boolean m_bRegulatory = true
int m_nControlType
byte[] m_yControlValue
int m_nLon
int m_nLat
int m_nWidth
String m_sLabel
CtrlGeo m_oFullGeo = null
Static Public Attributes
static Comparator< byte[]> ID_COMP
Protected Member Functions
void writeBin (StringBuilder sBuf, double dExplodeStep, int nZoom) throws Exception
void writeJson (StringBuilder sBuf) throws Exception
Package Attributes
String m_sVersion = "0.1"
long m_lUpdated
int m_nDoW = 127
ArrayList< int[]> m_nBetween = new ArrayList()
int m_nOffset = Integer.MIN_VALUE
int m_nPeriod
int m_nSpan
String m_sProj = "epsg:3785"
String m_sDatum = "WGS84"
long m_lTime
int m_nAlt
int m_nHeading
Private Member Functions
void generateId (byte ySrc)
Detailed Description
Definition at line 28 of file TrafCtrl.java.
Constructor & Destructor Documentation
TrafCtrl() [1/10]
cc.ctrl.TrafCtrl.TrafCtrl () inline
Definition at line 71 of file TrafCtrl.java.
    {
        super();
        m_bRegulatory = true;
        m_sLabel = "";
        if (m_nVTypes.isEmpty())
        {
            for (int nIndex = 3; nIndex < TrafCtrlEnums.VTYPES.length - 2; nIndex++)
                m_nVTypes.add(nIndex); // exclude pedestrians, rail, and unknown
            Collections.sort(m_nVTypes);
        }
    }
References cc.ctrl.TrafCtrl.m_bRegulatory, cc.ctrl.TrafCtrl.m_nVTypes, and cc.ctrl.TrafCtrl.m_sLabel.
TrafCtrl() [2/10]
cc.ctrl.TrafCtrl.TrafCtrl (String sControlType, int nControlValue, long lTime, TrafCtrl oCtrl, String sLabel, boolean bReg, byte ySrc) inline
Definition at line 86 of file TrafCtrl.java.
    {
        this(sControlType, nControlValue, null, lTime, 0, oCtrl, sLabel, bReg, ySrc);
    }
TrafCtrl() [3/10]
cc.ctrl.TrafCtrl.TrafCtrl (String sControlType, int nControlValue, ArrayList< Integer > nVTypes, long lTime, long lStart, TrafCtrl oCtrl, String sLabel, boolean bReg, byte ySrc) inline
Definition at line 92 of file TrafCtrl.java.
    {
        this();
        m_nControlType = TrafCtrlEnums.getCtrl(sControlType);
        if (nControlValue == Integer.MIN_VALUE)
            m_yControlValue = new byte[0];
        else
            m_yControlValue = MathUtil.intToBytes(nControlValue, new byte[4]);
        m_lTime = lTime;
        m_lStart = lStart;
        m_nLon = oCtrl.m_nLon;
        m_nLat = oCtrl.m_nLat;
        m_nHeading = oCtrl.m_nHeading;
        m_sLabel = sLabel;
        m_bRegulatory = bReg;
        m_nWidth = oCtrl.m_nWidth;
        for (TrafCtrlPt oPt : oCtrl)
            add(new TrafCtrlPt(oPt.m_nX, oPt.m_nY, oPt.m_nZ, oPt.m_nW));
        if (nVTypes != null)
        {
            m_nVTypes.clear();
            Collections.sort(nVTypes);
            for (Integer nVtype : nVTypes)
                m_nVTypes.add(nVtype);
        }
        generateId(ySrc);
    }
References cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrlEnums.getCtrl(), cc.util.MathUtil.intToBytes(), cc.ctrl.TrafCtrl.m_bRegulatory, cc.ctrl.TrafCtrl.m_lStart, cc.ctrl.TrafCtrl.m_lTime, cc.ctrl.TrafCtrl.m_nControlType, cc.ctrl.TrafCtrl.m_nHeading, cc.ctrl.TrafCtrl.m_nLat, cc.ctrl.TrafCtrl.m_nLon, cc.ctrl.TrafCtrl.m_nVTypes, cc.ctrl.TrafCtrl.m_nWidth, cc.ctrl.TrafCtrl.m_sLabel, and cc.ctrl.TrafCtrl.m_yControlValue.
TrafCtrl() [4/10]
cc.ctrl.TrafCtrl.TrafCtrl (String sControlType, String sControlValue, long lTime, TrafCtrl oCtrl, String sLabel, boolean bReg, byte ySrc) inline
Definition at line 124 of file TrafCtrl.java.
    {
        this(sControlType, TrafCtrlEnums.getCtrlVal(sControlType, sControlValue), lTime, oCtrl, sLabel, bReg, ySrc);
    }
References cc.ctrl.TrafCtrlEnums.getCtrlVal().
TrafCtrl() [5/10]
cc.ctrl.TrafCtrl.TrafCtrl (String sControlType, int nControlValue, ArrayList< Integer > nVtypes, long lTime, long lStart, double[] dLineArcs, String sLabel, boolean bReg, byte ySrc) inline
Definition at line 129 of file TrafCtrl.java.
    {
        this(sControlType, lTime, dLineArcs);
        m_sLabel = sLabel;
        m_bRegulatory = bReg;
        m_lStart = lStart;
        if (nControlValue == Integer.MIN_VALUE)
            m_yControlValue = new byte[0];
        else
            m_yControlValue = MathUtil.intToBytes(nControlValue, new byte[4]);
        if (nVtypes != null)
        {
            m_nVTypes.clear();
            Collections.sort(nVtypes);
            for (Integer nVtype : nVtypes)
                m_nVTypes.add(nVtype);
        }
        generateId(ySrc);
    }
References cc.ctrl.TrafCtrl.generateId(), cc.util.MathUtil.intToBytes(), cc.ctrl.TrafCtrl.m_bRegulatory, cc.ctrl.TrafCtrl.m_lStart, cc.ctrl.TrafCtrl.m_nVTypes, cc.ctrl.TrafCtrl.m_sLabel, and cc.ctrl.TrafCtrl.m_yControlValue.
TrafCtrl() [6/10]
cc.ctrl.TrafCtrl.TrafCtrl (String sControlType, int nControlValue, long lTime, double[] dLineArcs, String sLabel, boolean bReg, byte ySrc) inline
Definition at line 151 of file TrafCtrl.java.
    {
        this(sControlType, nControlValue, null, lTime, 0, dLineArcs, sLabel, bReg, ySrc);
    }
TrafCtrl() [7/10]
cc.ctrl.TrafCtrl.TrafCtrl (String sControlType, byte[] yControlValue, long lTime, double[] dLineArcs, byte ySrc) inline
Definition at line 157 of file TrafCtrl.java.
    {
        this(sControlType, lTime, dLineArcs);
        m_yControlValue = new byte[yControlValue.length];
        System.arraycopy(yControlValue, 0, m_yControlValue, 0, m_yControlValue.length);
        generateId(ySrc);
    }
References cc.ctrl.TrafCtrl.generateId(), and cc.ctrl.TrafCtrl.m_yControlValue.
TrafCtrl() [8/10]
cc.ctrl.TrafCtrl.TrafCtrl (String sControlType, long lTime, double[] dLineArcs) inline
Definition at line 167 of file TrafCtrl.java.
    {
        this();
        m_nControlType = TrafCtrlEnums.getCtrl(sControlType);
        m_lTime = lTime;
        m_nLon = Geo.toIntDeg(Mercator.xToLon(dLineArcs[5]));
        m_nLat = Geo.toIntDeg(Mercator.yToLat(dLineArcs[6]));
        m_nWidth = Mercator.mToCm(dLineArcs[7]);
        int[] nPrevPt = new int[]{Mercator.mToCm(dLineArcs[5]), Mercator.mToCm(dLineArcs[6]), m_nWidth};
        double dHdg = Geo.heading(nPrevPt[0], nPrevPt[1], dLineArcs[8], dLineArcs[9]);
        dHdg = Math.toDegrees(dHdg);
        m_nHeading = (int)(dHdg * 10 + 0.5);
        Iterator<double[]> oIt = Arrays.iterator(dLineArcs, new double[3], 5, 3);
        while (oIt.hasNext())
        {
            double[] dPt = oIt.next();
            int nX = Mercator.mToCm(dPt[0]);
            int nY = Mercator.mToCm(dPt[1]);
            int nW = Mercator.mToCm(dPt[2]);
            int nXd = nX - nPrevPt[0];
            int nYd = nY - nPrevPt[1];
            int nWd = nW - nPrevPt[2];
            TrafCtrlPt oTemp = new TrafCtrlPt(nXd, nYd, nWd);
            add(oTemp);
            nPrevPt[0] = nX;
            nPrevPt[1] = nY;
            nPrevPt[2] = nW;
        }
    }
References cc.ctrl.TrafCtrlEnums.getCtrl(), cc.util.Geo.heading(), cc.util.Arrays.iterator(), cc.ctrl.TrafCtrl.m_lTime, cc.ctrl.TrafCtrl.m_nControlType, cc.ctrl.TrafCtrl.m_nHeading, cc.ctrl.TrafCtrl.m_nLat, cc.ctrl.TrafCtrl.m_nLon, cc.ctrl.TrafCtrl.m_nWidth, cc.geosrv.Mercator.mToCm(), cc.util.Geo.toIntDeg(), cc.geosrv.Mercator.xToLon(), and cc.geosrv.Mercator.yToLat().
TrafCtrl() [9/10]
cc.ctrl.TrafCtrl.TrafCtrl (String sControlType, String sControlValue, long lTime, double[] dLineArcs, String sLabel, boolean bReg, byte ySrc) inline
Definition at line 198 of file TrafCtrl.java.
    {
        this(sControlType, TrafCtrlEnums.getCtrlVal(sControlType, sControlValue), lTime, dLineArcs, sLabel, bReg, ySrc);
    }
References cc.ctrl.TrafCtrlEnums.getCtrlVal().
TrafCtrl() [10/10]
cc.ctrl.TrafCtrl.TrafCtrl (DataInputStream oIn, boolean bLoadGeo, boolean bSetTiles) throws Exception inline
Definition at line 204 of file TrafCtrl.java.
    {
        m_sVersion = oIn.readUTF();
        m_yId = new byte[16];
        oIn.read(m_yId); // might need read loop
        m_lUpdated = oIn.readLong();
        int nCount = oIn.readInt();
        m_nVTypes.ensureCapacity(nCount);
        while (nCount-- > 0)
            m_nVTypes.add(oIn.readInt());
        Collections.sort(m_nVTypes);
        m_lStart = oIn.readLong();
        m_lEnd = oIn.readLong();
        m_nDoW = oIn.readInt();
        nCount = oIn.readInt();
        m_nBetween.ensureCapacity(nCount);
        while (nCount-- > 0)
            m_nBetween.add(new int[]{oIn.readInt(), oIn.readInt()});
        m_nOffset = oIn.readInt();
        m_nPeriod = oIn.readInt();
        m_nSpan = oIn.readInt();
        m_bRegulatory = oIn.readBoolean();
        m_nControlType = oIn.readInt();
        m_yControlValue = new byte[oIn.readInt()];
        oIn.read(m_yControlValue);
        m_sProj = oIn.readUTF();
        m_sDatum = oIn.readUTF();
        m_lTime = oIn.readLong();
        m_nLon = oIn.readInt();
        m_nLat = oIn.readInt();
        m_nAlt = oIn.readInt();
        m_nWidth = oIn.readInt();
        m_nHeading = oIn.readInt();
        m_sLabel = oIn.readUTF();
        nCount = oIn.readInt();
        ensureCapacity(nCount);
        while (nCount-- > 0)
            add(new TrafCtrlPt(oIn));
        if (bLoadGeo)
            m_oFullGeo = new CtrlGeo(oIn, bSetTiles, ProcCtrl.g_nDefaultZoom);
    }
References cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.TrafCtrl.m_bRegulatory, cc.ctrl.TrafCtrl.m_lEnd, cc.ctrl.TrafCtrl.m_lStart, cc.ctrl.TrafCtrl.m_lTime, cc.ctrl.TrafCtrl.m_lUpdated, cc.ctrl.TrafCtrl.m_nAlt, cc.ctrl.TrafCtrl.m_nBetween, cc.ctrl.TrafCtrl.m_nControlType, cc.ctrl.TrafCtrl.m_nDoW, cc.ctrl.TrafCtrl.m_nHeading, cc.ctrl.TrafCtrl.m_nLat, cc.ctrl.TrafCtrl.m_nLon, cc.ctrl.TrafCtrl.m_nOffset, cc.ctrl.TrafCtrl.m_nPeriod, cc.ctrl.TrafCtrl.m_nSpan, cc.ctrl.TrafCtrl.m_nVTypes, cc.ctrl.TrafCtrl.m_nWidth, cc.ctrl.TrafCtrl.m_oFullGeo, cc.ctrl.TrafCtrl.m_sDatum, cc.ctrl.TrafCtrl.m_sLabel, cc.ctrl.TrafCtrl.m_sProj, cc.ctrl.TrafCtrl.m_sVersion, cc.ctrl.TrafCtrl.m_yControlValue, and cc.ctrl.TrafCtrl.m_yId.
Member Function Documentation
compareTo()
int cc.ctrl.TrafCtrl.compareTo (TrafCtrl o) inline
Definition at line 750 of file TrafCtrl.java.
    {
        return TrafCtrl.ID_COMP.compare(m_yId, o.m_yId);
    }
References cc.ctrl.TrafCtrl.ID_COMP, and cc.ctrl.TrafCtrl.m_yId.
generateId()
void cc.ctrl.TrafCtrl.generateId (byte ySrc) inline private
Definition at line 256 of file TrafCtrl.java.
    {
        if (m_yId != null)
            return;
        Shake256 oMd = new Shake256();
        try
        (
            DataOutputStream oAbsorb = new DataOutputStream(oMd.getAbsorbStream());
            InputStream oSqueeze = oMd.getSqueezeStream();
        )
        {
            oAbsorb.writeLong(m_lUpdated);
            for (Integer nVal : m_nVTypes)
                oAbsorb.writeByte(nVal); // unbox and force to byte
            oAbsorb.writeLong(m_lStart); // include required schedule parameters
            oAbsorb.writeLong(m_lEnd);
            oAbsorb.writeByte(m_nDoW);
            for (int[] nBegDur : m_nBetween) // auto-skip empty array
            {
                oAbsorb.writeShort(nBegDur[0]);
                oAbsorb.writeShort(nBegDur[1]);
            }
            if (m_nOffset >= 0) // skip null schedule repeat parameters
            {
                oAbsorb.writeShort(m_nOffset);
                oAbsorb.writeShort(m_nPeriod);
                oAbsorb.writeShort(m_nSpan);
            }
            oAbsorb.writeBoolean(m_bRegulatory);
            oAbsorb.writeByte(m_nControlType);
            oAbsorb.write(m_yControlValue);
            oAbsorb.writeLong(m_lTime);
            oAbsorb.writeInt(m_nLon);
            oAbsorb.writeInt(m_nLat);
            oAbsorb.writeInt(m_nAlt);
            oAbsorb.writeInt(m_nWidth);
            oAbsorb.writeShort(m_nHeading);
            for (TrafCtrlPt oPt : this) // include path points
            {
                oAbsorb.writeInt(oPt.m_nX);
                oAbsorb.writeInt(oPt.m_nY);
                if (oPt.m_nW >= 0)
                    oAbsorb.writeInt(oPt.m_nW);
                if (oPt.m_nZ >= 0)
                    oAbsorb.writeInt(oPt.m_nZ);
            }
            byte[] yId = new byte[15];
            oSqueeze.read(yId);
            m_yId = new byte[16];
            m_yId[0] = ySrc;
            System.arraycopy(yId, 0, m_yId, 1, yId.length);
        }
        catch (Exception oEx)
        {
        }
    }
References cc.ctrl.TrafCtrl.m_bRegulatory, cc.ctrl.TrafCtrl.m_lEnd, cc.ctrl.TrafCtrl.m_lStart, cc.ctrl.TrafCtrl.m_lTime, cc.ctrl.TrafCtrl.m_lUpdated, cc.ctrl.TrafCtrl.m_nAlt, cc.ctrl.TrafCtrl.m_nBetween, cc.ctrl.TrafCtrl.m_nControlType, cc.ctrl.TrafCtrl.m_nDoW, cc.ctrl.TrafCtrl.m_nHeading, cc.ctrl.TrafCtrl.m_nLat, cc.ctrl.TrafCtrl.m_nLon, cc.ctrl.TrafCtrl.m_nOffset, cc.ctrl.TrafCtrl.m_nPeriod, cc.ctrl.TrafCtrl.m_nSpan, cc.ctrl.TrafCtrl.m_nVTypes, cc.ctrl.TrafCtrlPt.m_nW, cc.ctrl.TrafCtrl.m_nWidth, cc.ctrl.TrafCtrlPt.m_nX, cc.ctrl.TrafCtrlPt.m_nY, cc.ctrl.TrafCtrlPt.m_nZ, cc.ctrl.TrafCtrl.m_yControlValue, and cc.ctrl.TrafCtrl.m_yId.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), and cc.ctrl.TrafCtrl.write().
getId() [1/2]
static String cc.ctrl.TrafCtrl.getId (byte[] yId) inline static
Definition at line 662 of file TrafCtrl.java.
    {
        StringBuilder sBuf = new StringBuilder(16);
        int nOffset = 0;
        int nCount = 4;
        while (nCount-- > 0)
        {
            sBuf.append("/");
            Text.toHexString(yId, nOffset, nOffset + 4, sBuf);
            nOffset += 4;
        }
        return sBuf.toString();
    }
References cc.util.Text.toHexString().
Referenced by cc.rsm.RsmCollect.RsmRecord.cleanup(), cc.ws.CtrlTiles.doGet(), cc.ws.ValidateXodrTiles.doGet(), cc.ws.GeoLanes.doPost(), cc.ws.WxPoly.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcCtrl.getCurrentControls(), cc.ctrl.proc.ProcLatPerm.renderTiledData(), cc.ws.TcmReqServlet.run(), cc.ws.CtrlTiles.saveEdit(), and cc.ctrl.proc.ProcDebug.writeGeoLanes().
getId() [2/2]
static void cc.ctrl.TrafCtrl.getId (byte[] yId, StringBuilder sBuf) inline static
Definition at line 677 of file TrafCtrl.java.
    {
        sBuf.setLength(0);
        int nOffset = 0;
        int nCount = 4;
        while (nCount-- > 0)
        {
            sBuf.append("/");
            Text.toHexString(yId, nOffset, nOffset + 4, sBuf);
            nOffset += 4;
        }
    }
References cc.util.Text.toHexString().
getXml()
void cc.ctrl.TrafCtrl.getXml (StringBuilder sBuf, String sReqId, int nReqSeq, int nMsgNum, int nMsgTot, String sVersion, boolean bIncludeParams, int nPtsIndex, boolean bRemoveWidth, boolean bList) throws IOException inline
Definition at line 521 of file TrafCtrl.java.
    {
        if (!bList)
        {
            sBuf.setLength(0);
            sBuf.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        }
//      if (sVersion.compareTo("1.0") != 0)
//      {
//          sBuf.append("invalid version");
//          return;
//      }
        sBuf.append("<TrafficControlMessage>");
        sBuf.append("<tcmV01>");
        sBuf.append("<reqid>").append(sReqId).append("</reqid>");
        sBuf.append("<reqseq>").append(nReqSeq).append("</reqseq>");
        sBuf.append("<msgtot>").append(nMsgTot).append("</msgtot>");
        sBuf.append("<msgnum>").append(nMsgNum).append("</msgnum>");
        sBuf.append("<id>");
        Text.toHexString(m_yId, 0, m_yId.length, sBuf);
        sBuf.append("</id>");
        sBuf.append("<updated>").append(m_lUpdated / 1000 / 60).append("</updated>"); // convert to epoch minutes
        sBuf.append("<package>");
        if (m_sLabel != null && !m_sLabel.isEmpty())
        {
            sBuf.append("<label>").append(Text.truncate(m_sLabel, 63)).append("</label>");
        }
        else
        {
            sBuf.append("<label>null</label>");
        }
        sBuf.append("<tcids>");
        sBuf.append("<Id128b>");
        Text.toHexString(m_yId, 0, m_yId.length, sBuf);
        sBuf.append("</Id128b>");
        sBuf.append("</tcids>");
        sBuf.append("</package>");
        if (bIncludeParams)
        {
            sBuf.append("<params>");
            sBuf.append("<vclasses>");
            for (int nIndex = 0; nIndex < m_nVTypes.size(); nIndex++)
                sBuf.append("<").append(TrafCtrlEnums.VTYPES[m_nVTypes.get(nIndex)]).append("/>");
            sBuf.append("</vclasses>");
            sBuf.append("<schedule>");
            sBuf.append("<start>").append(m_lStart / 1000 / 60).append("</start>"); // convert to epoch minutes
            sBuf.append("<end>").append(m_lEnd / 1000 / 60).append("</end>"); // convert to epoch minutes
            sBuf.append("<dow>");
            int nDoW = m_nDoW; // bit-shift day-of-week characters
            for (int nDay = 0; nDay < 7; nDay++)
            {
                if ((nDoW & 1) > 0)
                    sBuf.append('1');
                else
                    sBuf.append('0');
                nDoW >>= 1;
            }
            sBuf.append("</dow>");
            if (!m_nBetween.isEmpty())
            {
                sBuf.append("<between>");
                for (int[] nBegDur : m_nBetween)
                {
                    sBuf.append("<DailySchedule>");
                    sBuf.append("<begin>").append(nBegDur[0]).append("</begin>");
                    sBuf.append("<duration>").append(nBegDur[1]).append("</duration>");
                    sBuf.append("</DailySchedule>");
                }
                sBuf.append("</between>");
            }
            if (m_nOffset >= 0)
            {
                sBuf.append("<repeat>");
                sBuf.append("<offset>").append(m_nOffset).append("</offset>");
                sBuf.append("<period>").append(m_nPeriod).append("</period>");
                sBuf.append("<span>").append(m_nSpan).append("</span>");
                sBuf.append("</repeat>");
            }
            sBuf.append("</schedule>");
            sBuf.append("<regulatory><").append(m_bRegulatory).append("/></regulatory>");
            sBuf.append("<detail>");
            ArrayList<String> sVals = new ArrayList(4);
            TrafCtrlEnums.getCtrlValString(m_nControlType, m_yControlValue, sVals);
            String sTag = sVals.get(0);
            sBuf.append("<").append(sTag);
            if (sVals.size() == 1) // null value so empty tag
                sBuf.append("/>");
            else
            {
                if (TrafCtrlEnums.CTRLS[m_nControlType].length == 1)
                    sBuf.append(">").append(sVals.get(1)).append("</").append(sTag).append(">");
                else // enumerated value that needs to be an empty tag, not a value
                {
                    if (sVals.size() == 2)
                        sBuf.append("><").append(sVals.get(1)).append("/></").append(sTag).append(">");
                    if (sVals.size() == 4)
                        sBuf.append("><").append(sVals.get(1)).append("/><").append(sVals.get(3)).append("/></").append(sTag).append(">");
                }
            }
            sBuf.append("");
            sBuf.append("</detail>");
            sBuf.append("</params>");
        }
        sBuf.append("<geometry>");
        sBuf.append("<proj>").append(m_sProj).append("</proj>");
        sBuf.append("<datum>").append(m_sDatum).append("</datum>");
        sBuf.append("<reftime>").append(m_lTime / 1000 / 60).append("</reftime>"); // convert to EpochMins
        sBuf.append("<reflon>").append(m_nLon).append("</reflon>");
        sBuf.append("<reflat>").append(m_nLat).append("</reflat>");
        sBuf.append("<refelv>").append(m_nAlt).append("</refelv>");
        if (!bRemoveWidth)
            sBuf.append("<refwidth>").append(m_nWidth).append("</refwidth>");
        sBuf.append("<heading>").append(m_nHeading).append("</heading>");
        sBuf.append("<nodes>");
        int nEnd = Math.min(size(), (nPtsIndex / 256 + 1) * 256);
        if (bList)
        {
            nPtsIndex = 0;
            nEnd = size();
        }
        for (int nIndex = nPtsIndex; nIndex < nEnd; nIndex++)
        {
            get(nIndex).writeXml(sBuf);
        }
        sBuf.append("</nodes>");
        sBuf.append("</geometry>");
        sBuf.append("</tcmV01>");
        sBuf.append("</TrafficControlMessage>");
    }
References cc.ctrl.TrafCtrlEnums.CTRLS, cc.ctrl.TrafCtrlEnums.getCtrlValString(), cc.ctrl.TrafCtrl.m_bRegulatory, cc.ctrl.TrafCtrl.m_lEnd, cc.ctrl.TrafCtrl.m_lStart, cc.ctrl.TrafCtrl.m_lTime, cc.ctrl.TrafCtrl.m_lUpdated, cc.ctrl.TrafCtrl.m_nAlt, cc.ctrl.TrafCtrl.m_nBetween, cc.ctrl.TrafCtrl.m_nControlType, cc.ctrl.TrafCtrl.m_nDoW, cc.ctrl.TrafCtrl.m_nHeading, cc.ctrl.TrafCtrl.m_nLat, cc.ctrl.TrafCtrl.m_nLon, cc.ctrl.TrafCtrl.m_nOffset, cc.ctrl.TrafCtrl.m_nPeriod, cc.ctrl.TrafCtrl.m_nSpan, cc.ctrl.TrafCtrl.m_nVTypes, cc.ctrl.TrafCtrl.m_nWidth, cc.ctrl.TrafCtrl.m_sDatum, cc.ctrl.TrafCtrl.m_sLabel, cc.ctrl.TrafCtrl.m_sProj, cc.ctrl.TrafCtrl.m_yControlValue, cc.ctrl.TrafCtrl.m_yId, cc.util.Text.toHexString(), cc.util.Text.truncate(), and cc.ctrl.TrafCtrlEnums.VTYPES.
Referenced by cc.ws.TcmReqServlet.run().
preparePoints()
void cc.ctrl.TrafCtrl.preparePoints (int nExplodeDist) inline
Definition at line 710 of file TrafCtrl.java.
    {
        if (nExplodeDist == 0)
            return;
        double[] dC = m_oFullGeo.m_dC;
        double[] dNT = m_oFullGeo.m_dNT;
        int nLimit = Arrays.size(dC);
        ArrayList<TrafCtrlPt> oNewPts = new ArrayList();
        int[] nPrevPt = new int[]{Mercator.lonToCm(Geo.fromIntDeg(m_nLon)), Mercator.latToCm(Geo.fromIntDeg(m_nLat)), m_nWidth};
        int nStep = (int)(nExplodeDist / (ProcCtrl.g_dExplodeStep * 100)) * 2;
        for (int nIndex = 1; nIndex < nLimit; nIndex += nStep)
        {
            int nX = Mercator.mToCm(dC[nIndex]);
            int nY = Mercator.mToCm(dC[nIndex + 1]);
            int nW = Mercator.mToCm(Geo.distance(dC[nIndex], dC[nIndex + 1], dNT[nIndex], dNT[nIndex + 1]) * 2);
            int nXd = nX - nPrevPt[0];
            int nYd = nY - nPrevPt[1];
            int nWd = nW - nPrevPt[2];
            TrafCtrlPt oTemp = new TrafCtrlPt(nXd, nYd, nWd);
            oNewPts.add(oTemp);
            nPrevPt[0] = nX;
            nPrevPt[1] = nY;
            nPrevPt[2] = nW;
        }
        int nX = Mercator.mToCm(dC[nLimit - 2]);
        int nY = Mercator.mToCm(dC[nLimit - 1]);
        int nW = Mercator.mToCm(Geo.distance(dC[nLimit - 2], dC[nLimit - 1], dNT[nLimit - 2], dNT[nLimit - 1]) * 2);
        int nXd = nX - nPrevPt[0];
        int nYd = nY - nPrevPt[1];
        int nWd = nW - nPrevPt[2];
        if (nXd != 0 || nYd != 0 || nWd != 0)
            oNewPts.add(new TrafCtrlPt(nXd, nYd, nWd));
        clear();
        addAll(oNewPts);
    }
References cc.util.Geo.distance(), cc.util.Geo.fromIntDeg(), cc.ctrl.proc.ProcCtrl.g_dExplodeStep, cc.geosrv.Mercator.latToCm(), cc.geosrv.Mercator.lonToCm(), cc.ctrl.CtrlGeo.m_dC, cc.ctrl.CtrlGeo.m_dNT, cc.ctrl.TrafCtrl.m_nLat, cc.ctrl.TrafCtrl.m_nLon, cc.ctrl.TrafCtrl.m_nWidth, cc.ctrl.TrafCtrl.m_oFullGeo, cc.geosrv.Mercator.mToCm(), and cc.util.Arrays.size().
Referenced by cc.ws.TcmReqServlet.run().
toMercatorPoints()
double[] cc.ctrl.TrafCtrl.toMercatorPoints () inline
Definition at line 691 of file TrafCtrl.java.
    {
        double[] dRet = Arrays.newDoubleArray(size() * 2 + 4);
        dRet = Arrays.add(dRet, new double[]{Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
        int nPrevX = Mercator.lonToCm(Geo.fromIntDeg(m_nLon));
        int nPrevY = Mercator.latToCm(Geo.fromIntDeg(m_nLat));
        for (TrafCtrlPt oPt : this)
        {
            int nCurX = nPrevX + oPt.m_nX;
            int nCurY = nPrevY + oPt.m_nY;
            dRet = Arrays.addAndUpdate(dRet, nCurX / 100.0, nCurY / 100.0);
            nPrevX = nCurX;
            nPrevY = nCurY;
        }
        return dRet;
    }
References cc.util.Arrays.add(), cc.util.Arrays.addAndUpdate(), cc.util.Geo.fromIntDeg(), cc.geosrv.Mercator.latToCm(), cc.geosrv.Mercator.lonToCm(), cc.ctrl.TrafCtrl.m_nLat, cc.ctrl.TrafCtrl.m_nLon, cc.ctrl.TrafCtrlPt.m_nX, cc.ctrl.TrafCtrlPt.m_nY, and cc.util.Arrays.newDoubleArray().
write()
void cc.ctrl.TrafCtrl.write (String sPath, double dExplodeStep, int nZoom, byte ySrc) throws Exception inline
Definition at line 324 of file TrafCtrl.java.
    {
        generateId(ySrc); // need id to build file path
        StringBuilder sBuf = new StringBuilder(sPath);
        if (sPath.endsWith("/"))
            sBuf.setLength(sBuf.length() - 1); // remove trailing path separator
        int nOffset = 0;
        int nCount = 3;
        while (nCount-- > 0)
        {
            sBuf.append("/");
            Text.toHexString(m_yId, nOffset, nOffset + 4, sBuf);
            nOffset += 4;
        }
        sBuf.append("/"); // finish path with filename
        Text.toHexString(m_yId, nOffset, nOffset + 4, sBuf);
        writeBin(sBuf, dExplodeStep, nZoom);
        writeJson(sBuf);
    }
References cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.m_yId, cc.util.Text.toHexString(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
Referenced by cc.ws.CtrlTiles.addControl(), cc.ctrl.CreateCtrls.createCtrl(), cc.ws.WxPoly.doPost(), cc.ctrl.RenderCtrl.main(), cc.rsm.RsmParser.parseRequest(), cc.ctrl.proc.ProcClosed.proc(), cc.ctrl.proc.ProcClosing.proc(), cc.ctrl.proc.ProcDebug.proc(), cc.ctrl.proc.ProcDebugOutlines.proc(), cc.ctrl.proc.ProcDirection.proc(), cc.ctrl.proc.ProcLatPerm.proc(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ctrl.proc.ProcOpening.proc(), cc.ctrl.proc.ProcPavement.proc(), cc.ctrl.proc.ProcSignal.proc(), cc.ctrl.proc.ProcStop.proc(), cc.ctrl.proc.ProcYield.proc(), cc.ws.CtrlTiles.saveEdit(), and cc.ws.CtrlTiles.splitLineArcs().
writeBin()
void cc.ctrl.TrafCtrl.writeBin (StringBuilder sBuf, double dExplodeStep, int nZoom) throws Exception inline protected
Definition at line 349 of file TrafCtrl.java.
    {
        sBuf.append(".bin");
        Path oPath = Paths.get(sBuf.toString());
        Files.createDirectories(oPath.getParent(), FileUtil.DIRPERS);
        try (DataOutputStream oOut = new DataOutputStream(FileUtil.newOutputStream(oPath)))
        {
            oOut.writeUTF(m_sVersion);
            oOut.write(m_yId);
            oOut.writeLong(m_lUpdated);
            oOut.writeInt(m_nVTypes.size());
            for (Integer nVal : m_nVTypes)
                oOut.writeInt(nVal);
            oOut.writeLong(m_lStart);
            oOut.writeLong(m_lEnd);
            oOut.writeInt(m_nDoW);
            oOut.writeInt(m_nBetween.size());
            for (int[] nBegDur : m_nBetween)
            {
                oOut.write(nBegDur[0]);
                oOut.write(nBegDur[1]);
            }
            oOut.writeInt(m_nOffset);
            oOut.writeInt(m_nPeriod);
            oOut.writeInt(m_nSpan);
            oOut.writeBoolean(m_bRegulatory);
            oOut.writeInt(m_nControlType);
            oOut.writeInt(m_yControlValue.length);
            oOut.write(m_yControlValue);
            oOut.writeUTF(m_sProj);
            oOut.writeUTF(m_sDatum);
            oOut.writeLong(m_lTime);
            oOut.writeInt(m_nLon);
            oOut.writeInt(m_nLat);
            oOut.writeInt(m_nAlt);
            oOut.writeInt(m_nWidth);
            oOut.writeInt(m_nHeading);
            oOut.writeUTF(m_sLabel == null ? "" : m_sLabel);
            oOut.writeInt(size());
            for (TrafCtrlPt oPt : this)
                oPt.writeBin(oOut);
            if (m_oFullGeo == null)
                m_oFullGeo = new CtrlGeo(this, dExplodeStep, nZoom);
            for (int nIndex = 0; nIndex < m_oFullGeo.m_dBB.length; nIndex++)
                oOut.writeInt((int)(m_oFullGeo.m_dBB[nIndex] * 100.0 + 0.5));
            oOut.writeDouble(m_oFullGeo.m_dLength);
            oOut.writeDouble(m_oFullGeo.m_dAverageWidth);
            CtrlGeo.writePts(oOut, m_oFullGeo.m_dC); // center line
            CtrlGeo.writePts(oOut, m_oFullGeo.m_dNT); // negative tangent line
            CtrlGeo.writePts(oOut, m_oFullGeo.m_dPT); // positive tangent line
        }
    }
References cc.util.FileUtil.DIRPERS, cc.ctrl.TrafCtrl.m_bRegulatory, cc.ctrl.CtrlGeo.m_dAverageWidth, cc.ctrl.CtrlGeo.m_dBB, cc.ctrl.CtrlGeo.m_dC, cc.ctrl.CtrlGeo.m_dLength, cc.ctrl.CtrlGeo.m_dNT, cc.ctrl.CtrlGeo.m_dPT, cc.ctrl.TrafCtrl.m_lEnd, cc.ctrl.TrafCtrl.m_lStart, cc.ctrl.TrafCtrl.m_lTime, cc.ctrl.TrafCtrl.m_lUpdated, cc.ctrl.TrafCtrl.m_nAlt, cc.ctrl.TrafCtrl.m_nBetween, cc.ctrl.TrafCtrl.m_nControlType, cc.ctrl.TrafCtrl.m_nDoW, cc.ctrl.TrafCtrl.m_nHeading, cc.ctrl.TrafCtrl.m_nLat, cc.ctrl.TrafCtrl.m_nLon, cc.ctrl.TrafCtrl.m_nOffset, cc.ctrl.TrafCtrl.m_nPeriod, cc.ctrl.TrafCtrl.m_nSpan, cc.ctrl.TrafCtrl.m_nVTypes, cc.ctrl.TrafCtrl.m_nWidth, cc.ctrl.TrafCtrl.m_oFullGeo, cc.ctrl.TrafCtrl.m_sDatum, cc.ctrl.TrafCtrl.m_sLabel, cc.ctrl.TrafCtrl.m_sProj, cc.ctrl.TrafCtrl.m_sVersion, cc.ctrl.TrafCtrl.m_yControlValue, cc.ctrl.TrafCtrl.m_yId, cc.util.FileUtil.newOutputStream(), cc.ctrl.TrafCtrlPt.writeBin(), and cc.ctrl.CtrlGeo.writePts().
Referenced by cc.ctrl.TrafCtrl.write().
writeIndex()
void cc.ctrl.TrafCtrl.writeIndex (DataOutputStream oOut) throws IOException inline
Definition at line 410 of file TrafCtrl.java.
    {
        oOut.writeInt(m_nControlType);
        oOut.write(m_yId);
        oOut.writeLong(m_lStart);
        oOut.writeLong(m_lEnd);
        oOut.writeInt((int)(m_oFullGeo.m_dBB[0] * 100.0 + 0.5));
        oOut.writeInt((int)(m_oFullGeo.m_dBB[1] * 100.0 + 0.5));
        oOut.writeInt((int)(m_oFullGeo.m_dBB[2] * 100.0 + 0.5));
        oOut.writeInt((int)(m_oFullGeo.m_dBB[3] * 100.0 + 0.5));
    }
References cc.ctrl.CtrlGeo.m_dBB, cc.ctrl.TrafCtrl.m_lEnd, cc.ctrl.TrafCtrl.m_lStart, cc.ctrl.TrafCtrl.m_nControlType, cc.ctrl.TrafCtrl.m_oFullGeo, and cc.ctrl.TrafCtrl.m_yId.
writeJson()
void cc.ctrl.TrafCtrl.writeJson (StringBuilder sBuf) throws Exception inline protected
Definition at line 424 of file TrafCtrl.java.
    {
        sBuf.append(".json");
        Path oPath = Paths.get(sBuf.toString());
        Files.createDirectories(oPath.getParent(), FileUtil.DIRPERS);
        sBuf.setLength(0); // reset JSON output buffer
        sBuf.append("{\n"); // open ctrl object
        sBuf.append("\t\"version\":\"").append(m_sVersion).append("\",\n");
        sBuf.append("\t\"id\":\"");
        Text.toHexString(m_yId, 0, m_yId.length, sBuf);
        sBuf.append("\",\n");
        SimpleDateFormat oFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        sBuf.append("\t\"updated\":\"").append(oFormat.format(new Date(m_lUpdated))).append("\",\n");
        sBuf.append("\t\"vtypes\":\n\t["); // start vtype array
        m_nVTypes.forEach((nVType) -> {sBuf.append("\n\t\t\"").append(TrafCtrlEnums.VTYPES[nVType]).append("\",");});
        sBuf.setLength(sBuf.length() - 1); // remove trailing comma
        sBuf.append("\n\t],\n"); // end vtype array
        sBuf.append("\t\"schedule\":\n\t{\n"); // start schedule object
        sBuf.append("\t\t\"start\":\"").append(oFormat.format(new Date(m_lStart))).append("\",\n");
        sBuf.append("\t\t\"end\":\"").append(oFormat.format(new Date(m_lEnd))).append("\",\n");
        sBuf.append("\t\t\"dow\":\"");
        int nCount = 0;
        int nDoW = m_nDoW; // bit-shift day-of-week characters
        while (nDoW != 0)
        {
            if ((nDoW & 1) > 0)
                sBuf.append(TrafCtrlEnums.DAYCHARS[nCount]);
            ++nCount;
            nDoW >>= 1;
        }
        sBuf.append("\",\n"); // end day-of-week
        if (!m_nBetween.isEmpty()) // skip empty schedule between parameters
        {
            sBuf.append("\t\t\"between\":\n\t\t["); // start between array
            for (int[] nBegDur : m_nBetween)
            {
                sBuf.append("\n\t\t\t{\"begin\":").append(nBegDur[0]);
                sBuf.append(", \"duration\":").append(nBegDur[1]).append("},");
            }
            sBuf.setLength(sBuf.length() - 1); // remove trailing comma
            sBuf.append("\n\t\t],\n"); // end between array
        }
        if (m_nOffset >= 0) // skip empty schedule repeat parameters
        {
            sBuf.append("\t\t\"repeat\":\n\t\t\t{\n"); // start schedule repeat object
            sBuf.append("\t\t\t\"offset\":").append(m_nOffset).append("\n");
            sBuf.append("\t\t\t\"period\":").append(m_nPeriod).append("\n");
            sBuf.append("\t\t\t\"span\":").append(m_nSpan).append("\n");
            sBuf.append("\t\t},\n"); // end schedule repeat object
        }
        sBuf.setLength(sBuf.length() - 2); // remove comma and newline
        sBuf.append("\n\t},\n"); // end schedule object
        sBuf.append("\t\"regulatory\":").append(m_bRegulatory).append(",\n");
        String[] sCtrl = TrafCtrlEnums.CTRLS[m_nControlType];
        sBuf.append("\t\"controltype\":\"").append(sCtrl[0]).append("\",\n");
        if (m_yControlValue.length > 0) // ignore null values
            sBuf.append("\t\"controlvalue\":\"").append(MathUtil.bytesToInt(m_yControlValue)).append("\",\n");
//          sBuf.append("\t\"controlvalue\":\"").append(sCtrl[m_nControlValue]).append("\",\n");
        sBuf.append("\t\"proj\":\"").append(m_sProj).append("\",\n");
        sBuf.append("\t\"datum\":\"").append(m_sDatum).append("\",\n");
        sBuf.append("\t\"label\":\"").append(m_sLabel).append("\",\n");
        sBuf.append("\t\"time\":\"").append(oFormat.format(new Date(m_lTime))).append("\",\n");
        sBuf.append("\t\"lon\":").append(m_nLon).append(",\n");
        sBuf.append("\t\"lat\":").append(m_nLat).append(",\n");
        sBuf.append("\t\"alt\":").append(m_nAlt).append(",\n");
        sBuf.append("\t\"heading\":").append(m_nHeading).append(",\n");
        sBuf.append("\t\"points\":\n\t["); // start point array
        for (TrafCtrlPt oPt : this) // include path points
        {
            sBuf.append("\n\t\t");
            oPt.writeJson(sBuf);
            sBuf.append(",");
        }
        sBuf.setLength(sBuf.length() - 1); // remove trailing comma
        sBuf.append("\n\t]\n"); // end point array
        sBuf.append("}\n"); // close ctrl object
        try (BufferedWriter oOut = new BufferedWriter(Channels.newWriter(Files.newByteChannel(oPath, FileUtil.WRITE, FileUtil.FILEPERS), "UTF-8")))
        {
            for (nCount = 0; nCount < sBuf.length(); nCount++)
                oOut.write(sBuf.charAt(nCount));
        }
    }
References cc.util.MathUtil.bytesToInt(), cc.ctrl.TrafCtrlEnums.CTRLS, cc.ctrl.TrafCtrlEnums.DAYCHARS, cc.util.FileUtil.DIRPERS, cc.util.FileUtil.FILEPERS, cc.ctrl.TrafCtrl.m_bRegulatory, cc.ctrl.TrafCtrl.m_lEnd, cc.ctrl.TrafCtrl.m_lStart, cc.ctrl.TrafCtrl.m_lTime, cc.ctrl.TrafCtrl.m_lUpdated, cc.ctrl.TrafCtrl.m_nAlt, cc.ctrl.TrafCtrl.m_nBetween, cc.ctrl.TrafCtrl.m_nControlType, cc.ctrl.TrafCtrl.m_nDoW, cc.ctrl.TrafCtrl.m_nHeading, cc.ctrl.TrafCtrl.m_nLat, cc.ctrl.TrafCtrl.m_nLon, cc.ctrl.TrafCtrl.m_nOffset, cc.ctrl.TrafCtrl.m_nPeriod, cc.ctrl.TrafCtrl.m_nSpan, cc.ctrl.TrafCtrl.m_nVTypes, cc.ctrl.TrafCtrl.m_sDatum, cc.ctrl.TrafCtrl.m_sLabel, cc.ctrl.TrafCtrl.m_sProj, cc.ctrl.TrafCtrl.m_sVersion, cc.ctrl.TrafCtrl.m_yControlValue, cc.ctrl.TrafCtrl.m_yId, cc.util.Text.toHexString(), cc.ctrl.TrafCtrlEnums.VTYPES, cc.util.FileUtil.WRITE, and cc.ctrl.TrafCtrlPt.writeJson().
Referenced by cc.ctrl.TrafCtrl.write().
Member Data Documentation
ID_COMP
Comparator<byte[]> cc.ctrl.TrafCtrl.ID_COMP static
Initial value:
= (byte[] y1, byte[] y2) ->
    {
        int nReturn = 0;
        for (int nIndex = 0; nIndex < y1.length; nIndex++)
        {
            nReturn = Byte.compare(y1[nIndex], y2[nIndex]);
            if (nReturn != 0)
                return nReturn;
        }
        return nReturn;
    }
Definition at line 57 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.compareTo(), cc.ws.CtrlTiles.doGet(), cc.ws.ValidateXodrTiles.doGet(), cc.ws.GeoLanes.doPost(), cc.ws.WxPoly.doPost(), cc.ctrl.proc.ProcCtrl.getCurrentControls(), cc.ws.TcmReqServlet.run(), and cc.ctrl.proc.ProcCtrl.updateIndex().
m_bRegulatory
boolean cc.ctrl.TrafCtrl.m_bRegulatory = true
Definition at line 43 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ws.GeoLanes.doPost(), cc.ws.WxPoly.doPost(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ws.CtrlTiles.saveEdit(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_lEnd
long cc.ctrl.TrafCtrl.m_lEnd = Long.MAX_VALUE
Definition at line 36 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.writeBin(), cc.ctrl.TrafCtrl.writeIndex(), and cc.ctrl.TrafCtrl.writeJson().
m_lStart
long cc.ctrl.TrafCtrl.m_lStart
Definition at line 35 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ws.CtrlTiles.saveEdit(), cc.ctrl.TrafCtrl.writeBin(), cc.ctrl.TrafCtrl.writeIndex(), and cc.ctrl.TrafCtrl.writeJson().
m_lTime
long cc.ctrl.TrafCtrl.m_lTime package
Definition at line 49 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_lUpdated
long cc.ctrl.TrafCtrl.m_lUpdated package
Definition at line 32 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_nAlt
int cc.ctrl.TrafCtrl.m_nAlt package
Definition at line 52 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_nBetween
ArrayList<int[]> cc.ctrl.TrafCtrl.m_nBetween = new ArrayList() package
Definition at line 38 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_nControlType
int cc.ctrl.TrafCtrl.m_nControlType
Definition at line 44 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.CreateCtrls.createCtrl(), cc.ws.GeoLanes.doPost(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.RenderCtrl.main(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ws.CtrlTiles.saveEdit(), cc.ctrl.TrafCtrl.writeBin(), cc.ctrl.TrafCtrl.writeIndex(), and cc.ctrl.TrafCtrl.writeJson().
m_nDoW
int cc.ctrl.TrafCtrl.m_nDoW = 127 package
Definition at line 37 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_nHeading
int cc.ctrl.TrafCtrl.m_nHeading package
Definition at line 53 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_nLat
int cc.ctrl.TrafCtrl.m_nLat
Definition at line 51 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.preparePoints(), cc.ctrl.TrafCtrl.toMercatorPoints(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_nLon
int cc.ctrl.TrafCtrl.m_nLon
Definition at line 50 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.preparePoints(), cc.ctrl.TrafCtrl.toMercatorPoints(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_nOffset
int cc.ctrl.TrafCtrl.m_nOffset = Integer.MIN_VALUE package
Definition at line 39 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_nPeriod
int cc.ctrl.TrafCtrl.m_nPeriod package
Definition at line 40 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_nSpan
int cc.ctrl.TrafCtrl.m_nSpan package
Definition at line 41 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_nVTypes
final ArrayList<Integer> cc.ctrl.TrafCtrl.m_nVTypes = new ArrayList()
Definition at line 33 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ws.GeoLanes.doPost(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ws.CtrlTiles.saveEdit(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_nWidth
int cc.ctrl.TrafCtrl.m_nWidth
Definition at line 54 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.preparePoints(), and cc.ctrl.TrafCtrl.writeBin().
m_oFullGeo
CtrlGeo cc.ctrl.TrafCtrl.m_oFullGeo = null
Definition at line 56 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ws.CtrlTiles.addControl(), cc.rsm.RsmCollect.RsmRecord.cleanup(), cc.ctrl.CreateCtrls.createCtrl(), cc.util.Geo.ctrlIntersectBounds(), cc.ctrl.proc.ProcCtrl.deleteControl(), cc.ws.GeoLanes.doPost(), cc.ws.WxPoly.doPost(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.proc.ProcCtrl.getStopLine(), cc.ctrl.RenderCtrl.main(), cc.rsm.RsmParser.parseRequest(), cc.ctrl.TrafCtrl.preparePoints(), cc.ctrl.proc.ProcClosed.proc(), cc.ctrl.proc.ProcClosing.proc(), cc.ctrl.proc.ProcDebug.proc(), cc.ctrl.proc.ProcDebugOutlines.proc(), cc.ctrl.proc.ProcDirection.proc(), cc.ctrl.proc.ProcLatPerm.proc(), cc.ctrl.proc.ProcMaxSpeed.proc(), cc.ctrl.proc.ProcOpening.proc(), cc.ctrl.proc.ProcPavement.proc(), cc.ctrl.proc.ProcSignal.proc(), cc.ctrl.proc.ProcStop.proc(), cc.ctrl.proc.ProcYield.proc(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ws.CtrlTiles.saveEdit(), cc.ws.CtrlTiles.splitLineArcs(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeIndex().
m_sDatum
String cc.ctrl.TrafCtrl.m_sDatum = "WGS84" package
Definition at line 48 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_sLabel
String cc.ctrl.TrafCtrl.m_sLabel
Definition at line 55 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ws.GeoLanes.doPost(), cc.ctrl.TrafCtrl.getXml(), cc.ws.CtrlTiles.saveEdit(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_sProj
String cc.ctrl.TrafCtrl.m_sProj = "epsg:3785" package
Definition at line 47 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_sVersion
String cc.ctrl.TrafCtrl.m_sVersion = "0.1" package
Definition at line 30 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_yControlValue
byte [] cc.ctrl.TrafCtrl.m_yControlValue
Definition at line 45 of file TrafCtrl.java.
Referenced by cc.ctrl.TrafCtrl.TrafCtrl(), cc.ws.GeoLanes.doPost(), cc.ws.WxPoly.doPost(), cc.ctrl.TrafCtrl.generateId(), cc.ihp.IHP.generateSpeedControls(), cc.ctrl.TrafCtrl.getXml(), cc.ctrl.proc.ProcClosed.renderTiledData(), cc.ws.CtrlTiles.saveEdit(), cc.ctrl.TrafCtrl.writeBin(), and cc.ctrl.TrafCtrl.writeJson().
m_yId
byte [] cc.ctrl.TrafCtrl.m_yId
Definition at line 31 of file TrafCtrl.java.
Referenced by cc.ctrl.proc.TdFeature.TdFeature(), cc.ctrl.TrafCtrl.TrafCtrl(), cc.ctrl.TrafCtrl.compareTo(), cc.ctrl.TrafCtrl.generateId(), cc.ctrl.proc.ProcCtrl.getCurrentControls(), cc.ctrl.TrafCtrl.getXml(), cc.ws.CtrlTiles.saveEdit(), cc.ws.CtrlTiles.splitLineArcs(), cc.ctrl.TrafCtrl.write(), cc.ctrl.TrafCtrl.writeBin(), cc.ctrl.TrafCtrl.writeIndex(), and cc.ctrl.TrafCtrl.writeJson().
The documentation for this class was generated from the following file:
src/cc/ctrl/TrafCtrl.java