Carma-cloud: cc.ctrl.proc.ProcPavement Class Reference
cc.ctrl.proc.ProcPavement Class Reference
Public Member Functions
ProcPavement (String sLineArcDir, String sLineArcBase, String sXodrDir)
void parseMetadata (Path oSource) throws Exception
ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
ProcCtrl (String sLineArcDir)
void parseMetadata (String sSource) throws Exception
abstract void parseMetadata (Path oSource) throws Exception
void process (String sLineArcsFile, double dTol) throws Exception
abstract ArrayList< CtrlLineArcs > combine (ArrayList< CtrlLineArcs > oLanes, double dTol)
Static Public Member Functions
static void renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
Static Public Member Functions inherited from cc.ctrl.proc.ProcCtrl
static void setStaticVariables (double dStep, String sDir, String sTdFF, int nZoom)
static void updateTiles (ArrayList< int[]> oTiles, ArrayList< int[]> oCtrlTiles)
static void updateTileRange (int[] nTileIndices, int[] nTmpTiles)
static ArrayList< CtrlLineArcs > combineLaneByRoad (ArrayList< CtrlLineArcs > oLineArcs, double dTol)
static void writeIndexFile (ArrayList< TrafCtrl > oCtrls, int nX, int nY) throws IOException
static void updateIndex (String sIndexFile, TrafCtrl oCtrl, long lTimestamp) throws IOException
static void renderCtrls (String sCtrlType, ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException
static boolean deleteControl (String sId) throws Exception
static boolean deleteControl (TrafCtrl oCtrl)
static ArrayList< TrafCtrl > getCurrentControls (int nCtrlType, double dMinLon, double dMinLat, double dMaxLon, double dMaxLat, boolean bLoadFullGeo)
Protected Member Functions
void proc (String sLineArcsFile, double dTol) throws Exception
abstract void proc (String sLineArcsFile, double dTol) throws Exception
Package Attributes
String m_sXodrDir
String m_sLineArcBase
Additional Inherited Members
Public Attributes inherited from cc.ctrl.proc.ProcCtrl
String m_sLineArcDir
Static Public Attributes inherited from cc.ctrl.proc.ProcCtrl
static final Object INDEXLOCK = new Object()
static double g_dExplodeStep
static String g_sTrafCtrlDir
static String g_sTdFileFormat
static String g_sGeolanesDir
static int g_nDefaultZoom = Integer.MIN_VALUE
static final byte CC = 0
static final byte RSM = 1
static final byte IHP2 = 2
Static Protected Member Functions inherited from cc.ctrl.proc.ProcCtrl
static boolean checkTileRange (int[] nTileIndices)
Static Protected Attributes inherited from cc.ctrl.proc.ProcCtrl
static final double WIDTHTH = 1.5
static final double LENLOWTH = 75.0
static final double STOPLINEENDOFFSET = 0.6
static final double STOPLINELATOFFSET = 0.1
static double[][] NUMBERS
static Comparator< int[]> LANETYPECOMP
static final HashMap< String, double[]> CHARS = new HashMap()
Static Package Functions inherited from cc.ctrl.proc.ProcCtrl
[static initializer]
static double getCoordAndHeadingAtLength (double[] dPoints, double dLength, boolean bReverse, double[] dPoint)
static int getStopLine (TrafCtrl oCtrl, ArrayList< double[]> oStops)
Detailed Description
Author
aaron.cherney
Definition at line 33 of file ProcPavement.java.
Constructor & Destructor Documentation
ProcPavement()
cc.ctrl.proc.ProcPavement.ProcPavement (String sLineArcDir, String sLineArcBase, String sXodrDir) inline
Definition at line 37 of file ProcPavement.java.
    {
        super(sLineArcDir);
        m_sXodrDir = sXodrDir;
        m_sLineArcBase = sLineArcBase;
    }
References cc.ctrl.proc.ProcPavement.m_sLineArcBase, and cc.ctrl.proc.ProcPavement.m_sXodrDir.
Member Function Documentation
combine()
ArrayList< CtrlLineArcs > cc.ctrl.proc.ProcPavement.combine (ArrayList< CtrlLineArcs > oLanes, double dTol) inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 54 of file ProcPavement.java.
    {
//      ArrayList<CtrlLineArcs> oLanesByRoads = ProcCtrl.combineLaneByRoad(oLanes, dTol);
//      return oLanesByRoads;
        return oLanes;
    }
Referenced by cc.ctrl.proc.ProcPavement.proc().
parseMetadata()
void cc.ctrl.proc.ProcPavement.parseMetadata (Path oSource) throws Exception inline
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 46 of file ProcPavement.java.
    {
        new XodrPvmtParser().parseXodrToCLA(oSource, m_sLineArcBase);
    }
References cc.ctrl.proc.ProcPavement.m_sLineArcBase, and cc.geosrv.xodr.pvmt.XodrPvmtParser.parseXodrToCLA().
Referenced by cc.ctrl.proc.ProcPavement.proc().
proc()
void cc.ctrl.proc.ProcPavement.proc (String sLineArcsFile, double dTol) throws Exception inline protected
Reimplemented from cc.ctrl.proc.ProcCtrl.
Definition at line 63 of file ProcPavement.java.
    {
        try
        {
            String sPvmtFile = m_sXodrDir + sLineArcsFile.substring(sLineArcsFile.lastIndexOf("/") + 1).replace(".bin", ".xodr.pvmt");
            parseMetadata(Paths.get(sPvmtFile));
            ArrayList<TrafCtrl> oCtrls = new ArrayList();
            ArrayList<CtrlLineArcs> oLineArcs = new ArrayList();
            try (DataInputStream oIn = new DataInputStream(new BufferedInputStream(FileUtil.newInputStream(Paths.get(sLineArcsFile + ".pvmt")))))
            {
                while (oIn.available() > 0)
                {
                    oLineArcs.add(new CtrlLineArcs(oIn));
                }
            }
            oLineArcs = combine(oLineArcs, dTol);
            ArrayList<int[]> oTiles = new ArrayList();
            for (CtrlLineArcs oCLA : oLineArcs)
            {
                TrafCtrl oCtrl = new TrafCtrl("pavement", oCLA.m_nLaneType, 0, oCLA.m_dLineArcs, "", true, CC);
                oCtrls.add(oCtrl);
                oCtrl.write(g_sTrafCtrlDir, g_dExplodeStep, g_nDefaultZoom, CC);
                updateTiles(oTiles, oCtrl.m_oFullGeo.m_oTiles);
            }
            renderTiledData(oCtrls, oTiles);
        }
        catch (Exception oEx)
        {
            oEx.printStackTrace();
        }
    }
References cc.ctrl.proc.ProcCtrl.CC, cc.ctrl.proc.ProcPavement.combine(), cc.ctrl.proc.ProcCtrl.g_dExplodeStep, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTrafCtrlDir, cc.ctrl.TrafCtrl.m_oFullGeo, cc.ctrl.CtrlGeo.m_oTiles, cc.ctrl.proc.ProcPavement.m_sXodrDir, cc.util.FileUtil.newInputStream(), cc.ctrl.proc.ProcPavement.parseMetadata(), cc.ctrl.proc.ProcPavement.renderTiledData(), cc.ctrl.proc.ProcCtrl.updateTiles(), and cc.ctrl.TrafCtrl.write().
renderTiledData()
static void cc.ctrl.proc.ProcPavement.renderTiledData (ArrayList< TrafCtrl > oCtrls, ArrayList< int[]> nTiles) throws IOException inline static
Definition at line 96 of file ProcPavement.java.
    {
        TdLayer oLayer = new TdLayer("pavement", new String[]{"type"}, new String[]{"d", "s"}, TdLayer.POLYGON);
        int nDriving = XodrUtil.getLaneType("driving");
        int[] nTags = new int[2];
        for (int[] nTile : nTiles)
        {
            int nX = nTile[0];
            int nY = nTile[1];
            Files.createDirectories(Paths.get(String.format(g_sTdFileFormat, nX, 0, 0, 0)).getParent(), FileUtil.DIRPERS);
            writeIndexFile(oCtrls, nX, nY);
            oLayer.clear();
            ArrayList<ArrayList<double[]>> oClippedLanes = new ArrayList();
            double[] dClipBounds = TileUtil.getClippingBounds(g_nDefaultZoom, nX, nY);
            double[][] dClips = new double[][]{Arrays.newDoubleArray(512), Arrays.newDoubleArray(512), Arrays.newDoubleArray(512)};
            oClippedLanes.add(new ArrayList());
            oClippedLanes.add(new ArrayList());
            oClippedLanes.add(new ArrayList());
            for (TrafCtrl oCtrl : oCtrls)
            {
                if (Collections.binarySearch(oCtrl.m_oFullGeo.m_oTiles, nTile, Mercator.TILECOMP) < 0)
                    continue;
                for (ArrayList oClipped : oClippedLanes)
                    oClipped.clear();
                TileUtil.clipCtrlGeoForTile(oCtrl.m_oFullGeo, dClips, dClipBounds, oClippedLanes);
                int nParts = oClippedLanes.get(0).size();
                for (int nPart = 0; nPart < nParts; nPart++)
                {
                    double[] dNT = oClippedLanes.get(1).get(nPart);
                    double[] dPT = oClippedLanes.get(2).get(nPart);
                    double[] dClippedPavement = Geo.createPolygon(dPT, dNT);
                    if (!Geo.isClockwise(dClippedPavement, 1))
                    {
                        dClippedPavement = Geo.reverseOrder(dClippedPavement);
                    }
                    nTags[1] = MathUtil.bytesToInt(oCtrl.m_yControlValue) == nDriving ? 0 : 1;
                    oLayer.add(new TdFeature(dClippedPavement, nTags, oCtrl));
                }
            }
            if (!oLayer.isEmpty())
            {
                try (DataOutputStream oOut = new DataOutputStream(new BufferedOutputStream(FileUtil.newOutputStream(Paths.get(String.format(g_sTdFileFormat, nX, g_nDefaultZoom, nX, nY)), FileUtil.APPENDTO, FileUtil.FILEPERS))))
                {
                    oLayer.write(oOut);
                }
            }
        }
    }
References cc.util.FileUtil.APPENDTO, cc.util.MathUtil.bytesToInt(), cc.util.TileUtil.clipCtrlGeoForTile(), cc.util.Geo.createPolygon(), cc.util.FileUtil.DIRPERS, cc.util.FileUtil.FILEPERS, cc.ctrl.proc.ProcCtrl.g_nDefaultZoom, cc.ctrl.proc.ProcCtrl.g_sTdFileFormat, cc.util.TileUtil.getClippingBounds(), cc.geosrv.xodr.XodrUtil.getLaneType(), cc.util.Geo.isClockwise(), cc.util.Arrays.newDoubleArray(), cc.util.FileUtil.newOutputStream(), cc.ctrl.proc.TdLayer.POLYGON, cc.util.Geo.reverseOrder(), cc.geosrv.Mercator.TILECOMP, cc.ctrl.proc.TdLayer.write(), and cc.ctrl.proc.ProcCtrl.writeIndexFile().
Referenced by cc.ctrl.proc.ProcPavement.proc(), and cc.ws.CtrlTiles.splitLineArcs().
Member Data Documentation
m_sLineArcBase
String cc.ctrl.proc.ProcPavement.m_sLineArcBase package
Definition at line 36 of file ProcPavement.java.
Referenced by cc.ctrl.proc.ProcPavement.ProcPavement(), and cc.ctrl.proc.ProcPavement.parseMetadata().
m_sXodrDir
String cc.ctrl.proc.ProcPavement.m_sXodrDir package
Definition at line 35 of file ProcPavement.java.
Referenced by cc.ctrl.proc.ProcPavement.ProcPavement(), and cc.ctrl.proc.ProcPavement.proc().
The documentation for this class was generated from the following file:
src/cc/ctrl/proc/ProcPavement.java