Carma-cloud: cc.geosrv.xodr.pvmt.LaneSection Class Reference
cc.geosrv.xodr.pvmt.LaneSection Class Reference
Public Member Functions
LaneSection ()
LaneSection (double dS, int nId)
void setInnerPaths ()
void add (Lane oLane)
void sortLanes ()
void getLanes (ArrayList< Lane > oLaneList)
void createPavement ()
void getShoulders (ArrayList< double[]> oShoulders)
Static Public Member Functions
static LaneSection getLaneSection (double dDist, ArrayList< LaneSection > oLaneSections)
Public Attributes
double m_dS
ArrayList< Lane > m_oLeft = new ArrayList()
ArrayList< Lane > m_oRight = new ArrayList()
Lane m_oCenter
int m_nId
LaneSection m_oPrevSect
double[] m_dEdgeEnds
double[] m_dPavement
ArrayList< double[]> m_oShoulders = new ArrayList()
Private Member Functions
void setInnerPaths (ArrayList< Lane > oLanes)
Static Private Attributes
static Comparator< Lane > LEFTLANES = (Lane o1, Lane o2) -> Integer.compare(o1.m_nLaneIndex, o2.m_nLaneIndex)
static Comparator< Lane > RIGHTLANES = (Lane o1, Lane o2) -> Integer.compare(o2.m_nLaneIndex, o1.m_nLaneIndex)
Detailed Description
Author
Federal Highway Administration
Definition at line 19 of file LaneSection.java.
Constructor & Destructor Documentation
LaneSection() [1/2]
cc.geosrv.xodr.pvmt.LaneSection.LaneSection () inline
Definition at line 33 of file LaneSection.java.
    {
    }
LaneSection() [2/2]
cc.geosrv.xodr.pvmt.LaneSection.LaneSection (double dS, int nId) inline
Definition at line 37 of file LaneSection.java.
    {
        m_dS = dS;
        m_nId = nId;
    }
References cc.geosrv.xodr.pvmt.LaneSection.m_dS, and cc.geosrv.xodr.pvmt.LaneSection.m_nId.
Member Function Documentation
add()
void cc.geosrv.xodr.pvmt.LaneSection.add (Lane oLane) inline
Definition at line 63 of file LaneSection.java.
    {
        if (oLane.m_nLaneIndex > 0)
            m_oLeft.add(oLane);
        else if (oLane.m_nLaneIndex < 0)
            m_oRight.add(oLane);
    }
References cc.geosrv.xodr.pvmt.Lane.m_nLaneIndex, cc.geosrv.xodr.pvmt.LaneSection.m_oLeft, and cc.geosrv.xodr.pvmt.LaneSection.m_oRight.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.endElement().
createPavement()
void cc.geosrv.xodr.pvmt.LaneSection.createPavement () inline
Definition at line 102 of file LaneSection.java.
    {
        ArrayList<Lane> oLanes = new ArrayList();
        getLanes(oLanes);
        Collections.sort(oLanes, LEFTLANES);
        int nDriving = XodrUtil.getLaneType("driving");
        double[] dEdgeR = null;
        for (int nIndex = 0; nIndex < oLanes.size(); nIndex++)
        {
            Lane oLane = oLanes.get(nIndex);
            if (oLane.m_nLaneType == nDriving)
            {
                dEdgeR = oLane.m_nLaneIndex < 0 ? oLane.m_dOuter : oLane.m_dInner;
                break;
            }
        }
        double[] dEdgeL = null;
        for (int nIndex = oLanes.size() - 1; nIndex >= 0; nIndex--)
        {
            Lane oLane = oLanes.get(nIndex);
            if (oLane.m_nLaneType == nDriving)
            {
                dEdgeL = oLane.m_nLaneIndex < 0 ? oLane.m_dInner : oLane.m_dOuter;
                break;
            }
        }
        if (dEdgeL == null || dEdgeR == null)
            return;
        double[] dPavementCenter = Arrays.newDoubleArray(Arrays.size(dEdgeL));
        dPavementCenter = Arrays.add(dPavementCenter, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
        int nLimit = Arrays.size(dEdgeR);
        m_dEdgeEnds = new double[]{dEdgeR[nLimit - 2], dEdgeR[nLimit - 1], dEdgeL[nLimit - 2], dEdgeL[nLimit - 1]};
        if (m_oPrevSect != null && m_oPrevSect.m_dEdgeEnds != null)
        {
            double dXr = m_oPrevSect.m_dEdgeEnds[0];
            double dYr = m_oPrevSect.m_dEdgeEnds[1];
            double dXl = m_oPrevSect.m_dEdgeEnds[2];
            double dYl = m_oPrevSect.m_dEdgeEnds[3];
            double dPathX = (dXr + dXl) / 2;
            double dPathY = (dYr + dYl) / 2;
            double dW = Geo.distance(dXr, dYr, dXl, dYl);
            dPavementCenter = Arrays.addAndUpdate(dPavementCenter, dPathX, dPathY);
            dPavementCenter = Arrays.add(dPavementCenter, dW);
        }
        for (int nIndex = 5; nIndex < nLimit; nIndex += 2)
        {
            double dXr = dEdgeR[nIndex];
            double dYr = dEdgeR[nIndex + 1];
            double dXl = dEdgeL[nIndex];
            double dYl = dEdgeL[nIndex + 1];
            double dPathX = (dXr + dXl) / 2;
            double dPathY = (dYr + dYl) / 2;
            double dW = Geo.distance(dXr, dYr, dXl, dYl);
            dPavementCenter = Arrays.addAndUpdate(dPavementCenter, dPathX, dPathY);
            dPavementCenter = Arrays.add(dPavementCenter, dW);
        }
        m_dPavement = dPavementCenter; // save local reference
    }
References cc.util.Arrays.add(), cc.util.Arrays.addAndUpdate(), cc.util.Geo.distance(), cc.geosrv.xodr.pvmt.LaneSection.getLanes(), cc.geosrv.xodr.XodrUtil.getLaneType(), cc.geosrv.xodr.pvmt.LaneSection.LEFTLANES, cc.geosrv.xodr.pvmt.LaneSection.m_dEdgeEnds, cc.geosrv.xodr.pvmt.Lane.m_dInner, cc.geosrv.xodr.pvmt.Lane.m_dOuter, cc.geosrv.xodr.pvmt.LaneSection.m_dPavement, cc.geosrv.xodr.pvmt.Lane.m_nLaneType, cc.geosrv.xodr.pvmt.LaneSection.m_oPrevSect, cc.util.Arrays.newDoubleArray(), and cc.util.Arrays.size().
Referenced by cc.geosrv.xodr.pvmt.Road.getPavementCtrlLineArcs().
getLanes()
void cc.geosrv.xodr.pvmt.LaneSection.getLanes (ArrayList< Lane > oLaneList) inline
Definition at line 93 of file LaneSection.java.
    {
        oLaneList.clear();
        oLaneList.add(m_oCenter);
        oLaneList.addAll(m_oLeft);
        oLaneList.addAll(m_oRight);
    }
References cc.geosrv.xodr.pvmt.LaneSection.m_oCenter, cc.geosrv.xodr.pvmt.LaneSection.m_oLeft, and cc.geosrv.xodr.pvmt.LaneSection.m_oRight.
Referenced by cc.geosrv.xodr.pvmt.LaneSection.createPavement(), and cc.geosrv.xodr.pvmt.LaneSection.getShoulders().
getLaneSection()
static LaneSection cc.geosrv.xodr.pvmt.LaneSection.getLaneSection (double dDist, ArrayList< LaneSection > oLaneSections) inline static
Definition at line 79 of file LaneSection.java.
    {
        int nIndex = oLaneSections.size();
        while (nIndex-- > 0)
        {
            LaneSection oTemp = oLaneSections.get(nIndex);
            if (dDist >= oTemp.m_dS)
                return oTemp;
        }
        return oLaneSections.get(0);
    }
References cc.geosrv.xodr.pvmt.LaneSection.m_dS.
getShoulders()
void cc.geosrv.xodr.pvmt.LaneSection.getShoulders (ArrayList< double[]> oShoulders) inline
Definition at line 167 of file LaneSection.java.
    {
        ArrayList<Lane> oLanes = new ArrayList();
        getLanes(oLanes);
        int nShoulder = XodrUtil.getLaneType(("shoulder"));
        for (Lane oLane : oLanes)
        {
            if (oLane.m_nLaneType == nShoulder)
            {
                double[] dEdgeR = oLane.m_dOuter;
                double[] dEdgeL = oLane.m_dInner;
                double[] dPavementCenter = Arrays.newDoubleArray(Arrays.size(dEdgeL));
                dPavementCenter = Arrays.add(dPavementCenter, new double[] {Double.MAX_VALUE, Double.MAX_VALUE, -Double.MAX_VALUE, -Double.MAX_VALUE});
                int nLimit = Arrays.size(dEdgeR);
                for (int nIndex = 5; nIndex < nLimit; nIndex += 2)
                {
                    double dXr = dEdgeR[nIndex];
                    double dYr = dEdgeR[nIndex + 1];
                    double dXl = dEdgeL[nIndex];
                    double dYl = dEdgeL[nIndex + 1];
                    double dPathX = (dXr + dXl) / 2;
                    double dPathY = (dYr + dYl) / 2;
                    double dW = Geo.distance(dXr, dYr, dXl, dYl);
                    dPavementCenter = Arrays.addAndUpdate(dPavementCenter, dPathX, dPathY);
                    dPavementCenter = Arrays.add(dPavementCenter, dW);
                }
                oShoulders.add(dPavementCenter);
            }
        }
    }
References cc.util.Arrays.add(), cc.util.Arrays.addAndUpdate(), cc.util.Geo.distance(), cc.geosrv.xodr.pvmt.LaneSection.getLanes(), cc.geosrv.xodr.XodrUtil.getLaneType(), cc.util.Arrays.newDoubleArray(), and cc.util.Arrays.size().
Referenced by cc.geosrv.xodr.pvmt.Road.getShoulderCtrlLineArcs().
setInnerPaths() [1/2]
void cc.geosrv.xodr.pvmt.LaneSection.setInnerPaths () inline
Definition at line 44 of file LaneSection.java.
    {
        setInnerPaths(m_oLeft);
        setInnerPaths(m_oRight);
    }
References cc.geosrv.xodr.pvmt.LaneSection.m_oLeft, cc.geosrv.xodr.pvmt.LaneSection.m_oRight, and cc.geosrv.xodr.pvmt.LaneSection.setInnerPaths().
Referenced by cc.geosrv.xodr.pvmt.LaneSection.setInnerPaths().
setInnerPaths() [2/2]
void cc.geosrv.xodr.pvmt.LaneSection.setInnerPaths (ArrayList< Lane > oLanes) inline private
Definition at line 51 of file LaneSection.java.
    {
        int nSize = oLanes.size();
        if (nSize > 0)
        {
            oLanes.get(0).m_dInner = m_oCenter.m_dOuter;
            for (int i = 1; i < nSize; i++)
                oLanes.get(i).m_dInner = oLanes.get(i - 1).m_dOuter;
        }
    }
References cc.geosrv.xodr.pvmt.Lane.m_dOuter, and cc.geosrv.xodr.pvmt.LaneSection.m_oCenter.
sortLanes()
void cc.geosrv.xodr.pvmt.LaneSection.sortLanes () inline
Definition at line 72 of file LaneSection.java.
    {
        Collections.sort(m_oLeft, LEFTLANES);
        Collections.sort(m_oRight, RIGHTLANES);
    }
References cc.geosrv.xodr.pvmt.LaneSection.LEFTLANES, cc.geosrv.xodr.pvmt.LaneSection.m_oLeft, cc.geosrv.xodr.pvmt.LaneSection.m_oRight, and cc.geosrv.xodr.pvmt.LaneSection.RIGHTLANES.
Referenced by cc.geosrv.xodr.pvmt.XodrPvmtParser.endElement().
Member Data Documentation
LEFTLANES
Comparator<Lane> cc.geosrv.xodr.pvmt.LaneSection.LEFTLANES = (Lane o1, Lane o2) -> Integer.compare(o1.m_nLaneIndex, o2.m_nLaneIndex) static private
Definition at line 25 of file LaneSection.java.
Referenced by cc.geosrv.xodr.pvmt.LaneSection.createPavement(), and cc.geosrv.xodr.pvmt.LaneSection.sortLanes().
m_dEdgeEnds
double [] cc.geosrv.xodr.pvmt.LaneSection.m_dEdgeEnds
Definition at line 29 of file LaneSection.java.
Referenced by cc.geosrv.xodr.pvmt.LaneSection.createPavement().
m_dPavement
double [] cc.geosrv.xodr.pvmt.LaneSection.m_dPavement
Definition at line 30 of file LaneSection.java.
Referenced by cc.geosrv.xodr.pvmt.LaneSection.createPavement(), and cc.geosrv.xodr.pvmt.Road.getPavementCtrlLineArcs().
m_dS
double cc.geosrv.xodr.pvmt.LaneSection.m_dS
Definition at line 21 of file LaneSection.java.
Referenced by cc.geosrv.xodr.pvmt.LaneSection.LaneSection(), cc.geosrv.xodr.pvmt.Geometry.addLanePoints(), cc.geosrv.xodr.pvmt.Arc.addLanePoints(), cc.geosrv.xodr.pvmt.Arc.addPoints(), cc.geosrv.xodr.pvmt.Line.addPoints(), cc.geosrv.xodr.pvmt.LaneSection.getLaneSection(), and cc.geosrv.xodr.pvmt.Road.getLaneSections().
m_nId
int cc.geosrv.xodr.pvmt.LaneSection.m_nId
Definition at line 27 of file LaneSection.java.
Referenced by cc.geosrv.xodr.pvmt.LaneSection.LaneSection(), cc.geosrv.xodr.pvmt.Road.getPavementCtrlLineArcs(), and cc.geosrv.xodr.pvmt.Road.getShoulderCtrlLineArcs().
m_oCenter
Lane cc.geosrv.xodr.pvmt.LaneSection.m_oCenter
Definition at line 24 of file LaneSection.java.
Referenced by cc.geosrv.xodr.pvmt.Geometry.addLanePoints(), cc.geosrv.xodr.pvmt.Arc.addLanePoints(), cc.geosrv.xodr.pvmt.LaneSection.getLanes(), and cc.geosrv.xodr.pvmt.LaneSection.setInnerPaths().
m_oLeft
ArrayList<Lane> cc.geosrv.xodr.pvmt.LaneSection.m_oLeft = new ArrayList()
Definition at line 22 of file LaneSection.java.
Referenced by cc.geosrv.xodr.pvmt.LaneSection.add(), cc.geosrv.xodr.pvmt.Geometry.addLanePoints(), cc.geosrv.xodr.pvmt.Arc.addLanePoints(), cc.geosrv.xodr.pvmt.LaneSection.getLanes(), cc.geosrv.xodr.pvmt.LaneSection.setInnerPaths(), and cc.geosrv.xodr.pvmt.LaneSection.sortLanes().
m_oPrevSect
LaneSection cc.geosrv.xodr.pvmt.LaneSection.m_oPrevSect
Definition at line 28 of file LaneSection.java.
Referenced by cc.geosrv.xodr.pvmt.LaneSection.createPavement().
m_oRight
ArrayList<Lane> cc.geosrv.xodr.pvmt.LaneSection.m_oRight = new ArrayList()
Definition at line 23 of file LaneSection.java.
Referenced by cc.geosrv.xodr.pvmt.LaneSection.add(), cc.geosrv.xodr.pvmt.Geometry.addLanePoints(), cc.geosrv.xodr.pvmt.Arc.addLanePoints(), cc.geosrv.xodr.pvmt.LaneSection.getLanes(), cc.geosrv.xodr.pvmt.LaneSection.setInnerPaths(), and cc.geosrv.xodr.pvmt.LaneSection.sortLanes().
m_oShoulders
ArrayList<double[]> cc.geosrv.xodr.pvmt.LaneSection.m_oShoulders = new ArrayList()
Definition at line 31 of file LaneSection.java.
RIGHTLANES
Comparator<Lane> cc.geosrv.xodr.pvmt.LaneSection.RIGHTLANES = (Lane o1, Lane o2) -> Integer.compare(o2.m_nLaneIndex, o1.m_nLaneIndex) static private
Definition at line 26 of file LaneSection.java.
Referenced by cc.geosrv.xodr.pvmt.LaneSection.sortLanes().
The documentation for this class was generated from the following file:
src/cc/geosrv/xodr/pvmt/LaneSection.java