Carma-cloud: cc.vector_tile.VectorTile.Tile.GeomType Enum Reference
cc.vector_tile.VectorTile.Tile.GeomType Enum Reference
Classes
class GeomTypeVerifier
Public Member Functions
final int getNumber ()
Static Public Member Functions
static GeomType valueOf (int value)
static GeomType forNumber (int value)
static com.google.protobuf.Internal.EnumLiteMap< GeomType > internalGetValueMap ()
static com.google.protobuf.Internal.EnumVerifier internalGetVerifier ()
Public Attributes
UNKNOWN =(0)
POINT =(1)
LINESTRING =(2)
POLYGON =(3)
Static Public Attributes
static final int UNKNOWN_VALUE = 0
static final int POINT_VALUE = 1
static final int LINESTRING_VALUE = 2
static final int POLYGON_VALUE = 3
Private Member Functions
GeomType (int value)
Private Attributes
final int value
Static Private Attributes
static final com.google.protobuf.Internal.EnumLiteMap< GeomType > internalValueMap
Detailed Description
GeomType is described in section 4.3.4 of the specification
Protobuf enum vector_tile.Tile.GeomType
Definition at line 49 of file VectorTile.java.
Constructor & Destructor Documentation
GeomType()
cc.vector_tile.VectorTile.Tile.GeomType.GeomType (int value) inline private
Definition at line 139 of file VectorTile.java.
{
        this.value = value;
      }
Referenced by cc.vector_tile.VectorTile.Tile.Feature.getType().
Member Function Documentation
forNumber()
static GeomType cc.vector_tile.VectorTile.Tile.GeomType.forNumber (int value) inline static
Definition at line 100 of file VectorTile.java.
{
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return POINT;
          case 2: return LINESTRING;
          case 3: return POLYGON;
          default: return null;
        }
      }
Referenced by cc.vector_tile.VectorTile.Tile.GeomType.GeomTypeVerifier.isInRange().
getNumber()
final int cc.vector_tile.VectorTile.Tile.GeomType.getNumber () inline
Definition at line 88 of file VectorTile.java.
{
        return value;
      }
internalGetValueMap()
static com.google.protobuf.Internal.EnumLiteMap< GeomType > cc.vector_tile.VectorTile.Tile.GeomType.internalGetValueMap () inline static
Definition at line 111 of file VectorTile.java.
{
        return internalValueMap;
      }
internalGetVerifier()
static com.google.protobuf.Internal.EnumVerifier cc.vector_tile.VectorTile.Tile.GeomType.internalGetVerifier () inline static
Definition at line 124 of file VectorTile.java.
{
        return GeomTypeVerifier.INSTANCE;
      }
References cc.vector_tile.VectorTile.Tile.GeomType.GeomTypeVerifier.INSTANCE.
valueOf()
static GeomType cc.vector_tile.VectorTile.Tile.GeomType.valueOf (int value) inline static
Deprecated:
Use forNumber(int) instead.
Definition at line 96 of file VectorTile.java.
{
        return forNumber(value);
      }
Member Data Documentation
internalValueMap
final com.google.protobuf.Internal.EnumLiteMap< GeomType> cc.vector_tile.VectorTile.Tile.GeomType.internalValueMap static private
Initial value:
=
            new com.google.protobuf.Internal.EnumLiteMap<GeomType>() {
              @java.lang.Override
              public GeomType findValueByNumber(int number) {
                return GeomType.forNumber(number);
              }
            }
Definition at line 121 of file VectorTile.java.
LINESTRING
cc.vector_tile.VectorTile.Tile.GeomType.LINESTRING =(2)
LINESTRING = 2;
Definition at line 62 of file VectorTile.java.
Referenced by cc.ws.CtrlTiles.doGet(), cc.ws.TrackTiles.doGet(), and cc.ws.ValidateXodrTiles.doGet().
LINESTRING_VALUE
final int cc.vector_tile.VectorTile.Tile.GeomType.LINESTRING_VALUE = 2 static
LINESTRING = 2;
Definition at line 80 of file VectorTile.java.
POINT
cc.vector_tile.VectorTile.Tile.GeomType.POINT =(1)
POINT = 1;
Definition at line 58 of file VectorTile.java.
Referenced by cc.ws.CtrlTiles.doGet(), cc.ws.TrackTiles.doGet(), and cc.ws.ValidateXodrTiles.doGet().
POINT_VALUE
final int cc.vector_tile.VectorTile.Tile.GeomType.POINT_VALUE = 1 static
POINT = 1;
Definition at line 76 of file VectorTile.java.
POLYGON
cc.vector_tile.VectorTile.Tile.GeomType.POLYGON =(3)
POLYGON = 3;
Definition at line 66 of file VectorTile.java.
Referenced by cc.ws.CtrlTiles.doGet(), and cc.ws.ValidateXodrTiles.doGet().
POLYGON_VALUE
final int cc.vector_tile.VectorTile.Tile.GeomType.POLYGON_VALUE = 3 static
POLYGON = 3;
Definition at line 84 of file VectorTile.java.
UNKNOWN
cc.vector_tile.VectorTile.Tile.GeomType.UNKNOWN =(0)
UNKNOWN = 0;
Definition at line 54 of file VectorTile.java.
Referenced by cc.ws.CtrlTiles.doGet(), and cc.ws.ValidateXodrTiles.doGet().
UNKNOWN_VALUE
final int cc.vector_tile.VectorTile.Tile.GeomType.UNKNOWN_VALUE = 0 static
UNKNOWN = 0;
Definition at line 72 of file VectorTile.java.
value
final int cc.vector_tile.VectorTile.Tile.GeomType.value private
Definition at line 137 of file VectorTile.java.
The documentation for this enum was generated from the following file:
src/cc/vector_tile/VectorTile.java